### ISSUE TITLE
Sounds not playing on map

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#1]
As of a Gmod update around March, sounds have stopped playing on our map and this is due to some change with the MAX_CHANNELS. This stops ambient and door sounds from playing and ruins the atmosphere of the map.

I posted a thread here:
http://facepunch.com/showthread.php?t=1255376

It contains near enough everything you need to know including a video. I would appreciate it if this could be looked into because we spent some time on the map and it would be great to have it working as it should again.

**Comment by JohnOakman** [comment]
It's a big up but the problem is still here: https://facepunch.com/showthread.php?t=1511479&p=50919703

**Comment by kem008** [comment]
I had the same problem with the name of sound if it isnt direct use this `Sound("name")`

**Comment by bruhhhandaluzxyt** [comment]
The first issue, damn.
