### ISSUE TITLE
Aborting HTTP request because we received a response with a content-length over 64M and we are not streaming

### ISSUE THREAD

**Issue by Khubajsn** [Facepunch/garrysmod-issues#1011]
I think this bug is present ever since Garry's Mod got +host_workshop_collection. I'm  aware it's not a Garry's Mod specific feature, but still, is there a way you could fix the problem where >64MB addons refuse to download?

```
Mounting Addon 'RP City45 2013' (118759412)
Downloading...
Aborting HTTP request because we received a response with a content-length over 64M and we are not streamingDownload Failed!
```

**Comment by azarus** [comment]
I have the same issue. Please remove this restriction or give us a command line option to download the addons even if its larger than 64 megabytes.

**Comment by Tenrys** [comment]
Any update on this?

**Comment by azarus** [comment]
Setup your own fastdl server and upload the large assets there. If its
server side then you have to upload the assets to the server yourself.

**Comment by robotboy655** [comment]
We just updated to latest Steamworks API, so I will try looking into fixing this again.

**Comment by X-Coder** [comment]
Any news on this?

**Comment by azarus** [comment]
Pre-download the assets and upload them to your game server, setup your own
webserver and fastdownload.

**Comment by X-Coder** [comment]
That's a workaround, not a solution. I need a fully automated solution updating my gameserver whenever workshop content gets updated - the current solution works fine until the 64MB limit is reached. The client side is not affected, only the server side.

**Comment by neico** [comment]
might be related to https://github.com/Facepunch/garrysmod-requests/issues/404

**Comment by azarus** [comment]
You can find the download link and download the addons using the steam web
api. So you can make an automated "workaround" :)

**Comment by robotboy655** [comment]
Sound be solved on Dev branch.

**Comment by uRandomAlex** [comment]
what a f_cking fast fix

**Comment by robotboy655** [comment]
You are welcome.

**Comment by azarus** [comment]
Just curious, why did it take so long? :D

**Comment by Jvs34** [comment]
He only had to switch the entire workshop api to use a newer one by valve that had problems of its own, and then wait for valve to slowly fix its shit so he could finally finish what he had to do.

Simple things really.

**Comment by azarus** [comment]
I just asked because i did not know what caused this issue. And was wondering why it took so long. 
Anyways it's nice that i can drop my download script soon :) Thanks for the update, thought it never going to be fixed.
