### ISSUE TITLE
Entity.SetEyeTarget has no effect on SENTs

### ISSUE THREAD

**Issue by disseminate** [Facepunch/garrysmod-issues#1013]
Not sure if it's just on SENTs or on other entities, but calling it has no effect. Understandably, doesn't work on entities with animated faces (players, NPCs, etc).

Still works fine on ragdolls (see: eye poser) but this bug has been around for over two years now.

**Comment by Noiwex** [comment]
Same here.

**Comment by Noiwex** [comment]
nigger

**Comment by robotboy655** [comment]
Fixed in Dev.

**Comment by Noiwex** [comment]
it was 2 years

**Comment by DrVrej** [comment]
Holy Jesus, after two years! Well I am glad it finally got fixed though, good job Rubat boi
