### ISSUE TITLE
Mouse missing in menu

### ISSUE THREAD

**Issue by JynxedJ0K3R** [Facepunch/garrysmod-issues#1020]
I'm pretty much new to the wonderful world of computer gaming. I've downloaded Garry's mod, and it opens up perfectly, however when it gets to the starting Menu, my cursor is missing. I can't tell if I'm hovering over anything. I've been told by a few others saying that there's probably something wrong with the game itself. Now, when I'm in another game say... TF2, I can see when I'm hovering over something. 
I'm not sure if this issue has been resolved or not, but any help? Answers?
I've already tried uninstalling and reinstalling it, so far no luck.
Much thanks!

**Comment by NeatNit** [comment]
Is this considered not a bug? Just recently discovered this. I have to have mouse trails fake-on (via registry value -1) because f.lux doesn't affect the cursor without it.

I just tested and acknowledge that this was a problem in HL2 as well, and probably every other Source game to date, but if Valve won't fix it, can't you?

**Comment by robotboy655** [comment]
Why would I waste my time fixing something that only 0.001% of people are affected by enabling completely useless and ridiculous Windows "feature"?

**Comment by NeatNit** [comment]
Alright, fair enough. I'll just use the software cursor cvar mentioned above. By the way I think it does have a purpose - for old&shitty LCD screens with horrendously slow response time, enabling trails gives the monitor that necessary extra time to make the cursor visible at all while in motion. Probably affects 0 people in 2015, but at some point it DID have a purpose.
