### ISSUE TITLE
Scripted sequences do not raise GM:EntityEmitSound

### ISSUE THREAD

**Issue by Kogitsune** [Facepunch/garrysmod-issues#1021]
Sounds emitted during scripted sequences don't raise EntityEmitSound.

```
hook.Add( "EntityEmitSound", "1", function( data ) print( data.SoundName ) end )
```

You can run this shared - only sounds emitted on the client raise EntityEmitSound, but that makes sense. Play on a map that uses them - d1_trainstation_xx have sequences near the spawns.

**Comment by NathanX-S** [comment]
Any updates?

**Comment by robotboy655** [comment]
I am going to assume this was about https://github.com/Facepunch/garrysmod-requests/issues/2005 or was fixed since.
