### ISSUE TITLE
Random Crashes on specific game mode - zombie survival

### ISSUE THREAD

**Issue by Anzeis** [Facepunch/garrysmod-issues#1037]
Greetings, 
over the past few weeks my Garry's mod has been crashing in the game mode "zombie survival", made by William "Jetboom" Moodhe.
I browsed his website and forums looking for a solution but nothing have worked so far.

It only happens in this game mode and it acts in a really odd way:
-it may crash up to over 30 times a day, and sometimes it doesn't crash at all for a 2-3 days straight.
-it may crash when I'm walking through props (less than 5) and sometimes it doesn't crash even though I walk through more than 10 props.
-it may crash upon creating a server or joining one, or it may crash after 10-20 minutes.

Some of the solutions I've found on the internet: 
Get a new computer (not viable)
Increase the VRAM of your computer (not viable)
Set the game to the lowest graphic settings (done) - Keeps crashing.
Close everything else but the game (done) - Keeps crashing.
Disable all the addons (done) - Keeps crashing.
Disable multicore rendering (done) - Keeps crashing.
Disabling 'Post processing" (done) - Keeps crashing.
Verify integrity of game cache (done) - Keeps crashing.
Reinstalling the game (done) - Keeps crashing.
Run it as administrator (done) - Keeps crashing.
Changing the 'Playback' audio settings to '16 bit, 48000 Hz (DVD Quality).' (done) - Keeps crashing.
Turning off the UAC and restarting. (done) - Keeps crashing.

The download links are the files created after every crash, all of them are from the same server, I had to deleted the other 300 I had, so I only have these ones right now but I have the same problem on every server.

https://www.dropbox.com/s/zt3pli3bld9obfn/hl2_140419_crash_2014_4_21T18_37_50C0.mdmp
https://www.dropbox.com/s/fqtm4ijlk03496x/hl2_140419_crash_2014_4_21T17_59_18C0.mdmp
https://www.dropbox.com/s/fz2ury4ohbeghuv/hl2_140419_crash_2014_4_21T17_51_6C0.mdmp
https://www.dropbox.com/s/bwqerreegdhhk8e/hl2_140419_crash_2014_4_21T17_10_18C0.mdmp

Or in case you don't want to download them:
## Dump Summary

Dump File:   hl2_140122_crash_2014_4_1T4_41_10C0.mdmp : C:\Users\stefano\Desktop\Inst\Steam\SteamApps\comm on\GarrysMod\hl2_140122_crash_2014_4_1T4_41_10C0.m dmp
Last Write Time:   31/03/2014 10:41:13 p.m.
Process Name:   hl2.exe : C:\Users\stefano\Desktop\Inst\Steam\steamapps\comm on\GarrysMod\hl2.exe
Process Architecture:   x86
Exception Code:   0xC0000005
Exception Information:   The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:   Not Present

I'm running Windows Vista SP 2
3062MB RAM
Processor: Intel(R) Core(TM)2 Duo CPU E7300 @ 2.66GHz (2 CPU), ~2.7GHz
DirectX 11 Installed. 
Running Gmod on DirectX 9.5

**Comment by robotboy655** [comment]
Closing as stale.
