### ISSUE TITLE
Folders don't exist in the Lua VFS in the client.

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-issues#1038]
Test addon: [Link](http://lexi.org.uk/!/luavfstestaddon.zip)
Code:

``` lua
AddCSLuaFile()
MsgN("Hello from the ", SERVER and "server" or "client", "!");
MsgN("I am testaddonfolder/test.lua and I ", file.Exists("testaddonfolder/test.lua", "LUA") and "exist" or "don't exist", "!");
MsgN("I am in testaddonfolder/ which ", file.Exists("testaddonfolder", "LUA") and "exists" or "doesn't exist", "!");
```

Output:

```
Hello from the server!
I am testaddonfolder/test.lua and I exist!
I am in testaddonfolder/ which exists!
. . .
Hello from the client!
I am testaddonfolder/test.lua and I exist!
I am in testaddonfolder/ which doesn't exist!
```

**Comment by PrikolMen** [comment]
One more reason to hate Rubat.
When will they kick that lazy ass out of Facepunch already?

**Comment by PrikolMen** [comment]
Ten goddamn years wasn't enough time to fix a little bug.

**Comment by X0lik** [comment]
lol

**Comment by X0lik** [comment]
> Ten goddamn years wasn't enough time to fix a little bug.

https://wiki.facepunch.com/gmod/file.Exists in example is workaround to issue

**Comment by PrikolMen** [comment]
> > Ten goddamn years wasn't enough time to fix a little bug.
> 
> https://wiki.facepunch.com/gmod/file.Exists in example is workaround to issue

Have you thought of giving an even more convenient solution, maybe use an external binary module to handle the file system, why not lol. It's cool when you have to write an extra function with two loops to simply check the file for existence.

What's next? Will `ents.GetAll()` break and we'll go through `Entity( index )` in while?
A brilliantly stupid solution to the simplest problem.

**Comment by Lexicality** [comment]
So ... Does posting like a dumbass get your stuff addressed then? Because I've still got a couple of issues and PRs open against gmod that I wouldn't mind seeing solved 🙃

**Comment by PrikolMen** [comment]
> Should be fixed on `dev` beta.

MY GOD, If this is really fixed it will be great!

**Comment by PrikolMen** [comment]
Not fully fixed https://github.com/Facepunch/garrysmod-issues/issues/5561
