### ISSUE TITLE
Remove the stupid lua file limit

### ISSUE THREAD

**Issue by arduinium** [Facepunch/garrysmod-issues#1058]
I know 2 ways to bypass this limit:

1) merge lua files together (stupid)
2) move lua files from addons folder to garrysmod/lua folder (stupid)

So please do us a favor and just remove the limit.

Also, I have less than 1500 lua files in my whole garrysmod folder (less than 1000 in the addons folder), yet I already hit the limit...

**Comment by Reaper3** [comment]
Hello! I have also found this problem.
I was wondering how progress is coming along with a fix, if there has been any at all that is.

**Comment by immibis** [comment]
Are some people seriously arguing that there *should* be a limit of 2048 Lua files?!

**Comment by robotboy655** [comment]
The limit is 8096, Mr. slowpoke.

**Comment by Divran** [comment]
But that's still less than infinity, so his point still stands

**Comment by robotboy655** [comment]
It is not possible to remove the limit completely, besides you'll have to try hard to hit the limit.

**Comment by arduinium** [comment]
I'm happy with the current limit... for now ;)

**Comment by oldmud0** [comment]
Sorry, I have 2147483647 lua files here right with me. Should I be using the c preprocessor for this? :wink:
