### ISSUE TITLE
Hook OnLuaError available in all realms

### ISSUE THREAD

**Issue by DerekSM** [Facepunch/garrysmod-issues#1069]
There is an OnLuaError hook, but it's currently only available in the menu realm, at least according to my tests; https://github.com/garrynewman/garrysmod/blob/ff51a59d5a821dec3c8f524631c86150b3e4744d/garrysmod/lua/menu/errors.lua#L11

This hook should be available on all realms.

**Comment by Exho1** [comment]
Open this back up! I need this hook

**Comment by Bo98** [comment]
See Facepunch/garrysmod-issues#149
