### ISSUE TITLE
Custom activity number not assigned (-1) to sequence on client

### ISSUE THREAD

**Issue by Varen** [Facepunch/garrysmod-issues#1085]
Any animated model which has activities not in the standard enum list, on client, will not load that Activity. 

Example: child.mdl, with the "nosepicking" sequence 5, activity ACT_PICKNOSE, which in this example will load as activity 2500 (Random number).

If I start a singleplayer game or a listen server, on host, GetSequenceActivity(5) will return 2500. Attempting to play the Activity 2500 in singleplayer will succeed.
On a client connecting, it will return -1. The activity cannot be played. 
However, if the client had already loaded the model in singleplayer in that session, it will load correctly.
Link to thread on FP where I asked for help against the issue:
http://facepunch.com/showthread.php?t=1387227
In said link, I use modified Age of Chivalry playermodels and animations. The issue is present also in completely custom models, with or without valve skeletons, as long as the activity is not in the ACT_\* enums included in the wiki.

**Comment by Kefta** [comment]
Would be fixed by https://github.com/Facepunch/garrysmod-requests/issues/950

**Comment by LPDaVinci** [comment]
Idk why this -1 thing appears on the

https://steamcommunity.com/workshop/filedetails/?id=848978803

addons.

before the april 2018 update it shows up the numbers for server and client. now its for clients on a server -1

**Comment by copperwarrior** [comment]
Running into this issue when using custom weapon hold types with custom playermodel animations. Is there a workaround for this yet that doesn't involve overwriting already created enums?

**Comment by robotboy655** [comment]
Fixed in https://github.com/Facepunch/garrysmod-issues/issues/5759 but keep in mind that the custom activity IDs  **will not be synched between client and server**, so you cannot use them in shared contexts.
