### ISSUE TITLE
"PlayerCanHearPlayersVoice " using too many of these hooks

### ISSUE THREAD

**Issue by ZeroServer** [Facepunch/garrysmod-issues#1087]
using too many of these hooks can cause server lag as PlayerCanHearPlayersVoice are very intensive.

even if no one use voice, there is a lag if there are many players on the server?

Fix please. :)

**Comment by robotboy655** [comment]
Reduced the update rate of the hook to every 5 seconds (to make sure servers have a chance to adjust the voice chat mask in between players talking) when nobody is speaking. Not much I can see that can be done about this hook besides completely removing it and in favor of forcing servers to manually set the bitmask for each player.

**Comment by meepen** [comment]
Five seconds may be a bit much, is there a possibility of adding invalidate
cache or update cache functions?

**Comment by robotboy655** [comment]
Is there a particular concern? Making the delay lower would be defeating the purpose of reducing it in the first place but maybe 2 seconds would be appropriate if there are some cases where 5 seconds is too much.

I wanna see how it goes on x86-64 servers next week and go from there.

**Comment by meepen** [comment]
Well I mean five seconds would be fine but for modes like ttt where
information is key, and someone dies at the beginning of the duration they
can talk for an extra five seconds after death.

I think having invalidate cache function would be the most optimal solution
as we could invalidate it based on events rather than tick updates.

**Comment by thegrb93** [comment]
100ms update rate would be a lot better. I think meepen's idea is ideal but requires addon updates

**Comment by meepen** [comment]
That would only be every 4 to 12 ticks so longer wouldn't hurt it too much
to be honest

**Comment by thegrb93** [comment]
This shouldn't have been done in the first place. Addons should do their own rate limiting.

**Comment by thegrb93** [comment]
Just realized this is called n(n-1) times per tick. I guess the update delay is warrented

**Comment by robotboy655** [comment]
The original update rate is 300ms. This is the rate that is used when somebody is talking, that has not changed.
