### ISSUE TITLE
Bug in "game_ui" entity upon player death

### ISSUE THREAD

**Issue by Matt2468rv** [Facepunch/garrysmod-issues#1092]
There is a bug in the game_ui entity.

In multiplayer, when the player is killed while he is using a game_ui entity, it doesn't remove the player from controlling the game_ui and doesn't allow the player to properly spectate and let others use the game_ui.  The spectating camera is stuck in place and the dead player is still in control of the game_ui.  Also when tested on a dedicated server, a red error continuously spams in the console upon the player's death: "mod_studio: MOVETYPE_FOLLOW with no model."

A mapping workaround to let other players use the game_ui when a player dies is to implement a trigger volume to check if the player controlling it is still there and alive, and if not, deactivate the game_ui.  However, this does not solve the problem of the spectating camera being stuck in place and a red error spamming uncontrollably in the console, and is merely a workaround, not a fix.

This is a very hindering issue for those who wish to use the game_ui entity in multiplayer maps.

**Comment by Matt2468rv** [comment]
Any chance this will be fixed?? I'd really love to use the "game_ui" entity for my map!

**Comment by robotboy655** [comment]
Can you make a test map for me to test this, or give me map name that already use the entity?

**Comment by robotboy655** [comment]
Nevermind, I think I got it.

**Comment by Matt2468rv** [comment]
Great, thanks for looking into this!
