### ISSUE TITLE
Bugbait & SMG Glitches

### ISSUE THREAD

**Issue by LordCasco** [Facepunch/garrysmod-issues#1112]
In Garry's mod if you have the bugbait in your hands, and you try to move, it doesn't have moving (Idle & Walking) animations and in third person shows up the world model animation is stand animation (idle_all_01) and if you throw it in third person you see is messed up (It throws it from the stomach).
SMG Part: -fixed-

**Comment by robotboy655** [comment]
The model is fixed, the view model bobbing when walking or 3rd person animations are not, it is a part of another issue that will need taking care of first.
