### ISSUE TITLE
Disable certain warnings

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#1134]
```
ngEyeAngles[0]', clamping.
DataTable warning: player: Out-of-range value (359.459290) in SendPropFloat 'm_angEyeAngles[0]', clamping.
DataTable warning: player: Out-of-range value (359.890839) in SendPropFloat 'm_angEyeAngles[0]', clamping.
DataTable warning: player: Out-of-range value (359.890839) in SendPropFloat 'm_angEyeAngles[0]', clamping.
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
EmitSound: volume out of bounds = 1.500000
DataTable warning: player: Out-of-range value (359.503021) in SendPropFloat 'm_angEyeAngles[0]', clamping.
DataTable warning: player: Out-of-range value (359.503021) in SendPropFloat 'm_angEyeAngles[0]', clamping
```

Discussion: http://facepunch.com/showthread.php?t=1374457&p=44896020&viewfull=1#post44896020

**Comment by Noiwex** [comment]
i want it to shut up

**Comment by MattJeanes** [comment]
These should be moved into developer 1/2 as @Revenge282 said.

**Comment by DrVrej** [comment]
This happens with me as well, specially EmitSound

**Comment by Nyaaaa** [comment]
Maybe if the devs were better at coding it wouldn't happen!

**Comment by robotboy655** [comment]
You are just asking for a ban, don't you?

**Comment by Nyaaaa** [comment]
@robotboy655 Not to be funny, But you get paid alot from garry to fix stuff no break it, Imo you're still a lua beginner!

**Comment by DrVrej** [comment]
His gonna ban you for it man, I wouldn't say that

**Comment by Noiwex** [comment]
It's not server developers to blame.
Shit works, but it spams a lot.

**Comment by Noiwex** [comment]
Anyway, I use enginespew as a workaround

**Comment by Nyaaaa** [comment]
@DrVrej I haven't done anything wrong, I'm showing my opinion!

**Comment by wiox** [comment]
Why would you want to disable a warning that indicates a sound is not playing because it is given an invalid volume?

**Comment by Noiwex** [comment]
Sigh.

**Comment by wiox** [comment]
>Hello, can I have 5 eggs?
>Here are your 3 eggs.
>Thank you.

**Comment by Revenge282** [comment]
It's not asking that they be disabled, it is asking that engine errors that the user has no control over be moved to the developer spews.  DataTable warnings and the EmitSound errors are not something a user needs to see.  That is for developers.  It would be very hard to dispute that.

**Comment by wiox** [comment]
The developer ConVar would need to be made more accessible. It's silly to assume every developer uses it.

**Comment by Revenge282** [comment]
I would imagine having something like a ConVar named "developer" where you could turn it on and off would be suffice...  Seriously though, how do you make it any more accessible than it already is?  They aren't Lua errors, because it's technically not bad code.
If the developer ConVar is 0, then there should really be no spew from the engine to the console.  Just your basic messages, and maybe anything fatal.

**Comment by robotboy655** [comment]
I am not sure if you realize this, but the console is called "Developer Console" for a reason. Nothing in it is aimed for regular users.

**Comment by Revenge282** [comment]
I'm not sure if you realize this, but we have kind of broken that rule with Gmod. ConCommands for gamemodes, binds, addons setting Cvars.  Yeah it'd be great if everyone made GUIs for their bind setups, but that isn't really an option since the concommand restriction in Lua.  The console may not be intended for users, but it very much has become a necessity now.

**Comment by robotboy655** [comment]
You don't need to read the console output to type in commands, do you?

**Comment by MattJeanes** [comment]
I believe that `DataTable warning: player: Out-of-range value (359.503021) in SendPropFloat 'm_angEyeAngles[0]', clamping` is not caused by any addons at all, and just source engine. I could be wrong though. EmitSound on the other hand can be caused by a variety of sources, from lua to map iirc

**Comment by Revenge282** [comment]
That wasn't the argument.  The argument was that the console is not for users.

But since users have to use the console, it would be a good idea to move *specifically* developer spew to the developer ConVar outputs.

**Comment by wiox** [comment]
What if a developer doesn't want to enable the developer convar?

**Comment by Revenge282** [comment]
Then the developer will get Lua errors, and not engine errors or other developer spew?

**Comment by MattJeanes** [comment]
If it's possible to trace down the cause of the error, then just make it a lua error if it's caused by lua or else hide it in developer 1/2

**Comment by wiox** [comment]
> Then the developer will get Lua errors, and not engine errors or other developer spew?

Warnings don't cause Lua errors. You are trying to hide messages that could be helpful to a developer wondering why he can't get a sound to play.

**Comment by Revenge282** [comment]
Then he can turn developer spew to 1.  I am not really getting what the downside of having it turned on if you are developing are?  The point is things like the DataTable warning, vertex errors, and many of the errors that are thrown with maps and such have no place outside of the developer spew.  Of course there are exceptions for things, and the invalid sound may very well be one.  I can't think of any others off the top of my head though.

**Comment by wiox** [comment]
If I type "lua_run Entity(1):EmitSound( ... )" in my console and nothing happens like hell is my first instinct to set developer to 1.

**Comment by Revenge282** [comment]
I appreciate you reading the entirety of my post and formulating a response pertaining to it.  Thank you for advancing the discussion.

**Comment by wiox** [comment]
The console __is__ a developer spew.

**Comment by Revenge282** [comment]
We just went over this literally 12 posts ago...

**Comment by wiox** [comment]
It's easy enough to make an addon not require console commands. If you're not able to do that, your addons are far from user friendly.

**Comment by robotboy655** [comment]
Lets just leave this pointless conversation at this:
https://github.com/Facepunch/garrysmod-requests/issues/269

If it ever will be added, you can do that you want with your output. Warnings will NOT be disabled or moved to developer 1.

**Comment by Revenge282** [comment]
Please don't attack me in a GitHub issue ticket.  We're here to get something changed for the better of the game, it's not a competition.  However, if it means anything, I am capable of not requiring console commands in my addons.  But, it is much easier to just "bind x +cmd" rather than to make a whole interface for the user to pick keys and commands within the addon. and there are definitely cases where avoiding them is either not effective or possible.
