### ISSUE TITLE
Crash when calling game.CleanUpMap() within ENT:StartTouch

### ISSUE THREAD

**Issue by Spacetech** [Facepunch/garrysmod-issues#1142]
The dedicated server crashes when you call game.CleanUpMap() within ENT:StartTouch of a map created brush type entity (a trigger).

The client and server build are 14.0.4.19.

**Comment by Kefta** [comment]
You could check if the engine is in the process of a physics callback when game.CleanUpMap is called, and queue it if so (same as https://github.com/Facepunch/garrysmod-requests/issues/940 / https://github.com/Facepunch/garrysmod-requests/issues/894).
