### ISSUE TITLE
Vector:WithinAABox() Doesn't Work with Negative Numbers

### ISSUE THREAD

**Issue by ischmal** [Facepunch/garrysmod-issues#1146]
print( tostring( Vector( 3, 3, 3 ):WithinAABox( Vector( 0, 0, 0 ), Vector( 5, 5, 5 )))
-- returns true

print( tostring( Vector( -3, -3, -3 ):WithinAABox( Vector( 0, 0, 0 ), Vector( -5, -5, -5 )))
-- returns false

**Comment by robotboy655** [comment]
It now orders vectors on its own
