### ISSUE TITLE
Vehicles do not generate PhysicsCollide without a driver

### ISSUE THREAD

**Issue by robotboy655** [Facepunch/garrysmod-issues#1175]
Basically, 
```
hook.Add( "OnEntityCreated", "", function( veh )
	if ( !veh:IsVehicle() ) then return end

	veh:AddCallback( "PhysicsCollide", function( veh, data ) print("hit") end )
end )	
```

Will only print "hit" when there's someone in the car. This only happens to prop_vehicle_jeep and prop_vehicle_airboat.

**Comment by Yuri6037** [comment]
I have the same problem with my mod_vc2. I'm unable to cause damages to a vehicle which has no drivers.

**Comment by wiox** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/56accfdb9c4abd32ae1dc26b2e4cc87898cf4dc1/sp/src/game/server/vehicle_base.cpp#L901-L904
