### ISSUE TITLE
GM:PlayerBindPress is not called for key releases

### ISSUE THREAD

**Issue by robotboy655** [Facepunch/garrysmod-issues#1176]
This makes its third argument worthless.

```
hook.Add( "PlayerBindPress", "", function( ply, cmd, pressed )
    print( ply, cmd, pressed )
end )
```

Output:

```
Player [1][Rubat]   +forward    true
Player [1][Rubat]   +use    true
Player [1][Rubat]   +speed  true
Player [1][Rubat]   +use    true
Player [1][Rubat]   +speed  true
Player [1][Rubat]   +forward    true
Player [1][Rubat]   +jump   true
Player [1][Rubat]   +moveright  true
Player [1][Rubat]   +forward    true
Player [1][Rubat]   +use    true
```

It should at least be called for -use, -speed, etc.

**Comment by Kefta** [comment]
Yeah it would be better to just call the -command equivalent on release; most implementations of this hook I've seen just ignore the third argument since it's been useless for so long.

**Comment by Tripperful** [comment]
It seems to work correctly from my tests at the moment, maybe close this ticket and remove the corresponding "BUG" from [that](http://wiki.garrysmod.com/page/GM/PlayerBindPress) page

**Comment by robotboy655** [comment]
It definitely doesn't work correctly.

**Comment by Tripperful** [comment]
Oh, yeah, it doesn't. I just got lucky to get it working somehow with +use in my particular case, the "pressed" argument works correctly there but nowhere else. That's very strange and still needs fixing, my bad

**Comment by mcNuggets1** [comment]
It doesnt work only on a few ones.

**Comment by lechu2375** [comment]
When this will be fixed??

**Comment by robotboy655** [comment]
I have looked into this and it's due to how engine handles the key-up events.

Basically it will only send the key-up event to the "event listener" that 'filtered' the key-down event, since it wouldn't make sense for the engine to receive the key-up event if the UI captured the key-down event.
This means that the `pressed` argument will only ever be false and the hook itself will only ever be called for key releases if the hook itself blocked the key-press in the first place.
