### ISSUE TITLE
Bad SetLocalOrigin on gmod_hands

### ISSUE THREAD

**Issue by dev02ify** [Facepunch/garrysmod-issues#1184]
Also see https://github.com/Facepunch/garrysmod-issues/issues/1185

Putting this here because I think it's a bug.
http://facepunch.com/showthread.php?t=1394674

Tested on a freshly installed vanilla server with a vanilla client. 
OS: Windows 7 (For both server and client)
## Post 1

"
I assume the gmod_hands entities are for the gmod13 hands that change with playermodels.

On my server the hand entities seem to be "welded" to the player, but they are very far away, they aren't on the player for some reason (Is it supposed to be like this?)

On certain maps this is fine, the hand entities happen to fall within the map boundaries when a player spawns or respawns, but on some maps the hand entities will spawn outside of the world boundaries. When this happens I get this error in the server console:

```
Bad SetLocalOrigin(Vector of the hands entity here) on gmod_hands (entity index of the hands entity)
```

I've tried teleporting to the vector it says and it's always outside of the world

(also when I teleport there since it's outside the map I get the error

```
Bad SetLocalOrigin(Vector) on player (1)
```

which I think proves that's what this error means)

I've looked on google but didn't find anyone asking about it, but it's in a lot of server consoles people have pasted for other reasons.
"
## Post 2

"
I did some testing and found ways to reproduce the error:

-Killing yourself or disconnecting near the edge, at the top corner, or outside of the map.
-Flying near the edge, to the top corner, or outside of the map and switching your weapons a lot (it will not happen on every switch, it happens on random switches.)
-Spawning in a location such that the hands spawn outside of the world (An example is sb_gooniverse on these spawn points: http://i.imgur.com/G2YC9oU.jpg http://i.imgur.com/HfDnJaV.jpg
-Creating any kind of entity outside of the map will give the error for that entity (such as spawning a prop or throwing a grenade) I would like to add that spawning props outside of the map throws this error:

```
Crazy physics on [entity id] [entity class] [entity angles] [entity position] - removing
```

-If you fly out of the map and kill yourself or switch your weapons, it will throw the same type of error but for the current weapon your holding, examples:

```
Bad SetLocalOrigin(Vector) on weapon_shotgun (entity id)
```

```
Bad SetLocalOrigin(Vector) on physgun_beam (entity id)
```

This error does not always occur under some of these circumstances, there's a lot of randomness to it. 
"

**Comment by mcNuggets1** [comment]
I also encountered these.

**Comment by robotboy655** [comment]
It's a result of unparenting/changing parents IIRC and ultimately doesn't really mean or do anything.

**Comment by fabianzimber** [comment]
Is there any workaround for this, or a possibility to disable the error message?
I know it doesn't break anything, but its an annoying console message, every time the player equips a toolgun or something

**Comment by Kefta** [comment]
You can install enginespew and hide the error.

**Comment by KingMonkeyBug** [comment]
How is this still open

**Comment by ZombieWars** [comment]
> How is this still open (after 10 years)

fr
