### ISSUE TITLE
concommand issuses

### ISSUE THREAD

**Issue by neico** [Facepunch/garrysmod-issues#1198]
1. AddConsoleCommand seems to have a problem with "connect", if it finds that word somewhere in the concommand then it doesn't register it, examples would be: "irc_connect" "irc_disconnect" "connect_irc", concommand.Add all adds those to the table, but the engine never registers those (maybe exporting the banned words to concommand.Add would be a good idea since the wiki doesn't list them anymore)

2. concommand.Remove is rendered useless, reason: no RemoveConsoleCommand which tells the engine to actually delete it, the only thing the function does currently is deleting the concommand out of the table, which has no effect on the engine...

**Comment by robotboy655** [comment]
1. Fixed.
2. Not a problem. It still does what it is supposed to.
