### ISSUE TITLE
d3_Breen Map bugged

### ISSUE THREAD

**Issue by Raffine52** [Facepunch/garrysmod-issues#1227]
Hello my first time posting, But after Dr.breen Blasts The Rods holding 3 people, After a white screen, Dr.Eli Will freeze after Finishing His Animation, Making Reaching To Dr.breen for the Final Battle unreachable without Noclip. Here the Error:

Dynamic prop Brokenarm1: no sequence named:open
Viewcontrol blackout_viewcontroller was enabled twice in a row!

**Comment by robotboy655** [comment]
I've looked into this, but was unable to identify the problem. It seems that either something prevents Alyx from walking to Eli, or something doesn't tell Alyx to walk there. It's definitely not the scenes or the model.

**Comment by robotboy655** [comment]
Should be fixed in Dev.

**Comment by kem008** [comment]
Okay I am really close to fix this map now I need to know why I stuck on the back when I get teleported.
Alyx is waiting for me everything looking good now :D
