### ISSUE TITLE
FCVAR_REPLICATED isn't enforcing itself properly. 

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#1234]
This appears to be an issue primarily with Lua based convars that are created. A basic example is with 'lua_errors_url' and that it won't update between state / server changes (therefore you get a fair bit of garbage). 

Other examples could be a convar for debugging that uses FCVAR_REPLICATED and FCVAR_ARCHIVE, as a result the client will always store the last value and use it when they join the server, regardless of what the server value is. 

The issue seems to persist from around the time when sv_allowcslua was added and engine based convars don't seem to suffer from this issue. 

This was briefly touched on over here - https://github.com/Facepunch/garrysmod-requests/issues/240

**Comment by willox** [comment]
Should be fixed in the dev branch.
