### ISSUE TITLE
OnReloaded not being called Clientside

### ISSUE THREAD

**Issue by ShadowRanger** [Facepunch/garrysmod-issues#1236]
Ever since the fix on OnReloaded recently, I've noticed a problem to where it is not being called on the client. For testing, I used the base gamemode and added a simple print to OnReloaded in the gamemode's shared.lua:

```
function GM:OnReloaded( )

    print( "OnReloaded has been called!" )

end
```

Firstly, I edited the init.lua and saved the file. OnReloaded was called and the debug text was outputted to the console. Next, I went ahead and edited the shared.lua file. Again, OnReloaded was called and the debug text was printed to the console. Lastly, I edited the cl_init.lua file. This time, nothing was printed to the console; OnReloaded was not called.

I'm also running the latest version of Garry's Mod on the dev branch. I'm not sure whether anyone else is having the same problem but I thought I should report that I am just in case. It would be great if someone could confirm this problem so we know whether it's an actual issue or not.

**Comment by StidOfficial** [comment]
I have a other problem.

Add this code :
`hook.Add("OnReloaded", "Test", function() print("test" ) end)`

Console return :
`Test`

And force autorefresh with \n :
```
hook.Add("OnReloaded", "Test", function() print("test" ) end)

```
Console return :
```
Test
Test
```

And remove :
`hook.Add("OnReloaded", "Test", function() print("test" ) end)`

Console return :
`Test`
