### ISSUE TITLE
util.KeyValuesToTable incorrectly parses strings that begin with numbers

### ISSUE THREAD

**Issue by Jcw87** [Facepunch/garrysmod-issues#125]
Example:

	"attributes"
	{
		"1-kill eater score type"
		{
			"attribute_class"	"kill_eater_score_type"
			"value" 	"3" 
		}
		"2-kill eater score type 2"
		{
			"attribute_class"	"kill_eater_score_type_2"
			"value" 	"59" 
		}
		"3-kill eater score type 3"
		{
			"attribute_class"	"kill_eater_score_type_3"
			"value" 	"60" 
		}
	}

Expected output:

	attributes = {
		["1-kill eater score type"] = {
			["attribute_class"] = "kill_eater_score_type"
			["value"] = 3
		},
		["2-kill eater score type 2"] = {
			["attribute_class"] = "kill_eater_score_type_2"
			["value"] = 59
		},
		["3-kill eater score type 3"] = {
			["attribute_class"] = "kill_eater_score_type_3"
			["value"] = 60
		}
	}

Output received:

	attributes = {
		[1] = {
			["attribute_class"] = "kill_eater_score_type"
			["value"] = 3
		},
		[2] = {
			["attribute_class"] = "kill_eater_score_type_2"
			["value"] = 59
		},
		[3] = {
			["attribute_class"] = "kill_eater_score_type_3"
			["value"] = 60
		}
	}

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/9053057/07ac4ee6-3a78-11e5-94a2-98f61bc51838.png)

**Comment by UAVXP** [comment]
Beautiful fix, bravo Robotboy
