### ISSUE TITLE
Possible Race-Condition when player get kicked/disconnect.

### ISSUE THREAD

**Issue by NightlyDev** [Facepunch/garrysmod-issues#1272]
When a player is kicked when connecting and when we try to access the player userdata at the same time, the server crash.

GDB Backtrace : 

#0  0xee0d38ab in real__game__GetWorld(ILuaInterface*) ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/server_srv.so
#1  0xe8cab91b in lj_BC_FUNCC ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/lua_shared_srv.so
#2  0xe8c9ca6d in lua_pcall ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/lua_shared_srv.so
#3  0xef0d01c0 in ?? ()
#4  0xe8c80615 in CLuaInterface::CallFunctionProtected(int, int, bool) ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/lua_shared_srv.so
#5  0xe8c7e50c in CLuaInterface::CallInternalGetBool(int) ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/lua_shared_srv.so
#6  0xedfe24ed in CLuaGameSystem::FrameUpdatePreEntityThink() ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/server_srv.so
#7  0xee059f70 in InvokePerFrameMethod(void (IGameSystemPerFrame::*)(), char const*) () from /home/nightlydev/reallife/reallife/garrysmod/bin/server_srv.so
#8  0xee3a0ee5 in CServerGameDLL::GameFrame(bool) ()
   from /home/nightlydev/reallife/reallife/garrysmod/bin/server_srv.so
#9  0xf61c9b3d in SV_Think(bool) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#10 0xf61ca4d5 in SV_Frame(bool) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#11 0xf6141f96 in _Host_RunFrame_Server(bool) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#12 0xf6142b09 in _Host_RunFrame(float) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#13 0xf6143128 in Host_RunFrame(float) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#14 0xf614c46e in CHostState::State_Run(float) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#15 0xf614c8c6 in CHostState::FrameUpdate(float) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#16 0xf614c989 in HostState_Frame(float) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#17 0xf61e055c in CEngine::Frame() ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#18 0xf61ddb6d in CDedicatedServerAPI::RunFrame() ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#19 0xf6d41225 in ?? ()
#20 0xf61ddfe5 in CModAppSystemGroup::Main() ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#21 0xf6219600 in CAppSystemGroup::Run() ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#22 0xf61de5a7 in CDedicatedServerAPI::ModInit(ModInfo_t&) ()
   from /home/nightlydev/reallife/reallife/bin/engine_srv.so
#23 0xf6d41192 in ?? ()
#24 0xf6d7b950 in ?? ()
#25 0xf6d7b950 in ?? ()
#26 0xf6d41612 in ?? ()
#27 0x08048872 in main ()

I'm running CentOS 7. After a user is banned when connecting, the function PlayerDisconnected is called. If we try to access userdata on the PlayerDisconnected hook, the server can crash.

**Comment by robotboy655** [comment]
This should've been fixed by one of previous updates.
