### ISSUE TITLE
function type() returns 'table' on Color objects

### ISSUE THREAD

**Issue by Revenge282** [Facepunch/garrysmod-issues#1283]
print( type( Color(255,255,255) ) ) returns 'type', should return 'Color'

**Comment by Kefta** [comment]
This could be fixed with a __type metamethod https://github.com/Facepunch/garrysmod-requests/issues/584

**Comment by willox** [comment]
We decided a while back that changing the behavior here isn't a great idea. I know quite a lot of code relies on it including multiple addons I even wrote myself.
