### ISSUE TITLE
SnapShot crashing

### ISSUE THREAD

**Issue by monkstick** [Facepunch/garrysmod-issues#1290]
17765(1899.259595):  L 07/11/2014 - 17:11:07: Engine error: [GM:CallWithArgs - !ThreadInMainThread] PlayerDisconnected

17764(1899.259416):  [GM:CallWithArgs - !ThreadInMainThread] PlayerDisconnected
17763(1899.259227):  L 07/11/2014 - 17:11:07: "[Salty]NavyBlue [GB]<35><STEAM_0:1:42865425><>" disconnected (reason "ERROR! Couldn't send snapshot.")
17762(1899.259014):  ERROR! SendData reliabe data too big (169590)17761(1899.176784):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.
17760(1899.069141):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.
17759(1899.067598):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.
17758(1899.065974):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.
17757(1899.064183):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.
17756(1899.062174):  CreateFragmentsFromFile: 'user_custom/89/894ed6b8.dat' doesn't exist.

This has been happening an awful lot the past few days.  Someone joins and they can't receive the snapshot, so the whole server crashes.  I don't care about the client not being able to join properly and needing to re-join, but could you perhaps do some wizardry so the whole server doesn't get taken down.

This is being run on Sandbox and its not isolated to one map.

**Comment by robotboy655** [comment]
#697
