### ISSUE TITLE
Ragdolls position is not restored after loading a save

### ISSUE THREAD

**Issue by Volkov893** [Facepunch/garrysmod-issues#130]
http://youtu.be/2ASbhe66N5k

I have seen this problem on Ubuntu 12.04 LTS 64-bit. Garry's Mod - 13.06.11.

**Comment by drSo** [comment]
This problem still exists.
But as @jdcoolha said, if you interact with them (usually on the shoes) they will be at their original position.

**Comment by robotboy655** [comment]
#445
