### ISSUE TITLE
lua_shared Exported C functions

### ISSUE THREAD

**Issue by sbarisic** [Facepunch/garrysmod-issues#1317]
Can we maybe get a little bit more exported lua api in lua_shared next time? For example there are these

> luaopen_base
> luaopen_bit
> luaopen_debug
> luaopen_jit
> luaopen_math
> luaopen_os
> luaopen_package
> luaopen_string
> luaopen_table
> lua_tolstring

but not these

> luaopen_io
> luaL_tolstring
> lua_tostring

And i'm missing lua_tostring the most there and i don't want to use ILuaBase->ToString or something because it just feels like hacking to get the proper offsets and what not when using C# for example.

**Comment by dkuschmierz** [comment]
Hi,

I know you closed the Topic 3 years ago, but at the Moment i‘m facing the same problem. Did you find out what was the Reason that lua_tolstring corrupted the heap?

**Comment by cartman300** [comment]
@dkuschmierz 

You might want to check this out.
https://github.com/cartman300/Lua.NET/blob/master/Lua.NET/LuaAPI.cs#L391

I don't remember why the C++ version didn't work anymore.
