### ISSUE TITLE
npc_maker and npc_template_maker not registering npcs killed with gravity gun

### ISSUE THREAD

**Issue by Panzerhandschuh** [Facepunch/garrysmod-issues#1344]
npc_makers and npc_template_makers do not register manhacks that are killed by picking them up and launching them into a wall with a gravity gun. I made a test map that has a npc_maker with 8 manhacks total and 4 max alive at the same time. When the npcs are killed by grabbing them and throwing them with the gravity gun, only 4 will spawn instead of the 8 total. If you kill them with any other weapon, the npc_maker will spawn all 8 and fire the "OnAllSpawnedDead" output as it should. Here is the test map I made in order for others to replicate the issue for themselves: https://www.mediafire.com/?p8xtapmmc05avjw
Press the button on the left to start the npc_maker spawner. The button on the right will start the npc_template_maker spawner. Both have the same issues with not detecting manhacks getting killed with gravity gun grab and punt into walls.

 I would appreciate it if this could be fixed since some maps on my server require the players to kill all the npcs on the npc_makers in order to progress.

**Comment by ZehM4tt** [comment]
https://github.com/ValveSoftware/source-sdk-2013/pull/362

**Comment by robotboy655** [comment]
Is it only with manhacks, or is it also with scanners and headcrabs, etc?

**Comment by ZehM4tt** [comment]
It appears its only with manhacks as SetOwner prevents any collision with them to avoid damage I assume.

**Comment by robotboy655** [comment]
I guess I will just make a test map and tell all the NPCs then or something.

**Comment by ZehM4tt** [comment]
I have already tested this with the SDK, only npc_manhack is affected.

**Comment by robotboy655** [comment]
You can kill them with the gravity gun by "punting" them a few times.

**Comment by ZehM4tt** [comment]
Yes thats because nobody overrides the owner, see my pull request.

**Comment by robotboy655** [comment]
Ok, I see why it happens now, will be fixed in GMod.
