### ISSUE TITLE
ClientSideProp resets parent when too distant to render

### ISSUE THREAD

**Issue by Varen** [Facepunch/garrysmod-issues#1355]
Tried to bonemerge a clientsideprop to a player. Works as long as the player remains in the field of view, then resets the parenting. I have to re-parent it to the player constantly. (Or, at least, every time clientsideprop:GetParent() != parentplayer)
I suppose it's a bug?

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/861
