### ISSUE TITLE
Aux Powers Not Functioning

### ISSUE THREAD

**Issue by BloodyMary55** [Facepunch/garrysmod-issues#1362]
Aux Powers (Sprint, Flashlight, Oxygen) are all disabled in Garry's Mod. mp_flashlight is outright blocked. The command "sv_infinite_aux_power" is set to 0 by default, but has no effect anyway. This is pretty detrimental to campaign players, and this issue has had popular support on Facepunch to be fixed.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/651
