### ISSUE TITLE
"enableaggressivebehavior" does not work on npc_strider

### ISSUE THREAD

**Issue by BloodyMary55** [Facepunch/garrysmod-issues#1363]
The Input "enableaggressivebehavior", which gives the npc_strider its ability to rapidly fire its minigun with high accuracy, does not function properly in Garry's Mod. The Strider will fire its cannon appropriately if ent_fire'd with the Input, but the cannon will deal 0 damage to the player and NPCs. This also makes the Strider's stomp attack extremely buggy and causes issues in several Strider sections on campaign maps.

https://developer.valvesoftware.com/wiki/Npc_strider

**Comment by robotboy655** [comment]
Damage will be fixed in the next update. I have no idea what you are talking about "Strider's stomp attack being extremely buggy", so unless you can give me examples, I am not going to be looking into it.
