### ISSUE TITLE
OnEntityCreated is called right before EntityRemoved is called on player objects on the server

### ISSUE THREAD

**Issue by JacobAsmuth** [Facepunch/garrysmod-issues#1371]
I know that was a convoluted bug description. Basically here's what happens:
1. player clicks "disconnect" (or somehow leaves the server)
2. OnEntityCreated is called, passing that player object (serverside only)
3. EntityRemoved is called, also passing that player object(shared)

http://facepunch.com/showthread.php?t=1374457&p=45460578#post45460578

edit: as a side note, can the hook names also be standardized? Either OnEntityRemoved or EntityCreated please!

**Comment by Kefta** [comment]
It seems players aren't the only entities created on disconnect. These are created when a player exits a single-player game:
```
Entity [2][soundent]
Entity [3][player_manager]
Entity [4][gmod_gamerules]
Entity [5][bodyque]
Entity [6][bodyque]
Entity [7][bodyque]
Entity [8][bodyque]
Entity [9][ai_network]
Entity [174][spotlight_end]
Entity [175][beam]
Entity [176][spotlight_end]
Entity [177][beam]
Entity [178][spotlight_end]
Entity [179][beam]
Entity [180][spotlight_end]
Entity [181][beam]
Entity [182][spotlight_end]
Entity [183][beam]
Entity [116][physgun_beam]
Entity [120][predicted_viewmodel]
Entity [121][predicted_viewmodel]
Entity [122][scene_manager]
```

**Comment by TIMONz1535** [comment]
If you save the player’s entity in a variable while he played on the server, and then compare it with the **EntityRemoved** argument, you will get a false result, because these are different entities :sob:

**Comment by robotboy655** [comment]
Should be solved on Dev.
