### ISSUE TITLE
Particle control points for "On Model Random" causing console spam.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#1374]
Cannot update control point 0 for effect 'FireWarmth_Heal' is basically spammed in my console whenever its placed on players, Even though its using On Model Random, If the entity in question has no Attachments then using 1 in the ParticleEffectAttach function client side will cause the spam aswell.

The only reason gmod is spamming this is because im calling ParticleEffectAttach multiple times to repeat a particle proccess, Since "Stopping Particle Effects" on something stops ALL effects, Im using this to have Multiple effects on the same entity without having to create any confined intricrate SHIT.

I could rectify this myself, If there was a client side hook that allowed me to return false whenever something was printed to the console, EG:

function ConsolePrint(txt)
if string.find(txt,"Cannot update control point") then
return false
end
hook.Add("OnConsolePrint","CPHOOK",ConsolePrint)

Sadly, This doesnt exist yet.

**Comment by robotboy655** [comment]
Switched to DevWarning instead.
