### ISSUE TITLE
Awesomium not loading Flash/Silverlight plugins on OS X

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-issues#1398]
I've done research and both the Adobe Flash Player and Microsoft SIlverlight are supposed to be loaded on all versions of Awesomium if installed on the client. My best guess through what I know about Awesomium is it's searching the path for the plugins, it should be searching for them in **/Library/Internet Plug-Ins**. Fixing this bug would allow gamemodes and addons like Cinema and PlayX to be fully functional on OS X.

**Comment by Jitterclick** [comment]
Wait, is this a fix or a guess? If you are explaining how to fix this can you please elaborate?
