### ISSUE TITLE
TTT: Picking Up Weapon with Magneto-Stick then Actually Picking it up Breaks Weapon

### ISSUE THREAD

**Issue by YourStalker** [Facepunch/garrysmod-issues#1401]
In Trouble in Terrorist Town if you pickup a weapon (like an m16 for example) with a magneto-stick then actually pick it up into your inventory to equip it when you pull out the gun you wont be able to shoot it. An easy way to test this out is to go on the map ttt_plaza_b7 and at the spawn you'll see gun racks. Take a weapon off the gun rack with the magneto-stick and then equip it. The gun won't be shoot-able till you drop it and pick it back up.

**Comment by YourStalker** [comment]
Why was this closed if it wasn't fixed?

**Comment by robotboy655** [comment]
This is not a place for TTT bug reports
