### ISSUE TITLE
DProgress still showing green even with no fraction set/fraction set to 0

### ISSUE THREAD

**Issue by Jax13** [Facepunch/garrysmod-issues#1402]
When you create a DProgress bar with vgui, a small percentage of the bar is already green regardless of what fraction you put
![capture](https://cloud.githubusercontent.com/assets/3679938/3861667/a11c8f0e-1f31-11e4-8ba2-11d0c8c962f6.gif)
in the gif, you can see how the actual progress bar overwrites over the small portion that is already there

**Comment by robotboy655** [comment]
Fixed https://github.com/garrynewman/garrysmod/commit/d187be6c07626a5e1ac641767ff6ea13c5264168
