### ISSUE TITLE
Crash with file.Find("models*/*", "GAME")

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#1405]
Hello,
When I type exactly **file.Find("models_/_", "GAME")**, the game crashes within 1 second.
I cannot say more than that.

**Comment by robotboy655** [comment]
Most likely was fixed, I cannot reproduce the crash with neither ```file.Find("models*/*", "GAME")``` nor ```file.Find("models_/_", "GAME")```.
