### ISSUE TITLE
render/Capture fails to capture area larger that main screen.

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#1410]
I have very huge render target (which is 8192x8192). And when I try to use render.Capture inside of it it just returns nil. If I tell render.Capture to capture smaller area (say, 1024x1024), it succeeds. Mine's screen resolution 1920x1080 so I thing there's something that blocks capture in higher res.

**Comment by Noiwex** [comment]
Hello?

**Comment by grinchfox** [comment]
Having some pain from this issue. So please fix it.

**Comment by robotboy655** [comment]
It seems that http://wiki.garrysmod.com/page/render/CapturePixels is unaffected, so if you can use that for now.

**Comment by Noiwex** [comment]
Unfortunately, it's really slow and doesn't allow us to save stuff in jpegs and pngs. Not a solution.

**Comment by robotboy655** [comment]
Will be fixed in next Dev branch update, whenever it updates.

**Comment by shadowscion** [comment]
I don't think this was actually fixed.

**Comment by Noiwex** [comment]
Depends on your videocard.
