### ISSUE TITLE
render/Capture through void captures void with alpha 1, and world with alpha 0.

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#1411]
Using tools like photoshop can reveal, that alpha channel comes inverted.

**Comment by UselessGhost** [comment]
Bringing attention back to this issue. Huge pain to not be able to make PNGs for shit without the alpha channel getting brutalized.

```
hook.Add( "PostRender", "a", function()
	local img = render.Capture{
		format = "png",
		x = 0,
		y = 0,
		w = ScrW(),
		h = ScrH()
	}

	f = file.Open( "image.dat", "wb", "DATA" )
	f:Write( img )
	f:Close()

	hook.Remove( "PostRender", "a" )
end )
```

Result: http://i.cubeupload.com/AkLsjo.png

**Comment by Noiwex** [comment]
http://wiki.garrysmod.com/page/render/SetWriteDepthToDestAlpha

**Comment by UselessGhost** [comment]
Passing true or false to this doesn't seem to change the outcome no matter where I put it and there's no documentation, could you perhaps elaborate?

**Comment by TrenchFroast** [comment]
Calling this in PreDrawSkyBox seems to make it capture correctly, haven't tested it too much though

**Comment by Noiwex** [comment]
Yeah, it's no use.

**Comment by NeatNit** [comment]
Just ran into this, any chance it gets fixed? render.Capture for PNG is just about worthless because of this.

**Comment by Tenrys** [comment]
save as jpg and rename to png? lolol

**Comment by Noiwex** [comment]
I used imagemagick to inverse alpha channel.

**Comment by robotboy655** [comment]
render.Capture no longer alters alpha channel in any way.

**Comment by Noiwex** [comment]
"render.Capture's alpha channel is now always fully opaque robotboy655 on Garrys Mod/main#4008"

No, this is wrong way to fix.

What about render targets with alpha channel?

**Comment by Noiwex** [comment]
revert pls

**Comment by robotboy655** [comment]
Give me a use case. Adding an option to disable this/invert the alpha channel shouldn't be too hard provided there's a reason to bother with it.

**Comment by Noiwex** [comment]
Pre-rendering contraptions to be displayed on website.

**Comment by NeatNit** [comment]
>render.Capture no longer alters alpha channel in any way.

I am on pre-release, this is still happening.

**Comment by robotboy655** [comment]
You need to set "alpha" to false.

**Comment by NeatNit** [comment]
how silly of me
