### ISSUE TITLE
markup.Parse gives weird word wrap when text has unicode symbols.

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#1420]
Picture is better that thousand words: https://dl.dropboxusercontent.com/u/7313569/ShareX/2014-08/2014-08-13_19-39-47.png

**Comment by robotboy655** [comment]
The supposed culprit: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/modules/markup.lua#L272

**Comment by Noiwex** [comment]
`select(2, blocks[i].text:gsub("[^\128-\191]", ""))`

**Comment by Noiwex** [comment]
Can garry finally unban me, so I could send pull requests?

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/pull/943
