### ISSUE TITLE
Issue starting up Gmod Server on Ubuntu 14.04

### ISSUE THREAD

**Issue by noahp78** [Facepunch/garrysmod-issues#1426]
I get this issue when starting the Gmod Delicated Server:

```
configstore.cpp (1257) : Assertion Failed: Saving local config store failed during shutdown
Assert( Assertion Failed: Saving local config store failed during shutdown ):/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/configstore.cpp:1257

Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20140815170423_1.dmp
success = yes
response:  CrashID=bp-dfe8254a-43e6-48a6-b3a6-6c8d42140815
configstore.cpp (101) : Assertion Failed: ConfigStore (InstallConfigStore) is dirty, and being destroyed, we're discarding data
Assert( Assertion Failed: ConfigStore (InstallConfigStore) is dirty, and being destroyed, we're discarding data ):/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/configstore.cpp:101

Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20140815170440_2.dmp
```

This doesn't stop the server from launching. But it takes a long time to do the uploading.

How to replicate:
1. Launch server with command "./srcds_run -console -game garrysmod -maxplayers 32 +map ttt_minecraft_b5 +gamemode terrortown +host_workshop_collection 299016116 -authkey ~ ~ ~"
2. Wait
3. There you go

Running latest version avaible on steamcmd
If it helps I'm using the latest ubuntu avaible for Windows Azure.

**Comment by Devul** [comment]
I am now having this issue on the newest Version of Ubuntu.

It starts up, but the error postpones startup for at least 30 seconds.
