### ISSUE TITLE
Ragdolls with collisions disabled have collisions re-enabled upon duplicating

### ISSUE THREAD

**Issue by sophersky** [Facepunch/garrysmod-issues#1431]
Title is self-explanitory, for example if I spawn a Breen ragdoll and disable collisions on it, and if I duplicate it and spawn it again, collisions will be re-enabled.

**Comment by robotboy655** [comment]
Should be fixed.

Could not reproduce what @DrVrej  has reported, likely that's a sideeffect of an addon you are running, like an anti spam/proppush addon.
