### ISSUE TITLE
Draggable panels are only droppable at the top of the panel

### ISSUE THREAD

**Issue by Netheous** [Facepunch/garrysmod-issues#1453]
You can only drop the panel if you drag it and drop at the top of the panel.
If the panel you want to drop another panel on is 500px tall and your draggable panel is 100px tall then you can only drag panel and drop it at first 100px of the non-dragable panel otherwise the func won't get called.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/96928f893f8458be914f043a996a325740ccc0e8
