### ISSUE TITLE
Nav Files (.nav) Do Not Load When Packed Into Addons (.gma)

### ISSUE THREAD

**Issue by nanospork** [Facepunch/garrysmod-issues#1455]
Adding a nav mesh into a .gma file causes the mesh to fail to load in Gmod with this console error: 
`nav file is wrong or something (1)`

So far, I have tested this with the nav mesh packed into an addon next to the map and packed in its own addon. Both nav meshes generated in Source SDK Base 2007 and in Gmod cause the same error. The nav mesh works fine when it is dropped directly into the garrysmod/maps folder. Opening the 2007 mesh and resaving it in Gmod has no effect other than slightly increasing the filesize.

Update: I have found that packing the nav mesh into the map file using VIDE or similar will work, as long as the map is only packed once. Packing more than once will apparently corrupt the map file somehow - obviously not the fault of Garry's Mod. This explains why my previous attempts to pack were unsuccessful - I had packed custom content earlier, then added the nav file later. Still, the nav file does not load if packed on its own into a .gma, so I will leave this thread up as it appears to be the only entry concerning this issue on this database.

**Comment by kklouzal** [comment]
Is this still an issue? Can we get the nav files loading again?

**Comment by willox** [comment]
it's fixed in the dev branch
