### ISSUE TITLE
Frequent crashes with Linux on joining a server

### ISSUE THREAD

**Issue by Sworddragon** [Facepunch/garrysmod-issues#1456]
If I'm playing for some time (1+ hour) and joining a server there is a chance that the game will crash after a certain point on the loading screen. After a restart of the game I'm able to successfully join the server where the crash appeared but after joining some more random servers the crash happens again. On looking with htop during the loading screens (and often before a crash appeared) I have noticed that the game has allocated nearly 4 GiB (VIRT) and written over 3 GiB (RES). Normally I would now assume that the game is only available in 32 bit and that just an OOM appeared possibly due to a memory leak. Here is my system environment:

Operating system: Linux 3.16.1 (x86_64)
Graphics card: GeForce GTX 650
Graphics driver: NVIDIA 331.89
X-Server: X.Org 1.15.1
Processor: AMD Phenom II X6 1045T
Memory: 16 GiB
Garry's Mod: 14.07.13

I'm assuming no addons are installed (as the addons menu doesn't list anything) or does the user-defined files that are automatically downloaded from some servers count?

**Comment by Sworddragon** [comment]
This issue got closed without giving a reason. Did this issue got fixed?

**Comment by s0r00t** [comment]
Nope.
