### ISSUE TITLE
Gravity Gun graphical issues

### ISSUE THREAD

**Issue by jackwilsdon** [Facepunch/garrysmod-issues#1464]
There seems to be some graphical issues with the Gravity Gun on Multiplayer. In third person, upon picking up an object with right click, the beams that are supposed to appear on the gun are displaced to the right of the player (drawn as it would be seen in first person). This seems to be caused by whether you spawn in third person with the Gravity Gun or not (thanks [Jvs](http://facepunch.com/member.php?u=226009)). ~~Also, using `E` to pick an object up will cause the Gravity Gun to go invisible in third person~~. I do not believe this shows for other players.

![](http://i.imgur.com/zpF7CYz.jpg)

**Comment by robotboy655** [comment]
Fixed
