### ISSUE TITLE
GMA whitelist not updated

### ISSUE THREAD

**Issue by AmyJeanes** [Facepunch/garrysmod-issues#1480]
As of https://github.com/garrynewman/gmad/commit/a121a70e298ab6e07fa77a5e4f72018c7480f758 GMAD now accepts more files, specifically gamemode content, but GMod itself (even on dev branch) does not, giving the following error:

```
Not loading addon 'AbyssRP' - file 'gamemodes/abyssrp/content/materials/env/obj/bank/bank_atm.vmt' not on whitelist
Couldn't mount addon [AbyssRP][addons/abyssrp_310462053.gma]
Removing bad addon addons/abyssrp_310462053.gma
```

**Comment by Mstrodl** [comment]
You should at least be able to extract them.
