### ISSUE TITLE
LINUX server .steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dgibbs64** [Facepunch/garrysmod-issues#1486]
I work on Linux Game Server Managers (https://github.com/dgibbs64/linuxgameservers) and I am starting to get reports of the following error when running Garrys Mod Server.

	Auto detecting CPU
	Using default binary: ./srcds_linux
	Enabling debug mode
	Server will auto-restart if there is a crash.

	Console initialized.
	Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
	Game_srv.so loaded for "Garry's Mod"
	Setting breakpad minidump AppID = 4000
	Initializing Steam libraries for secure Internet server
	[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
	dlopen failed trying to load:
	/home/gmodserver/.steam/sdk32/libsteam.so
	with error:
	/home/gmodserver/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
	Logging into anonymous gameserver account.
	Fetching Workshop Addons.. host_workshop_collection is unset
	dlopen failed trying to load:
	/home/gmodserver/.steam/sdk32/libsteam.so
	with error:
	/home/gmodserver/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
	dlopen failed trying to load:
	/home/gmodserver/.steam/sdk32/libsteam.so
	with error:
	/home/gmodserver/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
	dlopen failed trying to load:
	/home/gmodserver/.steam/sdk32/libsteam.so
	with error:
	/home/gmodserver/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
	Unknown command "cl_cmdrate"
	Unknown command "cl_updaterate"
	Unknown command "rate"
	"host_workshop_collection" = ""
	 game
	Network: IP 92.222.219.75, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
	Error loading cfg/trusted_keys_base.txt
	Error loading cfg/pure_server_minimal.txt
	PREP OK
	ConVarRef room_type doesn't point to an existing ConVar
	Executing dedicated server config file gmod-server.cfg
	Map cycle file 'cfg/mapcycle.txt' was not found.
	Nav File is wrong or something (4)
	Initializing Steam libraries for secure Internet server
	[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
	dlopen failed trying to load:
	/home/gmodserver/.steam/sdk32/libsteam.so
	with error:
	/home/gmodserver/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
	Logging into anonymous gameserver account.
	Unknown command "sv_allow_wait_command"
	Unknown command "sbox_plpldamage"
	Unknown command "sbox_maxspawners"
	Unknown command "sbox_maxturrets"
	Server logging enabled.
	Server logging data to file logs/L0909002.log
	L 09/09/2014 - 21:35:38: Log file started (file "logs/L0909002.log") (game "/home/gmodserver/serverfiles/garrysmod") (version "5727")
	Connection to Steam servers successful.
	   Public IP is 92.222.219.75.
	Assigned anonymous gameserver Steam ID [A-1:4033502214(4626)].
	VAC secure mode is activated.
	Tue Sep  9 21:35:43 CEST 2014: Server Quit

The problem is that .steam directory no longer appears to exist with SteamCMD

To fix the issue use the following commands:

    mkdir  ./.steam
    mkdir  ./.steam/sdk32/
    cp ./serverfiles/bin/libsteam.so ./.steam/sdk32/

Could this issue be resolved server side. If the server looks for libsteam.so in the bin dir instead of .steam/sdk32 I belive this should be easily resolved.

Thank you

**Comment by UltimateByte** [comment]
Still that error...
It's not critical but still there...

**Comment by robotboy655** [comment]
#180
