### ISSUE TITLE
Official website should state Linux support

### ISSUE THREAD

**Issue by NothingMuchHereToSay** [Facepunch/garrysmod-issues#1494]
http://www.garrysmod.com/updates/

There's a lack of promoting Linux we have here, mind if the webmaster of that website added a button? :P

**Comment by NothingMuchHereToSay** [comment]
Nope, still not fixed yet.

**Comment by mcd1992** [comment]
It would also need a OSX glyph as well. Might as well just use the SteamPlay icon there if we're gonna be pedantic. 

Realistically it doesn't really matter though. Everyone will just search for it on steam which shows the OS.
