### ISSUE TITLE
Clientside game.IsDedicated() always returns false

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#1495]
Hello,

The function **game.IsDedicated()** always returns **false** when used clientside.
On the Wiki, the given information is that this function can be used both clientside and serverside.

[game.IsDedicated() on Garry's Mod Wiki](http://wiki.garrysmod.com/page/game/IsDedicated)

**Comment by fruitwasp** [comment]
bump?

**Comment by robotboy655** [comment]
As far as I can tell the client has no way of knowing whether a server is dedicated or not, which is why the Lua binding is made to always return false on client.

**Comment by Kefta** [comment]
Maybe network the server type on connect? Don't know how useful that info would actually be.

**Comment by Bo98** [comment]
I think CS:GO has something similar for its net_graph. Possibly is just networked on connect.

**Comment by EstevanTH** [comment]
Then it's not a bug and the issue can be closed. 😄

**Comment by pparadoxx** [comment]
> Maybe network the server type on connect? Don't know how useful that info would actually be.

useful when using system.GetCountry()

**Comment by PrikolMen** [comment]
Dear Rubat, this will be fixed?

**Comment by RaphaelIT7** [comment]
The client fires the [server_spawn](https://github.com/OthmanAba/TeamFortress2/blob/master/tf2_src/engine/baseclientstate.cpp#L1224) gameevent when he joins the server.
The client also receives whether the server is dedicated. Maybe the value could be saved and returned until the client leaves the server.

It could also be bound to the [SVC_ServerInfo](https://github.com/OthmanAba/TeamFortress2/blob/master/tf2_src/common/netmessages.h#L389) net message, which receives all the data that the server_spawn gameevent uses.

If it would be done in one of these ways, this change wouldn't need any additional networking and could be done any time.

Example of the [server_spawn](https://github.com/OthmanAba/TeamFortress2/blob/master/tf2_src/engine/baseclientstate.cpp#L1224) gameevent:
(local game)
```lua
address = loopback
dedicated = false
game = garrysmod
hostname = Garry's Mod
ip = 0
mapname = gm_flatgrass
maxplayers = 8
os = W
password = false
port = 0
```

(joining a dedicated server)
```lua
----server_spawn----
address = 168.119.138.3
dedicated = true
game = garrysmod
hostname = Raphael's testing server
ip = 59406248
mapname = gm_flatgrass
maxplayers = 128
os = L
password = false
port = 29015
----------------------
```
