### ISSUE TITLE
Crouch Jumping causes movement hiccup until DuckSpeed ( time ) is over.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#1512]
A friend of mine asked me a question a while back regarding his BHop server. He told me that when crouch jumping onto some object higher than ground-level causes the player to stop moving momentarily. I was having trouble reproducing it. 

He asked me again a few hours ago if I had made any progress on it, so I came up with a theory... My assumption was that when moving into crouch, all works fine, but when jumping onto an object that is higher up, the player "lands" on the higher-up object but they aren't fully "touching" the ground / new object until the duck-time is up.

He tested my theory by setting DuckSpeed to 0 and it fixed the issue. The player no longer gets stuck / stopped from moving when crouch-jumping. I'm reporting this because it seems strange that DuckSpeed would cause this issue.

**Comment by willox** [comment]
Happens once curtime is a big number
