### ISSUE TITLE
IMaterial:SetTexture doesn't work with png files, sometimes it does.

### ISSUE THREAD

**Issue by EthanTheGreat** [Facepunch/garrysmod-issues#1517]
This works:

local currentMaterial = CreateMaterial( "newMatYay", "UnlitGeneric" )
currentMaterial:SetTexture( "$basetexture", "logo3.png" )

However something like:

local currentMaterial = CreateMaterial( "newMatYay", "UnlitGeneric" )
currentMaterial:SetTexture( "$basetexture", "logos/logo3.png" )

prints into console as: Texture 'logos/logo3.png' not found.

**Comment by robotboy655** [comment]
It does work perfectly with your code, as long as you load/cache the .png material first with Material(), like so:
```
	Material( "icon16/award_star_bronze_3.png" )
	MAT:SetTexture( "$basetexture", "icon16/award_star_bronze_3.png" )
```

**Comment by robotboy655** [comment]
Calling ```MAT:SetTexture( "$basetexture", "icon16/award_star_bronze_3.png" )``` first will cause the error material to be cached instead, since it will be trying to load a .vtf.

After caching, something like this will work too btw:
```MAT:SetTexture( "$basetexture", "icon16/award_star_bronze_3" ) ```

**Comment by robotboy655** [comment]
Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1531
