### ISSUE TITLE
util.PrecacheSound doesn't work with .ogg

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#1522]
As the title says, These functions/setups do absolutely NOTHING for the client, Running the sound even after labelling and "Precaching" them as so still causes the client to hitch for a moment before the sound loads.

Good.

**Comment by robotboy655** [comment]
Uh, I think this entire function is bogus.

Looking at the source code, it shouldn't precache anything ever. ( Maybe only sound scripts )

Or maybe I am misunderstanding it.

Either way, if something did prevent .oggs to be used with this, it should be fixed in Dev.
