### ISSUE TITLE
Removing a TextEntry's EditMenu causes the game to crash on TextEntry removal or the next right click

### ISSUE THREAD

**Issue by notcake** [Facepunch/garrysmod-issues#1523]
Calling _R.Panel.Remove on a TextEntry's right click menu (accessible via :GetChildren () or vgui.GetKeyboardFocus () after the first right click) causes the game to crash when the TextEntry is destroyed or right clicked again.

1. Create a TextEntry
2. Right click on the TextEntry to make it create its EditMenu.
3. Destroy its EditMenu ( eg. TextEntry:GetChildren () [1]:Remove () )
4. Right clicking the TextEntry again OR destroying the TextEntry causes Garry's Mod to crash.

Running the code below and right clicking on the TextEntry created will carry out steps 1 to 3:
```lua
if FRAME and FRAME:IsValid () then FRAME:Remove () end

FRAME = vgui.Create ("DFrame")
FRAME:MakePopup ()
FRAME:SetSize (400, 64)

FRAME.TextEntry = vgui.Create ("DTextEntry", FRAME)
FRAME.TextEntry:SetPos (4, 28)
FRAME.TextEntry:SetSize (FRAME:GetWide () - 8, FRAME:GetTall () - 32)

local focusedPanel = nil
hook.Add ("Think", "",
	function ()
		if vgui.GetKeyboardFocus () ~= focusedPanel then
			focusedPanel = vgui.GetKeyboardFocus ()
			
			if focusedPanel and focusedPanel:IsValid () and
			   focusedPanel:GetName () == "EditMenu" then
				-- Remove the EditMenu
				focusedPanel:Remove ()
			end
		end
	end
)
```

**Comment by robotboy655** [comment]
Non Lua-created panels can no longer be removed by Panel.Remove(). This change will not ship in next ( April ) update. Please let me know if this causes any problems.
