### ISSUE TITLE
Map causes crash on load after adding prop_static in Hammer

### ISSUE THREAD

**Issue by Guilmon** [Facepunch/garrysmod-issues#1535]
A previously working map stopped loading when attempting an update that adds TF2 props.

Maps (that use the same props) that were created before the latest TF2/GMod updates work fine. Is it related to the .NAV? Did something change in TF2 that breaks prop loading in GMod?

No errors in either the compile log or the garrysmod/garrysmod/console.log aside from water materials referencing themselves on $bottommaterial, and these worked before.

Map contains LUA scripted entities for a gamemode I'm working on, but it's just a test map. It broke when adding prop_statics that used TF2 models. The entities themselves worked fine.

For reference, I do use the Hammer.exe included with TF2 as opposed to the one in the SDK, as that one doesn't launch properly.

New maps made by friends of mine also encounter the problem, despite the maps loading fine in TF2.

**Comment by robotboy655** [comment]
Will be fixed in next update. ( Lightmap data is ignored )
