### ISSUE TITLE
include(currentFile) crash

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#1542]
If you call include and pass a path that resolves to the current file Garry's Mod will crash when launching a single player game.

Calling `include` on the client causes the fault module to be kernal32.dll, while the server fails with ntdll.dll.

The lua causes a crash on both the stable and development branches.

``` lua
if CLIENT then
    include(currentFile)
end

if SERVER then
    include(currentFile)
end
```

**Comment by robotboy655** [comment]
Closing as stale.
