### ISSUE TITLE
HTTP can only post parameters, not data.

### ISSUE THREAD

**Issue by zeroZshadow** [Facepunch/garrysmod-issues#1562]
Ive found that you cannot make an HTTP post request with just data, not parameters.

An example of this, im trying to implement GameAnalytics.com into an addon.
This requires me to send data as a post request, but not a parameter!

If i pass the string i want to post in parameters, it will not send it (as parameters need to be a table)
but when sending as {body = "somedata"} it will send it with body as a parameter, not the data.
(aaka, this becomes body="somedata", instead of just "somedata")

I suggest that if a string is passed to the parameters var, instead of a table, it will be send as is.

**Comment by snowywolf** [comment]
Same issue here. the only workaround (for clientside) is to use javascript.

**Comment by WinterPhoenix96** [comment]
I seem to remember POST Requests using the HTTP Library throwing up junk data when I tried it. That might be the same issue.

**Comment by robotboy655** [comment]
Added "body" and "type" ( falls back to "text/plain; charset=utf-8" ) to HTTP() input, body is the raw body for HTTP POST request, "type" is the content type for the body.

Setting "body" will override anything set with "parameters" table.

**Comment by zeroZshadow** [comment]
You are awesome!!
This allows me to use http://www.gameanalytics.com/ for tracking stuff like map and weapon usage.
Looking forward to the update.
