### ISSUE TITLE
BUG: Ragdolls turned into a statue wont turn back to normal

### ISSUE THREAD

**Issue by shoopdahoop** [Facepunch/garrysmod-issues#1564]
Whenever a ragdoll is made into a statue and duplicated, it will stay like that forever with no way to un-statue the ragdoll. This video demonstrates the bug:
http://youtu.be/yAGAiyuvRjo
(Wait for it to finish uploading)
Steps:
1. Make any ragdoll into a statue
2. Duplicate it
3. Try to un-statue the duplicated ragdoll. You will see it will stay as a statue no matter what you do.

**Comment by robotboy655** [comment]
Should be fixed on Dev beta branch and in the next update. This only affects new duplications. (Sorry, but this is how it has to be)
