### ISSUE TITLE
Panel:GetText() is limited to 1023 B and Panel:GetValue() is limited to 8091 B for TextEntries and 1023 B for other controls

### ISSUE THREAD

**Issue by notcake** [Facepunch/garrysmod-issues#1569]
This issue is preventing the Wiremod Expression 2 editor (and other code editors) from getting the full clipboard text when pasting into them.

``` lua
local control = vgui.Create ("DTextEntry")
control:SetText (string.rep ("A", 16384))
print (#control:GetText ())
print (#control:GetValue ())
control:Remove ()
```

Output:

```
1023
8091
```

**Comment by robotboy655** [comment]
Removed limit for TextEntry only for now, as the internal stuff for this REQUIRES a preset length.

Engine version of GetValue() remains unchanged, as it is really just an alias GetText() for Label and TextEntry and the only other panel that it does anything for is CheckButton, where there's only 2 possible values, "1" and "0".

If you really feel like there's some other panel that is really hindered by the limits of these 2 functions, do create a new issue or post here.
