### ISSUE TITLE
Pasting a long string into a text entry, undoing, then pasting anything in again causes part of the original string to be restored.

### ISSUE THREAD

**Issue by notcake** [Facepunch/garrysmod-issues#1588]
1. lua_openscript_cl the following:

``` lua
if FRAME and FRAME:IsValid () then FRAME:Remove () end

FRAME = vgui.Create ("DFrame")
FRAME:SetSize (256, 64)
FRAME:MakePopup ()

FRAME.TextEntry = vgui.Create ("DTextEntry", FRAME)
FRAME.TextEntry:SetPos (8, 32)
FRAME.TextEntry:SetSize (256 - 16, 64 - 40)

print ("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz")
print ("123")
```
1. Ctrl+C "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz" from the console
2. Ctrl+V into the text box
3. Ctrl+Z
4. Ctrl+C "123" from the console.
5. Ctrl+V into the text box
6. Press home
7. Resulting text is "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh123" or something similar.

(copy the text from the console, don't tab out of gmod to copy the text)

**Comment by thegrb93** [comment]
Trying to copy text from a DTextEntry also only partially copies the text.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
