### ISSUE TITLE
Gmod crashing when uploading a custom spray

### ISSUE THREAD

**Issue by ooblaze59oo** [Facepunch/garrysmod-issues#1590]
In Gmod version: 14.07.13
There is an issue when I try to upload a spray of mine.
I start up gmod normally and when I go into options and select the "Multiplayer" tab to import a spray and find the folder where the spray is located, my entire Garry's Mod closes. I can still reopen gmod and play on single an multiplayer. The crash only seems to happen when I try to open the folder where my spray is located. And yes i can recreate the crash as it seems to only affect that folder. I've tried moving the spray to a different folder to see if that would work, but no luck there either.

**Comment by robotboy655** [comment]
Closing as stale.
