### ISSUE TITLE
If you sit in a vehicle that is parented to you, the server crashes

### ISSUE THREAD

**Issue by Divran** [Facepunch/garrysmod-issues#1596]
This problem also happens if the vehicle is parented to an entity that is parented to you. I'm not sure if the crash occurs simply due to you sitting in the vehicle or if it happens because of the infinitely large positions that arise (because as you sit, you move to the chair. But the chair is parented to you so it also moves, and then you move with it, etc. Infinite loop, infinite position).
If the cause is infinite positions, then one possible fix may be to make a simple on vehicle enter hook that checks if the vehicle is parented to anything which is parented to the player that is trying to sit, and if so, unparent the vehicle (or prevent the player from entering the vehicle and display a chat message why they can't).
I will be doing some tests shortly to see if this solution works.

**Comment by willox** [comment]
Similar fix to yours is implemented in the game itself from next update. I wanted to just make it remove the parent-child relationship but it didn't seem to be possible to do properly.

**Comment by Divran** [comment]
@willox your fix spams the console with prints, just saying

**Comment by Kefta** [comment]
I think the Convar is sv_crazyphysics_echo or something
