### ISSUE TITLE
Chat Text Entry allows 127 characters but only outputs 126 when sent back to client.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#1615]
Simple minor bug.

As said, type out 127 chars and notice the last one is missing.

Input in default chat box:
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 1234567

Output: Acecool: 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456

**Comment by DaaOtt** [comment]
:+1:
