### ISSUE TITLE
util.TraceEntity doesn't take the entity's angles into account

### ISSUE THREAD

**Issue by ottworks** [Facepunch/garrysmod-issues#1617]
```
local function entvalid(trace)
    local ent = trace.Entity
    if trace.Hit then
        if trace.HitWorld then
            return true
        end
        if IsValid(ent) then
            if ent:GetClass() == "prop_physics" then
                return true
            end
        end
    end
end
```

In my SWEP code...

```
local tr = util.TraceEntity({
    start = ent:GetPos(),
    endpos = ent:GetPos(), 
    filter = filter,
    mask = MASK_SHOT,
    }, 
ent)
if not entvalid(tr) then
    PrintTable(tr)
    obj:EnableMotion(true)
    obj:Wake()
end
```

Result:
https://www.youtube.com/watch?v=U65xXY9Ker8

This pretty much makes util.TraceEntity useless.

**Comment by robotboy655** [comment]
This is pretty much how Source Engine has it, I don't think you will ever see a fix for this. Same goes for TraceHull.

**Comment by Kefta** [comment]
Yeah, Source just wasn't built to have rotatable hulls - a series of TraceLines is the closest you're going to get with the current functionality. Perhaps a new trace function that traces a rotated box/OBB could be possible.
