### ISSUE TITLE
util.DecalEx doesn't alter scale.

### ISSUE THREAD

**Issue by EthanTheGreat** [Facepunch/garrysmod-issues#1624]
![Wow](https://dl.dropboxusercontent.com/u/17839069/C_227.png)

Code:
util.DecalEx( self.SkidMaterial, Entity( 0 ), gtFL.HitPos, gtFL.HitNormal, Color( 255, 255, 255, 255 ), 5, 5, 0 )

Should be 5x5 but instead it's the texture's default scale which is 64x64.

I plan on coming up with something better anyway for the skid marks.

**Comment by Bacon-Man** [comment]
Hoping for a fix on this. I've tried 32x32 and even 2048x2048. There is no notable difference, even when placing the decal on world vs entity. Same fixed size.

**Comment by EthanTheGreat** [comment]
Bump!!!! The hacky alternative to creating skid-marks is using Imesh which is super laggy.

**Comment by xaviergmail** [comment]
+1

**Comment by DrVrej** [comment]
This has been a problem for a very long time, a fix for it would be great, so +1

**Comment by Cpt-Hazama** [comment]
I support +1

**Comment by robotboy655** [comment]
![bleh](http://i.imgur.com/QnOpqhX.jpg)

I looked into it and I don't think it's possible to properly fix it to use X and Y scales, but I can make it to take a scale value and have it scale both width and height, but even then its sort of weird, as shown on the screenshot above.

**Comment by DrVrej** [comment]
Better than nothing though, I would say keep it

**Comment by Mista-Epic** [comment]
That doesn't do anything, it keeps the same size. How should I be using this?

**Comment by Kefta** [comment]
@robotboy655 hasn't made the change, yet.

**Comment by Mista-Epic** [comment]
Ah, thanks.

**Comment by Bacon-Man** [comment]
@robotboy655 can you please give us an update on this issue?

**Comment by robotboy655** [comment]
I had another look and I am pretty sure Source's decal system simply doesn't have the ability to change the decal scales on a single axis. I guess I will just make the what was scaleX argument to just scale, like in the image above.

**Comment by robotboy655** [comment]
Fixed almost completely. The scale works as you'd expect, 2 = 2x size, 0.1 = 0.1scale.
Known problems not resolved yet:
* Doesn't work on entities with brush models
* Huge decals don't properly stick on maps, they may get cutoff by other faces, not sure if this is something fixable.
* Any issues of util.Decal will apply to util.DecalEx
