### ISSUE TITLE
Gmod crashing while playing DarkRP

### ISSUE THREAD

**Issue by 69** [Facepunch/garrysmod-issues#1627]
Sometimes, it just randomly drops without any reason at any given time. It is really annoying. 
[Here's a view of the report](http://dumps.metastruct.uk.to/dumper.py?dump=hl2_140713_crash_2014_11_29T10_54_31C0.mdmp)
[Here is the download link of the report](http://a.pomf.se/fujrqq.mdmp)

**Comment by thedarkassassin30** [comment]
I CANT EVEN SHOOT A GUN WITH OUT IT CRASHING AND IF IM NEAR ANYONE IT CRASHES JUST LIKE JAMM0US SAID IT CRASHES FOR NO REASON!!!!!!!!!!!!!!!!
