### ISSUE TITLE
Entity:GetMaterials() causes stutter

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#1637]
This function: http://wiki.garrysmod.com/page/Entity/GetMaterials causes a slight freeze that lasts for a second, similar to the one experienced when caching a model, however it happens every time the function is called. I have experienced this on both the normal and dev version of garrysmod and the reason this bugs me is because it's the only way to reliably get the index of a material in order to use the upcoming SetSubMaterial() function, as the wiki page suggests.

http://wiki.garrysmod.com/page/Entity/SetSubMaterial

For now I've made a large table of the materials that are used on the models I'm working on, but this really limits the functionality of the new Sub material functions.

**Comment by robotboy655** [comment]
Cannot seem to reproduce anymore, maybe its fixed since this report. Do tell if that is not the case.
