### ISSUE TITLE
OS X dev branch broken if required font is in a subdirectory (FT_New_Memory_Face failed. font:Arial error:85)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#1638]
I can no longer launch the GMod dev branch on OS X. It returns this engine error:

> FT_New_Memory_Face failed. font:Arial error:85

While it doesn't seem to be affecting _every_ OS X user (worked on my laptop but not my desktop), it appears to still be affecting many and it only happened after the introduction of FreeType in the dev branch so it should be fixed before it goes live. [Some people have already started complaining about the bug even though it's only on the dev branch so far.](http://steamcommunity.com/app/4000/discussions/1/619568074766590547/)

It's possible that Linux could be affected too. The linked discussion doesn't mention OS so it could easily be affecting Linux too. I however have not been able to confirm/reproduce this yet.

As a further note, this is NOT Yosemite specific (the latest version of OS X). I'm experiencing this on Mavericks (the previous version that was first released last year). This bug likely happens on both.

**Comment by Bo98** [comment]
Fixed.

**Comment by skeleton432** [comment]
I Am Really Confused With That Fix, First Of All, I Dont Understand what i need to move into a new subdirectory, if i go into library/fonts, that folder is empty, please help me

**Comment by skeleton432** [comment]
and secondly i am not on the dev branch, gmod released a new update 20 minutes ago and i get that error although im not using the dev branch, im on a mac.

**Comment by skeleton432** [comment]
nevermind

**Comment by Kanebotz1** [comment]
I am having a similar problem, except mine is a Tahoma error, not an arial error

**Comment by Kanebotz1** [comment]
But i tried the steps above and it didnt work

**Comment by Bo98** [comment]
The steps were not a fix but steps for reproduction.

Could you open the Font Book application and tell me if Tahoma is there?

**Comment by Kanebotz1** [comment]
G'day Bo, Yes there is a Tahoma in there but it has a Yellow Triangle
warning which says there are multiple copies.
Hope that can help you help me.

Best Regards,
Kanebotz1

**Comment by Bo98** [comment]
There should be a "Resolve Automatically" button when you select the font. See if that works.

**Comment by Kanebotz1** [comment]
G'day Bo,
I've tried to Resolve the font problem with the 'resolve duplicates' button
but Gmod still isn't working.
Something to note is that i am running 10.6.8 (Fair bit older)

Best Regards,
Kanebotz1

**Comment by Bo98** [comment]
If you click the arrow to the left of Tahoma, what list does it give and which of them are marked as duplicates and, if any, are marked as "Off"?

**Comment by Kanebotz1** [comment]
Here is what shows up on the font book.

Best Regards,
Kanebotz1

**Comment by Bo98** [comment]
I'm assuming you sent it as an attachment which GitHub doesn't seem to support through email. Could you upload it to an image sharing site like Imgur and post the link?

**Comment by Kanebotz1** [comment]
http://imgur.com/HhU1oaP,6LNsWK5

http://imgur.com/HhU1oaP,6LNsWK5#1

**Comment by Bo98** [comment]
Could you select "Regular", click the info icon in the top left of the window, and show me the output given in the right pane? It's possible that GMod is missing a font install path.

I'm assuming Font Book hasn't changed too much since 10.6.8 here.

**Comment by Kanebotz1** [comment]
Here you go

http://imgur.com/fc2GotP
