### ISSUE TITLE
Gmod is not launching

### ISSUE THREAD

**Issue by DerpyF4N** [Facepunch/garrysmod-issues#1650]
When i trying to launch gmod hl2.exe is crashing... 
Here is .mdmp

Microsoft (R) Windows Debugger Version 6.3.9600.17200 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [D:\Program Files (x86)\Steam\SteamApps\common\GarrysMod\hl2_140713_crash_2014_12_13T19_31_4C0.mdmp]
Comment: 'Sys_Error( Steam Error: No SteamUser.
- Make sure that Steam is up to date.
- Try restarting your PC.
- Try Garry's Mod -> Delete Local Content

Please let me know if you solve this bug! )
Uptime( 12.689843 )

Memory
memusage( 48 % )
totalPhysical Mb(4035.93)
freePhysical Mb(2072.22)
totalPaging Mb(8070.05)
freePaging Mb(5849.17)
totalVirtualMem Mb(4095.88)
freeVirtualMem Mb(3453.88)
extendedVirtualFree Mb(0.00)

Process Memory
WorkingSetSize Mb(79.18)
QuotaPagedPoolUsage Mb(0.41)
QuotaNonPagedPoolUsage: Mb(0.04)
PagefileUsage: Mb(89.94)

Paged Pool
prev PP PAGES: used: 0, free 0
final PP PAGES: used: 0, free 0
memallocfail? = 0
Active: inactive SpawnCount 0 MapLoad Count 0
Error count 0, end demo 0, abort count 0

ConVars (non-default)

var value   default
mat_colorcorrection
    '1' '0'
r_fastzreject
    '1' '0'
r_overlayfademin
    '1750' '1750.0f'
r_overlayfademax
    '2000' '2000.0f'
datacachesize
    '256' '64'
mat_forcemanagedtextureintohardware
    '0' '1'
mat_supportflashlight
    '1' '-1'
mat_dxlevel
    '110' '0'
mat_trilinear
    '1' '0'
mat_parallaxmap
    '0' '1'
mat_slopescaledepthbias_normal
    '0' '0.0f'
mat_depthbias_normal
    '0' '0.0f'
r_shadowrendertotexture
    '1' '0'
r_waterforceexpensive
    '1' '0'
mat_motion_blur_enabled
    '0' '1'
joy_xcontroller_found
    '0' '1'
mat_supports_d3d9ex
    '1' '0'

Console History (reversed)

1(0.905643):  Steam Error: No SteamUser.
- Make sure that Steam is up to date.
- Try restarting your PC.
- Try Garry's Mod -> Delete Local Content

Please let me know if you solve this bug!'
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: **\* Invalid ***

---
- Symbol loading may be unreliable without a symbol search path.           *
- Use .symfix to have the debugger choose a symbol path.                   *
- After setting your symbol path, use .reload to refresh symbol locations. *
  ****************************************************************************
  Executable search path is: 
  Windows 7 Version 7601 (Service Pack 1) MP (4 procs) Free x86 compatible
  Product: WinNt, suite: SingleUserTS
  Machine Name:
  Debug session time: Sat Dec 13 21:31:06.000 2014 (UTC + 2:00)
  System Uptime: not available
  Process Uptime: 0 days 0:00:17.000
  ................................................................
  ............................................................
  This dump file has an exception of interest stored in it.
  The stored exception information can be accessed via .ecxr.
  (12bc.5dc): Unknown exception - code 00000000 (first/second chance not available)
  **\* ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
  eax=00000000 ebx=00000000 ecx=00000031 edx=0333e429 esi=00000540 edi=20359819
  eip=77d10c42 esp=00328394 ebp=003283a4 iopl=0         nv up ei pl zr na pe nc
  cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00200246
  ntdll!NtGetContextThread+0x12:
  77d10c42 83c404          add     esp,4

**Comment by casadesteve** [comment]
I did all these but it's not starting. It started one day when I downloaded a map pack. I then unsubscribed all of my subscriptions and it still won't work
