### ISSUE TITLE
GMod downloads map from FastDL even after downloading it from workshop.

### ISSUE THREAD

**Issue by VigiFyre** [Facepunch/garrysmod-issues#1660]
1. resource.AddWorkshop a map.
2. Client connects to server.
3. Client downloads the map from workshop.
4. Clients downloads same map again from FastDL.

Thing is, if map is missing on FastDL, client will continue without problem, so map does mount from workshop addon.
So, what i'm asking for is: before downloading maps (or even any files, but most importantly maps) from FastDL, check if it was already downloaded from workshop.

Why won't i just remove map from FastDL:
1. I don't want to confuse players, why is map being downloaded every time they join.
2. I want map to be available on FastDL for those who have problems downloading from workshop.

**Comment by robotboy655** [comment]
This is kind of unavoidable because we only refresh the file system after all downloads are finished, refreshing it after every file or after downloading all workshop addons can cause additional instability and will increase loading times.

**Comment by TeddiO** [comment]
I know this hasn't been touched on for a while however would the solution to have the workshop stuff loaded and mounted first before FastDL starts not be viable at all?
Okay it's a little more time, but it's arguably less time than if a person (down)loads workshop content and then has to download the FastDL content as well.

**Comment by robotboy655** [comment]
Should be fixed in Dev. The code to guard against this already existed, but it didn't account for .bz2 files

**Comment by kevdaawsome** [comment]
poggers
