### ISSUE TITLE
Server crash after zombie npc kills bot

### ISSUE THREAD

**Issue by mario713** [Facepunch/garrysmod-issues#1662]
We were trying zombie npc spawned by Q to be killed by bot spawned by command !bot from ulx mod but bot was just standing and when zombie was killing him the whole server was crashing.

ULX - http://ulyssesmod.net/
Module for ULX which have !bot command - https://github.com/YVL-/Custom-ULX-Commands/blob/master/CustomCommands/lua/ulx/modules/sh/cc_util.lua

**Comment by Kefta** [comment]
Are you sure this is not a problem with the ULX module? This doesn't happen with a normal zombie NPC.
