### ISSUE TITLE
Matrix poping inside cam.Start3D2D

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#1663]
Calling cam.PushModelMatrix and cam.PopModelMatrix inside cam.Start3D2D broke.
Example:
![image](https://cloud.githubusercontent.com/assets/4114136/5509808/3811e722-87bc-11e4-8ef0-604214d0c988.png)

```
function draw.TextRotated( text, x, y, color, font, ang )
    render.PushFilterMag( TEXFILTER.ANISOTROPIC )
    render.PushFilterMin( TEXFILTER.ANISOTROPIC )
    surface.SetFont( font )
    surface.SetTextColor( color )
    surface.SetTextPos( 0, 0 )
    local textWidth, textHeight = surface.GetTextSize( text )
    local rad = -math.rad( ang )
    local halvedPi = math.pi / 2
    x = x - ( math.sin( rad + halvedPi ) * textWidth / 2 + math.sin( rad ) * textHeight / 2 )
    y = y - ( math.cos( rad + halvedPi ) * textWidth / 2 + math.cos( rad ) * textHeight / 2 )
    local m = Matrix()
    m:SetAngles( Angle( 0, ang, 0 ) )
    m:SetTranslation( Vector( x, y, 0 ) )
    cam.PushModelMatrix( m )
        surface.DrawText( text )
    cam.PopModelMatrix()
    render.PopFilterMag()
    render.PopFilterMin()
end

---------- Entity Draw ----------
cam.Start3D2D( self:LocalToWorld(Vector(0,0,14.6)), self:GetAngles(), 0.08 )
    -- Table ring --
    local size = 630
    local C = Color(0,255,125)
    surface.SetMaterial(Mat[1])
    surface.SetDrawColor(C)
    surface.DrawTexturedRect(-size*n/2,-size*n/2,size*n,size*n)

    -- Text --
    surface.SetTextColor(C)
    surface.SetTextPos(0,0)
    surface.SetFont("CardFontData")

    surface.DrawText("I work")
    draw.TextRotated("But I don't",0,0,Color(255,255,255),"CardFontData",90)

cam.End3D2D()
```

**Comment by Nak2** [comment]
I've tried in many ways to render cam.PopModelMatrix inside a 3D render-environment but with no luck.
I tried the beta- and live-version of the game and tried to render it in ENT:Draw and outside in render.hooks.
Something breaks the VMatrix rendering when its not inside a 2D-environment.

**Comment by robotboy655** [comment]
Does it work properly in live version?

**Comment by Nak2** [comment]
No. I got a suspicion that cam.start3d2d pushes a world matrix since it renders outside the cam.Start3D2D.

**Comment by robotboy655** [comment]
Well, than this is not a regression.

**Comment by Nak2** [comment]
Sorry, accidentally pressed the button when a window closed.
Short story:
I'm sure cam.PopModelMatrix pushes to a world matrix since it renders outside the target render.
HUDPaint - > even with cam.Start3D it renders on the screen as 2D
ENT:Draw / 3D-render - > renders at 0,0,0 and ignores the given scale

**Comment by Earu** [comment]
This bug still exists on all current Gmod branches, it would be great if it was fixed. As stated above the model matrices pushed into a 3D context seem to completely mess up where things are gonna draw, their scales and angles. Is `cam.Start3D2D` pushing a matrix ?

You can reproduce this issue fairly easily, start a 2D context inside a 3D one using for instance `cam.Start3D2D` and push a `Matrix` object using `cam.PushModelMatrix`.

**Comment by thegrb93** [comment]
Indeed cam.PushModelMatrix will replace the matrix used by cam.Start3D2D. It's bad enough cam.PushModelMatrix replaces matrices instead of multiplying, but not being able to cam.GetModelMatrix makes it impossible to do it ourselves.

**Comment by robotboy655** [comment]
I can add `cam.GetModelMatrix` and with minor changes to the function above you can make it work:
![yuy](https://user-images.githubusercontent.com/3299036/71827177-5bbd6800-30a8-11ea-8df5-aea5cb33f13f.gif)

Making changes to cam.PushModelMatrix can affect other addons in unexpected ways (and potentially the whole engine itself) so I probably won't be looking into that. Push/Pop matrix stuff are direct bindings to in-engine stuff.

**Comment by robotboy655** [comment]
Alternatively I could add an optional argument to `PushModelMatrix` that will get current matrix and push the multiplied result of current and input matrices instead.

Or I could do both.

**Comment by Earu** [comment]
Both would be incredibly helpful I'm sure!

**Comment by robotboy655** [comment]
Added both, but it will be a short while before they are on Dev, build server's having a problem
