### ISSUE TITLE
Source Recorder doesn't record any activity with the Physgun

### ISSUE THREAD

**Issue by Ankit-Maity** [Facepunch/garrysmod-issues#1709]
First, I record a demo using record "name". Then I stop it using another command. Fine till now.
Then, I start recording a movie (with h264 in a .mov container) and play the demo (so that it's unlaggy and everything is prerendered) and I realize that the spawn menu, weapon change and stuff aren't there in the demo. This is very problematic, cuz I was recording a montage for my new YouTube channel. Any fixes?

**Comment by robotboy655** [comment]
Any gui actions are not recorded in demos and will not be.
