### ISSUE TITLE
All ragdolls/props gone on previously working save

### ISSUE THREAD

**Issue by ToastyChase** [Facepunch/garrysmod-issues#1710]
I had put atleast 10 hours into making a big scene, without changing anything or adding any addons the saves no longer work correctly. Whenever I load them up everything I put into the map is  now gone. I tried completely wiping all my addons, re-installing the game and re adding them but still nothing. Even with the save that I uploaded.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

Don't forget to actually include the save file, the map you are trying to load it on and console log after trying to load the save.

**Comment by ToastyChase** [comment]
If I'm  not mistaken there is literally nothing in that fucking forum. So if someone could kindly if I did or did not waste 10 hours of my life that would be very kind.

**Comment by robotboy655** [comment]
Log in first.
