### ISSUE TITLE
The game models do this thing

### ISSUE THREAD

**Issue by Heeyay** [Facepunch/garrysmod-issues#1713]
![untitled](https://cloud.githubusercontent.com/assets/10367445/5593575/862eba96-91dc-11e4-8526-3d28904e372e.png)
This is what happens to any of the game models (ragdolls and npcs even player models) what can I do  to solve this? The game runs smoothly, all the props are normal and have their usual textures but it's only the game models that does this

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
