### ISSUE TITLE
Game crashes when loading singleplayer map

### ISSUE THREAD

**Issue by vovapopok142** [Facepunch/garrysmod-issues#1715]
Please help i cant load singleplayer in gmod i've tried everything 

This is my console commends

Adding Filesystem Addon 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\addons\hl2 ep2 content addon'
Adding Filesystem Addon 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\addons\spacebuild-master'
Adding Filesystem Addon 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\addons\tnb'
Initializing Awesomium..
No Kinect SDK
Unknown command "cl_thirdperson"
Unknown command "hud_showemptyweaponslots"
Unknown command "sv_backspeed"
Not playing a local game.
Couldn't mount addon - couldn't find file addons/cw_city_life_142861224.gma
Addons have changes - remounting
Download Finished
Extraction failed.. Oh oh! (C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/cw_city_life_142861224.gma)

Please help

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
