### ISSUE TITLE
Client tries to connect to wrong port from steam:// link.

### ISSUE THREAD

**Issue by suchipi** [Facepunch/garrysmod-issues#1716]
If running a server on a non-default port, eg `example.com:3333`, clicking a `steam://connect/example.com:3333` link will show `example.com:3333` in the game info dialog, but then the Garry's Mod client tries to connect to `example.com:27015` instead.

**Comment by robotboy655** [comment]
Doesn't happen, tried with 212.83.151.103:27200.

In either case, this is about Steam, not the game client.

**Comment by suchipi** [comment]
Isn't working for me with suchipi.com:49234.
I reported it here because the Steam Game Info dialog that appears when the server is unreachable shows the wrong port, but gmod connects to 27015, which leads me to believe it's happening within gmod instead of steam.

**Comment by robotboy655** [comment]
As you can see on this picture:
http://i.imgur.com/MU6oVFv.png

When trying to connect there without GMod launched, Steam gives it incorrect port already. The image is a crash log after starting the game by trying to connect to the server.

**Comment by suchipi** [comment]
Alright, my apologies. Thanks
