### ISSUE TITLE
Garry's mod crashes when loading Left 4 dead 1-2 maps and DoD maps

### ISSUE THREAD

**Issue by FaceSlap** [Facepunch/garrysmod-issues#1717]
Sometimes i try to load one map of L4D or L4D2 and he crashes!
I Really want play in these maps to make montages D:
Even DoD maps :8ball:

**Comment by robotboy655** [comment]
L4D2 maps are incompatible with Garry's Mod, you can't load them at all.
L4D maps should be compatible to some extent, but I may be wrong.
DoD:S maps should be 100% compatible, try without your addons.

Get help @ http://facepunch.com/forums/16
