### ISSUE TITLE
Unable to remove point_spotlight

### ISSUE THREAD

**Issue by RealDopey** [Facepunch/garrysmod-issues#1719]
[CODE]
if self.headlight and self.headlight:IsValid() then
	print("removing") -- runs
	self.headlight:Input("LightOff", self.headlight, self.headlight, 1) -- turns off the light
	self.headlight:Input("Kill", self.headlight, self.headlight, 1) -- does nothing
	self.headlight:Remove() -- does nothing
	print(tostring(self.headlight)) -- prints Entity [148][point_spotlight]
end
[/CODE]

Parenting the entity to another has a weird effect. The initial light animation does not move at all (just remains in midair where it spawned), but the actual dynamic light does move. If I point the parent at a wall, it lights up as if the light is also pointing at it. Neither is removed by :Remove() or :Input("Kill").

EDIT:
Sorry, code brackets don't seem to work.

**Comment by robotboy655** [comment]
Unless you can provide the code you used to create the entity I am not going to do anything about this. This entity uses, if I recall correctly from Hammer, 3 entities for different purposes.
