### ISSUE TITLE
(Gmod Server) Please help me with this....I NEED YOUR HELP GUYS

### ISSUE THREAD

**Issue by McSkizmo** [Facepunch/garrysmod-issues#1722]
There is not problem with Gmod its actually about the servers. When me or my friend trying to join each other's server after we didnt did cheked the Local Server and after we did 4 people, it is telling us that the server is not responding, the funny thing is that my other friend doing the same thing that we did and when HE IS OPENING SERVER ITS WORKING BY CILCKING JOIN AT STEAM.
I need your help please, we tryed Hamachi at consul...Doest Working

**Comment by robotboy655** [comment]
This is NOT A PLACE TO GET HELP. Get help @ http://facepunch.com/forums/16

**Comment by neico** [comment]
You know, this starting to get really annoying, how do these people even get here?

**Comment by robotboy655** [comment]
I have no idea. Probably Google. Steam sales are over though, so they should stop or at least reduce.
