### ISSUE TITLE
Black Muzzle Flash

### ISSUE THREAD

**Issue by MrBuBu** [Facepunch/garrysmod-issues#1724]
Hello,

about 2 weeks ago I got this black muzzle flash and I ant fix it!!!!
Please help
![unbenannt](https://cloud.githubusercontent.com/assets/10398991/5611548/3c4fb29c-94c8-11e4-9bc7-6cf4b6c5f99a.jpg)

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
