### ISSUE TITLE
Awesomium needs to be updated

### ISSUE THREAD

**Issue by xghozt** [Facepunch/garrysmod-issues#1726]
Awesomium seems to be behind in gmod, as it's currently running on 1.7.2.2 (I checked the process) and the current one at the time of posting this is 1.7.5.0. As far as I know, or as far as I've been able to research, there are some outstanding text rendering issues present in the earlier Awesomium versions, which I've had the pleasure of discovering the long and hard way..

![image](https://cloud.githubusercontent.com/assets/1783986/5622607/e17725fc-9513-11e4-91c7-5c95657935e0.png)

http://answers.awesomium.com/questions/87/awesomium-font-anti-aliasing-not-working.html
http://answers.awesomium.com/questions/4025/font-rendering-on-transparent-backgrounds.html

**Comment by Bo98** [comment]
Should fix #86 too. Would be good to have Awesomium updated before the next update is pushed (Linux peeps won't be happy if it isn't!).

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/398
