### ISSUE TITLE
achievements.IncBaddies() and others don't work.

### ISSUE THREAD

**Issue by Egor305** [Facepunch/garrysmod-issues#1729]
This one is simmilar to #1018.
Following functions do not work:
```lua
achievements.IncBaddies()
achievements.IncBystander()
achievements.IncGoodies()
```

Example of code which is affected by bug:
```lua
print("---")
print(achievements.GetCount(8).."/"..achievements.GetGoal(8))
print("Got another one!")
achievements.IncBaddies()
print(achievements.GetCount(8).."/"..achievements.GetGoal(8))
print("---")
```
(Note: 8 is id for War Zone)
Example output:
```
---
87/1000
Got another one!
87/1000
---
```

I'm on dev branch, and killing stuff the normal way works.

**Comment by robotboy655** [comment]
This is already fixed.

**Comment by Egor305** [comment]
Ok. Just wanna make sure, by "already fixed" you mean "fixed in next dev release", right?

**Comment by robotboy655** [comment]
No, by already fixed I mean it is fixed in the dev branch. It will not count if you simply try to call the function, you actually have to kill the NPCs.

**Comment by Egor305** [comment]
Ok, that makes sense. Thanks. Though, documentation on [wiki](http://wiki.garrysmod.com/page/achievements/IncBaddies) says the opposite.

**Comment by Bo98** [comment]
Oh, if the functions are now obsolete, you should probably remove:
https://github.com/garrynewman/garrysmod/blob/28b7be5cda7fdde1a19c59d43408dcb2df357fd8/garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua#L92-L107

**Comment by robotboy655** [comment]
You are obsolete. :v
