### ISSUE TITLE
Console text hard to read in OS X dev branch

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#1732]
![snapshot0005](https://cloud.githubusercontent.com/assets/1190754/5686061/b862d806-9837-11e4-8a93-396ffac63648.jpg)

Note the the odd character widths (you can't even see a lowercase L).

The console does print

```
m_face->glyph->bitmap.width is 0 for ch:108 verdana
```

I don't know whether this is related though.

**Comment by Egor305** [comment]
FYI, 108 is decimal codepoint for lowercase L in ASCII, so it _is_ related.

**Comment by GranPC** [comment]
Hey, can you look into this with the latest scheme update?

**Comment by Bo98** [comment]
Unfortunately still happening with today's update.

And no problem! :)

**Comment by GranPC** [comment]
Oh hang on I think I gave @UnderscoreKilburn the wrong files, I'll get back to you on this in a bit.

**Comment by UnderscoreKilburn** [comment]
Oh hey, can you give it a try now?

**Comment by Bo98** [comment]
The latest commit hasn't come through Steam yet but I will test it when it is.

**Comment by Bo98** [comment]
Is the build server stuck again or something? The update doesn't seem to have been pushed yet.

**Comment by GranPC** [comment]
Looks like it. Can you try downloading it from here and putting it in your resource folder: https://peniscorp.com/SourceScheme.res

**Comment by Bo98** [comment]
![snapshot0006](https://cloud.githubusercontent.com/assets/1190754/5754139/70ea9834-9c8c-11e4-9bc4-8fac899b744b.jpg)

Looks fixed!

The build servers seems to be working too again, for now.

Thanks!

**Comment by GranPC** [comment]
Fuck yes. How's freetype looking now in third party crap? Is it consistent
with Windows?

**Comment by Bo98** [comment]
Because of #1725, I'm not completely sure yet. But from what I've seen so far, it certainly looks promising!

I plan on doing comparison screenshots when #1725 is fixed.

**Comment by GranPC** [comment]
I was gonna do comparison screenies and post them but I guess I can
continue to be a lazy fuck, thanks!

**Comment by Bo98** [comment]
Haha.

Tbh I haven't started Windows in about a year so I hope it still works.
