### ISSUE TITLE
Clientside files are not sent except on join through AddCSLuaFile on GNU/Linux

### ISSUE THREAD

**Issue by anotera** [Facepunch/garrysmod-issues#1733]
I started a thread: http://facepunch.com/showthread.php?t=1445215. Tested with the GNU/Linux client and the GNU/Linux dedicated server, on Gentoo GNU/Linux. If you check the date modified on the clients cache/lua, files are only modified every time you join the server, and files are not sent if you call AddCSLuaFile after init. The current workaround is to network the files via the net.* library.

**Comment by robotboy655** [comment]
They are not supposed to be send after the server start, especially into the Lua cache.
