### ISSUE TITLE
downloading demos .....

### ISSUE THREAD

**Issue by salem2001** [Facepunch/garrysmod-issues#1734]
hello. when i download demo from the work shop

it does not work  i cant find it on the demo folder

pls help me

**Comment by robotboy655** [comment]
It's not designed to work like that

**Comment by salem2001** [comment]
how i can use demos and download it ? in garry's mod

**Comment by robotboy655** [comment]
You can't download demos, saves and dupes. The plan is to instead of subscriptions add them to favorites and be able to browse the favorites from the spawnmenu/main menu.
