### ISSUE TITLE
Metro Police (npc_metropolice) isn't considered an enemy by IsEnemyEntityName.

### ISSUE THREAD

**Issue by Egor305** [Facepunch/garrysmod-issues#1735]
That is, you get Innocent Bystander instead of War Zone when you kill Metro Police.

I'm pretty sure that they should be enemies, as they KOS you.

**Comment by Noiwex** [comment]
They aren't really enemies in the beginning of Half-Life 2.

**Comment by neico** [comment]
They are only being suppressed by a env_global entity in the beginning:

https://developer.valvesoftware.com/wiki/Env_global
