### ISSUE TITLE
[Odd behaviour] Physics gun blocks mwheelup/down keybinds when it (kindof) shouldn't.

### ISSUE THREAD

**Issue by Egor305** [Facepunch/garrysmod-issues#1737]
When you shoot physics gun, you can't use mouse wheel. It makes sense when you hold stuff, as scrolling moves prop on back-and-forward axis, and activating (default) keybind would instantly switch weapons, but the thing is, when you don't hold anything (i.e. shoot at world) scrolling does nothing at all, so, I think, it's more logical to not block keybinds when you don't hold anything.

(tl;dr - I want to ABH (bunny hop) with my mousewheel while shooting gravity gun in all the random directions for sweg)

**Comment by robotboy655** [comment]
You mean the Physics Gun?

**Comment by Egor305** [comment]
Yeah, right.

**Comment by robotboy655** [comment]
This isn't really "odd behavior", it does what it should do. There's no point in changing it ( just for one person ) so you can jump around with mouse wheel and shoot the beam for no reason.

**Comment by Egor305** [comment]
What I ment by "odd behavior" is that it's a bit confusing (especially the fact that you apparantly can "override" the keybindings like that), and should be considered to be changed. I guess it isn't really neccessary to change it - normal person wouldn't scroll mwheel while holding +attack down.
