### ISSUE TITLE
Addons have vanished and cant download anything from the workshop?

### ISSUE THREAD

**Issue by Dan8you** [Facepunch/garrysmod-issues#1741]
A few months ago out of no where my addons just vanished and it does not let me download other addons, if I click 'install' it just makes the noise and does nothing. I have re-installed Garrys mod many times and cleared all the files of Garrys mod on my computer and re-installed it. Also i have validated it before, but still nothing seems to work.

Please can you help :)

**Comment by robotboy655** [comment]
It's a problem with Steam and also happens in L4D2, so nothing we can do about it.

**Comment by Dan8you** [comment]
So my garrys mod is just worthless now?

**Comment by robotboy655** [comment]
Contact Steam support and complain to them why the workshop doesn't work for you.

**Comment by Dan8you** [comment]
okay cheers anyway :)
