### ISSUE TITLE
Speed Hack Bug thats affecting my Gameplay

### ISSUE THREAD

**Issue by Eaze22** [Facepunch/garrysmod-issues#1742]
Hey there, So Ive recently Installed Garrys Mod after a few years after getting a new PC but Im having an issue whenever I join a server ( This Problem is the same on CS:Source ) where im essentially speed hacking.. I seem to move at twice the speed as everyone else, and my in game clock in matches ticks down but bugs out like an example would be Its at 6:30 time but it goes down to 6:29 then straight back up to 6:30 then back to 6:29 then 6:28 and back up to 6:29.. Its really wierd and Ive tried uninstalling some software that seems to collide with the game such as Norton Security and even uninstalled both source and Gmod 3 times and tried validating the integrity the files and nothing seems to fix it. If anyone has any solutions it would be appreciated!

**Comment by robotboy655** [comment]
Remove your shitty hacks kid.

On a more serious note, this is not a place to get help. You can get help @ http://facepunch.com/forums/16
