### ISSUE TITLE
Weapon has endless trails

### ISSUE THREAD

**Issue by Dewd1979** [Facepunch/garrysmod-issues#1744]
Hi, I'm very new to this, and I checked the msg board first but didn't see anything that fit this description.
I just downloaded GMOD a couple of days ago but the issue I'm having is that whatever weapon I choose has this almost infinite trail on my screen, which i can barely see past. (depending on the weapon)
Mind you I have a very shitty computer, using just direct X with no video card, 2 Gigs of Ram and its just as slow as a fart. However even when I bump up the video settings its not really lagging. 
I've also tried dumbing the the graphics to next to nothing but this damn weapon trail won't go away.
Any idea what I an do to fix this please?
![trail](https://cloud.githubusercontent.com/assets/10574011/5789216/b80536dc-9e1e-11e4-9c29-81912308ebdb.jpg)

**Comment by robotboy655** [comment]
Very shitty computer is your problem.
