### ISSUE TITLE
Joint tool bug

### ISSUE THREAD

**Issue by 02500marc** [Facepunch/garrysmod-issues#1749]
Hi! I bought G mod recently and when in try to use the joint tool wich allows me to stick things together don't seem to work. Indeed, when I select it from my toolbar, it displays me a "#tool.joint.name" text, as you can see on the photo. I'd be happy if you can help me because, without this tool, my gameplay experience isn't full, and it's one of the most important tool of the game. As you may saw, I'm french so my english isn't perfect. Thanks!! :D
![2015-01-20_00002](https://cloud.githubusercontent.com/assets/10134578/5823541/db7504a0-a0dd-11e4-877b-5e11c06c7913.jpg)

**Comment by robotboy655** [comment]
Report this to the addon author, not here.

**Comment by 02500marc** [comment]
But this is not an addon?

**Comment by robotboy655** [comment]
Joint tool does not come with Garry's Mod by default.
