### ISSUE TITLE
Console message: Requesting texture value from var "$basetexture" which is not a texture

### ISSUE THREAD

**Issue by Dilbert-JonhonsonThe999th** [Facepunch/garrysmod-issues#1750]
I was just playing around in Gmod, having some fun on ttt_metropolis_v3 (i think) and ttt_roy_the_ship, and randomly got this console message when trying to spawn one of my modded npcs (Kayne And Lynch: Dead Men SNPC'S) and i saw the eyes on the were missing textures, and that some other base hl2 textures had a fade mask that was missing textures? does anyone know what this is?

NOTE: The eye thing happens also with my Black Mesa SNPCS, and i have legal C:SS models and textures from this website: http://kajar9.wix.com/cscheater2

**Comment by robotboy655** [comment]
That is called piracy.
