### ISSUE TITLE
string.gfind doesnt catch '^x' (where x is first letter)

### ISSUE THREAD

**Issue by KrakenZ** [Facepunch/garrysmod-issues#1751]
Same for string.gmatch.
But string.find and string.match catch it.

By the way, what's the difference between gfind and gmatch? they both return the exact same captures.

``` lua
for G1, G2, G3 in string.gfind( "abcde", "^a" ) do
    print( G1, G2, G3 ) -- Wont print anything because string.gfind did not catch anything.
end

print( string.find( "abcde", "^a" ) ) -- Will print "1,1"
```

**Comment by wiox** [comment]
The reason gfind and gmatch work the same is because gfind is deprecated in favor of gmatch. It's as simple as the naming being changed, they are 100% equal.

**Comment by KrakenZ** [comment]
Thought this was an unexpected behaviour; as the POSIX version catches it as expected. Thanks for clearing things up.

**Comment by willox** [comment]
Every verison of Lua I have tested has this behaviour. I'm not sure why you would restrict a gmatch to the beginning/end of a string anyway.
