### ISSUE TITLE
UniqueID extremely slow

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-issues#1755]
Calling UniqueID on a player takes ~10 times longer than calculating the UniqueID using util.CRC (which is half as fast as caching the UniqueID).
This is apparently caused by UniqueID looking up the sv_lan convar each call which is most likely unnecessary.

It should also be noted that this can be used to DoS servers that use UniqueIDs to identify players.

**Comment by neico** [comment]
sv_lan should be cached then as that value only takes effect after a changelevel (or before starting a map) anyays...

The question is if that function is using this file or a custom implementation based on it (which it probably is): https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/tier1/uniqueid.cpp

**Comment by wiox** [comment]
> The question is if that function is using this file or a custom implementation based on it (which it probably is): https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/tier1/uniqueid.cpp

I'm not sure why this is the question

**Comment by neico** [comment]
Well if it is then what he said about sv_lan wouldn't be the case, or do you see it in the file anywhere?

**Comment by wiox** [comment]
It's information available by reverse-engineering the CGMOD_Player::GetUniqueID method.

If you're after other evidence there's always the fact that the following benchmarks would make sense because of it.

```lua
local CRC = util.CRC
local UniqueID = FindMetaTable "Player" . UniqueID
local SteamID = FindMetaTable "Player" . SteamID

local ply = Entity(1)

if not IsValid(ply) then return end



local s = os.clock()

for i = 1, 1e5 do
	CRC( "gm_" .. SteamID(ply) .. "_gm" )
end

print("util.CRC", os.clock() - s)



local s = os.clock()

for i = 1, 1e5 do
	UniqueID(ply)
end

print("ply:UniqueID", os.clock() - s)



local s = os.clock()

for i = 1, 1e5 do
	GetConVarNumber "sv_lan"
end

print("GetConVarNumber", os.clock() - s)
```

```
util.CRC	0.091000000000001
ply:UniqueID	3.27
GetConVarNumber	3.341
```

Notice how similar the execution time for ply:UniqueID and GetConVarNumber is compared to util.CRC.

**Comment by VigiFyre** [comment]
:UniqueID should have never been made. It's slow, useless and makes no sense. Never use it ever.
If you want to convert SteamID to number and backwards, use these:
```lua
function SteamIDToInt32(id)
	local y, z = id:match("STEAM_0:([01]):(%d+)")
	return y and z and y + z * 2 or 0
end
function Int32ToSteamID(id)
	return id == 0 and "" or ("STEAM_0:%d:%d"):format(id % 2, math.floor(id / 2))
end
```

**Comment by Noiwex** [comment]
Similar request https://github.com/Facepunch/garrysmod-requests/issues/264

**Comment by syl0r** [comment]
UniqueID (if implemented correctly) isn't slow. CRC32 is a pretty fast algorithm that can easily handle 250 MiB per second even on older machines (source: http://www.cryptopp.com/benchmarks.html). So calculating it for ~25 bytes takes almost no time (even caching isn't much faster).

I just don't get why garry didn't make it return the steamid32 instead (since it is truly unique). I have scanned through over 14 million steamids and found ~64000 collisions using UniqueID's algorithm'

**Comment by thegrb93** [comment]
That's a bit scary since my admin mod uses unique id.

**Comment by Noiwex** [comment]
Idk why do people keep using uniqueid, it's unreliable as fuck.

**Comment by robotboy655** [comment]
```
util.CRC	0.10399999999998
ply:UniqueID	0.007000000000005
GetConVarNumber	5.522
```

As far as I can tell, it always did cache the result, the only problem I found with it is that it indeed tries to access sv_lan convar every time as you guys pointed out. Should be fixed in next Dev branch update.

**Comment by Noiwex** [comment]
Oh wow, nice. util.GetByUniqueID is fast now?
