### ISSUE TITLE
Game dosen't work with the new DirectX

### ISSUE THREAD

**Issue by Windolian** [Facepunch/garrysmod-issues#1756]
Hey.
I was installed the Windows 10 and it comes with the new DX12
And when i try to play GMOD it says "Direct X is out of date..."

**Comment by robotboy655** [comment]
You need to install DX9 to play the game.

**Comment by Bo98** [comment]
DX should be somewhat backwards compatible unless DX12 is different.

**Comment by robotboy655** [comment]
That error occurs if DX9 .dll file is missing

**Comment by Bo98** [comment]
Is that deliberate?

**Comment by robotboy655** [comment]
Exact info is here: http://support.facepunchstudios.com/kb/articles/26-your-directx-runtime-is-out-of-date

**Comment by robotboy655** [comment]
It is.
