### ISSUE TITLE
Bug: Default resolution of fresh install makes options/quit menu items inaccessible

### ISSUE THREAD

**Issue by chrisgbk** [Facepunch/garrysmod-issues#1757]
See attached image. It's impossible to actually go into the options to change settings ingame. Game defaults to 1440x480, 3:1 ratio(?). Before the garry's mod logo at the top left loads, the rest of the menu is visible for a moment until it gets pushed down. Workaround is to specify window size on commandline. Actual resolution of screen is 1920x1080. Since the resolution is listed in the 4:3 ratio list, it seems like it should be 1440x1080 instead.

![res](https://cloud.githubusercontent.com/assets/8484793/5891860/18cd53a2-a467-11e4-8e87-d89323b99516.png)

This is from a just-installed copy of garry's mod, on a fresh install of windows - had the same bug happen on my last computer a year or so ago, just never reported it.

**Comment by cinder1992** [comment]
Try starting the game with the following launch options:

-w 1920 -h 1080

then set the correct options in the options menu and remove the launch options.

**Comment by chrisgbk** [comment]
I already have done that, as I noted the workaround is to specify window size on commandline. The point of reporting this issue wasn't to get help fixing it short term, it's to get the problem solved long term.

**Comment by robotboy655** [comment]
Partially addressed this with https://github.com/garrynewman/garrysmod/commit/6b65370d5e320f2e2e24a175b011a385295870de, but I'd still need to find where it decides the default resolution and double check it.
