### ISSUE TITLE
Dropped physguns make the weapon glowing super bright

### ISSUE THREAD

**Issue by Kazaaam** [Facepunch/garrysmod-issues#1758]
I just made a script to drop weapon on death, very basic script so far, but I have a bug with the physgun.

For each dropped physgun on the ground, its glowing sprite (blue glowing light by default) is stacked on the player view instead of the world view physgun model. If I drop 10 times my physgun on a suicide, the glowing becomes very bright (see my screenshot). Picking up all dropped physguns resolve the problem.

![](http://i.imgur.com/9RM4FRR.jpg)

**Comment by robotboy655** [comment]
Will be fixed in next update.
