### ISSUE TITLE
Windows 7 startup problem

### ISSUE THREAD

**Issue by Helpneededplease** [Facepunch/garrysmod-issues#1759]
Whenever I try to loadup Gmod it doesnt start RIGHT away. I tried deleting ALL my addons, maps, mods, ect. yet nothing, I reached into the game files, nothing. Back upped, Updated, changed files NOTHING if anyone has ANY suggestions PLEASE let me know! I love Gmod and its the only game I payed money for ;-;

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
