### ISSUE TITLE
Gmod murder FOV issues

### ISSUE THREAD

**Issue by Evga123** [Facepunch/garrysmod-issues#1762]
So when I play gmod murder and I get the gun the field of view is messed up and when I look in the settings the field of view is normal. Here is a link to the screenshots: http://steamcommunity.com/id/The4701/screenshots/ the gun has a normal fov when in sandbox and as you can tell by screenshots the fov is normal when I am the murderer. Ignore fnaf and gmod elevator screenshots, the one representing this problem are the first 5 of which are murder

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
