### ISSUE TITLE
Ugly menu's/Squished menu's 

### ISSUE THREAD

**Issue by Lxyn** [Facepunch/garrysmod-issues#1763]
Here are some screenshot and my os is Mac OS X Yosemite 10.10.2 [IMG]http://i62.tinypic.com/oau0ps.jpg[/IMG]
[IMG]http://i58.tinypic.com/30dhvk5.jpg[/IMG]

**Comment by robotboy655** [comment]
Put your  screen resolution to be bigger than 800x600.
