### ISSUE TITLE
Altering video settings via cfg doesn't work when using -dxlevel launch-option or mat_dxlevel in +exec cfg file

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#1765]
The highres.cfg and lowres.cfg files execute on the client when I use +exec however when I change the dxlevel the rest of the cfg becomes irrelevant and all video settings are reset instead of loading them...

If dxlevel alters settings, it should be made into a blocking command so the cfg files work without needing to re-exec them when the game opens ( which resets the position of the window too )

**Comment by Acecool** [comment]
Actually, it appears when using mat_dxlevel in a file, it won't process it.

I've found a work-around but it is sloppy... Basically in my autoexec.cfg I set up an alias, hr and lr to exec highres.cfg or lowres.cfg and added +hr and +lr to the bat file, respectively.

It should work without having to re-exec the file via alias..

**Comment by robotboy655** [comment]
I'd say it is intentional.

**Comment by Kefta** [comment]
How so? Forcing your dxlevel shouldn't reset your video presets every time

**Comment by robotboy655** [comment]
1) You shouldn't be forcing your dxlevel
2) Looking at the code, It was definitely intended by Valve to be this way
