### ISSUE TITLE
util.TableToJSON doesn't handle arrays properly

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#1769]
```print(util.TableToJSON({1, 2, 3}))``` prints ```{"1":1,"2":2,"3":3}```. Should print ```[1, 2, 3]```

**Comment by wyozi** [comment]
Also ```util.JSONToTable("[1, 2, 3]")``` duplicates keys.

**Comment by Python1320** [comment]
Pure Lua alternative for the impatient people http://dkolf.de/src/dkjson-lua.fsl/home

**Comment by willox** [comment]
Fixed in the dev branch

**Comment by ZachPL** [comment]
This change appears to cause this issues with tommys TTT damagelog webpage, 
https://github.com/Tommy228/TTTDamagelogs/issues/242
trying to wrap my head around whats changed.

**Comment by robotboy655** [comment]
@ZachPL , This is not a place to moan about/report addons bugs.

**Comment by ZachPL** [comment]
wasnt sure if something was messed up with tabletojson still but its probably something he put in the php code to avoid the issue, sorry

**Comment by robotboy655** [comment]
If you have a suspicion there might be a problem with util.TableToJSON, then first do code checks yourself, and if there is in fact a defect, report it only then.
