### ISSUE TITLE
An addon_uploads folder located in remote takes up all of my Gmod Steam Cloud.

### ISSUE THREAD

**Issue by TheOneAndOnlyALX** [Facepunch/garrysmod-issues#1770]
An addon_uploads folder located in remote takes up all of my Gmod Steam Cloud.

So Im a map maker for GarrysMod, and lately I tried uploading a map to workshop.

I upload using CMD with gmad.exe; gmpublish e.t.c.

At first my map ended up weighing 331 MB (Due to un-optimized custom sound files). I tried uploading it atleast 6 times (This might be important later).
It gave me an error saying that my account ran out of space, So I decided to compress the sounds - the map ended up weighing 144MB.

I then tried uploading again but it still said that my account might ran out of space. Then I got suggested to clean my steam cloud, which I tried but it kept denying access to the remote folder through CMD (I have even launched it through administrator but that doesnt matter in the end).

I opened properties in Gmod and it said that I only have 10 MB left on Gmods Steam Cloud, 0.98 Gbs in storage. I then checked the remote folder and found a folder with a bit an unusual name - addon_uploads. I checked its size and it was 0.98 Gbs..
I opened it and saw 6 .gma files, which names were "1422113257_3683782764" all exactly the same name and even the same size - 168 MB.
One thing is that they have different times of modification:
24.01.2015 19:28
24.01.2015 19:35
24.01.2015 19:49
24.01.2015 20:12
24.01.2015 20:46
24.01.2015 21:14

![capture](https://cloud.githubusercontent.com/assets/10773700/5976603/44f76af8-a8a9-11e4-9f09-7ab69e5e1d7c.JPG)

![capture2](https://cloud.githubusercontent.com/assets/10773700/5976627/87e1ed5c-a8a9-11e4-8502-c923338c9117.JPG)

At that day and time I was making Six attempts to upload my 331 MB un-optimized version of the map.
So did I somehow break steam/gmod uploading a 331 MB map at first?
I really dont know, but to me it seems like a serious glitch.

I even asked a different map maker and he doesnt have that folder at all.

All help would be very appreciated, this is quite an important bug.

Thank you for your attention and help in advance.

**Comment by robotboy655** [comment]
Just delete them. Those are temporary files in process of uploading.

**Comment by TheOneAndOnlyALX** [comment]
I cant delete them, They are stored in steam CLOUD, They get re downloaded

**Comment by robotboy655** [comment]
Try running this tool: https://dl.dropboxusercontent.com/u/10382947/CloudCleanse.7z ( At your own risk )
It is made by @wiox and should clean any unneeded files from Steam Cloud.

**Comment by TheOneAndOnlyALX** [comment]
Still doesnt help, it removes my CFG folder, and I still have 2 more folders there as you can see.

**Comment by wiox** [comment]
Yeah that file only deletes cfg files in case somebody's modified them to be malicious.

**Comment by TheOneAndOnlyALX** [comment]
Yeah, so this bug still isnt solved. And I havent found it anywhere else, so Im guessing I might have broken steam/gmod somehow. I dont know but I really need help. I would clean Steam Cloud a different way which I know using CMD, but as I said it denies permission to the remote folder when I use CMD.
