### ISSUE TITLE
Server Workshop addons force downloads nothing

### ISSUE THREAD

**Issue by mrpotatofactory** [Facepunch/garrysmod-issues#1771]
When downloading addons and then entering the server not materials or models that were said downloading are featured in game as errors. A temporary folder where materials and models are stored would be nice where at the end of the session would automatically delete it's contents.

**Comment by robotboy655** [comment]
Are you saying that resource.AddWorkshop forced workshop addons have no effect on a game server? Because I am pretty sure the models, etc from such addons load properly.
