### ISSUE TITLE
Hands position messed up at respawn with the weapon dropping

### ISSUE THREAD

**Issue by Kazaaam** [Facepunch/garrysmod-issues#1772]
When I drop on death (with `DropWeapon(wep)`) some Workshop downloaded SWEPs, my hands position is messed up at respawn.

Bug found on:
- [Orbital Strike Marker](http://i.imgur.com/NIjvRyD.jpg) from [M9K Specialties](https://steamcommunity.com/sharedfiles/filedetails/?id=144982052) pack (http://i.imgur.com/HlW6F6b.jpg)
- weapon_fists (vanilla swep) : make disapear all weapon models at respawn

The problem disapear if you get back the weapon on the player view (via Spawn menu).

**Comment by robotboy655** [comment]
These are problems with said addons/weapons, not GMod. They do not use normal view models. I will fix the weapon_fists problem.
