### ISSUE TITLE
Pistol sometimes falls through the floor

### ISSUE THREAD

**Issue by meharryp** [Facepunch/garrysmod-issues#1773]
http://youtu.be/z9Fsrj_KskI
Only seems to be affecting the pistol, and tends to happen when it flips over after force has been applied. Here's the code used to spawn the pistol seen in that video:
```
local weapon = ents.Create( ply:GetActiveWeapon():GetClass() )
weapon:SetPos( ply:EyePos() + ( ply:GetAimVector() * 10 ) )
weapon:Spawn()
local phys = weapon:GetPhysicsObject()
if IsValid( phys ) then
	phys:AddVelocity( ply:GetAimVector() * 500 )
end
```

**Comment by robotboy655** [comment]
Its was a problem with the collision model, will be fixed.
