### ISSUE TITLE
Ghosted props stay ghosted when interacted with

### ISSUE THREAD

**Issue by cd109876** [Facepunch/garrysmod-issues#1775]
I'm on Windows 7.
For example I want to spawn in a truck trailer. It is ghosted because it is big. I pick it up with the physics gun and it stays ghosted. It worked fine 3 days ago, now it is broken. I am not in the dev branch. Bought GMod a week ago. This happens with ALL big props that are ghosted.

**Comment by robotboy655** [comment]
This is a problem with the addons you are using, not the game.
