### ISSUE TITLE
SWEP:Deploy is not always called on client

### ISSUE THREAD

**Issue by VigiFyre** [Facepunch/garrysmod-issues#1776]
Deploy is called when:
* Weapon is selected using default weapon hud.

Deploy is not called when:
* Weapon is selected by running "use weptest" command.
* Weapon is selected by running "Entity(1):SelectWeapon'weptest'" lua.

Which means clientside :Deploy is broken on TTT and on any other server that has custom weapon selection hud.

**Comment by Bo98** [comment]
Yep, there was an issue opened a while back but closed as "your fault". Never did find out how.

**Comment by robotboy655** [comment]
It is not called on client in singeplayer due to prediction. ( As mentioned on the wiki )

![image](https://cloud.githubusercontent.com/assets/3299036/6019125/c4859e26-aba5-11e4-9f67-c5442c9c3022.png)

**Comment by VigiFyre** [comment]
Who cares about singleplayer. I'm speaking about multiplayer. Dedicated server.

**Comment by robotboy655** [comment]
You can easily fix it with self:CallOnClient() and some game.Singleplayer()

**Comment by robotboy655** [comment]
It is called in multiplayer after first SWEP spawn.

**Comment by VigiFyre** [comment]
No it's not. I tried switching weapons multiple times.

**Comment by robotboy655** [comment]
But it does? 

![image](https://cloud.githubusercontent.com/assets/3299036/6019231/f9958d28-aba6-11e4-8710-332adf8b02fa.png)

Make sure your SWEP:Deploy is defined in a clientside or shared file.

**Comment by VigiFyre** [comment]
weptest/cl_init.lua http://pastebin.com/Nh8x8CwR
weptest/init.lua http://pastebin.com/S4dzxUt6
weptest/shared.lua http://pastebin.com/uhUQPAn3

**Comment by robotboy655** [comment]
Using your exact code: 

![image](https://cloud.githubusercontent.com/assets/3299036/6019383/a3d5e99e-aba8-11e4-902a-a6599b73140b.png)

**Comment by VigiFyre** [comment]
I did more testing.

Deploy is called when:
* Weapon is selected using mouse wheel from default weapon hud.

Deploy is not called when:
* Weapon is selected by running "use weptest" command
* Weapon is selected using "Entity(1):SelectWeapon'weptest'"

Which means clientside deploy is broken on TTT and on any other server that has custom weapon selection hud.

**Comment by robotboy655** [comment]
Alright, you should open an issue with proper name and all the info.

**Comment by VigiFyre** [comment]
I've changed title and first comment.

**Comment by Jvs34** [comment]
Uh it works like that because those commands force the player to equip the weapon serverside.
If you want it to behave properly then your custom weapon selection should use http://wiki.garrysmod.com/page/CUserCmd/SelectWeapon, which is the same way the default weapon selection works.

**Comment by VigiFyre** [comment]
Yep, i was just reading source engine's cpp files and also found that out. Now that i've changed our custom weapon selection to this way, everything works fine.
