### ISSUE TITLE
Any tool isn't working anymore

### ISSUE THREAD

**Issue by JEUBlitzKrieg** [Facepunch/garrysmod-issues#1777]
Hello,

Since this morning, I and many friends were experiencing a bug, when choosing any of the given tool in the Tool List, Both Addons or Non-Addons tool a referencing to a lua error, which is : 

 [ERROR] gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:167: attempt to call method 'GetInfo' (a nil value)
  1. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:167

**Comment by thegrb93** [comment]
Something is modifying the Owner member of your weapons. Maybe nadmod (I told him about this problem).

**Comment by mattycfp** [comment]
Incomplete.

**Comment by JEUBlitzKrieg** [comment]
How is it Incomplete ? I gave up the error code, and, I don't see what I could add, if you could please specify what is missing to this I would gladly complete it.
