### ISSUE TITLE
SetFlexScale has no effect when run clientside

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#1779]
SetFlexWeight works just fine however.

Tried this on a ClientsideModel with model 'models/player/Group01/male_02.mdl' inside a 3D context

On non-dev version

**Comment by robotboy655** [comment]
I am afraid clientside models do not support SetFlexScale.

**Comment by Donkie** [comment]
What would a workaround be? I need this for a ModelPanel

**Comment by robotboy655** [comment]
There is none, unless adding the multiplier in SetFlexWeight can be considered as one.
I am pretty sure the GetFlexWeight is also broken, but that should be fixable.

But for Flex scale I'd need to implement the functions to CBaseFlex and I don't know how easy that would be.

**Comment by Donkie** [comment]
Alright, good to know. You do what you can!

**Comment by bizzclaw** [comment]
This seems to work fine on Clientside Models now.
https://dl.dropboxusercontent.com/s/x0u04gxfyw24mqi/2018-11-27_18-39-26.mp4

**Comment by robotboy655** [comment]
I can confirm this being fixed.
