### ISSUE TITLE
Garrys Mod Bug

### ISSUE THREAD

**Issue by PepperJack36** [Facepunch/garrysmod-issues#1780]
All the time when i start gmods, he launch but i dont know how or what or when addon start to load exemple: TTT Huge Map and the game crash after 5 second i have try to delet-it and re instal it but its doesn't work  Heeeellllppp !!!!

**Comment by TheKiwi5000** [comment]
ithink you should provide some more detailed informaation, or at least the map download link, and a list of your addons.

**Comment by PepperJack36** [comment]
I ha e delete all my addon for try but it crash all the time !

Envoyé de mon iPod

**Comment by daunknownman2010** [comment]
http://facepunch.com/forumdisplay.php?f=16 post it there, not here. Robotboy655 made it invalid for a reason.

**Comment by brandanboo** [comment]
every time i go on it says face punch studios then the screen just goes blue

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
