### ISSUE TITLE
garrys mod on steam contents not working for fixing errors/missingtextures

### ISSUE THREAD

**Issue by Gribgrab** [Facepunch/garrysmod-issues#1784]
so on gmod steam there is a bug my computer crashed for some reason then when i re installed all my games i have all teh hallifes and portal/portal 2 and team fortress two classic and none of the contents are working for gmos i enabled them to gmos but they arent working is this just happening to me or is it a bug for other people plz fix it

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

**Comment by Gribgrab** [comment]
oh ok thx
