### ISSUE TITLE
Mounting and Un-Mounted Crash

### ISSUE THREAD

**Issue by TechnoTadhg** [Facepunch/garrysmod-issues#1786]
I don't know how to mount mods. I wanted to do the portal 1 final map and I was no-clipping around the map (I recognised the shape) and suddenly I crashed with a message saying 
![This](https://cloud.githubusercontent.com/assets/10999535/6196283/f0b32910-b3ce-11e4-97c2-ce255554da05.png)

**Comment by XxLegoTadhgxX** [comment]
Mounting fixed, problem is the crash

**Comment by XxLegoTadhgxX** [comment]
![agien it happens](https://cloud.githubusercontent.com/assets/10999535/6196520/cf6129fe-b3d0-11e4-8c74-e21735a96d93.png)
Another happened

**Comment by XxLegoTadhgxX** [comment]
![ugh](https://cloud.githubusercontent.com/assets/10999535/6196721/3aaba8b8-b3d3-11e4-81b2-019f5164dc1b.png)
Getting sick of theese

**Comment by robotboy655** [comment]
Posting this more than once is pointless.

**Comment by robotboy655** [comment]
Give more info on how to reproduce this or stop it.

**Comment by XxLegoTadhgxX** [comment]
It just randomly happens. I am using Portal 1 final map. Seemingly random

**Comment by DarthTealc** [comment]
This was happening during the Gmod 13 beta (or possibly earlier). It happens if you noclip in certain areas of one of the last Portal 1 maps. If I remember correctly it's the one with GLaDOS' chamber if you noclip outside of it.

I reported it and I thought Garry fixed it at the time but something might have changed. If I can find my original report I'll post it.

**Comment by XxLegoTadhgxX** [comment]
Thing is, while it does happen when no-clipped, it also happens without that happening. More often when no-clipping but other times it just happens without anything happening

**Comment by XxLegoTadhgxX** [comment]
It happened agien, exept without the message

**Comment by robotboy655** [comment]
Something tells me it's your PC, it doesn't happen to me. At least post crash dumps or something if you want to be helpful, better though post your PC specs and picture of advanced video settings window.

**Comment by deinemudda32** [comment]
I know this error from my server either.
I downloaded a pony model from workshop, got this crash every 2nd day.
I removed it, never happend again.
So it should be a model problem

**Comment by mattycfp** [comment]
>pony model

Do you understand how hard it is not to yell and scream at people for their opinions on a bug help git
:I

**Comment by deinemudda32** [comment]
Yea its really hard, dude.
I didnt said, its because of "X".
I said it could be.

Im not a proffessional coder to know everything about that error.
Youre comment is really useless and either you didnt helped anyone in the thread so just please don't give shit about could be argument shit :)

**Comment by mattycfp** [comment]
>so please don't give a shit about could be argument shit

Be forewarned, I am also a grammar Nazi. :)

Anywho. This seems to be an issue recently coming up. Have all of the games that cause this problem been updated somewhat recent to this problem? Maybe there was an engine error I didn't find out about.

**Comment by deinemudda32** [comment]
I changed it, before you even commented.
I am a grammar nazi either. but not in the english language. lucky boy

**Comment by mattycfp** [comment]
Idk what you are saying, so imma back out slowly and you can get someone else to fix your problem.

**Comment by TeddiO** [comment]
Although not a fix as such, verifying the contents of the respective game (in this case Portal) may resolve the issue. This was a more common problem in the past (2010 - 2012) and verifying the contents at that time usually helped.

**Comment by robotboy655** [comment]
Pretty sure this was fixed sometime ago, was related to ropes or something.
