### ISSUE TITLE
flashing bar on left side of screen... help!

### ISSUE THREAD

**Issue by rcghalohell** [Facepunch/garrysmod-issues#1787]
hello, I started playing garrys mod again after a while, and there is a flashing bar that flashes all the colors of the rainbow, and even overlaps my msi afterburner osd.

OS: windows 7 pro/ windows 8 dual boot
16gb ram
intel core i7 4700mq
NVidia GeForce gtx 780m

drivers are already up to date, and the bar is there at all times

this also happens on midnight club 2, idk what the issue is

**Comment by robotboy655** [comment]
Most definitely a problem on your side if it happens in a game that is not even on the same engine as GMod.

**Comment by rcghalohell** [comment]
Do you have any suggestions?

**Comment by thegrb93** [comment]
Maybe your gpu is defective.

**Comment by rcghalohell** [comment]
I don't know, I mean it works perfectly fine in other games


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: thegrb93 <notifications@github.com> </div><div>Date:02/15/2015  3:26 AM  (GMT-05:00) </div><div>To: Facepunch/garrysmod-issues <garrysmod-issues@noreply.github.com> </div><div>Cc: rcghalohell <rcghalohell360@live.com> </div><div>Subject: Re: [garrysmod-issues] flashing bar on left side of screen... help! (#1787) </div><div>
</div>
Maybe your gpu is defective.

---

**Comment by thegrb93** [comment]
Does it on both win7 and win8?

**Comment by rcghalohell** [comment]
Yea, and both in integrated and nvidia


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: thegrb93 <notifications@github.com> </div><div>Date:02/15/2015  3:30 AM  (GMT-05:00) </div><div>To: Facepunch/garrysmod-issues <garrysmod-issues@noreply.github.com> </div><div>Cc: rcghalohell <rcghalohell360@live.com> </div><div>Subject: Re: [garrysmod-issues] flashing bar on left side of screen... help! (#1787) </div><div>
</div>
Does it on both win7 and win8?

---

**Comment by thegrb93** [comment]
Only option I can think of is to find a different driver version. Maybe the one you have doesn't work well with directx9+certain games.

**Comment by rcghalohell** [comment]
Or maybe a running program,  did garrys mod recently have problems with msi afterburner with other players?


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: thegrb93 <notifications@github.com> </div><div>Date:02/15/2015  3:34 AM  (GMT-05:00) </div><div>To: Facepunch/garrysmod-issues <garrysmod-issues@noreply.github.com> </div><div>Cc: rcghalohell <rcghalohell360@live.com> </div><div>Subject: Re: [garrysmod-issues] flashing bar on left side of screen... help! (#1787) </div><div>
</div>
Only option I can think of is to find a different driver version. Maybe the one you have doesn't work well with directx9+certain games.

---

**Comment by thegrb93** [comment]
I had no idea what that was until I just now looked it up. Might want to try without that as well.

**Comment by rcghalohell** [comment]
Looks like it works, but I guess I won't be able to record content to share on youtube from this game :(


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: thegrb93 <notifications@github.com> </div><div>Date:02/15/2015  4:12 AM  (GMT-05:00) </div><div>To: Facepunch/garrysmod-issues <garrysmod-issues@noreply.github.com> </div><div>Cc: rcghalohell <rcghalohell360@live.com> </div><div>Subject: Re: [garrysmod-issues] flashing bar on left side of screen... help! (#1787) </div><div>
</div>
I had no idea what that was until I just now looked it up. Might want to try without that as well.

---
