### ISSUE TITLE
Game Content Won't Mount

### ISSUE THREAD

**Issue by MeowsGG** [Facepunch/garrysmod-issues#1788]
I cannot mount DOD:S, CS: GO, and Insurgency: A Modern Combat for some reason.
I try reinstalling them, but it won't work.
Please help.

**Comment by mattycfp** [comment]
Has your game been updated to Steampipe? Or is it pirated?

**Comment by robotboy655** [comment]
They must be converted to SteamPipe ( Launch at least once ) and be installed through Steam. Insurgency is the mod, not the game.

**Comment by MeowsGG** [comment]
None of my games are pirated and yes they were all launched at least once.
I didn't launch CSS but it worked anyways.
All are fully updated, and I validated the files.

**Comment by mattycfp** [comment]
Did you list all of the games that didn't work in your first post? Because I have a good feeling that it's because of it not mounting other reiterations of the Source engine.

**Comment by Bo98** [comment]
DOD:S should work though.

**Comment by robotboy655** [comment]
So, I just downloaded DOD:S, works as expected, so does CS:GO.
![image](https://cloud.githubusercontent.com/assets/3299036/6203926/0614a464-b541-11e4-98d8-78dd138fb088.png)

Seek help @ http://facepunch.com/forums/16 and don't forget to describe your problem thoroughly, maybe with pictures if necessary.
