### ISSUE TITLE
[TTT] english ttt_radio translation (for last words) is wrong

### ISSUE THREAD

**Issue by Joschasa** [Facepunch/garrysmod-issues#1792]
ttt_radio commands are translated to english (ignoring the local language setting) for use as last words. But this translation uses the local language in one step.

Initial report: https://github.com/Tommy228/TTTDamagelogs/issues/133
Faulty line:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua#L320
> RADIO.ToPrintable(target)

**Comment by robotboy655** [comment]
TTT bug reports do not belong here. You can either report it to TTT author or make a Pull Request that fixes the problem.
