### ISSUE TITLE
Respawning on your own server and you turn out really small

### ISSUE THREAD

**Issue by lukec331** [Facepunch/garrysmod-issues#1793]
hey guys im just going to tell you i dont really know how  to fix it so if u know how to fix it plz tell me

**Comment by lukec331** [comment]
and u can see under the world

**Comment by thegrb93** [comment]
You might have a mod installed that is doing that.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
