### ISSUE TITLE
Returning true on ShouldDrawLocalPlayer in sandbox. Crashes you.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#1794]
Somehow returning true on ShouldDrawLocalPlayer will cause an instant crash.

local function ShouldDrawLocalPlayer() return true end
hook.Add("ShouldDrawLocalPlayer", "derp", ShouldDrawLocalPlayer)

**Comment by robotboy655** [comment]
No its not:

![image](https://cloud.githubusercontent.com/assets/3299036/6238828/ed11814a-b706-11e4-8960-94e156508f5f.png)

**Comment by Nak2** [comment]
Try use it with CalcView.
https://www.youtube.com/watch?v=vz8eAlyMfMc
Yes .. I crashed in the end of the video. My TauntAddon I'm working on is affected aswell. This wasn't a problem until the update.

**Comment by robotboy655** [comment]
Post exact code to reproduce. Sandbox and some of my mods use CalcView and I still didn't crash. Tested on Dev branch.

**Comment by Nak2** [comment]
Not sure if it's just a script somewhere that messes it up. But here you go.
This is a part of my gamemode that creates a thirdperson view based on a traceline.
(It looks like my tauntaddon is affected as well.)

local function TP( ply, pos, ang, fov )
	local view = {};
	local dist = 100;
	local trace = {};
		trace.start = pos;
	trace.endpos = pos - ( ang:Forward() * dist );
	trace.filter = LocalPlayer();
	local trace = util.TraceLine( trace );
	if( trace.HitPos:Distance( pos ) < dist - 10 ) then
		dist = trace.HitPos:Distance( pos ) - 10;
	end;
	view.origin = pos - ( ang:Forward() * dist );
	view.angles = ang;
	view.fov = fov;
		return view;
end;
hook.Add( "CalcView", "ThirdPerson", TP );

After the view has changed .. run this: 
lua_run_cl hook.Add("ShouldDrawLocalPlayer","derp2",function() return true end)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/6243826/8e95eb14-b752-11e4-8566-c9af6fd0e410.png)

Nope. It's probably one of your addons/the gamemode.

**Comment by raubana** [comment]
Ok, so commenting out that suspect hook - "PrePlayerDraw" - fixed the problem. At the very least I can say that the thirdperson model is rendering now. Now I just have to figure out how to get the viewmodel to render again, and how to make the thirdperson player model draw nearly invisible.

**Comment by raubana** [comment]
Ok maybe it was being caused by my calling DrawModel on the player inside of PreDrawModel. Not sure how far along it actually gets before my game closes.
