### ISSUE TITLE
Vehicle damage system = source engine crash

### ISSUE THREAD

**Issue by Yuri6037** [Facepunch/garrysmod-issues#1795]
Ok, that's an issue for the forum message VC2:EjectPassengers crashing srcds. So basicaly, like said in the title it's a vehicle damage system.

So you'll call a function to eject passengers of the vehicle, but when you call it a crash happens : srcds.exe has stopped working, here is the crash informations : 
Exception code : 0xC0000005
Crash dumps files : http://dlsrv.sldt-team.net/public_dl.php?file=srcds.zip

To reproduce the crash, just create a PhysicsCollide callback on a prop_vehicle_jeep, if the impact velocity is > 1000, call GM:EntityTakeDamage.
In the EntityTakeDamage hook, just multiply by 512 the damages caused by the PhysicsCollide, then create an env_explosion at the vehicle's position, then call the famous VC2:EjectPassengers with only if (IsValid(vehicle:GetDriver()) then vehicle:GetDriver():ExitVehicle() end.
And you can say at least : "Good bye GMod Dedicated Sever !"

This works on singleplayer too, but the PhysicsCollide callback acts strangely. Instead of stopping to work, the client shuts down and the message "Engine Error ED_Alloc: no free edicts" comes up !

**Comment by wiox** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/56accfdb9c4abd32ae1dc26b2e4cc87898cf4dc1/sp/src/game/server/vehicle_base.cpp#L883-L955

I assume the hook is called here on line 912. If the player becomes ejected during that time, the later calls to GetDriver that expect a valid result will fail.

**Comment by Yuri6037** [comment]
Why close ? I still get the crash !!!

**Comment by Bo98** [comment]
It's likely fixed for the next update.

**Comment by Yuri6037** [comment]
Oh ok...
