### ISSUE TITLE
Garry's Mod searches the wrong path for part of the Steam API

### ISSUE THREAD

**Issue by nmirthes** [Facepunch/garrysmod-issues#180]
It would appear, from strace output, that hl2_linux is checking a single, hard-coded path for part of the Steam API. That being:

`$HOME/$STEAMDIR/linux32/libsteam.so`

I suspect the Source SDK looks here because the `$HOME/$STEAMDIR/sdk32` symbolic link points to the above directory. The library is actually found in `$HOME/$STEAMDIR/ubuntu12_32`. Exiting Steam and removing `$HOME/$STEAMDIR/linux32` doesn't result in Steam placing libsteam.so in that directory. Should probably search $GAMEDIR/bin, and then the directories mentioned earlier. Then there's arch, but that shouldn't be an issue for a while.

**Comment by robotboy655** [comment]
libsteam.so is no longer used by Garry's Mod.

**Comment by virtualdxs** [comment]
Is that so? I still get the error when I start my server, which I downloaded three days ago.

**Comment by Bo98** [comment]
He probably meant as of the next update. You can test it on the dev branch if you want.

**Comment by virtualdxs** [comment]
Alright. I like to keep things stable, so I just symlinked it and it works great. Thanks.

**Comment by Volantarius** [comment]
I'm getting this error from gmpublish_linux right now, im on dev too.
