### ISSUE TITLE
Game crashes when trying to load a quicksave.

### ISSUE THREAD

**Issue by Janfon1** [Facepunch/garrysmod-issues#1800]
I made a quicksave on Bigcity map. I was planning to make another animation, everything was set up, I used:
- SCars Slim
- Buick's Synergy Cars
  When I try to load it, I get immediate return to main menu with this message appearing on the console:

] load quick
Loading game from save\quick.sav...
Map file wasn't found, copying it from addon..
PREP OK
Map file wasn't found, copying it from addon..
Failed, using default cubemap 'engine/defaultcubemap'

Loaded Drop on Death Addon | v0.2 | By Kazaam

TEST [maps/ba_jail_blackops.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_adventurers.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_aperture_revisited.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_aperture_revisited.png][maps/gm_bigcity.bsp]
TEST [maps/gm_bigcity.bsp][maps/gm_bigcity.bsp]
FOUND IN ADDON [105982362]
TEST [maps/gm_fork.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_fork.nav][maps/gm_bigcity.bsp]
TEST [maps/gm_kitty0706.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_kitty0706.png][maps/gm_bigcity.bsp]
TEST [maps/gm_lair.bsp][maps/gm_bigcity.bsp]
TEST [maps/rp_richlandday.bsp][maps/gm_bigcity.bsp]
TEST [maps/rp_richlandnight.bsp][maps/gm_bigcity.bsp]
Making workshop map available for client download
Loading game from //MOD/save/gm_bigcity.HL1...
Unknown command "sv_tags"
Unknown command "sv_tags"
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg/mapcycle.txt' was not found.)
Precache of particle/particle_electrical_arc ambigious (no extension specified)
SV_BroadcastMessage:  Recipient Filter for message type 33 (reliable: yes, init: no) with bogus client index (1) in list of 1 clients

Host_Error: Reliable message (type 33) discarded.

//Same happens after disabling all of my addons:

] load quick
Loading game from save\quick.sav...
Map file wasn't found, copying it from addon..
PREP OK
Map file wasn't found, copying it from addon..
Failed, using default cubemap 'engine/defaultcubemap'

Loaded Drop on Death Addon | v0.2 | By Kazaam

TEST [maps/ba_jail_blackops.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_adventurers.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_aperture_revisited.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_aperture_revisited.png][maps/gm_bigcity.bsp]
TEST [maps/gm_bigcity.bsp][maps/gm_bigcity.bsp]
FOUND IN ADDON [105982362]
TEST [maps/gm_fork.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_fork.nav][maps/gm_bigcity.bsp]
TEST [maps/gm_kitty0706.bsp][maps/gm_bigcity.bsp]
TEST [maps/gm_kitty0706.png][maps/gm_bigcity.bsp]
TEST [maps/gm_lair.bsp][maps/gm_bigcity.bsp]
TEST [maps/rp_richlandday.bsp][maps/gm_bigcity.bsp]
TEST [maps/rp_richlandnight.bsp][maps/gm_bigcity.bsp]
Making workshop map available for client download
Loading game from //MOD/save/gm_bigcity.HL1...
Unknown command "sv_tags"
Unknown command "sv_tags"
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg/mapcycle.txt' was not found.)
Precache of particle/particle_electrical_arc ambigious (no extension specified)
SV_BroadcastMessage:  Recipient Filter for message type 33 (reliable: yes, init: no) with bogus client index (1) in list of 1 clients

Host_Error: Reliable message (type 33) discarded.

When I try to load anything else, it crashes, showing the gray screen in the end.
Any way I can retrieve those saves safely?

**Comment by robotboy655** [comment]
Closing as stale.
