### ISSUE TITLE
Shell Execute in Menu

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#1801]
![2015-02-24_07-37-25](https://cloud.githubusercontent.com/assets/3169571/6349420/48feb2a2-bbf8-11e4-9e91-27b60a437764.jpg)

Using a directory escape, this allows you to execute anywhere on the drive of the current process.

    OpenFolder("saves/../../garrysmod/../../garrysmod/../../common/../../SteamApps/../../Steam/../../Program Files (x86)/../../../yay.exe")

------------------------------

    "saves/../../garrysmod/../../garrysmod/../../common/../../SteamApps/../../Steam/../../Program Files (x86)/../../../"
 will escape into the root of the drive.

**Comment by robotboy655** [comment]
This is irrelevant since the only person who can take advantage of this is yourself, isn't it?

**Comment by Bo98** [comment]
Custom menus maybe. There's been a few of those recently.

**Comment by notcake** [comment]
I'm sure Willox will find a way to use this :v

**Comment by TheFreezebug** [comment]
Custom menu's will be able to take advantage of this indeed. There are also ways to bridge clientside and menu lua (though its unreliable, its possible)

**Comment by wiox** [comment]
In that case, this can be abused by any server already. update plox
