### ISSUE TITLE
Can't change weapons or shoot gmod

### ISSUE THREAD

**Issue by willbell75** [Facepunch/garrysmod-issues#1803]

**Comment by robotboy655** [comment]
This is not a place to get help. This is not even of any use to anyone even if you are looking for help.

**Comment by willbell75** [comment]
Where can i find the number to gmod

**Comment by robotboy655** [comment]
I have no idea what number you are looking for, but this is not a place to get help. Get help at this forum: http://facepunch.com/forums/16
