### ISSUE TITLE
Dead players behave as if they're alive after a certain period

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-issues#1807]
edit: Scratch that, this is happening in the live version as well.

A few seconds after dying (anywhere from 5 to 10 seconds), dead players seem to "respawn" as a ghost of sorts, completely invisible and maybe even without collision. Their death ragdoll freezes and you can control the "ghost" player. You can hear their footsteps and, if in water, their splashing sounds.

This is immediately noticeable if you suicide in gm_construct's lake, you'll notice the ragdoll stops moving and then you can hear the sounds of a player splashing in water.

**Comment by mcd1992** [comment]
Noticing this issue as well. Suicide then after a while just hold +back and you'll hear footsteps.

**Comment by robotboy655** [comment]
This is how source engine works.

**Comment by robotboy655** [comment]
To clarify, the player entity is not removed when you die, obviously. The "dead body" of the dead player is clientside. It never exists on server.

**Comment by UselessGhost** [comment]
Alright, fair enough. I've just never encountered this in any other Source game.
