### ISSUE TITLE
Crash when joining SOME servers

### ISSUE THREAD

**Issue by kareem897** [Facepunch/garrysmod-issues#1809]
Hi, every time I join a server like Mafiarp of methrp, when the loading reaches the last extracting, my gmod crashes. I tried deleting all gmod files and downloading them again and I un installed all my addons and I did verify integrity of game cache and still nothing works. I hope someone replies to me as soon as possible and thank you for your time.

**Comment by robotboy655** [comment]
This is a known problem for many people, no need to spam about it here, it won't change anything.
