### ISSUE TITLE
[DEV] When disabling an addon it's still enabled?

### ISSUE THREAD

**Issue by Nyaaaa** [Facepunch/garrysmod-issues#1811]
When disabling an addon it's still enabled, in SinglePlayer / Multi-Player?

Are you sure this is how it works?

**Comment by robotboy655** [comment]
The effect of disabling an addon will take action only after a restart, it's a problem @UnderscoreKilburn introduced in one of the previous updates.

**Comment by Nyaaaa** [comment]
Thanks
