### ISSUE TITLE
Garry's Mod TTT Playercolor

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#1812]
If colormode 0 -> White playermodels -> blue dead bodys
If colormode 1 -> Randomized color playermodels -> blue dead bodys
If colormode 2 -> Randomized all color playermodels -> blue dead bodys

i'm sure that shouldnt happen.
I removed it with editing player_color matproxy file.

**Comment by robotboy655** [comment]
This is a bug tracker for GMod, not TTT. Either report this to TTT author or Pull Request a fix.

**Comment by deinemudda32** [comment]
I'm sorray.
