### ISSUE TITLE
Gmod cant download addons and crashes

### ISSUE THREAD

**Issue by mercuryRisingg** [Facepunch/garrysmod-issues#1813]
Garrysmod is having problems with downloading addons and cant download 90% of them, also when joining a server that presents the addon name most of them say this at the end "[DISCONTINUED]" and then it crashes to desktop without a hl2.exe has stopped working or anything.

unsure of specs but it is a dell office model and everything stock except for video card its my friends pc so apologies for my retardation.
I have restarted, shut down, and even restored my pc from an earlier date.i have uninstalled gmod, deleted files, and removed previous addons.i also made gmod an exception in avg and firewall, turned off both firewall and avg to no avail. there is no dump file either. im pretty sure its the update that broke gmod for mac users and some windows users.

**Comment by robotboy655** [comment]
This is not helpful. If you seek help, go to http://facepunch.com/forums/16
