### ISSUE TITLE
GMPublish - Upload issues

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#1815]
I can't leave more description than this since its so random:

Sometimes, when I upload workshop addons (usually the bigger ones >50mb) it says it succeeds uploading and no error message is given, but when the client downloads it he gets an old version anyways.

I'd love to help debug this but currently its entirely impossible since there is no feedback.

**Comment by robotboy655** [comment]
I think I know what the problem here is. ( Files being deleted from Steam Cloud too quickly ).

**Comment by robotboy655** [comment]
I have committed changes to GMPublish, once it updates please test.
