### ISSUE TITLE
screen errors on gmod??

### ISSUE THREAD

**Issue by Krowler666** [Facepunch/garrysmod-issues#1816]
I honestly have no idea what the problem would be but I have tried re-downloading gmod once or twice and the screen when in the facepunch loading screen, main screen, server list screen, and in game my screen spazzes out with horizontal black lines running vertically up and down my screen almost like a really old tv if anyone knows what i mean please help :( this didnt start until 2 or 3 days ago and it is only on gmod, not any of my other games :/

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
