### ISSUE TITLE
Entity.SetGravity

### ISSUE THREAD

**Issue by EthanTheGreat** [Facepunch/garrysmod-issues#1817]
http://wiki.garrysmod.com/page/Entity/SetGravity

Doesn't work it seems.

code: lua_run player.GetByID( 1 ):GetEyeTrace( ).Entity:SetGravity( 100 )

**Comment by Jvs34** [comment]
It's a multiplier, and it only works for entities that use the movement system without a physobj ( anything other than MOVETYPE_PHYSICS such as crossbow bolt, npcs, etc ) 

I'll document that on the wiki, but really the function works fine.

**Comment by thegrb93** [comment]
We should get a function that works on movetype_physics though. What's the point if you can't have floating props?

**Comment by EthanTheGreat** [comment]
Thanks, I had no clue how to use it.

**Comment by wiox** [comment]
@thegrb93 
> We should get a function that works on movetype_physics though. What's the point if you can't have floating props? I mean yeah, you have use a tiny extra bit of cpu to read the entity's gravity value before applying the gravitational force, but that's not much work unless you have over 1000 or so objects (which would lag like hell on its own anyway).

You can probably get away with using http://wiki.garrysmod.com/page/PhysObj/EnableGravity.

**Comment by thegrb93** [comment]
Ah yeah at least there's that.
