### ISSUE TITLE
read random data on lua stack

### ISSUE THREAD

**Issue by meepdarknessmeep** [Facepunch/garrysmod-issues#1818]
if you call debug.getregistry()[[1]] (AdvancedLuaErrorReporter) and the first argument is not a string then you get returned a double (which can be used to be converted to addresses/other values)

**Comment by wiox** [comment]
"on lua stack"

call the police

**Comment by meepdarknessmeep** [comment]
calling police now

this isn't a serious issue but it's a bug.

**Comment by notcake** [comment]
meep i just used this bug to hack google

**Comment by neico** [comment]
imo the registry should have some protection that disallows direct access to numeric keys, alas references, nothing good will ever come out of messing with those as they are needed for C calls (at least on the gmod module api)

ex. add a metatable to the registry and tell __index that if the key is numeric return nil, and make __newindex disallow writing new numerics.

This doesn't cover the case of already existing numeric,
I created a __usedindex and __newusedindex metamethod in my own lua implementation to prevent that, I'd gladly take the penalty on performance by adding them over people messing with things they aren't supposed to...

**Comment by wiox** [comment]
If anybody is going to put the effort in to secure that I'd rather see the proper approach be taken and access to the registry removed.

**Comment by willox** [comment]
fixed

**Comment by Kefta** [comment]
What exactly did you change?

**Comment by meepdarknessmeep** [comment]
the c function probably

**Comment by willox** [comment]
I didn't do any big registry removing changes. Just made the function not output any data unless it was supposed to.
