### ISSUE TITLE
input library overflow

### ISSUE THREAD

**Issue by TheFreeman193** [Facepunch/garrysmod-issues#1819]
(This is the same as #284 but creating a new one as that's nearly two years old and doesn't cover the whole issue.)

Several functions within the *input* library cause the game client to crash with generic exceptions (0x0/0xC0000005) when passed large +/- integers (>6.3-6.5e4). Affects the following functions:
* IsKeyDown
* IsButtonDown
* IsMouseDown
* WasKeyPressed
* WasKeyReleased
* WasKeyTyped
* WasMousePressed
* WasMouseDoublePressed

Tested on latest dev update (2015.03.02). I'm assuming this is some kind of overflow. Seeing as the KEY_ enums don't even reach 256, I can't see why such large ints are being permitted?

**Comment by thegrb93** [comment]
Is this fixed? I have some code affected by this that I need to fix if it isn't.

**Comment by willox** [comment]
yes

**Comment by thegrb93** [comment]
Thanks
