### ISSUE TITLE
physenv.AddSurfaceData is broken

### ISSUE THREAD

**Issue by Master-Chris** [Facepunch/garrysmod-issues#1821]
This bug occurs on both the standard "live" version of Gmod (14.07.13) and the Dev branch on steam (2015.03.02).

Basically the lua function physenv.AddSurfaceData can only be used once. All subsequent attempts to use the function don't appear to work and the surface data is not properly loaded which leads to crashes*.

For example, this code works perfectly:

```lua
physenv.AddSurfaceData([[

"cartire"
{
    "base"        "rubber"
    
    "friction"    "1.2"
    "elasticity"    "3"
    "density"    "500"
}

"slidingcartire"
{
    "base"        "rubber"
    
    "friction"    "1"
    "elasticity"    "3"
    "density"    "500"
}

"trucktire"
{
    "base"        "rubber"
    
    "friction"    "5.0"
    "elasticity"    "3"
    "density"    "500"
}

"slidingtrucktire"
{
    "base"            "rubber"

    "friction"        "2.2"
    "elasticity"    "3"
    "density"    "500"
}
]])
```

In the above case both the truck and car drive as intended and there are no crashes when attempting to use the handbrake*, everything works perfectly. 

However if you split the code into two separate files or blocks like this:

```lua
physenv.AddSurfaceData([[

"cartire"
{
    "base"        "rubber"
    
    "friction"    "1.2"
    "elasticity"    "3"
    "density"    "500"
}

"slidingcartire"
{
    "base"        "rubber"
    
    "friction"    "1"
    "elasticity"    "3"
    "density"    "500"
}
]])
```

```lua
physenv.AddSurfaceData([[

"trucktire"
{
    "base"        "rubber"
    
    "friction"    "5.0"
    "elasticity"    "3"
    "density"    "500"
}

"slidingtrucktire"
{
    "base"            "rubber"


    "friction"        "2.2"
    "elasticity"    "3"
    "density"    "500"
}
]])
```

This causes the second vehicles surface properties to load incorrectly, in this case the truck. This means that when you attempt to use the handbrake* it will crash the game. Interestingly if you use the cars handbrake this does not crash the game, the first set of surface properties are loaded properly. If you change the order so the trucks surface properties are listed first will cause the car to crash the game instead.

I find this bug very limiting because it makes it impossible to have multiple separate vehicle addons installed and working at the same time if they both rely on custom surface properties. This currently forces me to release my vehicle pack as a single large download which I would prefer not to do.

*Using the handbrake in Source causes the players vehicles wheels to change their surface property to the "skidmaterial" specified in the vehicle handling text file, if the material cannot be found then this causes a crash.

**Comment by Master-Chris** [comment]
This is my first post on Github and I would just like to know if an admin has to add tags to an issue because I couldn't see any way of doing that when I was writing the problem out. I read that we aren't allowed to put tags in the titles.

**Comment by TheFreeman193** [comment]
Tags will be added for you- likely by @robotboy655 when he sees it.

**Comment by Master-Chris** [comment]
Ah ok, thanks @TheFreeman193

**Comment by robotboy655** [comment]
There's a grave complication with this issue, the function bound to this binding is defined in vphysics.dll, which we do not have access to.

There might be a way to fix it, but it is not a nice fix.

**Comment by Master-Chris** [comment]
Damn, sounds bad. Can I just ask though, do you know why this function replaced the original surfaceproperties text script system which is in all other versions of Source? I'm just not sure why it needed replacing in the first place.

**Comment by robotboy655** [comment]
It's not replaced, it is a Lua binding so you don't have to edit the manifest manually for every addon.

**Comment by Master-Chris** [comment]
Oh I see, hmm. I don't suppose there's a way to tell the game to load every script without the need for a manifest. I suppose that would increase load times a lot though. 

Is there a list of existing surface data values available? I was just thinking that perhaps you could add a set of generic tire friction values suitable for most vehicles and ship that with garry's mod, then we could use those values instead of making our own. I know this wouldn't be the most flexible system but it sounds like it's a lot simpler to implement.

**Comment by Master-Chris** [comment]
@robotboy655 Any news on this? Also you mentioned that it may be possible to fix the issue even though it's not a nice fix. Can you elaborate on what that would involve?

**Comment by robotboy655** [comment]
I will look into it after we push out the update and all the hot fixes, if necessary.

**Comment by Master-Chris** [comment]
Ok sounds good.

**Comment by Master-Chris** [comment]
@robotboy655 Has there been any progress on this?

**Comment by robotboy655** [comment]
Should be fixed in Dev branch when it updates.
