### ISSUE TITLE
SetGlobal functions breaking NWVars

### ISSUE THREAD

**Issue by TheFreeman193** [Facepunch/garrysmod-issues#1823]
I stumbled across this issue after noticing a legacy addon using *SetGlobalString* was breaking the UserGroup NWVar.

If one of the SetGlobal functions is called clientside **before** the global var is defined using the function serverside with the same identifier, all new NWVars of that type, defined serverside on a player, aren't networked. Non-player entities don't seem to be affected, and existing NWVars can still be read on both server & client. Only the NWVar type that was used in SetGlobal appears to be affected; calling SetGlobalBool clientside seems only to break SetNWBool serverside.

This was tested on the latest update of the dev branch (2015.03.02); it occurs in singleplayer and on listen and dedicated servers.

The problem can be reliably reproduced by calling one of the SetGlobal functions clientside with a random identifier, before attempting to create a new NWVar of the same type serverside. Any attempt to read the new NWVar clientside fails, despite the new value being readable on the server.

**Comment by UnderscoreKilburn** [comment]
Should be fixed, check again on the dev branch in a hour or two.

**Comment by TheFreeman193** [comment]
Will do, cheers.
