### ISSUE TITLE
HTTP doesn't support REST

### ISSUE THREAD

**Issue by AlexCoder25** [Facepunch/garrysmod-issues#1825]
Default library http won't send requests with such methods as PUT and DELETE.
As wiki says "A more powerful & advanced method can be used via the global HTTP function.", but it doesn't. There's only two methods supported: get and post. Get - is the default when I use any other methods like put, delete, qwerty, asdasd.

Also, using x-http-method-overide doesn't solve this problem. Don't know why is that.

**Comment by Noiwex** [comment]
Post example of your code.

**Comment by AlexCoder25** [comment]
local data =
{
	url = "http://localhost:5984/",
	method = "delete",
	parameters = {},
	headers = {
		["X-Http-Method-Override"] = "DELETE"
	},
	success = function(code, body, headers)
		print(body)
	end,
	failed = function(message)
		
 	end
}

HTTP(data)

**Comment by UnderscoreKilburn** [comment]
PUT and DELETE should be supported in the dev branch already, have you tried it yet?

**Comment by AlexCoder25** [comment]
My vault. 
"HTTP() now supports "head", "put" and "delete" as methods"
Didn't match. Couldn't test in dev, it's broken.

Remove this issue please.

**Comment by Bo98** [comment]
> Couldn't test in dev, it's broken.

What's broken? Should work fine.

**Comment by AlexCoder25** [comment]
On gmod startup. Can't show main menu.
MENU ERROR: lua/menu/errors.lua:67: attempt to call field 'Count' (a nil value)
	lua/menu/errors.lua:67 [v]
	lua/includes/modules/hook.lua:84 []

**Comment by AlexCoder25** [comment]
```lua
Errors[ addonid ] = error
```
Probably disposable folder in lua directory causes these errors.

**Comment by AlexCoder25** [comment]
I refreshed cache.
That was probably because of disposable files in lua directory.
