### ISSUE TITLE
Black Textures 

### ISSUE THREAD

**Issue by Tri445** [Facepunch/garrysmod-issues#1826]
I have a problem where the textures are black, at first its was small things but now i cant see anything because of this. Here is a screenshot of it.

http://cloud-4.steamusercontent.com/ugc/540768312200014415/CA4BF1E7F66C7AC177431A1D4E4193DAF9C2B3FB/1024x640.resizedimage

How can i fix this?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
