### ISSUE TITLE
IsValid errors for boolean, numbers, strings

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#1828]
```
] lua_run print(IsValid(false))
> print(IsValid(false))...
false
] lua_run print(IsValid(true))
> print(IsValid(true))...

[ERROR] lua/includes/util.lua:170: attempt to index local 'object' (a boolean value)
  1. IsValid - lua/includes/util.lua:170
   2. unknown - lua_run:1
```

Should print true on both.

**Comment by NeatNit** [comment]
actually seems to error out on numbers and strings as well. How has this not been caught before?

**Comment by NeatNit** [comment]
Sorry for the spam. This demonstrates the problem.
```
] lua_run print(IsValid(false))
> print(IsValid(false))...
false
] lua_run print(IsValid(true))
> print(IsValid(true))...

[ERROR] lua/includes/util.lua:170: attempt to index local 'object' (a boolean value)
  1. IsValid - lua/includes/util.lua:170
   2. unknown - lua_run:1

] lua_run print(IsValid(0))
> print(IsValid(0))...

[ERROR] lua/includes/util.lua:170: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:170
   2. unknown - lua_run:1

] lua_run print(IsValid(""))
> print(IsValid(""))...

[ERROR] lua/includes/util.lua:170: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. IsValid - lua/includes/util.lua:170
     4. unknown - lua_run:1

] lua_run print(IsValid("Hello World!"))
> print(IsValid("Hello World!"))...

[ERROR] lua/includes/util.lua:170: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. IsValid - lua/includes/util.lua:170
     4. unknown - lua_run:1

] lua_run print(IsValid(123))
> print(IsValid(123))...

[ERROR] lua/includes/util.lua:170: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:170
   2. unknown - lua_run:1

] lua_run asdf = 123
> asdf = 123...
] lua_run print(IsValid(asdf))
> print(IsValid(asdf))...

[ERROR] lua/includes/util.lua:170: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:170
   2. unknown - lua_run:1
```

**Comment by Bo98** [comment]
IsValid is for metatables. IsValid is just the same as meta:IsValid() but with the addition of a nil check. The error happens on the check for an IsValid method as indexing booleans and numbers are invalid in Lua and indexing strings is invalid in this scenario in GMod.

**Comment by thegrb93** [comment]
It has been known for a long time but nobody considered it an issue. Just don't put things that aren't entity/physics/nil into IsValid.

**Comment by NeatNit** [comment]
It should still return true for all boolean, number, table and string values if you ask me.

Though obviously if everyone disagrees with this then I'll back out.

**Comment by thegrb93** [comment]
I think the reasoning is that the cost of all the checks would be far worse than the benefit gained from resolving a potential lua error.

**Comment by Bo98** [comment]
I guess it is a somewhat common with the lack of predefined variable types in Lua. Only one check should be required if this was to be fixed (+ maybe an isstring because of the way string indexing works in GMod but that's a discussion for garrynewman/garrysmod#885). It should absolutely not return true however. This would just break things.

**Comment by NeatNit** [comment]
I guess it's my misunderstanding then. I thought IsValid was supposed to be a generic "is this thingamabob a valid thingamabob" function, in which case a number is valid, as is a boolean value (true and false alike).

I don't even remember how I came across this issue but it's probably easy to work around :smile:

**Comment by Bo98** [comment]
With most types in Lua, there really isn't any invalid state. Booleans for example are true and false. If they are not then they are not booleans.

**Comment by NeatNit** [comment]
Yeah but IsValid also checks if it's nil.

false is a valid Boolean value, but nil is not valid.

**Comment by wiox** [comment]
```lua
if x == nil then
```

**Comment by NeatNit** [comment]
Right.

Please ignore my brain fart. How do I remove an issue? :X

**Comment by NeatNit** [comment]
Right.

Please ignore my brain fart. How do I remove an issue? :X

**Comment by Bo98** [comment]
> false is a valid Boolean value, but nil is not valid.

Worth mentioning here that a nil boolean is not a boolean. Nil is its own type. What you're asking is to change IsValid to be only a nil check.

(You can close an issue by clicking the close button next to the comment button.)

**Comment by NeatNit** [comment]
I'm aware of that.

I see little point in discussing this further though - this is clearly a non-issue.

**Comment by Kefta** [comment]
Just wanted to mention that I tried fixing this issue with type, then I tried pcall, but both made the function noticiblely slower

**Comment by robotboy655** [comment]
There's nothing to fix. Numbers, booleans and strings are all valid unless they are nil. What you should be doing is 
```
if ( var ) then
end
```
for them.

**Comment by Bo98** [comment]
If you really wanted to "fix" it then a proper fix would be a `getmetatable(object)` nil check (to replace the object nil check) and not several type/pcall checks.

**Comment by thegrb93** [comment]
Still an extra function call. Just deal with it.

**Comment by Bo98** [comment]
More talking about the proper way to fix it over performance. I agree it is not worth it.

**Comment by NeatNit** [comment]
For the record, I've already been convinced that the function SHOULDN'T be changed, but I want to say that this is the whole point:
"Numbers, booleans and strings are all valid unless they are nil."
Following that statement, IsValid(number/bool/string) should return true since it's been given a valid value.

The point of using IsValid(object) instead of object:IsValid() is that object might be nil. The same goes for numbers, strings, and bools - and specifically for bools, it's annoying to differentiate between nil and false.

But like, this issue is closed. We should stop talking about it. I'm not setting a very good example. :X
