### ISSUE TITLE
timer.(Un)Pause breaking time left

### ISSUE THREAD

**Issue by TheFreeman193** [Facepunch/garrysmod-issues#1830]
If timer.Pause/UnPause is called on a paused/active timer respectively, the value for time remaining is corrupted, producing a number far larger. No error is thrown and the pause/unpause functionality is retained. Further calls compound the value.

This can be reproduced by creating a timer and checking with TimeLeft(), before calling Pause() twice, or UnPause() once on the active timer. Another call to TimeLeft() yields an incorrect value. If UnPause() was called, the timer will continue to count down from this new value.

Tested on the dev branch (2015.03.05).

**Comment by robotboy655** [comment]
Will be fixed in the next version.
