### ISSUE TITLE
После обновления 2015.03.09 не запускается Garry's Mod

### ISSUE THREAD

**Issue by Tykva** [Facepunch/garrysmod-issues#1834]
Получил обновление Garry's Mod 2015.03.09. После установки обновления не включается игра. При открытии игры виден синий экран с надписью "Loading", потом игра закрывается. 
------------------
OS: Ubuntu 15.04
Видеокарта: GeForce GT 635M/PCIe/SSE2
NVIDIA Driver Version: 346.47

P.S Translate the text in the translator.

**Comment by robotboy655** [comment]
Pretty sure this is duplicate of #1833.
