### ISSUE TITLE
Materials wont apply

### ISSUE THREAD

**Issue by geraldLRG** [Facepunch/garrysmod-issues#1839]
So i have been playing Gmod for around 2 years. i recently got banned on one of my main servers for a day and when i came back my props lost there materials so i tried to reapply them to it but when i tried i did not work. this is what i have tried : deleting my textures and reinstalling,restarting my computer and reinstalling my game. none of this has helped id like to fix this as soon as possible. Thanks in advance

**Comment by geraldLRG** [comment]
update after several minutes writing this my friend got the bug aswel*

**Comment by robotboy655** [comment]
Can you provide material paths?

**Comment by Bonfire** [comment]
A lot of players on one of my servers are also having the issue. It seems that none of the materials are showing up, not just selective materials. If it helps, the server where the issue resides is running the DarkRP gamemode.

**Comment by Bonfire** [comment]
It seems some players on one of my servers are also running into this issue. They've tried everything stated above, to no avail. Regarding the material paths, at-least for my players, none of the material work. They can't see the materials, but the materials **are** being applied.

**Comment by geraldLRG** [comment]
Not sure what you mean with "material paths" robotboy could you explain?(sorry for my bad english)

**Comment by robotboy655** [comment]
What materials exactly are not working?

**Comment by Bonfire** [comment]
Every single material is "broken". To the player, this is what it looks like: https://www.youtube.com/watch?v=_QUZK6SZkYI

None of the materials are shown to them, but if you don't happen to have this "bug", you can see the materials. Some players can see the materials, others run into this issue.

**Comment by deinemudda32** [comment]
Some of my players have this issue either.
I dont have it anyways.

**Comment by robotboy655** [comment]
It is caused by having the game in DirectX 8 mode.

Adding -dxlevel 95 to your CLIENT command like parameters will fix it.
