### ISSUE TITLE
Can't Play On servers. Help Please!

### ISSUE THREAD

**Issue by LPACE2** [Facepunch/garrysmod-issues#1846]
Can't play on servers. PLEASE HELP!
Ok, So i load my GMOD and go on the multiplayer list. I play on this server and as for i have all my addons. But The servers says i am missings the addons. As for I donladed their map and looked at it and it showed the red letters meaning i don't have the map. Please help me fix this addon issue. D:
It is so i can't play on a server as for the addons are messing with me. Please HELP!

What i did:
Delete all addons and re-installed them

**Comment by TheFreeman193** [comment]
The server browser maps issue has already been fixed with garrynewman/garrysmod@3ebf64f99a3eabbe78880522fd4e69fae089f4a8.

**Comment by LPACE2** [comment]
The issue is that the addons wont work when i play on the server. So i cant see anything. Thanks for the response also.
