### ISSUE TITLE
Crowbar hit detection issues

### ISSUE THREAD

**Issue by meepdarknessmeep** [Facepunch/garrysmod-issues#1848]
see video:
https://a.pomf.se/pdzitg.mp4

**Comment by robotboy655** [comment]
Can you test this in HL2 and confirm it doesn't do the same?

**Comment by Jvs34** [comment]
The crowbar uses a hulltrace of Vector(-16,-16,-16), Vector(36,36,36), that's intended.

**Comment by drakehawke** [comment]
As we discussed in the thread - this only happens on that specific wall in gm_construct. Everywhere else in gm_construct is fine and other maps are fine. It's a bug with the map.

**Comment by robotboy655** [comment]
In reality this is how crowbar works, it doesn't use a simple trace forward near entities, it uses some form of hull trace.

**Comment by robotboy655** [comment]
You can easily reproduce this by hitting these things in ravenholm:
http://i.imgur.com/PbflD0Y.jpg

Look where my crosshair is and where the hit mark is.
