### ISSUE TITLE
render.RenderView applies strange postprocessing effects to normal screen

### ISSUE THREAD

**Issue by drakehawke** [Facepunch/garrysmod-issues#1850]
```lua
			self.CameraFrame.PaintOver = function( pnl )

				if not IsValid( pnl.Entity ) then return end
				camdata.x = pnl.x + 5
				camdata.y = pnl.y + 30
				camdata.w = pnl:GetWide() - 10
				camdata.h = pnl:GetTall() - 35

				camdata.angles = pnl.Entity:GetAngles()
				camdata.origin = pnl.Entity:GetPos() + pnl.Entity:GetAngles():Forward() * 16

				IN_CAMERA = true

				render.RenderView( camdata )

				IN_CAMERA = false

			end
```

Worked fine before the update. Now the rendered view is fine but the main screen becomes:
![](http://puu.sh/gtxww/e6827c421f.jpg)

Couldn't see anything about render.RenderView in the changelog so I'm guessing it's a bug.

**Comment by robotboy655** [comment]
This is caused by halo library changes by @wiox 

https://github.com/garrynewman/garrysmod/commit/0768920d04f4d7eb9111a65ae685439216c3590b

**Comment by wiox** [comment]
Copy the fixed file to your server for a quick fix.
