### ISSUE TITLE
TTT Disappearing Guns

### ISSUE THREAD

**Issue by BuilderGaming** [Facepunch/garrysmod-issues#1853]
This has happened ever since teh update. It doesn't just happen with my Sleek Weapon Base guns, it happens with the base TTT guns. Heres a video
https://www.youtube.com/watch?v=MaHFxqo6Xhk&feature=youtu.be

**Comment by robotboy655** [comment]
It is caused by the addon your guns come from. And this is not a place to get help / report TTT bugs

**Comment by BuilderGaming** [comment]
Sorry about that. I saw TTT updates in gmod respitory

**Comment by thegrb93** [comment]
Lots of people are getting this bug so it isn't the addon the guns came from.
http://facepunch.com/showthread.php?t=1455126

**Comment by robotboy655** [comment]
It doesn't happen in Vanilla TTT without any addons.

**Comment by thegrb93** [comment]
It doesn't happen consistently.

**Comment by BuilderGaming** [comment]
Happens on SeriousTTT with M9k sometimes. 95% im fine though

**Comment by robotboy655** [comment]
I think people on Facepunch figured out why it happens, hopefully it will be fixed soon enough.
