### ISSUE TITLE
Game crashes after blue loading screen. 

### ISSUE THREAD

**Issue by OctopusPlaya** [Facepunch/garrysmod-issues#1859]
I'm using a distro called Zorin 9 64-Bit. I would like to upload a crash report but I don't know where they are located with Linux.

**Comment by robotboy655** [comment]
This is a known issue with Linux, no need to multiply the tickets.

**Comment by Random0824** [comment]
well are you going to fix it?

**Comment by TheFreeman193** [comment]
I believe it's being worked on, and there's no ETA at the moment.

**Comment by Random0824** [comment]
Hopefully it's soon, i wanna play me some gmod.

**Comment by OctopusPlaya** [comment]
It looks like there's time to update Rust but no time to fix Garry's Mod. Oh well, I guess we're just going to have to sit back and "wait for Kilburn" to fix it.
