### ISSUE TITLE
Garry's mod virus 

### ISSUE THREAD

**Issue by Hicksfamily56** [Facepunch/garrysmod-issues#1860]
My virus scanner found a virus on here so now I can't play can you send me my copy or somthing like that

**Comment by TheFreeman193** [comment]
This is likely a false positive. What did the scanner report? If your antivirus has removed files, you should verify your cache. Right click on Garry's Mod in the Steam library -> Properties -> Local Files -> Verify Integrity of Game Cache.

**Comment by Hicksfamily56** [comment]
Thx I will try
