### ISSUE TITLE
Garry's Mod Doesn't Download Certain Addons

### ISSUE THREAD

**Issue by ColdRamenz** [Facepunch/garrysmod-issues#1862]
I looked all over for issues like this but none were the same as mine (from what I've seen). Anyways, I was browsing the workshop for some addons, once I found a few I liked I went ahead and subscribed to them and opened Gmod. The usual workshop download label appeared and downloaded a few of the addons. I went through my list of installed addons and couldn't find a few of them. I went back and subscribed to the again and they still didn't download. I even had a friend do this too and it did the same thing. Also, once I go back to the workshop, the addons become unsubscribed, almost as if I never subscribed to them in the first place. I'm not sure what to do about this issue. I'll put in some links to the addons for more information.

First Addon (note: yes, I downloaded the other addon to make it work, it still doesn't download): http://steamcommunity.com/sharedfiles/filedetails/?id=123178506&searchtext=Blue+Falcon
Second Addon: http://steamcommunity.com/sharedfiles/filedetails/?id=132003821&searchtext=Ridable+Heavy

**Comment by robotboy655** [comment]
Those are not addons, they are duplications. You cannot subscribe to Dupes.
