### ISSUE TITLE
engine.WriteSave can write outside of GMod directory.

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#1863]
![2015-03-11_04-54-45](https://cloud.githubusercontent.com/assets/3169571/6593040/d0cdf8ec-c7aa-11e4-8863-6dd462214b9c.jpg)

Using NTFS file system's 256 character limit I'm allowed to snip off the .gms of the filename to make a .exe :v 

I'm sure that with a few extra functions it'd be more than possible to download an executable off of a server, write it to a file, and use that shell execute function in the menu (which by the way servers can bridge to) to run it.

EDIT: 

The JPEG that the function writes overwrites the content you put in the .exe, but there's likely a way to change the conetnts of the file.

**Comment by wiox** [comment]
Can't write a valid executable with this for sure.

**Comment by TheFreezebug** [comment]
I noticed, when you snip off the extension for the .gms file you also end up killing the extension for the .jpg file which is written after :(, therefore overwriting the first file (which even then has the GMS header in it) , but still. This would be nice to have patched, I don't want somebody writing junk files over my drive.
