### ISSUE TITLE
Addon browser not sorted alphabetically

### ISSUE THREAD

**Issue by ElHyperion** [Facepunch/garrysmod-issues#1864]
The addon browser is supposed to sort the addons alphabetically, since the newest update, but it appears to be completely random and changes every time the game is restarted, even although there has been no change to the addons by either uninstalling or subscribing to new ones

**Comment by robotboy655** [comment]
The change only affects this:
![image](https://cloud.githubusercontent.com/assets/3299036/6604921/b28ee596-c834-11e4-95b2-0d939be9f62d.png)

**Comment by ElHyperion** [comment]
Well I did not only want to tell that it's not being sorted alphabetically, but also point out that it's completely random now, whereas before it was at least sorted by the subscription date

**Comment by robotboy655** [comment]
It never had any defined sorting.

**Comment by ElHyperion** [comment]
It was sorted by the date subscribed until this update. If you subscribed to an addon, it always appeared on the first page and newer addons were stacking on it. Maybe not intentionally defined but it was at least that way.

**Comment by robotboy655** [comment]
I repeat once again, for the special people, it had NEVER had any defined sorting method, and nothing was changed about the sorting method. Although, I probably should add some sort of sorting because random is not OK.

**Comment by ElHyperion** [comment]
And I repeat again, for the normal people, that my game had it always sorted like that (no matter if defined or not) but now, after the last update, it somehow isn't anymore.
Yes, it would be fine if there was some propper sorting again, please do so

**Comment by TheFreeman193** [comment]
@ElHyperion You should probably discuss this in [garrysmod-requests](https://github.com/Facepunch/garrysmod-requests) instead.

**Comment by robotboy655** [comment]
No need, I will add sorting now.

**Comment by robotboy655** [comment]
Actually, this appears to be impossible due to how pagination is done in the addon browser, the best I can do is to sort alphabetically content that is currently on the page.

What this means is that there will be items starting with A and ending with Z on every page.

**Comment by TheFreeman193** [comment]
I reckon it's still far better than it being completely arbitrary. It would certainly make arduously scouring through each page easier. :tired_face:
