### ISSUE TITLE
Certain Combine Incapable of doing melee damage

### ISSUE THREAD

**Issue by TheMrFailz** [Facepunch/garrysmod-issues#1865]
Simply put, the standard combine soldier* and both variants of the prison guard are incapable of doing melee damage (their gun butt hit when you are too close to them) in singleplayer (not tested in MP). Elite Combine, zombies, etc. are however, capable of doing melee damage.

Extra: I don't have anything mod wise that effects combine specifically.

*The standard combine soldier does appear to occasionally be able to do melee damage. Prison guards however, cannot.

**Comment by robotboy655** [comment]
Cannot confirm in sandbox. Your situation could be possibly related to #1820
