### ISSUE TITLE
Strange Viewmodel and GravGun crash (without any errors)

### ISSUE THREAD

**Issue by XenMix** [Facepunch/garrysmod-issues#1867]
Please look at: http://facepunch.com/showthread.php?t=1455098&p=47301325#post47301325

**Comment by thegrb93** [comment]
Loads of people connecting to my server have been getting this too. It doesn't happen to me at all though. Might be related to. https://github.com/Facepunch/garrysmod-issues/issues/1842

**Comment by Yuri6037** [comment]
I get not exactly the same : when you equip GravGun, i got an Access Violation on HL2.exe. This occures only when all my first person models are completely invisible. At the inverse, when my first person models shows, the Access Violation does not happen.
Note : The access violation appears with physgun, tool gun, and the personal shield of Stargate Carter Addon Pack too.

It seams that only Hands weapons are not causing any Access Violation.

**Comment by robotboy655** [comment]
Test the Dev branch ( http://wiki.garrysmod.com/page/Dev_Branch ), it should be fixed there. Same goes for #1842

**Comment by Yuri6037** [comment]
So the DevBranch works, but not on all servers : 
- On my SRCDS local server, it crashes at Workshop Complete and after 3 minutes it says HL2.exe has stopped working, windows is searching a solution to the problem.
- On TSCM Stargate server you need to wait 2 minutes at Workshop Complete, but it works after.

**Comment by Yuri6037** [comment]
I forget to add the first person models invisible problem is partialy solved : when another player connects to the server all your first person models becomes invisible. You'll need to kill you ("kill" in Source Engine console) to be able to view them again.

**Comment by robotboy655** [comment]
Do not connect to non dev branch servers from dev branch.

**Comment by Yuri6037** [comment]
Ok that's worth !!! I just downloaded Dev Version on my server, and now there's randomly some Access Violation client side !!

**Comment by Yuri6037** [comment]
Now that's better it begans to crash everytime I pickup my GravGun !!!

**Comment by robotboy655** [comment]
Are you joining from Dev branch client to Dev branch server? And nobody else is that is not on Dev is joining? Do ```lua_run print(BRANCH)``` to verify that you, and your server are on Dev

**Comment by Yuri6037** [comment]
I'm on the dev branch server and client !

So visibly you need a prove of the crash on dev branch. I just made a video I'm currently uploading. However this may take up to 1 hours and 15 minutes exactly to upload

**Comment by Yuri6037** [comment]
This is the video : https://www.youtube.com/watch?v=7ajaSLerI_c&feature=youtu.be

The ZIP containing all dumps : http://dlsrv.sldt-team.net?public_dl.php?file=gmod_client.zip

**Comment by robotboy655** [comment]
You forgot the part where you show that you are running Dev branch on both server and client.

**Comment by XenMix** [comment]
Ok Yuri, j'ai la solution, tu dois être sous debian, réinstalle ta machine sous Ubuntu 12.04 ! ;)

**Comment by XenMix** [comment]
up. (edited)

**Comment by Yuri6037** [comment]
Ok I have a way to repoduce this issue : 
Requirements : 
- A good computer (than runs SRCDS + GMod client together),
- SRCDS development branch for Garry's Mod,
- GMod Client development branch.
Steps to reproduce : 
- Connect first to your local SRCDS server,
- Everything works fine,
- Reconnect back to the server,
- Now, wow no longer any first person models,
- Take your GravityGun in hands,
- Last, enjoy the Access Violation you just got !!

**Comment by LittleLou** [comment]
Still happens, even with the patch.
