### ISSUE TITLE
givecurrentammo acting weird on listen server

### ISSUE THREAD

**Issue by FeldrinH** [Facepunch/garrysmod-issues#1872]
When you use givecurrentammo on a listen server (haven't tested on dedicated server) it always gives the ammo to the host of the listen server, no matter who ran the command.
GMod 2015.03.05

**Comment by robotboy655** [comment]
What is givecurrentammo and why are you reporting it here?

**Comment by Bo98** [comment]
Console command.

**Comment by robotboy655** [comment]
Just looked at the source code, it is not supposed to give the ammo to anybody but the first player on the server. ( Player with Index of 1 )

Since it is defined with other singleplayer commands, guess what it is used for. Either way, you can easily replicate the command with Lua.
