### ISSUE TITLE
Every gmod server is crashing

### ISSUE THREAD

**Issue by McSniper1215** [Facepunch/garrysmod-issues#1873]
The title says it all. Not "every" but most. 

I know 6 professional sevrer owners who are completely lost and their player base is dying right now. 

We fixed all errors we could find, results, failure.

**Comment by thegrb93** [comment]
"professional" lol. Everyone knows there's crashing. This ticket helps nothing.

**Comment by McSniper1215** [comment]
Ehh whatever. Might as well push Garry to try to fix it
