### ISSUE TITLE
Open Console in Game - Crash

### ISSUE THREAD

**Issue by Boogeyfan** [Facepunch/garrysmod-issues#1874]
Hello also i have problems if i open the console in game my game crashes and also i have some strange texture bugs, here is the console log and how can i post the crash log? I also cant play Garry's Mod anymore because of that bug and because i don't know what i should do now. I hope you can help me or maybe fix this bug in a further update. I never had this problem before the update, if you can't help me i can't play it anymore.

Initializing Awesomium..
No Kinect SDK
Lua JIT is DISABLED!
Unknown command "cl_thirdperson"
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Unknown command "hud_showemptyweaponslots"
Unknown command "sv_backspeed"

**Comment by daunknownman2010** [comment]
That small Console log is nothing, it's what you normally see when you start the game up.

**Comment by Boogeyfan** [comment]
How to post the right log here?

**Comment by Commodore64Hank** [comment]
Hi.

Try this fix.

Unsubscribe from all addons on gmod.

Next, go to Steam/Steamapps/Garry's mod/ garrysmod and delete your addons folder. (You NEED to unsubscribe from your addons, please.)

After this, load up gmod and try the console, if that does not work, validate the files.

If it still doesn't work, try a reinstall of gmod (No backups.) 

If that doesn't work, then update your computer, get ccleaner and try and fix your computer, or stop running on a commodore64 if you are still using one.

Hope that helped.

**Comment by Boogeyfan** [comment]
Thank you very much but it didn't helped. I tried everything deleted addons and folder. Reinstalled gmod updated my computer and more. It still shows:

Initializing Awesomium..
No Kinect SDK
Lua JIT is DISABLED!
Unknown command "cl_thirdperson"
JOY_AXIS_X: mapped to Turn (absolute)
JOY_AXIS_Y: mapped to Look (absolute)
JOY_AXIS_Z: unmapped
JOY_AXIS_R: mapped to Forward (absolute)
JOY_AXIS_U: mapped to Side (absolute)
JOY_AXIS_V: unmapped
Advanced Joystick settings initialized
Unknown command "hud_showemptyweaponslots"
Unknown command "sv_backspeed"

I can only hope that the developers can fix this because i think its a developement bug.

**Comment by andrewarmy21** [comment]
I think I know the problem.

I think if you using -dxlevel 80 or 81 (haven't tested with 90), You can crash if you open Consloe in game.

I have this problem too but it now fixed for me.

How to fix it? 

1. Go to Garry's Mod.

2. Press Right Mouse on Garry's Mod

3. Press Properties

4. Press lauch settings

5. Type -dxlevel 90 or 91.

I hope this fix the problem!
