### ISSUE TITLE
I have a problem this started happening when gmod updated 

### ISSUE THREAD

**Issue by Diamondzislife** [Facepunch/garrysmod-issues#1878]
when I would go to my tool gun some time it would start chance for stacker to material and back and fourth and when I would try to change to my physgun or any other weapon it would just keep switching back to the tool gun right away and i even killed my self and it would still do it the only way I have found it by rejoining and any one know how to fix it is annoying to keep rejoining when this happens pls help me

**Comment by robotboy655** [comment]
Already fixed for next update.
