### ISSUE TITLE
Stucked on Tool Gun

### ISSUE THREAD

**Issue by cr0coDiL** [Facepunch/garrysmod-issues#1879]
Sometime you will get stuck with Tool Gun in your hands. I didnt see any errors in console. I tried respawn or giving weapons by console. Only reconnect worked for me. If it ´s already reported sorry I didnt notice it. Also Can I ask about probably time of hotfix?

**Comment by TheFreeman193** [comment]
This has been reported already and should be fixed on the dev branch. #1854
