### ISSUE TITLE
Hammer views rendering improperly

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#1880]
The Garry's Mod hammer does at least open normally without crashing, but when opening maps it renders everything very strangely. Using latest update.
![ss 2015-03-14 at 12 48 48](https://cloud.githubusercontent.com/assets/8015170/6652166/c79a24ee-ca48-11e4-9579-ea78166bb04a.png)

Specs, if important:
Windows 8.1
Intel i7 Quad-Core
8 GB DDR3
1TB HDD
AMD Radeon HD 6770M Series - 512mb GDDR5

**Comment by robotboy655** [comment]
Must something wrong on your end or the .vmf you are trying to load?
![image](https://cloud.githubusercontent.com/assets/3299036/6652227/0705374a-ca71-11e4-8123-724d3c9d8688.png)

**Comment by imp0se** [comment]
I tried multiple VMF files for different maps, and they all yield either that result or this: 
![ss 2015-03-14 at 01 34 57](https://cloud.githubusercontent.com/assets/8015170/6652375/074c436e-ca4f-11e4-8be1-11ed5da4dcb0.png)

**Comment by imp0se** [comment]
Only lightmap grid camera mode works, all other modes will cause the camera to bug out and freeze. All point entities appear obsolete. Every view point (top,right,left) appear at very strange angles.
![ss 2015-03-14 at 05 10 20](https://cloud.githubusercontent.com/assets/8015170/6653267/6460ba94-ca6d-11e4-9916-afe43d9d64db.png)

**Comment by robotboy655** [comment]
Try validating GMod? Maybe your Hammer settings are broken?

**Comment by imp0se** [comment]
My Hammer settings in that screenshot are the same settings I use in other game Hammers. Validating did nothing.

**Comment by robotboy655** [comment]
Try the hammer from Dev branch, it is updated to the latest version.

**Comment by robotboy655** [comment]
Assuming it is fixed for you then.
