### ISSUE TITLE
Hammer sends Steam "In-game Garry's Mod"

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#1881]
Not too big of a deal, but when Hammer is launched it says that you're in-game Garry's Mod.
![ss 2015-03-14 at 02 24 23](https://cloud.githubusercontent.com/assets/8015170/6652561/e9e4a8f0-ca55-11e4-8540-2732980c0fd7.png)

**Comment by cr0coDiL** [comment]
... This small bug cant kill anyone :D, but current condition of garrysmod can...

**Comment by kulcris** [comment]
the ability to launch garrysmod while hammer is open would be nice without having to compile a map

**Comment by yupi2** [comment]
@kulcris That's not something GMOD can fix as that's steam related. You can probably start Hammer from it's executable (wherever it's located) and then steam probably wouldn't complain about starting another game while it's open.

**Comment by kulcris** [comment]
No it says its gmod and the game is already running

**Comment by imp0se** [comment]
@yupi2
No, I launched Hammer from the executable. That's the only way AFAIK.

**Comment by robotboy655** [comment]
You can launch GMod First and then launch Hammer.

**Comment by robotboy655** [comment]
I figured a fix, remove steam_appid.txt from the folder Hammer.exe is in. Let me now if it affects GMod or GMPublish.

**Comment by robotboy655** [comment]
This does break GMPublish...

**Comment by neico** [comment]
From the start, steam_appid.txt was only supposed to be a development tool to quickly test things, it shouldn't be ever relied upon nor shipped to end users...

Of course this changes when it comes to dedicated server, as those don't have a steam client they need that file to know which appid they're supposed to emulate...

From the steamworks docs (the following below also applies to SteamAPI_RestartAppIfNecessary which has a seperate doc via header comments):

## Activating the API at run-time
Before any functions can be used, first SteamAPI_Init() must be called.

* A return of true indicates all required interfaces have been acquired and are accessible.
* A return of false indicates one of two conditions:
	1. The Steam client isn't running. A running Steam client is required to provide implementations of the various Steamworks interfaces.
	2. The Steam client couldn't determine the AppID of game. Make sure you have Steam_appid.txt in your game directory.
	**Note**: When you launch from Steam, Steam will automatically know the AppID of your game. When developing, you need to hint this to Steam with a text file. Create the text file steam_appid.txt containing only the AppID.

******

There's an alternative to that file: the **SteamAppId** environment variable, if you set it locally for GMPublish before initializing the steam api then you can avoid using the text file...

**Comment by robotboy655** [comment]
:+1:
