### ISSUE TITLE
1x1 Tile in Center of Textscreen, Blocks Text

### ISSUE THREAD

**Issue by Storeback** [Facepunch/garrysmod-issues#1882]
Hello everyone! In advance, thanks for taking the time to try and sort out this issue.

Whenever I, or another player places a textscreen (in any server, not one in particular) there is a 1x1 general gray block that covers a large portion of texts.

I am aware that there is an "invisible" square that is suppose to be there so it is movable with a physgun, but the square I am seeing is solid and blocking the text.

Any advice is much appreciated!

**Comment by robotboy655** [comment]
This is not a place to report bugs of 3rd party addons.

**Comment by Storeback** [comment]
@robotboy655 Could you redirect me to a place that could?

**Comment by robotboy655** [comment]
Report it to addon author or server owner or something.
