### ISSUE TITLE
Framerate issues.

### ISSUE THREAD

**Issue by DJSpeed** [Facepunch/garrysmod-issues#1883]
Before, I could play the game on the highest settings max frames, one day me and my friends were playing gmod, I had to go and restarted gmod, I came back to find that after turning on my computer and starting gmod, I lagged for NO REASON, I just dropped frames, I tried unsubscribing all my add ons and REINSTALLING GMOD, but nothing but lag. I used to be able to play at 300 frames I think, with max settings. Now Im playing at 30-40 ish fps.
What the hell happened?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
