### ISSUE TITLE
Crashing after update on March 9, 2015

### ISSUE THREAD

**Issue by SORguy25** [Facepunch/garrysmod-issues#1884]
Ever since the update on March 9, 2015, I have had issues occurring over the new fonts, GAME NOT LOADING.  I am using Mac as my platform and whenever I try to launch the app, and error code shows up-FT_New_Memory_Face failed. font:Arial error:85.  This is driving me crazy and I saw other people with the same issue. Please Help!!

**Comment by robotboy655** [comment]
Already reported.
