### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by L0sted** [Facepunch/garrysmod-issues#1885]
after update when i start game it gives 

 failed to dlopen /home/theext4/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/bin/materialsystem.so error=/home/theext4/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/bin/materialsystem.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
 failed to dlopen /home/theext4/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/bin/gmod_audio.so error=/home/theext4/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/bin/gmod_audio.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
 failed to dlopen /home/theext4/.local/share/Steam/steamapps/common/GarrysMod/GameUI.so error=/home/theext4/.local/share/Steam/steamapps/common/GarrysMod/GameUI.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога

Нет такого файла или каталога - No such file or folder

Kubuntu 14.10 X64, GeForce 760

**Comment by robotboy655** [comment]
Linux crashes on startup for everyone right now, wait for an update.
