### ISSUE TITLE
Linux support broken with latest update:

### ISSUE THREAD

**Issue by LiNuX4tHeWiN** [Facepunch/garrysmod-issues#1886]
every other Ubuntu/Linux i have talked to has had issues.
plz read EVERYTHING http://ubuntuforums.org/showthread.php?t=2268685

**Comment by gamax92** [comment]
Also experiencing this issue.
Garry's mod starts, shows the loading screen with "Loading" at bottom right, then closes.

**Comment by robotboy655** [comment]
This is already reported numerous times, no need to re report this.
