### ISSUE TITLE
Mac Issues

### ISSUE THREAD

**Issue by asianboi98** [Facepunch/garrysmod-issues#1887]
Since the new update of Garry's Mod, 2015-03-05, trying to play multiplayer has become a problem, it would crash every so often and when the server map changes. I've tried removing all add-ons, deleting and re-installing Garry's Mod, and it would still crash. It was never like this before this new update.

**Comment by robotboy655** [comment]
This is already reported 10 times, no need to report again. Wait for an update that fixes this.
