### ISSUE TITLE
Cannot move or remove effects after loading a saved game

### ISSUE THREAD

**Issue by JusMahBASSCannon** [Facepunch/garrysmod-issues#1889]
Hey,

I'm experiencing another problem with the Save/Load mehcanic in the spawnmenu. This is different than the T-Bone ragdolls, and seems to be worse.

My general use for the saves is for saving my place in comics, so I can continue at any time. So naturally, I'll need to move or remove some things as it progresses, and my problem is that any effects that I save on cannot be removed or moved when I load into the save once again. It seems to duplicate itself, making a completely isolated copy that can not be moved or removed by any means, not even with admin settings or the drop-down menus.

![2015-03-15_00050](https://cloud.githubusercontent.com/assets/11497161/6661744/5b766d94-cb66-11e4-9a73-ac30d0397b59.jpg)

![2015-03-15_00052](https://cloud.githubusercontent.com/assets/11497161/6661750/7d16e802-cb66-11e4-9d65-bc03e57d4473.jpg)

The immovable duplicate is on the top, while the movable orignal copy is on the bottom.

Doing anything with the movable copy does not affect the immovable copy at all, and removing the movable copy using the drop-down menu causes the original copies to disappear, as seen here:

![2015-03-15_00054](https://cloud.githubusercontent.com/assets/11497161/6661774/ed28d4ac-cb66-11e4-9398-4451440cff37.jpg)

Is this a Garry's Mod error, or an error with my addons (I have a lot, so I wouldn't be surprised)?

I am running a Windows 8.1 64-bit, and my Garry's Mod update is '2015.03.05'.

Thanks, 
-Devin.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

I just tested it and it works properly for me. That means something is wrong on your side. ( Or the models )
