### ISSUE TITLE
All HTML Panel callbacks/members not working as described in scriptedpanels.lua

### ISSUE THREAD

**Issue by SimonSchick** [Facepunch/garrysmod-issues#189]
See right here:

  ------
   HTML
  ------
  
  PANEL::StatusChanged( text )
	The text in the status bar has changed
	
  PANEL::ProgressChanged( progress )
	Loading progress changed
	
  PANEL::FinishedURL( url )
	Finished loading a specific URL
	
  PANEL::OpeningURL( url, target )
	Page wants to open URL.
	Return true to not load URL.
	
 ---------------
 - Member Vars -
 ---------------
	
  All
	Hovered			- 	bool (true if panel is hovered)
	
  Button
	Selected		-	bool (true if button is selected)
	Depressed		-	bool (true if button is depressed)
	Armed			-	bool (true if button is hovered)
	DefaultButton	-	bool (true if button is default button)
	
  HTML
	Progress		-	float (Progress bar amount between 0-1)
	Status			-	string (Status Bar Text)
	URL				-	string (Current URL)

**Comment by willox** [comment]
Awesomium doesn't exactly offer __proper__ events to use for these. Instead I'm going to add Panel hooks for similar methods under different names while I have the chance.

```lua
--
-- Called when this panel's DOM has been set up
-- You can run JavaScript in here
--
function PANEL:OnDocumentReady( url )

--
-- Called when this panel tries to open a child (such as a popup or new tab)
--
function PANEL:OnChildViewCreated( sourceURL, targetURL, isPopup )

--
-- Called when the title of the loaded document has changed
--
function PANEL:OnChangeTitle( title )

--
-- Called when the target URL of the frame has changed, this happens when you hover over a link
--
function PANEL:OnChangeTargetURL( url )
```

**Comment by Bo98** [comment]
No way to tell when it starts loading? DHTMLControls depends on that.

Also, is there any fix for :Stop() and :Refresh() functions?

**Comment by willox** [comment]
I'll get OnBeginLoadingFrame, OnFailLoadingFrame, and OnFinishLoadingFrame working before the next update (but only for the main frame).
