### ISSUE TITLE
Singleplayer mapselection

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#1890]
I don't know why it got removed or if its a bug that its removed.
But since the last update you arent able to open a singleplayer game via double click on a map icon.
I think that was very useful and I'm not sure why it got removed.

**Comment by Yuri6037** [comment]
Yes agree too, it was a good feature...

**Comment by robotboy655** [comment]
Fixed https://github.com/garrynewman/garrysmod/commit/c552b5b91ffdedac6fc9e35c64e08b0e1cdca7a2
