### ISSUE TITLE
linux servercrashs

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#1892]
Since the update my server keeps crashing like every hour.
Since the hotfix of the update my server runs better but the stability issues arent fixed.
It crashs with the message "Segmentation Fault". Since the update.
I don't know how to fix it, I don't get lua errors, clientside errors or other responses from the server. 
It just crashs and autorestarts.
Some random props spawns crash it, car spawns crash it.
I don't know how many things my server could actually crash.

(I opened a new issue, because the old one was before the hotfix)

**Comment by robotboy655** [comment]
There's no need to multiply issues.
