### ISSUE TITLE
Crash on startup in linux

### ISSUE THREAD

**Issue by ILOVEPIE** [Facepunch/garrysmod-issues#1895]
Here's the output of running it with gdb:

    Program received signal SIGSEGV, Segmentation fault.
    0xf0d553d3 in ?? ()
      from /home/username/.local/share/Steam/SteamApps/common/GarrysMod/bin/vguimatsurface.so

there's a lot of spam above it about missing debug info but apart from that there's nothing of note other than the output above.

**Comment by ILOVEPIE** [comment]
This bug is likely related to the new rendering system.

**Comment by ILOVEPIE** [comment]
oops accidentally closed

**Comment by robotboy655** [comment]
#1833
