### ISSUE TITLE
Ingame broken text fonts

### ISSUE THREAD

**Issue by Raxsyz** [Facepunch/garrysmod-issues#1896]
Hello, I'm reporting one issue that occurred in the last update of Garry's mod. My game got updated just yesterday and since then the issue occurred. It broke ingame text fonts specifically the ones that appear in C menu.

Here's some screenshots:

![2015-03-17_00001](https://cloud.githubusercontent.com/assets/11514085/6681241/b75dace6-cc63-11e4-83be-bef57a60d207.jpg)

![2015-03-17_00002](https://cloud.githubusercontent.com/assets/11514085/6681263/f6155100-cc63-11e4-90db-6a7007f35761.jpg)

The fonts are completely invisible, only when I highlight them with cursor the fonts are there but barely visible. Addons that use the same text fonts also reports the same issue, however all other texts in the game (the Q menu, pause menu... you name it) appear to be fine.

I've tried disabling all of the addons, verify integrity of game cache, restart steam, restart computer... The issue is still there. :/

**Comment by robotboy655** [comment]
It is known, it will be fixed in the next update.
