### ISSUE TITLE
DataTable warning: player: Out-of-range value in SendPropFloat

### ISSUE THREAD

**Issue by PotcFdk** [Facepunch/garrysmod-issues#1898]
So now that #1134 has been closed, I'd like to leave this here,
as I haven't been able to figure out if anyone with code access has ever taken a look at this.

To my understanding, the following warning
`DataTable warning: player: Out-of-range value (300.000000) in SendPropFloat 'm_angEyeAngles[0]', clamping.`
is [caused by outdated code](http://facepunch.com/showthread.php?t=1374457&p=44897245&viewfull=1#post44897245).

**Comment by wiox** [comment]
Reproduction for testing any applied fix
```lua
hook.Add( "CreateMove", "", function( cmd ) 
    cmd:SetViewAngles( Angle( 91, 0, 0 ) )
end )
```

**Comment by robotboy655** [comment]
I'll commit a fix for this in Dev, but please test it thoroughly so it doesn't fuck up something.
