### ISSUE TITLE
SENTs are given a new Lua table after their creation

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#1899]
``` lua
hook.Add( "OnEntityCreated", "", function( ent )
    local tab = ent:GetTable()

    timer.Simple( 0, function()
        assert( ent:GetTable() == tab )
    end )
end )
```

This means if you set a variable on a SENT in the OnEntityCreated hook, it will later be lost.
SWEPs are affected too.

**Comment by EstevanTH** [comment]
I can confirm. If you try to use the table during CalcView, you will have problems once.

**Comment by robotboy655** [comment]
Should be fixed in Dev.
