### ISSUE TITLE
net.Write/ReadUInt still doesn't use unsigned integers

### ISSUE THREAD

**Issue by Person8880** [Facepunch/garrysmod-issues#1903]
Server OS: Ubuntu 14.04.1

Writing a 32 bit unsigned integer caps out at 2147483648, when it should be able to go up to 4294967295. On Windows (at least in a listen server) this seems to work as expected.

**Comment by robotboy655** [comment]
You will have to post some test code/console output as a start.

**Comment by Person8880** [comment]
```lua
net.Receive( "unsigned_int_test", function( Len )
	print( Len, net.ReadUInt( 32 ) )
end )

if SERVER then
	util.AddNetworkString( "unsigned_int_test" )
end

concommand.Add( SERVER and "unsigned_int_sv" or "unsigned_int_cl", function( Ply, Command, Args, String )
	net.Start( "unsigned_int_test" )
		net.WriteUInt( 4294967295, 32 )
	if SERVER then
		net.Send( Ply )
	else
		net.SendToServer()
	end
end )
```

Windows listen server output:
```
] unsigned_int_sv 
32	4294967295
] unsigned_int_cl
32	4294967295
```

Linux dedicated server output:
```
] unsigned_int_sv
32	2147483648
] unsigned_int_cl
32      4294967295
```

So Windows client is writing a correct integer to the server, but the Linux server is not writing a correct integer to the client.

**Comment by robotboy655** [comment]
Is that 32bit OS? Can you test this on 64bit vs 32bit?

**Comment by Person8880** [comment]
The server's 64 bit, and so is the Windows client.

**Comment by robotboy655** [comment]
Can you try testing this on 32bit Linux?

**Comment by Person8880** [comment]
Not easily, no. Reinstalling on the server isn't an option as its in constant use.

Maybe someone else can pitch in if they have an existing 32 bit Linux installation, though I doubt many people use 32 bit anymore.

**Comment by robotboy655** [comment]
I have added some debug output to Dev branch, so please test when it updates. The debug message will be something like ```Sizeof: numbers``` on client when ReadUInt is called, please make do your test again and post back the results once next Dev branch update is published to Steam.

**Comment by Person8880** [comment]
Sorry for the delay, here's the output:
```
] unsigned_int_sv
Sizeof: 4 4 4 32 2147483648 
32	2147483648
unsigned_int_cl
Sizeof: 4 4 4 32 4294967295 
32      4294967295
```

**Comment by meepdarknessmeep** [comment]
you are missing a bit!!

**Comment by robotboy655** [comment]
I think I know why it happens, I have been looking at it from the wrong side.

**Comment by robotboy655** [comment]
I have committed a possible fix, please test once the Dev branch updates. ( See "Last Updated" here: https://steamdb.info/app/4000/ )

**Comment by Person8880** [comment]
Seems to have fixed it, thank you.

**Comment by robotboy655** [comment]
It was writing the number as an signed integer, the weird part why it did work on windows, but oh well.
