### ISSUE TITLE
file.Open doesn't support all standard modes

### ISSUE THREAD

**Issue by PotcFdk** [Facepunch/garrysmod-issues#1905]
The [wiki page](http://wiki.garrysmod.com/page/file/Open) says:
`string fileMode`: `The mode to open the file in, use this page` (http://lua-users.org/wiki/IoLibraryTutorial) `for reference of what modes are possible. For binary files, additional open methods are listed here.` (http://www.lua.org/pil/21.2.2.html)

The modes listed are:
```
"r": read mode (the default);
"w": write mode;
"a": append mode;
"r+": update mode, all previous data is preserved;
"w+": update mode, all previous data is erased;
"a+": append update mode, previous data is preserved, writing is only allowed at the end of file.
```

However, what I'm observing, is that none of the `+`-modes work (i.e., `file.Open` returns nil).
Is this intended or a bug?

**Comment by robotboy655** [comment]
Updated wiki with what is allowed.

**Comment by PotcFdk** [comment]
So how am I, for example, supposed to modify a single byte of a file? Read it all into memory and write it back to disk? That'd be pretty silly, especially for "huge" files.

**Comment by robotboy655** [comment]
You wouldn't be able to with any + modes. And this is not a place to post requests.
