### ISSUE TITLE
NetworkVars overlapping

### ISSUE THREAD

**Issue by DevZzzz** [Facepunch/garrysmod-issues#1906]
I have been debugging with NWVars, net., and now this.. It seems that NetworkVars is broken. Here's why..

Here I setup my Data Tables.
```Lua
function ENT:SetupDataTables()
	self:NetworkVar("String", "teststring", "TestString")
	self:NetworkVar("Int", 0, "TestInt")
	self:NetworkVar("Float", 0, "TestInt2")
end
```

When I set these on serverside - example
```Lua
ent:SetTestString("boo")
ent:SetTestInt(5933)
ent:SetTestInt2(15) -- This will override all other variables assigned to this entity that uses nwkvar
```

What they would return
String returns "boo"
Int returns 15
Int2 returns 15

This happens with bool also. If I added another string variable and set it under the others, it will replicate the int variable and will set the first string variable to the string you wanted for the second string variable. Confusing eh?

I tried reading them in the same order I set them and no changes. Is something wrong on my side or is this a bug?

**Comment by robotboy655** [comment]
Cannot confirm:
```
boo	5933	15
boo	5933	15
```

You have a problem in your code BTW, second parameter cannot be a string, it must be a number.

**Comment by DevZzzz** [comment]
I only made that mistake while rewriting it on here.
I just retried everything with all Int vars.
```Lua
555 555 555
555 555 555
555 555 555
```

**Comment by robotboy655** [comment]
You gave them all the same slot.

**Comment by DevZzzz** [comment]
Ah okay. The wiki page I was viewing is wrong. It gives two of the same variables the same slot - So I assumed that it was a default value.

http://wiki.garrysmod.com/page/Networking_Entities
```Lua
function ENT:SetupDataTables()

	self:NetworkVar( "Float", 0, "Amount" )
	self:NetworkVar( "Vector", 0, "BloodPos" )
	self:NetworkVar( "Vector", 1, "UrinePos" )

end
```
Thanks anyway.
http://wiki.garrysmod.com/page/Entity/NetworkVar -- Should have been the one I needed to read.

**Comment by wiox** [comment]
Variables of different types may use different slots. Read NetworkVar's documentation properly.

**Comment by DevZzzz** [comment]
Again.. It does not say this in the first link.. Which I was using as a reference.
