### ISSUE TITLE
No human/combine NPC animations

### ISSUE THREAD

**Issue by Duracraft27** [Facepunch/garrysmod-issues#1912]
None of my human/combine NPCs have animations. They all stand in T position. I have tried reinstalling, disableing addons, and downloading all game content packs none fix it. I'm open to any ideas that may help. The problem started after joining a NutScript/clockwork server(not sure which one it was) and havnt been able to fix it since.

**Comment by robotboy655** [comment]
This not a place to get help. Get help @ http://facepunch.com/forums/16

**Comment by philxyz** [comment]
The background to this issue is described by "Big Bang" here: http://facepunch.com/showthread.php?t=894868&page=3
