### ISSUE TITLE
Problem with downloading resources from server

### ISSUE THREAD

**Issue by Jazzelhawk** [Facepunch/garrysmod-issues#1914]
So I've noticed that when downloading resources from a dedicated server it downloads them based on the names of already existing files and not their content.

For example, say I have a ``test.png`` file in an addon (serverside) and it is set to download as a resource with ``resource.AddFile`` it will download the file to the client correctly in the download folder. But if you edit that image in the download folder and rejoin the server it will not re-download the resource from the server.

I have also noticed that if I have the ``test.png`` file in a clientside addon as well as on the server, gmod will not download the server's version of ``test.png`` which means that it could well be outdated.

My guess is that it detects the files using filenames and downloads them if they do not exist. But wouldn't it be better if it checks their content too with a checksum hash or something?

**Comment by robotboy655** [comment]
That's how Source Engine works, don't expect it to change. That is why Workshop addons and WorkshopDL is superior.
