### ISSUE TITLE
Prop Hunt Disappeared 

### ISSUE THREAD

**Issue by Karlarei2003** [Facepunch/garrysmod-issues#1915]
So, I go to the bottom right and click on "Sandbox" to change it to "Prop Hunt" but it is gone.  The only things there now are "Sandbox" and "TTT".

-The game is updated.
-I've uninstalled and reinstalled Prop Hunt

Thanks in advance.

**Comment by robotboy655** [comment]
Pretty sure it is duplicate of #1904
