### ISSUE TITLE
Engine Error CFURLGetFileSystemRepresentation fucked up

### ISSUE THREAD

**Issue by darkmich** [Facepunch/garrysmod-issues#1919]
Garry's Mod version 2015.03.12

Running on OX X 10.10.2

When joining a multiplayer server with other people on it, a window pops up saying "Engine Error: CFURLGetFileSystemRepresentation fucked up". After OK is clicked, the beachball comes up and spins. Shortly after, the game crashes without warning. Multiplayer with no other people and single player seem to work OK. I've tried multiple servers and get the same error.

**Comment by robotboy655** [comment]
#1917
