### ISSUE TITLE
Issue downloading upgrade on OSX

### ISSUE THREAD

**Issue by gsweb** [Facepunch/garrysmod-issues#1922]
Been trying to download the 2015.03.09 release of Gary's Mod but progress refuses to go past 1%,  Have tried deleting local content, taking Steam client offline and restarting but still cannot progress pass 1% progress with an eventual timeout. Am running OS X version 10.10.2 with Steam client build Jan 25, 2014, API v012, package version 1390852599

**Comment by daunknownman2010** [comment]
I don't think it's a problem with the game if you're trying to download the update. It's probably the steam servers giving you a hard time.
