### ISSUE TITLE
GMod Serverlaggs and Crashs

### ISSUE THREAD

**Issue by advancedrazor** [Facepunch/garrysmod-issues#1924]
Every GMod server so far has issues with the newest (shitty) update.
My server keeps crashing 5,000 times a day.
I checked all my freaking addons and they dont have any errors.
Without playing with addons it crashs either alot.

The server laggs with an i7 4970k, how is that even possible.
Cause it uses only one core ending with shitty physics laggs and only problems.
Either my TTT server crashs the whole day, because ragdolls fly crazy around.. DAFUQ?
Noone fixes the BIG bugs like Physics bugs, cause its difficult (oh), just the little ones noone care about, without 1-2 developers, mostly these fixes are causing bigger bugs to happen, thats what I saw, All the updates this and last year was useless and caused just things to break which worked before. I mean I love the fucking game, so much however!

All are saying "Addon developers fault",
Some developers arent playing the game anymore, because of the annoying shitty bugs, which arent going to get even fixed.

* It sucks that it uses 1 core, fact.
* Even counter strike source with a dual core can better run as garry's mod.
* Its full of kiddys, because someone forgot to set the age in steam, that would be 18, cause its half life 2.
* It crashs 20 times a day without a error
* The Setholdtype error sucks either and IS HAPPENING ON THE STANDARD GMOD_FISTS!
* If everyone says anything about garry's mod, then 50 idiots come and fuck around with him.

Please garry, come back and save the game :(, in a few years theres nothing to save though.
I just want GMod 10 back!

**Comment by advancedrazor** [comment]
Wow thats so Invalid.
Youre 100% right.
Just telling the truth is always invalid in GMOD, aint it?

**Comment by robotboy655** [comment]
No, this is not a place to whine or criticize updates. This is a bug tracker. You can go and tell your truth @ http://facepunch.com/forums/15

**Comment by advancedrazor** [comment]
Its not whining, I just want back the gmod version which actually worked.
