### ISSUE TITLE
Lockup on TTT Round Start

### ISSUE THREAD

**Issue by Kalbintion** [Facepunch/garrysmod-issues#1925]
After the latest update to GMOD (2015.03.12), TTT round starts on my server lock up the server and the server fails to respond to any console commands and rcon is no longer responded to. Players are disconnected from the server after a connection issue timeout. This happens with and without any addons to the server from a collection. A clean install of the server files has the same results.

**Comment by Kefta** [comment]
Cannot replicate on vanilla dedi. Are you using dedicated or listen?

**Comment by Kalbintion** [comment]
Dedicated. Validation of files returned no issues on server nor client

**Comment by Kalbintion** [comment]
Why was this marked as closed?

**Comment by robotboy655** [comment]
Because we cannot reproduce this on our end, and it seems to be only happening to you, which leads us to believe that this is a problem on your side. Latest version of the game is 25.03.2015.

**Comment by Kalbintion** [comment]
This issue was happening on the 12.03.2015 version and posted about prior to the latest update, I will check to see if the issue persists on my end with this latest update.

**Comment by Kalbintion** [comment]
Still having this issue even with the latest update on a clean system. Unless there can be some reasonable doubt of it being gmod, I still highly suspect something going on with gmod or TTT itself that is causing this issue. This problem did not present itself until the 3/12 update.

**Comment by robotboy655** [comment]
Update your addons and get help @ http://facepunch.com/forumdisplay.php?f=65.

This is a single case, the error is on your side.

**Comment by Kalbintion** [comment]
The issue exists without any addons of any type, outside of the files gmod comes with. No attempts of getting addons is done when the server is initially ran, and this issue persists.

**Comment by Kefta** [comment]
Have you tried FULLY deleting your server and reinstalling fresh from SteamCMD?

**Comment by Kalbintion** [comment]
Yes I have, my apologies if this wasn't made clear from the last line in the initial report. I repeated my clean install attempts when I was told of the new version.

**Comment by Kalbintion** [comment]
I wish for this issue to be re-opened as I have still been experiencing this issue and have come across more information:

The server errors for line 628 of player.lua, it's code is net.Send(ply) instead of net.Send(victim) - this error doesnt seem to be the culprit ~~but it may be part of it~~. Another issue, which we (myself and some testers I have) believe to be the cause is the chat system. Whenever a message is sent, it says "Error: hook-PlayerSay returned a non-string!" - The crash isn't happening every single time, but when the server crashes, it's always immediately after a message has been sent by someone on the server but before I see anything in the console about it. We had thought about this in the past as it had happened a few times on the previous versions but figured it was just a fluke chance. With the current version and this repeatedly happening the chat thing seems to be more of a viable option.

And after further testing, it crashes consistently when someone is in Spectator mode (like joining the server mid-round) while a round has started and says something in ALL chat - team chat works just fine.

And to reconfirm, this is being tested on a brand new installation of TTT with no addons and no modifications of any kind and on a Dedicated Server via srcds.

**Comment by Kefta** [comment]
Download the one from the main GitHub. All of those issues have already been fixed

**Comment by Kalbintion** [comment]
Alright, the issue is in regards to the ttt_limit_spectator_chat convar being set to '1' - I will assume this particular issue was fixed as well?

**Comment by Kefta** [comment]
No, the issue was my previous implementation of the new chat system.
