### ISSUE TITLE
Update 15.25.03 Messed Up Networking

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-issues#1929]
So I was working on - believe it or not - redoing the system that an addon of mine uses for *networking*. I was planning on finishing today and pushing the update to the workshop. Then I realized that an update to Garry's Mod had just been released. I figured that I should test my addon one more time to make sure that no changes had been made that would break my addon. And sure enough, there were.

Something seemed very off with the way networked information on entities was being passed from Server to Client. Nothing would happen, then it would transmit, then I couldn't get it to change... it was weird. So I put together a simple lua script to find out what was wrong. It added two Global functions:

* <code>TestNetworking( Entity )</code> which sets a networked vector on an entity, checks its value on the Server, then tells the Client to check its value, and
* <code>ClearNetworking( Entity )</code> which clears the networked vector and then does the same thing.

**The script is below.**

*lua/autorun/testnw.lua*
```
local function TestNetworkedVector( ent )

	print( ent:GetNWVector( "testvector", false ) )

end

if ( SERVER ) then

	util.AddNetworkString( "testnetworking" )


--[[---------------------------------------------------------
		The function to set a NW Vector
-----------------------------------------------------------]]

	function TestNetworking( ent )

		print( "Server" )


--			Create a vector...

		local TestVector = Vector( 1.123456, 2.123456, 3.123456 )


--			Set it on the entity, networked...

		ent:SetNWVector( "testvector", TestVector )


--			Check it on the Server...

		TestNetworkedVector( ent )


--			Tell the Client to check it...

		net.Start( "testnetworking" )
		net.WriteEntity( ent )
		net.Broadcast( )

	end

--[[---------------------------------------------------------
		The function to clear a NW Vector
-----------------------------------------------------------]]

	function ClearNetworking( ent )

		print( "Server" )


--			Clear the NW Vector...

		ent:SetNWVector( "testvector", nil )


--			Check it on the Server...

		TestNetworkedVector( ent )


--			Tell the Client to check it...

		net.Start( "testnetworking" )
		net.WriteEntity( ent )
		net.Broadcast( )

	end

elseif ( CLIENT ) then

	net.Receive( "testnetworking", function( len )

		print( "Client" )

		local ent = net.ReadEntity( )


--			Check it on the Client, immediately...

		TestNetworkedVector( ent )


--			Check it again, after some time...

		timer.Simple( FrameTime( ) + 0.1, function( )

			TestNetworkedVector( ent )

		end )

	end )

end
```

I then launched Garry's Mod, started a single player game on Construct, and spawned a prop_physics entity.
![barrel1](https://cloud.githubusercontent.com/assets/5619290/6839141/4e86f7ec-d332-11e4-908d-4a990c41f5d3.png)
I Ran <code>TestNetworking</code> on the prop_physics entity *(using a timer to be sure it was run while the game was unpaused)*, and these were the console results:

```
Server
1.123456 2.123456 3.123456
Client
false
1.093750 2.093750 3.093750
```

**Oh no!** It would seem that the net message arrived *before* the networked vector did! and when the networked vector did arrive, it was different from what it originally was.
I am certain that none of these phenomena were present before the update.

Next, I ran <code>ClearNetworking</code> on the prop_physics entity, and these were the console results:

```
Server
false
Client
1.093750 2.093750 3.093750
1.093750 2.093750 3.093750
```

The networked vector was cleared on the Server as expected, but it wasn't on the Client, as shown by it still being there, even after the time interval. **I can't make it go away!**

Then I had an idea. I booted into Windows (which I had not been in since yesterday; I was in OS X), started Steam in offline mode (to avoid installing the new GMod update), launched the previous version of GMod (15.09.03), and repeated the same experiment. These were the results:

<code>TestNetworking</code>:
```
Server
1.123456 2.123456 3.123456
Client
1.123456 2.123456 3.123456
1.123456 2.123456 3.123456
```

<code>ClearNetworking</code>:
```
Server
false
Client
false
false
```

**The networked vector showed up *before* the net message, the vector wasn't changed, and when the networked vector was set to nil on the Server, it was cleared on the Client.**

There was a change! Is the change intentional, or a bug? If it was intentional please let me know. Thanks.

**Comment by robotboy655** [comment]
It is not guaranteed that if you send a net message first, it will be received first, that's how networking works.

As for precision problems with the OLD system which was reverted to in the latest update (25 March), it's most likely a problem with the OLD system, and if that's the case, it was imprecise all of the time before update on March 9th.

The new system is better, but it was too unstable so it was temporarily reverted.
