### ISSUE TITLE
MC Supp

### ISSUE THREAD

**Issue by advancedrazor** [Facepunch/garrysmod-issues#1931]
How about adding multicore support, since its gone all my servers are running on low resources and crash alot.
I dont even know why it got removed in gmod 12 or was it 11.
However could you simply add it as a option probably and default set it to 'false' and fix the crashs step per step. update by update.
So actually some folks can use it.
I would appreciate it alot.

Thanks for reading.

**Comment by robotboy655** [comment]
This is not a place to request things.

https://github.com/Facepunch/garrysmod-requests/issues/152 Already requested.
