### ISSUE TITLE
White Dr. Breen texture

### ISSUE THREAD

**Issue by titanic4** [Facepunch/garrysmod-issues#1932]
There's graphical bug with Dr. Breen model in Garry's Mod. He appears as he was "painted" white. http://cloud-4.steamusercontent.com/ugc/709654652717802721/0B30EAA541ED3A916F375A100959A1C466064683/

On Half-Life 2 Dr. Breen is displayed normally as seen here: http://cloud-4.steamusercontent.com/ugc/709655291416358610/DB34B8C0A0308938DD63C3A7128B5FD897308749/

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
