### ISSUE TITLE
Update Screwed Over Singleplayer

### ISSUE THREAD

**Issue by ElevenWords** [Facepunch/garrysmod-issues#1933]
I play a lot of singleplayer and I found a lot of problems when the newest update came out. If anyone is asking about why I play on singleplayer and why not on a server, that's not important at the moment. These bugs only happen on dxlevel 81. I cannot use dxlevel 91 because the card I have doesn't support it and I don't think I'll be getting a new one. These are the bugs I've encountered so far:
-Materials don't show/work
-The wireframe is not visible

I might have faced other singleplayer bugs but I can't remember.
Hope this is fixed

**Comment by robotboy655** [comment]
If you go to the store page, you'll see that the minimum required video card is a DX9 compatible one.

This is already reported @ #1839 but it may not be ever fixed.
