### ISSUE TITLE
Detecive mode seems to be disabled

### ISSUE THREAD

**Issue by tonnuminat** [Facepunch/garrysmod-issues#1937]
People are shown as "Spectator" immediatly when they die without someone identifying them. The TTT help page says that means detective mode isn't enalbed. But i have detectives enabled and it always worked until now and i didn't change anything.

The problem just appeared out of nowhere today. And like I said I didn't change anything the last weeks. I also have some problems with ulx that might be relevant since they occured at the same time: https://github.com/Nayruden/Ulysses/issues/440

**Comment by robotboy655** [comment]
This is not a place to get help or report TTT problems / bugs.

http://facepunch.com/forums/16
