### ISSUE TITLE
robotboy655 you need to look through these problems more thoroughly

### ISSUE THREAD

**Issue by ElevenWords** [Facepunch/garrysmod-issues#1938]
You closed my previous thread without even looking at problems other than the problem with materials. There's a problem with wireframe. Wireframe works on servers but not in singleplayer. It's a problem on dxlevel 81. Please go more in depth to this problem :)

**Comment by robotboy655** [comment]
Dxlevel 81 is your problem.

Also, if you want to be helpful at all, post more info other than "it doesn't work".

1 Problem per issue/thread/report.
