### ISSUE TITLE
Possible duplicator crash. (Mdmp included)

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#1943]
These two mdmp occured after someone used the adv_duplicator tool and I thought they would be interesting since they are 12MB each unlike the usual 90kB ones I'm used to seeing.

https://dl.dropboxusercontent.com/u/72472980/exec_sparkysandbox_20150330_212528_1_PureClass.mdmp
https://dl.dropboxusercontent.com/u/72472980/exec_sparkysandbox_20150331_060827_1_PureClass.mdmp

**Comment by robotboy655** [comment]
Those are also vphysics.dll crashes, but they go further into windows DLLs for some reason.

![image](https://cloud.githubusercontent.com/assets/3299036/6926189/4d35dc72-d7ed-11e4-882e-2c96962f27e2.png)

**Comment by robotboy655** [comment]
Your problems might also be caused by the plethora of launch parameters your server uses.

**Comment by thegrb93** [comment]
I don't have access to those as I am using NFO. I'll ask them and see if I can see what they are.

**Comment by robotboy655** [comment]
Yes, you should change your rcon pass.
Your command line is ```exec_sparkysandbox.exe -ip 66.150.214.126 +maxplayers 28 -debug -console -nocrashdialog -norestart +host_timer_spin_ms 0 +r_hunkalloclightmaps 0 -tickrate 33  -disableluarefresh -nojit +rcon_password "***" -authkey F898E5C4FB2D64B1BDACC3C28287F3B8 +host_workshop_collection 350367326 -game garrysmod```

**Comment by thegrb93** [comment]
Thanks. Please hide my authkey too please.

**Comment by wiox** [comment]
The secrecy of your key died when you uploaded the dumps, it seems. Get a new one.

http://steamcommunity.com/dev/apikey

**Comment by thegrb93** [comment]
Okay done. Thanks. Is it possible to upload a dump privately?

**Comment by thegrb93** [comment]
Is it also possible to tell if it is a physics crash or not? I would like to only report crashes that aren't physics crashes.

**Comment by robotboy655** [comment]
Open the .mdmp in Notepad++ and search "vphysics". You there are more than 2 hits, it is most likely a physics crash.

**Comment by thegrb93** [comment]
Okay will do.
