### ISSUE TITLE
Can't clear NWEntity vars.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#1946]
With the current stable garrysmod version,

SetNWEntity("mystring") will set the nwvar to NULL on the server, but the client will remain the original value.

SetNWEntity("mystring",NULL) will set the nwvar to NULL on the server and client, but idk if this actually clears the NW var.

**Comment by robotboy655** [comment]
I can confirm this, but how do we know this wasn't the case before this years update, so I guess this will not be looked into but will be instead fixed whenever new NWvars come back.
