### ISSUE TITLE
Jeep Freezing

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#1948]
I didn't see any issue open relating to this, but I think it is about time jeep freezing got fixed.

Basically, this code fails to freeze a jeep.
```
local count = jeep:GetPhysicsObjectCount()
for I = 0, count - 1 do
	local p = jeep:GetPhysicsObjectNum(I)
	if p:IsValid() then
		p:EnableMotion(false)
	end
end

```

**Comment by Jvs34** [comment]
#1723 
The crashes were related to vphysics, so tough luck.

**Comment by daunknownman2010** [comment]
VPhysics doesn't like it when you freeze the Jeeps and causes a crash. This applies to every single Source Engine game/mod.

**Comment by thegrb93** [comment]
VPhysics is pissing me off.
