### ISSUE TITLE
Members of removed entities are not garbage collected (tested on sounds)

### ISSUE THREAD

**Issue by VigiFyre** [Facepunch/garrysmod-issues#1949]
```lua
ent.sound = CreateSound(ent, "ambient/machines/refinery_loop_1.wav")
ent.sound:Play()
ent.sound = nil
collectgarbage() -- not supposed to be in production code, here just for test
```
^ Sound disappears, as expected. ^

```lua
ent.sound = CreateSound(ent, "ambient/machines/refinery_loop_1.wav")
ent.sound:Play()
ent:Remove()
collectgarbage() -- not supposed to be in production code, here just for test
```
^ Sound stays there (forever?). ^

```lua
ent.sound = CreateSound(ent, "ambient/machines/refinery_loop_1.wav")
ent.sound:Play()
ent.sound = nil
ent:Remove()
collectgarbage() -- not supposed to be in production code, here just for test
```
^ Sound also stays there (forever?). ^

While i, of course, can run `ent.sound:Stop()` to get rid of sound, point is that, if i understand this correctly, sound object is not removed, and that is a memory leak.

**Comment by VigiFyre** [comment]
Uuhh, after several minutes it disappeared after all.
Something was keeping a reference to entity for some time it seems.
This issue can probably be closed, as gc works, it just doesn't happen that fast, what led to a bit of confusion.

**Comment by wiox** [comment]
If you waited 2 ticks before calling collectgarbage you probably wouldn't have had any issues.

**Comment by VigiFyre** [comment]
Of course i've waited for some time and tried to collect garbage multiple times.
If you read my message you would see that it only disappeared only several minutes, not "2 ticks".

**Comment by thegrb93** [comment]
He means don't garbage collect right after removing the sound because that is probably screwing up something.

**Comment by VigiFyre** [comment]
And if you read my message, you would see "not supposed to be in production code, here just for test" comment. gc is not even supposed to be manually called at all. I called gc only to make testing faster.

**Comment by thegrb93** [comment]
Stop saying "If you read" that's rude. You weren't clear about what happens when you don't garbage collect so don't even.

**Comment by VigiFyre** [comment]
Stop posting in closed issue.

**Comment by thegrb93** [comment]
You first
