### ISSUE TITLE
Refresh button not working

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#1953]
Title says it all,

When I click refresh when im in a certain category like TTT or Deathrun, the servers do not update. I need to go to the main page where all of the gamemodes are listed to refresh. Thus refreshing all gamemode servers causing lag. This happens in all tabs including internet, favorites, etc.

**Comment by UltimateByte** [comment]
Issue confirmed in my case (Windows).
This is a bit annoying.
