### ISSUE TITLE
What are the plans for Nextbot AI?

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#1955]
I just wanted to know what the plans are? Are nextbots going to be more optimized? Will they be able to climb ladders like in CS:S/TF2/L4D?

**Comment by robotboy655** [comment]
There are no plans.

**Comment by Loonesbury** [comment]
RB, do you mean there aren't any plans right now (the crash/corruption and nwvars issues are obviously more important right now) or that you or Killburn have decided not to continue NextBots?

**Comment by robotboy655** [comment]
There are no plants to "optimize" an engine feature ( which is impossible to do ). There are no strict plans with anything. If you'd follow development of this game,  you'd know that NextBots are getting some love in next update.

**Comment by Loonesbury** [comment]
Alright, I wasn't sure what part of his post you were replying to. Thanks.
