### ISSUE TITLE
Garry's Mod Issue with update

### ISSUE THREAD

**Issue by ToxiChilleR** [Facepunch/garrysmod-issues#1956]
After the in 2015 update i can not see tool gun animations. I can not see when a fading door fades, there is a 1x1 block in the text screen. When a fading door fades i can not see that. I cant even see when I put a material on a prop. I cant see any animation on the tool gun. I have literally done everything i could think of. I have uninstalled and re installed gmod, Re installed the other games that give me textures to gmod. I have unsubbed and deleted every add on i had to make sure i didnt have a faulty one. I have even deleted steam and installed it again. NOTHING IS WORKING AND IT IS MAKING ME MAD. I have tried to fix this the past couple of days. If anyone can help me please do i do not know wtf is wrong with my gmod

**Comment by robotboy655** [comment]
It is caused by running game in DirectX 8. Add -dxlevel 95 to your launch options.

**Comment by ToxiChilleR** [comment]
Ill try

**Comment by HavenSoldier** [comment]
Can someone please help me?

**Comment by HavenSoldier** [comment]
I am having a problem with turning it on and I just got it today.

**Comment by HavenSoldier** [comment]
It keeps saying I have to download DirectX Runtime from microsoft but I don't know how......sadly....

**Comment by thegrb93** [comment]
Google http://www.microsoft.com/en-us/download/details.aspx?id=35
