### ISSUE TITLE
VERSION and VERSIONSTR are defined in a bad time format.

### ISSUE THREAD

**Issue by Grocel** [Facepunch/garrysmod-issues#1959]
Also you can see here:
![2015.02.04 is bad](http://i.imgur.com/n4o0k9G.png)
VERSION and VERSIONSTR are being defined as YDM instead of YMD. They used to be YMD and there was even a patch that was supposed to keep them being YMD. But suddenly they got changed some how.

Why is it a problem?
http://facepunch.com/showthread.php?t=1450721&p=47450639&viewfull=1#post47450639
> **The problem is not about the format not looking nice or that you can't get used to it.** It's about the **comparability as a number**. So you can check that the version is greater than a specific one. In the current state it would be impossible or at least a huge pain in the ass to just check the game version. Also that breaks addons that do version checking.

**Comment by robotboy655** [comment]
Should be fixed once and for all.
