### ISSUE TITLE
SetParent and SetParentPhysNum Broken

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#1960]
```Entity(91):SetParent(Entity(1), 1) ```
Should parent to my eyes but just parents to me.

```Entity(91):SetParentPhysNum(Entity(92), 0)```
Error arguement \#1 expected number got userdata.

```
Entity(91):SetParent(Entity(92))
Entity(91):SetParentPhysNum(Entity(92), 0)
```
Doesn't parent to ragdoll bone, just the ragdoll. (The ragdoll is Entity(92))

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/SetParent

Read

**Comment by thegrb93** [comment]
Sorry forgot to mention I tried 
```
Entity(91):SetMoveType(MOVETYPE_NONE)
Entity(91):SetParent(Entity(1), 1)
```

**Comment by robotboy655** [comment]
If you don't know how a function works, it doesn't mean it's broken.

First of all, attachment numbers are highly dependent on the model:
![image](https://cloud.githubusercontent.com/assets/3299036/7002765/975a382e-dc58-11e4-8e0d-3d29a7e8609f.png)

Secondly, it does work:
```
] lua_run print(Entity(1):GetEyeTrace().Entity)
> print(Entity(1):GetEyeTrace().Entity)...
Entity [40][prop_physics]
] lua_run print(Entity(1):GetEyeTrace().Entity)
> print(Entity(1):GetEyeTrace().Entity)...
Entity [22][prop_ragdoll]
] lua_run Entity(40):SetParent(Entity(22), 7)
> Entity(40):SetParent(Entity(22), 7)...
] lua_run Entity(40):SetMoveType(MOVETYPE_NONE)
> Entity(40):SetMoveType(MOVETYPE_NONE)...
```

Weirdly enough, it worked in this case without SetMoveType,
http://i.imgur.com/QaRW9M0.gif ( 3MB GIF )

As for SetParentPhysNum, I am not sure how this function works, but it doesn't have entity as its first argument.

**Comment by robotboy655** [comment]
Ok, SetParentPhysNum only works clientside.

**Comment by thegrb93** [comment]
Is that a bug?

I'll try SetParent again later. I'm sure I was doing it right.

**Comment by robotboy655** [comment]
Doesn't look like it is.

**Comment by thegrb93** [comment]
Then I'll update the wiki page so it says it is client-side and not shared.

**Comment by robotboy655** [comment]
I already updated the wiki page.

**Comment by thegrb93** [comment]
Okay I tested again. It works on ragdolls but not players. Also I set the parent to the "eyes" (1) attachment for a Kleiner ragdoll and physgunning the ragdoll in different places causes the parented object to teleport around parenting itself to different attachments.

**Comment by thegrb93** [comment]
Any place a touch the ragdoll with the physgun, the object parents to that part i touched.

**Comment by robotboy655** [comment]
Go to http://facepunch.com/forums/65 and ask for help there, the functions are not broken, you are using them improperly.
