### ISSUE TITLE
Achivements

### ISSUE THREAD

**Issue by dacoolstuff** [Facepunch/garrysmod-issues#1961]
So far I have 9 achievements in Garry's mod but I'm supposed to have 10. The other achievement I'm supposed to have is the a "day of your life wasted" i know that because I've played the game for 53 hours now. The problem is that the achievement isn't unlocking and is supposed to be.

If you have the same or similar problem and know how to fix it please tell me.

**Comment by thegrb93** [comment]
Has to be 24 hours of unpaused game time. Menu time doesn't count.
