### ISSUE TITLE
Gravity gun entity position offset

### ISSUE THREAD

**Issue by immibis** [Facepunch/garrysmod-issues#1963]
If you pick up an entity with the gravity gun, the position returned by GetPos client-side doesn't match where the model is drawn.

Here is an example of a object with a 3D2D overlay, being held by the gravity gun and pulled against the column prop. The 3D2D overlays on the front and top are rendered based on the position returned by GetPos and GetAngles, but the model seems to have its own idea of the entity's position:

<img src="http://puu.sh/h3o1w.jpg">

(The money printers from DarkRP and its various addons are a particularly obvious example of this problem, but others do exist)

The entity in the screenshot's `Draw` function follows this structure:

```
function ENT:Draw()
    self.BaseClass.Draw(self)

    local Pos = self:GetPos()
    local Ang = self:GetAngles()

    local obbmin, obbmax = self:OBBMins(), self:OBBMaxs()

    Ang:RotateAroundAxis(Ang:Up(), 90)
    local corner0 = Vector(obbmin.x, obbmin.y, obbmax.z)
    cam.Start3D2D(self:LocalToWorld(corner0), Ang, scale)
        -- draw the top overlay
    cam.End3D2D()

    corner0 = Vector(obbmax.x, obbmin.y, obbmax.z)
    Ang:RotateAroundAxis(Ang:Forward(), 90)
    cam.Start3D2D(self:LocalToWorld(corner0), Ang, scale)
        -- draw the front overlay
    cam.End3D2D()
end
```

**Comment by robotboy655** [comment]
Try using http://wiki.garrysmod.com/page/Entity/GetRenderOrigin and http://wiki.garrysmod.com/page/Entity/GetRenderAngles instead

**Comment by immibis** [comment]
@robotboy655 Both return nil, even when I wave the entity around with the gravity gun, both before and after calling the base class's Draw function.

**Comment by robotboy655** [comment]
Cannot reproduce with given code in multiplayer or singleplayer.

**Comment by immibis** [comment]
I'm glad if this is finally fixed, but I don't really play GMod at the moment.
(Alternate steps to reproduce - go on any DarkRP server with decently high ping and wave a money printer around with your gravity gun. See if the label follows the model or not. It's not a DarkRP bug, or at least it wasn't 3 years ago)
