### ISSUE TITLE
env_projectedtexture has max projection distance of only 1500 gmod units

### ISSUE THREAD

**Issue by baldursgate3** [Facepunch/garrysmod-issues#1964]
In singleplayer, env_projectedtexture has unlimited projection distance while if you go into multiplayer, distance is limited to 1500 gmod units.

 Examples:

Multiplayer (lamp's projected distance is 20480 )
![image](https://cloud.githubusercontent.com/assets/5841766/7016249/905a1b86-dcd8-11e4-953a-845ebff4c831.png)

Singleplayer (lamp's projected distance is 20480 )
![image](https://cloud.githubusercontent.com/assets/5841766/7016292/6301dc68-dcd9-11e4-9455-7f46b906063d.png)

How to replicate this issue
Spawn a GMod lamp with following settings:

FOV = 179
Distance = 5000 or greater
Brightness = 4000

then compare light radius both in singleplayer and multiplayer

**Comment by robotboy655** [comment]
Increased to 10240 in Dev.
