### ISSUE TITLE
sound.PlayURL handling URLs incorrectly

### ISSUE THREAD

**Issue by TheConfuZzledDude** [Facepunch/garrysmod-issues#1966]
While attempting to create a translation addon, I discovered a bug with sound.PlayURL. As far as I can tell, it seems to add a "+" between all letters and percent characters, which means escaping accented characters in URLs doesn't work, so using Google's api for translation doesn't work (as in our case). 

For example, http://translate.google.co.uk/transl...tl=fr&q=%C3%A9
is parsed as:
http://translate.google.co.uk/transl...l=fr&q=%C3+%A9

AND

http://translate.google.co.uk/translate_tts?tl=fr&q=%E9
is parsed as:
http://translate.google.co.uk/transl...tl=fr&q=%C3%A9
which is then parsed as:
http://translate.google.co.uk/transl...l=fr&q=%C3+%A9

Here's a video too: https://www.youtube.com/watch?v=DCaV2Qgibjg

**Comment by r0uge** [comment]
I can confirm that I am having this issue as well.

**Comment by thegrb93** [comment]
It's putting + in between % encoded characters. Weird.

**Comment by r0uge** [comment]
Decoding the URL doesn't help, since Gmod automatically encodes URLs which contain special characters, leading to exactly the same issue.

**Comment by TheConfuZzledDude** [comment]
We've had to implement a workaround by opening the page in an HTML panel that's created on the fly, which is far from ideal. It works fine with the HTML panel, so it's definitely a problem specific to PlayURL

**Comment by robotboy655** [comment]
Pretty sure this doesn't happen anymore, GMod doesn't do anything to the URL you pass anyway, so it was  a problem with BASS.DLL
