### ISSUE TITLE
My game isn't working!

### ISSUE THREAD

**Issue by Noblewolf155** [Facepunch/garrysmod-issues#1969]
I have had Gmod for the past five months and yesterday it screwed up on me! I can no longer play on the maps nor my downloaded ones and when I go into my subscription folders it says Nothing found. I tried to download them again but it wouldn't download from the workshop. I also went to my game library in steam and it states that I have last play this game:tomorrow, WTF!!! I did back up the game but that did nothing, please help me. Thank you

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
