### ISSUE TITLE
Remove COLLISION_GROUP_DEBRIS_TRIGGER from TTT

### ISSUE THREAD

**Issue by TheKigen** [Facepunch/garrysmod-issues#1970]
As I've shown in the following thread COLLISION_GROUP_DEBRIS_TRIGGER should be removed (corpse.lua:378).  It has been shown to cause crazy physics.  Which in TTT results in a server crash.

http://facepunch.com/showthread.php?t=1460189

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/7098136/920ee96a-dfe5-11e4-8517-3353947ff708.png)

How hard is it to read?

**Comment by TheKigen** [comment]
Sorry, then lets change it to something closer to deprecating COLLISION_GROUP_DEBRIS_TRIGGER from GMod then?

**Comment by Bo98** [comment]
Do you have a replacement?

**Comment by TheKigen** [comment]
Right now it depends on the purpose that COLLISION_GROUP_DEBRIS_TRIGGER was used.  For the most part it appears that either ShouldCollide would need to be used or one of the other collision groups, such as COLLISION_GROUP_WEAPON.

**Comment by thegrb93** [comment]
>Do you have a replacement?

Don't use COLLISION_GROUP_DEBRIS_TRIGGER lol

**Comment by TheKigen** [comment]
Seems to actually be a wider issue with SetCollisionGroup.  Possibly when a player is intersected with the prop being set.

**Comment by TheKigen** [comment]
Bo98, see http://facepunch.com/showthread.php?t=1460189&p=47511040&viewfull=1#post47511040

I've done a much better analysis of what was happening and also provided a temporary fix. Until a GMod update provides CollisionRulesChanged() and RecheckCollisionFilter().
