### ISSUE TITLE
TEX instruction: unsupported sampler type used (OSX STEAM 10.10)

### ISSUE THREAD

**Issue by MaxMega12** [Facepunch/garrysmod-issues#1971]
I can load up the game just fine, however whenever I load a map, i get this:
![screen shot 2015-04-10 at 8 42 32 pm](https://cloud.githubusercontent.com/assets/11894558/7099552/4228c3a2-dfc3-11e4-992a-2c0b7e30876e.png)

It causes my game to crash, and I can't fix it. Any tips?

**Comment by robotboy655** [comment]
Pretty sure it is caused by your video card.

What is your video  card model exactly?

**Comment by MaxMega12** [comment]
It's a ATI Radeon HD 5670 (GPU)

**Comment by robotboy655** [comment]
http://forums.steampowered.com/forums/showthread.php?t=1302179
