### ISSUE TITLE
Server not showing on list in a timely manner

### ISSUE THREAD

**Issue by kulcris** [Facepunch/garrysmod-issues#1973]
I have been having an issue with my server now showing up on the server list until all other servers have loaded and even then it may or may not show up at all, I have heard somewhere that it is ip related? Like it looks for servers with an ip similar to my ip in order to find better ping servers? 
This issue is the same for nearly all other clients that join my servers and it has gotten to the point that few new players join anymore due to the server not showing up fast enough for anyone to see it

Server is hosted with ovh
ip is 167.114.159.183:27014
OS: CentOS6
ram:64gigs
Band:500Mbs

Average ping: 70

net_maxfilesize 900
sv_minrate 15000
sv_maxrate 0
sv_maxupdaterate 66
sv_minupdaterate 45
sv_minrcmdrate 45
sv_maxcmdrate 66
sv_stats 1
sv_timeout 90

**Comment by robotboy655** [comment]
Whatever your problem is, it is not caused by the game, it is caused by Valve Master Server which we have no control over.

**Comment by kulcris** [comment]
http://facepunch.com/showthread.php?t=1374457&p=44566155&viewfull=1#post44566155
http://facepunch.com/showthread.php?t=1450331
http://facepunch.com/showthread.php?t=1459461

- You can bypass this bug by enabling ANY filter (has users playing, is not
passworded, secure, etc.). Most people dont do this and even less people
even use the server browser capable of it (gmod has its own html based
server browser).

is there a way to by default add a "filter" into the server list automatically?  for example who searches for a passworded server? sadly the gmod browser does not use filters like the default browser does and so you cant bypass it without using the legacy browser (most users dont anymore) 
maybe a server filter for game garrysmod even though garrysmod is already filtered?

**Comment by robotboy655** [comment]
As I said, the "my server doesn't appear in the list" is not caused by the game, we cannot fix it.

I also highly doubt setting any filters will help, it makes no sense. ( Unless you can prove me wrong of course )
