### ISSUE TITLE
Give the server browser genres

### ISSUE THREAD

**Issue by DaaOtt** [Facepunch/garrysmod-issues#1974]
As detailed in [this post](http://facepunch.com/showthread.php?t=1459233&p=47495519&viewfull=1#post47495519) by TylerB:

>I still think that genres in the server menu would be a good idea for filtering down gamemodes.
>
>e.g.
>
>All
>- all servers, no filtering.
>
>Sandbox
>- Sandbox
>- Build To Kill
>- Sledbuild?
>
>RP
>- DarkRP
>- HL2RP
>- BuildRP
>- etc
>
>PvP
>- TTT
>- GunGaym
>- Murder
>- etc
>
>Minigames
>- EFT
>- Fretta
> etc
>
>Other
>- uncategorized?
>
>it would at least make the lesser known servers not off the bottom of the page, right?

...

>It'd be set the same way the gamemodes are set now.
>
>GM.Genre = "RP" or something
>
>if it's not a valid genre (as determined by the server list?) it'll fall into uncategorized

**Comment by wiox** [comment]
I really like this idea. Especially the fact that there would be predetermined genres so that "lol we are our own special genre" servers won't pop up constantly.

**Comment by DaaOtt** [comment]
Oops, clicked the wrong link.
