### ISSUE TITLE
No Admin Powers (School PC I can take home)

### ISSUE THREAD

**Issue by mickeyjay88** [Facepunch/garrysmod-issues#1975]
Hello everyone, I currently have no PC but the school provides everyone with laptops. I have purchased the game through steam and have a lot of hours spent in the game, I won't have my pc for a while so I was wondering if I can download Gmod in a zip? or something like that I CAN'T use steam due to restrictions in effect on the computer.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16.

The answer is no.

**Comment by mattycfp** [comment]
Just gonna say this: Garry's Mod isn't portable.
