### ISSUE TITLE
AutoRefresh breaks when wrapping include() directly with pcall

### ISSUE THREAD

**Issue by maritaria** [Facepunch/garrysmod-issues#1976]
I noticed that if you use:

``` lua
pcall(include,"myScript.lua")
```

AutoRefresh(or whatever its called) breaks, I assume it's because include unwinds the stack once to get the calling script and the pcall breaks it because it's a C stackframe.
Test code:

**File: autorun/testme.lua**

``` lua
print("testme.lua")
print("Include #1", include("testme/1.lua"))
print("Include #2", pcall(include,"testme/2.lua"))
print("Include #3", pcall(function() include("testme/3.lua") end))
```

**File: testme/1.lua**

``` lua
print("testme/1.lua")
error("1.lua failed")
```

**Repeat for 2.lua and 3.lua**
Sorry if my code-style isn't yours

When a changed version of 2.lua is written to disk it will create the following console message:
[Unhandled Lua Refresh: [NAME:testme/2.lua] [TYPE:]

My suggestions:
1. Throw an error when include() can't find the calling script
2. Let include() unwind until a valid lua stackframe has been found

While running these tests i noticed that the pcall that messes up AutoRefresh doesn't actually return false from the pcall. I know this should probably be a seperate request but, could there be a way to be notified of lua errors on the server? Possibly similar to the [OnLuaError](http://wiki.garrysmod.com/page/GM/OnLuaError) hook in the menu realm.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
