### ISSUE TITLE
Voice thing

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#1977]
IDK. I just switched to linux and this happens.

[ERROR] gamemodes/terrortown/gamemode/cl_voice.lua:651: attempt to compare number with nil
  1. Draw - gamemodes/terrortown/gamemode/cl_voice.lua:651
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:350

**Comment by robotboy655** [comment]
Do not report anything related to TTT here.
