### ISSUE TITLE
Constant game crashes during prop hunt matches

### ISSUE THREAD

**Issue by generalschrimpf** [Facepunch/garrysmod-issues#1979]
Recently (for the past couple weeks), whenever I play prop hunt, I always crash when the teams switch.  Sometimes the game shuts down without warning, sometimes it does the whole 'hl2.exe has stopped responding' and closes.
This needs to be fixed.
I have disabled all addons, verified game files, uninstall/reinstall, everything.  NOTHING HELPS.

If you've had this issue and know how to fix it, let me know please!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

If you wish to report a crash, you can learn how to do so properly here:
http://wiki.garrysmod.com/page/Crash_Reporting
