### ISSUE TITLE
Garry's Mod has high chance of crashing when I spawn my particle effect

### ISSUE THREAD

**Issue by baldursgate3** [Facepunch/garrysmod-issues#1981]
This is a recent issue that keeps crashing hl2.exe. 

Whenever I spawn one of my effects (specific ones not all), it mostly crashes the game when the player directly looks at it.

Video:
https://www.dropbox.com/s/h7innl2rdg75oen/hl2%202015-04-18%2020-33-10-276.avi?dl=0

How to replicate:
Download the pcf -  http://puu.sh/hiv67/7a1350fd1e.pcf

Use this code to spawn it:

function test( ply, command, arguments )
	local pos = ply:GetPos()
	for i=1, 50 do
		timer.Simple(i/4, function()
		ParticleEffect( "gf2_battery_03_explosion_01", pos, ply:GetAngles(), self )
		end)
	end
end
concommand.Add( "run_effect", test )

and wait until the game crashes

This type of a crash doesn't produce any crash dumps or errors just so you know.

**Comment by thegrb93** [comment]
Related? https://github.com/Facepunch/garrysmod-issues/issues/1968

**Comment by baldursgate3** [comment]
@thegrb93, I can't really tell if it's related. Particle overflow makes the user time-out from what I've seen but  only if there are immense amounts of particles. This could be something else.

**Comment by baldursgate3** [comment]
Update:

Some particles crash me when I enter the void and come back.
