### ISSUE TITLE
Invalid Panels should not error when printed.

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#1983]
Invalid Entities don't error when printed.

```lua
] lua_run_cl p = vgui.Create("DPanel") p:Remove()
] lua_run_cl print(p)
[ERROR] Tried to use invalid object (type Panel) (Object was NULL or not of the right type)
  1. unknown - [C]:-1
   2. print - [C]:-1
    3. unknown - LuaCmd:1
```

```lua
] lua_run_cl print(Entity(-1))
[NULL Entity]
```

Might expand to other types.

**Comment by robotboy655** [comment]
Will be fixed for Panels & Phys Objects.

Ideally this fix should be applied to all methods of those classes, but I'll need to study the shit a bit more.
The c++ side of Garry's Mod has a shit ton inconsistencies, just like Lua side does.
