### ISSUE TITLE
Null characters terminate strings with http.Fetch/Post

### ISSUE THREAD

**Issue by andyault** [Facepunch/garrysmod-issues#1984]
http functions don't have support for null (\0) characters, which is a problem when posting data like images from render.Capture

**Comment by thegrb93** [comment]
I think you have to % encode those types of characters.

**Comment by robotboy655** [comment]
It does properly work, it will appear as if it doesn't work if you print body directly into the console because then the null character will make the console output cut out. If you print each character as a byte, or just use string.len(), the data is all there.
