### ISSUE TITLE
"models/props_phx/gears/bevel90_24.mdl" has a wrong physics box.

### ISSUE THREAD

**Issue by L1Q** [Facepunch/garrysmod-issues#1985]
It appears that that the model has same physics box as "models/props_phx/gears/bevel36.mdl".
![bevel36.mdl and bevel90_24.mdl](http://i.imgur.com/6z7zIH6.jpg)
In order to see this, use following console commands: 
* sv_cheats 1; 
* vcollide_wireframe 1;  

OR use Rubat's entity inspector, it can also show the physics box.

**Comment by robotboy655** [comment]
This is a bug with the original model ( It's the same in the PHX SVN ).

There are others like ```models/mechanics/articulating/arm_base_b.mdl``` too.

**Comment by L1Q** [comment]
So how do we fix this?  
Can I upload fixed model somewhere?  
Where can I find the source for it?  
I can decompile if there are no sources.

**Comment by baldursgate3** [comment]
@L1Q, I can fix it cause I have some spare time.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/16895648/78332bd8-4b86-11e6-8393-348c0f18946c.png)

```models/mechanics/articulating/arm_base_b.mdl``` will be fixed too.
