### ISSUE TITLE
Cannot even get game to come up on my computer

### ISSUE THREAD

**Issue by HavenSoldier** [Facepunch/garrysmod-issues#1986]
I have tried every suggestion on this computer to get gmod to work and NOTHING!! There is no email or anything to get a hold of someone to help. I want a refund!! As I have looked over the reported "fixes" for it, nothing seems to work and people are having problems left and right. I feel this is a complete rip off!!! Where and how do I get my money back??!! Or someone please suggest how to get it working??!! PLEASE!!!!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help at http://facepunch.com/forums/16

If you want a refund, contact Steam Support.

**Comment by HavenSoldier** [comment]
That's the problem.... NO WHERE is willing to give HELP!!! Not

**Comment by BytewaveMLP** [comment]
Good luck with that.
You're not going to find help here; this is a bug tracker, not a help desk.
