### ISSUE TITLE
[Dev Branch] Navmesh Issues

### ISSUE THREAD

**Issue by mcd1992** [Facepunch/garrysmod-issues#1987]
Thanks again for implementing the navmesh bindings RBB. From my testing I was able to remove my module and run my gamemode which heavily uses the navmesh with no problems other than one quirk.

CNavArea:GetAllAdjacentAreas doesn't include one-way connections that are adjacent. Example being a navarea high above can have a one way (drop down) connection to a navarea below it and GetAllAdjacentAreas will see the navarea below. But the area below will not be able to see the area above it as an adjacent area. Basically just need to call CNavArea::GetIncomingConnections for each side and add it to the vector list of areas. Here's how I did it if it helps any: https://github.com/FgtHouse/fgt_navstuff/blob/master/src/fgt_classes/fgtnavarea.cpp#L72-85

I'll be sure to keep you updated on any other issues I find.
Thanks again!

**Comment by robotboy655** [comment]
Should it include such connections though? I mean, the connections are one way for a reason.

**Comment by mcd1992** [comment]
True, my though behind it is that the name 'Get[All]AdjacentAreas' implies that the function will return the areas touching all/a specific side regardless of connection direction.

Alternatively a binding to CNavArea::GetIncomingConnections would solve this problem.

**Comment by robotboy655** [comment]
I will add CNavArea::GetIncomingConnections & CNavArea::GetAllIncomingConnections

**Comment by mcd1992** [comment]
That'll work just fine, thanks again!

I'll leave this ticket open for you to close when it's implemented, or you can close it now.
