### ISSUE TITLE
engine.ActiveGamemode Issue on Client when creating a server

### ISSUE THREAD

**Issue by TigerKriid** [Facepunch/garrysmod-issues#1988]
#### Description

When you create a local Server and want to check the Active Gamemode, for example Scripts in lua/autorun or in addons/lua/autorun, it will show the wrong Gamemode for the client: **base**.

After reloading the Script it will show the correct Gamemode.
#### How to Replicate?

Create a file with the code

``` lua
-- Different Colors to see them easier in the console
MsgC(SERVER and Color(11,155,155) or Color(255,155,155),SERVER and "Active server Gamemode:" or "Active client Gamemode:",engine.ActiveGamemode(),", GAMEMODE_NAME: ",GAMEMODE_NAME,"\n")
```

Run a local Singleplayer or Multiplayer server with _sandbox_ and watch the console.

it will print the following:
- (in cyan) Active server Gamemode:sandbox, GAMEMODE_NAME: nil
- (in magenta) Active client Gamemode:**base**, GAMEMODE_NAME: nil

Reload the script after that and it will print the following:
- (in cyan) Active server Gamemode:sandbox, GAMEMODE_NAME: sandbox
- (in magenta) Active client Gamemode:**sandbox**, GAMEMODE_NAME: sandbox
#### What am i using it for?

I use it to disable Scripts that I don't want to use outside of sandbox

``` lua
if engine.ActiveGamemode() != "sandbox" then return end
```

tested this on Stable and Dev

Exe version 15.04.03 (garrysmod)
Exe build: 20:24:17 Apr 23 2015 (6004) (4000)

I wasn't able to test how it behaves when someone joins your server, yet.

**Comment by Bo98** [comment]
Put it in a PostGamemodeLoaded hook or something.

**Comment by chelog** [comment]
I need this badly before entities and gamemodes start to load. We just need the name of the gamemode folder or some identifier.I know I can load entities after gamemode loaded but it's just inconvenient. Can we have fix for this please?

**Comment by robotboy655** [comment]
Does something like this work?
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/shared.lua#L26-L33

**Comment by chelog** [comment]
@robotboy655 nah, GAMEMODE table is nil during execution. Like I need to detect gamemode directly in script located in `autorun/client` folder, just by `print(something)` in global state, outside hooks and functions. Is that possible?

**Comment by robotboy655** [comment]
Fixed.
