### ISSUE TITLE
gmad.exe whitelist blocks .txt files

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#1990]
The title is self-explanatory. Upon trying to create a gma out of a folder, it says that my file, "scripts/soundscapes.txt" is not allowed by whitelist.
I feel this is unnecessary, as no harm can be done via a text file, and would only benefit devs.
I need to use a .txt file for a custom soundscape I am using in my addon.

**Comment by robotboy655** [comment]
If it was allowed, the problem would be that your one custom soundscape will break every single other soundscape as you are overriding the soundscapes.txt. Plus the addon conflicts.

You should be able to add it via http://wiki.garrysmod.com/page/sound/Add

**Comment by imp0se** [comment]
Is there a way to use rndwave with sound.Add?

**Comment by robotboy655** [comment]
Read the wiki documentation. I linked it for a reason.
```
{
sound = {
	"snd1",
	"snd2"
}
}
```

Stop being lazy.
