### ISSUE TITLE
Crashing on Gmod

### ISSUE THREAD

**Issue by 187proof** [Facepunch/garrysmod-issues#1993]
My gmod keeps crashing, i've disabled all my addons, verified cache and have tried reinstalling. This same crash has been happening for a long time. 

Happens when im shooting with the SPAS shotgun, it happens at random sometimes, usually when i switch fast to it and shoot, freezes than crashes. I closed my previous issue about how to upload an MDMP file, used Mediafire. 

MDMP File: http://www.mediafire.com/download/uy1hezxfc6107qd/hl2_152503_crash_2015_4_26T18_37_12C0.mdmp

**Comment by mcd1992** [comment]
By 'SPAS Shotgun' you mean the vanilla HL2 one? Try running HL2 (and the two episodes if you have them) to see if they launch just fine, then try verifying their cache.

**Comment by 187proof** [comment]
I dont have HL2, its the M9k SPAS.

**Comment by mcd1992** [comment]
Then you don't have all addons disabled.... M9K weapons aren't built into Garry's Mod. Granted the addon shouldn't be able to make your game crash. Still try validating the games that you have mounted in gmod.

**Comment by 187proof** [comment]
I've gone into my Addons, and pressed Disable All many times, its server content from a Basewars server i play on, ill try validating CSS, strangest thing is sometimes i can play for a couple of hours without crashing because its only when i use that weapon, and other times in the first 10 minutes of using it I crash.

**Comment by imp0se** [comment]
Stop using that weapon then -_-
