### ISSUE TITLE
All workshop addons mount even when disabled, when Steam is offline / no internet.

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-issues#1994]
How to reproduce the issue: Have some workshop addons enabled, some disabled. Then when Steam is in offline mode, run a map in Gmod (single player since there's no multiplayer available). All addons will be mounted regardless of if they've previously been disabled or not.

I assume it's because they're gma files in the addon folder so it just mounts them as any non-workshop gma file would be mounted. Maybe they should be named with a slightly different syntax? eg instead of stacker_stool_104479831.gma it could be stacker_stool.104479831.gma (anything_goes_here.number.gma) and if 104479831 is listed as disabled in addonnomount.txt it'll not mount it. Any gma files with numbers that are unlisted would mount as normal, as would any without a number before the extension.

**Comment by mattycfp** [comment]
Surprised someone noticed this just now. 

Anyhow, it's been an error for a while, not just you. AFAIK, it's going to be fixed.

**Comment by robotboy655** [comment]
In offline mode, all .gmas in addons/ folder are loaded. It's been like that for 2 years.
