### ISSUE TITLE
Include runs 2 times instead of once?

### ISSUE THREAD

**Issue by Nyaaaa** [Facepunch/garrysmod-issues#1997]
Include runs 2 times instead of once?

**Comment by robotboy655** [comment]
No.

**Comment by Nyaaaa** [comment]
Why don't you test it on the server for your self..

**Comment by robotboy655** [comment]
How many times you were wrong before when coming here? This is not a place to get help.
Get help @ http://facepunch.com/forums/65

You are not even providing any useful info, like what realm, what server/client version, have you tried it without any addons.

```
util.lua
util/color.lua
util/sql.lua
extensions/net.lua
drive/drive_base.lua
drive/drive_noclip.lua
gmsave.lua
gmsave/entity_filters.lua
gmsave/player.lua
extensions/file.lua
extensions/angle.lua
extensions/debug.lua
extensions/entity.lua
extensions/ents.lua
extensions/math.lua
extensions/player.lua
extensions/player_auth.lua
extensions/string.lua
extensions/table.lua
extensions/util.lua
extensions/vector.lua
extensions/game.lua
extensions/motionsensor.lua
extensions/weapon.lua
extensions/coroutine.lua
shared.lua
obj_player_extend.lua
gravitygun.lua
player_shd.lua
animations.lua
player_class/player_default.lua
taunt_camera.lua
player.lua
npc.lua
variable_edit.lua

```

This is what I got by putting your code in ```includes/init.lua``` of latest Dev build ( shared )

**Comment by mcd1992** [comment]
If you're seeing the same file name being printed multiple times (like shared.lua). Keep in mind that include() will search for files relative to it's own location. It's not including the same file.

**Comment by Nyaaaa** [comment]
Actually i was including it from the addons, Not from init.lua, I'm not wasting anyones time, Dumbass!

**Comment by robotboy655** [comment]
Here's what mcds code gives me when ran on srcds from an addon in autorun:
![image](https://cloud.githubusercontent.com/assets/3299036/7424342/9ab26592-efa8-11e4-8333-efc479927829.png)

Clearly, you are wrong, yet again, and yet again are wasting everyones time by being completely ignorant. You didn't even bother providing any photographic evidence.

STOP with the bullshit and TEST your code PROPERLY before posting here or next time you might get a ban.

**Comment by robotboy655** [comment]
If this "bug" would've existed, we would have a lot more shit storm than one deluded guy.

**Comment by thegrb93** [comment]
He might be including a file in lua/autorun, which would cause the file to be run twice.

**Comment by Nyaaaa** [comment]
@thegrb93 Thanks that was better reply than robotboy's answer, I was using local oldinc = include instead of _G.include

**Comment by Nyaaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/5182757/7430915/cfeddfee-f010-11e4-89b3-eb0298db3216.png)

**Comment by Nyaaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/5182757/7430931/f3145020-f010-11e4-9dbc-17ce63828382.png)

**Comment by thegrb93** [comment]
@Nyaaaa From what I've learned here, you should ask for help here first. http://facepunch.com/forumdisplay.php?f=65

If nobody can help or they confirm it as a bug, then you can report a bug here.

**Comment by Nyaaaa** [comment]
@thegrb93 Then he doesn't need to reply, But it doesn't matter anymore because i'm going to never report any bug or anything here again due to his rudeness, And never look at facepunch again..
