### ISSUE TITLE
Bugginess with pose parameters

### ISSUE THREAD

**Issue by theJ8910** [Facepunch/garrysmod-issues#1998]
I'm creating a scripted entity that uses "models/combine_turrets/floor_turret.mdl" as its model.
Inside of its Think hook, I am running self:SetPoseParameter( "aim_yaw", x ), where x is a number between -60 and 60. Calling turret:GetPoseParameter( "aim_yaw" ) on the server returns x as expected, but on the client this returns y (where y = ( x - min ) / ( max - min )), a value between 0 and 1.

I've also noticed if the pose parameter isn't set every frame, when I attempt to move the turret with the physgun or clip out of the bounds of the map, the pose parameters change clientside to a different value for seemingly no reason.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/SetPoseParameter

You can and should call it clientside too, every frame/tick.

**Comment by Nyaaaa** [comment]
Then why is it shared?

**Comment by theJ8910** [comment]
@Nyaaaa Typically the way things work in Source, the server acts an authority on important things such as entity states (which include things related to animation like pose parameters) and synchronizes values that have changed to all clients who can "see" the entity (which is determined by the engine based on the entity's configuration, whether or not it is in the player's PVS, etc) each tick.

Because of latency and other factors, however, these updates may be delayed or occur at irregular intervals. To compensate for this, clients predict what is going to happen on the server, typically by running the same code the server is running.

As long as both the client and server share the same state and are running the same deterministic code, the client's simulation should be perfectly in sync with the server's simulation. In that case, why not just run it entirely on the client? That's possible, but what happens when you throw player inputs into the mix? For example, lets say your entity is using full clientside simulation, and if you use, it causes it to start animating. If you were the person who used the entity, it would start animating immediately for you, but at a later time for everyone else on the server as news that you had used the entity reached them. In other words, you would desync. The server acts as an authority to correct desynchronizations, in this sense.

@robotboy655 There's still the issue of self:GetPoseParameter() returning different values on the client and server. If you do self:SetPoseParameter( "aim_yaw", 30 ) on either the client or server, it behaves as expected. If you follow that up with print( self:GetPoseParameter( "aim_yaw" ) ) on the server, it returns "30" as expected, but on the client this will return 0.75 instead (it's always a number between 0 and 1). How is this inconsistent behavior not a bug?

**Comment by robotboy655** [comment]
As far as I can tell, this is how it is with all of Source Engine. Blame valve. You can easily get the proper value using the MinMax range.

**Comment by Nyaaaa** [comment]
@theJ8910 I already knew that lol, No need to tell me everything geez.
