### ISSUE TITLE
engine.LightStyle not affecting static props

### ISSUE THREAD

**Issue by Shendow** [Facepunch/garrysmod-issues#1999]
I am not entirely sure if it's a bug, but calling engine.LightStyle and then render.RedownloadAllLightmaps doesn't affect static props. This problem has been around since 2-3 years now.

This screenshot was taken with LightStyle "a" 

![image](https://cloud.githubusercontent.com/assets/1496804/7429469/fb1220e0-f001-11e4-95d8-e8e21cc1e356.png)

**Comment by Noiwex** [comment]
Static props don't update their lightness level. It's not a bug, because
source engine was never meant to have changing time of day.

**Comment by imp0se** [comment]
static: adjective - lacking in movement, action, or change, especially in a way viewed as undesirable or uninteresting.

**Comment by thegrb93** [comment]
Considering what http://wiki.garrysmod.com/page/engine/LightStyle is supposed to do, I'd like to see this fixed/changed. @imp0se that is really distasteful.

**Comment by robotboy655** [comment]
engine.LightStyle does exactly what it is supposed to.

**Comment by thegrb93** [comment]
It would be nice if it worked a little better. I also need to mention that cubemaps aren't affected either. Would be cool if the brightness of the cubemap materials were affected too.

**Comment by daunknownman2010** [comment]
Every Source game/mod has this problem, no matter what version it is. I don't expect this to be fixed.
