### ISSUE TITLE
file.Exists much slower than file.Open

### ISSUE THREAD

**Issue by Pecius** [Facepunch/garrysmod-issues#2001]
Checks with file.Exists appear to be much slower compared to using the read mode in file.Open function.
file.Exists seems to have a problem with files that aren't present in the file system which causes freezes if you try to check a larger amount of files.

This code demonstrates the issue
```lua
local validfile = "models/props_junk/watermelon01.mdl"
local invalidfile = "invalid/file/test.txt"

local trials = 1000

print("Trial with a valid model")

local t = SysTime()

for i = 1, trials do
	file.Exists(validfile, "GAME")
end

print("file.Exists\t-", SysTime() - t)

t = SysTime()

for i = 1, trials do
	file.Open(validfile, "r", "GAME")
end

print("file.Open\t-", SysTime() - t)

print("\nTrial with an invalid model")

t = SysTime()

for i = 1, trials do
	file.Exists(invalidfile, "GAME")
end

print("file.Exists\t-", SysTime() - t)

t = SysTime()

for i = 1, trials do
	file.Open(invalidfile, "r", "GAME")
end

print("file.Open\t-", SysTime() - t)
```

Results:
>Trial with a valid model
>file.Exists	-	0.094191044505806
>file.Open	-	0.056310144426334
>
>Trial with an invalid model
>file.Exists	-	41.363042811124
>file.Open	-	0.75909212421038

**Comment by neico** [comment]
I assume that you tested that on windows?

On windows the stat function (as gmod probably uses this function: https://github.com/garrynewman/bootil/blob/master/src/Bootil/File/File.cpp#L37) is only to make porting from windows to unix easier, but this comes with the drawback that windows's filesystem isn't designed the same way so I can very much believe that this function might be pretty slow.

What open probably does is actually checking for the file attribute, like checking if the file is readable, which is a lot faster then loading a struct, for example I use this on windows:

```cpp
GetFileAttributes( L"<file name>") == INVALID_FILE_ATTRIBUTES && GetLastError() == ERROR_FILE_NOT_FOUND
```

This of course is based on assumptions as it's hard to see the gmod src :P, you could probably make a lua module to test that or simply wait for a official statement.

**Comment by robotboy655** [comment]
Nope, file.Exists doesn't use the Bootil function.

Try calling file.IsDir() for the same paths and see its execution time.

**Comment by Pecius** [comment]
Results for file.IsDir
>Trial with a valid model
>file.IsDir	-	34.612043846615
>
>Trial with an invalid model
>file.IsDir	-	34.963918926765

And yes, these tests were done on Windows.

**Comment by neico** [comment]
At least those results don't differ much lol...

**Comment by thegrb93** [comment]
yeesh 35ms

**Comment by Pecius** [comment]
35 seconds.

**Comment by Noiwex** [comment]
35 years

**Comment by Bo98** [comment]
Worth noting that the same happens on OS X.

**Comment by robotboy655** [comment]
It's because if the file doesn't exist, it checks for IsDir, which appears to be extremely slow.

**Comment by willox** [comment]
```lua
Trial with a valid model
file.Exists	-	0.055618250108196
file.Open	-	0.045189169393051

Trial with an invalid model
file.Exists	-	0.63500476307934
file.Open	-	0.25165292255501
```

Fixed in the dev branch (within the next hour). This change should effect file.IsDir too.
