### ISSUE TITLE
big problems

### ISSUE THREAD

**Issue by kizuma** [Facepunch/garrysmod-issues#2002]
After 1 week of game servers. I had a big worries on the map (rp_rockford_v1b) I took them in screen look. 
![2015-05-03_00001](https://cloud.githubusercontent.com/assets/12220232/7444985/1ed40248-f19f-11e4-8054-b96aba8e93f4.jpg)
![2015-05-03_00002](https://cloud.githubusercontent.com/assets/12220232/7444986/1ede078e-f19f-11e4-86e5-c6ac90a37a3f.jpg)
![2015-05-03_00003](https://cloud.githubusercontent.com/assets/12220232/7444987/1ee8207a-f19f-11e4-90cd-7e1845bf4626.jpg)
![2015-05-03_00004](https://cloud.githubusercontent.com/assets/12220232/7444988/1efa24e6-f19f-11e4-9a40-471b8ba01c00.jpg)
![2015-05-03_00005](https://cloud.githubusercontent.com/assets/12220232/7444989/1efd3c8a-f19f-11e4-8f2c-e3d5a80aaa56.jpg)
![2015-05-03_00006](https://cloud.githubusercontent.com/assets/12220232/7444990/1f038414-f19f-11e4-99f8-789e4ae0cb48.jpg)

help me please.

Thank .

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
