### ISSUE TITLE
Hammer bizarre view render

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#2003]
![image](https://cloud.githubusercontent.com/assets/8015170/7446445/37f2d7ea-f1b3-11e4-943c-a7d8826db65b.png)

Tested on dev branch + live branch
Hammer renders all views strangely, and all entities are obsolete.

Windows 8.1 x64
Intel i7 Quad-Core
AMD Radeon HD 6770M - 512mb gddr5
8GB ddr3

**Comment by robotboy655** [comment]
It's a bug on your side + you have already reported this.
