### ISSUE TITLE
Awesomium useragent is missing some values

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-issues#2005]
The useragent sent by Awesomium seems to have placeholders for values that it doesn't fill. Here's the useragent I get on the current stable Gmod (2015.25.03 version string).
>Mozilla/5.0 (**%s**; U **%s**; en-US; Valve Source Client; **%s**) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/3.0.195.24 Safari/532.1

Could those %s placeholders be populated or removed? For comparison, the Steam overlay (in the current beta Steam client build 1430520382) gives me this for the bracketed section:
>(Windows; U; Windows NT 6.1; en-US; Valve Steam GameOverlay/1430520382; )

 
 

It might also be useful to have the Awesomium version and Gmod version included, something like:
>Mozilla/5.0 (Windows; U Windows NT 6.1; en-US; Valve Source Client; **Gmod/152503**) AppleWebKit/532.1 (KHTML, like Gecko) **Awesomium/1.7.5** Chrome/3.0.195.24 Safari/532.1

(In that example I'm using the current stable Gmod verstring, and current stable Awesomium number, not sure what version of Awesomium is currently being used by Gmod)

**Comment by mcd1992** [comment]
I've noticed this as well, not really a issue but getting more data is always good.

**Comment by robotboy655** [comment]
```
Mozilla/5.0 (*OS*; Valve Source Client) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1003.1 Safari/535.19 Awesomium/1.7.5.1 GMod/13
```
New format.
