### ISSUE TITLE
file.* Functions broken

### ISSUE THREAD

**Issue by 00875** [Facepunch/garrysmod-issues#2006]
I have no idea, but FPtje talk to me, what it's not a DarkRP problem.
https://github.com/FPtje/DarkRP/issues/1924

**Comment by robotboy655** [comment]
FPtje was wrong about you knowing how to write a bug report.

This is a problem on your side, caused by one of your addons. Get help @ http://facepunch.com/forums/65

**Comment by 00875** [comment]
I resolved! This is causing when in folder, where are many files we do file.Exist (or something else).
But, in past that was not a bug. Interesting...
