### ISSUE TITLE
Closing Garry's Mod sometimes will cause svchost.exe crash

### ISSUE THREAD

**Issue by 00875** [Facepunch/garrysmod-issues#2010]
When i close gmod, sometimes half of opened programms are crashes too. This is all by svchost.exe crash.
OS: Windows 8.1
CPU AMD FX 8350
GPU AMD Radeon R9 270
Last time when i closed Gmod, programms are crashed: Chromium, Steam, JET Screenshot, Notepad++, PuTTY, System Explorer, AIMP3. Windows say "Programm not working. Close the programm".
And if i lucky, BSoD will appear

**Comment by robotboy655** [comment]
This is not a bug with GMod, I know of one more person on Windows 7 who is affected by similar problem, and it is not GMod/Source Engine related.
