### ISSUE TITLE
Server is always crashes on exit or close (Linux)

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#2011]
When the server is running with workshop addons, closing it will cause Segmentation fault.
![2015-04-07_18-29_roboderpy ubuntu](https://cloud.githubusercontent.com/assets/6339511/7547934/dfc31e2c-f621-11e4-8ae0-6769bc7f7da1.jpg)
If on server are no addons workshop installed, it would successfully closed
![2015-05-09_08-10_roboderpy ubuntu](https://cloud.githubusercontent.com/assets/6339511/7547960/e19eb142-f622-11e4-9599-539b445aa3ee.jpg)

I think that is also happes on client (Windows are running WerFault.exe when i close gmod and creating somewhere crash dump)

**Comment by suchipi** [comment]
I can confirm this on Debian 7.

**Comment by neico** [comment]
That's been there for so long that some (including me) use this for automated server reboots without another wrapper script :/

**Comment by mcd1992** [comment]
This happens for me as well, but only with addons loaded. I believe I boiled it down to wiremod being the culprit.

**Comment by Noiwex** [comment]
Can't confirm on Fedora 21.

**Comment by xalalau** [comment]
Yep! This also happens to me exactly this way. Ubuntu 14.04.

**Comment by 00875** [comment]
Noiwex, i think you have no workshop addons installed. See http://wiki.garrysmod.com/page/Workshop_for_Dedicated_Servers
