### ISSUE TITLE
Errors when joining/having others join my server

### ISSUE THREAD

**Issue by TornadoStorm** [Facepunch/garrysmod-issues#2012]
Hello

I have been having this issue for a long time now, and I haven't been able to find a fix :(
Whenever I start a server for my friends to join, they all seem to have complete errors with anything that isn't vanilla. This also happens when i try to join someone else's private server, but it is only me that gets errors and texture issues.
I have confirmed that all of us have set our servers properly as with other people they don't get errors when joining someone's server, and only get errors when joining mine.

Things I have tried:
1. Verifying that I have set up a private server properly (even tried this over LAN)
2. Verifying integrity of game cache (Also completely deleting and reinstalling the game)
3. Removing and unsubscribing ALL addons
4. Downloading the addons required manually before joining someone else's private server
5. Using other software such as Hamachi or Evolve
6. Joining a private server with no addons enabled
7. Confirming in settings that all custom content to download is enabled
8. sv_lan 0

It seems joining public servers seems to work fine without any errors, and if I host a vanilla-only server, then no errors are seen for others. I've even tried only having 1 addon on a server AND 1 addon only installed and subscribed to in the game, so I don't know if it is mod clashes or anything.

I suspect maybe I have downloaded an addon/addons that have caused a change in the default game files, but I am not sure. I am 100% sure that the issue is with my computer. Please help! :(

Thanks in advance

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
