### ISSUE TITLE
Strange flashing wireframe

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#2013]
![image](https://cloud.githubusercontent.com/assets/8015170/7551294/8a5ae194-f65e-11e4-9c2a-6b541bd98f6f.png)
![image](https://cloud.githubusercontent.com/assets/8015170/7551296/910fe908-f65e-11e4-9b68-574cfa285bb2.png)
![image](https://cloud.githubusercontent.com/assets/8015170/7551298/94dea010-f65e-11e4-9590-54bee9d1d666.png)

On some areas in maps, there is a strange, spastic wireframe-thing that exhibits, erm, strange behavior. Sometimes comes in different colors.

**Comment by robotboy655** [comment]
Only report supposed bugs after you tested them in Vanilla.

**Comment by imp0se** [comment]
I have tested this in Vanilla Garry's Mod as well, I just took the screenshots the last time I saw the glitch.

**Comment by thegrb93** [comment]
I've never seen this. What map is that? Also why does it look like mat_fullbright 1?

**Comment by imp0se** [comment]
Unimplemented lighting system for that map (ew). I've had this issue on multiple maps. I've also asked others about this issue (they said yes) and seen it on livestreams.

**Comment by thegrb93** [comment]
You only answered one of the questions.

**Comment by imp0se** [comment]
The map in the screenshot was some ported map from a Minerva game, someone was playing it on a livestream and I took some screenshots since I had the same problem. I've also had the problem on my own map (gm_degenerate), as well as other maps.

**Comment by robotboy655** [comment]
Can you give me positions on gm_degenerate where the issue happens 100% of the time?

**Comment by imp0se** [comment]
The last place I saw it was the general surrounding area of 615.845337 2277.496582 -433.093628
However, keep in mind that this issue happens somewhat randomly, and as such is difficult to reproduce.
