### ISSUE TITLE
[dev] Panels derived from DModelPanel that override Paint() render the model in a different position

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-issues#2014]
As the title says.

```
local PANEL = {}

function PANEL:Paint()
	self.BaseClass.Paint( self )
end

vgui.Register( "DModelPanelExample", PANEL, "DModelPanel" )
```

http://i.cubeupload.com/ur6Nn1.jpg

The model renders in a different position even though the Paint function simply calls the Paint function of it's parent class.

Panels that derive from DModelPanel but do not override the Paint class do not have this issue.

**Comment by robotboy655** [comment]
```

function PANEL:Paint()
    self.BaseClass.Paint( self )
end

vgui.Register( "DModelPanelExample", PANEL, "DModelPanel" )

local f = vgui.Create( "DFrame")
f:SetSize(500, 500)
f:Center()
f:MakePopup()

local a = f:Add("DModelPanelExample")
a:SetModel("models/alyx.mdl")
a:Dock( FILL )
```

![image](https://cloud.githubusercontent.com/assets/3299036/7556158/2024b492-f76e-11e4-92a4-a29a61834c65.png)


It does work.

**Comment by robotboy655** [comment]
The default camera angles are not inherited for some reason though.

**Comment by UselessGhost** [comment]
Yeah, sorry, didn't realize it actually was just rendering off camera.

**Comment by wiox** [comment]
You're not passing Paint's parameters to the base method.
