### ISSUE TITLE
DoModal on two DFrames prevents interection with any of them

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#2015]
Input gets completely blocked and user is left with nothing but closing the game.

**Comment by robotboy655** [comment]
I've made a change to DoModal that should've been in the game a long time ago, but anyway, if cursor is not visible, DoModal will no longer work, call MakePopup() before DoModal(), that way I do not see any problems running this code:
```
concommand.Add("test", function(ply, cmd, arg, str )
	local f = vgui.Create("DFrame" )
	f:SetSize(500, 500)
	f:Center()
	f:MakePopup()
	f:DoModal()

	if ( str != "" ) then return end
	timer.Simple( 2, function() RunConsoleCommand("test", "Da") end )
end)
```

**Comment by robotboy655** [comment]
If the issue persits, please post code to repro.
