### ISSUE TITLE
Downloading Bug (MAC)

### ISSUE THREAD

**Issue by ZactacularZman** [Facepunch/garrysmod-issues#2018]
When I join big servers with a lot of players and downloads, right before its about to send client info, my gmod crashes. Keep in mind im on a mac, and this bug is only on a mac, i know this because others are having the same probablem and i have tried it on a windows computer. Im very frustrated that gmod doesnt care about mac users :(

**Comment by BytewaveMLP** [comment]
You imply Facepunch doesn't.

**A:** This isn't the place to get help. [This is](http://facepunch.com/forumdisplay.php?f=16).  
**B:** Don't join servers with a lot of addons, or remove some of your own. Garry's Mod's stability is dependent on system resources, and Macintosh computers aren't necessarily the best computers for that market.

**Comment by robotboy655** [comment]
Duplicate or similar to #888
