### ISSUE TITLE
DLabel:SetTextColor not working when setting the font to Trebuchet24

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2019]
I made a DLabel, set the font to Trebuchet24 and the color to (50,50,50). The result was a label that was way too bright.
```lua
local frame = vgui.Create("DFrame");
frame:SetSize(200,200);

local function newlabel()
	local label = vgui.Create("DLabel", frame);
	label:Dock(TOP);
	return label;
end

frame.label1 = newlabel();
frame.label1:SetText("Hello world 1");

frame.label2 = newlabel();
frame.label2:SetText("Hello world 2");
frame.label2:SetTextColor(Color(50, 50, 50));

frame.label3 = newlabel();
frame.label3:SetText("Hello world 3");
frame.label3:SetFont("Trebuchet24");
frame.label3:SetTextColor(Color(50, 50, 50));

frame.label4 = newlabel();
frame.label4:SetText("Hello world 4");
frame.label4:SetFont("DermaLarge");
frame.label4:SetTextColor(Color(50, 50, 50));

frame:Show();
```
[Results](http://prntscr.com/7549kn)
From this test we can see that setting the font to Trebuchet24 changes the behaviour of SetTextColor. It almost seems the font forces the color or has fixed transparency.
Even though [this wiki page](http://wiki.garrysmod.com/page/Default_Fonts) shows the font doesnt have a default transparency.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/7634203/fe52abe8-fa61-11e4-8623-48d74cc4af68.png)

Looks proper on my end. Also keep in mind that there's "additive" parameter a font can have ( See http://wiki.garrysmod.com/page/surface/CreateFont ), which makes the font translucent and brigther, which is what is happening on your end. ( Try setting the color to RED ), the weird part is why your font has the flag and it doesn't on my end, try validating your game.
