### ISSUE TITLE
Npc's don't produce footstep sounds when moving

### ISSUE THREAD

**Issue by thecombinepotato** [Facepunch/garrysmod-issues#2020]
NPCs don't seem to make noises when moving, such as the antlion guard not making the big thump upon moving and the combine soldier not have the heavy gear sound.

**Comment by thegrb93** [comment]
Huh that's weird I never noticed, but you're right.

**Comment by thecombinepotato** [comment]
It sure is weird. I think it's been like that since the previous version of Gmod but I'm not entirely sure, could be less or longer than that.

**Comment by imp0se** [comment]
Don't think they've ever made footstep noises.

**Comment by daunknownman2010** [comment]
This bug has been around after Garry's Mod 9 but before Garry's Mod 13.
