### ISSUE TITLE
Crashes when console, i have to press the chat button before i can use /, etc

### ISSUE THREAD

**Issue by ConorWolf** [Facepunch/garrysmod-issues#2022]
So everytime i open the console it crashes it's really annoying also when i touch the button /  i crash too because sometimes i forget to use the enter button (My chat button) then it crashes too and when i open up gmod (maybe this is normal)its frozen and i have to wait till it's unfrozen finally again this can be like 6 minutes sometimes it's really annoying like i have had so many crashes in garry's mod it's just that im sick of it and i decided to report it..
and also it redownloads addons when i start gmod sometimes and when i join a server i have to do with option>multiplayer i have to set do not download any addons because it redownloads ALL of them.

Thank you for reading i hope you could help me these problem is really annoying

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16.

( This is caused by you using DirectX 8 )
