### ISSUE TITLE
Missing "Q key" and "C key" menu textures

### ISSUE THREAD

**Issue by DeathCustard** [Facepunch/garrysmod-issues#2023]
Whenever i'm playing Gmod I Encounter this problem. When I load into a sandbox game the Q key, C key and tips pop ups have missing textures. And by missing textures I mean they are pink and black. I can scroll through the menu and spawn like normal. But some spots (Mostly the tools section.) is pitch black. I've looked everywhere for a solution but there is nothing! This is the only reason i steer away from playing Gmod. I've been playing the game for a couple years now, and its one of my favourites. And I would really love to get back to playing. Thanks :D

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/7650607/e0c2fdb8-fb00-11e4-824c-3459e91183e3.png)

**Comment by DeathCustard** [comment]
Hey robotboy655, I've tried doing what you told me to do multiple times and i'm still ending up with a missing menu. :P
