### ISSUE TITLE
Garry's Mod doesn't load L4D2 DLC content.

### ISSUE THREAD

**Issue by LordCasco** [Facepunch/garrysmod-issues#2027]
It seems Garry's Mod doesn't load L4D2 DLC content.

It only loads this path folder (common\left 4 dead 2\left4dead2),
but not the DLC ones. (common\left 4 dead 2\left4dead2_dlc1, left4dead2_dlc2 and left4dead2_dlc3)

Thus doesn't load the maps, models, materials and sounds found in these folders.

**Comment by willox** [comment]
Servers will still need to mount each directory in mount.cfg. Clients will just automatically mount the DLCs alongside base L4D2.
