### ISSUE TITLE
Engine Error : CMDLCache : out of memory

### ISSUE THREAD

**Issue by PawPewPow** [Facepunch/garrysmod-issues#2028]
When i start GMod , its good , i play Prop Hunt , its still good , but when i play GTA on GMod , when im downloading the Data from Workshop for 20 Min , its good , but then The Gmod closed and this think pop out
"Engine Error
Engine Error CMDLcache : out of memory "
http://img405.imageshack.us/img405/3785/errorzg.jpg

Need to fix This T_T Please i really wanna play , some people say give them ur spec 
well here is my spec : 
- Intel(R) Core(TM) 2 Duo CPU , E7500 2.9GHz ~ 2.9GHz
- 2 GB RAM
- DirectX 11
- Windows 7 Professional 32-bit
- NVIDIA GeForce GT 220

Thats what i know ...

Please i really wanna play ;_; Please Please Please HELP ;_;

**Comment by thegrb93** [comment]
You definitely need more RAM.

**Comment by PawPewPow** [comment]
Minimal ram ?

2015-05-17 1:28 GMT+07:00 thegrb93 <notifications@github.com>:

**Comment by thegrb93** [comment]
My computer is using 3.5GB right now with firefox and Garrysmod open. You might want to consider 8GB to be safe.

**Comment by imp0se** [comment]
2GB, not even Source can operate nicely with that, and that's astonishing.
As thegrb93 said, get more RAM (and of course get a 64-bit OS)

**Comment by thefunny711** [comment]
I have 8GB of RAM and yet I get this. It says I have 7.48 usable.

**Comment by robotboy655** [comment]
GMod, and any other Source Engine 1 game can only use 4GB on your RAM due to them being 32bit applications.

**Comment by thefunny711** [comment]
I've been playing it now for a few weeks, I had to dismount EVERY game, but it now works.
