### ISSUE TITLE
GibBreakServer does not spawn gibs

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#2029]
`PrecacheGibs()` was called. `GibBreakClient()` does work. Model tested was `models/props/cs_office/computer_monitor.mdl`

**Comment by TheFreeman193** [comment]
This works for me. Have you tried this in vanilla GMod?

**Comment by Mornedil** [comment]
Exact same issue for me.
GibBreakServer doesn't spawn gibs, but GibBreakClient does.

**Comment by Kefta** [comment]
Did you use PrecacheGibs before spawning them?

**Comment by krimsungh** [comment]
I am also having the same issue. Despite this post is 5 years old, it is still an issue. I also called PrecacheGibs and still does not work.

**Comment by robotboy655** [comment]
As stated on the wiki:
>This function is affected by props_break_max_pieces_perframe, props_break_max_pieces and breakable_multiplayer (must be set to 0, which also would make all prop gibs spawn serverside) console variables.

**Comment by robotboy655** [comment]
Alright made it not be affected by breakable_multiplayer.
