### ISSUE TITLE
Garry's Mod won't load up ( Mac Version )

### ISSUE THREAD

**Issue by acegaming** [Facepunch/garrysmod-issues#2031]
Garry's Mod won't load up, it show hl2_osx on the task bar at the top of the screen, but it closes down 1 or 2 seconds later.

My Mac's Specs:
 Model Name:	Mac Pro
  Model Identifier:	MacPro1,1
  Processor Name:	Dual-Core Intel Xeon
  Processor Speed:	2 GHz
  Number Of Processors:	2
  Total Number Of Cores:	4
  L2 Cache (per processor):	4 MB
  Memory:	12 GB
  Bus Speed:	1.33 GHz
  Boot ROM Version:	MP11.005C.B08
  SMC Version (system):	1.7f10
  Graphic Card: 
    Chipset Model:	ATI Radeon HD 5000
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Total):	1024 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x68b8
  Revision ID:	0x0000
  Memory:
  ECC:	Enabled

DIMM Riser A/DIMM 1:

  Size:	1 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x0809E811

DIMM Riser A/DIMM 2:

  Size:	1 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x02000E2A

DIMM Riser B/DIMM 1:

  Size:	1 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x0A005C12

DIMM Riser B/DIMM 2:

  Size:	1 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x01000F15

DIMM Riser A/DIMM 3:

  Size:	2 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x0206E92F

DIMM Riser A/DIMM 4:

  Size:	2 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x0206E824

DIMM Riser B/DIMM 3:

  Size:	2 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x01053629

DIMM Riser B/DIMM 4:

  Size:	2 GB
  Type:	DDR2 FB-DIMM
  Speed:	667 MHz
  Status:	OK
  Manufacturer:	0x8551
  Part Number:	0x463036313031302020202020202020202020
  Serial Number:	0x02075F2C

**Comment by TheFreeman193** [comment]
Do you get a report dialog? A crashlog will be far more helpful to us.

Things to try:
* [Verify your game cache](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335)
* Test with a clean copy of the game
