### ISSUE TITLE
Soundscapes packed into bsp do not load

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-issues#2032]
Using any packing application such as pakrat or bspzip to pack a soundscape (could be .txt files in general) does work. However, the soundscape does not load once in-map. Tried packing it into the bsp from the scripts folder and just packing it in by itself, but it still does not load.

**Comment by robotboy655** [comment]
You never learn do you.

Post as much info as you can. Everything. What you tried, which folders, which file names, what your map name was. Jeez.

**Comment by imp0se** [comment]
;c
Map name: gm_degenerate
Soundscript file name: soundscapes_degenerate.txt
Soundscape name: degenerate_outdoors_storm
Soundscript: http://pastebin.com/XshhVJh1
No matter where you put the .txt in the bsp, no matter how you pack it, it will not load in game. The file DOES pack, but despite this, it does not load in-game when an env_soundscape using its soundscape name tries playing / does not play the soundscript/soundscape.
Tried packing it with the scripts folder, tried packing it by itself.

**Comment by robotboy655** [comment]
Do not confuse soundSCAPES and soundSCIPTS. They are different.

Add the paths you tried adding the file to. ( scripts/, etc )

**Comment by imp0se** [comment]
Tried adding it to:
scripts/
data/
lua/
sound/
...as well as the base
Didn't see much use in attempting to pack into a path other than scripts/

**Comment by imp0se** [comment]
Okay, you'd need to put the soundscape into the soundscapes_manifest.txt. However, this isn't possible without overwriting it.

**Comment by FirstRoboticsGuy999** [comment]
You probably need to make an custom soundscape manifest and make sure it's in the "scripts" folder in the directory

**Comment by imp0se** [comment]
I obviously do have an env_soundscape entity in my map. Sure, you would need to add it to load in the soundscapes_manifest, however you cannot do that without overwriting it.

**Comment by robotboy655** [comment]
?

**Comment by imp0se** [comment]
??
What

**Comment by robotboy655** [comment]
I guess it is worked around by the "sound.Add alternative for soundscapes" request.

**Comment by imp0se** [comment]
So, keep this closed?
