### ISSUE TITLE
Garrysmod failing to mount correctly on Linux automatically - issue with gamedepotsystem

### ISSUE THREAD

**Issue by Kiwi-1995** [Facepunch/garrysmod-issues#2033]
Automatically the game detects a few games and leaves out the rest and fails to mount certain games. However manual changes are required to mount all games. This is not a new issue this is an old issue. But this is more directly at the problem and a work around since [awesomium](https://github.com/Facepunch/garrysmod-issues/issues/86) refuses to play nicely with Linux and OSX.

"gamedepotsystem"
{
	"hl2"		"1"
	"cstrike"		"1"
	"tf"		"1"
	"ep2"		"1"
	"portal"		"1"
	"portal2"		"1"
}

Above text is a manual configuration which does correctly mount all games listed.

However this is a automatic configuration

"gamedepotsystem"
{
	"hl2"		"1"
	"cstrike"		"1"
	"tf"		"1"
	"ep2"		"1"
}

Even though Portal 2 and Portal is installed it will incorrectly mount those and it will also incorrectly EP2 as well.

**Comment by robotboy655** [comment]
What's the issue exactly? The mount menu not opening is already reported.

**Comment by Kiwi-1995** [comment]
It isn't mounting anything.

**Comment by robotboy655** [comment]
It isn't mounting anything? According to your previous post, you say that ```Above text is a manual configuration which does correctly mount all games listed.```

**Comment by Kiwi-1995** [comment]
Yeah but automatically it's only mounting Cstrike and HL2. Nothing else.

**Comment by robotboy655** [comment]
If mountdepots.txt, the only 4 games above will be marked to be mounted, regardless of what games you have installed. It's not a bug. It is intended.

**Comment by Kiwi-1995** [comment]
Shouldn't it be created anyway and shouldn't it contain the games to mount based on what you have installed?

**Comment by robotboy655** [comment]
No, you don't want to have all games mounted by default, it reduces performance ( Loading times ). Only vital for gameplay games are mounted. ( Games that most servers might use or are using )

**Comment by Kiwi-1995** [comment]
Thanks for clearing that up anyway. It just didn't make sense as to why but I get that now. Thanks.
