### ISSUE TITLE
Garry's Mod Bugs (Can't use any weapon, can't spawn things)

### ISSUE THREAD

**Issue by qwertrewq** [Facepunch/garrysmod-issues#2035]
I got a new laptop, and then installed GMod, but it's all bugged. In my old desktop it was ok, then it satred bugging the same way (Can't use weapons), but in my new laptop, it has even more bugs! (Can't use weapons, can't spawn things) My laptop is a Samsung ATIV Book 2, 8GB RAM 1TB HD.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
