### ISSUE TITLE
buttons (tool) don't work when loading saves

### ISSUE THREAD

**Issue by 64m3r** [Facepunch/garrysmod-issues#2037]
Basically none of the buttons work that i placed on the map. Controlling the machines through the NUMPAD shortcuts works, but when i use a button it doesn't react.
I even tried right clicking the button to edit it/ change it's key... doesn't work.
NOTE: the Button(TOOL) , not the keyboard buttons.

**Comment by robotboy655** [comment]
Cannot confirm, after loading a save, I can still enable a Light set to Numpad 0 by using my Button set to Numpad 0.
