### ISSUE TITLE
Engine Error ( Please let me know if you fix this issue! )

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#2039]
Receiving an odd error with the latest dev-build. It came up while I was joining my local dev server. The client crashed shortly after during autorefresh ( updating a DarkRP addon for a friend ). Then this shows up each time I try to open gmod.

Launch Options: -multirun -steam -windowed -w 1280 -h 768 -condebug +mat_bumpmap 0 +mat_picmip 2 +exec autoexec.cfg +exec highres.cfg +hr +toggleconsole +lastlocal

Where execs are for video settings, +hr sets it to high-quality and +lastlocal connects me to last dev-server I started.

Everything below this is in the dialog ( I am not asking for solutions, the dialog did ).

-----------------------------------------------------------------------
Engine Error
-----------------------------------------------------------------------
Steam Error: No SteamUser.

- Make sure that Steam is up to date.
- Make sure that Steam is running.
- Try restarting your PC.
- Try deleting ClientRegistry.blob & restartiing Steam
- Try Garry's Mod -> Delete Local Content

Please let me know if you solve this bug!
-----------------------------------------------------------------------

Everything above this is in the dialog ( I am not asking for solutions, the dialog did ).

Restarting Steam resolved the issue ( NOTE: I left the Engine Error dialog up to copy it down while I exited and relaunched Steam, accidentally.. Steam reported the game was already running when I tried starting it again then I exited the dialog and relaunched whereby it said the game was still running because hl2.exe didn't close for a few more seconds... Then it started just fine... )

I am running latest dev-build. I have issues using the Verify Integrity of Game Cache because Steam always reports that I have a game or tool running when nothing is; it typically only works if I reboot or restart Steam.. I reported this issue to Steam but no solution was offered.

Hopefully this helps...

**Comment by wiox** [comment]
Try toggling your beta status for Steam in Steam's settings.

**Comment by Bo98** [comment]
I've been getting this a lot recently too. Restarting works every time.

**Comment by robotboy655** [comment]
I know that this may happen after playing pirated Steam games.

**Comment by Bo98** [comment]
Happens if I leave Steam on overnight.

**Comment by Acecool** [comment]
I haven't seen the dialog since it showed earlier... I don't have any pirated games on my computer and the only game I was working with was GMod; I do have multi-run enabled on GMod and the server starts with sv_lan 1 and insecure so there shouldn't be an issue with that either...

I also leave Steam on 24/7 and I often leave the game up 24/7 too.... I should mention I did have one of my dev servers up for 3 days or so before launching a DarkRP dev to fix an addon for a friend; it said something about port 27020 and 27006 or so being in use and that it was going to use 27022 but ended up using 27025 anyway...

I do have Family Sharing enabled / set up for my account on my network but I don't think anyone accessed anything ( she would've told me )

This was the FIRST time this dialog ever showed up for me and it kept showing up until I exited steam ( as aforementioned )....

**Comment by Yuri6037** [comment]
This happens to me too but rarely. Usualy this happens when Steam runs for too long time (when I left Steam for an entire night, the next day it does throw this. Also note that on my side restarting Steam doesn't change anything, but rebooting Computer (which shutdows when you reboot it) solves the problem. It's quite annoying, because actualy I have 4 slow (but realy stable no bad sectors) hard disks to boot when my computer starts up...

**Comment by robotboy655** [comment]
I have my laptop running for WEEKS without it ever popping up. Something on your systems is messing with registry I am assuming. Something makes the SteamAPI not work.

**Comment by Bo98** [comment]
Seems to have stopped happening for me lately. Is there any debug info you'd want the next time this happens?

**Comment by robotboy655** [comment]
I don't think there's anything we can do to stop SteamAPI from failing to load. Maybe SteamAPI update will help, we'll see.

**Comment by FirstRoboticsGuy999** [comment]
This message only appears for me when Steam isn't running. Launching Garrysmod doesn't open Steam on it's own; so Steam has to be running first in my experience.

**Comment by robotboy655** [comment]
Well that's one of the obvious causes of Steam API not working.

**Comment by kenken7679** [comment]
I solved the bug: The reason why there is no "SteamUser" is because no user is signed into Steam right? Well, the only reason why nobody is signed to Steam is because it didn't start! Steam didn't start when the OS started. I figured this out because I disabled Steam on Windows startup, which means that it can`t be signed in, creating the "No SteamUser" error we know and love...

**Comment by robotboy655** [comment]
Well obviously this error would happen if Steam isn't running, but that is not the only cause.

**Comment by Acecool** [comment]
I leave my PC on 24/7 and only restart for Windows updates, reluctantly, so my machine stays on for weeks or months at a time between restarts. This is the first, and only, time this error has ever appeared.

I rarely restart Steam and only do it if there is something that needs to be addressed ( such as GTA 5 had an area of the map which was corrupted and broke everything about the game and after the features broke the game crashed shortly after; Steam needed to be restarted, because even though no games or tools were running, Steam reported that all games and tools needs to be shut-down to run a validation... This is an issue with Steam which happens after I launch a game... The other reason I restarted steam was because I clicked cancel on the "restart steam" on the update for Steam Service [ Steam, and other utilities to keep games updated are becoming too bulky in my opinion ] which prevented games from launching - steam api... )

If Steam can not be controlled from within a game or on game-launch such as checking the API and issuing a restart command if not started, then it'd be a Steam issue to fix ( and, honestly, if this is the issue then each game developer shouldn't be responsible other than an api call, at most to check if launched, for certain features; it would be a Steam issue )...

I typically run my dev / local server as sv_lan 1 and insecure to allow multiple clients to join, and I rarely update anything other than GMod, CStrike and TF2 on server-update ( leaving the steam-requires-login games for rare updates which weren't part of anything recent ) so updating anonymously wouldn't have force logged me off ( although I do have issues with SteamCMD not releasing files at times [ or a similar issue ] which causes an exit warning when I close the window when +quit doesn't automatically; this may or may not be part of the issue....

I don't think it is a Steam running for too long as I rarely ever reboot or restart steam ( even when issues arise with needing to revalidate; I wait days or longer, if needed ).. Something must be triggering it and it may be with SteamCMD ( Robot, you use this, right? ) or something else ( updates or steam bug? )...

**Comment by kenken7679** [comment]
@robotboy655 
Yes, I understand that Steam not running isn't the only cause, but it makes sense: No Steam = No SteamUser. So, if the only cause isn't that Steam isn't running, it would have to be a portion of Steam that isn't running, like something that does user or user license authentication or something...

**Comment by kenken7679** [comment]
@Acecool 
Can you get me the information for your computer?
(Such as how much RAM you have, the processor that you have, the Motherboard you have, the Windows version you run, the architecture of the processor you use, the architecture of the Windows you use, etc.)
