### ISSUE TITLE
DProperties Setup("Generic") Error

### ISSUE THREAD

**Issue by Rainbow-Tech** [Facepunch/garrysmod-issues#2040]
# Basic Info

* Game version: 15.03.09
* Error: attempt to call method 'IsEditing' (a nil value)
* File: garrysmod/lua/vgui/prop_generic.lua
* Line: 20
* Full Error:
```
[ERROR] lua/vgui/prop_generic.lua:20: attempt to call method 'IsEditing' (a nil value)
  1. unknown - lua/vgui/prop_generic.lua:20
```
# How to recreate
```lua
local DermaPanel = vgui.Create("DFrame")
DermaPanel:SetSize(250, 150)
DermaPanel:Center()
DermaPanel:SetTitle("Bug Recreate")
DermaPanel:MakePopup()

local DProperties = vgui.Create( "DProperties", DermaPanel )
Row = DProperties:CreateRow("Please", "Fix")

Row:Setup("Generic") --Generic is the only one i know of that throws this error
Row:SetValue("Please fix")
Row.DataChanged = function( _, val ) print(val) end
```

# More Info
I have been using the DProperties Generic setup for my settings menu.
I forgot what update broke it, I thought it was me messing up something. But i guess not.

**Comment by robotboy655** [comment]
1) Your code doesn't even create a valid panel
2) Using this code, there are no Lua errors:
```
local DermaPanel = vgui.Create("DFrame")
DermaPanel:SetSize(250, 150)
DermaPanel:Center()
DermaPanel:SetTitle("Bug Recreate")
DermaPanel:MakePopup()

local DProperties = vgui.Create( "DProperties", DermaPanel )
DProperties:Dock(FILL)
Row = DProperties:CreateRow("Please", "Fix")

Row:Setup("Generic") --Generic is the only one i know of that throws this error
Row:SetValue("Please fix")
Row.DataChanged = function( _, val ) print(val) end
```

**Comment by Rainbow-Tech** [comment]
Then i have no idea why i am getting this "IsEditing" error on my end.

I guess i will have to do something else, My friends have the same thing.

**Comment by robotboy655** [comment]
Validate your server files. Try if it works by editing ( Right click on the entity in sandbox -> Edit properties ) the default Sandbox entities like Sky Edit. If it errors - the problem is on your side. But then again, the problem is 99% on your side.

**Comment by Rainbow-Tech** [comment]
I got it working, I looked at prop_generic. I did not know you had to add a table for it

```lua 
Row:Setup("Generic", {waitforenter = false})
```

Thanks for reminding me about the sky editor, I would have never fixed this if i didn't come here
