### ISSUE TITLE
Setup("Generic")

### ISSUE THREAD

**Issue by Senkaaaa** [Facepunch/garrysmod-issues#2041]
Version: 15.03.09
Error:

[ERROR] lua/vgui/prop_generic.lua:20: attempt to call method 'IsEditing' (a nil value)
  1. unknown - lua/vgui/prop_generic.lua:20

The lua that i use
lua
local DermaPanel = vgui.Create( "DFrame" ) -- Creates the frame itself
DermaPanel:SetPos( 50,50 ) -- Position on the players screen
DermaPanel:SetSize( 1000, 900 ) -- Size of the frame
DermaPanel:SetTitle( "Testing Derma Stuff" ) -- Title of the frame
DermaPanel:SetVisible( true )
DermaPanel:SetDraggable( true ) -- Draggable by mouse?
DermaPanel:ShowCloseButton( true ) -- Show the close button?
DermaPanel:MakePopup() -- Show the frame

local DProperties = vgui.Create( "DProperties" )
local Row1 = DProperties:CreateRow( "Category1", "Row1" )
Row1:Setup( "Generic" )
Row1:SetValue( "Hello World!" )
Row1.DataChanged = function( _, val ) print( val ) end

DProperties:Dock(FILL)

FUCKING READ ME
lua/vgui/prop_generic.lua IS NOT MY FILE

**Comment by robotboy655** [comment]
Don't recreate issues.
