### ISSUE TITLE
CNavArea:GetAdjacentAreas doesn't give all adjacent areas.

### ISSUE THREAD

**Issue by raubana** [Facepunch/garrysmod-issues#2043]
I was testing out some features for Gmod dev branch 2015.05.05. I found this by mistake - I was trying to create my own player bots from scratch (since player NextBots haven't been implemented yet), but I noticed my bots kept giving me failure messages when trying to calculate paths using a custom path finding algorithm. The weird thing was this was happening when I was just a couple of feet away sometimes.

I ran this code to test this out.

```lua
function GM:Think()
	local pl = ents.FindByClass("player")
	for i,ply in ipairs(pl) do
		if not ply:IsBot() then //I'm playing with bots right now, so...
			local tr = ply:GetEyeTrace()
			local closest = navmesh.GetNearestNavArea(tr.HitPos)
			closest:Draw()
			local adjacent = closest:GetAdjacentAreas()
			for j,nav in ipairs(adjacent) do
				nav:Draw()
			end
			break
		end
	end
end
```

You can see that the area to the right of the CNavArea I'm pointing to isn't showing up, even though it is connected to it.

![image](https://cloud.githubusercontent.com/assets/5302549/7804163/c1a399d6-032c-11e5-98bb-9ac5d4fd798a.png)

Doing the same test without the above code and instead with nav_edit 1 shows the connection does in fact exist.

![image](https://cloud.githubusercontent.com/assets/5302549/7804229/e44b9d2a-032d-11e5-9091-82edb6d0079a.png)

There were weird disconnects all over the map, which caused my path finding algorithm to give really shitty solutions... when it wasn't failing, I mean. The point being, this is something that probably will need to be fixed before the next release, what with all the nextbot stuff being planned.

**Comment by robotboy655** [comment]
No, the function works properly, your problem is ipairs since the table has a 0 indexed element ( I will maybe fix that )

**Comment by raubana** [comment]
Wait, I'm confused. Is there a bug with ipairs, or with CNavArea:GetAdjacentAreas?

**Comment by robotboy655** [comment]
Neither, pretty sure ipairs just doesn't count the 0 indexed element, I will correct that for all new navmesh functions. ( Why did you even use ipairs here? )

**Comment by raubana** [comment]
I'm more of a python guy. I usually just do
```python 
for x in y:
    ....
```
and it iterates the entire list. I knew that lua was different, what with 1 being the first index instead of 0, but I hadn't realized it'd skip over the 0'th index. If it's not too much hassle, do you know of a temporary work-around I could use for the time being?

**Comment by robotboy655** [comment]
Use ```pairs```, not ```ipairs```

**Comment by robotboy655** [comment]
Check wiki pages for both functions for more info, you only want ```ipairs``` when the loop order matters.

**Comment by raubana** [comment]
I didn't think pairs worked without keys. Oops.

**Comment by robotboy655** [comment]
Numbers are still keys.
