### ISSUE TITLE
navmesh.GetNearestNavArea sometimes returns CNavArea[NULL]

### ISSUE THREAD

**Issue by raubana** [Facepunch/garrysmod-issues#2044]
Sorry, I accidentally sent this before I'd typed anything, give me a second...

EDIT:

Alright, I don't have much to go off of here, other than this variable I printed from each of my bots. The one causing the error wasn't checking if the nav was valid (using IsValid), just if it was not nil. You can see that that particular CNavArea doesn't have an ID.

![image](https://cloud.githubusercontent.com/assets/5302549/7824400/aba7a510-03d0-11e5-8c50-7312f5fde0e5.png)

Obviously not an urgent problem, but it's something that might cause some people problems. It wasn't clear in the wiki if this was meant to happen or not, especially considering I hadn't used any filters.

**Comment by robotboy655** [comment]
Of course sometimes it will return an invalid CNavArea when it can't find a nearest nav area considering the options you have to the function.

http://wiki.garrysmod.com/page/navmesh/GetNearestNavArea

Might need to adjust things like ignoreZ and maxdist.
