### ISSUE TITLE
My materials arn't loading

### ISSUE THREAD

**Issue by Sp1ttingLlama** [Facepunch/garrysmod-issues#2045]
So I have been having an issue lately where when I spawn a prop and try to put a material on it they don't show up. I'm not talking about error signs, purple & black squares, etc. Other things it effects are textscreens where the middle isn't transparent, fading doors don't go transparent. It used to work before and I have tried installing and uninstalling Gmod, CS:S, TF2.

**Comment by robotboy655** [comment]
You are running the game with DirectX 8, switch to DirectX 9.
