### ISSUE TITLE
Gmod Crash like if we quit the game

### ISSUE THREAD

**Issue by Matspyder51** [Facepunch/garrysmod-issues#2048]
Actually, I working on a Ships HUD, but I don't know why, but after some minute with the HUD Draw (When I was in the ship) My Gmod crash, but I don't have error message, it's just a crash like if I quit the game, so I don't know what's going on because I don't have the Console client for show the error line ...

Sorry for my English, I'm French.

**Comment by robotboy655** [comment]
This is not a place to get help with developing mods for the game.

Seek help here: http://facepunch.com/forums/65 And don't forget to post the code that crashes.
