### ISSUE TITLE
Issue with Barnacles and noclip

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-issues#2051]
If a Player is picked up by a Barnacle NPC while they are noclipping, it will appear to disable noclip, but the engine flag `EFL_NOCLIP_ACTIVE` will still be set. So running `ply:IsEFlagSet(EFL_NOCLIP_ACTIVE)` on a Player that has been grabbed by a Barnacle and no longer appears to be noclipping *will return true*.
This could ruin other game elements or addons that rely on telling whether a Player is noclipping or not.

**Comment by robotboy655** [comment]
You usually do this check by using ```GetMoveType() == MOVETYPE_NOCLIP``` instead of EFlags.

Anyway, barnacles will no longer be able to pick up players in noclip.
