### ISSUE TITLE
Windows 8/8.1 downloading wrong version of Gmod 13 dedicated server with SteamCMD

### ISSUE THREAD

**Issue by dany777** [Facepunch/garrysmod-issues#2052]
So i saw there was a Gmod 13 update and so i decided to update it via my PC Windows 8.1
But after is done, when i tried to join my server, it said that the server you are trying to join is running on an older version

On my laptop Windows 7 it downloads the right version, so i had no choice but to download the update via my Windows 7 and then transfer it to my PC Windows 8.1

This is extremely annoying for me, please fix this problem

**Comment by neico** [comment]
It's more likely that your steamcmd client didn't get the new metadata yet, maybe try it again?

![](http://puu.sh/i8mvN/567bbbae8d.png)

**Comment by robotboy655** [comment]
There's nothing we can do about SteamCMD - we are not Valve.
