### ISSUE TITLE
New update bug

### ISSUE THREAD

**Issue by KJelles** [Facepunch/garrysmod-issues#2053]
I'm a TTT Player, 2.5k hours in TTT, and today there's been a update regarding UPD
Allowed spectators to talk in all chat – redirects to team

Whenever u die in mid-round and u press "Y" and u say something in chat then the server crashes, it's not just happening on my own server, but on every TTT server

Just pointed this out :)

(Sorry, English is not my native language)

**Comment by robotboy655** [comment]
I can confirm.

**Comment by FastDeath** [comment]
I can confirm too,
the ``ply:Say(text, true)`` call in ``terrortown/gamemode/gamemsg.lua`` on line 124 is creating an infinite loop, because the PlayerSay hook is called without the `` team_only `` argument being true even though it should be.

**Comment by wiox** [comment]
> Allowed spectators to talk in all chat – redirects to team

https://github.com/garrynewman/garrysmod/pull/890
