### ISSUE TITLE
.OGG sound object can't be manipulated as a global variable

### ISSUE THREAD

**Issue by mattkrins** [Facepunch/garrysmod-issues#2054]
I have noticed that .OGG sound objects can't be manipulated as a global variable.

Example code for replication: 
```lua
SOUND = false -- defining as global
function STARTOGG()
	SOUND = CreateSound( LocalPlayer(), "somesound.ogg" ) -- creating sound
	SOUND:Play() -- sound plays as usual
end
concommand.Add("startogg", STARTOGG)
	
function STOPOGG()
	if SOUND then print('true') end -- print's true
	SOUND:Stop() -- but we can't stop it?
end
concommand.Add("stopogg", STOPOGG)
```
MP3's/WAV's have no issue, it is only with OGG files.

**Comment by TheFreeman193** [comment]
The scope of the variable isn't relevant. This appears to be a problem with CSoundPatch:Stop() and OGG files. After calling Stop(), IsPlaying() returns false, yet the sound continues. The sound also does not loop. The other CSoundPatch methods work as expected.

**Comment by 00875** [comment]
SOUND = false -- defining as global
This is not needed, without 'local' any variable will become global

**Comment by robotboy655** [comment]
It seems that EmitSound doesn't play with .oggs properly.

**Comment by robotboy655** [comment]
Will be fixed.
