### ISSUE TITLE
Garry's mod crashes without error

### ISSUE THREAD

**Issue by Sypho** [Facepunch/garrysmod-issues#2055]
When I play garry's mod in single player works well same when I play murder or prop hunt servers but in DarkRp he download all addons but in the last one he crashes without error and with no reason
My config : processor : Intel(R) Core(TM) i3 CPU 540 @ 3.07 GHz 3.06 GHz
                           ram : 3 Go
              graphic card: Nvidea Geforce G210
             I have 1To of clearance
So I would like you to give me a solution for my BUG

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
