### ISSUE TITLE
Addon "updated" Creates Errors

### ISSUE THREAD

**Issue by EmperorMinilla** [Facepunch/garrysmod-issues#2058]
After I downloaded the latest GMOD update, I keep seeing a note on the top-left of my screen saying: The "addon "updated" is creating errors, check the console for details.

When I check the console, it repeatedly spams this:

[updated] lua/autorun/client/stt_aircraft.lua:136: Tried to use a NULL entity!
1. GetNWEntity - [C]:-1
2. v - lua/autorun/client/stt_aircraft.lua:136
3. unknown - lua/includes/modules/hook.lua:84

[updated] lua/autorun/client/stt_aircraft.lua:119: Tried to use a NULL entity!
1. GetNWEntity - [C]:-1
2. v - lua/autorun/client/stt_aircraft.lua:119
3. unknown - lua/includes/modules/hook.lua:84

[updated] lua/autorun/client/stt_aircraft.lua:136: Tried to use a NULL entity!
1. GetNWEntity - [C]:-1
2. v - lua/autorun/client/stt_aircraft.lua:136
3. unknown - lua/includes/modules/hook.lua:84

This may not seem like a big deal but when you're like me and want to submit a Garry's Mod screenshot to a website, you don't want this note on the screen.

**Comment by daunknownman2010** [comment]
Wait for the addon uploader to fix the addon.

**Comment by EmperorMinilla** [comment]
I just fixed it. The problem WAS NOT from an addon on the Steam workshop.

**Comment by ACSL8R** [comment]
How did you fix it? I'm having the same problem, reply ASAP please.
