### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2059]
Since the gmod update whenever I play TTT I get this error spammed in my console and every player is colored WHITE.
If they die they are colored blue again.

Error: Material models/error/new light1 has bad reference count 0 when being bound

**Comment by deinemudda32** [comment]
Well the error is gone on downloading the newest ttt version of github, but playermodels are colored white either, this wasnt before the update. (happens with no addons)
I beg for a fix for this.

**Comment by robotboy655** [comment]
This is not the place for begging for help, begging for fixes, reporting TTT problems.
