### ISSUE TITLE
There is something wrong with my version of gmod

### ISSUE THREAD

**Issue by aqua3422** [Facepunch/garrysmod-issues#2062]
When I first got gmod I went into sandbox mode to figure out how it works. When the game loaded there was like a big blur on the screen and it moves with the characters view so it didn't go away. I have downloaded it on both my computers and it is on the game still. At first it wasn't a big problem but it is beginning to get harder for me to play and enjoy gmod. Here is a picture http://steamcommunity.com/profiles/76561198181295461/home/# ;please tell me how to fix it because I've really been wanting to play.

**Comment by deinemudda32** [comment]
Screenshot redirects me too my profile history.
Even we need more information like which directx you use?
What settings you made in cfg or ingame in "settings" :P.

**Comment by daunknownman2010** [comment]
I believe that link your supplied goes to the friends activity page. Also, this is not the place for help. Post about this here: http://facepunch.com/forumdisplay.php?f=16
