### ISSUE TITLE
Half-Life 2 Weapons, meh

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2063]
Some bugs I figured out on killing npcs.

Grenades:
Throw all grenades of npc_grenade or weapon_grenade how its called whatever and you have no Weaponmodel, thats okay for 0 grenades but if you switch to another weapon and switch back you have the standard viewmodel again which shows a grenade, but you dont actually have one.
Probably just strip the weapon or use GetViewModelPos on WeaponEquip to check if it has actually ammo on it.

Crossbow:
Same here like on the grenades, but this time with the bolt.
I dont know if there is a animation for the crossbow without a bolt as deploy anim, however.

Stunstick:
Swing, Hold secondary fire and you got a unlimited particle effect on youre stick till you release sec fire. just looks ugly and is nonsense.

Every Weapon:
Shoot(swing), hold secondary fire -> ACT_IDLE animation doesnt play. (stunstick + crowbar doesnt reset to normal position)

S.L.A.M.:
Nonsense.
Why does Slams have ALTERNATE Ammo and not just normal ammo?
If you have more than 9 ammo, then you cant read the number anymore D:

Physics Gun:
Just a reskin of Grav Gun, but doesnt have an Idle animation...

Crossbow again:
You shoot a xbolt on a player, just removes the bolt from the map, but it sticks on walls.
To let the bolt stick in players is nearly impossible, or rather very difficult.
But on props or entities is easy as fuck, so why not?
Just use a SafeRemoveEntityDelayed Timer to remove the Entity after maybe 30 seconds.

Adding a drop function:
I added a drop function, with basic DropWeapon(), but everytime I collect a hl2 weapon I get back the spare ammo, maybe reset ammo to 0 cause you can spawn ammo in the entities tab.

**Comment by thegrb93** [comment]
Good report. Would be good to see these fixed. For your drop function, you can set the ammo of the gun to 0
http://wiki.garrysmod.com/page/WEAPON/TakePrimaryAmmo
http://wiki.garrysmod.com/page/WEAPON/TakeSecondaryAmmo

**Comment by deinemudda32** [comment]
Yea but sometimes theres some alt ammunition still in the swep, want to get that too.
Or isnt it saved?

**Comment by thegrb93** [comment]
Yeah you're right. Also I tested and found that those functions don't work on hl2 weapons.

**Comment by daunknownman2010** [comment]
Grenades & Crossbow(1): They are easy to fix by the developers, if they're willing to re-add the "auto-switch" to a another weapon when ammo is depleted.

**Comment by robotboy655** [comment]
Shit report. Most of these are Half-Life 2 bugs or just the way Valve made things.

One bug per issue.

**Comment by deinemudda32** [comment]
Alot aggree and "Shit Report". gg

**Comment by robotboy655** [comment]
And by "alot" you mean one guy?

It's just not worth the time to look into these minor issues that do not affect the game in any bad way, except for the last issue, which you are free to create a new report/request for.

**Comment by deinemudda32** [comment]
2 guys :D. actually.

**Comment by robotboy655** [comment]
If the issue is small it doesn't mean it's very easy to fix. None of those issues are important but the last one. That's the facts.

**Comment by deinemudda32** [comment]
Actually I worked on alot of weapon bases and as I know so far, 3 out of 5 issues are easy to fix.
I gonna report the last, even If I think its not the biggest.

**Comment by robotboy655** [comment]
Lua is far far far easier than C++. You don't know what you are talking about.

**Comment by deinemudda32** [comment]
I love challenges.
