### ISSUE TITLE
Seats

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2064]
You cant get damage on seats.
Maybe add a playerhull around the seat to add the damage via Damageinfo to the player, thats the easiest and best way I could figure out.

**Comment by thegrb93** [comment]
Already made this issue https://github.com/Facepunch/garrysmod-issues/issues/1056

**Comment by deinemudda32** [comment]
Were talking about all seats, not only the vehicle pot.

**Comment by thegrb93** [comment]
Seats are vehicle pods

**Comment by deinemudda32** [comment]
All of em?

**Comment by thegrb93** [comment]
Yeah

**Comment by daunknownman2010** [comment]
Seats use the same entity class (prop_vehicle_prisoner_pod). This issue has already been addressed and I think the developers should know by now.
