### ISSUE TITLE
lua_run hammer entity input "RunCode" or "RunPassedCode" not firing

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#2068]
I've made several maps and found out there is an issues while working with lua_run entity.
This happen with the current gmod update (15.06.01) that launched few days ago. Tried compiling the map that includes trigger_entity, with Output firing to the the lua_run's "RunCode" input entity but seems no longer firing the lua_run's input. It stays nothing but entity exist in the map.

here's the entity KVs for them:
trigger_once:
name: FireLua
Output: OnTrigger > LuaTest > RunCode > (no params, it'll executed automatically from lua_run's KVs) > 0 sec
(Except with RunPassedCode, I need to put a params for it)

lua_run:
name: LuaTest
Code: print([[hi, this is test entity]])

Console output with developer 2:
(5.49) output: (trigger_once,FireLua) -> (LuaTest,RunCode)()

and seems do nothing at all.
this occurs both in Singleplayer and Multiplayer.

While in garrysmod.fgd game data is present that input already defined for lua_run, but in game engine it seems not firing the entity input.

Does anyone else having this problem ?

**Comment by robotboy655** [comment]
gm_construct ones still work.

And so does this:
```
lua_run for id, ent in pairs(ents.FindByClass("lua_run")) do TRIGGER_PLAYER = Entity(1) ent:Fire("RunPassedCode",[[print("shit", TRIGGER_PLAYER)]]) end
```
