### ISSUE TITLE
Garry's Mod doesnt close

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2069]
If I end garry's mod normally.
In steam it says im playing garry's mod.
Awesomium Core is not in task manager listed, but hl2.exe is.
After 2-3 minutes it closes with a error message which is different everytime, sometimes there isnt one.

**Comment by daunknownman2010** [comment]
Please post this here: http://facepunch.com/forumdisplay.php?f=16

**Comment by deinemudda32** [comment]
Wait? Help and Support for a Crash.
No Support needed.

**Comment by 00875** [comment]
Known issue. Windows running WerFault when gmod closes.

**Comment by thegrb93** [comment]
Happens randomly for me too. I'll have to get a mdmp next time it does.

**Comment by daunknownman2010** [comment]
"Garry's Mod doesnt close" sounded like a something you'd ask the support. I've only had times where hl2.exe just takes awhile to exit but never had an error message or a mdmp appear.

**Comment by thegrb93** [comment]
Here's one https://dl.dropboxusercontent.com/u/72472980/hl2_150601_crash_2015_6_5T4_40_14C0.mdmp

**Comment by robotboy655** [comment]
That crash is happening in KERNELBASE.DLL, a windows binary. Infact, in the entire stack trace there are no GMod binaries, which makes this even harder to debug.

![image](https://cloud.githubusercontent.com/assets/3299036/8005109/107ef662-0b8f-11e5-9b7a-3064df93f0dc.png)

Looks like an infinite loop or something.

I had this problem too after one of the Steam Beta updates but then it just went away.

**Comment by deinemudda32** [comment]
First bug I reported which is taken serious.
Holy.

**Comment by thegrb93** [comment]
Here's a couple more.
https://dl.dropboxusercontent.com/u/72472980/hl2_150601_crash_2015_6_7T7_48_6C0.mdmp
https://dl.dropboxusercontent.com/u/72472980/hl2_150601_crash_2015_6_7T9_11_36C0.mdmp

**Comment by robotboy655** [comment]
First one is a different crash, second one seems to be caused by NVidia drivers?

**Comment by Noiwex** [comment]
Please fix dumps.garrysmod.com.

**Comment by thegrb93** [comment]
My screen flashed black after the gmod window closed when that mdmp was created. Probably isn't the same issue as before though.

**Comment by thegrb93** [comment]
Here's another. Took about 2 minutes for hl2.exe to close. https://dl.dropboxusercontent.com/u/72472980/hl2_150601_crash_2015_6_10T9_24_25C0.mdmp

I also created a .dmp file using the task manager before it crashed, and its 775MB. I'm current uploading it to dropbox.

**Comment by robotboy655** [comment]
```775MB. I'm current uploading it to dropbox.``` are you insane?

**Comment by thegrb93** [comment]
yes

**Comment by robotboy655** [comment]
These dumps are worthless though. That one also crashes in or due to nvidia dlls.

![image](https://cloud.githubusercontent.com/assets/3299036/8079585/3919ed4c-0f6e-11e5-8f7a-e6169570c6fe.png)

**Comment by thegrb93** [comment]
Maybe the other one will have some better info since I grabbed while the process was stuck.

**Comment by thegrb93** [comment]
https://dl.dropboxusercontent.com/u/72472980/hl2.DMP

**Comment by deinemudda32** [comment]
Everytime I close GMod via clicking on the Icon and pressing Close, hl2.exe doesnt close.
Everytime.
If I close GMod ingame, If I have luck it closes, if not same problem.
I manually have to go to Task Manager and close hl2.exe as Im too stupid to wait 3 minutes for it to close :)

**Comment by P4sca1** [comment]
Never had this issue before, using windows 8.1 and AMD Radeon R9 280X. 
Like RobotBoy said: I think this has something to do with your drivers maybe?

**Comment by deinemudda32** [comment]
I have the most updated nvidea drivers for the gtx770. I always have a clean and sexy computer.
I dont think this is a driver issue, because mostly I dont even get a crash, I had tons of issues where hl2.exe ran for hours.

**Comment by P4sca1** [comment]
Really weird... I have no ideo what could cause the crash then. Good luck with fixing it! :)

**Comment by thegrb93** [comment]
Can i get rid of the 775MB one yet?

**Comment by robotboy655** [comment]
Yes you can.

**Comment by UltimateByte** [comment]
I've seen this thing happening for years, even with half-life 2 and CSS... Don't know if it's still doing this as i don't really play those games very often.

Got the same issue, randomly with GMod... Bust most likely after having the game launched for a while, being in pretty heavy games for Source Engine.

Anyone is also having the screen freezing screen sometimes ? Or crash on connection (first image after loading) on some servers ?
https://github.com/Facepunch/garrysmod-issues/issues/2091
 I don't know if all of that is related, just sayin'.

Win7 x64 Ultimate SP1 (all updates done)
GTX 670, latest drivers

Could definately be an nVidia driver issue. Anyone encoutering this with AMD GPU ? If yes, could you please provide a dump file ?

**Comment by HDG-MrDeeJay** [comment]
#2429 I have it too, been happening for over a year now and has been worse with a new install of windows. Old instances of HL2 do not disappear from the task list, instead appearing suspended, with no I/O usage, RAM usage or CPU usage.

**Comment by kem008** [comment]
It is random happening not just garrys mod, all hl2.exe games

**Comment by Shigbeard** [comment]
willox pls is still happens dont close

**Comment by xDShot** [comment]
Happens on Linux hosts too! It just freezes when i press Quit from menu, and I have to pkill it to properly close it.

**Comment by Kefta** [comment]
Happens to me on CS:S and GMod -- not occurring on TF2.
