### ISSUE TITLE
New TTT issue with chat

### ISSUE THREAD

**Issue by Jerpy** [Facepunch/garrysmod-issues#2071]
I understand over the past few days there's been some issues with ttt chat, and how it has been heavily crashing servers everywhere because of when people use binds as spectators, or something of the sort. Currently, with the most up-to-date version of this repo, here is what happens when you try to press Y to chat as a spec

"[ERROR: Translation of spec_teamchat_hint not found]"

And if you press a bind as spectator, thankfully instead of crashing the server, it sends it to allchat. Although, you could see the issue with it sending any bind to allchat for the live people to see as well, as that could probably cause some issues.

**Comment by wiox** [comment]
Do you have a custom chatbox?

**Comment by Jerpy** [comment]
I do not, no.

**Comment by robotboy655** [comment]
Did you install ALL the latest files? Because it sounds like you did not.

**Comment by Jerpy** [comment]
No, I did. It was a complete deletion of the entire gamemode while I had shut the server down to do this, and then I had uploaded the updated gamemode, and started the server back up.

**Comment by Jerpy** [comment]
So is there no fix to this? Because I've confirmed for sure now on a fresh install, with a zero addon test server, that it is not user error and is indeed a problem in the code. I'm just not smart enough to figure out the code error, I suppose.

**Comment by robotboy655** [comment]
Cannot confirm using the latest files.
