### ISSUE TITLE
Bug with playermodels after update?

### ISSUE THREAD

**Issue by KJelles** [Facepunch/garrysmod-issues#2073]
If u crouch in TTT on any server, the head hitbox is in the stomach? we have no custom models at all, and we didn't scale any

**Comment by robotboy655** [comment]
What makes you think that is the case?

**Comment by KJelles** [comment]
cause u cant headshot nor u can see the name if a player crouches, there seem to be different default models aswell?

**Comment by KR4N1X** [comment]
Confirmed.

On my server, hitboxes are off when crouching. A hitbox render script shows that the hitboxes are there, and present on all models. However, when shooting the head hitbox directly, the shot does not register. You have to shoot at collarbone level or below to register a headshot.

This is even more evident when shooting from the side.

**Comment by KR4N1X** [comment]
Figured I'd add, this happens for all player models, gmod, css, and custom. The hitbox render client side lines up with the client side model render. Shooting the head hitbox is always a miss when player is crouched.

If you wish to replicate, join my server at ttt.garryscommunity.net and ask an admin or superadmins to help you replicate the hitbox issue. Only admins and above are permitted to toggle on and off hitbox rendering unfortunately.

**Comment by robotboy655** [comment]
It's not only TTT.

**Comment by KJelles** [comment]
didn't notice that then ^^ ;)

**Comment by robotboy655** [comment]
Will be fixed.

**Comment by KR4N1X** [comment]
Will be fixed? How about you close out the bug report when the bug is fixed, and not before. TY.

**Comment by robotboy655** [comment]
It's already fixed in Dev.

**Comment by KR4N1X** [comment]
How can i grab this? need it horribly.

**Comment by KR4N1X** [comment]
if SERVER then
hook.Add('PlayerSpawn', 'shitboxfix', function(ply) ply:SetHullDuck( Vector( -16, -16, 0 ), Vector( 16, 16, 58 ) ) end)
end

temp fix until they fix the borked server.dll values.

**Comment by KR4N1X** [comment]
This does however create a new issue robot.

Most maps were coded for the old broken duck hull of 45 for ducts and what not. Shitboxes were broken for headshots but manageable. With the update to 55 that you have put in dev, a LOT of maps are no longer usable.

**Comment by KJelles** [comment]
that, is right, why do updates break more then fix things. GMod hitboxes went worse since GMod 10..
