### ISSUE TITLE
player model randomly changes to a UFO

### ISSUE THREAD

**Issue by KR4N1X** [Facepunch/garrysmod-issues#2074]
Was not happening before the update. randomly and rarely, a player will suddenly look like and have the physics of a large UFO like object. Happens client and server.  A map force fixes it. No errors in console.

**Comment by robotboy655** [comment]
This is  not helpful at all.

**Comment by KR4N1X** [comment]
http://images.akamai.steamusercontent.com/ugc/39751186274466093/BE1D9606D2F9BC19DD7F59BBE2B912B57CCAF5C4/

**Comment by robotboy655** [comment]
That definitely looks like a problem on your side.

**Comment by KR4N1X** [comment]
models/props/de_nuke/coolingtank.mdl

found this in LAC

		timer.Simple(4, function()
			if ( not ply or not IsValid(ply)) then return end
			local ent = ents.Create("prop_physics")
			ent:SetModel( "models/props/de_nuke/coolingtank.mdl")
			ent:SetCollisionBounds(Vector(0,0,0), Vector(0,0,0))
			ent:SetSolid(SOLID_NONE)
			ent:SetCollisionGroup(COLLISION_GROUP_IN_VEHICLE)
			ent:Spawn()
			ent:SetRenderMode(RENDERMODE_NONE)
			ent:DrawShadow(false)
			ply.LAC_antiaimbotprop = ent
			ent.isantiaimbotprop = true
			ent.antiaimbotowner = ply
		end)

problem confirmed to be a shitty workaround for LAC.
