### ISSUE TITLE
Bug with "new" serverbrowser

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2075]
Sometimes the "new" serverbrowser just freezes.
The whole game is still in function, but not the browser.
In this time, youre mouse cursor is moveable, but nothing else can be done.
Often appears If I click too fastly on things.

**Comment by robotboy655** [comment]
OS? Console log? Anything of use?

**Comment by deinemudda32** [comment]
OS => Windows.
LOG => Don't have logs about this(Console doesnt say anything). I got this issue now the 5th time. Seems to happen randomly.

As said I just have the way to reproduce the bug.

**Comment by robotboy655** [comment]
Have it ever occurred to you that it just finished getting new servers at some point?

I cannot make anything out of the ordinary happen by "clicking too fast".

**Comment by deinemudda32** [comment]
Yea got it,
If you switch too often from public serverlist and favorites.
Then it just freezes a few seconds.

**Comment by robotboy655** [comment]
Oh that's just the HTML creating new elements, nothing I can do about it, its not permanent either, it unfreezes after a ( short for me ) while.
