### ISSUE TITLE
Crashs on TTT

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2077]
TTT often crashs randomy without a reason.
I investigated in that and it always say Segmentation Fault(Core Dumped).
I run 2 servers on linux. Happens every 2-3 hours. 24 Players per server mostly.
I run 2 other servers aswell.
Sandbox runs smoothly. DarkRP even. Just TTT crashs.

**Comment by P4sca1** [comment]
Same on my Linux server.

**Comment by deinemudda32** [comment]
Not only the Ragdolls are causing the crashes I saw either.
They even happen without anyone dieing or creating a ragdoll.
But ragdolls are a big part of it.

**Comment by robotboy655** [comment]
Update your TTT from the official repo.

**Comment by deinemudda32** [comment]
I said I did that already.

**Comment by dralletje** [comment]
I am still having this issue, why is it closed? :(
