### ISSUE TITLE
Player:Say()'s teamOnly parameter is broken

### ISSUE THREAD

**Issue by VintageSoap** [Facepunch/garrysmod-issues#2079]
The second parameter of <a target="_blank" href="http://wiki.garrysmod.com/page/Player/Say">Player:Say</a>, "teamOnly", is broken. No matter what type of value is passed in as the second argument to Player:Say, the corresponding  "teamChat" argument passed to the <a target="_blank" href="http://wiki.garrysmod.com/page/GM/PlayerSay">GM:PlayerSay</a> hook, as a result of calling Player:Say, will always be false. This only occurs when calling Player:Say, not when players use the chat normally (via "say" and "say_team" concommands).

I have tested this extensively on a fresh install of a Garry's Mod (sandbox) server, without addons or customization, apart from the code used to test this. I used PrintMessage to print out the value of "teamChat" (<i>tostring(teamonly)</i>) passed into GM:PlayerSay (<i>in player.lua of the base gamemode</i>) for verification purposes.

(pardon any parameter/argument terminology confusion)
(GMod version 2015.06.01)

**Comment by robotboy655** [comment]
Already fixed in Dev.
