### ISSUE TITLE
prop_physics PerformanceMode keyvalue can't be set

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2080]
I'm trying to set the performance mode of breakable prop_physics to 1 so they don't lag players so much, but it doesn't work.

```
>THIS:SetKeyValue("PerformanceMode","1")
>ME:ChatPrint(THIS:GetKeyValues().PerformanceMode)
0
```

I tried with ExplodeRadius and it works for that keyvalue.

**Comment by thegrb93** [comment]
prop_active_gib_limit 0 doesn't work either.

**Comment by robotboy655** [comment]
GetKeyValues is broken.

**Comment by thegrb93** [comment]
The props still produce gibs though.

**Comment by deinemudda32** [comment]
If something is broken, then it normally should be fixed :large_blue_circle:

**Comment by thegrb93** [comment]
I found props_break_max_pieces 0 works.

**Comment by daunknownman2010** [comment]
I mainly use AddOutput to change the key values (mainly if they already exist in the map).

**Comment by thegrb93** [comment]
I tried that too.

**Comment by thegrb93** [comment]
props_break_max_pieces 0 Seems to not work when the server starts with it set to 0.

**Comment by thegrb93** [comment]
Oh wait sorry. prop_active_gib_limit 0 has to be set on the client

**Comment by robotboy655** [comment]
I just tested your exact code in single player and it totally works.
Keep in mind that ```breakable_disable_gib_limit``` MUST be set to ```0``` for it to work.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/10429632/ad006a74-7102-11e5-87ff-f31fffc86f45.png)
![image](https://cloud.githubusercontent.com/assets/3299036/10429639/b6ebc2f4-7102-11e5-91c7-e2c0f73281f1.png)
