### ISSUE TITLE
Sandbox Jump Speed

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2081]
Since the Sandbox Jump Speed got added Players on my Server are jumping often backwards and then gain a huge amount of speed which brings them to the end of the map in 1-2 seconds.
I always hated the Sandbox Jump Speed change, but this is exaggerated!

**Comment by robotboy655** [comment]
You can remove it from the code yourself if you don't like it. That's why it's ported to Lua.

**Comment by deinemudda32** [comment]
I already did that, but everytime you update Garry's Mod I have to remove it again and I have bigger problems.

**Comment by thegrb93** [comment]
Here, you can test this out on your server. https://github.com/garrynewman/garrysmod/pull/984/files

**Comment by deinemudda32** [comment]
Well, thanks :)

**Comment by thegrb93** [comment]
Make sure you do sbox_bunnyhop 0
