### ISSUE TITLE
KeyValues Error, what ever it is

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2082]
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file models/noesis/donut.mdl
mdlkeyvalue, (*prop_data*),

**Comment by robotboy655** [comment]
That is a problem with that model.

**Comment by deinemudda32** [comment]
And why cant it be fixed?
Hey and its not invalid!
It was an error!

**Comment by Bo98** [comment]
@robotboy655 That model ships with GMod.

**Comment by deinemudda32** [comment]
I think he knows that :)

**Comment by robotboy655** [comment]
Report the model being wrong, not the error occurring.

**Comment by deinemudda32** [comment]
The model works, but the error appears. So I report the error.

**Comment by robotboy655** [comment]
The error is shown because the model is corrupted or some shit. It's been like that with that model forever.
