### ISSUE TITLE
Read only

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#2084]
Garrysmod seems to set all folders in it's directory to read only since the last update. On servers this ocurs swell but only while SRCDS is running.

**Comment by FirstRoboticsGuy999** [comment]
What game build and OS are you using? Check your the folder settings for the garrysmod directory. There isn't any reason why anything but Windows would change the flags.

**Comment by wiox** [comment]
This started happening to me right after the most recent update too. Could it be related to workshop items being removed when no longer subscribed to?

**Comment by robotboy655** [comment]
Cannot confirm? You won't be able to delete .gmas in use, that is true. I can still delete any folder.

**Comment by FirstRoboticsGuy999** [comment]
I didn't have any problems with folders after the most recent update but I did just switch back to dev build yesterday.

**Comment by robotboy655** [comment]
After Dev branch updates test whether it still happens to you. If it does, let me know.
