### ISSUE TITLE
FastDL is downloading the last uploaded files twice

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/garrysmod-issues#2087]
Hello, 
I've setup my FastDL but he's always downloading the last ca 5 files that I've uploaded. The files are allready on my computer, but they still get downlaoded. 
I think that has something to do with garrys mod and not with my fastdl.
Would be glad if you can tell me more about that problem. 
Regards, 
Pascal

(Excuse my bad english)

**Comment by robotboy655** [comment]
Post the client console log after downloading those fake files.

I am 99.99% sure you fucked up your setup for those files.

**Comment by P4sca1** [comment]
this helped me a lot. 
I saw this error in the console: 
HTTP ERROR 8 downloading http://**.de/fastdl/maps/graphs/ttt_fastfood_a6.ain.bz2
HTTP ERROR 8 downloading http://**.de/fastdl/maps/graphs/ttt_fastfood_a6.ain
HTTP ERROR 8 downloading http://**.de/fastdl/models/player/ghostrider/ghostrider.jpg.bz2
HTTP ERROR 8 downloading http://**.de/fastdl/models/player/ghostrider/ghostrider.jpg
Could you tell me what HTTP ERROR 8 is meaning?

**Comment by robotboy655** [comment]
When you open the link, the file should start downloading. It doesn't. There's your problem. Do you even own DOMAIN.de?

**Comment by robotboy655** [comment]
This is not a place to ask for help. Get help @ http://facepunch.com/forums/65

**Comment by Bo98** [comment]
```
HTTP_ERROR_FILE_NONEXISTENT = 8
```

Sounds like a 404.

**Comment by P4sca1** [comment]
Sorry I just changed the real Domain Name to DOMAIN.de. 
I'll take a look in other forums instead of spamming the comments here. 
Thanks for your help! :)
