### ISSUE TITLE
Glass plates catch fire when shot.

### ISSUE THREAD

**Issue by Col936** [Facepunch/garrysmod-issues#2088]
This is pretty self explanatory. The glass_plate entities catch fire when you do enough damage to them with guns. The fire burns for awhile, doing damage to the glass, and depending on the glass's health, may cause the glass to break. This is in singleplayer sandbox mode, in case it's not clear. The build is 2015.06.01.
![2015-06-09_00001](https://cloud.githubusercontent.com/assets/10701010/8073627/bc5263c0-0ef5-11e5-873e-efca9f9c403c.jpg)

Pictured: Glass burning.

**Comment by thegrb93** [comment]
Lol, it has always done this even since gmod9. Maybe the creator copied a flammable model's script or maybe it was a joke.

**Comment by Col936** [comment]
Funny, I didn't even notice that they existed until today. Shows how little I know after playing mostly sandbox for over a year.

**Comment by thegrb93** [comment]
Imo these panels should be made unbreakable.

**Comment by Kefta** [comment]
@thegrb93 No prop with the glass class should be made unbreakable

**Comment by robotboy655** [comment]
It wasn't in GMod until GMod 12, but still.

Don't expect it to be fixed. It will require to recompile all those models and we do not have the sources.

**Comment by thegrb93** [comment]
Just imagine the burning feeling of being too close to the damaged glass is you stepping on shards of glass.

**Comment by robotboy655** [comment]
Alright, I actually looked into it and it's a simple fix that doesn't require recompiling. All hail XVI32.

https://github.com/Facepunch/garrysmod-issues/issues/2082

This is also taken care of.
