### ISSUE TITLE
Awesomium in GMod doesn't support H.264/MP4 Video Playback in HTML5

### ISSUE THREAD

**Issue by WinterPhoenix96** [Facepunch/garrysmod-issues#2089]
I know this is a rather specific issue, however it's impacting a Video Service deployment I'm trying to do with the Cinema gamemode.

Basically it goes like this. The web server that hosts the target videos doesn't play nice with seeking using Flash-based Video Players, and will only buffer videos from the beginning going forward. However, seeking works in HTML5-based Video Players despite this.

For example, if I load [this video](https://2.bp.blogspot.com/gQ8pJ17dIEjQFQ23j1YgMsPpTBT5ySqvD0oLKt4QlA=m22) in a Flash-based Video Player, seeking will not work unless the video is buffered to that point. If I load the same video in a HTML5-based Video Player, it'll seek just fine to any point in the video, even 20 minutes in.

In Cinema, seeking is most often done by the code to keep the players in sync with the current time in the video. This cannot be done in this scenario and after trying multiple Flash-based Video Players (Video.JS, Flowplayer Flash, JWPlayer, etc) in Chrome, FireFox, and Garry's Mod, I could not once get it to work. If I play the video using an HTML5-based Video Player or by simply using the `<video>` HTML5 tag, I could play the video as well as seek it in Chrome and FireFox, however not in Garry's Mod, *due to the Awesomium Implementation not supporting this.*

Later builds of Awesomium seem to support H.264/MP4 Videos in HTML5, so I imagine it's some sort of issue due to the implementation in GMod not being up to date, however I cannot confirm this.

If you would like to check HTML5 `<video>` tag support in any given browser yourself, you can refer to [this webpage](http://www.quirksmode.org/html5/tests/video.html). I would invite you to open it in an Awesomium window in GMod to check for yourself and confirm.

Thank you for reading, and thank you all for your work thus far.

**Comment by robotboy655** [comment]
I don't know why you report awesomium issues here, it's not like we we caused them or can fix them.

This should be resolved by updating awesomium, which there's already an issue for.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/398

**Comment by WinterPhoenix96** [comment]
Ah alright. I didn't see that issue when I searched for Awesomium. Thanks for the link.

**Comment by Jitterclick** [comment]
What OS are you using?

**Comment by WinterPhoenix96** [comment]
Windows.
