### ISSUE TITLE
No way to add a server to favorites except legacy browser

### ISSUE THREAD

**Issue by UltimateByte** [Facepunch/garrysmod-issues#2090]
Title is self explaining, kids are always complaining to me "how do i put a server to favorites..." because they see the favorite menu.
I'd be grateful if you'd make servers right clickable in new server list, or add an option on the right to save them as favorite.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-requests

**Comment by UltimateByte** [comment]
OK sorry.

**Comment by thegrb93** [comment]
You can close it.
