### ISSUE TITLE
Garry's Mod not updating .lua files in real time (Linux)

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/garrysmod-issues#2092]
On my dedicated Windows Server, everything is updated in real time, eg: If I change anything in a config or something (.lua file not .cfg) it is directly applied. 
On my dedicated Linux Server I need to wait for a mapchange for the changes to be applied. 
I dont really know where I should post this, because I dont really know whether this is an issue, so I hope it is okay, that I posted it here. 
Regards, 
Pascal

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/71
