### ISSUE TITLE
I can't open the game

### ISSUE THREAD

**Issue by akouniakis** [Facepunch/garrysmod-issues#2093]
When I click on launch button it loads and the game starts. After loading the game for a few seconds when there is the message finalizing, the game minimizes and when I try to maximize it will just minimize after 2 seconds... Any ideas?

**Comment by P4sca1** [comment]
I had a similar issue about 5 days ago. (game crashed instead of minimizing) My problem was that there were some complications with my team fortress 2. I just deinstalled the game and it started working again. Maybe this can fix it for you too?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
