### ISSUE TITLE
util.PixelVisible broken !

### ISSUE THREAD

**Issue by Yuri6037** [Facepunch/garrysmod-issues#2094]
So due to the fact, it seams nobody know why I get the problem, well I think it's time to post that.

So basicaly I have a Vehicle Controler, and I'm trying to render lights on vehicles only when the player should see them.

To do that, I'm using util.PixelVisible. But each time I use this method, the lights becomes invisible which means the fucntion returns always 0.

Here is the code to reproduce the issue : 
[code]
local cache0 = {} //Left blinkers
local function DrawVehicleLights(entity, vehTbl, type)
	local dist = LocalPlayer():GetPos():Distance(entity:GetPos())	
	if (dist > 1500) then return end	
	if (type == 0) then
		for k, v in pairs(vehTbl.leftBlinkers) do
			local handle = cache0[k]
			if (handle == nil) then
				handle = util.GetPixelVisibleHandle()
				cache0[k] = handle
			end
			
		        local pos = entity:LocalToWorld(v)
			if (util.PixelVisible(pos, 1500, handle) == 0) then continue end
			render.SetMaterial(lightMat)
			render.DrawSprite(pos, 16, 16, Color(255, 255, 0, 255))
		end
         end
end
[/code]

EDIT : You also need to call that on a vehicle in PostDrawTranslucentRenderables. Be sure to pass a table containing some local positions (table that contains a table called leftBlinkers which contains local poses.

**Comment by robotboy655** [comment]
You are using them improperly. This is not a place to get Lua help. http://facepunch.com/forums/65

**Comment by Yuri6037** [comment]
Well it's still not working even with the solution you gave me : http://facepunch.com/showthread.php?t=1469526&p=47948717#post47948717
