### ISSUE TITLE
My resolution changed from 1366 x 768 to 1280 x 768 (windows)

### ISSUE THREAD

**Issue by jspencer00** [Facepunch/garrysmod-issues#2095]
i dont kno how to fix it i checked the in game options but i cant fix it i think it is from me plugging in my hdmi cord in but idk how to fix it.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

**Comment by Noiwex** [comment]
In command line options:
-sw -noborder -w 1366 -h 768
