### ISSUE TITLE
Cinema On Mac OS X / Please Don't Avoid This Issue! 

### ISSUE THREAD

**Issue by Jitterclick** [Facepunch/garrysmod-issues#2098]
As you may know, on mac OS X in the Cinema game-type. You can't hear or see the videos being shown.  This has been a bug for a while now. It NEEDS TO BE FIXED! This has gone on for too long, don't disregard this please. It is a big bug that YOU NEED TO DEAL WITH. It says on the screen "Adobe Flash not detected" or "Use a HTML 5 Browser to view this". Something, around there. I'm not the only one who want's this fixed. I don't want to just plainly not be able to play a part of a game because of the computer system I have. Please. Fix. This. From what I heard, it could be these causes: 

1. Something with Awesomnuim and Mac Adobe Flash isn't working well together.

2. Unfortunately, Garry's Mod for Mac doesn't support Adobe Flash.

3. "The path is defined in Awesomium's WebConfig class. I (c1yd3i) tired disassembling the gmhtml binary to find a string reference to the plug-in path property but couldn't find any. I (c1yd3i) did see that an instance of the WebConfig class was created so it's likely that the plug-in path property isn't being defined when the class is being created." - Screen Name "c1yd3i"

The man who here typed that up there said this could probably be fixed by you guys within minutes. Hope that is right, or at least he was right. Hope you fix this once and for all!

Here is some public insight to the bug tracking forum since 2013!! / https://github.com/Facepunch/garrysmod-issues/issues/1347

**Comment by robotboy655** [comment]
Don't recreate issues.

**Comment by Jitterclick** [comment]
Is that saying you don't care then Facepunch? Huh? You just want to update your buggy piece of crap Rust? The NSA couldn't even run that at 60 FPS. Really telling me not to recreate? It was back in 2013 for fucks fake. This Github is useless. Hehe, didn't want to fucking do this. Gonna have to.

**Comment by YourStalker** [comment]
lol

**Comment by Jitterclick** [comment]
@YourStalker Who are you laughing at? You obviously knew I'm kidding. No I'm not. Hiring my Hitman rn

**Comment by meepdarknessmeep** [comment]
-rep not funny and tries too hard
plus hank hill is on the most retarded of adult swim shows

**Comment by Jitterclick** [comment]
This isn't even steam you fucking faggot, keep your gay ass words up your ass. I'm not even trying hard for what? I'm being fucking totally honest this Rocketboy kid is a faggot and has a shitty name

**Comment by Velkon** [comment]
-rep too butthurt

**Comment by Jitterclick** [comment]
Have you also seen Adult Swim? It's all shit and kids hop off my tip @Velkon @meepdarknessmeep

**Comment by sasha-chan** [comment]
You should just solve your base issue and stop using a terrible operating system.

**Comment by meepdarknessmeep** [comment]
i agree use windows or (less superior) linux
