### ISSUE TITLE
Please Tell Me Why 

### ISSUE THREAD

**Issue by Jitterclick** [Facepunch/garrysmod-issues#2101]
Why? Why won't you fix it? It is a bug that you guys know you can fix, yet don't. Garry's Mod has a ton of bugs. Do you even play it? Answer my questions. Why hasn't MetaCritic rated your game?

**Comment by robotboy655** [comment]
This is not a place to ask random questions. If it was a 5 minute fix or if it was known how to fix it, it would've been already fixed. For all we know it's a bug with 3rd party software.
