### ISSUE TITLE
Physgun problem

### ISSUE THREAD

**Issue by Domis123** [Facepunch/garrysmod-issues#2103]
As i play Gmod the other day, i noticed that my physgun does not rotate properly (What i mean is that i try rotating with E, i can rotate it in front and back, but not in the sides (It has very familiar effects like the Keep Upright from the C menu) I can rotate anything properly!) This problem has also occured to some of my friends.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
