### ISSUE TITLE
VelocityDecay (Replacment Function)

### ISSUE THREAD

**Issue by Matspyder51** [Facepunch/garrysmod-issues#2107]
Hi, I don't know where to ask, but the VelocityDecay Function has been deleted but lot of addons had just comment the lines, so I have find the SetLighting function, can be a replacment ?

**Comment by thegrb93** [comment]
http://wiki.garrysmod.com/page/CLuaParticle/SetAirResistance

**Comment by robotboy655** [comment]
All Lua questions should be asked here: http://facepunch.com/forums/65

VelocityDecay didn't do anything as far as I know.

**Comment by Matspyder51** [comment]
robotboy65 : VelocityDecay didn't do anything as far as I know.

The Carter Addon Pack had just comment the lines, since, If I use a lot of weapons in same time, we have a big graphic crash, so I think is that
