### ISSUE TITLE
Gmod keeps on crashing when launching

### ISSUE THREAD

**Issue by RanderenReborn** [Facepunch/garrysmod-issues#2108]
Whenever I launch it from steam or from the files it goes to the blue loading screen and crashes seconds later. Please help? I've verified game files, re-installed it, restarted my computer and even reinstalled all files of the game. I'm on Windows 7 Home Prem

**Comment by daunknownman2010** [comment]
Help & Support: http://facepunch.com/forumdisplay.php?f=16
