### ISSUE TITLE
FastDL oversight

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [Facepunch/garrysmod-issues#2109]
With the advent of the workshop, modelers are being extremely lazy with their filenames, and even a few of the most popular weapon packs have spaces in some of their model names. This seems to generate an error when downloading these files. Here is an example of some textures refusing to operate via FastDL, which were sourced from the Workshop.
```
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/frame norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/frame norm.vtf
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/silencer norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/silencer norm.vtf
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/slide norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/twinkie m9/slide norm.vtf
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/bullet norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/bullet norm.vtf
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/chamber norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/chamber norm.vtf
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/frame norm.vtf.bz2
HTTP ERROR 8 downloading http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/frame norm.vtf
```

The only common denominator that my friend's testing has concluded is that the spaces are causing the error.

**Comment by robotboy655** [comment]
No, I don't think so:
![image](https://cloud.githubusercontent.com/assets/3299036/8266760/9c0b20d8-1748-11e5-906a-d7b8de6316a5.png)

**Comment by HDG-MrDeeJay** [comment]
Well that didn't show for me.

Thank you anyway.

**Comment by thegrb93** [comment]
There's no "norm" in your file names according to this directory listing.

http://fastdl.ndlee.com/materials/models/weapons/v_models/satan/

**Comment by HDG-MrDeeJay** [comment]
yeah we removed it in a test to see if the 500 becomes a 404 if the file 
isn't there, instead of remaining a 500 error.

**Comment by robotboy655** [comment]
Whatever it is, it's a problem with your web server, nothing to do with GMod.
