### ISSUE TITLE
nan or inf with certain Vector/Angle functions crashes

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2111]
lua_run Entity(67):SetAngles(Angle(math.huge,0,0))

**Comment by thegrb93** [comment]
or
lua_run Entity(67):SetAngles(Angle(tonumber("nan"),0,0))

**Comment by wiox** [comment]
tonumber( "nan" ) returns nil, you're looking for
```lua
Angle( 0/0, 0, 0 )
```

This should be fixed to make debugging script issues easier.

**Comment by Kefta** [comment]
Also happens when using nan/inf in vector functions

**Comment by thegrb93** [comment]
Lets make a list

* Crash
SetAngles

* No crash
SetPos

**Comment by Kefta** [comment]
SetPos with nan does crash

**Comment by thegrb93** [comment]
Woops maybe I only tried it with inf.

**Comment by Bo98** [comment]
> SetPos

Related: #533

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/8329966/a5cc7dba-1a86-11e5-8fda-8bc6d14fd0d5.png)
