### ISSUE TITLE
debugoverlay.BoxAngles ignores color argument

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2112]
It is always set to white.

Note that this does not happen with debugoverlay.Box.

**Comment by robotboy655** [comment]
Got'em. ( Fixed )

**Comment by Bo98** [comment]
Just noticed just now that ignoreZ is the same but affects both functions this time.

**Comment by robotboy655** [comment]
Those functions do not have ignoreZ parameter.

**Comment by Bo98** [comment]
Huh, wiki must be wrong then.

**Comment by robotboy655** [comment]
Already taken care of
