### ISSUE TITLE
Gmod will not open after i click launch

### ISSUE THREAD

**Issue by UbuntuNinja101** [Facepunch/garrysmod-issues#2114]
When i start up gmod on steam it says preparing to launch for a quick second and then dose not launch plz i have wanted to play gmod for a week but since this keeps happeing.... idk what to do plz help

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

Sounds like a problem with Steam. Restart your PC.
