### ISSUE TITLE
Arguments of SWEP:DoDrawCrosshair( x , y ) are not affected by GetAimVector() with SWEP.AccurateCrosshair enabled

### ISSUE THREAD

**Issue by Jvs34** [Facepunch/garrysmod-issues#2117]
It works if you go in thirdperson and move your aim around, but using the context menu aim does nothing.

**Comment by robotboy655** [comment]
Does the default crosshair change position?

**Comment by Jvs34** [comment]
Yes, I added the blue rectangle to show the crosshair better but I did not return true.
```
SWEP.AccurateCrosshair = true

function SWEP:DoDrawCrosshair( x, y )
	surface.SetDrawColor( 0, 250, 255, 255 )
	surface.DrawOutlinedRect( x - 32, y - 32, 64, 64 )
end
```

![img1](https://lh3.googleusercontent.com/-OHdwV8w6w9E/VYmJ8l_WrEI/AAAAAAAAE74/z6BYdp9qBqI/s0/gm_construct0005.png) with thirdperson and thirdperson_mayamode

![img2](https://lh3.googleusercontent.com/-P8Jl2LITEkA/VYmJ8oojhvI/AAAAAAAAE70/5og8H27o_6E/s0/gm_construct0006.png) with ShouldDrawLocalPlayer and CalcView.

**Comment by robotboy655** [comment]
Fixed SWEP.AccurateCrosshair not taking into account worldclicker aim and sometimes hitting the player entity itself
