### ISSUE TITLE
My Game is freaking the F**k Out

### ISSUE THREAD

**Issue by Lumberjackcandy** [Facepunch/garrysmod-issues#2118]
When i load into a server or single player my game will go all weird here are screen shots

 http://steamcommunity.com/sharedfiles/filedetails/?id=467115512

http://steamcommunity.com/sharedfiles/filedetails/?id=467115618

http://steamcommunity.com/sharedfiles/filedetails/?id=467115573

Plz Help

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
