### ISSUE TITLE
CAN NOT DIE (PLEASE HELP)

### ISSUE THREAD

**Issue by meganerd101** [Facepunch/garrysmod-issues#2119]
For some reason, when playing singleplayer, I can not take damage.  I just stay at 100 health and can't die except for using 'kill' in the console.  This is an issue and no fun for me.  PLEASE HELP ME!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

What makes you think this is a place to get help?
