### ISSUE TITLE
CPU overflow

### ISSUE THREAD

**Issue by Sinon420noscoper** [Facepunch/garrysmod-issues#2127]
ГАВНООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООООО БЛЯЯЯЯЯЯЯЯЯЯЯЯЯДЬ СУКА ВЕРНИТЕ ДЕНЬГИ СУКА МОИ ДЕНЬГИ БЛЯЯЯДЬ СУКА ЭТО ДЕНЬГИ АБДУЛОВЕРОВАНИЯ БЛЯДЬ КАК ЭТО БЛЯДЬ СДЕЛАТЬ СУКА НИХУЯ НЕ ПОЛУЧАЕТСЯ ЕРРОРИТ ВСЕ БЛЯДЬ НАДАЛАРЫ МЕНЯ ВСЕ СУКА НАДАЛАРЫ ВСЕ СУКА НАЕБЫВАЮТ СИДЯТ ЖИРУЕТ ТАМ РОБОТБОЙ ХУОЙОУ БЛЯДЬ СУКА МУДАКИ ОБОССРАНЫЕ бляяять.... СУКА НУ КАК ТАКОЕ ГАВНО МОЖНО БЫЛО НАКОДИТЬ Я СССУКА ВООБЩЕ НЕ ПРЕДСТАВЛЯЮ СУКА ДИБИЛ ТЫ ЕБАНЫЙ РОБОТБОЙ ТЫ СУКА БЛЯДЬ НИКОМУ НЕ НУЖЕНН НННАХУЙ!!!!!! ГОВНО ССУКА В АБДУЛОАДУ БУДЕШЬ ГОРЕТЬ ЧМО СОБАЧИЕ БЛЕЯТЬ НАДАЛАРЫ ВСЕ СУКА БЛЯТЬ НАДАЛАРЫБЛЯДЬОУЫГРВФЫВФЫОВ МИЛЛИОНЫЫ ПОГИБЛИ МИНГОВ ССУКА ГОВНОООООООООООООООООООООООООООБЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯТЬ ТЫ БЛЯДЬ БЛЯДЬ НЕТУ СЛОВ ТЫ ХУЖЕ БОМЖА ДАЖЕ!!!! УБЕЙСЯ ОБ СТЕНУ Я НЕ ЗНАЮ НО НЕ ДЕЛАЙ ТАКОЕ ГОВНО БЛЯДЬ МУДААААААААААААААААААААК В КВАДРАТЕ БЛЯТЬ!!!!! СУКААААААААААААААААААААААААААА ВСЕ ТОРМОЗИТ НАХУЙ СТАК ОВЕРФЛОВ СУКА ГОВНОООО БЛЯТЬ ПЯТЬ ФПС СУКА У МЕНЯ В ХАЛФЕ СТО ФПС А ЗДЕСЬ ИЗЗА ТВОЕГО ГОВНОКОДА ПЯТЬ БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯТЬ ДАУУУУН!!!!! УМРИ НАХУЙ УОЙОБОК СУКА КОНЕЧНЫЙ ОБОССАНЫЙ ОБОСРАНЫЙ!!!!!

**Comment by Sinon420noscoper** [comment]
WHAT A FUCK YOU ARE DOING?

**Comment by Sinon420noscoper** [comment]
You fucking piece of shit, go away from garry's mod development

**Comment by Sinon420noscoper** [comment]
WHAT DO YOU DO FOR GARRYSMOD? NOTHING!
FUCK YOU
![](http://puu.sh/iCE8G.png)

**Comment by P4sca1** [comment]
Is there any way to ban this user? He is just flaming, it really sucks.
