### ISSUE TITLE
Ragdolls are repositioned to the "T" shape and have blank Facial Expressions in Re-loaded Saved Maps

### ISSUE THREAD

**Issue by Balthazar13** [Facepunch/garrysmod-issues#2128]
When I load a saved map in game the ragdolls I placed in it will be in the "T" position and any work on eye and facial positioning is reset. Some folks on the steam discussion page have also reported that they had reinstalled the game and removed all addons to see if it would fix the problem but it still persist. The only solution I currently know of doesn't necessarily fixes the bug but rather fixes the ragdoll in the current session. If you use the Physics Gun on the ragdoll while it is in the "T" position it will put them back into the original positioning you had them in or that they were intended to be in (as loading other maps, created and uploaded to the Steam Workshop by other users, will result in the same issue) but like I said it will only last in the current session. Once you save the game again it will return to the "T" position when you reload the map meaning that this current solution is not ideal especially for saved games with more ragdolls scattered about the map. Welding the ragdolls will also result in the same problem as I had tried on multiple occasions to see if welding them would work. The only solution in fixing the eye and facial positioning is to redo the work which is also not ideal as it also resets upon reloading the saved world not even returning to normal when you use the Physics Gun on it. This bug is small but irritating nonetheless. I don't know how long this problem has been around but if I remember correctly I had the problem since I reinstalled the game back at the start of this year. I don't know if this bug has already been reported on this site and I had searched to see if it had and all I found was many pages of unrelated issues. Forgive me if it has already been posted. Fixing this bug would be greatly appreciated as I had became interested in creating scenes in game and creating saved worlds for myself.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/445
