### ISSUE TITLE
HTML Panel Transparency Issues

### ISSUE THREAD

**Issue by SpencerSharkey** [Facepunch/garrysmod-issues#2129]
There's a rendering problem with the HTML panel. I don't know if it's something wrong with Awesomium, but the anti-aliasing transparency around text looks pretty bad. This exists within the main menu.

The images speak for themselves, check the nasty border around the font on the image with the solid background:

![kpp08](https://cloud.githubusercontent.com/assets/4871369/8390385/e9602a16-1c5e-11e5-982a-956220e996d4.png)

![wutkd](https://cloud.githubusercontent.com/assets/4871369/8390386/eb671a9a-1c5e-11e5-9aa1-da03f5dd0538.png)

The effect is extremely noticeable when using transparent backgrounds:

```
html { 
        background: transparent; 
}
body {
	background: transparent;
	color: white;
}
```

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/865

Possibly related: https://github.com/Facepunch/garrysmod-issues/issues/2106
