### ISSUE TITLE
gamemode.Register doesn't allow you to register a new gamemode

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2130]
When calling the function gamemode.Register, you cannot select the 'registered' gamemode using the "gamemode" console command.
The code in /lua/includes/modules/gamemode.lua shows that registering a new gamemode only stores it in lua and doesn't tell the engine there has been an update.

Before you make the argument that you are not supposed to create your gamemodes like this:
The function is not marked as internal on the [wiki](http://wiki.garrysmod.com/page/gamemode/Register), nor does any of the documentation indicate that this isn't allowed

The only reason I could think of to not allow this usage is because garry/devs of gmod assumed noone would ever use this and build new functionality around this assumption like auto-reload and tracking the workshop addon for a gamemode.

Also, the engine calls gamemode.Register when loading gamemodes (after addons) and uses a 4th unused argument; a boolean valued false.

```lua
local mygm = {};
gamemode.Register(mygm, "mygm", "base");
--type into console: "gamemode mygm"
--output: "Couldn't change active gamemode - 'mygm' not found"
```
I also tested this code by registering the GM table of a gamemode under a different name.

**Comment by robotboy655** [comment]
You are not supposed to do this. Can you even come with a reason to do this? You will not be able to switch to a new gamemode without a map reload, which resets the entire Lua state.

**Comment by mooshbeef** [comment]
I was experimenting with stuff including generating gamemodes from lua. Eitherway, thanks for updating the documentation :)
