### ISSUE TITLE
Garry's Mod crashing after installing some addons

### ISSUE THREAD

**Issue by Lor1221** [Facepunch/garrysmod-issues#2131]
I have had Garry's mod since 2013. I recently installed some addons. When I loaded up a game in single player, it instantly crashed and exited Garry's Mod. I have several crash reports, but I have no idea how to open them or put them on this thread. Can you tell me how?

**Comment by robotboy655** [comment]
It's a common crash, it happens if you install too many addons, don't bother with crash reports.

**Comment by Lor1221** [comment]
Thank you. Sorry for not replying, my power went out for 8 hours
