### ISSUE TITLE
return "" on hook PlayerSay does not work

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/garrysmod-issues#2133]
function Test( ply, text )
	if text == "!test" then 
		return ""
	end
end 
hook.Add( "PlayerSay", Test) 

If you type in !test in chat, it will still print !test in chat. 
The Gamemode is trouble in terrorist town and I'm using the latest version from github.

**Comment by Kefta** [comment]
Can you try modifying the current PlayerSay function in the gamemode? I think it has something to do with my implementation

**Comment by P4sca1** [comment]
Not quite sure what you mean.
How should I modify this function?

**Comment by Kefta** [comment]
Modify the PlayerSay function in the terrortown gamemode

**Comment by thegrb93** [comment]
>hook.Add( "PlayerSay", Test) 

This is wrong dood

**Comment by P4sca1** [comment]
Sorry guys, it was late yesterday ... 
Tested it with the correct code and it is working.
