### ISSUE TITLE
Increased or Enlarged Eyes Problem

### ISSUE THREAD

**Issue by GradualGamer** [Facepunch/garrysmod-issues#2134]
Whenever i am in game my ragdoll or npc eyes are enlarged and block

![gm_flatgrass0027](https://cloud.githubusercontent.com/assets/13108898/8418907/e30c873c-1e6a-11e5-8b99-82f2d5c592ee.jpg)

**Comment by Jvs34** [comment]
Check out robotboy's guide on the workshop.
http://steamcommunity.com/sharedfiles/filedetails/?id=374522921
