### ISSUE TITLE
My game freezes at startup loading Facepunch screen.

### ISSUE THREAD

**Issue by JD400RR** [Facepunch/garrysmod-issues#2135]
Whenever I start up my game, it goes through the loading bar like always, and as soon as it says "Finished!", my game freezes and I can't exit the game, even if I click my desktop button, so I have to reset my computer. Can anyone help me? I really want to play Garry's Mod

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
