### ISSUE TITLE
Gmod13 Crash On Singleplayer Loading No Matter What Is Changed

### ISSUE THREAD

**Issue by orangefox712** [Facepunch/garrysmod-issues#2137]
3 Months ago my gmod started having problems with crashing no matter what is done to fix the game. It only crashes however when singleplayer is loaded in any kind of way. Multiplayer works fine. I've unmounted all games and addons and it sitll wont work. And don't say to verify game cache... it doesn't work. If anyone knows what's wrong then i'll gladly take that info. If you want a closer look then send me your email and i'll send you the game files so you can fix it. I should mention it's a steam copy.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

**Comment by orangefox712** [comment]
then don't have steam put it as a support site

**Comment by Bo98** [comment]
Where in Steam does it do that?
