### ISSUE TITLE
New chat-issues in TTT

### ISSUE THREAD

**Issue by Heady92** [Facepunch/garrysmod-issues#2140]
Cheers.

Now, that the chat works again how it should do we got another new problem:

As it should be, traitors and detectives have their team-chat.
Further everyone has an all-chat.
The real issue is the team-chat, innocent player now have.

Once an innocent writes in innocent team-chat (which EVERYONE [not just innocents] can read) he is proven innocent, because traitors and detectives have their own team-chat only readable by their comrades.

The "{TEAM}"-tag should be removed when an innocent writes in team-chat or it should be redirected to all-chat. I think that would be the easiest way to fix this issue.

**Comment by robotboy655** [comment]
This is not a place to report TTT bugs.
