### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Woyken** [Facepunch/garrysmod-issues#2141]
After last update 15.07.02, I loaded game once with all my addons as always it worked just fine, but when I closed game next time it would not start, it crashes on loading screen: hl2.exe has stopped working. I did verify cache it did download 2 files but no help... I reinstalled my game to try with a fresh copy without any addons, still nothing. I even updated my graphics card drivers, still... It does not generate a crash log file in steamapps/common/garrysmod. Is there any other log file I could check? Or anything I could try out?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

Validate your TF2.
