### ISSUE TITLE
TF2 Ragdoll Glitch

### ISSUE THREAD

**Issue by Smitty-Werbenjagermanjensen** [Facepunch/garrysmod-issues#2142]
Ragdolls will disappear after spawn and the following will appear in the console:
Unknown command: headtrack_reset_home_pos
Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)
Attemped to precache unknown particle system "taunt_spy_cash"!
Attemped to precache unknown particle system "taunt_spy_headbutt_cig_burn"!
Attemped to precache unknown particle system "taunt_spy_headbutt_cig_smoke"!
Attemped to precache unknown particle system "taunt_spy_flip_dirt"!

**Comment by robotboy655** [comment]
This is not a place to ask for help. Get help @ http://facepunch.com/forums/16
