### ISSUE TITLE
5.1 surround speakers not working properly

### ISSUE THREAD

**Issue by ElHyperion** [Facepunch/garrysmod-issues#2143]
Since the newest update, I can't hear anything from the rear speakers on a 5.1 setup. Front stereo channel and center speaker work just fine, but if I turn around so that a certain sound source is right behind me, I can't hear it at all.

4ch and 7.1 options in audio menu seems to work just fine for me, but that is only a temporary workaround since I don't have side speakers

**Comment by robotboy655** [comment]
Nothing about sound was changed in the latest update.

**Comment by ElHyperion** [comment]
Turns out it was only a temporary problem, not sure what fixed it but not restarting.
You can remove/close/whatever this issue
