### ISSUE TITLE
Server Hosting With "Start a New Game" (Server Not Responding)

### ISSUE THREAD

**Issue by TheTrueBlue** [Facepunch/garrysmod-issues#2144]
Hello there! I'm sorry if anybody else had to endure this bug that I stumbled upon, but I bought Garry's Mod hoping I could play with my friend and have fun! But that didn't actually happen. I made a server with Start a New Game but once she tried to join it said "server not responding" and my server wasn't listed in the internet section. Please look to this or somebody answer to this so me and my friend can play Gmod. 

Thanks for reading this,
TheTrueBlue

**Comment by robotboy655** [comment]
http://support.facepunchstudios.com/kb/articles/24-my-friend-can-t-join-my-server
