### ISSUE TITLE
Game keeps crashing please help

### ISSUE THREAD

**Issue by skinny29216** [Facepunch/garrysmod-issues#2146]
My friends game keeps crashing when he launches Garrys mod. He said when it crashes the game freezes and then steam crashes after it please help because we want to play it. The problem started about 3 days ago if anyone has a solution please tell me.

**Comment by Noiwex** [comment]
Not you personal support.

**Comment by TheFreeman193** [comment]
This is a bug tracker; for general help goto http://facepunch.com/forums/16.
