### ISSUE TITLE
Dedicated server working for everyone but me

### ISSUE THREAD

**Issue by TheNinjer** [Facepunch/garrysmod-issues#2147]
I created a dedicated server and everyone but myself can connect to it. Yes, I have:
Forwarded the correct ports (Did 27000-27050 TCP & UDP just to be safe)
My start.bat is

@echo off
cd c:\srcds/orangebox
echo Starting game server.
echo Beginning "Garry's Mod"
srcds.exe -console +map gm_freespace_13 -game garrysmod +maxplayers 45 +ip [internal ip] -port 27015 -gamemode sandbox
echo "Garry's Mod" has now started.
echo It is recommended that you start Server Crash Recovery aswell.

(My internal ip is already in the box)

My firewall is off
scrds.exe has permission to bypass my firewall
The error I'm getting is "Connection failed after 4 retries"

Version is: 2015.06.28

**Comment by TheFreeman193** [comment]
This is a bug tracker; for general help goto http://facepunch.com/forums/16.
