### ISSUE TITLE
Error in my server

### ISSUE THREAD

**Issue by espion601** [Facepunch/garrysmod-issues#2148]
When I run my server 's made me a really boring error that I can not get settled I let you see
13(3.985890): Engine hunk overflow!
12(1.856604): Error! Variable "%keywords" is multiply defined in material "plaster/plaster_ext_02"!
11(1.811238): PREP OK
10(1.794875): Network: IP 192.168.1.73, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
9(1.414499): Changing gamemode to DarkRP (darkrp)
8(0.641318): Adding Filesystem Addon 'c:\users\mickael\desktop\serveur gmod\steamapps\common\garrysmodds\garrysmod\addons\rp_rockfordv1b'
7(0.640091): Adding Filesystem Addon 'c:\users\mickael\desktop\serveur gmod\steamapps\common\garrysmodds\garrysmod\addons\extra'
6(0.638626): Adding Filesystem Addon 'c:\users\mickael\desktop\serveur gmod\steamapps\common\garrysmodds\garrysmod\addons\cstrike'
5(0.637505): Adding Filesystem Addon 'c:\users\mickael\desktop\serveur gmod\steamapps\common\garrysmodds\garrysmod\addons\css_content_addon-jan2015'
4(0.633793): No -authkey
3(0.631163): Fetching Workshop Addons..2(0.342883): Logging into anonymous gameserver account.
1(0.104189): Initializing Steam libraries for secure Internet server

**Comment by robotboy655** [comment]
You are hitting the limit(s) set by these console variables:
```mem_min_heapsize - Minimum amount of memory to dedicate to engine hunk and datacache (in mb) ( Default 48 )
mem_max_heapsize - Maximum amount of memory to dedicate to engine hunk and datacache (in mb)" ( Default 256 )
mem_max_heapsize_dedicated - Maximum amount of memory to dedicate to engine hunk and datacache, for dedicated server (in mb) ( Default 64 )```

**Comment by Bo98** [comment]
`+r_hunkalloclightmaps 0` helps too IIRC
