### ISSUE TITLE
TTT CVars are "archive notify replicated" on fresh install

### ISSUE THREAD

**Issue by AutoFrenzy** [Facepunch/garrysmod-issues#2149]
In order to make games more interesting, I change ttt_traitor_pct randomly from .25 to .32 before each round so the number of traitors isn't always the same. Some update recently changed ttt_traitor_pct so that it ahs the notify flag set. This tells players when it is changed, and obviously ruins the effect I am trying to achieve. I have tested in game that other players can see when it changes

I looked in terrortown/gamemode/init.lua to fix the issue, but it is not set as a notify cvar in that file. I did a fresh install with app_update 4020 in the steamcmd

Code:
....
CreateConVar("ttt_roundtime_minutes", "10", FCVAR_NOTIFY)
CreateConVar("ttt_preptime_seconds", "30", FCVAR_NOTIFY)
CreateConVar("ttt_posttime_seconds", "30", FCVAR_NOTIFY)
CreateConVar("ttt_firstpreptime", "60")

local ttt_haste = CreateConVar("ttt_haste", "1", FCVAR_NOTIFY)
CreateConVar("ttt_haste_starting_minutes", "5", FCVAR_NOTIFY)
CreateConVar("ttt_haste_minutes_per_death", "0.5", FCVAR_NOTIFY)

CreateConVar("ttt_spawn_wave_interval", "0")

CreateConVar("ttt_traitor_pct", "0.25")
CreateConVar("ttt_traitor_max", "32")

CreateConVar("ttt_detective_pct", "0.13", FCVAR_NOTIFY)
CreateConVar("ttt_detective_max", "32")
CreateConVar("ttt_detective_min_players", "8")
CreateConVar("ttt_detective_karma_min", "600")

-- Traitor credits
CreateConVar("ttt_credits_starting", "2")
CreateConVar("ttt_credits_award_pct", "0.35")
CreateConVar("ttt_credits_award_size", "1")
CreateConVar("ttt_credits_award_repeat", "1")
CreateConVar("ttt_credits_detectivekill", "1")

CreateConVar("ttt_credits_alonebonus", "1")

-- Detective credits
CreateConVar("ttt_det_credits_starting", "1")
CreateConVar("ttt_det_credits_traitorkill", "0")
CreateConVar("ttt_det_credits_traitordead", "1")

CreateConVar("ttt_announce_deaths", "1", FCVAR_ARCHIVE + FCVAR_NOTIFY)

CreateConVar("ttt_use_weapon_spawn_scripts", "1")

CreateConVar("ttt_always_use_mapcycle", "0")

CreateConVar("ttt_round_limit", "6", FCVAR_ARCHIVE + FCVAR_NOTIFY + FCVAR_REPLICATED)
CreateConVar("ttt_time_limit_minutes", "75", FCVAR_NOTIFY + FCVAR_REPLICATED)

CreateConVar("ttt_idle_limit", "180", FCVAR_NOTIFY)

CreateConVar("ttt_voice_drain", "0", FCVAR_NOTIFY)
CreateConVar("ttt_voice_drain_normal", "0.2", FCVAR_NOTIFY)
CreateConVar("ttt_voice_drain_admin", "0.05", FCVAR_NOTIFY)
CreateConVar("ttt_voice_drain_recharge", "0.05", FCVAR_NOTIFY)

CreateConVar("ttt_namechange_kick", "1", FCVAR_NOTIFY)
CreateConVar("ttt_namechange_bantime", "10")

local ttt_detective = CreateConVar("ttt_sherlock_mode", "1", FCVAR_ARCHIVE + FCVAR_NOTIFY)
local ttt_minply = CreateConVar("ttt_minimum_players", "2", FCVAR_ARCHIVE + FCVAR_NOTIFY)

-- debuggery
local ttt_dbgwin = CreateConVar("ttt_debug_preventwin", "0")
....

Despite the fact that only some of them are set with notify, when looking in the console, they display this

Code:
] ttt_traitor_pct 
"ttt_traitor_pct" = "0.250000"
 archive notify replicated
] ttt_allow_discomb_jump 
"ttt_allow_discomb_jump" = "0"
 archive notify replicated

I am running no mods on the server

**Comment by AutoFrenzy** [comment]
Looks like any settings included in gamemodes/terrortown/terrortown.txt are set to that state

**Comment by robotboy655** [comment]
This is caused by this commit:

https://github.com/garrynewman/garrysmod/commit/f1ffa6a05f81606a79fb5a33914d8fbd1e3685fd

You should be able to fix this for your TTT copy by removing the convar from ```gamemodes/terrortown/terrortown.txt```.

This is not a TTT bug tracker.
