### ISSUE TITLE
Gravity gun and Pocket not working on Gmod DarkRP

### ISSUE THREAD

**Issue by DeathbyGinger** [Facepunch/garrysmod-issues#2151]
Whenever I try to pick up a printer/shipment/gun with my grav gun or pocket, the entity either does not move, or it says "you cannot put this in your pocket!" I am playing on my own server and none of these things are restricted, for my brother can operate the gravity gun and the pocket perfectly on his computer. Please help!

**Comment by Kefta** [comment]
This is for Garry's Mod, not DarkRP. Post this on the DarkRP forums instead.
