### ISSUE TITLE
cl_downloadfilter "mapsonly" prevents downloading all workshop content (including maps)

### ISSUE THREAD

**Issue by bmwalters** [Facepunch/garrysmod-issues#2153]
I've just done some testing (joining some random servers with cl_downloadfilter "mapsonly") and it appears that cl_downloadfilter "mapsonly" is preventing all workshop content, and only allowing fastdl/serverdl maps.

A nice fix would be only allowing addons containing the "map" tag when the filter is applied, but apparently we don't have metadata until the addon is downloaded.

**Comment by robotboy655** [comment]
Doesn't cl_downloadfilter not affect workshop downloads at all? Or do you mean cl_downloadfilter "mapsonly" DOESN'T prevent workshop maps from downloading? ( which would be pretty much impossible to fix )

**Comment by Velkon** [comment]
It prevents all workshop files from downloading and tries to download the map directly from the server.

**Comment by zerfgog** [comment]
Thanks for going through the issues.
Unfortunately, I don't remember opening this issue. :8ball:
I've just done some testing (joining some random servers with cl_downloadfilter "mapsonly") and it appears that cl_downloadfilter "mapsonly" is preventing all workshop content, and only allowing fastdl/serverdl maps.

**Comment by robotboy655** [comment]
Well this isn't exactly easily fixable without making an addon format for maps different and forcing every workshop creator to use it instead or otherwise marking addons as "have maps" in the downloadables list.

**Comment by zerfgog** [comment]
Well, if we have access to addon metadata at the time, you could check for "map" being listed as a Type, of course this wouldn't work for every addon, but it's better than none.

**Comment by robotboy655** [comment]
We don't because it is being retrieved when "Retrieving addon info #X" is seen in the loading bar.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
