### ISSUE TITLE
"surface.CreateFont()" always renders cyrillic symbols with "Tahoma"

### ISSUE THREAD

**Issue by Phyksar** [Facepunch/garrysmod-issues#2154]
The function "surface.CreateFont()" always renders cyrillic symbols with "Tahoma", although the font has cyrillic symbols.

I have already posted this bug in Garry's Mod Developers Discussion (and not only me) and still it is unsolved. Will it be fixed someday?

![gmod fonts](https://cloud.githubusercontent.com/assets/13320416/8766540/5d348086-2e4d-11e5-9414-7a9fc9852215.png)
Palatino Linotype, standart Windows font

As I assume, "Tahoma" are rendered because some fonts don't have cyrillic symbols (like "coolvetica") but it needs to be rendered somehow. I don't know what is going on when this function calls ("surface.CreateFont()"), but is it possible to make one more unnecessary option in FontData that will force some specified symbols to draw with only this font (an option like
{ forcesymbols = "абвгдежзийклмнопрстуфхцчшщъыьэюя" })?

**Comment by robotboy655** [comment]
Already reported.

**Comment by robotboy655** [comment]
#842

**Comment by VigiFyre** [comment]
Maybe it's finally time to fix the problem, eh?

**Comment by Bo98** [comment]
It probably will be fixed if Freetype is ever implemented again. Pretty sure it worked in the week it was in GMod.

**Comment by Noiwex** [comment]
We need this more than new tf2 maps.
