### ISSUE TITLE
Warning: Table downloadables is full, can't add "file"

### ISSUE THREAD

**Issue by dany777** [Facepunch/garrysmod-issues#2156]
resource.AddFile limit is 4096 and i have more than that, i know you are thinking why is not better using the workshop download?

Because it keeps re-downloading the workshop addons when i join, re-join or map changes and that wastes more time trying to spawn in the server

Isnt there a command or something to increase the file limit? This really annoys me, i want to get the perfect FastDL for my server

**Comment by robotboy655** [comment]
You've hit the limit, cut down on your downloads or use workshop.

**Comment by Noiwex** [comment]
Workshop is huge pain to update, also copyright shits aren't sleeping.

**Comment by Noiwex** [comment]
Datatable limits are so 2004. Unfortunately we can't do much and neither
developers have any will to do anything.

**Comment by Noiwex** [comment]
How many years passed since Garry assigned to himself that dynamic model
precache? We still struggle with 2048 models limit.

**Comment by Noiwex** [comment]
You can't say "cut down on %s", it's wrong attitude to developers.

**Comment by daunknownman2010** [comment]
You should blame Valve for not raising any of these limits themselves.

**Comment by Noiwex** [comment]
Facepunch can do it themselves.

**Comment by FastDL-Issue** [comment]
Yes, use the Workshop, what a brilliant idea! 
![Example](https://i.imgur.com/5KXdQIm.png)
Thanks!

**Comment by Kefta** [comment]
Don't send so many files to the client.

**Comment by FastDL-Issue** [comment]
My point is it's funny how Facepunch both simultaneously suggests the Workshop and also bans the Workshop addons. 

As a server owner there is nothing that can be done once the stupid addfile limit is reached because of how heavily enforced the copyright is even for unlisted addons marked as "Server Content"

**Comment by FlorianLeChat** [comment]
If you knowingly violate the rules imposed by Valve and Facepunch regarding Workshop addons, why are you complaining about this solution? What did you honestly expect when you published copyrigth content?..
