### ISSUE TITLE
Crashing and not reopening

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#2157]
Hello,

For some reason, on our 2014 Macbook Pro, garrysmod will crash (Which has been addressed before) but for some reason, when we try to re open the program, it gets tuck on "Launching Garry's Mod"

I am unsure on why this is happening. I know that Garry's Mod has had a memoryleak for a long time but I am not sure if this is steam not realizing that garrys mod has fully closed down. 

Probably a Steam Error but just wanted to post as it may be a LUA thing too.

**Comment by Kefta** [comment]
It's not Lua, since that's not what the binaries are made in.

**Comment by TheFreeman193** [comment]
I'm guessing this is something to do with steam sync not being ready or perhaps just it waiting for a response. In either case, restarting steam normally resolves this.

**Comment by MrUnknownGamer** [comment]
Sorry, I had to do this for my little brother or else he'd throw a fit. Sorry about this roboboy.
