### ISSUE TITLE
please fix it

### ISSUE THREAD

**Issue by benjaminfuller832** [Facepunch/garrysmod-issues#2159]
before i downloaded garrys mod on steam i downloaded a bunch of stuff from the work shop and when i downloaded garrys mod and went to ubscriptions nothing was there and it wont show up in game andand when i try to click the download button it responds like normal but still has the original download logo saying download and doesnt workplease fix it please.

**Comment by mcd1992** [comment]
Read this.
https://github.com/Facepunch/garrysmod-issues/blob/master/README.md

"This is not the place for help and support. You can ask for help here instead: http://facepunch.com/forums/16"
