### ISSUE TITLE
HandleChange_Lua broken on OS X (always returns false)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2162]
Might not seem like a big issue at the moment as it is really an internal thing (though binary modules could use it), but it will be an issue that needs fixing for AutoRefresh to work on OS X if garrynewman/bootil#16 was merged.

Worth noting that it does work on Linux DS. I don't know about the client but I don't see any reason why it shouldn't. I kept this separate from the main AutoRefresh request since this seems to affect OS X only.

**Comment by robotboy655** [comment]
It only returns false if the last argument isn't "lua".

**Comment by Bo98** [comment]
Odd because I'm explicitly giving it "lua" as a 3rd argument.

**Comment by robotboy655** [comment]
It must be a Bootil string. ( A std::string )

**Comment by Bo98** [comment]
Yeah the exact same code works on Linux DS but not OS X.
