### ISSUE TITLE
Failed to create D3D device

### ISSUE THREAD

**Issue by sammyt291** [Facepunch/garrysmod-issues#2163]
Hello,
This issue started happening just after the last nVidia driver update and Garrysmod update, (which of those two has created the issue im unsure)

Im currently running my GTX 555 with driver version 353.30.

I have just over 3500 hours on my steam profile for garrysmod and this is the first time I have encountered this issue.

Any help regarding the issue would be much appreciated,
and yes I have been to the steam link in the error window to no avail.

The reason for posting it here is just to clear up that this is not a issue with Garrysmod itself being incompatible with the new nVidia driver etc.
Also: I have tried starting gmod on both my integrated chip and my gpu after a steam file validation both with the error, which leads me to believe it is an issue with Garrysmod.

![Image of Error](http://i.imgur.com/9OWQp8m.png)

**Comment by robotboy655** [comment]
It is a problem with your video card drivers, not Garry's Mod. Rollback your drivers and report this bug to NVidia or something.
