### ISSUE TITLE
Nav_analyze still runs at generation even with nav_quicksave set to 1

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#2165]
Nav_analyaze is what is run after the initial Nav mesh is generated and sampled, however since this process is mostly for generating CS:S Bot related information, some people like to turn it off. Before you here able to disable it by setting nav_quicksave to 1, but now nav_quicksave is defaulted to 1 and nav_analyze is still running. I can tell it's running because for the last nine hours, the generation has been stuck at "finding hiding spots 2%" This is troublesome because larger maps sometimes can take a very long time to go through the analyze process while most nextbot NPCs don't utilize most of the information generated. (I actually use hiding spots though, but I find it more time effected to manually make those depending on the map).

**Comment by robotboy655** [comment]
If you go to CSS or any other game that supports nav meshes and generate a navmesh there with nav_quicksave set to 1, does it still take that much time?

The time it takes to generate with quicksave is much less than it is without quicksave, I have tested this myself when generating a proper navmesh for gm_construct and gm_flatgrass.

Nothing about navmesh generation is changed in GMod and the time it takes to generate is only dependant on the complexity of the map.

The fact that it appears to be stuck at that point doesn't mean it actually is.
