### ISSUE TITLE
Server crash bug

### ISSUE THREAD

**Issue by theplayer232** [Facepunch/garrysmod-issues#2168]
Simple & effective:
1. take rope tool
2. open console
3. do this: rope_addlength 1e24
4. spawn kleiner ragdoll
5. put the rope between legs
6. wait a moment for crash

forgot to mention: rope needs to be rigid.

**Comment by thegrb93** [comment]
Doesn't work for me.

**Comment by thegrb93** [comment]
I think you forgot to say the rope needs to be rigid. The ragdoll goes berserk if the rope is rigid.

**Comment by theplayer232** [comment]
Yes, sorry for that, must be rigid.

**Comment by daunknownman2010** [comment]
Nothing seems to crash for me either.

**Comment by thegrb93** [comment]
https://github.com/garrynewman/garrysmod/pull/1030 maybe this will stop it.

**Comment by theplayer232** [comment]
@thegrb93 yep, that fixed it what you did.
