### ISSUE TITLE
Detective can find all traitors with a console command

### ISSUE THREAD

**Issue by meepdarknessmeep** [Facepunch/garrysmod-issues#2169]
via @wyozi
https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/gamemodes/terrortown/gamemode/weaponry.lua#L445-L472

you can send credits to anyone, and even if you have no credits you can send it to them and check if they can receive it (even off your team!)

**Comment by robotboy655** [comment]
This is not a place to post TTT bugs - either PR a fix or don't post it here.
