### ISSUE TITLE
Single Player does not load!

### ISSUE THREAD

**Issue by beasticle1199** [Facepunch/garrysmod-issues#2170]
I don't know if this has been solved, but based on my internet research, it hasn't.  I have many addons/maps/mods installed, and I have been playing for as long as I have been on Steam.  But never have I encountered this problem until I wanted to take a break from the MP grind.  When I boot up a single player map, or at least select one, the game takes me through the standard loading screen, finally gets to "Initializing game resources" or something like that, and then crashes, without even the slightest error message or "something is creating script errors."  Please help, and if this has been solved, don't be a jerk and rant hate comments on the forum.  Thanks!

**Comment by beasticle1199** [comment]
I don't know how exactly to view or share my crash logs, but I have located them if that would help.

**Comment by robotboy655** [comment]
Too many mods - uninstall some.
