### ISSUE TITLE
Server crash bug #2

### ISSUE THREAD

**Issue by theplayer232** [Facepunch/garrysmod-issues#2171]
Reporting another crash bug.

how to produce:
1. Open console and type: muscle_addlength 1e24
2. select fixed and start on
3. make expansion time 100
4. spawn ragdoll
5. attach muscle from sky to hand of any ragdoll, kleiner recommended
6. crash

**Comment by thegrb93** [comment]
The muscle addlength is clamped already between -1000 and 1000. Maybe that should be shortened?
