### ISSUE TITLE
Garrysmod cannot open now that I have windows 10

### ISSUE THREAD

**Issue by Bryantdl7** [Facepunch/garrysmod-issues#2172]
Heres some crashlog links. This just started with the install of win10

There's quite a few just to show it is a recurring issue, I'm sure you'll find the same error in each mdmp.
http://darkstorm.site.nfoservers.com/hosted/crashes/

here's an extracted one if you don't want to trust my .mdmp's
http://dumps.metastruct.uk.to/dumper.py?dump=hl2_2117156_crash_2015_7_31T1_59_6C0.mdmp&key=dD1YrKJ40E_SGzkSd2vCfyEtNZJioWMgnu3hOKNQSMRoj6VCWscTV6dvmnKhSUTFH4e9-xhLnh885BWzecxab67wkV4iRiAYftQ14A1ylVvHck2vWn6zT_Y3TBZ-tw65Kt4hEIX0n9YFmk7Az5H71gjX0J9l0k7twQZHqqARR-w=

**Comment by robotboy655** [comment]
That crash is not caused by Garry's Mod.

You seem to be crashing in a 3rd party module ```gshookhelper.dll```. Related files from your crash are ```AUDIOSES.DLL``` and ```rpcrt4.dll ```
