### ISSUE TITLE
Monitor goes black as if a resolution change has occurred

### ISSUE THREAD

**Issue by Bryantdl7** [Facepunch/garrysmod-issues#2173]
Upon launching garrysmod my screen goes black for a moment as if I am changing to a different resolution. However, both gmod and my computer are 1920x1080 resolution. I have tried doing a clean install of Garry's Mod, with no addons, and this still occurs. My video card is an AMD R9 200 series and I am running windows 10 if that is of any help.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
