### ISSUE TITLE
DListLayout DTextEntry children change order when gaining/losing focus

### ISSUE THREAD

**Issue by SticklyMan** [Facepunch/garrysmod-issues#2175]
I've come across an issue where a DTextEntry child in a DListLayout will get reordered to the bottom when focus is gained or is lost from it, AND the DListLayout is later invalidated.

Here is a video that shows the issue:
https://www.youtube.com/watch?v=r3mEaat24d0

This is a description of what's happening in the video:
1. The script to create the sample VGUI controls is run
2. The DListLayout's children is printed- you can see that they match up with the order on the panel itself.
3. The DTextEntry is focused, then unfocused.
4. The DListLayout's children is printed again- you can see that the DTextEntry has been moved to the bottom.
5. I invalidate the DListLayout, thus the visible order of the children is changed.

I'm hazarding a guess that the DTextEntry gets re-added or re-parented to the list view, thus causing the reordering of items, but I'm not sure. There might not be an easy fix for this, but I did want to make the issue known.

Below is all you should need to replicate this test yourself:

Sample VGUI code:

	local frame = vgui.Create( "DFrame" )
	frame:SetSize( 200, 400 )
	frame:SetPos( 100, 100 )
	frame:MakePopup()
	frame:SetTitle( "Panel children test" )
	test_list = vgui.Create( "DListLayout", frame )
	test_list:SetPos( 5, 25 )
	test_list:SetSize( 195, 190 )
	
	local txtfield = vgui.Create( "DTextEntry" )
	test_list:Add(txtfield)
	
	local txtfield = vgui.Create( "DTextEntry" )
	test_list:Add(txtfield)
	
	local label = vgui.Create( "DLabel" )
	label:SetText("Label 1")
	test_list:Add(label)
	
	local label = vgui.Create( "DLabel" )
	label:SetText("Label 2")
	test_list:Add(label)
	
	local label = vgui.Create( "DLabel" )
	label:SetText("Label 3")
	test_list:Add(label)

Console commands run during the test:

	lua_openscript_cl <sample_code.lua>
	lua_run_cl PrintTable( test_list:GetChildren() )
	* Click on the DTextEntry *
	lua_run_cl PrintTable( test_list:GetChildren() )
	lua_run_cl test_list:InvalidateLayout()

**Comment by TheFreeman193** [comment]
DListLayout makes use of the standard docking system within panels [(source)](../../../garrynewman/garrysmod/blob/master/garrysmod/lua/vgui/dlistlayout.lua#L41) and so this is likely a result of how children are handled (unsorted). Not sure if there's an easy fix for this.

**Comment by wiox** [comment]
You can sort docked panels by setting their z-position.

**Comment by SticklyMan** [comment]
Thanks for pointing that out, @wiox! Setting a default Z-pos in DListLayout's OnChildAdded seemed to fix the issue for me:
```
child:Dock( TOP )
child:SetZPos( #self:GetChildren() )
```

.. I'm not entirely sure that wouldn't mess with anything else, though.

**Comment by wiox** [comment]
There's not much in the base game that set's the z-position. It should probably be added in to DListLayout though.

**Comment by SticklyMan** [comment]
That quick fix does have an issue if you, for example, add 5 items, remove the 3rd, then add another, the new item won't added at the end. We could either iterate through the children and find the highest existing ZPos, or just use a property and increment it each time something's added, but it seems a tidbit excessive.

I tried to get a solution using self:GetChildren()[n-1]:GetZPos(), but it had some quirks that somehow managed to muck up the order.

**Comment by robotboy655** [comment]
I have looked into it, and fixing it would cause this:
![image](https://cloud.githubusercontent.com/assets/3299036/9939848/1c4ebf58-5d75-11e5-843a-24133c228a81.png)

Which can be fixed with another hack or something, but it will also affect any other addon that uses  DListLayout will also be affected

**Comment by robotboy655** [comment]
#2574
