### ISSUE TITLE
Start driving prop from any distance

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#2176]
This lua code allows controlling props from any distance, even other side of map.

Code:
function sdrv()
for k,v in ipairs(ents.GetAll()) do
if (v:GetClass() == "gmod_camera" or "cam" or "viewmodel") then
net.Start("properties")
net.WriteString("drive")
net.WriteEntity(v)
net.SendToServer()
end
end
end
concommand.Add("startdrv", sdrv)

then open that script as clientside and put or throw prop any distance and type "startdrv" to console without quotes.

**Comment by thegrb93** [comment]
It is already known that net messages can be used to trigger properties from anywhere. Your if statement should be if (v:GetClass() == "gmod_camera" or v:GetClass() == "cam" or v:GetClass() == "viewmodel") then

**Comment by robotboy655** [comment]
This should now be fixed for good.

Added proper distance check and entity validity check to all built-in properties.

Custom properties can now use properties.CanBeTargeted( ent, ply=NULL ) to enable these checks for their properties.
