### ISSUE TITLE
.gma files won't get deleted

### ISSUE THREAD

**Issue by shoopdahoop** [Facepunch/garrysmod-issues#2178]
With a previous update, Garry said that unsubscribing from addons deleted the associated .gma file. That doesn't seem to be the case all of a sudden. I unsubscribed from multiple addons, and the .gma files were still there.

**Comment by robotboy655** [comment]
It only works if you unsubscribe while you are in the game ( and possibly only through the Steam Workshop webpage while in-game )

**Comment by shoopdahoop** [comment]
oh... .-.

**Comment by bmwalters** [comment]
@robotboy655 this was fixed a few updates ago with the `menu_cleanupgmas` change, correct?

**Comment by robotboy655** [comment]
You still have to run it manually. It will be properly fixed for subscriptions with ISteamUGC

**Comment by uRandomAlex** [comment]
Add an option to disable automatic unsubscribed addon removing. I don't want my 3 hours of effort building base be wasted just because some stupid addon creator removed his props.

**Comment by Kefta** [comment]
Is automatic GMA removal still planned? Because it seems fine how it is now imo
