### ISSUE TITLE
sbox_persist doesn't persist through server restarts

### ISSUE THREAD

**Issue by Fuzzik** [Facepunch/garrysmod-issues#2180]
sbox_persist "1" is in my server.cfg, thus being set before the map loads. Making an entity persistent and using changelevel to see if it is still there works fine, but even after using changelevel to load the same map, persistent entities are gone after a server restart.

The persist file for the map "data/persist/mapname_1.txt" is still there, but it's as if it's being ignored by the game.

**Comment by mcd1992** [comment]
If I'm not mistaken persisting entities only works in single player or on listen servers.

**Comment by robotboy655** [comment]
I am pretty sure your convar is being reset to 0.

**Comment by Fuzzik** [comment]
After a restart the server console says its set to 1.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/gamemodes/sandbox/gamemode/persistence.lua#L51-L54

Add ```print(PersistPage)``` and see what it prints ( BEFORE the ```if then return end``` bit )

**Comment by Fuzzik** [comment]
Alright, one moment.

**Comment by Fuzzik** [comment]
A bit confused, should that print something to the server console on startup or do I execute it in game, or something else?

**Comment by robotboy655** [comment]
Add it to the file, restart your server and look for server console output.
```
hook.Add( "InitPostEntity", "PersistenceInit", function()

	local PersistPage = GetConVarString( "sbox_persist" )
	print("DONT MISS ME: ------------------------------------- ", PersistPage)
	if ( PersistPage == "0" ) then return end

	hook.Run( "PersistenceLoad", PersistPage );
	
end )
```

**Comment by Fuzzik** [comment]
DONT MISS ME: ------------------------------------- 1

**Comment by robotboy655** [comment]
Dedicated server?

**Comment by Fuzzik** [comment]
Yes

**Comment by robotboy655** [comment]
server.cfg is executed AFTER or WHILE InitPostEntity, so it is too late.

![image](https://cloud.githubusercontent.com/assets/3299036/9147916/204eb446-3d77-11e5-9e10-183202f8cec3.png)

You can see PersistPage in console before the sbox_persist prints in red from the server.cfg, which is for me:
```
sbox_persist
sbox_persist "1"
sbox_persist
```

**Comment by Fuzzik** [comment]
Would you recommend setting it in the batch file that opens the server or somewhere else so it is set to 1 before InitPostEntity?
