### ISSUE TITLE
Entity:SetMaterial doesn't work on DirectX 8 (or lower?)

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#2182]
The title says it all.
One of my gamemodes relies on this heavily, and players are gaining an unfair advantage by changing  the value of mat_dxlevel, revealing entites that should otherwise be quite hard to see. I will try to work around it using MaterialOverride, but having this fixed would be quite nice.

**Comment by xaviergmail** [comment]
>4:08 PM - Willox: willox solution 102
>4:09 PM - Willox: MINIMUM:  
OS: Windows® Vista/XP/2000 
Processor: 1.8 GHz Processor 
Memory: 2GB RAM 
Graphics: DirectX® 9 level Graphics Card (Requires support for SSE)
>4:10 PM - CSi. Xavier: so I can give the middle finger to anyone running dx8
>4:10 PM - Willox: you can

**Comment by Noiwex** [comment]
check if they have dx9 shader level support, if they not then kick em

**Comment by xaviergmail** [comment]
That's an option. Instead, I'll bother them with an annoying popup giving them an option to either change mat_dxlevel or to leave it at its current value and not draw the entities.

**Comment by xDShot** [comment]
Is it fixed already? This is still happening for me.

**Comment by robotboy655** [comment]
DirectX 8 is not officially supported by Garry's Mod, or any other Source Engine game at this point.
