### ISSUE TITLE
SortedPairsByMemberValue failing to unset __SortedIndex and bad performance

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#2183]
Unlike all the other SortedPairs\* functions SortedPairsByMemberValue does not create a copy of the original table. This results in __SortedIndex being set on the original table. While __SortedIndex is being unset in the fnPairsSorted function, if it reaches the end of the keys, it is not being unset in the case of 
a) lua errors 
b) break statements.

Example Code:

``` lua
local testTable = {{ID=1},{ID=2},{ID=3}}
for k,v in SortedPairsByMemberValue(testTable,"ID") do
    break
end
PrintTable(testTable)
```

This example would not unset __SortedPairs on the testTable, while using SortedPairsByValue (on an appropriate table) would work just fine.
To fix this the original table should be copied first.

I also find it really weird that all of the sorting functions create a deep copy (table.Copy) of the original table, when that is completely unnecessary (for example sorting a table that contains the global table and other really large tables would take ages).

Also, this apparently crashes my game but I can't figure out why.

``` lua
_G.ID = 1
local crashTable = {_G, _G, _G}
for k,v in SortedPairsByMemberValue(crashTable, "ID") do
    print(v.ID)
end
```

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/5e9d4fa05ea9cc69c56e5c0857d5247dcabdc192

I don't follow on the deep copy stuff, is there any other way to copy a Lua table?

**Comment by Bo98** [comment]
I think he means that it only needs to copy the top level table rather than recursing through and copying every child table.

Simplified example:

```lua
-- Deep copy (like table.Copy)
function deepCopy(orig)
    local ret = {}
    for k, v in pairs(orig) do
        if type(v) == "table" then
            ret[k] = deepCopy(v)
        else
            ret[k] = v
        end
    end
    return ret
end

-- Shallow copy
function shallowCopy(orig)
    local ret = {}
    for k, v in pairs(orig) do
        ret[k] = v
    end
    return ret
end
```

**Comment by robotboy655** [comment]
That's actually a good point, thanks.
