### ISSUE TITLE
Server lag bug

### ISSUE THREAD

**Issue by theplayer232** [Facepunch/garrysmod-issues#2184]
Very simple and effective, doing with multiple ragdolls makes it stronger lag.

How to:
https://www.youtube.com/watch?v=6tVjL8Z2EHQ

**Comment by mcd1992** [comment]
This is an issue with the source physics engine, not a garrysmod only issue.

**Comment by robotboy655** [comment]
Yeah, there's nothing we can about physics bugs like that.
