### ISSUE TITLE
Helpppppp

### ISSUE THREAD

**Issue by OpTwist** [Facepunch/garrysmod-issues#2186]
My Garrys mod says theres something wrong with my DirectX runtime I updated it like it said but it wont work. Can anyone help? Please I payed 10 dollars to play not to get some piece of junk sitting here. It looks super fun so I need someone to help!!! I have DirectX 11 and it says I need a minimum of 9 so i have the right version.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16 or http://support.facepunchstudios.com/

Solution here:
http://support.facepunchstudios.com/kb/articles/26-your-directx-runtime-is-out-of-date
