### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Grizze** [Facepunch/garrysmod-issues#2188]
This issue has been around for me for quite a while now.After launching Garry's Mod It will take me to the blue loading screen.After a few second It just close on it's own.Doesn't even take me to the main menu or show me an error message!
I have tried the following:
-Removing all addons
-Uninstalling Garry's mod and installing it
-Using -autoconfig and -sw
-Uninstalling and installing steam
-dxlevel 81
-Verifying integrity of game cache
Here's the crash report:
http://dumps.metastruct.uk.to/dumper.py?dump=hl2_150628_crash_2015_8_10T16_16_57C0.mdmp
Thanks a lot :P

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
