### ISSUE TITLE
NW Vars has high chance of failing when applied to player in PlayerInitialSpawn hook.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2189]
I've noticed since sometimes usergroups aren't being applied to players. admins sometimes have to rejoin to get their privileges.

Also oddly things like this can happen,
```
] lua_run_cl print(Entity(1):GetNWString("UserGroup"))
superadmin
] lua_run_cl print(Entity(1):IsAdmin())
true
] lua_run print(Entity(1):GetNWString("UserGroup"))

] lua_run print(Entity(1):IsAdmin())
false
```

**Comment by robotboy655** [comment]
I am going to dismiss this as "a problem on your side" because we'd have much more shitstorm if this was the case, including my own admin mod ( which uses the same exact thing ) not working, but it does work.

Unless other people can confirm this is happening of course.

**Comment by thegrb93** [comment]
Can you explain the desync between the server and client nwvars though?

**Comment by robotboy655** [comment]
Override of NWVar functions? By an addon or someshit? I for sure can't explain the fact that you have no usergroup set on server.

**Comment by robotboy655** [comment]
You haven't even bothered to post any code that sets the nwvar

**Comment by thegrb93** [comment]
It won't help, but here it is. It overwrites the PlayerAuthSpawn here, https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/lua/includes/extensions/player_auth.lua#L81

```
hook.Add("PlayerInitialSpawn", "PlayerAuthSpawn", function(ply)
	local rank = ply:EV_GetRank()
	ply:SetNWString( "EV_UserGroup", rank )
	ply:SetUserGroup( evolve.ranks[ rank ].UserGroup )
	hook.Call( "EV_PlayerRanked", nil, ply, rank )
	
	evolve:TransferPrivileges( ply )
	evolve:TransferRanks( ply )
	
	ply:SetNWInt( "EV_JoinTime", os.time() )
	ply:SetNWInt( "EV_PlayTime", ply:GetProperty( "PlayTime" ) or 0 )
	net.Start("EV_TimeSync")
		net.WriteUInt(os.time(), 32)
	net.Send(ply)
end)
```

**Comment by thegrb93** [comment]
Forgot to mention I also deleted the existing code that did the ranking on player spawn. The preexisting code also had the same issue.

**Comment by thegrb93** [comment]
This gets the rank
```
function _R.Player:EV_GetRank()
	if ( SERVER and self:IsListenServerHost() ) then return "owner" end
	
	local rank
	
	if ( SERVER ) then
		rank = self:IsFullyAuthenticated() and self:GetProperty( "Rank", "guest" ) or "guest"
	else
		rank = self:GetNWString( "EV_UserGroup", "guest" )
	end
	
	if ( evolve.ranks[ rank ] ) then
		return rank
	else
		return "guest"
	end
end
```

**Comment by robotboy655** [comment]
As soon as you start editing game files you lose all support at least from me.

Either test it with vanilla GMod and report back or go troubleshoot your problems on the forums.

**Comment by thegrb93** [comment]
What I meant by "overwrites" is I add my hook after the original, but I will experiment some more. debug.getinfo shows that SetNWString is defined in C at least.

**Comment by thegrb93** [comment]
I think I should also mention the original code used the PlayerSpawn hook and a timer.

**Comment by thegrb93** [comment]
https://github.com/Xandaros/evolve/blob/master/lua/ev_framework.lua#L649

**Comment by robotboy655** [comment]
Whatever the case, the new NWVars should fix this problem whenever @UnderscoreKilburn decides to  come back and fix his goddamn nwvars already

**Comment by thegrb93** [comment]
Still having the issue so I'm going to use this as a hack.

```
hook.Add("PlayerInitialSpawn", "PlayerAuthSpawn", function(ply)
	local function doRanking()
		local rank = ply:EV_GetRank()
		ply:SetNWString( "EV_UserGroup", rank )
		ply:SetUserGroup( evolve.ranks[ rank ].UserGroup )
		hook.Call( "EV_PlayerRanked", nil, ply, rank )
		
		evolve:TransferPrivileges( ply )
		evolve:TransferRanks( ply )
		
		ply:SetNWInt( "EV_JoinTime", os.time() )
		ply:SetNWInt( "EV_PlayTime", ply:GetProperty( "PlayTime" ) or 0 )
		net.Start("EV_TimeSync")
			net.WriteUInt(os.time(), 32)
		net.Send(ply)
	end
	doRanking()
	
	local function retry()
		if ply:GetNWString("UserGroup")=="" then
			doRanking()
			timer.Simple(1, retry)
		end
	end
	timer.Simple(1, retry)
end)
```

**Comment by Mrkrabz** [comment]
Same issue, having a timer of 0.1 seconds seems to solve it.

**Comment by thegrb93** [comment]
I think the problem is that I have an addon that sends about 12kb of data over the net channel at PlayerInitialSpawn, so maybe it was getting full or something. I've removed that and hopefully that fixes it.

**Comment by thegrb93** [comment]
It seems less common now, but I've still sometimes had the NWVar on the server get removed after the player it is on noclips outside the map. The NWVar on the client remains the same, but on the server it doesn't exist anymore.

**Comment by robotboy655** [comment]
It is normal for new ones to be desynched ```on the client``` when the entity leaves the players PVS, it would get synched back when the entity enters the PVS again. That's now most entity data storage works in any multiplayer game. The entity may even become non existent.

**Comment by thegrb93** [comment]
The NWVar gets destroyed on the server though. Not the client.
