### ISSUE TITLE
Linux servers does not work from the last update

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-issues#2190]
Error
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
./srcds_run: line 353: 32407 Segmentation fault      (core dumped) $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Tue Aug 11 12:58:37 EDT 2015: Server restart in 10 seconds
Tue Aug 11 12:58:39 EDT 2015: Server Quit

Information about the vps by command uname --all
2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Its happen to more linux servers : http://facepunch.com/showthread.php?t=1450721&p=48435639#post48435639

**Comment by P4sca1** [comment]
Add -debug and show us the error then.

**Comment by P4sca1** [comment]
http://facepunch.com/showthread.php?t=1458227&p=48435556#post48435556
Does this fix the issue for you too?

**Comment by hanm13** [comment]
----------------------------------------------
CRASH: Tue Aug 11 13:38:23 EDT 2015
Start Line: ./srcds_linux -console -game garrysmod +maxplayers 5 +exec dev.cfg +map rp_industrial17_v1.bsp -secure -port 26553 +gamemode combinecontrol -tickrate 12 -debug
End of Source crash report
----------------------------------------------



Copy linux32 to bin folder did not help.

**Comment by mcd1992** [comment]
Did you fix the issue @hanm13 ?

If not try doing a app_update validate.

**Comment by hanm13** [comment]
Yeah I fixed it
