### ISSUE TITLE
improve prop search

### ISSUE THREAD

**Issue by X-Coder** [Facepunch/garrysmod-issues#2192]
Is it possible to improve the prop search?

Right now it is kind of useless for me because as soon as I start the search my game is kind of frozen for a few minutes until it finished searching, so I stopped using it - even if I would need it often.

I play garrysmod for many years, and it was always like this as far I remember. The computer is new and very fast so this shouldn't be the issue. I'm using a few bigger addons (spacebuild / stargate) and some game mounts (tf2, ep1, ep2, css).

How is the search actually working?
Is it using some kind of cache on the first run, or does it lookup all the .mdl files on each run on the whole game and mounts?

If there is no cache, would it be possible to create one? Maybe by a button which builds or refreshes the cache so later searches are faster without the freezing?

**Comment by robotboy655** [comment]
There is a cache, it is that slow because sit looks through thousands of files each second.

**Comment by X-Coder** [comment]
Why can't this be improved?

**Comment by thegrb93** [comment]
The cache is stored in memory. It would be nice to store the cache on the disk so it won't have to be generated each time the game is restarted.

**Comment by robotboy655** [comment]
Yeah, it would be nice so that if you add an addon, it is never included into the search.

**Comment by thegrb93** [comment]
I'm not saying it wouldn't need extra work.

**Comment by X-Coder** [comment]
robotboy655, the cache you mean is build on the first search and only lasts for the current map, if you do a map change, its gonna rebuild the cache on first search again.

For now, I changed it myself to a persistent cache using SQlite in the GetAllFiles function, it only gets regenerated when I say so by using a console command.

But you are right about adding new addons / files, the the persistent cache has then to be rebuild. For now I will do this manually by the console command (when I install new addons or play on another server). This is still better for me than letting it rebuild the cache each time.

If I would do it automatic, then I would have the same problem the current GetAllFiles() is having  which makes the game looks like frozen while the GetAllFiles () function is running.

I don't know anything about coroutines, but is it possible with this to make the game not freeze while the GetAllFiles() function is running?
