### ISSUE TITLE
SetModelScale increases the size of player/player (not player/world) collisions

### ISSUE THREAD

**Issue by ottworks** [Facepunch/garrysmod-issues#2193]
So it appears that hull sizes between players act way bigger than between player and world. Meet Bot01.
![He's very friendly.](http://i.imgur.com/4mC7oRK.png)
Bot01 has a scale of 2. That means his hull ranges from (-32, -32, 0) to (32, 32, 144).
![Works fine with props.](http://i.imgur.com/gbutHAZ.png)
But when I collide with him with a normal hull of (-16, -16, 0)-(16, 16, 72), it feels twice as big:
![Front.](http://i.imgur.com/2TQpYMe.jpg)
![Back.](http://i.imgur.com/gC9VfSl.png)
My Y pos ranges from 102.5 to -57.5, minus my own hull 86.5 to -41.5, or 128 units wide. 
The Z pos is also similar, ranging from 144 to -144, or 288 tall.
Okay, that's weird, let's measure some more.

| Scale | World Width | Player Width | Width Percentage | World Height | Player Height | Height Percentage |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 32 | 32 | 100% | 72 | 72 | 100% |
| 2 | 64 | 128 | 200% | 144 | 288 | 200% |
| 3 | 96 | 288 | 300% | 216 | 648 | 300% |
| 0.5 | 16 | 8 | 50% | 36 | 18 | 50% |

So yeah basically player/player collision hulls are being scaled twice (which doesn't make very much sense because I'm setting to absolute numbers in my code) while player/everythingelse hulls are fine. This leads to smaller players getting stuck inside of larger players. You can watch a less detailed demonstration of the problem [here](https://www.youtube.com/watch?v=L2JtT1JnkDA).

**Comment by DaaOtt** [comment]
It also appears that player and already-broken func_breakable_surf collisions are just as large as player/player collisions.

**Comment by DaaOtt** [comment]
@UnderscoreKilburn

**Comment by DaaOtt** [comment]
Also does this with physgun:

![](http://i.imgur.com/cUg4esv.jpg)

**Comment by robotboy655** [comment]
Cannot confirm this with a bot

```lua_run Entity(2):SetModelScale(8)```

**Comment by robotboy655** [comment]
Actually, I can see the difference, but it's not as bad as you have it, the scaled player vs player collisions scale properly, while the scaled player vs world collisions do not scate at all.

**Comment by robotboy655** [comment]
```Entity(2):SetHull( Vector(-16,-16,0) * 8,Vector(16,16,72) * 8)``` Seems to work better.

**Comment by DaaOtt** [comment]
Oops, looks like it's something else: SetModelScale  affects player/window collisions, but Hull affects everything else

**Comment by DaaOtt** [comment]
It seems that they BOTH affect player/player collisions but hull affects everything else

**Comment by DaaOtt** [comment]
![](http://i.imgur.com/XmwQYnw.png)
produces a hull that is 64 wide; 4x scale + 0.5x hull = 2x collisions

**Comment by DaaOtt** [comment]
Okay well it seems I've completely missed the point of SetModelScale. Guess I'll have to use matrixes if I want good hulls.

**Comment by DaaOtt** [comment]
Wait no cause then I won't get my hitboxes. New request: a SetModelScale that doesn't mess with collisions.

**Comment by thegrb93** [comment]
Hopefully this can also fix the screwed up hull sizes/hitboxes pac3 player scale modification has.

**Comment by Python1320** [comment]
I rewrote the player resizing on PAC3. It no longer uses SetModelScale. Not sure how much better it is, since I don't personally use it, but I've heard of no extra complaints.

**Comment by DaaOtt** [comment]
@willox

**Comment by TheRedKorsar** [comment]
Do this bug have some improve? It is easy to test, it. Just make modelscale of bot to 2 and try to hit his body with prop... Nothing. prop hit old Hull Size box, 32x32x72 But you as player hit his hull 64x64x144...
![image](https://user-images.githubusercontent.com/7902575/28693958-eb9c6068-732f-11e7-8efb-d153fe2b00f9.png)

**Comment by mcNuggets1** [comment]
This is still a thing.
Players getting stuck on shit after SetModelScale is called on them

**Comment by roboderpy** [comment]
Still waiting on this bug.

**Comment by refugeecamp** [comment]
Not sure if this is the best way to do this but I think this issue is still present in a different form as mentioned here: https://forum.facepunch.com/gmoddev/bucec/Wonky-player-entity-collisions-when-scaling-entities-down/1/

**Comment by Headshotz** [comment]
Its been bug for years, I think its better add new argument for not scale the hull, just scale the player model itself including hitboxes as well. So we can use SetHull without problem. This is better than manual the ManipulateBone stuff because its does networking to everyone and having choke so bad.

**Comment by LeQuackers** [comment]
I did some research and I think I found part of the problem.

In shareddefs.h the hull min/max macros all use ```CBaseAnimating::GetModelScale```, which is also called in ```CCollisionProperty::SetCollisionBounds```. When ```CBasePlayer::RefreshCollisionBounds``` is called it uses the already scaled hull macros to setup the players bboxes, which is scaled again when the collision bounds are set.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/shareddefs.h#L88-L99

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/collisionproperty.cpp#L674-L675

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/player.cpp#L8321-L8345

Also, ```CBasePlayer::GetPlayerMins/Maxs``` uses the hull macros as well. Both of these are used in player movement, so simply removing the scaling from the macros would break stuff.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/baseplayer_shared.cpp#L364-L405

**Comment by LeQuackers** [comment]
Did some tests; the hull doesn't appear to scale with ```Entity:SetModelScale```, so ```CBaseAnimating::GetModelScale``` was probably removed from the hull macros a while ago.

That leaves ```CBasePlayer::RefreshCollisionBounds``` using the player's hull to create their bboxes which are then scaled by ```CBaseAnimating::GetModelScale``` in ```CCollisionProperty::SetCollisionBounds```.

Multiplying the hull mins/maxs by the inverse of the model scale before setting the player's bboxes could fix it, but it seems hacky.

**Comment by LeQuackers** [comment]
Setting the collision bounds before player movement mitigates the issues and almost fixes it for bots. With varying sizes, the bots don't get stuck in each other. If the player's size is unchanged, they don't get suck in the scaled bots either, however; if the player's size has been changed, they are still likely to get stuck in the bots.

```
ScaledPlayers = ScaledPlayers or {}
function PhysTest(ent, scale) -- needs to be called on SERVER and CLIENT
	ent:SetModelScale(scale, 0)
	
	ent:ResetHull()
	
	local min, max = ent:GetHull()
	ent:SetHull(scale * min, scale * max)
	
	local min, max = ent:GetHullDuck()
	ent:SetHullDuck(scale * min, scale * max)
	
	ScaledPlayers[ent] = true
end



hook.Add("StartCommand", "test", function(ply, cmd)
	for other, _ in pairs(ScaledPlayers) do
		local min, max
		if other:IsFlagSet(FL_DUCKING) then
			min, max = other:GetHullDuck()
		else
			min, max = other:GetHull()
		end
		
		local scale = 1 / other:GetModelScale()
		other:SetCollisionBounds(scale * min, scale * max)
	end
end)
```

**Comment by LeQuackers** [comment]
Did some more tests; it seems like the physics object isn't being moved properly for whatever reason. Setting either the player's position or the physics object's seems to fix it (minus the prediction errors). I suspect ```Entity:SetNetworkOrigin``` has something to do with it; the wiki says it's the same as  ```Entity:SetPos``` server-side, but the tests show otherwise.

Here's what I have so far:

```
ScaledPlayers = ScaledPlayers or {}
function PhysTest(ent, scale)
	ent:SetModelScale(scale, 0)
	
	ent:ResetHull()
	
	local min, max = ent:GetHull()
	ent:SetHull(scale * min, scale * max)
	
	local min, max = ent:GetHullDuck()
	ent:SetHullDuck(scale * min, scale * max)
	
	ScaledPlayers[ent] = true
end

hook.Add("StartCommand", "test", function(ply, cmd)
	for other, _ in pairs(ScaledPlayers) do
		local min, max
		if other:IsFlagSet(FL_DUCKING) then
			min, max = other:GetHullDuck()
		else
			min, max = other:GetHull()
		end
		
		local scale = 1 / other:GetModelScale()
		other:SetCollisionBounds(scale * min, scale * max)
	end
end)

hook.Add("FinishMove", "test", function(ply, mv)
	-- players/bots don't get stuck
	-- players/bots can't be pushed
	-- pushing props causes damage more often
	local phys = ply:GetPhysicsObject()
	if phys and phys:IsValid() then
		phys:EnableMotion(true)
		phys:SetPos(mv:GetOrigin())
		phys:EnableMotion(false)
	end
	
	-- previous tests:
	
	-- players/bots can get stuck, but you have to try
	--[[local phys = ply:GetPhysicsObject()
	if phys and phys:IsValid() then
		phys:SetPos(mv:GetOrigin())
	end]]
	
	-- players/bots don't get stuck, but it breaks animations
	--[[ply:SetPos(mv:GetOrigin())
	ply:SetSaveValue("m_vecAbsVelocity", mv:GetVelocity())
	return true]]
	
	-- very likely to get stuck (this should behave like the SetPos test, but doesn't)
	--[[ply:SetNetworkOrigin(mv:GetOrigin())
	ply:SetSaveValue("m_vecAbsVelocity", mv:GetVelocity())
	return true]]
end)
```

Also, I set m_vecAbsVelocity directly because ```Entity:SetAbsVelocity``` sets the local velocity. I was trying to figure out if the velocity of the player had something to do with it, still not sure.

**Comment by robotboy655** [comment]
Yeah even after adjusting the hull to be scaled there's still a weird issue with player/player collisions being scaled improperly which is probably causing the prediction errors with climbing slopes/stepping down, interestingly only for scales >1.

I will put the hull scaling onto dev/pre-release on Monday

**Comment by robotboy655** [comment]
I think I figured it all out, keeping this open till I commit the code.

**Comment by LeQuackers** [comment]
What was the issue?

**Comment by robotboy655** [comment]
Should be all fixed.
