### ISSUE TITLE
DoModal suppresses DComboBox functionality

### ISSUE THREAD

**Issue by 10853** [Facepunch/garrysmod-issues#2194]
Title says it all, really. I've created a DFrame and added a DComboBox child to it. It works fine while DoModal isn't being called, but if it is, I can no longer select any of the options in the DComboBox's internal panel.

**Comment by robotboy655** [comment]
Fixed

https://github.com/garrynewman/garrysmod/commit/97f423bd50bf73a0dc6cde095c36cdf174aac606
