### ISSUE TITLE
iMac OS X Yosemite “Up-To-Date” GMOD will NOT even launch

### ISSUE THREAD

**Issue by TheSupremePatriot** [Facepunch/garrysmod-issues#2196]
What is going on?

I attempted to use the app twice

First time, bought it, no luck
refund

second time, “thought i give it another shot”,
no luck
refund

I really would love to have third time “be the charm” as some would say....

What do I have to do to get this to work?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16

**Comment by TheSupremePatriot** [comment]
Then why was someone else have a thread on here about it?
