### ISSUE TITLE
buildcubeworld doesn't work any more.

### ISSUE THREAD

**Issue by totalgaara** [Facepunch/garrysmod-issues#2197]
Hi.

Since the latest update of August, buildcubeworld doesn't work anymore, he is crashing with vtex error.
(no file errors). It just say : 

bounce: 1/1 sample: 146/147
bounce: 1/1 sample: 147/147
vtex failed to compile cubemap!

I tried on my new compilated map, an a old map witch i'm sure it's working, but it's fails too.

Thank

**Comment by robotboy655** [comment]
Care to at least attach a map that crashes?

**Comment by totalgaara** [comment]
Hi, when i build my map with hammer, I have every time type the command otherwise reflections are pink :

mat_specular 0
buildcubemaps
mat_specular 1

But since the last update day , mat_specular 1 buildcubemaps is functional but does not save it crash and recharge my map without save
I wrote a topic on the site because I thought Facepunch simply that my map was to have a bug or something else. But it turned out that I was not alone in this situation

**Comment by robotboy655** [comment]
Yeah, I figured that you have a problem, can you attach a map that causes the problem or not?

**Comment by totalgaara** [comment]
Here is my map 

http://www.mediafire.com/download/s4hcnq5stvxliu9/rp_rockford_heavencity_1.bsp

it's based on Rockford Maps.

**Comment by robotboy655** [comment]
I am pretty sure the problem is with your map. Make sure you don't have an mulitple env_cubemaps in the exact same spot.
