### ISSUE TITLE
G-Mod StudioMdl issue with 32 bodygroups or more.

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#2198]
Hello,

it has recently been discovered that the G-Mod StudioMdl will not compile models with 32 bodygroups or more. Compiling with 31 bodygroups or less will make the model work correctly.
Going over the limit will give out this error message : "ERROR: 'EXCEPTION_ACCESS_VIOLATION' (assert: 1)"

If possible, can anything be done to the G-Mod version of StudioMdl to allow for more than 32 ?

Thanks.

**Comment by robotboy655** [comment]
It should now be unlimited in Dev and in the next update. Let me know if there are any problems, but there shouldn't be any.
