### ISSUE TITLE
Anomaly Linux errors (client)

### ISSUE THREAD

**Issue by 00875** [Facepunch/garrysmod-issues#2200]
![2015-08-17_12-03_ponyrp rc 0 19 shoot that](https://cloud.githubusercontent.com/assets/6339511/9298389/6b63da5c-44d8-11e5-93d1-bbcddf71b238.jpg)

6 secs and client crashing.
Windows clients works perfectly.

**Comment by robotboy655** [comment]
This is not a place to get help with scripting. Get help @ http://facepunch.com/forums/65
