### ISSUE TITLE
Most CS:GO props invisible in Windows Garry's Mod

### ISSUE THREAD

**Issue by weallmissedme** [Facepunch/garrysmod-issues#2201]
So, here's a problem I've experienced. I used to be a linux user. EVERY SINGLE CS:GO map prop would show up on Linux. EVERY. LAST. ONE. But I recently switched to windows. Now, almost none of them show up. Is anyone aware of what could cause this?

**Comment by Noiwex** [comment]
verify your cache

**Comment by weallmissedme** [comment]
I did. Still nothing. Which I find incredibly odd. I dont' know why switching OS'S would break it.

**Comment by robotboy655** [comment]
http://facepunch.com/forums/16
