### ISSUE TITLE
http library onFailure functions don't give any useful errors.

### ISSUE THREAD

**Issue by ARitz-Cracker** [Facepunch/garrysmod-issues#2202]
The only thing the onFailure function passed to the http.Fetch and http.Post functions is given is a string saying "unsuccessful". What the hell does that mean?!

Did the connection time out? Has the connection been refused? Was the host not found? Is the steam HTTP service unavailable? Who knows, you figure it out!

It's a pain trying to give support for my addons that use this function, when I have no idea if it's a problem on my end or their end. (Usually it's a problem on their end, but I don't gain any insight on what their issue actually is)

Please give me actual errors that I can work with!

**Comment by robotboy655** [comment]
AFAIK Steam API doesn't even provide any HTTP error codes, only some arbitrary error codes.

**Comment by ARitz-Cracker** [comment]
Even that would be more useful than a general failure message. (If it was documented)

**Comment by robotboy655** [comment]
Alright, so the errors are:
```invalid url``` - Invalid url ( no request was even attempted to be made (
```invalid request``` - Steam HTTP lib failed to create a HTTP request
```error``` - OnComplete callback's second argument bError is true
```unsuccessful``` - OnComplete's first arugment pResult->m_bRequestSuccessful returned false

There's no way to get a HTTP error or any other error, and none of the SteamHTTP stuff is documented anywhere.

**Comment by Bo98** [comment]
Don't have access to Steamworks but what is pResult->m_eStatusCode used for (I've seen it used but I don't know if it really exists)?

**Comment by robotboy655** [comment]
It returns 0 unless it is a successful request, at which point onsucess is called.

**Comment by ARitz-Cracker** [comment]
So, this means that we can't get any useful information passed to us unless we switch to something different like curl?

**Comment by ZehM4tt** [comment]
Actually HTTPRequestCompleted_t has it inside, see the EHTTPStatusCode m_eStatusCode member which is the enum:
...
// Success codes
	k_EHTTPStatusCode200OK =					200,
	k_EHTTPStatusCode201Created =				201,
	k_EHTTPStatusCode202Accepted =				202,
...

**Comment by robotboy655** [comment]
Changing not k_EHTTPStatusCode200OK queries to call unsuccess function will break anything that already uses the success function to handle not k_EHTTPStatusCode200OK codes.

I guess I will document this behavior on wiki tho.
