### ISSUE TITLE
MOVETYPE_PUSH broken

### ISSUE THREAD

**Issue by huwpascoe** [Facepunch/garrysmod-issues#2203]
MOVETYPE_PUSH doesn't work.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/func_movelinear.cpp#L69
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/subs.cpp#L199

As shown here with func_movelinear, you're supposed to be able to use SetAbsVelocity or SetLocalVelocity to create things like elevators but in the lua scripts, creating something similar to func_movelinear does nothing and the entity doesn't move!
```
self.Entity:PhysicsInit( SOLID_VPHYSICS )
self.Entity:MakePhysicsObjectAShadow( false, false )
self.Entity:SetMoveType(MOVETYPE_PUSH)
...
self.Entity:SetLocalVelocity( Vector(1000, 0, 0) )
```
Interestingly though, standing on the still entity and jumping seems to add the requested velocity vector to your jump vector, so something is trying to happen at least.

**Comment by Jcw87** [comment]
MOVETYPE_PUSH does work, it just requires a little messing about. This is some code from my Doom Maps addon.

	function ENT:Setup()
		-- blah blah code
		self:SetMoveType(MOVETYPE_NOCLIP) -- Without this, move speeds get messed up
		self:SetMoveType(MOVETYPE_PUSH)
		-- blah blah more code
	end

	function T_MovePlane(sector, speed, dest, crush, floorOrCeiling, direction)
		local ent = tobool(floorOrCeiling) and sector.ceiling or sector.floor
		-- blah blah code
		ent:SetSaveValue("m_flMoveDoneTime", save.ltime + math.abs(dest - pos.z)/(speed))
		ent:SetMoveType(MOVETYPE_PUSH)
		ent:SetLocalVelocity(Vector(0, 0, (speed * TICRATE) * direction))
		-- blah blah more code
	end
