### ISSUE TITLE
Mac OS X 10.10.5 Crashing for Memory and Engine Errors

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#2204]
I love my Mac, but when it comes to gaming it's not the best choice. Garry's mod really shows this by constantly crashing when using the Mac.  I have mainly gotten two errors involving memory and a vertex buffer error. Before you say this, I know — these issues are commonly posted on the bug report forums, but none have been in my config. or recently.  To start, I sometimes get the error "not enough memory" which doesn't make since considering that a have a functioning swap and 8GB of onboard memory installed.  I also get the error "failed to lock vertex buffer in CMeshD8X::LockVertexBuffer: nVertexCount=3097, nFirstVertex=0"  I have a mid 2012 MacBook Pro 13" with Intel HD 4000 Graphics and 8GB of memory.  Part of the issue could be the 5400RPM HDD.  I would appreciate any insight on these errors.

**Comment by robotboy655** [comment]
```Intel HD 4000 Graphics ```

And you complain games dont work properly. Either way, this "report" is absoultely useless and most likely a duplicate.

**Comment by Noiwex** [comment]
It works on windows with these Intel chips, don't underestimate them.

**Comment by Jake3231** [comment]
I understand that others have had this issue. I just haven't seen any food fixes or patches since the other bug reports were posted (even from some a few years back).  As for the graphics, I know they're not the best graphics you can get, but my game runs very smoothly and comfortably exceeds the game's requirements.  I'm sorry if this was a waste or your time...
