### ISSUE TITLE
Cubemaps do not build while using the 'painted' skybox texture.

### ISSUE THREAD

**Issue by youmenow1** [Facepunch/garrysmod-issues#2205]
As of the most recent update, **Buildcubemaps** work fine with any "actual" skybox material excluding when the **painted** skybox texture is set.

Upon entering the command with the **painted** skybox texture I am greeted post build in the console with **"Can't load skybox file painted to build the default cubemap!"** and **"Failed, using default cubemap 'engine/defaultcubemap'"** repeated for every cubemap entity. Of course, after this no resulting cubemaps have been successfully built and no impact on map filesize has been made.

I have heard many reports of multiple people experiencing the same problem, so I am not alone on this and thought it would be worth opening an issue over. Hopefully it can be sorted soon!

If you may require anything from my end I am more than happy to supply. Also if anyone else could contribute any findings on this issue that would be fantastic too. With that said, it seems the source of the problem is fairly obvious (at least from what I can tell) with a connection to a lack of default cubemap generation due to the textures procedural nature, so the cause of the problem shouldn't be too hard to discover (as for the difficulty of its fix I don't know, as I am not a programmer).

**Comment by robotboy655** [comment]
Should be fixed in Dev.
