### ISSUE TITLE
Entity:SetSubMaterial() silently fails

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2207]
The function Entity:SetSubMaterial() silently fails if the second argument is a material instead of a string. And I'm guessing it would when passing anything but a string to it.

Would like to have the traditional error of "expected 'string' but got '[PASSED_TYPE_HERE]'"
Instead of having to scratch my head for an hour of my life.

Thank you for reading my issue

PS: If your argument is "check the documentation" then please tell me how I was supposed to guess that I was calling the function wrong if it doesn't tell me so...

**Comment by robotboy655** [comment]
It doesn't silently fail, it resets the submaterial override.

I fail to see how when a function doesn't seem to be doing what it should, you don't immediately go and  check the documentation.
