### ISSUE TITLE
Memory leak with env_skypaint

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#2212]
I've been working on my gamemodes atmosphere .. however I kept crashing with "CUtIRBTree overflow!" for which I take as a memory leak.

I then spent 45 mins comparing it with my old github version .. slowly updating each file until the hl2-memory rocketed off with 200~700k-ram pr second.
I tracked it down to these single lines:

	print("Checking skies..")
	local l = ents.FindByClass( "env_skypaint" )
	local env_skypaint = nil
	if #l<1 then
	    env_skypaint = ents.Create('env_skypaint')
	    env_skypaint:Spawn();
	    env_skypaint:Activate();
	    game.ConsoleCommand("sv_skyname painted\n");
	    print("Activate skypaint")
	else
		env_skypaint = l[1]
	end

	local c = Color(75/6,75/6,75/6)

	env_skypaint:SetKeyValue("startexture","")
	env_skypaint:SetKeyValue("starfade",0)
	env_skypaint:SetKeyValue("topcolor",c.r/255 .. " " .. c.g/255 .. " " .. c.b/255)
	env_skypaint:SetKeyValue("bottomcolor",c.r/255 .. " " .. c.g/255 .. " " .. c.b/255)
	env_skypaint:SetKeyValue("duskscale",0)
	env_skypaint:SetKeyValue("fadebias",0)

Since there already is an env_skypaint entity on gm_flatgrass, the script just changes the key values. 
Not sure if I'm using it in a wrong way .. but its the similar way I used the entity in my weather-project back a ½ year ago. It had no problems back then.

**Comment by robotboy655** [comment]
Cannot reproduce. I just today was working with env_skypaint and nothing happened. Running your exact code doesn't do anything.
You didn't even bother to include where you are running the code from, hooks, filenames anything.
Client hardware, most importantly RAM.

**Comment by Nak2** [comment]
I find your last reply slightly derogatory, lets keep this professional.

I didn't provide a hook since I was able to reproduce the same effect outside the hook system.
I'll provided a video of a clean Garrysmod (Forgot to remove a HUD for my radioproject in the lua/autorun folder)
https://www.youtube.com/watch?v=x91Gf2ib5ow

**Comment by robotboy655** [comment]
Ok, I think I can confirm this.

It's due to this line:
```env_skypaint:SetKeyValue("startexture","")```
If you use an empty string it will leak for some reason.

**Comment by Nak2** [comment]
Thanks for confirming it. I would guess it keeps generating an unknown texture.
Its a silly memory leak but an annoying one when you spent 45 mins hunting it down.

**Comment by robotboy655** [comment]
I am pretty sure this can be done with any shader.

**Comment by Nak2** [comment]
Probably. It is a memory leak nonetheless tho.
Are you able to block the function from running if the string is empty?

I would feel bad for those who run over the same time ticking bomb.
