### ISSUE TITLE
Engine Error "classname missing from entity!"

### ISSUE THREAD

**Issue by TDGLeGameur** [Facepunch/garrysmod-issues#2214]
I would first point out that yours is I have not good English so it is normal for mistakes
So when I start garry's mod everything goes well, and I rejoin a jailbreak server and I see that the game gives me the error "classname missing from entity", I saw that it came from the map "blackops" and j will like to avoid this mistake to play on this server.
Thank you in advance.

**Comment by Kefta** [comment]
The blackops map works fine? I've played on it multiple times in CS:S and GMod without an issue
