### ISSUE TITLE
Font & Crosshaire problem (Letter Q on middle screen)

### ISSUE THREAD

**Issue by WareZ57** [Facepunch/garrysmod-issues#2219]
Hello,  The font HUD error http://goo.gl/sMCYjZ  The font install doesn't work on Windows 10 http://goo.gl/RSfMi3  all HL2 game is  installed http://goo.gl/W2qJg6 and  is actived on GMOD http://goo.gl/99C9gP

Gmod and All HL2 Game were all in clean reinstall without success
Thanks you.

How to fix it ?

 

(Sorry for my bad english)

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
