### ISSUE TITLE
Steam GMOD Error Code

### ISSUE THREAD

**Issue by GmodSteamPlayer** [Facepunch/garrysmod-issues#2221]
Alright so me and my friend were using hamachi to get into a server and play, but when I am about to join, when its doing the last loading bar, it crashes, giving me this error message: CUtlStreamBuffer::Close() Write (null) failed 4242 != 95008
Any help? Thanks!!!! -GmodSteamPlayer

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
