### ISSUE TITLE
AddAmmoType/BuildAmmoType doesn't invoke rebuild of ammo types

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2223]
Running AddAmmoType, even when subsequently calling BuildAmmoType, after the initial build will not register the type. Although BuildAmmoType returns them in the ammo table, the ID remains -1 as the key is unknown to the method.

**Comment by robotboy655** [comment]
Pretty sure that's intended. BuildAmmoTypes is only called by the engine when the ammo types are being built.

**Comment by Kefta** [comment]
When is BuildAmmoTypes called by the engine? Can there be a ConCommand or callback on BuildAmmoTypes to rebuild the ammo table?

**Comment by Kefta** [comment]
This is lame
