### ISSUE TITLE
Linux server hangs on startup

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2225]
Our linux server hangs after loading the addons and doesnt get to "PREP OK".
With hanging I do mean like forever, the server can't startup.
I don't know what information you need, so feel free to ask.

Linux 64 bit
gamemode darkrp

I also noticed that I'm still able to execute console commands like "gamemode sandbox" and "_restart".
We have also tried to remove all the addons, which did not solve the issue.

Validating the game using SteamCMD also had no effect (game already up to date)

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ http://facepunch.com/forums/16
