### ISSUE TITLE
Calling util.Effect("effect_name" effect_data) does not lead to EFFECT:Render() on client (only when dedicated server)

### ISSUE THREAD

**Issue by philxyz** [Facepunch/garrysmod-issues#2233]
v 2015.09.11 and earlier:

I am triggering an effect using util.Effect() - as described in the title.

I am calling it from both the client and server code.

If the server is a listen server, both EFFECT:Init() and EFFECT:Render() are called back on the client. However, If the server is dedicated, only EFFECT:Init() gets called on the client.

**Comment by robotboy655** [comment]
Post your effect code at least.

**Comment by philxyz** [comment]
=== Effect code ===
function EFFECT:Init(data)
        print("Effect Init Called")
end

function EFFECT:Think()
        return false
end

function EFFECT:Render()
        print("Effect Render Called")
end



=== Then on the server: ===

util.Effect("name_of_effect", edata)



-- I am not distinguishing between SERVER and CLIENT when calling util.Effect

**Comment by Jvs34** [comment]
Remember that EFFECT is actually an entity, to make it able to be seen by a player you have to set the renderbounds properly on it, I've never had troubles with my scripted effects.

**Comment by philxyz** [comment]
I see.. I wasn't aware of renderbounds. Thanks...

**Comment by philxyz** [comment]
It turned out that this was because I was returning false in EFFECT:Think(). Renderbounds didn't make a difference. Thanks, though. Hopefully this comment doesn't re-open the ticket.
