### ISSUE TITLE
Sound Bug!

### ISSUE THREAD

**Issue by konrad2503** [Facepunch/garrysmod-issues#2240]
Everytime i am on a map(SP) i got a lot of
CSoundEmitterSystemBase::AddSound( 'CW_MP5_BOLTFORWARD', 'scripts/sounds/lua.txt', ... ), script file not list in manifest 'scripts/game_sounds_manifest.txt'

and all hl2 /fas2 / m9k sounds are fucked up.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
