### ISSUE TITLE
Can't load any map!

### ISSUE THREAD

**Issue by WAC02mc** [Facepunch/garrysmod-issues#2242]
So, I don't know how to fix this, but I keep crashing trying to load any map. It loads until there are 2 Bars left and crashes.It doesn't show it crashes it just sends me to my desktop. Please help! 
Crash Log: https://www.dropbox.com/s/n7ipwp2xg874i59/hl2_150913_crash_2015_9_17T1_34_25C0.mdmp?dl=0
Add-Ons: (Collection)
http://steamcommunity.com/sharedfiles/filedetails/?id=519973931

**Comment by robotboy655** [comment]
It'd be helpful if you'd post your entire addon list.

**Comment by WAC02mc** [comment]
IDK if that works but plz try it

**Comment by robotboy655** [comment]
No it does not.

**Comment by WAC02mc** [comment]
There does that help or do you want GMa files?

**Comment by robotboy655** [comment]
Is this absolutely all of them? If so, I will look into it next week and try to reproduce the crash.

**Comment by WAC02mc** [comment]
Yes this is all of them.

**Comment by WAC02mc** [comment]
To reproduce the crash i just had to try to load a map.

**Comment by WAC02mc** [comment]
whoops

**Comment by robotboy655** [comment]
Ok, I managed to reporoduce the crash and find the culprit. The problem, precisely, is that you are hitting the obnoxious 8192 .lua file limit. Once you hit the limit and try to load new files, the game crashes.

I will look into fixing the problem now.

**Comment by WAC02mc** [comment]
ok

**Comment by robotboy655** [comment]
Will be fixed in next update. It may still crash if you get too many addons for your PC to handle, but not from the file limit.

**Comment by WAC02mc** [comment]
when is the next update?

**Comment by robotboy655** [comment]
when its done

**Comment by WAC02mc** [comment]
ok thanks for the help :D
