### ISSUE TITLE
HL2 Health Station showing animation that looks incorrect

### ISSUE THREAD

**Issue by benjamen50** [Facepunch/garrysmod-issues#2243]
Garry's Mod Version: 2015.09.13

When having a health station with charge in it. The animation does not correspond to the amount of charge it has left in it. Instead 50%-ish animation equals to 1% charge When draining the health station from 100% to 0%, the animation shows from 100% to 50% then suddenly 0%.

The animation never shows under 50% and 1% charge

**Comment by imp0se** [comment]
From what you described, I don't think I've ever had this issue before.
Did you try doing this again with all addons disabled?

**Comment by thegrb93** [comment]
I've seen it many times. Basically you expect more health but it just drops straight to 0 after a certain point.

**Comment by robotboy655** [comment]
http://i.imgur.com/LoHlGdu.gifv
