### ISSUE TITLE
Garrys mod is a virus??????

### ISSUE THREAD

**Issue by SNEAKYNINJA91O** [Facepunch/garrysmod-issues#2244]
i was going on garrys mod and then it said it was a virus any help????

**Comment by robotboy655** [comment]
Free anti virus software are known to cause false-positives on the game.
Either get a proper paid anti virus, or add the game folder to exceptions and report the file as false positive.

You can scan the offending file via http://virustotal.com for a proof that it is your anti virus malfunctioning, and not the game being a virus.
