### ISSUE TITLE
notification.AddProgress(uid, text) doesn't handle multiline properly

### ISSUE THREAD

**Issue by maritaria** [Facepunch/garrysmod-issues#2245]
Showing the bug:
```lua
local text = "Server has received a software update\nUse !svn for more information";
local index = {};
notification.AddProgress(index, text);
timer.Simple(10, function()
	notification.Kill(index);
end);
```
Output:
![Example of the issue](http://i.imgur.com/AZcssQQ.png)
Doesn't create 2 notifications, I just ran it twice before making the screenshot

How to fix the [function]
(https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/lua/includes/modules/notification.lua#L179) causing the bug:
```lua
function PANEL:SizeToContents()

	self.Label:SizeToContents()
	
	local width = self.Label:GetWide()
	
	if ( IsValid( self.Image ) ) then
	
		width = width + 32 + 8
	
	end
	
	width = width + 20
	self:SetWidth( width )
	
	local labelHeight = self.Label:GetTall()
	self:SetHeight( labelHeight + 6 )
	
	self:InvalidateLayout()

end

```

**Comment by mooshbeef** [comment]
PS: I assumed that the 32 in self:SetHeight was the height of the label, but this might need adjusting if it's not.

**Comment by robotboy655** [comment]
http://i.imgur.com/kfYdS3S.png

https://github.com/garrynewman/garrysmod/commit/a58db44c48fa1b69538a8effe371eae8000cc9f8
