### ISSUE TITLE
Light Tool endlessly creates new entities and crashes the game

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-issues#2248]
**When the Light Tool is equipped, it will continuously create** (and then remove?) **new prop_physics entities every think, and if the game is left paused it will eventually crash to desktop with a "no free edicts" error message.**

Put this code:
`hook.Add( "OnEntityCreated", "test", function( ent ) print( ent ) end )`
into lua/autorun, start a new game in Sandbox, equip the light tool, and check the console.

It will look like this:
![screen shot 2015-09-23 at 12 36 51 pm](https://cloud.githubusercontent.com/assets/5619290/10051945/1a5c0774-61f2-11e5-95a4-d1731a1dbf17.png)
And it will continue to spam with more and more entities with higher and higher indexes until the game crashes with:
![screen shot 2015-09-23 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/5619290/10051993/666373dc-61f2-11e5-9a3d-9e7da604c9b0.png)

**This was tested on a clean, addon-free GMod installation in both OS X and Windows.**

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/47da51f5b74fba393336fc6b0cf900578fbe4910
