### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Piehthyte** [Facepunch/garrysmod-issues#2249]
After the new update I noticed a memory leak in my game. It tends to crash itself.

Here is the crash report if you need it at all

https://dl.dropboxusercontent.com/s/yjyk4k48ocp7inj/hl2_150913_crash_2015_9_24T22_36_11C0.mdmp?dl=0

**Comment by robotboy655** [comment]
The fact that the game crashes doesn't mean it's a memory leak.

**Comment by Piehthyte** [comment]
That its sucking up all my memory whilst I go onto a server does raise some good questions. Also the latest update did some fixes to how the memory is handled.

**Comment by Piehthyte** [comment]
Just an update. It seemed to either be an issue with Windows 10 or just my installation. Please note that I did reinstall my Garry's Mod multiple times in attempt to remedy the issue, none of which fixed it until I downgraded back to Windows 8.1.
