### ISSUE TITLE
std::logic_error when starting DS on Debian 7/8/ CentOS 7x64 with Workshop

### ISSUE THREAD

**Issue by andregomesdepaiva** [Facepunch/garrysmod-issues#2251]
Same issue as this old FP thread: https://facepunch.com/showthread.php?t=1335192

I've created a new thread on https://facepunch.com/showthread.php?t=1486885&p=48764749#post48764749

The server won't start On Debian 7/8 x64 and CentOS 7 x64 if you set workshop usage (API Key and Collection ID)

Tried different collections, apikeys and a reboot but no lucky, i'm trying Ubuntu Server 12.04 x64

Log:

~Console initialized.
Couldn't load shader dll: game_shader_generic_garrysmod_srv.so
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load: /.steam/sdk32/libsteam.so
with error: /.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
Logging into anonymous gameserver account.
Fetching Workshop Addons..
Calling GetCollectionDetails
terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::_S_construct null not valid
./srcds_run: line 372: 10008 Aborted $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Thu Sep 24 05:32:01 BRT 2015: Server restart in 10 seconds

Works fine without workshop

**Comment by robotboy655** [comment]
Closing as workshop system has been remade completely since this report.
