### ISSUE TITLE
ERROR: failed to create vertex decl for vertex format 0x00050403!

### ISSUE THREAD

**Issue by braddevans** [Facepunch/garrysmod-issues#2253]
ERROR: failed to create vertex decl for vertex format 0x00050403! You'll probably see messed-up mesh rendering - to diagnose, build shaderapidx9.dll in debug.

system info: https://www.dropbox.com/s/m21g9icrx0m3dh9/DxDiag.docx?dl=0

**Comment by robotboy655** [comment]
Your PC and video card barely meets the minimum requirements.

**Comment by braddevans** [comment]
it was working properly before i got a new operating system

**Comment by robotboy655** [comment]
New operating system? From what? Windows XP? You have 1 GB ram, which is less than the minimum requirement, and you got 
```Display Memory: 250 MB
Dedicated Memory: 0 MB```
Which is not enough to play GMod.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/10135123/fe133744-65f3-11e5-9c28-6cc19061bf88.png)

**Comment by braddevans** [comment]
it worked on windows 7 starter

**Comment by braddevans** [comment]
i have at least got 200 hours playing gmod before the new os :+1:
