### ISSUE TITLE
Garry's Mod Fists

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2254]
In multiplayer sometimes if you switch to fists and back, then every Weapon is invisible till you change back to Fists.

**Comment by robotboy655** [comment]
Pretty sure its either a fucked up gamemode or you are running old/edited version of the thing.

"sometimes" is not helpful either.

**Comment by deinemudda32** [comment]
Happens on DarkRP and Sandbox.
Even only if the server is lagging.
The issue is very popular, so you should know what I mean.

**Comment by robotboy655** [comment]
Old old outdated Sandbox and DarkRP servers that use the GMod fists are affected. I know what you are talking about, and it was fixed some time ago, normal fists SWEP no longer uses any material hacks.

**Comment by deinemudda32** [comment]
Actually we are using the updated fists already.

**Comment by robotboy655** [comment]
I don't think so. Unless you can provide a vanilla reproduce case, which you can't.

DarkRP doesn't use normal GMod fists as far as I know.

**Comment by deinemudda32** [comment]
Yea I am stupid. Didnt saw you removed the PreDraw Hook.
Anyways thanks for answering my dumb intentions.

**Comment by robotboy655** [comment]
As per usual.
