### ISSUE TITLE
Saves creating bugged duplicates of effects

### ISSUE THREAD

**Issue by PureSoul-Luxx** [Facepunch/garrysmod-issues#2255]
(Singleplayer) - Sorry my english...
-----------------------------------------------
I placed a purple colored skydome effect on the skybox of bigcity but, the next day when I came to play again it had it's original color. After looking more closely, there was another skydome at the same place, without the green circle, unable to be deleted.

Then I tried these steps to prove it: load the game without effects; spawn 2 or more effects; change their colour; save & disconect; play singleplayer and there you go... anoying ghosts.

I found that another user got the same problem, check this: http://steamcommunity.com/app/4000/discussions/1/558754260285102466/
Windows 7 ultimate - Service pack 1
-----------------------------------------------

Hope this could be fixed relatively soon.
Looking foward for your answer; Another random dude/girl from le interwebs ~
![gm_bigcity0000](https://cloud.githubusercontent.com/assets/14947923/10260227/ba24b83c-6940-11e5-9404-abd21b6bafc4.jpg)
![gm_bigcity 2015-10-1 01-38-37](https://cloud.githubusercontent.com/assets/14947923/10260229/bd959086-6940-11e5-9e13-d57e0b6af02c.jpg)
The same map (yeah the saved does not look good cause it was not suposed to be an actual photo).

**Comment by robotboy655** [comment]
Cannot reproduce? I tried the following:
1) Start a new SP game on gm_construct
2) Spawning 2 ammo box effects
3) Coloring both a color a different color
4) Saving using gm_save
4.5) clearing the map and loading again
5) Disconnecting
6) Loading a new game and then loading the save
7) Disconnecting
8) Loading the save while not on a map from the "Saves" menu.

None of this caused any sort of anomalies, the effects loaded properly and did not create any "undeletable" props.

So, what's happening is either:
1) You are running outdated or pirated version of the game - try validating it on Steam
2) Some addon is messing up your save - uninstall the addon

**Comment by PureSoul-Luxx** [comment]
https://www.youtube.com/watch?v=AO-JOuQ6exM&feature=youtu.be

You answered fast, so I recorded the thing. Now it's clear what I mean... thanks for the supp :)

**Comment by robotboy655** [comment]
That is exactly what I did and nothing like that happened, which means it is a bug caused by one of your addons, and not Garry's Mod.

The second time you disconnected there were a bunch of Lua errors too.

Try temporarily uninstalling ALL of your addons ( Workshop, and whatever you installed into your gmod folder ) and see if that fixes the problem.

The T-posed ragdolls are expected, so is cleanup options not working.

**Comment by PureSoul-Luxx** [comment]
Tried in construct and the same happened...  then I did it without addons. You were right. After checking addon by addon I found the problem:

Door STool

An actually useful tool but, if you have it enabled things like this will happen.
Thanks for everything !

**Comment by robotboy655** [comment]
My Half-Life 2 Tools addon has a door tool that is better in every way and does not cause this problem.

**Comment by PureSoul-Luxx** [comment]
Somehow, fixing the problem led me to invisible props of my addons, and spawning the unused in that map worked fine, while spawning the invisible ones (already in the save) don't. Strange...

Well, quitting the game solved that. Now, where can I find your addon?
