### ISSUE TITLE
Corpses dispearing

### ISSUE THREAD

**Issue by TeddyMartin** [Facepunch/garrysmod-issues#2256]
So when KeepCorpses is set off, when npcs die they disspear in only 30 seconds or less for some reason. Sometimes they disspear immedietley when i kill them. Same thing as when i knock a headcrab off a zombie. Sometimes its only there for 10 seconds and sometimes it dispeares immedietley so it looks like no headcrab drops!! Please fix this! half-life 2 doesnt do this!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
