### ISSUE TITLE
sql.SQLStr doesn't escape backslash

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2257]
print(sql.SQLStr("Hello world\\"))//The double backslash translates into a single one during run-time
> 'Hello world\'
I would expect this to be scaped into \\ (in lua: "\\\\")

I found this because some stupid user put a backslash at the end of his name, and a chat logging addon I have can't log anything because the backslash at the end of his name escapes the quote the SQLStr function puts around his name and 'corrupts' the SQL query.

**Comment by wiox** [comment]
This is expected behaviour for SQLite.

**Comment by mooshbeef** [comment]
I'm not... but someone else is :P

**Comment by wiox** [comment]
In that case, he's a bad boy. This really isn't an issue with sql.SQLStr.
