### ISSUE TITLE
ACT_HL2MP_JUMP enum has no matching sequence

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2259]
Inherited from HL2: DM; don't know if this is a GMod issue or Source issue.

**Comment by robotboy655** [comment]
It is intended sort of. HL2:DM doesn't have a "normal" holdtype jump animation, and so does GMod.

**Comment by robotboy655** [comment]
You could argue why don't I add it, but I am no animation expert.

**Comment by Kefta** [comment]
Doesn't really need one if HL2: DM doesn't; the SLAM jump works for all intensive purposes. Just odd that the enum exists

**Comment by robotboy655** [comment]
The Enum is still used by many things.
