### ISSUE TITLE
Reloading in thirdperson resets FOV to first person while still drawing the local player

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2260]
Can be fixed by going into first person and back out again

**Comment by robotboy655** [comment]
Sounds a lot like a problem with either your 3rd person code or the SWEP base. I know my SWEPs on purpose reset the FOV to 0 when reloading, besides, SetFOV is not the proper way of setting permanent FOV, CalcVIew's FOV return value is.

**Comment by Kefta** [comment]
@robotboy655 I am talking about the default thirdperson ConCommand and reloading the game/typing the reload ConCommand, not reloading a weapon.

**Comment by robotboy655** [comment]
First of all, these things should be mentioned, secondly, why do you even care about it, isn't it a cheat command in multiplayer anyway?

**Comment by Kefta** [comment]
Yes, which I have enabled for multiplayer thirdperson animation testing

**Comment by Jvs34** [comment]
If you can replicate this bug with a Lua version of thirdperson that'd be lovely, otherwise stop, thirdperson is a really glitchy command and it even fucks up with weapon prediction.
