### ISSUE TITLE
ACT_HL2MP_SWIM undefined

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2262]
> print(Entity(1):GetSequenceActivityName( Entity(1):SelectWeightedSequence( ACT_HL2MP_IDLE + 9 ) ))...
ACT_HL2MP_SWIM

> print( ACT_HL2MP_SWIM )...
nil

Doesn't seem to carry from the animation file to a defined enum.

**Comment by robotboy655** [comment]
ACTs are not loaded from any files, they are hardcoded

**Comment by robotboy655** [comment]
It seems it was commented out for some reason.

**Comment by Kefta** [comment]
Works fine; it's even used in the normal HoldType. Also. ACT_HL2MP_SWIM_IDLE is not defined, but works

**Comment by robotboy655** [comment]
Are you sure it's ```ACT_HL2MP_SWIM_IDLE``` and NOT ```ACT_HL2MP_IDLE_SWIM```?

**Comment by Kefta** [comment]
@robotboy655 https://github.com/robotboy655/gmod-animations/blob/master/gm_base_m.qci#L12
