### ISSUE TITLE
SetNWVarProxy callbacks are not being called

### ISSUE THREAD

**Issue by maritaria** [Facepunch/garrysmod-issues#2263]
http://wiki.garrysmod.com/page/Entity/SetNWVarProxy

``` lua
--After connecting, run in console:
lua_run Entity(1):SetNWVarProxy("Test", print)
lua_run Entity(1):SetNWString("Test", "asdf") --Nothing happens
lua_run Entity(1):GetNWString("Test") --prints asdf
```

Broken for both client and server side

**Comment by mooshbeef** [comment]
Also http://wiki.garrysmod.com/page/Entity/GetNWVarTable doesn't exist

**Comment by robotboy655** [comment]
They are only available with the "new" NWvars, that are not in the game right now, because @UnderscoreKilburn can't be bothered to finish them.

**Comment by mooshbeef** [comment]
If he can just call the EntityNetworkedVarChanged hook then I think it'll work for now

**Comment by Acidic9** [comment]
Any update on this or is EntityNetworkedVarChanged still a dead function?

**Comment by Kefta** [comment]
Just use NW2.

**Comment by Acidic9** [comment]
Any example you could provide?

**Comment by Acidic9** [comment]
http://wiki.garrysmod.com/page/Entity/SetNWVarProxy

This seems to be the new method.

**Comment by Kefta** [comment]
Your NW proxy will be called if you use NW2 functions. Etc Entity:SetNW2String ()

**Comment by Acidic9** [comment]
I believe it is Entity:SetNWString() (No 2 in the function name)

**Comment by Kefta** [comment]
I did not make a typo.

**Comment by Acidic9** [comment]
http://wiki.garrysmod.com/page/Special:Search?search=SetNW2String&fulltext=Search

**Comment by Kefta** [comment]
They are not documented. You can still use them in-game, though.

**Comment by Acidic9** [comment]
Oh yes you are right, that is so string. Should I be using NW2 rather than the regular NW?

**Comment by Kefta** [comment]
They still have a few issues (look in the "New NWVars" milestone) but are more efficient overall.

**Comment by Bo98** [comment]
Just to be clear, be aware that the methods are named "NW2" just so people can test them prior to them replacing the original NWVar methods. When that happens, the NW2 methods will probably be removed, so you will need to update your scripts if that happens.

**Comment by Acidic9** [comment]
Okay thank you for that. I'll continue to use the current NW functions for now.

**Comment by Kefta** [comment]
@Bo98 1.5 years later, still waiting 😕

**Comment by Bo98** [comment]
Yeah, it does feel abandoned at this stage.

**Comment by maritaria** [comment]
Didnt expect this to ever pop up again; way back when, I ended up making a piece of code that checks for changes in the `Think` callback.

**Comment by robotboy655** [comment]
Restored SetNWVarProxy for old/current NWVars. The NW2Vars now have their NW2VarProxies, the hook still only applies to NW2Var
