### ISSUE TITLE
HTTP functions cause a stall when used in Shutdown hook

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#2264]
Bit of an unusual one, but typically the second time a server changelevel's, if you're using any HTTP functions in the ShutDown hook the server then stalls. It remains responsive to any pings but players are unable to go through the connecting & handshaking process and the server won't appear in the public list. 

Example code:
```lua
hook.Add("Shutdown", "Shutdowntest", function()
    http.Fetch( "http://google.com", function(a,b,c,d) end , function() end) 
    http.Post( "http://google.com", tblStuffToSend , function(a,b,c,d) end , function() end) 
end
````

Replace urls / add content where appropriate.

**Comment by zeroZshadow** [comment]
This seems to have been fixed, as I'm using HTTP inside shutdown just fine.

**Comment by robotboy655** [comment]
Well then let me know if that changes.
