### ISSUE TITLE
Update sv_skyname to support Single Player / Listen Servers

### ISSUE THREAD

**Issue by looterz** [Facepunch/garrysmod-issues#2265]
This is the only way we can support overriding a maps current skybox material with painted in these environments. I would suggest monitoring for when sv_skyname is changed and forcing a reload of the sky materials, much like what happens when a new client joins a dedicated server with a new sv_skyname set.

**Comment by robotboy655** [comment]
It already does.

**Comment by looterz** [comment]
Yep just found out what I was doing wrong, hook was called post init - my bad.
