### ISSUE TITLE
Garrys mod keeps crashing when loading into map

### ISSUE THREAD

**Issue by imahakr** [Facepunch/garrysmod-issues#2266]
I know it's caused by the WW2 Weapons mod shown here http://steamcommunity.com/sharedfiles/filedetails/?id=106550832
What's the problem? Are there any conflicting mods? I really want to use this mod but the game always crashes.

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_150913_crash_2015_10_11T10_59_38C0.mdmp

**Comment by robotboy655** [comment]
It's not a crash because of specific addon, it's a crash because of you hitting the 8192 .lua file limit. It will be fixed in the next update for singleplayer.
