### ISSUE TITLE
Chrome_IOThread (Awesomium) Crash on Mac when joining a server

### ISSUE THREAD

**Issue by ndrewh** [Facepunch/garrysmod-issues#2268]
Since the crash is in a chrome thread, this may be an Awesomium bug, but I am reporting here since there are quite a few unsymbolicated addresses in the crash report which could reveal a different story.

When joining a server (during the final stages of the loading process, ie. just after "Sending client data", when everything is rendered), Garry's mod crashes: 

http://pastebin.com/2uHAjYHb (see thread 20)

A "ULX MOTD" window is opened as soon as things are loaded in on this server, which could have something to do with it, but of course, it would be ideal if Garry's Mod did not crash.

Garrys mod 2015.9.13

**Comment by robotboy655** [comment]
I don't think it's an awesomium crash at all. It's just one of those OSX video memory crashes.

**Comment by ndrewh** [comment]
Very interesting! The issue seemed isolated to a specific server, which is odd since I've never had issues with this server before. For this reason I was hesitant to report, since it could be a server misconfiguration. But at the same time I believe whatever is going on here should not cause the entire game to crash.

As far as I can tell, the crashed thread in all the reports its logged is a ChromeIO thread. I'm interested, how did you make the conclusion that it's video memory related?

**Comment by ndrewh** [comment]
Can you provide any references to similar crashes or any steps I should take to resolve the issue?

Thanks!

**Comment by robotboy655** [comment]
Closing as stale.
