### ISSUE TITLE
gui.OpenURL appears to be broken

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-issues#2271]
Trying to open any valid URL results in nothing occurring. Examples:

```
lua_run_cl gui.OpenURL( "http://google.com" )
lua_run_cl gui.OpenURL( "http://www.google.com" )

lua_run_cl gui.OpenURL( "https://google.com" )
lua_run_cl gui.OpenURL( "https://www.google.com" )
```

Tested in Singleplayer on both main and dev branches and in Multiplayer on main (Windows 8.1).

As a result, [Player:ShowProfile()](http://wiki.garrysmod.com/page/Player/ShowProfile) also no longer does anything. Clicking user's avatars on the [base gamemode scoreboard](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/cl_scoreboard.lua#L22-L29) no longer opens up the user's profile on the Steam overlay.

**Comment by robotboy655** [comment]
You must have Steam Game Overlay enabled and operational. ( I.E. You can open it via Shift + Tab or w/e )

**Comment by Mista-Tea** [comment]
My overlay has always been enabled.

**Comment by robotboy655** [comment]
Yeah, all 4 predictably work for me, as there were no changes to the game that would suddenly make it not work.

**Comment by Mista-Tea** [comment]
Thank you for at least looking in to this, Robotboy.

I still haven't resolved the issue on my end, unfortunately. I will try a different Steam account to see if the settings are causing it (seeing as I haven't changed any of them in months). I will also test it on my laptop to see what the results are. Hopefully I can just resolve this on my end.
