### ISSUE TITLE
env_soundscape_triggerable not restoring after using Clean Up Everything or load save.

### ISSUE THREAD

**Issue by Noctara** [Facepunch/garrysmod-issues#2272]
My map request using env_soundscape_triggerable, but if i pressed Clean Up Everything or load an save, the soundscapes will disappear. (After using ent_fire command i think the entity still exist, but not working.) Normal env_soundscape working fine. If map contain many env_soundscape and env_soundscape_triggerable, after Clean Up Everything or load save env_soundscape's still work, but _triggerable don't.

Sorry if my English is bad.

**Comment by robotboy655** [comment]
Should be fixed in the next update & soon on the Dev beta branch.
