### ISSUE TITLE
HL2 non-firebullets weapons ignore hitboxes outside of hull

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2273]
https://www.youtube.com/watch?v=85G2IyuJrxk

Happens with RPG laser and physgun as well. There also seems to be a bug with the name/health display not showing up in this case when there is another entity in the background.

Should be fixable by just applying a ClipRayToCollideable/Entity trace.

**Comment by robotboy655** [comment]
I can confirm the "non world entity behind player hitboxes outside of the hull" problem on both, FireBullets and util.TraceLine, but I don't think I will be looking into Crossbow/RPG stuff, it's barely a priority.

**Comment by Kefta** [comment]
I guess this is only intended to hit hulls and not hitboxes
