### ISSUE TITLE
Disabled addons should not download automatically

### ISSUE THREAD

**Issue by L1Q** [Facepunch/garrysmod-issues#2276]
When I do a fresh install of garry's mod, I would like to run actually fresh and clean game and I don't like to see a tedious process of all my ~70 addons being downloaded at the firt run.
I wish all addons installed automatically via steam (with garrysmod), so when steam says it has installed my game, it is complete now and ready to launch with all my subscriptions enabled, *just like in Skyrim!*  
If it does not work this way, why do I have to download all the stuff I actually disabled?  

P.S: I would not write this text if It didn't take so long for those addons to download. Yeah, I know It's my fault that I've subscribed to all of them, but you get my point.

**Comment by robotboy655** [comment]
In Dev now, you can use -noworkshop to disable workshop addons in singleplayer completely.

The Skyrim-like behavior should be enabled when we switch to ISteamUGC.
