### ISSUE TITLE
ACT_VM_HOLSTER does not reset the viewmodel

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2278]
Running the holster anim does not reset the viewmodel to the new weapon

**Comment by robotboy655** [comment]
What do you mean "it does not reset the video model to the new position"?
What makes you think it should reset anything at all?

**Comment by Kefta** [comment]
No, it doesn't change the ViewModel model. If you switch weapons, let's say pistol to SMG and there's a holster Anim on the pistol, the pistol will lower, then instantly raise back up with the SMG having a pistol for the viewmodel instad

**Comment by robotboy655** [comment]
I don't think it's supposed to reset anything. Playing any other animation after the weapon is switched will give the same result.
I am assuming when the animation is played from weapon object, it sets the view model of the weapon object before playing the animation.

**Comment by Kefta** [comment]
I fixed this by manually resetting the viewmodel now that SetWeaponModel can accept NULL. Thanks
