### ISSUE TITLE
FindMetaTable ignores the __metatable key

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2280]
I did not see this on the Lua 5.2/3 versioning list, so this should be default implementation for FindMetaTable.

**Comment by aStonedPenguin** [comment]
Why does FindMetaTable even exist when lua already has getmetatable?

**Comment by Kefta** [comment]
set/getmetatable are just shorthands for debug.getregistry() anyway; FindMetaTable is totally useless it seems, but still abundant among the base code

**Comment by willox** [comment]
Why would you want FindMetaTable to react to the __metatable metaproperty?

**Comment by Kefta** [comment]
But how is FindMetaTable any different than getmetatable? And why would I not want it to react to __metatable? That's against default Lua behaviour; there's no reason for the metatable key to even exist if it doesn't redirect search calls

**Comment by willox** [comment]
__metatable is a metamethod. Metamethods apply to userdata or to tables, not to strings?

**Comment by thegrb93** [comment]
Yeah __metatable is used in starfall to hide the table containing all the implementation functions. Luckily debug library is used instead of FindMetaTable or people might get full access to the server lua.

**Comment by willox** [comment]
debug.getmetatable completely ignores __metatable, though?

**Comment by thegrb93** [comment]
Oh i mixed them up. it uses getmetatable()

**Comment by willox** [comment]
disaster averted

**Comment by immibis** [comment]
FindMetaTable and getmetatable do different things anyway. getmetatable gives you the metatable for a particular object; FindMetaTable gives you a "well-known metatable" given its name.

That is, if `p` is a player, then `getmetatable(p)` returns the metatable shared by all players, and so does `FindMetaTable("Player")`. `FindMetaTable(p)` would fail, and `getmetatable("Player")` would return the metatable for strings.

**Comment by Kefta** [comment]
@immibis Then the only difference it seems is the method of retrieval. Why should they behave differently in how they interpret keys?

Also, @willox, __metatable is listed under metamethods on the event page: http://lua-users.org/wiki/MetatableEvents

**Comment by thegrb93** [comment]
Ah ok, so FindMetaTable just retrieves the metatable from _R

**Comment by Kefta** [comment]
@thegrb93 I believe setmetatable also retrieves from the registry, but through type-matching.

**Comment by immibis** [comment]
@Kefta What use would it be if `FindMetaTable` *did* return the value of `__metatable`?

**Comment by willox** [comment]
The registry has nothing to do with metatables! Garry's Mod just happens to store things there.

__metatable exists to modify the behavior of setmetatable and getmetatable. Adding new functionality to this isn't "the Lua way". It's just asking for complicated nonsense to be added to an already too complicated API.

This is similar to requesting that math.cos be able to take Vector and Amgle arguments, it's only reason of existence is so that you can request crap.

**Comment by immibis** [comment]
> Oh Rubat, we're still waiting for table.Exists.

@willox http://wiki.garrysmod.com/page/table/HasValue ?
