### ISSUE TITLE
Entity:SetWeaponModel should have its weapon argument as optional.

### ISSUE THREAD

**Issue by Jvs34** [Facepunch/garrysmod-issues#2282]
This function is used to associate a viewmodel with a weapon when you deploy the weapon, but you should also be able to set the weapon argument to NULL ( or nil, whatever ) once you stop using the viewmodel.

That is the correct way that is done internally, otherwise the viewmodel will keep showing up until the weapon is destroyed.

**Comment by robotboy655** [comment]
Done
