### ISSUE TITLE
Crouching while noclipping

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2283]
Should it be that way, that you can dodge while noclipping?
Its kinda weird and such useless.

**Comment by robotboy655** [comment]
Should it not be that way? Is there any reason to get rid of it?

Please stop posting worthless ideas. It is this way because it is this way in all Source Engine games, and it is useful to move slower while in noclip. ( Especially when building )

**Comment by deinemudda32** [comment]
But why has your body to move down a half player hull?
It just looks awful.

And its not worthless, its the detail which always counts.

**Comment by robotboy655** [comment]
```It is this way because it is this way in all Source Engine games```
