### ISSUE TITLE
NULL Vehicle will return true to IsValid and crash the server if GetDriver is used.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2285]
Here's the code that causes the crash

```
local entmeta = FindMetaTable("Entity")
local vehiclemeta = FindMetaTable("Vehicle")

function vehiclemeta:SetPos(v)
	print(v,self:IsValid(),self)
	if self:IsValid() and self:GetDriver():IsValid() then
		self:GetDriver():ExitVehicle()
	end
	entmeta.SetPos(self, v)
end
```
This is what it prints
443.184082 71.708061 -12287.968750	true	Vehicle [NULL]

This happens whenever I spawn a prop_vehicle_jeep or prop_vehicle_airboat

**Comment by robotboy655** [comment]
Vehicles do not have a custom IsValid method, so I am not surprised it returns true. I will look into the crash problem.

**Comment by robotboy655** [comment]
Fixed.
