### ISSUE TITLE
FPS is low when joining a new server.

### ISSUE THREAD

**Issue by MrGrim2323** [Facepunch/garrysmod-issues#2288]
So an example, which happens to me many times.

1- Im on a server, then the server decides to change the map (Z Survival), (60+ FPS)
2- Map changes and everything is ok, but the FPS is not. it drops to 2 or 10, which normally it is like 50-60.

Not only Survival, even if I decided to change the server, the only way to fix it is to restart Gmod every time I want to join a new server, which takes a long process.

I really appreciate any help.

**Comment by Noiwex** [comment]
Try disabling antialiasing, it helped me.

**Comment by robotboy655** [comment]
Most likely caused by https://github.com/Facepunch/garrysmod-issues/issues/2650
