### ISSUE TITLE
ENTITY:SetNoDraw( true )

### ISSUE THREAD

**Issue by MalboroGmod** [Facepunch/garrysmod-issues#2289]
When I take a props with the PhysGun and I set ENTITY:SetNoDraw( true ) the game/server crash.
When I create a VGUI "SpawnIcon" with the model of a ENTITY with SetNoDraw( true ) the game/server crash.

**Comment by robotboy655** [comment]
Just tested this with a prop_physics and ```lua_run Entity(1):GetEyeTrace().Entity:SetNoDraw( true )``` and it doesn't crash.

**Comment by MalboroGmod** [comment]
When I take a props with the PHYSGUN

**Comment by MalboroGmod** [comment]
I can make you a video if you whant

**Comment by MalboroGmod** [comment]
https://youtu.be/-DaHeLdtbmk

My Code:

	ent:SetPos(Vector(0,0,0))
	ent:SetNoDraw(true)
	ent:SetCollisionGroup(COLLISION_GROUP_WORLD)

**Comment by MalboroGmod** [comment]
I fixed it with this:

	ent:PhysicsDestroy()
	ent:SetNoDraw( true )
	ent:SetPos( Vector( 0, 0, 0 ) )
	ent:SetCollisionGroup( COLLISION_GROUP_WORLD )
