### ISSUE TITLE
Game Crashes upon attempting to load saves with no error message being displayed

### ISSUE THREAD

**Issue by Jericoshost** [Facepunch/garrysmod-issues#2290]
Note: When I was first directed to the site the link bypassed the read-before-posting page.
I'm not sure it is just a map add-on problem as it is affecting many different maps at the same time, so it may be a system problem so I am leaving this up.

So far I have found that some maps have stopped working upon load and re-load.
You can start the map up easily in "Start a new game" and do whatever you want and then save.

But when you try to load the map it begins the process normally and crashes right after "Loading Resources" should finish but before the next phase.

It doesn't seem to be mod/add-on related (I deleted all of mine before re-trying the maps with fresh saves made post deleting the add-ons)

I have a feeling that it is somehow map specific but I don't know how (No error message pops up)
[Crash.txt](https://github.com/Facepunch/garrysmod-issues/files/36081/Crash.txt)

.
A few maps that are having this problem are: Gm-Shambles (Day and night versions) and Aftermath Night and Day (A Pack with two maps). There are a few more but I can't remember their names off the top of my head, and Probably more I don't know about.

Other Maps (Examples are: Decay and Silent hill (One of the versions)) Work just fine with being loaded and re-loaded.

And I am using the Steam Workshop and Garry's Mod through steam.
I am using the version from 2015.09.13 (That is what it says in the top right corner of the menu)
It is really disappointing because I really wanted to use the GM_Shambles map.

**Comment by Jericoshost** [comment]
[Crash.txt](https://github.com/Facepunch/garrysmod-issues/files/36082/Crash.txt)
I copied the text that looked important from the MDMP file and put it here because the site doesn't support MDMP files.

**Comment by Jericoshost** [comment]
I looked deeper and it seems it is related to cube maps somehow? Is there a way to fix the cube map skybox thing?

**Comment by robotboy655** [comment]
Fixed
