### ISSUE TITLE
Server crashes shortly after load (.mdmps provided)

### ISSUE THREAD

**Issue by kurozael** [Facepunch/garrysmod-issues#2291]
If you could let me know why the crashes are happening so I can tell if it's part of the gamemode or what addon might be causing it that'd be great.

http://www.filedropper.com/srcds1678491crash20151117t155820c0

http://www.filedropper.com/srcds1678491crash20151117t161651c0

**Comment by robotboy655** [comment]
Both crashes occurred in gmsv_cloudauthx_15_win32.dll, one, I am assuming, from PCalling something in CheckPassword, the other one only has lj_meta_tget in call stack, and then the module again.

**Comment by kurozael** [comment]
Very strange indeed, thanks @robotboy655
