### ISSUE TITLE
Fragmented packet nonsense

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#2292]
Read:
https://facepunch.com/showthread.php?t=1485127&p=49130754&viewfull=1#post49130754
https://facepunch.com/showthread.php?t=1485127&p=49133492&viewfull=1#post49133492

I guess we should continue this discussion here instead. I can provide a few more complete logs from clients trying to join if needed.

**Comment by robotboy655** [comment]
#2099
