### ISSUE TITLE
Font anti-aliasing breaks font

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#2293]
It seems like the antialiasing option of surface.CreateFont breaks some letters in certain fonts.
![ss 2015-11-21 at 04 12 22](https://cloud.githubusercontent.com/assets/1258762/11316419/aaf2902c-9006-11e5-9556-aa8a2b1e87c8.png)
Open Sans (left: anti-aliased, right no anti-aliasing) seems to break like that for any font sizes smaller than 18. This seems to happen to almost all the Google fonts I tried.

This is what it should look like:
![ss 2015-11-21 at 04 29 56](https://cloud.githubusercontent.com/assets/1258762/11316464/b069c212-9008-11e5-8e7d-217b2554f648.png)

Code used to create that font:

``` lua
surface.CreateFont("OpenSans16", {
    font="Open Sans",
    size=16,
    weight=500,
    antialias=true
})
```

Link to the font:
https://www.google.com/fonts/specimen/Open+Sans

**Comment by Bo98** [comment]
Which OS?

**Comment by syl0r** [comment]
Windows, but I'm pretty sure this happens on other OS as well

**Comment by willox** [comment]
Fixed for Windows, It'll be on the dev branch later today.

**Comment by willox** [comment]
OSX doesn't seem to have this issue
