### ISSUE TITLE
Some fonts of the default font list have additive rendering

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-issues#2294]
I found the root cause for a problem I have been having for a while #2019
It turns out that *some* fonts are set to additive rendering by default (this didn't use to be the case).

From the default font list:
- Trebuchet24
- HudHintTextSmall
- HudHintTextLarge
- CenterPrintText
- HL2MPTypeDeath

This issue also interferes with derma controls like the comboboxes and is very very annoying.

**Comment by mooshbeef** [comment]
PS: I figured this out by drawing a black text over a white background and control the font using a convar.

**Comment by robotboy655** [comment]
This is not a bug, this was the case forever, this is intended by the engine.
