### ISSUE TITLE
PLAYER:GetEyeTrace() doesn't take into account LagCompensation

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-issues#2295]
It seems like PLAYER:GetEyeTrace() only traces up to once per tick and then caches the result for the rest of that tick. This means that depending on whether the first call to GetEyeTrace in a tick is lag compensated, the trace that is cached is gonna be different.

```LUA
ply:LagCompensation(true)
local eyeTrace = ply:GetEyeTrace();
ply:LagCompensation(false)
```
This example leads to two cases, either the lag compensation does nothing because the result was already cached, or it makes the GetEyeTrace() function return a lag compensated trace for every other call for the rest of the tick.

**Comment by robotboy655** [comment]
Yes it does indeed cache the result, as per its design.
https://github.com/garrynewman/garrysmod/blob/3e138636eb1b0ad6ed785dedf350020755cff5f1/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L175

I guess it should be mentioned on the wiki.

**Comment by Jvs34** [comment]
As a side note, I would suggest doing the trace yourself, so you can fine-tune the mask and filter yourself instead of the default "anything goes" of GetEyeTrace(), especially if this code is for a melee weapon.

**Comment by syl0r** [comment]
I think caching is a really good thing since tracing several times per tick might be really expensive. That's why I think that GetEyeTrace should cache a lag compensated trace as well as a normal one (as soon as a lag compensated one is needed). This will not impact performance and it will result in exactly the behaviour one would expect.

**Comment by ZehM4tt** [comment]
Just do it yourself by calling util.GetPlayerTrace

**Comment by syl0r** [comment]
I know I can achieve this functionality by myself. The thing is, this should clearly be part of the function that already exists and most people use.

**Comment by ZehM4tt** [comment]
Then how about you implement it, test it, once everything works you could just easily create a Pull Request instead of being a begger.

**Comment by syl0r** [comment]
Show me the function that allows me to check whether or not the player is currently lag compensated.
Unfortunately there isn't one or I would've made one.

**Comment by thegrb93** [comment]
@ZehM4tt what part of "this should clearly be part of the function that already exists and most people use." didn't you understand?

@syl0r doesn't this return if something is compensated? http://wiki.garrysmod.com/page/Entity/IsLagCompensated

**Comment by syl0r** [comment]
As far as I know that function just returns if an entity is being affected by lag compensation.
See:
http://wiki.garrysmod.com/page/Entity/SetLagCompensated

**Comment by Jvs34** [comment]
This is meaningless, there's no performance improvement whatsoever in doing what you asked, just do the trace manually and call lag compensation yourself.

GetEyeTrace() is an utility function that simply returns the unaltered player's trace, that's it.
We already have enough spoonfeeding wrappers as it is, let's not change stuff just for the sake of it please.

**Comment by Bo98** [comment]
garrynewman/garrysmod@9a0cffc
