### ISSUE TITLE
Windowed mode mouse moving by itself

### ISSUE THREAD

**Issue by auskfc** [Facepunch/garrysmod-issues#2298]
When I window Garry's Mod the mouse moves by itself. I have done a hard wipe of Gmod and reinstalled it though this problem still occurs.

**Comment by auskfc** [comment]
Why did you close it?

**Comment by Kefta** [comment]
It must be a computer issue; I can't replicate it.

**Comment by robotboy655** [comment]
Pretty sure this is when in TTT the round ends or starts and the vgui appears, so it actually may be a real issue.

**Comment by robotboy655** [comment]
Will be fixed.

**Comment by zerfgog** [comment]
What was the issue?

**Comment by robotboy655** [comment]
SetCursorPos works when the game is not focused/alt tabbed out.

**Comment by auskfc** [comment]
It is fine now thanks
