### ISSUE TITLE
My Garry's Mod wont stop updating for some reason... need help

### ISSUE THREAD

**Issue by JohnYee** [Facepunch/garrysmod-issues#2302]
So it say on the download section, evrthing is 0bytes/0bytes/no time remaining at all here a link to somebody that want to see what happening 
![wtf](https://cloud.githubusercontent.com/assets/16151171/11589169/3d9f7eca-9ac1-11e5-9cba-ae466b68cbf9.png)

and i also tried reinstalled gmod and removing the "appworkshop_4000.acf" but its only temporaily....bcz after i download a new addon the bug back again.

Please help... ;-; and sorry about my english

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

You can pretty much ignore this, it's nothing.
