### ISSUE TITLE
Gmod has post processing effects for bug.

### ISSUE THREAD

**Issue by DrTufo** [Facepunch/garrysmod-issues#2303]
When I load gmod the menu goes super bright for some reason and the game changes brightness or shadeness when im looking around or walking also i didn't change any settings at all. It happens then goes away then happens again what do I do? This is the one that is normal http://steamcommunity.com/sharedfiles/filedetails/?id=500612815 and this is the one that has the bug http://steamcommunity.com/sharedfiles/filedetails/?id=500612709

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
