### ISSUE TITLE
Day Of Defeat View Model Missing!

### ISSUE THREAD

**Issue by Ghost-Robotics** [Facepunch/garrysmod-issues#2305]
It is simple whenever I select the Day Of Defeat Source Player Models, the player model hands are missing! It does not even go to the default one they are just...one. Whenever I use it there's nothing holding my guns or anything. This goes for both the American soldier and the German soldier player models, and I have done what I believe is all I could do, tried different player models that all worked fine, unmounted then remounted the game, and even completely deleted and reinstalled day of defeat source and still nothing. It is funny because it was working before in previous version but not now. And I have tested it with add ons turned off and it still did not work.

**Comment by Kefta** [comment]
Works fine for me; it has nothing to do with DOD. Just delete your VPKs in your garrysmod folder and validate your files.
