### ISSUE TITLE
Nextbot - Crash when using path:GetCurrentGoal() after path:Update() in the same tick.

### ISSUE THREAD

**Issue by MyHatStinks** [Facepunch/garrysmod-issues#2306]
I'm using the development branch, version 2015.12.07.

Easily reproduced.
Line 280 in the [nextbot base code](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua#L280) after path:Update(), add path:GetCurrentGoal(). Spawn the test npc and crash to desktop. Issue does not occur if you add path:GetCurrentGoal() on line 278, before path:Update().

**Comment by robotboy655** [comment]
Fixed, returns nil instead.
