### ISSUE TITLE
Shader issue

### ISSUE THREAD

**Issue by InFeCtedxZomBie** [Facepunch/garrysmod-issues#2307]
https://youtu.be/8q3ifdXwyfE No clue why...

**Comment by Jvs34** [comment]
Unfortunately that is not very helpful, it might be the addons of the server itself that do that.

**Comment by InFeCtedxZomBie** [comment]
it does that on all servers

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
