### ISSUE TITLE
cant start a map in Gmod

### ISSUE THREAD

**Issue by XV-javi** [Facepunch/garrysmod-issues#2311]
so this started happening some time ago and what happens is i dont know if its because i have a lot of addons i have like 350 or more addons but that have never been a problem until now i hope its not but what happends is that i enter the gmod and after does all the addon charging and everithing i enter the start a game thing and then i select a map to play by miself and then theres the charging screen and everithing normal BUT THEN BOOM when the charging finishes then the game close himself and with no notification of whats the problem it just F*CKING CLOSE HIMSELF AND I NEED HELP IM TIRED OF THIS GAME and no i dont think its my computer because in the internet page can you runnit i have seen that i can and i have seen all the properties i need to see and i can say for shoure that maybe its the mods that doesnt work because i have i think like 15 or more mods that give me an error whenever im going to play a game it have never been a proble becawse it was only like 5 but one day i looked on the workshop and everithing and i dounlowded a lot of mods and i didnt check i just whent away and one day i wanted to pley and boom the bug happened so if theres a way you can help me please help im really stresed for this and i reallly want to play gmod PLEASE!!!

**Comment by robotboy655** [comment]
Too many addons.

https://facepunch.com/forums/16
