### ISSUE TITLE
graphics bug

### ISSUE THREAD

**Issue by jellybaby1123** [Facepunch/garrysmod-issues#2312]
I have a bug that has been here since 3/12/15 update, where there is a solid line which cuts across my screen. this makes it very hard to play as you cannot see what you are doing.
![2015-12-10_00005](https://cloud.githubusercontent.com/assets/16246763/11728967/a94b6ac2-9f84-11e5-8985-703d8b736f60.jpg)
![2015-12-10_00003](https://cloud.githubusercontent.com/assets/16246763/11728972/b4c8b29c-9f84-11e5-8edb-ddc9d752b899.jpg)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/11729232/dfb2fcda-9f96-11e5-8a51-4e433f7b7dae.png)

What made you think asking for help with Rust here was a good idea?

**Comment by jellybaby1123** [comment]
@robotboy655 facepunch forums directed me here...

**Comment by robotboy655** [comment]
Link please.
