### ISSUE TITLE
When Awesomium is focused, you cannot open the console

### ISSUE THREAD

**Issue by BillyOnWiiUIn144p** [Facepunch/garrysmod-issues#2317]
When an Awesomium element (DHTML etc.) is "focused" (i.e. when you click on it), when opening the console, it seems to close it again immediately and then sometimes close the game UI. (or not seem to open it at all in the first place)

The console can be opened by pressing ESC -> Options -> Console key however, which could suggest some kind of "layering" issue.

I currently have my console binded to the default, ` / ~

Recreation:
1. Create a HTML panel in a DFrame
2. Click it, select some text or whatever
3. Try using your console key

Windows, US Keyboard layout, 2015.09.13

**Comment by robotboy655** [comment]
As far as I know you have to HOLD the key.

**Comment by BillyOnWiiUIn144p** [comment]
Oh wow. :v:
