### ISSUE TITLE
Maps not loading in dev brach 2015.14.12

### ISSUE THREAD

**Issue by Marcelievsky** [Facepunch/garrysmod-issues#2318]
Hello,

I noted the new update mentioned above, and when I try to load any maps (or load a save), the loading does not complete (infinite load screen). I have several maps and addons, and this is my first time sending issues, and I really appreciate if someone tell me if there's a crash.log or something to send.

Thanks

**Comment by willox** [comment]
There was an update to the dev branch about 2 minutes ago after I reported the same issue. Try now.

**Comment by Raffine52** [comment]
I Am having the Same Problem, Too.

Facepunch Logo Loading Is Fine, But then I load a Map and GMOD Will get stuck in the loading screen.
