### ISSUE TITLE
Game Crashes If Trying to Load a New Map or Disconnect While in Single Player

### ISSUE THREAD

**Issue by Raffine52** [Facepunch/garrysmod-issues#2321]
Hello, I got another Bug in GMOD after the Dec 15 2015 Patch that I Need to Report.

When you Try to Load a New Map or Disconnect while in Single Player, GMOD Will Crash.

**Comment by Jvs34** [comment]
I could replicate it after the third try, here's the crash dump.
https://dl.dropboxusercontent.com/s/pfgurajykbkl8db/hl2_151215_crash_2015_12_16T8_46_4C0.mdmp?dl=0

**Comment by robotboy655** [comment]
should be fixed in next dev update.
