### ISSUE TITLE
half life 2 ep: 2 effects errors

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2322]
I get this error if i Kill an antlion worker:
Attempted to create unknown particle system type "antlion_gib_02"!

This if i kill an antlion grub:
Attemped to precache unknown particle system "GrubBlood"!
Attempted to create unknown particle system type "GrubSquashBlood"!

If I kill an Antlion Guardian then it transforms on death to an normal antlion guard.

**Comment by DrVrej** [comment]
This happens with all particles, and its annoying as fuck

**Comment by deinemudda32** [comment]
I only encountered the issue with HL2 EP2 effects.

**Comment by robotboy655** [comment]
Will be fix'd

**Comment by kem008** [comment]
u will encounter other not just particle.
