### ISSUE TITLE
GMod won't load in OS X after the December update.

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-issues#2323]
After the December update, whenever I launch GMod in OS X, it will stay at the loading screen indefinitely and never go to the main menu. *(Rather than the normal loading screen, the screen that appears after launching GMod in OS X is nothing but blank white. This issue has been around for the past few months but I never reported it because the game always finished loading normally and went to the main menu.)* Now, after the most recent update, it just gets stuck at the blank white screen and never goes to the main menu.
I have done tests in both OS X and Windows and both the issue with the blank loading screen and the failure to actually finish loading are only present in OS X.

**Comment by Bo98** [comment]
@robotboy655 The Awesomium corrupt file I reported a few weeks back has returned:

```
dyld: Library not loaded: @executable_path/Awesomium
  Referenced from: /Users/boanderson/Library/Application Support/Steam/SteamApps/common/GarrysMod/bin/Awesomium.framework/Versions/A/awesomium_process
  Reason: no suitable image found.  Did find:
	/Users/boanderson/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/Awesomium: truncated mach-o error: segment __TEXT extends to 38498304 which is past end of file 33554432
```

Copying the file **.../SteamApps/common/GarrysMod/Awesomium.Framework/Versions/Current/Awesomium** to **.../SteamApps/common/GarrysMod/bin/Awesomium** fixes it. This isn't the first time it happened so I'm not sure what's happened on Facepunch's end.

**Comment by Bo98** [comment]
This should be fixed now as of the latest update.
