### ISSUE TITLE
(Mostly harmless) assertion failure on workshop addon download

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2324]
```
ASSERT ASSERT ASSERT
Message: m_pThread == NULL
Module:	
File:	../../../src/Bootil/Threads/Thread.cpp
Line:	56
Function:	~Thread
```

Happens twice whenever a Workshop addon finishes downloading.

Thought it would be worth reporting in case there is a bigger problem that this is causing (eg. memory leak).

**Comment by robotboy655** [comment]
OS?

**Comment by Bo98** [comment]
OS X.

**Comment by Bo98** [comment]
It doesn't appear in the console in case you were wondering. It's sent to stdout so I only saw it when I ran GMod from the command line.

**Comment by Revenge282** [comment]
Same error currently on Win10 x64

**Comment by TheFreeman193** [comment]
Can confirm this on dev branch 2016/01/14 on 64-bit Win7. Doesn't occur on base branch.

**Comment by Mista-Tea** [comment]
Happening to me on Win 8.1 x64 (dev branch). A workshop addon is trying to download automatically, causing my game to crash on startup.

![Dialog](https://i.gyazo.com/359faa21e5c7c4e220ece23cf2522b7d.png)

**Comment by willox** [comment]
We know the issue and it'll be fixed soon. No need for any more information.

**Comment by Mista-Tea** [comment]
Sorry, thanks for the update.

**Comment by willox** [comment]
:hammer:'d

**Comment by kem008** [comment]
There is already a Workshop issue created with the same problem (y)
