### ISSUE TITLE
OnEntityCreated will pass null entity when a vehicle spawned (serverside only)

### ISSUE THREAD

**Issue by ischmal** [Facepunch/garrysmod-issues#2325]
I have a Workshop addon that adds a variety of functionality to vehicles, after the December update it essentially stopped working entirely. I tracked down the culprit to the OnEntityCreated hook.

On the server, when the spawned entity is a vehicle, the entity fails IsValid( ent ) and a tostring( ent ) returns Vehicle [NULL].

I created an OnEntityCreated hook that prints the entity then outputs the IsValid result. I also added a .5 second timer to do the same thing. Vehicles do the following:

    Vehicle [NULL]
    Valid spawned ent: false
    After .5 seconds: Vehicle [14][prop_vehicle_jeep]

Which implies the entity becomes valid perhaps a tick after the hook is called. I only see this issue present with vehicle entities with the serverside hook. The clientside hook seems to work fine.

I have patched my addon by adding a .1 second simple timer inside the hook, but I would not be surprised if other addons or code have been adversely affected by this.

**Comment by syl0r** [comment]
I'm having the same issues, one of my libraries checks IsValid() before performing any operation on the entity and thus breaks if used before the vehicle is fully spawned.
This change also seems to break consistency between spawning vehicles and other entities:
```lua
local e = ents.Create("prop_physics")
local v = ents.Create("prop_vehicle_jeep")
print(IsValid(e), IsValid(v))
```
This prints true, false

**Comment by robotboy655** [comment]
Vehicle.IsValid was added to prevent crashes when trying to use a vehicle methods on an invalid vehicle. The unfortunate part a vehicle becomes valid only after Spawn() has been called on the entity. You can blame Valve for that.

**Comment by ischmal** [comment]
What would you recommend as a "best practice" solution? Creating a custom OnEntitySpawned hook by overriding ent.Spawn()?

Do you think vehicles should continue to even call OnEntityCreated considering the passed in variable is useless without a timer (and behaves differently on client and server)?

**Comment by thegrb93** [comment]
Why would ents.Create/OnEntitySpawned return an invalid vehicle anyway? I don't see why an IsValid is needed at that point.

**Comment by Jvs34** [comment]
Revert the change, but add checks to the vehicle functions for GetDrivableVehicle() to see if it's NULL, and add a function like Vehicle:IsFulllyInitialized or whatever you want to call it.

Then we can document the wiki to tell people to call the functions like GetDriver or whatever after that function returns true ( which is after spawn ).

**Comment by Jvs34** [comment]
I'm looking into this shit and I can understand why you did this change, this vehicle handling is pretty annoying.

**Comment by robotboy655** [comment]
@Jvs34 , Yeah, that is what I am thinking of doing, and I do agree, it is annoying.

**Comment by robotboy655** [comment]
In fact, all vehicle methods already have proper checks, so you can simply override Vehicle.IsValid to use Entity.IsValid for now and it should work fine.

**Comment by robotboy655** [comment]
Fixed in Dev
