### ISSUE TITLE
hl2.exe recognized as Malware by F-Secure

### ISSUE THREAD

**Issue by der-eismann** [Facepunch/garrysmod-issues#2326]
Hey everyone,

after today's update my F-Secure constantly tells me that the hl2.exe of Garry's Mod contains "Gen:Variant.Kazy.5494" malware:
https://www.f-secure.com/v-descs/other_w32_generic.shtml
F-Secure is also not the only one to detect Malware:
https://www.virustotal.com/de/file/4f089395d23ffdef2e9d2e92351a2109177d9276a14a1656edd18a5bd75024dc/analysis/

Did you catch something malicious? Or is this false alert?

**Comment by Bo98** [comment]
It's a false alert. Not sure if there's anything Facepunch can do but please do report it as a false positive to F-Secure if you can.
