### ISSUE TITLE
Broken...

### ISSUE THREAD

**Issue by N0VACRAW3R** [Facepunch/garrysmod-issues#2328]
Hello, I was wondering if someone could help me out, when I was loading Gmod it started out regularly but when it said finished, nothing happened. So I tabbed out seeing if that resolved the problem, (usually works for me) I tried clicking back on the game but it didn't open. So I tabbed out again to where it said desktop and everything else but it only showed "desktop" and my other opened tabs. This never happened since the recent update. I did literally everything but nothing worked. If anyone can help me i'd be more than grateful.

**Comment by Bo98** [comment]
Which OS?

**Comment by N0VACRAW3R** [comment]
pretty sure os x

**Comment by N0VACRAW3R** [comment]
im using a macbook air

**Comment by Bo98** [comment]
#2323

**Comment by N0VACRAW3R** [comment]
ty
