### ISSUE TITLE
December update broke -multirun

### ISSUE THREAD

**Issue by DerekSM** [Facepunch/garrysmod-issues#2335]
You can no longer use the -multirun command line parameter to open a second instance of garry's mod.

This was useful for developing as you could have two different players on your same machine test iron out bugs on a local server, rather than having to invite friends onto a multiplayer server to test out the bugs.

Adding -insecure as a server parameter should be able to allow this to happen (and yes i've already tested it, and no it doesn't work)

**Comment by Jvs34** [comment]
Can you try starting the server in lan mode ( sv_lan 1 ) and see if that also happens? If it works you might be able to use it as a workaround until this is fixed.

**Comment by DerekSM** [comment]
It was always sv_lan 1. sv_lan 0 will just have the message "Steam validation rejected.", while sv_lan 1 will get stuck on Connecting to server

**Comment by robotboy655** [comment]
Can you at least explain how it "does not work"?

**Comment by DerekSM** [comment]
Before this update you could join a local dedicated server with your main client and a separate instance of the same client on the same server. The other client would be given a different steamid (I think it was just STEAM_0:0:0). The server console would say duplicate steamid but you would still be able to join.

Post update you can still open the instance but you cannot join the same server as it will get stuck on connecting to server.

**Comment by BomBom123** [comment]
Seems the new steam auth checking on player connect to prevent SteamID spoofing has broke it.

**Comment by robotboy655** [comment]
Will be fixed.
