### ISSUE TITLE
Bugs on last update

### ISSUE THREAD

**Issue by comedinha** [Facepunch/garrysmod-issues#2337]
I know this is not the place over these problems but occurred in the last update garry's mod

The weapons that do spawn in ttt are in a much smaller amount there was some restriction to spawn items?

Sometimes the hud is completely clean, removing everything appeared. Without errors.
http://steamcommunity.com/id/comedinha/screenshot/645503094103315870
Not show default ttt hud

I also noticed problems in hitbox, before the errors occur but now have more often you shoot on the person, blood and not remove damage.

**Comment by deinemudda32** [comment]
The problem with the HUD is in Sandbox either.

**Comment by comedinha** [comment]
Yes, all bugs is a garry's mod bug, not gamemode bug

**Comment by robotboy655** [comment]
1 report per issue.
