### ISSUE TITLE
Prop spawn issue

### ISSUE THREAD

**Issue by comedinha** [Facepunch/garrysmod-issues#2338]
I know this is not the place over these problems but occurred in the last update garry's mod

The weapons that do spawn in ttt are in a much smaller amount there was some restriction to spawn items?

**Comment by robotboy655** [comment]
This is not a place for TTT bug reports or whatever.

**Comment by comedinha** [comment]
This not is a TTT bug, the bug give on latest gmod update

**Comment by robotboy655** [comment]
How is "The weapons that do spawn in ttt are in a much smaller amount" is not a TTT problem and is caused by GMod update, and only happens to you instead of every server ever?

**Comment by comedinha** [comment]
https://facepunch.com/showthread.php?t=1500238
