### ISSUE TITLE
Hud problem issue

### ISSUE THREAD

**Issue by comedinha** [Facepunch/garrysmod-issues#2339]
I know this is not the place over these problems but occurred in the last update garry's mod

Sometimes the hud is completely clean, removing everything appeared. Without errors.
http://steamcommunity.com/id/comedinha/screenshot/645503094103315870
Not show default ttt hud

on https://github.com/Facepunch/garrysmod-issues/issues/2337 other member related same problem on sandbox...

**Comment by robotboy655** [comment]
Unless you can give me a way reproduce it, I cannot confirm it and will count it as addon failure.

**Comment by deinemudda32** [comment]
Some people said, if you press Escape and get back to game your HUD dissapears

**Comment by robotboy655** [comment]
It doesn't happen to me when I do that.

**Comment by deinemudda32** [comment]
I don't have any problems, too.
But 2 peoples reported it to me.

**Comment by comedinha** [comment]
Yeah, this is a gmod problem, press esc and hud back
But robot not reproduce... All bugs reported by me is illusions...

**Comment by deinemudda32** [comment]
I didnt mean that.

**Comment by ThatOneCactus** [comment]
It also happens to me when I hit escape. Well, maybe escape, but i know it happens everytime i open console. I hope you can find a way to fix this, because it also disables your ability to use chat on servers, and you can't exit out unless you ctrl+shift+esc, at least that's the way it affects me.

**Comment by robotboy655** [comment]
Did you happen to have a Steam Controller @comedinha?

**Comment by kem008** [comment]
It is happening with me not just in Dev Branch in the current stable version also :=( and I am using Windows without any controller just keyboard and mouse :(

**Comment by comedinha** [comment]
No, i no have Steam Controller...
Sometimes this error show when I open the console...

**Comment by robotboy655** [comment]
What error?

**Comment by deinemudda32** [comment]
I don't understand anything, right now.

We talked about an issue, which hides your hud permanently even if youre not in the menu, which really pisses off.

**Comment by comedinha** [comment]
The error is hud not showing
Sometimes the hud disappear, to back need press esc and esc again...
I'm not sure but often it occurred to me after I open the console

**Comment by kem008** [comment]
No there is no error it is a bug which can cause problems with binds.
If you ingame and and in menu then u press ESC to return to the game then you hud disappear and if you not press ESC double times your gameplay will be ruin like press Y button like chat cause PlayerCameraAngles changes :D :D 
Thats all I know about this and it will ruin the ESC also you cant return to the menu anymore or Console or anything :(

**Comment by kem008** [comment]
I know it only happens if we go to the main menu with ESC in-game then we select Resume Game after this your whole hud Disappear and you need to switch back to the main menu before other functions disable.

--

Thats all I found about this. Sorry but I dont want duplicate

**Comment by ShinyaKogami** [comment]
6 people reportet this issue to ..

Hud dissapear's if u tab-out, or open the Steam-Browser .. u can fix this issue by clicking "esc" 2-times

**Comment by kem008** [comment]
This is fixed I checked so we can close this now if it appears again you can open it.
