### ISSUE TITLE
Old created demo error - Crashes Game

### ISSUE THREAD

**Issue by camjac251** [Facepunch/garrysmod-issues#2344]
I have a few demos that I recorded before the update went out and would like to be able to make something out of them but currently Garry's Mod will crash when trying to load them.
Clean install as well, still crashing.

I've attached 3 old demos
[demo.zip](https://github.com/Facepunch/garrysmod-issues/files/72067/demo.zip)
[demo2.zip](https://github.com/Facepunch/garrysmod-issues/files/72068/demo2.zip)

 and my dump logs.
[gmod-dumps.zip](https://github.com/Facepunch/garrysmod-issues/files/72071/gmod-dumps.zip)

I recorded this on the September 2015 version and am trying to load up the demos using version 2015.12.16.

I recorded this in Serenity Gaming DarkRP 82.196.16.39:27015 (added that for troubleshooting reasons) and made sure I had all of the addons required for playing it back, it worked just fine before the update.

Here is what I did in 2015.12.16 to get this issue:
I would start a new game on any map, load the console and type in "playdemo mydemoname" then hit enter, mydemoname being the name of my demo. It would then appear to load then until it reaches the second to last bar or so then Gmod would close, no crashing notification or freezing, it would just quit.

**Comment by robotboy655** [comment]
Old demos are no longer playable in the newest version of the game - there were networking changes.
This is unfixable. Not the crashing, but the playback.
