### ISSUE TITLE
Murder Green Highlight not appearing

### ISSUE THREAD

**Issue by StevyLee** [Facepunch/garrysmod-issues#2345]
Hello so i mainly play Murder and a crucial part of murder is finding clues. It's extremely difficult as clues are meant to have a green highlight around to indicate its position.
My green highlight seems to not show and it is to note that picking up objects with the phys gun does not show a blue mark around the object

I've tried mu_halo_loot 1
              mu_halo_render 1
But does not seem to be recgonised in the console.
Please help!

**Comment by Kefta** [comment]
This is not a Garry's Mod issue. Make a Murder issue. Also, halos do not work on non-Windows OSes iirc

**Comment by StevyLee** [comment]
My brothers have mac like mine and it seems to work on theirs
