### ISSUE TITLE
Garry's Mod Problem

### ISSUE THREAD

**Issue by AlexiizKiller** [Facepunch/garrysmod-issues#2349]
I have bought Garrys Mod on Steam Yesterday and i cant play it, I start it normaly but playing it, it crashes and the screen corrupts, thanks for help

My PC:
GPU: Radeon 5450 HD (1024 Mb)
Ram: 4GB
Proccesor: Intel Core i3 @3.4 GHz
OS: Windows 7 Ultimate x64

**Comment by Jake3231** [comment]
I think I may have a similar issue.  Do you have any addons installed?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
