### ISSUE TITLE
Crash when tossing hopper mine at many npcs

### ISSUE THREAD

**Issue by Panzerhandschuh** [Facepunch/garrysmod-issues#2351]
The crash happens when you pick up hopper mines with a gravity gun and throw them at large groups of npcs. The crash doesn't seem to happen from any particular event. Sometimes it happens before throwing the hopper mine, and sometimes it happens a few seconds after throwing the hopper mine.

The crash may also happen when throwing other physics objects like explosive barrels.

The crash does not seem to happen in HL2 (only gmod).

The attached zip contains the crash dump file, a demo showing how I cause the crash (1-2 seconds at the end of the demo were cut off before the crash), and a map used to test the crash (required for the demo).

[crash files.zip](https://github.com/Facepunch/garrysmod-issues/files/72784/crash.files.zip)

**Comment by robotboy655** [comment]
Will be fixed, thanks a bunch!

**Comment by Panzerhandschuh** [comment]
I'm almost certain this crash also happens with explosive barrels. Combine helicopter bombs might also cause crashes but I haven't confirmed it.

**Comment by robotboy655** [comment]
Nah, I doubt it, the crash issue here was related to changes to the combine mine.

**Comment by Panzerhandschuh** [comment]
Yeah, actually I think I'm getting some unrelated crashes from barrels and helicopter bombs. It's just that the barrel crashes were happening on the same map with the mine crashes, so I thought they were related. I'll submit new reports.
