### ISSUE TITLE
Modelprecache stringtable still at 2048

### ISSUE THREAD

**Issue by maurits150** [Facepunch/garrysmod-issues#2352]
![img1](https://cloud.githubusercontent.com/assets/637201/12024515/09ee7828-ada5-11e5-810a-1dfba2f3361d.png)

As discussed in the next update thread. It's supposed to be 4096 but it seems to crash out at 2048 and concommands are also still reporting 2048.

https://facepunch.com/showthread.php?t=1497739&p=49406373

While you're at it an attempt to raise it to 8k instead may be worthwhile.

**Comment by Python1320** [comment]
I could assume precaching 3000 models during join onto a server is going to be ... slow, but this is better than 2k limit I guess.

**Comment by robotboy655** [comment]
It was actually 2k, it will be raised to what it is in source sdk 2013 - 4k.
Loading 8k models into memory on server connect might be a bit too excessive.

**Comment by maurits150** [comment]
Thanks man.

I personally disagree with 8k being excessive as all hard limits in the engine should be raised to the maximum feasible and instead soft limits should be introduced (in the form of e.g. concommands) and it should be up to developer what limit gives the best scalability to usability ratio. For example a server that's exclusively using small and low poly models should be able to take advantage of the 8k limit and servers with insane high poly car models should set their limit to 2k.
(This assuming that no pre-allocation takes place and that empty table space isn't wasted space.)

Nonetheless any raise is a good raise so it's appreciated.

**Comment by robotboy655** [comment]
You are putting too much trust into DarkRP server owners to know what any of this means.

**Comment by Kefta** [comment]
@robotboy655 They wouldn't know about it. Just leave it at 4k and allow server owners to raise it if need be.

**Comment by maurits150** [comment]
About missing 100% of the shots not taken...

Wondering if raising it to 8k is possible, now that the norm is having SSDs that are fast enough to load the entire GMod directory into RAM within a few seconds?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/2119
