### ISSUE TITLE
Model related crash

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#2353]
It seems as though using the zombine model (models/player/zombie_soldier.mdl) on a server causes any client in the PVS with it to eventually crash. Unfortunately, I don't have any good instructions to reproduce the issue due to its lack of predictability, but I do have some crash dumps. Hopefully they will help pin down the issue.

The crash dumps below are from 5 different clients after experiencing the issue. Thanks!

https://u.pomf.is/jcrkpd.zip

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/12036629/769d6672-ae50-11e5-86f9-fd25357443ec.png)

**Comment by DracTheGreat** [comment]
Yeah, I got the same thing. I'll try a different file host real quick. I think pomf is blacklisted or something. 
https://mega.nz/#!I4wwyLDA!PsUDzkBJ6sw4B18X-e9P8_oVn88SJRfjgQeIasuiaTQ

**Comment by robotboy655** [comment]
Models affected:
models/player/combine_soldier_prisonguard.mdl (Fixed)
models/player/zombie_soldier.mdl
models/player/soldier_stripped.mdl

**Comment by ritzbits** [comment]
Have the two models below been fixed? It looks like they're still causing crashes.

models/player/zombie_soldier.mdl
models/player/soldier_stripped.mdl

**Comment by robotboy655** [comment]
No, we do not appear to have source files for those 2 so I haven't looked into it since.

**Comment by besenyei** [comment]
Can you explain why these models cause crashes? fixing it is one thing, but the cause is still a mystery.

**Comment by robotboy655** [comment]
I don't remember what the original issue was, but after looking through my email history I think the underlying crash was fixed earlier this year.
