### ISSUE TITLE
Lua Panic! Something went horribly wrong "not enough memory" 

### ISSUE THREAD

**Issue by RemiVillien** [Facepunch/garrysmod-issues#2354]
Hi,

I recently buy a new video card (Titan X OC gigabyte) and now i get this error when i'm in sending client

```
Lua Panic! Something went horribly wrong "not enough memory"
```

I have 16gb of ram.

I tried to
-reinstall Windows / Gmod
-Delete / Unsubscribe all addons

**Comment by Kefta** [comment]
Allocate more memory with the -heapsize flag.

**Comment by DropMotion** [comment]
I already tried that but still don't work.

**Comment by thegrb93** [comment]
Can VRam limit create this error? After all, he says the only change was his video card.

**Comment by kem008** [comment]
I also got this error. Last week. I got 8 gb ram and my ram wasnt full only 3 gb used. While gmod ran.

**Comment by thegrb93** [comment]
http://stackoverflow.com/questions/639540/how-much-memory-can-a-32-bit-process-access-on-a-64-bit-operating-system
