### ISSUE TITLE
Crash when explosive barrel touches trigger_hurt

### ISSUE THREAD

**Issue by Panzerhandschuh** [Facepunch/garrysmod-issues#2355]
This crash doesn't seem to happen with every trigger_hurt, but it does happen for the trigger_hurt on the map I attached in the zip file. Oddly, when I try to decompile the map and copy the trigger_hurt into a new test map, the crash does not happen so maybe there's more to the crash than just the trigger_hurt.

The zip file also contains a crash dump and a demo showing how to replicate the crash. Another very odd thing - when I recorded the demo, the crash did not happen the first time a barrel touched the trigger_hurt, but the second time. Also, the demo ends a few seconds before I explode the second barrel due to the crash.

[crash files.zip](https://github.com/Facepunch/garrysmod-issues/files/74312/crash.files.zip)

**Comment by willox** [comment]
The map you've uploaded is under a different name to the demo, but I was able to reproduce your crash _only_ when using the gravity gun.

**Comment by Panzerhandschuh** [comment]
Sorry, I uploaded the wrong version of the map. The download should be fixed now.

**Comment by robotboy655** [comment]
Will be fixed.
