### ISSUE TITLE
util.TableToJSON doesn't properly encode numerically indexed tables

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-issues#2356]
```
] lua_run print( util.TableToJSON( { "asdf", "asdf", "asdf" } ) )
> print( util.TableToJSON( { "asdf", "asdf", "asdf" } ) )...
{"1":"asdf","2":"asdf","3":"asdf"}
```

The correct result should be something like this:

```
["asdf","asdf", "asdf"]
```

Due to the lack of differentiation between numerically indexed and string indexed tables in Lua, I think the best way to determine if a table is numerically indexed or mixed index would be to compare the results of the length operator and table.Count. It's not the fastest solution but JSON encoding is an expensive operation anyways.

```
function IsNumericTable( tab ) return table.Count( tab ) == #tab end
```

**Comment by robotboy655** [comment]
Already reported.
