### ISSUE TITLE
PANEL:OnCursorMoved() only works for x, y < w, h 

### ISSUE THREAD

**Issue by Netheous** [Facepunch/garrysmod-issues#2357]
I've created my own slider using OnCursorMoved and several other things and appearently PANEL:OnCursorMoved() only returns x and y smaller than width and height.

Ergo, if I have it on a panel of size 200x100 and print out the X and  Y that OnCursorMoved returns, it'll never get past 200 nor 100.
It'll reach 199 in X and 99 in Y maximum.

It's the version from 2015.12.16

**Comment by robotboy655** [comment]
This is intended behavior as far as I know, since the hook only works when the cursor is on the actual panel.
