### ISSUE TITLE
Crash on map load (Manjaro Linux)

### ISSUE THREAD

**Issue by chick8ed** [Facepunch/garrysmod-issues#2358]
I seem to get a 50% chance of loading a map.
Steps for reproducing the crash:
Open Garry's Mod
Load any map
And it should load to the point where its either sending client info for online servers or initilizing game data for offline.
Afterwards, the hl2_linux process should hang around for a while, not being able to be killed, and should die.
I've tried reinstalling and disabling all addons. Neither worked.
System specs
 OS: Manjaro 15.12 Capella
 Kernel: x86_64 Linux 4.4.0-1-MANJARO
 Resolution: 1440x900
 DE: XFCE4
 CPU: Intel Core i3 CPU 550 @ 3.192GHz
 GPU: GeForce GTX 550 Ti
 RAM: 5833MiB

**Comment by mcd1992** [comment]
https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Garry.27s_Mod

Try some of those fixes and make sure you have the appropriate 32 bit libraries installed.
