### ISSUE TITLE
Ragdoll "Control With Motion Sensor" option missing (Kinect)

### ISSUE THREAD

**Issue by xXSnowyXx** [Facepunch/garrysmod-issues#2359]
BuildID 902419 (2015.12.16)
Kinect appears and can show video in main menu however right clicking a ragdoll in the options menu no longer shows the "Control With Motion Sensor" option. I believe this has only happened in the latest build as it was working for me recently - reports elsewhere start the day after it's release and according to one report using an old version fixed the problem.

**Comment by michu469** [comment]
Problem with this:
```
Filter = function( self, ent, ply ) 

		if ( CLIENT && !motionsensor ) then return false end
		if ( CLIENT && !motionsensor.IsAvailable() ) then return false end
		if ( !ent:IsRagdoll() ) then return false end
		if ( !gamemode.Call( "CanProperty", ply, "motioncontrol_ragdoll", ent ) ) then return false end
		
		return true 
```
Even if i bypass this animation ragdoll is really laggy.

**Comment by michu469** [comment]
from screen capture video
https://www.dropbox.com/s/5c4x1avptd2k3n2/bug.mp4?dl=0

**Comment by robotboy655** [comment]
Will be fixed in Dev.
