### ISSUE TITLE
I Think I Got a Beta? 

### ISSUE THREAD

**Issue by TitusStudios** [Facepunch/garrysmod-issues#2360]
At the top right corner of the screen there is a text saying the map i'm on like GM_flatgrass.bsp and the FPS and i can not see the lights , lamps , materials and my game crashes if i go onto my desktop.

**Comment by Kefta** [comment]
Delete your garrysmod folder in ~/steamapps/common/, and reinstall with Steam cloud sync disabled. Also, I would disable all your workshop addons

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
