### ISSUE TITLE
Texture and Vehicle errors

### ISSUE THREAD

**Issue by TerraVoltGaming** [Facepunch/garrysmod-issues#2363]
when shooting a gun a get a large smoke texture in my face and the bullet is occasionally a bullet that is collored pink and black. Also, ONLY the airboat and the pod vehicals from HL2 (the vehicles that come with the game), and ships from the stargate addon pack are the only ones i can get in or move w/ my phys-gun. everything else is just there, not modifiable (crtl r-click), no collisions, nor movable, etc. just visible. Please help me as well as you can. i can deal with the gun texture errors but the Vehicles are becoming irritatng. my steam name is the same as this name i am using now.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
