### ISSUE TITLE
Crash Workshop complete

### ISSUE THREAD

**Issue by Mitrong13** [Facepunch/garrysmod-issues#2364]
Hello, 
When I want to join a waiter DarkRP my games downloads addons them then arrived has workshop complete my games crash

Cordialy Mitrong13.

**Comment by willox** [comment]
Do the crashes generate any crash dumps (.mdmp files) in SteamApps\common\GarrysMod?

**Comment by Mitrong13** [comment]
Yes.

2016-01-02 19:19 GMT+01:00 William Wallace <notifications@github.com>:

**Comment by Mitrong13** [comment]
2016-01-02 20:40 GMT+01:00 romain leveque <romain.flame09@gmail.com>:

**Comment by willox** [comment]
If you want to share the dumps you'll need to upload them to a file sharing website (megaupload, google drive, whatever you know) and supply the public link.

**Comment by Mitrong13** [comment]
https://mega.nz/#!z983zaDY!jev7kUUIjxVs1H0LkmxTREArF5ri7QdPVf7u5OWB1MI


2016-01-02 20:44 GMT+01:00 William Wallace <notifications@github.com>:

**Comment by Mitrong13** [comment]
I have reboot my game but he crashed again.


2016-01-02 20:57 GMT+01:00 romain leveque <romain.flame09@gmail.com>:

**Comment by Mitrong13** [comment]
So ? Why i have crash ?

2016-01-03 15:39 GMT+01:00 romain leveque <romain.flame09@gmail.com>:

**Comment by kem008** [comment]
You get this message also?
[Screenshot](http://imgur.com/lltr9hY)

**Comment by gmodcrashed** [comment]
i have the same issue, in a specific server when joining, after the workshop complete message pops up, the game crashes, here are the links to some of the crash files:
https://drive.google.com/file/d/0B6wWqqx0u0vwV1U2Z3pYcDF0WWs/view?usp=sharing
https://drive.google.com/file/d/0B6wWqqx0u0vwTUxMN1ZPZ0xyN1k/view?usp=sharing
https://drive.google.com/file/d/0B6wWqqx0u0vwS1V3ckFKT0F1UGc/view?usp=sharing
https://drive.google.com/file/d/0B6wWqqx0u0vwU2ZwRzdNQktHbms/view?usp=sharing
https://drive.google.com/file/d/0B6wWqqx0u0vwZjgzNlVab3F3WjA/view?usp=sharing

**Comment by robotboy655** [comment]
@gmodcrashed you have an entirely different problem - https://github.com/Facepunch/garrysmod-issues/issues/951

**Comment by gmodcrashed** [comment]
@robotboy655 any solution?

**Comment by robotboy655** [comment]
This should've been solved by the April updates.
