### ISSUE TITLE
bug with grenade

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#2367]
![2016-01-04_00008](https://cloud.githubusercontent.com/assets/10911451/12094133/f4bda8a2-b317-11e5-9642-7444ed02d99d.jpg)

**Comment by Kefta** [comment]
Uh

**Comment by robotboy655** [comment]
I am assuming he's referring to the fact that the model has a grenade in hands with 0 ammo left.

**Comment by kem008** [comment]
On my side it has never happened before weird I will keep checking it :D

**Comment by robotboy655** [comment]
:D :D Please stop posting ::D information that is already mentioned in the :D:D tickets, you are wasting your own time :D :D

**Comment by kem008** [comment]
I got time bro :D

**Comment by Kefta** [comment]
Stop

**Comment by robotboy655** [comment]
Going to call this one fixed, the grenade is automatically stripped when you run out of ammo.
