### ISSUE TITLE
Tab out glitch

### ISSUE THREAD

**Issue by Marx4058** [Facepunch/garrysmod-issues#2368]
Any time I tab out of a game to use console or mess with gmod settings it messes up the game I was on. It takes away all my buttons uses except for the wasd keys. If I try to use chat (y) all it does is rotate my camera view. It even takes away the use of the esc button. Uninstalling the game and reinstalling it does not fix it.

**Comment by robotboy655** [comment]
Cannot confirm this. Post all the information you can, full list of addons, launch parameters, directX version used in game ( mat_dxlevel convar ), video options, windowed or not, noboroder or yesborder, etc

**Comment by Fire-Gaming** [comment]
Same thing happens to me, I don't know why though. It seems to be random

**Comment by thegrb93** [comment]
I've never had this. What do you mean tab out? alt+tab?

**Comment by Fire-Gaming** [comment]
for me it isn't tabbing, it just happens randomly

**Comment by bellum128** [comment]
I and a friend have also had this issue. No UI elements are appearing, and the escape menu won't open.

**Comment by robotboy655** [comment]
If you cannot prove a reliable way of reproducing this bug, do not post at all. There's no point in posting "I have this bug too" in a bug tracker, it serves no use.

**Comment by robotboy655** [comment]
If this still happens, let us know.
