### ISSUE TITLE
SWEP.CallOnClient ignores BaseClass calls

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2369]
For example:
```
function SWEP:Deploy()
   if ( SERVER ) then self:CallOnClient( "SharedDeploy" ) end
   return true
end

function SWEP:SharedDeploy()
   -- stuff
   BaseClass.SharedDeploy( self )
end
```

The client just ignores the BaseClass call and doesn't run the function, just using the highest class' SharedDeploy function.

**Comment by robotboy655** [comment]
This makes 0 sense. Are you implying the call from C++ cherry picks through the code and decides not to call certain code?

Can you provide a full example code to reproduce this?

**Comment by Kefta** [comment]
weapon_1
```
function SWEP:Deploy()
	if ( SERVER ) then
		print( "weapon_1: Deploy" )
		self:SharedDeploy()
		self:CallOnClient( "SharedDeploy" )
	end
	
	return true
end

function SWEP:SharedDeploy()
	print( "weapon_1: SharedDeploy" )
end
```

weapon_2
```
DEFINE_BASECLASS( "weapon_1" )

SWEP.Base = "weapon_1"

function SWEP:SharedDeploy()
	print( "weapon_2: SharedDeploy" )
	BaseClass.SharedDeploy( self )
end
```

The following will print when weapon_2 is deployed:
(Server) >weapon_1: Deploy
(Server) >weapon_2: SharedDeploy
(Server) >weapon_1: SharedDeploy
(Client) >weapon_2: SharedDeploy

weapon_1: SharedDeploy is never printed on the client, meaning CallOnClient for some reason just seemingly skipped over the BaseClass call.

**Comment by willox** [comment]
```
] give weapon_2
weapon_1: Deploy
weapon_2: SharedDeploy
weapon_1: SharedDeploy
weapon_2: SharedDeploy
weapon_1: SharedDeploy
```

If you are not on single player you should make sure both files are AddCSLuaFile'd.

**Comment by Kefta** [comment]
I am on single player; sorry -- forgot to mention that part

**Comment by willox** [comment]
That's really odd. I didn't modify your code _at all_.

**Comment by willox** [comment]
I can only suggest that you add a few debug prints inside SharedDeploy. Print BaseClass, BaseClass.ClassName, BaseClass.SharedDeploy.

PrintTable( debug.getinfo( BaseClass.SharedDeploy ) ) too.

**Comment by Kefta** [comment]
I can't seem to replicate it now; I'll chalk it up to some function overflow since I was doing a lot of loops in each.
