### ISSUE TITLE
Crash Gmod Multiplayer

### ISSUE THREAD

**Issue by Somedeos** [Facepunch/garrysmod-issues#2370]
Hi sorry to bother you,

Since yesterday my game crash , without reason this happened during my development server , I even reinstall the game and the game still crash , my administrators (server ) arrive to connect to the server. The game crashes when i open a menu ( props , scoreboard , F4 menu) in darkrp .
I feel it only just in multiplayer because in single player i do not crash .

My spec :

Windows 10 - 64Bits
Intel Core I5-4690K
GeForce GTX 970 4Go
16Go RAM

Crash logs : http://dumps.metastruct.uk.to/dumper.py?dump=hl2_151216_crash_2016_1_7T0_39_17C0.mdmp&key=BQbW32giJlc6liqVVbBf9UEPLePjm18WEWC4RaKANXKwyT0M1bTG7CPW92vGtYVLO8WTv5c1PIxeqQ27og8SaGf57vgM8y8bqn-MXhflG6PzDBqYSd9lBHif8rTGxCzZxXqD6tKGZoZu8iOMEUZsZv-W7Yc5FdULquVuokNIrgQ=

PS: With DirectX 9 (launch option -dxlevel 90) i don't have crash but without launch option, i have this error during this sending client info : Engine Error "failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=288, nFirstVertex=0"

I hope there is a solution because I am very annoyed to develop my server, Thanks you.

**Comment by willox** [comment]
Your link doesn't work

**Comment by Somedeos** [comment]
Link update, sorry

**Comment by Somedeos** [comment]
With the command -dxlevel 120 and the resolution 1280x720 the game works but when I return with resolution 1980x1080 the plant Thurs. and the game is horrible in 1280x720, if you have a solution I'm interested

**Comment by Kefta** [comment]
-dxlevel 95 is the max (98 as well but there are some major flaws)

**Comment by siasur** [comment]
For me it sounds like a problem with your graphics card ram. Do you have simliar problems in other games (on high res and high video settings)?
