### ISSUE TITLE
Possible linux mic bug

### ISSUE THREAD

**Issue by Kaosheaven** [Facepunch/garrysmod-issues#2371]
when i test my mic in steam it works perfectly fine, i also tested it in skype, and ts3, when im not in a server and i do a mic test garry's mod actually registers my mic but, once i hop onto a server it just doesnt work, also aparently it doesnt even register the chat overlay when i attempt to use it

im on linux mint 17.3 rosa x86_64

**Comment by Kaosheaven** [comment]
I love it how facepunch gives Linux users the middle finger thanks for your time

**Comment by zerfgog** [comment]
What did you do to solve the issue (for future reference & other users)

**Comment by Kaosheaven** [comment]
I didn't I can't figure out what the issue is I tried a couple of things 


Sorry :/
