### ISSUE TITLE
Text Becoming Black Squares

### ISSUE THREAD

**Issue by GaminAwesome** [Facepunch/garrysmod-issues#2373]
THis is weird all of the text is turning into black squares!

**Comment by zerfgog** [comment]
try laying off the acid

**Comment by Kefta** [comment]
:8ball:

**Comment by GaminAwesome** [comment]
no really its annoying!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
