### ISSUE TITLE
Game crashes while Toggle Console in the server

### ISSUE THREAD

**Issue by MrEmerik2000** [Facepunch/garrysmod-issues#2376]
The game crashes while i'm toggle console in the following server: [QC/FR] Québec Murder [ 2X Meurtrieurs | Pointshop | Models ] This server has a mesh spray tool called SprayMesh (it's available on the Workshop, didn't crash while spraying on walls). I'm open up the console, the game freezes and crashes. I have a supplies of sprays in mu imgur account. Can you fix this crash.

**Comment by robotboy655** [comment]
Stop using Direct X 8.
