### ISSUE TITLE
Fix gravity algorithm on props

### ISSUE THREAD

**Issue by meepdarknessmeep** [Facepunch/garrysmod-issues#2377]
https://a.uguu.se/pesbyu_2016-01-09_22-08-31.webm

Did you know gravity doesn't effect metal fences as much as hula bobbleheads?

**Comment by robotboy655** [comment]
You don't fix it, and I don't know how many times I have to repeat that we cannot edit vphysics.dll

**Comment by meepdarknessmeep** [comment]
You can fix it, by editing the values in the model data or entity data or whatever it is.

**Comment by thegrb93** [comment]
Use the mass tool if you need to change a prop's air resistance.

**Comment by Velkon** [comment]
gravity mark on his test server again?
