### ISSUE TITLE
SetSubMaterial does not work with Gmod CHands

### ISSUE THREAD

**Issue by Valkyrie121** [Facepunch/garrysmod-issues#2379]
if I run the following
 Entity(1):GetHands():SetSubMaterial(1, "maxofs2d\models\gm_painting")
nothing happens, no errors just nothing

**Comment by robotboy655** [comment]
The actual bug is that SetSubMaterial does not work on bonemerged entities.

**Comment by UnderscoreKilburn** [comment]
Should be fixed in dev now.
