### ISSUE TITLE
Unable to set Texture Detail above high on Mac.

### ISSUE THREAD

**Issue by justin97530** [Facepunch/garrysmod-issues#2383]
I can't seem to set the texture detail to above Medium, even though the recommended for my system is High.

![Screenshot](https://cloud.githubusercontent.com/assets/2884155/12321503/5d9af5a0-bad4-11e5-83ad-8c940f35c473.png)

-- Information --
Garry's Mod version: 2015.12.16 (Steam)
Monitor Refresh Rate: 60Hz
System: Macmini6,1
RAM: DDR3-1600 10GB
CPU: Intel Core i7 3615-QM
GPU: Integrated Intel HD 4000 (1356MB)

-- Video Settings --
Model detail: High (Recommended: High)
Texture detail: Medium (Recommended: High)
Shader detail: High (Recommended: High)
Water detail: Reflect all (Recommended: Simple reflections)
Shadow detail: High (Recommended: Low)
Color Correction: Disabled (Recommended: Disabled)
Antialiasing mode: None (Recommended: None)
Filtering mode: Bilinear (Recommended: Bilinear)
Wait for vertical sync: Enabled (Recommended: Enabled)
Motion Blur: Enabled (Recommended: Disabled)
Field of view: 75
Multicore Rendering Enabled (Recommended: Enabled)

-- Gameplay Information --
Average FPS: 60

**Comment by robotboy655** [comment]
This is intentional.

**Comment by justin97530** [comment]
Why?

**Comment by robotboy655** [comment]
To help with crashes.

**Comment by justin97530** [comment]
Ah, I see, I'll just have to deal with the sorta-bad textures then. Thanks anyways!

**Comment by kurisubrooks** [comment]
@robotboy655 Is this just for Intel/Integrated graphics? 
I haven't played Garry's Mod in a while, but I have a fairly powerful dedicated graphics card inside, and if i'm not able to perform at graphics higher than Medium, that's very disappointing.

**Comment by Bo98** [comment]
> Is this just for Intel/Integrated graphics?

No, it is a memory related crash so the graphics card made no difference, no matter how powerful.

**Comment by kurisubrooks** [comment]
So, you disable a better entire experience for the game because the developers don't want to fix a bug?
.. Right

**Comment by willox** [comment]
I believe this is a choice made by Valve

**Comment by kurisubrooks** [comment]
That's very disappointing then. Sorry to pester you all.

**Comment by Bo98** [comment]
> I believe this is a choice made by Valve

The graphics limitation? IIRC TF2 had it recently as a temp workaround for a bug (reverted now?) but I don't think any other games have it.

**Comment by justin97530** [comment]
I have TF2 and time, I'll test if the workaround is still there.
