### ISSUE TITLE
Shiny's crash on loading menu

### ISSUE THREAD

**Issue by shinybaubles** [Facepunch/garrysmod-issues#2388]
When I launch gmod and it reaches the menu where you're supposed to see the "start new game, etc." 
It crashes, HL2.exe stops working.
I've tried reinstalling steam and gmod.

Even stranger is that there's no crash log.

**Comment by robotboy655** [comment]
Verify TF2

**Comment by shinybaubles** [comment]
I don't have TF2 installed. I've verified the other source games.
