### ISSUE TITLE
garys mod doesent fulie close after the late update #626762

### ISSUE THREAD

**Issue by kalis0x** [Facepunch/garrysmod-issues#2392]
h3y guys 4 sum reasen my gari's mod doesnt close if it is open in steam like it not fully close exe is still in steam overlay can some1 fix thanx

**Comment by deinemudda32** [comment]
very funny.

**Comment by kalis0x** [comment]
@deinemudda32 
this is not a joke my geralds mod is siriously broke!!!!

**Comment by zerfgog** [comment]
this is percisely why nobody likes you cdriza

**Comment by kem008** [comment]
Strange I played with the game today with the dev branch and I had no issue with it only with old problems which will be get fixed in the future I hope :D I pray :D
