### ISSUE TITLE
Workshop Infinite Download GLITCH

### ISSUE THREAD

**Issue by MarcSenpai** [Facepunch/garrysmod-issues#2393]
When i downloaded addons in steam it was ok but now i dont know why all time in queue i have Garry´s Mod - Workshop Content all time downloading and dont let me update other games, and dont download nothing, dont know what it is but its so bad, help me pls 
![1](https://cloud.githubusercontent.com/assets/16740965/12376309/a87243fc-bcec-11e5-9969-9032f0d31571.png)

**Comment by Kefta** [comment]
This is a problem with Steam downloads, not Garry's Mod.
