### ISSUE TITLE
new 4096 model problems

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#2398]
After the server goes over 2048 models this happens with newly spawned models

![2016-01-19_19-48-59](https://cloud.githubusercontent.com/assets/3169571/12436844/a1524486-bee6-11e5-8d23-4efb751eaafa.jpg)

We start spawning trigger models, looping back to the beginning of the client's cache array. 

![2016-01-19_19-50-13](https://cloud.githubusercontent.com/assets/3169571/12436846/a645ddcc-bee6-11e5-9ee7-69feaa82fd1d.jpg)

~~Server stringtable size was increased to 4096 but is the client's still 2048?~~

@Python1320 verified this is not the case. Something else is causing the client to turn into tumblr.

**Comment by Python1320** [comment]
```dumpstringtables_new modelprecache``` says it is 4000, could be some other limit somewhere

**Comment by robotboy655** [comment]
Fixed in dev, naturally steam.inf is bumped though, so sorry.
