### ISSUE TITLE
npc_template_maker destination group does not work in multiplayer

### ISSUE THREAD

**Issue by Panzerhandschuh** [Facepunch/garrysmod-issues#2399]
For some reason setting this property causes the npc_template_maker to not spawn npcs in multiplayer games. It works in single player though. I have attached a zip containing a map that uses destination groups and the associated vmf.
[destgroup_test.zip](https://github.com/Facepunch/garrysmod-issues/files/96824/destgroup_test.zip)

**Comment by kem008** [comment]
I found this bug in Half Life 2 campaign in Episode 2 ep2_outland_06a only 2 hunter spawn other 2 one not spawn.

**Comment by robotboy655** [comment]
Will be fixed in Dev.

**Comment by kem008** [comment]
okay its not affect ep2_outland_06a I need to find what it does this bug the whole encounter stops after 2 hunter death but it needs to spawn other hunters after 2 death >.<
