### ISSUE TITLE
file.Read + string.Explode unexpected results

### ISSUE THREAD

**Issue by tomasas** [Facepunch/garrysmod-issues#240]
Reading files that contain new lines turns the new lines to char 13 instead of char 10.

<code>
local str = string.Explode("\n", file.Read("abc.txt", "DATA"))
local mdl = str[1]
print(string.byte(mdl:sub(1)).." "..string.byte(mdl:sub(mdl:len())))
</code>
Having a file with some text and new lines you can recreate this easily yourself.
This will always return char 13 at the end spot where \n is in the original string. When reading it somehow manages to turn char 10(\n) to char 13. Since if you replace "\n" with string.char(13) in the string Explode function it will work fine it seems.

This only started happening when an update was made about 4 days ago.

**Comment by bmwalters** [comment]
This isn't an issue with string.Explode; when I run `print(string.byte(file.Read("test.txt", "DATA")[12]))`
where test.txt has the contents `hello world\nhey\n`, I get `13`.

This means that interestingly, file.Read converts a read file into CRLF format, even if the input file is LF. I wonder if this behavior is the same on Linux and OS X (I'm on Windows).
