### ISSUE TITLE
Need help with DHTML panels

### ISSUE THREAD

**Issue by jarari** [Facepunch/garrysmod-issues#2401]
Before update I could change alpha of the panel using PANEL:SetAlpha(int) function, but I can't after the update.

So I took a look on changelist and found "Proper alpha blending for Awesomium panels".

Which blends with which specifically?

How can I change alpha of the panel?

**Comment by neico** [comment]
Pretty sure that change was about html alpha rendering, something along #2129.
Did you try SetBGColor since it seems you want to make the entire panel transparent, not just elements within a website.

**Comment by jarari** [comment]
@neico I tried SetBGColor, no luck. 
SetBGColor(Color(255,255,255,0)) completely hides the panel, but 1-255 shows the panel with full opacity.

**Comment by jarari** [comment]
Oh, I figured it out.
The update separated alpha of the panel itself, and the content..
so I just had to change the opacity of content!

Such a dumb I was lol
