### ISSUE TITLE
BUG - Garry's mod local server + off line steam

### ISSUE THREAD

**Issue by Cpcdos** [Facepunch/garrysmod-issues#2402]
Hi,
I've problems with my friends, when I put steam in off line mode, and I create a local server included in game menu (Local server:checked and percistence mode:2) for gaming, clients cannot join my server.
More preciselly: My garry's mod server is displayed on LAN list, so it's not a network problem, I can ping... but when a client joint my server, "Connecting to server..." turn in loop.
We have tested to restart computer or change PC server with off line steam, same problem! 

And when we put steam in on line mode, it work...

There are solution ?
It's a bug ?

Thank you
Sébastien FAVIER
PS:Sorry for my bad bad English level

**Comment by Acecool** [comment]
Make sure sv_lan is 0 ( 1 means only clients on your LAN may join ) and maxplayers is more than 1 ( 1 sets it to singleplayer server ). Also, I don't recommend creating a listen-server for many reasons; if you just want to play then my reason for that is.. if your client crashes then everyone else loses connection. For most game-modes this may not matter, but if you're playing sandbox and building something and forget to save, then it could be lost.

If a client can see your server, but not properly join.. you may have an issue with your router. Make sure the proper ports are unblocked ( such as 27015 UDP, 27005 UDP or both; if I recall correctly )...


If all else fails: I'd recommend using SRCDS.. It's easy to create, I even have the bat files set up ( you only change the path ): https://dl.dropboxusercontent.com/u/26074909/tutoring/server_srcds_steamcmd/setting_up_a_server_with_steamcmd.lua.html

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

With upcoming P2P this shouldn't be a problem.
