### ISSUE TITLE
Calling navmesh.AddWalkableSeed on a dedicated server creates massive console spam

### ISSUE THREAD

**Issue by Xyxen** [Facepunch/garrysmod-issues#2403]
It's pretty easy to replicate. Running
```lua
navmesh.AddWalkableSeed(vector_origin, vector_up)
```
on a dedicated server results in
```
UTIL_GetListenServerHost() called from a dedicated server or single-player game.
```
being spammed several times per frame in the server console.

I've done some digging, and it looks to me that the following happens:

1. `navmesh.AddWalkableSeed` presumably calls `CNavMesh::AddWalkableSeed`.
2. [The seed is added to `m_walkableSeeds`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/nav_generate.cpp#L4642)
3. During `CNavMesh::Update` (called once per frame), `m_walkableSeeds` [is iterated over to render the spots using `DrawLine`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/nav_mesh.cpp#L349-L353)
4. [`DrawLine` is a macro expanding to `NDebugOverlay::Line`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/nav_mesh.cpp#L32)
5. [`NDebugOverlay::Line` calls `GetLocalPlayer()`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/debugoverlay_shared.cpp#L102)
6. [On the server, `GetLocalPlayer()` calls `UTIL_GetListenServerHost()`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/debugoverlay_shared.cpp#L25)

The easiest way to fix this is probably wrapping [the for loop in step 3](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/nav_mesh.cpp#L343-L354) with
```C++
if (!engine->IsDedicatedServer())
{
    ...
}
```

**Comment by SpencerSharkey** [comment]
:100:

**Comment by zerfgog** [comment]
:sunny: 
:dromedary_camel: :palm_tree: :dromedary_camel: :older_man: :dromedary_camel::package: :dromedary_camel:    :dromedary_camel:
---
:clock10:
---
:dromedary_camel::older_man::package:   :man_with_turban:
:dromedary_camel::older_man:   :package::man_with_turban:
:older_man:         :gun::man_with_turban:

:man_with_turban::key::package:
:man_with_turban::shipit:

:shipit:

**Comment by robotboy655** [comment]
Will be taken care of. And you really need to stop spamming.
