### ISSUE TITLE
GetThirdPerson

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2404]
```
[ERROR] gamemodes/base/gamemode/shared.lua:220: attempt to call method 'GetThirdPersonMode' (a nil value)
  1. unknown - gamemodes/base/gamemode/shared.lua:220
```
I get this error when Im stuck in the debris in ep1_citadel_00

**Comment by kem008** [comment]
After the fix a new probelm appeared :D 

in ep2_outland_01 when an npc_hunter kill alyx and he block me to the debris, I get this problem if I use DUCK when Im stuck in the debris :D 
```
[ERROR] gamemodes/base/gamemode/shared.lua:220: attempt to call method 'GetThirdPersonMode' (a nil value)
  1. unknown - gamemodes/base/gamemode/shared.lua:220


[ERROR] gamemodes/base/gamemode/shared.lua:220: attempt to call method 'GetThirdPersonMode' (a nil value)
  1. unknown - gamemodes/base/gamemode/shared.lua:220

[<FP>ICEMAN|3|STEAM_0:1:4782422] Lua Error:

[ERROR] gamemodes/base/gamemode/shared.lua:220: attempt to call method 'GetThirdPersonMode' (a nil value)
  1. unknown - gamemodes/base/gamemode/shared.lua:220
```

**Comment by robotboy655** [comment]
It's the exactly the same bug that as fixed.

**Comment by neico** [comment]
It sounds more like the vehicle variable isn't a valid vehicle object. (personally I'd rather check for validity then to check if there's a function with that name like your fix did)

But I didn't see you pulling the lua code onto steam yet so he shouldn't be able to see any differences yet, right? Unless twitter ate most of the commit messages again... (there might be people that don't know that changes to the repo aren't reflected on the mod immediately)

**Comment by kem008** [comment]
strange I got another version lua error talked about cameradistance in the afternoon I cant understand why it says again GetThirdPersonMode -.-

**Comment by robotboy655** [comment]
The issue is not that the vehicle is not valid vehicle, which it clearly is since you are inside of it, the problem is that that particular vehicle entity class is not considered a Lua vehicle, so the Vehicle metatable is not applied to it.

```
print( vehicle, IsValid( vehicle ), vehicle.IsValidVehicle, vehicle.SetThirdPersonMode, vehicle.GetDriver )
```

``
Entity [658][prop_vehicle_choreo_generic]	true	nil	nil	nil
Entity [658][prop_vehicle_choreo_generic]	true	nil	nil	nil
Entity [658][prop_vehicle_choreo_generic]	true	nil	nil	nil
```

**Comment by neico** [comment]
Sounds like checking against IsValidVehicle looks cleaner then, though the wiki text is a bit misleading then, if you can't access the vehicle functions and IsValidVehicle is considered one of them, then this whole function makes less sense...

Almost wants me to request a optional argument for IsValid that when true, checks if the object is a valid lua based object, would help detect c++ weapons like weapon_physcannon etc.
