### ISSUE TITLE
DTextEntry SizeToContents doesn't do anything.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2405]
Doesn't resize to fit the text. Can you also make it possible to copy text from a text entry that has editing disabled? Also this https://github.com/Facepunch/garrysmod-issues/issues/1588 is breaking my textentry :(

**Comment by robotboy655** [comment]
It's not really supposed, as it only works on Label derived panels.

You can use this temporary fix for now: http://wiki.garrysmod.com/page/Panel/GetContentSize

I also updated all the wiki pages for proper documentation.

**Comment by thegrb93** [comment]
Okay thanks. I'll try that
