### ISSUE TITLE
Noclip while dead

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2408]
You can use noclip while dead.

You are still spectating your ragdoll, till you are too far away then you can scout around the map.

**Comment by Kefta** [comment]
https://github.com/garrynewman/garrysmod/pull/1119

**Comment by deinemudda32** [comment]
Oh sorry.
I thought I would be the first one who reports this.

Im sorry.

**Comment by Kefta** [comment]
@deinemudda32 You were, and I just submitted it.

**Comment by deinemudda32** [comment]
Oh hehe.
