### ISSUE TITLE
Weird Brightness Flickering-Bug

### ISSUE THREAD

**Issue by RoiEXLab** [Facepunch/garrysmod-issues#2410]
On my Computer I run into a weird Issue.
The Brightness seems to change Randomly when i look in specific angles.
I reinstalled the game completely, but nothing changed.
Whe I turn on the flashlight this does not happen. (It seems to have something to do with map-brightness).
Watch the Video if you are not sure what I'm talking about: https://youtu.be/-pU44Ue-1Ok
I'm using an AMD Radeon R9 290
and an AMD FX-8350
running on Windows 8.1

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
