### ISSUE TITLE
prop_physics debris overlapping on break (multiplayer only)

### ISSUE THREAD

**Issue by Panzerhandschuh** [Facepunch/garrysmod-issues#2415]
When certain physics objects break (using the break input), the debris spawn inside of each other and cause a significant frame rate drop. This issue only happens in multiplayer. In single player, the debris scatter instead of getting stuck inside each other. The attached map file replicates this issue by spawning helicopter bombs and breaking them when they touch the ground. This issue also affects prop_physics_override.

[physics_break_test.zip](https://github.com/Facepunch/garrysmod-issues/files/106095/physics_break_test.zip)

**Comment by robotboy655** [comment]
It's not from overlapping ( the gibs don't have physics with anything but world ), it's from the sheer amount of clientside gibs created. Also the fire.

I think the default limits for the gib amounts are a bit too generous:
```
"prop_active_gib_limit" = "999999"
 game
"prop_active_gib_max_fade_time" = "999999"
 game
```
And the fact that gibs don't despawn if you look at them.

**Comment by robotboy655** [comment]
Ok, I see the issue in MP.

**Comment by Panzerhandschuh** [comment]
Will this be fixed/closed? I noticed it's still an issue in today's update.

**Comment by robotboy655** [comment]
It it wasn't closed, it wasn't fixed. It may or may not be fixed in the future.

**Comment by Panzerhandschuh** [comment]
Alright, thanks for the update.
