### ISSUE TITLE
Users can't connect, get "server has newer version" error.

### ISSUE THREAD

**Issue by solsane** [Facepunch/garrysmod-issues#2417]
I have a SteamCMD gmod server hosted on an ubuntu server. Everything seems to be working fine and has no indication of not working fine. However when me or others attempt to join the server, with the latest version of Garry's mod, the error "The server you are trying to connect to is running a newer version of the game." I have tried updating the server and I've had no luck.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
