### ISSUE TITLE
Gmod crash in ep2_outland_09

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2418]
I dont know why It worked in this week. But now it isnt
I get crash on spawn. ( **On Beta** **ListenServer** ) 
Same is happening in **Srcds** with **non beta** 
In sandbox crash also so I didnt do anything wrong :D :D

[Link listenserver beta](http://dumps.metastruct.uk.to/dumper.py?dump=hl2_160130_crash_2016_1_30T10_55_14C0.mdmp&key=Kux0e2S7bTXo69dYcWCOo88XcBwmcmvgs99ZoP2-Ced8Nwmrij2DFF2xQwtMQEFta-Xe9MEWDyVjth7k-fPCVomWeJKzrkUskhw5IEem3_Z09KTuNS0SAH2rWf8aZDDtBj4FDb9UhX8xoqkPQ2YXj5MQ0ts0FeusFZqTdY9KA6o=)

**Comment by kem008** [comment]
Okay it is working now on my listen server beta with all addons disabled weird. Have you fixed hl2 mdl animations?

**Comment by robotboy655** [comment]
So, you pretty much confirmed it is a problem on your side. Was it that hard to do that **BEFORE ** making a post here?

**Comment by kem008** [comment]
The strange things are coming from new fixes which ruin addons for me now in some maps.

**Comment by robotboy655** [comment]
That's why you are asked to **test those fixes on your addons and report them in max detail before an update is released**

**Comment by kem008** [comment]
Ye but the addon wont work I know which addon do the crash but I cant understand why now before it didnt. It is fixing hl2 mdl for hl2 ep1 and ep2 missing animations...

**Comment by Kefta** [comment]
I merged all the model animations, however, they suffer from a problem of sequences having the same name and causing issues when a newer/older sequence is played in HL2 or EP2 maps, respectively. Still trying to find a workaround for this.

**Comment by kem008** [comment]
Thanks for the answer becuz the model fix addon fixed alyx Enter Car animation :D and right now I cant use it anymore and somehow I got a bug back when combinecannon cant target the player :D

**Comment by kem008** [comment]
im trying to turn off playerdeath 
`local noplydie = ents.FindByClass("logic_choreographed_scene")
			for k, v in pairs( noplydie ) do
	
				v:SetKeyValue("onplayerdeath", "0")
			end`
