### ISSUE TITLE
PlayerCanSeePlayersChat broken (not called)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2420]

**Comment by willox** [comment]
Can't reproduce

**Comment by WilliamVenner** [comment]
@willox 

This is a bit of an old issue but it seems to be occurring for me.

I can't get this hook to call at all. I've tried on both DarkRP and Sandbox, and I've tried with minimal addons (basically a fresh server.)

I'm just using this command:

```
lua_run hook.Add("PlayerCanSeePlayersChat", "lol", function(...) PrintTable({...}) end)
```

Nothing gets printed when I type a message.

![image](https://user-images.githubusercontent.com/14863743/70390708-4da2fb80-19c5-11ea-837b-c04cd465ae8d.png)
