### ISSUE TITLE
Hitting "Resume Game" hides hud.

### ISSUE THREAD

**Issue by AgentAgrimar** [Facepunch/garrysmod-issues#2421]
As the title simply says, hitting the _"Resume Game"_ button on the menu hides the hud,
Using the _ESC Button_ however, corrects the issue, and does what it is supposed to do.

It has confused me a few times before realizing this...

**Comment by kem008** [comment]
this issue is already uploaded but good to see others report :-)

**Comment by robotboy655** [comment]
Thanks for finally actually finding the cause instead of saying "it doesn't work"!

**Comment by comedinha** [comment]
I not click "Resume Game" to hide for me...
