### ISSUE TITLE
MsgC sometimes lags behind

### ISSUE THREAD

**Issue by BillyOnWiiUIn144p** [Facepunch/garrysmod-issues#2422]
Hi,

I've noticed this happening quite frequently recently:

![](http://i.imgur.com/Nu37ce8.png)

Is there a specific cause?

**Comment by robotboy655** [comment]
MsgC starts a new print call for each color, so it's entirely possible for such things to happen.

**Comment by BillyOnWiiUIn144p** [comment]
Thanks.

**Comment by robotboy655** [comment]
It could also be the "blogs one community" message

**Comment by BillyOnWiiUIn144p** [comment]
I don't think so, it prints after the last gradient.

But I think you're right with the colours thing, that IS a gradient so it's most likely that it will fuck up.

It's more of an aesthetic problem so I don't really mind at all, it's just that it happens a lot :S
