### ISSUE TITLE
Glock Sound Missing

### ISSUE THREAD

**Issue by Violat0r** [Facepunch/garrysmod-issues#2426]
I reported this issue before in the update thread that the update on 1/19/2016 broke the Glock sound.

robotboy655 pointed out the issue may be with the changes [done here](https://github.com/garrynewman/garrysmod/commit/85663681b3c573a538829a0542b9d17458a7b6e2) and was attempted to be fixed [by this](https://github.com/garrynewman/garrysmod/commit/02296c12fe0e1e2b8e17e2dff00ec58fe5ac268b)

After today's update 2/2/2016, the sound is still missing and still showing the following error:
Failed to load sound "weapons\pl_gun3.wav", file probably missing from disk/repository

**Comment by robotboy655** [comment]
Your server is not up to date.

**Comment by Violat0r** [comment]
@robotboy655 My servers are maintained by NFO servers, the server is up to date. Just to be on the safe side, I did create a new local server on my PC to test the issue and it is still present. The issue is not the server being out of date.

**Comment by Kefta** [comment]
I just tested this on a new TTT dedi; cannot replicate

**Comment by Violat0r** [comment]
Let me try to be as specific as possible.

Client(others are still reporting the issue in game, highly unlikely it is my config):
Verified my local Garry's Mod game files and other source games files.
Source games installed: CS:GO, CS:S, HL2, L4D2, and TF2.
Not subscribed to any Garry's Mod workshop items.

Server:
Installed via steamcmd (app_update 4020 validate).
Startup line:
srcds.exe -console -game garrysmod +map ttt_bb_teenroom_b2 +maxplayers 36 +gamemode terrortown -tickrate 66 -insecure
server.cfg only contains ttt_minimum_players 1 and ttt_debug_preventwin 1 for testing.
Tested on ttt_bb_teenroom_b2 and ttt_minecraft_b5
No addons or other modifications were made to the server.

**Comment by Kefta** [comment]
If it's still not working for you, just change your glock's soundscape file in the code to the raw sound path

**Comment by comedinha** [comment]
Same problem here
https://youtu.be/7vO3iU8_FuM
(My ping is 290 = lagg ;-;)

The glock code
```
AddCSLuaFile()
SWEP.HoldType = "pistol"

if CLIENT then
   SWEP.PrintName = "Glock 18"
   SWEP.Slot = 1

   SWEP.Icon = "vgui/ttt/icon_glock"
   SWEP.IconLetter = "c"
end

SWEP.Kind = WEAPON_PISTOL
SWEP.WeaponID = AMMO_GLOCK

SWEP.Base = "weapon_tttbase"
SWEP.Primary.Recoil	= 0.9
SWEP.Primary.Damage = 15
SWEP.Primary.Delay = 0.10
SWEP.Primary.Cone = 0.025
SWEP.Primary.ClipSize = 20
SWEP.Primary.Automatic = true
SWEP.Primary.DefaultClip = 20
SWEP.Primary.ClipMax = 60
SWEP.Primary.Ammo = "Pistol"
SWEP.AutoSpawnable = true
SWEP.AmmoEnt = "item_ammo_pistol_ttt"

SWEP.UseHands			= true
SWEP.ViewModelFlip		= false
SWEP.ViewModelFOV		= 54
SWEP.ViewModel  = "models/weapons/cstrike/c_pist_glock18.mdl"
SWEP.WorldModel = "models/weapons/w_pist_glock18.mdl"

SWEP.Primary.Sound = Sound( "Weapon_Glock.Single" )
SWEP.IronSightsPos = Vector( -5.79, -3.9982, 2.8289 )

SWEP.HeadshotMultiplier = 1.75
```

**Comment by Violat0r** [comment]
I am fairly sure that weapon_ttt_glock.lua is not the issue. It has not been changed since it was last known to be working. You can also try it out for yourself by replacing Weapon_Glock.Single with Weapon_FiveSeven.Single for example.
