### ISSUE TITLE
void CTriggerCamera::Disable( void ) crash

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2428]
Load the map d1_trainstation_05 and jump to the ichthyosaur scene, eventually it will crash or this will happen:

(1313.49) input t9_teleport_outside_rl: viewcontrol_ickycam.Disable()
Host_Error: DLL_SetView: not a client

Thats because of a missing check here:

```if ( m_hPlayer && m_hPlayer->IsAlive() )```

It should be:

```if ( m_hPlayer && m_hPlayer->IsPlayer() && m_hPlayer->IsAlive() )```

Like in the Enable function.

**Comment by kem008** [comment]
point_viewcontrol is broken in gmod.
