### ISSUE TITLE
Windows 10: Garry's Mod doesn't close when instructed to.

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [Facepunch/garrysmod-issues#2429]
http://i.imgur.com/cDsfLmt.png

In this session of windows, I have launched Garry's Mod 1 time. I played on a server for a few hours, and then told the game to close.

After logging into my computer again (it locks the computer after about an hour of inactivity), Steam suddenly reports GMOD as running. A further inspection using Process Hacker reveals that there are several HL2.exe processes, suspended, under the following command line:

"G:\Steam Library\steamapps\common\GarrysMod\hl2.exe" -steam -game garrysmod -windowed -noborder

In addition, when GMOD closes, it creates a Windows Error Reporter instance as a child process to hl2.exe.

This is a fresh installation of Windows 10 Professional x64. Every drive in this machine was wiped a week ago and freshly re-installed. This is a problem that ONLY occurs with Garry's Mod and NOT with any other source engine game.

These suspended processes maintain their impact on system resources AND can confuse steam and other applications into thinking that Garry's Mod is running when it isn't.

They are also all parented to a "Non-existent process (8464)".

Can GMOD please be patched to correctly handle itself and its children when told to close? If skype can do it, so can you!

Just to clarify too, I had encountered this issue in the past on Windows 7, however the integrity of the OS at that stage was questionable at best. There's also no common denominator other than Garry's Mod itself: No other source engine game that I have played has done this before.

**Comment by deinemudda32** [comment]
I reported this already, but you gave some decent details tho.

**Comment by robotboy655** [comment]
#2069

**Comment by HDG-MrDeeJay** [comment]
ty for pointing me to old issue
