### ISSUE TITLE
Remover effect missing after changing visleaf

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2431]
class CLuaEffect gets created, but I don't see the sparks that normally appear when something is deleted.

**Comment by robotboy655** [comment]
![nope](http://i.imgur.com/tyhd5ez.gif)

**Comment by thegrb93** [comment]
It was failing every time last night. For now it fails each time you first delete an entity after you enter a different visleaf. e.g. Each time you enter/leave the secret room in gm_flatgrass, the effect won't work for the first time.

**Comment by robotboy655** [comment]
It was local multiplayer.

**Comment by thegrb93** [comment]
![](https://dl.dropboxusercontent.com/u/72472980/out.webm)
