### ISSUE TITLE
Entity.Remove doesn't work on entities with collision errors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2432]
http://pastebin.com/kj0ZwKjN

This is a log I received from someone using this script: https://github.com/Kefta/Entity-Crash-Catcher
The two entities that are flagged for removal are removed at least 15 times each with increasing velocity on every think. The script is not even able to catch the nan position in time before the crash, making it impossible to prevent it. The title is vague for the very reason that the only information we have on the crash is this: https://facepunch.com/showthread.php?t=1460189

**Comment by kem008** [comment]
if I remove all game_text entity from some half life 2 episode 2 maps on my server crash like in ep2_outland_09

**Comment by robotboy655** [comment]
Pretty sure what happened there is that the server crashed trying to remove the entity. As you know, the removal is not immediate and is done on the next tick.

The crazy physics catcher was changed since so it should all be better anyway.
