### ISSUE TITLE
No zombie attack effect if ply:SetTeam(0 - 4) value

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2433]
Its easy to just use teams with a number beyond 4 BUT it will break SetNoCollideWithTeammates because it actually wants a team id from 1-4.

So assigning a Team in the range from 0-4 will break zombie attacks.

Edit: To clarify, they do attack but they will not do any damage this also only happens on npc_zombie and npc_fastzombie as far as I can tell.

**Comment by robotboy655** [comment]
Duplicate of #1820
