### ISSUE TITLE
RenderOverride on players breaks weapon material handling

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2434]
(Let me just say here that I'm not the one using RenderOverride on a player - [PAC is](https://github.com/CapsAdmin/pac3/search?utf8=%E2%9C%93&q=RenderOverride))

Setting a material on weapon while RenderOverride is hooked to a player will result in the material applying to the whole player world model rather than being restricted to the weapon.

**Comment by Kefta** [comment]
Does resetting the player's material before calling DrawModel in RenderOverride workaround the issue?

**Comment by roboderpy** [comment]
Because EF_BONEMERGE entities are always drawing parent first when calling Entity:DrawModel()

**Comment by robotboy655** [comment]
Pretty sure this is fixed.
