### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by Cloudhunter** [Facepunch/garrysmod-issues#2436]
Hey everyone. I've recently experienced an issue on Linux - CentOS 7 64 bit to be precise.

When starting a server (sandbox, no addons, gm_construct), messages like this are spammed in the console (sorry about the length):

`Assigned anonymous gameserver Steam ID [A-1:3548164105(6356)].
VAC secure mode is activated.
Unhandled Lua Refresh: [NAME:includes/modules/utf8.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/concommand.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/properties.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/undo.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/construct.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/weapons.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cleanup.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/widget.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/team.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/http.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/usermessage.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/scripted_ents.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_schedule.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/player_manager.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/duplicator.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/drive.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/gamemode.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/numpad.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/saverestore.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cookie.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/list.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cvars.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/baseclass.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/hook.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/constraint.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_task.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/entity_filters.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/sql.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/color.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/init.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player_auth.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/string.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/ents.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/vector.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/net.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/coroutine.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/weapon.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/motionsensor.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/angle.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/game.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/file.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/table.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/entity.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/debug.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/math.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/sh_anim.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/ai_translations.lua] [TYPE:!UNKNOWN]
L 02/06/2016 - 23:10:44: "Collin<2><STEAM_0:1:xxxxxxxx><>" connected, address "xxx.xxx.xxx.xxx:27005"
Client "Collin" connected (xxx.xxx.xxx.xxx:27005).
L 02/06/2016 - 23:10:44: "Collin<2><STEAM_0:1:xxxxxxxx><>" STEAM USERID validated
Unhandled Lua Refresh: [NAME:drive/drive_base.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:drive/drive_noclip.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/modules/utf8.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/concommand.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/properties.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/undo.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/construct.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/weapons.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cleanup.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/widget.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/team.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/http.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/usermessage.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/scripted_ents.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_schedule.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/player_manager.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/duplicator.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/drive.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/gamemode.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/numpad.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/saverestore.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cookie.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/list.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cvars.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/baseclass.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/hook.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/constraint.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_task.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/entity_filters.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/sql.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/color.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/init.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player_auth.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/string.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/ents.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/vector.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/net.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/coroutine.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/weapon.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/motionsensor.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/angle.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/game.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/file.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/table.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/entity.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/debug.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/math.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/sh_anim.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/ai_translations.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:drive/drive_base.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:drive/drive_noclip.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/modules/utf8.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/concommand.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/properties.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/undo.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/construct.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/weapons.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cleanup.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/widget.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/team.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/http.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/usermessage.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/usermessage.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/scripted_ents.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_schedule.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/player_manager.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/duplicator.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/drive.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/gamemode.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/numpad.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/saverestore.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cookie.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/list.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cvars.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/baseclass.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/hook.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/constraint.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_task.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/entity_filters.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/gmsave.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/sql.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/util/color.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/init.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player_auth.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/string.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/ents.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/vector.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/net.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/player.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/coroutine.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/weapon.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/util.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/motionsensor.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/angle.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/game.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/file.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/table.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/entity.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/debug.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/extensions/math.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/sh_anim.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:gamemodes/base/entities/weapons/weapon_base/ai_translations.lua] [TYPE:!UNKNOWN]
L 02/06/2016 - 23:11:22: "Collin<2><STEAM_0:1:35274518><>" entered the game
Unhandled Lua Refresh: [NAME:drive/drive_base.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:drive/drive_noclip.lua] [TYPE:!UNKNOWN]
Unhandled Lua Refresh: [NAME:includes/modules/utf8.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/concommand.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/properties.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/undo.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/construct.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/weapons.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/cleanup.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/widget.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/team.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/http.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/usermessage.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/scripted_ents.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/ai_schedule.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/player_manager.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/duplicator.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/drive.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/gamemode.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/numpad.lua] [TYPE:!MODULE]
Unhandled Lua Refresh: [NAME:includes/modules/saverestore.lua] [TYPE:!MODULE]
`

There are a bunch of errors upon joining. And people can't move around or spawn things from the menu.

I have tried googling the issue but it does seem to be a new one (although there seems to be one pastebin similar, here: http://pastebin.com/fmHrrmst).

Does anyone have any ideas as to what could be causing this, or any potential fixes?

Thanks!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
