### ISSUE TITLE
Workshop Update Bug

### ISSUE THREAD

**Issue by TT13001** [Facepunch/garrysmod-issues#2441]
When I start Steam, an update of Workshop content is available but it's always at 0 bytes / 0 bytes...
How I can fix it ?

PS: Sorry for my English, i'm french :) 
![capture d ecran 2](https://cloud.githubusercontent.com/assets/13998983/12889916/7d5905d8-ce81-11e5-823b-6c225f3e3dd0.png)

**Comment by robotboy655** [comment]
It's not a Garry's Mod bug, and as such, cannot be fixed.

Steam developers were notified of the issue but chose not to do jack shit about it, so go blame Steam on Steam Support.

**Comment by TT13001** [comment]
Issue posted on Steam forum. Thanks for the answer !
