### ISSUE TITLE
Big bug/issue

### ISSUE THREAD

**Issue by Zerowolf22** [Facepunch/garrysmod-issues#2442]
A weird bug I havnt seen before.. like for real.

When ever I joined a server everthing where white,black and see threw texture. If I opened my options to see if anything is wrong inputed, the option tap is just a white page with nothing, like a white paper so is the workshop download bar.

http://steamcommunity.com/sharedfiles/filedetails/?id=619428324
http://steamcommunity.com/sharedfiles/filedetails/?id=619428196
http://steamcommunity.com/sharedfiles/filedetails/?id=619421740

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
