### ISSUE TITLE
Crashing when opening Console

### ISSUE THREAD

**Issue by scottlocks** [Facepunch/garrysmod-issues#2443]
Garrys Mod likes to crash when the console is opened in Multiplayer. As well, fences do not like to appear where they are in multiplayer, but are visible in SinglePlayer. 

1) reinstalled Garrys Mod and all other Source Games
2) Remounted all additional content
3) Tested on other servers with same issue appearing on all
4)  #955 without luck(mat_dxlevel 90 95 etc)
5) Not my laptop(MSI GS60 044, I7 4710HQ, 16GB Ram, 1.2TB of Storage, GTX970m 3GB). I can play Fallout 4 without issue..... a much more demanding game. 

Dump File is below. 
https://drive.google.com/file/d/0B-ePqU953myJbTg3UmdHTTN3MVk/view?usp=sharing

Thanks!

**Comment by bbart23** [comment]
Having the same problem here. Complete reformat of hard drive and fresh install. It has been like this for about a year now.

**Comment by scottlocks** [comment]
Mine is no longer crashing. I disabled Steam Cloud and updated to the Dev Stream. Seemed to solve my issues. 

I'm also on W10 if that helps at all.

**Comment by bbart23** [comment]
Wow thank you for the quick reply. Dev Stream fixed it for me as well. Thanks a lot!

**Comment by scottlocks** [comment]
No worries! I would not constitute Dev Steam as a fix though. There is still something occurring as a issue here that should be looked into. For now though I'd say its a workaround.

**Comment by scottlocks** [comment]
Love how there is no support for this at the moment...

**Comment by Bo98** [comment]
When there's 442 other open issues waiting to be fixed, I wouldn't expect anything.

**Comment by bbart23** [comment]
It's a little ridiculous. I am still having the problem btw, that Dev stream was strictly a temporary fix, only worked that one day.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1448
