### ISSUE TITLE
Why not default +r_hunkalloclightmaps 0 for servers ?

### ISSUE THREAD

**Issue by UltimateByte** [Facepunch/garrysmod-issues#2445]
Hi there,

My suggestion is this : Please, default r_hunkalloclightmaps to 0, as it makes half of gmod servers crash on start if set to the default value of 1, including the very popular map rp_rockford_v1b, at least for linux servers. It's one more thing preventing admins from smoothly running a gmod server.

2 questions about r_hunkalloclightmaps need answers first, to see if it would be smart to set it to 0 by default.
1. Does it serve any purpose on a server ? I couldn't tell the difference with it set at 0 or 1.
2. Who does it affect ? Linux servers ? Linux servers and clients ? Both linux and windows servers ? 

My guess is that it only affects servers, and paradoxically is only useful for clients.

Facepunch, please fix :)

**Comment by Bo98** [comment]
It used to be a thing (https://facepunch.com/showthread.php?t=1002155) but seemingly no longer for some reason.

**Comment by UltimateByte** [comment]
Yep @Bo98 , I saw that too.
Another option obviously could be : Set a higher limit if possible.

**Comment by robotboy655** [comment]
The only thing it affects is how the memory is allocated for light data, 0 = to normal "program memory" with alloc or 1 = to Valve's seemingly limited to certain size "MemoryStack memory" with Hunk_Alloc

**Comment by willox** [comment]
It was only ever set to 0 by default for clients afaik

**Comment by UltimateByte** [comment]
@robotboy655 For record, the serverside error, on maps such as the (buggy) rp_rockford_v1b is : Engine hunk overflow!, which crashes the server.
Fix as a server admin is to add +r_hunkalloclightmaps 0 as a start parameter.

A fix from Gmod could either be setting this to 0 by default, or increasing the limit if possible.
Any chance you can do something about it ?

**Comment by UltimateByte** [comment]
I'd like to know if you're gonna do something about that, so i can change the Linux Game Server Manager accordingly or not. If you need more time to check this out, please just tell me.

**Comment by UltimateByte** [comment]
@robotboy655 In the end, will you default this to 0, or should i close this ?

**Comment by robotboy655** [comment]
Maybe in the future, but not for the current update.

**Comment by UltimateByte** [comment]
Thanks for answering btw, it'll help us for LGSM decisions we have to take.

**Comment by UltimateByte** [comment]
Any update on this ?
We're applying +r_hunkalloclightmaps 0 by default now, so this is solved for LGSM users.
https://github.com/GameServerManagers/LinuxGSM/blob/master/GarrysMod/gmodserver#L56

However, would still be great to add this by default for others, and quite easy to implement i guess. :)

**Comment by uRandomAlex** [comment]
@UltimateByte It's set to 0 for performance reasons, I think. At first, this limits the memory that can be used (decreasing RAM usage), at second, hunk memory is faster to access then normal "program memory". The way you should handle this setting is to have a checkbox ("Are you running big maps?", default enabled if found big maps from predefined list and/or found RP gamemode) or automatically determine using experimental method (run server, crashes -> add "+r_hunkalloclightmaps 0", run server again).

**Comment by UltimateByte** [comment]
Still not solved ?
It's been a year, just for a svar.

**Comment by Kefta** [comment]
Just curious, is there any reason you would ever want it set to 1? I can't think of a situation where Valve's alloced memory would be more than the default set.

**Comment by UltimateByte** [comment]
@Kefta Did you ever try to start a Linux server on any big popular map like DarkRP ones? It crashes.

I personally don't care because i'm not even running such maps anymore, mainly sandbox servers... But it would help other users and avoid having LinuxGSM to use a workaround to change this setting by default.

**Comment by WinterPhoenix96** [comment]
Could we please have this set to 0 by default on Servers? That's been the default on Clients for like 7 years now and really doesn't seem to hurt anything.

**Comment by robotboy655** [comment]
Changed it to 0 by default. I guess lets see if breaks anything.

**Comment by WinterPhoenix96** [comment]
Thanks Rubat!

**Comment by UltimateByte** [comment]
@robotboy655 It won't break anything for Linux servers, I can guarantee. We've been putting the option by default in LinuxGSM for a while, and from thousands of users for the Garry's Mod script, nobody ever complained about this.
