### ISSUE TITLE
GetDefault will always return an empty string for clientside convars

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2446]
] lua_run_cl local test = CreateClientConVar( "GetDefaultDoesntWork", "4" ) print( test:GetDefault() ) print( "\n"..type( test:GetDefault() ) )

string
] lua_run_cl local test = CreateClientConVar( "GetDefaultDoesntWork", "whatever" ) print( test:GetDefault() ) print( "\n"..type( test:GetDefault() ) )

string

**Comment by willox** [comment]
It looks like GetDefault won't work for any Lua ConVars. CreateConVar and CreateClientConVar both don't set the default. Will fix.

**Comment by willox** [comment]
Spotted a memory leak there, too.

**Comment by Kefta** [comment]
Thank you!
