### ISSUE TITLE
game.CleanUpMap() and doors.

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2448]
How to reproduce:
1. maxplayers 12; map d1_trainstation_01
2. Go to Barney
3. lua_run_sv game.CleanUpMap()
4. Go there again.

There will be some doors missing now, attempting to use the filter for game.CleanUpMap does not solve the issue, they will not get cleaned up but they remain open or eventually cause some issues with triggers and other map related inputs where  they depend on the state or might even get locked.

**Comment by robotboy655** [comment]
Are you sure those are not the doors meant to be transferred by changelevels?

**Comment by ZehM4tt** [comment]
Before game.CleanUpMap() : http://images.akamai.steamusercontent.com/ugc/498015283490684208/198A56E4CE7334663D2E238B6D2B47BC94668516/

After: http://images.akamai.steamusercontent.com/ugc/498015283490684725/0CB5C65282D45712DCAE521E7908FA1645397732/

I doubt they are within the transition trigger

**Comment by robotboy655** [comment]
Should be fixed in Dev.
