### ISSUE TITLE
I call this one the walking left bug

### ISSUE THREAD

**Issue by thetippigamer** [Facepunch/garrysmod-issues#2449]
so for some reason when i start a new game of sand box or join a server my character auto walks to the left. i tried a few things, such as rebinding my keys, I tried to release the left strafe key in console. but nothing worked. so i decided to check my game files to make sure everything is there. Well what do you know i'm missing a file.....but it wont download and the glitch is still happening. Please help.

**Comment by Kefta** [comment]
Delete your cfg folder and verify your game.

**Comment by robotboy655** [comment]
This is not a place to get help.
