### ISSUE TITLE
Server - Workshop Addons not updating

### ISSUE THREAD

**Issue by Zythoxic** [Facepunch/garrysmod-issues#2451]
I updated my Server Content Addon for a new Model but it didn't update when i joined my Server. I tried restarting and everything. Nothing worked. Then i deleted the .gma from my GarrysMod "downloads" Folder. After joining the server again it worked. Subscribing to the Addon on the Workshop works aswell. So for some reason the Addons won't update or something on Server join. I've got that problem since the January 2016 Update.

**Comment by UltimateByte** [comment]
Server platform ?
Addon ID ?

Gmod team aren't wizards.

**Comment by Zythoxic** [comment]
I'm hosting it on my Computer and the Addon ID's are
503849721
503853132
504246909
598534705
503845840
503847162

**Comment by UltimateByte** [comment]
So let's assume you're a Windows user.
The only potentially relevant addon would be the one that failed updating.

**Comment by UltimateByte** [comment]
Could be a timestamp issue when the dev updated his addon... Or something else i can't think of.

**Comment by Zythoxic** [comment]
Well the Problem is it doesnt work with ANY Addon of mine. It worked before the update that's not a problem.

**Comment by Zythoxic** [comment]
And i updated them multiple times because i'm adding stuff all the time. All the Addons listed are uploaded by me. I can't really test it with other Addons since they're not getting updated pretty much.

**Comment by UltimateByte** [comment]
So the problem occurs only with addons that you uploaded to the workshop ?

Could that possibly be something with the way you make them ?

**Comment by Zythoxic** [comment]
I don't think it's because of the way i make them. Like i said everything worked great before the Update.

**Comment by robotboy655** [comment]
It should be fixed on the Dev branch / next update.
