### ISSUE TITLE
High network usage caused by the prop_vehicle_prisoner_pod's Think

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#2452]
Hello people,
As I wish the best for Garry's Mod, I let experts say whether it's a good idea to solve this problem or not.

I found out that _prop_vehicle_prisoner_pod_ entities produce a high network usage, compared to other entities. If I disable their Think by adding the engine flag [EFL_NO_THINK_FUNCTION](http://wiki.garrysmod.com/page/Enums/EFL), the high network usage disappears.
I created an addon to work around this problem: [Seats Network Optimizer](http://steamcommunity.com/sharedfiles/filedetails/?id=622814666)

[src/game/server/hl2/vehicle_prisoner_pod.cpp, line 323](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/vehicle_prisoner_pod.cpp#L323)

``` cpp
void CPropVehiclePrisonerPod::Think(void)
{
    SetNextThink( gpGlobals->curtime + 0.1 );

    if ( GetDriver() )
    {
        BaseClass::Think();

        // If the enter or exit animation has finished, tell the server vehicle
        if ( IsSequenceFinished() && (m_bExitAnimOn || m_bEnterAnimOn) )
        {
            GetServerVehicle()->HandleEntryExitFinish( m_bExitAnimOn, true );
        }
    }

    StudioFrameAdvance();
    DispatchAnimEvents( this );
}
```

We can see that `DispatchAnimEvents( this )` is called on each frame even if the seat is doing nothing. It may be the responsible of the useless traffic.
_How to know that the seat is doing something?_
- a driver just entered
- a driver just exited
- the SaveValue `m_bEnterAnimOn` is `true`
- the SaveValue `m_bExitAnimOn` is `true`

In all other cases, the Think seems to be able to be safely disabled.

Well, thanks for reading this small message. See you later!

Love,
Momo :heart:

**Comment by thegrb93** [comment]
Good find

**Comment by EstevanTH** [comment]
That's easy to find after setting up the seats in my university, with *net_graph* enabled. :stuck_out_tongue_winking_eye:

**Comment by Kefta** [comment]
It's CBaseServerVehicle's think

**Comment by LUModder** [comment]
I doubt this actually fixes any lag, just seems like a gimmick to me that you're using a think hook to stop a think hook.

**Comment by Kefta** [comment]
No, he's right. There's no reason for any anims nor frame advancing to occur when there's no one in the pod.

**Comment by robotboy655** [comment]
There actually is for the exit animation.

**Comment by Kefta** [comment]
Should it not be called only when the player is getting out? Not every think?

**Comment by robotboy655** [comment]
I just tested it, and the slight network overhead from that is not actually that big, and disabling the think function ( With your Lua example ) completely fucks up the pod, at least with the HL2 pod model so you can't exit it or look around  after entering it.

```
lua_run for id,e in pairs(ents.FindByClass("prop_ve*")) do print(e, e:IsEFlagSet(EFL_NO_THINK_FUNCTION) ) e:AddEFlags(EFL_NO_THINK_FUNCTION) end
```

**Comment by Kefta** [comment]
Just ran into this again the other day; here's a quick fix I made. This code will make the pod's Think method dormant unless the player is entering, inside, or exiting the pod: https://github.com/Kefta/gs_podfix

**Comment by robotboy655** [comment]
I have disabled the animations on the pods if they are empty & animations are not running on `dev` beta.

I could not see any "high network usage" when having dozens of them spawned, but I guess there's no reason to have them animate when empty.

**Comment by Battlefieldkille** [comment]
Do keep in mind that changing this affects the pods in HL2, if that even matters.

This is how it looks like on any other branch:
![2](https://github.com/Facepunch/garrysmod-issues/assets/69215350/417ca56f-af7f-4260-a5e0-3d408c3fec38)

This is how it looks like on `Dev`:
![2](https://github.com/Facepunch/garrysmod-issues/assets/69215350/83614916-b77c-479e-9cf0-61407e7782c5)

Map:
[d3_citadel_01_d.zip](https://github.com/Facepunch/garrysmod-issues/files/15254809/d3_citadel_01_d.zip)
