### ISSUE TITLE
Player NextBots ("bots") run extra movement simulations, making them faster than players.

### ISSUE THREAD

**Issue by raubana** [Facepunch/garrysmod-issues#2457]
**Garry's Mod Version:** 2016.02.03

Player NextBots (aka "bots") seem to be able to move faster than human-players; they lurch forward about every 13 server ticks. It seems that the engine runs two movement simulations for these bots during these lurches.

This bug can be quickly replicated and tested using the script below. While in multiplayer, run "run_botmovebug_testscript' in the console and then press forward.
[botmovebug_testscript.zip](https://github.com/Facepunch/garrysmod-issues/files/137199/botmovebug_testscript.zip)

This bug was discovered in this thread on Facepunch.com:
https://facepunch.com/showthread.php?t=1506441

**Comment by darkjacky** [comment]
I reported this here: https://facepunch.com/showthread.php?t=1485127&p=48797365#post48797365
After seeing your post I reported it to Willox on steam (because it reminded me).
Anyway thank you for opening the issue. Lets hope Willox will find the cause.

**Comment by willox** [comment]
Thanks for the easy-to-use reproduction code
