### ISSUE TITLE
Fix OSX issues with case-sensitive filesystems

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2458]
File paths containing capital letters fail to open on OSX systems when Garry's Mod is installed on a drive with a case-sensitive filesystem.

**Comment by UltimateByte** [comment]
Non-workshop addons with capital letters in their main folders don't work in linux too, as UNIX is sensitive to capital letters.

For anyone interested, i made a BASH zip updater script, which allows you to install and keep addons updated, and convert folders to lowercase (optional), just by running it. Manual is on the page, and more details into the script itself (that you need to edit to put your links in) https://github.com/UltimateByte/zip-updater

**Comment by willox** [comment]
@UltimateByte, every folder in the Garry's Mod installation should be lowercase, the rest doesn't matter.

**Comment by UltimateByte** [comment]
@willox I agree. But how can you convince a dev to use a lowercase name for his addon ?

I can assure you, if you put an addon with a file structure of "garrysmod/addons/MyCapsAddon" on a unix system, it will never work.
If you're using "garrysmod/addons/my-lowercase-addon" it will work.

Is that impossible to allow uppercase recognition for addons as many of them contain some uppercase in their names ?
