### ISSUE TITLE
Mounts "overlapping"

### ISSUE THREAD

**Issue by daunknownman2010** [Facepunch/garrysmod-issues#2460]
The new map mounting system is awesome, but it appears to start overlapping content when it starts prioritising more content. Let's say I start the game and start my game on a Counter-Strike map. If I then change the game to a sandbox map, the Counter-Strike content still overrides some of the content (Footsteps for example) and cannot be fixed unless I restart the game.

This is only on the Garry's Mod dev branch (Where this new system is introduced).

**Comment by willox** [comment]
Thanks!
