### ISSUE TITLE
I create point_viewcontrol error in console

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2464]
I created a point_viewcontrol to make d3_breen_01 better.
I get this message when the camera get input "Enable"

```
CTriggerCamera could not find a player!
```

**Comment by robotboy655** [comment]
This is not a place to get modding help.

https://facepunch.com/forums/65

**Comment by kem008** [comment]
Its not modding its a problem with point_viewcontrol.
It cant find any player.

**Comment by robotboy655** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/triggers.cpp#L3019

**Comment by robotboy655** [comment]
AKA you are using it wrong.

**Comment by kem008** [comment]
It returns with this message 
if this is false
 ```
if ( m_hPlayer->IsPlayer() )
	{
		pPlayer = ((CBasePlayer*)m_hPlayer.Get());
	}
```

**Comment by robotboy655** [comment]
Well obviously, because the activator you gave the entity is not a player.

**Comment by kem008** [comment]
I am not using Use input just Enable and activating it through logic_timer
