### ISSUE TITLE
Text on HUD vertical position bug

### ISSUE THREAD

**Issue by chelog** [Facepunch/garrysmod-issues#2466]
I can't test it right now because of #2465 but my server users report that all HUD elements that use text has their text shifted down for approx 10-20 px. Also I saw clientside errors about non-existing font "HudHintTextSmall". I don't know if it is connected but still report this.

Clients who reported this are on Windows x64

[SCREENSHOT](https://pp.vk.me/c631619/v631619780/181a6/FxkP50E9g4s.jpg) - note the text at the bottom right and text above the circle on the left (at least it MUST be above)
This happened after the update

EDIT: Just to note, both of these are dependent on `ScrH()`

**Comment by Kefta** [comment]
The enums for text alignment have changed this update

**Comment by chelog** [comment]
@Kefta okay, thank you, I'll update with comment if I find things fixed

**Comment by robotboy655** [comment]
Your addons will have to adjust. ```The TEXT_ALIGN_TOP``` and ```TEXT_ALIGN_BOTTOM``` enumerations now work properly instead of ```TEXT_ALIGN_BOTTOM``` not doing anything and TEXT_ALIGN_TOP having the effects of ```TEXT_ALIGN_BOTTOM```.
