### ISSUE TITLE
GitHub update tagged but missing latest changes

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2467]
@willox tagged 2016.02.22 but the repo doesn't match what was pushed to clients. Notably the utf8.len fix but there might be others.

**Comment by Bo98** [comment]
The tag will need recreating to point to the correct commit now.

**Comment by robotboy655** [comment]
WILLOX GET TO IT @willox

**Comment by willox** [comment]
:zzz:

**Comment by willox** [comment]
Disaster averted.
