### ISSUE TITLE
Crazy origin then entity removing when it is idle for some time

### ISSUE THREAD

**Issue by chelog** [Facepunch/garrysmod-issues#2468]
Well, [here's the video](https://youtu.be/7h08k2Fkv1g) which shows the thing that started happening.
When entity is idle for about 10 seconds, it starts to move very quickly (according to console log) and removes, however it remains being colliding with everything (like it just turned invisible).
This appears for every vehicle in the add-on. (It's modified version of SCars, just in case).

The problem started appearing only in the new update (22.02.2016).

Some logs:
```
ServerLog: prop_physics(models/props_vehicles/carparts_wheel01a.mdl) Got removed
Crazy origin on entity [915][prop_physics]
        Origin:           [0.000000, 0.000000, -16384.660156]
        Angles:           [-66.636047, 122.269890, 359.913818]
        Velocity:         [0.000000, 0.000000, -1986.452393]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!
```
```
Crazy origin on entity [937][prop_physics]
        Origin:           [-0.000000, 0.000000, -16403.111328]
        Angles:           [0.000010, 28.695803, 180.000015]
        Velocity:         [0.000000, 0.000000, -1980.000000]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!
```

SRCDS is on Ubuntu 14.04 x64

**Comment by willox** [comment]
I don't understand if that is a prop or a vehicle? Nothing has changed that should result in different behaviour of prop_physics entities.

**Comment by chelog** [comment]
@willox it's wheels, two of them, just props
when vehicle's entity is idle and not turned on, it has no effect on wheels except braking them. Maybe some axis rotation damping causes this?

**Comment by robotboy655** [comment]
Try disabling the crazy physics removing and defusing and see what happens then.

**Comment by robotboy655** [comment]
Try unmodifying the mod and see if it changes anything,

**Comment by chelog** [comment]
@robotboy655 with `sv_crazyphysics_remove 0` and `sv_crazyphysics_defuse 0` it does not remove but displaying these warnings every tick until I remove the vehicle:
```
Crazy origin on entity [919][prop_physics]
        Origin:           [-0.000000, 0.000000, -38868.488281]
        Angles:           [36.000687, 80.112000, 179.997131]
        Velocity:         [0.000000, 0.000000, -1986.412354]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Crazy origin on entity [915][prop_physics]
        Origin:           [0.000000, 0.000000, -39110.886719]
        Angles:           [-0.837262, -99.750641, 180.000015]
        Velocity:         [0.000000, 0.000000, -1995.394165]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Crazy origin on entity [919][prop_physics]
        Origin:           [-0.000000, 0.000000, -38898.332031]
        Angles:           [36.000687, 80.112000, 179.997131]
        Velocity:         [0.000000, 0.000000, -1989.590576]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Crazy origin on entity [915][prop_physics]
        Origin:           [0.000000, 0.000000, -39140.585938]
        Angles:           [-0.837262, -99.750641, 180.000015]
        Velocity:         [0.000000, 0.000000, -1980.000000]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Crazy origin on entity [919][prop_physics]
        Origin:           [-0.000000, 0.000000, -38928.222656]
        Angles:           [36.000687, 80.112000, 179.997131]
        Velocity:         [0.000000, 0.000000, -1992.750122]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
```
I'll try the original SCars and tell you. But as far as I remember I haven't modified any physics-related things

**Comment by willox** [comment]
You can set sv_crazyphysics_warning to 0 for now if you like. Do I just need to spawn any SCar car to reproduce this?

**Comment by chelog** [comment]
@robotboy655 well, with `sv_crazyphysics_remove 0` and `sv_crazyphysics_defuse 1` it outputs
```
Crazy origin on entity [914][prop_physics]
        Origin:           [0.000000, 0.000000, -16413.666016]
        Angles:           [0.051327, 89.977707, 0.036652]
        Velocity:         [0.000000, 0.000000, -1990.388916]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Crazy origin on entity [916][prop_physics]
        Origin:           [-0.000000, 0.000000, -16413.025391]
        Angles:           [-0.044468, -90.020950, 359.939514]
        Velocity:         [0.000000, 0.000000, -1990.376831]
        Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
```
not removing entity, then problem never happens again until I re-spawn the vehicle and set it to idle again

**Comment by willox** [comment]
The issue is that all vehicles in source by default spawn 4 wheel physics objects, even if they don't get attached to anything.

Because the models in SCars don't really have wheels, those physics just fall until they become invalid. I'll try to get a fix ready, but I'd expect it at earliest tomorrow. Sorry!

**Comment by chelog** [comment]
@willox okay, I got it, that's not critical when it's not removing entities but still needed to remove these crazy things
thank you a lot

**Comment by UltimateByte** [comment]
Sorry about upping this, but is that really the only fix that we can find ?

Got that issue on 2 servers using ACF. Some props disappeared randomly, so i checked the logs, and found similar things. 

```
Crazy angular velocity on entity [517][prop_physics]
Origin: [953.152222, -1812.421021, -8062.204102]
Angles: [51.487415, 155.168961, 82.060387]
Velocity: [646.980896, -2681.993408, -729.161804]
Angular Velocity: [-18803.498047, -18791.375000, 79191.890625]
Defusing!
Removing!
Crazy angular velocity on entity [515][prop_physics]
Origin: [954.785950, -1872.468262, -8181.129395]
Angles: [-24.476460, 98.562035, 173.855927]
Velocity: [1856.144775, -497.116272, -665.395325]
Angular Velocity: [-5190.594727, 47722.164062, 94473.359375]
Defusing!
Removing!
Crazy angular velocity on entity [492][prop_physics]
Origin: [1008.104187, -1829.201782, -8173.481934]
Angles: [11.215736, 179.576447, 7.406021]
Velocity: [-730.844238, 2096.098145, 4645.688477]
Angular Velocity: [-89853.562500, -34246.089844, -551.606995]
Defusing!
Removing!
```

Note that my server.cfg contains those 2 lines required by ACF ( https://acf.googlecode.com/svn/INSTALL%20FUCKING%20READ%20THIS.txt )

```
lua_run local tbl = physenv.GetPerformanceSettings() tbl.MaxAngularVelocity = 30000 physenv.SetPerformanceSettings(tbl)
lua_run local tbl = physenv.GetPerformanceSettings() tbl.MaxVelocity = 20000 physenv.SetPerformanceSettings(tbl)
```

**Comment by robotboy655** [comment]
Don't set ```sv_crazyphysics_defuse``` to ```0``` if you wish to avoid crashes.

**Comment by UltimateByte** [comment]
Thanks for the advice.
What does it do exactly ? Stops props movements ?

**Comment by ViperPlay** [comment]
@robotboy655 so how to fix that?
