### ISSUE TITLE
Why is My Option looking weird why can i see my recentguns

### ISSUE THREAD

**Issue by ProblemMate** [Facepunch/garrysmod-issues#2469]
hi yday i wanted to type unbind and i typed unbind all everything fucked up i went to the options and press defaults setting and still i can't seem to find the consol option there anymore i wanted to bind all againor type config_default but still i never seen this before and why do i see what guns iv'e been using before  and why cant i find toggel consol option in the OPTIONS fack my life and i just got a co for 212th please anyone find something to fix this and one more thing when i click advance setting i can see the consol but still do not know where to press to toggel it not say fix any key for it it just a check box. and why can't i use c on the server so i can enable third person..

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
