### ISSUE TITLE
What Happened with the mounting function?

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2470]
I see there is no message on the console if I am playing on a hl2 map or ep1 or ep2.
It doesnt say Half Life 2 mounted.
Or other games.

**Comment by willox** [comment]
Sorry I had to hold it back. Should return in the future.

**Comment by kem008** [comment]
Please put this back it was awesome to see in the next update without this all hl2 ep1 ep2 maps are unplayable.

**Comment by willox** [comment]
I know it's great. I need to figure out a better way to dump the cached sounds, materials, and models once the game changes though.

**Comment by kem008** [comment]
Great news thanks keep up the good work :+1:

**Comment by daunknownman2010** [comment]
You could make the mounting function only override HL2, EP1, EP2 content and leave the other games to mount like normal. So when you start a EP1 map, it prioritises EP1. When it's another map, it uses legacy mounting. It's useless prioritising Counter-Strike Source, Day of Defeat, L4D, etc.

**Comment by robotboy655** [comment]
@daunknownman2010 , That's not the problem.
