### ISSUE TITLE
game.MountGMA large file crashing

### ISSUE THREAD

**Issue by LynxstormDEV** [Facepunch/garrysmod-issues#2476]
So the title kinda says it all, When using game.MountGMA on a server to allow the player to download stuff while playing on it, it can cause crashes if the file is big.

**Comment by willox** [comment]
Are you able to give me the GMA you are using?

**Comment by LynxstormDEV** [comment]
Can give the Collection, basically just adding all the different workshop files separately
http://steamcommunity.com/sharedfiles/filedetails/?id=593229601

**Comment by Seba0702** [comment]
Clients on my server crash as well sometimes with this. And player models that are being downloaded will go from error to a glitched version of the playermodel. To resolve this the client experiancing this glitch have to rejoin or the server have to restart map or server.

**Comment by willox** [comment]
If that is the cause for crashing it should be fixed in the dev branch

**Comment by FFG-Blinkenn** [comment]
I personally have also had issues with mountGMA to the point of not using it because of the issues it can cause, (https://www.youtube.com/watch?v=KrbMSRNBdsc [skip to 1:00]) this gets all removed after removing any addons using mountgma, it would also be inconsistent with players crashing (sometimes to desktop)

**Comment by willox** [comment]
If you start up your client and server both on the dev branch, do you get any issues?

**Comment by FFG-Blinkenn** [comment]
Ran it in dev branch didnt get any crashes when running large gma's

**Comment by willox** [comment]
I don't know if the crashes were ever caused by large files then. I think it was just people having issues with ragdolls/vehicles (which should be fixed).
