### ISSUE TITLE
Sending too much data on spawn results in the client receiving the wrong stuff?

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2478]

**Comment by mcd1992** [comment]
I've noticed a similar issue on Linux clients where too many net messages sent before the player is fully in the game can cause crashes. Might be related.

**Comment by thegrb93** [comment]
Only issues I saw were NWVars being wrong which is why I moved them to a timer.

**Comment by willox** [comment]
It's an old issue. I haven't gotten around to looking at it yet but if anybody knows a way to reproduce it easily just say.
