### ISSUE TITLE
Workshop Download/Extracting Issues during loading screen.

### ISSUE THREAD

**Issue by MichaelTheLongo** [Facepunch/garrysmod-issues#248]
Well, when I try to join my usual server, the loading screen pops up like usual. Then it says "Downloading Raid and Print DarkRP Content" then it says "Extracting Raid and Print DarkRP Content" and then it says "Extracted Raid and Print DarkRP Content" and then it just crashes to desktop. Any ideas?

**Comment by robotboy655** [comment]
The entire system was changed, and it was probably out of memory crash.
