### ISSUE TITLE
Pause Bug (Multiplayer)

### ISSUE THREAD

**Issue by Happy-friend1337** [Facepunch/garrysmod-issues#2481]
If cvar **sv_pausable = 1**
Any player can pause, but... unpause _not working_ at clientside or serverside :D
PS. Why it's work as game_end?

Fuckin' helmet

**Comment by willox** [comment]
The naming of these console commands is slightly misleading. "unpause" is not related to pause.

If you want to unpause the game, just run the "pause" command again (it's a toggle).
