### ISSUE TITLE
Game crashing when mounting content while it's active

### ISSUE THREAD

**Issue by Beeperdp** [Facepunch/garrysmod-issues#2483]
I pulled this video which shows what happens:

https://www.youtube.com/watch?v=Ayt82f6nUZo&feature=youtu.be&t=50s
(I didn't make the video, but I have the same issue and so do others)

Basically, if you mount the GMA while you are looking at it, it will crash your game. I have tried lots of different things and it seems this cannot be fixed by editing the code, and that it is an issue with GMOD.

**Comment by willox** [comment]
Please try on the dev branch

**Comment by Beeperdp** [comment]
Dev branch seems to have fixed this issue entirely, thanks for keeping everything working :D

**Comment by willox** [comment]
:+1:
