### ISSUE TITLE
Rewrite Global Variables (Clientside)

### ISSUE THREAD

**Issue by Happy-friend1337** [Facepunch/garrysmod-issues#2484]
CLIENT_DLL,GAMEMODE,_G,_MODULES,_VERSION,CLIENT,CLIENT_DLL,SERVER,GAMEMODE_NAME,NULL,VERSION,VERSIONSTR,BRANCH = `nil`
Or_
CLIENT_DLL,CLIENT,SERVER = `true`

**What for, this?**

**Comment by willox** [comment]
What do you want to know?

**Comment by Happy-friend1337** [comment]
@willox hehe, it or not joke?

**Comment by robotboy655** [comment]
Я так понимаю, что Вы Русский, как насчёт рассказать о своей проблеме на Русском?

**Comment by Happy-friend1337** [comment]
@robotboy655 Я просто хочу знать зачем давать возможность клиентам перезаписывать глобальные переменные :D

**Comment by robotboy655** [comment]
Это стандартная фича языка Lua. Никто специально не делал это возможным.
