### ISSUE TITLE
The new Feburary 2016 update

### ISSUE THREAD

**Issue by Flash21** [Facepunch/garrysmod-issues#2486]
After the update I have no sound when I use weapons the walking sound is different theres no pictures on the scroll menu when you switch weapons and no sounds also the scrolling is messed up on it i verified the integrety cache and it said 8 files failed and they were fixed I did it again and it said it was fine so I and it had same problem so I did it again and it said 1 failed and will be fixed then I did it again it said it was fine I and same problem and it keeps doing the same thing now.

The time my gamer started doing this was after the two Feburary 2016 updates.

**Comment by Kefta** [comment]
Do you have any content packs in your addons?

**Comment by Flash21** [comment]
Yea

**Comment by Kefta** [comment]
Delete them

**Comment by Flash21** [comment]
Ok

**Comment by Flash21** [comment]
I don't think it does but does m9k weapons count

**Comment by robotboy655** [comment]
This is not a place to get help. What makes you think this is a place to get help?
