### ISSUE TITLE
Crazy physics removing elevator physics box that is used to detect when elevator is on correct floor

### ISSUE THREAD

**Issue by KGoodale13** [Facepunch/garrysmod-issues#2487]
Crazy physics seems to be removing the physics box on the elevator on the map rp_evocity2_v2p this physics box is used by the map to detect when the elevator is on the correct floor, so as a result the elevator just goes up and down and never stops. Maybe you could allow us to whitelist some items by entity ID or whitelist any crazy physics that occur within X seconds of the server starting as they will be part of the map.

Crazy origin on entity [1154][func_physbox]
	Origin:           [-249.700012, -2178.780029, -16405.470703]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, -993.168579]
	Angular Velocity: [0.000000, 0.000000, -0.000000]

**Comment by willox** [comment]
This appears to already be fixed in the dev branch
