### ISSUE TITLE
Flickering triangles when drawing meshes with normalmapped materials

### ISSUE THREAD

**Issue by uldislazdins** [Facepunch/garrysmod-issues#2489]
There's a bug with the mesh library that causes triangles to flicker when using a VertexLitGeneric material that has a $bumpmap. It can be fixed by specifying an IMesh as the first argument for mesh.Begin and drawing the IMesh instead. The same bug applies to render.DrawQuadEasy.

EDIT:

It also seems that the normalmap isn't used when drawing meshes. Here's a screenshot:
http://i.imgur.com/tOQoKoo.jpg

The plug (a regular entity) uses the same material (models/flesh) as the pipe (a mesh drawn using IMesh and the mesh library). It's clear that the plug has a normalmap while the pipe does not. I use MATERIAL_QUADS, mesh.Position, Normal and TexCoord to draw the mesh. The mesh is drawn inside ENT.Draw.

**Comment by willox** [comment]
Can you supply code that will reproduce the issue?

**Comment by uldislazdins** [comment]
http://pastebin.com/5bAYbsUE

For me it looks something like this: http://imgur.com/qIYFnd8

The flickering is hard to screenshot.

The quad with the correct normalmap is the one that should flicker (drawn using mesh library only). The other glossy quad does not flicker, but does not have a normalmap either (drawn using IMesh). The other two quads use a material that does not have a normalmap. Both do not flicker. Calling Mesh with a material does not change anything.

The flickering type/pattern also changes when switching weapons.

The problem does not seem to depend on the GPU. I tested on a GeForce 525M and a Radeon HD 5870 - same problem.

**Comment by thegrb93** [comment]
IMesh seems to not even support normals anymore. What happened?

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/issues/382

**Comment by willox** [comment]
This is fixed on GMod's dev branch if you pass tangent data in to the mesh's vertices. Don't be fooled by `mesh.TangentS`, `mesh.TangentT`, or IMesh:BuildFromTriangles's `tangent`/`binormal` parameters, cuz they aren't what you need.

You can either `mesh.UserData( tangentX, tangentY, tangentZ, tangentHandedness )` or `vertex.userdata = { tangentX, tangentY, tangentZ, tangentHandeness }` depending on how you're making your mesh. It might seem a little odd, but this is just how models in source do it and how the shaders expect to get the data.

You can see an example @ https://github.com/CapsAdmin/pac3/pull/578.

![](https://files.facepunch.com/willox/2018-02-15/Va4tm0GK.png)

And yeah, this still needs documenting on the wiki.
