### ISSUE TITLE
Gmod server settings problems

### ISSUE THREAD

**Issue by killerpandabomb** [Facepunch/garrysmod-issues#249]
whenever i start a new game on 2, or more, players (using hamachi) my settings aren't used. i.e. when i set the vehicle limit to 100, then i go into the game and i hit the vehicle limit at 3, this also happens with npc's, not sure about anything else though.

i set the vehicle limit to 100 (along with everything else because that's what i usually do)

![2013-07-09_00003](https://f.cloud.github.com/assets/4975957/770379/4566bb3c-e8cb-11e2-82c6-b0d467080b36.jpg)

then when i try to spawn 4 vehicles, it stops at three and tells me i hit the vehicle limit

![2013-07-09_00008](https://f.cloud.github.com/assets/4975957/770380/4a4e241e-e8cb-11e2-9ef6-a4c3093903f2.jpg)

please help!

**Comment by robotboy655** [comment]
Correct me if I am wrong, but this seems to be fixed in the Dev branch at least?
