### ISSUE TITLE
I can't see any of my hud

### ISSUE THREAD

**Issue by Derpyfish1095** [Facepunch/garrysmod-issues#2493]
So I'm playing the game and then I leave for like 15 mins then I crash and I'm like ok normal gmod response then I start back up and then I was like hmmm I can't the the little   .:. Thing and I was like ok I'll just reset and then I noticed my health was gone and at this point I'm panicing I'm like omg my gmod hates me was it says something I sad? So I was like ok just reinstall I was convinced that this would work so I was like waiting for it and it finally finished  and I opened it up thinking it was going to work and guess what it didn't so I'm sad very sad at this point I almost cried a little all of these thoughts where going through my head about the first time I got the game and I did in fact shed a tear so I was like no man up so I decided to make a issue report so yeah can't see my hud and if there Is a fix I would love to know so yeah thanks for the help :D have a nice day/night

**Comment by Kefta** [comment]
Delete your garrysmod folder, turn off Steam cloud sync, and reinstall. Also, for future reference, this is not the place for issues. Go here instead: https://facepunch.com/forumdisplay.php?f=16
