### ISSUE TITLE
RecipientFilters can have NULL players in them.

### ISSUE THREAD

**Issue by mcd1992** [Facepunch/garrysmod-issues#2494]
Currently if a player is in a RecipientFilter and then leaves their entity userdata becomes NULL and the RecipientFilter will return a NULL userdata in GetPlayers. We also can't remove the NULL player with RemovePlayer() because it asserts that the player is valid. 

Can we get RemovePlayer to allow NULL or even better get GetPlayers to only return valid players?

**Comment by robotboy655** [comment]
GetPlayers will now only return valid players.

**Comment by mcd1992** [comment]
Thanks
