### ISSUE TITLE
Source Engines VGUI Build Mode & LUA VGUI

### ISSUE THREAD

**Issue by NavyCo** [Facepunch/garrysmod-issues#2496]
Source Engines [VGUI Build Mode](https://developer.valvesoftware.com/wiki/VGUI_Documentation#Build_mode) & LUA VGUI kinda are buggy when used together... It decides to do some ugly mess with the colors... I'd like a fix due to the usefulness of the VGUI Build Mode.

**Comment by robotboy655** [comment]
They are not meant to be used together. That tool is for valve's gui .res files.
