### ISSUE TITLE
Crash: GetFlexName with some negative values

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#2499]
using a ragdoll of Alyx Vance, running `alyx:GetFlexName(-1)` to `alyx:GetFlexName(-21)` will produce weird three-letter results (shown from -1 to -21 below). Below that, some values seem to return an empty strings (-22, -26, -27), while others crash the whole game (-23, -28, -30). I made no attempt to map it out as re-launching the game after every crash is very time-consuming.

Confirmed on both live and dev. Windows 10.

```
rop
sor
art
pen
D32
13L
7ZR
26L
U32
18L
U9R
0CL
14R
25L
U4R
U2L
U1R
ral
rer
ght
lyx
```

**Comment by robotboy655** [comment]
Made it return nothing if given id is < 0. Same goes for GetFlexBounds, just in case.
