### ISSUE TITLE
Clientside Ragdolls don't support flex (face posing)

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#2500]
I'm posting this here in the blind hope that it would be an easy fix. Clientside Ragdolls, created with _Entity:BecomeRagdollOnClient_ or with _ClientsideRagdoll_, do not support flex. _Entity:HasFlexManipulatior_ returns **false**, and none of the flex functions do anything.

**Comment by robotboy655** [comment]
Possible duplicate of #1779

**Comment by Kefta** [comment]
Definitely a duplicate of #1779
