### ISSUE TITLE
resource.AddWorkshop Not Checking If Content Has Been Updated

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-issues#2501]
I've been able to replicate this issue on my own computer by completely unsubscribing and deleting the addon in question from my game.

On my server I use resource.AddWorkshop() for two addons:
One contains the map in which the server uses
The other contains content that the gamemode requires

If clients are not physically subscribed to the addons specified by resource.AddWorkshop, and those addons are updated, upon rejoining the server these clients will still have the old, cached, version of the content from when it was originally downloaded through resource.AddWorkshop.

This is especially frustrating since the map is downloaded this way and returning clients are unable to join due to receiving
`your map [maps/map_name.bsp] differs from the server's.`

Having clients go to the workshop and subscribe then reconnect remedes this however it defeats the entire purpose of the feature.

I've been able to recreate this issue multiple times over different client and server installations.

**Comment by robotboy655** [comment]
This is fixed in Dev as far as I am aware.

**Comment by kklouzal** [comment]
Okay I really hope so!

I want to add some info to the bug. If the user is subscribed but has the addon DISABLED the issue is not there since a disabled addon will still update itself.
