### ISSUE TITLE
table.sort doesn't go through table[ 0 ]

### ISSUE THREAD

**Issue by Netheous** [Facepunch/garrysmod-issues#2503]
table.sort doesn't seem to take anything whats under [ 0 ] into consideration, it's most likely starting from [ 1 ].

When I had my values added via:
`table.insert( first, second )`
The thing under 0 was always on top, despite the sorting function.

When I added values manually via:
`first[ #first + 1 ] = second`
It started working flawlessly (because first thing was under [ 1 ] and not [ 0 ])

**Comment by willox** [comment]
>Sorts table elements in a given order, in-place, from table[1] to table[n], where n is the length of the table. If comp is given, then it must be a function that receives two table elements, and returns true when the first is less than the second (so that not comp(a[i+1],a[i]) will be true after the sort). If comp is not given, then the standard Lua operator < is used instead.

>The sort algorithm is not stable; that is, elements considered equal by the given order may have their relative positions changed by the sort.

>- http://www.lua.org/manual/5.1/manual.html

Why do you expect it to work differently?

**Comment by Netheous** [comment]
Well, it's not on Gmod wiki - I believe it should be included there to prevent confusion.

**Comment by Bo98** [comment]
> When I had my values added via:
> `table.insert( first, second )`
> The thing under 0 was always on top, despite the sorting function.

But `table.insert` starts at 1?

**Comment by neico** [comment]
Sounds to me that he wasn't aware that lua in general starts arrays / tables on 1 not 0 like most other languages do, and unless gmod has a serious oversight (bug) somewhere this should apply to every gmod specific function as well.

Funny enough, this statement is only vaguely mentioned in the manual, but pretty much on the bottom of PiL it states it a bite more concretely: http://www.lua.org/pil/2.5.html

**Comment by Netheous** [comment]
Your attempt to patronize me is amusing.

Especially since you replied to an already closed ticket.
