### ISSUE TITLE
showfps and showpos text is so small

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2506]
I am using `1440x900` `16:10` in Windowed mode.
I am using Dev Branch

Version:
`
Protocol version 24
Exe version 16.02.26 (garrysmod)
Exe build: 04:24:18 Mar  7 2016 (6324) (4000)
`

[Screenshot](http://i.imgur.com/nzTIFEV.jpg)

--

As you can see I am using `cl_showfps 1` and `cl_showpos 1` and the text is pretty small then the previous version had.
[Old Screenshot](http://i.imgur.com/5rNUIty.jpg?3)
In the top right corner you can see the previous version of the text size was much higher and wider ( maybe just wider.)

**Comment by willox** [comment]
is this OSX?
