### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by L1V1NGH311** [Facepunch/garrysmod-issues#2509]
So I used to play Garry's mod a lot. And recently (at about 8 this morning, UTC+12:00) I was unable to load Garry's mod. Instantaneous crash when I click 'Play'. The main forum about it says I should receive a .mdmp file. I searched the entire Garry's mod folder and there was nothing. I really would like this to hopefully be fixed.

**Comment by robotboy655** [comment]
This is not a place to get help.

http://support.facepunchstudios.com/kb/articles/6-i-get-crashes-on-start-or-the-screen-is-just-black
