### ISSUE TITLE
fonts don't seem to download with FastDL this update

### ISSUE THREAD

**Issue by Splerge** [Facepunch/garrysmod-issues#2510]
to reproduce:
get a custom font
install it on your gmod, add it to fastdl and AddResource it
test it out, should work (I found this with MantleHud's opensans-bold.ttf)
delete the file on your gmod
now join, font will be broken

no idea if this is a problem on workshop as well but it probably is considering people always have workshop font issues

**Comment by willox** [comment]
Installing fonts to garrysmod/download/resource/fonts/... is working fine for me. Can you confirm that the file is downloading from your server to that directory?

**Comment by Splerge** [comment]
Yeah I'll see if it's downloading at all

**Comment by Splerge** [comment]
It's not downloading. it is added like this:
resource.AddFile("resource/fonts/opensans-bold.ttf")
serverside and the file is correctly located on the FastDL as <root>/garrysmod/resource/fonts/ it works for everything else.

**Comment by willox** [comment]
What do you have sv_downloadurl set to?

**Comment by Splerge** [comment]
It's set to the fastdl, I know the fastdl is set up correctly because the maps are downloaded through there just fine and have been for the entire life of the server, it's just now that I've been having trouble with fonts (cleared my download folder yesterday and noticed this, got 2 others to confirm)

**Comment by robotboy655** [comment]
Just tested it with this code:
```if SERVER then resource.AddFile("resource/fonts/opensans-bold.ttf") end```

Your exact file name and it works perfectly.
