### ISSUE TITLE
Patch materials always error when created using CreateMaterial

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2511]
Works (VMT):

```
patch
{
    include materials/models/shiny.vmt
}
```

Does not work (Lua):

``` lua
CreateMaterial("testpatchmat", "patch", {
    ["include"] = "materials/models/shiny.vmt"
})
```

**Comment by willox** [comment]
This is pretty much intended behaviour. I suppose it might be worth fixing.

**Comment by xaviergmail** [comment]
Have you figured a workaround in the meantime?

**Comment by thegrb93** [comment]
Have you tried doing it with the parameters directly instead of using 'include'?

**Comment by willox** [comment]
It's 100% intended. Patch materials are implemented as a sort of pre-processing of material files rather than being an actual shader.

**Comment by xaviergmail** [comment]
Interesting. Is it possible to load VMTs from the data folder then?

**Comment by willox** [comment]
I never mentioned doing so

**Comment by xaviergmail** [comment]
Ah yes I did. I'll try that instead, thank you.
