### ISSUE TITLE
crouch key stuck when holding

### ISSUE THREAD

**Issue by robthedude** [Facepunch/garrysmod-issues#2512]
hello,

yesterday i was playing darkrp when suddenly my crouch key get's stuck in a way it seems like i get pressed in the ground, it suddenly happened and my key itself didn't break at all, infact only in gmod my key does that.

also a gmod addon is stuck with updating, it keeps going back in the queue, i already restarted steam and verified the content of gmod but it's still broken

please help me as i have no clue what coused this or how to fix it

thanks in advance

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
