### ISSUE TITLE
EntityFireBullets outputting wrong damage

### ISSUE THREAD

**Issue by Mysterypancake1** [Facepunch/garrysmod-issues#2517]
```
hook.Add("EntityFireBullets","FireBulletsTest",function(ply,tbl)
        print(tbl.Damage)
end)
```

Seems to print 0 in the console no matter how much damage is actually caused by the weapon.

But, it also seems to print the correct value if the weapon is a SWEP. Could this be fixed?

(This request was from [this thread](https://facepunch.com/showthread.php?t=1510954) and I thought I may as well post it here)

**Comment by robotboy655** [comment]
IIRC it is 0 only for HL2 weapons, because it will apply different damage to a player or an NPC.

**Comment by Jvs34** [comment]
Yeah the damage for hl2 weapons is calculated after the hook because it uses the value from the ammo type.
