### ISSUE TITLE
Serverside bonemerging causes entities to disappear

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-issues#2518]
It seems that bonemerging on the server is seriously broken. If you bonemerge entities, leave the pvs (or stop rendering them?) and come back, it sometimes makes all entities on the map disappear. The same happens if a full client refresh is requested (such as recording a demo).
This also seems to be caused by the bug:
![ss 2016-03-19 at 12 38 23](https://cloud.githubusercontent.com/assets/1258762/13898384/a19138b8-edcf-11e5-9470-98244ebab5ca.png)

Bonemerging clientside models to serverside models does not appear to cause this issue.

Video of it happening:
https://www.youtube.com/watch?v=ZBLrvqS1t50

Code and steps to reproduce it (on flatgrass):
```lua
for i = 0, 100 do
	local rootShard = ents.Create("prop_physics")
	rootShard:SetPos(Vector(0, 0, -12200) + VectorRand() * 500)
	rootShard:SetModel("models/props_c17/FurnitureDrawer001a_Shard01.mdl")
	rootShard:Spawn()
	local shard1 = ents.Create("prop_dynamic")
	shard1:SetModel("models/Items/item_item_crate_chunk02.mdl")
	shard1:SetParent(rootShard)
	shard1:AddEffects(EF_BONEMERGE)
end
```
Either noclip below the structure on flatgrass and come back up or start recording a demo after running above code on the serverside.

**Comment by robotboy655** [comment]
Should be better in Dev
