### ISSUE TITLE
markup.Parse / utf8.offset bad index to string when at 1280x1024

### ISSUE THREAD

**Issue by Kogitsune** [Facepunch/garrysmod-issues#2519]
String in question: <font=ChatFont><color=white>You can jump off walls <color=ltgreen>0</color> times in a row. Hold the move key in the direction desired and jump. Also, take <color=ltgreen>0</color> less fall damage.</color></font>

Code:

`markup.Parse( "<font=ChatFont><color=white>You can jump off walls <color=ltgreen>0</color> times in a row. Hold the move key in the direction desired and jump. Also, take <color=ltgreen>0</color> less fall damage.</color></font>", 830 )`

830 is the value of `math.min( 1080, self:GetForceW( ) or 600 ) )`, which only happens for users of my code running at a screen width of 1280. This issue does not occur if you run 1280x960, which has the same 830 forcew value, and also does not occur on other x1024 resolutions.

> [ERROR] lua/includes/modules/markup.lua:363: bad index to string (out of range)
>   1. error - [C]:-1
>    2. offset - lua/includes/modules/utf8.lua:234
>     3. Parse - lua/includes/modules/markup.lua:363

When this happens, curString is empty and lastSpacePos is 0.

**Comment by willox** [comment]
I thought this was fixed. At least there's some proper code to reproduce it this time, I'll take a look.

**Comment by willox** [comment]
The height of the string is determining the size of ChatFont which explains why it only happens on certain resolutions. As for the actual issue, you should be able to fix it now by modifying line 362 in your server's markup.lua to be:

```lua
if (lastSpacePos == string.len(curString) && lastSpacePos > 0) then
```

The fix will also be on the dev branch soon enough.
