### ISSUE TITLE
Player:AnimSetGestureWeight() does not work properly

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#2521]
It's hard to explain the exact issue, so here's a video.

https://dl.dropboxusercontent.com/u/41867685/Sharex/pics032016/2016-03-19_21-19-40.mp4

Because there's no way to play gestures in a way that "Fades in" like other sequences, I attempted to use AnimSetGestureWeight() to gradually set the weight from 0 to 1. However, I discovered that the weight does not actually set the influence of the gesture, but really does nothing. The most it can do is not delay the gesture until the weight gets set to > 0.5

Anyways, thanks for looking at this. Been porting animations all day and I got pretty disheartened when I found out how hard it is to do something as simple as gradually transitioning in a gesture.

Here's my code by the way.

```
function pmeta:DoGesture(slot, gesture, loop, fade, startw, endw)
	local start = CurTime()
	local CurW = startw or 0
	self:AnimRestartGesture(slot,gesture,loop)
	self:AnimSetGestureWeight(slot, CurW)
	hook.Add("Think", "GestureTrans_"..start, function()
		if CurTime() > start + 5 or CurW >= 1 then
			hook.Remove("Think","GestureTrans_"..start)
			self:AnimSetGestureWeight(slot, CurW)
			return
		end

		fade = fade or 2

		CurW = math.Round(math.Approach(CurW, endw or 1, FrameTime() * fade),2)
		print("Current Weight: ",CurW)
	end)
end
```

**Comment by robotboy655** [comment]
You are only calling AnimSetGestureWeight twice in your code? ( i.e. Not every frame the animation is going, only on start and end )

**Comment by bizzclaw** [comment]
**Wow**... I just woke up, read the code and noticed that instantly before checking back here... I'm so stupid lol. I must of been brain dead from porting and blending animations all day.

Anyways, it works. so sorry I made this post in error.
