### ISSUE TITLE
Crashing within 5 minutes of joining a server

### ISSUE THREAD

**Issue by Nightan** [Facepunch/garrysmod-issues#2523]
My garry's mod lets me play single player just fine but when I join a multiplayer game it either lets me play for 30 seconds or 5 minutes. I have all the addons the server needs, CS: Source, L4D2, and tf2. I can't find a absolute fix anywhere...

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
