### ISSUE TITLE
Clientside ents.FindByModel doesn't work.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2524]
When I have 10 of these props, it just prints 1	=	CSEntity [class C_BaseFlex]

lua_run_cl PrintTable(ents.FindByModel("models/Combine_Helicopter/helicopter_bomb01.mdl"))

If I make the C and H lowercase then it prints nothing.

**Comment by robotboy655** [comment]
Will be fixed.

**Comment by thegrb93** [comment]
Ran into this again
`lua_run PrintTable(ents.FindByModel("models/props_c17/furnituremattress001a.mdl"))`
1	=	Entity [88][prop_ragdoll]
`lua_run_cl PrintTable(ents.FindByModel("models/props_c17/furnituremattress001a.mdl"))`
<nothing>

**Comment by meepen** [comment]
Isn't this just pvs? Entities don't exist clientside until you first see
them / are informed of them

**Comment by thegrb93** [comment]
I was looking at it so it definitely existed.

**Comment by meepen** [comment]
I don't think this is the same issue though, the original issue was that upper case and lower case was differentiated in the function, but now you are saying they aren't the same between states.

**Comment by thegrb93** [comment]
It is different, but the title matches.

**Comment by meepen** [comment]
The title is shit (non informative) and you have no way to reproduce or any other self diagnostics such as trying to find the entity yourself without that function, we have no information to go off of

**Comment by thegrb93** [comment]
I posted the reproduction code, go fuckyourself

**Comment by meepen** [comment]
![image](https://user-images.githubusercontent.com/6186313/58379361-385a0880-7f70-11e9-89d3-9a7a665c308f.png)
Very good reproduction code.

**Comment by thegrb93** [comment]
Do it in dedicated server

**Comment by meepen** [comment]
![image](https://user-images.githubusercontent.com/6186313/58379429-29278a80-7f71-11e9-8720-984de8f97ed5.png)

**Comment by thegrb93** [comment]
What OS? Windows server and windows client.

```
] lua_run_cl PrintTable(ents.FindByModel("models/props_c17/FurnitureMattress001a.mdl"))
] lua_run_cl PrintTable(debug.getinfo(ents.FindByModel,"S"))
lastlinedefined	=	-1
linedefined	=	-1
short_src	=	[C]
source	=	=[C]
what	=	C
] lua_run_cl PrintTable(ents.FindByModel("models/props_c17/FurnitureMattress001a.mdl"))
] lua_run_cl PrintTable(ents.FindByModel("models/props_c17/FurnitureMattress001a.mdl"))
] lua_run_cl print("hi")
hi
] lua_run_cl PrintTable(ents.FindByModel("models/props_c17/furnituremattress001a.mdl"))
```

**Comment by thegrb93** [comment]
Doesn't work with any model btw.
```
] lua_run_cl PrintTable(ents.FindByModel("models/props_lab/*"))
] lua_run_cl PrintTable(ents.FindByModel("models/props_lab/blastdoor001c.mdl"))
```

**Comment by meepen** [comment]
Windows Server and Windows Client. I didn't override ents.FindByModel either

**Comment by thegrb93** [comment]
Well what the fuck then

**Comment by meepen** [comment]
What's your client version? Have you tried running `lua_run_cl print(Entity(x))`?

**Comment by thegrb93** [comment]
Latest stable release, print(Entity(x)) works as expected.

**Comment by robotboy655** [comment]
Does the model name appear in the server's console when using "dumpgamestringtable" in on a Dev-branch server for you?
