### ISSUE TITLE
util.TableToJSON discarding data in non sequential tables that have a nil first value

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-issues#2525]
When calling util.TableToJSON on an non sequential table that has a nil first key, data is discarded.
```
] lua_run print( util.TableToJSON( { [ 2 ] = 1, [ 3 ] = 2, [ 5 ] = 3 } ) )
> print( util.TableToJSON( { [ 2 ] = 1, [ 3 ] = 2, [ 5 ] = 3 } ) )...
[1,2]
```
The expected result should be something like this:
```
{"2":1,"3":2,"5":3}
```
Please fix, this has been causing a very confusing data loss situation in one of my addons for a few weeks now.

**Comment by willox** [comment]
Any tables that aren't a valid sequence with no extra keys will now output as objects like you ask

**Comment by Diamondjack77** [comment]
Well this explains my issue, Will this be included in the next update?

**Comment by robotboy655** [comment]
The issue is closed, it means it has been taken care of.
