### ISSUE TITLE
Non ClearType and non TrueType fonts crashing client

### ISSUE THREAD

**Issue by glebqip** [Facepunch/garrysmod-issues#2529]
For example:
surface.CreateFont("CrashTestFont", {
  font = "System",
  size = 32,
  weight = 400,
  blursize = 0,
  scanlines = 0,
  antialias = false,
  underline = false,
  italic = false,
  strikeout = false,
  symbol = false,
  rotary = false,
  shadow = false,
  additive = false,
  outline = false
})
hook.Add("HUDPaint","FontsCrashTest",function()
  draw.DrawText("Test","CrashTestFont",ScrW()/2,ScrH()/2,Color(255,255,255))
end)

When we run it on client, we get a crash. If we replace System to Arial, all be fine. I tested it with System and Fixedsys fonts

**Comment by Noiwex** [comment]
ClearType is rendering technology, not font format.

**Comment by willox** [comment]
The game only supports TrueType fonts. I'll fix the crash.
