### ISSUE TITLE
GM.PlayerDeathSound plays SLAM click sound instead of muting death sound at all

### ISSUE THREAD

**Issue by Necrossin** [Facepunch/garrysmod-issues#2531]
Started happening after the March update.

If you return true in PlayerDeathSound hook - player will now emit "weapons/slam/buttonclick.wav" sound on death, instead of having no death sound at all. 
Happens in all gamemodes, including base and sandbox (if you override this function to return true).

**Comment by Jvs34** [comment]
Happens due to hl2 deathmatch player trying to detonate slams on death.

**Comment by Jvs34** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2mp/hl2mp_player.cpp#L1234


https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2mp/hl2mp_player.cpp#L1219

**Comment by Jvs34** [comment]
CWeapon_SLAM::SatchelDetonate doesn't call back to CHL2MP_Player::DetonateTripmines so it's safe to remove the EmitSound from CHL2MP_Player::DetonateTripmines

**Comment by robotboy655** [comment]
Will be taken care of.
