### ISSUE TITLE
Model missing since the revert

### ISSUE THREAD

**Issue by Sachha** [Facepunch/garrysmod-issues#2533]
Hi, 

I've a lot of model that are missing in my server with the revert of the March Update and i'm not alone.
This is basic Gmod model like  : 
Model missing: models/nova/airboat_seat.mdl

I'm on a Linux distribution

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/14144193/5787c752-f697-11e5-9ee3-4f2f4f40941e.png)

It's still there.

**Comment by Sachha** [comment]
... Told you that i'm on a Linux distribution (on my server). It work on in Local (Windows)

This guy got the same problem and explain that's it's a case sensitive problem : https://facepunch.com/showthread.php?t=1250302&p=40892759&viewfull=1#post40892759

**Comment by robotboy655** [comment]
That report is from 2013.

Besides, if it worked after the update before revert ( I am assuming it didn't work before the update ), then it will be fixed whenever we ship that update again.

**Comment by Sachha** [comment]
I've reinstalled a fresh installation on another Linux server and same problem appear, so it's a gmod problem.

Also NPC entity have some trouble : http://images.akamai.steamusercontent.com/ugc/510404625797648098/07F065C3BC159C4528007369F2AC24C1951148AC/

They spawn like that. It's probably specific to Linux but most of the server run on Linux.

Hope that you will found what happening

**Comment by mcd1992** [comment]
I don't have this issue on the dev branch with Linux server and client.

Actually re-install and don't put your addons back in until after you test its working with pure vanilla gmod.

**Comment by Sachha** [comment]
I've installed another server (completly vanilla, no workshop/addon/gamemode) and there is the same problem ... Some model missing (maybe corrupted), NPC have a strange position ...

**Comment by mcd1992** [comment]
What model and NPC.

**Comment by Sachha** [comment]
The update 31/03/2016 fixed my problem! 

I don't know how, why or anything else but it work now ! Thanks x)
