### ISSUE TITLE
NextBots don't appear if spawned in InitPostEntity

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#2535]
By "not appear" I mean they don't exist in ents.FindByClass("mynextbot").

Most notably breaks persisted nextbots.

**Comment by robotboy655** [comment]
They don't spawn on the first map spawn.

**Comment by kem008** [comment]
So thats why it not spawned I though I scripted it wrong. Thanks.
So I should add it to something else like PlayerSpawn but it would be much better with initpostentity.

**Comment by robotboy655** [comment]
Fixed.
