### ISSUE TITLE
Keyboard Bug?

### ISSUE THREAD

**Issue by Nesjob** [Facepunch/garrysmod-issues#2536]
In the keyboard settings missing the option "weapon drop " "sprint" and traitor shop open". Why can a people help me? (German/English)

**Comment by robotboy655** [comment]
TTT/Custom gamemode bindings will obviously not part of the base game.

**Comment by Nesjob** [comment]
NO! The settings not in the complete game, this was example for it in ttt, sprint is not in der commands!

**Comment by robotboy655** [comment]
What commands are you talking about? What are you talking about? The Options > Keyboard menu?

**Comment by robotboy655** [comment]
Oh, I think I know what you mean, you have one of those pirated CS:S addons installed, don't you?
