### ISSUE TITLE
Mouse Acceleration

### ISSUE THREAD

**Issue by TheHamGamer** [Facepunch/garrysmod-issues#2537]
This has only just started the time before the last time I played GMod. My mouse (in the settings, I don't have raw input, I don't have mouse acceleration, and my sensitivity is on 1.06 or something like that) keeps randomly accelerating or maybe changing sensitivity randomly (it goes very high for a split second). I've tried everything in the mouse settings and nothing seems to work. I have looked it up and I don't see anybody with this issue. Does anybody have a fix?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
