### ISSUE TITLE
ConVarExists("maxplayers") incorrectly returns true

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2538]

**Comment by robotboy655** [comment]
This is intentional believe it or not.

**Comment by Bo98** [comment]
What benefit does it provide now that GetConVarNumber no longer works on it?

**Comment by robotboy655** [comment]
I will most likely add backwards compatibility for GetConvarNumber

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/991cb7a2787a20a73926f2fe3736759a94c8a42e
