### ISSUE TITLE
Stack Corruption (on clients): Electric boogaloo

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#2539]
I've managed to find an edge case where some sort of memory stack corruption is happening. 

Essentially
- Join a server
- Have the server time out
- Rejoin (possibly attempt while the server is down).

I can't replicate it 100% of the time but the eventual end result seems to be that the entire clientside Lua state becomes corrupted and the only way to fix it is a complete restart of GMod.

I can confirm that at http://bbroleplay.co.uk/lauerrors/ , errors 1794, 1808, 1858, 1859, 1860 and 1632 all occur during this state of client corruption and never any other time.

**Comment by willox** [comment]
It'd be handy to know any asynch operations your server runs clientside. HTTP, steamworks.Download,  sound.PlayFile/sound.PlayURL, etc.

**Comment by TeddiO** [comment]
No async operations of those kind run on clients (at least that I'm aware of, there is a few surface.PlaySounds here and there but I don't know how those use the sound library).

**Comment by TeddiO** [comment]
Just revisiting this, I am running some HTML panels, however these don't get created until the user has called a certain event.

However I've managed to replicate the issue by causing timeouts. What I have found though is usually a rejoin is enough to fix it, but not always.
