### ISSUE TITLE
gm_video/video.Record doesn't save when disconnecting from the server without stopping

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2540]
```
(FPtje) Falco: fuck I recorded all this
(FPtje) Falco: but then I disconnected
(FPtje) Falco: and poof the recording is gone
(FPtje) Falco: gm_video sucks
```

**Comment by robotboy655** [comment]
gm_video sucks and should not exist. =\

**Comment by robotboy655** [comment]
Uh, it doesnt stop recording when you leave the server and will stop recording and save the file when you exit the game.

**Comment by Bo98** [comment]
So when you rejoin does it just resume? gm_video is broken on OS X and Linux so I was just going by what Falco said.

**Comment by robotboy655** [comment]
It will continue to record until you tell it to stop.

**Comment by Bo98** [comment]
No idea then. I'll talk to him later.
