### ISSUE TITLE
Workshop maps doesnt get automatically send to client after update

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-issues#2541]
Workshop maps doesnt get automatically send to client after update.

**Comment by willox** [comment]
Workshop map downloads work fine for me. What do you mean when you say automatically?

**Comment by uRandomAlex** [comment]
When I add map on server Workshop collection and changelevel to it, it automatically 'resource.AddWorkshop' with Workshop ID of the map. But seeems that it doesn't work. Map don't download, when I trying to connect to my server, and I get kicked with 'Missing map' error.

**Comment by willox** [comment]
Nothing is automatically resource.AddWorkshop'd except for gamemodes.

**Comment by robotboy655** [comment]
It still works.

![image](https://cloud.githubusercontent.com/assets/3299036/14228109/a0ebb0c8-f914-11e5-9956-658d55ebb10e.png)

**Comment by robotboy655** [comment]
Keep in mind the map workshop addon must be mounted on your server, i.e. be in the collection.

**Comment by kem008** [comment]
Why need to use it as gma and not legacy on server?

**Comment by robotboy655** [comment]
Because there's no other way for the server to know what workshop addon the map is from to mark that workshop addon for download, obviously.
