### ISSUE TITLE
Crashes on Garry's mod

### ISSUE THREAD

**Issue by JoleBGV** [Facepunch/garrysmod-issues#2544]
Bonjour
J'ai téléchargé Garry's mod via steam sur un imac de 1To, avec OSX el capitan. Au début tout allait bien, mise à part que, à la palce des personnes, des objets, des armes et des véhicules, il était affiché "ERROR". Il y avait aussi à la palce de la couleur des murs, des routes et des surfaces, des petits carrés rose et noire. J'ai donc voulu télécharger des addons pour essayer de résoudre le problème (je ne sais pas vraiement à quoi sert les addons). J'en maintenant plus de  mille. Et maintenant lorsue je veux rejoindre un serveur dark RP, il crash au chargement, ou bien après quelques minutes de jeu.

Pouvez vous m'éclairer à ce sujet. Merci.

**Comment by kem008** [comment]
You somehow duplicated your posts maybe internet glitch :+1: 
[https://github.com/Facepunch/garrysmod-issues/issues/2545](url)

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
