### ISSUE TITLE
Setting a Nextbot to a certain model causes gmod to freeze after February Update

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#2546]
This is a re-pose from a facepunch thread I wrote, but got absolutely no attention:

So this has been an issue I've been struggling with ever since the February update, but I always just figured it was my fault or it was something I was doing wrong or something wrong with my Nextbot base.
So I started working on a new base from complete scratch, but the issue is not going away and there's only one thing that is the same between the two bases: The model.
Furthermore, what leads me to believe it's the model is that I've tried changing the npc to use a different model and they work fine, no issue, but the second I change them back to the model I want, the game completely locks up.

To put this in perspective, I was using the old 2012 Aftermath Fallout player models ported by Silverlan for this NPC, but, seeing as the source files for that are gone and I figured it was something wrong with the model, I took it upon myself to just re-port all of the animations. I mean I didn't completely waste my time, I use these models for players, not just NPCs, but still even after re-porting every single player holdtype animations, the issue persists.

I'm not sure if it's the number of animations, or maybe I'm compiling the model wrong or something (even though I'm using Gmod's studiomodel.exe), but no matter what I do, ever since the February update, I haven't been able to use these models as NPCs. The only reason I'm posting this now, in April is because I've run out of options and the only thing I can think of is that it's an issue with Gmod.

Here are two videos showing what is happening:

Setting the model on my old NPC base
https://dl.dropboxusercontent.com/u/41867685/Sharex/pics042016/2016-04-05_18-00-29.mp4
Setting the model on my new NPC base
https://dl.dropboxusercontent.com/u/41867685/Sharex/pics042016/2016-04-05_18-08-54.mp4
Setting the model on the test nextbot (npc_tf2_ghost)
https://dl.dropboxusercontent.com/u/41867685/Sharex/pics042016/2016-04-06_20-41-08.mp4

In all instances, the NPC starts out as another model from fallout. I then change nothing but it's model and spawn it and I'm met with a complete lock up of the game (it seems to happen once they start moving). At this point it could stay frozen forever and never recover. Now I understand that this could be my fault because it's my model, but despite that it doesn't change the fact that **it used to work just fine before the update**. If this can't be fixed, I'd love to know if I can somehow revert the part of the server that controls the nextbots back to an earlier point before this issue for just myself somehow, or if anyone knows what I'm doing wrong with these, they could let me know.

Anyways, here's the models if anyone is curious to try it themselves.
https://dl.dropboxusercontent.com/u/41867685/Sharex/pics042016/decay_playertest.zip
I didn't bother including textures, but that shouldn't really be an issue.

I suppose if someone wants to see my QC if they know it has something to do with how I compile my models, send me a PM and I'll let you have a look. I do have to mention that this is my first major attempt at porting an animation system like this, and I have done the best I can without any reference and only the functions on the valve developer wiki as a guide, so my QC won't look super professional.

**Comment by robotboy655** [comment]
Cannot confirm.

![image](https://cloud.githubusercontent.com/assets/3299036/14545956/9ef814ce-02aa-11e6-8823-76bccd986aa1.png)

Using your model, it just freezes for a second loading the gargantuan model and then everything works as expected.
