### ISSUE TITLE
menu_cleanupgmas crash on -noworkshop

### ISSUE THREAD

**Issue by bigdogmat** [Facepunch/garrysmod-issues#2547]
If you have -noworkshop turned on in command line, using menu_cleanupgmas will crash bootil with this error

![ss 2016-04-09 at 12 42 42](https://cloud.githubusercontent.com/assets/7156309/14401844/49efb322-fded-11e5-97a8-342d49629744.png)

And here's the crash log
http://puu.sh/obxsQ/205b25140c.mdmp

**Comment by robotboy655** [comment]
Done.

**Comment by bigdogmat** [comment]
Thanks!
