### ISSUE TITLE
Bug de luminosité en multijoueur

### ISSUE THREAD

**Issue by ShoowChoco** [Facepunch/garrysmod-issues#2549]
Bonsoir/Bonjour.

J'ai récemment eu un bug de luminosité sur un serveur gmod. Le blanc et les couleurs vives sont vraiment lumineuses donc ça me dérange quand je veux jouer. Un joueur m'a dit de taper une commande dans la console (je ne m'en rapelle plus c'etait du genre blablabla_blabla er le numéro 0) mais mon jeu a crash et depuis je ne peux plus me connecter sur le serveur en question, mais je peux me connecter sur d'autres serveurs.

**Comment by BillyOnWiiUIn144p** [comment]
Why do you think we speak French

Why does almost every French person think everyone can speak French

I don't understand

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

**Comment by Noiwex** [comment]
Baguette.

**Comment by BillyOnWiiUIn144p** [comment]
![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)![](http://steamcommunity-a.akamaihd.net/economy/emoticon/iambaguette)
