### ISSUE TITLE
ENT:BeingLookedAtByLocalPlayer() always returns false until certain things happen?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2551]
Tooltips won't draw on anything while in singleplayer or listen server until the context menu is opened. I haven't tested other cases, but it is a weird bug.

**Comment by willox** [comment]
Related to https://github.com/Facepunch/garrysmod-issues/issues/2516

**Comment by robotboy655** [comment]
BeingLookedAtByLocalPlayer is already fixed.
