### ISSUE TITLE
GetSaveTable/GetInternalVariable clientside missing fields

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2552]
Let's take for example m_vecAbsVelocity. This shows up in the serverside's usage of the function, however, it's missing clientside even though it's defined as a field in c_baseentity.cpp.

In fact, GetSaveTable only returns 5 elements clientside as opposed to 265 serverside when used on a player. Testing done in singleplayer.

**Comment by robotboy655** [comment]
They only show DataDesc fields.

**Comment by Kefta** [comment]
Can this be changed to match the serverside implementation?

**Comment by Jvs34** [comment]
I doubt that, the savetable is serverside for a reason, because it's used for the source savesystem.
Why some datadescs have been added clientside beats me, considering that they're not used at all.

The datatable would most likely be more useful than the savetable, but then there'd be inconsistencies anyway.

**Comment by robotboy655** [comment]
I am thinking of putting Prediction and Base Data descs for GetSaveTable, not sure about the rest of the functions.

I really do not want to copy paste huge chunks of case comparisors

**Comment by jbuug** [comment]
Seems like an intresting idea

**Comment by Kefta** [comment]
I misunderstood the difference between the different fields at the time when I made this issue. Specifically, having DEFINE_FIELDs, DEFINE_PRED_FIELDs, and their variants clientside would fulfill the function consistency. There's a lot you can do with the fields serverside but it ruins prediction not being able to execute the same operations shared.

**Comment by roboderpy** [comment]
It looks like `GetSaveTable` always return 5 entries no matter what on client realm, even when there **are** other variables known to client (for example, NW2Vars are predicted and should be present in `GetSaveTable` clientside)

**Comment by robotboy655** [comment]
My current plan is to add `GetInternalTable()` that returns everything it can on both client and server, affecting `GetInternalVariable()`, but not `GetSaveTable()`.

`SetSaveValue()` is problematic and I will need to figure out some way to add `SetInternalVariable` without copypasting hundreds of lines of code for it.

The reason I want to keep SaveTable and InternalTable separate is for possible use by duplicators.

**Comment by robotboy655** [comment]
Decided to bail on the original plan as there ended up next to no difference serverside, so I just enabled the 3 functions that already exist to read/write the prediction table on the client instead.

GetSaveTable() now has an optional parameter, which you can set to true to return ALL the variables, not just save table. I have not found differences serverside, but there will be a difference clientside.

SetSaveValue and GetInternalVariable will always have access to all the variables.

That being said, there isn't even that many useful things clientside so I am not sure any of this was worth it.

**Comment by Kefta** [comment]
There is a lot of data clientside useful for prediction, thank you!
