### ISSUE TITLE
Setting NetworkVar clientside on player doesn't set it back to server value until player changes ground

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2553]
Very odd bug, but easy to test.
Code:

```
hook.Add( "OnEntityCreated", "CStrike - PlayerSetupDataTables", function(p)
   if ( p:IsPlayer() ) then
      p:InstallDataTable()
      -- Using no timer will result in nil returns
      -- Using a frame timer (0 sec) will result in nil returns clientside only
      timer.Simple( 0.1, function() p:NetworkVar( "Int", 0, "ShotsFired" ) end )
   end
end )
```

Now, set a value clientside on the player, don't move but let time pass, then print it out on the client. The value should be the same as what you set it to even though serverside it will still be 0. Then, jump or fall off a surface so that your ground entity undergoes a change (it needs to go from NULL to something). Reprinting the value clientside will show that the value now matches the server's. Testing done in singleplayer. Not tested with player class NetworkVars.

**Comment by Acecool** [comment]
Setting a value clientside should never alter the servers; this is part of the programming philosophy to never trust client input ( ie always verify ), otherwise they'd be able to set how much money they have, teleport, etc....

This just shows that the data isn't resynced or updated on the client until they do something major ( ie when they move other clients in their PVS will need to receive the updates too )...

**Comment by Kefta** [comment]
I never said the server value should change to match the client, but I thought that if a NetworkVar clientside doesn't receive the same update serverside, it should revert next frame/tick. Maybe I'm wrong in that, but I have only noticed this behaviour in players and no other entity that uses NetworkVars

**Comment by Acecool** [comment]
Yeah, the first half covered that ( about security ) which wasn't what your post was about.. my bad..

The second part went back towards the topic and went into some detail and speculation as to why it was done that way..

**Comment by Kefta** [comment]
Here's another application of the issue: I am setting a NetworkVar serverside in PrimaryAttack (for single-player). If the player is changing ground, the value will be sent to the client correctly.

Standing still: http://puu.sh/pjxwg.png
Running across a lot of little props: http://puu.sh/pjxwn.png

Note that these are being set in predicted hooks in single-player if that makes a difference.

**Comment by Kefta** [comment]
Might be related to the bug listed here? https://wiki.garrysmod.com/page/Entity/NetworkVarNotify

**Comment by Kefta** [comment]
NW2 vars don't have this issue.
