### ISSUE TITLE
Helicopter Bomb sounds sometimes repeat

### ISSUE THREAD

**Issue by gamerscruffy** [Facepunch/garrysmod-issues#2555]
Hello, I have been playing around with the helicopter bombs in the Entities menu. I just noticed that sometimes, the helicopter bomb makes an infinite loop of the detonation sound. Removing it as it detonates is probably another way to cause this problem.

**Comment by robotboy655** [comment]
"sometimes" is not helpful. I could not reproduce the issue. If you find a way to reproduce it, let us know.

**Comment by thegrb93** [comment]
Probably the same issue that causes the fire's burning sound effect to never end.
