### ISSUE TITLE
CallOnClient doesn't work in Deploy when called with SelectWeapon

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2556]
```
SWEP.Base = "testwep"
SWEP.Spawnable = true

function SWEP:Deploy()
    self:CallOnClient( "PrintMessage" )
    self:PrintMessage()
end

function SWEP:PrintMessage()
    print"hi"
end
```

Spawn it with the Q-menu or use SelectWeapon

**Comment by robotboy655** [comment]
Player.SelectWeapon works, but I can see why it doesn't work on spawn. I am not sure what can be done to fix it though. The problem is that the CallOnClient usermessage gets to the client before the Lua entity is initialized on client, i.e. has all it's Lua shit loaded.

**Comment by Kefta** [comment]
How long is the delay? Can a timer be internally used if the entity is seen to be uncreated?

**Comment by Kefta** [comment]
I can sort of fix this by calling CallOnClient( "SharedDeploy" ), then 0.1 seconds later use CallOnClient again to check if SharedDeploy was called or not. It seems the delay for the lua state being ready clientside is more than a frame since a 0 second timer does not working.

**Comment by Kefta** [comment]
Can you possibly just delay the shared call of Deploy until the clientside Lua state is avaliable?

**Comment by Kefta** [comment]
Fixed by checking the weapon state in a Think hook, which is ran as soon as the weapon is known clientside.
