### ISSUE TITLE
Missing Models

### ISSUE THREAD

**Issue by putzismydog** [Facepunch/garrysmod-issues#2557]
I am missing the standard models for garry's mod lie the lamp, i was making a dupe right and i switched to a night map and spawned my dupe then tried to add lights to it but once i spawned them they turn invisible and i get a script
 error :/
![help](https://cloud.githubusercontent.com/assets/18492116/14577142/17fb6400-033e-11e6-9c38-bb9f326c51ab.jpg)
![help 2](https://cloud.githubusercontent.com/assets/18492116/14577143/1d929ce4-033e-11e6-8d38-c3683e3e1118.jpg) (btw this is my first time using github so dont hate :/

**Comment by Kefta** [comment]
Can't replicate (main or dev branch). Could you post what error you're getting?

**Comment by robotboy655** [comment]
The error is probably the failure to draw the glow sprite.

Validate your game in Steam and try switching your lamp model.
