### ISSUE TITLE
Changing sv_gravity via q--menu

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2559]
If you change sv_gravity in q-menu to a different value, then the convar is not working anymore and is floating from -200 to 600 gravity all the time.

**Comment by robotboy655** [comment]
One of your addons is causing the issue.

**Comment by mcNuggets1** [comment]
I have no addons at all installed in my singleplayer.

**Comment by robotboy655** [comment]
![d](https://cloud.githubusercontent.com/assets/3299036/14583485/b05456d8-042b-11e6-850d-b7ee2e047c84.gif)

It is a problem on your side.

**Comment by mcNuggets1** [comment]
Sometimes it work, sometimes not. I don't know actually.
