### ISSUE TITLE
if goes true when should false.

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2562]
My code wants to check if the player kill an npc with a `weapon_physcannon `but needed to add `prop_physics.`
```
hook.Add(O"nNPCKilled", "MyNpcKillerCheck", function(npc, killer, weapon)
if killer && killer != NULL && killer:IsPlayer() then
		if weapon == nil then return end
		if weapon != nil then print(weapon) end
		print(weapon:GetClass())
		if (weapon != "weapon_physcannon" || weapon != "prop_physics") then
			print("TRUE")
			for k, v in pairs(Hl2c.Ravenholm.Maps) do
				if game.GetMap() == v then
					if !file.Exists("hl2c_data/ravenholm-no-achi.txt", "DATA") then
						file.Write("hl2c_data/ravenholm-no-achi.txt")
						print('"[hl2c] file.Write("hl2c_data/ravenholm-no-achi.txt")"')
					end
				end
			end
		end
	end
end)
```
It always print true can you tell me why it goes true in DevBranch???
If I kill an npc with my physcannon???
```
Hl2c = Hl2c or {}

Hl2c.Ravenholm = Hl2c.Ravenholm or {}
Hl2c.Ravenholm.Maps = {
	"d1_town_01",
	"d1_town_01a",
	"d1_town_02",
	"d1_town_02a",
	"d1_town_03",
	"d1_town_04"
}
```
Here where my table is coming from.

```
Version: 16.02.26 (garrysmod)
Build: 21:02:25 Apr 16 2016 (6370) (4000)
```

**Comment by Kefta** [comment]
First off, your code is extremely bloated. Second off, it's because you're using an || statement, meaning that statement will always be true. Lastly, prop_physics is not a weapon.

**Comment by kem008** [comment]
but it printed in weapon:GetClass() also as a weapon and if print as weapon I get the index number of the prop_physics.

**Comment by robotboy655** [comment]
I am assuming you are referring to this line
``` if (weapon != "weapon_physcannon" || weapon != "prop_physics") then```
Which will do the following:

If the ```weapon``` variable is not "weapon_physcannon" or it is not "prop_physics" it will pass, i.e. be true, because the variable weapon cannot be two values at the same time it will always pass, because one or the other will equivalent to true.

**Comment by Kefta** [comment]
Here's your code properly done:
```
Hl2c = Hl2c or {}

Hl2c.Ravenholm = Hl2c.Ravenholm or {}
Hl2c.Ravenholm.Maps = {
    ["d1_town_01"] = true,
    ["d1_town_01a"] = true,
    ["d1_town_02"] = true,
    ["d1_town_02a"] = true,
    ["d1_town_03"] = true,
    ["d1_town_04"] = true
}

hook.Add("OnNPCKilled", "MyNpcKillerCheck", function(npc, killer, weapon)
	if (killer ~= NULL and 
		weapon ~= "weapon_physcannon" and 
		HL2c.Ravenholm.Maps[game.GetMap()]) then 
		-- Do your file stuff here
	end
end)
```

**Comment by kem008** [comment]
thx then.
