### ISSUE TITLE
GM:SetupMove Clientside Hiccups

### ISSUE THREAD

**Issue by Dgrouse96** [Facepunch/garrysmod-issues#2565]
I wrote about this a year ago, but found it hard to reproduce the issue, now with a program called clumsly, I can simulate varying amounts of lag. - Even without using clumsly, the dedicated server shows the same issue.

Client's lag affects SetupMove.
- If you set the client's velocity only once out of the multiple ticks it will not apply this velocity.
- When I was told it was a problem with my code and and was asked to write a script to set the client's velocity at a key press, there were no issues.
- Of course there's going to be no issues because the keypress is ran correct to the ticks that need the same set velocity value.

With 200 ping, I print whether or not the attack key is being pressed ---
- I press my attack key for a split second, 
- This is what the server sees:

( tostring(cmd:KeyDown(IN_ATTACK)).." : "..CurTime() )

false : 56.055000305176
false : 56.069999694824
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.129997253418
true : 56.145000457764
true : 56.159999847412
true : 56.174999237061
true : 56.189998626709
true : 56.204998016357
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.309997558594
true : 56.324996948242
true : 56.340000152588
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182
false : 56.41499710083

- This is what the client sees:

false : 56.084999084473
false : 56.084999084473
true : 56.099998474121
true : 56.099998474121
true : 56.099998474121
true : 56.11499786377
false : 55.889999389648
false : 55.904998779297
false : 55.919998168945
false : 55.934997558594
false : 55.949996948242
false : 55.965000152588
false : 55.979999542236
false : 55.994998931885
false : 56.009998321533
false : 56.024997711182
false : 56.03999710083
false : 56.055000305176
false : 56.069999694824
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.11499786377
true : 56.129997253418
false : 55.919998168945
false : 55.934997558594
false : 55.949996948242
false : 55.965000152588
false : 55.979999542236
false : 55.994998931885
false : 56.009998321533
false : 56.024997711182
false : 56.03999710083
false : 56.055000305176
false : 56.069999694824
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.129997253418
true : 56.129997253418
true : 56.145000457764
true : 56.145000457764
true : 56.145000457764
true : 56.159999847412
false : 55.949996948242
false : 55.965000152588
false : 55.979999542236
false : 55.994998931885
false : 56.009998321533
false : 56.024997711182
false : 56.03999710083
false : 56.055000305176
false : 56.069999694824
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.129997253418
true : 56.145000457764
true : 56.159999847412
true : 56.159999847412
true : 56.174999237061
true : 56.174999237061
true : 56.174999237061
true : 56.189998626709
true : 56.189998626709
true : 56.189998626709
true : 56.189998626709
true : 56.204998016357
true : 56.204998016357
true : 56.204998016357
true : 56.219997406006
true : 56.219997406006
true : 56.219997406006
true : 56.235000610352
true : 56.235000610352
true : 56.235000610352
true : 56.25
false : 55.994998931885
false : 56.009998321533
false : 56.024997711182
false : 56.03999710083
false : 56.055000305176
false : 56.069999694824
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.129997253418
true : 56.145000457764
true : 56.159999847412
true : 56.174999237061
true : 56.189998626709
true : 56.204998016357
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.25
true : 56.264999389648
true : 56.264999389648
true : 56.264999389648
true : 56.279998779297
true : 56.279998779297
true : 56.279998779297
true : 56.279998779297
true : 56.294998168945
false : 56.084999084473
true : 56.099998474121
true : 56.11499786377
true : 56.129997253418
true : 56.145000457764
true : 56.159999847412
true : 56.174999237061
true : 56.189998626709
true : 56.204998016357
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.294998168945
true : 56.309997558594
true : 56.309997558594
true : 56.309997558594
true : 56.309997558594
true : 56.324996948242
true : 56.11499786377
true : 56.129997253418
true : 56.145000457764
true : 56.159999847412
true : 56.174999237061
true : 56.189998626709
true : 56.204998016357
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.309997558594
true : 56.324996948242
true : 56.340000152588
true : 56.340000152588
true : 56.340000152588
true : 56.340000152588
true : 56.354999542236
true : 56.354999542236
true : 56.354999542236
true : 56.354999542236
true : 56.369998931885
true : 56.369998931885
true : 56.369998931885
false : 56.384998321533
false : 56.384998321533
false : 56.384998321533
false : 56.399997711182
false : 56.399997711182
false : 56.399997711182
false : 56.41499710083
true : 56.189998626709
true : 56.204998016357
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.309997558594
true : 56.324996948242
true : 56.340000152588
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182
false : 56.41499710083
false : 56.41499710083
false : 56.430000305176
true : 56.219997406006
true : 56.235000610352
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.309997558594
true : 56.324996948242
true : 56.340000152588
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182
false : 56.41499710083
false : 56.430000305176
false : 56.430000305176
false : 56.444999694824
false : 56.444999694824
false : 56.459999084473
true : 56.25
true : 56.264999389648
true : 56.279998779297
true : 56.294998168945
true : 56.309997558594
true : 56.324996948242
true : 56.340000152588
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182
false : 56.41499710083
false : 56.430000305176
false : 56.444999694824
false : 56.459999084473
false : 56.459999084473
false : 56.474998474121
false : 56.474998474121
false : 56.474998474121
false : 56.48999786377
false : 56.48999786377
false : 56.48999786377
false : 56.48999786377
false : 56.504997253418
false : 56.504997253418
false : 56.504997253418
false : 56.520000457764
false : 56.520000457764
false : 56.520000457764
false : 56.534999847412
true : 56.324996948242
true : 56.340000152588
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182
false : 56.41499710083
false : 56.430000305176
false : 56.444999694824
false : 56.459999084473
false : 56.474998474121
false : 56.48999786377
false : 56.504997253418
false : 56.520000457764
false : 56.534999847412
false : 56.534999847412
false : 56.549999237061
false : 56.549999237061
false : 56.549999237061
false : 56.564998626709
false : 56.564998626709
false : 56.564998626709
false : 56.579998016357
true : 56.354999542236
true : 56.369998931885
false : 56.384998321533
false : 56.399997711182

I know having the client refresh faster is how it should be to smooth movements out. But the more lag you have the more the key stutters true-false-true-false-true-false when I've only pressed it once.
- at 5 ping, there's almost no stuttering.
- at 80 ping, there's lots of stuttering. etc.

The issue with my code:
- Player presses keys to impulse a velocity, (kicking off a wall)
- A variable (NextWallKick) is set to Curtime()+0.1 (stops the player from kicking for 0.1 seconds)
- With variable set, client does extra refreshes on the code, and the NextWallKick variable blocks the refreshes from setting the clients velocity.
- Without the extra refreshes setting the velocity, nothing happens on the clientside and a prediction error occurs

A hacky workout I came up with is to get the server to send a net message to the client telling them when they are allowed to kick again.
- The issue with this is that clients will get prediction errors by kicking faster than they are allowed to.

Another attempt to fix this issue is by checking if the current refresh is at the same CurTime as the last and setting a bool called IsFirst, but as printing the key showed, it stutters over time.

SetupMove has always been this rubbish, been trying to work around this issue for ages, but it's much too limiting. Are the extra refreshes and stuttering really necessary?

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/Prediction

Your code is probably wrong. Get help from the [proper place](https://facepunch.com/forumdisplay.php?f=65) and if it turns out there's an actual bug in the game, come back here with code that can reproduce the issue.

**Comment by Dgrouse96** [comment]
```
local NextUp = 0
function GM:SetupMove(ply,mv,cmd)
	if NextUp < CurTime() then
		if cmd:KeyDown(IN_ATTACK) then
			mv:SetVelocity(Vector(0,0,500))
			NextUp = CurTime()+0.1
		end
	end
end
```
[Screenshot of pred errors](http://steamcommunity.com/sharedfiles/filedetails/?id=668654651)

**Comment by Dgrouse96** [comment]
Do you see the issue now?
How else should I write that to work?
