### ISSUE TITLE
Camera and Toolgun gone from weapon select menu

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#2567]
There was an update to pre-release today and this happened.

Live:
![gm_flatgrass0042](https://cloud.githubusercontent.com/assets/2400026/14652273/436354ae-067c-11e6-9fe3-4cc68508c7c6.jpg)

Pre-release 2016-04-19:
![gm_flatgrass0041](https://cloud.githubusercontent.com/assets/2400026/14652272/4361e4de-067c-11e6-852b-046cfd51ff01.jpg)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/14653420/96ed3b76-0681-11e6-813e-b278fb18bcef.png)

**Comment by NeatNit** [comment]
What is your screenshot showing exactly? (besides a whole bunch of irrelevant debug information)

Yes, you can equip the toolgun through the spawn menu, but that doesn't make it appear in the weapon selection.

**Comment by robotboy655** [comment]
Tell me please how exactly I was supposed to know you can equip it from spawnmenu but it is invisible in the selection? You never said anything like that.

**Comment by Kefta** [comment]
He showed that in the comparrison picture: category 6 was missing.

**Comment by robotboy655** [comment]
Yes, never it was mentioned that he could spawn it or equip it.

**Comment by NeatNit** [comment]
Why are you being so aggressive? I was in sandbox and the weapons should be there from the first second. I switched between live and prerelease like 5 times to confirm that I wasn't hallucinating, confirmed that it was a bug in the prerelease and went straight here to report it. The underlying cause is not something I had any idea about, and I didn't feel like doing any sort of investigation. That's your job. Should I have just kept my mouth shut and _not_ reported the bug?

Regardless, this issue no longer occurs. I have no idea if you fixed it in an update or if a magical unicorn messing with the code was the original cause of the bug in the first place.

**Comment by willox** [comment]
It's a bug in the dev branch

**Comment by robotboy655** [comment]
I am not being a aggressive. I am saying that I opened up prerelease and what you reported as broken was not broken, so to prove that it is working properly, I took a picture of the toolgun and the prerelease label, thinking that the weapon did not appear in the game for you completely. And then you tell me you can spawn it.

**Comment by NeatNit** [comment]
1. The title of this issue is "Camera and Toolgun gone __from weapon select menu__", not gone from the game.
2. The screenshots only showed the weapon select menu, so that's where you need to check
3. EVEN IF I should have elaborated that, in the end, I did. Yes, it only happened in the second reply, but it happened. After that you just started with accusations, when a simple "oh, you should have said so" would have sufficed.

**Comment by robotboy655** [comment]
I just explained why I thought my screenshot was enough to prove you wrong, sheesh.

Anyway, fixed in Dev.
