### ISSUE TITLE
Playing on singleplayer then going on multiplayer disables ply:ConCommand for that player

### ISSUE THREAD

**Issue by BurgerLUA** [Facepunch/garrysmod-issues#2569]
What the title says. It spams this error on client:

FCVAR_SERVER_CAN_EXECUTE prevented server running command: <servercommandhere>

I'm using the non-beta version of garrysmod.

**Comment by end360** [comment]
What console command are you attempting to run?

**Comment by BurgerLUA** [comment]
It was a console command that I made, but it works for any custom console made such as gm_giveswep.

**Comment by willox** [comment]
Are you creating your console command on both the client and the server? That's something you probably want to avoid. This issue should be fixed on the dev branch.
