### ISSUE TITLE
RenderView and Capture giving weird results

### ISSUE THREAD

**Issue by stuartpb** [Facepunch/garrysmod-issues#2571]
I'm working with this function to capture images from the player's position:

``` lua
concommand.Add("test_capture", function(ply, cmd, args)
  local res = tonumber(args[1]) or 2048
  local format = args[2] or 'png'
  local extension = format == 'jpeg' and 'jpg' or format
  local suffix = args[3] and '-'..args[3] or ''
  local captureData = {
    format = format,
    h = res, w = res, x = 0, y = 0,
  }
  local viewData = {
    angles = ply:EyeAngles(),
    x = 0, y = 0, w = res, h = res, aspectratio = 1, fov = 90,
    dopostprocess = args[3] and not not string.find(args[3], 'post'),
    drawmonitors = true,
    drawviewmodel = false, drawhud = false,
  }

  local rtName = 'testrt_' .. res
  render.PushRenderTarget(GetRenderTarget(rtName, res, res))
  render.RenderView(viewData)
  local image = render.Capture(captureData)
  render.PopRenderTarget()
  local f = file.Open('test-'..res..suffix..'.'..extension, "wb", "DATA")
  f:Write(image)
  f:Close()
end)
```

However, I'm seeing a pile of issues in the resulting files:
- The skybox texture appears to be rendering at my screen's resolution, regardless of the RenderView / Capture size.
- The alpha channel, when exporting as PNG, appears to be something like the inverse of the foreground fog - everything that _isn't_ in the sky is rendered as nearly transparent.
- The physgun's glow is showing up even though I'm not rendering the viewmodel (though I guess the physgun glow is like the rocket laser in that it's rendered in-world so that's to be expected?)

Post-processing seems to add additional problems, but turning it off doesn't fix any of the things I just described.

Test results (with and without alpha):

[test-1024.jpg](https://cloud.githubusercontent.com/assets/572196/14726161/14bad21c-07d5-11e6-91c1-20450e1140f6.jpg)
[test-1024.png](https://cloud.githubusercontent.com/assets/572196/14726163/14bd57da-07d5-11e6-96ff-260a672e9376.png)
[test-1024-post.jpg](https://cloud.githubusercontent.com/assets/572196/14726162/14baf738-07d5-11e6-8c76-5304a5d9d40e.jpg)
[test-1024-post.png](https://cloud.githubusercontent.com/assets/572196/14726160/14babd72-07d5-11e6-9013-9c5d27d46031.png)
[test-2048.jpg](https://cloud.githubusercontent.com/assets/572196/14726158/14ba5788-07d5-11e6-9564-a06982600c91.jpg)
[test-2048.png](https://cloud.githubusercontent.com/assets/572196/14726164/14ca08b8-07d5-11e6-9f1f-a9dbe1581194.png)
[test-2048-post.jpg](https://cloud.githubusercontent.com/assets/572196/14726165/14cae940-07d5-11e6-8223-9bfa763fa8ea.jpg)
[test-2048-post.png](https://cloud.githubusercontent.com/assets/572196/14726159/14baadc8-07d5-11e6-94b5-a9123dc5e9c3.png)

**Comment by stuartpb** [comment]
Also, the FOV on these looks like *way* more than 90 degrees.

**Comment by robotboy655** [comment]
You can disable alpha as per https://github.com/Facepunch/garrysmod-issues/issues/1411

**Comment by jorjic** [comment]
The depth buffer is being written to the alpha channel. Not sure if this is intended behavior outside of render.Capture, but you can workaround this by calling render.SetWriteDepthToDestAlpha and setting it to false before rendering. 

```lua
    panel = vgui.Create( "DModelPanel" )
    function panel:PreDrawModel()
        render.SetWriteDepthToDestAlpha( false )
    end
```
