### ISSUE TITLE
sound.PlayURL() not working on Linux.

### ISSUE THREAD

**Issue by quidsquid** [Facepunch/garrysmod-issues#2577]
sound.PlayURL() doesn't seem to be working on Linux from my experience. I've tried this on all of my linux computers (all arch) only to have the same issue. From what I can tell, sound.PlayURL() doesn't think any of my urls are valid on Linux, while passing the check on Windows.

For example, this script will play 'thetrain.mp3' on Windows systems, while printing Invalid URL on Linux systems.

```
function testplaysound( url )
		sound.PlayURL( url, "", function(station)
			if IsValid(station) then
			    station:Play()
			    MsgC( Color( 100, 100, 255 ),"[Porchlight]", Color( 200, 200, 200 ), " Played sound : ", url, "\n" )
			else
			    MsgC( Color( 100, 100, 255 ),"[Porchlight]", Color( 200, 200, 200 ), " Invalid URL : ", url, "\n" )
			end
		end)
end
testplaysound("http://392fn60m9re79.xyz/WWWEBWORLLD/sputsounds/thetrain.mp3")
```

Here are my system specifications
```
user@arch_black
OS: Arch Linux 
Kernel: x86_64 Linux 4.5.1-1-ARCH
Uptime: 5h 52m
Packages: 1316
Shell: bash 4.3.42
Resolution: 5760x2160
DE: XFCE4
WM: Xfwm4
WM Theme: NumixHolo
GTK Theme: NumixHolo [GTK2]
Icon Theme: gnome
Font: Sans 10
CPU: Intel Core i7-4790K CPU @ 4.3GHz
GPU: GeForce GTX 980
RAM: 5928MiB / 15898MiB
```

Also, this facepunch thread might be of use.
https://facepunch.com/showthread.php?t=1515771

**Comment by mcd1992** [comment]
Dev branch or main?

**Comment by quidsquid** [comment]
main

**Comment by Grocel** [comment]
Bass is updated in dev. Could you test it on dev too, so we know if it was fixed there or not.

**Comment by quidsquid** [comment]
Yup, it's working fine on the dev branch.
Went ahead and checked the error code on the main branch also. 
The error code was 44.

**Comment by Grocel** [comment]
Error 44. Seems like a codec issue to me. When it is fixed in dev version it should be fine then.
