### ISSUE TITLE
Garry's Mod Crashes Because Of Awesomium (Mac)

### ISSUE THREAD

**Issue by spittalwillo** [Facepunch/garrysmod-issues#2578]
Ok So Ive also Left A Issue On The FacePunch Forums: Recently Ive Been Playing On A Star Wars RP Server (Which i am Staff On) And Recently Alot Recently My Game Has Been Crashing From Awesomium! ( If Needed I Will Provide Crash Reports)

**Comment by spittalwillo** [comment]
Crashed Thread:        0  AwesomiumBrowserMain

**Comment by robotboy655** [comment]
No crashdumps and it's most likely a duplicate anyway

**Comment by Shigbeard** [comment]
Doesn't change the fact that awesomium needs to be replaced.

**Comment by spittalwillo** [comment]
Its Not A Duplicate! Ask My Mates This Crashing Is Seriously Annoying
