### ISSUE TITLE
NPCs

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2582]
The Antlion NPC seems to have no fear of Thumpers.
In Half-Life 2 a Antlion does not cross a thumpers way, in GMod the Antlion ignores the Thumper like it were not there. This makes the Thumper useless.

Also antlions does not react to bugbaits, however.

The fast zombie torso should be hidden if hl2 ep 2 is not owned, as it is an ERROR without it.

The next bot npc "Test NPC" should also be removed or at least hidden, as it is unimportant to keep it anyway.

**Comment by robotboy655** [comment]
Antlions most definitely are afraid of the Thumpers and the Fast Zombie Torso model is shipped with GMod.

I'd record a video but I am too lazy.
![image](https://cloud.githubusercontent.com/assets/3299036/14922573/0231550e-0e41-11e6-877f-476a6a6c1ddf.png)

**Comment by mcNuggets1** [comment]
I just looked into it, and you are right, not all the time, the antlion is not afraid of the thumper, just in some cases, like if he is attacking you.

However they ignore the bug baits of yours.

Demo: https://www.dropbox.com/sh/tpgg7brpf4n8azn/AADnDjnx-MUI25k-sarW2r3Za?dl=0

And what about the Test NPC, does it have a purpose?

**Comment by robotboy655** [comment]
Antlions not caring about bugbaits is normal, that behavior is only active if the map you are currently in has a env_global entity that states that antlions are friendly. By default that is only present in the nova prospect maps from HL2.

As for Test NPC, it serves the same purpose as the bouncy ball/manhack welder, etc, they are examples for new coders on how to make weapons/entities/npcs.

**Comment by mcNuggets1** [comment]
It has no purpose in playing Garry's Mod, then how about restricting it to AdminOnly?

**Comment by zerfgog** [comment]
Perhaps Test NPC could be altered into something that would make sense in playing Sandbox? The bouncy ball certainly does, and the manhack welder at least adds something.

**Comment by Kefta** [comment]
Do it on your server if it's that big of an issue.

**Comment by mcNuggets1** [comment]
I would recommend to change it to a pathfinding enemy npc, for testing nav maps.
