### ISSUE TITLE
NPCs are in T-Position and don't work (NOT because of disable thinking)

### ISSUE THREAD

**Issue by Dogerium** [Facepunch/garrysmod-issues#2583]
All of my NPCs began staying in the T-position (the same as the one used for disabled thinking bots) and never work. Some of them still shoot, like the combine, but don't have ANY animations at all. I've tried redownloading my mods, verifying game cache and reinstalling. None works. If they're shot, they still take damage and can still die. Disable thinking is NOT checked ever and any of the other commands including keep corpses and etc. Please help.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
