### ISSUE TITLE
Game is now mounting GMA files after local lua files

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#2584]
I have made some custom lua scripts, placed into lua folder to overide which were in the GMA files to fix some bug and make new features. It worked in the past. But at about 3 or 4 months ago, the game began to refuse the replacement and use everything in the GMA file instead when start up. So every time I open the game, I have to create a map(necessary), tab out to open notepad++, open custom script, change something, undo the changes, save it, for every custom script, to notify the engine that some special script in its lua folder was changed to load it, then tab back into the game and reload, which looks stupid >.<

**Comment by robotboy655** [comment]
Put your lua files into an addon in addons/
