### ISSUE TITLE
Steam Error: No SteamUser

### ISSUE THREAD

**Issue by Resaec** [Facepunch/garrysmod-issues#2585]
I encounted this error today and found a fix probably not related to the core problem.

It happens to me when Steam is in Family View and Garry's Mod is not allowed to be played.
This happens in both of these cases:
1. Steam is locked from the beginning (autostart with family view)
2. Steam was relocked and you are in family view again

You may consider adding this
"- Make sure that Steam is not in Family View or allow Garry's Mod to be played while in Family View"
to the "How to fix" message.

Game version is 2016.04.24

**Comment by robotboy655** [comment]
Thanks, I will make sure to include this info in the error message.

:+1:
