### ISSUE TITLE
ENTITY:GetBodyGroups() returns no value on some entities (func_door e.g.)

### ISSUE THREAD

**Issue by kojiDev** [Facepunch/garrysmod-issues#2590]

**Comment by robotboy655** [comment]
GetBodyGroups only works on entities that are models ( i.e. entities that can actually have body groups )

**Comment by kojiDev** [comment]
func_door allows to SetModel on it, but w/o rendering, so I'm just paranting prop_dynamic on it and it seems ok btw.

**Comment by robotboy655** [comment]
https://developer.valvesoftware.com/wiki/Func_door

func_door is a brush entity. The "w/o rendering" part should give you a clue the model is not being used. If you strap on a prop_dynamic over the prop_door, call your function on that prop_dynamic instead of your bodygroups and whatnot.

**Comment by AbigailBuccaneer** [comment]
I think it still makes sense to return an empty table, rather than `nil`. If you really want to make it clear that this entity doesn't support calling `GetBodyGroups()`, then `ENT.GetBodyGroups` should be `nil`

**Comment by robotboy655** [comment]
No, that makes no sense.

Why would you want to check if a function exists over checking if the output is nil or not.
Changing this behavior is also going to fuck up any addons that rely on it returning nil ( rely as in do something else, like "this thing has no bodygroups" message )
