### ISSUE TITLE
Server crash randomly every hour cause of this error 

### ISSUE THREAD

**Issue by MrDiaboloz** [Facepunch/garrysmod-issues#2591]
Hi since the latest update i have these error 
ERROR! SendData reliable data too big (214492)
ERROR! SendData reliable data too big (XXXXX)

`ServerLog: [FAdmin] Karim Saidani (STEAM_0:0:132436206) Attempted to switch noclip
L 05/04/2016 - 22:50:55: [FAdmin] Karim Saidani (STEAM_0:0:132436206) Attempted to switch noclip
ERROR! SendData reliable data too big (214492)
Increasing buffer size for snapshot payload.
FIND [/home/elysion/Steam/steamapps/common/Counter-Strike Source Dedicated Server/cstrike/*.vpk]`

And then crash.... i dont know what can i do i test everything (check all of my addons / updates addons / check mysql database) and nothing...

**Comment by willox** [comment]
Are you running the server on a machine you have access to? Or is this a shared host?

**Comment by MrDiaboloz** [comment]
we ha dedicated host (ovh) 
Intel i7 4790K	4 c / 8 t	4 GHz+	32 Go 
1333 MHz	240 Go SSD

**Comment by willox** [comment]
Yeah I think I've spotted the issue. I'll try to get a fix up on the prerelease branch for tomorrow.

**Comment by MrDiaboloz** [comment]
ok

**Comment by willox** [comment]
Are you able to try running your server on the prerelease branch? Players will still be able to connect. Let me know if you do and the issue is resolved.

http://wiki.garrysmod.com/page/Hosting_A_Dedicated_Server

**Comment by MrDiaboloz** [comment]
Ok i will try

**Comment by MrDiaboloz** [comment]
my server dont crash since 5 hours it seems work your fix

**Comment by MrDiaboloz** [comment]
ok i think  its fix no crash yesterday

**Comment by willox** [comment]
Thanks
