### ISSUE TITLE
Stuck Voiceboxes on Lua Refresh

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#2592]
To re-simulate change a client lua file live on a dedicated server while someone is talking.

The voicebox will stay stuck indefinitely for all the players on the server until map change or reconnect.

**Comment by willox** [comment]
What gamemode were you running?

**Comment by stickz** [comment]
[Morbus](https://github.com/Remscar/Morbus). But it should theoretically be an issue on anywhere, as the voice boxes are part of the game itself and not any one gamemode.

**Comment by robotboy655** [comment]
You are actually wrong, they are part of the gamemode, and Morbus does override them, so I am going to assume this is a bug with that gamemode and not the default voice notifications, unless you can reproduce it in Sandbox/Base gamemode.

https://github.com/Remscar/Morbus/blob/c34b717dab7b446a20fdf74b9e806a1cc9493457/MorbusGamemode/gamemodes/morbusgame/gamemode/client/cl_chat.lua#L41

**Comment by robotboy655** [comment]
The default gamemode cleans all extra icons every 10 seconds.

https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/cl_voice.lua#L107-L118

**Comment by bigdogmat** [comment]
> The default gamemode cleans all extra icons every 10 seconds.

That timer wouldn't do anything though. It's checking if the player isn't valid, though in the PlayerEndVoice function it's making sure the player is valid.
