### ISSUE TITLE
NotifyShouldTransmit confusing baseline updates

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-issues#2593]
### Test setup ###
Bots in a room not in your PVS.
### Code ###
```lua
hook.Add("NotifyShouldTransmit","a",function(ent,s)
	print(s and "^" or " ",ent)
end)
```
### Output ###
Here is what happens every 10 seconds:
```
net_showmsg svc_PacketEntities

Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661554, max 1108, changed 5, bytes 28
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661556, max 1108, changed 6, bytes 32
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661558, max 1108, changed 6, bytes 34
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661562, max 1108, changed 23, BL update, bytes 172
^	Player [3][Bot02]	
^	Player [4][Bot03]	
^	Weapon [723][none]	
^	Weapon [724][none]	
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661562, max 1108, changed 5, bytes 33
 	Player [3][Bot02]	
 	Player [4][Bot03]	
 	Weapon [723][none]	
 	Weapon [724][none]	
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661564, max 1108, changed 5, bytes 30
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661566, max 1108, changed 23, bytes 47
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661568, max 1108, changed 5, bytes 30
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661570, max 1108, changed 5, bytes 33
Msg from 94.23.170.2:27015: svc_PacketEntities: delta 661572, max 1108, changed 5, bytes 33
```
We receive baseline update which triggers NotifyShouldTransmit telling us players and weapons of players are not dormant, even though they are not in our PVS or drawing. (ply:IsDormant() also returns false).
Next entity message and only next entity message (there can be multiple frames in between) does the player become dormant again, as can be seen on the output.
PS: You can also observe this with cl_entityreport 1 ( Just wait 10 seconds to see the players and weapons start blinking )

### The Problem ###

How to tell when the update is a fake player dormancy? You can SetNoDraw(true) a player next to you and it appears dormant except for that one frame, but does not flicker for that one frame. How does the engine know not to draw the player?

### The Niggle ###
Some things I try to optimize need expensive initialization each time a player becomes visible, so having all players initialize every 10 seconds for no reason is quite problematic. I can wait one "frame" to see if the players become invisible again, but this means one frame flickering on visual stuff and does not fix the problematic cases when the second update takes more than a frame.

### Findings ###

 - m_bUpdateBaseline is the bit which is enabled when this problem occurs, but what if during that frame the player does become nondormant? Relevant files: 
   - netmessages.cpp
      - m_bUpdateBaseline
   - sv_ents_write.cpp
      - SV_DetermineUpdateType, etc
   - cl_ents_parse.cpp
      - CL_MarkEntitiesOutOfPVS, CL_CallPostDataUpdates
   - baseclientstate.cpp 
      - ReadPacketEntities
   - client.cpp
      - ReadEnterPVS

 - During these updates hook "UpdateAnimation" does get called even if player is outside of PVS.

### Workaround ###
Give us bindings to PVS calculation functions clientside to check ourselves if players are at least not in our PVS. I'm not sure if this is possible without a lot of effort, though.
 - IVEngineServer->GetClusterForOrigin
 - IVEngineServer->GetClusterCount
 - IVEngineServer->GetAllClusterBounds
 - IVEngineServer->CheckOriginInPVS
 - IVEngineServer->CheckBoxInPVS
 - See for example: https://github.com/Elecner/gm_pvs/blob/master/src/

End function could be a crude util.PVSCheck(util.ToPVS(Vector a), util.ToPVS(Vector b))

**Comment by willox** [comment]
There's not really a way around this. The game defaults to networking players to you at least every 10 seconds, at which point the call to NotifyShouldTransmit is valid.

Servers can change how often this happens with sv_playerforcedupdate if they want.
