### ISSUE TITLE
Footsteps causing mass lag

### ISSUE THREAD

**Issue by acj2001** [Facepunch/garrysmod-issues#2596]
I am hoping this is the right place to report this. I didn't find any other reports based on this issue either.

For the past few days/weeks, I have been encountering a lot of lag involving HL2 NPCs. At first, I thought it was add-on related, but then I realized others were experiencing it as well, hardly acknowledging it. I came to the conclusion it was caused by a recent update, and I remembered the footstep fixes. So many NPCs running at the same time will cause a lot of footstep sounds to play, which is most likely the cause of this lag.

I am experiencing this in the April 2016 update version.

**Comment by willox** [comment]
Can you describe the effect of the lag and give us a screenshot that includes your net graph? Just type net_graph 1 in the console to bring it up.

**Comment by acj2001** [comment]
The lag is basically a massive FPS drop. Here are a few screenshots showing my net graph while 9 NPCs were running around gm_construct.
https://drive.google.com/file/d/0BxV-hBc81VBZVnUtc3Jnc0NMUG8/view?usp=sharing
https://drive.google.com/file/d/0BxV-hBc81VBZSUpyZnlESzB5UzQ/view?usp=sharing
https://drive.google.com/file/d/0BxV-hBc81VBZZjl0cWZndWtXVnM/view?usp=sharing

I also filmed a few NPCs running across the map. My net graph is shown during the video.
https://youtu.be/YBIBHXxsP5w
The tool used to control the NPCs' movement has nothing to do with the lag.

**Comment by willox** [comment]
I'm an idiot. Please run with net_graph 3.

**Comment by acj2001** [comment]
https://drive.google.com/file/d/0BxV-hBc81VBZQ3g0Vm90dEJmUW8/view?usp=sharing
https://drive.google.com/file/d/0BxV-hBc81VBZNzU3dDM5QXVSdW8/view?usp=sharing
https://drive.google.com/file/d/0BxV-hBc81VBZYVpVWlYwMkd5S1U/view?usp=sharing

https://youtu.be/QOV_XhaR6tk

**Comment by willox** [comment]
If you're in singleplayer the footsteps shouldn't be effecting anything at all. I can't reproduce your issue even with four times as many NPCs. Please try without any addons installed.

**Comment by acj2001** [comment]
I tried it without any add-ons, and there were no issues.

I'm sorry if this took up too much of your time. I'll try uninstalling a few add-ons.
