### ISSUE TITLE
Non-latin characters stopped displaying correctly in all fonts in dev version

### ISSUE THREAD

**Issue by glebqip** [Facepunch/garrysmod-issues#2597]
Non-latin characters stopped displaying correctly in all fonts in dev version

**Comment by glebqip** [comment]
For example:
surface.CreateFont("TestFont", {
  font = "Segoe Script",
  size = 32,
  weight = 400,
  blursize = 0,
  scanlines = 0,
  antialias = false,
  underline = false,
  italic = false,
  strikeout = false,
  symbol = false,
  rotary = false,
  shadow = false,
  additive = false,
  outline = false
})
hook.Add("HUDPaint","TestFont",function()
  draw.DrawText("TestТест","TestFont",ScrW()/2,ScrH()/2,Color(255,0,0))
end)
What we got:
![image](https://cloud.githubusercontent.com/assets/6125008/15091834/0dc406e6-145e-11e6-9392-99a6e50ca6bd.png)

**Comment by Bo98** [comment]
Add `extended = true,` to your surface.CreateFont table.

**Comment by glebqip** [comment]
Oh, thx! It work.
