### ISSUE TITLE
HL2 weapons don't register hitboxes outside with hulls

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2600]
https://www.youtube.com/watch?v=ZbFPel74zl8

Melee and bullets both. The crowbar/stunstick only seems to collide with hulls and not hitboxes at all, which could be intentional to increase accuracy, but it should probably be adjusted so that it checks for both. Also, I've noticed this behaviour is pretty inconsistent among NPCs: my video displays the general case that happens with players and HL2 actives, but the weapons seem to behave correctly with mechanical NPCs like the helicopter that have small hulls but a lot of hitboxes. HL1 NPCs seem to throw the weapons totally off with only certain hitboxes registering melee and weapon hits.

**Comment by robotboy655** [comment]
What happened to your "If it is in HL2:MP, why change it?" philosophy? :v

Anyway, I personally don't want to bother with this, most servers use custom SWEPs anyway.

**Comment by Kefta** [comment]
Because HL2: DM doesn't account for CS:S :( Plus I'm having this problem in my own SWEPs and I don't know why -- it's EXTREMELY inconsistent

**Comment by robotboy655** [comment]
Oh, I guess it's worth mentioning that the whole "hitting hitboxes outside of the hull" is only applied to players, not NPCs or Entities or whatever.

**Comment by Kefta** [comment]
Didn't know that, thanks
