### ISSUE TITLE
Player:UniqueID Alternative

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-issues#2602]
I don't see any good uses for UniqueID as they have frequent collisions, and its functionality doesn't follow up to its function name. I came up with these small functions that returns actual unique id, and the return range fits 32 bit integer(both signed and unsigned), unlike SteamID64.
```
local PLAYER = FindMetaTable("Player")

function PLAYER:UniqueID2( )
	local y,z = string.match(self:SteamID(), "STEAM_0:(%d):(%d+)")
	return z*2+y
end
function UniqueIDToSteamID( uniqueid )
	local y = uniqueid%2
	local z = (uniqueid-y)/2
	return "STEAM_0:"..y..":"..z
end
function SteamIDToUniqueID( steamid )
	local y,z = string.match(steamid, "STEAM_0:(%d):(%d+)")
	return z*2+y
end
```
It also perform about 3 times faster than original (C) function:

![](http://i.imgur.com/HN3pWbs.png)

**Comment by robotboy655** [comment]
We don't need any more of these functions, use Ply:SteamID(64)()

**Comment by edgarasf123** [comment]
Yes, but the purpose of Ply:UniqueID() is that it returns a numeric value. Ply:SteamID(64)() returns in string format. One of possible advantage of having steamid in numeric value is optimization, such as sending large user databases over net stream( such as banlist).

**Comment by Kefta** [comment]
tonumber

**Comment by edgarasf123** [comment]
SteamID64 is way too large number for lua number type, it looses precision(floating point rounding error).

**Comment by thegrb93** [comment]
You can write your own tonumber which converts the steamid string into a 8 length uint data string.

**Comment by edgarasf123** [comment]
This site uses same format, they call it SteamID32 which I think is probably proper name.
https://steamid.xyz/40357164

**Comment by edgarasf123** [comment]
Also [pdata](https://github.com/garrynewman/garrysmod/search?utf8=%E2%9C%93&q=GetUniqueID) uses CRC...

**Comment by willox** [comment]
PData and UniqueID's implementations won't change

**Comment by thegrb93** [comment]
I think the fact it's is a security risk overrides compatibility reasons

**Comment by edgarasf123** [comment]
Yes, but maybe in next major update such as Gmod14. PData functionality could be replaced with SteamID32.

**Comment by edgarasf123** [comment]
There is also other option. Make a lua script and run it when server start, which would transit pdata databases to a new version.
