### ISSUE TITLE
vector/angle leaking?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2603]
I put collectgarbage() and print(collectgarbage("count")) in a timer to track memory usage with this test. This is the result.
```
310689.5625
310689.875
310689.5625
310689.5625
310689.875
310689.5625
] lua_run hook.Add( "Think", "MemTest", function() for i=1,4096 do test[Vector(1,1,1)] = true end end )
> hook.Add( "Think", "MemTest", function() for i=1,4096 do test[Vector(1,1,1)] = true end end )...
314913.703125
319266.140625
323489.703125
327713.765625
332066.140625
336289.703125
340513.765625
344865.8359375
349089.5625
304161.5703125
308514.078125
312737.640625
316961.703125
321314.078125
325537.640625
378913.703125
383266.015625
387489.703125
391713.640625
396066.078125
400289.703125
404513.640625
408866.328125
413089.390625
417313.703125
421666.265625
425889.703125
430113.640625
434466.078125
438689.703125
541217.609375
545570.078125
549793.640625
554017.703125
558370.015625
562593.703125
566817.703125
571170.015625
575393.703125
579617.640625
583970.078125
588193.640625
] lua_run hook.Remove( "Think", "MemTest", function() for i=1,4096 do test[Vector(1,1,1)] = true end end )
> hook.Remove( "Think", "MemTest", function() for i=1,4096 do test[Vector(1,1,1)] = true end end )...
591009.5
591009.875
591009.4375
591009.5
591009.8125
591009.5
] lua_run print(table.Count(test))
> print(table.Count(test))...
5824512
591009.4375
591009.875
591009.4375
591009.5
591009.875
591009.4375
591009.5
591009.8125
591009.5
591009.4375
591009.875
] lua_run for k, v in pairs(test) do test[k] = nil end
> for k, v in pairs(test) do test[k] = nil end...
591009.5
408993.4375
408993.875
408993.4375
408993.5
408993.8125
408993.5
408993.4375
408993.875
408993.5
408993.4375
408993.875
] lua_run print(table.Count(test))
> print(table.Count(test))...
0
```
The memory doesn't go back down. Is this normal?

**Comment by thegrb93** [comment]
The reason I'm asking is because a friend of mine is having issues with 'out of memory' and crashing while working with heavy vector processing.

**Comment by Jazzelhawk** [comment]
Just to make this issue clearer, I used the code from here: https://github.com/INPStarfall/Starfall/issues/407#issuecomment-218580718

And this is the result:
```
] lua_run_cl print( "Initial memory: ", math.Round(collectgarbage( "count" )/1024, 2) .. " MB" )
Initial memory: 	127.1 MB
] lua_openscript_cl test.lua
Running script test.lua...
GC1: 	248.02 MB
GC2: 	166.13 MB
GC3: 	166.13 MB
GC4: 	166.13 MB
GC5: 	166.13 MB
GC6: 	166.13 MB
GC7: 	166.13 MB
GC8: 	166.13 MB
GC9: 	166.13 MB
GC10: 	166.13 MB
GC11: 	166.13 MB
GC12: 	166.13 MB
GC13: 	166.13 MB
GC14: 	166.13 MB
GC15: 	166.13 MB
GC16: 	166.13 MB
```

**Comment by willox** [comment]
I'm pretty sure this isn't a thing. You can't just attribute an increase in memory usage to the vectors not being collected properly.

**Comment by thegrb93** [comment]
So then it's normal.

**Comment by ThatOneCheetah** [comment]
That is because the test of 5 seconds does not seem to properly show the issue; something isn't being collected properly which eventually has always resulted in to "Lua Panic! not enough memory"; this is **not** expected behaviour, and that would become clear if you'd have taken a look yourself.

**Comment by willox** [comment]
```lua
function GC_Start()
	collectgarbage "restart"
end

function GC_Stop()
	collectgarbage "stop"
end

function GC_Count()
	return collectgarbage( "count" )
end

function GC_Collect()
	for i = 1, 1024 do
		collectgarbage( "collect" )
	end
end

--

-- Make sure nothing is going to be automatically collected or get in the way of our measurements
GC_Collect()
GC_Stop()

local BaseMemory = GC_Count()

for i = 1, 2^22 do
	Vector()
end

print( "Memory Delta (With vectors)",		GC_Count() - BaseMemory )

GC_Collect()
print( "Memory Delta (Without vectors)",	GC_Count() - BaseMemory )

-- Re-enable the GC
GC_Start()
print "\n"
```

**Comment by ThatOneCheetah** [comment]
Are you being serious right now? 
I'm pretty sure I specified using them as **KEYS** in tables, and I'm not sure about the Vector constructor and what it produces when you pass no args (presumably *0,0,0*) but this is **NOT** what was being referred to at all.

**Comment by willox** [comment]
Prove it, damnit.

**Comment by willox** [comment]
```lua
function GC_Start()
	collectgarbage "restart"
end

function GC_Stop()
	collectgarbage "stop"
end

function GC_Count()
	return collectgarbage( "count" )
end

function GC_Collect()
	for i = 1, 1024 do
		collectgarbage( "collect" )
	end
end

--

-- Make sure nothing is going to be automatically collected or get in the way of our measurements
GC_Collect()
GC_Stop()

local BaseMemory = GC_Count()

do
	local tab = {}

	for i = 1, 2^12 do
		table.insert( tab, Vector( 1, 2, 3 ) )
	end
end

print( "Memory Delta (With vectors)",		GC_Count() - BaseMemory )

GC_Collect()
print( "Memory Delta (Without vectors)",	GC_Count() - BaseMemory )

-- Re-enable the GC
GC_Start()
print "\n"
```

It's the same shit. Stop wasting my time if you don't have an actual issue to report.

**Comment by willox** [comment]
I'm not testing it with keys.

**Comment by thegrb93** [comment]
Correct me if I'm wrong, but I think the crashes may be because the vectors are being created too fast for the pool to clean itself? Or does it keep gradually increasing over time until the crash?

**Comment by willox** [comment]
If you know how to produce a crash you should just report that issue instead

**Comment by ThatOneCheetah** [comment]
Apparently, setting all the values in a table to nil in lua doesn't mark them for garbage collection?
However, setting the table itself to nil or to an empty table does.

[Test code](http://pastebin.com/51pKtDEx)

A) I am sorry for blaming it on Vectors, but;
B) If you had read and used the test code already provided, this misunderstanding would not have occured.

**Comment by willox** [comment]
> However, setting the table itself to nil or to an empty table does.

Anything I place in to a table and then remove is properly GC'd for me. I think you're witnessing the memory usage of the table itself.

If you throw x amount of things in to a table and then remove them all, that table is still going to have allocated a certain amount of memory for itself. I don't believe LuaJIT ever free's those allocations until the table itself is removed.
