### ISSUE TITLE
127 Physical Property limit (physenv.AddSurfaceData useless)

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#2604]
I know this is likely a source engine limit that is not fixable because its in vphysics, but its worth a try to get it fixed. 

I was trying to add physical properties to my server, and noticed that they weren't initializing, they didn't even exist. I got curious and made a fast little check 
` for I=0,127 do
        print( string.format("%X",I) .. " -- " .. util.GetSurfacePropName( I ) )
end`

which yields this

```
......

71 -- phx_rubbertire2
72 -- grenade_napalm
73 -- demoman_grenade
74 -- brass_bell_large
75 -- brass_bell_medium
76 -- brass_bell_small
77 -- brass_bell_smallest
78 -- hay
79 -- metal_barrellight_hl
7A -- metal_barrel_hl
7B -- plastic_barrel_verybuoyant
7C -- friction_00
7D -- friction_10
7E -- friction_25
7F -- frictionm_00
80 -- default
```
After the 0x80, the rest of the entries are "default" indicating a fallback. 

The limit is an 8 bit unsigned int of 128 :\ 

This means, that because we have so many entries in garrysmod's surfaceprops.txt that physenv.AddSurfaceData is now completely useless, and will not perform any function because garrysmod is using ~~all 128 entities~~ over 128 entries. Meaning the portal entries are not being added to the engine at the bottom of the list, because at 0x7F (Frictionm_00) you're already at the limit. Therefore in the surfaceprops.txt portal entries

```
"energyball"
{
	"base"		"glass"
	"elasticity"	"1000"
	"friction"	"0"
}

"sphere"
{
	"base"		"metal"
	"elasticity"	"3"
	"dampening"	"0.2"
	"friction"	"0.2"
	"density"	"1000"
}
``` 
are completely omitted, and not functional.

**Comment by robotboy655** [comment]
You are right in saying that it is pretty much impossible to fix.

It is a limitation in the IVP, the physics engine VPhysics uses.

Not sure to do about physenv.AddSurfaceData though.

**Comment by TheFreezebug** [comment]
Damn, I figured as much.

Perhaps the physics properties should be loaded dynamically depending on what content is mounted? That seems like a viable solution,as its unlikely servers (especially specialized servers) are going to have all game content mounted at once.

**Comment by robotboy655** [comment]
That doesn't really solve anything though, sure it may work for servers, but you'd also need to have this for clients, and those usually have most games mounted anyway. Besides it is possible that they need to match on server and client like soundscapes do.

**Comment by TheFreezebug** [comment]
That does it then, its not fixable and there's no viable solution for it. I'll just edit my server's surfaceproperties.txt, I only need the effects it has serverside (Friction!)

Thanks for the info, 

Still don't know about physenv.AddSurfaceData, but i'm going to close this

**Comment by Kefta** [comment]
I think AddSurfaceData should be kept, even if it is restricted by GMod's surfaceproperties.txt. Some people might modify their server's version to make space for custom surface props.

**Comment by Grocel** [comment]
This is a limitation of vphysics as confirmed by Rubat today. [Source](https://discord.com/channels/565105920414318602/589120351238225940/1494800262492192868)
