### ISSUE TITLE
PANEL:OnKeyCodePressed() doesn't work unless you do MakePopup(), but then it can't be parented

### ISSUE THREAD

**Issue by Netheous** [Facepunch/garrysmod-issues#2606]
I'm in need to track buttons that player is using while my panel is focused - the issue is that it won't accept my input unless I do MakePopup(), which sadly unparents my panel from the frame and disallows me to SetParent() it back.

Mind you calling panel:SetKeyboardInputEnabled( true ) doesn't do any good.
@edit Appearently it's still parented, just position is screwed.

**Comment by Netheous** [comment]
Mind you calling panel:SetKeyboardInputEnabled( true ) doesn't do any good.

**Comment by robotboy655** [comment]
```
	local a = vgui.Create("DFrame")
	a:SetSize(500, 500)
	a:MakePopup()
	
	local b = vgui.Create("DPanel",a)
	
	b:RequestFocus()
	b.OnKeyCodePressed = print
```
