### ISSUE TITLE
fist holdtype

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2607]
when switching from fist to normal holdtype sometimes it doesnt apply.

I tried to solve this too many times.
Sometimes when switching to fists it uses the pistol holdtype.

**Comment by robotboy655** [comment]
Are you referring to the Fists SWEP or some random SWEP that uses fists holdtype?

**Comment by robotboy655** [comment]
I am going to assume it is a problem with your code.

**Comment by mcNuggets1** [comment]
No it is the basic fist swep.

When switching to a swep with normal holdtype it does bug around.

**Comment by robotboy655** [comment]
Cannot reproduce that with the default fists SWEP:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/weapons/weapon_fists.lua

and a SWEP with normal holdtype, even with 600 ping and 50% loss.

**Comment by mcNuggets1** [comment]
I have to document this.

**Comment by mcNuggets1** [comment]
However in my listen server the issue is not there, but in my dedicated it is there.
