### ISSUE TITLE
Entity:GibBreakClient crashes client when used on func_button

### ISSUE THREAD

**Issue by RenTec** [Facepunch/garrysmod-issues#2609]
Testing the function entity:GibBreakClient from the wiki https://wiki.garrysmod.com/page/Entity/GibBreakClient will crash a client if used on a func_button.

```
function SWEP:SecondaryAttack()
	tr = self.Owner:GetEyeTrace()
		if !tr.Hit then return end
		if !tr.Entity:IsValid() then return end
	tr.Entity:GibBreakClient(tr.Normal*100)
end
```

[hl2_160424_crash_2016_5_13T5_32_4C0.zip](https://github.com/Facepunch/garrysmod-issues/files/262601/hl2_160424_crash_2016_5_13T5_32_4C0.zip)

**Comment by robotboy655** [comment]
Entity.GibBreakClient can no longer be called on non BaseAnimating entities ( Fixes crash when using on brush entities )
