### ISSUE TITLE
GM:AddDeathNotice can not be overrided through hooks

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#2611]
When DrawDeathNotice can be overrided
https://github.com/garrynewman/garrysmod/blob/451b4ff5d1aea7b9b06a8024ef706c248a79647e/garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua#L118
https://github.com/garrynewman/garrysmod/blob/451b4ff5d1aea7b9b06a8024ef706c248a79647e/garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua#L90
etc

**Comment by weemartin2001** [comment]
Has this been fixed?

**Comment by sannysc** [comment]
In this code, as well as the example on the wiki, it is used as a normal function, not a hook. Rubat has also confirmed this on the wiki page, but it looks like he reverted his edit claiming that. I think there is some confusion here about whether or not this is an actual hook or just a function.

**Comment by Kefta** [comment]
Should be a hook imo - would allow you to override/block the death notification details before they're sent

**Comment by weemartin2001** [comment]
I was thinking just use it so that it is only called everytime a player dies so you don't need to make your own functions for it (in other words I'm lazy)
