### ISSUE TITLE
Multiple Crash Logs When Joining Server

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#2615]
I haven't been able to test this crash much for symptoms, but the host that I was joining is using an external display at a different resolution than the native display onboard the host's laptop.  I joined the server and got three different crash logs.
[OSXCrash_1.txt](https://github.com/Facepunch/garrysmod-issues/files/265108/OSXCrash_1.txt)
[OSXCrash_2.txt](https://github.com/Facepunch/garrysmod-issues/files/265110/OSXCrash_2.txt)
[OSXCrash_3.txt](https://github.com/Facepunch/garrysmod-issues/files/265111/OSXCrash_3.txt)
I also got the error "attempt to call global 'GetViewEntity'(a number value)", and even later "not enough memory" which doesn't make sense in this case.

These aren't errors I've seen before, so I'd appreciate any feedback on these, and any fix if needed.

**Comment by willox** [comment]
Set cl _threaded_bone_setup to 0 in your console (SHIFT+ESC) and tell us the crashes continue

**Comment by Jake3231** [comment]
Sure.  I'll let you know once I can test that. Should be today!

**Comment by Jake3231** [comment]
I tried joining the same host on the same world with your command, and I got a crash still...  Here is the crash log I got.  I still need to test with the Tardis addon.  
[OSXCrash_4.txt](https://github.com/Facepunch/garrysmod-issues/files/265281/OSXCrash_4.txt)

**Comment by willox** [comment]
Is it possible one of your addons are changing the ConVar? Does this only happen on certain servers?

**Comment by Jake3231** [comment]
I haven't been able to test this much, but I think it's more likely for an arson to cause this than a certain server, as I am playing on LAN.

**Comment by robotboy655** [comment]
Closing as stale.
