### ISSUE TITLE
Large number of navmesh.GetNavAreaByID return NULL on some TF2 maps.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#2626]
I'm currently developing a gamemode that relies on the navmesh functions and ran into some tf2 maps that act a bit odd.
One of the maps in question is "cp_degrootkeep" where 53% of the 2651 navmesh returned [NULL].
![navmeshbug](https://cloud.githubusercontent.com/assets/4114136/15412259/763ea18c-1e26-11e6-89a6-95bb6b12f0ca.png)

The nextbot entities seems unaffected and can path-find areals without any problems. I did try to re-generate the navmesh, but with no different results.

Script used:
```
lua_run C = 0 for I=1,navmesh.GetNavAreaCount() do if !navmesh.GetNavAreaByID(I):GetSizeX() then C = C+1 print(I,navmesh.GetNavAreaByID(I)) end end print(100/navmesh.GetNavAreaCount()*C.."% out of "..navmesh.GetNavAreaCount().." is [NULL]")
```
Hope it helps.

**Comment by robotboy655** [comment]
Nav mesh generation ( and manual editing ) will cause certain nav areas be deleted, but the IDs will never be changed unless you do the compact IDs thing. Use the http://wiki.garrysmod.com/page/navmesh/GetAllNavAreas or compress your IDs. ( There's a console command for that, or you can just use my tool, Easy Navmesh Editor ).

There's a reason IsValid exists.
