### ISSUE TITLE
Help me with Gmod

### ISSUE THREAD

**Issue by 1Sans1** [Facepunch/garrysmod-issues#2634]
I got huge problems
I cant join the server, IP is 31.186.250.222:27015. It just disapeared from my history AND the server list. I tryed rreinstal the game. Rebooted steam, Rebooted PC. Verifid my Cache .Nothing helped. I cant even join on my friend it says "Server is not responding". Help me please!

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
