### ISSUE TITLE
Developer Console weird.

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2635]
Something bad has happened with the developer console it is black and if I want to select the text it goes all black.
here when I not select the text. [Pic](http://i.imgur.com/KepCOva.png)
When I select the text. [Pic](http://i.imgur.com/wwSNuOv.png)
Not just Developer console the whole UI. [Pic](http://i.imgur.com/BOiQDKf.png)
Version:
```
Protocol version 24
Exe version 16.04.30 (garrysmod)
Exe build: 02:02:36 May 11 2016 (6381) (4000)

```

**Comment by Bo98** [comment]
#2632

**Comment by kem008** [comment]
It solved somehow. When I joined to a server and ye I am using Win 7 64-bit

**Comment by kem008** [comment]
But please fix it. I dont want to spam on every start this mat_reloadallmaterials
