### ISSUE TITLE
CUtlLinkedList overflow! (exhausted index range) (65535)

### ISSUE THREAD

**Issue by BoXiousNet** [Facepunch/garrysmod-issues#2636]
I'm posting this here, because I'd like a detailed explanation over what caused this issue.

A player used a detonation pack to explode a lot of zombies, and that caused only 3 players to crash, including myself.

Crash dump included: https://db.tt/hgTjm4kI

**Comment by robotboy655** [comment]
I guess search is too cool for you.

#1968
