### ISSUE TITLE
Clientside Entity:CallOnRemove is triggered each time a large lagspike occurs.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2637]
Checking if the entity is valid inside the callback returns true too.

**Comment by thegrb93** [comment]
Here's my workaround

ply:CallOnRemove("clothes",function() timer.Simple(0, function() if not ply:IsValid() then clothes:Remove() end end) end)

**Comment by thegrb93** [comment]
I guess the player entity gets recreated after lag?

**Comment by robotboy655** [comment]
I don't think its a bug.

**Comment by thegrb93** [comment]
I also found that a clientside prop will come unparented from a player if there's a lagspike, they noclip through the map, leave the PVS you're in, and sometimes when exiting a vehicle. Should I just put SetMoveParent in a think hook or something?

**Comment by LeQuackers** [comment]
Not sure about the vehicle thing, but Entity:Remove gets called when an entity leaves the local player's PVS and Entity:Initialize gets called when the entity re-enters it. Hooking GM:NotifyShouldTransmit might be applicable if you're using client side models.

pull request [#1295](https://github.com/garrynewman/garrysmod/pull/1295)

**Comment by DBotThePony** [comment]
This is not a bug, but a design oversight of source engine. On huge lag spike, client request full update AND purge all known serverside entities outside of current PVS

**Comment by DBotThePony** [comment]
And about clientside model parenting - use https://wiki.facepunch.com/gmod/GM:NotifyShouldTransmit

**Comment by robotboy655** [comment]
Ultimately caused by https://github.com/Facepunch/garrysmod-issues/issues/4675
