### ISSUE TITLE
Endless loop with timer.Simple()

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#2638]
Hi Rubat, hi William, hi everybody,

Maybe I am dumb, but here's my problem.

I wanted to see the team right when it's available on the client, so I made a small code. Unfortunately it fails and produces an endless loop. :worried:
```lua
local function loopuntilteam()
	if LocalPlayer().Team then
		print( LocalPlayer(), "is in the team", LocalPlayer():Team() )
	else
		timer.Simple( 0, loopuntilteam )
	end
end
loopuntilteam()
```

That would be safer if timers added from timers were executed on the next frame. What do you think?

Momo. :heart:

**Comment by ExtReMLapin** [comment]
are you retarded

**Comment by EstevanTH** [comment]
I totally forgot about the Think hook, thanks for the idea.
By the way I found out the team I was looking for: it's `0`.

**Comment by mcNuggets1** [comment]
This should be closed.

**Comment by EstevanTH** [comment]
I honestly do not think so. :grimacing:

**Comment by ExtReMLapin** [comment]
It should not even be on github. There are places for learning lua, github issues repo is not one.

**Comment by thegrb93** [comment]
Infinite callback loops aren't an issue with garrysmod.

**Comment by robotboy655** [comment]
Funny thing it works on my end, anyway, use Think hook as already suggested.

**Comment by thegrb93** [comment]
I didn't know this before now, but this actually causes softlock now. Didn't it used to get executed next frame? Now it freezes the game.

**Comment by EstevanTH** [comment]
That is exactly what I spotted: when `timer.Simple( 0, TheFunction )` is executed during the timers execution, the execution of the added timer is not guaranteed to be done on next frame and hence can produce an endless loops that may not be expected by a developer in a few cases.

**Comment by thegrb93** [comment]
I think it's because adding a 0 duration timer inside of a timer callback causes it to execute on the same frame rather than the next frame.

**Comment by EstevanTH** [comment]
Yes, I think that in those cases, a tiny delay such as `0.001` must be selected to force the execution on next frame.

**Comment by ExtReMLapin** [comment]
S T O P

P O S T I N G
