### ISSUE TITLE
Game Unplayable + Menu Glitched - PLEASE HELP

### ISSUE THREAD

**Issue by korbinpl** [Facepunch/garrysmod-issues#2640]
First off, I would like to say that I have already tried these things:
-_Verify Integrity of Game Cache_
-_Reinstalled Gmod_
-_Remove all addons through "addons" folder_

Now, onto the error itself.
______________________________________________________
______________________________________________________

![](http://i.imgur.com/EfNtxi1.png)
**This is the console when I first load into the menu.**

______________________________________________________

![](http://i.imgur.com/T3b2WZy.png)
**This is what my singleplayer menu looks like, even though I have maps**

______________________________________________________

![](http://i.imgur.com/HD0PYaf.png)
**This is what my "Addons" "Saves" & "Demos" menus all look like**

**Then each menu is followed by this same error**
![](http://i.imgur.com/VS0gZWw.png)

______________________________________________________

![](http://i.imgur.com/RfYtPzt.png)
**I then join a map through console**

![](http://i.imgur.com/w5Rr4PY.jpg)
**Random spawn point. Item list not working. No weapons are able to be switched to. It's broken**

**_CONSOLE WHEN I JOIN A MAP_** https://justpaste.it/up5h

______________________________________________________

**I then try to open the door, and right as I click "E" on it, my game crashes and I receive this error**
![](http://i.imgur.com/D0qhUMl.png)

______________________________________________________

Anyone please help! I really would appreciate it.

**Video preview of the error, includes multiplayer errors too. Please watch.**
https://youtu.be/kZl8GOOmHAY

**Comment by robotboy655** [comment]
First of all, this is not a place to get help, secondly, uninstall your addons before reporting stuff like that.

https://facepunch.com/forums/16 - For GMod help

Also you should've posted basic PC info, how many HDDs you have, which of them has Steam, which of them has GMod, addon list, anything at all that we can work with.
