### ISSUE TITLE
Weird Issue with Entity:CallOnRemove

### ISSUE THREAD

**Issue by gspetrou** [Facepunch/garrysmod-issues#2641]
I'm not sure if reporting this is even worth it because I honestly have no clue how to reproduce it but I was once given the error bellow on my TTT server. While the error traces back to some TTT code the error occurred in a non-TTT file and looks like it could happen to any entity. I'm assuming a simple validity check would fix the issue but thought I might as well report it anyways.

```Lua
lua/includes/extensions/entity.lua:104: attempt to index local 'mytable' (a nil value)
  1. CallOnRemove - lua/includes/extensions/entity.lua:104
   2. efn - gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua:189
    3. unknown - gamemodes/terrortown/gamemode/corpse.lua:438
```

I should also mention that this wasn't a random event. The error occurred when the knife should have been removed.

**Comment by thegrb93** [comment]
https://github.com/garrynewman/garrysmod/blob/eaf7d98968e8c2e887c03a60130eaf224a884643/garrysmod/gamemodes/terrortown/gamemode/corpse.lua#L440

rag was NULL when this line was executed?

**Comment by gspetrou** [comment]
I guess so? Like I said I don't have much info on the issue, sorry.

**Comment by robotboy655** [comment]
Nothing special, just a missing validity check in TTT.
