### ISSUE TITLE
Can we do something against fake server ?

### ISSUE THREAD

**Issue by MrDiaboloz** [Facepunch/garrysmod-issues#2642]
Hello,
I have a community of 2 server in garrys mod but we have everytime soem people who copy our name and our idea to steal our community or weist i want to know if we can do something (they didnt respond when we contact hem) there is a way to warn these server ?

**Comment by kem008** [comment]
No becuz. Gmod not support that. You can steal others idea also. Its a problem. But nobody can find out who is the original creator. But in the real world same happening.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
