### ISSUE TITLE
i cant join any servers anymore

### ISSUE THREAD

**Issue by killermemestar** [Facepunch/garrysmod-issues#2646]
i have no idea if this is about the addons because this only started when i tried joining defcon's methrp server and when i try joining any server including defcon's methrp sometimes when im loading my game goes into my tab the bottom and then i try to make it full screen again then it just says my name timed out and when it doesnt happen then the second i finish loading i lose connection (red text at the upper left corner on a timer) i experience it on 2016.04.24 version and i tried exiting the game and restarting my computer and i still have the same issue singleplayer works fine though

**Comment by Kefta** [comment]
Can't confirm on my dedi; it's not a GMod issue.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
