### ISSUE TITLE
Bug With barnacle

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#2647]
Barnacle Can not eat headcrab on zombie pls fix it
![20160529184327_1](https://cloud.githubusercontent.com/assets/10911451/15634476/10bbd7a2-25c5-11e6-9628-8370a6e8cf68.jpg)
![20160529184330_1](https://cloud.githubusercontent.com/assets/10911451/15634478/17074678-25c5-11e6-9871-ee3a05a14a0b.jpg)

**Comment by robotboy655** [comment]
Are you serious?

**Comment by Cthutq295** [comment]
yes

**Comment by kem008** [comment]
It is an animation and part of other stuffs. Please stop being that XDDDDD
