### ISSUE TITLE
TTT server Crash (vphysics)

### ISSUE THREAD

**Issue by matiasg90** [Facepunch/garrysmod-issues#2649]
Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x7fd5934

Thread 0 (crashed)
 0  vphysics.dll + 0x8ccbc
    eip = 0x69d6ccbc   esp = 0x0027d108   ebp = 0x0027d124   ebx = 0x000ffff0
    esi = 0x062eef84   edi = 0x0000ffff   eax = 0x07ed59c0   ecx = 0x07ed5940
    edx = 0x0000fffe   efl = 0x00010206

https://facepunch.com/showthread.php?t=1517254
the server goes down about 10 times a day.

**Comment by Kefta** [comment]
Are these ConVars enabled? https://facepunch.com/showthread.php?t=1508156&p=49825601&viewfull=1#post49825601

Also @willox , it happens in TTT (and Zombie Survival, but that gamemode has become antiquated) because of the fact that the bodies are set to the DEBRIS_TRIGGER collision group, which seems to marginally increase crashes.

**Comment by matiasg90** [comment]
sv_crazyphysics_warning 1
sv_crazyphysics_remove 1
sv_crazyphysics_defuse 1

**Comment by Kefta** [comment]
Do you get warnings before a crash?

**Comment by matiasg90** [comment]
No

**Comment by matiasg90** [comment]
More dumps:
http://dumps.metastruct.uk.to/dumper.py?dump=srcds_2117156_crash_2016_6_1T3_23_11C0.mdmp&key=Bekmxq3ceI30zlFycNKCq9tbPEhCxompjp2MRQrv8FxUDcaezS5kFBoRYkRpWGTfseF8E59P9bmUcTXxfuuBRnqcHjI0YaQLYi0jQx1wyOs2cwD_vPTd6Uxru3HQEe1iy2ReeEsEbpnghFjLvZdjmEEVldD6v9jNa2N1-uHeGt8=

http://dumps.metastruct.uk.to/dumper.py?dump=srcds_2117156_crash_2016_6_1T4_57_6C0.mdmp&key=kjIeNMD3CdAG0qY5JptacCWvhDsD2dfjP_sQhP7I9Y884SjL2fC4m_LpAadTE7_soOHMDccaXJdo-BjK2d_OddH5Z56iBHtzs2me8a33H7cshz034ZzIkYOsrFARjpv4C-gYPdcMNYob_L1-O0-lqPXkC7fwnaTcTh7mBWqTThY=

**Comment by matiasg90** [comment]
More dumps:
http://190.112.0.107:88/dev/dump.rar

moment before crashing (the body goes crazy and flies all over the map.)
https://i.gyazo.com/db38a8d24ef157fb933ce080c3d1c1d1.png

**Comment by robotboy655** [comment]
Closing as stale.
