### ISSUE TITLE
Bear glitch

### ISSUE THREAD

**Issue by demandred87** [Facepunch/garrysmod-issues#2653]
Two times today a bear has glitched through foundation. First time I logged in to find I was killed by a bear while logged off sleeping on the ground floor in my temp base. Second time I found a bear inside my courtyard which is surrounded by a foundation perimeter. Prior to this last patch, they were able to glitch through high externals, but not foundation.

**Comment by zerfgog** [comment]
you do understand that there is a difference between the words `garrysmod-issues` and `rust`, right?

**Comment by demandred87** [comment]
Yes, I do know there is a difference between what he says and what is actually the truth due to the fact that one, this is an alpha early release game, and second the fact that he must be a very busy man so things won't be perfect. What I am getting at is that I personally nor have I heard of other people whether on the Reddit sub, youtube, or twitch having bears glitch through foundation. We all know they they glitch through deployable items such are furnaces, high externals, and others but through foundation, no. The purpose of this post though is nothing more than to report a glitch, but since FacePunch doesn't have their own dedicated internal bug report setup, I am posting here.

**Comment by bigdogmat** [comment]
> Yes, I do know there is a difference between what he says and what is actually the truth due to the fact that one

What? No really, tell me you're trolling

**Comment by zerfgog** [comment]
The point of my comment was that you have the wrong game here; this is the Garry's Mod issue tracker, not Rust. You can't report problems with rust here; they'll be ignored.

**Comment by demandred87** [comment]
Son of a bitch. I clicked the link on the rust page and it took me here. Thanks.

**Comment by demandred87** [comment]
I only half read your comment.

**Comment by Bo98** [comment]
Out of interest, on which "rust page" did you find a link to here?
