### ISSUE TITLE
Game hates singleplayer

### ISSUE THREAD

**Issue by Wrenchy247** [Facepunch/garrysmod-issues#2654]
Whenever I load up a map in singleplayer, the game keeps crashing. On multiplayer, the game loads up successfully, but on singleplayer, no! I validated the files, Reinstall the game, deleted some add-ons. NOTHING WORKS! I hope you guys fix this in the next update.

**Comment by Kefta** [comment]
Try it with a fully vanilla game on the dev branch. Also, provide crash logs and system information.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
