### ISSUE TITLE
Blood Decals

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2659]
If you shoot something, which stands behind a entity, the blood decal appears behind the entity, on the world.
Why can't blood decals stick to entities, like in original half-life2?

**Comment by robotboy655** [comment]
Please stop crating these worthless "reports". We will not spent time on "fixing" Source Engine behavior just because there is a single person who thinks we should or that it is "incorrect".

**Comment by mcNuggets1** [comment]
I would fix it up myself, but as I have no access and it is not possible to override with mods, I have no choice but creating an issue, which is quite not worthless.
I am not the only human on earth, who has noticed it. 
If it was source engine behaviour, then why does it work in HL2?
