### ISSUE TITLE
Players x has joined the game, another time

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2660]
Player x has joined the game it is called. But it is should be called Player x is joining the game and there should be a message for when the player is really connected, not when just beginning to connect.

Why was this closed, btw?
It is a issue. Not a big one, but still a issue

**Comment by Kefta** [comment]
@mcNuggets1 Is right. It's called before this should be: https://github.com/Facepunch/garrysmod-requests/issues/718

**Comment by robotboy655** [comment]
Please stop crating these worthless "reports". We will not spent time on "fixing" Source Engine behavior just because there is a single person who thinks we should or that it is "incorrect".

**Comment by mcNuggets1** [comment]
It is a 2 second fix, which should'nt bother to fix it all.

I am not a single person, alot of people are getting distracted because of this wrong messaging.

**Comment by Kefta** [comment]
It's a language fix?
