### ISSUE TITLE
Annabelle

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2661]
When reloading the annabelle shotgun, an error pops up:
ERROR: Shotgun Reload called incorrectly!

**Comment by Kefta** [comment]
Because it's meant for NPCs. I can Lua port it for players if you wish.

**Comment by mcNuggets1** [comment]
I know it is meant for NPCs, but why can Players pick it up then?

**Comment by kem008** [comment]
You can pickup alyxgun as well and other npc weapons. But it was scripted for npc so no client side script for it. Only server side.

**Comment by Kefta** [comment]
Because Father Gregori was never meant to die. I believe this was patched in HL2 a while back.

**Comment by mcNuggets1** [comment]
If Alyx dies, the Alyx Gun is not dropped.

**Comment by kem008** [comment]
Normal. Alyx never die.

**Comment by mcNuggets1** [comment]
If I kill her, she dies.

**Comment by kem008** [comment]
But the weapon scripted as Alyx never dies. If she dies then the weapon disappear.

**Comment by mcNuggets1** [comment]
Why does Grigoris weapon then stay?

**Comment by kem008** [comment]
Dunno yet. You should ask Valve about it. Maybe they wanted to give that weapon to the player but later they ignored that project and they left the code there. To be able to pick up.

**Comment by Kefta** [comment]
As I said, they already fixed this in HL2. Reporting that Gregori should not drop the Annabelle is a valid report. This is not.

**Comment by mcNuggets1** [comment]
What is wrong with just using the fix, the source engine used?

**Comment by robotboy655** [comment]
As you can see on this picture:
()[http://i.imgur.com/SZnxshC.jpg]

He does indeed drop the weapon in HL2 too.

**Comment by mcNuggets1** [comment]
Isn't it fixable though?

**Comment by robotboy655** [comment]
It's default Source Engine behavior, which we will not change.

**Comment by mcNuggets1** [comment]
Why not?
1 line code.

**Comment by robotboy655** [comment]
Quoting myself:
```
We will not spent time on "fixing" Source Engine behavior just because there is a single person who thinks we should or that it is "incorrect".
```

**Comment by robotboy655** [comment]
Single person might be exaggeration in this case, but you get the point. It's not broken, it won't be "fixed".

**Comment by mcNuggets1** [comment]
Then fix the reload error.

Error means broken.

**Comment by robotboy655** [comment]
Won't be spending time on something that
1) Works even though prints errors
2) Nobody uses

Might hide the error, but then again, why bother.

**Comment by mcNuggets1** [comment]
It bothers, because it throws an error.

**Comment by Kefta** [comment]
It was not intended then.
http://steamcommunity.com/games/220/announcements/detail/2110217062141668727

Read the last note.

**Comment by mcNuggets1** [comment]
good point

**Comment by robotboy655** [comment]
"Fixed being able to pickup Grigori's annabelle in Ravenholme if you got to the wrong place at the wrong time" != It shouldn't be dropped when he is killed, which is default behavior for any NPCs death.

**Comment by Kefta** [comment]
Can you make Alyx drop the Alyx gun then for consistency?

**Comment by robotboy655** [comment]
I think that will cause problems in episodic campaign when alyx picks up a different gun and maybe when holsters her weapon. If I wasn't clear before, I'd rather avoid changing default HL2/Source behavior, to be consistent with HL2 and stuff.
