### ISSUE TITLE
Father Grigori should not drop the Annabelle

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2662]
The Annabelle should be removed on Death of Father Grigori, like the Alyx Gun, instead the player can pick it up.

https://github.com/Facepunch/garrysmod-issues/issues/2661

**Comment by kem008** [comment]
man this is by Valve it is normal. Forget that thing.

**Comment by Kefta** [comment]
@kem008 Valve fixed it already.

**Comment by kem008** [comment]
Maybe in gmod wasnt included the fix.

**Comment by robotboy655** [comment]
Please stop crating these worthless "reports". We will not spent time on "fixing" Source Engine behavior just because there is a single person who thinks we should or that it is "incorrect".

Especially since these can be "fixed" by mods.

**Comment by mcNuggets1** [comment]
This can be fixed by mods, but it should be fixed in actual game, not by mods.
