### ISSUE TITLE
GetSaveTable incompatible with array fields.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#2667]
It will only return/set the first value in the array, serialization is impossible by that. 
Best example would be m_GMOD_int, m_GMOD_bool, etc., since there are 32 of each theres no way to set/get the values.

**Comment by robotboy655** [comment]
Is there anything else that uses this? You can get the m_GMOD* values using the Entity:GetDT* functions.

**Comment by ZehM4tt** [comment]
Well you are right about GetDT however for serialization purpose it would be nice to have something generic where I don't have to ignore specific fields.

**Comment by Kefta** [comment]
It would be nice if this function worked properly clientside, as well.

**Comment by ZehM4tt** [comment]
Also it would be nice if we would have extended information about the fields, some are FIELD_POSITION (world absolute) and some are FIELD_VECTOR (relative), I can not tell the difference by the value alone, this is important if you transition them via a relation entity such as landmarks, atm I have a tons of fields hardcoded, this is not optimal at all. It would be somewhat nice if there would be alternative binding such as GetDataDescField/GetCountDataDescField/SetDataDescField, its probably best its mapped as [key] = { {entry1}, {entry2} } for array support.

**Comment by Kefta** [comment]
m_rgflCoordinateFrame is a great example. I could create the function requested in https://github.com/Facepunch/garrysmod-requests/issues/761 myself if I could get the field as a VMatrix or even table of tables. It wouldn't be pretty, but possible.

**Comment by robotboy655** [comment]
Should be handled

**Comment by ZehMatt** [comment]
Okay that seems like a step forward,  now how do we set those fields? This change broke pretty much my entire gamemode due its new output format.

**Comment by robotboy655** [comment]
Hey, you asked for it, not me. And you can't set this yet.

**Comment by robotboy655** [comment]
I don't really see how your gamemode would break from this tho, unless you call SetSaveValue on each table key?

**Comment by ZehMatt** [comment]
Thats the point of serializing, only the positions/angles requires correction. So could you perhaps allow the input to be a table? Also what would be the point having the data if I can't set it back at some point?

**Comment by Kefta** [comment]
Maybe just allow a sequential table of values for setting? Just like the Get output.

**Comment by ZehMatt** [comment]
Thanks, that did the trick.
