### ISSUE TITLE
Dupe and Save not working

### ISSUE THREAD

**Issue by Soeone** [Facepunch/garrysmod-issues#2671]
Some How the dupe and save tags is not working And i also restarted my Garry's mod but it did not work. It says Website unreachable. How do you Fix it Plz!

**Comment by robotboy655** [comment]
I have no idea what you are talking about.

**Comment by Kefta** [comment]
He's referring to subscribing to dupes and saves I believe

**Comment by robotboy655** [comment]
"Website unreachable"?

**Comment by WilliamVenner** [comment]
maybe some shitty antivirus

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
