### ISSUE TITLE
Vehicles (mainly cars) have no Shadows while driving.

### ISSUE THREAD

**Issue by chip1234RR** [Facepunch/garrysmod-issues#2673]
here some screenshoots of my problem: http://puu.sh/ptzNv/34eb568d6c.png you can see the jeep i am currently driving does not have a shadow, but the car in the background that is not beeing driven at the moment has one. this issue has not been there when i first got the game, here a screenshoot from 2015 http://puu.sh/psXAP/7ffc4b5579.png and the same picture remade today http://puu.sh/ptzsu/ae9118ba3e.png i need this fixed as soon as possible.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
