### ISSUE TITLE
It's completely impossible to align the text of DTextEntries to the left, center or right

### ISSUE THREAD

**Issue by Mysterypancake1** [Facepunch/garrysmod-issues#2676]
Not much more to say here.
![](https://camo2.githubusercontent.com/3cd5a8990c61906788ecab7d1a5e0c544cbbcd42/687474703a2f2f692e696d6775722e636f6d2f62555667307a772e706e67)
I also requested this [here](https://github.com/Facepunch/garrysmod-requests/issues/680).

**Comment by robotboy655** [comment]
Do not duplicate requests.

**Comment by Mysterypancake1** [comment]
Sorry, it's just that I really want this to be fixed, and it hasn't been fixed after many months now, good to know you're at least reading the issues/requests :)
