### ISSUE TITLE
Broken Optimization

### ISSUE THREAD

**Issue by BrewsterTKoopa** [Facepunch/garrysmod-issues#2678]
The April update has broken the optimization.Big maps like gm_chapparal gm_Gmall and so forth lag like heck,my PC has great specs it was also just fine before the update. the creator of gm_chapparal had made a optimized version but it does not work i'm not saying "focus on fixing the maps" I'm just asking,can you please fix the optimization problem? Its not the maps themselves, Its the optimizing for them. It ruins my video making as most of these maps I require for my videos. I'm not the only one having it too,i know alot of other people suffering from it,it doesn't make all maps lag,but only big ones. Also these maps used to work just fine before the April  update too,mind that.

**Comment by BrewsterTKoopa** [comment]
This should be a bug or breaking issue,the update broke optimizing,thus rendering is broken for a majority of maps

**Comment by Kefta** [comment]
What did it SPECIFICALLY break besides your FPS? I haven't noticed any change.

**Comment by BrewsterTKoopa** [comment]
It's not just mine,basiclly this,I got a high-end running PC my friend does too,He said told me how optimization works, the maps i described worked just fine up until the april update,he made it so you can see the world in wireframe,he said it shown the entire map was rendered,no render fog at all(as shown here http://steamcommunity.com/sharedfiles/filedetails/?id=702573906 ),he saw through the map from parts where if you looked it would not be seen,yet he saw it. he went to rp_Downtown and that map had no lag(as shown here http://steamcommunity.com/sharedfiles/filedetails/?id=702579842 ) when i told him about  "gm_chapparal" he went on on it and shows the map was completely lagging like hell.

**Comment by BrewsterTKoopa** [comment]
for short:it broke optimization

**Comment by Kefta** [comment]
You're referring to occlusion. Can you confirm this is not happening in another Source game (CS:S or HL2)?

**Comment by BrewsterTKoopa** [comment]
hm,i could try? I'll see about getting one of these maps onto CS:S But do awnser while i do this. What if it only effects gmod?

**Comment by BrewsterTKoopa** [comment]
just tested a different map(cause i couldn't get the other two) one that does suffer broken optimizing,yeah i runs perfectly fine on CS:S.

**Comment by robotboy655** [comment]
Do you have anything to back that up? Like a side by side comparison of the wireframe in CS:S and GMod in exact same position ( use getpos and setpos concommands ) where in GMod "you can see more in wireframe than in CSS"?

**Comment by BrewsterTKoopa** [comment]
well those side-by side comparison of the two maps listed above are my back-ups,but i'll do a couple of videos or screenshots(videos of the lag if i can't get the wireframe command to work)

**Comment by robotboy655** [comment]
"videos of the lag" would not be helpful at all. for mat_wireframe to work, you need to have sv_cheats set to 1.

**Comment by BrewsterTKoopa** [comment]
True. One moment,Robotboy

**Comment by BrewsterTKoopa** [comment]
Well here you go

http://steamcommunity.com/sharedfiles/filedetails/?id=706058952

http://steamcommunity.com/sharedfiles/filedetails/?id=706070356

**Comment by robotboy655** [comment]
* Your games do not run at the same resolution ( CSS is 720p, GMOD is 900p )
* Probably do not have exact same video settings, make sure they do ( Multi core rendering should be disabled on both )
* Should've used getpos, setpos console commands
* No FPS counter?
* Is GMod running with no addons?
* Every single thing visible in wireframe in GMod is still visible in wireframe in CSS

**Comment by BrewsterTKoopa** [comment]
A:oh
B:i'll test it out
C:i'll try those
D:i did use fraps on gmod(5 FPS)
E:no its not it ran with my usual amount of addons,and yes i did get rid of a large amount and it still lags
F:took me a while to notice the red but i'm no expert with it okay?


I would like to again,point out this http://steamcommunity.com/sharedfiles/filedetails/?id=702579842  this is a map with a good optimization.

 this one isn't and it lags like heck http://steamcommunity.com/sharedfiles/filedetails/?id=702573906 it again,used to ran JUST fine before the April update he said i should be able to see these mountains

**Comment by robotboy655** [comment]
There's no way a huge, possibly larger than flatgrass map with 0 map optimization ( Nothing in the map breaks view from one corner to the other ) worked "just fine" before the update and would "lag like heck" now.

**Comment by BrewsterTKoopa** [comment]
It did. The entire time i would play before the update it would be fine. plus i played on gm_Gmall that map is fairly is smaller then gm_flatgrass(maybe the old one?) that map ran just fine too mind that,i would've gotton some pictures of it in CS:S but my paranoia of workshop downloaders got the best of me. To quote my friend who also experienced the issue,these are his words.

"holy shit yeah"
"I see what you mean"
"30 FPS"
"if i'm on the outside of the map and look towards the inside,the map is not optimized, thats why"

"maybe the update broke the hint blocks(optimization blocks),i'm having trouble optimizing a map of my own,"

He setted sv_cheats 1 and mat_wireframe 1 then shown me the image of the mountains picture

"thats what you would see,the blue indicates blocks/props.green boxes indicate effects such as lighting,there are several mountains blocking the town in the distance,you shouldn't be able to see them" 
"this is because:there is no fog to hide the distance,so you can see so far you can see the entire map,even the things underground which you can't see naturally,thus bad preformance"

He did sv_cheats 1 and mat_wireframe 1 to another map.
"and go behind a building or something to see if the map is loading in it's entirety and if its, bad optimization."

He shows me rp_downtown_v4c_v2, a well optimized map http://steamcommunity.com/sharedfiles/filedetails/?id=702577922
"this is the corner of the map you can't see the other side of the map because it is optimized"
Then he tells me he uploaded 4 more screenshots
http://steamcommunity.com/sharedfiles/filedetails/?id=702579057
http://steamcommunity.com/sharedfiles/filedetails/?id=702579216
http://steamcommunity.com/sharedfiles/filedetails/?id=702579666 
the forth was the "optimisation" one i shown earlier.

**Comment by robotboy655** [comment]
Yes, that's how map optimization works. (roughly). As you can see on your rp_downtown_v4c_v2 picture, the optimization on maps is not broken in Garry's Mod.

Here are two comparison pictures of the big map that "worked better for you":
CSS: http://i.imgur.com/FuqXij9.jpg
GMOD: http://i.imgur.com/pZ4a8sh.jpg

With identical video settings, on the exact same spot, as you can see, the performance is pretty much identical. My settings being: http://i.imgur.com/OHWnGkE.png

Its the map's fault that it is unoptimized, not the game's

**Comment by robotboy655** [comment]
And this is considering Garry's Mod is more demanding than CS:S is. The picture was taken without any mods what so ever. Not to mention Garry's Mod will have fixed "multicore rendering", doubling your FPS in most cases.

**Comment by BrewsterTKoopa** [comment]
i'm loading rp_downtown_v6 without addons right now,if it lags i'll do the video settings as shown in CS:S if that does not work,i'll try yours. I'm sorry if  i sound rude or annoying,i'm trying my best to help everyone who has this problem

**Comment by BrewsterTKoopa** [comment]
its..fixed,i loaded it up...too many addons...of..course well nvm, i'm just a huge idiot say now,What is the recommended amount of addons one should have?

**Comment by robotboy655** [comment]
There's no such thing as "recommended amount of addons". Just uninstall addons you don't use, or think might be causing performance issues.

**Comment by robotboy655** [comment]
If you can identify what addons are slowing down the game, you should report that to the addon author.

**Comment by BrewsterTKoopa** [comment]
alright,thanks robotboy,sorry for wasting your time :c

**Comment by BrewsterTKoopa** [comment]
okay issue STILL has problems http://steamcommunity.com/sharedfiles/filedetails/?id=707124714

>wireframe
>I disabled all the addons except 3,counting this map the other two were it's content packs
this is a gargantuan map,low FPS as you can see.

I used to have atleast 1000 addons,game ran fine before the update,unclose this issue casue it is NOT solved!

**Comment by BrewsterTKoopa** [comment]
now i got atleast like 200 and it still lags like heck

**Comment by robotboy655** [comment]
We have already established that one of your addons is causing the problem. It takes only 1 to fuck up your FPS. Or the map is very badly optimized.
