### ISSUE TITLE
TTT Lua Error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2679]
[ERROR] gamemodes/terrortown/gamemode/weaponry.lua:271: Tried to use a NULL entity!
  1. Remove - [C]:-1
   2. unknown - gamemodes/terrortown/gamemode/weaponry.lua:271
    3. unknown - lua/includes/modules/concommand.lua:54

**Comment by robotboy655** [comment]
This is not a place to report TTT bugs.

Either send a Pull Request to fix the bug ( https://github.com/garrynewman/garrysmod ), or contact the gamemode author. ( https://github.com/garrynewman/garrysmod/tree/master/garrysmod/gamemodes/terrortown )
