### ISSUE TITLE
About Garry's mod problems

### ISSUE THREAD

**Issue by Elvinkey9x** [Facepunch/garrysmod-issues#2680]
[http://imgur.com/kikZPWt](url)
Do anyone know how to fix it ? I verify integrity of game cache... many times, reinstall games but it does not work

**Comment by Kefta** [comment]
Delete your VPKs in garrysmod and sourceengine, then verify. Also, this is not the place for help -- it's for GMod bugs.

**Comment by BrewsterTKoopa** [comment]
what about the optimization i told of? The amount of addons i have DOES NOT work for it and i got new proof of it

**Comment by thegrb93** [comment]
This is unrelated, Koopa.

**Comment by BrewsterTKoopa** [comment]
right.Sorry

**Comment by robotboy655** [comment]
Should be fixed in Dev Beta branch.
