### ISSUE TITLE
Clientside weapon state is purged too quickly on player death

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2681]
- Player dies
- Holster is called serverside only

If you try networking to the client to tell it to run the Holster method, it's no longer available, making for really hacky methods to reset any player variables.

**Comment by willox** [comment]
This was once the case and has since been changed back. The entity is valid up until the EntityRemoved hook is ran.

**Comment by roboderpy** [comment]
Use OnRemove. It is called clientside.

**Comment by Kefta** [comment]
It's not when the player dies.

**Comment by Kefta** [comment]
I lied, it is called but later than the server after network variables have already been updated. I don't really know why Holster is called at all when the player is dying, but it can be worked around.
