### ISSUE TITLE
Server crashes upon executing ent_create

### ISSUE THREAD

**Issue by RyanJGray** [Facepunch/garrysmod-issues#2683]
I know this is probably not mean't to be used on the server at all, but I thought that I would post this here anyway.

Basically, the server crashes when you run the following concommands:

1. sv_cheats 1
2. ent_create weapon_pistol

This is what happens when you try this:
![ss 2016-06-23 at 09 57 30](https://cloud.githubusercontent.com/assets/3857322/16320045/c099d972-398d-11e6-8761-7529ba15612d.png)

You probably won't need it but here's the MDMP file:
[srcds_2117156_crash_2016_6_23T20_57_10C0.mdmp](http://puu.sh/pDwm7/d1e50fd697.mdmp)

**Comment by robotboy655** [comment]
![http://i.imgur.com/VWFJFLw.png]()

Cannot confirm.
