### ISSUE TITLE
Gmod bug

### ISSUE THREAD

**Issue by iblue001** [Facepunch/garrysmod-issues#2686]
Hello so I just got Garry's mod and as soon as I click refresh page it freezes and the same sound keeps playing over and over. I have a decent PC so it isn't that. I have directx 11. My PC specs are Intel core i7 5500u nvidia 940m with 2gb of vram. 8gb ddr3 ram. If you need any other information just tell me.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
