### ISSUE TITLE
ENT:Touch - functionality changed

### ISSUE THREAD

**Issue by suicidalbanana** [Facepunch/garrysmod-issues#2689]
Heya's,

Just a heads up that something seems to have changed with the ENT:Touch function, got a bug report on a age old mod saying it was suddenly acting up in certain maps, and it turns out it was detecting ENT:Touch on trigger entity's on some maps, which it never did before. (edit: trigger_soundscape to be specific)

So i went to investigate and noticed this:
https://wiki.garrysmod.com/page/ENTITY/Touch
That page has been last updated the 20th of this month, making me think something was changed around the same time.

So the reason im making this issue is that the recent change (whatever it was) doesn't seem to have gone well, since without any change to my code the addon suddenly started acting different because of the changed ENT:Touch now firing for trigger_* entities.
Since im guessing that thats a bug (new behavior replacing old behavior rather then beeing an optional new feature) im posting it here, if its not a bug, my bad for misunderstanding, and it might be an idea to start posting changelogs (targeted at devs) to steam then (im not going near fp with a 10foot pole)

Best regards,
..

**Comment by robotboy655** [comment]
Nothing about it was changed, and most definitely not on 20th June. The last Garry's Mod update was in April.

All the changes are documented on the official website and are linked to with each update from Steam Announcements.

http://www.garrysmod.com/updates/

**Comment by suicidalbanana** [comment]
Ok then, mustve been something else(?..), ty for the updates url & info :)
