### ISSUE TITLE
Odd Engine Error *Downloading issue?*

### ISSUE THREAD

**Issue by Unknownic** [Facepunch/garrysmod-issues#2691]
Couldn't include file 'panel\animation.lua' (File not found)
(@lua/includes/extensions/client/panel.lua (line 2))

-I've verified
-I've deleted it and verified
-I've checked and it was actually there
-It might be a downloading issue..

what could I do?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
