### ISSUE TITLE
Pre-Release DFrame Crashes

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#2695]
My Awesomium web browser started crashing when closing the window, on pre-release. This was a never before seen issue on the previous version of Garry's Mod. My entire game client is crashing when this happens, which is kinda lame considering it is or should be separate for redundancy purposes.

It happened three times in a row. The first time I had low memory and corrected the issue. I believe the second and third time could have been a side-effect of the first crash. I rebooted and rejoined the same gameserver 3 times in a 4 minute period. (solid state stripe, cpu bound loading times)

Attached bellow is the crash dump to file on the third time.
[crash_dump.zip](https://github.com/Facepunch/garrysmod-issues/files/340357/crash_dump.zip)

Posted bellow is sample code for rendering the same window.

```
ulx.motdmenu_exists = true

local isUrl
local url

local FrameColor = Color(0, 0, 0, 0) --You can set your own frame color, remember to decrease the alpha value.
local ButtonColor = Color(0, 0, 0, 0) --You can set your own button color, remember to decrease the alpha value.

function ulx.showMotdMenu( steamid )

    local MenuFrame = vgui.Create("DFrame")
    MenuFrame.OPaint = MenuFrame.Paint
    MenuFrame:SetSize(ScrW() * 0.95, ScrH() * 0.95)
    MenuFrame:SetPos((ScrW() - MenuFrame:GetWide()) / 2, (ScrH() - MenuFrame:GetTall()) / 2)
    MenuFrame:SetTitle("Welcome to " .. GetHostName())
    MenuFrame:SetVisible(true)
    MenuFrame:SetDraggable(true)
    MenuFrame:ShowCloseButton(true)
    MenuFrame.Paint = function(w, h)
        w = MenuFrame:GetWide();
        h = MenuFrame:GetTall();
        MenuFrame.OPaint(MenuFrame, w, h)
        surface.SetDrawColor(Color(60, 60, 60, 255))
        surface.DrawLine(1, w-27, w-1, h-27)
        draw.RoundedBox( 6, 0, 1, w, h+1, FrameColor )
    end
    MenuFrame:MakePopup()

    local MenuPSheet = vgui.Create("DPropertySheet", MenuFrame)
    MenuPSheet:SetPos(13, 30)
    MenuPSheet:SetSize(MenuFrame:GetWide() - 25, MenuFrame:GetTall() - 84)

    local Google = vgui.Create("HTML")
    Google:SetPos( 25, 50 )
    Google:SetSize( 250, 250 )
    Google:OpenURL("https://www.google.com")

    local Youtube = vgui.Create("HTML")
    Youtube:SetParent(MenuPSheet)
    Youtube:SetPos( 25, 50 )
    Youtube:SetSize( 250, 250 )
    Youtube:OpenURL("http://www.youtube.com")

    local Here = vgui.Create("HTML")
    Here:SetParent(MenuPSheet)
    Here:SetPos( 25, 50 )
    Here:SetSize( 250, 250 )
    Here:OpenURL("https://github.com/Facepunch/garrysmod-issues/")  

    local order = {}
    order[1] = {"Google", Google, "gui/info", false, false, "Google"}
    order[2] = {"Youtube", Youtube, "gui/info", false, false, "Youtube"}
    order[3] = {"Here", Here, "gui/info", false, false, "Here"}

    for _, tab in pairs(order) do
        MenuPSheet:AddSheet(unpack(tab))
    end
end

function ulx.rcvMotd( isUrl_, text )
    isUrl = isUrl_
    if not isUrl then
        ULib.fileWrite( "data/ulx_motd.txt", text )
    else
        if text:find( "://", 1, true ) then
            url = text
        else
            url = "http://" .. text
        end
    end
end
```

**Comment by stickz** [comment]
It's the DPropertySheet or DFrame causing the crashing issue. This code just did the same thing.
https://github.com/Remscar/Morbus/blob/c34b717dab7b446a20fdf74b9e806a1cc9493457/MorbusGamemode/gamemodes/morbusgame/gamemode/client/cl_roundhistory.lua

**Comment by robotboy655** [comment]
Can you come up with minimal code to reproduce it, without the ulx or morbus bullshit?

**Comment by stickz** [comment]
Narrowing down the issue currently, it's not pre-release ether. Looks like low memory DPropertySheet/DFrame interactions that are instantly crashing my game client.

**Comment by robotboy655** [comment]
And try it without your custom launch parameters.

**Comment by stickz** [comment]
Okay it definitely is pre-release. These three commands in my autoexec.cfg with nothing else changed from the stock configuration is causing the crash. I am closing off a rendered DFrame with the "x button." under very low memory available in my running environment.

```
gmod_mcore_test 1

mat_queue_mode -1

cl_threaded_bone_setup 1
```

Attached bellow is anther crash dump from this narrowed down testing.
[crash_dump2.zip](https://github.com/Facepunch/garrysmod-issues/files/340463/crash_dump2.zip)

**Comment by stickz** [comment]
I just tried this under the same conditions and it didn't crash my client.

```
ulx.motdmenu_exists = true

local FrameColor = Color(0, 0, 0, 0) --You can set your own frame color, remember to decrease the alpha value.

function ulx.showMotdMenu( steamid )
    local MenuFrame = vgui.Create("DFrame")
    MenuFrame.OPaint = MenuFrame.Paint
    MenuFrame:SetSize(ScrW() * 0.95, ScrH() * 0.95)
    MenuFrame:SetPos((ScrW() - MenuFrame:GetWide()) / 2, (ScrH() - MenuFrame:GetTall()) / 2)
    MenuFrame:SetTitle("Welcome to " .. GetHostName())
    MenuFrame:SetVisible(true)
    MenuFrame:SetDraggable(true)
    MenuFrame:ShowCloseButton(true)
    MenuFrame.Paint = function(w, h)
        w = MenuFrame:GetWide();
        h = MenuFrame:GetTall();
        MenuFrame.OPaint(MenuFrame, w, h)
        surface.SetDrawColor(Color(60, 60, 60, 255))
        surface.DrawLine(1, w-27, w-1, h-27)
        draw.RoundedBox( 6, 0, 1, w, h+1, FrameColor )
    end
    MenuFrame:MakePopup()
end
```

I cannot provide anymore information than this. It's going beyond my programing expertise.
