### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by cynderdragon** [Facepunch/garrysmod-issues#2696]
Garrys mod crashes on startup with 
![crash 1](https://cloud.githubusercontent.com/assets/20244178/16524130/b6b80d5e-3f9e-11e6-9c2c-a7e6d343b660.png)

[hl2_160620_crash_2016_7_1T14_7_34C0.zip](https://github.com/Facepunch/garrysmod-issues/files/343602/hl2_160620_crash_2016_7_1T14_7_34C0.zip)

I've also verified the gmod files and steam says they are ok.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
