### ISSUE TITLE
Bone manipulation screws up player render bounds

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2697]

**Comment by thegrb93** [comment]
Don't know if intended or not, but setting a bone manipulation in the client realm will forever manipulate the bone and won't be able to remove it and trying to set the manipulation serverside won't work if it's set clientside.

**Comment by willox** [comment]
If that were true, reload wouldn't work on the inflator. Make another issue if you can reproduc ethat.

**Comment by thegrb93** [comment]
Okay I tested it more thoroughly. It looks like I mistook what was happening, but it turns out that if it's set in the clientside, the serverside won't be able to remove it without first setting its own value.
I.e.
```
] lua_run_cl Entity(1):ManipulateBoneScale(42,Vector(30,30,30)) --works
] lua_run Entity(1):ManipulateBoneScale(42,Vector(1,1,1)) --fails
] lua_run Entity(1):ManipulateBoneScale(42,Vector(1,1,2)) --works
] lua_run Entity(1):ManipulateBoneScale(42,Vector(1,1,1)) --works
```
