### ISSUE TITLE
Crash by surface.CreateFont() function

### ISSUE THREAD

**Issue by art-gur** [Facepunch/garrysmod-issues#2699]
If you paste this part of code in autorun to client, he crash. It's happened when you change a blursize. If blursize >= 100 then client is crashing.

`surface.CreateFont( "TestFont", {
    font    = "Trebuchet24",
    size    = 21,
    weight  = 1000,
    blursize = 100
})`

Link to dump file: https://yadi.sk/d/PLpzfjL-swhBK

**Comment by robotboy655** [comment]
Fixed in Dev by clamping the value to 0-80. The actual maximum value is not static (I got crashes with 85) and you should not need to go above 20-40 anyway, it will create graphical artifacts and the text is beyond blurred into non existence by that point.
