### ISSUE TITLE
Concommands created client side not removed after disconnect

### ISSUE THREAD

**Issue by maritaria** [Facepunch/garrysmod-issues#2705]
Today I broke my head for about two hours over this bug.

When a concommand is created using **concommand.Add**, then the client will not forget it after disconnecting from a server. Steps to reproduce using console commands.
Server:
```
lua_run concommand.Run = print
```
Client:
```
lua_run_cl concommand.Add("changeteam") concommand.Remove("changeteam")
retry
changeteam
```
Result:
"Unknown command: changeteam" appears on the client
And nothing is printed on the server console

**Comment by Bo98** [comment]
I believe this is fixed on both the dev and prerelease branches.

**Comment by willox** [comment]
Yeah, all commands created by Lua are automatically removed on d/c in the next update. concommand.Remove will never completely remove a command though.
