### ISSUE TITLE
ShowHelp, ShowTeam, ShowSpare1 and ShowSpare2 hooks on Client

### ISSUE THREAD

**Issue by looterz** [Facepunch/garrysmod-issues#2706]
Currently ShowHelp, ShowTeam, ShowSpare1 and ShowSpare2 are server-side hooks only. It would be great if we could have them be called on the server and client. One of the reasons being PlayerBindPress doesn't receive calls if the focus is on a VGUI menu.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/100
