### ISSUE TITLE
rag doll clean up

### ISSUE THREAD

**Issue by fubne** [Facepunch/garrysmod-issues#2707]
The rag doll clean up problem has been on my Garr's mod  game for around one year and its very annoying and i do not know how it happen it basically cleans up your rag dolls every 10 minutes then there gone a little text on screen Says successful rag doll cleanup  i have tried going to options and looking at the clean up section but nothing comes up can you please help me to figure out  this rag doll glitch thank you

.

**Comment by WilliamVenner** [comment]
It's probably one of your addons.

**Comment by fubne** [comment]
might be i have a lot so i don't now what one it could be

**Comment by WilliamVenner** [comment]
Neither do I. You'll need to disable all of your Workshop addons. On the main menu, click "Workshop" and then click Disable all addons (or something similar). It'll disable all your workshop addons but unfortunately you'll just have to deal with it unless you want your ragdolls cleared every 10 minutes.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
Its not a bug with the game.

**Comment by fubne** [comment]
thanks every one

**Comment by fubne** [comment]
omg its not addons i just tested it what do i do?
