### ISSUE TITLE
Main Menu Spamming (Unplayable)

### ISSUE THREAD

**Issue by Mushroomguy** [Facepunch/garrysmod-issues#2711]
Game has no addons, I verified cache and changed keyboard.
I doubt that I have some code spamming the menu command so I can't really tell what's causing this.
Game is on Dev branch, but it happens on normal branch too...

[video](https://www.youtube.com/watch?v=RaP-wzioWv0&feature=youtu.be)

I included the map loading part as it appears to happen in there too.

**Comment by Kefta** [comment]
Would you care to share the script error you're getting?

**Comment by Mushroomguy** [comment]
It's a server error related to some Nextbots I'm using, nothing really affecting the problem.
([ERROR] addons/gbot/lua/autorun/bot_demo.lua:6: attempt to index global 'MGBotFunctions' (a nil value)

**Comment by robotboy655** [comment]
```Game has no addons```
```addons/gbot/lua/```

**Comment by Mushroomguy** [comment]
I meant not in the Workshop form.
I'm aware of the stuff I code.

**Comment by Mushroomguy** [comment]
I think I fixed it, but the solution doesn't really make sense to me...
I simply disabled Steam Cloud on the game, don't really know how that fixed it.
Maybe some error in reading the local files?
