### ISSUE TITLE
Retry in single player causes freeze/crash.

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#2713]
I often use "retry" to reconnect to servers, when I go to "reload" in singleplayer, I often mistype that as "retry"

Retry on singleplayer acts funny, when the game crashes, upon reboot, it loads you instantly into singleplayer.

**Comment by mcNuggets1** [comment]
can confirm that.

**Comment by UnkN56** [comment]
When you use retry in single player, you server aren't shutdown, i.e. you just connect again & reload client side scripts.

**Comment by robotboy655** [comment]
`retry` in singleplayer now acts like `map currentmap.bsp`
