### ISSUE TITLE
nullptr crash, happens quite often.

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2714]
Here are the mdmps: http://share.epic-domain.com/hl2_160706_crash_2016_7_10T14_47_1C0.zip

Since I can't isolate this on my own it would be neat if someone could look into this, it seems to be always at the same spot however.

**Comment by robotboy655** [comment]
Caused by giving npc_manhack a model with out a physics mesh basically

**Comment by robotboy655** [comment]
Or rather if PhysicsDestroy() is called on a manhack, as I couldn't get it to crash with physics-less model.

**Comment by robotboy655** [comment]
Should be fixed in Dev.

**Comment by ZehM4tt** [comment]
Cheers. Could you perhaps describe what exactly happened? This just started to happen recently

**Comment by robotboy655** [comment]
Nothing happened, something on your server started removing physics objects of manhack NPCs.
