### ISSUE TITLE
HTTP http.Fetch false-erroring since newest update.

### ISSUE THREAD

**Issue by ChampRay** [Facepunch/garrysmod-issues#2716]
I run a little forum software service that corresponds with my users forum through http.Fetch.

So for this example take this:

http://mistchat.com/api/query?api_key=a&api_secret=b&table=users&steamid=blah

A query like this via http.Fetch was working fine before julys update, which I assume has something to do with: 

_HTTP() no longer leaks request references and won’t crash if the Lua state is destroyed during a request._

In the newest update, the http.Fetch will just run the error callback function with the error of "unsuccessful"

I tried the same code on a server on aprils update only, it works, tried it on a server with julys update, this issue occurs.

**Comment by willox** [comment]
I can't reproduce this with the given URL. Is it still happening?

"unsuccessful" is given when m_bRequestSuccessful is not set by the Steam API, which is documented to be whenever the server sends no response to the client, regardless of if there was an HTTP error.

**Comment by willox** [comment]
I tried the URL you emailed me and got a successful response
