### ISSUE TITLE
WHAT THE FUCK!

### ISSUE THREAD

**Issue by ChaoticAssassin** [Facepunch/garrysmod-issues#2717]
Why was the keyboard bind settings changed in Garry's Mod? Now we can't bind push to talk, team chat, global chat, weapon switch, and various other much needed things which is a problem because I had to unbindall in console and everything cleared now I can't do shit but walk, jump, crouch, and shoot.

**Comment by robotboy655** [comment]
Why the fuck do you use illegal pirated game content addons and complain something doesn't work?

**Comment by ChaoticAssassin** [comment]
What
