### ISSUE TITLE
GetInternalVariable returns nothing for some variables that are in GetSaveTable

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2721]
print( Entity(1):GetInternalVariable( "m_nMuzzleFlashParity" ))...

print( Entity(1):GetSaveTable().m_nMuzzleFlashParity )...
0

print( Entity(1):GetInternalVariable( "waterlevel" ))...

print( Entity(1):GetSaveTable().waterlevel )...
0

**Comment by robotboy655** [comment]
It's not a bug as per the wiki page descriptions

**Comment by Kefta** [comment]
Can a GetInternalField function or something of the sort be added to get a specific SaveTable value? Getting the entire table every time for just one key is kind of wasteful

**Comment by robotboy655** [comment]
Maybe post a request to get GetInternalVariable functionality extended.
