### ISSUE TITLE
ParticleEffectAttach Player Bug

### ISSUE THREAD

**Issue by Mushroomguy** [Facepunch/garrysmod-issues#2723]
Trying to use PATTACH_ABSORIGIN and PATTACH_ABSORIGIN_FOLLOW on players that aren't LocalPlayer will cause the particle to not appear.

[example pic](http://images.akamai.steamusercontent.com/ugc/500281030594265228/3721E487F14A6BB8088F0FCC2F12EF61974A5F72/)

Both players are running the same code, game says they're both on fire and are taking damage.

**Comment by robotboy655** [comment]
Post code.

**Comment by Mushroomguy** [comment]
game.AddParticles("particles/burningplayer.pcf")
PrecacheParticleSystem("burningplayer_red")

--ran on client:
ParticleEffectAttach("burningplayer_red",PATTACH_ABSORIGIN_FOLLOW,LocalPlayer(),1)
ParticleEffectAttach("burningplayer_red",PATTACH_ABSORIGIN_FOLLOW,Entity(2),1)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/16839209/8bf12474-49d6-11e6-9a3e-52f0240e8757.png)

Looks like it's working to me?

**Comment by Mushroomguy** [comment]
I tried running the code multiple times, but to no avail.
I guess it's a bug on my end, but I made one of my friends test it out too, and the flames didn't appear on his part either.
