### ISSUE TITLE
SetCollisionBounds not working as it should

### ISSUE THREAD

**Issue by CaMoTraX** [Facepunch/garrysmod-issues#2724]
Everything seems fine at start. But as soon i rotate the Prop -/ Entity the Box seems to to stay in its position and angles and is no longer relative to the entity.

![4000_screenshots_20160713225846_1](https://cloud.githubusercontent.com/assets/2554310/16819887/c15a3bd8-494e-11e6-9568-7caf613170df.jpg)

 > self.wide = 250
> 	local scale = Vector( self.wide, 5, 5 )
> 	self.scale = scale
> 	
> 	self:PhysicsInitBox( -scale, scale ) 
> 	self:SetCollisionBounds( -scale, scale )
> 	self:PhysWake()*

**Comment by robotboy655** [comment]
I think you are confusing Collision Bounds and Collision Mesh. Collision Mesh is what you are actually colliding, and SetCollisionBounds does not affect it in any way.

**Comment by CaMoTraX** [comment]
Is there a way to change the "Physics Box"? So when i Resize my ENTITY...?

When i use Collision Bounds i collide with something too. Wierd.

**Comment by CaMoTraX** [comment]
How can i resize the phyics hull instead? 
self:PhysicsInitBox( Vector( -self.wide/2, -1, -5 ), Vector( self.wide/2, 1, 5 ) ) 
Does not work. It wont rotate with the Entity...

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/PhysicsInitConvex

**Comment by CaMoTraX** [comment]
local VERTICES = {}
	VERTICES[1] = { pos = Vector( -self.wide/2, -5, -5 ) }
    VERTICES[2] = { pos = Vector( self.wide/2, 5, 5 )  }
	
	self.Entity:EnableCustomCollisions( true )
	self.Entity:SetSolid( SOLID_CUSTOM  )
	self.Entity:PhysicsInitConvex( VERTICES )

Tried this but aint working... How does the function work? Wiki dosent tell anything how to use it -.-

**Comment by robotboy655** [comment]
Added an example to the wiki page.
