### ISSUE TITLE
render.DrawBox ignores color argument

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#2725]
Exactly what title says
In my addon
```
cam.Start3D(DrawPos, DrawAngle, FoV, DrawX, DrawY, Width, Height)
	render.SuppressEngineLighting(true)
	render.SetMaterial(whitemat)
	render.ModelMaterialOverride(whitemat)
	draw.NoTexture()
	render.ResetModelLighting(1, 1, 1)
	render.SetColorModulation(1, 1, 1)
	render.SetBlend(1)
	
	DHUD2.MinimapFakeModel:DrawModel()
	ProceedDraw(ply, DrawPos, DrawAngle)
	render.SuppressEngineLighting(false)
	render.ModelMaterialOverride()
cam.End3D()
```

I use DHUD2.MinimapFakeModel:DrawModel() to make render.DrawBox use real color.
Without it, render.DrawBox uses *the last model* draw color that was specified by render.SetColorModulation()
Because of that, i am forced to reset color by calling render.SetColorModulation() and DHUD2.MinimapFakeModel:DrawModel()

Without that hacky fix:
![2016-07-15_12-11_garry s mod](https://cloud.githubusercontent.com/assets/6339511/16864266/52350282-4a85-11e6-8263-f73352d82e93.jpg)
![2016-07-15_12-12_garry s mod](https://cloud.githubusercontent.com/assets/6339511/16864267/52352514-4a85-11e6-8efd-50abf3d6ae53.jpg)
With hacky fix:
![2016-07-15_12-11_garry s mod 3](https://cloud.githubusercontent.com/assets/6339511/16864269/570b6b98-4a85-11e6-9a5a-f679cb02ce98.jpg)
Source:
https://github.com/roboderpy/dhud2/blob/master/lua/dhud/cl_minimap.lua#L284

**Comment by robotboy655** [comment]
```
render.SetMaterial( Material( "vgui/white" ) )
render.DrawBox( ent:GetPos(), ent:GetAngles(), mins * scale, maxs * scale, Color( 255, 0, 0 ) )
```
This works for me.

It seems that the argument does not color vertexlitgeneric materials, you have to use this to color them before drawing them:
```
mat_wireframe:SetVector( "$color", Vector( 0, 1, 0 ) )
```

draw.NoTexture will not do anything 3d render context.

**Comment by roboderpy** [comment]
I use draw.NoTexture because player markers is drawn using surface.DrawPony.

**Comment by roboderpy** [comment]
```
whitemat:SetVector('$color', Vector(RED, GREEN, BLUE))
```
It works!
