### ISSUE TITLE
Concommand crashes server, but don't crash client

### ISSUE THREAD

**Issue by 60percentCaffeine** [Facepunch/garrysmod-issues#2726]
When I run "flush" concommand from server, it crashes.
BUT: if I run "flush" concommand on client, it don't crash. Singleplayer don't crash too.
"prerelease" branch. (seems that it's the same as "live" now)

**Comment by uRandomAlex** [comment]
Why this crash don't getting attention? It's a crash too! ;(

**Comment by robotboy655** [comment]
Are you here for attention or for reporting bugs?

**Comment by Kefta** [comment]
It's not like this is a dire crash; it's user initiated.

**Comment by uRandomAlex** [comment]
@robotboy655 I just don't want to see my issue forgotten, like this: https://github.com/Facepunch/garrysmod-issues/issues/14 , https://github.com/Facepunch/garrysmod-issues/issues/24 , https://github.com/Facepunch/garrysmod-issues/issues/39 , and hundreds of others.

**Comment by robotboy655** [comment]
This "your issue" is equivalent of typing "quit" into server console. It has barely any significance over other more pressing matters.

**Comment by WinterPhoenix** [comment]
Apparently fixed

**Comment by robotboy655** [comment]
It is fixed now.
