### ISSUE TITLE
CNewParticleEffect / CLuaParticle crashes & strange behavior

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#2727]
Calling any function on a null / invalid CNewParticleEffect or CLuaParticle will crash the game. (especially on CNewParticleEffect when calling  v:StopEmissionAndDestroyImmediately() )

https://dl.dropboxusercontent.com/u/40443211/hl2_160706_crash_2016_7_17T4_16_54C0.mdmp

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2700
