### ISSUE TITLE
qHull precision error only on linux 

### ISSUE THREAD

**Issue by wickett707** [Facepunch/garrysmod-issues#2728]
I was only getting the following error with this particular map on linux dedicated server, but not on a windows dedicated server.
map: 
rp_chaos_city_v33x_03
Workshop Link: http://steamcommunity.com/sharedfiles/filedetails/id=296403366&searchtext=chaos+city

console output:
https://gyazo.com/826004f0120b578bfa7606d5879f4a25

**Comment by robotboy655** [comment]
Does it happen on TF2 srcds on that same machine?

**Comment by wickett707** [comment]
Are you suggesting I load up the map on a TF2 server? lemme go download the server content

**Comment by robotboy655** [comment]
Yes, download TF2 srcds and try running the map on it. That's your only hope of getting this fixed.

**Comment by wickett707** [comment]
It still gave me the same error

**Comment by wickett707** [comment]
I would rather not run windows server because security reasons, is there some way I could get this map working on linux, i have seen other servers using it before, and my previous host was linux based, but not a dedicated server like the one I just purchased.

**Comment by robotboy655** [comment]
Well tough luck, it's confirmed unfixable. Does it actually cause any problems on the server?

**Comment by wickett707** [comment]
It makes it impossible to start the server, it will restart every time the error is passed

**Comment by robotboy655** [comment]
Try extracting the addon? The workshop link you posted points to a non existent addon.

**Comment by robotboy655** [comment]
Also you are trying to switch your server to a gamemode you do not even have installed.

**Comment by wickett707** [comment]
I ave already fixed the gamemode issue, by adding the gamemode to the collection, (sorry have been up for days) https://steamcommunity.com/sharedfiles/filedetails/?id=296403366 and here is the workshop link

**Comment by robotboy655** [comment]
As I said, try extracting the map and installing it manually. See if it makes any difference. Make sure the 3 content packs are in your server's collection.

**Comment by wickett707** [comment]
Alright, I just attemped running the server with only the content packs and the map install, and css mounted, and it just simply will not work, I am not sure what the issue is but it appears to be somewhere with my linux dedi, it is running Ubuntu 14.04 with 32 bit libraries installed.

**Comment by wickett707** [comment]
the map was also manually extracted to the maps folder

**Comment by wickett707** [comment]
https://gyazo.com/ffcc8bbd6a412462800780a244d24dd2 here is a much better view of my console output I am getting

**Comment by robotboy655** [comment]
It seems that those errors are unrelated, try adding +r_hunkalloclightmaps 0 to your server start up.

**Comment by wickett707** [comment]
that looks to have solved it
