### ISSUE TITLE
Garry's Mod crashes on startup

### ISSUE THREAD

**Issue by Sytarie** [Facepunch/garrysmod-issues#2729]
Hey,

I've no add-ons, I never played the game before.

Whenever I launch Garry's Mod, my game crashes when loading, just after the "Initializing Serverside" text. 

Nothing appears, the windows just disappears.

I tried to reinstall steam, direct X, garry's mod, to verify game's cache, to add some commands before launching, but nothing worked. My config seems to be good enough too.

Here's the crash log : 

[hl2_160706_crash_2016_7_17T18_21_10C0.txt](https://github.com/Facepunch/garrysmod-issues/files/368071/hl2_160706_crash_2016_7_17T18_21_10C0.txt)

(I couldn't upload mdmt files on Github)

Thanks

**Comment by robotboy655** [comment]
You are crashing in dsound.dll, a DirectX/DirectSound binary. Could be one of your audio device(s) seem to be misconfigured or something. Not a problem with the game as far as I can tell. Try launching TF2 and see if it works.

**Comment by Sytarie** [comment]
I don't have TF2 anymore on my computer. I installed it months ago and I couldn't launch it.
