### ISSUE TITLE
Certain NPCs disappear after loading a save (Dev version) 

### ISSUE THREAD

**Issue by Mawrak** [Facepunch/garrysmod-issues#2730]
Barnacles from HL2 and HL:Source, poison zombies, zombines, fast zombie torsos, combine ships and scanners, antlion workers and probably some other NPCs disappear if I make a save, and then load it. They do not seem to be falling through floor, but rather completely disapper from the map like they were never there.
Game version is Dev Branch 2016.07.16

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/7915163e27b0257c9310f6b354f63712b54db918
