### ISSUE TITLE
SWEP/Initialize does not get called on client sometimes

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2732]
If you spawn a SWEP with the toolgun, Initialize does not get called.

Does happen too, if you give yourself a weapon serverside with the meta:Give function.

**Comment by Kefta** [comment]
Yes! Had to work around this in my weapon base by making a SWEP variable track when it was initialised, and if it was not on deploy, initialise it.

**Comment by mcNuggets1** [comment]
I am a noob coder (almost). I wish I had this sort of workaround.
My weapon base is screwed due to this. (Broken ironsights etc)

**Comment by mcNuggets1** [comment]
I feel like this getting ignored :/

**Comment by Kefta** [comment]
It's not hard to fix in the Lua state. There's tons of bugs on this GitHub, many game breaking that take higher precedent.

**Comment by sigmasoldi3r** [comment]
updates?

**Comment by robotboy655** [comment]
No, unless you can reproduce it.

**Comment by WilliamVenner** [comment]
Even toolgun tools are affected by this

**Comment by thegrb93** [comment]
Never seen this happen

**Comment by sigmasoldi3r** [comment]
my gah! 2020 still open, didn't even remember this issue :I

**Comment by robotboy655** [comment]
Simply cannot reproduce with any of the methods mentioned.

I can make it happen if I spawn a SWEP under my feet while already having the gun, in which case it would get instantly deleted so as far as the client goes, it never existed in the first place, which is the correct behavior.

**Comment by mcNuggets1** [comment]
It happened a long time ago.
It was fixed a long time ago, atleast i couldnt ever reproduce it again.
