### ISSUE TITLE
hl2.exe stopped working

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2734]
hl2. exe stops working sometimes when exiting the game while in multiplayer.

**Comment by Kefta** [comment]
This was closed a while back even though it wasn't fixed

**Comment by robotboy655** [comment]
One of the causes was fixed, it seems it wasn't the only cause. Either post a crash log (.mdmp of the current, up to date live version) or don't post at all. These "game sometimes crashes" reports are worthless.

**Comment by mcNuggets1** [comment]
Ok, It does not create crash dumps.

**Comment by Kefta** [comment]
Can you get an OS stacktrace?

**Comment by mcNuggets1** [comment]
What means an OS stacktrace?
