### ISSUE TITLE
The faceposer can only use half the supported engine amount of flexes

### ISSUE THREAD

**Issue by FissionMetroid101** [Facepunch/garrysmod-issues#2735]
A friend of mine recently ragdolled a model that I had made for SFM which has ~85 flexes.  When trying to use flex 65-85 the console gives the error "Unknown command: faceposer_flex65" and so on.  The max limit a model can have is 128 flexes but it seems the faceposer is set to only use 64.

**Comment by robotboy655** [comment]
Fixed in Dev
