### ISSUE TITLE
Better Player Sequence/Animation control

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#2736]
Overriding Player Animations is overly difficult, there's not much explanation on the wiki or facepunch, It should be a bit easier to override  player animations with ACT Enums and Sequences.

**Comment by robotboy655** [comment]
You already have full control of the animations. The entire animation system for player models is done in Lua, you can find the source here:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/animations.lua
