### ISSUE TITLE
Interfaces drawn with `SWEP.DrawHUD` are not affected by `CHudWeapon` in the `SWEP.HUDShouldDraw` hook

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-issues#2738]
Interfaces drawn with `SWEP.DrawHUD` are not affected by the hud name `CHudWeapon` (no hud name at all) in the `SWEP.HUDShouldDraw` hook. I think it should be, as that hud is only drawn while the weapon is in use.

**Comment by Kefta** [comment]
CHudWeapon are for the weapon/ammo indicators. SWEP.DrawHUD is filtered through GMod's HUD panel -- forgot the element name.

**Comment by fruitwasp** [comment]
Let me explain further. I want to draw `interface x` on the hud while camera swep is active. As it's for one specific swep, I used `SWEP.DrawHUD` to draw it. Because I don't want to draw any other hud apart from the chat and weapon selection, I return false at the end of `SWEP.HUDShouldDraw`. If I return true whenever the hud name is `CHudGMod` (which you meant by GMod's HUD Panel), not only `interface x` but also all other hudpaint elements will be drawn.
