### ISSUE TITLE
Crashing on "Sending Client Info" ----  UPDATED ----

### ISSUE THREAD

**Issue by SkiMcgee** [Facepunch/garrysmod-issues#2740]
I have actual console logs from MY own computer, not the games.
http://pastebin.com/cU1s94ym

Here is what I said in the original post: 
https://github.com/Facepunch/garrysmod-issues/issues/2739

Please take a look at my original post and then look at the crash logs That i have put up above. And I'm not trying to reopen my old post or spam. I'm adding some new information

**Comment by Kefta** [comment]
Still an OSX related crash.

**Comment by SkiMcgee** [comment]
Please note that some of the things within that console log is just some other background things not the game

**Comment by robotboy655** [comment]
If you want to add on onto the issue, post in the original issue.
