### ISSUE TITLE
Trace.MatType returns incorrect materials (possibly only with glass)

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2741]
Test code while looking at the windows in cs_office:
```
local vEyePos = Entity(1):EyePos()

local tr = util.TraceLine({
	start = vEyePos,
	endpos = vEyePos + Entity(1):EyeAngles():Forward() * 1000,
	filter = Entity(1)
})

print( tr.MatType )

if ( SERVER ) then
	print( tr.Entity:GetMaterialType() )
end
```
```
] lua_openscript testtrace.lua
Running script testtrace.lua...
67
89
] lua_openscript_cl testtrace.lua
Running script testtrace.lua...
67
```

For reference, 67 is MAT_CONCRETE; 89 is MAT_GLASS. I've only noticed this with glass. This could be worked around if GetMaterialType was available clientside as well.

**Comment by robotboy655** [comment]
http://i.imgur.com/GdRKwOS.jpg  ??

![image](https://cloud.githubusercontent.com/assets/3299036/17087774/34943094-521a-11e6-94f4-6441bf56c244.png)

??

**Comment by robotboy655** [comment]
Oh, you were looking at the no draw part of the glass, that won't be fixable.

**Comment by Kefta** [comment]
Huh, my brush visualiser didn't show a NoDraw there; guess I'll double check next time. Thanks!

**Comment by Kefta** [comment]
Can we get a GetMaterialType binding clientside to make sure the returns are accurate?
