### ISSUE TITLE
DTextEntry:GetText() is limited to 1023 characters

### ISSUE THREAD

**Issue by Jazzelhawk** [Facepunch/garrysmod-issues#2742]
As the title says, is there a reason for this?

There's also this issue #1569 which is the same. The reason I created this issue even though it has already been reported is because it doesn't look as though the other issue was recognized and was also from a long time ago.

**Comment by Kefta** [comment]
It was recognised; there are a lot of issues on this Github that haven't been gotten to because they're not game-breaking. Creating duplicates just clutters it even more.
