### ISSUE TITLE
CEffectData.m_fFlags defaults to 0x3 on server and 0x0 on client

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2743]
```
] lua_run print( EffectData():GetFlags() )
> print( EffectData():GetFlags() )...
3
] lua_run_cl print( EffectData():GetFlags() )
0
```
I don't know if this is a new issue, but I never noticed it being 3 serverside before.

**Comment by robotboy655** [comment]
EffectData() does not create a new object every time, it reuses one object.

https://github.com/garrynewman/garrysmod/blob/0fd23135bbd94a09a194ba16bbff4c1a3a56867b/garrysmod/gamemodes/sandbox/entities/entities/gmod_emitter.lua#L182

**Comment by Kefta** [comment]
Then the default values (at least flags since that's the only value I see people wouldn't set but could still affect the outcome) should be restored when EffectData is called

**Comment by robotboy655** [comment]
Done.

**Comment by Kefta** [comment]
Thanks a bunch
