### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2744]
### Details
Lua error

[ERROR] gamemodes/sandbox/entities/effects/selection_ring.lua:45: attempt to compare nil with number
  1. unknown - gamemodes/sandbox/entities/effects/selection_ring.lua:45

### Steps to reproduce
You need to be on a multiplayer server, but exact steps to reproduce I can't give.

**Comment by robotboy655** [comment]
It's a problem with that server.

**Comment by mcNuggets1** [comment]
How about just check if self.Alpha is a valid number in line 45.
I get this Error on normal sandbox servers without modifications either.

**Comment by Kefta** [comment]
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/effects/selection_ring.lua#L27

It should always exist if there wasn't any modifications.

**Comment by Bo98** [comment]
I've seen the error mentioned before (couple people have mentioned it in the Next Update thread) but I have no idea what causes it.

**Comment by mcNuggets1** [comment]
Yeah, and who the hell does modify the Alpha of an effect,?

**Comment by Kefta** [comment]
@mcNuggets1 It's probably a bad addon that doesn't do it intentionally. If this were to happen on a vanilla Sandbox server, or you found something that unintentionally cleared an effect table or caused the Init not to run, THEN it would be an issue.

**Comment by mcNuggets1** [comment]
Sorry, but I got no addon which uses the effect or clearly modifies it.

I already stated, that this did happen to me in singleplayer one time without any addons at all.

**Comment by Kefta** [comment]
Without any steps to replicate, there's not much that can be done

**Comment by mcNuggets1** [comment]
There is.
Fixing the lua error by validing alpha is a numer.

**Comment by Kefta** [comment]
Then we should just check if every variable is valid in the engine!

**Comment by mcNuggets1** [comment]
No, just things which Could error.

**Comment by Kefta** [comment]
How could that error unless Init was overrided?

**Comment by robotboy655** [comment]
It's not a good idea to start adding excessive validity checks, the underlying issue must be fixed.

**Comment by mcNuggets1** [comment]
I dont have an explaination, just a Methode how to fix it. 

by the Way I Found the course. it Happens on Using a Tool Gun, but I dont know More than that currently. Oh and that not everytine receives the error.

**Comment by MStruntze** [comment]
I spoke with [someone else](https://steamcommunity.com/id/SerisTheOtter/) about this a few months ago.
He said that it was caused by a memory leak in a weapon pack (FAS2) causing gmod to run out of memory or something.
It's a common issue for players who've been on one of my servers for 5+ hours.

**Comment by mcNuggets1** [comment]
I don't have FAS2 subscribed and it still happens.

**Comment by MStruntze** [comment]
It was just an example. Might be something else on your end. But since it doesn't happen on _all_ servers, something must be causing it.
