### ISSUE TITLE
Manhackdecal util/Decal

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2747]
### Details
When creating a manhackslashdecal Shared in Multiplayer Servers, the Decal Appears Twice

### Steps to reproduce
Already explained.

**Comment by Kefta** [comment]
https://wiki.garrysmod.com/page/util/Effect did you set the fourth arg to true?

**Comment by mcNuggets1** [comment]
Er Are Talking about util/decal

**Comment by Kefta** [comment]
Okay, did you set the fourth arg of util.Decal to true?

**Comment by mcNuggets1** [comment]
Well a 4. Argument. That seems New. i guess im outdated
