### ISSUE TITLE
Float overflow on ApplyForce crashes game

### ISSUE THREAD

**Issue by oldmud0** [Facepunch/garrysmod-issues#2750]
### Synopsis
According to wiremod/wire#1189, applying an abnormal force to an entity, such as by doing `phys:ApplyForceCenter(Vector(1e54, 1e54, 1e54))`, will instantly crash the server.

### Possible cause
Lua uses double-precision floats, while the Source engine uses single-precision floats for physics. When extremely large numbers are passed to the Source engine, the values are not clamped to the limits of float (`±3.40282346638528859e+38` and epsilon value `±1.4e-45`), resulting in undefined behavior leading to a crash.

### Known workaround
ApplyForce can be clamped before being called, with a minor performance hit. However, it is not clear what other methods are also affected by this defect.

### Crash dumps
[Link](http://dumps.metastruct.uk.to/dumper.py?dump=hl2_160706_crash_2016_7_30T14_52_57C0.mdmp&key=CObGFJYEV97-DheKVUHtAm7OoUr_KboG-lZbtHxQ26_q48bcn1tG6mZRN7NyYDZvk4gX03Q1jL0v2GRiF15AOGHCiMISvy5DMV6Xs9e1prGgZTmeqzjf2CLLWC-Y9g7nLKyf1eZh9gIkrlyWKZjIx6bwaXx30BxSgb97S1ib6BI=)

Point of interest:
```
532(427.607059):  Removing!
531(427.607056):  Defusing!
530(427.607052):  	Angular Velocity: [0.000200, -0.000100, 0.000000]
529(427.607044):  	Velocity:         [-1.#IND00, -1.#IND00, 1.#QNAN0]
528(427.607039):  	Angles:           [90.000000, -90.000008, 180.000000]
527(427.607030):  	Origin:           [-1.#IND00, -1.#IND00, 1.#QNAN0]
526(427.607012):  Crazy origin, velocity on entity [124][gmod_wire_expression2]
```
The game detects that something is wrong but crashes in the process of removing the object. Could this be some sort of conflict or race condition between GMod's physics workarounds and Source's physics engine trying to fix the problem by itself?

**Comment by robotboy655** [comment]
Crazy Physics crashing should be fixed in Dev.
