### ISSUE TITLE
Vector * nil returns empty vector

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2752]
> print( Vector( 0, 5, 10 ) * nil )...
0.000000 0.000000 0.000000

If this is intended behaviour, it sure is a weird choice.
This does not happen with angles.

**Comment by bigdogmat** [comment]
It doesn't do any type checking, even `Vector(1, 15, 2) * "yo"` is allowed

**Comment by robotboy655** [comment]
Do we want to change this though? I am afraid that there are bad addons using this bad behavior.

**Comment by Kefta** [comment]
If they do, then errors SHOULD appear in this case. It's broken/unintended behaviour and addons should be fixed accordingly. It would be different if this was being deprecated, but this should have never been this way in the first case and is causing undefined results. Push out why any new errors may appear in the next update announcement and say we'll help them fix it on FP or something if they don't know how.

**Comment by Bo98** [comment]
SetNWBool(entity) 2.0.

**Comment by robotboy655** [comment]
Lets see how many errors this will make.
