### ISSUE TITLE
I have a problem.Help me pls

### ISSUE THREAD

**Issue by DarkSombro** [Facepunch/garrysmod-issues#2754]
One day i playing in one server and i dont have all the textures of the map,and i decided to dowload the textures when i put the textures in the folder of addons and i open the game all normalyy,but when why are charging the menu we have a problem.The menu are buged all the m enu are squares purple and blacks not let me do anything.II have reinstalled 4 times and nothing new.Help me pls

**Comment by Kefta** [comment]
Delete your garrysmod folder, turn off Steam cloud sync, and reinstall. Also, do the same for CS:S, HL2, and TF2 if you have them.

In the future, you can get help on Facepunch. This is for game bugs and not specific issues.

**Comment by DarkSombro** [comment]
I did what you told me and not going

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
