### ISSUE TITLE
file.Exists(x,"LUA") ignore custom content mounted in lua/ directory from clientside

### ISSUE THREAD

**Issue by Gedo789** [Facepunch/garrysmod-issues#2755]
### Details

This issue is happening when you use the function file.Exists(x,"LUA") from the clientside.
But does not appear when used serverside. Which is not a normal behavior.

I was in singleplayer during this issue. So, these custom contents exist for the client.
My Garry's Mod's version is 2016.07.06, vanilla.

However, if "GAME" is used as path argument, it will report the custom content from the `lua/` directory correctly.
### Steps to reproduce

1a. Create a folder/file in `addons/new_addon_folder/lua/<content>`
1b. Or, create a folder/file directly in `lua/` directory
2. Execute these functions on the clientside:
`file.Exists("custom_folder","LUA")` OR `file.Exists("custom_file.lua","LUA")`

**Comment by uRandomAlex** [comment]
It is normal behavior. If you'll set sv_allowcslua to 1 and rejoin then "LUA" path will show you what you need. LUA path shows what Lua you are able to load, it's not just a copy of "GAME" path.

**Comment by Gedo789** [comment]
Even with `sv_allowcslua 1`, it still doesn't show what I want.
I'll wait for a better answer about this issue.

**Comment by TehBigA** [comment]
This may even be related to the dev branch changelog's
> Clientside auto-refresh no longer depends on the placement of serverside AddCSLuaFile calls
I wonder if the LUA filesystem searching depends on what the server expects the client to have which I believe is told to the client in some fashion.
