### ISSUE TITLE
DTextEntry does not validate pasted text

### ISSUE THREAD

**Issue by boxama** [Facepunch/garrysmod-issues#2756]
### Details

DTextEntry does not call the AllowInput hook when text is pasted, meaning client-side validation is easily 
broken. It also means that DTextEntrys which are set to numeric only also allow the user to break it.
There's no OnPaste hook either, or any other method of detecting pastes before they are applied, so I don't see any way to fix this in Lua.
### Steps to reproduce

Eg, try

``` Lua
lua_run_cl f = vgui.Create('DFrame') f:SetSize(200,75) t=f:Add('DTextEntry') t:Dock(TOP) t:SetNumeric(true) f:MakePopup()
```

Then paste anything in the entry.

**Comment by robotboy655** [comment]
Should be fixed on Dev. Let me know if causes problems.
