### ISSUE TITLE
Awful collision problems with player:SetNoCollideWithTeammates(true)

### ISSUE THREAD

**Issue by JetBoom** [Facepunch/garrysmod-issues#2757]
### Details

If you enable this function, players seem to have wonky collision issues. Including:
- Players from OTHER teams not being able to stand on their head.
- Being thrown off of frozen objects if two or more players of the same team are on said object.
- Getting stuck/killed in func_doors and other moving brush objects which wouldn't do so with the function disabled.

The only workaround is to use ShouldCollide in place of this function which is a massive performance loss.
### Steps to reproduce
- Set player:SetNoCollideWithTeammates(true) on a bunch of people. Need to use teamid 1-4, the function has no effect otherwise. I assume because of CONTENTS_TEAM# playing a part.
- player:SetAvoidPlayers is off
- Simply spawn a bot and bot_mimic 1. Move back and forth on the same frozen prop and one of you will be launched off.
- Do the above step with a moving brush entity and you will be either killed, stuck, or launched.

**Comment by Noiwex** [comment]
not only that, ShouldCollide makes your bullets go straight through your teammates.
Given that SetNoCollideWithTeammates also has limited number of teams it works with, it's really uncomfortable.

**Comment by Noiwex** [comment]
also this https://github.com/Facepunch/garrysmod-issues/issues/1820

**Comment by Optiframe** [comment]
I would like to see this fixed sometime soon so I can improve my server perf.

**Comment by besenyei** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3082
https://github.com/Facepunch/garrysmod-issues/issues/2375
https://github.com/Facepunch/garrysmod-issues/issues/1820
https://github.com/Facepunch/garrysmod-issues/issues/2433

If only this was fixed, it would really improve server performance a lot.
ShouldCollide is too expensive and limits how many players a server can handle.

**Comment by besenyei** [comment]
I tested this, with sv_turbophysics 0/1

When I turned it on, the bottom 2 issues were no longer a problem.
This tells me that motion disabled props must probably still be waking up when players collide with this function enabled.

**Comment by robotboy655** [comment]
The first issue should be fixed on Dev.

The latter two I am still looking into, but no promises.

**Comment by robotboy655** [comment]
Apparently player's physics object's angles just start to drift when inside each other, which is what was causing the flinging issue. Had to resort to resetting the angle if it's deviates too much from `0, 0, 0`.

Thanks to whoever it it was who pointed out `physics_highlight_active` and `sv_turbophysics`, it was very helpful.

The killing issue should also be fixed.

I have spent too much time on this, hopefully it was worth it.
