### ISSUE TITLE
Garry's Mod

### ISSUE THREAD

**Issue by BrownCrown13** [Facepunch/garrysmod-issues#2758]
I have a problem where it tells me Garry's Mod is updating, but it says 0/0 completed. It never leaves my folder no matter how much I do to remove it.

Also, I can't even join a game. Whether it's a Online Server or whether it's a local server that doesn't require anything but my own internet. It will launch and all the updates will download, but it crashes right before the game is launched. Please either fix this issue or give me my money back.

**Comment by Kefta** [comment]
This is a place for GMod bugs. The 0/0 problem is a Steam bug and happens with any game that utilises workshop. If you want a refund, Steam has its own requesting policy that you can follow. If you want help on the crashing issue, post here with info such as OS, hardware, any crash dumps, etc: https://facepunch.com/forumdisplay.php?f=16
