### ISSUE TITLE
Unexpected Behavior with Player:Give

### ISSUE THREAD

**Issue by LuaTenshi** [Facepunch/garrysmod-issues#2760]
### Details

The give command is described as giving a weapon to a player. However it also gives ammo to a player.
Would it be possible to have a command that only gives a weapon (without ammo)?
### Steps to reproduce

Give a player a weapon (with Player:Give()), strip that weapon from the player. Give the same weapon to the player again. (They will get more ammo for that weapon too.)

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Player/Give

**Comment by LuaTenshi** [comment]
Thank you very much for adding this!
