### ISSUE TITLE
Gmod locks up PC On sending client

### ISSUE THREAD

**Issue by championsmarts** [Facepunch/garrysmod-issues#2761]
### Details
My gmod locks up my PC When i send client info
Specs:

Processor Intel(R) Pentium(R) CPU N3530 @ 2.16GHz
 
Video Card Intel(R) HD Graphics
 
RAM 4.0 GB
 
Operating System Microsoft Windows 8.1 (build 9600), 64-bit

**Comment by Kefta** [comment]
Garry's Mod has serious issues with Intel integrated graphics -- you should meet the minimum requirements.

**Comment by championsmarts** [comment]
So what do i do

**Comment by Kefta** [comment]
Upgrade your graphics card. If you need further help, you can post here: https://facepunch.com/forumdisplay.php?f=16

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
