### ISSUE TITLE
Brushed Based SENTs do not respond to +use

### ISSUE THREAD

**Issue by waut3r** [Facepunch/garrysmod-issues#2762]
### Details
While brush-based SENTs respond to hooks like StartTouch and what not, brush-based SENTs with physics never seem to respond to OnUse(), which would be extremely useful.

### Steps to reproduce
Here's the code I used today to test this:

```
AddCSLuaFile();

ENT.Base  = "base_entity";
ENT.Type  = "brush";

function ENT:Initialize()
  self:PhysicsInit(SOLID_VPHYSICS);
  self:SetMoveType(MOVETYPE_PUSH);
  self:SetSolid(SOLID_VPHYSICS);
  self:GetPhysicsObject():EnableMotion(false);
  self:SetUseType(CONTINUOUS_USE);
end

function ENT:Use()
  print("Testing:" .. CurTime());
end
```

For the map, all that needs to be done is creating a brush, tying it to the SENT, and compiling. Using my code, it will be solid and respond to things like physcannons (which can also be disabled by changing MOVETYPE_PUSH to MOVETYPE_NONE), but not +use.

**Comment by robotboy655** [comment]
"brush" entities are not brushes, they are ```triggers```.
