### ISSUE TITLE
Instant crash on map change in GMod Multiplayer

### ISSUE THREAD

**Issue by NanoAi** [Facepunch/garrysmod-issues#2763]
### Details

Garry's Mod closes (with no errors) when attempting to changelevel, or more specifically... game.ConsoleCommand( "changelevel " .. map ..  "\n" )

![](https://i.mirai.red/images/x3Hcl.png)
### Steps to reproduce

Start Garry's Mod, press single player.
Start a Multiplayer game (mine was with 4 slots).
Change the map to the same map (mine was gm_flatgrass) with the "changelevel" command.

---

Repeat the same steps above except for the last step use...
lua_run game.ConsoleCommand( "changelevel gm_flatgrass\n" )

**Comment by LuaTenshi** [comment]
Why is this invalid?

**Comment by mcNuggets1** [comment]
This is only happening for me in rare cases.
