### ISSUE TITLE
RPG Launcher makes "empty clip"-noise when equipped FIRST TIME

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2766]
### Details
When equipping the RPG Launcher from Half-Life 2 it makes noise, when equipped the first time (spawned via spawnemenu etc.).

### Steps to reproduce
Spawn HL2 rpg.

**Comment by Kefta** [comment]
Happening every time it's deployed for me. I haven't checked the code, but I'm sure it's the intended deploy sound.

**Comment by mcNuggets1** [comment]
It spams the sound like 50 times, that is not normal.

**Comment by robotboy655** [comment]
I applied a duct tape patch to the sound spam in multiplayer on first equip, there's a problem of sorts with networking on a certain variable and its not worth wasting time trying to fix it.
