### ISSUE TITLE
Linux doesn't play .MP3 sound files even with all gstreamer packages.

### ISSUE THREAD

**Issue by Alkajato** [Facepunch/garrysmod-issues#2769]
GMod Version: 2016.07.06

Linux simply does not play any sort of .mp3 file from any add-on that uses mp3 sounds. I even have all the gstreamer packages installed and it continues to do this. I am using Manjaro Linux and have found no help anywhere on this. 
An example error of what it outputs when attempting to play an mp3 is this.

"Create Stream Failed error 44
Failed to load sound "weapons/dmg_colt1911/draw.mp3", file probably missing from disk/repository"

1. Run a version of Linux newer than Ubuntu 14.04 (As far as I know the mp3's worked in 14.04)
2. Whether or not gstreamer is installed, any add-ons you have that attempt to play an mp3 will fail to do so.

**Comment by robotboy655** [comment]
https://facepunch.com/showthread.php?t=1528233 Does this help?

**Comment by Alkajato** [comment]
This fixed it even though technically Octopi told me the building of the packages failed so something went right.

It would be much easier to deal with this if Garry could put in the minimal requirements (for Linux) on steam what packages are required.
