### ISSUE TITLE
SetMoveCollide only available serverside

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2770]
Listed on the wiki as shared as well as being a shared modifier to m_MoveCollide in the engine.

**Comment by Kefta** [comment]
https://github.com/willox/gmod-csweapons/blob/master/lua/entities/ent_basecsgrenade.lua#L10 Just to note it wasn't always this way.

**Comment by robotboy655** [comment]
https://github.com/willox/gmod-csweapons/blob/master/lua/entities/ent_basecsgrenade.lua#L5

**Comment by Kefta** [comment]
Okay, that was relly dumb.

(But my point still stands https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/c_baseentity.h#L1054)

**Comment by robotboy655** [comment]
Is now shared.
