### ISSUE TITLE
SetDisabled for DText Entry

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#2773]
For some reason, DTextEntry when set to disabled, fades, but you can still press enter and have it run the specified action.

```lua
  -- Begin Settings Tab --
  local 1 = vgui.Create("DTextEntry", Sett)
  1:SetSize(NitroDLS:GetWide(), 20)
  1:SetPos(15, 30)
  1:SetText("Website URL")

  1.OnEnter = function()
    print("hi")
  end

  local 2 = vgui.Create( "DCheckBoxLabel", Sett )
  2:SetPos( 15, 5 )
  2:SetText( "tester" )
  2.OnChange = function()
    if 2:GetChecked() == true then
      1:SetDisabled(true)
    else
     1:SetDisabled(false)
    end
  end
```

**Comment by bmwalters** [comment]
Your reproduction code isn't even valid; you can't have variable names that begin with numbers.

**Comment by MrUnknownGamer** [comment]
I masked all of the variable names

**Comment by robotboy655** [comment]
Big server men are going to steal variables from your code.

!(http://i.imgur.com/EJXdQha.png)[]

**Comment by robotboy655** [comment]
On a more serious note, do we want OnEnter to work when disabled? I mean obviously you shouldn't be allowed to actually edit the thing while it is disabled, but I am not sure about OnEnter. I don't see any reason why we should not call it on a disabled DTextEntry, given you can easily just add the check in your OnEnter callback if you need it only when the panel is enabled.

**Comment by robotboy655** [comment]
You will no longer be able to enter text, but OnEnter will still run.
