### ISSUE TITLE
workshop items stop working after a day or 2

### ISSUE THREAD

**Issue by karljacent00199** [Facepunch/garrysmod-issues#2774]
i have reinstalled garrys mod 3 times in the last 2 days as the workshop items always stop working for me i do more fixing then playing 
please fix this thankyou

**Comment by Kefta** [comment]
This is for Garry's Mod bugs; workshop issues probably stem from the Steam workshop.

**Comment by karljacent00199** [comment]
if it happens every 1 to 2 days then it must be a bug with in garrys mod aswell i have sent loads of support tickets to steam about it have got nothing back its been doing this since i got the game over a year ago

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
