### ISSUE TITLE
Scripted entity event system produces incorrect behavior

### ISSUE THREAD

**Issue by samuelmaddock** [Facepunch/garrysmod-issues#2775]
### Details

Garry's Mod scripted entities [fire events immediately](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/entities/entities/base_entity/outputs.lua#L66-L83), bypassing the event queue. This differs in the behavior of the [Source Engine entity implementation](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/cbase.cpp#L246-L275) which queues events to fire on the next think tick(?). This can lead to incorrect behavior with entities that involve complex event logic.

This is a problem I ran into when recreating the math_counter entity in Lua (samuelmaddock/zombie-escape#5). The fix involved [recreating a simple event loop system](https://github.com/samuelmaddock/zombie-escape/blob/master/ZombieEscape/gamemode/modules/boss/ents/entities/math_counter/init.lua#L265-L298).
### Steps to reproduce
1. Create an entity which fires two or more events which depend on a value from the previous event
2. Fire the event

**Observed:** The resulting value of the first event may get overwritten if the second event fires before setting the value.
**Expected:** The first event finishes processing completely while queueing up the next event. The proceeding event is fired on the next frame.

Maps that display this behavior: [ze_bioshock_v5_6](http://gamebanana.com/maps/187732), [ze_TESV_Skyrim_v4fix](http://gamebanana.com/maps/175427)

Let me know if you need more information as this can be difficult to reproduce.

**Comment by robotboy655** [comment]
Added activator & caller arguments to Entity.Fire, both default to NULL
Switched base_entity:TriggerOutput to use Entity.Fire so it uses the internal engine event queue system

So this should be fixed. Also mentioned the differences between `Entity.Fire` and `Entity.Input` on the wiki.
`Entity.Fire` directly uses the internal `g_EventQueue.AddEvent`
