### ISSUE TITLE
SLAM Sounds not found

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#2776]
System: Windows 10, 64 Bit; Gmod reinstalled, no addons installed

When using/placing the SLAM (from HL2 Category) in Sandbox, the sounds fail to play.
The SLAM itself works fine.

Console Output:
`Failed to load sound "weapons\tripwire\hook.wav", file probably missing from disk/repository
Failed to load sound "weapons\tripwire\mine_activate.wav", file probably missing from disk/repository`

It seems that the sounds are in 'GarrysMod\sourceengine\hl2_sound_misc_dir.vpk' but can't be accessed because they aren't loaded.

**Comment by robotboy655** [comment]
Those sounds are not in ```GarrysMod\sourceengine\hl2_sound_misc_dir.vpk``` because these sounds are from Half-Life 2: Deathmatch.

**Comment by mcNuggets1** [comment]
Why don't we add them to the game?
Atleast dont play the sound if it does not exist.

**Comment by robotboy655** [comment]
For the very same reason we don't ship CS:S sounds with the game.
