### ISSUE TITLE
Contextmenu

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2780]
### Details
When you rightclick while context menu is opened and close the context menu, the cursor stays forever.

### Steps to reproduce
hold C
press right mouse
let go C

**Comment by Kefta** [comment]
Works fine for me. Otherwise, the context menu would stay if you right clicked on an entity

**Comment by mcNuggets1** [comment]
Oh sorry, hold mouse2 either till the context menu is closed, then let go mouse2.

**Comment by Kefta** [comment]
Context menu closes and the mouse stays, but goes away when either mouse button is pressed again. Still don't see the issue.

**Comment by mcNuggets1** [comment]
The issue is, the mouse should be gone :P

**Comment by Kefta** [comment]
I don't even see the issue. The mouse being left over allows you to click on interactables, much like DarkRP's F3 mouse feature.

**Comment by thegrb93** [comment]
In sandbox there's nothing to interact with when the context menu is closed so the mouse shouldn't be on screen.

**Comment by robotboy655** [comment]
The thing is you can't even interact with anything, the cursor goes away as soon as you click any mouse button.

**Comment by robotboy655** [comment]
Should be fixed in Dev.
