### ISSUE TITLE
cam.Start3D and cam.Start don't use the default offcenter settings

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#2782]
Under normal circumstances, using `cam.Start3D()` or `cam.Start()` with no parameters will initiate a 3D rendering context which is exactly the same as the normal view. This is similar to how `render.RenderView()` works with no parameters.

However, during a poster render (where the view is split up into sections and renders each of them zoomed in), `cam.Start[3D]()` will NOT inherit the offcenter settings from the engine view. The 3D context will be initiated for the full screen. This differs from `render.RenderView()`, which inherits the offcenter values correctly.

It's very difficult, if not impossible, to find the actual offcenter values to use in `cam.Start()`'s table to match the regular view.

#### Recreation:
```Lua
-- Start3D and render just one ent
hook.Add("RenderScene", "ShowingPosterFail", function()
	if not IsValid(enttorender) then return end
	render.Clear(0, 0, 0, 255, true, true)
	cam.Start3D()	-- also tested with cam.Start(), identical results
		enttorender:DrawModel()
	cam.End3D()

	return true
end)

-- RenderView - this works just fine
hook.Add("RenderScene", "ShowingPosterSuccess", function()
	if not renderview then return end
	render.RenderView()
	return true
end)
```
https://www.youtube.com/watch?v=wZGqMZvEEjU

In the linked video, I demonstrate how both of the functions above handle poster renders in the game. The first one picks just a single entity and draws it. The second one draws the entire screen as usual. During gameplay, both of them work fine. However, when creating a poster screenshot, only the second function produces usable results.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/17684454/83650a76-6364-11e6-9eaf-7a598fd0d69d.png)
