### ISSUE TITLE
Entity:DeleteOnRemove Crashes game when used on ragdoll

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#2785]
### Details
Entity:DeleteOnRemove Crashes the game when used on ragdoll. 
`self:DeleteOnRemove(prop_ragdoll_ent)`

**Comment by robotboy655** [comment]
Cannot confirm, nothing happens besides what is supposed to.

**Comment by DrVrej** [comment]
Ok you probably didn't understand what I meant.
Here is an example:
```
	local ragdoll = ents.Create("prop_ragdoll")
	ragdoll:SetModel("ragdoll")
	ragdoll:SetPos(self.Corpe:GetPos())
	ragdoll:SetAngles(self.Corpe:GetAngle())
	ragdoll:Spawn()
	ragdoll:Activate()
        self.Corpse:DeleteOnRemove(ragdoll)
```
self.Corpse is a ragdoll too. I tried using the remover tool and I removed the self.Corpse ragdoll and then it crashed the game when it tried to removed the other ragdoll.

**Comment by robotboy655** [comment]
What happened to posting this crucial information in the first place? You just had to wait for it to be closed to offer helpful information?

**Comment by DrVrej** [comment]
Sorry, I thought the one sentence I wrote would have explained the problem, so do you want me to send a crash dump or something?

**Comment by robotboy655** [comment]
Naturally.

**Comment by robotboy655** [comment]
I tried it with 2 ragdolls and again nothing happened.

**Comment by DrVrej** [comment]
Alright I am going to try again right now and see if it crashes. Also I am on the dev branch.

**Comment by DrVrej** [comment]
Ya still crashed, here is dump file:
[ragdoll crash dump.zip](https://github.com/Facepunch/garrysmod-issues/files/428617/ragdoll.crash.dump.zip)

**Comment by robotboy655** [comment]
One of your should collide hooks causes this.

**Comment by DrVrej** [comment]
Does it say which addon exactly? Because non of my manually installed addons and the addons that I have made have the ShouldCollide hook.

**Comment by robotboy655** [comment]
Obviously not.

**Comment by bigdogmat** [comment]
You could try finding it by printing out all ShouldCollide hooks, hopefully the addon would've given it a unique name.

**Comment by DrVrej** [comment]
I found out that disabling all addons doesn't fix it, you also have to remove this function:
`ragdoll:SetCollisionGroup(1)` Then it gets fixed, but once I enable my addons again, it starts crashing. I tried doing `PrintTable(hook.GetTable())` but didn't see any ShouldCollide hooks
