### ISSUE TITLE
 MAX_CHANNELS issue 

### ISSUE THREAD

**Issue by JohnOakman** [Facepunch/garrysmod-issues#2787]
Due to the lack of answers in my facepunch topic I put a link to it here, everything is explained with evidences : https://facepunch.com/showthread.php?t=1511479&p=50919703

Thanks for your answer and maybe for a fix.

**Comment by robotboy655** [comment]
You already had an answer in #1

**Comment by JohnOakman** [comment]
That's not an answer or any kind of fix.
The sounds were good a year ago and now they doesn't work anymore.
So what happened ?

**Comment by JohnOakman** [comment]
ok so that could help but it's still not any kind of fix: http://steamcommunity.com/app/211/discussions/2/648812917768609923/
