### ISSUE TITLE
FireAnimationEvent doesn't run on first predicted time

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2788]
IsFirstTimePredicted always returns false in FireAnimationEvent

**Comment by robotboy655** [comment]
That is how it works in the engine. ( OnFireEvent )

**Comment by Kefta** [comment]
How do I prevent util.Effect from running twice every fire then?

**Comment by robotboy655** [comment]
I think the 2 last arguments are meant for that

**Comment by robotboy655** [comment]
Also, check event IDs, etc.
