### ISSUE TITLE
Krieg 550 Commando model outputs bad effect in FireAnimationEvent options

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2789]
The effect should be EjectBrass_556, but instead, the underline character is invalid. This only happens with this model. "DispatchEffect: effect 'EjectBrass?556' not found on client"

**Comment by robotboy655** [comment]
Model path exactly? Looking through source files for both view and world model, they both are correct.

**Comment by Kefta** [comment]
models/weapons/v_snip_sg550.mdl
models/weapons/w_snip_sg550.mdl

It seems like it sometimes works. Here's a console print of the character display and byte number of the character in question over five iterations:

_
95
?
173
DispatchEffect: effect 'EjectBrass?556' not found on client
?
173
DispatchEffect: effect 'EjectBrass?556' not found on client
?
173
DispatchEffect: effect 'EjectBrass?556' not found on client
?
173
DispatchEffect: effect 'EjectBrass?556' not found on client

**Comment by robotboy655** [comment]
Well the problem is clearly not with the default models, I have never seen this happen before, all the model files contain "EjectBrass_556", source and compiled. And the fact that it "sometimes works" doesn't make any sense either. I'd say it's a problem on your side.

**Comment by Kefta** [comment]
I'll have others test as well.

**Comment by Kefta** [comment]
If it's any indication, the options also includes two different velocities:
EjectBrass_556 2 85
EjectBrass_556 2 85
EjectBrass?556 2 80
DispatchEffect: effect 'EjectBrass?556' not found on client
EjectBrass?556 2 80
DispatchEffect: effect 'EjectBrass?556' not found on client
EjectBrass?556 2 80
DispatchEffect: effect 'EjectBrass?556' not found on client
EjectBrass?556 2 80
DispatchEffect: effect 'EjectBrass?556' not found on client
Soundscape: construct.outside
EjectBrass?556 2 80

**Comment by robotboy655** [comment]
You must have outdated/overridden the c_ model of the gun. v_snip_sg550 is not shipped with the game so blame valve if you use it and it doesn't work.

**Comment by Kefta** [comment]
Okay, well it turns out that CStrike events aren't hardcoded into the engine like the engine code had me believed, and this is in the v_model QC

{ event AE_CLIENT_EFFECT_ATTACH 0 "EjectBrass?556 2 80" }

Sorry for wasting your time.
