### ISSUE TITLE
IMaterial:GetVector() clamps values

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-issues#2791]
### Details
The IMaterial:GetVector() function clamps values between 0 and 1 even though vectors outside of the range are allowed within vmts (example: https://developer.valvesoftware.com/wiki/Phong_materials#Phong_Fresnel_ranges)
If you use IMaterial:GetString() on the same variable it returns the correct representation of the vector.

### Steps to reproduce
Create any material, for example
```
"VertexlitGeneric"
{
	"$phongfresnelranges" "[6 33 5]"
}
```
Then run:
```lua
local material = Material("path/to/vmt")
print(material:GetVector("$phongfresnelranges")) -- 1.000000 1.000000 1.000000
print(material:GetString("$phongfresnelranges")) -- [ 6.000000 33.000000 5.000000 ]
```

**Comment by robotboy655** [comment]
It is only meant to return linear color vectors ( GammaToLinear ), not 3D space vectors.

**Comment by robotboy655** [comment]
I will rename the current function and make GetVector do what it was meant to do, even though this is a bad way to go about it, I doubt anyone uses it for the fact that it appears to not work.
