### ISSUE TITLE
Minidumps are not generating the right OS

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#2792]
Minidumps are not generating the right build number, and it can be used to know what is the os version

![http://i.imgur.com/q0Juizj.png](http://i.imgur.com/q0Juizj.png)

**Comment by ExtReMLapin** [comment]
Seems to be only a problem on windows 10, because else it's giving the right windows nt version

**Comment by robotboy655** [comment]
Say thanks to Microsoft:
http://stackoverflow.com/questions/27246562/how-to-get-the-os-version-in-win8-1-as-getversion-getversionex-are-deprecated

Not sure if we can fix it without dropping support for Win XP and lower if we would to switch it to GetProductInfo

**Comment by Bo98** [comment]
Windows 10 should actually work for GetVersion/GetVersionEx if you modify the manifest (windows_default.manifest in Source SDK 2013), adding `<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>`.

I agree it's shitty and it's something else to remember when a new OS comes round but it's the only way.

**Comment by ExtReMLapin** [comment]
thanks microsoft

**Comment by Bo98** [comment]
`GetProductInfo` appears to be more for identifying the type of OS (eg. Home, Professional, Enterprise etc.).

What "replaced" GetVersion/GetVersionEx is stuff like `IsWindows10OrGreater` which is unsuitable for this purpose so updating the manifest appears to be the only way to go.
