### ISSUE TITLE
Ladder bug

### ISSUE THREAD

**Issue by darrnokturna** [Facepunch/garrysmod-issues#2794]
1. “Breaking” ladders.
   We bind a key to “kill”, then climb onto a ladder and press that key, then disconnect from the server.
2. Respawning on a ladder.
   First we bind a key to kill, for example: bind b “kill”. Climb onto the ladder and press the “b” key. You will spawn on the ladder with full ammo and health.
   Example in [hl2dm](http://youtu.be/iSzzyEBxrMw?t=8s).

**Comment by MinIsMin** [comment]
That's a known bug for a long time. The error will probably not resolved.

**Comment by darrnokturna** [comment]
According to [RLS] V952 he fixed it hl2dm, dunno about garrysmod:
Ex in hl2dm:
№1 Can be fixed by dereferencing reserved_spot entity from the game code.
№2 Can be fixed removing player->pl.deadflag check in CGameMovement::PlayerMove and by adding aditional checks to CHL2GameMovement::LadderMove

[code]if ( player->pl.deadflag && lm->m_hForceLadder.Get() )
{
    SetLadder( NULL );
    lm->m_bForceLadderMove = false;
    lm->m_hForceLadder = NULL;
    return false;
}[/code]
