### ISSUE TITLE
weapon_physcannon and weapon_rpg missing sounds bug - server side

### ISSUE THREAD

**Issue by panica23** [Facepunch/garrysmod-issues#2796]
[YouTube](https://youtu.be/TrYd7nZP6Pg)
There is no gravity gun sounds on server side. Currently playing on Windows server.
But everything is ok on client side.

Also there is no sounds on the third shot with weapon_rpg Windows server.
[YouTube](https://youtu.be/ATHTd0_uaTw)

**Comment by robotboy655** [comment]
Fixed the Gravity Gun sounds but I have no idea what is wrong with RPG sounds.

**Comment by robotboy655** [comment]
RPG sounds are now fixed too!
