### ISSUE TITLE
weapon_slam missing sounds

### ISSUE THREAD

**Issue by darrnokturna** [Facepunch/garrysmod-issues#2797]
[Video](https://youtu.be/6QJfRsshVM8) There is no weapon_slam sounds
Please upload them
"weapons\tripwire\hook.wav"
"weapons\tripwire\mine_activate.wav"
"weapons\slam\buttonclick.wav"

**Comment by Jvs34** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2776

> Those sounds are not in GarrysMod\sourceengine\hl2_sound_misc_dir.vpk because these sounds are from Half-Life 2: Deathmatch.

> For the very same reason we don't ship CS:S sounds with the game.
