### ISSUE TITLE
[hammer] Model Browser irremovable black background

### ISSUE THREAD

**Issue by darrnokturna** [Facepunch/garrysmod-issues#2799]
![-1](https://cloud.githubusercontent.com/assets/21275896/18034076/408b57d2-6d3c-11e6-973a-7ce77ffcd68e.jpg)
For some reason, Model Browser has irremovable black background. I can't see some model's in browser.
And yes, I know about sourceschemebase.res. but changing 124 line "Panel.BgColor" gives me nothing.

**Comment by robotboy655** [comment]
Yeah, I am aware of the problem, unfortunately I could not fix it when i tried. ( It used to be all black )

**Comment by robotboy655** [comment]
You can edit garrysmod/resource/SourceScheme.res's "Panel.BgColor" for now.

**Comment by darrnokturna** [comment]
![test](https://cloud.githubusercontent.com/assets/21275896/18175335/955cd9e4-7079-11e6-8b0a-2de221eac329.jpg) Yeap, works for now, but wanna ask about default models, crossbow has black color, can you fix it?

**Comment by robotboy655** [comment]
!()[http://i.imgur.com/aCRrMK1.png]
