### ISSUE TITLE
Random client crashes

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2801]
In the dev branch I'm getting random crashes it seems that it happens right when a player is about to die but its not always happening, this seems to be a null pointer from trying to get a entity from the entity list, could be probably checked before using it.

Dump: http://share.epic-domain.com/hl2_160828_crash_2016_8_28T20_27_4C0.mdmp

**Comment by robotboy655** [comment]
Found 7 cases of this crash. All should be fixed on Dev within an hour or two.

**Comment by ZehM4tt** [comment]
Thanks for that one, was it in all cases the ItemHolsterFrame function?
