### ISSUE TITLE
Flash not working

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#2805]
Few months ago flash was working, and i'm using it as a music player for an addon (jwplayer).

Video showing the problem : https://www.youtube.com/watch?v=3PGg8A07d7Q

Link to test the flash player : http://extrem-team.com/wolfdjtest/song.php?id=7434045c9c8fef0510e88fe82b1dcfba

**Comment by mcd1992** [comment]
Do you have the IE version of flash installed? If I recall correctly awesomium uses your system flash plugin, which the IE installer installs.

A better solution is to try and use HTML5 for playing videos or doing canvas stuff. Not sure if awesomium supports any of that though. Might have to bother the devs about the switch to CEF.

**Comment by Bo98** [comment]
IE version is ActiveX though? Awesomium should be using the NPAPI version, which is the "Firefox version".

**Comment by mcd1992** [comment]
That would make sense. But I recall telling people to install the IE version of flash on old Theater servers, which they said fixed it. I have no clue how awesomium decides on Windows.

**Comment by ExtReMLapin** [comment]
Also, i tried to install the "old fix" but seems to be dead.

**Comment by thegrb93** [comment]
I just ran into this issue too. Can't install the IE version of flash either since it's only for windows 7 or lower and it errors when I try.

**Comment by ExtReMLapin** [comment]
RIP Flash
