### ISSUE TITLE
User agent awesomium for restrict acces to my loading screen!!!!

### ISSUE THREAD

**Issue by MrKuBu** [Facepunch/garrysmod-issues#2811]
User agent awesomium for restrict acces to my loading screen please!!!

**Comment by robotboy655** [comment]
What?

**Comment by bmwalters** [comment]
I'm assuming he wants the same thing as #2810 and #2811. @MrKuBu see my comments in both of those issues. For further discussion, create a Facepunch post.

**Comment by MrKuBu** [comment]
Whats a network conditions?
