### ISSUE TITLE
[ClientSide] EntityFireBullets, only works on players.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#2812]
### Details
Working on a weapon-system that create effects for bullets, and noted 'EntityFireBullets' doesn't get called for NPC's on the client.

### Steps to reproduce
hook.Add("EntityFireBullets","BulletBug",function(ent,bulletdata)
	print((SERVER and "[SERVER]" or "[CLIENT]"),ent:GetClass())
end

![image](https://cloud.githubusercontent.com/assets/4114136/18383323/4008dd14-7685-11e6-8bc8-4200b000353b.png)

**Comment by Jvs34** [comment]
FireBullets gets called clientside for players because of prediction, it's intended.

If you want to create effects you can create a scripted effect in the hook with util.Effect or replace the bullet tracer.

**Comment by Nak2** [comment]
Darn, looks like I can't hook into non-custom weapons on the client then.
