### ISSUE TITLE
Serveur Crash 

### ISSUE THREAD

**Issue by estebanlll** [Facepunch/garrysmod-issues#2813]
### Details

Hello i have issue my gmod crash recently but there is not lua error i got "engine error" : 
Sep  8 12:11:39 ns3047367 kernel: [105936.614714] perf interrupt took too long (2514 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
Sep  8 18:13:47 ns3047367 kernel: [127708.278668] srcds_linux[4700]: segfault at fffffffc ip 00000000f2af26dc sp 00000000ff9aa510 error 5 in vphysics_srv.so[f29f2000+19f000]
Sep  8 19:11:01 ns3047367 kernel: [131149.994618] srcds_linux[31017]: segfault at 3fff7 ip 00000000f2b28717 sp 00000000ff9af670 error 4 in vphysics_srv.so[f2a28000+19f000]
Sep  8 20:24:22 ns3047367 kernel: [135558.960363] srcds_linux[1132]: segfault at 0 ip 00000000f2a8fa51 sp 00000000ffcea790 error 4 in vphysics_srv.so[f2961000+19f000]
gizmo: Sep  9 15:05:14 ns3047367 kernel: [202946.626318] srcds_linux[4290]: segfault at fffffffc ip 00000000f2a616dc sp 00000000fff51bf0 error 5 in vphysics_srv.so[f2961000+19f000]
Sep  9 16:47:20 ns3047367 kernel: [209084.052708] srcds_linux[20074]: segfault at fffffffc ip 00000000f2af26dc sp 00000000ffd20120 error 5 in vphysics_srv.so[f29f2000+19f000]

And segfaults errors when there is X players : 
HardWare ;

Intel i7-6700K OC
4 Cores / 8 Threads
4,0 GHz / 4,2 GHz
64 Go DDR4 2133 MHz
2 x 480 Go SSD 
RAID SOFT
Host : https://www.ovh.com/fr/
Game : 
OS : Debian 8
### Steps to reproduce

Tell us to to reproduce the problem

**Comment by MrDiaboloz** [comment]
I got this in console logs : 
`./srcds run : ligne 372 : 14392 Erreur de segmentation $HL CMD Add "-debug" to the ./srcds run command line to generate a debug.log to help with solving this samedi 3 septembre 2016, 15:35:44 (UTC+0200): Server restart in 10 seconds FIND [/home/gmodservers/css contents/*.vpk] ADDING [/home/gmodservers/css_contents/cstrike_pak_000.vpk] Adding Path: [/home/gmodservers/css_contents] Couldn't load shader dli: game shader generic garrysmod srv.soConVarRef mat dxlevel doesn't po. Game srv.so loaded for "Garry's Mod" 
Setting breakpad minidumpAppID = 4000 Initializing Steam libraries for Workshop.. 
`

**Comment by Kefta** [comment]
That doesn't contain any info.

**Comment by MrDiaboloz** [comment]
yes but i got this in console when i got error quote upper

**Comment by robotboy655** [comment]
Closing as stale.
