### ISSUE TITLE
TTT - German personal pronouns

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#2818]
When searching a body in TTT while having the language set to German the following appears:
When the person died through crushing ("L.search_dmg_crush"):

Viele **seiner** Knochen sind gebrochen. ...
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/lang/german.lua#L186

"seiner" -> male form

When the person was stabbed to death ("L.search_dmg_stab"):

**Sie** wurde stark geschnitten. ...
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/lang/german.lua#L192

"Sie" -> female form or the person

Which form should be used? Male or female? Not both, that's for sure.
In the english file, it says: "They are ...".
@markusmarkusz maybe you can help.

**Comment by markusmarkusz** [comment]
The main problem with translating is that the German language is a complicated language. There are words that can not be gender-neutral defined without circumscribe long.
I would just love to customize the language system so that the grammatical mistakes and spelling mistakes could be corrected.
But I don't know, how I could implement this without rewriting some more things.
The most mistakes are on places where messages got concatenated for example at the quick chat commands.

**Comment by robotboy655** [comment]
This is not a place to report TTT bugs.

Either send a Pull Request to fix the bug ( https://github.com/garrynewman/garrysmod ), or contact the gamemode author. ( https://github.com/garrynewman/garrysmod/tree/master/garrysmod/gamemodes/terrortown )

**Comment by markusmarkusz** [comment]
@svdm
Just tagging you here 'cause I don't know which way I should choose to contact you xD.

**Comment by bmwalters** [comment]
It would be awesome if TTT was [filter-branch](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/)'d into a separate repo and pulled in as a [submodule](https://github.com/blog/2104-working-with-submodules) to GMod, that way there would be an appropriate issue tracker and independent PR system.

**Comment by svdm** [comment]
I'm not convinced it's worth making major changes just to handle a better German translation. But it's hard to weigh pros and cons when it's not clear what the changes would entail (how they would affect other languages, how much more complex the language system would become, etc).

In the end though the translations will never be as fluent as English. There will always be cases where in another language you'd structure a text completely differently, way beyond the level of individual sentences/language strings. And I'm sure the German right now is clear enough for people to be able to understand what is going on in their video game.

RE: bug reporting, I guess there's no place for it right now. I'd be fine with monitoring a bugtracker somewhere and respond to the legitimate issues reported there, but I'm not very interested in setting up and maintaining one (or moderating all the random "omg unban me from the server plz i no cheat" issues people will inevitably create).

**Comment by MinIsMin** [comment]
I think, we should decide which form to use. Either the male form, the female form or, for which I am, the person (**neutral**).

Male form: Er wurde erstochen.
Female form: Sie wurde erstochen.
Neutral: Die Person wurde erstochen.

**Comment by markusmarkusz** [comment]
If I have enough time I can correct the complete translation.

**Comment by MinIsMin** [comment]
Thanks.
Which form are you going to use? Neutral?

**Comment by markusmarkusz** [comment]
https://github.com/garrynewman/garrysmod/pull/1241
Later I will create a gist with all strings that have problems with for example plural forms of some words.
