### ISSUE TITLE
LuaJIT corrupting bitwise or modulo operations

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2820]
I have been tearing my hair out over this issue since every time I add prints, the issue disappears. For a function math.MD5PseudoRandom( int ), the return varies for the same argument.

Code and results: http://pastebin.com/EhpiiNH6

Adding prints to the bitwise seems to make the issue disappear completely.

**Comment by thegrb93** [comment]
What happens if you turn jit off?

**Comment by Kefta** [comment]
That did the trick

**Comment by thegrb93** [comment]
Are you sure 
nSeed = nSeed % 0x100000000
is right? All your other hex numbers are DWORD while that one is a QWORD. Maybe there's some signed-unsigned undefined behavior occurring.

**Comment by Kefta** [comment]
I wonder if JIT costs less than using bit.band( blah, 0xFFFFFFFF ) in place of the QWORD modulos.

**Comment by Python1320** [comment]
Have you tried with bare luajit? Maybe this could be a good reason to try to update to latest/later luajit version if it has this fixed.

**Comment by thegrb93** [comment]
Happens in luajit 2.0.4 too.

**Comment by thegrb93** [comment]
I put it in the love.update() callback in love2d just to try it and it's kind of interesting. I get 
1246386142 six times as the program is starting (and jit is still initializing?)

Then 3935365040 once

Then mostly 601912188 but it sometimes 4122142404 will appear twice.
Has this been reported to JIT yet? They might be able to fix it.

**Comment by willox** [comment]
it's pretty likely that you won't get cross-platform (including JIT compiled vs interpreted code) determinism from operations like ^ or passing values that are out of range in to the bit library. I'm not sure about modulo either. It's a topic well above my knowledge, so I can't help you much.

You'd probably see this exact issue even if you had written this code in C# or Java.

**Comment by Kefta** [comment]
I'll just change all the modulos to use bitand n-1, which is equivalent for when n is a power of 2.

**Comment by willox** [comment]
Best advice I can give it to stick to +, -, /, * as much as you can. You can't trust the math library either.

**Comment by Kefta** [comment]
@willox Is there a way to have direct bitwise operations?

**Comment by willox** [comment]
On a float without converting to an int internally? That's not really a thing.
