### ISSUE TITLE
Lua file names with spaces in them don't get networked to the client

### ISSUE THREAD

**Issue by ARitz-Cracker** [Facepunch/garrysmod-issues#2821]
### Details

I wanted to test if the net messages work BEFORE the client loads all entities. The answer is yes! However, my shared lua file didn't work when I put spaces in the name.
### Steps to reproduce
1. Here's some code

``` lua
MsgN("NET TEST!!!!!!!!!!!!!!")
if SERVER then
    util.AddNetworkString( "aritz_net_test" )

    hook.Add( "PlayerInitialSpawn", "ARCNetTest", function(ply)
        MsgN("NET TEST!!!!!!!!!!!!!! SENDING TO "..tostring(ply))
        net.Start("aritz_net_test")
        net.Send(ply)
    end)
else

    net.Receive("aritz_net_test",function(len)
        for i=1,10 do
            MsgN("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
        end
    end)
end
```
1. save that code in lua/autorun/net test.lua
2. notice how it doesn't work
3. save it as lua/autorun/nettest.lua
4. notice how it does work

**Comment by ARitz-Cracker** [comment]
Oh I should also note that I only tested this on windows. Will do loonix when I get home

**Comment by Shigbeard** [comment]
![http://i.imgur.com/Gdso3rx.png](http://i.imgur.com/Gdso3rx.png)

**Comment by uRandomAlex** [comment]
@Shigbeard Thanks, didn't know about syntax highlighting!

**Comment by markusmarkusz** [comment]
If I'm not wrong then you have to use AddCSLuaFile(). Otherwise the file wouldn't be downloaded by the client.

**Comment by Kefta** [comment]
@markusmarkusz But it doesn't work with files with spaces in the name

**Comment by ARitz-Cracker** [comment]
@markusmarkusz files in autorun are automatically AddCSLuaFile'd. AddCSLuaFile still doesn't work when it comes to file names with spaces.

**Comment by robotboy655** [comment]
This is intentional for now. I have added an explicit message that tells you it will not send the file to clients and why to avoid confusion.
