### ISSUE TITLE
Crash on a Zombie Panic! Source folder

### ISSUE THREAD

**Issue by PlNG** [Facepunch/garrysmod-issues#2822]
When I browse models in the Zombie Panic! Source it crashes (immediately) on models in the "props_sapid" folder, this includes searches that yield results from it.

I have verified the game cache integrity of both games and run the Zombie Panic! Source: Sapid Cerebrum map.

**Comment by Kefta** [comment]
Can confirm

**Comment by mcNuggets1** [comment]
Is this going to get fixed anytime soon or do I have to unmount alot of games to keep my game from crashing?

**Comment by Kefta** [comment]
@PlNG They are separate projects with separate developers - Garry's Mod development is still active.

**Comment by robotboy655** [comment]
Closing as stale. If you can still reproduce the issue, please open a new issue and provide model paths, etc., actual steps to reproduce the crash.
