### ISSUE TITLE
Left 4 Dead 2 models

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2823]
### Details
When searching in sandbox for left 4 dead models, my game instantly crashes.

### Steps to reproduce
Search for left  4 dead playermodels or models.

**Comment by robotboy655** [comment]
same issue as https://github.com/Facepunch/garrysmod-issues/issues/2822

**Comment by mcNuggets1** [comment]
I meant left 4 dead, not zombie panic.

**Comment by Kefta** [comment]
@mcNuggets1 Same cause is what I'm assuming he meant.
