### ISSUE TITLE
Checkboxes not visible on Linux

### ISSUE THREAD

**Issue by Zebra1337** [Facepunch/garrysmod-issues#2826]
### Details

The checkboxes on the mount menu and start game menu are not visible on Linux client.

http://i.imgur.com/wsXbgkq.png
### Steps to reproduce

Launch the game on Linux. I'm using Fedora 24 on kernel 4.7.2.

**Comment by MyCatFishSteve** [comment]
I have this issue as well. I'm using Arch Linux on kernel 4.7.4-1 and I've had this issue for a very long time. I'm on the stable branch for the Steam client.

CPU: AMD FX-4130
GPU: Radeon HD 7750
RAM: 8GB

**Comment by Simon311** [comment]
Reminds me of #86.

**Comment by MinIsMin** [comment]
I have this issue too. I'm using Ubuntu 16.04.1 64 Bit - Stable Branch.
See the left spaces:
![20161020122423_1](https://cloud.githubusercontent.com/assets/18466226/19556237/798335fc-96c0-11e6-9859-81c1bc41f6cc.jpg)

**Comment by mcd1992** [comment]
This is a known issue with awesomium on Linux. Whenever gmod moves to CEF this shouldn't happen.

**Comment by Bo98** [comment]
[The Awesomium 1.7.5 changelog](http://wiki.awesomium.com/changelogs/whats-new-1-7-5.html) says:

> _Note: to actually display unstyled checkboxes, radio buttons, or progress bars, users will need to declare global CSS so that these widgets are painted by WebKit instead._

Was this ever done?

**Comment by mcd1992** [comment]
I'm not sure what the changelog meant but manually drawing the checkbox does work with some CSS rules.

Using some guys CSS rules with some changes draws checkboxes on Linux.
https://gist.github.com/mcd1992/5f71574fd14f38ac5396af30d28a5027

Putting that in Menu.css with the Awesomium inspector works for me.
http://i.imgur.com/F3KzYPm.jpg

**Comment by MyCatFishSteve** [comment]
Good find, mcd1992.

Can you please make a pull request on the official Garry's Mod repo? I'm sure it will get pulled into the master branch.

**Comment by mcd1992** [comment]
Ehh, problem is this CSS fix should only apply to Linux (and OSX?) clients. I'm not familiar with AngularJS and if its even capable of detecting client operating system. If not then this will need to have some system for only inserting the stylesheet html link on problem OSs.

**Comment by Bo98** [comment]
Yes, and such a fix needs to be applied globally and not just to the main menu.

**Comment by SharpOB** [comment]
`12 Nov 2016`
Ouch.
Could we expect a solution to this any time soon?

**Comment by Bo98** [comment]
Just to clarify: this does not happen on OS X, just Linux.

**Comment by SharpOB** [comment]
I honestly believe a solution to this would be easy. The code is right above, and all they need to do is add it to the Linux version of the game. It is honestly disgusting it has gone this long without a solution.

**Comment by Bo98** [comment]
And why it hasn't been done yet is also right above.

> There is no information on how to "declare global CSS so that these widgets are painted by WebKit instead"

Key word: global

**Comment by SharpOB** [comment]
Still, fixing the main menu would be welcome. Without it, you cannot create a new server properly or mount a game (unless you use mount.cfg).

**Comment by Bo98** [comment]
@robotboy655 Did you try `WebConfig.user_stylesheet`?

http://www.awesomium.com/docs/1_7_5/cpp_api/struct_awesomium_1_1_web_config.html#a03632dee9fdcb2437257fda88c2bd3c6

**Comment by SharpOB** [comment]
And this issue appears to be dead again.

**Comment by robotboy655** [comment]
Should be fixed on Dev. Please do tell if it actually is fixed.

**Comment by mcd1992** [comment]
Works on my Machine™

Thanks
