### ISSUE TITLE
Console doesn't open as it should on Linux

### ISSUE THREAD

**Issue by Zebra1337** [Facepunch/garrysmod-issues#2827]
### Details
The console refuses to open on the main menu. Workaround is to open the options menu and then the console opens properly. Doesn't happen on any other source game.

### Steps to reproduce
Load up gmod on Linux and try opening the console (with it enabled in the options) - it won't open. Then open the options and try again - it works.

Fedora 24 - kernel 4.7.2

**Comment by robotboy655** [comment]
Either hold the console key in main menu or use the SHIFT+ESC alternative.
