### ISSUE TITLE
Programming error: CMatRenderContext::Bind: NULL material

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-issues#2829]
```lua_run_cl debugoverlay.SweptBox( LocalPlayer():GetPos(),LocalPlayer():GetPos(),Vector(0,0,0),Vector(10,10,10),Angle(0,0,0))```

**Comment by Kefta** [comment]
This prints in console whenever the game starts as well.

**Comment by robotboy655** [comment]
A bunch of debug overlay functions were trying to use cached materials without caching them first. Will get it fixed soon.
