### ISSUE TITLE
Skybox texture seems transformed

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2830]
### Details
Well the details are unknown but what I can say for sure that the skybox is somewhat corrupted, see the image below.

![hl2_2016-09-25_09-33-57](https://cloud.githubusercontent.com/assets/5415177/18813760/d3bf0b14-8305-11e6-897d-0466a89a63da.png)

Amazing nobody ever noticed.

**Comment by robotboy655** [comment]
Yeah, ours HL2 materials differ from those in HL2.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/18815424/9d7afc32-8339-11e6-8662-b71eb7bac152.png)

**Comment by ZehM4tt** [comment]
So whats the solution now? Will they be replaced in the sourceengine vpks?

**Comment by robotboy655** [comment]
Need to update sourceengine vpks from hl2, but my upload speed sucks so I will have to ask willox to do it.

**Comment by ZehM4tt** [comment]
Okay, thanks!

**Comment by robotboy655** [comment]
Should be fixed with the next dev update
