### ISSUE TITLE
Issues with weapons

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2832]
### Details
I got some issues with weapon I wanted to report.

All weapons:
* Does'nt have a Deploy animation.
* Idle animations begin, when actual Deploy animation(which does not exist) is over. (1 second after deploy ~)

Physics Gun:
* Does not have an idle animation.
* Sometimes goes invisible due to serverlag/clientlag.

Flechette Gun:
* Origin of the flechettes is not the weapon, instead the aim vector.
* Does not have an idle animation.

Fists:
* Does have an deploy animation, but not a deploy timer.(means you can instantous use the fists after equip)
* Can not destroy glass.

Manhack Gun:
* doesnt have idle + deploy anims.

### Steps to reproduce
Equip the weapons.

**Comment by robotboy655** [comment]
All weapons have deploy animations, they are just played 4times as fast. There's a convar for that.

Also you should stop with these non issues.

**Comment by Kefta** [comment]
What's the convar? Also, the lack of idle animations is from the actual models, which is Valve's choice. I could PR the manhack/flechette gun to have idle anims, but it's really not a huge concern.

**Comment by mcNuggets1** [comment]
I know there is a ConVar actually, but that is not the issue.
The Idle animations + idle animations only working after the original length of Deploy animations are ran are the issue. + The invis physgun, fists do not have a deploy timer and can not destroy glass, like crowbars,  flechettes are positioned at aimvector etc.

**Comment by robotboy655** [comment]
The only real issue here is fists not breaking glass.

Idle animations on SWEPs is not an issue, its up to each SWEP to implement them or not, Flechettes are positioned where they should be, just like every single weapon in the game. The "invis physgun" can only be looked into if you have proof of it happening and have a reliable way to reproduce it. Animations in C weapons will not be looked into, at least not anytime soon.

Do not post issue compilations.

**Comment by mcNuggets1** [comment]
I was speaking about the Idle animation of the C++ weapons being initialized too late.
The invisible physgun bug is well known to alot of players. I already told how to reproduce it.
The RPG missile is spawned in the RPG weapon, while the flechettes are spawned in the center of the screen, which looks awful.
