### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2834]
### Details
I updated to Dev to test the new search bar in sandbox.
I browsed for something.
The bar resetted itself every ten seconds, beginning from the half, what was a curiosity.

But after searching for just "1" my game crashed after loading 500 items.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Search for something.
Search for "1"

**Comment by robotboy655** [comment]
Your are probably crashing when trying to render the L4D(2) spawnicons.

```
(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)
```
POST THE CRASH DUMPS IF YOU ARE GOING TO REPORT CRASHES!

What do you mean by "The bar resetted itself every ten seconds, beginning from the half, what was a curiosity.". Do you mean the blue bar showing progress? That's normal.

**Comment by mcNuggets1** [comment]
The blue bar was like 8/10 of the way finished, but then suddenly resetted itself to 4/10, I think because GMod found new models to load.

**Comment by mcNuggets1** [comment]
https://www.dropbox.com/s/hru8k3xfycbsgpb/hl2_160921_crash_2016_9_25T15_5_34C0.mdmp?dl=0
Crashdump

**Comment by robotboy655** [comment]
Yeah, you are crashing when rendering a spawnicon for this model:
```
2270(813.113760):  MDLCache: c1_chargerexit/doors_glass_1.mdl needs to be recompiled
```

Completely unrelated to the spawnmenu changes.

As for the blue bar, it is normal for the very reason you pointed out yourself.
