### ISSUE TITLE
DNumSlider

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2835]
### Details
If you disable displaying decimals on the DNumSlider, but setting a number value to it, it automatically is a decimal.

### Steps to reproduce
Create DNumSlider.
SetDecimals to 0.

**Comment by robotboy655** [comment]
Do you mean that you can edit the value manually and set it to a decimal?
![d](https://cloud.githubusercontent.com/assets/3299036/18817098/a74ca360-8360-11e6-922d-4ef0b5547bca.gif)

**Comment by mcNuggets1** [comment]
No, I integrated in a panel.
Set the value to like 20, and it displayed 20.00, when I change the values it goes without decimals.

**Comment by robotboy655** [comment]
Post some code to reproduce it. I have no idea what you are saying.

**Comment by robotboy655** [comment]
Do you mean to say that you are SetValue'ing BEFORE setting the SetDecimal to 0?

**Comment by bigdogmat** [comment]
Guessing he means as to when you slide the slider to a whole number it'll be displayed as just that number without the fraction.

e.g. slide to 2, `2` is displayed

Although when you type in a whole number it gets displayed with a fraction to the hundredths place,

e.g. type in 2, `2.00` is displayed

**Comment by robotboy655** [comment]
That doesn't happen?
![aa](https://cloud.githubusercontent.com/assets/3299036/18817214/feee4440-8363-11e6-8bc2-9c4195032d2e.gif)

**Comment by mcNuggets1** [comment]
Yea I actually setted SetDecimals after Value.
Wow, I am stupid...
