### ISSUE TITLE
Game lags whan shooting full auto weopons 

### ISSUE THREAD

**Issue by LouisAreHorse** [Facepunch/garrysmod-issues#2836]
When you shoot ant weapon of the full auto weopon catagory it severly lags your game so far I've only had this problem on windows tell me if anyone else has this porblem

**Comment by Kefta** [comment]
You mean like the HL2 SMG and AR2? I haven't encountered this problem.

**Comment by LouisAreHorse** [comment]
No but with all full auto weapons (addon weapons, the deafult weapons,  vecial based weapons)

**Comment by Kefta** [comment]
So addons only? Which "default" weapons are causing this?

**Comment by LouisAreHorse** [comment]
SMG, AR2 and other full auto weapons

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
