### ISSUE TITLE
Game crashed by using "gameui_show_dialog"

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-issues#2839]
### Details

My game crashed.

Link to mdmp file: https://hostr.co/Bt0Srb6j89lG
### Steps to reproduce
- start a new game
- type `gameui_show_dialog dtiknni`
- press escape key
- press escape key
- Game Crashed

**Comment by robotboy655** [comment]
Command is useless and is already blocked, I don't think there's any point in trying to fix this.

**Comment by robotboy655** [comment]
I have removed the concommand now.
