### ISSUE TITLE
Closing the context menu while using a slider causes it to get  "stuck on"

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-issues#2840]
### Details
This only occurs in the Dev branch.
Closing the context menu while using a slider inside of it will cause it to be permanently "stuck on" (I don't know the right terminology for this. focused?) and act as if the mouse button is held down whenever the cursor passes over it.

### Steps to reproduce
1. Use the Q menu to select any tool with sliders in its cpanel so it appears in the context menu.
2. Hold C to open the context menu and show the tool's cpanel. (the bug will not occur with the Q menu)
3. In the context menu, click and hold down the mouse button on a slider to use it as you normally would. Either the slider itself or the "number scratch" (the control used by clicking to the left of the slider) will work for this.
4. While still holding down the mouse button, let go of C to close the context menu. 
5. Reopen either the context menu or the Q menu, and hover the cursor over the slider/scratch you were using earlier. It will act as if you're still holding down the mouse button on it - sliders will automatically move to the cursor, and scratches will "trap" the cursor and use your mouse input until you move it fast enough to get unstuck. Clicking the slider/scratch or a different control will not fix it.
6. Repeat steps 3 and 4 for any number of sliders - there's no limit to how many can get "stuck" this way.

**Comment by robotboy655** [comment]
Will be fixed.
