### ISSUE TITLE
Server crashes if "prop_combine_ball" is spawned and exploded underwater

### ISSUE THREAD

**Issue by CommanderNZ** [Facepunch/garrysmod-issues#2841]
### Details
Server crashes if "prop_combine_ball" is spawned and exploded underwater.

Crazy origin, angles, velocity, angular velocity on entity [1561][prop_combine_ball]
Origin:           [-1.#IND00, -1.#IND00, 1.#QNAN0]
Angles:           [-1.#IND00, 1.#QNAN0, 180.000000]
Velocity:         [-1.#IND00, -1.#IND00, 1.#QNAN0]
Angular Velocity: [-1.#IND00, -1.#IND00, 1.#QNAN0]
Defusing!
Removing!

### Steps to reproduce
Just spawn a ""prop_combine_ball" underwater and make it exploded.
Can either be spawned by console or Lua, crash will happen either way.

**Comment by robotboy655** [comment]
Cannot reproduce on Dev:
![image](https://cloud.githubusercontent.com/assets/3299036/18894423/964b3920-851b-11e6-9268-0d0be5739d06.png)

It just explodes normally or gets removed by crazy physics if you don't explode it.

**Comment by Kefta** [comment]
Tested with the same spawning parameters as the AR2 (minus the entity specific methods that the Lua state doesn't have access to), no crash:
![](http://i.imgur.com/mBZaJrD.png)
