### ISSUE TITLE
Pre-release crashes on Linux

### ISSUE THREAD

**Issue by xDShot** [Facepunch/garrysmod-issues#2842]
When I launch Garry's Mod, the loading screen appears, but on 'Initializing all game systems' it just closes. No mdmp being created, so I cannot load it here.

OS - Arch Linux x64

**Comment by Jake3231** [comment]
I have tested this on my OS X 10.11.6 Mac, and it works fine.  On your distribution of Linux, is there anything like the Mac's Console, where you can see any messages printed to the log by running processes?

**Comment by xDShot** [comment]
Well, I've launched steam from terminal (virtual console), then launched Garry's Mod, but didn't notice anything helpful.

I'd tell if I found something helpful.

**Comment by willox** [comment]
I'm not a Linux user, but there's not much that can happen unless you can grab a coredump related to this issue. https://wiki.archlinux.org/index.php/Core_dump

**Comment by xDShot** [comment]
I'll see if I can grab core dump. Is it safe to upload here? Because it might have a very sensitive data I'd not to share in public, afaik.29.09.2016, 09:41, "William Wallace" <notifications@github.com>:I'm not a Linux user, but there's not much that can happen unless you can grab a coredump related to this issue. https://wiki.archlinux.org/index.php/Core_dump

**Comment by xDShot** [comment]
I'll see if I can grab core dump. Is it safe to upload here? Because it might have a very sensitive data I'd not to share in public, afaik

**Comment by willox** [comment]
You can email willox@facepunchstudios.com if you prefer

**Comment by xDShot** [comment]
@willox I've sent you my coredump to you via email. Could you please examine it?

**Comment by xDShot** [comment]
Alright, it seems the problem was on my side. I've updated the graphics drivers and it runs fine :)
