### ISSUE TITLE
PANEL:HasFocus() returns true when PANEL:OnFocusChanged(false)

### ISSUE THREAD

**Issue by TehBigA** [Facepunch/garrysmod-issues#2843]
### Details
From within PANEL:OnFocusChanged, when it is called with false (loss of focus) self:HasFocus() still returns true.

Looks like PANEL:HasFocus() just has the old value when the hook is called. If this is intentional it should be updated on the wiki, but it's causing some issues with DNumberWang validation since it checks for focus and prevents updates to the value. I was trying to validate the value in PANEL:OnFocusChanged(false).

### Steps to reproduce
Execute code and click on then off the text entry.
`
local frame = vgui.Create('DFrame')
frame:SetSize(400, 300)
frame:MakePopup()
frame:Center()

local entry = vgui.Create('DTextEntry', frame)
entry:Center()
function entry:OnFocusChanged(gained)
    print('PANEL:OnFocusChanged(', gained, ')')
    print('self:HasFocus() = ', self:HasFocus())
end

`

**Comment by robotboy655** [comment]
Yeah, its intentional.
