### ISSUE TITLE
October update has even more broken optimization.

### ISSUE THREAD

**Issue by BrewsterTKoopa** [Facepunch/garrysmod-issues#2844]
Just like the april update http://steamcommunity.com/sharedfiles/filedetails/?id=771974521
its lagging like heck,but actually its even worse. i don't know how,i got ALOT less addons then in the april update and this update made it even more unplayable. it broke map optimization even more,evidenced by the wireframe and the low fps as it says up there.

according to my friend who has alot less addons then me,

ANON:Soooo much lag it's unplayable.

its bad enough he can't play his favorite map. I love gmod and i know i might be establishing that fact too much,but its just its a great game to me. it helped me who i am today i love contributing to it. and the greatest maps are too laggy due to the optimizing.

**Comment by robotboy655** [comment]
Stop blaming shitty maps ( or shitty addons ) with shitty-to-no optimization lagging on updates.

It is not fault of the updates, but of the shitty maps ( or shitty addons ) and their authors.

Here's a comparison of the same map from workshop, with no addons installed at all ( -noaddons and -noworkshop ) on both Dev and normal Steam versions of the game.
http://imgur.com/a/3EPTk

In the exact same position using getpos and setpos console commands.

**Comment by robotboy655** [comment]
Not to mention mat_wireframe lowers your FPS considerably as well.

**Comment by BrewsterTKoopa** [comment]
the game does not freeze when my menu is paused,i also had mat_wireframe on because i knew you would suggest me to show you that. it is entirely the updates fault.

**Comment by BrewsterTKoopa** [comment]
i have known updates of the game had broken several things of the years of garry's mod. how are you not acknowledging it? old maps work fine, before the update. plus keep in mind alot of my friends also get this same issue. you can think i'm some kid or something but rest surely knowing that its the update's fault.

**Comment by Kefta** [comment]
Take a video on the main and dev branches with no addons installed to show this change.

**Comment by BrewsterTKoopa** [comment]
but i tested it on the pre-release.

**Comment by BrewsterTKoopa** [comment]
nevermind,anyways i'll do it. in the mean time here http://steamcommunity.com/sharedfiles/filedetails/?id=772072826

**Comment by BrewsterTKoopa** [comment]
.......actually no nevermind,rubat i'm sorry for wasting your time,same with your Kefta. If disabling addons or removing addons that i might've used is the only way to stop the update's side effects,alright.

**Comment by BrewsterTKoopa** [comment]
after testing a very laggy map that went normal,i'm gonna do my own test,to see if a addon is causing my lag because i notice gm_shambles was not broken.
