### ISSUE TITLE
Custom models

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2845]
### Details
Nearly every custom player model in GMod has this one issue.
When jumping and colliding with the ground, the playermodel plays an weird animation sequence.
Like the player fell down and gets up again.

I could promise, this wasnt before the may update.

### Steps to reproduce
select custom playermodel
activate third person
jump a few times

http://puu.sh/rtVay/489aef85ff.jpg

**Comment by robotboy655** [comment]
This is a problem with said models.

**Comment by mcNuggets1** [comment]
This wasnt happening, before the gmod update.
And if it is, how it is supposed to be fixed?

**Comment by robotboy655** [comment]
Model authors must fix this in their addons by following what default player models do. You are using GM12 era player models or people are using GM12 era player models as player model examples.

**Comment by mcNuggets1** [comment]
Isnt there a quick fix, or something as this is really annoying.

**Comment by robotboy655** [comment]
No, there is no a "quick fix".

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/230 would be the quick fix. IIRC, the issue is using the old male anim structure
