### ISSUE TITLE
Increase D3D9 Vertex Index.

### ISSUE THREAD

**Issue by saengbok** [Facepunch/garrysmod-issues#2846]
### Details
Graphics engine creates an overflow when too many textures are loaded at once.

### Steps to reproduce
On TTT gamemode, get chainsaw (or any weapon which creates a lot of blood) then aim at person who has to crash. The person with integrated graphics, will receive following error, which comes from HL2 Engine.

https://gyazo.com/51c7889a2668456425887d4d8afe83f3

Please consider increasing a index buffer limit to 16bits.

**Comment by thegrb93** [comment]
They're already 16 bit, idk why it's using the signed max value of vertices. 32 bit would be the next step up, but that will hit performance and idk if the devs even have control over it.

**Comment by saengbok** [comment]
I was about to mention unsigned 16 bit. Sorry.

**Comment by robotboy655** [comment]
This isn't how it works.

For decal crash, refer to https://github.com/Facepunch/garrysmod-issues/issues/2566
