### ISSUE TITLE
3000 range events not passed into FireAnimationEvent

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2847]
Unhandled animation event 3900 for player
Unhandled animation event 3900 from player --> weapon_hl2mp_frag
(1630.41) input <NULL>: npc_grenade_frag.SetTimer(2.5)
Unhandled animation event 3005 from player --> weapon_hl2mp_frag
Unhandled animation event 3015 from player --> weapon_hl2_357

These errors are printed in console, however, FireAnimEvent is never called. These are usually handled in WEAPON::Operator_HandleAnimEvent

**Comment by Kefta** [comment]
It seems to be something with all HL2 weapon events since this will also print with the default SMG:
Unhandled animation event 21 from player --> weapon_smg1
Unhandled animation event 21 from player --> weapon_smg1

**Comment by robotboy655** [comment]
Now they are

**Comment by Kefta** [comment]
Thank you!

**Comment by Kefta** [comment]
They are still not passed. Tested with the .357 and "Unhandled animation event 3015 from player --> gsweapons_hl2_weapon_357" is printed, but the event didn't trigger FireAnimationEvent.

**Comment by robotboy655** [comment]
They definitely seem to be working for me on Dev.

```
Giving Rubat a weapon_flechettegun
526.208496 -353.343994 -83.968994	-0.528 -179.340 0.000	21	357 muzzle
526.208557 -353.343994 -83.959045	-0.588 -179.340 0.000	21	357 muzzle
466.494232 -354.031860 -147.968994	-0.528 -179.340 -0.000	3015	
466.345612 -354.033569 -83.968994	-0.528 -179.340 0.000	21	357 muzzle
466.345551 -354.033569 -83.973366	-0.695 -179.340 0.000	21	357 muzzle
466.329559 -354.033752 -84.090279	-5.202 -179.340 0.000	21	357 muzzle
466.288147 -354.034241 -84.198135	-9.561 -179.340 0.000	21	357 muzzle
466.086639 -354.036560 -84.414230	-20.301 -179.340 0.000	21	357 muzzle
465.873413 -354.039001 -84.500137	-27.936 -179.340 0.000	21	357 muzzle
465.572968 -354.042480 -84.504036	-37.043 -179.340 0.000	21	357 muzzle
465.090363 -354.048035 -84.260696	-51.477 -179.340 0.000	21	357 muzzle
520.733582 -549.391479 -147.968994	4.796 -95.036 -0.000	3015	
563.647888 -898.327271 -79.917473	6.048 -177.220 0.305	21	357 muzzle
561.985840 -898.513550 -79.926125	5.881 -177.217 0.275	21	357 muzzle
559.525208 -898.788635 -80.067993	0.392 -177.214 0.250	21	357 muzzle
558.154053 -898.935669 -80.211174	-5.289 -177.213 0.223	21	357 muzzle
556.931091 -899.061829 -80.359734	-12.011 -177.213 0.199	21	357 muzzle
547.794373 -900.016968 -143.968750	6.292 -176.920 0.000	3015	
547.794373 -900.016968 -79.968750	7.304 -176.260 0.000	21	357 muzzle

```

My code being https://hastebin.com/qefocapoli.lua

Keep in mind, the 3000 range evens are serverside only

**Comment by Kefta** [comment]
@robotboy655 Oh, the wiki still had it listed as clientside only. I have fixed it and noted about the event range realms. Thanks.
