### ISSUE TITLE
All r_decal_* commands doesnt seem to work

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2848]
### Details
The said commands just do nothing.

### Steps to reproduce
Change one of the convars, and see it do nothing

**Comment by robotboy655** [comment]
They are disabled in GMod on purpose.

**Comment by mcNuggets1** [comment]
How about removing them then?

**Comment by robotboy655** [comment]
How about no?

**Comment by mcNuggets1** [comment]
Yeah, I always wanted to have something that does absolutely nothing, but promises to do something.
Good idea!

**Comment by Kefta** [comment]
@mcNuggets1 There's probably hundreds of unused convars currently available in Garry's Mod; it's not worth the time to go through the entire codebase to test which do, especially when some are still used internally. I'd be fine with hiding them to the client, but again, probably not worth the time.
