### ISSUE TITLE
Switching to a weapon with no ammo does not update the viewmodel

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2849]
Replication (tested on dev branch in single-player):
- Give and switch to weapon_base
- Run "lua_run local p=Entity(1) local w=p:GetActiveWeapon() p:RemoveAmmo(9999, "pistol") w:SetClip1(0) w:SetClip2(0)"
- Switch away and switch back

**Comment by robotboy655** [comment]
Seems to be a sideeffect of when GMod started allowing to "whip out" empty weapons and when AutoSwitchFrom is set to true.

**Comment by robotboy655** [comment]
FIx'd

**Comment by Kefta** [comment]
Thank you!
