### ISSUE TITLE
error in my game npc wrong 

### ISSUE THREAD

**Issue by default321** [Facepunch/garrysmod-issues#285]
I'd like to report that my game was ok, but  now it has a problem. The characters appears standing up wrong. 

this is 1 photo of my game
![hl2 2013-07-18 12-36-36-91](https://f.cloud.github.com/assets/5041186/820963/be7c9602-efd0-11e2-8efe-d20215bf8435.png)

**Comment by kem008** [comment]
This bug is still exist in Dedicated Servers not just npcs like props and others...
