### ISSUE TITLE
First client HUD_PRINTCENTER is slightly grey

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2850]
First HUD_PRINTCENTER of a player starting up their game will be slightly discoloured (grey vs the expected white). Tested in single-player

First: http://i.imgur.com/g9Dzdx9.jpg
Subsequent: http://i.imgur.com/POS9R4E.jpg

**Comment by mcNuggets1** [comment]
Can approve this.

**Comment by robotboy655** [comment]
Fixed...
