### ISSUE TITLE
Peer-to-peer can't be properly disabled

### ISSUE THREAD

**Issue by SentryGunMan** [Facepunch/garrysmod-issues#2852]
### Details

Tell us exactly what happens, every single detail that you can think of

When launching GMod (even in singleplayer or the main menu), p2p can't be turned off. This poses a problem for me due to bandwidth usage limits, so I don't get to develop as much as I'd want to. I've tried adding p2p_enabled 0 to my autoexec.cfg, +p2p_enabled 0 to my launch options, neither of which actually work. They make the command set to 0 once I've loaded, but it's still creating bandwidth through steam.exe (presumably from p2p connections). Narrowing this down to p2p is all an assumption on my end, but it's happened in every other game I've played with steamworks p2p compatibility, so I'm sure that it's probably the reason it started happening in GMod for me too. 
### Steps to reproduce

launch gmod
check network monitor

**Comment by robotboy655** [comment]
I dunno, your story doesn't even add up on my end.

![image](https://cloud.githubusercontent.com/assets/3299036/19177526/9a962b50-8c52-11e6-8cd7-f137c78f745f.png)

Steam uses periodically 0.1Mbps at max in main menu/singleplayer, which would take 30mb per month at best at this rate, and it has nothing to do with P2P or GMod because it does it when no games run as well.

**Comment by robotboy655** [comment]
You can also try limiting bandwidth in Steam Downloads Settings. And make sure it's not Steam updating something like a game or an addon or Steam Cloud synching something.

**Comment by SentryGunMan** [comment]
![image](https://cloud.githubusercontent.com/assets/3654255/19205127/769c227a-8cae-11e6-82ba-b4341819563b.png)
![image](https://cloud.githubusercontent.com/assets/3654255/19205188/d8b86dec-8cae-11e6-962a-9a473e7f71bb.png)

**Comment by willox** [comment]
I've just double checked for you. None of the Steamworks API's P2P methods are even called unless you're in a multiplayer (> 1 max players) game. Nor are they called in the main menu.

**Comment by robotboy655** [comment]
Could be Steam workshop, in which case you should try -noworkshop and see if there's any difference.

**Comment by SentryGunMan** [comment]
Using -noworkshop makes no difference. I wouldn't doubt it being some other part of Steam, but I don't know what would do it considering I've tried unsubscribing from every addon and even making sure GMod and HL2 are the only games in the common folder, which didn't have any impact.

**Comment by robotboy655** [comment]
Maybe it's time to contact Steam Support then? Since clearly GMod is not the only game that causes this and it Steam that uses bandwidth.
