### ISSUE TITLE
Server Side Multi-Core Support

### ISSUE THREAD

**Issue by Mrsexyness** [Facepunch/garrysmod-issues#2853]
I believe you should add Multi-Core support to the server side of G-Mod, servers would perform so much better and It will make G-Mod look way better as it has been an issue for along time and it kills people hosting servers at home with an alright CPU, but it only uses one core.

**Comment by uRandomAlex** [comment]
@Mrsexyness The problem that it's just not possible. From what I know physics is the most expensive thing, and it's single-threaded. GMod devs don't have access to VPhysics source code. There is a multi-threaded replacement for VPhysics, but it's not completed and consumes way more resources then VPhysics.

**Comment by Mrsexyness** [comment]
What if the make everything that isn't physics related run on another core. When you have a 40+ player server that stuff adds up and DarkRP isn't fun on a 12-22 tick server.

**Comment by neico** [comment]
What sense does it make if you move everything beside physics to another core?
That's only shifting things around, not to mention the obvious threading issues you'll run into while trying to sync physics with the rest...

You can't just rip out parts of a system and patchwork it together in a scrambled fashion in the hopes that it still does what it's supposed to...

**Comment by Mrsexyness** [comment]
Maybe in the future, I feel like the VPhysics issue is limiting G-Mod server side.I am going to close this now, Thank for replying guys.
