### ISSUE TITLE
WEAPON:GetCycle() always returns 0 or 1

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2856]
Doesn't matter if it's a SWEP or engine weapon.

**Comment by robotboy655** [comment]
There's no weapon specific function GetCycle. It would use the world model, and I don't think it animates properly as there's no need for it. So I'd say this is normal for what it is.

**Comment by Kefta** [comment]
Oh, I thought it would redirect to the viewmodel. Thanks for the info
