### ISSUE TITLE
Holstered weapons still draw their shadows

### ISSUE THREAD

**Issue by daunknownman2010** [Facepunch/garrysmod-issues#2857]
It seems in the latest October update, the weapons that are holstered draw their shadow. I've noticed this occur in the Source 2013 SDK code before, so I expect it's from a HL2 code update.

Cycle through all the weapons you have in your HUD, then draw your playermodel to make your shadow visible. You'll see that all the weapons you've just cycled through still draw their shadow even though they're holstered. It should look like this:

![20161010223333_1](https://cloud.githubusercontent.com/assets/5220286/19239837/6d87ef50-8f3a-11e6-8e5f-37ab502c599e.jpg)
_As you can see, I am currently holding a pistol but you can see all the other weapons (Eg. crossbow)._

**Comment by willox** [comment]
I think I've noticed this before the update too

**Comment by DrVrej** [comment]
Same here

**Comment by willox** [comment]
Does this only happen when you've got whatever addon is rendering your legs installed? I'll need to know what addon it is (is it on the Workshop?)

**Comment by Kefta** [comment]
This happens to me without the legs mod. Here's the most commonly used one, however: https://steamcommunity.com/sharedfiles/filedetails/?id=112806637

**Comment by willox** [comment]
How do you reproduce it? Can you run debug_dump in your console and upload the garrysmod/debug_dump.txt file here? It lists all your ConVars so watch out for any rcon passwords and similar data.

**Comment by Kefta** [comment]
I can reproduce it on the dev branch by starting up a single-player game of gm_construct through the console, spawning and looking through a camera, and switching through the weapons. The shadows of each weapon don't appear until you swap to it. Here's my dump file: http://pastebin.com/LvuFPpRb

**Comment by willox** [comment]
Yeah this is clearly a regression from some recent change I'll have to find. Thanks.
