### ISSUE TITLE
The "Q Menu" Broken On Some Servers.

### ISSUE THREAD

**Issue by BalisticGaming** [Facepunch/garrysmod-issues#2858]
### Details
Tell us exactly what happens, every single detail that you can think of

When i join certain servers (CombustionEngineers Train Build) Being One Of Them, No One Can Use There "Q Menu" for spawning in props at all, but everythink else works fine.

http://steamcommunity.com/profiles/76561198060547331/screenshot/253716559976042838

**Comment by robotboy655** [comment]
It's a problem with said server.
