### ISSUE TITLE
"Q Menu" Broken For Prop Spawning

### ISSUE THREAD

**Issue by BalisticGaming** [Facepunch/garrysmod-issues#2859]
http://steamcommunity.com/profiles/76561198060547331/screenshot/253716559976112711
http://steamcommunity.com/profiles/76561198060547331/screenshot/253716559976042838

HOW MUCH MORE PROOF WOULD YOU LIKE?

No One Can Use The Q MENU To Spawn Props!

Please Fix It, And Not Just Say Its A ServerSide Problem, BECAUSE ITS NOT!

**Comment by daunknownman2010** [comment]
You're really trying to get on @robotboy655's nerves by doing this. The server configuration could've corrupted itself, also GIVE US DETAILS ABOUT THE SERVER/OS. This won't be solved with screenshots.

**Comment by BalisticGaming** [comment]
Fine, you want more details? Here you go, but this might not be the same for ever server!

**Comment by AilynRockRyan** [comment]
the os is lunbuntu
before the update we didnt have the same problem
we have 4 server in out comunity with the same problem and 1 of the servers are rented

**Comment by Bo98** [comment]
Does validating the serverside installation make any difference, if your host allows you to do that? (Yes, validating matters because files are networked)

**Comment by AilynRockRyan** [comment]
that is app_update 4020 validate right?

**Comment by robotboy655** [comment]
Try the following: Disable all addons.

**Comment by Bo98** [comment]
Yes, that's right.

**Comment by BalisticGaming** [comment]
Disable the addons, then what? Just leave them off untill another update or somethink?

**Comment by robotboy655** [comment]
Not you, the server owner.

**Comment by BalisticGaming** [comment]
I am a server owner...

**Comment by AilynRockRyan** [comment]
balistic is the server owner im just the host

**Comment by BalisticGaming** [comment]
Yes, but i do have one server which I pay for (rent). So how would i "disable" them?

**Comment by robotboy655** [comment]
So you are saying that both of you host server(s) and you don't know how to remove the addons you installed onto your server(s)...?

Remove the collection from the start up parameters and rename the addons/ folder, then restart the server. See if the issue is fixed.
If it is -> The problem is with one of your addons
If it is not-> Post clientside console log when server is not running any addons.

**Comment by BalisticGaming** [comment]
Ok thank you, I will give you an update...

**Comment by AilynRockRyan** [comment]
so we removed all addons. that turn out to be the problem :P   but heres the thing how the fuck do i know witch on does it xD

**Comment by Bo98** [comment]
Add them back one by one.

**Comment by AilynRockRyan** [comment]
oh god :P
thats gonna take a month xD

**Comment by Bo98** [comment]
You can add them back in batches then remove the addons in the batch one by one again when you get the problem again I guess. I'm sure you can think of a way to do it.

**Comment by BalisticGaming** [comment]
Yep... How fun...

**Comment by sammyt291** [comment]
Could this issue be being caused by addons that add their model folders to the spawn menu?
such as SProps or:
http://steamcommunity.com/sharedfiles/filedetails/?id=584656893

**Comment by BalisticGaming** [comment]
Its possible, I'll try removiung them

**Comment by robotboy655** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=571043209

This is one of the mods that causes this. Relevant error:
```[ERROR] lua/autorun/semassets_init.lua:15: attempt to call method 'GetInfoNum' (a nil value)
1. fn - lua/autorun/semassets_init.lua:15
2. Call - addons/ulib/lua/ulib/shared/hook.lua:109
3. Function - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/content.lua:79
4. unknown - gamemodes/sandbox/gamemode/spawnmenu/creationmenu.lua:38```

Basically look for mods that have Lua errors.
