### ISSUE TITLE
DComboBox no longer allows Integers, how do I sort then?

### ISSUE THREAD

**Issue by doctorluk** [Facepunch/garrysmod-issues#2860]
The patch details claim the following:
`NEW - DComboBox – Proper sorting and ability to disable it`

I have a form that asks date of birth details when first joining (18+), thus it is crucial to be sorted and easy to use.

The way I did add days was:
```
for i = 1, 31, 1 do
	day:AddChoice( i )
end
```

Then I get this error now:
```
[ERROR] lua/vgui/dcombobox.lua:168: attempt to index local 'v' (a number value)
  1. OpenMenu - lua/vgui/dcombobox.lua:168
   2. DoClick - lua/vgui/dcombobox.lua:225
    3. unknown - lua/vgui/dlabel.lua:232
```

So the only way to fix this is to use strings instead. I do this now:
```
for i = 1, 31, 1 do
	day:AddChoice( i .. "" )
end
```
which leaves me with this: https://gyazo.com/783646908244867e424e0f880872d06a

Where is the documentation for the new sorting function and why did you even remove the possibility to use simple numbers?

EDIT: OS is Ubuntu

**Comment by robotboy655** [comment]
Yeah my bad, I assumed it to be always a string that is longer than 1 character. Will fix.

**Comment by robotboy655** [comment]
In your case you should use SetSortItems( false ) though.

**Comment by doctorluk** [comment]
Yes, this function makes it look like before. Thanks for the quick reply and solution!

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/4239fb2e9fd546417a95ef5fab09eb4a0db23764
