### ISSUE TITLE
Memory starts growing the more you change levels

### ISSUE THREAD

**Issue by daunknownman2010** [Facepunch/garrysmod-issues#2862]
I've changed to around 15 different maps because of a friend having "Out of memory" issues. With 16GB of RAM, I decided to test out this theory of a possible "memory leak". After changing to about 15 different maps with changelevel, I have come to the conclusion that perhaps something definitely is not right with the memory usage. I've gotten to around 3.1 GB of RAM before Garry's Mod crashed unknowingly. My friend, Wolvindra, believes that this never happened before the October update and stayed at a stable rate before he applied the update.

[http://puu.sh/rEjMn/e2027a6ca6.jpg](url) Wolvindra was kind enough to get an image of the memory usage too.

**The memory usage only grows by using the changelevel command and changing to different maps (Changing to the same map does not increase the memory usage by a large amount). If this is normal behaviour, please comment and close this post.**

**Comment by Vinzuerio** [comment]
Additional screenshot from my actual crash with "Out of memory" with 4-5x changlevels
http://puu.sh/rEkcR/b72460faa2.png

some of my other friend also having this issue too, it gets the memory goes up to 2 GB with 7x changelevels
https://puu.sh/rEiUK/e5dec03d2e.jpg

Happens on both in Singleplayer or even in Multiplayer. This doesn't seem happen this much before in gmod October update.

**Comment by daunknownman2010** [comment]
I got myself a screenshot before it decided to crash again. The game will always crash once it reaches the 3.1 GB of RAM usage mark.
![memoryleek](https://cloud.githubusercontent.com/assets/5220286/19267299/95f4f694-8fe0-11e6-8a38-fd74709e8cfc.png)

**Comment by Vinzuerio** [comment]
**update:**
Some clients having worse artifacts after they got no memory left in their RAM, which resulting like this:
http://puu.sh/rF9zu/bf59c00895.jpg
http://puu.sh/rF9AF/3efce5371d.jpg
http://puu.sh/rF9Vm/2915572ed3.jpg

And I also noticed when you go outside of the map (Any maps including sandbox or gm_flatgrass), or entering to 3D skybox, your screen will freeze for 10 - 15 seconds, which then I noticed the memory suddenly getting full in a quick up to 2 GB, with no "out of memory" notice.

However, this also happens **if you stay still in the map for long time, (while not reloading the map), the RAM will fills up very quickly and resulting memory goes up to 98%**

happens on All Windows OS, both 32-bit & 64-bit, Not sure with other OS...

**Comment by robotboy655** [comment]
I'd recommend you start looking into the addons your server(s) have installed. I cannot reproduce this 10 second freeze on flatgrass, and neither can I reproduce "standing for long time quickly fills up RAM". Nothing happens on my end.

**Comment by Vinzuerio** [comment]
I've also tried hosting with no addons and no workshop in multiple times, and since after installing october update then I created for both listen and dedicated server.
Listen server however it goes really bad as dedicated server one, since it seems multiplies when more players joining.
Started with clean dedicated server and it still happen to the clients (including me), ram goes fills up really quick.
The only effect is when changing into any maps in several times or staying too long will cause the RAM fills up really quick.

It seems doesn't matter how much RAM you have, it still affects when it reaches to 3 GB marks (mentioned from @daunknownman2010 )

**Comment by daunknownman2010** [comment]
On my end, I did not get memory leaking from standing still, only from changing levels. However, removing everything (including legacy addons) and playing in pure Sandbox will make memory grow still. I began on gm_construct, changed to gm_flatgrass, then changed through the cs_* maps then de_* maps. The memory starts growing to a point Garry's Mod can't handle it and crashes like previously mentioned.

**Comment by Vinzuerio** [comment]
I just realised this from the update changelog

"PNG/JPEG textures/materials are now properly garbage collected and will be free’d on a level change"

Do this may relate? because AFAIK it may not being free'd for some reason when level changes

**Comment by willox** [comment]
I see the issue, you can expect an update for tomorrow.

**Comment by bmwalters** [comment]
Lmao.
![](http://i.imgur.com/vPqjt9i.png)

**Comment by willox** [comment]
```cpp
void CImage::CloseImage()
{
	if ( !m_pImage )
		return

	FreeImage_Unload( m_pImage );
	m_pImage = NULL;
}
```

**Comment by Vinzuerio** [comment]
Thank you!
