### ISSUE TITLE
(hook) PopulatePropMenu

### ISSUE THREAD

**Issue by etc-network-interfaces** [Facepunch/garrysmod-issues#2863]
### Details
Good evening. First of all, thank you for improving Garrysmod and shipping updates. 

I just encountered an issue with the latest update. 

Let's assume I have the following code in a fille called "./lua/autorun/custom-props.lua"

**Custom category**

```lua
hook.Add("PopulatePropMenu", "Custom Props", function()
        local contents = {}

        table.insert( contents, {
		type = "header",
		text = "Just some custom props"
	} )
	table.insert( contents, {
		type = "model",
		model = "models/props_c17/oildrum001.mdl"
	} )
	spawnmenu.AddPropCategory( "CustomProps", "Custom Props", contents, "icon16/shape_square.png", 9254 )
end)
```
While this should register a new category, the GM hook simply wipes it.

```lua
function PopulateFromEngineTextFiles()
 
	-- Reset the already loaded prop list before loading them again.
	-- This caused the spawnlists to duplicate into crazy trees when spawnmenu_reload'ing after saving edited spawnlists

	PropTable = {}

 	spawnmenu_engine.PopulateFromTextFiles( AddPropCategory )
 end
```

https://github.com/garrynewman/garrysmod/commit/1baf0c452b1b59a8401e314fdb0553caa26a2046?w=1#diff-6f083ef30d23cecdf384116fbb47f82dR171

Now I'm not an expert but it seems that the ```PropTable = {}``` variable overrides any category that was previously added.

When I removed the ```PropTable = {}``` variable, the category was successfully registered (thus visible in Q-Menu).

OS: Server on Debian Linux, Client on Windows 7

### Steps to reproduce

1. Create a custom spawnlist / or category in a "PopulatePropMenu" hook.
2. Check if the category is available (Q-menu)
3 If not, go to lua/includes/modules/spawnmenu.lua and remove the ```PropTable = {}``` variable at line 173
4. Now check if you can see the category (Q-menu)

_**Edit:**_

Might be related: https://facepunch.com/showthread.php?t=1537327

**Comment by robotboy655** [comment]
What you are doing is inherently wrong, you should not be forcing adding spawnlists to player's spawnlists infinitely.

What you should be doing is what SProps is doing - adding a whole new category that player can pull items from into his spawnlists when needed.
