### ISSUE TITLE
New chair hitboxes don't take explosive damage.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2864]
The chairs take bullet damage now which is nice, but not explosion damage for some reason.

**Comment by robotboy655** [comment]
I am not bothering with figuring this out.

**Comment by Kefta** [comment]
Check the RadiusDamage filter

**Comment by mcNuggets1** [comment]
The damage itself isn't working for me.
I can't damage myself in a chair, bullets go just through me. (Tested with creating a bullet shot through me, while I am not in the ignoreentity filter)

**Comment by mcNuggets1** [comment]
Just the airboat sit works.

**Comment by robotboy655** [comment]
Passengers/drivers cannot be damaged in any vehicle. This is just how it is.

**Comment by robotboy655** [comment]
Yes, those are also considered vehicles.

**Comment by robotboy655** [comment]
Should be fixed on Dev beta when it next updates.
