### ISSUE TITLE
IMaterial:GetColor() is very slow&&causes memory leak after update

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#2865]
After update, addons that are getting many pixels from single image at one game frame just crashing the game.

Example - PPM. Try to apply custom mark, game would freeze, then crash with "Out of memory"

Next code
```
local mat = Material('materials/ppm_custom/testing.png')
print(mat:Width())
print(mat:Height())

local t = SysTime()
local color = mat:GetColor(513, 513)
print((SysTime() - t) * 1000)

local t = SysTime()
local color2 = mat:GetColor(1, 1)
print((SysTime() - t) * 1000)

PrintTable(color)
PrintTable(color2)
```

Gives next output:
```
512
512
24.643678419011
17.700819737968
a	=	6
b	=	128
g	=	233
r	=	18
a	=	255
b	=	255
g	=	255
r	=	255
```

I think it is related to FreeImage update

UPD: Reading pixes also causing **major** memory leak

**Comment by robotboy655** [comment]
#2862 Related?

**Comment by roboderpy** [comment]
I don't think so. This memory leak comes from reading pixels itself. If you call GetColor(), for example, 16 000 times, your GMod would *nom nom nom* 3 308 MB of RAM then, after some moment, crash without any error popups

**Comment by roboderpy** [comment]
It is sad that every GMod update is not coming without bunch of bugs :(

**Comment by daunknownman2010** [comment]
It is sad that no one in the community bothers to even test the pre-release. It's why the main branch gets a bunch of bugs like this. I assume there's something not freeing up the memory properly in the code.

**Comment by bgpony** [comment]
@daunknownman2010 I really wish they would release betas like they do for many other games, which now includes CS:Go.

**Comment by bmwalters** [comment]
@bgpony we do - in the exact same way as CS:GO - the game's "Betas" tab - select "prerelease" for beta or "dev" for bleeding edge

**Comment by Kefta** [comment]
@daunknownman2010 I always play on the dev and prerelease branches; it's now pretty convenient to test new builds unlike before.

**Comment by daunknownman2010** [comment]
@Kefta I'm not saying everyone doesn't test the beta branches, but a majority of the community doesn't bother. I'm happy to test the prerelease/dev, but never noticed the memory leaks until recently when people started reporting on getting "Out of memory" errors on occasions.

**Comment by willox** [comment]
I see the issue, you can expect an update for tomorrow.

**Comment by bmwalters** [comment]
Lmao.
![](http://i.imgur.com/vPqjt9i.png)

**Comment by bgpony** [comment]
@bmwalters Thanks! I wasn't aware of this. That's very helpful.
