### ISSUE TITLE
VGUI text width ignores ampersands (&)

### ISSUE THREAD

**Issue by Xyxen** [Facepunch/garrysmod-issues#2867]
Anything internally using a TextImage (e.g. DLabel, DButton) incorrectly calculates their width when ampersands are used. This is particularly noticable when SizeToContents is used:

![hl2_2016-10-12_15-14-09](https://cloud.githubusercontent.com/assets/434951/19327914/a8b9f24e-908e-11e6-9ccb-03958a7fda20.png)

The above image was generated using the minimal test case below:

``` lua
concommand.Add("test_vgui_ampersand", function()
    Derma_Message("Message with && ampersand", "Title with && ampersand", "Button with && ampersand")
end)
```

The regular behaviour is that a single ampersand preceding a character (e.g. `&a`) designates that character as an accessibility hotkey, and the ampersand is not rendered. An actual ampersand character can be displayed by escaping the ampersand with another (i.e. `&&` rather than `&`). This can be seen [here in `TextImage.cpp`.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/vgui2/vgui_controls/TextImage.cpp#L398-L415)

However, [here in the same file,](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/vgui2/vgui_controls/TextImage.cpp#L507-L511) the total width of the text is calculated _ignoring ALL ampersands._ The correct behaviour would be to ignore all _unpaired_ ampersands, and count each ampersand pair as one. Of course, [all of this may be partial cruft anyway,](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/vgui_controls/Controls.h#L149-L151) but removing it altogether might (at least) break certain language strings from older Source games.

This is all tested on the latest dev branch (2016.10.12). I'd like to confirm that what I've described is definitely the issue, but I don't have the time to be compiling SDK2013 right now.

**Comment by willox** [comment]
I looked in to this before and was also lead to the `VGUI_DRAW_HOTKEYS_ENABLED` definition. I'll give it another look.

**Comment by Faerachnidendro** [comment]
Please update if you finda  fix for this one, always gets under my skin not being able to use &

**Comment by willox** [comment]
This behaviour sucks quite a bit (100%). I'm disabling it in any VGUI created by the menu/client state. It'll still exist in stuff like the options menu.
