### ISSUE TITLE
javascript_util.lua:26: attempt to index a nil value

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#2868]
### Details
[lua/includes/util/javascript_util.lua:26](https://github.com/garrynewman/garrysmod/blob/78db0e40da7480c9ba0224e465dc264de87b5322/garrysmod/lua/includes/util/javascript_util.lua#L26)

Console log:
```
unhandled input: (OnPlayerJoin) -> (game_player_manager), from (player,); target entity not found
unhandled input: (OnPlayerSpawn) -> (game_player_manager), from (player,); target entity not found
Sending full update to Client CaptainPRICE
Compressing fragments (2070 -> 1659 bytes)

[ERROR] lua/includes/util/javascript_util.lua:26: attempt to index a nil value
  1. unknown - lua/includes/util/javascript_util.lua:26
   2. OpenURL - [C]:-1
    3. Function - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua:10
     4. unknown - gamemodes/sandbox/gamemode/spawnmenu/creationmenu.lua:38
```

### Steps to reproduce
Edit:
I have managed to run into it the second time.
So, the script error pops up when I was joining a server. And I don't know how to reproduce it.

From server's console (yes, server is up2date, version 20161011):
![image](https://cloud.githubusercontent.com/assets/9789070/19396529/d9960d24-9243-11e6-9940-bbaddaa742a1.png)

**Comment by robotboy655** [comment]
Aand nothing happens when I follow your steps. Does this happen if you start your game with ```-noworkshop -noaddons```?

**Comment by CaptainPRICE** [comment]
> nothing happens when I follow your steps

Same. It did error for once, and now I can't reproduce it.

> Does this happen if you start your game with -noworkshop -noaddons?

Yes there was `-noaddons` in startup parameters.

I'm closing this issue until I (or somebody else) run into it the second time.

**Comment by CaptainPRICE** [comment]
Reopening as I have just run into it again...

**Comment by robotboy655** [comment]
Details, where are they?

**Comment by robotboy655** [comment]
Try Dev branch singleplayer or local multiplayer that you host and see if you can reproduce it.
