### ISSUE TITLE
gmad: flac files are not allowed in the whitelist

### ISSUE THREAD

**Issue by VictorienXP** [Facepunch/garrysmod-issues#2870]
Issue with the Garry's Mod Addon Creator 1.1:
The .flac files are not allowed in the whitelist. But we can play .flac files with sound.PlayFile()
I know that's not a big issue, I don't think many users will use .flac in workshop addon anyway... But it's still better than .wav to keep sound quality with lossless compression, so why not?

**Comment by Noiwex** [comment]
It's very strange that it's supported.

**Comment by VictorienXP** [comment]
Maybe not, I think sound.PlayFile() is using BASS and when I'm looking [here](http://www.un4seen.com/) there is the "BASSFLAC" add-on.
But yeah this is strange anyway... I don't really know how it works but it should maybe be another .dll file but as far as I know there is only bass.dll

**Comment by bmwalters** [comment]
@VictorienXP I don't believe the game currently supports playback of FLAC. I downloaded [this FLAC file](http://www.lindberg.no/hires/test/2L-106/2L-106_stereo_DXD-352k_MAGNIFICAT_04.flac) (**warning: 410 mb**), and when I ran:
```lua
sound.PlayFile("sound/testflac.flac", "", function(s, e, es)
  print(s, e, es) 
  if IsValid(s) then s:Play() end
end)
```

If GMod doesn't support playback of FLAC files, it doesn't make sense to allow them in addons, so this issue should be closed.
I got:
```
nil	41	BASS_ERROR_UNKNOWN
```

**Comment by Kefta** [comment]
There are BASS ALAC/FLAC modules, so I believe this should be a request for implementing those
