### ISSUE TITLE
Wildcards in ents.FindByModel are not working/implemented

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-issues#2872]
`Main` branch
`ents.FindByModel` is not being overridden by anything
`Windows` - Server 2012, 64-bit
Running this `serverside`

[ents.FindByClass](http://wiki.garrysmod.com/page/ents/FindByClass) allows you to pass arguments with wildcards like `*prop*` and find every `prop_physics` entity.

The wiki page for [ents.FindByModel](http://wiki.garrysmod.com/page/ents/FindByModel) states that it also supports wildcards, but that does not appear to be true. For example, spawning any of the various PHX hunter props and using `*hunter*` does not work. It only finds the ents when the full model path is provided.

If it's broken, fixing it would be nice. If it's not implemented to support wildcards, adding that support would equally be as nice.

**Comment by willox** [comment]
It looks like only suffix wildcards are supported (e.g. "prop_*"). I'm not sure that support for prefix wildcards would be very useful either.

**Comment by Mista-Tea** [comment]
Sorry for the late response on this.

From testing, prefix wildcards do work for ents.FindByClass. For example, ```print( #ents.FindByClass("*physics") )``` works properly since it's finding all of the prop_physics entities I have spawned out. If you're referring only to ents.FindByModel, then disregard this.

On the other hand, I am unable to use any wildcards at all on ents.FindByModel. Using the chair model
```models/props_c17/chair02a.mdl``` for testing:
- ```ents.FindByModel( "models/props_c17/chair02a.mdl" )``` works as expected
- ```ents.FindByModel( "models/props_c17/chair02a*" )``` returns nothing (suffix wildcard)
- ```ents.FindByModel( "*chair02a.mdl" )``` returns nothing (prefix wildcard)

Having the ability to use  wildcards (pre/suff/both) would be particularly useful. If you need convincing, consider an administration system that allows players/admins to clean up/freeze/select particular props based on their model only, without having to specify the entire model path. Being able to do something like ents.FindByModel( "*chair*" ), "*cube*", "*hunter*", etc could be nice.

**Comment by thegrb93** [comment]
You mean "*chair*", "*cube*", "*hunter*". A full string search for non-wildcard inputs would be slow.

**Comment by Mista-Tea** [comment]
I'm not sure I understand you. The examples I listed would allow you to find props like this:

ents.FindByModel( "*hunter*" ) ->
models/_hunter_/blocks/cube05x2x025.mdl
models/_hunter_/plates/plate2x8.mdl
models/_hunter_/blocks/cube075x075x075.mdl

ents.FindByModel( *cube*" ) ->
models/hunter/blocks/_cube_075x075x075.mdl
models/hunter/blocks/_cube_05x2x025.mdl

Just as examples. Leaving off the wildcards would not return anything (that is expected).

**Comment by robotboy655** [comment]
You can use ``` to prevent markdown, like so : ```*cube*``` fyi

**Comment by Kefta** [comment]
Related to https://github.com/Facepunch/garrysmod-requests/issues/1183.

**Comment by robotboy655** [comment]
It did not have wildcards, but will in the next update.
