### ISSUE TITLE
PreCleanupMap/PostCleanupMap only called on server

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#2875]
The hooks are marked as shared in the wiki but in my experiments only get called on serverside.

Nicely boosts the difficulty of hacking around bugs like #2874 though.

**Comment by robotboy655** [comment]
Actually only PreCleanupMap doesnt work on client

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/19442488/223507f6-9492-11e6-8e38-ea1218692737.png)
