### ISSUE TITLE
cl_defaultweapon

### ISSUE THREAD

**Issue by Velkon** [Facepunch/garrysmod-issues#2877]
Setting cl_defaultweapon to something not valid, then dying while holding a SWEP that uses SWEP:Deploy will cause it to not get called when you spawn back in. (Clientside)

This for some reason also breaks any sweps that use hl2 viewmodels, not allowing you to set anything related to bones. Until you switch to a different wep and back

**Comment by robotboy655** [comment]
I don't follow and I can't reproduce.

![image](https://cloud.githubusercontent.com/assets/3299036/19476501/3aa917e0-9542-11e6-858b-9b24fca438db.png)
