### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2878]
### Details
Spawned a light and removed it immediatly.

[ERROR] gamemodes/sandbox/entities/weapons/gmod_tool/stools/light.lua:187: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. UpdateGhostLight - gamemodes/sandbox/entities/weapons/gmod_tool/stools/light.lua:187
    3. Think - gamemodes/sandbox/entities/weapons/gmod_tool/stools/light.lua:207
     4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:175

### Steps to reproduce
spawn light and remove it immediatly.

**Comment by robotboy655** [comment]
Fixed
