### ISSUE TITLE
KeyValues wont update on manually setting the spawnflag keyvalue

### ISSUE THREAD

**Issue by WhiteKitty00** [Facepunch/garrysmod-issues#2879]
### Details
When using **ent:SetKeyValue()** to change the '_spawnflags_' keyvalues, the function **ent:GetSpawnFlags()** will return the correctly updated spawnflags, but **ent:GetKeyValues()['spawnflags']** still will return '_0_' as spawnflags, I did NOT test if it applies also on other keyvalues.

### Steps to reproduce
This code is ripped from a forum response I gave, giving you the example to read and write the flags:
(Relinking to pastebin cus formatting wont work here with the code markdown..)
[PASTEBIN](http://pastebin.com/MK7NRTDD)

### Version

**2016.10.11**

_Protocol version 24
Exe version 16.04.30 (garrysmod)
Exe build: 15:45:59 Sep 26 2016 (6533) (4000)_

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2520
