### ISSUE TITLE
Joining low tick servers keep this setting in singleplayer after disconnecting

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2881]
### Details

If you join a low tick server with like 12 ticks and then head to singleplayer, you have the exact same tickrate as the server you were playing on.
Influencing crouching, shooting etc.
### Steps to reproduce

Join a server with low tick.
Open up a listen server game.

**Comment by willox** [comment]
Yep

**Comment by mcNuggets1** [comment]
This is really annoying, isn't there any workaround to set the tickrate of the client? :c

**Comment by robotboy655** [comment]
This is fixed.
