### ISSUE TITLE
Starting a new listen server game, while one is already active bugs around

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2883]
### Details
This Error spams my console when creating a new listen server game, when there are already players on my currently listen server.
Host_Error: SV_CreatePacketEntities: GetEntServerClass failed for ent 1.

Does not appear always.

### Steps to reproduce
Start a listen server.
Invite a friend.
After he is authed, play a little bit.
Go to start a new game.
Start a new listen server.
Now you are thrown to home menu and this Error keeps spamming the console till the user disconnects.

**Comment by robotboy655** [comment]
#880
