### ISSUE TITLE
RPG creates on Equip a muzzleflash and spamming noise

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2884]
### Details
This actually should have been fixed in the latest update, but it is not.

### Steps to reproduce
Equip rpg in multiplayer.

**Comment by robotboy655** [comment]
It doesn't spam noises for me, it only plays the "laser on" and "laser off" sounds once as it should.

**Comment by mcNuggets1** [comment]
Oh sorry, enable thirdperson.

**Comment by robotboy655** [comment]
I am so sick of your BS tbh

**Comment by mcNuggets1** [comment]
I am sick of GMod Bug either.
