### ISSUE TITLE
TTT Ragdolls reset Skins/Bodygroups

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2889]
### Details
Explained above.

### Steps to reproduce
Edit bodygroup/skin, create a ragdoll

**Comment by robotboy655** [comment]
This is not a place to report TTT bugs.

Either send a Pull Request to fix the bug ( https://github.com/garrynewman/garrysmod ), or contact the gamemode author. ( https://github.com/garrynewman/garrysmod/tree/master/garrysmod/gamemodes/terrortown )
