### ISSUE TITLE
Typo in the Features page on the Website.

### ISSUE THREAD

**Issue by Ev1lbl0w** [Facepunch/garrysmod-issues#2890]
### Details
On the Features page (http://www.garrysmod.com/features/), there's a typo in the **Single & Multiplayer** section. In the second line, it reads "But playing with friend is **funner**". It should probably be "**funnier**.

I know you guys have way more important things to fix than a typo. Still, it's an issue, I guess...

**Comment by Bo98** [comment]
"Funnier" means "more humourous". I would've thought it is trying to say "more fun". I guess you could argue "funner" isn't officially a word in many dictionaries, though it is still used by people in informal contexts.

**Comment by Ev1lbl0w** [comment]
Well, since I'm not a native english speaker, I interpreted it as a typo. If it's indeed intentional, then I'll close the issue. Thanks @Bo98

**Comment by willox** [comment]
I fixed it
