### ISSUE TITLE
Problem with server!!Mising mapss!!!

### ISSUE THREAD

**Issue by moryhd** [Facepunch/garrysmod-issues#2892]
I have a problem with Gmod,i connect to the server and i appear a problem "mising map"pls fix this bug and to all servers... :(

**Comment by Kefta** [comment]
This is not a GMod bug; enable downloads in your Options -> Multiplayer settings and set your cl_downloadfilter to all

**Comment by moryhd** [comment]
No working..
On this server its not working 80.188.186.245:27019

**Comment by moryhd** [comment]
and HTTP ERROR 1 downloading in console..

**Comment by robotboy655** [comment]
The server is misconfigured and does have downloads set up properly.
