### ISSUE TITLE
Source Query Protocol returns wrong version string

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#2893]
### Details
The "version" field (https://developer.valvesoftware.com/wiki/Server_queries#Response_Format) from a source query has returned "16.04.30" for quite some time now. I thought this was gonna return the garrysmod version, which it obviously isn't. Is it broken or is it returning some internal engine version?

### Steps to reproduce
1) Run a source query on a gmod server.
2) Look at the return

**Comment by Bo98** [comment]
This might be because the steam.inf file hasn't been updating on new builds for a while.

**Comment by robotboy655** [comment]
It returns the steam.inf version, which infact is "16.04.30". Either we forgot to update it, or updating it was not necessary.
