### ISSUE TITLE
Garry's Mod Crash MACINTOSH

### ISSUE THREAD

**Issue by Ziksax** [Facepunch/garrysmod-issues#2895]
Bonsoir,

Je suis sur Mac, et lorsque que j'essaye d'aller sur un serveur DarkRP Garry's mod le jeu crash au sending client info voici le message d'erreur : http://pastebin.fr/48355
J'ai contacté Apple ils disent que le problème vien bien de garry's mod ! Aidez moi j'aimerais vraiment pouvoir jouer mais sa plante à chaque fois :/

Cordialement

Good evening,

I'm on Mac, and when I try to go on a DarkRP Garry's Mod server crash the game client sending info here is the error message: http://pastebin.fr/48355
I contacted Apple they say the problem vien well garry's mod! Please help me I would really like to play but his plant every time: /

cordially

**Comment by robotboy655** [comment]
##2206
