### ISSUE TITLE
P2P friends only doesn't work.

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#2896]
### Details
Whenever I load a P2P game up, none of my friends can join, regardless of whether the friends-only box is checked or not.

EDIT: Another thing is that even when the friends only box is unchecked before starting a game, I still get this in my console.
Only Allow Friends: friend list owner set to 76561198060651213 (you)!

### Steps to reproduce
Load up a P2P game and set the friends-only option to true (or tick the box if in GUI)

### Proof
Player Hoxton has joined the game
Client "Hoxton" connected (p2p:76561198068070226).
Dropped Hoxton from server (Sorry, the game could not verify your friendship because it is not properly configured. - Only Allow Friends)
] p2p_friendsonly 0
Player Hoxton has joined the game
Client "Hoxton" connected (p2p:76561198068070226).
Dropped Hoxton from server (Sorry, the game could not verify your friendship because it is not properly configured. - Only Allow Friends)

(Hoxton is my Steam friend btw.)

**Comment by willox** [comment]
This is an issue with the "Only Allow Friends" addon.
