### ISSUE TITLE
GMOD Server BUG - Engine Error

### ISSUE THREAD

**Issue by Mikkeltm** [Facepunch/garrysmod-issues#2897]
Hello GMOD Developer

i´m sitting with this huge problem on my gmod server and my host wanted me to report this issue to this site.

My server is a DarkRP server and around 1-2 hours  in average all players get disconnected back to desktop with this issue " "render.PopFilterMag underflow" " 

Photo of issue: http://www.noelshack.com/2013-39-1380006794-engineerror.png

As I told my support i didnt add any new mods / entities to the server so this is pretty weird

the issue started around Friday 16 o´cloak and im losing hole my player base.

Do you have any idea what could started this issue and sorry for my bad english! :)

Thankyou!

**Comment by robotboy655** [comment]
It's caused by one of your addons ( clientside addons )

**Comment by Mikkeltm** [comment]
How can that be possible I didnt add anything new to the server, and just happend after the update?
