### ISSUE TITLE
monster_bigmomma on event_killed not die

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2898]
### Details
So if you spawn a monster_bigmomma or try it on a map where well scripted and others like on a hl1 map or any mod map and you try kill him or give input "kill" it wont kill the npc.

### Steps to reproduce
Spawn a monster_bigmomma on sandbox use ur lua knowledge to give him an input "kill" then u will see the problem. Also if you try kill him. Nothing happen.

**Comment by Kefta** [comment]
Does the big momma ever actually die in the HL1 campaign?

**Comment by kem008** [comment]
it dies. But if in gmod not doesnt have that function. Can you guys add it? I wont use snpc or any kind of lua addon. Becuz it will override c++ stuff. Which not works fine on lua side. Also default entities will control bigmomma wrong.

**Comment by robotboy655** [comment]
It's by design, you are not supposed to be able to kill it on any map other than the one it is supposed to die on.

**Comment by robotboy655** [comment]
Even on the HL1:S map it doesn't actually die, it just plays an animation and gets removed.

**Comment by kem008** [comment]
Then I need to post a request.

**Comment by robotboy655** [comment]
Made it die in Sandbox ( HL:S map behavior unchanged ). It will not despawn on death tho.
