### ISSUE TITLE
Weapon select opens when holding +attack and scrolling with the Physgun

### ISSUE THREAD

**Issue by LuaTenshi** [Facepunch/garrysmod-issues#2899]
### Details
When holding down mouse1 or even mouse2 and scrolling (while having the physgun out), it will automatically go into the weapon select when you're not expecting it to. 

**If you don't have a prop/entity being held** with your physgun.

![Feels broken to me...](https://cloud.githubusercontent.com/assets/3096584/19990842/46d9b0e8-a207-11e6-99a0-02b44f17b8ec.gif)

Is this intended?
Wouldn't it be better for it to just not go into weapon select at all?

### Steps to reproduce
1. Hold down mouse1 (+attack) with the physgun selected.
2. Scroll (invnext, invprev).

**Comment by LuaTenshi** [comment]
@willox is already aware of this issue and he has said something about it here... #2873 
Sorry for the trouble. (A friend told me that the issue wasn't listed so I didn't bother searching first.)

**Comment by LuaTenshi** [comment]
Just to clarify when holding down mouse1, and scrolling the weapon does not automatically change like in #2873 but the weapon select still opens which feels broken, and just makes things uncomfortable.

**Comment by robotboy655** [comment]
Sounds normal and intended?

**Comment by LuaTenshi** [comment]
Would it be possible to add a toggle to change how people want the physgun to work? I'm pretty sure that it hasn't done this before.

**Comment by robotboy655** [comment]
No toggles. You can override the weapon selection with Lua to whatever your heart desires.

And I am pretty sure it always did this, its just it used to instantly switch the weapon and now it doesn't.

**Comment by LuaTenshi** [comment]
Not all servers allow running clientside lua. In fact most don't. That's why I asked for the toggle.
Also wouldn't having fast weapon switch on have the same effect as the bug that caused people to instantly switch weapons?
