### ISSUE TITLE
Dedicated Server refuses to download workshop collection

### ISSUE THREAD

**Issue by Bloodwave** [Facepunch/garrysmod-issues#290]
I've followed the directions as followed here: http://wiki.garrysmod.com/page/Hosting_A_Dedicated_Server

It collects the correct workshop items because it displays the name but when it attempts to actually download them to the server, the percentage slowly goes up and then it just sends "Download failed". I've retried at least 10+ times and I can't get it to budge and its really causing a issue for those who upload server content onto it.
I'm not completely sure if this is in Garry's hand but i'd love to at least get something done about it.

**Comment by czmate10** [comment]
Why is this closed? It's still an issue, and I don't think there should be a time limit of the download.
