### ISSUE TITLE
FIX ITS BUG PLS!!!

### ISSUE THREAD

**Issue by igorprovagos** [Facepunch/garrysmod-issues#2903]
Hello,i have big problem,after update Rust appeared bug.
My PC:
CPU: 8 GB
Processor: AMD FX(tm) - 4350 Quad-Core Processor 4.2 GHz
Windows: 7 64x
Video card: Nvidia Geforce 750 Ti.

My problem https://yadi.sk/d/4If0P3sEy7Lk2

**Comment by robotboy655** [comment]
This is not a place to talk about Rust.
