### ISSUE TITLE
EF_FOLLOWBONE enum missing

### ISSUE THREAD

**Issue by Thendon** [Facepunch/garrysmod-issues#2905]
**Details**
According to http://wiki.garrysmod.com/page/Entity/FollowBone the enum EF_FOLLOWBONE will be set. 
After using Entity:FollowBone(), Entity:GetEffects() is returning 1024 but EF_FOLLOWBONE  is returning nil. 
Also http://wiki.garrysmod.com/page/Enums/EF lists only enums up to 512 so I continued scripting with a const 1024 which seems working fine.

**Steps to reproduce**
`lua_run_cl print(EF_FOLLOWBONE)`  x)

**Comment by Kefta** [comment]
I believe this is a typo, and should say EF_BONEMERGE, instead. EF_FOLLOWBONE doesn't exist in the public codebase anywhere.

**Comment by willox** [comment]
That's no typo.

**Comment by Thendon** [comment]
yea EF_BONEMERGE does something different.
