### ISSUE TITLE
CUserCmd:SelectWeapon( NULL ) errors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2906]
A player is able to have a NULL active weapon; why can't it be selected? I am doing this in StartCommand.

**Comment by robotboy655** [comment]
You are not meant to be able to switch to a NULL weapon. There are NULL checks all over the place in the engine.

**Comment by Kefta** [comment]
Try removing all weapons.

**Comment by robotboy655** [comment]
I never said it is impossible, I said that it can't be done with the functions you want.
