### ISSUE TITLE
Gravity gun, no deploy delay

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2907]
### Details
You can instantly use the grav gun, wether deploy delay is at 0.001 or 100.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
test it out

**Comment by daunknownman2010** [comment]
This is natural behavior inherited from Half-Life 2: Deathmatch's code. The gravity gun was meant to be an instant pull-out weapon.

**Comment by mcNuggets1** [comment]
Why then is the grav gun influenced by sv_defaultdeployspeed convar?

**Comment by daunknownman2010** [comment]
Dunno, but I would assume Garry's Mod still has this:

**Comment by robotboy655** [comment]
I don't think this is worth changing.

**Comment by mcNuggets1** [comment]
Actually I want to set sv_deployspeed to 1.4 on my server.

**Comment by robotboy655** [comment]
Alright, fine.

Yes, this means that you can no longer grab AR2 balls that you yourself fire without increasing sv_defaultdeployspeed above the default of 4
