### ISSUE TITLE
http.Fetch crashes server if used too soon... ( note, this is AFTER gmod lua loads, addons loaded, base gm loaded, my gm loaded, then call http.Fetch == crash )..

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#2910]
### Details
I've been having some issues with GMod dev SRCDS crashing and I finally had a chance to look into it today ( It started after I updated my local SRCDS on the 3rd )... I Isolated it to PostAutoLoader after launching one and that being the last line which was called prior to crash. As of right now it is only used by my versioning system to check addon modules ( networking, etc.. ) version data to see if there is a new version available... It calls version:CheckForUpdates in a hook.Add which calls http.Fetch... 

I blocked http.Fetch and the server didn't crash... If I allow it during auto-refresh it works... This is just an issue during startup..

There was an issue with http not working in earlier versions of GMod when called really early which is why I set up the hooks to run it after Garry's Mod Lua, Addons, Base, Gamemode has all loaded - now the issue appears to be back even though it isn't called really early... if I add a timer.Simple( 0, function( ) ... end ); then it doesn't crash... ( and for some reason timer.Simple 0 didn't block it from running; I was prepared to rewrite the timer system to use os time instead of CurTime/RealTime/whatever... although I may still do this... )

### Steps to reproduce
Call http.Fetch in the SERVER realm after all of your GM files have finished loading...

I don't modify or redirect http.Fetch or any functions it may use... Adding timer.Simple 0 around it seems to resolve the issue but that, to me, is a hack / bandaid and if it broke for me then it is likely that others may experience this issue too...

**Comment by roboderpy** [comment]
Confirmed. On main branch it will write ```HTTP failed - ISteamHTTP isn't available!```, but on dev branch server just crashes

**Comment by roboderpy** [comment]
![2016-11-11_19-26_roboderpy dbot- -steamcmd](https://cloud.githubusercontent.com/assets/6339511/20215084/c216332e-a844-11e6-9d2f-cf882491b48b.jpg)
Is it a joke?
@robotboy655

**Comment by robotboy655** [comment]
yea, special for you
