### ISSUE TITLE
Gamecrash - render.PopFilterMag underflow

### ISSUE THREAD

**Issue by Mikkeltm** [Facepunch/garrysmod-issues#2912]
I made a ticket like this for 2 weeks ago and you told me that it was a addon. I was figuering out what it could be and my host said i could remove 10 at the time and see if it happend. Now im sitting here two weeks after it all startet. And I tryed everything removed my bought addons and even the Workshop addons 10 by 10.

The crash is working like this where there is around 35+ in the server after 15 min all game crash with engine error "render.PopFilterMag underflow".

I have no clue what to do like I told you i removed ALL the addons 10 by 10 and when they crashed  I ofc just re-added them to the server cuz then  I knew they wasnt the problem.

Please tip me up, and dont close the ticket so i can response to the ticket

Thanks alot!

**Comment by robotboy655** [comment]
It is a problem with one of your addons. If it wasn't - every GMod server would be affected.

**Comment by Mikkeltm** [comment]
Read my ticket man before you close it

**Comment by Bo98** [comment]
This isn't a ticket system anyway. It's a bug tracker.

Support can be found at http://support.facepunchstudios.com/ or http://facepunch.com/forums/16 (community)
