### ISSUE TITLE
HTTP() doesn't work on dev branch (server)

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#2914]
*Since i see that **no one** look into closed issues, i decided to post a new issue (when i should post stuff in old, **existsing and related** issue)*

As the title says HTTP() on server side now only printing one line into console ```HTTP failed - ISteamHTTP isn't available!```
![2016-11-11_19-26_roboderpy dbot- -steamcmd](https://cloud.githubusercontent.com/assets/6339511/20216968/32439a82-a850-11e6-83c3-1f984d0b7e3e.jpg)

**Comment by robotboy655** [comment]
3late
