### ISSUE TITLE
Bullets not always networking properly after October Update

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2919]
### Details
Weapons which have a frequency shooting rate sometimes doesnt transmit bullets in multiplayer game.
(Singleplayer is fine)

Tested on 66 tick servers with the mg_gun_base and m9k gun base and either TTT weapon base.
All have the same problem.
However it works better on 33 tick servers or below.

Before the October update everything was fine.

### Steps to reproduce
Start a 66 tick server without being the host of it.
Join the server.
Play around with some weapons.

Disclaimer: All weapons I have tested are derived from the m9k weapon base, the mg_gun_base and the TTT weapon base, however some weapons work flawless, like the mac10 of M9k.
But weapons like SR3M Vikhr, Tar 21, AS Val transmit nearly none bullets.

**Comment by Kefta** [comment]
Can you replicate it with weapon_base or any engine weapons?

**Comment by robotboy655** [comment]
Stop with shitty vague reports. What "does not transmit"? What does that even mean? Do bullets never shoot on the server? Or what?

**Comment by mcNuggets1** [comment]
Mkay, mister "I add bugs to an update", I will provide evidence then.

**Comment by robotboy655** [comment]
You should ALWAYS start with the evidence, how is that not obvious?

**Comment by mcNuggets1** [comment]
Because I got shit to manage. 
Anyways SERVERSIDE:
https://puu.sh/shaRW/3675bb9d25.png

-> NETWORK MESSAGES are send with MsgAll and CLIENT MESSAGES are just sent clientside.

**Comment by mcNuggets1** [comment]
The function ShootBullets only get called once after SWEP:CanPrimaryAttack() returned true.

**Comment by mcNuggets1** [comment]
That is on a listen server:
Everything works here.
https://puu.sh/shb1m/22556f78b9.png


HOWEVER I DO NOT UNDERSTAND HOW SHOOTBULLETS GETS CALLED 3 TIMES CLIENTSIDE

**Comment by Kefta** [comment]
That's because of prediction; print IsFirstTimePredicted and you'll see that it returns true only for the first clientside call. I'm still not seeing the issue with what you're describing; your first screenshot is extremely vague and has no timestamps or prints to see if it's in prediction

**Comment by mcNuggets1** [comment]
That is not the problem, the bullets are transmitting on the server, but not on the client.

**Comment by Kefta** [comment]
What does "transmit" mean in this context?

**Comment by mcNuggets1** [comment]
No muzzleflash, no Bullet hole, no Bullet case, no Effects at all, but serverside it does network properly.

**Comment by mcNuggets1** [comment]
Tried with IsFirstTimePredicted, that does not change anything besides fucking up Viewpunch

**Comment by robotboy655** [comment]
Feels like you are throwing around words you do not understand or something. The fact that English doesn't seem to be your first language doesn't help either.

Anyway, so as I can understand, you are simply not getting any? effects when shooting specific weapons? Not even view model animations? Is that it?

Can you replicate it, with default weapons? weapon_base? The flechette launcher? Or addons like this one:
http://steamcommunity.com/sharedfiles/filedetails/?id=180507408

So far it seems like a shitty weapon pack is your problem. i.e. bad prediction code ( if any ), bad accounting for lag.

And if you have "shit to manage", then manage your shit before trying to do something else, like posting here.

**Comment by mcNuggets1** [comment]
Before the october update everything worked just fine as it should, but as it came out, my own gun base, the m9k gun base and the TTT base began doing weird things.

https://puu.sh/shcxY/3fd958743c.txt

This is the code used for shooting.
Now tell me what is wrong with it, I nearly can ensure you, nothing is wrong with it.

It is funny, you say it is bad predicted, when I am just using self.Weapon:SetNextPrimaryFire(CurTime() + delay) as every weapon base either.

**Comment by Kefta** [comment]
if CLIENT and !game.SinglePlayer() then

There's an issue right there. SetEyeAngles should be done shared

**Comment by robotboy655** [comment]
You are not making your case any better by completely ignoring everything I say or ask. If you are not willing to cooperate, there's nothing I can do for you.

Prediction is far more complicated than using ```self.Weapon:SetNextPrimaryFire(CurTime() + delay)``` which is completely unrelated.

**Comment by mcNuggets1** [comment]
To cooperate, what should I do?

I am not that good in describing things in english, well, but everything I wants is to script some things in Lua, have fun with a nyan gun explosion and stuff, but these things just come out of the nothing.
I worked months on this weapon base and one update nearly destroyed the shooting function.

So accurate:
The animation using SendWeaponAnim is not working properly evertime.
When shooting 1 time 3 bullets appear.
The muzzleflash however works everytime.
The tracer networks properly either.
But the impact effect not.

**Comment by mcNuggets1** [comment]
It is not only my base, which broke, m9ks broke either.

And how ever it only does not work properly on 66 tick servers. 
I dont know honestly, I tried anything to just make this work again.

**Comment by Kefta** [comment]
I'll test your base later, but in the mean time, if you could narrow it down to a specific block of code or function that would cause these issues -- which I cannot replicate with my weapon base nor weapon_base, that would be great.

**Comment by mcNuggets1** [comment]
I am testing around already.
I couldnt find anything specific.

I built in prints for everything, but client fucking up with 3 times calls, making everything not that easy to read.

**Comment by Kefta** [comment]
Again, you can check IsFirstTimePredicted to only get the client to print once, but don't use it for anything else firing related

**Comment by mcNuggets1** [comment]
Ah right. Thank you.

**Comment by robotboy655** [comment]
So if these are your problems:
* The animation using SendWeaponAnim is not working properly evertime. - This is how Source engine works. You cannot play the same animations two times with it one right after another.
* When shooting 1 time 3 bullets appear. - As I said above, this is the telltale sign of a shit or rather nonexistent prediction on the weapon
* The muzzleflash however works everytime. - As it should, not a problem
* The tracer networks properly either. - As it should, not a problem
* But the impact effect not. - Again, if the bullets are not hitting the same place on client and server - it is normal.

All of this is how it always has been. Nothing was changed.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Prediction

Here you can read more about prediction and how to use/implement it.

**Comment by mcNuggets1** [comment]
Maybe I was just as always to intense aggressive about something not working and offending people again.
