### ISSUE TITLE
Barnacle keep eating player after death.

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2921]
### Details
So it happens if you cought by an npc_barnacle and dies during eating you but not barnacle killed u. He will keep eating you.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Find an npc_barnacle. When he cought you and starts eating you. Try die like suicide. Then you will respawn and see you keep losing HP.

**Comment by robotboy655** [comment]
Cannot reproduce. If a barnacle kills me ( HL2 one ), or if I kill myself, or if a combine or a zombie kills me, it just stops eating.

**Comment by kem008** [comment]
so u tried to eat urself with a npc_barnacle and used kill on console. Then it stopped eating u? For me and my friends still keep eating.
