### ISSUE TITLE
InputExplodeIn is it really exist? grenade_helicopter

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2923]
### Details
ExplodeIn Fire for me not working
[Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/npc_attackchopper.cpp)
Also the problem is we have a missing defintion on npc_attackhelicopter.cpp I think. `HL2_EPISODIC `which helps the bomb to explode on contact with npc_helicopter. Like in EP2. In gmod this never happens. Really annoying. Also `hl2_episodic `returns 1 on `ep2_outland_08 `where we kill npc_helicopter.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Just spawn a grenade_helicopter fire an input ExplodeIn and then you will see nothing happens. No matter if gives a param too.

**Comment by robotboy655** [comment]
Everything inside HL2_EPISODIC is safe to assume to be not working in GMod.

**Comment by kem008** [comment]
Then I will try to make an explosion effect to the helicopter. I have no other idea.

**Comment by robotboy655** [comment]
Should work in Dev.

**Comment by kem008** [comment]
Tested it working fine. You can see on the screenshot the explosion effect of the bomb. Also I'm using a custom explosion effect because original one from Valve so bad.
[Screenshot](http://i.imgur.com/yHdUmNv.jpg)

**Comment by kem008** [comment]
Can you tell me what are the changes now ep2_outland_08 crash my server if not on sandbox just on my gamemode.
