### ISSUE TITLE
Can't jump while pressing Reload and pressing W

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2924]
### Details
Explained above.

### Steps to reproduce
Hold RUN(W) and RELOAD(R) then try to jump.

**Comment by bigdogmat** [comment]
This is a hardware limitation of your keyboard and not the games fault.

**Comment by mcNuggets1** [comment]
Why should my keyboard do that, that does not maky any sense?!

**Comment by robotboy655** [comment]
Because that's how shitty membrane keyboards work.

Works properly for me with a full mechanical keyboard.

**Comment by bigdogmat** [comment]
> Why should my keyboard do that, that does not maky any sense?!

For manufacturers to save money they usually put sets of keys on the same circuit, this way they don't have to have as many.

**Comment by mcNuggets1** [comment]
Well, thanks for sharing these informations :)
