### ISSUE TITLE
Persistence is broken

### ISSUE THREAD

**Issue by glenlife** [Facepunch/garrysmod-issues#2925]
### Details
I'm sorry, it's that simple. On a Sandbox server with no addons, or with ULX, with sbox_persist set to 1 or 0 in server.cfg and live, all scenarios tested -- Persistence will NOT load on a server. Persistence will save the .txt file in data. But the server never loads the persistence .txt file.

Please fix this! It's so important, this is a core feature of the game that servers rely on!

### Steps to reproduce
Persist props/entities, they will save. But try to load the server up, .txt file may have info on persisted items but the server WILL NOT LOAD any of those items.

**Comment by DogsPajamas** [comment]
I'm having this same issue. Nothing works!

**Comment by robotboy655** [comment]
Yeah, server.cfg is too late to set Lua convars.

**Comment by GlenAnderson** [comment]
I hope this is a priority fix! :) It seems so simple and silly!

I can't do anything to change up the map for a cool server I wanted to do D: I can't really start it until this is fixed. ;( Thanks!

**Comment by glenlife** [comment]
Is a fix coming soon? Persistence is so important, this has been broken for so long now... :(

**Comment by robotboy655** [comment]
You can use autoexec.cfg instead for now. Make sure to not have the convar in server.cfg and have it only in autoexec.cfg

**Comment by robotboy655** [comment]
Fixed wit a little bonus http://i.imgur.com/jlV9hhQ.gifv
