### ISSUE TITLE
srcds on windows10 crash

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2927]
### Details
So I am using:
```
Protocol version 24
Exe version 16.04.30 (garrysmod)
Exe build: 17:06:53 Nov  7 2016 (6575) (4000)
```
Never happend before it somehow crash anymap no matter. Happens if I quit from the server and when I spawn first time. I got so much mdmp. I am using my own gamemode that never crashed before like this.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)
[crash mdmp](https://1drv.ms/u/s!Aj2YbK2FXOgzbrkVY3MGxBzVlNc)

### Steps to reproduce
Just use srcds on win10 try any gamemode. Use any map. I tested on sandbox also. Crash instantly on initial spawn. I didnt modified sandbox or base.

**Comment by robotboy655** [comment]
Cannot reproduce. Your server.dll and god knows what else is outdated. Reinstall/update your server.

AND STOP USING THIS BUGTRACER AS A SUPPORT WEBSITE BEFORE YOU ARE BANNED.

**Comment by kem008** [comment]
I updated my server. To test ur new fixes for the helicopter stuff. Maybe i reinstall lets see. Dunno why you dont want to support customers then. That sentence understandable.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help on the official forums or the support websites. This is a bug tracer. User errors are not bugs.

If you are using the Dev branch, FUCKING SAY SO.

**Comment by robotboy655** [comment]
You are crashing from using HTTP ( or http.Fetch ) in a timer.Create, but I could not reproduce it.
Reinstall your server and try again.

**Comment by kem008** [comment]
Thank you. You told me in the first time only use dev branch if I wanna use bug tracker. Thats why Im not posting it. But posted version.
