### ISSUE TITLE
Asigning keys to tables

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2928]
### Details
Whenever I try to insert a key into a table, we'll name it key 1, when key 2 existis, key 2 is moved to key 3, but key 1 to key 1.
Remains in key 1, key3 existing in an table.

Used the table.insert function for that.

https://puu.sh/slo9Y/48bf3eee61.png

### Steps to reproduce
first : table.insert(table, 1, 1)
then: table.insert(table, 2, 1)
-> bugged

**Comment by bigdogmat** [comment]
I don't understand what the issue is, also your explanation doesn't really make sense.

Anyways `table.insert` works exactly as it should for me,

![ss 2016-11-17 at 12 50 29](https://cloud.githubusercontent.com/assets/7156309/20397545/1dea3c96-acb8-11e6-923e-4287ed07b84c.png)

**Comment by mcNuggets1** [comment]
Do it exactly as I said.

**Comment by robotboy655** [comment]
Go to https://www.lua.org/demo.html and tell me its bugged.

**Comment by bigdogmat** [comment]
> Do it exactly as I said.

I did?

**Comment by mcNuggets1** [comment]
Well then I am again stupid as fuck.
