### ISSUE TITLE
2 bugs that i found out on 17th of November 2016.

### ISSUE THREAD

**Issue by 0nionManLV** [Facepunch/garrysmod-issues#2929]
### Details
So i was playing Gmod multiplayer in DarkRP and i found some bugs, and they are- invisible models even if i have addons and false effects for gravity gun. 

So i'll start with gravity gun- i open gmod and go into multiplayer server and when i take my gravity gun in hand it has not those "electricity" effects at the end of those 3 legs but it has cubes of textures as example from cardboard box, when i restart gmod it sometimes changes those effects to diffrent false texture cubes that aren't the little electricity lighting, once i even got wireftame effects so because of that i was kind of cheater cause i was able to see anyone with gravity gun out trough walls.         

Second bug is this invisible model bug. I was playing same DarkRP and i wanted to exchange some money on ATM but when i went to it i realized that ATM model is invisible, i can see only screen and text above it, i did check addons and that stuff and i know that it is not addon's problem cause i did see them before, that bug just randomly appeared. 

### Steps to reproduce
It happened randomly so there isn't way to reproduce it sadly.

**Comment by Kefta** [comment]
It's the problem with the server. You can fix the grav gun issues by reinstalling removing your addons or deleting your /garrysmod/download folder.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
