### ISSUE TITLE
game.GetSkillLevel returns garbage value in serverside Initialize hook

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2930]
I'm guessing the variable hasn't been set yet so C++ is assigning it to garbage memory. Tested in single-player on the dev branch. Also happens in PostGamemodeLoaded. InitPostEntity seems to be the first hook it is a valid result in.

**Comment by Jvs34** [comment]
Makes sense, it's affected by the gamerules entity which controls some hl2 stuff so I guess that should probably be mentioned on the wiki.

**Comment by Kefta** [comment]
Maybe make it error if the gamerules pointer is null?

**Comment by robotboy655** [comment]
Will return no value.
