### ISSUE TITLE
Z-filtering issue with .PCF Particles

### ISSUE THREAD

**Issue by MrGibb** [Facepunch/garrysmod-issues#2933]
### Details
.PCF particle effects exhibit a sort of Z-filtering issue when colliding with map geometry and props, causing jarringly hard edges. This affects ALL particles that use the PCF format, regardless if they were spawned by the map, by emitter tool, or any other method. 

![genericsmokepcf2](https://cloud.githubusercontent.com/assets/23620399/20466832/bcc9b48c-af37-11e6-89cb-36c726470ac4.jpg)

This only affects .PCF particle effects specifically. The default Half-Life 2 effects that do not utilize the PCF format (bullet impacts, explosions, muzzle flashes, etc), as well as Gmod's LUA particles work as expected.

### Steps to reproduce
Spawn PCF particle effect. The emitter tool's "Generic Smoke" effect is one that comes with Garry's Mod by default. The "Blood Impact" effect is another.
Place effect against and/or toward walls, floor, ceiling, or map props such as pipes and vehicles.
Observe.

**Comment by besenyei** [comment]
It also affects water effects.

water_impact.pcf (water_foam_01, water_foam_line_long and water_foam_line_short) exhibit the issue too.

--------------------------

### ep2_outland_01

Garry's Mod
![20180715212833_1](https://user-images.githubusercontent.com/39219459/42738314-b604bf8a-8879-11e8-9a23-917f85d021ea.jpg)

Half-Life 2: Episode 2
![20180715213252_1](https://user-images.githubusercontent.com/39219459/42738306-9b79c5b6-8879-11e8-8b5c-f212a44b6693.jpg)

**Comment by robotboy655** [comment]
This is due to our depth buffer.

This is what it looks like in HL2:
![](https://files.facepunch.com/rubat/1b0711b1/20190307203332_1.jpg)

And this is GMod:
![](https://files.facepunch.com/rubat/1b0711b1/20190307203528_1.jpg)

You will notice the ugly lines on the ground, thats the problem

**Comment by MrGibb** [comment]
> 
> 
> This is due to our depth buffer.

I'm guessing that means this is not worth the trouble to fix? I understand if that's the case.

**Comment by thegrb93** [comment]
No, that's just the explanation. I can't think of any reason not to make it like hl2, but maybe there is.

**Comment by robotboy655** [comment]
It it was changed in Gmod intentionally and I don't know why which is why i haven't reverted the change.

Maybe someone here knows why, as in, they are taking advantage of this change.

The change I am talking about is the depth buffer distance being changed from 192 to 8k

**Comment by robotboy655** [comment]
I have changed it back to 192 for the time being as I can't think of anything that would need this change to 8k, if anyone spots something off on Dev, please let me know.
