### ISSUE TITLE
Angle doesn't allow just one or two arguments

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2934]
For example, Angle(1) will error with:
[ERROR] lua_run:1: bad argument #2 to 'Angle' (number expected, got userdata)
  1. Angle - [C]:-1
   2. unknown - lua_run:1

By contrast, Vector(1) will return a vector with x=1, y=0, z=0.

**Comment by willox** [comment]
"got userdata"?

**Comment by robotboy655** [comment]
Now it does, even though I can't think of any scenario where you'd need this.
