### ISSUE TITLE
Issue with a flag npc/player

### ISSUE THREAD

**Issue by Shaieve** [Facepunch/garrysmod-issues#2936]
Hey in a friend's CC gamemode of HL2RP, he made a flag faction for us and its the Antlion Worker, whenever a guy shoots the venomous spits stuff it says administering antidote and stuff and that's a bug and the only way to fix it is by you guys, is there something someone can do to fix it

**Comment by robotboy655** [comment]
It's not a bug, it's part of the game that you can disable with Lua.

http://wiki.garrysmod.com/page/GM/HUDShouldDraw

**Comment by Kefta** [comment]
How do you disable the sound?

**Comment by robotboy655** [comment]
What sound?

**Comment by Jvs34** [comment]
What sound? The hev suit doesn't say anything in gmod other than the flatline sound.

**Comment by Kefta** [comment]
Nevermind, I'm thinking of the geiger radiation

**Comment by Shaieve** [comment]
Oh, thanks.
