### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2939]
### Details
[ERROR] lua/includes/modules/numpad.lua:108: attempt to index field 'keystate' (a number value)
  1. Activate - lua/includes/modules/numpad.lua:108
   2. unknown - gamemodes/sandbox/gamemode/player.lua:205

### Steps to reproduce
Straight out of my console.

**Comment by robotboy655** [comment]
One of your addons fucks it up.
