### ISSUE TITLE
widget_base calls render.DrawCube, a nonexistent function

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Facepunch/garrysmod-issues#2940]
`widget_base`'s `ENT:OverlayRender()` [calls `render.DrawCube`](https://github.com/garrynewman/garrysmod/blob/b3171137890829e2322e9c564b0d0baae9827255/garrysmod/lua/entities/widget_base.lua#L202). This function doesn't actually exist. This results in the continuous spam:

```
[ERROR] lua/entities/widget_base.lua:202: attempt to call field 'DrawCube' (a nil value)
  1. OverlayRender - lua/entities/widget_base.lua:202
   2. v - lua/includes/modules/widget.lua:138
    3. unknown - lua/includes/modules/hook.lua:84
```

This can be tested by running `ent_create widget_base` in the console.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/4f651b5df49fbe20f4bdbfb6754904df862c938c
