### ISSUE TITLE
lua_error_url 

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#2942]
For some reason, `lua_error_url ` will not send the POST command. I've tried multiple ways of coding and I've never received a POST message. I think it needs to be fixed. Unless its me.

**Comment by robotboy655** [comment]
Still works perfectly in my tests, make sure you have "s around your url, or the convar will only contain "http:".

![image](https://cloud.githubusercontent.com/assets/3299036/20796900/339db552-b7e1-11e6-964c-f005e2d8aee4.png)

**Comment by MrUnknownGamer** [comment]
My convar is fine, what I'm saying is that the POST command doesn't work. I tried it on my local server and on my hosted server.

**Comment by robotboy655** [comment]
It does work, I tested it on my local web server.

**Comment by robotboy655** [comment]
I will do some changes to it on the Dev branch soon, test after it updates.

**Comment by MrUnknownGamer** [comment]
Ok, tell me when to update to dev branch

**Comment by MrUnknownGamer** [comment]
Still not working with new update
