### ISSUE TITLE
"Fetching Subscriptions" bug (Doesn't mount addons)

### ISSUE THREAD

**Issue by PsychicSloth** [Facepunch/garrysmod-issues#2948]
I have recently installed Garry's Mod for Steam on a new computer and when I started the game, the main menu appeared with a "Fetching Subscriptions" bar that remained at 0 of (amount of addons)
 ![20161202160650_1](https://cloud.githubusercontent.com/assets/24376280/20869627/2f5279be-ba2b-11e6-9849-f41889a24fd1.jpg)

I checked my addons folder and nothing was there. 
![20161202155433_1](https://cloud.githubusercontent.com/assets/24376280/20869633/4307f18c-ba2b-11e6-86a1-d5172fe1ac1a.jpg)

I tried to go in-game to check if it would work and there were still no addons 
![20161202155242_1](https://cloud.githubusercontent.com/assets/24376280/20869636/58b01fa0-ba2b-11e6-86bf-29a236b87e62.jpg)

I did some research on this and found out this was a new feature that was in the 2016 October update, where the subscriptions would load on the main menu.

Please fix this bug :o)

*EDIT

I found the solution. I needed to set the date and time correctly. It worked when I did that.

**Comment by Bo98** [comment]
Check your console for any errors.

**Comment by Jake3231** [comment]
Just curious, is this Windows?

**Comment by daunknownman2010** [comment]
@Jake3231 Judging by how the fonts are rendered, it seems like Windows. Having used Garry's Mod on Windows, macOS and Ubuntu Linux, each operating system seems to display fonts a tiny bit differently. I could be wrong with this though.

As for the fetching subscriptions problem, the only way to see what's happening is in the console like @Bo98 suggested. There could be other factors causing this too such as the speed of your hardware or speed of your internet.

**Comment by MinIsMin** [comment]
@daunknownman2010 
You're right, fonts are rended differently on each system.

**Comment by azerty999** [comment]
same problem fix please

**Comment by PsychicSloth** [comment]
Found the solution. You need to set the date and time correctly.

**Comment by Bo98** [comment]
That would make sense. Though you would think GMod would've closed that progress box when it failed though.
