### ISSUE TITLE
server not autogenerating mountsdepot.txt

### ISSUE THREAD

**Issue by Kaosheaven** [Facepunch/garrysmod-issues#2950]
### Details
the server isnt auto generating the mountsdepot.txt so certain things arent able to be spawned namely certain source engine games entities

after grabbing the mountsdepot.txt from my client and adding it to the server then restarting fixes
running on linux version of server
### Steps to reproduce
install server
turn on after mounting content (hl2:ep2 primarily)
try to spawn one of the objects described below
you will notice you cant spawn the jalopy, the seat that is from hl2:ep2 content, hunters, and the flechette gun projectile models wont show

**Comment by robotboy655** [comment]
Even if it would auto generate it, you'd still need to manually edit it to tell the game that you have EP2 content mounted.

**Comment by neico** [comment]
"../hl2/ep2"? (or wherever it ends up using steamcmd, haven't checked lately)
There's not much validation the server can do beside checking for an existing folder and/or gameinfo.txt

alas, grab mount.cfg, check for entries and path, if path exists, add "1" to mountdepots.txt, if not fall back to standard expected path for the game, and if that still doesn't exist put "0" to mountdepots.txt

So the file could be pre-generated, if someone has their content folders outside of the normal structure (not next to "garrysmod") then you can still edit the mount.cfg afterwards, but for most cases the standard path should be sufficient.

Or simply ignore the mountdepots.txt on servers completely and only use the mount.cfg (with optional default paths as fallback)

Side note: the situation above actually seems to be described here: http://wiki.garrysmod.com/page/Mounting_Content_on_a_DS#/mountdepots.txt

Is IsMounted still broken in the way it's described there?

**Comment by robotboy655** [comment]
It's not broken, it returns whether a game is mounted or not, which is set by mountdepots.txt.

**Comment by robotboy655** [comment]
It is now auto generated on both clients and servers if it doesn't exist.
