### ISSUE TITLE
Spraying with toolgun

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2955]
### Details
If you spray on the ground while staying at that position, then the decal does not get created.

### Steps to reproduce
Spray in mp game on the ground while staying at that position.

**Comment by Kefta** [comment]
Pretty sure this has to do with the decal hitting the player instead -- I requested a filter be added to util.Decal a while back

**Comment by robotboy655** [comment]
Fixed
