### ISSUE TITLE
PlayerHurt not called on client

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-issues#2956]
There are now two possibilities:
Either, [this](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/shared.lua#L26-L31) is wrong and the function should only be server-side, or PlayerHurt isn't called on the client for some reason.
If the last thing is true, you should ask whether it's so important to provide this function to the client at all. Because there is also "player_hurt" as [Game Event](http://wiki.garrysmod.com/page/Game_Events).

Since I don't know which of the two statements is correct, I didn't make a pull request on GitHub to move it to the serverside file.

**Comment by robotboy655** [comment]
It's serverside only.

**Comment by Kefta** [comment]
@robotboy655 Can you move the function init only, then?
