### ISSUE TITLE
Toolgun traces sometimes go through entities which have a parent

### ISSUE THREAD

**Issue by ARitz-Cracker** [Facepunch/garrysmod-issues#2957]
### Details
* This does NOT happen with player:GetEyeTrace()
* The incorrect position only seems to be on the server
* I was running a listen server when I tested this

After creating this hook
```
hook.Add("CanTool","willox pls fix",function( ply, tr, tool )
	print(tr.HitPos)
end)
```
And spamming the color tool on a prop which has another prop as its parent, this happens!
```
S:-409.982605 -21.807470 -12287.968750
C:-89.182434 3.913074 -12246.241211
C:-89.182434 3.913074 -12246.241211
S:-409.982605 -21.807470 -12287.968750 // Woah!
C:-89.182434 3.913074 -12246.241211
C:-89.182434 3.913074 -12246.241211
S:-409.982605 -21.807470 -12287.968750 // Woah, again!
C:-89.182434 3.913074 -12246.241211
S:-89.176514 3.913548 -12246.240234
C:-89.182434 3.913074 -12246.241211
S:-89.176514 3.913548 -12246.240234
C:-89.182434 3.913074 -12246.241211
S:-89.176514 3.913548 -12246.240234
C:-89.182434 3.913074 -12246.241211
```

### Steps to reproduce
1. Create that hook in the shared space
2. Parents a prop to another prop using entity:SetParent()
3. Spam a tool on the child prop
4. Cry - this step should only apply to you if you're making an addon that requires the HitPos to always be accurate

**Comment by robotboy655** [comment]
Printout the tool argument, CanTool is a Lua hook and is not called from a single place. There are 4 constraint tools that call it manually for Prop Protection purposes from their Right Click functions.

**Comment by ARitz-Cracker** [comment]
Color is one of the tools where this happens, also materials, basically any tool that doesn't do much to the entity when you press primary fire.

**Comment by ARitz-Cracker** [comment]
I figured it out. Sometimes the trace goes _through_ the child entity

**Comment by ARitz-Cracker** [comment]
![here's a gif](http://puu.sh/sLbdq/243b870805.gif)

**Comment by ARitz-Cracker** [comment]
Here's a gif http://puu.sh/sLbdq/243b870805.gif

**Comment by thegrb93** [comment]
Is it possible for an addon to edit the hitpos from another hook?

**Comment by ARitz-Cracker** [comment]
debug.Trace confirms everything is squeaky clean. Besides, how would that cause the trace going through entities which have a parent?

**Comment by thegrb93** [comment]
It can happen if an addon does it's own trace using a filter with the hit entity of the original trace then stores the result on the table passed from the hook call.

I'm not sure how debug.Trace confirms that isn't the case. Can you explain how?

**Comment by thegrb93** [comment]
I didn't see there was a parent though. I can confirm that, I thought it was intended that traces don't hit parented entities because they don't have a physobj.

**Comment by ARitz-Cracker** [comment]
Whether or not it's intended, it should at least by consistent.

**Comment by robotboy655** [comment]
I cannot reproduce your inconsistency, using just SetParent and 2 props. Just do SetSolid( SOLID_NONE ) on all child props.

**Comment by ARitz-Cracker** [comment]
Here

The reason why this is kinda important to me is because I am making a tool where left clicking sets the parent and right clicking clears the parent
http://www.aritzcracker.ca/uploads/aritz/Garry%27s%20Mod%202016-12-12%2010_16_53%20AM.mp4
Again, I'm using a listen server

**Comment by robotboy655** [comment]
Well I can tell you right now that what you are trying to do should be impossible.

For some reason the physics object on client is not getting deleted or something, and it has nothing to do with tools specifically. You can fall through the parented props ( the "child" props ) and you can shoot through them as well.

**Comment by ARitz-Cracker** [comment]
It's not only the client. You can see that _sometimes,  (mostly when something behind the child prop ISN'T worldspawn) the trace does hit the child prop. (Visibly demonstrated with the color tool actually changing the color)
So, you can see that the server does think that the child entity's physobject exists. (in some conditions)
Obviously making the trace hit the child prop will be more convenient to me, and I think that _should_ be what happens. If I walk on a child prop, why shouldn't the trace hit it?
http://www.aritzcracker.ca/uploads/aritz/Garry%27s%20Mod%202016-12-12%2011_36_41%20AM.mp4

**Comment by robotboy655** [comment]
Something is bugged that makes the prop have bugged physics. This is not intended behavior, intended behavior is for the child props to have no physics at all. This is how it works in all Source engine games. Most likely the physics object is simply not destroyed properly for some reason. The only reason the prop changes color is because the color tool changes it clientside, since the trace hits the entity clientside.

**Comment by ARitz-Cracker** [comment]
Not really, tools that do serverside functions sometimes "work" aswell, and the trace hitting the child on the server is further confirmed by the console log. However, if child props are not supposed to be interacted with at all, I'll see if I can find a workaround to my problem.

**Comment by ARitz-Cracker** [comment]
Also, https://github.com/garrynewman/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/colour.lua#L44

**Comment by robotboy655** [comment]
Actually I am not completely correct. But this is not going to be changed/fixed.

According to this:
https://developer.valvesoftware.com/wiki/Entity_Hierarchy_(parenting)

You cannot parent physics based objects. So prop_physics is not meant to be able to be parented to anything. I tried the same setup in Half-Life 2 and same happens, except that bullets never hit the child prop_physics entities.
