### ISSUE TITLE
HL1-NPCs being Errors

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2958]
### Details
Install and mounted Half-Life 1.
Got NPCs in NPCs-Category, but showing up as ERRORs.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Told above.

**Comment by robotboy655** [comment]
You need Half-Life: [b]Source[/b].

**Comment by Jvs34** [comment]
Is it Half Life 1 or Half Life 1: Source? We only have support for the source version otherwise.

**Comment by mcNuggets1** [comment]
Half Life 1 normal, but why is it then mounted?

**Comment by kem008** [comment]
how the hell you mounted hl1?

**Comment by mcNuggets1** [comment]
I just mounted hl1 returning in npcs being spawnable as Errors.

**Comment by Kefta** [comment]
Your HL1 is corrupted, then

**Comment by mcNuggets1** [comment]
I started it to test it out, and it works properly.

**Comment by Kefta** [comment]
It's not

**Comment by mcNuggets1** [comment]
It is, if you have half-life 1 installied, I could mount it, I don't know why.

**Comment by robotboy655** [comment]
It is due to a bug. For example, try creating the folder ```Source SDK Base 2007``` in ```common/``` will allow you to mount 3 Source mods.
