### ISSUE TITLE
"BRANCH" returns "unknown"

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-issues#2959]
### Details
It seems like "BRANCH" only returns "unknown".

### Steps to reproduce
Execute this lua code: ```print(BRANCH)```

It doesn't matter if it is running clientside (CLIENT_DLL / MENU_DLL) or serverside (GAME_DLL).

![image](https://cloud.githubusercontent.com/assets/7966992/21076347/2b068dfc-bf29-11e6-9809-5bc44bae0818.png)

**Comment by willox** [comment]
it's only set to something else when you're on one of the specialised branches

**Comment by markusmarkusz** [comment]
Why isn't this documented? :c
The wiki just says:
> Returns the branch the game is running on.

**Comment by willox** [comment]
It's just a global that happens to exist. I don't see a reason why it even needs documentation to be honest.
