### ISSUE TITLE
Excessive Memory Usage by "Malloc" on OS X

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#2960]
### Details
Today I was playing on a LAN server, and it got to the point where when I would try to join the game, my Gmod client would just crash.  I suspect that it is due to the server using too much system memory.  I looked at the crash report, and it seems to indicate that the game was using about 2.8Gb of memory, which I think is too close to Gmod's 3 GB limit on OS X.  The issue is that "Malloc" is shown to be taking up a 1.6GB of memory alone.  I don't know exactly what that means in this instance, but I don't feel that it should be taking more memory than OpenCl.  This ties into my thought on memory management [here](https://github.com/Facepunch/garrysmod-requests/issues/860). 

VM Region Summary:
ReadOnly portion of Libraries: Total=343.5M resident=0K(0%) swapped_out_or_unallocated=343.5M(100%)
Writable regions: Total=2.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.2G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
ATS (font support)                33.5M       12 
ATS (font support) (reserved)        4K        2         reserved VM address space (unallocated)
Accelerate.framework               128K        2 
Activity Tracing                  2048K        2 
CG backing stores                  880K        3 
CG image                          16.0M        4 
CG shared images                   240K        8 
CoreAnimation                       36K        6 
CoreUI image data                  156K        2 
CoreUI image file                  192K        4 
Kernel Alloc Once                    4K        2 
MALLOC                             1.6G     1001 
MALLOC guard page                   48K       11 
MALLOC_LARGE (reserved)          186.8M        9         reserved VM address space (unallocated)
Memory Tag 242                      12K        2 
Memory Tag 249                     156K        2 
OpenCL                               8K        2 
OpenGL GLSL                        128K        3 
Process Corpse Info               2048K        2 
Stack                            109.3M       31 
Stack Guard                       56.1M       31 
VM_ALLOCATE                      211.2M      635 
__DATA                            29.1M      324 
__GLSLBUILTINS                    2588K        2 
__IMAGE                            528K        2 
__LINKEDIT                        83.6M       52 
__OBJC                            3648K       88 
__TEXT                           260.0M      299 
__UNICODE                          552K        2 
mapped file                      155.0M      151 
shared memory                     34.1M       13 
===========                     =======  ======= 
TOTAL                              2.7G     2678 
TOTAL, minus reserved VM space     2.5G     2678 

Model: MacBookPro12,1, BootROM MBP121.0167.B17, 2 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000

**Comment by Bo98** [comment]
Doesn't really say much, but there is a memory issue/leak with the macOS version, yes.
