### ISSUE TITLE
ConVar callbacks added without indentifiers cannot be removed

### ISSUE THREAD

**Issue by Tenrys** [Facepunch/garrysmod-issues#2961]
I mistakenly added a ConVar callback without an identifier, and noticed there were like 7 callbacks everytime I reran a script. So before adding an identifier I decided to remove them with cvars.RemoveChangeCallback, but the second parameter wont accept numbers (gotten with cvars.GetConVarCallbacks), so unless I restart the server they won't go away.

**Comment by robotboy655** [comment]
Yes, that is exactly why identifiers were added to cvars.AddChangeCallback
