### ISSUE TITLE
I go to start up the game and it starts then shuts down it gave me possible solutions but i tried them all and none of them helped

### ISSUE THREAD

**Issue by Dinogamma** [Facepunch/garrysmod-issues#2963]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by daunknownman2010** [comment]
Nothing useful here at all and this is not the place for support.

**Comment by robotboy655** [comment]
Make sure your Steam is not ran as Administrator or in Windows Compatibility mode.
