### ISSUE TITLE
timer.Exists() returns true even if the timer has been removed

### ISSUE THREAD

**Issue by ewauq** [Facepunch/garrysmod-issues#2964]
### Details
When I check if a timer exists or not with `timer.Exists()`, it returns _true_ even if the timer has been removed/destroyed.
I guess that `timer.Remove()` doesn't completely remove the timer. I don't know if it is a bug or a normal behaviour that I don't understand.

I know that I can check the timer timeleft to know if the timer is running or not, but this is weird to see that `timer.Exists()` still returns _true_.

### Example code

```lua
timer.Create("test_timer_1", 30, 1, function() print("test_timer_1 ended") end)
print(timer.Exists("test_timer_1")) -- returns true
print(timer.TimeLeft("test_timer_1")) -- returns 30

timer.Remove("test_timer_1")
print(timer.Exists("test_timer_1")) -- returns true
print(timer.TimeLeft("test_timer_1")) -- returns nothing
```

**Comment by robotboy655** [comment]
Fixed
