### ISSUE TITLE
Linux crash when returning Sequence ID that's less than zero for CalcMainActivity's second return parameter

### ISSUE THREAD

**Issue by gspetrou** [Facepunch/garrysmod-issues#2967]
If the second return parameter in CalcMainActivity is a number that's less than zero it will crash Linux servers.

```lua
hook.Add("CalcMainActivity", "Crash", function()
    return nil, -1
end)
```

**Comment by robotboy655** [comment]
I cannot reproduce it, on Ubuntu 12 SRCDS using Virtual Box.

And even then your report makes no sense because -1 is what it returns by default unless you are driving a vehicle.
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/animations.lua#L290
