### ISSUE TITLE
Materials Don't Work Every So Often

### ISSUE THREAD

**Issue by AnthonyFuller** [Facepunch/garrysmod-issues#2969]
### Details
When you put a material on something, it wont show up. Also with textscreens shows a 3x3 square because it is supposed to be invisible.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links) No crashes

### Steps to reproduce
IDK Maybe change video settings.

TO  FIX;

-dxlevel 95 in launch options ONLY ONCE

Remove that after the game has loaded then close it then add -windowed

Then it will fix

DO NOT REMOVE -WINDOWED

**Comment by robotboy655** [comment]
Caused by DirectX 8 mode, which is not officially supported. Stop using DirectX 8 in GMod.

**Comment by AnthonyFuller** [comment]
How do I stop using it?

**Comment by robotboy655** [comment]
Don't put dxlevel 8 into your command line properties. Upgrade hardware if necessary.

**Comment by AnthonyFuller** [comment]
I am hopefully getting a new graphics card for Christmas! So yeah!
