### ISSUE TITLE
SWEP switching during physgun primary fire

### ISSUE THREAD

**Issue by ElHyperion** [Facepunch/garrysmod-issues#2974]
### Details
While using the physgun's primary fire on anything that isn't a pickupable entity and scrolling through weapons (next / previous weapon keybinds), the weapon selection appears and interrupts the phys beam. If Fast weapon switch is enabled, the player immediately switches to another weapon/tool. This does not happen while manipulating an entity with the physgun of course.

The problem appeared in the previous version of GMod and hasn't been fixed in the December update. Before that, the weapon selection would never appear while holding the primary fire with a physgun, no matter what the user was aiming on.

### Steps to reproduce
Press and hold the primary fire button with physgun equipped while not aiming on any entity, and use the next or previous weapon buttons (scrollwheel)

**Comment by robotboy655** [comment]
I don't see how this is a problem/bug.
