### ISSUE TITLE
DarkRP / Star Wars crash

### ISSUE THREAD

**Issue by enviousity** [Facepunch/garrysmod-issues#2975]
Random crashes involving around 10+ people. Been happening since the update, and probably every 20 minutes - an hour.

Not sure what's causing it or how to reproduce it. It seems very randomised. 

[hl2_161216_crash_2016_12_20T6_53_33C0.zip](https://github.com/Facepunch/garrysmod-issues/files/663000/hl2_161216_crash_2016_12_20T6_53_33C0.zip)

**Comment by MinIsMin** [comment]
Duplicate from #2971. Same crash, more information at #2971.
