### ISSUE TITLE
IGModAudioChannel:Stop() invalidates object - Play does not restart

### ISSUE THREAD

**Issue by TehBigA** [Facepunch/garrysmod-issues#2977]
### Details
`IGModAudioChannel:Stop()` acts as if it is a `:Remove()` (which should also be added) invalidating the audio channel. The [wiki](http://wiki.garrysmod.com/page/IGModAudioChannel/Stop) claims that a stopped channel can be restarted with `IGModAudioChannel:Play()`, but this is not the case. Some actions (`IGModAudioChannel:GetState())`) performed upon a stopped audio channel returns:
```lua
Tried to use invalid object (type IGModAudioChannel) (Object was NULL or not of the right type)
```
and others just do nothing.

I believe the current stop functionality should be changed into a remove method and stop should do exactly as the wiki informs (stop the stream and reset it). Also this has inconsistent behavior as most methods do not produce a `Tried to use invalid object (type IGModAudioChannel) (Object was NULL or not of the right type)` error when the channel is invalid.

*This is reproducible with audio files on disk.*

### Steps to reproduce - With or without *noplay or noblock*
```lua
lua_run_cl sound.PlayFile('sound/music/hl2_song29.mp3', '', function(channel) _G.channel = channel end)
-- Sound should start playing
lua_run_cl channel:Stop()
--- Sound should stop playing
lua_run_cl channel:Play()
-- Does nothing
lua_run_cl print(channel:IsValid())
-- Prints false
```

**Comment by Jvs34** [comment]
Duplicate of #1497

**Comment by Kefta** [comment]
For the issue being open for two years, the wiki should really be updated

**Comment by TehBigA** [comment]
Whoops, thought I searched for it.

**Comment by TehBigA** [comment]
Closing since it's a duplicate.
