### ISSUE TITLE
Game attempting to load materials every frame. 

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-issues#2979]
### Details
Materials attempt to load every several frame causing extremely exessive IO use and loss of FPS in game. 

Servers of which have many missing materials are unplayable. 

### Steps to reproduce
Tell us how to reproduce the problem, step by step

Place a material your client doesn't have on any entity on the map and attempt to render it
Open up an executable which can monitor IO, filter for hl2.exe 

Watch: see every frame your client tries to load the file. 

Even showbudget shows that the filesystem is eating up resources.

![Budget](http://merp.ga/share/2016-12/2016-12-20_17-50-36.png)

And my ProcMon shows the following 

![Procmon](http://merp.ga/share/2016-12/2016-12-20_17-52-00.png)

(do note that i've only included ONE directory for this, when a missing material tries to load every frame, it is checking the following

+ 1 garrysmod root
+ how many number of filesystem addons you have
+ how many number of games you have mounted

)

**Comment by robotboy655** [comment]
So basically a dupe of https://github.com/Facepunch/garrysmod-issues/issues/511

**Comment by TheFreezebug** [comment]
@robotboy655 Not specifically a dupe. #511 causes instantaneous lag (a complete freeze) until the material system figures out that those files don't exist.

This is different, and instead is causing incredible frame lag with literally hundreds of thousands of read attempts per minute (Making the difference from #511 that the material system never figures out that these don't exist, and keeps trying to load them) , this has only been an issue with the recent update.

This can be really harsh on harddrives that aren't rated for many consecutive hours of read / writes back-to-back.

**Comment by robotboy655** [comment]
Why are you blaming it on the new update? There wasn't even anything remotely relevant to the material system changed.

**Comment by robotboy655** [comment]
To be clear, we are talking about SetMaterial() on entities? Not anything else?

**Comment by TheFreezebug** [comment]
@robotboy655 That's why i'm confused about it. I've only experienced this, and have had players complain about it since the new update. 

It appears to only be caused by :SetMaterial upon further investigation.

**Comment by robotboy655** [comment]
So it will do that only if you run SetMaterial() every frame, something you should never do anyway.

**Comment by TheFreezebug** [comment]
Doesn't seem to be it, I checked all of my draw calls and none were calling SetMaterial every frame. 

Quick update: It seems to have suddenly stopped with no explanation. Every player on every server that this was experienced on has reported it suddenly stopping.. what the actual fuck. I/O calls are down as well.

I'll re-open this if this spontaneously appears again.

**Comment by robotboy655** [comment]
Maybe one of your server devs did something stupid around the update dropped and undid it now?

**Comment by TheFreezebug** [comment]
No, that doesn't seem to be it. I control all of the addons on the server and have checks for them. It seems that it is exhibiting this behavior just by the engine itself -- nothing to do with SetMaterial or Material. 

I detoured both and it doesn't seem to be being called at all 

![TextureLoading](http://merp.ga/share/2016-12/2016-12-22_20-16-15.jpg)

I detoured it both on server and client, yet no avail.  It began exhibiting this behavior again.

**Comment by robotboy655** [comment]
Why is there always whitespace and special symbol for you in the material path?

Can you collect a few material paths and post them? Are there any patterns to it? What models/entities use those materials in the server?

**Comment by TheFreezebug** [comment]
The paths seem to be surrounded in " [ ]".

Example 
materials/ [models/props/mytexture.vmt]  

And sure, when I catch it happening again I can capture some paths for you.

**Comment by TheFreezebug** [comment]
Here you go. 

Here's a stack leading up to one of the attempted file searches.

http://merp.ga/share/2016-12/stack.CSV

and here is a log file of several paths

http://merp.ga/share/2016-12/LOG.CSV

**Comment by robotboy655** [comment]
Some addon does uses tostring on IMaterial object incorrectly ( Returned by Material() function ). it should be using mat:GetName().

**Comment by TheFreezebug** [comment]
![nope](http://merp.ga/share/2016-12/2016-12-23_16-31-37.png)

Welp. That was it, thanks for your support through all of this. I'd never have figured that out.
