### ISSUE TITLE
Favorite servers aren't showing up since update

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2983]
### Details
Since update my favorite servers with less player counts aren't showing up till I refresh the list.

### Steps to reproduce
Favorise some servers.

**Comment by Bo98** [comment]
Possibly a regression with https://github.com/garrynewman/garrysmod/commit/b3171137890829e2322e9c564b0d0baae9827255 not taking `type` into account.

**Comment by mcNuggets1** [comment]
Any news?

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/181d0b8f626006871f98cf0fb2d95487694d880b
