### ISSUE TITLE
LocalPlayer():IsAdmin and LocalPlayer():IsSuperAdmin functions are nil inside spawnmenu.AddContentType

### ISSUE THREAD

**Issue by philxyz** [Facepunch/garrysmod-issues#2984]
As part of my prop protection system, I build my own spawn menu for models.

I need to check whether the local player is admin (on the client) so as to set up the GUI for allowed / disallowed props.

Recently however, I'm having the problem described in the title - and I'm not sure exactly which version this started to not work, but I'm pretty sure it was in one of the last two stable releases.

`spawnmenu.AddContentType("model", function(container, obj)
        local shouldNotThrowError = LocalPlayer():IsAdmin()
        print("value is: " .. tostring(shouldNotThrowError))
end)`

I am calling this from cl_init.lua

Nor does it work if I call IsAdmin() outside the call to AddContentType and refer to it from inside.

**Comment by thegrb93** [comment]
I don't think the NWVar for IsAdmin is set until the player is authenticated.

**Comment by philxyz** [comment]
Thanks - weird how it was working before then. I'll try adding the content type to the spawn menu at that point. I hope that's not too late to register it, though.

**Comment by philxyz** [comment]
OK, I sorted the problem by checking to see if the function is nil at that point. I'll close this since I was able to work around it. It worked before - but whether it should have or not is another question.
