### ISSUE TITLE
My addons dont have icons and not working!!! HELP PLEASE!!!

### ISSUE THREAD

**Issue by huisobaki123** [Facepunch/garrysmod-issues#2985]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by Kefta** [comment]
Post here with actual code excerpts and more details: https://facepunch.com/forumdisplay.php?f=16
