### ISSUE TITLE
SteamCMD "Updating workshop items for app 4000, (0/0 bytes)

### ISSUE THREAD

**Issue by Tyler13700** [Facepunch/garrysmod-issues#2986]
I am updating my garry's mod server with SteamCMD, I type `app_update 4000 validate` in, and it updates fine, until it gets to the workshop, then it says its 0.00% complete, and it has 0 bytes complete, 0 bytes to download. I dont know why this is happening, I could run it fine before I added addons into it. Please help.

This basically just happens for me when I have about 180 addons into my steamCMD server. It just gives me and endless list going on forever.

**Comment by robotboy655** [comment]
SteamCMD is not a product of Facepunch.

Garry's Mod does not use SteamCMD to install workshop addons onto dedicated servers.

**Comment by Tyler13700** [comment]
"closed" I didn't know the admins were as aggressive as the steam community. Where can I ask for a valid bug on steamcmd?

**Comment by Kefta** [comment]
Steam support
