### ISSUE TITLE
Couldn't include file 'cl_init.lua' (File not found)

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-issues#2989]
I've been plagued by an intermittent bug throughout the history of my gmod career.

Setup a basic gamemode.
Make sure there is a client side lua file.
Edit the file to include some basic VGUI or anything really just as long as it's not blank.
Now go ahead and start up a dedicated server running this gamemode.
Join the server and make changes to the file.
Have another player join and the console prints out:
Couldn't include file 'cl_init.lua' (File not found)
It only happens to NEW connecting clients though, clients that were already connected before you made changes to the file won't experience the issue.

What the?

At first I assumed I had an error in the code however the code runs just fine for clients who were already connected before you made any changes to the file.

Some kind of CRC check error with lua refresh?

It's EXTREMELY frustrating as I like to edit my gamemodes while players are playing so I can receive immediate feedback and this issue requires a server restart for those newly connected players to get the file.

**Comment by robotboy655** [comment]
Should be fixed in Dev
