### ISSUE TITLE
Env_screeneffect missing effects needed to work.

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-issues#2990]
### Details
When placing a [env_screeneffect](https://developer.valvesoftware.com/wiki/Env_screeneffect) and attempting to start the effect with StartEffect 8, it will report in the console saying it can't find the screen space effect that was selected, and do nothing, this also happens in all the EP1/2 maps.  I have EP1 and EP2 mounted, and no addons active.

EDIT: I also tested the env_screeneffect in my map in EP2, and it worked there.

This is what it says when I attempt to start the effect:
"Could not find screen space effect [Effect Name]"

Any effect type you select makes the console say it's missing, these are all the effects that are missing:
episodic_stun (Advisor Stun)
episodic_intro (Intro Blur)
ep2_groggy (Groggy Vision)

### Steps to reproduce
There are two ways you can reproduce it.

1. You can go into any EP1 or EP2 map where scenes with the Advisors are at, when the visual effects start the console will report the error I mentioned above.

2. You can create a box map with just an env_screeneffect and info_player_start in it, and do "ent_fire env_screeneffect StartEffect 8", this will start the effect and make it last for 8 seconds, as soon as you enter it into the console, it will report the error I mentioned above.

**Comment by robotboy655** [comment]
Fixed
