### ISSUE TITLE
Strange NW2Vars behaviour

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#2992]
### Details
It appears that at some point of autoreload/adding vars its messing up the expected results.

### Steps to reproduce
1. The test code has to be placed at entities\weapons\weapon_nwvar2.lua
2. Execute: lua_run Entity(1):StripWeapons() Entity(1):Give("weapon_nwvar2")
    Result: Ok all good
3. Change "TargetAng" to something like "TargetAng22222222",
    Result: Ok all good
4. Execute: lua_run Entity(1):StripWeapons() Entity(1):Give("weapon_nwvar2")
    Result: Ok all good
4. Change "TargetAng2222222" back to "TargetAng".
    Result: Ok all good
5. Execute: lua_run Entity(1):StripWeapons() Entity(1):Give("weapon_nwvar2")
    Result: Value mismatch: 0 ~= 100000

NOTE: It sometimes takes a few more runs to get there, I just keep renaming the first two nwvars back and forth and keep executing strip + give, it will trigger it at some point.

### Test code 
```lua
if SERVER then
	AddCSLuaFile()
end

SWEP.PrintName = "Test"
SWEP.Author = "Test"
SWEP.Instructions = ""

SWEP.Spawnable = true
SWEP.AdminOnly = true

SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = -1
SWEP.Primary.Automatic = true
SWEP.Primary.Ammo = "none"

SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = true
SWEP.Secondary.Ammo = "none"

SWEP.HoldType = "physgun"
SWEP.Weight = 5
SWEP.AutoSwitchTo = false
SWEP.AutoSwitchFrom = false
SWEP.UseHands = true
SWEP.ViewModel = "models/weapons/c_superphyscannon.mdl"
SWEP.WorldModel = "models/weapons/w_Physics.mdl"

if CLIENT then
	SWEP.Slot = 0
	SWEP.SlotPos = 2
	SWEP.DrawAmmo = false
	SWEP.DrawCrosshair = true
	SWEP.DrawWeaponInfoBox = false
	SWEP.BounceWeaponIcon = false
	SWEP.ViewModelFOV = 54
end

local TEST_VAL = 100000
local TEST_VAR = "EffectState"

function SWEP:Initialize()
	if SERVER then
		self:SetNW2Vector("TargetPos", Vector(0, 0, 0))
		self:SetNW2Angle("TargetAng", Angle(0, 0, 0))
		self:SetNW2Bool("Holding", true)
		self:SetNW2Entity("AttachedEnt", nil)
		self:SetNW2Int(TEST_VAR, TEST_VAL)
	end
end

function SWEP:Think()
	if CLIENT then
		local val = self:GetNW2Int(TEST_VAR)
		if val == TEST_VAL then
			print("Ok all good")
			self.Think = function() end
		else
			print("Value mismatch: " .. val .. " ~= " .. TEST_VAL)
			self.Think = function() end
		end
	end
end
```

### Additional info 
![hl2_2016-12-29_10-35-32](https://cloud.githubusercontent.com/assets/5415177/21540895/e65f572c-cdb2-11e6-81ad-28d68a7be192.png)

**Comment by willox** [comment]
This should be fixed for servers on the dev branch. There are potentially other bugs.
