### ISSUE TITLE
Two problems with env_projectedtexture and env_screeneffect only effecting skybox

### ISSUE THREAD

**Issue by Matty-64** [Facepunch/garrysmod-issues#2993]
### Details
Ok, so the first issue with it is very minor, but I thought I'd just mention it here anyway, in the env_projectedtexture's spawnflags tab, there is a spawnflag listed as "Enabled" which, simply said, doesn't work, when you uncheck it, it doesn't turn off the projected texture when it spawns as seen [here](http://steamcommunity.com/sharedfiles/filedetails/?id=828676419), no errors in the console about it either.  I looked into the FGD, and the spawnflag's number is 1 if that helps.

The second issue with the env_projectedtexture is when you turn off the shadows of the projected texture, and turn it off and then back on, you can no longer enable the shadows on it, this also happens if you have the shadows disabled by default, and you can't enable the shadows again until you turn the projected texture off and then on again.  It's a odd bug, but it makes it hard to optimize your map when you have to turn projected textures on and off.

And lastly, the bug with env_screeneffect, I tested this in the development build, so I don't know if this is final behavior or not, but just in case, the title pretty much says it all, env_screeneffect only effects the skybox, and very faintly shows on other geometry, which isn't how env_screeneffect works in EP1 and EP2, there is however no errors in console about it this time.

I made a video showing all three of these bugs in the order I listed them in, which can be found [here](https://youtu.be/sUIqZrJXsDo).

### Steps to reproduce
When I was testing my map, I came across the bug I mentioned yesterday, so I created a small test map to see the problems more clearly, and I used that map to reproduce the bugs I mentioned above, the map can be downloaded in BSP and VMF format [here](https://github.com/Facepunch/garrysmod-issues/files/676831/Projected_Test_Map.zip).

**Comment by Kidnation** [comment]
Just tested it in Half-Life 2, and the same problems happen there as well, all be it a little glitchy.

**Comment by robotboy655** [comment]
env_screeneffect is fixed on all versions and I am afraid changing env_projectedtexture's spawnflag behavior will break existing maps that incorrectly expect it to work like it does now, so not sure what to do about it.

The shadow toggling issue should be fixed on Dev beta branch and in the next update.

**Comment by Kidnation** [comment]
Awesome.  My only idea for the spawnflag issue is to make a new spawnflag or keyvalue that can be checked/enabled to start the projected texture off instead of on.  I don't know of any Source games off the top of my head that use any spawnflag but 1, but a new keyvalue would probably be best for compatibility.
