### ISSUE TITLE
Panel:GetChild( 0 ) crashes when panel does not have children

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-issues#2997]
### Details

Call `GetChild( 0 )` on any panel without a child to crash the client. This crash does not occur with indexes above 0. Normally the index starts at 1 on a table, but [the wiki tells otherwise.](http://wiki.garrysmod.com/page/Panel/GetChild). I think it should return `nil` instead, just like it does for any other index.

I do not think this has anything to do with the OS, but I have been able to reproduce this on both Windows 10 and Ubuntu 16.04 LTS.

### Steps to reproduce
`lua_run_cl panel = vgui.Create( "Panel" ) panel:GetChild( 0 )`

**Comment by robotboy655** [comment]
Fixed in Dev
