### ISSUE TITLE
Player.SelectWeapon calls Deploy and Holster outside of prediction

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3000]
With Deploy and Holster being predicted hooks, it would make sense for Player.SelectWeapon to queue the weapon to switch on the next command, but that is not the case.

Weapon code (identical for both classes):
```
SWEP.Spawnable = true
SWEP.Category = "Test"

function SWEP:Deploy()
	print("(" .. self:GetClass() .. ") Deploy. Command:", self:GetOwner():GetCurrentCommand())
	
	return true
end

function SWEP:Holster(p)
	if (p ~= self) then
		print("(" .. self:GetClass() .. ") Holster to " .. p:GetClass() .. ". Command:", self:GetOwner():GetCurrentCommand())
	end
	
	return true
end
```

Switching with UserCmd.SelectWeapon/weapon selector:
```
(weapon_test2) Holster to weapon_test. Command:	userdata: 0x595caa68
(weapon_test) Deploy. Command:	userdata: 0x595cb7a0
(weapon_test) Holster to weapon_test2. Command:	userdata: 0x596789a0
(weapon_test2) Deploy. Command:	userdata: 0x596782d0
(weapon_test2) Holster to weapon_test. Command:	userdata: 0x5916b958
(weapon_test) Deploy. Command:	userdata: 0x5ba7e3f0
```

Switching with Player.SelectWeapon/spawn menu:
```
] lua_run Entity(1):SelectWeapon("weapon_test2")
> Entity(1):SelectWeapon("weapon_test2")...
Player:GetCurrentCommand called outside of command/prediction
(weapon_test) Holster to weapon_test2. Command:
Player:GetCurrentCommand called outside of command/prediction
(weapon_test2) Deploy. Command:
] lua_run Entity(1):SelectWeapon("weapon_test")
> Entity(1):SelectWeapon("weapon_test")...
Player:GetCurrentCommand called outside of command/prediction
(weapon_test2) Holster to weapon_test. Command:
Player:GetCurrentCommand called outside of command/prediction
(weapon_test) Deploy. Command:
```

Player.GetCurrentCommand is still the only way to test if the code is in a predicted state. See https://github.com/Facepunch/garrysmod-requests/issues/887 and https://github.com/Facepunch/garrysmod-requests/issues/888

**Comment by Jvs34** [comment]
You won't get any actual prediction with something initiated by the server like this. 
Unless the new behaviour of SelectWeapon makes it so it queues the weapon to be switched during a prediction frame on both client and server, the solution that will work the best (without prediction) will be to make the function use CallOnClient as a workaround.

I highly doubt you'll get what you're asking for here.

**Comment by Kefta** [comment]
Then I guess this is a request for SelectWeapon's behaviour to be changed to queue the switch since there's no way to tell when a method is called in prediction or not.
