### ISSUE TITLE
Error Message on d1_town_02a

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#3009]
### Details

It happens on HL2 map where Grigori shoot the propanetanks and then they explode. After this server printing this error all the time. Not causing any bug. But really annoying error spam.
```
!! ERROR: bad input/output link:
!! env_fire(propanetanks_1_fire_a,Extinguish) doesn't match type from <null>(<null>)
```
map: `d1_town_02a`

Just posted this issue not should be prio but you should know about that.
(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Go to this map `d1_town_02a` then wait for the event when Grigori shoot these propane tanks.

**Comment by robotboy655** [comment]
![Uploading image.png…]()

Exact same thing happens in Half-Life 2 -> Not a Gmod problem.
