### ISSUE TITLE
Lerp_Hermite may produce whacky results

### ISSUE THREAD

**Issue by daunknownfox2010** [Facepunch/garrysmod-issues#3010]
### Details
So, this "bug" also happens on other Source 1 (2013) games. On Garry's Mod, it is not as bad. Basically, after some time of playing, the models will begin to twitch strangely and it's just visually annoying. Note: fps_max has affect on this bug so play around with low and high values till you get it!

Video of the Garry's Mod version of the bug: https://youtu.be/mKY-9KifL6E
Issue reported on Source-SDK-2013 (Includes video of the HL2MP version of this bug): https://github.com/ValveSoftware/source-sdk-2013/issues/404

### Steps to reproduce
Just stay around on a game. Even just host a LAN game with a few bots like I did and play around with fps_max values. Waiting is what causes this bug to occur, so patience!

**Comment by mcNuggets1** [comment]
I just had this bug 5 minutes before ;)

**Comment by kpjVideo** [comment]
Perhaps an issue with a loss of single float precision?

**Comment by daunknownfox2010** [comment]
So we found the culprit. There is an issue that involves **Lerp_Hermite** which causes interpolated pose parameters to have visual issues (such as twitching like crazy). The reason it does this is because it's unreliable and will eventually result in a massive overshoot and/or NaN. The issue was reported in the Source SDK 2013 repository and a fix was found, as seen here: https://github.com/ValveSoftware/source-sdk-2013/issues/404#issuecomment-405042224
