### ISSUE TITLE
Some ragdolls becomes prop_physics! 

### ISSUE THREAD

**Issue by FrankelNorman1999** [Facepunch/garrysmod-issues#3012]
**Hey, guys, I have a trouble.**

When I spawn some ragdoll (like on pic) they becomes a prop - no rig, no face\eye posing.
![image](https://cloud.githubusercontent.com/assets/25014250/21777789/84f9075a-d6b1-11e6-8809-b4933094d23a.png)

I have a Steam-version game, Windows 10, and living in Russia
Tell me, what's wrong, please

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

**Comment by kem008** [comment]
is it not crazy physics? u not get error on console?

**Comment by Kefta** [comment]
Crazy physics removes entities, not change them

**Comment by kem008** [comment]
custom collision can do this and crazy phsics can appear on console.
