### ISSUE TITLE
Models Disappear, Shadow spam for no reason.

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#3013]
### Details
On first time you spawn you can get this bug like see no models brushes. Makes the game awesome.
Also If you have ever played on big maps like hl2 maps on canals or coast maps you will like it. Randomly shadow spammed on ground. Reason is unknown. No message about it on console.
(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Try spawn on a server you will get model invisible bug. I saw that happens on Source Engine 2013 games. Valve stopped working on it. Only way to fix this model disappaer bug is to rejoin by not developer :D. :D
Shadow bug just play on big maps. With many players.

**Comment by robotboy655** [comment]
Assuming I understood the issue correctly, its a problem with renderables list overflowing.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1968

**Comment by besenyei** [comment]
Even though he didn't explain it properly, he is correct in a way.

Too many shadows rendered on the surface can cause an overflow.

> CUtlLinkedList overflow! (exhausted index range) (65535)
> CShadowMgr::AddShadowDecalToSurface - overflowed m_ShadowDecals linked list!

**Comment by thegrb93** [comment]
spamming citadel/dog npc models is one known big cause

**Comment by besenyei** [comment]
I know the reply is deleted, but that issue regarding npc_dog is because of it's ropes.

Spawning 10 of them in HL2 causes an overload in "CRopeManager::AddToRenderCache count to large for cache!"

In Garry's Mod, Client Animation spikes a lot, disabling rendering for the ropes cuts this down a lot.
