### ISSUE TITLE
Random crashing at spawn

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3014]
When I join with the dev branch sometimes it crashes on spawn. No idea whats causing it.

[hl2_170109_crash_2017_1_10T22_8_44C0.zip](https://github.com/Facepunch/garrysmod-issues/files/697514/hl2_170109_crash_2017_1_10T22_8_44C0.zip)

**Comment by robotboy655** [comment]
Does this happen without multicore enabled?

**Comment by ZehM4tt** [comment]
Nope, same thing.

**Comment by robotboy655** [comment]
Post a crash log without mcore

**Comment by ZehM4tt** [comment]
mat_queue_mode was set to 0, not sure what you want.

**Comment by Bo98** [comment]
gmod_mcore_test 0

**Comment by robotboy655** [comment]
More importantly, cl_threaded_bone_setup 0

**Comment by ZehM4tt** [comment]
gmod_mcore_test only controls mat_queue_mode.  And I'll give it a try and let you know.

**Comment by ZehM4tt** [comment]
Looks like its actually caused by that, no crashes so far.

**Comment by robotboy655** [comment]
Going to close this as stale. (We no longer have symbols that go as back as 2017) If the issue happens again, open a new report.
