### ISSUE TITLE
Dedicated servers will download but not mount linked collections.

### ISSUE THREAD

**Issue by EpicCreeperHD** [Facepunch/garrysmod-issues#3016]
Hello,

I've hosted a couple of private servers to play on with friends for the last few years and we've recently tried linking a collection containing shared addons to both of the main collections. According to the server console, it had downloaded successfully but when it attempted to mount it, it couldn't. Instead the console read as follows: 

Not loading addon 'addons/ds_838996237.gma' - addon header invalid

So I was left wondering whether linking collections is supported and there's just a bug preventing it from working or if there's no support for collection linking at all, to which I say: "Hey, that's something that _should_ be supported! Would you kindly do that in the next update?". Either way, I consider this an issue and have decided to post it here seeing as nobody else has (that I could see).

Thanks,
            EpicCreeper

**Comment by robotboy655** [comment]
Already taken care of in Dev.
