### ISSUE TITLE
chat.AddText() no longer shows icons.

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#3017]
### Details
Icons no longer work with chat.addtext, they produce a purple and black icon despite the image existing on the client (and server)

### Steps to reproduce
icon = Material("path/to/icon.png")
chat.AddText(icon)

**Comment by robotboy655** [comment]
This was never a feature of the default chatbox, and it will never be.

**Comment by biorisk2** [comment]
Yes it was..?
Nutscript had this for a long long time, it's the exact method they used.
