### ISSUE TITLE
Clientside Entity:SetEyeAngles() only targets LocalPlayer.

### ISSUE THREAD

**Issue by Luabee** [Facepunch/garrysmod-issues#3018]
### Details

Running Entity:SetEyeAngles() clientside ignores the target Entity and changes the LocalPlayer's eye angles, even if you specify a different entity to set them for.

### Steps to reproduce

1. Spawn a bot in a game.
2. Run this code clientside:
```
Entity(2):SetEyeAngles(Angle(0,0,0))
```
Your own eye angles will change to Angle(0,0,0)

**Comment by robotboy655** [comment]
Fixed in Dev
