### ISSUE TITLE
Crashing at "Sending client information" on linux

### ISSUE THREAD

**Issue by Atexx** [Facepunch/garrysmod-issues#3019]
### Details
RAM usage goes up to even 3GB at Sending client information until the game crashes without an error or an error saying that I ran out of memory (still had free ram)
Only happens in servers with addons. Fresh install of GMOD no addons installed.
### Steps to reproduce
1. Join server with addons
2. Wait until you get to sending client information
3. Crash.

**Comment by Atexx** [comment]
Managed to join a RP server but gmod takes 2,4gb RAM and my RAM usage is 97% Awful performance. Only change I did was disabling multicore rendering because I was fucking with settings quite randomly. I don't think GMod should be using up this much ram unless it's a bug.

**Comment by robotboy655** [comment]
So at 2.4GB RAM usage its 97% used, but at 3GB you "still had free ram"? That's an interesting story.

But regardless of that, I think you are missing one very important point about GMod's RAM usage: it will use as much RAM as the server requires it to use to load and display every single addon, sound, material, texture, model and map. It will never stop even if it does not have any more memory and is about to crash. This is especially problematic on very large unoptimized maps and on shitty unoptimized servers made by 14 year olds who do not understand this simple truth and cram every single shitty DarkRP addon on their servers. 

There are a few things we can do to marginally improve memory footprint of the game ( and we do plan on looking into some of it in 2017 ), but there's only so much we can do and at one point those servers will still have too many addons to handle reliably by most/some people.

This is especially bad on huge RP servers.

**Comment by Atexx** [comment]
Ah sorry for forgetting to mention that, 70% free ram was on a freshly rebooted system with some chrome windows and spotify running, that 2,4GB and managed to join a server was with more stuff running on my pc. I just doubt it's because of server addons size because it happens on all kinda servers from TTT to sandbox and RP. Also this is the first time this has happened to me on GMod since I bought it in like 2008.

**Comment by Atexx** [comment]
@robotboy655 I'd like to make sure that you guys acknowledge that there is a problem with the memory allocation of addons because the ram supposedly used by server addons never goes down even after joining singleplayer or disconnecting. Something is wrong with it.

**Comment by philxyz** [comment]
Something you need to be aware of (and may be) is that OpenGL does not provide a way to find out how much memory is in use on the GPU and when it's full. If it can't fit any more, the game crashes. You can reduce the texture quality settings to lowest to sort-of-get-around this to an extent.

**Comment by neico** [comment]
A few things that make me wonder when reading through here are:

Since you use Linux, are you using SWAP (be it file or partition)? This is more or less equivalent to the page file on windows and can avoid RAM being exhausted in some cases.

if we talk about GRAM (Graphics RAM) / GPU Memory / GPU RAM like @philxyz mentioned, then maybe you should state as such, because you can monitor both RAM and GRAM, and tell at least how full each is. (even if OGL doesn't natively allow as such) and both can result in the game crashing if either is exhausted.

If your GRAM is the one being exhausted there's not much that can be done to work around it (like you can with normal RAM) as that's a hard limit on your graphics card and only replacing it can change that.

**Comment by atomiclord** [comment]
still an issue. i have the same issue running on kubuntu 18.04 with 16gb of ram, gpu is gtx 980 4gb of vram.

**Comment by robotboy655** [comment]
Closing as stale. If the issue still happens, please open a new report.
