### ISSUE TITLE
SetHoldType bugs around with no world model set

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3022]
### Details
Tested on a TTT-Server and DarkRP-Server.

When giving a weapon serversidely often the player's holdtype does not change or get changed incorrectly.

Seems to happen more often when having heavily lags.

### Steps to reproduce
Connect to a server
Strip weapons
Give fists for example

**Comment by Kefta** [comment]
Do you have any reproduceable code, or any steps that could be done on Sandbox?

**Comment by mcNuggets1** [comment]
Not really, as it depends on lag.

**Comment by mcNuggets1** [comment]
I tested around after 4 months of inactivity now.

SetWeaponHoldType always work directly, while SetHoldType sets the HoldType often incorrectly.
Switching all "SetHoldType " to "SetWeaponHoldType" fixes the issue.

However SetWeaponHoldType should be replaced with SetHoldType, atleast I heard that

**Comment by robotboy655** [comment]
SetWeaponHoldType is called on the weapon every time Set/GetHoldType updates.

You should check for inconsistencies between serverside and clientside GetHoldType when the issue occurs.

**Comment by mcNuggets1** [comment]
I investigated and it  seems only to happen with the "fist" holdtype.
If I give players a weapon with fist holdtype set, everyone has a ar2 holdtype or pistol holdtype.

**Comment by robotboy655** [comment]
Can you be certain that there's a problem with the game and not whatever weapon addon you are using?

**Comment by mcNuggets1** [comment]
It is 100% the game. It's there in TTT, DarkRP and Sandbox. The same issue.

Clientside + serverside it returns the right string but when actually rendered, it renders the complete opposite that it should.
Seems to happen when the holdtype is getting set serverside, not clientside.

**Comment by mcNuggets1** [comment]
https://i.imgur.com/w773O2W.png

Here, i have it somewhat documented here.

**Comment by Kefta** [comment]
The specific case with bots not updating their holdtype with the fists is a [documented bug](http://wiki.garrysmod.com/page/Weapon/SetHoldType).

**Comment by mcNuggets1** [comment]
Well, then it's not only for bots.

**Comment by mcNuggets1** [comment]
Yeah, it works on players too, they aren't updating their holdtypes.
It just says normal, while rendering fist holdtype.

**Comment by mcNuggets1** [comment]
Could this issue be resolved anytime soon?
It's an issue I run into every day and the only workaround is to give every weapon a worldmodel and turn it invisible + hide the shadow.

**Comment by robotboy655** [comment]
Well since you are the only one who can reproduce it, hop onto Dev branch and try again. 

I have fixed bots not updating holdtype clientside on weapons with no world model.

**Comment by robotboy655** [comment]
Should be fixed whenever it updates
