### ISSUE TITLE
Lightmaps do not update on prop_static models

### ISSUE THREAD

**Issue by Revenge282** [Facepunch/garrysmod-issues#3023]
https://facepunch.com/showthread.php?t=1537303&p=51706245&viewfull=1#post51706245

When updating the lightmaps, prop_statics are not updated to reflect the changes.  I believe this was supposed to be fixed some time ago, but it doesn't seem to have been.

ent:Fire("TurnOff")/ent:Fire("TurnOn") on light_environment:
http://puu.sh/bPbY5/0c86991e1d.webm

engine.LightStyle(0,"b")/engine.LightStyle(0,"y"):
http://puu.sh/bPc77/dac9b4c453.webm

Please see the thread linked for a more detailed description, but the above videos should explain most of what needs to be done.

**Comment by robotboy655** [comment]
Read http://wiki.garrysmod.com/page/render/RedownloadAllLightmaps

**Comment by Revenge282** [comment]
Yeah, I did read...

It, as I said, does not affect prop_static.  If this has something to do with the parameter -staticproplighting (as mentioned in the thread linked), then it could be the cause.

**Comment by Revenge282** [comment]
@robotboy655 As I am being told by a friend who compiled the same map without -staticproplighting, he is not seeing the prop_statics update either.

**Comment by robotboy655** [comment]
You must call ```render.RedownloadAllLightmaps( true )``` after *each* engine.LightStyle call, *with the argument set to true for static props*.

**Comment by Revenge282** [comment]
_**I read and executed the code, as I was supposed to according to the wiki.  It still does not update the prop_statics in the map, only the world.**_  I already stated this before.

**Comment by robotboy655** [comment]
Are you applying engine.LightStyle to all lightstyles ( first arg) only only 0, which only covers the world afaik?

**Comment by Noiwex** [comment]
there's two types of natural lights - sun and sky
