### ISSUE TITLE
PreDrawViewModel being called with a nil viewmodel half of the time

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3024]
Code: hook.Add("PreDrawViewModel", "Foo", function(vm) print(vm) end)

Tested in single-player. The hook will be called twice per render: once with the actual viewmodel entity and once with nil. Doesn't make sense on why it would be called twice.

**Comment by robotboy655** [comment]
Hm, apparently it has been there forever and is called just before PreDrawEffects. I have no idea why its there or what its purpose is

**Comment by Kefta** [comment]
Good thing Garry left comments

**Comment by Kefta** [comment]
Does removing it have any noticeable adverse effects?

**Comment by markusmarkusz** [comment]
I made a list for the wiki with the order of the Render Hooks.

Here is the original one (had edited something):
https://gist.github.com/markusmarkusz/85134798a06e6608d17ba77a76b2ce78

Is this an mistake by me or is it true that PostDrawViewModel is not called when PreDrawViewModel is called with nil?

**Comment by Kefta** [comment]
It shouldn't be called at all, I think. Also, your list has two PreDrawViewModels next to each other

**Comment by markusmarkusz** [comment]
I obtained this list by saving the arguments of hook.Call(). I had used the Base Gamemode for testing.

**Comment by Kefta** [comment]
If there are any other duplicate/out of order calls besides this one, you should report it.

**Comment by Kefta** [comment]
I believe I see why it's being called:  it's ran right before actual viewmodel entities are drawn, and its for non-viewmodel entities that have their rendergroup set as RENDERGROUP_VIEWMODEL. Looks like in first-person, the hook order ends up being:

```
...
GM:GetMotionBlurValues(...)
GM:PreDrawViewModel() with no args
ENTITY.Draw(num) for viewmodel rendergroup entities
ENTITY.RenderOverride() for viewmodel rendergroup entities
GM:PreDrawViewModel(...) with the normal args
...
```

This still shouldn't be called with no arguments, if at all.

**Comment by robotboy655** [comment]
Renamed that one call to `PreDrawViewModels` as I do believe that's what it was meant to be called, similarly to PreDrawEffects, PostDrawEffects, PreDrawHUD, etc, all of which are called from the same place as the now called `PreDrawViewModels`

**Comment by Kefta** [comment]
Can we get a ``PostDrawViewModels`` to know when the renderer has moved out of the viewmodel projection space for RT copying?

**Comment by robotboy655** [comment]
It would be equal to `PreDrawEffects` and I'd rather avoid more every-frame hooks, so no.

**Comment by Kefta** [comment]
Fair
