### ISSUE TITLE
player/zombie_fast.mdl missing hitbox numbers and head hitbox

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3027]
![fast zombie](http://i.imgur.com/Ff00IF6.png)
None of the hitboxes are numbered, so there's no headshot damage or whatever.

How it should be,
![charple](http://i.imgur.com/ii6SF1U.png)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/22737423/ac293c70-ee0b-11e6-9823-612818c6fe89.png)

Better?

**Comment by MinIsMin** [comment]
Looks good, but why are the fingers not included in the hitbox?

**Comment by robotboy655** [comment]
Hitboxes cannot be rotated and trying to cover the fingers will result in a lot of air you can hit to hit a hand.
