### ISSUE TITLE
Weapon:LastShootTime() not working in singleplayer

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3028]
### Details
Weapon:LastShootTime() never works in singleplayer.

### Steps to reproduce
Use it in singleplayer

**Comment by robotboy655** [comment]
More accurately it was never set serverside.

**Comment by mcNuggets1** [comment]
https://wiki.garrysmod.com/page/Weapon/LastShootTime
It says its shared, so I thought It would work everywhere.

**Comment by mcNuggets1** [comment]
Returns still 0 on devbranch, it is in the changelog marked as fixed however.

**Comment by robotboy655** [comment]
It only set on bullet shooting weapons after a bullet was shot. It is also not networked to clients.

**Comment by mcNuggets1** [comment]
When I shoot a bullet with owner:FireBullets() in singleplayer, nothing happens.
That is called shared.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/24516829/b3caf284-1584-11e7-9ef0-dde021cb1cba.png)

**Comment by mcNuggets1** [comment]
Does return always 0 clientside on a listen server.

I'm running it in the docrosshair hook.

**Comment by robotboy655** [comment]
Bullets are not shot on the client in singleplayer, so obviously SetLastShootTime is never called.

**Comment by mcNuggets1** [comment]
Even if I call it manually, it does not work.

**Comment by robotboy655** [comment]
...

PrimaryFire/Attack is never called in singleplayer.

**Comment by mcNuggets1** [comment]
How the heck should we call it then?

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Weapon/CallOnClient

You would've known all this information if only you've bothered to open the wiki page for http://wiki.garrysmod.com/page/WEAPON/PrimaryAttack

**Comment by mcNuggets1** [comment]
Thanks anyway.
