### ISSUE TITLE
render.PushFlashlightMode continue to "lit" objects even if ProjectedTexture is hidden

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#3029]
When you are using `render.PushFlashlightMode(true)` (of course after draws you pop it), rendered models has ghost lights.

How to reproduce:
1. Place an projected light source (example: lamp from tools)
2. Draw a model forward to light, so it is lighted by lamp.
3. Delete lamp.

This causes model to still be lighted by texture, but there is no lamp that create projected texture on that model.

**Comment by DBotThePony** [comment]
Reproduction look like:

```lua
mesh:Draw()
render.PushFlashlightMode(true)
mesh:Draw()
render.PopFlashlightMode()
```
This doesn't specifically apply to `IMesh`es, models are bugged too

<details>
<summary>Screenshots</summary>

![gmod_AnSZfXwFyO](https://user-images.githubusercontent.com/6339511/104085021-e23df400-527e-11eb-819e-e26ed6cb1369.png)
![gmod_9sUhAMleff](https://user-images.githubusercontent.com/6339511/104085023-e407b780-527e-11eb-93fd-45b418f4be17.png)
![gmod_Uk4DQN5Bzc](https://user-images.githubusercontent.com/6339511/104085024-e5d17b00-527e-11eb-9eb3-6bcdf0d6d6e3.png)
![gmod_bIpoEowlcm](https://user-images.githubusercontent.com/6339511/104085025-e79b3e80-527e-11eb-94c8-f18de2c35506.png)
![gmod_ABnQPTWDk0](https://user-images.githubusercontent.com/6339511/104085026-e9650200-527e-11eb-9efa-dc6734733aa9.png)

</details>

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/ENTITY:GetRenderMesh does not suffer from this. You can use it in the mean time.

Related issue is https://github.com/Facepunch/garrysmod-issues/issues/2301 I do believe both are caused by the same thing, which is flashlight states not being set up.

**Comment by robotik517** [comment]
Hi, found a solution of sorts

drop in client realm

local meta = FindMetaTable("ProjectedTexture")
if !meta.OldRemove then 
	meta.OldRemove = meta.Remove
end
function meta:Remove()
	self:SetBrightness(0)
	self:Update()
	timer.Simple(0.1,function()
		self:OldRemove()
	end)
end

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/render.RenderFlashlights

Added this function (example included) that solves the issue.

`render.PushFlashlightMode` is garbage and should have never been exposed.
