### ISSUE TITLE
Sandbox HUD does not show ammo above 255

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3030]
### Details
Sandbox HUD does not show ammo above 255

### Steps to reproduce
Set ammo above 255

**Comment by Kefta** [comment]
Pretty sure this is an HL2 limit

**Comment by robotboy655** [comment]
It's a networking limit (Clip1 and 2 are specifically made to network only 8 bits), I can get it fixed next time we change network protocol.

**Comment by robotboy655** [comment]
Fixed in Dev, now networks 16 bits which should be more than plenty
