### ISSUE TITLE
Pulley not using constraint info on maps.

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#3033]
### Details
The map d1_canals_06 has a pulley constraint which is just dangling around.

![hl2_2017-01-30_04-12-32](https://cloud.githubusercontent.com/assets/5415177/22411277/5a3fdb8c-e6a2-11e6-8806-6d8c59333d21.png)

 The issue is probably that garry added entity keyvalues which probably replace the original anchor points. This can be seen here: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L1151-L1152 they normally dont exist in the SDK.

It would be probably as simple as setting the value inside CPhysPulley::CreateConstraint passed on info parameter to the new key values to ensure it uses that instead of 0,0,0.

**Comment by robotboy655** [comment]
So that is what is causing that, well spotted. I'd like to try to work it out myself soon

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/22413487/fe3e522c-e6c0-11e6-8ff5-10d9b0169893.png)

Success?

**Comment by ZehM4tt** [comment]
sweet, thanks!
