### ISSUE TITLE
Random server crashes [linux]

### ISSUE THREAD

**Issue by MStruntze** [Facepunch/garrysmod-issues#3034]
### Details
I have for several months experienced random crashes, which I've somewhat linked to the amount of vehicles (or models at all?) being cached(/precached).
Increasing the amount of precached vehicles seems to cause more frequent crashes, through I'm unable to find a way to 100% cause a crash.

A weird scenario:
I had x amount of vehicles cached on serverstart. Server was _somewhat_ stable. Added 20 (just to prove the point) more vehicles to precaching, server crashes as soon as I look a certain map prop. Crash log for that is similar to crash log nr. 3.

I know that not all of the included crash logs are similar, but I just included some of those I had, where most recent crash is the focus.
_It seems to mention hitboxes in most of the them._

**Most recent crash**:
https://gist.github.com/MStruntze/04f1f3e1c8eee142f2616102a228740f
core file: https://mega.nz/#!I5UwSKwS!p9weyezzOOizTUOoKRoHhEuylf76dYx-vobWCo94Ksc

**Crash logs:**
1: https://gist.github.com/MStruntze/e4b7796364116924e7cd63cda8e2b39c
2 (3 crashlogs): https://gist.github.com/MStruntze/a02e7fb00104989532d51a4003ab3a26
3: https://gist.github.com/MStruntze/218a23d2d94088bc2dea2d1d5b0d7c4c

### Steps to reproduce
It seems to happen at random, though precaching more vehicles or similar seems to increase the chance of crashes - not for a specific vehicle, but no matter what vehicle it is (often popular from workshop)

**Comment by MStruntze** [comment]
Here's one more: https://gist.github.com/MStruntze/20845fbaf690c40d879ead9aff5f821d

**Comment by MStruntze** [comment]
Three crashes within an hour. No crashes for fives days, then suddenly these three:
https://gist.github.com/MStruntze/ce92964598e21aca038633a49f16ff54

**Comment by MStruntze** [comment]
Forth time: https://gist.github.com/MStruntze/e4fb841bb6cf281cf90997cc79266eee

**Comment by robotboy655** [comment]
Copypasting the same crashes over and over will not help. I am pretty sure this is caused by certain models being traced against, the problem is. I do not know which models those would be ( assuming custom models ) or how to reproduce the crash so it can be fixed.

**Comment by MStruntze** [comment]
They're not copypasted at all. I just included four more crashes which were similar to the original crashlogs. Not all of them are the same, and they're certainly not just duplicates.
We had a vehicle with pretty complex physics reduced since the crashes posted eight days ago (3rd feb). Both my servers have been crash-free for five days, until today where it suddenly crashes four times. No changes have been made.
