### ISSUE TITLE
Website using garys mod as a means to install malware

### ISSUE THREAD

**Issue by wackydude1234** [Facepunch/garrysmod-issues#3036]
was watching a video on youtube and saw an advert for "garys mod for free" and clicked it to see what it was, links to this: http://www1.kidsvideogame.com/ex_ts/garrysmod.html?cid=M6npstY2s5kGGns&amp;kwd= it's a toolbar website.

**Comment by robotboy655** [comment]
How is this fault of the game?

**Comment by wackydude1234** [comment]
It's not but i wasn't sure how to report it.

**Comment by Kefta** [comment]
It's not worth the time, money, and trouble of Facepunch to pursue one scamming website that has a minimal internet presence.
