### ISSUE TITLE
Entity's properties and Entity.PhysicsInit* can crash together

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-issues#3039]
### Details
Networked properties of the entity with custom physics (created with Entity.PhysicsInit* function) can crash the server.
For example, you can crash any server where you can spawn bouncy ball, because it uses Entity.PhysicsInitSpherical

#### Crash log
https://puu.sh/tOrBn/d03d26e185.mdmp

### Steps to reproduce
1. Spawn a bouncy ball
2. Spawn button on this ball and remove it
3. Change any property of the ball
4. Spawn buttons again 2 times
5. Server will crash

Video: https://youtu.be/SJ-hhPLhdF4

It work in multiplayer and singleplayer

**Comment by thegrb93** [comment]
I wonder if this is why all those tanks and cars and shit that use spherical wheels crash the server so much when they are pasted.

**Comment by TheMerkyShadow** [comment]
Can confirm this does work.

**Comment by robotboy655** [comment]
Duplicate of #2450

**Comment by robotboy655** [comment]
I found a fix for bouncy ball specifically, but I am not sure how to transplant that onto all PhysicsInit calls properly, or what the underlying issue is ( due to it being in vphysics ) or how to detect when a constraintsystem is no longer valid.
