### ISSUE TITLE
ClientsideModels aren't garbage-collected properely

### ISSUE THREAD

**Issue by knah** [Facepunch/garrysmod-issues#304]
Issue is simple and straightforward: if you don't delete ClientsideModels manually, you will run out of them at some point. However, if you do :Remove() them manually, you will be fine. This behaviour kind of violates purpose of garbage collection.

Here is my test on client:
```
] lua_run_cl gCSModels = {}
] lua_run_cl for i=1,5000 do local cm = ClientsideModel("models/error.mdl",RENDERGROUP_OPAQUE) if not IsValid(cm) then break end table.insert(gCSModels,cm) end print(#gCSModels,"so far")
5000	so far
] lua_run_cl for i=1,5000 do local cm = ClientsideModel("models/error.mdl",RENDERGROUP_OPAQUE) if not IsValid(cm) then break end table.insert(gCSModels,cm) end print(#gCSModels,"so far")
CBaseEntityList::AddNonNetworkableEntity: no free slots!
8174	so far
] lua_run_cl for k,v in pairs(gCSModels) do v:Remove() end gCSModels = {}
] lua_run_cl for i=1,5000 do local cm = ClientsideModel("models/error.mdl",RENDERGROUP_OPAQUE) if not IsValid(cm) then break end table.insert(gCSModels,cm) end print(#gCSModels,"so far")
5000	so far
```
This example shows that they are :Remove()'d normally and free the slots.
However, if instead of removing them I just do "gCSModels = nil" and then try to force garbage collection (either via collectgarbage("collect") or by just spamming some string or tables), they aren't freed up.
Obviously, this will lead to code using ClientsideModels erroring out randomly if client doesn't rejoin a server often enough, especially if server makes heavy use of ClientsideModels and relies on garbage collection to free them.

**Comment by robotboy655** [comment]
#1387
