### ISSUE TITLE
Loading Screen Music Issue

### ISSUE THREAD

**Issue by TheMerkyShadow** [Facepunch/garrysmod-issues#3040]
It seems the html <iframe> tag with a youtube embed seems to be failing.
It works perfectly on any other browser, seems to be failing on gmod.
Possible steam http browser issue or awesomium problem?
 
Plz. People tell me im not crazy....
That joining previous servers with loading screens with music dont work anymore.

**Comment by Andrew1134** [comment]
yea i have that issue as well

**Comment by Bo98** [comment]
Good riddance.

On a serious note, perhaps https://github.com/garrynewman/garrysmod/pull/1330 is related.

**Comment by TheMerkyShadow** [comment]
I just want to point out I think this a serious issue.
I know most servers have cancerous music. But if what i'm saying is correct hundreds of loading screens and scripts now have to be modded or fixed cause this doesn't work anymore.

**Comment by Bo98** [comment]
The issue is much wider than just loading screen music anyway. It's every YouTube video afaik.

**Comment by TheMerkyShadow** [comment]
It seems to be fixed now?

**Comment by Bo98** [comment]
It was a YouTube change that broke it in the first place, so possibly.

There's still a issue on GMod's part but that's not YouTube specific, and is covered by the pull request linked above.
