### ISSUE TITLE
GMPublish no longer compresses GMAs larger than 350MB

### ISSUE THREAD

**Issue by slayer3032** [Facepunch/garrysmod-issues#3043]
I have an addon which before compression is unfortunately 353MB, however after compression it's an astounding 15.7 MB. Something between December of 2015 and now has caused this to no longer work. The following image is an attempt to reupload my currently live workshop addon from the downloads\server folder of my garrysmod.

![gmpublishisshit](https://cloud.githubusercontent.com/assets/1855794/22632369/668f48ca-ebcd-11e6-9c02-03fe5b97e291.png)

If you wish to recreate, subscribe to this addon, grab the uncompressed GMA and shove it into GMPublish to see it fail.

http://steamcommunity.com/sharedfiles/filedetails/?id=858159900

**Comment by slayer3032** [comment]
gmpublish_linux does not have an arbitrary limit placed on files before compression and happily compressed both the old GMA and the new one unaltered.

![gmpublishlinux](https://cloud.githubusercontent.com/assets/1855794/22632352/5336d144-ebcd-11e6-9b9a-959c33894dd6.png)

**Comment by robotboy655** [comment]
Nothing was changed, there wasn't an update to GMod since December and there wasn't an update to GMPublish since even longer.

The reason it fails is simply because your system fails to allocate enough RAM to compress the file if I had to guess, since it requires much more than 350mb to do it. I may be wrong.

**Comment by Revenge282** [comment]
Tried to do the exact same process as mentioned above, using the same GMA he was, and it failed for me as well.  Except I am running a six-core i7-5820K with 32GB of RAM...

Setting GMPublish with the LAA flag fixed the issue.  This needs to be corrected for release version.

Also, why is GMPublish not open-source like GMAD?

**Comment by Noiwex** [comment]
Happened to me recently too.

**Comment by Noiwex** [comment]
And no, robotboy, it has changed.

OLD GMOD
$ sha1sum.exe gmpublish.exe
222d1acbdf90a5fee284db6c3c39be7b1c886642 *gmpublish.exe

NEW GMOD
$ sha1sum.exe gmpublish.exe
2c6bdf932d7d64f06d9b18c0de2539421aab703c *gmpublish.exe

**Comment by Bo98** [comment]
SHA-1 change could easily be a rebuild or something by the build server.

**Comment by Noiwex** [comment]
Might be, but still wondering wtf is going on.

**Comment by Noiwex** [comment]
Alright, it seems to be issue with LAA. Why the hell stuff is still 32bit.

**Comment by arthurgeron** [comment]
We are in 2019 and still we have a 32bit software to upload stuff to the workshop. Amazing
