### ISSUE TITLE
failure and denial or as in error in the installment

### ISSUE THREAD

**Issue by shadowwarwolf** [Facepunch/garrysmod-issues#3045]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step:.... I was able to download it so i have been able to play for a week then it stoped working I had to turn off my computer I kept trying to get it to work then I decided to uninstall it and then reinstall it but now it wont install back on to my computer can you give me any help??

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
