### ISSUE TITLE
map_background is broken in Garry's Mod

### ISSUE THREAD

**Issue by adih2001** [Facepunch/garrysmod-issues#3046]
Hello!
I added to my map some features that allow a nice cinematic camera show if the map is launched via `map_background` (map background is a command just like `map` but instead this command allows you to run a map in the background of the menu) but it seems to be broken. The hud is showing up, the disconnect and resume to game buttons show up and also there is a huge line in the middle of the screen and thoose should not show up.
Here is a video of how map_background looks in Garry's Mod:
[https://www.youtube.com/watch?v=pNqLnyJkS1Y](https://www.youtube.com/watch?v=pNqLnyJkS1Y)

Here is another video of the same map but ran in Half Life 2 (still used map_background)
[https://youtu.be/IALlzf0mmoA](https://youtu.be/IALlzf0mmoA)
As you can clearly see in the Half Life 2 video there is no disconnect and resume to game button , no hud and no line in the middle of the screen.

Steps to reproduce

If you are intersted to run the map by yourself in same conditions here is the map link: [http://steamcommunity.com/sharedfiles/filedetails/?id=762485766](http://steamcommunity.com/sharedfiles/filedetails/?id=762485766)
After downloading the addon just type `map_background demo_realistic_lighting` in console or if you don't want to download the map you can just try it on any other map.
Sorry for my bad english

Thanks.

**Comment by robotboy655** [comment]
map_background is not "properly supported" in GMod as there's little to no reason to bother fixing the problems you point out.
