### ISSUE TITLE
Bad glow coordinates of weapon_stunstick, weapon_rpg, weapon_crossbow

### ISSUE THREAD

**Issue by panica23** [Facepunch/garrysmod-issues#3047]
weapon_stunstick
![cuk_4yhzyws](https://cloud.githubusercontent.com/assets/21275896/22855330/fac4f6b8-f08f-11e6-8ab6-92ebb3312a61.jpg)

Also weapon_crossbow
![image_2017-02-27_17-50-47](https://cloud.githubusercontent.com/assets/21275896/23365870/c66dd7d0-fd15-11e6-829c-dc5250f62eae.png)

weapon_rpg
![8_g5a53dncg](https://cloud.githubusercontent.com/assets/21275896/23322222/fddd873e-faf3-11e6-89e7-2d858600fe36.jpg)

**Comment by darrnokturna** [comment]
Also weapon_rpg
![8_g5a53dncg](https://cloud.githubusercontent.com/assets/21275896/23322222/fddd873e-faf3-11e6-89e7-2d858600fe36.jpg)

**Comment by robotboy655** [comment]
As far as I can tell, the stunstick is already fixed, the RPG and Crossbow are fixed in Dev.

**Comment by marigi64** [comment]
I think the extra RPG laser sprite (that got removed in the Dev branch) is actually supposed to be stretched as seen in hl2 and its episodes here:
<img width="525" alt="rocket laser" src="https://user-images.githubusercontent.com/53112738/61750267-47322f80-ade8-11e9-83f4-d659646330ac.png">

Also the stunstick isn't glowing or sparking at all when being swung. 
Here it is in hl2 deathmatch: 
![stunstick](https://user-images.githubusercontent.com/53112738/61764824-da398c80-ae1d-11e9-8434-6fbfbfbcffb0.gif)

**Comment by robotboy655** [comment]
Nah the laser was disabled on purpose because it was too much trouble to get working apparently, and yes, i am aware of the stunstick first person fx in singleplayer

**Comment by marigi64** [comment]
alright thanks

**Comment by robotboy655** [comment]
Fixed the effect not showing in singleplayer, but it is too bright and I don't know whats up with that, probably not gonna look into it too much.
