### ISSUE TITLE
Heavy props with physgun getting stripped

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#3048]
### Details
If you hold a entity with the physgun, and then get ````StripWeapons```` called on you, the prop you held will not get its mass reset to its original, instead it will have the max weight (45678) set on it. This is problematic in for example Flood where high mass = high buoyancy which people were abusing for a while.

The current workaround is to use ````StripWeapon("weapon_physgun")```` which handles the mass-resetting properly

### Steps to reproduce
* ````bind b "lua_run Entity(1):StripWeapons()"````
* Pick up a prop (blue barrel for example), press b while holding it.
* Watch how you now can stand on it while it's floating without problem.

**Comment by robotboy655** [comment]
Should be fixed in Dev in an hour or so.
