### ISSUE TITLE
NPC Dropping weapons (LAG)

### ISSUE THREAD

**Issue by evilbiggy38** [Facepunch/garrysmod-issues#3049]
How does one go about disabling npc's dropping weapons on death?

Having hundreds of AR's on the ground is really taxing on a server cpu, and is bringing my server to the brink of crashing very often. I found a few "NPC battle cleanup" mods but the setup was vague and didn't appear to work at all.

Any help is greatly appreciated

**Comment by kem008** [comment]
there is a flag to dont drop on death i think.
