### ISSUE TITLE
 Problem with the download of addons that remains at 0gb

### ISSUE THREAD

**Issue by Ortinox** [Facepunch/garrysmod-issues#3050]
When I download addons there is a bug, this bug has to download an addon, it remains at 0gb and it uses the connection and I can not download other addons or updates.

Here is a screenshot : 
![capture](https://cloud.githubusercontent.com/assets/25767051/22925232/3811a056-f2a8-11e6-8f02-17f73ed3c0aa.PNG)

Sorry for my English, I'm French

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

This isn't even a problem with GMod

**Comment by uRandomAlex** [comment]
Try to restart Steam.
