### ISSUE TITLE
User Interface unusable on the 2016 13" MacBook Pro (Assumed any 13" screen)

### ISSUE THREAD

**Issue by RandomEthan** [Facepunch/garrysmod-issues#3051]
### Details

I use a 13" MacBook Pro, the 2016 model without a touchbar to be precise. If I try to open any server list on Garry's Mod, the UI is broken. 

It's difficult to explain, so I have attached a screenshot. 

I would guess that it would be the same on certainly any other 13" OSX computer, and maybe for other OS's too. 

Regardless, it makes finding a decent server to play on online almost impossible, and it would be great if this could be checked out.

Thanks.

<img width="1680" alt="screen shot 2017-02-15 at 19 59 45" src="https://cloud.githubusercontent.com/assets/25803165/22993449/fe25bf9e-f3ba-11e6-9b62-e0473da985fb.png">

### Steps to reproduce

1) Open Garry's Mod on a 13" MacBook or other 13" screen OSX computer (I only know that this occurs on my 13" MacBook pro).

2) Press "Find Multiplayer Game"

3) Select any gamemode's corresponding server list, to open up a server list.

4) You should be able to see the same as or similar to what is in the attached screenshot.

**Comment by Bo98** [comment]
What resolution are you using? (check in GMod: Settings -> Video)

**Comment by RandomEthan** [comment]
800 x 600, I hadn't thought of this, and upping the resolution does allow me to see all the majority of the information, though it is still squashed, so it is partially cutting parts off. It is certainly an improvement though.
<img width="1680" alt="screen shot 2017-02-15 at 20 52 05" src="https://cloud.githubusercontent.com/assets/25803165/22994975/cb5fad9e-f3c0-11e6-9849-b37829aa7045.png">

**Comment by robotboy655** [comment]
Set your resolution higher still. Nothing we can do if you play at 800x600 or 1024x768

**Comment by mcd1992** [comment]
Ehh, his menu's CSS seems off. It should be aligning things on the right anyway. Might be a simple fix, even though I agree that such a low resolution is shit.

https://i.imgur.com/xkrzJMQ.png Looks fine on Linux at 800x600

**Comment by mcd1992** [comment]
Oh actually I'm wrong, when you actually look at servers vs gamemodes it shits the bed.

![Wat](https://i.imgur.com/OGnLy9Z.png)

**Comment by Bo98** [comment]
It's because that space at the right is used by the player list when you select a server.

**Comment by mcd1992** [comment]
Yea I forgot about that until I started trying to fix it :V

I guess the legacy browser is the lazy fix for it.
