### ISSUE TITLE
PLAYER:GetWeapons() does not always give a sequential table

### ISSUE THREAD

**Issue by KingofBeast** [Facepunch/garrysmod-issues#3052]
### Details
Basically the title. The table that's returned is not always sequential. This is not expected behavior. It seems that as weapons are given to a player, the table is populated sequentially properly. However, as they're stripped from a player those indexes remain empty and the other entries are not pushed down.

### Steps to reproduce
Strip weapons from a player

![Proof!](https://yasbit.ch/2b3.png)

**Comment by Kefta** [comment]
Yeah, I reported this back on the old GitHub and Garry said it was intentional iirc

**Comment by KingofBeast** [comment]
Well that's retarded.

**Comment by aStonedPenguin** [comment]
Garry Code™

**Comment by Kefta** [comment]
Also, to note, this can be replicated by printing the weapon table, removing a weapon, then reprinting.

**Comment by markusmarkusz** [comment]
Is the problem client side only?

**Comment by Kefta** [comment]
@markusmarkusz No 
![1ucldvn](https://cloud.githubusercontent.com/assets/4593679/23092853/8c954b2a-f599-11e6-84f6-5f94a9fdc89d.png)

**Comment by robotboy655** [comment]
I'd imagine the only reason this would be intentional is to have some sort of permanent position for given weapon in player's inventory. Even then I am not sure how useful that is.

**Comment by uRandomAlex** [comment]
Player:GetWeaponsList? or GetWeaponsSeq, but the first one sounds better

**Comment by KingofBeast** [comment]
Would just be more logical to make GetWeapons return sequential tables and if for some odd reason the inventory does require permanent positions, just make it keep track of that itself.

**Comment by robotboy655** [comment]
It is now ensured to be sequential and starts with index 1.
