### ISSUE TITLE
Blood textures are cut up in squares.

### ISSUE THREAD

**Issue by 73584jay** [Facepunch/garrysmod-issues#3054]
Recently, I have noticed that when blood appears on a wall or floor, parts of the blood seem to be cut off in squares. I have tried to reinstall GMod, but when I start up GMod it does the same thing and even uninstalling some of my addons doesn't work. I found out it has nothing to do with an update because it started doing this not when an update came out, and I didn't get the February update until today. I do not know how to recreate this texturing error because it came randomly. I have a suspicion that an addon ruined some of the game files, but I don't have proof. Please, try to fix this as soon as you can! Thank You!
![20170221222208_1](https://cloud.githubusercontent.com/assets/25945896/23198355/464b979e-f884-11e6-81f5-dca8d7a53481.jpg)
![20170221222213_1](https://cloud.githubusercontent.com/assets/25945896/23198356/465d34cc-f884-11e6-908a-b95e22638649.jpg)
![20170221222203_1](https://cloud.githubusercontent.com/assets/25945896/23198357/46613716-f884-11e6-9998-1f0c7244478f.jpg)

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

**Comment by 73584jay** [comment]
Thank you! The website you mentioned was a great help!
