### ISSUE TITLE
UpdateRenderTarget isn't working

### ISSUE THREAD

**Issue by UAVXP** [Facepunch/garrysmod-issues#3055]
### Details
After I tried to call UpdateRenderTarget function, console says:
```
[ERROR] lua_run:1: attempt to call global 'UpdateRenderTarget' (a nil value)
    1. unknown - lua_run:1
```
As I can see at wiki.garrysmod.com, it's not deprecated feature ([http://wiki.garrysmod.com/page/Global/UpdateRenderTarget](http://wiki.garrysmod.com/page/Global/UpdateRenderTarget))

### Steps to reproduce
For example:
1) Run in server console "lua_run UpdateRenderTarget( Entity(1):GetEyeTrace().Entity )", while you're alone on server and looking on a prop
2) Or run "lua_run UpdateRenderTarget( nil )"

**Comment by Bo98** [comment]
I think this was removed in GMod 13 when the RT Camera was removed.

**Comment by UAVXP** [comment]
@Bo98 The thing is that function working at Sandbox and not working at other gamemodes, I assume.

**Comment by Bo98** [comment]
And it doesn't work in Sandbox derived gamemodes like DarkRP?

**Comment by UAVXP** [comment]
@Bo98 Yep.

Sandbox server:
![2017-02-22_21-17-10](https://cloud.githubusercontent.com/assets/3075683/23228203/6312c58a-f944-11e6-8a29-fb13e49c6b75.png)

DarkRP server:
![2017-02-22_21-17-27](https://cloud.githubusercontent.com/assets/3075683/23228208/666f356a-f944-11e6-98f8-c67733b0da5b.png)

Fretta server:
![2017-02-22_21-17-42](https://cloud.githubusercontent.com/assets/3075683/23228212/690696ce-f944-11e6-9c70-f3f470e6cdb5.png)

**Comment by UAVXP** [comment]
Okay, that's strange, for some reason this function works on our server, but when I've created a local server and tried to run "lua_run UpdateRenderTarget( nil )" - console said "attempt to call global 'UpdateRenderTarget' (a nil value)
"

**Comment by robotboy655** [comment]
This function doesn't exist, that's why it errors.

It was on the wiki due to a mistake wen it was created

**Comment by Bo98** [comment]
@UAVXP You probably have an addon that adds the UpdateRenderTarget function on your Sandbox server, such as wire-extras.

**Comment by UAVXP** [comment]
@Bo98 Yeah, you're right.
