### ISSUE TITLE
Lightmaps buggs out sometimes

### ISSUE THREAD

**Issue by UAVXP** [Facepunch/garrysmod-issues#3056]
### Details
It's hard to tell, so I would show a video of this bug: https://www.youtube.com/watch?v=i6tWqkpbzvE

### Steps to reproduce
This is map from video, zip-file contains .bsp and .vmf: [door_rot_test2.zip](https://github.com/Facepunch/garrysmod-issues/files/794679/door_rot_test2.zip)

**Comment by robotboy655** [comment]
You are using a texture made for models on a not-model.

Basically the texture is using wrong shader, the model shader, which reacts differently to lighting information.

**Comment by robotboy655** [comment]
Just to further prove my point, you are using "BRICK/BRICK_MODEL", which is a material shipped with GMod ( Not HL2 ) that uses the "VertexLitGeneric" shader, while what you want to use is "Brick/brickwall003a", which uses the "LightmappedGeneric" shader.

**Comment by UAVXP** [comment]
Oh, shit, that's my fault, sorry then, didn't noticed it, thanks. Goddamn I'm blind
