### ISSUE TITLE
Player:SetMuted(bool) always toggles muted state

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-issues#3058]
### Details
Unlike documented here: http://wiki.garrysmod.com/page/Player/SetMuted
Player:SetMuted() always toggles the muted state of a player regardless of the argument (even if you do not provide a bool at all)
### Steps to reproduce
Tell us how to reproduce the problem, step by step
for k,v in pairs(player.GetAll()) do v:SetMuted(false) end
for k,v in pairs(player.GetAll()) do print(v:IsMuted()) end -- will alternate between true and false

**Comment by robotboy655** [comment]
Yep, CVoiceStatus::SetPlayerBlockedState's blocked argument is not used in the function, gj valve

**Comment by robotboy655** [comment]
Fixed
