### ISSUE TITLE
Bad position of last update and map name in all resolutions

### ISSUE THREAD

**Issue by somebadguy** [Facepunch/garrysmod-issues#3059]
![hw1g_34opla](https://cloud.githubusercontent.com/assets/26014950/23323811/637ac74e-fafb-11e6-9d8f-0241f35ef8e8.jpg)

**Comment by robotboy655** [comment]
Yeah I totally agree, but I am not sure what would be a better position.

**Comment by somebadguy** [comment]
May be this can be solved with auto appearance, when u aim on that angle (will show the last update)
or make it like in cs go, tf2:
![nlkkt8xpbj8](https://cloud.githubusercontent.com/assets/26014950/23330794/8b0a01e0-fb68-11e6-8a0b-ace1c82452d1.jpg)
![ul1_nutlzys](https://cloud.githubusercontent.com/assets/26014950/23330795/8b0bc944-fb68-11e6-842e-c0eb222edb70.jpg)
Or mb like this
![default](https://cloud.githubusercontent.com/assets/26014950/23330822/4dfb70a8-fb69-11e6-957a-47a11286a82e.jpg)

**Comment by robotboy655** [comment]
Can't really do either of those, you have to be able to click the GMod's black box so it takes to the update page, and the black box does not have a fixed size, it is much longer on dev Branch.

**Comment by robotboy655** [comment]
Ended up just moving that text 30 pixels down.
