### ISSUE TITLE
spelling mistake when gmod is loading

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3065]
### Details
It says "Initializing serverside..".

The 2 dots are unnecessary, should be only one, hmph?

**Comment by robotboy655** [comment]
I don't think you could get more nitpicky with you 'bug reports', but you always manage to prove my expectations wrong

**Comment by uRandomAlex** [comment]
so, is this fixod?/ it is a very importont problem!11
