### ISSUE TITLE
Content File Locked While Installing

### ISSUE THREAD

**Issue by Dawood562** [Facepunch/garrysmod-issues#3066]
While installing this game, I got towards the end and it abruptly ended, going into the 'Update Needed (Not queued)' section, with the status 'Content File Locked'. I then attempted to play anyways, when it stopped me still. I have included a screenshot with that popup that comes when I try to play.

Thanks!
![image](https://cloud.githubusercontent.com/assets/26071443/23377821/485d1bee-fd29-11e6-9a91-d00a8839e645.png)

**Comment by robotboy655** [comment]
Not a problem with the game obviously, contact Steam Support.
