### ISSUE TITLE
Mounting problem ep2_outland_10 same model name but different

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#3069]
### Details
Simple Half-Life 2 and Episode Two are using the same model name and path but they are different models.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Go to Episode Two ep2_outland_10 and check the radar cache's cave entrance with Half Life 2 mounted ...

[original](https://i.imgur.com/u7CtlKz.jpg)
[hl2-model](https://i.imgur.com/utGUohx.png)
[in-game](https://i.imgur.com/uD3Arhn.png)

**Comment by robotboy655** [comment]
Nothing we can do about it.

I'd also say its the same problem as https://github.com/Facepunch/garrysmod-issues/issues/793
