### ISSUE TITLE
strange behaviour of system.UpTime/AppTime/SteamTime

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-issues#3070]
### Details
[`system.AppTime()`](http://wiki.garrysmod.com/page/system/AppTime), [`system.SteamTime()`](http://wiki.garrysmod.com/page/system/SteamTime) and [`system.UpTime()`](http://wiki.garrysmod.com/page/system/UpTime) give strange results.
The results of these functions are wrong, if I have understood the wiki correctly.

Client: Windows 10; GMod Version `2017.02.20` (latest)
Server: Debian 8; GMod Version `2017.02.16` (latest)

###### [`system.UpTime()`](http://wiki.garrysmod.com/page/system/UpTime):
```lua
timer.Create("UpTime", 2, 5, function() MsgN(system.UpTime()) end)
```
Results for example in:
```
0
2
1
3
5
```

**On Server:**
```lua
timer.Create("UpTime", 2, 5, function() MsgN(type(system.UpTime())) end)
```
```
no value
no value
no value
no value
no value
```

###### [`system.AppTime()`](http://wiki.garrysmod.com/page/system/AppTime) (**Only serverside**):
```lua
timer.Create("AppTime", 2, 5, function() MsgN(type(system.AppTime())) end)
```
```
no value
no value
no value
no value
no value
```
###### [`system.SteamTime()`](http://wiki.garrysmod.com/page/system/SteamTime) (**Only serverside**):
```lua
timer.Create("SteamTime", 2, 5, function() MsgN(type(system.SteamTime())) end)
```
```
no value
no value
no value
no value
no value
```

**Comment by robotboy655** [comment]
None of those functions are meant to be working on any dedicated server.

**Comment by markusmarkusz** [comment]
But what about UpTime? It doesn't work for me even in menu state.

**Comment by robotboy655** [comment]
The documentation for it is wrong, as well as the function name. UpTime is not what it does.

It's a direct binding to Steam's ISteamUtils->GetSecondsSinceComputerActive.

I can't quite understand how exactly it works and there's little to no documentation on it from Steam, but as far as I can tell, it's related to the Steam's AFK timer. Moving mouse cursor resets the timer to 0.

**Comment by robotboy655** [comment]
I will update the wiki pages.
