### ISSUE TITLE
lookup, lookdown, moveup, movedown are broken

### ISSUE THREAD

**Issue by ForrestMarkX** [Facepunch/garrysmod-issues#3071]
These console commands seem to be broken in Garry's Mod and I have no idea why they would be

**Comment by Jvs34** [comment]
They only work with keyboard look being enabled, by setting cl_mouselook to 0 when in the main menu.

**Comment by ForrestMarkX** [comment]
Ohh hmm I see, thanks for the info!

**Comment by robotboy655** [comment]
Use Lua. The Move hooks.
