### ISSUE TITLE
Lua ERROR "not enough memory"

### ISSUE THREAD

**Issue by Vinipop** [Facepunch/garrysmod-issues#3072]
Hello everybody I post this message in the hope of finding a solution to my problem ... Every time I join a specific server (Darck RP), at the time sending client info, my games stop with only one I tried several things that it had marked on tutos or things like its .I was told that it had a relationship with the RAM (Cw which is an addons) lua / cw and several things like its that i have tried to reinstall my games still nothing. Is not even the temp of copied! In any case if someone knows (apparently the "lua" is something "complicated") ... I take the solution!

(And excuse me for the mistakes of spelling because I am French) Thank you! ;)

**Comment by kem008** [comment]
wtf?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
