### ISSUE TITLE
Missing activity enums on players

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3075]
These activities are used in m_anm but not defined in the codebase:

ACT_HL2MP_IDLE_COWER
ACT_HL2MP_SIT_CAMERA
ACT_HL2MP_SIT_duel
~~ACT_HL2MP_SIT_KNIFE~~
~~ACT_HL2MP_SIT_MELEE2~~
ACT_HL2MP_SIT_PASSIVE
ACT_GMOD_DEATH
ACT_GMOD_SHOWOFF_STAND_01
ACT_GMOD_SHOWOFF_STAND_02
ACT_GMOD_SHOWOFF_STAND_03
ACT_GMOD_SHOWOFF_STAND_04
ACT_GMOD_SHOWOFF_DUCK_01
ACT_GMOD_SHOWOFF_DUCK_02
ACT_FLINCH
ACT_FLINCH_BACK
ACT_FLINCH_SHOULDER_LEFT
ACT_FLINCH_SHOULDER_RIGHT
ACT_DRIVE_POD
ACT_HL2MP_ZOMBIE_SLUMP_ALT_IDLE
ACT_HL2MP_ZOMBIE_SLUMP_ALT_RISE_FAST
ACT_HL2MP_ZOMBIE_SLUMP_ALT_RISE_SLOW

**Comment by ShadowBonnieRUS** [comment]
seems ACT_HL2MP_IDLE_COWER is 2058 serverside and undefined clientside.
```Lua
local id = me:LookupSequence("idle_all_cower")
print(me:GetSequenceActivityName(id),me:GetSequenceActivity(id))
```
![image](https://user-images.githubusercontent.com/49488893/81504789-e8e12980-92f3-11ea-8344-f34be95bd3e5.png)

**Comment by thegrb93** [comment]
Bump

**Comment by robotboy655** [comment]
Added the rest
