### ISSUE TITLE
FPS drops each time a soundscript is played

### ISSUE THREAD

**Issue by ghost0123** [Facepunch/garrysmod-issues#3077]
### Details
1. Using weapon quick switching
[+showbudget](http://images.akamai.steamusercontent.com/ugc/83719631612919195/6E342FCCFFD711AC914AF106A1B4F706A8CE787F/) - FileSystem spikes
[fs_tellmeyoursecrets 1](http://images.akamai.steamusercontent.com/ugc/83719631612919633/3D433465E83A648635E7E930480E1012B6D7F10E/)

2. Lua created weapons (used [CW 2.0 ](https://steamcommunity.com/sharedfiles/filedetails/?id=349050451)as an example) cause fps drops each time a soundscript (for firing, reloading, etc) is played.
[fs_tellmeyoursecrets 1](http://images.akamai.steamusercontent.com/ugc/83719631612956957/6387B0DC283816B4EF1096568E62E77EEEEFE576/)

**Comment by ghost0123** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/869

**Comment by robotboy655** [comment]
It's actually very interesting why it tries to search soundscripts in the filesystem, it shouldn't be doing that

**Comment by robotboy655** [comment]
I think I found the problem, but I cannot commit the fix just yet.

**Comment by robotboy655** [comment]
Fix should be in Dev, please test it and tell us if it is better/fixed/worse.

**Comment by ghost0123** [comment]
It's better, the soundscripts don't cause an issue after the first time loaded, however
It still does the massive search in every possible directory in the filesystem for the first time it needs to play the soundscript.

**Comment by robotboy655** [comment]
Obviously it has to load the sound files into the memory the first time around, after that its cached and fast.

**Comment by Kefta** [comment]
Does precaching the sound-script change that?
