### ISSUE TITLE
SENT:Physics* hooks are only called for SOLID_VPHYSICS and MOVETYPE_VPHYSICS entities

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3078]
CBaseEntity::PhysicsSimulate is called for all entities regardless of their move or solid type in the engine, but the hooks on the entities aren't.

**Comment by robotboy655** [comment]
It doesn't use CBaseEntity::PhysicsSimulate

**Comment by robotboy655** [comment]
Only PhysicsCollide has a MOVETYPE_VPHYSICS check

**Comment by Kefta** [comment]
Ah, what method does PhysicsCollide bind to? I thought it would have been the MoveCollide branches
