### ISSUE TITLE
Higher entity limit

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3079]
### Details
Maximum 8194 entites is way too less for big servers with 128 players on it.
I would suggest to double the limit.

**Comment by neico** [comment]
First of that's more of a request than a issue,  
second, it'll be very hard to increase the limit without making the engine even more unstable (especially with that many players, the engine is simply not well tested for this kind of size)

The most important thing would be to force coders to not waste entity slots by making the entities as abstract as possible, but that's probably going to be impossible given the different approaches people tackle things.

**Comment by mcNuggets1** [comment]
Wrong issue tracker, I see.

Forgot about that. Sorry.
