### ISSUE TITLE
Sound Characters do not work with .ogg audio files

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#3081]
https://developer.valvesoftware.com/wiki/Soundscripts#Sound_Characters

Sound path modified to use the Directional sound character
The third ogg file could be any ogg file

Entity( 1 ):EmitSound( "<music/hl1_song17.mp3" ) -- Using the "<" direction sound character
Entity( 1 ):EmitSound( "<garrysmod/save_load4.wav" )

Entity( 1 ):EmitSound( "<garrysmod/save_load4.ogg" ) -- This file doesn't technically exist, I'm pointing out an example, it could be any ogg sound file, directional characters won't work and instead it will be treated as part of the path

**Comment by robotboy655** [comment]
Appears to be fixed. At the very least @ works with ogg file saved through Audacity.

**Comment by Kefta** [comment]
> and < seem to work now, as well
