### ISSUE TITLE
SetNoCollideWithTeammates Issues

### ISSUE THREAD

**Issue by ForrestMarkX** [Facepunch/garrysmod-issues#3082]
### Details
Using this function seems to cause various issues involving collision and **it doesn't matter if you use team ids 1-4. A team with ID 1 will still get killed by a func_movelinear if two players of that team collide with each other while ontop of it**

Here are the issues I've found so far when testing this function. These all happen if two collision hulls from players of the same team overlap at all.

1. Standing ontop of a physics prop will make you collide with teammates
2. Standing ontop of any object that isn't the world will either kill you or eject you.
3. You can't stand ontop of a player of the opposite team as your ground entity gets forced to null every frame.

### Steps to reproduce
Setup a team with ID 1 and call SetNoCollideWithTeammates(true) on the spawned players
Stand ontop of a prop/mover and have the other player do the same
The second you two collide the mover/prop will either A. Sling you away or B. Stop moving or C. Kill you

Related to another issue #2757

**Comment by ForrestMarkX** [comment]
Only way I've found to fix this is by moving the player hulls up one unit but this causes different issues

**Comment by polartron** [comment]
Any workarounds for this yet?

**Comment by ForrestMarkX** [comment]
No, the only thing I was able to track down is when two players touch the object they are standing on will called Blocked which is most cases kills both players or slings them away

**Comment by Kefta** [comment]
Could always use a ShouldCollide hook @polartron

**Comment by polartron** [comment]
For performance reasons it would be best if this worked properly. ShouldCollide does create some exponentially growing performance problems with high player counts (70-80 players).

I'm guessing this is an engine problem, but it would be nice to understand what is going on under the hood with this function.

I am trying to optimize an existing gamemode https://github.com/JetBoom/zombiesurvival

**Comment by ForrestMarkX** [comment]
Most of the problem with performance on ZS is traces from bullets, TakeDamage events and collision events
