### ISSUE TITLE
Firing under water with secondary fire

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3083]
### Details
Some Hl2 weapons spam clipping sounds then.

### Steps to reproduce
Go in singleplayer/multiplayer.
Equip hl2 pistol.
Go underwater.
Hold secondary fire.
Enjoy?

**Comment by Kefta** [comment]
This BaseCombatWeapon behaviour from having m_bAltFiresUnderwater set to false, even without a secondary fire. I don't really see a huge problem with it besides a minor annoyance, but it's an easy fix, I guess.
