### ISSUE TITLE
NULL_texture:IsError() errors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3086]
Tried to use invalid object (type ITexture) (Object was NULL or not of the right type)

Alternatively could add an IsValid method for ITextures.

**Comment by robotboy655** [comment]
It doesn't check for validity of the object, but rather whether the material technically exists. I suppose IsValid can be added

**Comment by robotboy655** [comment]
How did you even get a NULL texture?

**Comment by Kefta** [comment]
render.GetRenderTarget seems to return a NULL texture sometimes

**Comment by robotboy655** [comment]
Got it. Can you think of any way of getting a NULL IMaterial?

**Comment by Kefta** [comment]
It's something I've personally never ran into, so no idea.

**Comment by robotboy655** [comment]
Is there actually a reason for testing for invalid Itextures? render.GetRenderTarget will return an invalid one if there are no render target override active (and it is required for render.SetRenderTarget), but that should be able to be changed to return nil and it should still work without breaking anything.

Is there anything else I am missing?

**Comment by Kefta** [comment]
That's the only way I know of getting an invalid texture.

**Comment by robotboy655** [comment]
Let's see if anything breaks.
