### ISSUE TITLE
Frozen at the blue screen that has a loading bar almost fully finished.

### ISSUE THREAD

**Issue by Rapolis** [Facepunch/garrysmod-issues#3087]
### Details
I start up the game, after a little of waiting it gets stuck in this screen FOREVER: http://prntscr.com/en4ppj
Awesomium processes open up which are invisible. No way, I didn't find a window with an error. Just frozen solid. And while I thought the error didn't happen, I waited over 10 minutes.
This is the most annoying error ever. I also tried using RobotBoy's Lua Menu to fix the problem. And it worked! But my game freezes when I try to start any game, like joining servers, playing singleplayer, hosting servers.
Trying to fix it doesn't work, I tried: verifying game integrity cache, re-installing, deleting the bin file, force uninstalling with IOBit Uninstaller Pro and it is NOT caused by an addon conflict.
After all this situation, I got into a HUGE panic that I wasted 4.99 euros (I only paid that much, because it was on Christmas) only to play 427 hours and get this error. While writing this issue, I got this: http://prntscr.com/en4w7l
I spent about 23 minutes finding for a solution, found nothing, but bumped threads, very old and others complaining: "me got da problemo 2".

### Computer Specs
CPU: 4x Intel Core I5-4690
GPU: MSI nVidia GTX 960
DirectX Version: 12.0
OS: Windows 10 Pro
RAM: 16 GB

### Steps to reproduce
Don't know how, but something may have messed with my d3d9.dll file.

Hope you can tell me the solution. Don't make this another wasted 10 minutes.
I spent a total of about 43 minutes of this whole adventure.
@garrynewman and @robotboy655, I hope you can fix this. If not, others may bump into this thread and spew out a good fix, or not.

P.S. If you were wondering, I did NOT pirate this game. Check out my steam profile to see what I mean: http://steamcommunity.com/id/57754383/

**Comment by robotboy655** [comment]
```
Sub-processes (like awesomium_process.exe) shouldn't be set to run as admin, symptoms can be anything awesomium related or just hangs during loading.

This will cause problems like The game freezing on "Finished" on Facepunch Screen
```

This is the only known cause of this problem.

**Comment by Rapolis** [comment]
Ahh... I get it now. Thanks for the solution, hope it works.
I also like your lua menu! It's compact, simplistic and brings the feel of a simple lua coder and classic G-Mod.

**Comment by Rapolis** [comment]
@robotboy655, sorry if I'm wasting your time, but I don't know how to make awesomium_process.exe not set to run as admin. And when I got that issue, the admin mode was still turned off, here's proof: http://prntscr.com/eneq9w
I see no problem here. I don't know what's causing that error still.

**Comment by robotboy655** [comment]
Then something else is preventing it from being launched, like GMod being installed in some weird directory.
