### ISSUE TITLE
Hang/crash when an ENT contains a table with a default value

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#3088]
### Details
The game hangs and crashes, presumably after entering an infinite loop, when saving the game while an entity exists whose ENT definition has a subtable with a [default value](https://www.lua.org/pil/13.4.3.html).
### Steps to reproduce
Easiest method: open lua/entitites/sent_ball.lua and add the following lines somewhere:
```Lua
ENT.Laughs = { amusing = "lol", notreally = "haha" }
setmetatable(ENT.Laughs, { __index = function(k) return "rofl" end })
```
Launch the game, open sandbox, spawn a ball, save the game (using the Saves tab). Game will become unresponsive.

Tested on Windows only, on both the live branch and prerelease.

**Comment by Kefta** [comment]
This was fixed with the scripted_ents/weapons copy method updates.
