### ISSUE TITLE
PhysObj.SetBuoyancyRatio allows values outside of intended range

### ISSUE THREAD

**Issue by icegt95** [Facepunch/garrysmod-issues#3091]
### Details
This is a little one. [PhysObj.SetBuoyancyRatio](http://wiki.garrysmod.com/page/PhysObj/SetBuoyancyRatio) allows values outside of the intended 0-1 range to be passed, specifically on the positive end.

### Steps to reproduce
Set an entity's physics object's buoyancy ratio to 999999 and the object will fly out of water with supersonic speed.

```
-- some entity ent
local phys = ent:GetPhysicsObject()

if IsValid( phys ) then

    phys:SetBuoyancyRatio( 999999 )
    phys:Wake()

end

```

**Comment by thegrb93** [comment]
Not a bug. I think the wiki description is just too vague.

**Comment by robotboy655** [comment]
Updated the wiki page.
