### ISSUE TITLE
PLAYERANIMEVENT_CANCEL_RELOAD enum missing

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3095]
As referenced here: https://github.com/garrynewman/garrysmod/blob/03b82174f0884b60d6c1fa4a9a25e55b500ffb27/garrysmod/gamemodes/base/gamemode/animations.lua#L381

Thanks glua discord

**Comment by robotboy655** [comment]
Done, also made it automatically fire so the reload animations are automatically cancelled when switching weapons.
