### ISSUE TITLE
GMod Crashing on default maps (construct/flatgrass)

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#3098]
### Details
When loading either gm_construct or gm_flatgrass, approx 75% of the time GMod will flat out crash-to-desktop without a not-responding or anything of the like, the crashing itself seems to be random, and I've tried with or without addons.

Although on one occasion when loading into construct the game said something about rebuilding a nodegraph before crashing.

Windows 10 x64,
Intel Quad-Core I7-6700 @ 3.40GHz Processor
AMD Radeon R5 350 / Intel HD Graphics 530
16GB RAM.

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_170220_crash_2017_3_28T15_15_4C0.mdmp

### Steps to reproduce
Literally no steps, I just load into the map either by start new game or by using the "map" command in the console, and then boom, crash mid-load.

**Comment by Kefta** [comment]
Try with no addons, even workshop disabled

**Comment by Roachdaripper** [comment]
I have done, no changes seem to occur and I've tested and re-tested owing to the random nature of the crashes.

**Comment by robotboy655** [comment]
Awesomium crash, usually caused by running 3rd party programs that fuck with it, such as some free anti viruses or in-game overlays.
