### ISSUE TITLE
Everything but models loading with AddWorkshop addons

### ISSUE THREAD

**Issue by Iamgoofball** [Facepunch/garrysmod-issues#3099]
### Details
When you join a server that adds its workshop addons to the client downloads with `resource.AddWorkshop()`, you'll find that when you load in after downloading and mountinng the addons, all the textures, vgui elements, and sounds loaded properly, but the model does not. This is fixed if you restart the game and reconnect, but not if you just reconnect.

### Steps to reproduce
I made an example addon loader and a workshop collection to help demonstrate this issue.

Put the following gist in an autorun inside of an addon.
https://gist.github.com/Iamgoofball/a40b9ae1ec241a3cef8a6f86f07e7d1d 
Set the server's workshop collection to this:
http://steamcommunity.com/sharedfiles/filedetails/?id=893676132

1. Boot the server up as Sandbox after setting your collection key to the above. `engine.GetAddons()` is fucky and doesn't like to work the first time an addon is mounted to the server so if it throws a warning in the console about invalid addons just restart srcds and it'll work.
2. Join the server as a client. Notice that the game detects, downloads, and mounts the addons requested by the server.
3. Go to the Weapons tab in your Q spawnmenu, navigate to the TFA Insurgency tab. See the weapon icon properly loading from the addon.
4. Click to equip and spawn the weapon. You'll notice that the model is an error, Firing the weapon will play the correct sounds, and the vgui, sounds, and textures are all loaded properly, except that the model is not loaded.
5. Restart the game. Rejoin the server. Spawn the weapon again. The model is visible.

I've reproduced this with 3 other addon's models, all completely independent of eachother.

I mean, this might just be a problem with AddWorkshop(), might be a problem with joining, might be a problem with models, idk. It's pretty broken and the only thing stopping players from just being able to join the server and play various gamemodes without having to restart the entire game.

**Comment by robotboy655** [comment]
I have tried it with your code & your collection and nothing happened. Everything worked from the first try, on the Dev branch.

**Comment by Iamgoofball** [comment]
I'm using the current non-dev build, I'll switch over to it. Maybe that's my issue.

**Comment by Iamgoofball** [comment]
I hate one-offs.

**Comment by robotboy655** [comment]
The only reason what you described with models would happen is if the client already tried loading that model in that game session.

I.E. some other server doesn't force the models to download, user tries to spawn that model, it appears as error, user leaves, joins another server that DOES force that model to download, but user still sees error when the model is spawned. This is normal and has nothing to do with workshop or w/e, it's just how Source caches models.
