### ISSUE TITLE
hl2.exe crashs

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3101]
### Details
Sometimes when chaning map, the game suddenly crashs without creating a dump file with the message hl2.exe does not work anymore (or something similiar)

### Steps to reproduce
Seems to happen randomly...

**Comment by Kefta** [comment]
I can confirm this. I just thought it was my game, but I removed all of my addons and it's still happening on dev branch

**Comment by robotboy655** [comment]
Can you at least attach console logs or some sort of information on how to reproduce this?

**Comment by robotboy655** [comment]
I am assuming this is only started recently ( 2 days ) and only on the dev branch? I'd like to know what maps you are switching to, how, singleplayer/local MP/dedi MP, what gamemode, does it happen without addons?

**Comment by Kefta** [comment]
Did this on a listen server with two players, no addons, and without peer-to-peer enabled. I randomly alternated between map/changelevel until I finally got it to crash. Sometimes it closes instantly after the world loads, sometimes, hl2.exe will stop responding twice. Here's the console log for the last two iterations: https://pastebin.com/rDTwhvGg

This attempt took 19 changes, but I've had it happen after the first change. Here are my startup flags: -window -noborder -heapsize 8388608 -high -novid -noforcemparms -noforcemaccel -noworkshop -condebug

**Comment by mcNuggets1** [comment]
It is happening to my server, since quite a while.
But suddenly it happens even for the client to me very often.

**Comment by robotboy655** [comment]
Do either of you have mcore enabled?

**Comment by mcNuggets1** [comment]
I always have.

**Comment by robotboy655** [comment]
Can you try disabling it and see if this happens then?

**Comment by mcNuggets1** [comment]
It happens on my server either...

**Comment by robotboy655** [comment]
So the only crashes I could make happen is one with "map" being called too soon (the first lua load) on the client, in which case a msgbox pops up telling the "world has no physics data" and one on srcds with the "bot" concommand being run on the first lua load/tick which crashes with physics. Both produce dumps so I am assuming this is not the crash I am looking for.

**Comment by Kefta** [comment]
I do have mcore enabled (it's enabled by default on dev, anyway); I will test without.

**Comment by Kefta** [comment]
Haven't had it occur for the past few days, although I've still had mcore enabled. A recent change possibly fixed it?

**Comment by robotboy655** [comment]
The only 2 things I fixed since your previous post are that the "bot" concommand will not work before InitPostEntity and a small change to player's initial spawn - hull customization in GMod was resetting the physics stuff for the player where the engine originally did not.

Can @mcNuggets1 confirm @Kefta s words?

**Comment by robotboy655** [comment]
The 2 things I fixed should've been causing problems ever since SetHull stuff was added, so I am not sure that was it.

**Comment by mcNuggets1** [comment]
I am testing now on dev branch.

**Comment by Kefta** [comment]
Just had it happen again: http://i.imgur.com/ZeWuzp0.jpg

The response error message will come up once, and after your close the program, will not close it until it shows up again. No dump, single-player, dev branch.

I did save a file during loading in one of my addons to fix the script error shown in the image, and I have noticed the crashing is more common while tabbed out.

**Comment by willox** [comment]
Is it crashing or freezing?

**Comment by Kefta** [comment]
This time it was freezing. Sometimes, it instantly crashes to desktop.

**Comment by Kefta** [comment]
Just had it happen again; I am able to move for the first second before it instantly stops responding.

**Comment by willox** [comment]
If it's only freezing you can create a dump file from task manager: https://support.microsoft.com/en-gb/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows-vista-and-in-windows-7

It'll be a full dump containing all of the processes memory, so you won't want to upload it publicly, so just pm me it or something.

**Comment by Kefta** [comment]
@willox Emailed

**Comment by willox** [comment]
That should be fixed on the dev branch within 30 mins

**Comment by Kefta** [comment]
What was the issue if I may ask?

**Comment by robotboy655** [comment]
Some code related to VPK was hitting an infinite loop. Let us know if it still freezes/crashes.
