### ISSUE TITLE
Crash Then need to Install GMOD Again 

### ISSUE THREAD

**Issue by Tripy21** [Facepunch/garrysmod-issues#3102]
### Details
i open up Gmod and i cant Click any thing in there and t stays like that untill i have to turn off my CP when i go back in i have to intsall the game to play it uninstalls by its selfe

hl2_170220_crash_2017_3_30T23_48_26C0.rar

### Steps to reproduce
i just Open Gmod up and some times it happens some times it dosent it is Random

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
