### ISSUE TITLE
CreateMaterial does not update existing procedural materials

### ISSUE THREAD

**Issue by Xyxen** [Facepunch/garrysmod-issues#3103]
### Details

Subsequent calls to [`CreateMaterial`](http://wiki.garrysmod.com/page/Global/CreateMaterial) with the same material name have no effect. This is a problem when using autorefresh to tweak procedural material parameters. The only workaround I know of is to change the name of the material each time (i.e. creating a new material for every revision).

These materials also stick around between map changes and between servers, so the only way to return to using the original material name is to restart the game. This means that materials created on one server may override those on another. As a result, a required matparam change for a newer version of an addon may be ignored if a client joined a server running an older version of the addon within the same session.

### Steps to Reproduce

The script below highlights the issue:
```lua
concommand.Add("mat_testcreate", function(ply, cmd, args)
	local texName = args[1] or "EXAMPLE_TEXTURE"
	local mat = CreateMaterial("update_test", "UnlitGeneric", {
		["$basetexture"] = texName
	})
	print("$basetexture = " .. mat:GetString("$basetexture"))
end)
```
Example usage showing the parameters not being updated:
```
] mat_testcreate first
$basetexture = first
] mat_testcreate second
$basetexture = first
] mat_reloadallmaterials
...
] mat_testcreate second
$basetexture = first
```

### Speculation

I did some investigation with the 2013 SDK. I assume that `CreateMaterial` is a binding to `g_pMaterialSystem->FindProceduralMaterial(name, texgroup, keyvalues)` (probably via [`CMaterialReference::Init`](https://github.com/ValveSoftware/source-sdk-2013/blob/f56bb35301836e56582a575a75864392a0177875/mp/src/public/materialsystem/MaterialSystemUtil.cpp#L64-L69)) which will either return the procedural material with the given name, or failing that, create a new one using the given keyvalues. Hence, only the first call will have any effect on the stored material parameters.

My first thought was to check for the existence of a material with that name, and call `g_pMaterialSystem->CreateMaterial` if one is found. However, while the new material successfully steals the name, it *is* a new material. The result is that there are now two materials, the oldest of which is inaccessible by name (but may still be referenced via `g_pMaterialSystem->GetMaterial` by using the corresponding material handle). Thus, any existing references continue to point to the material with the old parameters, which is undesired.

Ultimately, the ideal solution is for the existing `IMaterial` to be updated, as they are for non-procedural materials when `mat_reloadmaterial` is used. If VMT changes from disk can be loaded in correctly, there doesn't seem to be any technical reason that this behaviour can't be extended to `CreateMaterial`. As far as I can tell, it should just mean swapping out the backing store for the material (which might be a `KeyValues` structure or an array of `IMaterialVar`)? Unfortunately, the code behind the implementations of `IMaterial` and `IMaterialSystem` are not available in the public SDK, so I haven't been able to easily continue my search. I assume the required magic is somewhere in `CMaterial`.

Please let me know if there's any further information needed.

**Comment by NeatNit** [comment]
Similar issue with GetRenderTarget\[Ex\], it's impossible to change the dimensions (or other properties) of a previously-created render target. In particular, this makes it impossible to make a render target that always matches the game resolution if the user has changed it, like how the engine-defined _rt_fullframefb (and others) are always kept up to match.

**Comment by robotboy655** [comment]
Made it update the material instead of just returning it, let me know it if breaks anything.

**Comment by willox** [comment]
This has been changed a little further to avoid some crashes it introduced with mcore rendering. A side-effect is that you can't change the shader parameter after the material has been initially created any more.

**Comment by robotboy655** [comment]
This change will be reverted for the updates, it just creates more problems than it solves.

Maybe we will look into destroying the created materials between server changes instead, which should solve the biggest problem with the created material not updating.

**Comment by thegrb93** [comment]
@willox @robotboy655 is this one of the sideeffects? https://www.youtube.com/watch?v=LPZZdnEWEHo

**Comment by thegrb93** [comment]
Might be the fault of https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/material.lua#L38

**Comment by robotboy655** [comment]
The changes were rolled back, so whatever you are experiencing, it is not part of the update, nothing broke. You could try GetKeyValues() on the material and see what is set and what is not.

**Comment by thegrb93** [comment]
Yah, unrelated problem. It's weird IMaterial.SetUndefined behavior.

**Comment by Kefta** [comment]
Could you reopen this so it isn't forgotten about?

**Comment by robotboy655** [comment]
Lua created materials ( CreateMaterial ) are now cleaned up on map shutdown

**Comment by louiefox** [comment]
Shader name and parameters aren't updated when it updates the material
