### ISSUE TITLE
Buttons not quite working after save

### ISSUE THREAD

**Issue by runnerbeany** [Facepunch/garrysmod-issues#3110]
# Details
When loading a save which contains buttons, the buttons will not work.
## Example:
I have a save on construct which has buttons which control *lamps*.
When I load the save again, the buttons animate but don't toggle the lamps. However, the buttons that control the *lights* do work. 

# Steps to reproduce
Place buttons which toggle *lamps*. Place some lamps to be controlled, too.
Then place buttons which toggle *lights*. Again, place lights to control.

Save it, and then load it again. The lights will toggle but the lamps won't.

**Comment by robotboy655** [comment]
Should be fixed on Dev Steam Beta Branch within 1 hour.
