### ISSUE TITLE
Issues with Half-Life: Source Characters

### ISSUE THREAD

**Issue by Gene-Worm** [Facepunch/garrysmod-issues#3111]
So, lately I've come across some fairly notable issues with Garry's Mod's Half-Life: Source characters that I would like to address.

Disclaimer: I searched through already existing threads to see if anyone else has reported these issues, and I didn't see any. But if there are, I apologize if some of these were already covered.

### Details

1. Alien Grunt's Hornet (monster_hornet) is recognized by other NPCs and will be targeted as an enemy, so the Grunt's opponent will shoot at the incoming projectiles instead of the Grunt. This is because the hornet is an NPC, and there's nothing telling it not to be seen by hostiles.

2. HL:S Headcrabs (monster_headcrab) sometimes appear to ignore any enemies. I am still investigating exactly what is causing this and when it happens, as it seems random. Seems to happen mostly on multiplayer.

3. Houndeyes (monster_houndeye) will not chase enemies, but instead follow them if they get out of site.

4. HECU Marines/Grunts (monster_human_grunt) is in the same class as The Combine, so they won't fight against each other. I know this is a part of the game's design, but logically it doesn't make any sense. Xenians also don't fight Antlions, but I can sort of see how that might work.

5. The Tentacle (monster_tentacle) only seems to have any attack collision at the center of its body, and therefore its head just goes through anything it attacks. It also has a flies sound that seems to loop after it is remove.

6. Ichthyosaur (monster_ichthyosaur), Leech (monster_leech), G-Man (monster_gman), and Barnacle (monster_barnacle) seem to be missing from the spawnmenu, but they are in the game.

7. Ichthyosaur seems to have the wrong ConVar set for attacking, so it does no damage. This can be easily fixed by changing sk_ichthyosaur_melee_dmg to sk_ichthyosaur_shake in the skill.cfg file.

8. Leech uses the Half-Life 2 model, making the NPC fail to function properly. This could be fixed the same way the Barnacle was fixed.

9. Nihilanth is bugged, as it doesn't attack any enemies and it perpetually loops its death animation. But I know that's part of its design in Half-Life, so I understand if there's no fixing it.

10. Apache (monster_apache), Osprey (monster_osprey), and the three Turrets (monster_sentry, monster_turret, monster_miniturret) aren't even in the game. I did notice that there is code in the base_npcs file for the turrets to appear in the spawnmenu, but it is commented out and you can't spawn them through the console.

### Steps to reproduce

1. Spawn an Alien Grunt and put it again something, like say a Combine Soldier. Notice how the soldier is focused on the hornets instead of the monster? If you can't tell, try it with something like a melee attacking NPC, like a Zombie.

2. I've had a hard time pin-pointing exactly how to replicate this, but if you try to spawn a Headcrab on multiplayer, it just won't attack most of the time.

3. Spawn a Houndeye. Notice how it isn't even trying to chase after you or any enemies you set up for it?

4. Spawn an HECU Marine (Grunt) and put it against any Combine NPC. They won't fight each other. Same thing for if you put any HL:S alien against any Antlion.

5. Spawn a Tentacle and let it hit you. Notice how you aren't taking any damage? Now, try walking to the center of its body and you'll start taking 25 damage.

6. Look in the spawnmenu under Half-Life: Source (make sure you don't have any addons that automatically add them) and see how none of those NPCs mentioned are in there? Now, go into the console and type (without quotation marks) "sv_cheats 1", and then "npc_create *entity name*". I parenthesized the entity names for any readers, and they will appear.

7. Spawn an Ichthyosaur with either the console or custom Lua, and let it attack you. Notice how you are taking no damage from it?

8. Spawn a Leech with either the console or custom Lua, and look at the model. Notice how it is using the Half-Life 2 model instead, and how it is unable to attack?

9. Spawn the Nihilanth. Notice how it hardly ever attacks (it does sometimes). Now, kill it and notice how its death goes on forever?

10. Use the same console command(s) I mentioned on .6, but instead for those entities. The console should instead be returning "Attempted to create unknown entity type monster_example!".

**Comment by robotboy655** [comment]
1) Fixed.
2, 3 and 9) This is the HLS behavior. Can be related to poor NPC support on custom maps, etc. (AI Nodes etc)
4) Fixed
5) Sounds are fixed, but not the collisions
6) They are duplicate/have no purpose outside of HLS/broken(barnacle)
7) Fixed
8) Not fixed (yet?)
10) Yes
11) One problem/bug per issue/ticket.

**Comment by Kefta** [comment]
In relation to 10, why are they commented out?

**Comment by robotboy655** [comment]
No clue. I didnt do it.

**Comment by Kefta** [comment]
It seems they're not included because the NPCs aren't implemented in Garry's Mod at all
