### ISSUE TITLE
pcall doesn't stop include errors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3112]
It will print the file error to console but not halt the function, causing pcall to return true.

Semi-related: https://github.com/Facepunch/garrysmod-issues/issues/1976

**Comment by TASSIA710** [comment]
This workaround worked for me:
```lua
local exec = CompileFile("your_file.lua")
local status, err = pcall(exec)
```

**Comment by Kefta** [comment]
That doesn't work with autorefresh though.

**Comment by robotboy655** [comment]
This is ultimately a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3112 - same cause.
