### ISSUE TITLE
Broken Menu

### ISSUE THREAD

**Issue by Gamer221** [Facepunch/garrysmod-issues#3113]
The menu is like broken or something. I can't access anything.

First, i added the line `lua.Run("for _, game in ipairs(engine.GetGames()) do if game.installed and not game.mounted then engine.SetMounted(game.depot, true) end end");` to the end of my `.steam/steamapps/common/GarrysMod/garrysmod/html/js/lua.js` , so that the source games i have are mounted (#86 issue).
Then i removed the line. Now the menu looks like <a href="http://imgur.com/a/1pxHh">this.</a>
I'm on Linux Xubuntu 15.10.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
