### ISSUE TITLE
Workshop Perpetually "downloading", and Error[37] on 90% of subscribed items when launching gmod.

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#3121]
### Details
![image](https://cloud.githubusercontent.com/assets/11798863/24811770/5c5bc28a-1bbf-11e7-96d9-14df40672eaa.png)

That's under Steam's downloads almost 24/7. It doesn't happen with any other game.
As Steam detects it as a download, it often stops me from launching GMod at all, and usually postpones other downloads.

When I **can** launch the game, any item I've subscribed to but not yet downloaded takes an age to download, even when it's a small addon and even when I plug my computer into Ethernet, and the moment it hits 100% I get an error[37] without the addon extracting.

### Steps to reproduce
I have no idea if this is a problem exclusive to me or if it's a problem others are having, but I couldn't see anything like this posted in other issues.

**Comment by Roachdaripper** [comment]
I just subscribed to some more items to test, and I got this

![image](https://cloud.githubusercontent.com/assets/11798863/24811891/dac8a50c-1bbf-11e7-9022-641da9366c47.png)

What?

**Comment by robotboy655** [comment]
Why are you posting pictures of Steam and bugs of Steam here? This isn't a place to report bugs with Steam.
