### ISSUE TITLE
Addons you mount when joining a server, stay in local game

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3123]
### Details
Explained above.

### Steps to reproduce
Join server.
Go to singleplayer.
Enjoy?

**Comment by mcNuggets1** [comment]
Then I got no issues at all.

It is just not removing them from my game when leaving from the server.

**Comment by Jake3231** [comment]
Does this occur only on the prerelease branch, or on the release branch as well?

**Comment by mcNuggets1** [comment]
Every branch.

**Comment by Jake3231** [comment]
Thanks. I'll see if I can get my game to do this as well. Just to make sure we're on the same page, in your single player world, you can spawn items that were included in addons downloaded from servers?

**Comment by mcNuggets1** [comment]
We are talking about mounted workshop addons.
I don't know if file addons are affected.

**Comment by Kefta** [comment]
Just replicated on my end - seems to only apply to workshop addons.

**Comment by mcNuggets1** [comment]
Its happening to some lua files either, tickrate and nearly ALL server settings which are shared, ALSO.
This is a pretty huge issue.

**Comment by Kefta** [comment]
I think the Lua files issue is due to the cache not being cleared between sessions (https://github.com/Facepunch/garrysmod-issues/issues/2712 maybe?)

**Comment by robotboy655** [comment]
Should be fixed.
