### ISSUE TITLE
Burn (replace) Awesomium

### ISSUE THREAD

**Issue by ThatOneCheetah** [Facepunch/garrysmod-issues#3129]
### Details
I think that many GLua devs can agree, it's time to get rid of Awesomium.  
I realise that there might be complications in doing so (unexpired licenses, finding a replacement, re-doing code), but this can no longer be.  
  
The current source of my Awesomium-induced frustration is the fact that it's CSS support is... y'know, behold (text in divs added for debugging):  
  
#### Firefox  
![Proper rendering](http://latet.uk.to/git/Screenshot_11apr17_1753.png)  
  
#### Awesomium
![Wtf is this shit](http://latet.uk.to/git/Screenshot_11apr17_1753_1.png)  
  
Awesomium seems to literally jump off of a bridge any time it sees the following things:  

- 'Shortened' CSS; such as `animation: cheese 1s ease infinite, cake 0.55s forwards;`  
- Anything too 'modern'; such as `vmin, vmax, vw, vh, background: url( ... ), position: fixed, box-shadow, etc...`, though if you specifically use `background-image: url( "..." );` (**with quotes**) it doesn't seem to complain
- Anything to do with transparency on non-Windows platforms  
- Pretty much anything a normal web front-end requires

### Steps to reproduce  
Write a web-page, include some (fancy) simple *(though apparently not so simple)* CSS, yay broken stuff!  
  
To my surprise, even IE10 and IE11 seem to handle this web-page just fine.
  
### Note  
I know this is a re-occurring issue, but at this point it seems easier to just get rid of it instead of trying to fix it; which in itself is also a shitty task, but we can consider it broken nonetheless.

**Comment by ThatOneCheetah** [comment]
There doesn't seem to be any issues referring to this specific behaviour in Awesomium/GMod; it might or might not be related to the bindings, so I understand the `invalid` label, however, marking it as duplicate and closing the issue, thus regarding it a non-issue, seems like rushed decision-making.

**Comment by Kefta** [comment]
There's already an open issue about it. That's why it's a duplicate

**Comment by ThatOneCheetah** [comment]
Would've been nice to see a reference to that open issue, because I seem to be overlooking it; otherwise I wouldn't have created this issue to begin with.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/24922843/5a6fd6c8-1ef8-11e7-8514-784fc8af51e5.png)
