### ISSUE TITLE
menu_reload crashes the game

### ISSUE THREAD

**Issue by Klizmotron** [Facepunch/garrysmod-issues#3130]
### Details
Well, it's fairly simple, when I use menu_reload, I get this: 

![Crash message](http://i.imgur.com/Tc49wwJ.png "Crash message")
[Crash dump download](https://dl.dropboxusercontent.com/s/f27x40dvb58qwff/hl2_170220_crash_2017_4_12T19_34_53C0.mdmp)

I have no idea what can be the cause, as well as I'm not sure if it's my setup relevant or a current game bug, so I can provide more info if needed.

### Steps to reproduce
1. Launch the game
2. Use _menu\_reload_ console command (crashes even in main menu)

**Comment by robotboy655** [comment]
You are not supposed to use it anyway.

**Comment by Jake3231** [comment]
On the latest version of the dev branch (2017.4.12) I cannot reproduce this issue. I have tried this on my macOS 10.12.4 computer, but not on a Windows computer.

**Comment by Bo98** [comment]
I think it's to do with the server list. Try playing around with the server list and then do `menu_reload`.

**Comment by robotboy655** [comment]
I don't think it has anything to do with any specific panel. 

It happens with my Lua menu too, and everything in default menu is HTML.
It must be related to how the Lua state is recreated.
I have a fix for myself through trial and error, but I won't commit it without at least identifying what causes the problem. As I already said, it's not a command you should be using, its meant for gmod devs only.

**Comment by willox** [comment]
The issues caused by the serverlist were fixed ages ago. It's probably timers and anything else that works in a similar way. Seems like a non-issue to me though

**Comment by robotboy655** [comment]
menu_reload is no longer a console command.
