### ISSUE TITLE
NaN problems

### ISSUE THREAD

**Issue by Klizmotron** [Facepunch/garrysmod-issues#3139]
### Details
Is there any _true_ way to check values for NaN (0 / 0)?
I haven't found any functions for that purpose in gmod lua, but I'm stuck now since I really need this

### Steps to reproduce
```Lua
local a = 0 / 0 -- NaN variable
print( a ) -- prints out "nan"
print( type( a ) ) -- prints out "number"
print( isnumber( a ) ) -- prints out "true". P.S. isnumber( NotANumber ) == true? Wut?
```

**Comment by bigdogmat** [comment]
This isn't a bug. Also you can check with this,

```lua
local function isNan(num)
  return num ~= num
end
```

**Comment by Klizmotron** [comment]
Thanks! That's a way to go. I guess this thread is closed now. It's strange that ```isnumber( nan )``` returns ```true ``` though, a kind of a logical paradox. Well, NaN is a kind of a logical paradox itself, so maybe it's okay. Hard to say. Anyways, I think this thread is closed now, thanks for your help once again.
