### ISSUE TITLE
vcollide_wireframe not showing custom physics objects

### ISSUE THREAD

**Issue by Klizmotron** [Facepunch/garrysmod-issues#3140]
### Details
That is probably more of a request than of an issue, why not make it draw physics objects created with [PhysicsInitConvex](https://wiki.garrysmod.com/page/Entity/PhysicsInitConvex)/[PhysicsInitMultiConvex](https://wiki.garrysmod.com/page/Entity/PhysicsInitMultiConvex)? I mean the cases where the physics object is initialized clientside or shared, if it's serverside only, it's obvious that the client just can't know it's shape (where with models he can suppose it). It would help debugging the process of custom hulls generation a lot. Probably not so many people face this, but anyways, maybe it can be fixed by changing 2 lines of code, and if so, why not :+1: 

### Steps to reproduce
1. Create a SENT which initializes its physics using [PhysicsInitConvex](https://wiki.garrysmod.com/page/Entity/PhysicsInitConvex) (clientside or shared)
2. Run _vcollide\_wireframe 1_ clientside (requires _sv\_cheats 1_)

**Comment by robotboy655** [comment]
Simply put, it's not supposed to. Everything in that system relies on model indexes and only for SOILD_VPHYSICS entities.

If you can notice, it doesn't work with NPCs OR func_physbox'es
