### ISSUE TITLE
Garry's Mod Troubles with KeyBinds

### ISSUE THREAD

**Issue by Pr0xGaM3z** [Facepunch/garrysmod-issues#3142]
### Details
Tell us exactly what happens, every single detail that you can think of

Load GMod, try to change any bind or bind any key for specific text, example: "bind F "say Test Message"", console provides error shown in picture below and written below. Literally all I did was redownload the game after resetting my PC. Only installed GMod and it is giving me this error. Tried it on TF2 (yes ik this is a facepunch git but they both run off the same Source Engine.) and it does the same thing.

https://steamuserimages-a.akamaihd.net/ugc/84848791503288941/E6B9385DFCE6DF68680F21A65B47C4E6032C4C08/

### Steps to reproduce
Tell us how to reproduce the problem, step by step
1) Load Game
2) Have console open and options open
3) Go into options and change any key bind
4) Console says 
"userconfig.cfg not present; not executing
Host_WriteConfiguration: Wrote cfg/config.cfg
Using joystick 'Xbox360 controller' configuration
JOY_AXIS_X: mapped to Side (absolute)
JOY_AXIS_Y: mapped to Forward (absolute)
JOY_AXIS_Z: unmapped
JOY_AXIS_R: mapped to Look (absolute)
JOY_AXIS_U: mapped to Turn (absolute)
JOY_AXIS_B: unmapped
Advanced Joystick settings initialized"

**Comment by robotboy655** [comment]
It's not an error, it just means you have advanced controller settings enabled.
