### ISSUE TITLE
Server startup failure [cause not yet determined, sorry, currently investigating]

### ISSUE THREAD

**Issue by Faerachnidendro** [Facepunch/garrysmod-issues#3143]
### Details
Initially suspected workshop hosting to be the cause, currently investigating actual cause - sorry!

### Steps to reproduce
Attempt to start dedicated server starting on a map which is to be fetched from a hosted workshop collection.

**Comment by robotboy655** [comment]
Nothing to do with workshop, you are simply trying to start the server with no map, nothing to be done about this really.

**Comment by Faerachnidendro** [comment]
The map in question, ttt_richland_fix (http://steamcommunity.com/sharedfiles/filedetails/?id=572477267), does exist on the workshop and in the collection from which it is being hosted and has been downloaded by the server - although has not redownloaded not since the latest update which makes mention of changes to the way workshop is utilized.

Am I supposed to manually move the already downloaded workshops to the new directory?

**Comment by robotboy655** [comment]
No workshop addons load on your server. Where do you expect the server to load the map from when the filesystem doesn't know where map file is?

Your server should start from a map that will be there 100% of the time.

**Comment by Faerachnidendro** [comment]
With all due respect, 2 hours ago my server started on a workshop-hosted map, now it does not.

The previous behavior was that when starting up, the server would first download workshops from a hosted collection, when starting up the desired map the server would check the filesystem for the required file, if not found it would check the workshops contained in the hosted collection(having already downloaded any that were missing in the previous stage).
If the map was found within the workshops on the server, voila, the map would load.

It's not coming from thin air, it's simply failing to load - I do not know why, unless it is a case of the server searching for said workshops, in a different directory as of this update.

**Comment by robotboy655** [comment]
I repeat, it has nothing to do with any changes. Your server fails to load any workshop addons because it cannot connect to Steam. It would do the exactly the same thing if your server would not be able to connect to Steam before the update.

Your only options are to figure out why your server cannot connect to Steam (either your server host is blocking Steam, or Steam is having trouble) or extract your map addons.

**Comment by Faerachnidendro** [comment]
Okay that makes sense, with the exception of why my server is failing to connect - which could be for any number of reasons that I'm currently troubleshooting my way through.

Thank you for the clarification.

**Comment by Faerachnidendro** [comment]
Oh for fuck's sake... my fucking retarded antivirus hadn't properly triggered it's application-modification-protection module. Rebooting the machine fixed everything... I know, I know, I'm a pain in the arse - I hang my head in shame and apologise profusely.
