### ISSUE TITLE
Workshop download error

### ISSUE THREAD

**Issue by Winkeladvokat** [Facepunch/garrysmod-issues#3145]
I cant download most of the addons from workshop

53 new addons
WS: Finished!

WS: Processing 53 addons...
Processing addon 53: FBI Playermodels (107411755)...
   Addon needs downloading...
   Downloading [ 0% of 4.3 MB ]
   Download Failed! Code: 37
Processing addon 52: Hit Numbers (110871780)...
   Addon up to date, mounted!
Processing addon 51: TDMCars - Base Pack (112606459)...
   Addon up to date, mounted!
Processing addon 50: Hitman: Blood Money Agent 47 Player Model (123581457)...
   Addon needs downloading...
   Downloading [ 0% of 3.8 MB ]
   Download Failed! Code: 37
Processing addon 49: Security Guard Playermodels (169011381)...
   Addon needs downloading...
   Downloading [ 0% of 7.6 MB ]
   Download Failed! Code: 37

Processing addon 43: Improved Stacker (264467687)...
   Addon needs downloading...
   Downloading [ 200% of 24.7 KB ]
   Download Failed! Code: 37

**Comment by robotboy655** [comment]
It's a problem with Steam API, nothing we can do about it.
