### ISSUE TITLE
Pressing F11 with a CEF instance active in Dev Branch causes crash

### ISSUE THREAD

**Issue by ILOVEPIE** [Facepunch/garrysmod-issues#3147]
### Details
Causes a crash
### Steps to reproduce
Press F11 while a CEF frame is active in the Dev Branch, it causes a crash.

**Comment by willox** [comment]
Have you got F11 bound to any console commands?

**Comment by ILOVEPIE** [comment]
No, but CEF has it bound to togging a fullscreen view, If it helps there was also a video playing on youtube in CEF.

**Comment by robotboy655** [comment]
Closing as stale. If the issue still happens, please open a new report.
