### ISSUE TITLE
White screen, then "hl2.exe has stopped working" after a few seconds

### ISSUE THREAD

**Issue by Rapolis** [Facepunch/garrysmod-issues#3149]
### Details
This is weird, starting up the game just shows a white screen then this happens: http://prntscr.com/exvri1
I can't even get to the Facepunch loading screen with that. I tried changing DirectX versions and nothing happened. Tried reinstalling, didn't work. Tried removing some files like cfg and bin then verifying game integrity cache, didn't work. Restarting doesn't work too.
I haven't opened steam in a few months nor have played any games.

### Specs
Driver version: Latest
DirectX: 12
GPU: Overclocked MSI GTX 960
CPU: Quad-core Intel Core i5-4690
RAM: 16 GB
OS: Windows 10 Pro

### Launch options used
-windowed -noborder

### Steps to reproduce
[ONLY HAPPENS TO ME]

### Crash .mdmp file
https://www.dropbox.com/home?preview=Crash+Report.zip

I Hope you can help me solve this issue.

**Comment by willox** [comment]
That dropbox link will only work for you. You'll need to get a sharable link. If it's easier, just email your dumps to willox@facepunchstudios.com.

**Comment by Rapolis** [comment]
I sent it now.

[Patient waiting mode activated]
