### ISSUE TITLE
Client Crashes Since 4/17/2017 Update

### ISSUE THREAD

**Issue by Violat0r** [Facepunch/garrysmod-issues#3150]
### Details
With the latest update to GMod on 04-17-17 has caused crashes to occur to clients. 

I run many servers with different gamemodes. Ever since the update many people have complained to me that they started crashing. The crashing seems to be random and I cannot find a single addon that may be causing it. We have 5 common addons across these servers being  motdgd, lunera, tmysql, and ulx/ulib. We found that removing lunera and jukebox helped reduce crashes but it does still happen while people are playing the game. People are reporting crashing when loading in when lunera opens or opening jukebox however a crash can happen at any time when with those addons disabled. I have also crashed a few times and I am only subscribed to one item on workshop [TTT Advanced Disguiser](https://steamcommunity.com/sharedfiles/filedetails/?id=606792331). We did not test tmysql since it is serverside and shouldn't have any impact on clients. From our testing, it does not seem like it is any one addon that is causing the crashing but something from the update.

May or may not be relevant but one user reported [Rainbow blood](https://steamcommunity.com/sharedfiles/filedetails/?id=168490861) has stopped working since the update.

Also the update broke in jukebox a cap of how many songs may be displayed at one time. I have reported this issue to the dev but I figured this may somehow be relevant as well.

Common addons:
[lunera](https://www.gmodstore.com/scripts/view/1621/lunera-the-motd-system-plaxus-collection)
[jukebox](https://www.gmodstore.com/scripts/view/1505/garrys-mod-jukebox-youtube-music-player)
[tmysql](https://github.com/bkacjios/gm_tmysql4)
[ulx](https://github.com/TeamUlysses/ulx)
[ulib](https://github.com/TeamUlysses/ulib)

Crash dumps separated by user:
https://www.dropbox.com/s/yy66pnt9d4uq9o7/dumps.zip?dl=0

### Steps to reproduce
Load into a server.
Trying to close lunera when finished loading by clicking x.

Pressing F7 to load Jukebox.

Playing the game.

**Comment by willox** [comment]
This only happens when multi-core rendering isn't enabled. We'll get a hotfix out as soon as possible.

**Comment by Jake3231** [comment]
> We'll get a hotfix out as soon as possible.

Violat0r, can this issue still be reproduced after the hotfix was released?
