### ISSUE TITLE
Crash on setting position of a prop outside of the world in dev

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3155]
### Details
The stacker addon from workshop is still capable of crashing servers and clients.
http://steamcommunity.com/sharedfiles/filedetails/?id=104479831

This causes props to glitch through walls etc. when used or instantly crashes the server/listen host on using high numbers like 99999999999999.

### Steps to reproduce
Use stacker with abnormal numbers.

**Comment by robotboy655** [comment]
Honestly its the fault of the mod for not controlling user input.

**Comment by mcNuggets1** [comment]
I still use it to crash other servers, so I guess I don't want it to be fixed, but I want to report everything either.
It's a conflict.

**Comment by Damianu** [comment]
Works with wiremod and holograms too, at least on linux.

**Comment by robotboy655** [comment]
This should be fixed as much as we can. The rest can be taken care by mods, by not spawning entities outside of the max map boundaries.
