### ISSUE TITLE
Shadow bugs

### ISSUE THREAD

**Issue by hgAspirin9999** [Facepunch/garrysmod-issues#3158]
### Details
Broken shadows on custom maps 

### Steps to reproduce
1)Start dark map with some light sources (I used rp_lr_refuge_v1)
![20170422120811_1](https://cloud.githubusercontent.com/assets/27885343/25303230/3785ce30-2757-11e7-8984-188682a46f8a.jpg)
![20170422122210_1](https://cloud.githubusercontent.com/assets/27885343/25303231/3d2197ca-2757-11e7-8334-e628e61e306a.jpg)

![20170422123158_1](https://cloud.githubusercontent.com/assets/27885343/25303260/b693cd58-2757-11e7-9c83-5afe48167d4c.jpg)
![20170422124000_1](https://cloud.githubusercontent.com/assets/27885343/25303330/f15e1e92-2758-11e7-95d8-5ac02ebf5290.jpg)

**Comment by willox** [comment]
Does this stop happening if you run `r_radiosity 4` in your console? SHIFT+ESC will open the console.

**Comment by hgAspirin9999** [comment]
No, it did not work.

**Comment by willox** [comment]
Sorry, I meant `r_radiosity 3`.

**Comment by hgAspirin9999** [comment]
Thank you, this glow has gone.

**Comment by Kefta** [comment]
What does 4 even change behaviourly from 3? It isn't documented in the convar help text.
