### ISSUE TITLE
Crash when decaling tdm cars

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3159]
### Details
https://www.dropbox.com/s/yhxmahc2z5b2gbe/hl2_170422_crash_2017_4_23T11_19_38C0.mdmp?dl=0
still happens on stable with newest update

### Steps to reproduce
decal on tdm car?

**Comment by willox** [comment]
What model/car was this happening with?

**Comment by mcNuggets1** [comment]
I'll try again, as I forgot about that.

**Comment by mcNuggets1** [comment]
Tested.

Does only happen on "camarozl1tdm"

Chevrolet Camaro ZL1

**Comment by mcNuggets1** [comment]
Does happen on some Bugattis either.

**Comment by SharpOB** [comment]
Well then, this indicates it is likely a bug with the models themselves, not the game. Take it up with the addon author.

**Comment by goigle** [comment]
This is happening on more than just TDM cars

**Comment by mcNuggets1** [comment]
It does happen for a lot of player models or high poly textures.
This issue needs some attention finally.

**Comment by robotboy655** [comment]
Should be fixed on Dev. The initial fix was for a bit different thing (Too many vertices caused crash on memory allocation) which is why it didn't fix this case.

**Comment by mcNuggets1** [comment]
Could you look into actually placing decals onto high poly models?
It doesn't crash anymore, but still there should be a decal.
