### ISSUE TITLE
Crash with Houndeye squads

### ISSUE THREAD

**Issue by darkpikmin99** [Facepunch/garrysmod-issues#3160]
### Details
A Half-Life Source houndeye inside a squad crashes the game after it has killed something.

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_170422_crash_2017_4_23T13_38_39C0.mdmp

### Steps to reproduce
Spawn 2-4 Houndeyes (Half-Life Source not Half-Life Renaissance)
Assign all Houndeyes to a squad (name doesn't matter)
Let the Houndeyes kill something.
*GAMECRASHES*

**Comment by robotboy655** [comment]
Thanks for not posting a crash dump that we can download.

**Comment by darkpikmin99** [comment]
I wanted to but it wasn't supported apparently. Is there a way to get the .mdmp file to download? (Visual Studio wasn't working and I got slightly impatient)

**Comment by robotboy655** [comment]
Nothing happens when I let them kill me or HL:S NPCs. Assuming I fixed it yesterday on Dev branch,

**Comment by darkpikmin99** [comment]
I was in dev branch when the crash happened. If its not crashing normally, maybe it might be an addon or some other condition. (sometimes I had changed them to be friendly rather then hostile, or I had them with squads of other npcs that WEREN'T Houndeyes.)

**Comment by robotboy655** [comment]
Post the .mdmp or actual steps to reproduce then.

**Comment by Bo98** [comment]
> Is there a way to get the .mdmp file to download? 

Don't click "share without download" (or whatever it is) and use the other link.

**Comment by darkpikmin99** [comment]
https://www.dropbox.com/s/0ac9ojsimcx85za/hl2_170422_crash_2017_4_23T14_58_49C0.mdmp?dl=0
Crash dump file for download (hopefully)

**Comment by robotboy655** [comment]
Well I can tell you one thing - the crash doesn't seem to be from the Dev branch, either way, the issue should be fixed on Dev branch.
