### ISSUE TITLE
Game update broke mp3 files

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#3161]
### Details
One of the game updates in April broke playback of mp3 files.

The following errors appear in console very frequently.
```
Couldn't create BASS audio stream (unsupported file format)
Failed to load sound "music\morbus_human_victory.mp3", file probably missing from disk/repository
```

### Steps to reproduce
function EndSound() calls surface.PlayerSound [here](https://github.com/Remscar/Morbus/blob/4079e75eed29798322d01c3f6220b4c31bc03cd4/MorbusGamemode/gamemodes/morbusgame/gamemode/cl_init.lua#L151-L159).

And the workshop pack holding the sound file is mounted after the client joins like this...

**Server Side**
```
function GM:PlayerInitialSpawn( Player player )
   if ValidEntity(player) then 
	umsg.Start("Morbus_SpawnInitialized",player)
	umsg.End()
   end
end
```

**Client Side**
```
function InitWorkshopContent()	
	timer.Simple(10, function()				
		-- Download and mount morbus sound pack 
		steamworks.FileInfo( 811776488, function( result )
			if result.installed == false then
				steamworks.Download( result.fileid, true, function( name )
					game.MountGMA( name )
				end )
			end
		end )
	end)
end
usermessage.Hook("Morbus_SpawnInitialized", InitWorkshopContent)
```

**Comment by robotboy655** [comment]
If that was the case, a lot of complaints about this would happen. Something on your PC specifically was changed that made the mp3 playback impossible.

Entering ```play music/hl1_song10.mp3``` into my console makes the sound play without any error.
