### ISSUE TITLE
Missing HL1 entities

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3170]
- monster_turret
- monster_miniturret
- monster_sentry
- monster_apache
- monster_osprey
- speaker
- weaponbox (if the other weapons are ever added)

**Comment by Kefta** [comment]
Unrelated but odd, the HL1 hand-grenade weapon can be used in Garry's Mod, and is the only HL1 engine weapon that seems to be implemented.

**Comment by mcNuggets1** [comment]
Is it difficult to port new weapons from other games to gmod by the way?

**Comment by Kefta** [comment]
If you mean port to SWEPs, then it does take a little work for accurate ports and replicating spread/recoil algorithms.

**Comment by mcNuggets1** [comment]
No I mean C++ weapons.

**Comment by Kefta** [comment]
As a module, I've never seen it done but I'm sure it's possible. Internally with access to GMod source, it's not difficult at all since all weapons between Source games follow the same registration format, although prediction might be screwy for some games since CS:S uses a slightly different system.

**Comment by Kefta** [comment]
Added some additional entities. This should be everything missing minus weapons/weapon-related ents. Except item_longjump which wouldn't work anyway.

**Comment by Kefta** [comment]
Just realised this is a duplicate of https://github.com/Facepunch/garrysmod-requests/issues/338.
