### ISSUE TITLE
Workshop Fonts not mountig

### ISSUE THREAD

**Issue by ApertureDevelopment** [Facepunch/garrysmod-issues#3171]
### Details
When you join a server which downloads stuff on the client via ressource.AddWorkshop() it seems to not mounting fonts. Means: Custom fonts aren't loading which causes bugs with some addons , like the regular GMod font at that size doesen't fit in the DFrame. It's an annoying bug which I noticed a while ago while trying to setup my server.

### Steps to reproduce
Add Custom Fonts via ressource.AddWorkshop() and try to use them.

**Comment by captain1242** [comment]
It works when you manually add the Addons. Just not when you try to add them via ressource.AddWorkshop()
