### ISSUE TITLE
ply:Give crashes with second argument true.

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#3175]
### Details 
ply:Give crashes if the crowbar already exists with the second argument true.

### Steps to reproduce
lua_run hook.Add("PlayerSpawn", "test", function(ply) ply:StripWeapons() ply:Give("weapon_crowbar", true) ply:Give("weapon_crowbar", true) end)
lua_run Entity(1):Spawn()

**Comment by robotboy655** [comment]
Fixed.
