### ISSUE TITLE
[Linux] Game crash

### ISSUE THREAD

**Issue by Jcraft-Miner** [Facepunch/garrysmod-issues#3177]
Distro Ubuntu Studio 16.04
Graphics card nVidia GTX 950
Graphics driver nvidia-375

Logs:
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 2097152, Total Avail: 2097152, Current Avail: 1273280
GL_MAX_SAMPLES_EXT: 32
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 3

The game doesn't get past the blue screen that says loading, it just crashes. It wont show the actual loading bar either.

I have tried to delete all workshop items, verified integrity of game files, and i deleted the game and redownloaded and nothing.

**Comment by Jcraft-Miner** [comment]
Let me know if the core dump would be useful because its 642 Mb

**Comment by willox** [comment]
Does this happen on the development branch? 

```
- Exit the game
- Right click on Garry's Mod in Steam and select Properties
- Go to Betas tab and select the desired branch
```

**Comment by Jcraft-Miner** [comment]
Yes, the same thing happens on the dev build.

**Comment by willox** [comment]
You can email core dumps to willox@facepunchstudios.com. They'll be a lot smaller if you zip them first.

**Comment by hjri** [comment]
I have this issue as well on debian testing. I managed to get the batcktrace in gdb:
```
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
__strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:94
94      ../sysdeps/i386/i686/multiarch/../../i586/strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:94
#1  0xf7e208ab in __GI___strdup (s=0x0) at strdup.c:41
#2  0xd5538ccf in ?? () from /media/hdd/hdd/houka/steam/SteamApps/common/GarrysMod/bin/libbass.so
```
looks like problem in libbass?

**Comment by zerobeat4393** [comment]
Have this same exact issue but only with starwars RP. Literally the only thing i get this error on is starwars RP servers. It downloads all server content then at sending client info it closes. The fix to this has to be somewhere, it's probably so simple too, like downloading a repo

**Comment by FFG-Blinkenn** [comment]
Note about the crash: ram usage will go to about ~4 GB and then crash. On basically any server with lots of content. I had enough ram and swap memory as well, any memory switched to swap will remain in memory after the crash.

**Comment by TheDoctorLink** [comment]
I have the same issue when starting up the game. I'm running on Debian. Completely re-installing the game, verifying files or using the dev branch does not do anything for me either.

**Comment by Jcraft-Miner** [comment]
I have solved the issue, it seems that the libbass.so library provided in garry's mod has some strange issues on some computers, downloading a new version of libbass.so and replacing the one in the garry's mod folder has resolved the issue entirely.
