### ISSUE TITLE
PLAYER:Name cuts off names

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#3178]
### Details
Steams name limit is 32 characters, PLAYER:Name cuts off at 31

### Steps to reproduce
Make your name 32 characters

**Comment by CaptainPRICE** [comment]
`Player.Name` is alias of `Player.Nick` function, just saying.
I think its engine bug, not really GMod-only issue (tested).

**Comment by mcNuggets1** [comment]
They still should fix it, even if it's an source issue.

**Comment by robotboy655** [comment]
This should be solved in the next update.
