### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3179]
### Details
https://wiki.garrysmod.com/page/PhysObj/CalculateForceOffset
This function does error, though the given args are valid and NOT NIL!

Error:
bad argument #2 to '__mul' (number expected, got nil)

(Does not make sense, as argument #2 needs to be a vector!)

Now, I have tried really anything to make this shit not error.
I even added a check for a vector, used IsValid checks and != nil checks.

( THIS FUNCTION IS USED IN HOVERBOARDS-ADDON AND DOES ERROR THERE TOO BY THE WAY )

### Steps to reproduce
Unknown actually, I don't know the cause, but in very rare cases, this function does error.

**Comment by Kefta** [comment]
The error you posted isn't from that function, it's saying you're doing some_vector * nil, and it's expecting scalar multiplication.

**Comment by mcNuggets1** [comment]
It is from the exact same line.

**Comment by bigdogmat** [comment]
Because you did the multiplication operation in one of the arguments

**Comment by mcNuggets1** [comment]
I gotta say, I am an idiot.
