### ISSUE TITLE
No crash dumps on windows

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#3182]
### Details
Windows SRCDS doesn't make crash dumps

### Steps to reproduce
Crash server, get annoyed, rinse and repeat

**Comment by aStonedPenguin** [comment]
Apparently it's broken on linux too

**Comment by MStruntze** [comment]
The usual information dump to debug.log as well as a core dump seems to still work on linux? Unless  this is caused by the hotfix of course, I haven't updated for that one just yet.

**Comment by Priorr** [comment]
+1 please fix, thanks

**Comment by robotboy655** [comment]
I am fairly certain this boiled down to that specific case being a hang not a crash.
