### ISSUE TITLE
SRCDS doesn't mount collections

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-issues#3185]
### Details

> WS: Fetching collection info...
> Processing collection 627607304...
>    Collection ''
>    Reported 0 items, skipping
> WS: Finished!
> 
> WS: Processing 0 addons...
> WS: Finished!

### Steps to reproduce
Run a server with Workshop collection on Windows.

**Comment by uRandomAlex** [comment]
I've found an old version of SRCDS on my computer and it works perfectly. May be you can add a launch parameter to use old Workshop mount system for servers?

**Comment by robotboy655** [comment]
Works for me with that same collection.

!()[[http://i.imgur.com/9c1QJQ3.png]

Keep in mind that your collection MUST be visible to everyone, i.e. must not be set to hidden or friends only.

**Comment by uRandomAlex** [comment]
Why it does not for me then? Addons and binary modules are not the cause because they are loaded after Workshop collections.

**Comment by robotboy655** [comment]
What OS? Do you have up to date Steam binaries on your server? Does your server have direct connection to Steam?

**Comment by uRandomAlex** [comment]
My OS is Windows Server 2008 R2 Standard. I don't have Steam installed on my server. It seems that it has direct connection to Steam.

**Comment by robotboy655** [comment]
I have added better errors when collection info fails to Dev branch, please switch to it and see the console output then.

**Comment by uRandomAlex** [comment]
It seems that the bug occurs randomly because I have just started this server with no problems. Is dev branch compatible with release branch? If it is, I will switch and tell you if I will encounter this again.

**Comment by robotboy655** [comment]
It should be compatible, yes.

**Comment by uRandomAlex** [comment]
I get the same message on dev branch.

> Initializing Steam libraries for Workshop..
> Waiting for Steam to log us in......
> WS: Fetching collection info...
> Processing collection 627607304...
>    Collection ''
>    Reported 0 items, skipping
> WS: Finished!
> 
> WS: Processing 0 addons...
> WS: Finished!

**Comment by robotboy655** [comment]
I've added some temporary debug output for this part, please try again and send me the log.

But it seems that Steam just doesn't return any info about the collection.

**Comment by robotboy655** [comment]
Anything?

**Comment by uRandomAlex** [comment]
I can't reproduce this bug right now. SRCDS either lose connection to Steam after logging in and SRCDS seems to load cached version of Workshop collection, or it loses connection before logging in and it doesn't load Workshop collection.
