### ISSUE TITLE
modern valve games arent that compatible with garrys mod

### ISSUE THREAD

**Issue by TheRealLuke** [Facepunch/garrysmod-issues#3186]
newer valve games have a problem with garrys mod such as counter strike global offensive and left 4 dead.
there is a picture below of one of the problems with the csgo player ragdoll.
![capture](https://cloud.githubusercontent.com/assets/28544908/25824096/08d6dba6-3436-11e7-8b30-a7860804dea7.PNG)

as you can see the ragdolls arms are bent back in a deformed way. the left for dead ragdolls have parts of there bodys see threw.  
facepunch please fix this if you can thanks

**Comment by Kefta** [comment]
That's because newer games aren't technically "compatible" with GMod, but a hack was implemented to allow the models to load.

**Comment by TheRealLuke** [comment]
will there be a garrys mod 2 or something    that can be using newer
graphics and be compatible

**Comment by Kefta** [comment]
No

**Comment by Jake3231** [comment]
> will there be a garrys mod 2 or something    that can be using newer
graphics and be compatible

I remember reading something about a Garry's Mod sequel, which is described in [this interview](http://www.pcgamer.com/a-garrys-mod-sequel-is-in-the-works/) with Garry.
