### ISSUE TITLE
Opening app Issue

### ISSUE THREAD

**Issue by PrimaryLists** [Facepunch/garrysmod-issues#3187]
### Details
Whenever I'm  opening up the Garry's mod app it takes 30 mins + .  Even though after 30 min + it still wouldn't open. Also I tried the same process from opening garrys mod in steam and still didn't work

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
