### ISSUE TITLE
Lua error on dev branch

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3189]
### Details
[ERROR] lua/entities/widget_bones.lua:19: attempt to compare nil with number
  1. GetParentPos - lua/entities/widget_bones.lua:19
   2. unknown - lua/entities/widget_bones.lua:63
    3. TraceLine - [C]:-1
     4. UpdateHovered - lua/includes/modules/widget.lua:46
      5. PlayerTick - lua/includes/modules/widget.lua:89
       6. fn - lua/includes/modules/widget.lua:149

### Steps to reproduce
Bone manipulate npc
Shoot npc

**Comment by robotboy655** [comment]
Fixd
