### ISSUE TITLE
why does the game crash when i try to load a LFD map?

### ISSUE THREAD

**Issue by TheRealLuke** [Facepunch/garrysmod-issues#3191]
any time i try to load a LFD map garrys mod just crashes for some reason
please help me if you know why this is thanks

**Comment by Kefta** [comment]
Can you post the mdmp that was created?

**Comment by robotboy655** [comment]
The No Mercy (Hospital) maps from L4D1 won't work due to some models crashing the game, if that is the map you hvae problems with.

**Comment by TheRealLuke** [comment]
The map I'm having trouble with is the airport_runway map

**Comment by TheRealLuke** [comment]
Kefta, what is mdmp?

**Comment by Kefta** [comment]
It should be located in your ~/common/garrysmod/ folder
