### ISSUE TITLE
util.IsValidModel returns true for model "models/error.mdl" ?

### ISSUE THREAD

**Issue by Electfried** [Facepunch/garrysmod-issues#3192]
When attempting to do a check for a valid model using the function util.IsValidModel would you not expect it to return false for models/error.mdl?

lua_run_cl print(util.IsValidModel("models/error.mdl"))

**Comment by Kefta** [comment]
That's because it's an existing model and isn't an anim file. This is expected behaviour

**Comment by Electfried** [comment]
Yes, I understand it's an existing model but the model serves literally no other purpose than to replace invalid models. This model doesn't have any bone physics (my main problem with it) or anything of value on it other than it's main purpose, so I don't see a problem with returning false.

**Comment by Kefta** [comment]
It's still a valid model in the regard the function handles invalidity. I would recommend just checking if the model is valid and isn't error.mdl in whatever context you need it.
