### ISSUE TITLE
Hook is not called

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3194]
### Details
https://wiki.garrysmod.com/page/GM/CreateClientsideRagdoll isn't called when a death ragdoll of a player spawns.

### Steps to reproduce
Use the hook

**Comment by robotboy655** [comment]
Yes, and it's not supposed to because the ragdoll is serverside.

Run ```PrintTable(ents.FindByClass("hl2*"))```

hl2mp_ragdoll is the entity created by https://wiki.garrysmod.com/page/Player/CreateRagdoll when a player dies

**Comment by mcNuggets1** [comment]
Is there a hook then to influence the spawn behaviour?

**Comment by robotboy655** [comment]
Actually the issue is different, the player ragdolls are created differently on client, I may be able to force it to call the hook.

**Comment by robotboy655** [comment]
You can just not call Player:CreateRagdoll if you dont want the player ragdoll.

**Comment by robotboy655** [comment]
Or use https://wiki.garrysmod.com/page/Player/GetRagdollEntity

**Comment by mcNuggets1** [comment]
Thanks for now.

**Comment by robotboy655** [comment]
Added a hack

**Comment by mcNuggets1** [comment]
Is this online on dev version?

**Comment by robotboy655** [comment]
should be

**Comment by mcNuggets1** [comment]
works.
Thx
