### ISSUE TITLE
give worldspawn kills physics

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3195]
### Details
"give worldspawn" kills Physics.

### Steps to reproduce
"give worldspawn" in console with sv_cheats

**Comment by Kefta** [comment]
Could you at least make the title descriptive?

**Comment by thegrb93** [comment]
That's pretty funny, but there's a million ent_fire/give/whatever commands that break the game. This isn't worth reporting.

**Comment by robotboy655** [comment]
Not to mention all of those require sv_cheats.

**Comment by uRandomAlex** [comment]
May be Player:Give('worldspawn') crashes physics too? If it is, I think it
should be fixed. Sometimes finding the source of weird behavior is annoying
because it leaves no crashdumps or errors.

20 мая 2017 г. 6:30 пользователь "Rubat" <notifications@github.com> написал:

**Comment by Kefta** [comment]
It does, but again there are so many "give class" cases that will cause issues. It's a case of don't do it.

**Comment by mcNuggets1** [comment]
However give player returns a null entity.
While ent_spawn crashs game.

**Comment by Kefta** [comment]
Same logic applies to ent_spawn

**Comment by mcNuggets1** [comment]
I meant running "give player" does not crash game instead errors, while "ent_spawn player" crashs.

**Comment by Kefta** [comment]
Yes, and my point still stands. Creating exceptions for everything that causes undesired behaviour or crashes with give or ent_spawn would be a fruitless task.
