### ISSUE TITLE
GM:PlayerButtonDown/GM:PlayerButtonUp are called multiple times on Multiplayer

### ISSUE THREAD

**Issue by TheOpalium** [Facepunch/garrysmod-issues#3197]
### Details
It seems this hook is called multiple times on multiplayer. 3 to 5 times, to be precise. Tried it on different game modes and it doesn't seem to affect it. Using the latest GMod server and client.
One more thing I noticed is that Up seems to be called once/twice more than Down. But that might be something else.

### Steps to reproduce
Just hook into the function. Here's what I used to test:

`hook.Add("PlayerButtonUp", "TestPBU", function(ply, btn)`
   `ply:PrintMessage(HUD_PRINTTALK, "Up "..btn.." from "..ply:Nick())`
`end)`

`hook.Add("PlayerButtonDown", "TestPBD", function(ply, btn)`
   `ply:PrintMessage(HUD_PRINTTALK, "Down "..btn.." from "..ply:Nick())`
`end)`

**Comment by bigdogmat** [comment]
Both of those hooks are predicted, use [IsFirstTimePredicted](http://wiki.garrysmod.com/page/Global/IsFirstTimePredicted).

**Comment by Jvs34** [comment]
Just as an addendum, those hooks won't be called in singleplayer on the client because of prediction, so make sure to account for that if you care.

**Comment by TheOpalium** [comment]
Gotcha, my bad. Ignore this.

**Comment by robotboy655** [comment]
For anyone who might find themselves here, the wiki page for the function has a note about this that links to an article with more information about prediction.

http://wiki.garrysmod.com/page/GM/PlayerButtonDown
