### ISSUE TITLE
Base Gamemode - "impulse" console command crash

### ISSUE THREAD

**Issue by OmegaExtern** [Facepunch/garrysmod-issues#3198]
### Details
Garry's Mod immediately crashes to desktop (without any error dialog boxes).
Sorry, I can't upload a (mini) dump file at the moment. It may be worth to say that I am running it on Windows OS.

#### Dump Summary
Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information: Not Present

### Steps to reproduce
1. Launch Garry's Mod with the following launch options:
`-console -low -noworkshop -noaddons -sw -w 800 -h 600 +sv_cheats 1 +maxplayers 1 +gamemode base +map gm_flatgrass`
2. Once you are in-game, open up Console and submit `impulse "200";` ([wiki](https://developer.valvesoftware.com/wiki/Impulse)).

Unfortunately `200` does not seem to be the only one, [see here for more](https://github.com/Facepunch/garrysmod-issues/issues/3198#issuecomment-302911108)!

**Comment by OmegaExtern** [comment]
[Go to forum thread at Facepunch](https://facepunch.com/showthread.php?t=1564723).

---

So, giving a weapon to a player seems to fix the crash:
```lua
Entity(1):Give("weapon_pistol")
```

The question is, how would you fix it without giving a weapon?

**Comment by OmegaExtern** [comment]
For the joy, I've decided to code a simple brute-forcer script to see if there are more codes which would cause gmod to crash. And unfortunately, I have found even more impulse codes for crashin' it...
10+ and counting:
```
200
456
712
968
1224
1480
1736
1992
2248
2504
2760
3016
3272
// And more....
```

**Comment by robotboy655** [comment]
This is exactly why SetActiveWeapon(NULL) is not a thing.

Fixed
