### ISSUE TITLE
Entity:ManipulateBoneScale() fails the 1st time with CSEnt entities

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#3201]
Hey there,

### Details
When I manipulate the bone scale on a clientside model, it only works starting from the 2nd I call [`Entity:ManipulateBoneScale()`](http://wiki.garrysmod.com/page/Entity/ManipulateBoneScale), this is a little disturbing. On the first call, nothing seem to happen.

It's like there is a required flag that applies after manipulating the bone, making the bone manipulation not to occur.

### Steps to reproduce
On *gm_construct* you can do this:
```lua
lua_run_cl BARIL = ClientsideModel( "models/props_c17/oildrum001.mdl", RENDERGROUP_OPAQUE )
lua_run_cl BARIL:SetPos( Vector( 192.39, -1212.77, -143.51 ) )
lua_run_cl BARIL:SetAngles( Angle( 0, 122.76, 0 ) )
lua_run_cl BARIL:ManipulateBoneScale( 0, Vector( 1,1,2 ) )
lua_run_cl BARIL:ManipulateBoneScale( 0, Vector( 1,1,2 ) )
```

### Greetings
Momo :heart:

**Comment by thegrb93** [comment]
I've also noticed this. Luckily is easy to workaround.

**Comment by robotboy655** [comment]
Fixed
