### ISSUE TITLE
Potential server browser enhancement; Could increase browser speed. 

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-issues#3202]
These are features that are not original as in I didn't invent the concepts/features. I am only applying them here from other games. I believe that if implemented correctly as a whole a genuine improvement to server browser speed will be made with only minor changes to the current menu. 

## Problems with the current menu: 

- Speed of listing off all the servers.
- Population of the menu between "Favorites", "History", "Local Network", and "Internet" are not done at the same time. 

### Restructuring the menu layout
Restructuring the multiplayer menu layout is something needed for an improved user experience. Something that is more user friendly and universal to the look and feel of past browsers should result in a better overall menu. 

The following can be done to succeed at the above: 

- Rename "Find Multiplayer Game" to "Multiplayer Server Browser" on the first screen for gmod. This is a "no big deal" type thing but it is more inline with what is found after clicking the button: a server browser. 
- [I created a quick reference image](http://imgur.com/gallery/3EjJu) for what I had in mind for the menu changes. It has a large focus on filters to basically reduce the amount of stuff that has to be brought into the menu while still allowing for the same amount of stuff if the player desires it. Obviously Im not a color palette genius but in terms of functionality this is a huge step forward. 
- Where it says "Updating available gamemodes.." that is supposed to be a "refreshing/loading" message spot. It allows for the user to know what exactly is being done. When not loading this can also be used to rotate through hints, announcements, etc. 
- I forgot "Map" but it should have been on the top bar alongside the others. 
- Gamemode Image can be used when just "Internet" is tapped. That's basically the "Ill see everything please" button so I thought attaching the image may look nice. Also being able to doing the "Sort By" function by clicking the "GM Image" text could then bunch all the servers together. 

Anyways. That's the idea. Input would be appreciated.

**Comment by Jake3231** [comment]
This seems to be a really cool idea, especially judging from the image you provided.  I would suggest that you move this issue to [garrysmod-requests](https://github.com/Facepunch/garrysmod-requests).
