### ISSUE TITLE
Certain nav files packed into maps (EG: CSS Maps) cause an engine crash

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#3204]
Just as the title says, If a nav file is packed into the BSP itself then it will cause an engine crash upon trying to load the map.

You can re-create this rather easily by just grabbing a map with a nav mesh built into it, for example de_bretagne_2_se ( Which can be found here: http://gamebanana.com/maps/download/190649 )

**Comment by robotboy655** [comment]
It's already fixed on the Dev branch. Next time test the Dev branch before posting anything here.
