### ISSUE TITLE
Linux physics gone wild when constraint.Weld Worldspawn to Small Prop

### ISSUE THREAD

**Issue by gamerpaddy** [Facepunch/garrysmod-issues#3205]
Hello i just noticed an issue which i never noticed before.
It Only happens on Linux servers, it doesnt on Windows and Singleplayer. 
I tried it on 2 different servers, works 100% of the time. Both running tick 66.

By using the Weld tool attaching **Worldspawn (Entity(0))** to a small **physics entity** (prop physics, sents, weapons) causes it to freak out throwing this error:
```
Crazy origin, angles, velocity, angular velocity on entity [1010][prop_physics]
	Origin:           [-nan, -nan, nan]
	Angles:           [-nan, nan, 180.000000]
	Velocity:         [-nan, -nan, nan]
	Angular Velocity: [-nan, -nan, nan]
Defusing!
Removing!
```

It only work with small models, changing the weight doesnt matter.

Welding it the other way around (prop to world) doesnt make them freak out.
altering the physenv settings from default to a higher or lower value doesnt fix it.

Any ideas?

**Comment by FFG-Blinkenn** [comment]
Tested on a windows server, it does indeed happen on windows servers as well.

**Comment by FFG-Blinkenn** [comment]
To reproduce: 
1. Spawn a models/gibs/hgibs.mdl
2. Use the welder tool to the world, then the prop.
3. Crazy Physics inbound.

**Comment by robotboy655** [comment]
Added some code to the constraint library that should help prevent this.
