### ISSUE TITLE
[MAC] filesystem_stdio.dylib!

### ISSUE THREAD

**Issue by paulpall** [Facepunch/garrysmod-issues#3206]
I have a MacPro1,1 running 10.6.8. As far as I know, I meet all the requirements mentioned in Steam, yet when I try running Garry's Mod, I get the following error:
"AppFramework : Unable to load module /Users/(My Account)/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/filesystem_stdio.dylib!"
 I've also included a screenshot of the error. I'm terribly sorry if this issue is already mentioned and I missed it.
![screenshot](https://cloud.githubusercontent.com/assets/28998696/26520743/f3fc20ec-42e0-11e7-8352-ab2c6cc764c6.png)

**Comment by robotboy655** [comment]
Please contact the support website for support with the game.

https://support.facepunchstudios.com/
