### ISSUE TITLE
Male human models invisible?

### ISSUE THREAD

**Issue by aVeXBoss** [Facepunch/garrysmod-issues#3207]
For some reason my male human npc bodies aren't showing only their head but the female npcs I can see just fine how do I fix this so I can see the males

**Comment by SharpOB** [comment]
Take a screenshot of how the models appear. Also, check the console for any errors, and screenshot them. Some information on your setup would be helpful, too, i.e. do you use Linux?

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
