### ISSUE TITLE
HTML error at server browser: white screen, console spam

### ISSUE THREAD

**Issue by SharpOB** [Facepunch/garrysmod-issues#3208]
![20170529105634_1](https://cloud.githubusercontent.com/assets/24550634/26546022/dffa237a-445f-11e7-9007-6e839c2a73af.jpg)

### Details
For some odd reason, Garry's Mod has began, just today, to make the screen turn white when populating the server list. This happens for some time with the console spammed by the error, but after a couple minutes, is spammed by a different error. There _may_ be other errors printed to the console that I can't see due to the spam. These errors make it clear what is happening:

`[HTML] :1: Uncaught ReferenceError: AddServer is not defined`

`[HTML] :1: Uncaught ReferenceError: FinishedServeres is not defined` [sic]

### Steps to reproduce
https://www.youtube.com/watch?v=Q-kreYhzSQE

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

**Comment by robotboy655** [comment]
verify you game cache on steam
