### ISSUE TITLE
Server doesn't show in the serverbrowser if it has no players

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-issues#3212]
### Details
My servers don't show in the serverbrowser if they have no players. Bots don't count as players in this case. Steam API shows that my servers are listed (http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=37.230.210.119&format=json), but they don't show in the 'Internet' tab, though I can see them in my Favorites and I can connect to them. It didn't happen when I was hosted on a Windows server with 'April 2017 Update Hotfix' update. Now I use Debian 8 with the latest stable game update. I don't think it's the fault of my addons because I ran the same addons on my old machine.

### Steps to reproduce
1. Run a Linux server on Debian 8 with latest stable game update
2. Check your serverbrowser.
3. Join your server or ask someone to do so.
4. Check your serverbrowser again.

**Comment by robotboy655** [comment]
Empty servers are only shown after all non empty servers load.
