### ISSUE TITLE
Changelevel to new map version freezes the game

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#3215]
### Details
Title, my theory is that the map is cached somehow but not invalidated by the bsp update

If I instead disconnect and create a new listen server (without restarting gmod) it works fine.

I could not generate any crash dump since it simply freezes

When I tried it in a singleplayer game it worked, but the map ingame was completely bonkers

### Steps to reproduce
1. Compile a map, put it in maps folder
2. Start a listen server with the map (multiplayer)
3. Test around, compile the map again and overwrite the existing .bsp with the new one
4. Do changelevel to the same level, the loading screen freezes indefinitely on "Retrieving game data..."

**Comment by G-Force007** [comment]
Same as typing retry in console

**Comment by robotboy655** [comment]
I never experienced this myself when compiling maps, so closing as stale report.

If you do experience this, please provide the 2 map files and exact steps to reproduce the crash/hang.
