### ISSUE TITLE
Entity.GetMaterials only returns a maximum of 127 materials (assuming the entity has more)

### ISSUE THREAD

**Issue by bull29** [Facepunch/garrysmod-issues#3216]
My original intention was to use this function to fetch every material from that the map uses, not sure how easy this is to change or even possible to

**Comment by Python1320** [comment]
You can actually parse the materials from the map yourself in the meanwhile: https://github.com/CapsAdmin/tod/blob/master/lua/autorun/tod.lua#L240

**Comment by robotboy655** [comment]
Entity.GetModelMaterials will now return complete list of materials if used on a brush model, including the map. Maximum for models is reduced to 128 (from 256) which matches other places in the engine when it comes to model materials. (They are limited to 32 by studiomdl anyway)
