### ISSUE TITLE
Material type problem for Gravitygun

### ISSUE THREAD

**Issue by Driven49** [Facepunch/garrysmod-issues#3218]
Hi,

I noticed that the models compiled with **$SurfaceProp** on **MAT_FLESH (70)** are not taken by the **Gravitygun**.
It's quite painful to see models that you can not take with the **Gravitygun**.
If you could fix this problem it would be really nice for the **upcoming update of Garry's Mod**.

This problem is achievable by compiling a model with the "**$SurfaceProp**" property on "**flesh**" and **trying to take it with the Gravitygun in game**.

Thanks guys.
Regards,

**Comment by robotboy655** [comment]
I'd imagine it is by design since the grav gun shouldn't pick up props of that type.

**Comment by robotboy655** [comment]
I'd also imagine you can fix it with Lua via setting the material type.
