### ISSUE TITLE
DCollapsibleCategory:Add(str) line wants to use a color when the line is hovered by mouse but due to a mistake in code it never happens

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-issues#3223]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/vgui/dcategorycollapse.lua#L84
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/vgui/dcategorycollapse.lua#L90
global lookup for `hovered`

if I replace `hovered` with `button:IsHovered()` then it looks like this

![](http://i.imgur.com/MfDqq0G.png)

Which looks kind of bad. The color is picked form the derma skin png file itself.

**Comment by robotboy655** [comment]
Fixed and updated the .png to accommodate for the fix.

Hopefully this won't destroy community skins.
