### ISSUE TITLE
ragdoll_motion.lua: RagdollUpdatePhysics is called with undefined global "i"

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-issues#3224]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/base/entities/entities/ragdoll_motion.lua#L303

But I can't tell what it's supposed to be. Maybe it's just supposed to be nil? The wiki says the first argument is unknown, is it it based on this finding?

**Comment by robotboy655** [comment]
Turns out RagdollUpdatePhysics has no arguments
