### ISSUE TITLE
ai_schedule.New  accepts debug name but is never set due to typo

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-issues#3226]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/ai_schedule.lua#L23 

looks like it's meant to be `__debugname__`

unsure if fixing this will cause unexpected behavior

**Comment by robotboy655** [comment]
Since it's not really used anywhere I doubt it will cause unexpected behavior
