### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by MrCoala** [Facepunch/garrysmod-issues#3227]
The server is randomly crashing and unfortunately i can not reproduce it. It occurs totally randomly (10-30 times a day) and most of the time it only crashes but then again it freezes sometimes.
I added the debuglog and the core file to this thread.

[debug.txt](https://github.com/Facepunch/garrysmod-issues/files/1102983/debug.txt)

[core.zip](https://github.com/Facepunch/garrysmod-issues/files/1102978/core.zip)
## System specs:
![grafik](https://user-images.githubusercontent.com/18616998/27552450-baa28168-5aa7-11e7-9133-42bd1d79456b.png)

## Usually a crash looks like that in the crash log:

_----------------------------------------------
CRASH: Mon Jun 26 18:18:22 CEST 2017
Start Line: ./srcds_linux -game garrysmod +map ttt_plaza_b7 -maxplayers 64 +rcon_password XXXXXXXXXXXXXXXX +port 27019 -authkey XXXXXXXXXXXXXXXX -debug -autoupdate +host_workshop_collection XXXXXXXXXXXXXXXX
[New LWP 23906]
[New LWP 23969]
[New LWP 23910]
[New LWP 23907]
[New LWP 10163]
[New LWP 23909]
[New LWP 23908]
[New LWP 23912]
[New LWP 16226]
[New LWP 10323]
[New LWP 23958]
[New LWP 13347]
[New LWP 14294]
[New LWP 10436]
[New LWP 9896]
[New LWP 11658]
[New LWP 24612]
[New LWP 10459]
[New LWP 9519]
[New LWP 15022]
[New LWP 10759]
[New LWP 15497]
[New LWP 23913]
[New LWP 10807]
[New LWP 9178]
[New LWP 13314]
[New LWP 11578]
[New LWP 11579]
[New LWP 10413]
[New LWP 12821]
[New LWP 12662]
[New LWP 16147]
[New LWP 9715]
[New LWP 9148]
[New LWP 23973]
[New LWP 12116]
[New LWP 10166]
[New LWP 16835]
[New LWP 15399]
[New LWP 17040]
[New LWP 11248]
[New LWP 13292]
[New LWP 12033]
[New LWP 12522]
[New LWP 12206]
[New LWP 9043]
[New LWP 14098]
[New LWP 12995]
[New LWP 13290]
[New LWP 11033]
[New LWP 16765]
[New LWP 9802]
[New LWP 12955]
[New LWP 14521]
[New LWP 11137]
[New LWP 12768]
[New LWP 12873]
[New LWP 13403]
[New LWP 14057]
[New LWP 10118]
[New LWP 13920]
[New LWP 9540]
[New LWP 10458]
[New LWP 10034]
[New LWP 9667]
[New LWP 16480]
[New LWP 9142]
[New LWP 17021]
[New LWP 14944]
[New LWP 9668]
[New LWP 14820]
[New LWP 9778]
[New LWP 11744]
[New LWP 14056]
[New LWP 11449]
[New LWP 11447]
[New LWP 15734]
[New LWP 10504]
[New LWP 10414]
[New LWP 14924]
[New LWP 13068]
[New LWP 9541]
[New LWP 12872]
[New LWP 15024]
[New LWP 16670]
[New LWP 12311]
[New LWP 15021]
[New LWP 10783]
[New LWP 10854]
[New LWP 13409]
[New LWP 12478]
[New LWP 16396]
[New LWP 17095]
[New LWP 10782]
[New LWP 10457]
[New LWP 11525]
[New LWP 15184]
[New LWP 10342]
[New LWP 10033]
[New LWP 9076]
[New LWP 10851]
[New LWP 10167]
[New LWP 16834]
[New LWP 11829]
[New LWP 12869]
[New LWP 16397]
[New LWP 14642]
[New LWP 10437]
[New LWP 14943]
[New LWP 15232]
[New LWP 14643]
[New LWP 15110]
[New LWP 11426]
[New LWP 15896]
[New LWP 12994]
[New LWP 9964]
[New LWP 13251]
[New LWP 16669]
[New LWP 11711]
[New LWP 11425]
[New LWP 9044]
[New LWP 10760]
[New LWP 11225]
[New LWP 23948]
[New LWP 12724]
[New LWP 10320]
[New LWP 10610]
[New LWP 10162]
[New LWP 11267]
[New LWP 12790]
[New LWP 12477]
[New LWP 9854]
[New LWP 10806]
[New LWP 15968]
[New LWP 14009]
[New LWP 11809]
[New LWP 15231]
[New LWP 11004]
[New LWP 9984]
[New LWP 14816]
[New LWP 15522]
[New LWP 15864]
[New LWP 17020]
[New LWP 12798]
[New LWP 13250]
[New LWP 11741]
[New LWP 10165]
[New LWP 12034]
[New LWP 13713]
[New LWP 10855]
[New LWP 15582]
[New LWP 12426]
[New LWP 9327]
[New LWP 9072]
[New LWP 17041]
[New LWP 11598]
[New LWP 15894]
[New LWP 10321]
[New LWP 13408]
[New LWP 23911]
[New LWP 11360]
[New LWP 14923]
[New LWP 10037]
[New LWP 14995]
[New LWP 13346]
[New LWP 9179]
[New LWP 15819]
[New LWP 10036]
[New LWP 12769]
[New LWP 12954]
[New LWP 17096]
[New LWP 13069]
[New LWP 10523]
[New LWP 14994]
[New LWP 15630]
[New LWP 12119]
[New LWP 12905]
[New LWP 12427]
[New LWP 12590]
[New LWP 11810]
[New LWP 15995]
[New LWP 10456]
[New LWP 12479]
[New LWP 23956]
[New LWP 15301]
[New LWP 15581]
[New LWP 15496]
[New LWP 13180]
[New LWP 11638]
[New LWP 15302]
[New LWP 12870]
[New LWP 10611]
[New LWP 11742]
[New LWP 11003]
[New LWP 15185]
[New LWP 9261]
[New LWP 12723]
[New LWP 10119]
[New LWP 15019]
[New LWP 9965]
[New LWP 15109]
[New LWP 15994]
[New LWP 14522]
[New LWP 12011]
[New LWP 11224]
[New LWP 12310]
[New LWP 11526]
[New LWP 11831]
[New LWP 11639]
[New LWP 12476]
[New LWP 15629]
[New LWP 9141]
[New LWP 12611]
[New LWP 12906]
[New LWP 12117]
[New LWP 9716]
[New LWP 12718]
[New LWP 9943]
[New LWP 15820]
[New LWP 9173]
[New LWP 14097]
[New LWP 11032]
[New LWP 15400]
[New LWP 12010]
[New LWP 14008]
[New LWP 9803]
[New LWP 10164]
[New LWP 9520]
[New LWP 12521]
[New LWP 9326]
[New LWP 16148]
[New LWP 12789]
[New LWP 13712]
[New LWP 12688]
[New LWP 12589]
[New LWP 10852]
[New LWP 13293]
[New LWP 15020]
[New LWP 15733]
[New LWP 13289]
[New LWP 16460]
[New LWP 12820]
[New LWP 15523]
[New LWP 11247]
[New LWP 11659]
[New LWP 9049]
[New LWP 13313]
[New LWP 9147]
[New LWP 11599]
[New LWP 15971]
[New LWP 15526]
[New LWP 9983]
[New LWP 9050]
[New LWP 16944]
[New LWP 11523]
[New LWP 11982]
[New LWP 14819]
[New LWP 11832]
[New LWP 24331]
[New LWP 9942]
[New LWP 15023]
[New LWP 16766]
[New LWP 15967]
[New LWP 9713]
[New LWP 12610]
[New LWP 11830]
[New LWP 12875]
[New LWP 15970]
[New LWP 10322]
[New LWP 10255]
[New LWP 10256]
[New LWP 12719]
[New LWP 11359]
[New LWP 16945]
[New LWP 17156]
[New LWP 11138]
[New LWP 16461]
[New LWP 12663]
[New LWP 12867]
[New LWP 12874]
[New LWP 14293]
[New LWP 9260]
[New LWP 11450]
[New LWP 11446]
[New LWP 11712]
[New LWP 11522]
[New LWP 9071]
[New LWP 9172]
[New LWP 9855]
[New LWP 11266]
[New LWP 13179]
[New LWP 9075]
[New LWP 16227]
[New LWP 11981]
[New LWP 11743]
[New LWP 15865]
[New LWP 16481]
[New LWP 9714]
[New LWP 10343]
[New LWP 9895]
[New LWP 15525]
[New LWP 10524]
[New LWP 13402]
[New LWP 12689]
[New LWP 9779]
[New LWP 14817]
[New LWP 12868]
[New LWP 12120]
[New LWP 10503]
[New LWP 12207]
[New LWP 12799]
[New LWP 13921]
Core was generated by `./srcds_linux -game garrysmod +map ttt_plaza_b7 -maxplayers 64 +rcon_password d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf75ddf9b in ?? ()
#0  0xf75ddf9b in ?? ()
End of Source crash report
----------------------------------------------_

[debug.txt](https://github.com/Facepunch/garrysmod-issues/files/1102983/debug.txt)

[core.zip](https://github.com/Facepunch/garrysmod-issues/files/1102978/core.zip)

**Comment by robotboy655** [comment]
Closing as stale.
