### ISSUE TITLE
BaseAnimatingOverlay Animations are bugged out

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3228]
https://yadi.sk/d/SZvBtJYG3KUvCX

Because same is happening with players, even if it is called internally by gmod (e.g. player enters noclip and gmod calls RestartGesture with `gmod_breath_noclip_layer` internally), i got very triggered, and opened the issue

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/RestartGesture
http://wiki.garrysmod.com/page/Entity/SetLayerCycle
http://wiki.garrysmod.com/page/Entity/IsValidLayer

**Comment by roboderpy** [comment]
After 10 mins of experimenting, they are still running at random. Even when animation is not playing, `IsValidLayer` returns `true` on gesture's `layerID`, until animation finishes serverside

**Comment by roboderpy** [comment]
So that's it

**Comment by robotboy655** [comment]
What exactly is the problem here? What's bugging out? What's running at random? Obviously IsValidLayer will return true for the layer after it was created until it is killed via the autokill argument.

Are you using these functions on a nextbot? They won't work properly for other entities. (SENTS)

**Comment by roboderpy** [comment]
Look at video above. Im trying to play rocket firing anim on sentry. It plays clientside at random.

**Comment by robotboy655** [comment]
I have tried replicating your video with this code and it worked as I expected.

```

AddCSLuaFile()

ENT.Base = "base_nextbot"
ENT.Spawnable = false

function ENT:Initialize()

	self:SetModel( "models/buildables/sentry3.mdl" )

end

function ENT:Think()
	if SERVER then
		--print( self:IsValidLayer( 0 ), self:IsPlayingGesture( ACT_RANGE_ATTACK2 ) )
	end
end

function ENT:RunBehaviour()

	while ( true ) do
		if ( !self.test ) then
			self.test = true
			coroutine.wait( 5 )

			print("------------1", self:RestartGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------2", self:AddGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------3", self:RemoveGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------4", self:AddGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------5", self:RemoveGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------6", self:AddGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------7", self:AddGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )

			print("------------8", self:AddGesture( ACT_RANGE_ATTACK2 ))
			coroutine.wait( 5 )
		end

		coroutine.wait( 1 )
		coroutine.yield()

	end


end

--
-- List the NPC as spawnable
--
list.Set( "NPC", "npc_tf2_ghost", {
	Name = "Test NPC",
	Class = "npc_tf2_ghost",
	Category = "Nextbot"
} )
```

**Comment by roboderpy** [comment]
I think you are testing it in singleplayer

**Comment by robotboy655** [comment]
I tested it on dedicated server as well.

**Comment by robotboy655** [comment]
Provide me with minimal code to reproduce your issue and your testing conditions.

**Comment by roboderpy** [comment]
You should put on wiki that `Gesture` functions are only working when called inside `BehaveUpdate`

And also you should put that `BehaveUpdate` is called almost frequent as `Think` and `NextThink` affects `BehaveUpdate`. Im blind without proper documentation.

One more question to you, why `SuppressHostEvents` doesn't suppress sounds, but suppress events?
```
SuppressHostEvents(Entity(1))
Entity(1):EmitSound('sometest.wav')
SuppressHostEvents(NULL)
Entity(1):EmitSound('sometest.wav')
```
```
Failed to load sound "sometest.wav", file probably missing from disk/repository
Failed to load sound "sometest.wav", file probably missing from disk/repository
[GCompute GLua STEAM_0:1:58586770 (DBotThePone) -> Server]
```

When i do my SWEP (tf2 sweps), they have fire delay, and i fire in `Think` with `SuppressHostEvents` call.
Sound plays twice, and bullet fires twice too, but my `CRITICAL HIT!!!` label displays only once. If i call `SuppressHostEvents(NULL)` right before making effect in predicted fire in `Think` hook, event will be displayed twice. Also i tried to fire instantly, e.g. in `PrimaryAttack` hook, sounds and bullets are still firing twice.

**Comment by roboderpy** [comment]
And there's a bug with looped animations
Willox already asked me about minimal code to reproduce, so there it is
```

local SWEP = {}

SWEP.PrintName = 'Bug Display'
SWEP.Author = 'DBot'
SWEP.Spawnable = true
SWEP.AdminSpawnable = true

SWEP.ViewModel = 'models/weapons/c_models/c_soldier_arms.mdl'
SWEP.WorldModel = 'models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl'
SWEP.UseHands = false

function SWEP:Initialize()
    self.nextTestAnim = 0
    self.nextAnimChange = CurTime() + 1
end

function SWEP:SetupDataTables()
    self:NetworkVar('Entity', 0, 'TF2WeaponModel')
end

function SWEP:Deploy()
    if SERVER and not IsValid(self.viewModel) then
        self.viewModel = ents.Create('gmod_hands')
        local ent = self.viewModel
        ent:SetPos(self:GetPos())
        ent:SetModel(self.WorldModel)
        ent:Spawn()
        ent:Activate()
        ent:SetParent(self:GetOwner():GetViewModel())
        ent:AddEffects(EF_BONEMERGE)
        self:DeleteOnRemove(ent)
        self:SetTF2WeaponModel(ent)
    end

    return true
end

function SWEP:PostDrawViewModel()
    if IsValid(self:GetTF2WeaponModel()) then
        self:GetTF2WeaponModel():SetNoDraw(true)
        self:GetTF2WeaponModel():DrawModel()
    end
end

function SWEP:Think()
    if CLIENT then return end
    if self.nextAnimChange > CurTime() then return end
    self.nextAnimChange = CurTime() + 1
    if self.nextTestAnim < 4 then
        self:GetOwner():GetViewModel():SendViewModelMatchingSequence(6) -- dh_reload_loop
        self.nextTestAnim = self.nextTestAnim + 1
    else
        self.nextTestAnim = 0
        self:GetOwner():GetViewModel():SendViewModelMatchingSequence(0)
    end
end

function SWEP:OnRemove()
    if IsValid(self.viewModel) then
        self.viewModel:Remove()
    end
end

weapons.Register(SWEP, 'rocket_launcher_bug')
```
@robotboy655

**Comment by robotboy655** [comment]
These functions work outside BehaveUpdate.

**Comment by roboderpy** [comment]
nope, Sentry's animation works perfectly when called inside `BehaveUpdate`

**Comment by roboderpy** [comment]
![fd9265cf41_code - insiders_2017-06-28_06-38-56](https://user-images.githubusercontent.com/6339511/27614505-7749b2b2-5bcc-11e7-8f03-f16706367532.png)
![72b28f2875_code - insiders_2017-06-28_06-39-11](https://user-images.githubusercontent.com/6339511/27614515-85d686b6-5bcc-11e7-99aa-b378bb19edbd.png)

**Comment by roboderpy** [comment]
@robotboy655 https://dbot.serealia.ca/sharex/2017/06/6f4906f20b_%25pn_-2017-06-28_06-41-26.webm - when all `Gesture` are being called inside `BehaveUpdate`

**Comment by robotboy655** [comment]
Hm, it seems that you are right after all. I can confirm its not working properly outside of BehaveUpdate for nextbots, most likely due to internal nextbot optimizations.

I would enable "anim" entities to be able to use AnimLayers, but that would require networking change, so I cant do this for this update, but I can do it for the next one. I have tested and it works properly that way.

For any other questions go to the forums, for any other bug reports, create new issues.
