### ISSUE TITLE
Main Menu Fonts are broken and I can barely read anything on the Servers List

### ISSUE THREAD

**Issue by AcMafee-Web** [Facepunch/garrysmod-issues#3230]
![](http://i.imgur.com/WYSa0Zp.jpg)

I'm not sure exactly what is causing this issue. In some other programs, characters aren't showing up and I'm desperately trying to find a fix for this.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16

Doesn't even sound like an issue with the game, but your PC.
