### ISSUE TITLE
Gmod continuously crashes

### ISSUE THREAD

**Issue by ratmeal** [Facepunch/garrysmod-issues#3231]
![screen shot 2017-06-24 at 6 23 14 pm](https://user-images.githubusercontent.com/29682021/27712467-2af2a480-5cf5-11e7-8b12-1c27e92c8a37.png)
The game crashed after seeing these messages in the console, it has been crashing alot and i would like some help. I use a mac also.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/16
