### ISSUE TITLE
Crash on spawn after a few maps played

### ISSUE THREAD

**Issue by ghost0123** [Facepunch/garrysmod-issues#3233]
### Details
After playing a few maps on a server, there's a chance for anyone to crash on any map, it's usually a small number of people who do (1 or 2 at the minimum).

crash dump provided:
---
In this I and one other crashed, while everyone else was fine, it does happen other times, but I don't have crash dumps for them.

**Comment by robotboy655** [comment]
Can you send a different dump? That one crashes VS2017 for some reason

**Comment by ghost0123** [comment]
Alright, I'll provide another asap.

**Comment by ghost0123** [comment]
It appears to originate from a lua error, not a gmod problem as I once thought.
