### ISSUE TITLE
Killing npc_helicopter after spawning it crashes the server

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-issues#3241]
### Details
At first I thought this issue was my fault, since I haven't updated my dedicated server: #3240 
But shortly after I found out that it's actually something to do with killing an npc (a helicopter/ a strider) after spawning it before it starts moving.

[Dump](https://dl.dropboxusercontent.com/s/9jhei4b7dbipxkb/srcds_2117156_crash_2017_7_12T18_48_42C0.mdmp)

I also got this assert, not sure if it's important:
![](http://i.imgur.com/daXFaqW.png)

### Steps to reproduce

- bind N "rcon lua_run local a=Entity(1) local b=a:GetEyeTrace().Entity local c=DamageInfo() c:SetDamageType(bit.bor(DMG_BLAST,DMG_AIRBOAT)) c:SetDamage(1000) c:SetInflictor(a:GetActiveWeapon()) c:SetAttacker(a) b:TakeDamageInfo(c)"
- Spawn a combine helicopter, look at it and press N before it starts moving

[Video](https://dl.dropboxusercontent.com/s/tg3q2xk0w9e3acd/2017-07-12_21-48-15.mp4)

**Comment by robotboy655** [comment]
Should be fixed in Dev

**Comment by Tripperful** [comment]
Just checked on dev, it is fixed, thanks
