### ISSUE TITLE
Linux no longer works?

### ISSUE THREAD

**Issue by linkjay1** [Facepunch/garrysmod-issues#3242]
I can no longer play GMod in Linux? I was able to play before the July update, and now suddenly I can't?

Every time I start it from Steam, it says on Steam that I am playing it, and then suddenly I am no longer playing it. I don't think the task even starts. 

I tried reinstalling it on a completely vanilla version of the game and that didn't help. I am running the latest xUbuntu which is running Ubuntu version 16.04 in the back-end.

Apparently, other Linux users are also having this same issue and are reporting it in the news for GMod. Is it just me, or is Linux for GMod not a thing anymore?

**Comment by daunknownman2010** [comment]
Sorry to burst your bubble but I have Garry's Mod perfectly running on KDE neon 5.10.3 (Ubuntu 16.04.2 LTS) right now. Therefore, this cannot be classified as a bug and you must submit this as a support ticket to Facepunch instead. Be sure to also include hardware and other technical information that may help solve the issue at support.

**Comment by robotboy655** [comment]
https://gmod.facepunch.com/blog/july-2017-update/

```
Linux builds of the game now depend on GLIBCXX 3.4.19. You may run in to some issues if your C++ runtime is a decade out of date.
```

**Comment by linkjay1** [comment]
Updated the package and it didn't work. Running GMod via terminal revealed that it was my USB device causing it. It was causing this exact error:

```
Found joystick 'Generic X-Box pad' (0300000038070000a002000000010000), but no recognized controller configuration for it.
*** stack smashing detected ***: /home/jay/Desktop/LinuxSteal/SteamLibrary/steamapps/common/GarrysMod/hl2_linux terminated
./hl2.sh: line 67: 28028 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```


After I removed the device from the computer, it started normally.

**Comment by linkjay1** [comment]
Just to follow up, it seems that my the USB device I had plugged in, my wired Xbox 360 controller, seems to cause GMod to not start every single time. When the device is plugged in, it will not start the game. However, when it is not, the game starts perfectly fine. 

I don't use the controller for GMod, but leave it plugged in for every other game. Is this a known issue? Are other people experiencing this, or is it just me?

**Comment by mcd1992** [comment]
Interesting, it looks like gmod wasn't compiled with the stack-protector in the past. At some point during the glibc update or something it got enabled.

For __stack_chk_fail to get called though the stack must of been corrupted at some point. If you can hop on the dev branch and generate a coredump to send to the developers.

**Comment by linkjay1** [comment]
Looks like the latest update solved the issue. I am now able to start the game and play around no matter the status of the controller. Good work guys!
