### ISSUE TITLE
OnRemove being called on all entities when a player first joins the server

### ISSUE THREAD

**Issue by SleepyMode** [Facepunch/garrysmod-issues#3245]
### Details
Since one of the Garry's Mod updates one of the most carefully planned systems we had in NutScript broke with no way to fix it, causing OnRemove to be called on all entities when a player first joins the server and removing plenty of things which are required for the server to run correctly, leading to something really frustrating which the NutScript development team, after carefully checking the codes over and over again concluded it has begun after one of the recent Garry's Mod updates.
Although we are not sure the issue is directly within Garry's Mod it is something done to it that caused it.

### Steps to reproduce
1) Download NutScript and place a vendor on the map.
2) Get a new player which never played the server to join.
3) Vendors will disappear because OnRemove was called on all of them.

**Comment by Kefta** [comment]
Could you post steps that can be done with vanilla Garry's Mod?

**Comment by SleepyMode** [comment]
Not sure regarding vanilla Garry's Mod, but it is a garry's mod update which broke the gamemode, and after reading the contribution guide we were asked to post regardless.

**Comment by Kefta** [comment]
It doesn't really help unless you're able to provide a replication method that uses specific code.

**Comment by Python1320** [comment]
ENT:OnRemove clientside is supposed to be called on entities regardless of whether they actually were removed or not (full game state snapshot update). You can use ENT:Think for example to see when they reappear. Initialize is NOT called again. 
If you want a proper hook, https://wiki.garrysmod.com/page/GM/NotifyShouldTransmit should be the way to go. 

This is how it has always been, but I bet on your gamemode you get so much stuff on join nowadays (or rather, a long enough freeze) that a fullupdate happens which causes the OnRemove to be called as that is what fullupdate more or less does.

There is basically nothing to fix, it's just how it has always been even if it _is_ a bit weird. NotifyShouldTransmit should probably have entity hook for ease of use, but we can't have everything now can we 😃
