### ISSUE TITLE
gui.OpenURL confirmation missing strings

### ISSUE THREAD

**Issue by FarukGamer** [Facepunch/garrysmod-issues#3248]
### Details
The gui.OpenURL confirmation window has no valid strings inside the title,text and button.
![screenshot_1](https://user-images.githubusercontent.com/12494967/28471599-f76925bc-6e3d-11e7-87ed-2f247f8c276a.png)

### Steps to reproduce
Simply call gui.OpenURL( url string )

**Comment by Bo98** [comment]
GameUI_Yes and GameUI_No could probably be reused but the other strings would indeed need adding.

**Comment by willox** [comment]
@Bo98 if that were the case we'd need to add GameUI_Nope
