### ISSUE TITLE
Server execute errors

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3250]
### Details
FCVAR_SERVER_CAN_EXECUTE prevented server running command: gameui_activate

When opening a url with gui.OpenURL the error appears and the url cancels to open.

### Steps to reproduce
Use gui.OpenURL on SRCDS

**Comment by robotboy655** [comment]
Cannot reproduce. It works for me on both listen and dedicated server. Post code or steps to reproduce.

**Comment by mcNuggets1** [comment]
Ah, the error is different.

I am using a chat command which triggers a command to open a URL.
The confirmation opens in the background, means you have to open the ESC-menu to confirm or deny.

**Comment by robotboy655** [comment]
```Post code or steps to reproduce.```

**Comment by mcNuggets1** [comment]
You said steps were okay also, but okay.

`hook.Add("PlayerSay", "BUG", function(ply, text)
	if (string.lower(text) == "!bug") then
		ply:ConCommand("bug")
		return ""
	end
end)

concommand.Add("bug", function()
	gui.OpenURL("https://steamcommunity.com/sharedfiles/filedetails/?id=453291147")
end)`

**Comment by robotboy655** [comment]
Yeah that's due to Player.ConCommand, not sure if anything can be, or even should be done about this.

I'd assume its a security feature from Source Engine to stop malicious servers in other games from hiding the main menu via console commands.

**Comment by mcNuggets1** [comment]
When using the concommand otherwise, without using the chat, it opens in esc menu, and is gone when closing the esc menu.

It worked before the update.
It broke.

**Comment by robotboy655** [comment]
What "worked" before the update?
The changes to gui.OpenURL were made in the most recent update, nothing broke it.

**Comment by mcNuggets1** [comment]
But why the heck is opening a url only possible when being in esc menu?
Atleast do the confirmation in the foreground of the game.

**Comment by robotboy655** [comment]
Don't run gui.OpenURL in a console command that is run by Player.ConCommand. Even a 0 second timer in the concommand will fix the problem.

**Comment by mcNuggets1** [comment]
Thanks for fixing the issue
