### ISSUE TITLE
SourceTV crashes on listen server/Chromium process doesn't close

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3251]
Immediately crashes with "UpdatePlayerName with bogus slot 129". May be a separate issue, but with the -chromium flag enabled, chromium_process.exe requires being force closed after crashing. This doesn't seem to happen with other segfaults.

Dump: https://drive.google.com/uc?id=0BzHUGYx2_b8tVV9ZU2JQbHNQOWM

**Comment by robotboy655** [comment]
Just has to do with default value of tv_maxclients and the limit of maxplayers to 128 recently.
