### ISSUE TITLE
mp_maxdecals in server.cfg can lock up server 

### ISSUE THREAD

**Issue by kulcris** [Facepunch/garrysmod-issues#3252]
### Details
Changed some settings in server.cfg and then ran exec server 

Server crashed to the point of locking up the whole machine, with a repeating message stating "did not set mp_maxdecals 15" or something like that 

### Steps to reproduce
have mp_maxdecals  set to something in the server,cfg and reloading the config

OS: Ubuntu Version 14.04 i believe

Ran via server console

This has happened 2-3 times so i know it wasnt a one time thing

**Comment by robotboy655** [comment]
There is no such console command or variable called "mp_maxdecals".

**Comment by Kefta** [comment]
Maybe he means mp_decals?

**Comment by kulcris** [comment]
Wow, oops i forgot to update this O.o my bad

If i remember right this was some addon i had installed that i had forgotten about. this should probably be closed.
