### ISSUE TITLE
xFuscator - cannot load malformed byecode

### ISSUE THREAD

**Issue by PieCrafted** [Facepunch/garrysmod-issues#3253]
### Details
I try to run this:
`RunString('\27\76\117\97\81\0\1\4\4\4\8\0\209\0\0\0\108\111\99\97\108\32\76\48\68\116\61\123\91\49\93\61\34\92\55\50\92\49\48\49\92\49\48\56\92\49\48\56\92\49\49\49\92\51\50\92\49\49\57\92\49\49\49\92\49\49\52\92\49\48\56\92\49\48\48\34\44\91\50\93\61\34\92\56\56\92\55\48\92\56\53\92\53\51\92\55\53\92\53\50\92\53\53\92\52\56\92\56\50\92\51\50\92\52\57\92\53\51\92\51\50\92\53\50\92\56\55\92\53\49\92\53\51\92\52\56\92\55\55\92\53\49\92\52\54\92\51\50\92\55\53\92\56\50\92\53\49\92\54\56\92\52\57\92\53\53\92\51\50\92\53\53\92\52\56\92\51\50\92\56\56\92\55\48\92\56\53\92\53\51\92\55\53\92\53\50\92\53\53\92\52\56\92\56\50\92\51\51\34\125\112\114\105\110\116\40\76\48\68\116\91\49\93\41\0\0\0\0\0\0\0\0\0\0\0\2\3\7\0\0\0\10\128\0\0\9\64\64\128\9\192\64\129\69\0\1\0\134\0\64\0\92\64\0\1\30\0\128\0\5\0\0\0\3\0\0\0\0\0\0\240\63\4\12\0\0\0\72\101\108\108\111\32\119\111\114\108\100\0\3\0\0\0\0\0\0\0\64\4\43\0\0\0\88\70\85\53\75\52\55\48\82\32\49\53\32\52\87\51\53\48\77\51\46\32\75\82\51\68\49\55\32\55\48\32\88\70\85\53\75\52\55\48\82\33\0\4\6\0\0\0\112\114\105\110\116\0\0\0\0\0\7\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0\13\0\0\0\48\21\46\155\33\199\206\109\27\6\35\115\0\3\0\0\0\6\0\0\0\0\0\0\0')`
but it errors out with "cannot load malformed byecode"

### Steps to reproduce
I was using https://github.com/ExtReMLapin/XFuscator -fixed for gmod (supposedly)

Trying to obfuscate print("Hello World.");

And I run in CMD using `lua XFuscator.lua "C:\Users\***\Desktop\XFuscator-master\tests\HelloWorld.lua" -nostep2`

**Comment by Kefta** [comment]
![](http://i.imgur.com/0242YX7.png) This is not valid code. RunString doesn't accept raw bytecode:  the string has to resolve to actual code.
