### ISSUE TITLE
HTTP POST body doesn't send null characters \0

### ISSUE THREAD

**Issue by SpiralP** [Facepunch/garrysmod-issues#3254]
I'm running into this problem for a project I'm working on that has to use the body of the POST request to send data, and has to have \0 terminators in the data.

```lua
HTTP{
	method = 'POST',
	url = 'https://httpbin.org/post', -- some http echo service
	
	body = 'H\0ELLO WORLD',
	
	success = function(code, body)
		local t = util.JSONToTable(body)
		print(
			t.headers['Content-Length'], -- 1
			#t.data,                     -- 1
			t.data                       -- 'H'
		)
	end,
	failed = error,
}
```

similar to #1984

**Comment by Python1320** [comment]
I tested with netcat and hex editor of the response from this and it is indeed only "H"

**Comment by robotboy655** [comment]
Oh, the problem is in the sending, not received, I will get that fixed.

**Comment by SpiralP** [comment]
Still having problems with this and sending any kind of binary data with null characters through `body` using the HTTP{} structure.

Thanks for trying to get this fixed! Here are some pictures, hope it helps

![image](https://user-images.githubusercontent.com/2898730/42721379-e5be6348-86ee-11e8-92ae-d8e28fd81bbc.png)

![image](https://user-images.githubusercontent.com/2898730/42721412-4ce750d4-86ef-11e8-9f06-26b88933e837.png)
