### ISSUE TITLE
Using SetAllowWeaponsInVehicle(true) causes invalid aim angles.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3261]
### Details
Setting ply:SetAllowWeaponsInVehicle(true) causes the aim angles to be slightly off when the player is inside.

http://share.epic-domain.com/2017-08-06_15-26-17.mp4

**Comment by robotboy655** [comment]
It's partly because AimPunch does not decay while in a vehicle and partly because the vehicle is tilted and that tilt is added to the aimvector, possibly something to do with the vehicle mounted weapon aiming but I am not sure.

**Comment by ZehM4tt** [comment]
I used a simple seat for the passenger side so its not the jeep I'm in.

**Comment by ZehMatt** [comment]
Heres a work around for anyone who faces this issue:

```
local vehicle = ply:GetVehicle()
if IsValid( vehicle ) then

	local eyeAng = ply:GetAimVector():Angle()
	ang:Set(eyeAng + ply:GetViewPunchAngles())

	local _, localAng = WorldToLocal( Vector(0,0,0), ang, Vector(0,0,0), vehicle:GetAngles())
	ang:RotateAroundAxis( ang:Forward() * -1, localAng.r)

	view.angles = ang

	return hook.Run( "CalcVehicleView", vehicle, ply, view )
end
```

This has to be placed in CalcView. Also while being in that seat the FOV is off from the client and does not match whats set on server.

**Comment by robotboy655** [comment]
The root cause of this is fixed.
