### ISSUE TITLE
Game crashes/freezes trying to apply decals on complex meshes

### ISSUE THREAD

**Issue by goigle** [Facepunch/garrysmod-issues#3264]
Same issue as #2566

Here's the dump file: https://www.dropbox.com/s/65n1psz8k2oz2yn/hl2_170801_crash_2017_8_8T4_12_50C0.mdmp?dl=0

and the specific model I'm having issues with: https://steamcommunity.com/sharedfiles/filedetails/?id=604863059

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3159
