### ISSUE TITLE
Lua concommands aren't removed from autocompletion list on concommand.Remove

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-issues#3266]
Lua concommands aren't removed from autocompletion list on concommand.Remove. Probably that's because concommand.Run registers console command in the engine using AddConsoleCommand, but concommand.Remove doesn't unregister it. There is also no function like RemoveConsoleCommand to unregister a Lua concommand, but it is certainly possible because Garry's Mod removes all Lua concommands when you disconnect from server.

**Comment by uRandomAlex** [comment]
This is really important, please don't let this issue die like hundreds of other issues

**Comment by robotboy655** [comment]
How is this "really important"? How often are you deleting console commands? For what purpose?

**Comment by willox** [comment]
This is unlikely to change. Source ConVars & ConCommands were not designed to be removed at runtime, so I decided to settle with removing them on level change rather than changing a lot of things.
