### ISSUE TITLE
Spectating an entity doesn't update spectator position, causing area portals not to load

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3267]
![](http://i.imgur.com/mNygQj8.jpg)

This is while spectating another player. Hacky fix is to constantly update the player's position to the entity's. Credit to @KingofBeast for finding.

**Comment by raubana** [comment]
I believe that was intentional. The server will need to use the spectated entity's origin to transmit its PVS. You can do that with the SetupPlayerVisibility hook.

**Comment by Kefta** [comment]
I don't see what benefit there is of it not being done automatically.

**Comment by raubana** [comment]
It could just be so the option is there. I can't say for sure, I'm assuming it has to do with network performance.

**Comment by Kefta** [comment]
I don't think anything would be saved networking-wise since the entity being spectated is always going to be non-dormant.

**Comment by raubana** [comment]
I take back what I said, yeah this doesn't make a whole lot of sense.

**Comment by robotboy655** [comment]
Cannot seem to reproduce this either, altho I do remember this happening to me on CS:S's Dust2.

**Comment by Kefta** [comment]
I don't think it works when spectating bots.

**Comment by robotboy655** [comment]
Cannot reproduce with a non bot on a dedicated server. (sv_lan 1 multirun)
Spectating with
```
Entity(2):Kill()
Entity(2):Spectate(5)
Entity(2):SpectateEntity(Entity(1))
```

Can anyone else?

**Comment by KingofBeast** [comment]
I'm not in a place I can test at this very moment but have you tried mode 4? Not sure if it makes a difference internally but I don't remember testing the issue with a third-person spectate mode, only first-person.

**Comment by robotboy655** [comment]
No difference

**Comment by Kefta** [comment]
I somewhat replicated it spectating a bot on a listen server on para_spaceship_v8 with ``lua_run Entity(1):Spectate(OBSERVER_MODE_IN_EYE, Entity(2))`` I couldn't get the exact glitch as originally shown, but I did get fullbright areas that changed when I moved past an area portal.

![](https://i.imgur.com/VLID2S8.jpg)
![](https://i.imgur.com/MnRSqgw.png)
![](https://i.imgur.com/566Cq3M.jpg)

Loading the visleafs at any point as the actual player, or going outside of the map with noclip as either the player or bot causes the issue to not appear again until a changelevel, so when testing, the bot must spawn in a different area than the player.

On a somewhat unrelated note, I also managed to get my player's c_hands and viewmodel floating in the bot's vision near 0, 0, 0 in this state. This might be related to https://github.com/Facepunch/garrysmod-issues/issues/2226.
![](https://i.imgur.com/DkuzTVm.jpg)

**Comment by mcNuggets1** [comment]
I've had this happening too while spectating someone in a large size map.
There was an area portal I couldnt see through, until the player moved through it, even though the player was able to see it.

**Comment by Dimantio** [comment]
I have a very closely similar issue to this where my player view stop updating when set by Player:SetViewEntity, using Spectate with CHASE mode is fine. The video below show both mode. Also my player position is updated every tick alas it's still happening.

[Video](https://i.qcgames.org/c2r70.mp4)

**Comment by robotboy655** [comment]
I was looking through the entire fucking engine to find why this was happening but it turned out to be this: `SetMoveType( MOVETYPE_NONE );` in `Player:Spectate()` binding. Fuck me.

Also explains why I couldn't reproduce it before, it only happens for 3 spectate modes.
