### ISSUE TITLE
error level argument doesn't manipulate stack trace

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3271]
The error function will only take into account the level argument for prepending the source, but the stack trace seems to be hardcoded to level 0. Example:

```
] lua_run error("test", 1)
> error("test", 1)...

[ERROR] lua_run:1: test
  1. error - [C]:-1
   2. unknown - lua_run:1

] lua_run error("test", 2)
> error("test", 2)...

[ERROR] test
  1. error - [C]:-1
   2. unknown - lua_run:1

] lua_run error("test", 3)
> error("test", 3)...

[ERROR] test
  1. error - [C]:-1
   2. unknown - lua_run:1
```

**Comment by willox** [comment]
That's how it is supposed to work. You might want it for pretty error messages, but that'd just be hiding information.

Stock Lua is like this, I thought it was a bug a few years ago too.

**Comment by Kefta** [comment]
Having Error work again too would be nice so you can do this manually
