### ISSUE TITLE
Some metatables for default types missing from registry

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3273]
This means they cannot be retrieved with FindMetaTable. These include:
- TYPE_SCRIPTEDVEHICLE (Vehicle, 20) (different than actual Vehicle type?)
- TYPE_PANEL (Panel, 22)
- TYPE_PARTICLE (CLuaParticle, 23)
- TYPE_PARTICLEEMITTER (CLuaEmitter, 24)
- TYPE_USERMSG (bf_read, 26)
- TYPE_IMESH (IMesh, 28)
- TYPE_PARTICLE (pixelvis_handle_t, 31)
- TYPE_DLIGHT (DynamicLight, 32)
- TYPE_VIDEO (IVideoWriter, 33)
- TYPE_SOUNDHANDLE (IGModAudioChannel, 38)
- TYPE_PARTICLESYSTEM (CNewParticleEffect, 40)

Also, TYPE_COUNT is 42 but there is no type id of 41. Is that supposed to account for TYPE_COLOR (which is 255)?

**Comment by Bo98** [comment]
`TYPE_COUNT` has always been +1 of the last enum, even before `TYPE_COLOR`.

**Comment by Kefta** [comment]
The last enums is 40, though, yet TYPE_COUNT is 42.

**Comment by Bo98** [comment]
`TYPE_PROJECTEDTEXTURE`?

**Comment by robotboy655** [comment]
TYPE_SCRIPTEDVEHICLE is a leftover from pre GMod 13 days.

I have just added the missing TYPE_PROJECTEDTEXTURE

**Comment by Kefta** [comment]
Actually, it looks like I didn't test properly:  all the metatables are present in one realm or the other (except TYPE_SCRIPTEDVEHICLE for the pre-stated reason), but not all are shared for obvious reasons. Ideally, it would be great if the TYPE_* enums were only defined in the realm their metatable was, but this would have to be done with a pretty major rework to Garry's Mod's type system.
