### ISSUE TITLE
[Linux Mint] GMod crashes after using VPK script

### ISSUE THREAD

**Issue by FlashDaggerX** [Facepunch/garrysmod-issues#3274]
NOTICE: I read [this](https://github.com/Facepunch/garrysmod-issues/issues/612) already.
[Script Source, 1st one](https://developer.valvesoftware.com/wiki/VPK#Linux_users)

GMod crashes with the same error, but those fixes do not work. I tried re-installing the game and I played with ${LD_LIBRARY_PATH}.

**Comment by robotboy655** [comment]
Does one from any other source game work for you?

**Comment by FlashDaggerX** [comment]
It's the only source game I have

**Comment by Kefta** [comment]
Can you try TF2 (it's free)?

**Comment by FlashDaggerX** [comment]
I will edit this commit when It's finished

**Comment by robotboy655** [comment]
Edits will not pop up in notifications, so just post a new comment.

**Comment by FlashDaggerX** [comment]
It does not.

**Comment by robotboy655** [comment]
I will tell what it seems to be not - a GMod problem.
