### ISSUE TITLE
Player:Alive() returns true in PlayerDeath but false in PlayerSilentDeath

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3275]
From PlayerDeath's description on the wiki, it makes it sound like PlayerSilentDeath is the silent alternative to PlayerDeath, and DoPlayerDeath is the hook for doing death events while the player is still alive. This, however, is contrasted by the fact that the player is still alive in PlayerDeath. The behaviour should be clarified at the very least.

**Comment by robotboy655** [comment]
Changing ```PlayerDeath``` hook is not an option, so the plan is to change ```PlayerSilentDeath``` to match the ```PlayerDeath``` hook, which means Player:Alive() will now return true in ```PlayerSilentDeath``` and weapons will still be on the player in ```PlayerSilentDeath``` hook.
