### ISSUE TITLE
Linux version won't run lua scripts

### ISSUE THREAD

**Issue by FlashDaggerX** [Facepunch/garrysmod-issues#3278]
I'm trying to run a GMod Lua Project of mine with addon format. When I start GMod, it can't find the addon. I move it to the lua folder and try it there, same thing. I restart every time I move it to a folder, and it just won't find the files (I even tried removing it from addon format).

There's actually a repository for said project [here](https://github.com/FlashDaggerX/pLog).

**Comment by robotboy655** [comment]
Get help @ https://facepunch.com/forums/65
