### ISSUE TITLE
Crash with game.CleanUpMap

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3279]
### Details
Some clients crash when game.CleanUpMap is used but not all the time.

### Steps to reproduce
No idea. Dump is from dev branch.
[hl2_170831_crash_2017_9_1T13_56_41C0.zip](https://github.com/Facepunch/garrysmod-issues/files/1270463/hl2_170831_crash_2017_9_1T13_56_41C0.zip)

**Comment by Kefta** [comment]
Possibly related to https://github.com/Facepunch/garrysmod-issues/issues/3211?

**Comment by willox** [comment]
Unrelated
