### ISSUE TITLE
Material() load png in initial HUDDrawScoreBoard crash

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3282]
When the player spawns and runs the initial HUDDrawScoreBoard hook, this code can crash them. It seems random and affects slower computers more frequently.
```
v.MuteGUI:SetImage( "icon32/unmuted.png" )
```
Crash dump:
https://www.dropbox.com/s/d3o81w8zoaelgaf/hl2_170801_crash_2017_9_4T3_35_58C0.mdmp?raw=1

**Comment by willox** [comment]
Can you provide enough code to reproduce this? I've been investigating this for a few days without results.

**Comment by thegrb93** [comment]
Yeah one second

**Comment by thegrb93** [comment]
https://pastebin.com/HjJRwWj1

**Comment by thegrb93** [comment]
I had just launched garry's mod so that can't be the case

**Comment by thegrb93** [comment]
I think it is much more probable if you are joining from another server though.

**Comment by willox** [comment]
Seems to happen 100% of the time if you follow these steps:

```
map gm_flatgrass
open scoreboard
map gm_construct
open scoreboard
```

I'll look in to it this week.
