### ISSUE TITLE
Clientside GetBonePosition and GetAttachment random crashes on entities with workshop models

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3284]
Another crash I'm trying to squash. Seems to also happen when the player joins, but I can't reproduce this one reliably. I'll upload crashdumps when I get one.

**Comment by thegrb93** [comment]
Forgot to mention it's clientside.

**Comment by thegrb93** [comment]
Here's some mdmps I collected https://www.dropbox.com/s/yab3kef9tlwq621/mdmp.7z?raw=1

**Comment by thegrb93** [comment]
I've collected 47 more dumps with traces leading to these functions. Lemme know if u want them

**Comment by robotboy655** [comment]
Can you get some dumps from the Dev version? ( no more than 5, 1 or 2 ideally ) It appears that we don't have symbols for whatever version you used in there.

**Comment by thegrb93** [comment]
Some of the dumps might be too old, but most should be the stable version. I'll try to filter only stable version dumps. Dev version is impossible to get dumps for.
