### ISSUE TITLE
3D skybox rendering still occurs on maps with 2D skyboxes

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3287]
Tested map: https://steamcommunity.com/sharedfiles/filedetails/?id=110286060

r_3dsky 0 still causes a 25% FPS boost even though there is no 3D skybox present. No visual change occurs when the convar is toggled.

**Comment by thegrb93** [comment]
Vanilla gmod? Some addons such as pac3 won't render with r_3dsky 0 which boosts performance.

**Comment by robotboy655** [comment]
Honestly I don't see any difference between r_3dsky 1 and 0 on that map in the middle of the town with the fountain. Definitely not a 25% FPS boost.

**Comment by Kefta** [comment]
It's because r_3dsky 0 skips calling PreDrawSkyBox, SetupSkyboxFog, a Draw*Renderables hook cycle, and PostDrawSkyBox. I was incorrect about the cause.
