### ISSUE TITLE
Crash in listen server with "map" command

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3288]
Dumps: https://drive.google.com/uc?id=0BzHUGYx2_b8tNFZyT2VHOTVCWnc

I was playing around with the hook file, but there were no Lua errors between maps.

**Comment by mcNuggets1** [comment]
Happens to me after the map successfully changes.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2763
