### ISSUE TITLE
ENT/SWEP.RenderGroup = RENDERGROUP_STATIC(_HUGE) crashes game

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3290]
ent_static:
```
ENT.RenderGroup = RENDERGROUP_STATIC
```

Dump: https://drive.google.com/uc?id=0BzHUGYx2_b8ta1BTYTZHaEs2LUU

**Comment by robotboy655** [comment]
Will be fixed. I will probably also end up disabling those 2 render groups on SWEPs/ENTs, as they are not meant to be used.
