### ISSUE TITLE
OnEntityCreated weirdness with npc_zombie

### ISSUE THREAD

**Issue by ForrestMarkX** [Facepunch/garrysmod-issues#3300]
### Details
When trying to change the model of a npc_zombie in OnEntityCreated the call seems to get delayed sometimes by a few seconds.

### Steps to reproduce
Add a hook for OnEntityCreated then check if the spawned ent is a npc_zombie and inside a timer that runs next frame change the NPCs model. The zombies model won't change for a few seconds.

### Other info
This happens alot in my gamemode port of Zombie Master when spawning zombies from trap nodes. The same issue seems to not occur when spawning zombies from a zombie node. I currently don't know exactly if the issue is with OnEntityCreated as I added code to remove the spawned zombie and instead call the same spawn function that the zombie node does and it seems ent:Remove and GAMEMODE:SpawnZombie don't get called until a few seconds after the zombie from the trap node spawns but adding a print in the if statement where these functions are getting called shows that it's getting called one frame after the zombie spawns. 

This issue seems to only occur with npc_zombie. 

This issue didn't happen at all with the exact same code until the July update.

**Comment by Kefta** [comment]
Set the model in a timer inside of that hook since ::SetZombieModel is called inside the ::Spawn method, and make sure the hook is shared to compensate for networking delay time.

**Comment by ForrestMarkX** [comment]
I'm aware of SetZombieModel and it worked fine adding a timer that runs the frame after the zombie spawns. It works to cause printing ent:GetModel() on the client and server outputs the right model but the model is still the default zombie and doesn't change until a few seconds later

**Comment by Kefta** [comment]
I can't reproduce it -- changes immediately for me: https://youtu.be/XRPjebJTNR4

**Comment by ForrestMarkX** [comment]
Hmm odd, it happens 80% of the time in Zombie Master if the zombie was spawned by the map

**Comment by Kefta** [comment]
Can you find a way to reproduce it with actual code?

**Comment by ForrestMarkX** [comment]
In Sandbox no

**Comment by Kefta** [comment]
Your code makes no sense anyway -- you're spawning the zombie from the timer and then immediately removing it. Either way, this is a problem with your gamemode.

**Comment by ForrestMarkX** [comment]
I forgot to add a (not ent.SpawnedFromNode) to that code. This issue makes 0 sense how would code somewhere cause a ent:Remove and SpawnZombie to not even run until a few seconds later? Mind you it's not SpawnZombie because the code works like it should through zombie nodes

**Comment by Kefta** [comment]
Your English isn't really making sense:  if you cannot reproduce the issue with code in Sandbox/Base with stripped code, then it shouldn't be here. Describe your problem here, instead: https://facepunch.com/forumdisplay.php?f=65

**Comment by ForrestMarkX** [comment]
I'll just stick to the hack I added to temp fix the issue. I'm still 100% sure it's a gmod issue since I made 0 changes to the code and it worked fine but the July update came around and it suddenly just broke.
