### ISSUE TITLE
Upgrade from LuaJIT 2.0.4 to 2.0.5

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#3305]
I'm suggesting to make this upgrade.

> The current stable version is LuaJIT 2.0.5.
> This release has various bugfixes over 2.0.4 — an update is recommended.

[LuaJIT Download](https://luajit.org/download.html).
[LuaJIT Change History](https://luajit.org/changes.html).

**Comment by Tripperful** [comment]
It should be [there](https://github.com/Facepunch/garrysmod-requests/issues) I guess
