### ISSUE TITLE
SoundDuration returns 0 in server side.

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-issues#3306]
Bug : SoundDuration will return 0 in the server side

Example : 
`print(SoundDuration("vo/Breencast/br_collaboration02.wav"))`

**Comment by Kefta** [comment]
Related https://github.com/Facepunch/garrysmod-issues/issues/936

**Comment by hanm13** [comment]
It does give the right value in the client side but not in the server side.

**Comment by hanm13** [comment]
@robotboy655 can you confirm it ?

**Comment by robotboy655** [comment]
No I can't, really:
![image](https://user-images.githubusercontent.com/3299036/30851471-6c54e1ac-a2b1-11e7-992d-83096fe5f488.png)

Probably duplicate of #936

**Comment by hanm13** [comment]
```
lua_run print(SoundDuration("msuic/hl1_song10.mp3"))
> print(SoundDuration("msuic/hl1_song10.mp3"))...
0
lua_run print(SoundDuration("msuic/hl1_song10.mp3")/2)
> print(SoundDuration("msuic/hl1_song10.mp3")/2)...
0

```


I am using Linux Centos.

**Comment by TIMONz1535** [comment]
Does not work on Linux dedicated server properly, always return 0. Everything works on Windows.
