### ISSUE TITLE
file.Append Ignores \n

### ISSUE THREAD

**Issue by 10853** [Facepunch/garrysmod-issues#331]
Title says it all. It's possible to work around this by using the tried-and-true file.Open/file.Write/file.Close method, but doing so kinda defeats the purpose of having a shortcut for it in the first place.

**Comment by bmwalters** [comment]
I was unable to reproduce this with the following steps:
1. Create a file named "test.txt" in the data folder.
2. Edit the file to set its contents to "hello world\n" (trailing newline)
3. Run the following code:
```lua
file.Append("test.txt", "hey\nworld\n")
```
4. The file contains newlines as expected.
