### ISSUE TITLE
Gmod codebase is still using self.Owner

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3310]
https://github.com/Facepunch/garrysmod/search?utf8=%E2%9C%93&q=self.Owner&type=
![da728c108c_hl2_2017-10-03_06-38-49](https://user-images.githubusercontent.com/6339511/31104157-8b91f524-a805-11e7-8ac3-ec3627f76a8c.png)

**Comment by Kefta** [comment]
Submit a PR then.

**Comment by roboderpy** [comment]
ok

**Comment by CornerPin** [comment]
Close? Facepunch/garrysmod#1420
