### ISSUE TITLE
Timeouts and Extreme Lag on CentOS 7

### ISSUE THREAD

**Issue by ehnathan** [Facepunch/garrysmod-issues#3311]
I've using a Garry's Mod server to test out on a dedicated machine to diagnose lag issues and with that diagnoses, I have been doing a lot of research on how to properly optimize a Garry's mod server and I have tried everything with no luck. Once the server hits 55+ Players, everything lags like crazy.

Server Content-side:

120 addons, 12 File Addons (Including WoS Lightsabers,  ULX, Etc)

Server Configuration:

Server.cfg performance settings:

```
sv_minrate 450000 
sv_maxrate 0
sv_mincmdrate 10 
sv_minupdaterate 10
sv_maxcmdrate 12
sv_maxupdaterate 12 
net_splitpacket_maxrate 2097152

```

Server Command Line:

`./srcds_run -game garrysmod -console -norestart +r_hunkalloclightmaps 0 +rcon_password {{redacted}} -tickrate 12 -port 27015 +ip {{redacted}} +fps_max 0 +maxplayers 64 +map rp_kamino_standalone +hostname {{redacted}} +gamemode starwarsrp +host_workshop_collection {{redacted}} -authkey {{redacted}}`

Server Machine Specifications:

Operating System CentOS 7

Intel Xeon E5-1650v4 @ 3.6ghz (Server at max is only using 19% CPU)

1TB WD Black Hard Drive

16GB of Ram (Server at max is only using 1.1GB)

1Gbps Connection (Fiber Line)

**Comment by ehnathan** [comment]
Dealt with over ticket.

**Comment by xaviergmail** [comment]
@ehnathan Did this end up being a linux/garrysmod related issue?

https://xkcd.com/979/
