### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Szczupak** [Facepunch/garrysmod-issues#3316]
Every time I try to start or join a game, gmod crashes. It doesn't matter what map I try, or is it singleplayer or multiplayer. On singleplayer it crashes after loading resources, on multiplayer after sending client info. I tried removing all addons, clearing the cache and validating game files.

My OS is 64-bit Windows 10.

[crashlogs.zip](https://github.com/Facepunch/garrysmod-issues/files/1404115/crashlogs.zip)

**Comment by robotboy655** [comment]
Unmount TF2 for a fix for now

**Comment by robotboy655** [comment]
Fixed in dev
