### ISSUE TITLE
render.ClearDepth also clears the stencil buffer

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-issues#3317]
### Details
[render.ClearDepth](http://wiki.garrysmod.com/page/render/ClearDepth) clears not only the **depth buffer**, but also the **stencil buffer**.

### Code to reproduce
Uncomment the line with `render.ClearDepth`, and the blue shape of intersection won't be drawn
```lua
local RT = GetRenderTarget("image", 512, 512)

hook.Add( "HUDPaint", "StencilTest", function()
    render.PushRenderTarget(RT)
    cam.Start2D()
        render.Clear(0, 0, 0, 255, true, true)
        surface.SetDrawColor(255, 255, 255, 255)
        draw.NoTexture()
        
        render.SetStencilEnable(true)
            render.SetStencilWriteMask(255)
            render.SetStencilTestMask(255)
            render.SetStencilReferenceValue(1)
            
            render.SetStencilCompareFunction(STENCIL_ALWAYS)
            render.SetStencilPassOperation(STENCIL_INCRSAT)
            render.SetStencilFailOperation(STENCIL_KEEP)
            
            surface.SetDrawColor(255, 0, 0, 255)
            surface.DrawRect(192, 192, 128, 128)
            
            surface.SetDrawColor(0, 255, 0, 255)
            surface.DrawPoly({
            	{x=256, y=150},
            	{x=356, y=350},
            	{x=156, y=350}
            })
            
            render.SetStencilReferenceValue(2)
            render.SetStencilCompareFunction(STENCIL_EQUAL)
            --render.ClearDepth()
            
            surface.SetDrawColor(0, 0, 255, 255)
            surface.DrawTexturedRect(0, 0, 512, 512)
        render.SetStencilEnable(false)
    cam.End2D()
    render.PopRenderTarget()
    
    
    render.DrawTextureToScreenRect(RT, 0, 0, 512, 512)
end )
```
Without **render.ClearDepth**:
![image](https://user-images.githubusercontent.com/7669876/31853518-69e0a02e-b692-11e7-92b5-e1acb10883ca.png)
With **render.ClearDepth**:
![image](https://user-images.githubusercontent.com/7669876/31853520-7eaca30e-b692-11e7-92f8-b6e19e192e84.png)

**Comment by CornerPin** [comment]
Can easily be fixed as it just calls [IMatRenderContext::ClearBuffers](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/materialsystem/imaterialsystem.h#L1113) with **bClearStencil** being **true**.

**Comment by Kefta** [comment]
You can work around this by using [render.Clear](http://wiki.garrysmod.com/page/render/Clear), instead. You'll have to clear the color to the current color since there doesn't seem to be an option to skip that operation.

**Comment by thegrb93** [comment]
Thanks for the workaround. This is a pretty big issue for one of my addons.

**Comment by robotboy655** [comment]
You can now do `render.ClearDepth( false )` to not clear the stencil buffer.
