### ISSUE TITLE
GMOD crashes when joining a defined server

### ISSUE THREAD

**Issue by karl-police** [Facepunch/garrysmod-issues#3318]
**### Details**
I've put the crash log here I hope the link is fine.
Crash Log: https://workupload.com/file/SykHxQk

I was searching SCP gamemode servers looking around connecting different servers. At one server I noticed that a model was invisible, maybe because of conflicting issues. Then I joined a server which has this IP: 149.56.194.242:27015
No, I'm not advertising, it happend on that server and I even restarted my gmod and it did not fix.

The point is that GMOD crashed and it should not crash, it should try to prevent it from the crash or atleast tell us why it crashes, I hope the crash log is fine. I would really like to know how to get information about it.

**### Steps to reproduce**

This is very hard because the problem might has to do with something about conflicting addons.

Open GMOD
Connect to the IP listen above.
See?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3316
