### ISSUE TITLE
L4D branch props not working as static props and .dx80.vtx -StaticPropLighting crash.

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-issues#3320]
I noticed when using props from L4D branch games like Portal 2 and Counter-Strike Global Offensive, that almost none of them work as static props (prop_static), VBSP says that it failed to load the .mdl file for the prop.  The [IDST1 Header](https://gyazo.com/bbbfcfba10441161b5d1e9e8ceca7d1f) in the .mdl file seems to be the problem, I extracted and changed one of the prop's .mdl Header to IDST0 (Orangebox) using a Hex Editor, and the prop successfully loaded as a static prop.

Although a second issue pop'd up after changing the Header to IDST0, since many L4D branch .mdl files don't have .dx80.vtx files to accompany them, VRAD reports that the prop is missing it's .dx80.vtx file, this isn't really an issue unless you add -StaticPropLighting to VRAD's parameters, VRAD will compile lighting for the map, but once you load up the map, it will crash once you look at the prop without reason (or freeze indefinitely if you spawned looking at the prop).  I tried using a custom prop meant for the Orange Box, and removed it's .dx80.vtx file, and the same thing happened when compiling with -StaticPropLighting.

[StaticPropTesting.zip](https://github.com/Facepunch/garrysmod-issues/files/1416565/StaticPropTesting.zip)

The .zip file has the map, and 2 versions of the model I used for testing, along with a .mdmp dump file that got made during the -StaticPropLighting crash and of course, a .txt file that has the steps to reproduce these 2 errors.

**Comment by robotboy655** [comment]
Both of these should be fixed a while back.
