### ISSUE TITLE
GravGunPickupAllowed is only called serverside

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3325]
The hook is never called clientside despite being documented as shared. If that's the intentional behaviour then the wiki and function location in the base gamemode should be altered to reflect so.

**Comment by robotboy655** [comment]
Looking at the code, it seems to be by design

**Comment by Kefta** [comment]
Yeah, I didn't expect too much adapting from the HL2 grav gun in GMod

**Comment by robotboy655** [comment]
Late, but the documentation on the wiki was correct until someone named "Pyro-Fire" changed it to be incorrect the same day you made this ticket.

**Comment by Kefta** [comment]
It should probably be moved from shared in the base gamemode then.
