### ISSUE TITLE
player.GetCount() return as nil

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#3332]
GetCount return as nil.

```
[ERROR] gamemodes/hl2c-iceman/gamemode/server/init_postentity.lua:944: attempt to call field 'GetCount' (a nil value)
  1. unknown - gamemodes/hl2c-iceman/gamemode/server/init_postentity.lua:944
```

**Comment by bigdogmat** [comment]
You've probably overwritten the `player` global with a local in your scope.

**Comment by kem008** [comment]
I cant find player.GetCount in the basic lua files. I didnt overwritten the player global.

**Comment by neico** [comment]
The entire point of the function is that it comes from the C side, so yes, you won't find it in a lua file.

And if you aren't overriding the global someone else is, try without addons etc.
