### ISSUE TITLE
DTextEntry:GetText() is Trimming Off the Last Letter (DEV BRANCH)

### ISSUE THREAD

**Issue by Luabee** [Facepunch/garrysmod-issues#3334]
### Details
I just ran into an issue **on the dev branch** with DTextEntry:GetText() returning all but the final character of the actual text.

It was applying to both singleplayer games on the dev branch and on multiplayer servers which were not on the dev branch.

I switched off of the dev branch and it was fixed.

### Steps to reproduce
Once I noticed the issue, I used this code to test it:
```
local frame = vgui.Create("DFrame")
frame:SetSize(300,100)
frame:Center()
frame:MakePopup()

local lbl = vgui.Create("DLabel",frame)
lbl:Dock(TOP)
lbl:SetText("")

local entry = vgui.Create("DTextEntry",frame)
entry:Dock(TOP)
function entry:Think()
    lbl:SetText(self:GetText())
end
```
The label was always showing the text minus one letter. For instance, "**Rubat's thicc ass**" would show "**Rubat's thicc as**".

**Comment by robotboy655** [comment]
Should be fix
