### ISSUE TITLE
Recording software doesn't record gmod's sound

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#3335]
Tried with OBS and with Bandicam

On bandicam and OBS , even recording the whole screen doesn't record gmod's sound

Video showing the problem : https://www.youtube.com/watch?v=6z1LiBRS4-o

Could be linked to #3326

**Comment by robotboy655** [comment]
OBS definitely works for me with these settings and game capture:
![image](https://user-images.githubusercontent.com/3299036/33508597-fc17c1c0-d703-11e7-92a1-5a10a42e8e59.png)

**Comment by Kefta** [comment]
@ExtReMLapin That issue is in regards to Linux

**Comment by ExtReMLapin** [comment]
It was a Xonar DGX drivers issues, reinstalling drivers fixed the whole shit


fucking hell
