### ISSUE TITLE
Entity:GetSequenceActivity(seq) improper bound check

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3336]
GetSequenceActivity for sequences less than -1 will return the same sequence number as the 1st (0th index) sequence. GetSequenceActivityName, on the other hand, will return "Unknown" and throw an out-of-bounds dev message.

**Comment by robotboy655** [comment]
Should be solved. Will return -1 for any sequence id out of bounds properly now.
