### ISSUE TITLE
PLAYER:Give() can spawn things other than just weapons

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-issues#3339]
http://wiki.garrysmod.com/page/Player/Give

The wording makes it sound like the function is intended for weapons only. However, it will allow you to spawn a variety of entities including NPCs and SENTs. Doesn't work on vehicles (`Attempted to create unknown entity type Pod! NULL Ent in GiveNamedItem!`)

```lua
Entity(1):Give( "npc_alyx" )
Entity(1):Give( "edit_fog" )
Entity(1):Give( "sent_ball" )
Entity(1):Give( "gmod_playx") -- with the PlayX addon
```
Etc.

**Comment by Kefta** [comment]
Pretty sure this just uses the same method internally as the "give" concommand, which can spawn any entity.

**Comment by Mista-Tea** [comment]
The behavior is unexpected for PLAYER:Give() considering the wiki only ever mentions it in the context of giving weapons. In my case, this lead to players spawning NPCs/SENTs where they shouldn't have been.

**Comment by robotboy655** [comment]
This feels like a non issue to me. If you let any user basically directly call Player.Give on your server its kinda your fault.

It IS _intended_ for weapons only, but it is NOT restricted to weapons only. I guess it is something wiki failed to mention and I am at fault there. It is fixed.

**Comment by Mista-Tea** [comment]
I wasn't just letting players directly call ply:Give() without having my own checks in place, but I had no idea the function would work with things other than weapons.

Thanks for taking the time to clarifying things and the wiki edit. That will hopefully prevent confusion in the future.
