### ISSUE TITLE
Low Quality Texture Bug?

### ISSUE THREAD

**Issue by MattDistraction** [Facepunch/garrysmod-issues#334]
![2013-07-29_00002](https://f.cloud.github.com/assets/5117305/876024/05da794a-f8b6-11e2-8a71-2f3ac3e19fc6.jpg)
This was taken in Gmod 13.07.07.

Lately my gmod's been running looking like pic above and I have no idea how to fix it. It sort of looks like how distant objects are supposed to swap out for lower quality models and textures, only up extremely close. I tried changing the texture settings, but there appeared to be no difference in quality. I ran gmod in DirectX 8 and 9, but the problem persisted. Verifying the cache yielded no results, and deleting/reinstalling the game entirely still fixed nothing. Next I'm considering disabling or unsubscribing from most of my addons, but I wouldn't think that would change much considering the problem was still there even before they began reinstalling.

This bug is really ruining gmod for me, so if anyone can help, I'd appreciate it.

Here's my specs- they shouldn't be part of the problem as gmod has ran absolutely fine on my pc in the past.

![specs](https://f.cloud.github.com/assets/5117305/876063/96bbd548-f8b7-11e2-9bb8-8fdf3f29d63a.jpg)

**Comment by Availer2121** [comment]
I know I might be late but I am desperate and have this exact problem, I honestly dont know what to do to fix it.

**Comment by thegrb93** [comment]
Bad addon can cause it. Could also be a setting.

**Comment by Availer2121** [comment]
I reset all my addons and it still deosnt work
I uninstalled and reinstalled, even factory reset
still no results

**Comment by thegrb93** [comment]
make sure you delete the garrysmod folder in addition to uninstalling
