### ISSUE TITLE
Collision Issues/Invisible Walls in Portal 2 and CSGO Maps

### ISSUE THREAD

**Issue by MrGibb** [Facepunch/garrysmod-issues#3342]
### Details
Recent updates to Gmod have allowed the loading of maps from Counter-Strike: Global Offensive, Portal 2, and even Source Filmmaker. In testing, all of the maps from these games have collision issues regarding projectiles, physical objects, NPCs, and tracers. These do not impede player movement, but severely impact the gameplay of these maps in other ways.

Issues include the inability for the Physgun to project its beam beyond the gun itself or running into invisible barriers. STools are similarly non-functional.

![sp_a2_ricochet_physgunissue2](https://user-images.githubusercontent.com/23620399/33579924-9a0925ee-d908-11e7-85c4-414a0167ae00.jpg)

Weapons exhibit strange issues. Tracers often fly off-center from the crosshair, bullets do not make contact with surfaces or NPCs, and ejected shell casings float in the air.

![de_stmarc_floatingshells](https://user-images.githubusercontent.com/23620399/33579213-38a57192-d906-11e7-8874-0788ff2d6df1.jpg)

Ragdolls often spawn strangely, suspended in the air for a time. NPCs often spawn in the air and cannot see the player or hostile NPCs.

![cs_agency_mossmanspawn](https://user-images.githubusercontent.com/23620399/33579328-ae43db14-d906-11e7-8050-4cf75260d546.jpg)
![de_sugarcane_npcspawn](https://user-images.githubusercontent.com/23620399/33579664-c6e6ec6e-d907-11e7-8096-fd9b1795b030.jpg)

While every CSGO and Portal 2 map I've tested has this problem, the severeness of the issue varies. Some maps have large areas where no collision issues are noticed, others have pervasive issues across the map. 

Interestingly, maps from Left 4 Dead and Left 4 Dead 2 do not seem to have these collision issues as of the latest dev built at this time.

### Steps to reproduce
Tell us how to reproduce the problem, step by step

Load a map from Counter-Strike: Global Offensive or Portal 2 in Gmod. As of the latest dev build, I've tested "cs_agency", "de_stmarc", and "de_sugercane" from CSGO. Also "sp_a2_ricochet" and "mp_coop_catapult_1" from Portal 2.

Attempt to use the Physgun, spawn ragdolls, fire weapons, etc. "de_stmarc" is especially problematic and makes the issues easy to spot.

**Comment by Kefta** [comment]
The support for the maps is still in progress. These specific issues are probably from incorrect structs for clips brushes and triggers.

**Comment by robotboy655** [comment]
I am not exactly sure what causes this. I tried even decompiling some maps with these problems and there's nothing out of the ordinary in places where it happens.

**Comment by Kefta** [comment]
I've been investigating this issue a bit more and there is definitely some weird things happening. On ``surf_starfire_csgo``, I've managed to replicate a few issues:
- Traces will randomly mix up their start and end positions
- Traces travel through solids and the world
- Traces return different results between the client and server

All of these issues appear at the same time and I haven't been able to isolate them. Here's a video showing off my findings:
<iframe width="560" height="315"
src="https://www.youtube.com/watch?v=iCDY7-TE1qc" 
frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>

Trace gun code:
```
-- Test in multiplayer so PrimaryAttack is run in both realms
-- Red = server, blue = client

local DEBUG_TRACE = false

local vClientStart, vClientEnd

function SWEP:PrimaryAttack()
	if (IsFirstTimePredicted()) then
		local pPlayer = self:GetOwner()

		if (pPlayer:IsValid()) then
			local vStart = pPlayer:GetShootPos()
			local vAimVector = pPlayer:GetAimVector()
			vAimVector:Mul(16384 * math.sqrt(3)) -- Max map distance

			local tr = util.TraceLine({start = vStart, endpos = vStart + vAimVector, filter = pPlayer})

			if (DEBUG_TRACE) then PrintTable(tr) end
			if (tr.StartPos ~= vStart) then print("tr.StartPos doesn't match the actual start!") end

			if (SERVER) then
				net.Start("weapon_tracetest")
					net.WriteVector(tr.StartPos)
					net.WriteVector(tr.HitPos)
				net.Send(pPlayer)
			else
				vClientStart = tr.StartPos
				vClientEnd = tr.HitPos
			end
		end
	end
end

if (SERVER) then
	util.AddNetworkString("weapon_tracetest")
else
	local vServerStart, vServerEnd

	net.Receive("weapon_tracetest", function()
		vServerStart = net.ReadVector()
		vServerEnd = net.ReadVector()
	end)

	hook.Add("PostDrawTranslucentRenderables", "weapon_tracetest", function()
		if (vServerStart == nil or vServerEnd == nil) then return end
		render.DrawWireframeSphere(vServerStart, 5, 50, 50, Color(255, 0, 0))
		render.DrawWireframeSphere(vServerEnd, 25, 50, 50, Color(255, 0, 0)) -- End spheres are five times as big

		if (vClientStart == nil or vClientEnd == nil) then return end
		render.DrawWireframeSphere(vClientStart, 5, 50, 50, Color(0, 0, 255))
		render.DrawWireframeSphere(vClientEnd, 25, 50, 50, Color(0, 0, 255))
	end)
end
```

**Comment by zxz41** [comment]
From what I found it seems to be an issue related to visleafs. What happends if the map is repacked without/fast VVIS?

On `sp_a2_ricochet` I found the following leafs to cause raytrace issues.
```
Leaf 34, Area 1, Cluster 8
Leaf 124, Area 1, Cluster 41
Leaf 127, Area 1, Cluster 44
Leaf 119, Area 2, Cluster 37
Leaf 126, Area 2, Cluster 43
Leaf 129, Area 2, Cluster 46
Leaf 138, Area 2, Cluster 51
Leaf 293, Area 2, Cluster 132
```
I don't have the tools right now to recompile VVIS for Portal 2/CSGO. So I won't be able to test a recompiled version.

**Comment by willox** [comment]
fixed in the dev branch
