### ISSUE TITLE
IGModAudioChannel:SetTime( ) bug

### ISSUE THREAD

**Issue by ZpyduCat** [Facepunch/garrysmod-issues#3346]
### Details
изотово што в одном потоке все работает то при болших перемотках игра силно зависает.
решение: переместит перемотку в другой поток.
**_пожалузто fiks_**

### Steps to reproduce
ну и так все понятно...
береш музло
потом перематываешь примерно на (3 или больше) минуты и может зовиснуть...

### P.S.
робот мне лен на англицки переводить читай нослождайся
а ещо в правилах не написано на каком языке писать....

**Comment by iagrib** [comment]
Wha?

**Comment by ZpyduCat** [comment]
че не так то, робот....

**Comment by robotboy655** [comment]
English only.

**Comment by ZpyduCat** [comment]
покажи где сказано что инглиш онли

**Comment by ZpyduCat** [comment]
а сам баг то пофиксиш? плз

**Comment by RenTec** [comment]
..... *Sigh*
