### ISSUE TITLE
Sound.PlayFile function arguments constant BASS error

### ISSUE THREAD

**Issue by RenTec** [Facepunch/garrysmod-issues#3348]
Looks like [sound.PlayFile](http://wiki.garrysmod.com/page/sound/PlayFile) throws a BASS error every time when trying to play anything.

```Lua
sound.PlayFile( "ambient/machines/combine_shield_loop3.wav", "mono", function( station, num, err )
  if ( IsValid( station ) ) then
    station:Play()
  else
    print(num,err)
  end
end )
```
**_Console: BASS_ERROR_FILEOPEN_**

Happens no matter the variable names or file path with any local sounds.

**Comment by CornerPin** [comment]
You forgot to put "sound/" at the beginning of the path.

**Comment by RenTec** [comment]
Shouldn't be required according to the wiki and I don't recall ever having
to use the sound/ prefix before. Wiki example doesn't work, GitHub code
references don't work, code posted 6 days ago on Facepunch that did work
now doesn't work.

**Comment by robotboy655** [comment]
The wiki example works for me I just tested it a few days ago, which means its a problem on your side.

**Comment by Grocel** [comment]
This is caused by the auto looping sound which are not supported by BASS yet.

**Comment by robotboy655** [comment]
You DO need the "sound/" bit.

```
sound.PlayFile( "sound/ambient/machines/combine_shield_loop3.wav", "mono", function( station, num, err )
  if ( IsValid( station ) ) then
    station:Play()
  else
    print(num,err)
  end
end )```

This works, but doesn't loop automatically for reasons stated above.

**Comment by Grocel** [comment]
Yeah that "sound/" path thing is needed too of course. The point I meant was that auto looping sound files has cues in them which BASS used to to not like much causing it to error with "unknown error" or other errors quite often. Maybe that problem got already fixed in the past.

That auto looping is a source thing. So BASS does not auto loop the files of course, which is fine.
