### ISSUE TITLE
Crash when playing multiplayer modded sandbox

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3350]
### Details
I can't analyze the crash, seems like it happened random, but I don't know.
https://www.dropbox.com/s/p4s59i80yjqvckd/hl2_171219_crash_2017_12_22T14_34_20C0.mdmp?dl=0

### Steps to reproduce
there are none.

**Comment by robotboy655** [comment]
It's a vphysics crash related to ragdolls, congrats.

**Comment by mcNuggets1** [comment]
It was clientside tho. lol.

**Comment by thegrb93** [comment]
I imagine clientside still does some vphysics simulation for prediction or jigglebones.

**Comment by robotboy655** [comment]
Probably duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3327 ,stale report.
