### ISSUE TITLE
Hydraulics do not have a "Toggled" checkbox

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#3351]
### Details
Hydraulic does not have a non-toggled/toggled option

### Steps to reproduce
When connecting two props with hydraulics you have to press the action button again to contract the hydro when it is already stretched.

### Possible solution
When adding "Toggled" checkbox flag the player will be able to contract the hydraulics on active key release ( a.k.a The player can release the key to contract the hydraulic ). The old behavior can be done when the "Toggle" checkbox is checked ( a.k.a The player must hit the activating key again to contract the hydraulic )
![20171225115208_1](https://user-images.githubusercontent.com/9112662/34337872-ce3a090a-e96b-11e7-95be-65c0afaa0eb1.jpg)
![20171225115321_1](https://user-images.githubusercontent.com/9112662/34337873-ce56c536-e96b-11e7-9313-76e4ac8ad5d8.jpg)
![20171225115330_1](https://user-images.githubusercontent.com/9112662/34337874-ce77351e-e96b-11e7-94ce-adb4092a7ee9.jpg)

### Possible application
The player will be able to build turning cars without using thrusters or wiremod.

**Comment by robotboy655** [comment]
It's not a bug. This is not the place to request things.
