### ISSUE TITLE
Flashlight ragdolls/playermodels blood bug

### ISSUE THREAD

**Issue by flah65** [Facepunch/garrysmod-issues#3352]
Well. Community forget say to you about existing bug over years.
When you point flashlight on ragdoll with blood on it, blood just makes invinsible(alpha zero?)
Also if players have blood on their body that bug work too.
![image](https://user-images.githubusercontent.com/24764580/34340559-337418d8-e9c1-11e7-9d02-4978590dc3b1.png)
![image](https://user-images.githubusercontent.com/24764580/34340561-4437cdc2-e9c1-11e7-887b-0fea48145174.png)

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2954
