### ISSUE TITLE
OSX rapid scroll glitch

### ISSUE THREAD

**Issue by rudeustudeus** [Facepunch/garrysmod-issues#3353]
### Details
On MacOS/OSX, scrolling in-game on Garry's Mod is really broken since 2013 now.
If I scroll forwards, it sometimes goes forward, or it just goes backwards, regardless of that it scrolls way too far to be usable. Regardless of physgun_wheelspeed, whether it is 20 or 99999 it is really messed up. I often kill myself with props due to this issue.

Furthermore it also affects in-game menus like the spawn menu and anything else that is derma and scrollable. 

### Steps to reproduce
On the OSX client for Garry's mod (I used MacOS Sierra 10.12 and 10.12.4)

Try to move a prop with the physgun using your mouse wheel. It simply does not work, I have tested this issue on my imac and macbook pro with the same results.

I have recorded a short LQ video below.

https://www.youtube.com/watch?v=j6VufIOIhJo

**Comment by aimeec1995** [comment]
I should also say the cursor often dissapears in-game but it is easy enough to replicate in the menu with lua that I don't really care. I am going to look into making a video about my issue now

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2772
