### ISSUE TITLE
Barnacle "Bone-Spitting" Bug

### ISSUE THREAD

**Issue by Dobbi124** [Facepunch/garrysmod-issues#3354]
### Details:
On the latest developmental version of Garry's Mod (As of12.27.17), I was play testing with the Barnacles, and I stumbled into an issue. The issue is that whenever a Barnacle eats something, for example an Antlion, the bones it would spit out would be instantly grabbed by the Barnacle and would be latched onto the tentacle of the Barnacle. I'm not sure if this is suppose to happen because it seems weird that this feature would be intended for it to constantly and instantaneously latch onto the remains it regurgitates.   

### Steps to Reproduce:
1. Make a singleplayer game.
2. Spawn in a Barnacle.
3. Spawn in an NPC (I suggest Antlion because I did Antlion.)
4. Make the Antlion become latched onto by the Barnacle.
5. Make sure that the Barnacle is not injured, latches off of it's prey, or just altered at all during this time to make results more accurate.
6. Make sure the creature you have chosen is eaten.
7. Observe the Barnacle after it has eaten, and watch for any bones it spits out, and watch how it grapples onto them so quickly.

Hopefully this helps because I searched GitHub and saw nothing else pertaining to this topic.

![20171227174345_1](https://user-images.githubusercontent.com/34899129/34395611-a1bd0b6e-eb2f-11e7-8358-6bff2646e038.jpg)
![20171227174346_1](https://user-images.githubusercontent.com/34899129/34395613-a48e6f0e-eb2f-11e7-91f9-722750efa44d.jpg)
![20171227174347_1](https://user-images.githubusercontent.com/34899129/34395615-a8bf4a12-eb2f-11e7-8bab-f9bd0fbcbaf5.jpg)
![20171227174349_1](https://user-images.githubusercontent.com/34899129/34395616-aabb70de-eb2f-11e7-9c17-17063f671041.jpg)
![20171227174350_1](https://user-images.githubusercontent.com/34899129/34395617-ac6e2f16-eb2f-11e7-840e-cfcc6b7af3e0.jpg)
![20171227174351_1](https://user-images.githubusercontent.com/34899129/34395618-ae35c4ee-eb2f-11e7-9bb3-6bb8cae673b9.jpg)
![20171227174402_1](https://user-images.githubusercontent.com/34899129/34395620-af8dd200-eb2f-11e7-8189-f42781c61a75.jpg)

**Comment by robotboy655** [comment]
This is the exact same behavior in vanilla HL2
