### ISSUE TITLE
Crash on load in Arch Linux

### ISSUE THREAD

**Issue by soup6020** [Facepunch/garrysmod-issues#3355]
Log here: https://ghostbin.com/paste/qw7w4
This happens when I run from Steam, and launch hl2.sh manually. I have an i5-7500, an RX 480 using amdgpu, and 16 GB of RAM. I am on the latest development build.

**Comment by aimeec1995** [comment]
Make sure multicore rendering is disabled, it is broken at the moment and will likely remain that way for linux/osx.

Try setting the parameters to disable it in your launch options maybe

**Comment by superE03** [comment]
Disabling multicore rendering did not fix the problem. The output is exactly the same.
