### ISSUE TITLE
Vehicle and Weapon Changing Bug

### ISSUE THREAD

**Issue by Spitfire01** [Facepunch/garrysmod-issues#3356]
### Details
On Windows version 2017.12.19; When you get out of a vehicle and you try changing your weapon/tool it doesn't scroll or change the type of weapon, it just doesn't happen. The 'HUD' to select your weapon does not appear at all.

### Steps to reproduce
1) Spawn in a vehicle,
2) Get in and drive, doesn't matter the length of movement.
3) Get out and try scrolling to change your weapon.

**Comment by robotboy655** [comment]
I am going to say this is a mod problem or a problem on the server you are playing on. I cannot reproduce this without any mods.

You should try doing the same, add ```-noworkshop -noaddons``` to your launch options for gmod, that will temporarily disable all your addons, and then try doing your steps in singleplayer.
