### ISSUE TITLE
Player remains burning while not ignited

### ISSUE THREAD

**Issue by aurowora** [Facepunch/garrysmod-issues#3358]
Hello! I have a SWEP that ignites the owner in its Think hook, something like 

function SWEP:Think()
	if SERVER then
		self.Owner:Ignite(0.1,100)
        end
end

The SWEP is a part of the breach gamemode, but I do not believe that it is an issue with the Breach gamemode.
Full code: [weapon_scp_457.zip](https://github.com/Facepunch/garrysmod-issues/files/1596550/weapon_scp_457.zip)

The issue is that occasionally the player who once had the SWEP will remain on fire after dying, being stripped, or any other event that would cause them to no longer have the SWEP. I can confirm that the player is not being ignited from any other source. The player does not actually seem to be ignited, rather the fire effect is not stopped. The player does not take burning damage and ply:Extinguish() has no effect.
ply:IsOnFire() returns false as well. The only way the fire stops is if the client in question leaves and rejoins the server. This does not seem to occur every time, as most of the time, the fire stops as it should.

If more information is needed, I will try my best to provide it.

EDIT: GMOD version is 2017.12.19

**Comment by ZehMatt** [comment]
Welcome to the unreliable networked sounds.

**Comment by LeQuackers** [comment]
Probably related to [recipientfilter.cpp#L409](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/recipientfilter.cpp#L409) (credit to [thegrb93](https://github.com/Facepunch/garrysmod-issues/issues/2793#issuecomment-243013611)). [EntityFlame.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/EntityFlame.cpp) uses ```EmitSound( "General.StopBurning" )``` to stop the burning noise, which doesn't happen if you're too far away.

**Comment by LeQuackers** [comment]
This seems to fix it.

Setup:
- ignite a prop/bot/player
- move more than 2500 units away or under the map
- undo prop or kill bot/player
```
if CLIENT then
	hook.Add("EntityRemoved", "issue-3358", function(ent)
		if ent:GetClass() == "entityflame" then
			ent:EmitSound("General.StopBurning")
		end
	end)
end
```

**Comment by robotboy655** [comment]
Applied that fix to the entity itself and it seems to work in my tests. Let me know if the issue pops up again after the next big update or on 'dev' beta.
