### ISSUE TITLE
OBBMaxs() returns wrong value while ducked

### ISSUE THREAD

**Issue by dearmochi** [Facepunch/garrysmod-issues#336]
Even after using SetHullDuck numerous times, OBBMaxs() returns Vector(16, 16, 60)

```
] lua_run Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 1))
> Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 1))...
> print(Player(6):OBBMaxs())...
16.000000 16.000000 60.000000
] lua_run Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 65))
> Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 65))...
> print(Player(6):OBBMaxs())...
16.000000 16.000000 60.000000
] lua_run Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 100))
> Player(6):SetHullDuck(Vector(-16, -16, 0), Vector(16, 16, 100))...
> print(Player(6):OBBMaxs())...
16.000000 16.000000 60.000000
```

**Comment by Python1320** [comment]
Can confirm.

References at http://facepunch.com/showthread.php?t=1374457&p=46016660&viewfull=1#post46016660 for why it doesn't seem to work.
And now a video at http://facepunch.com/showthread.php?t=1450721&p=47461732&viewfull=1#post47461732

**Comment by robotboy655** [comment]
Ok, removing that HL2MP piece of code fixes the problem ( HL2MP code was overriding the GMod collision bounds set by GMod ), but it does not fix the prediction errors, which also occur with the non ducked function.
