### ISSUE TITLE
sound.Generate can not make sounds less than 1 second long

### ISSUE THREAD

**Issue by vingard** [Facepunch/garrysmod-issues#3360]
sound.Generate can not make sounds less than 1 second long. Please can this be fixed?

**Comment by Kefta** [comment]
![](https://i.imgur.com/sE0Wnoz.png)

Are these related? If so, can the fix be applied to the main branch?

**Comment by robotboy655** [comment]
Considering the commit is about a different function/problem, no

**Comment by robotboy655** [comment]
I seemingly cannot reproduce this.
```
local frequency = 2000 -- Hz
local samplerate = 44100

local function data( t )
	return math.sin( t * math.pi * 2 / samplerate * frequency ) 
end

for i=1,10 do
	timer.Simple( i, function()
		sound.Generate( "testsnd_" .. i, samplerate, 0.1 * ( 10 - i ), data )
		surface.PlaySound( "testsnd_" .. i )
	end )
end
```

Using this code it generates increasingly shorter sounds that are all less than 1 second long.
