### ISSUE TITLE
cam.Start does no type checking on argument

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3361]
It even seems to still create a render instance, regardless of the argument given.

**Comment by robotboy655** [comment]
It falls back to 3D and default parameters for every table member in this case.

I am hesitant to change this because some crappy mod might break.

**Comment by Kefta** [comment]
I don't think it would looking through the GitHub code instances (most people use Start3D, anyway) but I think it should error to let the mod maker know they're sending in an improper argument.

**Comment by robotboy655** [comment]
It now errors when given no arguments.
