### ISSUE TITLE
Player:RealName() returns steam name that is set when joining server and doesn't update

### ISSUE THREAD

**Issue by LewisLector** [Facepunch/garrysmod-issues#3364]
### Details
When you go to get someones RealName() after they've changed Steam Name it still returns the old name and doesn't update on server unless they rejoin

### Steps to reproduce
1. Print own RealName()
2. Change Nickname on steam
3. Print RealName() again and note it's previous nickname.

**Comment by bigdogmat** [comment]
`player:RealName()` isn't a method in Gmod by default, this is an addons/gamemodes fault.

**Comment by LewisLector** [comment]
I just realized.
