### ISSUE TITLE
Crash with point-sized hull

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3365]
Code: ``lua_run Entity(1):SetHull(vector_origin, vector_origin)``
Dump: https://drive.google.com/uc?id=1ajTmgIJ-PWRn-vy0CiUcktSt-NpiiM-T

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.

**Comment by Kefta** [comment]
Does it just ignore the values now or create an actual point-sized hull?

**Comment by robotboy655** [comment]
No, it does not create a non existent hull.
