### ISSUE TITLE
Entity:InitializeAsClientEntity() crash a game

### ISSUE THREAD

**Issue by art-gur** [Facepunch/garrysmod-issues#3368]
### Details
When I using InitializeAsClientEntity function on fully clientside entity, I got a crash.

Example code:
```
local prop = ents.CreateClientProp()
prop:SetPos(Vector(0, 0, 0))
prop:SetModel("models/props_interiors/VendingMachineSoda01a.mdl")
prop:SetMaterial("models/shiny")
prop:SetColor(Color(255, 255, 0))
prop:SetParent(LocalPlayer())
prop:InitializeAsClientEntity() 
prop:Spawn()
```
[MDMP-file](https://drive.google.com/file/d/1wPOJa6Vs76TM-qIiRXXbTQwPss0EjnGS/view)

### Steps to reproduce
Use a broken function for clientside only prop.

**Comment by robotboy655** [comment]
I think the problem here is that ents.CreateClientProp() already calls InitializeAsClientEntity internally.

**Comment by robotboy655** [comment]
Don't use InitializeAsClientEntity(). It should probably be removed.
