### ISSUE TITLE
thirdperson_mayamode acting weird

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3369]
### Details
If you enable it, switch map, you still have thirdperson, but a weird one.

### Steps to reproduce
sv_cheats 1, thirdperson, thirdperson_mayamode, changelevel gm_construct

**Comment by Kefta** [comment]
This applies with the normal thirdperson concommand, as well. I reported it a while back to be told that the default thirdperson will never be fixed.

**Comment by robotboy655** [comment]
Its kinda pointless to fix it since there are infinitely better 3rd person mods out there, wouldn't you agree?

**Comment by mcNuggets1** [comment]
I am only using the built in.

**Comment by Kefta** [comment]
While I agree Lua thirdpersons will always be better, it would be nice for the changelevel bug to be fixed so it can be used for quick debugging.

**Comment by mcNuggets1** [comment]
Such things as the maya mode doesn't seem to exist in the workshop tho.

**Comment by Kefta** [comment]
You can pretty easily recreate it in Lua.

**Comment by robotboy655** [comment]
So basically the problem is that it doesn't shut itself off on changelevel and gets stuck in very close distance to the player model, is that it?

**Comment by mcNuggets1** [comment]
That should be it.

**Comment by mcNuggets1** [comment]
Thanks for fixing it, you are my bae.
