### ISSUE TITLE
Cyrillic.

### ISSUE THREAD

**Issue by flah65** [Facepunch/garrysmod-issues#3370]
Well. We all know that cyrillic fonts aren't supported(except roboto only). Okay, похуй.
Today I'm found that https://wiki.garrysmod.com/page/string/upper won't work with cyrillic too(cyrillic still have lowercase but it works great with english)!
2018. You know, many years from realese. Won't you try to fix this пиздец?

**Comment by robotboy655** [comment]
Basically same issue as https://github.com/Facepunch/garrysmod-issues/issues/2988
