### ISSUE TITLE
PostDrawHUD acting weird with fonts

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3371]
### Details
Seems like it fucks up fonts, when drawing them in PostDrawHUD, atleast for me, with almost no addons it does.

### Steps to reproduce
Hook into PostDrawHUD and draw a font with size < 20

**Comment by Kefta** [comment]
``lua_run_cl hook.Add("PostDrawHUD", "", function() surface.SetFont("DermaDefault") surface.SetTextColor(255, 255, 255, 255) surface.SetTextPos(ScrW()/2, ScrH()/2) surface.DrawText("Test text") end)``

Works fine for me in single-player.

**Comment by mcNuggets1** [comment]
I was using draw.SimpleTextOutlined with the Roboto Cn font, size 16 on the midscreen.

It was drawing the alphabetical letters incorrectly in a few sentences.
Switching to HUDPaint fixed it so far.

**Comment by Kefta** [comment]
Can you post exact code to replicate the issue?

**Comment by mcNuggets1** [comment]
`if CLIENT then
	surface.CreateFont("PVP_ScreenMsg", {font = "BebasNeue", size = 40, width = 1000, antialias = true})

	hook.Add("HUDPaint", "PVP_ScreenMessage", function()
		local scrw = ScrW()
		local scrh = ScrH()
		local offset = 0
		surface.SetFont("PVP_ScreenMsg")
		local size = surface.GetTextSize("player defeated bla bla bla bla bla")
		draw.SimpleTextOutlined("player defeated bla bla bla bla bla", "PVP_ScreenMsg", scrw / 2 - size / 2, scrh / 5 + offset, Color(255, 255, 255, 255), TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP, 1, Color(0, 0, 0, 255))
	end)
end`

**Comment by robotboy655** [comment]
Try multicore vs no multicore

**Comment by mcNuggets1** [comment]
It is not a multicore bug.

**Comment by mcNuggets1** [comment]
Already reported.

**Comment by adigram** [comment]
I have also run into that Issue. It only appears in PostDrawHUD. It is sice dependend: the smaller the font the bigger the effect. Same Code in HUDPaint will draw fine. Some Words have more of an Effect than Other. Maybe This is Charachter dependent ? I Notice that "g" gets cut of on the bottom on sizes lower than 20. And "C" somtimes has an extra line on the Left (see picture fontsize 20). 

![grafik](https://user-images.githubusercontent.com/62439584/79640532-5a650680-8192-11ea-99f1-5543d40e2ee6.png)
```lua
surface.CreateFont("testFont10", {font = "DermaDefault", size = 10})
surface.CreateFont("testFont15", {font = "DermaDefault", size = 15})
surface.CreateFont("testFont20", {font = "DermaDefault", size = 20})
surface.CreateFont("testFont23", {font = "DermaDefault", size = 23})
surface.CreateFont("testFont30", {font = "DermaDefault", size = 30})
surface.CreateFont("testFont40", {font = "DermaDefault", size = 40})
surface.CreateFont("testFont43", {font = "DermaDefault", size = 43})
local HudWC = ScrW()/2
local HudHC = ScrH()/2
local space = 30
local testText = "GRENATE CROWBAR"

hook.Add("PostDrawHUD", "ADI_bugReport_Funky_font", function()
	draw.SimpleText( testText.." 10" , "testFont10",HudWC, HudHC+space , color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 15" , "testFont15",HudWC, HudHC+space*2, color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 20" , "testFont20",HudWC, HudHC+space*3, color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 23" , "testFont23",HudWC, HudHC+space*4, color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 30" , "testFont30",HudWC, HudHC+space*5, color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 40" , "testFont40",HudWC, HudHC+space*6, color_white ,TEXT_ALIGN_CENTER)
	draw.SimpleText( testText.." 43" , "testFont43",HudWC, HudHC+space*7, color_white ,TEXT_ALIGN_CENTER)

	surface.SetFont( "testFont20" )
	surface.SetTextColor( 255, 255, 255 )
	surface.SetTextPos( HudWC, HudHC ) 
	surface.DrawText( "DrawText " ..testText )
end)
```

**Comment by GitSparTV** [comment]
Bruh you put Lua fonts in CreateFont...

**Comment by adigram** [comment]
Ops yes. But Still. I replaced it wit "Arial" still an issue.
