### ISSUE TITLE
ENT:Activate() After scaling a vehicle with bones; Game Crash

### ISSUE THREAD

**Issue by WasabiThumb** [Facepunch/garrysmod-issues#3372]
### Details
Every vehicle that is not a chair in the unmodded game (Jeep, Airboat leads me to the conclusion this only happens with boned vehicles) will crash after using ENT:Activate() after ENT:SetModelScale(). Extremely frustrating, because resizing vehicles will now result in inaccurate physboxes. No!!!
[MDMP FILE](https://mega.nz/#!dmwWWA4Q!Ec6LfgTd_qA-s-1Gs_wtGR4J8UUlDQJiM2WtsAF54T4)

### Steps to reproduce
1. Target a "boned" vehicle and set a local variable's value to it
2. Use ENT:SetModelScale(any integer) on it
3. Use ENT:Activate() on it
4. Watch your CPU usage soar and Garry's Mod slowly crash and burn
Example:
![Code](https://image.ibb.co/cd5wYb/Capture.png)
Output:
As soon as a valid "boned" vehicle comes into existence, your game crashes.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/48bdd1f8-30ea-4e10-a569-072782d60543)

```

	concommand.Add( "crash_vehicle", function(ply)
		ply:GetEyeTrace().Entity:SetModelScale( 2 )
		ply:GetEyeTrace().Entity:Activate()
	end )
```

**Comment by WasabiThumb** [comment]
Looking back, it was definitely the load of the operation on every think. I was dumb. But major props for properly investigating "issues" from over 6 years ago.
