### ISSUE TITLE
Add a blocked command for RunConsoleCommand !

### ISSUE THREAD

**Issue by TheCocasio** [Facepunch/garrysmod-issues#3373]
Hi, please add "_restart" in Blocked ConCommands (http://wiki.garrysmod.com/page/Blocked_ConCommands)

with
`ply:SendLua("RunConsoleCommand('_restart\')")`

You can make crash a Garry's mod client.

**Comment by Donkie** [comment]
There are many ways you can crash a client from the server, adding this wouldn't make any difference.

**Comment by TheCocasio** [comment]
That complicates the way to make crash a client.

**Comment by Donkie** [comment]
No, it really doesn't.
`ply:SendLua("while true do end")`

**Comment by TheCocasio** [comment]
Most owner server use RunConsoleCommand('_restart') for make crash.

**Comment by TheCocasio** [comment]
If you are here for trolling , get out.

**Comment by TheCocasio** [comment]
If you look http://wiki.garrysmod.com/page/Blocked_ConCommands , "exit" is here.

Why not "_restart"

**Comment by EgrOnWire** [comment]
@TheCocasio this is useless, as you can crash a client by doing __anything__ with client. There's issues which need to be fixed instead of those unneccessary blacklist changes.

**Comment by LewisLector** [comment]
If it's that scary remake the function and add it to a blacklist.

**Comment by joeyjumper94** [comment]
some server restart scripts run _restart on the server.
local RCC=RCC or RunConsoleCommand
if CLIENT then
	function RunConsoleCommand(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
		if string.lower(a)=="_restart" then
			error[[blocked _restart,
the third part of the stack should say where this function was called from.]]
		end
		RCC(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
	end
end
local meta = FindMetaTable( "Player" )

function meta:ConCommand(cmd)
	if string.StartWith(string.lower(cmd),"_restart") then
		if SERVER then
			for k,v in ipairs(player.GetAll()) do
				if v:IsAdmin() then
					v:PrintMessage(HUD_PRINTTALK,"someone check the server console")
				end
			end
		end
		error[[blocked _restart,
the third part of the stack should say where this function was called from.]]
	end
	if SERVER then
		self:SendLua("LocalPlayer():ConCommand("..cmd..")")
	else
		local tbl=string.Split(cmd," ")
		RCC(tbl[1],tbl[2],tbl[3],tbl[4],tbl[5],tbl[6],tbl[7],tbl[8],tbl[9],tbl[10],tbl[11],tbl[12],tbl[13],tbl[14],tbl[15],tbl[16],tbl[17],tbl[18],tbl[19],tbl[20],tbl[21],tbl[22],tbl[23],tbl[24],tbl[25],tbl[26])
	end
end``

**Comment by joeyjumper94** [comment]
here, if you are that concerned, use this.
[sh__restart_blocker.zip](https://github.com/Facepunch/garrysmod-issues/files/1761685/sh__restart_blocker.zip)
you can also use this if the server has it or allows CSLua

**Comment by besenyei** [comment]
Add volume, and voice_overdrive.

**Comment by robotboy655** [comment]
Added volume and voice_overdrive, as well as _restart on client only, servers can still use it.
