### ISSUE TITLE
utf8.force(str) seems to be broken

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#3375]
### Details
It seems that utf8.force() does not properly replace invalid characters in a non utf8 string. This is especially problematic since users might have names that might either not be utf8 to begin with, or when too long will be cut to an invalid utf8 string by source.
This can cause errors when I try and insert someone's name into the database using utf8 encoding, as the database will refuse any invalid utf8 strings.
I haven't tested it but it might be the case that only trailing invalid characters are not being replaced properly:

### Steps to reproduce
```lua
local str = "❖•Ạ•Ķ•Ạ•Ṣ•❖" -- converted to hex e2 9d 96 e2 80 a2 e1 ba a0 e2 80 a2 c4 b6 e2 80 a2 e1 ba a0 e2 80 a2 e1 b9 a2 e2 80 a2 e2 9d 96
local brokenStr = str:sub(1,31)
print(string.byte(brokenStr, 1, 100)) -- converted to hex e2 9d 96 e2 80 a2 e1 ba a0 e2 80 a2 c4 b6 e2 80 a2 e1 ba a0 e2 80 a2 e1 b9 a2 e2 80 a2 e2 9d
print(string.byte(utf8.force(brokenStr), 1, 100)) -- converted to hex e2 9d 96 e2 80 a2 e1 ba a0 e2 80 a2 c4 b6 e2 80 a2 e1 ba a0 e2 80 a2 e1 b9 a2 e2 80 a2 e2 9d
```
This code gives me this as result, which according to at least utf8, is an invalid utf8 string.
![notepad _2018-01-21_14-08-35](https://user-images.githubusercontent.com/1258762/35194494-a05320ea-feb4-11e7-8a3e-4f16473365c4.png)

As a comparison, this code in scala will return "�", which is ef bf bd, i.e. the unicode replacement character.
```scala
println(new String(Array(0xE2.toByte, 0x9D.toByte), "utf8")) // �
```

**Comment by willox** [comment]
It looks like this happened because UTF-8 decoding did not make sure the string was long enough to contain the expected amount of continuation bytes.

**Comment by FredyH** [comment]
Thanks for that incredibly fast fix, just one thing that can also be improved in the future.
Currently utf8.force (the fixed one) replaces the same string I posted in my initial comment with "❖•Ạ•Ķ•Ạ•Ṣ•��", i.e. it replaces each of the trailing characters with a utf8 replacement character.

I am pretty sure this is not the ideal behaviour though and other utf8 libraries (for example Source's and Java's one) seem to replace both trailing characters with just one replacement character.

**Comment by willox** [comment]
I'm not sure how those libraries are deciding whether a set of bytes should be replaced with 1 or more U+FFFDs. If it's something you want, make a pull request. I'll be sure to look at it.
