### ISSUE TITLE
Built-in AI's TranslateSchedule uses the wrong weapon names.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3376]
### Details
In Garry's Mod the NPCs dont hold the original weapon class like in HL2 such as "weapon_pistol", "weapon_smg1" instead they have "ai_weapon_pistol", "ai_weapon_smg1" .. this leads to some code not working properly, some examples:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_metropolice.cpp#L684
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_metropolice.cpp#L1201
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_metropolice.cpp#L4273
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_metropolice.cpp#L4295
etc.

I think this should be updated to have somewhat better AI using the HL2 combat mechanics.

**Comment by robotboy655** [comment]
Fixed in todays update.
