### ISSUE TITLE
Dropped NPC weapon doesn't carry lua data on replacement.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3377]
### Details
NPCs typically hold ai_weapon_pistol, ai_weapon_smg etc. In Garry's Mod those weapons seem to be replaced once they are dropped. So any data assigned to the built-in weapon will be not copied/moved.

### Steps to reproduce
1. Spawn npc_combine_s with SMG1, should receive ai_weapon_smg1.
2. Assign any variable to the active weapon in OnNPCKilled.
3. Data is lost on dropped object.

NOTE: This is only the case where NPC's have the ai_ prefixed weapons.

**Comment by Kefta** [comment]
This is fixed on the dev branch.
