### ISSUE TITLE
DListView_Column:SetMaxWidth(int) causing crash when int too small

### ISSUE THREAD

**Issue by Ljgoombruh** [Facepunch/garrysmod-issues#3382]
Desc:
When creating a DListView and using the created DListView_Column objects' SetMaxWidth(), if the passed int is too small (as far as I can tell, smaller than the size of the contained text), the entire game crashes.

To reproduce:
-Create a DListView
-Create a new column
-Set the column's width to 8 or less

Version:
2017/12/19

A concommand to reproduce:

```
//CLENT
//Use in console: example_casher [any string] [number]
//When number <= 8 for me, Garry's Mod hangs, and the normal windows "hl2.exe has stopped working" popup is displayed.
concommand.Add("example_crasher", function(ply, cmd, args)
	local CrashMenu = vgui.Create("DListView")
	CrashMenu:SetSize(ScrW()/3+ScrW()/5, ScrH()/2+ScrH()/3)
	CrashMenu:Center()
	local CrashColumn = CrashMenu:AddColumn(args[1])
	CrashColumn:SetMaxWidth(tonumber(args[2]))
end)

```

**Comment by robotboy655** [comment]
Fixed!
https://github.com/Facepunch/garrysmod/commit/32eddb2e0b87cdad454a5e7a1312df6aa3c4e274
