### ISSUE TITLE
gui.OpenURL does not work in Modals

### ISSUE THREAD

**Issue by Kamshak** [Facepunch/garrysmod-issues#3383]
### Details
When you use gui.OpenURL in a modal the popup that  appears (do you really want to visit X) appears under the modal, thus cannot be confirmed or denied.

![Demo](https://thumbs.gfycat.com/HospitableBabyishAmericanbittern-max-14mb.gif)
[See Video](https://gfycat.com/HospitableBabyishAmericanbittern)

### Steps to reproduce
```lua
frame = vgui.Create( "DFrame" )
frame:SetSize(250, 150)

local btn = vgui.Create("DButton", frame)
btn:Dock(TOP)
btn:SetText("Open Link")
function btn:DoClick()
	gui.OpenURL("https://google.com")
end

frame:Center( )
frame:MakePopup()
frame:DoModal()
```

**Comment by mcNuggets1** [comment]
Modal functionaly is broken af, you can also shoot if not clicking at the panel.

**Comment by WilliamVenner** [comment]
DermaMenus don't work either even if you call DoModal() on them

**Comment by robotboy655** [comment]
Should be fixed, by making the confirmation also modal.

**Comment by MattJeanes** [comment]
Is that fix live? It's still marked as a bug on https://wiki.facepunch.com/gmod/gui.OpenURL

**Comment by FlorianLeChat** [comment]
It's still marked as a "bug" until the fix is released to everyone (next update), for the moment it's only available in dev branch (?).
