### ISSUE TITLE
Remove regression caused by recent render/Capture changes

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#3386]
Now that previous frame is always clear, it's nearly impossible to spot usage of any cheats that utilize overlay to display their ESP/wallhack output.

Usage of ESP/wallhack puts players at severe advantage, thus making the game unfair.

And recent changes to render.Capture just made work a lot harder for server owners.

Why cheat detection point was not even considered when you made these changes?

![](https://cdn.discordapp.com/attachments/152162730244177920/407914473492316173/Screen_Shot_2018-01-30_at_15.06.20.png)

It sounds like a joke and mockery, seriously.

Now, even with shittiest cheat that uses DLL injection, you're undetectable.

You left server owners with no other choice but ban people based on their behavior, which is not really reliable method. You can't be confident that you aren't false flagging someone. You can't see what hack they're using.

**Comment by Kefta** [comment]
Not only can cheats just bypass RenderView internally, the concern of privacy is much greater than cheat detection. Only one can make Facepunch liable for legal trouble and result in people losing sensitive information without their knowing. The alternative solution you provided in the original solution is absolutely infeasible and still hurts detection.

**Comment by Noiwex** [comment]
I promised nothing to you, it's just considerations. And yes, you have my utmost disrespect, I absolutely dislike you and hope you have the worst in your life. You mad already? Good.

**Comment by Noiwex** [comment]
This issue is useless. I apologize to code_gs for any personal attacks that may be happened.

**Comment by KittoniuM** [comment]
u r just mad cuz som1 usin bp rdm u in darkrp and steal ur printer noob gtfo stop wastin mr. willox time u edgy teenager

**Comment by Noiwex** [comment]
Shut up cheating cunt.

**Comment by KittoniuM** [comment]
stay mad nerdboy u just mad cuz strong vegan bp users keep rdming u hahahah u r crazy crazy behind the cage
