### ISSUE TITLE
Index Buffering Error

### ISSUE THREAD

**Issue by ltzGummy** [Facepunch/garrysmod-issues#3387]
### Details
hello i was wondering when this Index buffering error is going to get fixed. i run a fairly new gmod server and every now and then players will randomly leave the server in bulk due to this Index Buffering Error, been looking up on the internet and seems to be no solution! people are saying remove the player models, maps etc this is not working! the server was basically a default server and was still getting buffering errors.

to top things off i wipe the whole server and is still existing! wtf is going on. this error is really annoying and was wondering if their is a fix for bloody error cant stand it anymore xD

Kind Regards, Gummy 

### Steps to reproduce
play on a server for a mass amount of time to reproduce this error

**Comment by robotboy655** [comment]
Assuming you mean an Engine Error pop up for clients with the message:
```too many indices for index buffer. tell a programmer (x>32768)```

There is nothing we can do without a way to reproduce the error on demand, or like any information besides "it happens".
The error will not happen on a vanilla server.

The error is related to any renderable mesh in-game, meaning models, decals, map meshes and that type of thing. It may be very common with very high poly models on your server.
