### ISSUE TITLE
Physical Properties STool broken on Chromium branch

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-issues#3392]
### Details
On the Chromium branch of GMod, the Physical Properties tool is throwing out the following error after trying to use it on any prop. This issue does not happen on the regular branch.
```
[ERROR] lua/includes/modules/construct.lua:14: attempt to call global 'IsValid' (a nil value)
  1. SetPhysProp - lua/includes/modules/construct.lua:14
   2. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/physprop.lua:31
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:227
```

**Comment by robotboy655** [comment]
It's due to the fact that Chromium branch is running on an outdated version of the game (somewhere around Nov 2017)

**Comment by robotboy655** [comment]
Fixed
