### ISSUE TITLE
Garry's Mod crashes on startup

### ISSUE THREAD

**Issue by BearIsBoar** [Facepunch/garrysmod-issues#3394]
### Details
I start  up Garry's Mod, it goes black, flashes, black again with only the mouse cursor showing. Gmod crashes my display drivers and I'm unable to play any other games unless I restart my PC. This issue happens with every Source game but not non-Source games. Game cache has been verified; the game's been uninstalled and reinstalled 4 times; I've deleted all addons from Gmod; I checked drivers were up to date (they were).

Crash Log: mdmp file

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_171219_crash_2018_2_17T1_33_11C0.mdmp&key=r6Nl_gDSTQcWb0nmop4iH_jMv5I5By8p2DInrHxgXhq97heFGDKhbNgJurOrxYESDWcN2lf8u-MVgs98bHNCdqDIwTnb0-deHHLY2yRLzOQaHIh4FSQrbtHNm4BLtSquhNSTPjANdv7Q-beW62SbbEwVJH0o-2Ar40vmGdjAn_0=

### Steps to reproduce
Just starting up Garry's Mod crashes the game and display drivers.

**Comment by robotboy655** [comment]
```
-Error Message-
There was an error creating the 'DermaDefaultBold' font!


5(12.901047):  Failed creating fallback font 'Tahoma' for the font 'Tahoma'!
4(12.901024):  Failed creating font 'Tahoma'!
```

It appears you are missing some default Windows fonts which causes the game to not start.

**Comment by BearIsBoar** [comment]
Tahoma is installed. Thank you for replying though. I can hear sounds coming from Garry's Mod's main menu but nothing displays except "Garry's Mod" in the top left corner.

**Comment by robotboy655** [comment]
How can you hear sounds if the game crashes? Can you delete all .mdmp files and attach newest one after the "crash" happens

**Comment by BearIsBoar** [comment]
Well I'm not sure if they game crashes or not, but it defiantly crashes my display drivers. I can hear the menu sounds and the Gmod tab still open but that's where it ends. I can't see the menu and have to restart my PC to fix the crashed display drivers. The mdmp I linked is most recent.

**Comment by robotboy655** [comment]
Since the driver crash issue is not exclusive to GMod, this issue does not belong here. Update/rollback your graphics drivers, don't run the game with -dxlevel 90, etc.

The .mdmp is unrelated at all, and is related to fonts. And since you are unwilling to follow my instructions, there's nothing I can do for you on this either.

If you came here to get help, this is not the place to get help, you can get help at the official GMod forums:
https://forum.facepunch.com/f/gmodhelp
