### ISSUE TITLE
render.OverrideBlendFunc(false) not working?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3396]
The issue is explained here, https://github.com/CapsAdmin/pac3/pull/565

~~I think there's two possibilities.~~

~~render.OverrideBlendFunc misbehaves with the PostDrawTranslucentRenderables hook, or~~ ~~render.OverrideBlendFunc(false) doesn't work.~~

**Comment by thegrb93** [comment]
```>lua_run_cl hook.Add("PostDrawTranslucentRenderables","A",function() render.OverrideBlendFunc(true, BLEND_ONE, BLEND_ONE) render.OverrideBlendFunc(false) end)
```
Lots of weird shit happens

**Comment by CapsAdmin** [comment]
No temporary workaround that limits this or anything? For instance you can only use this for opaque drawables until it's fixed. If not feel free to merge.

**Comment by thegrb93** [comment]
It affects PostDrawOpaqueRenderables too

**Comment by willox** [comment]
Is there another function in GMod that allows the blend operation to be changed? I think this function is missing some params.

**Comment by Kefta** [comment]
render.SetBlend for all render operations and render.OverrideAlphaWriteEnable for the RT alpha

**Comment by willox** [comment]
I'm talking about D3DBLENDOP. Need to add something for this in to render.OverrideBlendFunc I think.

**Comment by thegrb93** [comment]
Yeah, you're right.

**Comment by willox** [comment]
This should be fixed on the dev branch. I've actually added a new function that has all of the required params called render.OverrideBlend (documentation not yet a thing), leaving render.OverrideBlendFunc to be deprecated. Both work properly, though.

Probably won't throw this in to monday's update.
