### ISSUE TITLE
TDM Car crash

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3398]
### Details
I suddenly got a crash from spawning a tdm car, after game rebooted it worked again.

https://www.dropbox.com/s/a3awofvd7ww41ai/hl2_171219_crash_2018_2_22T0_4_37C0.mdmp?dl=0

### Steps to reproduce
???

**Comment by mcNuggets1** [comment]
Crashs with high poly models are still a thing.
Is there going to be a fix?

**Comment by robotboy655** [comment]
Closing as stale. If the issue still happens, please open a new issue with crash dumps and the affected models and reproduction steps, etc.
