### ISSUE TITLE
DarkRP FPS Lag After February 2018 Update

### ISSUE THREAD

**Issue by GorkemF** [Facepunch/garrysmod-issues#3402]
### Details
i update the server and my game with the latest update all the players starts complaining about MASSIVE fps lags that happens every 3-5 seconds (some were saying that it got worse when they had the darkrp swep "keys" in their hand i really dont know the exact reason after the massive drop but just wanted to point it out since other people might have the same issue

PS: the server doesnt have anything thats "too special" just regular gmodstore addons and workshop addons combined

**Comment by goksankadir** [comment]
I'm having this too, CPU usage just absolutely shoots up.

According to somebody on FP it's SQLite

https://gmod.facepunch.com/f/gmoddev/ruwe/Next-Update-v8-February-2018-Update-is-out/1/#unseen

**Comment by sbsalex** [comment]
Its either what is stated above, or clientside reading/writing to and from the clients data folder. Thats what I've narrowed it down to.

**Comment by robotboy655** [comment]
A fix for this has been pushed, you should get it in ~5 minutes, update your servers then.
