### ISSUE TITLE
resource.AddFile ignores resource/ folder including

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#3406]
Hello.
You can view full description here: [Thread on Garry's Mod Forum](https://gmod.facepunch.com/f/gmoddev/obmk/Server-Content-Downloading-and-activating-custom-font-files/1/)

[resource.AddFile](http://wiki.garrysmod.com/page/resource/AddFile) won't add any files from resource/ folder such as fonts.

Also tried as resource.AddSingleFile.
Fonts size are 34 KB and 25 KB.
Downloading them from Workshop will activate them.
Using steamworks.Download -> game.MountGMA will give error:
```
Failed to load custom font file 'c:/program files (x86)/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/digital7mono.ttf'
(Also error happends with other fonts, which exists in same folder)
```

As **code_gs** sad: 
> It's a reported bug - for now, you can only make people manually subscribe or use FastDL.

So, I refresh ticket. Thanks

**Comment by Kefta** [comment]
resource.AddFile works if you have a web server, but it doesn't work if it's downloading from the server (iirc, been a while since I've tested)

**Comment by GitSparTV** [comment]
But it can add files from materials, etc.
They are located in server folder

**Comment by GitSparTV** [comment]
@Kefta 
How do you imagine addding file from web server?

**Comment by Kefta** [comment]
sv_downloadurl

**Comment by GitSparTV** [comment]
Seems like fonts couldn't be imported from sv_downloadurl.
They were packed in bzip's and placed in /resource/fonts/

**Comment by GitSparTV** [comment]
I'm bumping this issue due to my post on forum. @robotboy655 

[Forum Thread](https://forum.facepunch.com/f/gmoddev/obmk/Server-Content-Downloading-and-activating-custom-font-files/1/)


Gmod accepts fonts in resource/fonts/*
- [x] Installing them manually: **Works**
- [x] Downloading a Workshop addon with fonts by subscription (manually): **Works**
- [ ] resource.AddFile(): **`Failed to load custom font file '...\steam\steamapps\common\garrysmod\garrysmod\download\resource\fonts\....ttf'`**
- [ ] MountGMA: **Doesn't work**
- [ ] FastDL (sv_downloadurl): **Access denied to whole resource folder**

**Comment by mcNuggets1** [comment]
FastDL using sv_downloadurl works for me.

**Comment by GitSparTV** [comment]
@mcNuggets1 > FastDL using sv_downloadurl works for me.

Did it download font when your font is deleted from resource/fonts/ and cache/download folder is cleaned?

**Comment by GitSparTV** [comment]
Ok, speaking about font issue.
For version 190430 (client) and 190428 (server).
1. Fonts **will** be downloaded if the font has resource.AddFile. (Not tested with sv_downloadurl downloading)
2. Fonts **will not** be installed if some addon has this font. The error message appears: `Failed to load custom font file `*path to steam*/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/*font name*`
3. Font **will not** be downloaded even if server has resource.AddFile because addon said he has that font, but it errors.

**Comment by GitSparTV** [comment]
@robotboy655. As I described above, only one method works, but this method it pointless in terms of the Workshop. That's the only folder where you can put fonts.

**Comment by GitSparTV** [comment]
Any update?

**Comment by robotboy655** [comment]
I am getting mixed signals here. First you say it doesn't work, then you say it does work. You do not provide example addons that have the problems.

I have a few fonts in my `download/resource/fonts` folder, all of them load except for one which cannot be loaded by Windows Font Viewer either. (i.e. its a corrupted file)

**Comment by GitSparTV** [comment]
Ok, i will make a test addon

**Comment by robotboy655** [comment]
Ok, I reproduced the error and as far as I can tell, the error message does nothing, the fonts are just attempted to be loaded twice and should still work. I will look into getting that false error message to not appear.

Anything else that needs solving?

**Comment by GitSparTV** [comment]
Well, for me (and for all players who told me) they don't work. I will ping you when I re-do the test

**Comment by adamnejm** [comment]
Same thing here, hosting my resources with FastDL / Workshop.
Materials have downloaded fine, but I had no luck with fonts.
I've tried:
Tried `bz2` compression;
`AddFile` and `AddSingleFile`, executed from `garrysmod/addons/test/lua/autorun` and from `garrysmod/lua/autorun`;
~10 different fonts (all `.ttf`);
Workshop Collection;
`AddWorkshop`;
Not using the `resource` lib;
lowercase, camelCase, UPPERCASE, Matching Case;
and things I've honestly don't remember anymore because I've spent 8 hours trying to get a fucking font to load.

**Comment by adamnejm** [comment]
Setup:
1. Lanuch command: `srcds_run -game garrysmod -console -port 27015 +ip ***.***.***.*** -strictportbind -norestart +maxplayers 16 +gamemode sandbox +map gm_flatgrass`
2. Font not installed in the system.
3. Files `img_test.png` and `bignoodletoo.ttf` not in the `garrysmod/download` folder (locally).
4. Folder `download/resource/fonts` exists (locally).
5. FastDL hosted on separate server (forced https), containing:
```
materials/test_img.png (2kb; no transparency)
resource/fonts/bignoodletoo.ttf (84kb)
```
6. `sv_downloadurl` with following structure `https://facepunch.com/folder/subfolder/fastdl/`
7. `sv_allowdownload` and `sv_allowupload` both set to `1`
8. `cl_downloadfilter` set to `all`
9. GitHub addons temporarily moved to `garrysmod/addons/noaddons`



**TESTING 1. - Non-addon structure**
------------------------------------------------------------
Following tests are done with:
1. Loader file on server in `garrysmod/lua/autorun/res_loader.lua` (read res_loader.lua contents at the bottom)
2. File `bignoodletoo.ttf` in `garrysmod/resource/fonts/bignoodletoo.ttf`
3. File `img_test.png` in `garrysmod/materials/img_test.png`

**Server logs**
---------------
Server log: https://pastebin.com/raw/yD0hytDp

**Joining server on default Garry's Mod branch (opted out of any betas) - WINDOWS 10**
---------------
Client log: https://pastebin.com/raw/YHuJawDh
Result:
- File `img_test.png` downloaded to: `garrysmod/download/materials`
- File `bignoodletoo.ttf` downloaded to: `garrysmod/download/resource/fonts`

**Joining server on Garry's Mod branch: `x86-64 - Chromium + 64-bit binaries` - WINDOWS 10**
---------------
Client log: https://pastebin.com/raw/9REKfFAX
Result:
- File `bignoodletoo.ttf` downloaded to: `garrysmod/download/resource/fonts`
- File `img_test.png` downloaded to: `garrysmod/download/materials`

**Joining server on default Garry's Mod branch (opted out of any betas) - LINUX**
---------------
Client log: https://i.imgur.com/OjfuRlM.png (only this avaiable, sorry)
Result: 
- No files downloaded

**Joining server on Garry's Mod branch: `x86-64 - Chromium + 64-bit binaries` - LINUX**
---------------
Client log: https://pastebin.com/raw/C2vzBTf7
Result:
- File `img_test.png` downloaded to: `garrysmod/download/materials`



**TESTING 2. - Addon**
------------------------------------------------------------
Following tests are done with:
1. Loader file on server in `garrysmod/addons/test/lua/autorun/res_loader.lua` (read res_loader.lua contents at the bottom)
2. File `bignoodletoo.ttf` in `garrysmod/addons/test/resource/fonts/bignoodletoo.ttf`
3. File `img_test.png` in `garrysmod/addons/test/materials/img_test.png`

**Server logs**
---------------
Server log: https://pastebin.com/4is5k4AQ

**Joining server on default Garry's Mod branch (opted out of any betas) - WINDOWS 10**
---------------
Client log: https://pastebin.com/raw/LVCrKRDF
Result:
- File `img_test.png` downloaded to: `garrysmod/download/materials`

**Joining server on Garry's Mod branch: `x86-64 - Chromium + 64-bit binaries` - WINDOWS 10**
---------------
Client log: https://pastebin.com/raw/5rcTnGBS
Result:
- File `img_test.png` downloaded to: `garrysmod/download/materials`

**Joining server on default Garry's Mod branch (opted out of any betas) - LINUX**
---------------
Client log: https://i.imgur.com/RkX4sWY.png (only this avaiable)
Result:
- No files downloaded

**Joining server on Garry's Mod branch: `x86-64 - Chromium + 64-bit binaries` - LINUX**
---------------
Client log: https://pastebin.com/raw/VGhF76Qx
Result:
- File `img_test.png` downloaded to: `garrysmod/download/materials`



**Contents of res_loader.lua**
```lua
print("Resource Loader (res_loader.lua) has executed", SERVER)
if SERVER then
    resource.AddSingleFile("resource/fonts/bignoodletoo.ttf")
    resource.AddSingleFile("materials/test_img.png")
end
```

**Comment by robotboy655** [comment]
I couldn't reproduce fonts not downloading from addons, on windows 10

You can use `developer 1` on your server to see if a file was added into the download list at all. The font MUST exist on the server for it to be added to the downloads list, in root or in addon does not matter.

![](https://files.facepunch.com/rubat/1b0911b1/2020-01-09_19-06-18.png)
