### ISSUE TITLE
Scrolling broken on Mac OS still.

### ISSUE THREAD

**Issue by rudeustudeus** [Facepunch/garrysmod-issues#3408]
### Details
Scrolling on mac in gmod is extremely unpredictable. You can scroll through the entire server list or spawn menu without so much as blowing on your scroll wheel. Props are extremely finicky, they go every which way and sometimes will not move at all when trying to scroll them seemingly ignoring physgun_wheelspeed.

That is just the tip of the iceberg of how broken the osx client is but that is one thing that absolutely needs fixing for this to be playable.

### Steps to reproduce
Join a server. The problem occurs more frequently outside of a controlled environment.
Attempt to scroll through any derma panel.
Attempt to (extensively) scroll a prop. Be sure to drop it and spawn a new prop to see varied effects.

Here is an example of what my scroll delta looks like on windows.
(scrolling forward)
1
1
1
1
1
1
(scrolling backwards)
-1
-1
-1
-1
-1
-1

On osx, it is anything but that. Almost completely random. Something like this when scrolling forward.
1 
0
-34 
62
85
-12

This has been tested on a 2008 macbook pro, a 2012-ish imac and a mac mini as well as a hackintoshed pc. I have tried a regular mouse as well as apple's magic mouse and the effects are largely the same.

I should also say this has been a problem since the RELEASE of gmod on mac. I am sorry but that is unacceptable.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3353
