### ISSUE TITLE
util.JSONToTable returns talbe with invalid json.

### ISSUE THREAD

**Issue by mtuska** [Facepunch/garrysmod-issues#3410]
### Details
Providing a numeric or random string value into util.JSONToTable provides a table. Should be returning nil for malformed/invalid JSON.

### Steps to reproduce
lua_run print(util.JSONToTable(14525)) -- Provides table
lua_run print(util.JSONToTable(true)) -- Error
lua_run print(util.JSONToTable("true")) -- Provides table
lua_run print(util.JSONToTable("waffle")) -- Provides nil
lua_run print(util.JSONToTable("{}")) -- Provides the only expected table

**Comment by willox** [comment]
This will be fixed in the dev branch shortly - it'll only accept tables or arrays as the root element.
