### ISSUE TITLE
Calling net.Broadcast too early when loading source engine saves clangs gmod

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3412]
Tracebacks using debug.sethook
![screenshot](https://i.dbot.serealia.ca/2018/03/hl2_2018-03-06_15-58-33.png)
Preventing addons from calling net.Broadcast while loading save resolve the issue.

After that happened, player is unable to close game in any way (excluding killing in task manager). Even clicking on close button is not working.

**Comment by robotboy655** [comment]
Cannot reproduce with the following code:
```
if SERVER then
	util.AddNetworkString( "test" )
	net.Start("test")
	net.Broadcast()
else

	net.Receive("test", function()
		print("Daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	end )
end```
I tried loading a level, going through changelevel and ```load autosave```

**Comment by roboderpy** [comment]
You must call Broadcast() inside EntityRemoved hook on each event

**Comment by meepen** [comment]
Why do you need it to error

**Comment by robotboy655** [comment]
It's a silent error (i.e. it won't stop code), I can replace it with a (dev)message or nothing at all, I just thought it may be useful for developers to know when the message doesn't go through and why.
