### ISSUE TITLE
Entity:IsRagdoll() returns false when used in EntityRemoved

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-issues#3414]
### Details
As the title says, [Entity:IsRagdoll()](http://wiki.garrysmod.com/page/Entity/IsRagdoll) always returns false for ragdolls in the [EntityRemoved](http://wiki.garrysmod.com/page/GM/EntityRemoved) hook.

### Steps to reproduce
1. Run this code:
```lua
local function isRagdollFix(ent)
	return ent:GetClass() == "prop_ragdoll"
end

hook.Add("EntityRemoved", "IsRagdollTest", function(ent)
	if isRagdollFix(ent) ~= ent:IsRagdoll() then
		print(ent, ent:IsRagdoll())
	end
end)
```
2. Spawn any ragdoll and remove it.

**Comment by robotboy655** [comment]
fixed
