### ISSUE TITLE
SLAM doesn't have limited ammo

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-issues#3418]
### Details
The SLAM can be used infinitely, without ever running out of ammo. I don't think this is intentional!

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Give yourself SLAMs and then equip them; if you see any numbers in the lower-right then I might be mistaken. If you don't see any numbers, then it's clear.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/37275942-2ea202de-25e9-11e8-88a0-67587ca934f9.png)

It's definitely limited.

**Comment by BreakinBenny** [comment]
Then the problem might be from me playing with a person who has the SLAM's ammo limit reach the ceiling…

What about when the SLAM ammo exceeds 10 or so? Is it possible to prevent players from equipping them and grenades if either has no ammo left, @robotboy655?
