### ISSUE TITLE
Thirdperson seating low in Muscle Car

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-issues#3419]
### Details
In my experience, the view from the EP2 muscle car in firstperson is completely unobstructed (so that's fine). HOWEVER, in third person view you can see that the driver is seated lower than they actually should be. I'm confident this was a problem even before Garry's Mod 13, but it's kinda amazing it has persisted after all these years when the firstperson camera was fixed.

I believe Synergy doesn't have this problem, but it's been so long since I played that and I might be wrong

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Spawn the default HL2 EP2 Jeep (Jalopy, as it's incorrectly referred to by its script file and entity name), then enter it, and turn on the thirdperson camera… or observe another player as the driver.

### Other notes
Is prop_vehicle_jalopy a valid entity in Garry's Mod?

**Comment by robotboy655** [comment]
This is due to the Jalopy model itself, not much we can do about it because it comes with HL2: EP2 and we do not have source files for models of that game,

**Comment by BreakinBenny** [comment]
If such is the case, then I'd like to know how Synergy managed to take care of that issue. If the team behind it didn't modify the Muscle Car model at all (but didn't reuse prop_vehicle_jalopy), then they must've somehow managed to add an offset for the driver attachment.

**Comment by BreakinBenny** [comment]
It seems the Muscle Car uses an episodic version of the HL2 Jeep, or at least programming for the Episodic content… but…

https://github.com/ValveSoftware/source-sdk-2013/tree/master/sp/src/game/server/episodic

**Comment by BreakinBenny** [comment]
Here's a follow-up after I spoke on Synergy's Discord channel: 
![discordchat](https://user-images.githubusercontent.com/4566768/41195484-616a37dc-6c2e-11e8-8eb8-b7e7275f1f33.png)

Balimbanana lists these outputs:
OnCompanionEnteredVehicle
OnCompanionExitedVehicle
PlayerOn
PlayerOff

**Comment by neico** [comment]
the model might be unavailable, but the source code behind it's entity is available, and that's where the attachment offset is calculated, Obsidian Conflict opted to keep the codebase of both Jeep and Jalopy codebase separate (prop_vehicle_jeep & prop_vehicle_jeep_episodic), contrary to Synergy (which also modified quite a handful of vehicle models to add additional attachment offsets for passengers, so I wouldn't be surprised if they also did that to the Jalopy) which uses the same entity for both vehicles.

In essence you need to add the following function to `game/client/c_prop_vehicle.cpp`:
```cpp
bool C_PropVehicleDriveable::GetPassengerRenderOffset( Vector &vecOffset, int &iAttachment, int nRole )
{
	int iPassengerAttachment = LookupAttachment( "vehicle_feet_passenger0" );
	if( iPassengerAttachment < 1 ) return false;

	iAttachment = iPassengerAttachment ;
	vecOffset.Init();
	return true;
}
```
and add that to the deviants as well with vecOffset.Init() having the following params:
prop_vehicle_choreo_generic: `0.0f, 0.0f, -30.0f`
prop_vehicle_crane: `3.0f, -30.0f, 17.0f`
Jeep: `0.5f, 0.5f, 0.0f`
Jalopy: `0.0f, 0.-4.5f, 8.0f`
Airboat: `1.0f, -4.5f, -5.5f`

**Comment by robotboy655** [comment]
I patched the models (Jalopy and Crane) with a hex editor.,
