### ISSUE TITLE
Crashing on Mac OS X

### ISSUE THREAD

**Issue by ARandomFriz** [Facepunch/garrysmod-issues#3421]
Details:
 Almost whenever the player dies, or a npc combine is hit or dies the game instantly crashes(this tends to always crash the game). This happens when no add-ons are being used. Even re-downloading the game doesn't fix the problem.
From what I've observed from other Mac users this appears to be a direct result of the February 2018 update which came out 2/26/18

Crash Report:
[Gmod Crash Report.txt](https://github.com/Facepunch/garrysmod-issues/files/1805481/Gmod.Crash.Report.txt)

Steps to reproduce:
To reproduce this simply play on any MacBook or iMac, and do one of two things.
1. Have you're in game avatar die (This sometimes takes a few tries but does crash the game) 
2. Attack or kill a NPC (This crashes the game instantly)

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3404#issuecomment-372559425
