### ISSUE TITLE
Get/SetGlobal* functions un-setting

### ISSUE THREAD

**Issue by cannon** [Facepunch/garrysmod-issues#3422]
### Details
**Since the latest game update**, I've had issues with functions like SetGlobalBool and SetGlobalEntity. The issue is that the value will randomly un-set itself (so GetGlobal* returns the default), both on the client and the server. I've experienced this on different servers, different setups.

### Steps to reproduce
Have server with activity going on. Get issue randomly.

**Comment by mcNuggets1** [comment]
This issue is extremely old.

**Comment by thegrb93** [comment]
Same goes for Entity.SetNW*

**Comment by Dimantio** [comment]
Having this issue as well, pretty disappointing.

**Comment by robotboy655** [comment]
This was fixed in Dev version of the game and in the next update.
