### ISSUE TITLE
Entity/SWEP ScriptedEntityType non-existent in list.Get

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-issues#3423]
### Details
The ScriptedEntityType is not properly added to the entity/weapon list, thus making custom `spawnmenu.AddContentType` not work, unless the list is manualy edited with a workaround
The code is there, `list.Get` just does not store the information, thus defaulting to default type.
### Steps to reproduce
Set SWEP.ScriptedEntityType to a custom one, create a new AddContentType, and watch how nothing happens :(

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/b6c040fb48076efa96d4533da5c957b028b11b20
