### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by Ep1cM1n10n** [Facepunch/garrysmod-issues#3425]
### Details
Well, my game will crash on startup EVERY time i try to play, ive reinstalled both  the game, AND Steam, but it makes no difference, ive uninstalled all addons and tried every fix but nothing.
Here is a link to the MDMP file
https://www.dropbox.com/s/ydze1uaifpqzows/hl2_180315_crash_2018_3_27T2_22_59C0.mdmp?dl=0

### Steps to reproduce
I launch my game. There is nothing else.

I found this is the issue
EXCEPTION_ACCESS_VIOLATION

**Comment by robotboy655** [comment]
Try switching your game to the Dev branch on Steam and see if that fixes the problem.

http://wiki.garrysmod.com/page/Dev_Branch

**Comment by Ep1cM1n10n** [comment]
I forgot to say i already have.

**Comment by robotboy655** [comment]
It was just updated, try again and see if its fixed. If its not, attach new crash logs

**Comment by Ep1cM1n10n** [comment]
Thank you! This fixed it!
