### ISSUE TITLE
cl_show* "bugs"

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#3426]
### Details
![Screenshot](https://i.imgur.com/Ypuxbyf.png)

There are various `cl_show*` variables which enable rendering of FPS/pos/etc.

Consider: Move the `cl_showfps`, `cl_showpos`, and `cl_showbattery` 30 pixels down the Y-axis (when escape menu is visible). (Like @robotboy655 has done [here](https://github.com/Facepunch/garrysmod-issues/issues/3059).)

### Steps to reproduce
There are (engine) *bugs* with a couple of them:
- When `cl_showfps` is set to `2`, then a "FPS label" being rendered is not positioned correctly along the X-axis (see the very first line of text in the screenshot above). It should be positioned at `(ScrW() - m_iFpsLabelWidth) - offsetX`.
- `cl_showbattery` is only rendered if either `cl_showpos` or `cl_showfps` is enabled (`> 0`).
- When `cl_showpos` and `cl_showbattery` are both enabled (set to `1`), a battery label is being rendered above/after the velocity (3rd line of cl_showpos text).

**Comment by robotboy655** [comment]
Fixed what was reasonable. 

![image](https://user-images.githubusercontent.com/3299036/116541518-37684900-a8f4-11eb-9d55-7d38b3a4ad80.png)

I don't see this being terribly useful while in main menu, you might as well just use `getpos` concommand to get an easily copy-able position and angles.
