### ISSUE TITLE
Chromium boot crash on Linux

### ISSUE THREAD

**Issue by linkjay** [Facepunch/garrysmod-issues#3427]
### Details
Using the latest Arch Linux and Linux kernel.

uname -a:
`Linux computer 4.15.11-1-ARCH #1 SMP PREEMPT Mon Mar 19 18:21:03 UTC 2018 x86_64 GNU/Linux`

Using the Chromium beta branch on Steam, Garry's mod will crash on the very first blue loading screen. The window is made and get's to the loading part, but never gets to the Facepunch logo. [This thing](https://i.linkjay.io/bmcAlv.png).

Could it possibly have to do with the "No usable sandbox!" error? I ran it with --no-sandbox and that didn't seem to help.

Running hl2.sh manually logs: https://pastebin.com/rq79xHnP

GIF of it actually happening (same effect when ran from Steam, just did it from terminal to show logs at the same time as game): https://i.linkjay.io/nxTIiK.gif

### Steps to reproduce

1. Start game with Steam or hl2.sh on the Chromium branch (on linux (maybe Arch-only?))
2. Wait
3. Game crashes

**Comment by willox** [comment]
With arch's build of the kernel you'd need to manually setup chrome's suid sandbox. There's no instructions on how to do that with gmod yet.
