### ISSUE TITLE
weapon_medkit isn't lag compensated

### ISSUE THREAD

**Issue by end360** [Facepunch/garrysmod-issues#3431]
### Details
The weapon_medkit PrimaryFire uses TraceLine but doesn't set lag compensation on the player.

### Steps to reproduce
1. Get a medkit
2. Be laggy
3. Look at code

**Comment by end360** [comment]
Fix proposed in https://github.com/Facepunch/garrysmod/pull/1481

**Comment by Kefta** [comment]
Fix was merged
