### ISSUE TITLE
util.isValidModel returns false for valid models

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-issues#3432]
Yesterday I've been trying to make a use out of util.isValidModel but it returned false for some valid models paths that were even precached ("models/weapons/w_toolgun.mdl", for example).

I could spawn and render a ClientsideModel with these models on the next line of code without any errors, so there's something really weird going on.

Have anyone else had this issue? Thanks.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2287

**Comment by SamuelMoriarty** [comment]
Can confirm some strange behaviour:

Assuming an existing, valid model:
1. IsValidModel returns true on Client if the model has been precached on the Server.
2. IsValidModel returns false on Client if the model hasn't been precached on the Server. 
3. Calling PrecacheModel on Client doesn't seem to make any difference.
4. IsValidModel returns true on Server regardless of caching status.

**Comment by Tripperful** [comment]
@SamuelMoriarty this might be the case.

Though I can't say this is expected behavior and therefore it should be either fixed to function as expected or be documented properly.

**Comment by robotboy655** [comment]
A model is invalid if:
* The path starts with a space ( )
* The path is less than 4 characters
* The path starts with maps/
* The path doesn't start with models
* The path contains any of the following
  * _gestures, _animations, _postures, _gst, _pst, _shd, _anm, _ss, .bsp, cs_fix
* On the server: If the model isn't precached AND the path doesn't exist in the filesystem
* Precaching via CBaseEntity::PrecacheModel failed
* Model type isn't mod_studio
* model is the error model

**Comment by Tripperful** [comment]
I will try to make a code sample that illustrates the issue consistently so that it's easier to track what's going on. I'm still wondering since the models I've been testing yesterday satisfied the above criteria.

**Comment by thegrb93** [comment]
If you look at the issue I linked, it happened to me before too but as a rare bug. When it happened, props could no longer be spawned from the spawn menu due to util.isValidModel returning false. I don't think I tested what happens if you try creating the prop anyway, but I bet it probably would've crashed or something.

**Comment by robotboy655** [comment]
Maybe your server is hitting the precache limit or something?

**Comment by thegrb93** [comment]
Yeah possibly

**Comment by Tripperful** [comment]
Yeah, @SamuelMoriarty is right. It returns false clientside if the model is not precached on the server.

```Lua
local model = "models/roller.mdl"

concommand.Add( "modeltest", function()
	print( model, "valid: " .. tostring( util.IsValidModel( model ) ) )
	util.PrecacheModel( model )
	print( "precached" )
	local csmodel = ClientsideModel( model )
	print( "cs model: " ..  tostring( csmodel ) )
	csmodel:Remove()
	print( model, "valid: " .. tostring( util.IsValidModel( model ) ) )
end )
```
output:
```
models/roller.mdl	valid: false
precached
cs model: CSEntity [class C_BaseFlex]
models/roller.mdl	valid: false
```
after I run ```util.PrecacheModel( "models/roller.mdl" )``` on the server:
```
models/roller.mdl	valid: true
precached
cs model: CSEntity [class C_BaseFlex]
models/roller.mdl	valid: true
```
So the model is considered invalid clientside if it was not precached by the server, which is a bit unexpected for me, even though I am able to draw this model clientside or whatever, just like it happens when spawnicons are rendered.

Seems like the only way around wound be using file.Exists.

I will update the wiki page to make it clear that this function returns false for models that are not precached by the server.

**Comment by robotboy655** [comment]
Looked briefly into this, and yes, clientside model precaching doesn't do anything, all functions affected.

**Comment by robotboy655** [comment]
have you actually tested if this is fixed or you just dont care about this particular issue?
