### ISSUE TITLE
Random Client Side Crashes

### ISSUE THREAD

**Issue by Damien0053** [Facepunch/garrysmod-issues#3435]
Not sure what causes the crashes but who it affects varies. 

https://cdn.discordapp.com/attachments/337122751578112000/433673439383912470/hl2_180315_crash_2018_4_11T17_0_33C0.mdmp

**Comment by robotboy655** [comment]
Happens when shooting ragdolls from the effects because the ragdoll doesn't have physics objects or they are somehow fucked. Perhaps you have a shitty addon or a ragdoll model?

**Comment by Damien0053** [comment]
Oh I see, Sorry for late reply, it seems we have fixed it now that we know what we are looking for. Appreciate the help.
