### ISSUE TITLE
file.Find/IFileSystem has undefined behaviour when paths have three+ slashes

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3437]
For "models", it seems to cause all files and subdirectories to be listed regardless of subdirectory:
![](https://i.imgur.com/trNdt2g.png)

Not sure what it is doing for "materials", but it lists more files for some reason:
![](https://i.imgur.com/AX1IQQS.png)

This also applies for backslashes, and two blackslashes seems to also have an effect on the number of subdirectories:
![](https://i.imgur.com/jUrl1a9.png)

**Comment by NeatNit** [comment]
What is the expected behavior when there's 2+ consecutive slashes?

This may be the result of code similar to https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/commands.lua#L13-L17:
``` Lua
-- Clean up the path from attempted blacklist bypasses
arguments[ 1 ] = arguments[ 1 ]:gsub( "\\\\+", "/" )
arguments[ 1 ] = arguments[ 1 ]:gsub( "//+", "/" )
arguments[ 1 ] = arguments[ 1 ]:gsub( "\\/+", "/" )
arguments[ 1 ] = arguments[ 1 ]:gsub( "/\\+", "/" )
```

**Comment by robotboy655** [comment]
Automatically removes double or more consecutive slashes now.
