### ISSUE TITLE
linux multicore rendering

### ISSUE THREAD

**Issue by mrweegeeman** [Facepunch/garrysmod-issues#3442]
stop letting personal grudges prevent you from helping hundreds of players
https://github.com/Facepunch/garrysmod-issues/issues/3366
https://github.com/Facepunch/garrysmod-issues/issues/3439
https://github.com/Facepunch/garrysmod-issues/issues/3440
https://github.com/Facepunch/garrysmod-issues/issues/3441

also could you maybe make it go back to crashing people so that someone can at least try to patch it themselves
^ That seems like the least you can do :)

actually the least you could do is use words like a big boy and communicate rather than blocking me or ignoring emails and closing every thread and locking github tickets

**Comment by sannysc** [comment]
Anyone who tries to play video games on an OS that isn't Windows deserves to have their game crash.

**Comment by robotboy655** [comment]
Closing as per this reply:
https://github.com/Facepunch/garrysmod-issues/issues/3366#issuecomment-382666982

**Comment by Kefta** [comment]
You should at least leave one of these issues open to show the issue is present for any new users - just label as wontfix.

**Comment by robotboy655** [comment]
But you may wanna try the Dev branch in an hour or smth

**Comment by robotboy655** [comment]
Good point @Kefta

**Comment by mrweegeeman** [comment]
Well color me impressed

**# THANKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**
