### ISSUE TITLE
SetHull and SetHullDucked Z Vector causing issues

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#3445]
When changing the players hull via SetHull or SetHullDuck and changing the Z Vector portion of the players hull, even when networked causes what i can only describe as laggy/hitchy movement.

Simply change the hull per say PL:SetHull( Vector(-16,-16,0), Vector(16,16,65) ) in the console, even with lua_run_cl.

**Comment by ZehMatt** [comment]
Have you tried cl_showerror 2?

**Comment by MagentaIris** [comment]
Ofcourse, But this isn't something you can fix manually unless i'm missing some magical function that was lost to the tides of time back in 2007, Sorry.

001 CCollisionProperty::m_vecMaxsPreScaled - vec[] differs (1st diff) (net 16.000000 16.000000 61.000000 - pred 16.000000 16.000000 72.000000) delta(0.000000 0.000000 11.000000)
002 CCollisionProperty::m_vecMaxs - vec[] differs (1st diff) (net 16.000000 16.000000 61.000000 - pred 16.000000 16.000000 72.000000) delta(0.000000 0.000000 11.000000)

**Comment by robotboy655** [comment]
Should be fixed in Dev.
