### ISSUE TITLE
Spawning any Half-Life Source headcrab breaks schedules on HL2 headcrabs, or vice versa

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-issues#3446]
After spawning either HL1 headcrab NPC (monster_headcrab or monster_babycrab), any HL2 headcrabs will be unable to attack enemies until the map is reloaded. Alternatively, spawning any HL2 headcrab first causes the same error on HL1 headcrabs, making _them_ unable to attack. Whichever set of NPCs is spawned first will work normally, and whichever is spawned second will break.

Console spew related to this bug can be seen with developer mode turned on (i.e. **developer 100** in console):
- When the bug first occurs, spawning a headcrab from the second group for the first time (i.e. if you've already spawned an HL1 headcrab, this message occurs the first time you spawn an HL2 headcrab):
	**ERROR: file contains a schedule (SCHED_HEADCRAB_RANGE_ATTACK1) that has already been defined!
	       Aborting schedule load.**

- When any broken headcrab other than fast tries to attack:
	**Couldn't find schedule (SCHED_HEADCRAB_RANGE_ATTACK1)
	GetScheduleOfType(): No CASE for Schedule Type 88!**

- When a broken fast headcrab tries to attack:
	**Couldn't find schedule (SCHED_FAST_HEADCRAB_RANGE_ATTACK1)
	GetScheduleOfType(): No CASE for Schedule Type 106!**

- When a broken HL1 normal headcrab notices an enemy:
	**Couldn't find schedule (SCHED_HEADCRAB_WAKE_ANGRY_NO_DISPLAY)
	GetScheduleOfType(): No CASE for Schedule Type 90!**

- When a broken poison headcrab notices an enemy:
	**Couldn't find schedule (SCHED_HEADCRAB_WAKE_ANGRY)
	GetScheduleOfType(): No CASE for Schedule Type 89!**

- When a broken poison headcrab is thrown by a poison zombie:
	**Couldn't find schedule (SCHED_HEADCRAB_FALL_TO_GROUND)
	GetScheduleOfType(): No CASE for Schedule Type 98!**

**Comment by robotboy655** [comment]
Fixed.
