### ISSUE TITLE
Random Crashes on Arch Linux

### ISSUE THREAD

**Issue by MSTVIRUS** [Facepunch/garrysmod-issues#3448]
### Details
Specs:
Processor: AMD Ryzen 7 1700
Mobo: MSI Gaming Pro Carbon X370
Graphics Card: Nvidia Geforce GTX 1060
Ram: 16Gb
Hard Drive: 2Tb
OS: Arch Linux with Openbox Window Manager

I've encountered two types of crashs but the "Lua Panic! Something went horribly wrong! 'not enough memory'" is the most encountered one. I simply don't know how to fix the Lua Panic Error and it seems to occur at random. The other crash is random too. Sometimes it occurs 5 minutes after game startup and other times it doesn't ever occur.

### Steps to reproduce
I don't know how to reproduce either as they're both random and I don't get crashlogs either.

**Comment by daunknownman2010** [comment]
Since you're running Arch, you should also include the fact whether you're running Steam Runtime or natively. Also ensure the file system you're using is not using 64-bit inodes (it's the default on XFS and Ext4). Just a question, is there any addons you're running as well?

**Comment by MSTVIRUS** [comment]
Well I should also include that I'm new too Arch and Linux in general but I know that I'm running Steam Native. I'm bit sure what inodes are but I know that 32bit support has been enabled to install Steam. I also have lots of addons.

**Comment by daunknownman2010** [comment]
Inodes are used for data structures in Unix systems. Without getting too in-depth about them though, basically some 32-bit software have issues running on 64-bit inode file systems including the Source Engine. I know that Ext4 and XFS default to using 64-bit inodes which can cause problems for a good chunk of 32-bit software not compiled for it, so if you use one of those two you're likely running on 64-bit inodes.

As for the addons, have you tried disabling them all and running the game as clean as possible? It could be possible that the addons are causing the crashes as well. I've tried to make the game get the random crashes you're experiencing on my Arch installation but I've had no luck.

**Comment by MSTVIRUS** [comment]
I have and it works but the server I play on has quite a few oof them and I don't want errors all over my screen and yeah I'm using Ext4

**Comment by daunknownman2010** [comment]
So by the sounds of it, it's more the server's fault for including various addons that is causing your game to crash then, so I guess you're able to throw out the file system idea now. Anyway, if you want to get core dumps on Arch Linux, have a look into _coredumpctl_ on the Arch Wiki if you have it enabled: [https://wiki.archlinux.org/index.php/Core_dump](url)

**Comment by MSTVIRUS** [comment]
Alright I'll generate a coredump but it seems that restarting my computer also helps

**Comment by MSTVIRUS** [comment]
Damg. I really like Linux mostly becuase of the godlike framerate increase but I might have to switch back to Windows 10 if I can't find a fix.

**Comment by daunknownman2010** [comment]
Well, sometimes it might be worth doing a fresh re-install of Arch and seeing if it works then. I've had many moments with Arch where something doesn't work one time and then works right after a re-install. If you do want to re-install Arch and see if that works, make sure to do _mkfs.ext4 -O \^64bit /dev/sd**_ to force Ext4 to use 32-bit inodes for better compatibility.

**Word of advice: most games on Steam are built only to work with Ubuntu and its configurations, be warned that using Arch Linux means you'll have to do stuff on your own most of the time.**

**Comment by MSTVIRUS** [comment]
Thanks. I'm gonna close this now
