### ISSUE TITLE
Strange Console Print: "Error - no MetaName string type for userdata (AGH!)"

### ISSUE THREAD

**Issue by Kamshak** [Facepunch/garrysmod-issues#3452]
### Details

Another help request - I'm seeing a lot of console prints with the message "Error - no MetaName string type for userdata (AGH!)". A search in files for the string does not result in anything so i'm suspecting gmod itself is somehow printing this.

Could any of the devs run a quick search through the code and comment what could be the cause of this? It's printed when I create and use MySQLOO query objects (which are userdata i think?). 

Much appreciated! 

### Steps to reproduce

Reproduction isn't clear, unfortunately. I believe that it is related to creating queries through the mysqlOO module.

**Comment by Kefta** [comment]
I believe this error occurs when you try to retrieve the type of a userdata object whose metatable has no MetaName key. This happens with mysqloo since the query and database objects do not have these.

**Comment by Kamshak** [comment]
That would be amazing @Kefta! Would help out a lot of people who are getting their consoles spammed and I can't really tell them anything other that I have no idea how to fix this :smile: :see_no_evil:

**Comment by willox** [comment]
It already returns "UserData". I don't see any reason to keep this error print around though so I'll remove it.
