### ISSUE TITLE
Weird Half-Life Source entity replacements

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3453]
Was playing on HLS maps and noticed some incorrect entities spawning from breakable boxes. Here's a list of those weird replacements:

ammo_9mmar = item_ammo_smg1_large
ammo_357 = item_smg1_grenade
ammo_argrenades = item_ammo_ar2
ammo_buckshot = item_box_buckshot
ammo_crossbow = item_box_flare_rounds
ammo_gaussclip = weapon_stunstick
weapon_crossbow = item_flare_round
weapon_glock = item_ammo_pistol
weapon_handgrenade = weapon_ar1
weapon_tripmine = weapon_ar2

List may be uncompleted. So why is this made? Some entities can't be replaced through lua, mostly it says in console something like "unable to spawn unknown entity type unused (*ent_class*)"

**Comment by robotboy655** [comment]
Can it be that Half-Life Source entities don't exist in GMod for the most part with some exceptions?

**Comment by TheMostUpset** [comment]
They don't exist, but can be recreated in Lua. And those replacements (probably hardcoded) make that impossible in most cases.
Some entities (like weapon_ar1) don't even exist in the game, but replacing HLS ones for some reason.

**Comment by robotboy655** [comment]
Oh I see, you mean only from func_breakables, that is due to Valve changing drop definitions from HL1 to HL2.

You will find the lists here:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/func_break.cpp#L47-L105

I don't see any way this can be fixed without fucking up all HL2 content.

**Comment by TheMostUpset** [comment]
Thanks for that table, I've fixed the issue by replacing m_iszSpawnObject value in breakables.

**Comment by Kefta** [comment]
This has been fixed on HL1 maps.
