### ISSUE TITLE
FCVAR_REPLICATED doesnt even work

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3454]
### Details
If you create a serverside convar with the fcvar replicated flag, it just doesnt even get networked.
The wiki doesnt say anything about it being broken either.

### Steps to reproduce
Use FCVAR_REPLICATED flag on a convar and print the convar to yourself
It works on listen servers for the host, but not other players!

**Comment by sannysc** [comment]
You need to create the convar on the client as well, not just the server.

**Comment by mcNuggets1** [comment]
The text says "For serverside ConVars, it will send its value to all clients"

**Comment by Kefta** [comment]
It will sync the value to the client version, which needs to exist.

**Comment by mcNuggets1** [comment]
For real, it should be in the wiki.
It would make things much easier, but thanks anyways.

**Comment by sannysc** [comment]
I think that's referring to convars marked with `FCVAR_SERVER_CAN_EXECUTE`, which makes it so that only the server can change it.

**Comment by robotboy655** [comment]
I'd think that's really obvious that it needs to exist on client for this to work.

**Comment by thegrb93** [comment]
Wasn't obvious to me when I first tried using it eitiher.

**Comment by Kefta** [comment]
I don't know how else you'd be able to get the value if the convar doesn't exist - it just doesn't make logical sense.

**Comment by thegrb93** [comment]
It's easy to assume that the server sets up replicated convars on the client internally.

**Comment by sannysc** [comment]
The wiki page was updated, so hopefully there is no confusion going forward.
