### ISSUE TITLE
Half-Life Source NPC voice can only be heard by listenserver host

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3456]
Start a listenserver - you'll be hearing all Half-Life Source NPC lines (when you press use on them), but connected players will not.
Start a dedicated server and join it - NPCs don't talk too.

Scripted lines are broken as well.

**Comment by TheMostUpset** [comment]
I don't know if you guys did something, but it suddenly started working well. And by now it's broken again after some update.

**Comment by robotboy655** [comment]
There were no changes to this.

**Comment by TheMostUpset** [comment]
sentences.txt is the cause of this.
Tried PrecacheSentenceFile on server with different filenames: if such file is valid, clients are starting to hear HL2 voices.
If player has HL1 version of that file in garrysmod/scripts, everything works fine, but it overrides HL2 one.

**Comment by robotboy655** [comment]
Gmod ships and includes both versions of sentences.txt. It does not get loaded from mounted games.
There shouldn't be any mismatch.

**Comment by TheMostUpset** [comment]
I tried loading HL1 sentences from data folder (all clients have it in their data folder as well), but it still uses HL2 one. Seems like a bug for me

**Comment by TheMostUpset** [comment]
sentences-hl1.txt not being loaded at all, that's why I'm trying various workarounds

**Comment by TheMostUpset** [comment]
Ok, can I do a request?
There is GM:EntityEmitSound() but it doesn't detect sentences. If there were, let's say, GM:EntityEmitSentence(), I could simply detect sentences and do Entity:EmitSound with CHAN_VOICE to simulate speech

**Comment by robotboy655** [comment]
Should be fixed in Dev after it updates.
