### ISSUE TITLE
util.TraceLine and util.TraceHull filters do not work with non-sequential tables

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#3463]
When calling util.TraceLine or util.TraceHull, non-sequential filter tables don't work. Here's the code that I used, with g_nonBotBreakables and g_nonBotDoors being tables that are filled with entindexes as keys and their corresponding entities as values.
```
function TestTraces( type )
	local player = Entity( 1 )
	local aim = player:GetAimVector()
	aim.z = 0.0
	local tr =
	{
		mins = Vector( 0, 0, -16 ),
		maxs = VEC_HALFHUMAN, -- defined as Vector( 0, 0, 36 ), never changes
		start = player:GetPos() + VEC_HALFHUMAN,
		endpos = (player:GetPos() + VEC_HALFHUMAN) + aim * 500.0,
		mask = MASK_ALL,
		ignoreworld = true,
		filter = (type == true) and g_nonBotBreakables or g_nonBotDoors
	}
	local result = util.TraceHull( tr )
	print( result.Entity )
	print( ((type == true) and g_nonBotBreakables or g_nonBotDoors)[ result.Entity:EntIndex() ] )
end
```
In theory, this code should never, _ever_ print that the filter table chosen by "type" has the hit entity's entindex inside it. However, upon calling this function with "true" and hitting a prop_door_rotating (an entity that isn't inside g_nonBotBreakables), the console prints the following:
```
Entity [147][prop_door_rotating] -- the entity
Entity [147][prop_door_rotating] -- the entity in the filter table (which shouldn't have been hit)
```

**Comment by Kefta** [comment]
To quote from https://github.com/Facepunch/garrysmod-requests/issues/1129,

> It's not a bug, though. Why do you want the functions to support non-sequential tables? It will just make it slower internally

**Comment by maximlahaxim** [comment]
@Kefta I didn't know it'd make it slower, actually.

**Comment by mcNuggets1** [comment]
This is not an issue tbh

**Comment by Kefta** [comment]
This is intentional behaviour - changing the filter internally to loop over all keys will be slower and can unintentionally break addons that do stuff like:
```
local multi_purpose_table = {
	foo = some_ent, -- This is a string key so it will not be filtered
	some_other_ent, -- This is a sequential numerical key so it will be filtered
	some_other_other_ent
}

util.TraceLine({..., filter = multi_purpose_table})
```
