### ISSUE TITLE
Entity/GetAnimInfo returns no value

### ISSUE THREAD

**Issue by ThatLing** [Facepunch/garrysmod-issues#3464]
Calling Entity/GetAnimInfo returns no value because it bails out if the ptr returned by GetBaseAnimating() is **valid**. It should only bail out if the ptr is invalid, someone literally forgot to add an `!` in the expression. This also explains why it crashes on entities that have no valid C_BaseAnimating i.e. world.

![](https://i.imgur.com/VX4PuMk.png)

**Comment by robotboy655** [comment]
fixd
