### ISSUE TITLE
soundscripts / fonts not cleaning up after map change

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3465]
### Details
if you add soundscripts via sound.Add, they wont get removed, you cant remove them with lua either.
Restart game modus activated.

There should be a way to remove sound scripts to be fucking honest.

### Steps to reproduce
sound.Add restart map

**Comment by robotboy655** [comment]
Partly duplicate of https://github.com/Facepunch/garrysmod-issues/issues/502

**Comment by mcNuggets1** [comment]
Tickrate, ConVars, Lua files, Addons, Models, Materials are affected either.

**Comment by CapsAdmin** [comment]
Even game.MountGMA persists. This can potentially be used for running clientside lua on servers (confirmed but a bit obscure and probably not that big of an issue) and overriding assets? (didn't confirm, but lua works)

**Comment by mcNuggets1** [comment]
@CapsAdmin It already works, in my clientside_errors file on the server, there are errors from clientside workshop addons erroring.

**Comment by robotboy655** [comment]
Tickrate was fixed a long time ago, Workshop addons/lua are being reset now on Dev.

**Comment by mcNuggets1** [comment]
You can override default gmod fonts and when the user leaves the server, a lot of fonts may be changed.

**Comment by robotboy655** [comment]
They will be fixed whenever you join a new server/singleplayer though?

**Comment by mcNuggets1** [comment]
It didn't for me for a lot of times.
But I'm talking about back in the days.
I don't know, maybe like 2 years ago, I joined this specific darkrp server and it always mixed up my fonts.

**Comment by robotboy655** [comment]
On the topic of soundscripts, what problems them not being cleared causes?

**Comment by mcNuggets1** [comment]
Both have limits, as far as I know, which could result for fonts in crashes and for soundscripts in not being able to add anymore.

**Comment by robotboy655** [comment]
You can most definitely override existing soundscripts.
![image](https://user-images.githubusercontent.com/3299036/118268139-ada8a600-b4c5-11eb-9de9-db62db016887.png)

Soundscripts do have appear to have a limit as far as I can tell. Fonts would also be only limited by available memory.

**Comment by robotboy655** [comment]
Soundscripts show now also be cleared.

If you feel that there's something else that should be handled on disconnect, open a new issue and describe what issues it not being cleaned up causes.
