### ISSUE TITLE
render.CopyTexture doesn't do anything?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3468]
Can't get this function to do anything

**Comment by thegrb93** [comment]
render.CopyRenderTargetToTexture too

**Comment by meepen** [comment]
Nice code to replicate
It definitely does work

**Comment by thegrb93** [comment]
It's one line of code to replicate. The only reason I can think it not working is it requires being in a rendering hook, but the wiki doesn't say so.

**Comment by Kefta** [comment]
CopyTexture uses CopyRenderTargetToTexture internally, which probably won't work outside of a render hook.

**Comment by thegrb93** [comment]
Decided to test it again and still couldn't get any results. Tried setting the destination to a rendertarget as well and no difference.
```
lua_run_cl hook.Add("HUDPaint","a",function() render.CopyTexture(Material("gm_construct/flatgrass"):GetTexture("$basetexture"), Material("concrete/concreteceiling003a"):GetTexture("$basetexture")) end)
```

**Comment by thegrb93** [comment]
Ok it seems that it only works with render targets
