### ISSUE TITLE
NPC.GetEnemy Consistency Change

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#3471]
Recently a new update has been announced for Garry's Mod and one of the changes is the return type of the NPC function, `NPC.GetEnemy` This may seem like a fair change as it makes sense to return a `NULL` entity rather than `nil` and I do agree that's how the function should have been made from the beginning. But Garry's Mod has been around for many years, `NPC.GetEnemy` has always returned `nil`, by changing the return type after this many years is unnecessary, especially due to the amount of problems it's going to cause. This change has been tested by many SNPC creators on many different bases. All of the SNPC bases and SNPC addons have been broken because of this change. Changing a function that has remained the same since the beginning of Garry's Mod is very unneeded. It's unnecessary to break every SNPC addon on the workshop. Which is why I kindly ask to please revert this change before the release of this update. Thank you very much.

**Comment by Kefta** [comment]
You should be using IsValid on the return anyway, which handles nil and NULL. The nil return was undocumented and should have never been treated as such:  it's improper code.

**Comment by VpSnipes** [comment]
I'm not sure why something like this would be changed years later, it just doesn't make sense. This just causes unwanted issues and up-roar in the community, as stated above it breaks things, too many things. It's best to just revert the change and not do anything with it, if anything, you'd get a lot less people who would yell/complain to the devs if they switch it back. Would be a smart move if you ask me.

**Comment by Cpt-Hazama** [comment]
I've created a petition for this update. Hopefully this issue will be resolved soon as it will not just be our SNPC mods that are effected by this change.

https://www.change.org/p/garry-s-mod-community-npc-getenemy-consistency-change

**Comment by Kefta** [comment]
So @Cpt-Hazama was able to make a petition A MINUTE after you created this issue?

**Comment by DrVrej** [comment]
@Kefta If you don't believe you can simply check every SNPC addon on the workshop that's not a Nextbot.

**Comment by Cpt-Hazama** [comment]
@Kefta I made it earlier, just waited to publish it. Please stay focused on the topic at hand.

**Comment by VpSnipes** [comment]
"Unless "all" these bases just so happened to copy-and-paste the same code from your base." I'm sorry you feel this way sir. I regret to inform you, but we don't all think alike. It's clear the update was needed, but the change made this far in was a bad call and should've been made a lot sooner.

**Comment by birdbrainswagtrain** [comment]
Good luck with that petition.

**Comment by Cpt-Hazama** [comment]
The way I see this update is that we're like farmers who have worked so hard to grow our crops but then a bunch of construction workers come in and plow our stuff. We ask "what are we supposed to do now? Our crops are ruined.." and you guys say "just work with what you got" (referring to all the crushed up pieces of crop across the ground).

This can be an easy fix on your guy's end. On our end though, as seen through tests it is an absolute disaster and it will be for over 1,000,000 users/server players. Consistency or not, a bad decision on your end for not considering how it will impact all the big mods on the workshop (especially considering Garry's Mod is ran by the workshop. Just making updates for a vanilla Garry's Mod is just bad programming for this type of situation).

**Comment by Velkon** [comment]
Just stop writing shitty fucking code smh

**Comment by edgarasf123** [comment]
This is a minor update, the analogy @Cpt-Hazama gave can be related to GMod 13 update. This is something that is easy to fix. Just do a mass search for `NPC.GetEnemy` and add `IsValid` where needed. 

For addons that are abandoned, oh well, just take the code and release a fixed version with appropriate credits.

**Comment by Kefta** [comment]
Your "million player" argument is based on VJBase's 970k subscribers. Just like an API change, you could update your base and it will trickle down to addons that depend on it, which you have made all your developers do by adding a workshop dependency to VJBase. I've subscribed to the top 5 SNPC addons that aren't using your base (I think, Steam popular sorting is wonky atm), and none use GetEnemy incorrectly. For reference:

https://steamcommunity.com/sharedfiles/filedetails/?id=1205759235 (none of ERROR's uses it incorrectly)
https://steamcommunity.com/sharedfiles/filedetails/?id=1097446344
https://steamcommunity.com/sharedfiles/filedetails/?id=1143815468 - Doesn't use GetEnemy at all
https://steamcommunity.com/sharedfiles/filedetails/?id=1164723792
https://steamcommunity.com/sharedfiles/filedetails/?id=125988781 - Doesn't use GetEnemy at all

In fact, the only ones I have found to be using GetEnemy's nil return is your base and all SNPCs by Predator CZ who I have reached out to.

**Comment by Kefta** [comment]
And it's not off-topic to claim you are sending people to your issues to bump/boast your support. Cpt-Hazama has only posted on issues created or supported by you on this GitHub with no useful feedback other than mirroring what you say:

https://github.com/Facepunch/garrysmod-issues/issues/1962
https://github.com/Facepunch/garrysmod-issues/issues/1624
https://github.com/Facepunch/garrysmod-issues/issues/947

**Comment by DrVrej** [comment]
@Kefta That's because these are more newer SNPCs / bases, Also, more than half the time the code will fail silently without an error in console. Now as for my base, yes I will update it and I will update the addons I have made, but what about all the 100s of other addons?

**Comment by Kefta** [comment]
Point me to other addons using it incorrectly that aren't SNPCs using your base or by Predator CZ,

**Comment by DrVrej** [comment]
I don't know how other people are making it, but from what I know so far, my base, Predator's SNPCs and CPT Base are broken. A simple way to see if an addon will be affected is decompile the addon and check how `GetEnemy` is used, because like I mentioned before more than half the time parts of the code aren't running and no console error is given.

**Comment by Kefta** [comment]
That's how I've been checking. I did miss CPTBase, but luckily enough, it was made by Cpt-Hazama so he should be fully aware by now :)

**Comment by DrVrej** [comment]
Here is a simple example of how it would silently fail:
`
-- Previously this statement would check if the SNPC has an enemy and it will only continue if it has an enemy, but due to the recent change it will continue whether or not an enemy is present.
if self:GetEnemy() != nil then
     -- code
else
    -- code
`

**Comment by DrVrej** [comment]
Not always, here let me give you another example:

```
-- In this simple example, it will place a sprite at the given attachment only when it has seen an enemy, this would not create an error because no where in the code 'GetEnemy' is called.
if self:GetEnemy() != nil then
	local glow = ents.Create("env_sprite")
	glow:SetKeyValue("model","texture.vmt")
	glow:SetKeyValue("scale","0.08")
	glow:SetKeyValue("rendermode","5")
	glow:SetKeyValue("rendercolor","255 0 0")
	glow:SetKeyValue("spawnflags","1")
	glow:SetParent(self)
	glow:Fire("SetParentAttachment","blah",0)
	glow:Spawn()
	glow:Activate()
	glow:Fire("Kill","",0.1)
end
```

**Comment by Kefta** [comment]
That is a very fair example, but I did not see any of those cases in the addons that relied on GetEnemy's nil return. You can theorise any code breakage like that with an API change, but it seems quite non-essential to its functionality and an easy fix.

**Comment by DrVrej** [comment]
No I do agree they are easy fixes, but many of the addons that are currently uploaded do use this type of statements, and their owners will probably never update them, thus causing an addon that somebody liked before to break. I mean let's be honest right now, is this change really necessary after all these years? I just don't see a reason to break 100s of addons just for a cosmetic reason. I appreciate the updates that the developers have been doing recently, but this change is just not necessary, I am just simply asking them revert this small change.

**Comment by robotboy655** [comment]
I like how in your petition you say that I am reluctant to fix my mistakes, but you literally told me that there's an issue (but you didn't even tell me what it was) only 1 hour before creating your petition.

Anyway, we _do_ address any regressions that are _reported_. We give 2 week warning before every update and ask you, the mod authors and players in general, to test your addons and report any regressions. That's the whole point of the Dev branch.

Instead of just reporting that a recent change breaks something in your or someone else's mod, you first went and flamed on my profile, created a pointless petition, and _only then_ asked someone else to report the problem.

Anyway, I will look into this next week, in the mean time please do go ahead and just fix your code to futureproof your addons. The return value of NPC.GetEnemy is documented to be an Entity since June 2014. You should be using IsValid global function to validate whether an Entity exists or not, not an undocumented behavior that you copied from another addon.

**Comment by VpSnipes** [comment]
`local entEnemy = self:GetEnemy()
		if(entEnemy ~= nil and entEnemy:IsValid()) then
--code--
end`

Something along these lines, correct?

**Comment by Kefta** [comment]
That code will work, but it can be shortened to ``local entEnemy = self:GetEnemy() if(IsValid(entEnemy)) then --code-- end``

**Comment by DrVrej** [comment]
Thank you very much for looking into this, I am currently updating my base to futureproof it. By the way my mistake for misusing the function, I have been comparing it as a `nil` since the making of my base back in 2012, I didn't know it was supposed to return an entity, thank you for the notice. As for the petition or comments, those weren't by me (Just to clarify).

**Comment by Velkon** [comment]
Are you really using enemy != nil

**Comment by Velkon** [comment]
No wonder your code fucking breaks, is this a joke or some shit

**Comment by Cpt-Hazama** [comment]
@robotboy655 So is it alright to release an update for my mods before this game update is released?

Also, sorry for being aggressive earlier on your profile. We've just been through a lot of situations similar to this in the past so it just gets under my skin at times.

**Comment by sannysc** [comment]
Why are you asking for permission to update your own addons? Come on man.

**Comment by mcNuggets1** [comment]
This is so fucking embarassing.

You start a fucking petition and annoy people for doing their job, instead of just fixing your coding mistakes.
The time you wasted for this is like 10 the times of fixing your addon.

Thanks for nothing.

**Comment by Kefta** [comment]
@mcNuggets1 Compatibility with previous code is a legitimate concern. Please keep it civil.

**Comment by mcNuggets1** [comment]
@Kefta I didnt question that.

I am just angry to see people blaming gmod devs for their problems, instead of fixing them theirselves.

He wrote weird code in the first place, so it's his concern to fix it up, not the concern of robotboy655.
If I was too overdramatic about it, then sorry. This behaviour just plagues me.

**Comment by DrVrej** [comment]
@mcNuggets1 I just want to start with saying that I am not the creator of the petition nor have I blamed the Garry's Mod developers anywhere in this post. My post is simply asking the developers to consider reverting this change to avoid breaking 100s of addons. As for your second statement on why so many SNPC addons use this type of check, it's because before GMod 13 all of the SNPC addons (Including bases) used `nil` to check whether or not an enemy is seen. For example my base was initially released publicly back in 2012, before GMod 13 was even a thing. Which is why if you look through my base you will find many codes dating back to 2012 and even 2011. Just as all other SNPC creators from GMod 12, I never had a reason to update statements like this. But the problem isn't about me changing some lines of code, I already did that and will be updating my addons. The problem is that 100s of other addons will be breaking and many of their owners have left GMod and will not be updating them. As for others they have a serious reason to be angry about this, as an example, one of the SNPC creators on the workshop has 59 addons, now I don't know about you, but I personally would be pissed off if I had to go through 59 addons and update them one by one.

**Comment by mcNuggets1** [comment]
@DrVrej If there are some addons breaking due to this change, people will upload fixes for these addons, if the author of the addon didn't do it already.

It's a minor type consistency check, it won't cause much trouble.

**Comment by robotboy655** [comment]
The changes have been reversed for GetEnemy and GetTarget for the time being.

**Comment by biorisk2** [comment]
@robotboy655 Why not create a new function instead of editing the old? This way old addons still function & you get the performance or consistency that the change brought?

**Comment by Kefta** [comment]
It bloats the API - if a new function was added for every change, it would become a sea of deprecation and exceptions.

**Comment by biorisk2** [comment]
This is more of an important function that would adversely effect over 1,000,000 players for the worse if changed tho.. im sure for that level of impact - you could create a single alternative function.

(to be fair - if this update came through I would've just replaced the _G function with one that emulated the old)

**Comment by Kefta** [comment]
The developers who have showed concerns in this thread have already updated their addons, which covers the majority of players affected by this change.

**Comment by VpSnipes** [comment]
The change is needed, I'm glad for the time being it's been reverted for others to take note of and change their addons. I'll be doing changes to mine as well for future updates, thank you.
