### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-issues#3472]
Sometimes i get my gmod cleaned resetting stuff etc.. and i notice some errors where nobody rly talk about..
If you start with a clean gmod and start SP your console shows you this errors (started gm_construct)

Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
Nav File is wrong or something (4)
Attemped to precache unknown particle system "generic_smoke"!
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedrt)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedlf)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedbk)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedft)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedup)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/painteddn)

can we do something about this stuff or is there any info about it?

**Comment by Kefta** [comment]
```
Nav File is wrong or something (4)
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedrt)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedlf)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedbk)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedft)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/paintedup)
Requesting texture value from var "$startexture" which is not a texture value (material: skybox/painteddn)
```
are all from the map.

```
Attemped to precache unknown particle system "generic_smoke"!
```
is from a default particle in the game.

The ``sk_*_dmg_crowbar`` and ``sk_*_dmg_stunstick`` convars are not defined in GMod, assumingly from HL2DM weapons being used instead of HL2, thus the skill level file cannot set them.

**Comment by mcNuggets1** [comment]
You have to see the console of Counter Strike: Source upon starting the game and a map.

**Comment by Combine900** [comment]
@mcNuggets1 i know.. but i dont rly care about these as they will get no more updates.. sadly

**Comment by Combine900** [comment]
@Kefta Thanks for ur answer

**Comment by Kefta** [comment]
There's nothing really to fix - you can request the missing convars to be added but the other errors are standard/map-related.

**Comment by mcNuggets1** [comment]
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"


I got these two right now, for some reason.

**Comment by Kefta** [comment]
The particle error has been fixed, and I requested the convars in https://github.com/Facepunch/garrysmod-requests/issues/1150
