### ISSUE TITLE
errro when having no weapons at all

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3473]
### Details
mod_studio: MOVETYPE_FOLLOW with no model.

this error spams when another player has NO weapons at all in multiplayer.
(It doesn't always occur, but it does and is fixed with giving the player a weapon)

### Steps to reproduce
Strip another players of their weapons in MP

**Comment by Kefta** [comment]
The Warnings should just be removed from C_BaseAnimating::FindFollowedEntity() since the NULL return is handled properly in places that call it.

**Comment by robotboy655** [comment]
Moved it to developer 1.
