### ISSUE TITLE
Weird behaviour with Ignite on a player

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3476]
### Details
The sound of a burning player, when this players dies sometimes plays further, even tho Extingush is called upon death of the player

### Steps to reproduce
unknown

**Comment by Kefta** [comment]
Classic Source bug, been there as long as I can remember

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3358
