### ISSUE TITLE
Unable to delete presets

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-issues#3479]
### Details
In the preset editor, the delete preset button doesn't seem to work.
I got a bug report about this for my addon but it happens fine in the button tool too

### Steps to reproduce
1. Select button tool
2. Hit the + button to create a preset (called aaaa)
3. Hit the + button to create another preset (called bbbb)
4. Open the preset editor
5. Delete bbbb
6. `map gm_construct`
7. Check the presets dropdown, bbbb is still there

**Comment by robotboy655** [comment]
I cannot confirm this behavior on Dev branch vanilla singleplayer.
