### ISSUE TITLE
npc_sniper won't kill the player second time

### ISSUE THREAD

**Issue by DanilaFoxPro** [Facepunch/garrysmod-issues#3480]
### Details
npc_sniper will ignore player after having killed him once.
Edit: After killing the player, sniper is stuck in SCHED_PSNIPER_PLAYER_DEAD. This schedule has no interruptions, thus preventing sniper from doing anything at all.

### Steps to reproduce
Spawn npc_sniper via the console or place him on your map, let him kill you.
He won't shoot you again.

**Comment by robotboy655** [comment]
Fixed in Dev.
