### ISSUE TITLE
SQLITE malformed database schema (-1)

### ISSUE THREAD

**Issue by d4kir92** [Facepunch/garrysmod-issues#3481]
### Details
my database gone broke:
sql.LastError() print out:
malformed database schema (-1)

### Steps to reproduce
i cant reproduce it, but i can send the sv.db file if it would help

**Comment by edgarasf123** [comment]
Delete sv.db and it should not throw the error message, next time just make regular backups of the file. Other than that, it's something devs could not fix using the error message alone unless you can give some specific code that would lead to unintentional database corruption.

Although, the most likely the cause of the corrupted database is that your server has crashed or was forcefully closed while the database was written to.

**Comment by d4kir92** [comment]
k thanks for the info :)

**Comment by robotboy655** [comment]
Closing as stale.
