### ISSUE TITLE
Player flashlight or env_projectedtexture isn't clipped (r_flashlightscissor is broken)

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3482]
The env_projectedtexture isn't clipped and therefore casts a much bigger shadow map.

I've compared against a few source games, and the result is, something in Garry's Mod changed.

# Garry's Mod
![20180528190724_1](https://user-images.githubusercontent.com/39219459/40625647-a9227b8e-62ab-11e8-9285-bea65fb5164c.jpg)

with r_shadowwireframe 1
![20180528190716_1](https://user-images.githubusercontent.com/39219459/40625653-b08c83ba-62ab-11e8-8314-78afe615caca.jpg)

# Counter-Strike: Source
![20180528190842_1](https://user-images.githubusercontent.com/39219459/40625614-7ed19e1e-62ab-11e8-87ef-17ebfe0f680a.jpg)

with r_shadowwireframe 1
![20180528190357_1](https://user-images.githubusercontent.com/39219459/40625626-89f9396e-62ab-11e8-9058-af11cc329c7a.jpg)

# Half-Life 2: Episode 2
![20180528192044_1](https://user-images.githubusercontent.com/39219459/40625793-61cc3c2e-62ac-11e8-8c52-ff77f5ee55b9.jpg)

with r_shadowwireframe 1
![20180528192037_1](https://user-images.githubusercontent.com/39219459/40625797-6520db28-62ac-11e8-938c-372a6a947f9a.jpg)

Edit:
It looks like r_flashlightscissor is broken in Garry's Mod.
It's also default to 0 in Garry's Mod as well, when it is fixed, please make it default to 1.
Tested on the prerelease branch, in case that matters.

**Comment by besenyei** [comment]
iirc, last time something involved the flashlight being changed was to fix this other issue, https://github.com/Facepunch/garrysmod-issues/issues/141

**Comment by robotboy655** [comment]
No, that's different.

**Comment by besenyei** [comment]
> This is disabled in GMod intentionally, though I do not know why.
Is there a good reason to even disable this, intentionally?
I can only think of bad reasons.

**Comment by besenyei** [comment]
I would like to see this enabled, because the performance loss from overdrawing is not worth it.

**Comment by robotboy655** [comment]
I have just tested and there's no noticeable performance difference with it enabled and disabled, with like 50 env_projectedtextures. In fact its a tiniest bit faster without it.

It also causes visual artifacts on the view model of the physgun/gravity gun:
![image](https://user-images.githubusercontent.com/3299036/41858438-9619c1e8-78a2-11e8-85ff-5866d64210af.png)

**Comment by besenyei** [comment]
The performance loss from an env_projectedtexture is entirely scene dependant.
Flashlight models, flashlight shadows, shadow rendering, brush model rendering should always see some cost.

https://steamcommunity.com/sharedfiles/filedetails/?id=620613205
This map in particular has real fps issues whenever a projected texture is used, the brush model windows spike up a lot in shadow rendering and brush model rendering.

**Comment by besenyei** [comment]
[Fixing cuts in projected texture](https://developer.valvesoftware.com/wiki/Env_projectedtexture/fixes#Fixing_cuts_in_projected_texture) - this doesn't really "fix" anything, it just disables r_flashlightscissor.

**Comment by Kefta** [comment]
Even if r_flashlightscissor is not re-enabled, the projected texture incorrect cutoff is a bug of its own noticeable on some brush contacts. Maybe that should be moved to an issue of its own so those fixes can be implemented?

**Comment by besenyei** [comment]
I wasn't aware of that being a separate issue, but what ever the case, would it be a viable solution to "update" the projected texture with what ever is avaible from [source sdk 2013](https://github.com/ValveSoftware/source-sdk-2013)?

I'm just presuming the one in Garry's Mod must be based on an earlier version.

**Comment by Kefta** [comment]
Jk I misunderstood the page, was thinking of a clipping bug fixed in https://github.com/ValveSoftware/source-sdk-2013/pull/336/files

**Comment by besenyei** [comment]
That screenshot from Robotboy655 looks like r_flashlightscissor is cutting the flashlight at the wrong position, which in this case is at the view model position.

**Comment by besenyei** [comment]
Do you think you could remove the "wont fix" ?

**Comment by Raox2** [comment]
Engine performance fixes are definitely worth looking at.

**Comment by Kefta** [comment]
``The issue is actually with the flashlight casting light on the view models, which doesn't work well with r_flashlightscissor.``

Which works fine without r_flashlightscissor. Sounds like the actual issue is how it clips on viewmodels, which is probably why Valve didn't have viewmodel lighting enabled in the first place.

**Comment by besenyei** [comment]
This could also help, https://github.com/Facepunch/garrysmod-requests/issues/874

**Comment by besenyei** [comment]
### [zs_last_stand_mall_v5a](http://142.44.142.152/fastdl/garrysmod/maps/zs_last_stand_mall_v5a.bsp.bz2)

345 fps
![20180717025648_1](https://user-images.githubusercontent.com/39219459/42792438-2967bbfa-896d-11e8-9869-982978671a4e.jpg)

164 fps with flashlight on
![20180717025659_1](https://user-images.githubusercontent.com/39219459/42792443-2dc9ec18-896d-11e8-829e-880f962be416.jpg)

I have gmod_mcore_test 1, Nvidia GTX 1080Ti, and i7 8700K and if I am losing that much fps to a single flashlight in a _complex_ scene, how's it going to affect those with lower hardware?

------------------------------

Lets say I'm one of those unfortunate, who's unable to make use of multi-core rendering, here's the result:

95 fps with gmod_mcore_test 0
![20180717031207_1](https://user-images.githubusercontent.com/39219459/42792890-553e14de-896f-11e8-979a-73a2d386bff7.jpg)


-----------------------------------------------------------

r_flashlightdrawfrustum 1, r_shadowwireframe 1, and r_flashlightlockposition 1.

The flashlight frustum box is excessively large, and this in turn produces over-sized map shadows from it's contact points on the world.

This is what the flashlight does at that position in my previous images.
![20180717030351_1](https://user-images.githubusercontent.com/39219459/42792653-618d9d50-896e-11e8-8cef-7cb121e30010.jpg)

 --------------------------------------

I could just do, r_drawtranslucentworld 0 to disable rendering those _complex_ windows, but that wouldn't solve the issues originating from the flashlight itself.

**Comment by robotboy655** [comment]
It has no effect. Same map, same spot:

```r_flashlightclip 0;r_flashlightscissor 0```
![image](https://i.imgur.com/8Yu8yc5.jpg)

```r_flashlightclip 1;r_flashlightscissor 1```
![image](https://i.imgur.com/LncB3KT.jpg)

![image](https://user-images.githubusercontent.com/3299036/42821576-847a4cf0-89e1-11e8-9636-d6a30267f380.png)

**Comment by robotboy655** [comment]
I also noticed this bug with 2 lamps with different FOV:
![image](https://i.imgur.com/0Mc1OyX.jpg)

**Comment by besenyei** [comment]
That is really disappointing to hear, thanks for testing it out.

**Comment by robotboy655** [comment]
Maybe I am missing something, but I do think I have restored every single disabled bit of it.

**Comment by besenyei** [comment]
In your screenshots, it does look like something is wrong.

r_flashlightscissor 1 is clearly cutting the map shadow, but the cost remains the same, it's as though it isn't cut.

**Comment by robotboy655** [comment]
You can create a test map and test it in hl2 vs gmod.

**Comment by besenyei** [comment]
Alright, I've can confirm without a doubt that I was wrong the entire time.
I tested on Counter-Strike: Source (create_flashlight) and Garry's Mod and can conclude this issue.

-------------------------------------------------------

### Counter-Strike: Source

![20180717193630_1](https://user-images.githubusercontent.com/39219459/42838544-0cf4ff3c-89f9-11e8-8ec2-733955d3d53e.jpg)

`mat_queue_mode 2, r_flashlightscissor 1`
![20180717193643_1](https://user-images.githubusercontent.com/39219459/42838557-12d4f1aa-89f9-11e8-99e0-ed827ec31875.jpg)

`mat_queue_mode 2, r_flashlightscissor 0`
![20180717193924_1](https://user-images.githubusercontent.com/39219459/42838594-2321300a-89f9-11e8-93f8-0aad4dfdc2a5.jpg)

`mat_queue_mode 0, r_flashlightscissor 1`
![20180717193658_1](https://user-images.githubusercontent.com/39219459/42838645-414039d2-89f9-11e8-8c82-4494daca5892.jpg)
`mat_queue_mode 0, r_flashlightscissor 0`
![20180717193722_1](https://user-images.githubusercontent.com/39219459/42838662-4b07163e-89f9-11e8-8a32-53626ff666b9.jpg)




r_flashlightscissor doesn't actually do anything beneficial, and Shadow Rendering is indeed the tiniest bit faster with it disabled, the difference is negligible, 1-2 fps difference.


I suppose the issue is the flashlight is inherently an unoptimized part of the source engine, so I'll accept that, thanks for your assistance regarding this matter, and sorry for wasting your time.

**Comment by besenyei** [comment]
Could disable receiving shadows on translucent world be a solution to one of the problems?

**Comment by Kefta** [comment]
I'm pretty sure they also use a clipped projected texture, which leads to similar bugs; https://www.youtube.com/watch?v=7sWQ7xZR4zo
