### ISSUE TITLE
Out-of-bounds array read with monster_*_dead

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3483]
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/hl1/hl1_npc_barney.cpp#L929

No bounds checking is done on m_iPose, which can be set to any integer value in ::KeyValue. Applies to monster_barney_dead, monster_hgrunt_dead, monster_scientist_dead, and monster_hevsuit_dead.

**Comment by robotboy655** [comment]
Fixed and added a proper model for monster_hevsuit_dead
