### ISSUE TITLE
Too many indices for index buffer.

### ISSUE THREAD

**Issue by Likanin555** [Facepunch/garrysmod-issues#3484]
### Details
Crash/Error:
,,Too many indices for index buffer. tell a programmer (59838>32768)"

This crash always happen, when on screen is too many decals/particles/effects.

Version GMod: 2018.05.28

[http://www.mediafire.com/file/gls0k34gwry8p92/hl2_180528_crash_2018_5_29T21_51_27C0.mdmp/file](url)
### Steps to reproduce
I.
Create so many decals in one place.

II.
Spawn so many particles.

**Comment by DreamsOfCyanide** [comment]
> 
> 
> Is there any reason this has not been fixed yet, it's annoying you shoot a prop which has a high res texture on it and your game crashs?

r_drawmodeldecals 0 tends to work

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3159
