### ISSUE TITLE
PhysObj Additions aren't in the update

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3486]
The new PhysObj functions aren't there. Might be others too, but I only checked for the physobj ones.

**Comment by robotboy655** [comment]
The server must obviously be updated to the latest version before you can use the new stuff.

**Comment by thegrb93** [comment]
How da hell is my up-to-date client able to join an out-of-date server? Anyway, I'll try to get the server updated. Thanks.

**Comment by robotboy655** [comment]
SteamCMD sometimes doesn't update properly. You can always check the VERSIONSTR global.

**Comment by thegrb93** [comment]
from NFO
'What has happened is that the update was not marked as required. I'm unsure where they are getting the idea that things work as they describe.

The update is marked as optional. We have scheduled it to roll overnight.'

**Comment by Kefta** [comment]
Required updates = servers need to be updated for clients to join (nettable changes). Anything else is optional.
