### ISSUE TITLE
Bug with ducking

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3488]
### Details
When entering a vehicle while holding IN_DUCK and leaving vehicle while holding IN_DUCK, you have the same speed as running while being ducked.

### Steps to reproduce
Above

**Comment by robotboy655** [comment]
Fixed.

**Comment by DBotThePony** [comment]
It still happen (tested with `prop_vehicle_prisoner_pod`)

**Comment by robotboy655** [comment]
It's not the same issue. It's a pretty silly oversight from Valve too.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/player.cpp#L5456-L5470
