### ISSUE TITLE
Crashes when joining a server

### ISSUE THREAD

**Issue by ldawkes** [Facepunch/garrysmod-issues#349]
The game crashes just after "Retrieving server info...", after one or two attempts, it will join the game, but i'd like to actually get in first time.

Crash dump: http://bit.ly/13LvcBz

**Comment by Kefta** [comment]
Garry's Mod still has serious compatibility/stability issues with Overwolf -- I am not sure why.

**Comment by robotboy655** [comment]
With any Overlay, I have heard Discord does it too.

**Comment by Kefta** [comment]
Could it possibly be looked into? It works fine in CS:S

**Comment by robotboy655** [comment]
1) I cannot reproduce the issue
2) There's next to no info on the issue

How do you expect it to "be looked into"?

**Comment by Kefta** [comment]
Fine, I'll get evidence
