### ISSUE TITLE
game.SetSkillLevel's value always gets reset to skill convar's, and skill.cfg is never called on change

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3491]
This is because of ``CGameRules::Think`` constantly calling ``SetSkillLevel( skill.GetInt() )``, I assume because convar callbacks weren't a thing when difficulty levels were first implemented for HL1.

Fix steps:
- Remove ``SetSkillLevel( skill.GetInt() );`` from ``CGameRules::Think``.
- Add ``SetSkillLevel( skill.GetInt() );`` to ``CGameRules``' or ``CGModGameRules``' constructor.
- Add ``RefreshSkillData( true );`` to ``CGameRules::OnSkillLevelChanged``
- Remove ``SetSkillLevel( skill.IsValid() ? skill.GetInt() : 1 );`` from ``CGameRules::RefreshSkillData`` to prevent recursive calls.
- Add callback method to the ``skill`` convar (defined in engine/host.cpp) to call ``SetSkillLevel``.

**Comment by robotboy655** [comment]
Fixed.
