### ISSUE TITLE
god/notarget concommands don't work in multiplayer

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3493]
Doesn't seem to do anything. GodEnable/Disable are still functional.

**Comment by robotboy655** [comment]
sv_cheats needs to be set to 1, even in singleplayer.

**Comment by Kefta** [comment]
sv_cheats is enabled, testing on a dev branch listen server:
![](https://i.imgur.com/zsCk0i6.png)

**Comment by robotboy655** [comment]
How does something like this even break. Will look into it soon.

**Comment by Kefta** [comment]
I see why, it's the ``gpGlobals->deathmatch`` check, which is why ``notarget`` doesn't work either. ``gpGlobals->deathmatch`` is only true in multiplayer, so I guess the concommands never worked in non-singleplayer.

**Comment by Kefta** [comment]
Any chance this could be fixed? Really simple one-line removal for each concommand.

**Comment by robotboy655** [comment]
F
