### ISSUE TITLE
Fix serverbrowser query breaking A2S/GS traffic seperation thus making server hardening easier

### ISSUE THREAD

**Issue by Leystryku** [Facepunch/garrysmod-issues#3495]
### Details
When using sv_master_share_game_socket garrysmods serverlist.Query function returns _replyip:replyport_ instead of _replyip:gameserverport_. 

This makes seperating A2S traffic and gameserver traffic **impossible**. Functionality is only broken in gmods server browser.

Seperating A2S and gameserver traffic seems like something that would allow nice migrations of all kinds of server query based attacks, so it's something that a large portion of the gmod base could profit from.

### Steps to reproduce
Set sv_master_share_game_socket to 1, and refresh, the server will be unjoinable due to the address not being replyip:gameserverport

### Fix
Change a single variable. Instead of using QueryPort use ConnectionPort
```
uint16 m_usConnectionPort;    
  uint16 m_usQueryPort;
  uint32 m_unIP; 
```

**Comment by SnowboiTheGr8** [comment]
This functionality is broken and it has advantages so it should be fixed. It's a shame certain people are downvoting this just to spite Ley.

**Comment by JDaymon** [comment]
Hey you fucking dumbass, I hope you just retire already, you're fucking retarded! I swear to god you're dumb as hell! You're incorrect retarded and fucking stupid, if you don't stop being this ignorant and retarded I'm thinking you're gonna have to end it and fuck off! JUST LEAVE ALREADY NO ONE CARES WHAT YOU THINK BREAKS SOMETHING BECAUSE IT ISNT WHAT BREAKS IT YOU FUCKING DUMBASS

**Comment by fst3a** [comment]
BRING IT ON PERPS

**Comment by ExtReMLapin** [comment]
if your name is noi we don't care what you think

**Comment by joeyjumper94** [comment]
so if this was fixed it would be harder to hit gmod servers offline?

**Comment by SnowboiTheGr8** [comment]
@joeyjumper94 Kinda - you could use this to better distribute the attacks, or to provide remote DDoS mitigation, a bit like Cloudflare works on a website 👍

**Comment by willox** [comment]
It sounds like this issue is just that the query port is read from the steam api server responses instead of the game port

**Comment by robotboy655** [comment]
Made it use the connection port over the query port.
