### ISSUE TITLE
NPC pistol accuracy and AR2, SMG sound bug

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3496]
### Details

NPCs are too accurate with the pistol regardless of their proficiency, changing their weapon proficiency from Poor to Perfect makes no difference. 

NPCs with AR2s and SMGs have choppy firing sounds.

Started happening after the February update, still present after the May update.

### Steps to reproduce

Spawn NPCs equipped with the pistol, AR2 and SMG.

**Comment by ZehMatt** [comment]
Probably because the ai_weapon_* stuff is gone as they use the normal weapons now. So the fake shoot trajectory is no longer calculated for the pistols when AI holds it. Not sure about the sound issue, not happening on my end.

**Comment by robotboy655** [comment]
The sound bug is fixed, the accuracy problem was fixed in #3742
