### ISSUE TITLE
Lua based weapons are more expensive in DrawOpaqueRenderables

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3499]
I've compared between weapons in sandbox and their lua based duplicates, the lua based weapons appear to be more expensive in DrawOpaqueRenderables than weapons created from the engine.

As an example, I gave 50 bots weapon_smg1 and [weapon_nyangun](https://steamcommunity.com/sharedfiles/filedetails/?id=123277559).
weapon_smg1
![20180608085543_1](https://user-images.githubusercontent.com/39219459/41146224-931fd5a0-6afa-11e8-9896-5b82cac331f6.jpg)

weapon_nyangun
![20180608085606_1](https://user-images.githubusercontent.com/39219459/41146226-972a22ea-6afa-11e8-87c2-a0bead6bfe24.jpg)

I've conducted other tests, and I can conclude the issue is with weapons made in lua.

**Comment by Kefta** [comment]
Probably because Lua weapons have to make C->Lua calls for WEAPON:DrawWorldModel and WEAPON:DrawWorldModelTranslucent, and Lua->C calls for self:DrawModel()
