### ISSUE TITLE
fog malfunctions in dev branch

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3500]
### Details
some parts of the map will be completely fogged up when they shouldn't be
![23-52-46](https://user-images.githubusercontent.com/22709121/41169622-68d06cfc-6afe-11e8-8404-05070dd0b863.png)

other parts are never fogged
![09-44-19](https://user-images.githubusercontent.com/22709121/41170336-aa92be22-6b00-11e8-9b52-fa6f546b3e7c.png)

### Steps to reproduce
get any map that has a fair amount of geometry and add an env_fog_controller or use a lua script to create fog like
`

	hook.Add("SetupWorldFog","rp_downtown_em_hs_fog",function()

	render.FogColor(129,138,140)

	render.FogEnd(2750)

	render.FogMaxDensity(1)

	render.FogMode(MATERIAL_FOG_LINEAR)

	render.FogStart(0)

	return true

	end)

`

**Comment by robotboy655** [comment]
FUK

Post map names and positions where this happens. (using getpos console command)

**Comment by joeyjumper94** [comment]
https://github.com/joeyjumper94/rp_downtown_em_hs that's the map
it's derived from rp_downtown_evilmelon

setpos 793.815796 1002.391785 -39.106590;setang 18.310539 161.445847 0.000000

setpos -1658.379883 -434.634216 1045.891235;setang 22.329948 175.513962 0.000000

**Comment by roboderpy** [comment]
This happens even without fog setup and with **ALL** hooks disabled (including gamemode ones)

**Comment by robotboy655** [comment]
Should be solved on Dev.
