### ISSUE TITLE
macOS Support Going Forward

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#3509]
At WWDC 2018 Apple introduced macOS 10.14 Mojave, which further warns users about running 32-bit applications (like Steam and Garry's Mod). Also announced, Apple has deprecated OpenCL and OpenGL in 10.14, and say they will eventually not be supported on macOS.

Though these changes will not affect compatibility with macOS 10.14, are there any plans to retain compatibility with future versions of macOS that may not support 32-bit applications nor OpenGL?

**Comment by meepen** [comment]
nice meme

**Comment by rudeustudeus** [comment]
They won't even fix game breaking bugs from the time the game was released. All the gmod devs are just dumb kids who use windows 10, so I wouldn't expect them to do any *nix fixes.

**Comment by meepen** [comment]
Bad meme from someone who doesn't know how game development works

**Comment by Bo98** [comment]
I believe there has been some work on 64-bit. (I've been away from here for a few months so I haven't caught up with everything.)

OpenGL deprecation isn't an immediate concern I would say. Many things get deprecated but _very_ little get removed. Unlike 32-bit where they hinted at support being dropped in the near future, the deprecation of OpenGL is just formally marking the end of active development on it as they encourage everyone to use Metal. Plus, Metal adoption isn't particularly high yet as Metal is not a cross-platform API (Valve-backed MoltenVK fills this gap now) so I expect it to stay around for the foreseeable future.

**Comment by propguardiandarkcide** [comment]
The problem stands that none of the gmod devs have any clue how to program outside their cozy soy boy windows 10 machines. Core features of gmod are broken on this OS and they do not care at all.

**Comment by Kefta** [comment]
Nice bait

**Comment by thegrb93** [comment]
>calling anything but macOS soyboy machines
