### ISSUE TITLE
Custom Weapons menu populating issue. 

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-issues#3516]
### Details
Tell us exactly what happens, every single detail that you can think of
https://pastebin.com/vc5eLrhp
The above link shows the code im working with. Trying to populate an independent menu that has sub categories for more specific branches of those weapons. Issue is, for some reason it won't populate the menu with weapons of like name(Matching print names). 
(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

This is the unsliced version of the code: 
https://pastebin.com/ySL4QKNu

**Comment by robotboy655** [comment]
This isnt a place to get help with scripting.

https://forum.facepunch.com/f/gmoddev
