### ISSUE TITLE
God mode doesn't work in sandbox

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#3517]
I enabled god mode in the SandBox gamemode but it doesn't work.
Also option "Player Damage Player" aka PvP doesn't work too.

**Comment by robotboy655** [comment]
Cannot confirm, assuming multiplayer without any mods.

```sbox_godmode 1``` will make ```sbox_playershurtplayers 1``` feel like not working because you know, everyone is in god mode.
