### ISSUE TITLE
GetInternalVariable unsupported fields.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3518]
GetInternalVariable is currently only able to use a limited set of field types, from what I can tell those are float, string, time, sound, model, vector. 

However some fields are encoded with FIELD_CHARACTER (single byte, still numeric), FIELD_SHORT (two bytes, still numeric) etc. For example m_takedamage is using FIELD_CHARACTER, this value can be obtained via GetSaveTable but for performance reasons I think GetInternalVariable should have the same results as GetSaveTable.

**Comment by Kefta** [comment]
Since GetSaveTable gets the value correctly, https://github.com/Facepunch/garrysmod-requests/issues/1002 would be a good alternative to utilise those conditions.

**Comment by ZehMatt** [comment]
Its essentially the same thing just with a different name from where I see it, but yes I wouldn't mind if its called GetSaveValue either.

**Comment by robotboy655** [comment]
Fixed
