### ISSUE TITLE
Large Addon Crashing Game & Steam Client

### ISSUE THREAD

**Issue by MrAmos123** [Facepunch/garrysmod-issues#352]
Hello,

This is a well-known bug, but it needs to be fixed!
I'm trying to download some addons for Garry's Mod, this particular addon is 122MB's..
Elevator: Source;
I've subscribed to it in-game, it crashes.. I've subscribed to it on Steam client, it crashes..
I've not subscribed to it at all, and tried to lt the server handle the request.
Everything I do, don't work, and I've tried to get around this bug, in nearly every possible way.

Please, this needs to be fixed.. I'm trying to set up a server, but I can't join it due to this bug..

My internet speed is 1mbps, enough to handle addons. (This should not be relevant though..)

It's easy to recreate, subscribe to a really big addon (80 and up) and, watch the game die..

Thanks,
MrAmos123.

P.S This bug has been around a while now.. Don't you think it's time to fix?

**Comment by robotboy655** [comment]
Cannot reproduce with said addon on live version of the game.

**Comment by MrAmos123** [comment]
@robotboy655 Sorry you had to deal with this request. I've just read it back now and realised how inarticulate I was.

Also, congratulations on getting hired at Facepunch!

**Comment by thegrb93** [comment]
> @robotboy655 Sorry you had to deal with this request. I've just read it back now and realised how inarticulate I was.
> 
> Also, congratulations on getting hired at Facepunch!

5 years late m8
