### ISSUE TITLE
Entity:__newindex can crash the game

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-issues#3522]
### Details
Well, Entity's `__newindex` metamethod can crash the game if key is not a string or a number (and it converts number to a string). Perhaps, it just calls `LUA->GetString` without any checks.
### Steps to reproduce
This code will crash the game:
```lua
local ent = Entity(1)
ent[true] = 123 -- crash
print(ent[true])
```
This code won't crash and it works correctly:
```lua
local ent = Entity(1)
ent:GetTable()[true] = 123
print(ent[true]) -- 123
```
Instead of `true` there can be any value that is neither a string nor a number.

**Comment by Kefta** [comment]
This does not happen on panels for the record, which is another stock userdata type with a __newindex method.

**Comment by robotboy655** [comment]
Fixed.
