### ISSUE TITLE
Scene sounds playing before needed

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-issues#3525]
### Details
In every Half-Life 2 to Episode 2 map I've played, the sounds and voices in scenes (.vcd) play about 0.6 seconds before the actual time they're set to play, so for example, a stun stick zap or character voice that's meant to play at 1.5 seconds in the HLFaceposer timeline will play at about 0.9 seconds in-game.  Which makes character facial expressions, gestures, etc. look extremely out of sync.

### How to reproduce
This happens to every scene in the game, so you can go to any Half-Life 2 map with characters on it to see it.  Although the easiest way to see this is to go on the first map of Half-Life 2 (d1_trainstation_01), and either watch the Breen broadcasts in the map, or go to where the one guy who gets pushed by a metrocop and knocks down his brief cases in the process.  You notice that the cloth sound that plays when the metrocop pushes him, plays before the metrocop actually does it, so you'll hear the sound, and then you'll see the metrocop push him, when in Half-Life 2, this plays when he pushes him.

**Comment by robotboy655** [comment]
Whatever it is, it is on your side. Look into your settings. ( debug_dump console command ).

I cannot confirm this.

**Comment by Kidnation** [comment]
So apparently the issue was caused by snd_mixahead being set to 1 for some reason, sorry to waste your time on this.  If anyone else has this issue and sees this, set snd_mixahead to 0.1 to fix it.
