### ISSUE TITLE
VVIS.exe corrupted?

### ISSUE THREAD

**Issue by kulcris** [Facepunch/garrysmod-issues#3528]
### Details
When trying to compile a map with the VVIS that is provided in the garrysmod/bin folder it freezes at PortalFlow:   0

This has been verified about 20 times going so far as to create a new map and test it.

Grabbing vvis from source sdk 2013 and using that to compile a map works perfectly. 

I deleted VVIS and verified game cache (it redownloaded it) and this resulted in a freeze again in the same spot

(Used nems batch compiler to test with other versions of vvis.exe)

### Steps to reproduce
Compile a large map with VVIS.exe provided in the garrysmod/bin folder

**Comment by kulcris** [comment]
When using GMOD vvis.exe
https://i.gyazo.com/thumb/1200/1a4a9a4281d8485c223ef5b718a88c38-png.jpg

When using source sdk multiplayer vvis.exe
https://i.gyazo.com/63fed63d8b76ed468a62a929b30e295a.gif

**Comment by neico** [comment]
Since you compile a large map I also assume it has large open areas, did you try using [func_viscluster](https://developer.valvesoftware.com/wiki/Func_viscluster) to batch those together?
Maybe there's just too many visleafs for it to calculate?

**Comment by DanilaFoxPro** [comment]
I think GMod's VVIS just doesn't show the progress while compiling. (Probably to reduce the runtime by not checking the compile progress?)

It just jumps from "0" to "0...1...2...3...4...5...6...7...8...9...10" when it's finished.

**Comment by kulcris** [comment]
i think you missed my point, i created a new map that was literally a small box big enough for maybe two players and it got stuck at 0 for over 24 hours

This was also back in July so you are a bit late to the party
