### ISSUE TITLE
Possible Source 1.5 map fix

### ISSUE THREAD

**Issue by Train654** [Facepunch/garrysmod-issues#3529]
The fullbright and general weirdness of the maps in the csgo, l4d and portal 2 shared source engine build maps could be possibly caused by an entity's key or value being too long, seeing as that engine build supports more characters, the usual culprit is sky_camera.
Hope this helps out.

**Comment by robotboy655** [comment]
According to VDC, sky_camera has no new keyvalues in any other engine version, so how key value length would have any effect? They are stored in plain text, not in binary.

Can you give example(s) of entities in newer engine version having key or value too long?

**Comment by Train654** [comment]
![deadcenter](https://user-images.githubusercontent.com/38988610/42760503-f9ae219a-890a-11e8-8c1f-178fa32738aa.png)

this is an example on c1m1_hotel, after removing the entity and compiling the map it worked fine, compiling it with the entity still existing gave an error suggesting that an entity's keyvalue is too long and the map acted very weirdly in-game.

**Comment by robotboy655** [comment]
Bumped to 64(from 32). Lets see if it fixes anything.
