### ISSUE TITLE
info_bigmomma seems to be broken and doesn't recover monster_bigmomma health

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3530]
info_bigmomma entity controls monster_bigmomma movement, health and other stuff. (https://developer.valvesoftware.com/wiki/Info_bigmomma_(GoldSource_Engine))
So the health thing seems to be broken. Bigmomma has 150 health on spawn, when it goes <= 0, the NPC moves to another point and health must be recovered after destination, but it doesn't happen, HP stays the same value.

It also could be bug in monster_bigmomma NPC code. If I remember correctly, this started to happen since it became killable on all maps after some Gmod update.

**Comment by robotboy655** [comment]
I see this behavior is disabled (commented out), but it wasn't on that update (which only changed whether the damage should be taken or not), it was commented out since before June 2014.

I will re-enable it.
