### ISSUE TITLE
Joining a server that normally works crashes the game

### ISSUE THREAD

**Issue by Toasty-Engineer** [Facepunch/garrysmod-issues#3531]
### Details
This happened out of nowhere, but joining a DarkRP server in multiplayer crashes the game with a lua "out of memory" error soon after connecting. It only happens on multiplayer, no issues with singleplayer as far as I could tell. It only seems to happen when enough people are connected, as I could play for a good while until the server started to fill up past 50+ people.

### Steps to reproduce
1. Join a heavily populated server with a bunch of addons
2. Crash, either during "Sending client info..." or after connecting with an "out of memory" error
It's inconsistent, sometimes it lasts for a while or for only a few seconds. Sometimes it doesn't even fully load before crashing.

**Comment by mcNuggets1** [comment]
Crash dump, Silly?

**Comment by Kefta** [comment]
I don't think Lua out of memory errors generates a dump, though I could be mistaken.

**Comment by mcNuggets1** [comment]
Could be, but "out of memory" is a clear error code and doesn't need a dump then.

Can't it be fixed by the engine instead of crashing the game tho?
I mean like clearing memory before it crashes your game and then error in the console.

**Comment by Kefta** [comment]
You can't just "clear out memory", it's storing stuff needed by the game.

**Comment by mcNuggets1** [comment]
I thought so, but maybe there is irrelevant stuff spammed which could get removed and error instead of crashing.

**Comment by robotboy655** [comment]
Closing as stale.
