### ISSUE TITLE
maps doesnt load

### ISSUE THREAD

**Issue by err0r1nc0de** [Facepunch/garrysmod-issues#3532]
### Details

when i run a map, on "loading resources" part it gives a script error then gets to main menu

**Comment by Kefta** [comment]
What's the script error? Have you tried disabling addons?

**Comment by err0r1nc0de** [comment]
error happens at 7th loading cube or somthing that shows how much loaded

**Comment by Kefta** [comment]
Can you check your console and post the error?

**Comment by err0r1nc0de** [comment]
it happen several times i deleted addons and reinstalled first it worked updated , worked again reused updategmod.exe and error started
note: it also shows time as 2017

**Comment by Kefta** [comment]
Do you own the game on Steam? The outdated version + random update exe implies you're using an unofficial version.

**Comment by err0r1nc0de** [comment]
nothing special going on as i seen, but another useless error could be making it unssenable , its repeating

**Comment by err0r1nc0de** [comment]
unofficial

**Comment by Kefta** [comment]
Facepunch does not support pirated copies of the game.
