### ISSUE TITLE
util.TraceLine returns nil in some rare cases.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#3535]
### Details
util.TraceLine() somehow returns as nil for some people. This is sadly not something I could replicate, but I get more and more reports from people who use my mod StormFox.

### Lua details
The error occurred here: (At t.HitPos)
```
local function ET(pos,pos2,mask)
		local t = util.TraceLine( {
		start = pos,
		endpos = pos + pos2,
		mask = mask or LocalPlayer(),
		filter = LocalPlayer():GetViewEntity() or LocalPlayer()
		} )
		t.HitPos = t.HitPos or (pos + pos2)
		return t
end
```
> [StormFox - Environment mod [BETA]][ lua/stormfox/functions/cl_raineffect.lua:55](https://github.com/Nak2/StormFox/blob/master/lua/stormfox/functions/cl_raineffect.lua#L55): attempt to index local 't' (a nil value)

I've asked people to run PrintTable(debug.getinfo(util.TraceLine)) but the function isn't overwritten.
I sadly can't supply any more details, hopefully you can take a look at it.

**Comment by Kefta** [comment]
Unrelated to your issue, but you can't use entities as a mask parameter in a trace. Also, GetViewEntity will always return an entity so your ternary case will never be reached. And lastly, HitPos will always be defined in the trace struct.

**Comment by mcNuggets1** [comment]
Since when is LocalPlayer() a mask also?

**Comment by Nak2** [comment]
I think I accidentally added a player as a mask, when I got annoyed at the tracers not behaving as it should.

Players have gotten some strange errors that should not be possible, that is why I've included a lot of safeguards.
As the error points out; util.TraceLine returned a nil. I've made a work-around by checking if the result is a nil for now.

**Comment by robotboy655** [comment]
It will return nil in only the following cases:
* The world hasn't initialized yet
* The first argument isn't a table
