### ISSUE TITLE
IGModAudioChannel crash when using a half garbage collected object

### ISSUE THREAD

**Issue by SpiralP** [Facepunch/garrysmod-issues#3537]
`sound.PlayURL` sometimes crashes when calling `tostring()`, `SetVolume()` or other methods on a half garbage-collected instance of IGModAudioChannel.
I'm only calling these in my addons after checking IsValid() which is always true.

```lua

local weakTable = setmetatable({}, {__mode = 'k'}) -- weak key table

sound.PlayURL(
	"https://cdn.rawgit.com/Metastruct/garrysmod-chatsounds/60fe5fa8/sound/chatsounds/autoadd/holyshitj/that%20is%20still%20some%20good%20meat%20on%20that%20fucking%20fish.ogg",
	"",
	function(sndObject)
		
		weakTable[sndObject] = true
		
		timer.Simple(0.1, function()
			collectgarbage("collect") -- garbage collect once to clean up C object, but not lua object yet
			-- collectgarbage("collect") -- fully gc
			
			timer.Create("a", 0, 0, function()
				local snd = next(weakTable)
				if not snd then return end -- was fully gc'd
				
				print(snd:IsValid()) -- always true?
				print(tostring(snd)) -- will call __tostring, and sometimes print corrupted strings or crash
			end)
		end)
	end
)
RunConsoleCommand'showconsole'
```
I've had to run this sometimes at most 8 times before crashing

here's one example of it showing corrupted strings
![image](https://user-images.githubusercontent.com/2898730/43056797-1c64eed4-8df3-11e8-8764-4ff1a344d8c1.png)
here's the mdmp from the session the screenshot was taken in
[hl2_180717_crash_2018_7_23T4_6_23C0.zip](https://github.com/Facepunch/garrysmod-issues/files/2217907/hl2_180717_crash_2018_7_23T4_6_23C0.zip) or online at [dumps.metastruct.uk.to](http://dumps.metastruct.uk.to/dumper.py?dump=hl2_180717_crash_2018_7_23T4_6_23C0.mdmp)

I'm running this on dev branch, 180717
unsure if related to #3401

**Comment by robotboy655** [comment]
Should be fixed in Dev. Let me know if you find any regressions.

**Comment by SpiralP** [comment]
Yup, can't get it to crash anymore! Thanks so much!
