### ISSUE TITLE
Gmod crashes when you read certain NAN floats from binary

### ISSUE THREAD

**Issue by ZakBlystone** [Facepunch/garrysmod-issues#3538]
### Details
When reading `0xFFFFFFDF` or `0xFFFFFFBF` as a float from a binary file, the game crashes.

### Steps to reproduce
```
lua_run local f = file.Open("dontreadthis.dat", "wb", "DATA") f:WriteULong(0xFFFFFFDF) f:Close()
lua_run local f = file.Open("dontreadthis.dat", "rb", "DATA") print(f:ReadFloat()) f:Close()
```

_NOTE: this is not an issue with write functionality. In the initial test I produced the input file using a hex editor._

### Other unexpected behavior
When reading the float `0xFFFFFFEF` the return value is `true`.
When reading the float `0xFFFFFFCF` the return value is `thread: 0xe0000000`.
When reading the float `0xFFFFFFAF` the return value is `cdata: 0xe0000008`.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/43076514-1f36f892-8e8d-11e8-843d-41d888c53541.png)

Cannot confirm? Tried a bunch of your example values and nothing happens that isn't supposed to happen?

**Comment by Foohy** [comment]
Hmm, I was able to repro it in sandbox singleplayer no mods as well. Here's a dump of my crash:
http://host.foohy.net/public/Documents/hl2_180528_crash_2018_7_23T17_7_39C0.mdmp

I've just tested on the dev branch, and it seems to crash for me there as well.

**Comment by robotboy655** [comment]
Does it happen for you in the x64 builds?
https://forum.facepunch.com/f/gmoddev/btgwr/64-bit-Garry-s-Mod/1/

The crash is happening in LuaJITs print() function.

**Comment by Kefta** [comment]
This issue also exists with the net library - reading a ``nan`` float from a ``nan`` uint32 bit pattern causes a crash.
MDMP: https://drive.google.com/uc?id=1te-7I15Nr7ZjrJZCtzx63hbWOugTfW-E

**Comment by Kefta** [comment]
This has been fixed.
