### ISSUE TITLE
Linux x64 Unable to load filesystem_stdio_client.so

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3540]
OS: Ubuntu 18.04
Branch: x86-64

When starting GarrysMod it fails without an error.

Didn't get asked about running 32 or 64 Bit version of GarrysMod by Steam [unlike willox said](https://gmod.facepunch.com/f/gmoddev/ruwe/Next-Update-v8-February-2018-Update-is-out/12/#postcvqpsp).

Running gmod_linux_x64 via nautilus produces:
![gmod_x64](https://user-images.githubusercontent.com/18466226/43087993-a8c357ec-8e90-11e8-923d-3e4d13e4df81.png)
(file exists)

Running gmod_linux_x64 in a terminal produces:
`Failed to load /home/min/.steam/steam/steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so: (null)
AppFramework : Unable to load module /home/min/.steam/steam/steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so!`

Running hl2.sh (the startscript of GarrysMod) in a terminal produces:
`hl2.sh: line 9: cd: hl2.sh: Isn't a folder
hl2.sh: line 65: lldb: command not found
`

**Comment by willox** [comment]
Looks like I left some debugging stuff in hl2.sh, I'll remove it in a sec. Not sure that's your problem though.

**Comment by MinIsMin** [comment]
It starts and crashes: https://paste.ee/p/SYNbA

**Comment by willox** [comment]
I would guess that either the permissions on `chromium_process_x64` are incorrect, or it is missing some dependencies of its own. You could try checking with the `ldd` command.

I will have a better look at all of Linux's dependencies soon.

**Comment by MinIsMin** [comment]
Got the update but it's in the wrong folder:
It's in /bin but it's expected to be in /bin/linux64.

Moving the file and starting GarrysMod works:
Game starts, lagging for 10 seconds, minimizing itself and displays the start menu.
My startup parameter from Steam (-noworkshop) is ignored, seems like it's not passed to the binary.
When exiting via start menu GarrysMod crashes: https://paste.ee/p/w9Blc

**Comment by MinIsMin** [comment]
GarrysMod seems to extract all addons from workshop and deletes them after all got extracted:
`Not loading addon 'ttt_community_pool_2017' - file '' not on whitelist
Couldn't mount addon [ttt_community_pool_2017][addons/ttt_community_pool_2017_936764744.gma]
Removing bad addon addons/ttt_community_pool_2017_936764744.gma
`
(all addons I have subscribed to)

**Comment by willox** [comment]
Alright, I'll fix the location of that binary and log an issue for the workshop addons (i know what's up there.).
