### ISSUE TITLE
GMA loading using longs instead of ints on 64-bit builds

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#3541]
`Not loading addon 'ttt_community_pool_2017' - file '�' not on whitelist Couldn't mount addon [ttt_community_pool_2017][addons/ttt_community_pool_2017_936764744.gma] Removing bad addon addons/ttt_community_pool_2017_936764744.gm`

**Comment by meepen** [comment]
change it to std::int32_t and friends pls
