### ISSUE TITLE
[TTT] Localization file.

### ISSUE THREAD

**Issue by Satton2** [Facepunch/garrysmod-issues#3544]
### Details
1. Untranslatable message.
![image](https://user-images.githubusercontent.com/23385240/43138256-e5d209a0-8f56-11e8-9155-16726123660e.png)
There is no line in localization file to make a translation of this message.

2. Untranslated text.
![image](https://user-images.githubusercontent.com/23385240/43139056-74cfcafa-8f59-11e8-9000-7abab3f87da0.png)
This messages are already translated (Lines: **603**, **604**, **605**, **606**) but wasn't applied to chat messages.

3. Untranslatable tips.
![1](https://user-images.githubusercontent.com/23385240/43138854-dedefe26-8f58-11e8-8f3e-6e4da02458e1.gif)
Untranslatable tips above tabs in «Traitor  equipment menu» ((_if we will look at detective equipment menu there will still be said «traitor» and this is an issue too_)).

4. Untranslatable items names.
![image](https://user-images.githubusercontent.com/23385240/43139260-f2d4880a-8f59-11e8-9fca-9ba801ba0c0a.png)
Discombobulator and the Poltergeist and UMP Prototype should be translatable.

5. Untraslatable text.
![image](https://user-images.githubusercontent.com/23385240/43139450-670f7e28-8f5a-11e8-9db4-93442cadfeec.png)
«Instant kill» above wounded players that are you looking at with a knife should be translatable.

6. Untraslatable text.
![1](https://user-images.githubusercontent.com/23385240/43139813-688ea94e-8f5b-11e8-840c-df7674eae9e7.gif)
While using a DNA scanner, you can look at something and see its type. This types and «Type:» should be translatable.

7. Untranslatable text.
![1](https://user-images.githubusercontent.com/23385240/43140204-15d7679e-8f5c-11e8-951c-5763bc0eb59f.gif)
While using Binoculars, you can look at body and «Body detected» text will appear. This text should be translatable and zoom levels should be translatable too.

8. Untranslatable text.
![image](https://user-images.githubusercontent.com/23385240/43140761-1e35067a-8f5d-11e8-98e0-8322c92e48af.png)
Title of «moved to spectator mode» message should be translatable.

9. Untranslated text.
![image](https://user-images.githubusercontent.com/23385240/43140969-77622be2-8f5d-11e8-8a6d-dbf87f7b7c19.png)
There is a «Close» button if «DNA Scanner control menu» that should use translation from line **61**.

10. Move text.
![image](https://user-images.githubusercontent.com/23385240/43141137-dbf5e67a-8f5d-11e8-8303-110106595a2b.png)
Can this text (_Sort by:_) been moved to left a little bit?

11. Too small buttons.
![image](https://user-images.githubusercontent.com/23385240/43141317-4f390450-8f5e-11e8-9fa6-2dd13ed4eb72.png)
This problem appears only in Russian translation, but there is no way to «cut» this text, so can this buttons be extended?

### Steps to reproduce
Run TTT server and check all out. =)

**Comment by Satton2** [comment]
Also see this: https://github.com/Facepunch/garrysmod/pull/1518

**Comment by Satton2** [comment]
Oh I almost forgot.
12. Change this line's text.
![image](https://user-images.githubusercontent.com/23385240/43141947-e7774a3c-8f5f-11e8-882d-fb297031d52c.png)
Why is there {role}? As I know, this message appears only when Traitor kills a Detective.

**Comment by CornerPin** [comment]
Looking at the code, this also should appear when a detective kills a traitor.
https://github.com/Facepunch/garrysmod/blob/5b0c1fb660d7d169e4ff8d128691d0620a6307c7/garrysmod/gamemodes/terrortown/gamemode/player.lua#L644-L658

**Comment by Satton2** [comment]
@CornerPin Doesn't work. At least for me:
1. Traitor kills Detective:
![1](https://user-images.githubusercontent.com/23385240/43146256-862000f8-8f69-11e8-99e5-c89dad49d236.gif)
2. Detective kills Traitors:
![2](https://user-images.githubusercontent.com/23385240/43146735-6e1fa5b6-8f6a-11e8-9ae3-d9fa554aaff4.gif)

**Comment by svdm** [comment]
The message works, but by default the Detective killing the Traitor does not actually get a credit for it via that mechanism (`ttt_det_credits_traitorkill` is set to 0) so the message is not shown. If you were to change that convar it would be used. The credit award that does pop up is the one for every detective when any of them kills a traitor.

Anyway, I'll look into these hardcoded texts.

**Comment by svdm** [comment]
1. The AFK message: this message is sent from the AFK player's client, so it could only be translated to their language, but that doesn't make sense when the other players are the ones reading it. So in practice this could only be translated by changing how the message works (which I'm not going to do right now).

2. Chat muting messages: the translated versions are used for the mute indicator in the interface. The chat messages are sent from the server and therefore can't be translated without changing how they work. Given that the translated version is also visible that doesn't seem urgent.

3. and 4, 5, 6, 7, 8, 9 will all be fixed. 10 & 11 I'll test with the Russian translation and see if I can adjust those things.

**Comment by robotboy655** [comment]
TTT issues do not belong in this repo.

**Comment by Satton2** [comment]
@robotboy655 Okay. As I can see, everything was already fixed and added. But here is my question: «Where I can write about this issues?»

**Comment by Satton2** [comment]
@svdm I have found another missing string:
**Newton launcher alternative fire**:
![image](https://user-images.githubusercontent.com/23385240/46918650-0e556680-cfdd-11e8-92ab-3d1228220b09.png)
Can you add it?
