### ISSUE TITLE
PNG materials aren't rendering on the ToolGun screen, error() fixes it for this session

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#3545]
### Details
What is rendering : 

![](https://i.imgur.com/FTFNWuD.png)

What should be rendered : 

![](https://i.imgur.com/h46ZLMe.png)

I managed to fix the rendering by error()'ing inside the rendering function.

### Steps to reproduce

create a errorer.lua and put it in `garrysmod\lua\weapons\gmod_tool\stools`

``` Lua

TOOL.Category = "reeee"
TOOL.Name = "errorshower"
TOOL.Command = nil
TOOL.ConfigName = ""

function TOOL:LeftClick(trace)
	return true
end

function TOOL:RightClick(trace)
	return true
end

function TOOL:Reload(trace)
	return true
end

local tbl2 = {Material("gui/lmb.png"), Material("gui/rmb.png"), Material("gui/r.png"), Material("gui/e.png"), Material("gui/html/back"), (Material("gui/html/forward"))}

function TOOL:DrawToolScreen(width, height)
	
	surface.SetDrawColor(20, 20, 20, 255)
	surface.DrawRect(0, 0, width, height)
	surface.SetDrawColor(color_white)

	for k, v in pairs(tbl2) do
		surface.SetMaterial(v)
		surface.DrawTexturedRect(32 * (k - 1), 0, 32, 32)
	end
end
```

Adding an error() in the rendering function DO FIX THE ISSUE even after reloading the map, but the issue is back after restarting the game.

Really short video showing the issue : https://www.youtube.com/watch?v=EtMsGKZ4rIQ&feature=youtu.be

Long video showing the bug + the investigations : https://www.youtube.com/watch?v=9Wre1ArddMc

**Comment by ExtReMLapin** [comment]
Could be related to : #922

**Comment by ExtReMLapin** [comment]
Replacing the surface lib code by render code **doesn't fix** the issue

``` Lua
		render.SetMaterial( v )
		render.DrawScreenQuadEx(32 * (k - 1), 0, 32, 32)
```

**Comment by robotboy655** [comment]
Ok, turns out so this is because the .png materials are missing the `$ignorez` flag set on

**Comment by robotboy655** [comment]
Ok, turns out this is because the .png materials are missing the `$ignorez` flag, which is set on the materials you chose to show the problem doesn't apply to. ( `gui/html/*` )

The fact that you claim it doesn't happen on Linux is weird and probably needs further investigation, although I am not sure which behavior is 'correct'.

For this issue in particular, I am going to be adding `ignorez` parameter to PNG loading, as well updating the relevant wiki pages to include this information.

**Comment by ExtReMLapin** [comment]
Thank you rubat for not giving up

**Comment by garryspins** [comment]
This issue persists on rendertargets created with any depth parameter not `MATERIAL_RT_DEPTH_NONE`, added a note on the wiki about it.
