### ISSUE TITLE
Player not detected for trigger_changelevel

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3546]
trigger_changelevel or trigger_transition

Start on d1_trainstation_01, proceed into the trigger for the next map, nothing happens, except this error in the console.
> Player isn't in the transition volume trainstation_01_to_02, aborting

Tested on gmod x86 and x64, on single player.

changelevel2 map crashes the game.

Both issues do not occur on the normal branch.

**Comment by robotboy655** [comment]
Should be fixed.
