### ISSUE TITLE
SetModelScale crash when scale is too high

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3547]
Idk which models crash or what scale value is too high, but duplications are able to crash servers from it.

https://github.com/wiremod/advdupe2/pull/139

**Comment by deadmonstor** [comment]
It's because when the model hits the boundaries of the 32 bit int limit. (From what I have seen)
This will cause the physics engine to fuck around and all props from then on will fall through the map and cause the server to crash after a while.

**Comment by Kefta** [comment]
High model scale seems to just have awful performance, even when not being drawn. Setting my local player's scale to 1000 even when not being drawn (in first-person) tanks my FPS. I could not get it to crash, however.

**Comment by deadmonstor** [comment]
Place a massive scale'd prop then place a prop it will fall under the map then the server will crash

**Comment by robotboy655** [comment]
Ok I did some tests and it seems that the value of around 400-500 is where physics start to destroy server FPS (tested a few props of different size), so the serverside SetModelScale is now clamped at +-400.

Clientside SetModelScale is unaffected

I am not sure I can really do anything better considering its vphysics.

**Comment by NanoAi** [comment]
People are still crashing servers with huge props and Duplicator in 2019. 
This is how I fixed it...
```
local ENT = FindMetaTable("Entity")
local oldSetModelScale = ENT.SetModelScale

function ENT:SetModelScale( scale, deltaTime )
	oldSetModelScale( self, scale, deltaTime )

	local min, max = self:OBBMins(), self:OBBMaxs()
		if min:Distance(max) > 12000 then
			oldSetModelScale( self, 1, 0 )
			FixInvalidPhysicsObject( self )
		end
	end
end
```

**Comment by robotboy655** [comment]
Can you provide steps to reproduce?

**Comment by NanoAi** [comment]
1. Get a dupe of an already existing SetModelScaled prop. (Anything with `ModelScale = inf` or another huge number.)
2. Attempt to spawn the dupe on the server (it works better if the initial prop is quite large initially.)
3. The server will either crash, or lag quite a bit. (Getting close to the huge prop, if the server didn't crash makes performance drop even more.)
--------
I used the following code to test...
With a dupe of the following model... `models/props_c17/furniturewashingmachine001a.mdl`
Another model to try this with is... `models/props_phx/huge/evildisc_corp.mdl`

```
local dogeneric = duplicator.DoGeneric
function duplicator.DoGeneric( ent, data )
	if ( not data ) then return end
	data.ModelScale = math.huge
	print("Duplication Spawned\n---------------------")
	PrintTable(data)
	print("---------------------")
	dogeneric( ent, data )
end

local ENT = FindMetaTable("Entity")
local oldSetModelScale = ENT.SetModelScale

function ENT:SetModelScale( scale, deltaTime )
	oldSetModelScale( self, scale, deltaTime )

	local min, max = self:OBBMins(), self:OBBMaxs()
		if min:Distance(max) > 12000 then
			print("This entity is way too big!")
			oldSetModelScale( self, 1, 0 )
			FixInvalidPhysicsObject( self )
		end
	end
end
```
I can send you a video of how exactly it's done as well as a dupe file directly. Because I don't want to post that here since it may enable griefers who find this post before the issue is fixed.

**Comment by thegrb93** [comment]
Maybe you have an addon overriding duplicator.DoGeneric and doesn't contain the scale patch.

**Comment by NanoAi** [comment]
@thegrb93 I was spawning it with Advanced Duplicator 2 (latest), I'd assume it contains the patch above.

**Comment by thegrb93** [comment]
Ah. Also I assumed the clamp was in the lua code, but it seems to actually be in the SetModelScale function.

**Comment by robotboy655** [comment]
I cannot reproduce any crashes, even with the evildisc prop, but I do see performance drops with it if you spam it, and again, there's not much I can do about it.
It cannot be truly fixed because the problem is with vphysics, all I can do is just limit the duplicator's SetModelScale.

**Comment by robotboy655** [comment]
Thing is you don't even need SetModelScale for the evildisc prop to create severe lag.

**Comment by ShadowBonnieRUS** [comment]
Crashes when scaling any ragdolls.
