### ISSUE TITLE
Changing mat_hdr_level in-game causes it to crash

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3548]
Switching between mat_hdr_levels in singleplayer causes the game to crash.
Tested on gmod x86 and x64.

It might be similar to another issue I posted (https://github.com/Facepunch/garrysmod-issues/issues/3550), where the crash occurs from triggers made to load or reload the map, at least one of the crashes from this issue, I saw the loading screen for a second and then it crashed.

**Comment by robotboy655** [comment]
Duplicate of #3550
