### ISSUE TITLE
No Audio??? (Mac OS X)

### ISSUE THREAD

**Issue by Portago** [Facepunch/garrysmod-issues#355]
I Run OS X Mountain Lion And Whenever i spawn something Such As The Amnesia SNPCS It Automatically turns off my audio. I can still hear the volume sounds but nothing else. And this was ever since the game got updated.

**Comment by Portago** [comment]
This just shows you do not want to help. I am not getting on your website
again.

Goodbye.

**Comment by BytewaveMLP** [comment]
He doesn't want to help because this isn't a helpdesk. This is an **issue tracker** for **conformed issues**.

**Comment by Bo98** [comment]
Isn't even Facepunch's website lmao.

**Comment by Portago** [comment]
Ending the conversation here. There's no point in talking to anyone here.

I appreciate the explanation. Goodbye.
