### ISSUE TITLE
trigger_autosave in vehicles causes the game to crash

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3550]
The crash only occurs on gmod x64.

----------------------

Tested on singleplayer, ep2_outland_06a.
Drive the jalopy to the radio tower location to the auto save trigger, and the game crashes.

The console has much more than this on display, but this snippet should be enough.
```
(81.58) input trigger_plateau: autosave.Save()
(81.58) input trigger_plateau: looktrigger_citadel.Disable()
(81.58) input trigger_plateau: looktrigger_citadel.Disable()
(81.58) input trigger_plateau: looktrigger_citadel.Disable()
(81.58) input trigger_plateau: alyx.AddContext(06a_looking_for_radio:1)
Saving game to save\autosave.sav...
WARNING! Field m_iClassname is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_iGlobalname is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_iParent is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_iszResponseContext is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_target is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_iszDamageFilterName is using the wrong FIELD_ type!
Fix this or you'll see a crash.
WARNING! Field m_iName is using the wrong FIELD_ type!
Fix this or you'll see a crash.
```

save [savename] command can also cause the above errors, but the game doesn't crash.

**Comment by willox** [comment]
So this is 'fixed', but vphysics saving/loading is won't 64-bit builds. You'll still crash on load.

I don't think we really use this system in GMod, but if we wanted to we'd just have to replace the vphysics save/restore system with our own. I'll make another issue for that, but it's low priority.
