### ISSUE TITLE
Detail props not rendered correctly

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3551]
ep2_outland_06a

Half-Life 2: Episode 2
![20180725161256_1](https://user-images.githubusercontent.com/39219459/43209966-d9927560-9025-11e8-8aff-964b92929f01.jpg)

gmod normal and dev
On these branches, they are squared.
![20180725161202_1](https://user-images.githubusercontent.com/39219459/43210039-04680714-9026-11e8-81df-b738a1f66a61.jpg)

gmod x86-x64
On this branch, they are black and squared
![20180725160811_1](https://user-images.githubusercontent.com/39219459/43210091-26ef72f4-9026-11e8-9c0a-a1c9e4e54576.jpg)
I also noticed some artifact issues with the physgun, gravity gun glow on the detail props.
Certain detail props in the area are upside-down.

**Comment by besenyei** [comment]
Does that also have something to do with why Detail Prop Rendering is a bit more expensive?

**Comment by willox** [comment]
This is back to the old behaviour now. They definitely look nicer in ep2, but I'd treat it as a not-quite-related request.

**Comment by robotboy655** [comment]
FYI They look nicer in EP2 because it uses a different spritesheet for them. Copying over the texture to GMod will make them look identical, but It will break the HL2 ones, etc.
