### ISSUE TITLE
Linux x64 Flickering and lags

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3554]
OS: Ubuntu 18.04
Branch: x86-64

There are awful flickering and lags in x64 branch: https://streamable.com/kydtm
(Pressed W multiple times, the attack button just once)
FPS are 70-110, works fine on all other branches.
No addons installed.

**Comment by willox** [comment]
I don't recall seeing anything like this, but it's been a while since I was on the Linux x64 client. Is it TTT specific?

**Comment by besenyei** [comment]
I did find a similar flickering issue, where you ignite an npc and this causes the viewmodel to flicker.
Ignite npc_barney, and watch your viewmodel flicker, you will also notice as you move a remnant of it is also flicking in the world.

**Comment by MinIsMin** [comment]
Don't know if it's TTT specific but Sandbox is working fine.

**Comment by MinIsMin** [comment]
Seems fixed.
