### ISSUE TITLE
Player:Kick with long reasons

### ISSUE THREAD

**Issue by cannon** [Facepunch/garrysmod-issues#3559]
If you do Player:Kick with over ~512 characters, the server console will show the error "buf_AddRawText overflow". More importantly, the target won't be kicked. This could be an issue with long ban reasons (making the ban fail to function, as the server can't kick them on join) or extra wordy kick messages. I think this should be patched on the game itself as I've never seen any admin system which checks for that.

Also, if you kick with a player with >~256 but <~512 characters, it gets trimmed to ~256 before they actually see it.

**Comment by robotboy655** [comment]
Both issues fixed. ~512 is the limit now, altho its more like ~498 realistically because the command and player index also uses up the buffer.
