### ISSUE TITLE
Server can easily be crashed via game.GetWorld():Spawn()

### ISSUE THREAD

**Issue by ajloveslily14** [Facepunch/garrysmod-issues#3560]
Description is in the title really,

    lua_run game.GetWorld():Spawn()

**Comment by CornerPin** [comment]
Why would you do this

**Comment by thegrb93** [comment]
This isn't anything special. e.g. ```lua_run game.GetWorld():Fire("kill")``

**Comment by Kefta** [comment]
Official inputs and functions (not including save/datatable modification) should be stopped from crashing the game.

**Comment by ajloveslily14** [comment]
>Why would you do this

I don't know why would you player:Fire("kill") or player:Remove()

**Comment by ExtReMLapin** [comment]
i don't think player:Remove() is working anymore

**Comment by Kefta** [comment]
@ExtReMLapin I think that was his point

**Comment by RossElliman** [comment]
while true do end lads

**Comment by mcNuggets1** [comment]
Isn't game.GetWorld():Fire("kill") the same as Remove() which was fixed?

**Comment by robotboy655** [comment]
Funnily enough it doesn't crash me on gm_construct via ```lua_run game.GetWorld():Spawn()```

**Comment by siasur** [comment]
Just tried `game.GetWorld():Spawn()` and `game.GetWorld():Fire("kill")` on my dedicated test server...

Here is the result:
`lua_run game.GetWorld():Spawn()
> game.GetWorld():Spawn()...
Executing dedicated server config file server.cfg
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
Warning: Game server already logged into steam.  You need to use the sv_setsteamaccount command earlier.
lua_run game.GetWorld():Fire("kill")
> game.GetWorld():Fire("kill")...
Preventing CBaseEntity::InputKill on a player or world!`

**Comment by hiddencoders** [comment]
I guess mark it as fixed then?
