### ISSUE TITLE
Prop_physics doesn't collide with displacements

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3563]
Issue only occurs on gmod x86-x64 branch.

Tested on [zs_splinter_v2](http://142.44.142.152/fastdl/garrysmod/maps/zs_splinter_v2.bsp.bz2)
prop_physics falls through the displacement ground for some odd reason.

--------------------------

It was also posted in this thread - ([64-bit Garry's Mod](https://forum.facepunch.com/f/gmoddev/btgwr/64-bit-Garry-s-Mod/2/#postcvrjnq))

**Comment by willox** [comment]
Doesn't seem like a generic issue with vphysics and displacements, maybe it's some certain flags that are on these surfaces.

**Comment by thegrb93** [comment]
You should mention x68-x64 in the issue's title.

**Comment by Kefta** [comment]
That's what milestones and labels are for.

**Comment by willox** [comment]
Solids were being parsed out of the map with invalid CONTENTS_ flags, but the original code was never settings the flags anyway. Might be down to compiler fuckery.

I've fixed it, but maybe some other stuff is gonna suddenly become solid? Hopefully not.
