### ISSUE TITLE
Weapon:TranslateFOV zooming doesn't open func_areaportal

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3564]
Happens on all branches.

func_areaportals closed by distance do not open when zooming with Weapon:TranslateFOV.
It does when you use Player:SetFOV

-----------------------------

hl2 suit zoom, and weapon_crossbow zoom work fine.
gmod_camera suffers from this issue.

**Comment by besenyei** [comment]
Looks like it might be an issue with [Weapon:TranslateFOV](https://wiki.garrysmod.com/page/WEAPON/TranslateFOV).
[Player:setFOV](https://wiki.garrysmod.com/page/Player/SetFOV) seems to work fine on it's own.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
