### ISSUE TITLE
ENT:GetRenderMesh not working?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3567]
I've been trying to get this hook working. I even tried with the example on the wiki and no luck. The hook is called and I return the table like I should, but nothing gets rendered. http://wiki.garrysmod.com/page/ENTITY/GetRenderMesh

**Comment by robotboy655** [comment]
The example code on the page you linked works fine, and you didn't even bother posing your code.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/blob/1a817e0d137afdeb2ef7286ec71cf28cb2d84315/lua/entities/starfall_hologram/cl_init.lua

**Comment by thegrb93** [comment]
Mind you, I tried returning all sorts of different things and even pasted the example code into it, but no luck.

**Comment by thegrb93** [comment]
I'll try just the whole example alone and see.

**Comment by thegrb93** [comment]
The example alone works, but when I copy the code from the example into my entity, it doesn't work. I guess I have to strip it down until I find what's breaking it.

**Comment by thegrb93** [comment]
I found some at-a-distance code that was scaling the entity to 0 which is why it wasn't rendering. Thanks for the confirmation though, I was trying everything to try to get it to work.

**Comment by thegrb93** [comment]
I also found that it doesn't work if Material key is missing. I'll add that to wiki
