### ISSUE TITLE
Hook "PlayerSpawn" doesn't work

### ISSUE THREAD

**Issue by TheCocasio** [Facepunch/garrysmod-issues#3570]
Hi ,

This Hook isn't functional in clientside

``hook.Add("PlayerSpawn","PlayerSpawn_Example",function(ply) print("TEST") end)``

**Comment by Kefta** [comment]
It's documented as serverside only: https://wiki.garrysmod.com/page/GM/PlayerSpawn

**Comment by TheCocasio** [comment]
Okay...

**Comment by CornerPin** [comment]
For the clientside, use **player_spawn** [game event](https://wiki.garrysmod.com/page/gameevent/Listen).
