### ISSUE TITLE
Setting health on players causes hitches in movement

### ISSUE THREAD

**Issue by Mushroomguy** [Facepunch/garrysmod-issues#3572]
When setting health to any amount on a player it causes them to jolt forward (or backwards?) in a manner that resembles lag compensation when shooting weapons.

host_timescale .1
lua_run Entity(1):SetHealth(100)

This is actually visible with timescale set to 1, but for demonstration purposes .1 helps to see the problem. This is particularly annoying for regenerating health systems, as setting health every tick definetely causes jittery movement.

Tried running Entity(1):Fire("addoutput","health 100") and it causes the same issue. So maybe something to do with running inputs on player?

**Comment by meepen** [comment]
because it is supposed to be shared

**Comment by Mushroomguy** [comment]
Tried setting it on client too, same thing happens; not that I expected much since setting health on client is kind of useless and impossible to sync with when everything happens on server.

**Comment by Kefta** [comment]
Set it shared in a predicted hook.

**Comment by Mushroomguy** [comment]
Sorry, should have explained it better in the comment above. I'm setting health in SetupMove in both realms, but nothing different happens. My real question would be why does it affect player movement?

**Comment by meepen** [comment]
yeah it shouldn't affect player movement unless something is modifying player speed based on health

**Comment by ZehMatt** [comment]
Try cl_showerror 2 and see if you are getting any prediction errors.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/5449
