### ISSUE TITLE
file.Exists doesn't search in addons sound/ folder

### ISSUE THREAD

**Issue by redsigma** [Facepunch/garrysmod-issues#3573]
### Details
Basically i'm using this line:
local path = "sound/" .. string.Trim(tfolderSearchActive[j])
local exist = file.Exists( path, "DATA" )
if exist then   <---- this prints false

I tried with "./sound" and "sound\\" and neither of them worked.
Even on the wiki it says DATA it's suppose to search in mounted addons. I tried with WORKSHOP just in case but didn't worked.

**Comment by yupi2** [comment]
you should be using "GAME" not "DATA"

**Comment by redsigma** [comment]
yeah my bad i actually wrote there another line. 
It's file.Exists( "sound/" .. string.Trim(tfolderSearchActive[j]), "GAME" ) . Doesn't work with  it.
But if i think about it there's no need to search the /sound folder in addons because it will always exist there so probably this behavior is intended. 

It should be mentioned on the wiki though.

**Comment by CornerPin** [comment]
![image](https://user-images.githubusercontent.com/7669876/44020200-d607be0a-9ee9-11e8-97c6-800e25e2970a.png)

**Comment by ExtReMLapin** [comment]
yes it does, close the issue, there is real stuff to fix

**Comment by redsigma** [comment]
I actually found out file.Find( "sound/*", "WORKSHOP" ) also returns the files from GAME, so I will use it. I leave this here if somebody needs this information before i close the issue.

**Comment by ExtReMLapin** [comment]
Thank you 👍
