### ISSUE TITLE
Material Proxies are ignoring entity argument in non-engine matproxy.Call

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-issues#3574]
### Details
Internally, the **matproxy.Call** gets called from the engine, with the entity argument to decide which entity to affect, instead of affecting all entities. This works fine with materials that have the Proxies defined in them, but not when calling the proxies artificially on materials without the proxy in it. When debugging the matproxy.Call function, it shows no difference when it is called from the engine and from the way explained below. The proxy name, universal name, material and entity are all correct. However, if the call was not made from the engine (the material having the proxy specified in the vmt), all the entities with the material will get affected, exactly the same as if there was no proxy at all and the vmt values were affected globally.

The proxies get initialized properly, and unless I am missing something, I don't understand why this does not work as it should.

### Steps to reproduce
Spawn two (or more) blue barrels from HL2 (models/props_borealis/bluebarrel001.mdl) and set the color of one of them with the Color tool (the Red value determines the cloak factor), run the following code, and the barrels will look all the same, but they should not as the entity argument was passed, but it seems to not do anything. All the entities seem to share the material from the latest spawned entity.
```
matproxy.Add( {
	name = "CloakTestProxy",
	init = function( self, mat, values )
	end,
	bind = function( self, mat, ent )
		print(self, mat, ent)
		local col = ent:GetColor() or Color(0,0,0)
		
		local val = 1 - (col.r/255)
		
		mat:SetInt("$cloakpassenabled", 1)
		mat:SetFloat("$cloakfactor", val )
		mat:SetFloat("$refractamount", 1)
	end
} )

local cloakedMatCache = {} // to avoid calling Material() every frame

local function initproxy(proxy, mat)
	if !cloakedMatCache[mat] then
		cloakedMatCache[mat] = Material(mat)
	end
	matproxy.Init(proxy, proxy..mat, cloakedMatCache[mat], {})
end

local function callproxy(proxy, mat, ent)
	matproxy.Call(proxy..mat, cloakedMatCache[mat], ent)
end


initproxy("CloakTestProxy", "models/props_borealis/bluebarrel001")

hook.Add("PostDrawTranslucentRenderables", "MatProxyTest", function()
	for k, v in pairs(ents.FindByClass("prop_physics")) do
		if v:GetModel() == "models/props_borealis/bluebarrel001.mdl" then
			callproxy("CloakTestProxy", "models/props_borealis/bluebarrel001", v)
		end
	end
end)
```

**Comment by robotboy655** [comment]
It will never work if you call ```matproxy.bind``` manually, because all you do is equivalent of  ```Material( mat ):SetFloat( "$refractamount", 1 )```

Your materials are not instanced, which I expect the materials in ```matproxy.bind``` are when it is called from the engine.

Basically there is no bug here.

**Comment by Gmod4phun** [comment]
That is a shame
