### ISSUE TITLE
Entity.FireBullets Tracer ignores specified trace

### ISSUE THREAD

**Issue by Arkten** [Facepunch/garrysmod-issues#3576]
### Details
**Garry's Mod Version:** 2018.08.14
**Lua Version:** 5.1
**Operating System:** Linux 64-bit

The tracer generated by Entity.FireBullets completely ignores the source position of the trace specified in the bullet structure and and always uses Player.GetShootPos as the source position and then moves to the specified end position of the trace. The trace itself is performed correctly.

### Steps to reproduce
Put this into your SWEP:ShootBullet() function
```Lua
self:GetOwner():FireBullets({
	Num = 1,
	Src = Vector(0, 0, 0),
	Dir = self:GetOwner():GetAimVector(),
	Tracer = 1
})
```
You should still see the tracer originating from the barrel of your gun and not from position (0/0/0) as specified.

**NOTE: You will need to shoot a certain distance to see the tracer at all!**

**Comment by robotboy655** [comment]
The default tracers are coded to automatically attach to the attachment 1 of your weapon models, it is not a bug. You can code your own custom tracer effect that will originate from whenever you want.
