### ISSUE TITLE
Misplaced HL2 weapon sprites in third-person

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3580]
![](https://i.imgur.com/5PveAoO.png)
Stunstick

![](https://i.imgur.com/NMO6MHh.png)
Grav gun

![](https://i.imgur.com/oHDLa7t.png)
RPG

![](https://i.imgur.com/wl48Cwz.png)
Crossbow

Tested with the thirdperson command on a listen server using the dev branch.

**Comment by mcNuggets1** [comment]
Emitting bullets is bugged too for hl2 weapons.

**Comment by robotboy655** [comment]
The stunstick and RPG should be fixed in Dev.

**Comment by robotboy655** [comment]
Crossbow and gravity gun are now fixed as well.
