### ISSUE TITLE
Spawnicons cache error model for missing models

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#3584]
### Details
[SpawnIcons](http://wiki.garrysmod.com/page/Category:SpawnIcon) cache an image of the error model when the model does not exist.

I don't know that this is necessarily a bug but there's no reason it shouldn't just render a static missing model image without creating and caching a new one.

### Steps to reproduce
- Create a [SpawnIcon](http://wiki.garrysmod.com/page/Category:SpawnIcon) for a model that does not exist
-  Observe a cached image of the error model

**Comment by robotboy655** [comment]
I wouldn't consider this a bug, otherwise it'd regenerate the spawnicons with missing models every session.

**Comment by aStonedPenguin** [comment]
It shouldn't generate or cache anything for missing models, it should just render an already generated image for them all.

**Comment by robotboy655** [comment]
I agree with you, in an ideal world it should work like that, but it will double the loading times for spawnicons/spawnmenu if we poll whether the model exists or not every time a spawn icon is loaded.

**Comment by Kefta** [comment]
Can it progressively check if missing models exist once during gameplay?

**Comment by robotboy655** [comment]
The fallback is handled by the engine model loading, but I did find a way to detect it.
