### ISSUE TITLE
Camera Attachment still a problem four years later?

### ISSUE THREAD

**Issue by Vented** [Facepunch/garrysmod-issues#3585]
This was reported 4 years ago and was supposed to be "looked at"?
https://github.com/Facepunch/garrysmod-issues/issues/1255

It used to work back then too but an update broke it, hence why it was reported originally. Can you at least give an exact answer for it not working instead of just not responding and acting like you didn't see it or something? I don't wanna be rude but a 4 year wait time is pretty long.

Also, these people had to find a workaround to get it to work and that might not even work either(?) on: https://gmod.facepunch.com/f/gmoddev/btatk/How-to-attach-first-person-camera-to-a-bone/1/

If this has been answered already and I just haven't seen it then I apologize for being a douchebag.

**Comment by robotboy655** [comment]
Dont make duplicate issues

**Comment by Vented** [comment]
Then at least fucking fix it?

**Comment by Vented** [comment]
Listen bud, if you can't fix the problem then admit to it instead of trying to hide the issue away from sight lmao.

**Comment by Kefta** [comment]
How is he hiding it? The issue has the same visibility as any other on the issue tracker.

**Comment by Vented** [comment]
People who look at this github don't view the closed category most of the time.
In fact, who cares about that, the real question is why this hasn't been fixed yet.
