### ISSUE TITLE
Detail props more expensive in gmod x64

### ISSUE THREAD

**Issue by besenyei** [Facepunch/garrysmod-issues#3589]
ep2_outland_06a

gmod x86
![20180901100113_1](https://user-images.githubusercontent.com/39219459/44944433-6a1db480-adce-11e8-81ab-b7c43537cc91.jpg)

gmod x64
![20180901100149_1](https://user-images.githubusercontent.com/39219459/44944434-6e49d200-adce-11e8-9db7-bab1656cddb6.jpg)

--------------------------

[zs_swimmingpool_v7
](http://142.44.142.152/fastdl/garrysmod/maps/zs_swimming_pool_v7.bsp.bz2)

gmod x86
![20180901194828_1](https://user-images.githubusercontent.com/39219459/44949001-6fa3ea80-ae20-11e8-96a1-8ce920dab3a3.jpg)

gmod x64
![20180901194719_1](https://user-images.githubusercontent.com/39219459/44949002-76caf880-ae20-11e8-96df-4eee8c47cbc1.jpg)

-------------------------

Some detail props do not render on gmod x64.

**Comment by willox** [comment]
These screenshots are both from the new branch, right?

**Comment by besenyei** [comment]
Yes.

**Comment by besenyei** [comment]
This post is relevant: https://forum.facepunch.com/f/gmoddev/btgwr/64-bit-Garry-s-Mod/4/#postcvtrxq
It does not however explain the issue of some detail props not rendering.
