### ISSUE TITLE
render.BrushMaterialOverride is broken and doesn't do anything

### ISSUE THREAD

**Issue by somethingwild** [Facepunch/garrysmod-issues#3591]
It's suppose to override brush material in the upcoming render operations, but as it's broken, it doesn't do that. Would it be possible to get it fixed?

**Comment by somethingwild** [comment]
@ExtReMLapin It's already known that it's broken, it even says so in the wiki.  

https://forum.facepunch.com/f/gmoddev/liju/render-BrushMaterialOverride-is-it-broken-or-am-I-using-it-wrong/1/

https://wiki.garrysmod.com/page/render/BrushMaterialOverride

I don't really see how testing it would do anything.

**Comment by willox** [comment]
What hook do you expect to use this in?

**Comment by somethingwild** [comment]
I wanted to do it in RenderScene, specifically for rendering out a 16-bit depth buffer.

**Comment by willox** [comment]
So this is related to your SetShader issue. Were you expecting this to override materials for all surfaces on the map, not only brush entities?

**Comment by somethingwild** [comment]
Yeah exactly. I wanted to have a render pass which applies a single material with a specific shader to every object, every brush, every surface including world geometry.  But without SetShader or render.BrushMaterialOverride, it's just not possible.

**Comment by willox** [comment]
I think render.BrushmaterialOverride isn't what you want anyway. Nor is render.MaterialOverride as it is a pretty misleading function and only really works for entities.

Wouldn't a function that overrides the material used for every single draw call work better for you?

**Comment by somethingwild** [comment]
I think a function like that would really be useful and appropriate. If you can do that, I would appreciate it a lot.

**Comment by willox** [comment]
Should be on the dev branch later today. It may not be perfect.

```lua
local X = Material( "CONCRETE/CONCRETEFLOOR026A" )
hook.Add( "RenderScene", "", function() render.WorldMaterialOverride( X ) end )
```

![](https://files.facepunch.com/willox/2018-09-05/XSrYY8eB.jpg)
