### ISSUE TITLE
flashlights mute current weapon sound

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3593]
### Details
The sound of the flashlight turning it off or on, mutes any other sound bound to your weapon.
It's just odd and should be changed.

### Steps to reproduce
Press flashlight button repeatledly while shooting a hl2 weapon or reloading or whatever

use weapon:EmitSound and then turn on flashlight, the EmitSound object will be removed or muted immediately.

**Comment by robotboy655** [comment]
There you go, another non issue fixed.

**Comment by mcNuggets1** [comment]
I don't wanna be rude, but this actually was a pretty big deal for me.

When emitting long ass sounds, you could just mute them, even for other players.
The Keypad Cracker for example could be completely muted and therefore you only hear clicking flashlights.

But thanks for fixing it anyways <3
