### ISSUE TITLE
Error which effictively says nothing, like the old PhysicsCollide error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3605]
### Details
My console sometimes says there is something fishy with HitboxSet, but it doesn't tell where, it just says some entity has a bad hitbox (spamming sometimes)

### Steps to reproduce
-

**Comment by robotboy655** [comment]
And you didn't even have the common sense to screenshot the error so we can try to find what causes it

**Comment by mcNuggets1** [comment]
[UH-OH!] Invalid HitboxSet on something.

Also there is this non informative error:
Garry: Tried to activate constraint in physics callback! This could cause crashes! Ignoring!

**Comment by robotboy655** [comment]
Ok I see the warning and where its coming from, unfortunately there's not much I can do to improve the information it provides as the warning is not attached to an entity.

I have made ```SetHitboxSet``` not produce it when used with bad strings.

I don't see whats "non informative" about the second warning, its pretty self explanatory.

**Comment by mcNuggets1** [comment]
It's not referencing the entity which make the error happen, like the other physics callback error.
