### ISSUE TITLE
Some effects don't work in multiplayer.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3606]
Because of this https://github.com/ValveSoftware/source-sdk-2013/issues/465

**Comment by robotboy655** [comment]
Can you actually reproduce this? I have tried spawning a gunship on gm_construct on a dedicated server in the mirror room and the muzzleflash does work as expected.

**Comment by ZehMatt** [comment]
Yeah you are too close on 0,0,0 which is nearly the center of gm_construct. Try some maps where it has complex geometry and far away from 0,0,0

**Comment by ZehMatt** [comment]
Just look at how DispatchEffect is implemented, when m_vecOrigin is not assigned PAS will not work, simple as that. I even took the effort to find every case where its not assigned ;(
