### ISSUE TITLE
GMod player name systems bug out when deleting invisible "entities" at coordinates 0,0,0

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-issues#3609]
### Details
While i was messing around in the game, i discovered that there were some "invisible" entities in the map which persist across sessions, and exist at coords 0,0,0. When deleting them with a area remover, they seem to glitch out the player name system in gmod.
Checking coords 0,0,0 with tools which highlight entities to be deleted:
![image](https://user-images.githubusercontent.com/42521608/45774035-a1a4b180-bc54-11e8-876c-2d2a6c45ff39.png)

Upon deleting them, after a second the names in chat become blank, and each time i press tab to see names, the console gets spammed with this:
] 
: why
: goddamnit

[ERROR] gamemodes/base/gamemode/cl_scoreboard.lua:97: bad argument #1 to 'SetText' (string expected, got nil)
1. SetText - [C]:-1
2. unknown - gamemodes/base/gamemode/cl_scoreboard.lua:97

and this pops up:
https://i.imgur.com/j2OlA3Z.jpg

This is the chat (some of the messages are mine and some are my friend's messages, he was the one pissed off about something)
https://i.imgur.com/S2azbPV.jpg

### Steps to reproduce
Grab a prop, and use some way of tracking what position it's currently at (preferably wire gps)
When you reach position 0,0,0, grab out a tool that highlights nearby entities (something like the Admin Remover tool)
If a bunch of entities appear in one place, delete them 
After a second, chat names in chat will go blank and pressing tab to check on names shows console errors and blank names

**Comment by Kefta** [comment]
It's probably because you're deleting the gamerules and player manager - I'd imagine there's many more issues linked to those being removed. I don't believe this is a bug.

**Comment by robotboy655** [comment]
It's because you are removing ```player_manager``` which is used for some of the player data.

**Comment by mcNuggets1** [comment]
Maybe prevent deleting them?
