### ISSUE TITLE
Mixed use of non-developer and developer messages in network graph

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3614]
[Here](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/ai_networkmanager.cpp#L639-L664). The ``Warning`` and ``DevMsg``s should both be changed to ``DevWarning``s for style consistency. And perhaps only prepend commas after the first list item to prevent dangling comma.

Without ``developer`` enabled:
![](https://i.imgur.com/pBlovKh.png)

With ``developer`` enabled (dangling comma example):
![](https://i.imgur.com/W9ykQnE.png)

**Comment by robotboy655** [comment]
Really scraping the bottom of the barrel on this one, huh?

**Comment by Kefta** [comment]
Anything to get you more ferraris Rubat
