### ISSUE TITLE
Clientside player muting is broken with >32 players

### ISSUE THREAD

**Issue by cannon** [Facepunch/garrysmod-issues#3616]
### Details
Tell us exactly what happens, every single detail that you can think of

When you do Player:SetMuted, if the player's connection ID (entity ID) is above 32, it won't work. However, if you mute the player with entity ID (id-1)%32 +1 (repeat subtract 32 until the id is <= 32) then it will mute the initial target. For example muting player with connection id 5 will mute the players with id 5, 37, 69, and 101. Muting any player above connection id 32 does nothing.

### Steps to reproduce
Tell us how to reproduce the problem, step by step

Get a server with a lot of people, try muting some. (This only is an issue if the gamemode uses the clientside SetMuted)

**Comment by CaskoChan** [comment]
This needs to be fixed asap

**Comment by Raox2** [comment]
Would be nice to see this fixed. Well documented bug report, by the way.

**Comment by Dimantio** [comment]
I've been dealing with this issue for years fix please.

**Comment by Scotty10** [comment]
Would be awesome to see this fixed

**Comment by besenyei** [comment]
Would like to see this issue looked into, it's always been an annoyance.

**Comment by willox** [comment]
This should be fixed on our dev branches now. It's client-side only, so no need for servers to have the fix.

The bug is here: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/voice_status.cpp#L381
