### ISSUE TITLE
ENT:Touch is always called in singleplayer and listen servers but not on dedicated servers

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3619]
### Details
ENT:Touch is always called even with not setting a entity to trigger in listen servers, but on dedicated servers, you actually have to in order for it to work.

### Steps to reproduce
Don't set trigger upon a entity with MOVETYPE_FLYGRAVITY and it still will react to ENT:Touch, but not on dedi servers.

As seen in this addon:
https://steamcommunity.com/sharedfiles/filedetails/?id=1323286207&searchtext=Hunting+Bow

**Comment by robotboy655** [comment]
I have just tested it, and the Touch hooks are definitely called consistently across all three for me.

The hooks will be called if only 1 of the 2 entities in a collision have the ```FSOLID_TRIGGER``` ```(Entity.GetSolidFlags)``` set. If both have the flag set, the hooks will not be called.

You can see the full logic for this here:
https://github.com/pmrowla/hl2sdk-csgo/blob/master/game/shared/physics_main_shared.cpp#L939-L1033

**Comment by mcNuggets1** [comment]
I may not fully understand the issue, though In the SWEP I sent you, you can see the issue clearly when shooting an arrow.

On dedicated servers it will get stuck in the air, on listen servers it will fly like it is supposed to.
SetTrigger(true) fixes the issue on dedicated servers, but doesn't change anything about the usage on the listen server.

**Comment by robotboy655** [comment]
I just tested the SWEP on a self-hosted dedicated server, and the arrows do not get stuck in the air. (And there are no SetTrigger calls in the entire addon so there are no workarounds by the author as far as I can tell)

Maybe something else on your end is causing the problem? Closing this until you can reproduce the problem with just that 1 addon or whatever other addons/code.
