### ISSUE TITLE
DMenuBar doesnt' work properly with DSubMenus

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3620]
### Details
https://i.imgur.com/bP3Tjde.png
This occurs to happen.
There aren't any options to select after you opened the derma menu once and then closed and reopened it without closing the DFrame once.

With adding another option to the dmenubar the submenus now arent working anymore at all.

### Steps to reproduce
first test code:
https://pastebin.com/dv15dSbk

second test code:
https://pastebin.com/cFG8hRWS

**Comment by robotboy655** [comment]
You will want to call ```dmenu:SetDeleteSelf( false )``` on any new submenus (it is not done automatically because the menus are meant to be auto-destroyed when used via ```DermaMenu()```), but I see the actual problem and will get it fixed.

I will document this on the wiki.
