### ISSUE TITLE
Could it be fixed util.SpriteTrail can crash the game?

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3621]
### Details
Could it be fixed that util.SpriteTrail with invalid materials crash the game?

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/46250163-ae3bbd80-c43d-11e8-9bce-9d07a5ffb015.png)

Could it be fixed that you never post steps to reproduce? Like post code or at least materials that cause the problem, ANYTHING?

**Comment by mcNuggets1** [comment]
It's documented in the wiki, why should I add steps to reproduce upon that?

https://i.imgur.com/qJ9TrIj.png

**Comment by thegrb93** [comment]
I mean, step to reproduce: use invalid material with util.SpriteTrail. I don't see why he has to go any further into detail.

**Comment by robotboy655** [comment]
Fixed
