### ISSUE TITLE
game.AddAmmoType added types do not sync to client correctly on 64-bit branch

### ISSUE THREAD

**Issue by Raox2** [Facepunch/garrysmod-issues#3623]
### Details
game.AddAmmoType does not sync ammo values to client correctly on 64-bit branch. It seems the client cannot detect a user having ownership of ammo on the server, but anything purely serverside that uses the ammo operates fine with it. Essentially, gaining ammo from a custom type doesn't sync to the client, meaning the client believes it has 0 ammo of said type, which is not the truth.

### Steps to reproduce
Unfortunately, I can't consistently replicate it. Mostly happens on multiplayer and requires a Garry's Mod restart to attempt to fix, since it usually persists the entire session.

**Comment by robotboy655** [comment]
Are you calling the function shared? Because you are supposed to.

**Comment by Raox2** [comment]
Yes, it is shared. This never happens to anyone using a standard branch.

**Comment by TheMostUpset** [comment]
Something similar also happens if client is not using dev branch, but server does (or vice-versa)
Haven't tested with x64 one, but I guess it is the same issue.
I think it won't be an issue after main branch update.

**Comment by robotboy655** [comment]
This should no longer be a problem.
