### ISSUE TITLE
Can't hear a sound with level 0 everywhere in multiplayer

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3624]
EmitSound with soundLevel set to 0 makes sound able to hear everywhere, but only in singleplayer. In MP, when player is far away of sound position, the sound can't be heard at all. This makes me unable to restore Black Mesa announcement VOX system because sounds need to be heard on the whole map. The solution is to use net.Broadcast() and play it clientside, but I use EmitSentence and it doesn't work clientside.
Is anything can be fixed? Make sounds with soundlevel 0 able to hear everywhere in multiplayer or make EmitSentence work clientside?

**Comment by end360** [comment]
I'm not an expert but this probably has to do with the PVS or PAS, which would explain why broadcasting it works.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2793

**Comment by robotboy655** [comment]
EmitSentence was fixed to work clientside
