### ISSUE TITLE
GetVehicleViewPosition crashes when used on an empty prop_vehicle_prisoner_pod

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3627]
It also returns garbage data for the 3rd return for all vehicles, even when a passenger is in it. Tested in local multiplayer.

Dump: https://drive.google.com/uc?id=137qCDuOZEXAjYK1Ha9WgRwKBh_DpKPa-

**Comment by robotboy655** [comment]
Fixed.

The garbage output was replaced with default values
