### ISSUE TITLE
SpawnIcon/ModelImage bodygroups are not saved correctly

### ISSUE THREAD

**Issue by impulsh** [Facepunch/garrysmod-issues#3628]
Setting the bodygroups on a SpawnIcon or ModelImage results in some odd behaviour. For some models - like `models/zombies/classic.mdl` - it will not render the bodygroup, but it will save the correct image at `materials/spawnicons/models/zombies/classic_010000000.png`.

For other models - like the citizen models found in https://steamcommunity.com/sharedfiles/filedetails/?id=677916509 - the default model will be rendered and saved correctly at `materials/spawnicons/models/zelpa/clockwork/male_01.png`. Applying a bodygroup will save it at `materials/spawnicons/models/zelpa/clockwork/male_01_000001000.png` as you'd expect, however it will be saved without the bodygroups being rendered, making it appear identical to the default `male_01.png` file.

**Comment by impulsh** [comment]
This issue applies to the icon editor as well since it just uses ModelImage anyway. Model, skin, and bodygroups are being set with http://wiki.garrysmod.com/page/Panel/SetModel with standard arguments `panel:SetModel("models/zelpa/clockwork/male_01.mdl", 0, "000001000")`. It will render correctly, but the saved file will not render the bodygroups at all - which means that it will be rendered incorrectly since it wasn't saved to the spawnicons cache properly.

**Comment by robotboy655** [comment]
I see, should be fixed in Dev and in the next update.
