### ISSUE TITLE
Malformed JSON generated with 0/0 as a value

### ISSUE THREAD

**Issue by TrixterTheTux** [Facepunch/garrysmod-issues#3629]
### Details
util.TableToJSON produces malformed JSON if you pass 0/0 as a value into it.

### Steps to reproduce
Run ``lua_run print(util.TableToJSON({test = 0/0}))`` in the console.
![hi](https://maho.is-a-good-waifu.com/83f07e.png)

**Comment by Kefta** [comment]
Both nan and inf are ignored by util.TableToJSON now.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3561
