### ISSUE TITLE
SetModelScale always sets to -400 now

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3631]
Do Entity:SetModelScale(1) to anything serverside, you'll get game crash or this
![20181010114009_1](https://user-images.githubusercontent.com/7527872/46717460-8b9d7600-cc81-11e8-8afb-f1ffadccec26.jpg)

**Comment by robotboy655** [comment]
I have never managed to make it crash from SetModelScale.

I will get this fixed ASAP
