### ISSUE TITLE
Discord + 1080ti + Garrysmod = Crash to desktop

### ISSUE THREAD

**Issue by kulcris** [Facepunch/garrysmod-issues#3632]
### Details
I upgraded my video card to a 1080ti, when starting gmod after this it would crash with this crash message

`
Dump Summary
------------
Dump File:	hl2_180821_crash_2018_10_11T15_36_43C0.mdmp : E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\hl2_180821_crash_2018_10_11T15_36_43C0.mdmp
Last Write Time:	10/11/2018 10:36:44 AM
Process Name:	hl2.exe : E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\hl2.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.17134
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
hl2.exe	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\hl2.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.2.17134.254
kernel32.dll	C:\Windows\System32\kernel32.dll	6.2.17134.1
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.2.17134.319
apphelp.dll	C:\Windows\System32\apphelp.dll	6.2.17134.1
user32.dll	C:\Windows\System32\user32.dll	6.2.17134.319
win32u.dll	C:\Windows\System32\win32u.dll	6.2.17134.1
gdi32.dll	C:\Windows\System32\gdi32.dll	6.2.17134.285
gdi32full.dll	C:\Windows\System32\gdi32full.dll	6.2.17134.345
msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	6.2.17134.1
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	6.2.17134.319
advapi32.dll	C:\Windows\System32\advapi32.dll	6.2.17134.319
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.17134.1
sechost.dll	C:\Windows\System32\sechost.dll	6.2.17134.319
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.2.17134.112
sspicli.dll	C:\Windows\System32\sspicli.dll	6.2.17134.1
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.2.17134.1
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.2.17134.345
ole32.dll	C:\Windows\System32\ole32.dll	6.2.17134.137
combase.dll	C:\Windows\System32\combase.dll	6.2.17134.112
psapi.dll	C:\Windows\System32\psapi.dll	6.2.17134.1
winmm.dll	C:\Windows\System32\winmm.dll	6.2.17134.1
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.2.17134.1
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.2.17134.1
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.2.17134.1
imm32.dll	C:\Windows\System32\imm32.dll	6.2.17134.1
gameoverlayrenderer.dll	C:\Program Files (x86)\Steam\gameoverlayrenderer.dll	4.70.72.78
launcher.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\launcher.dll	1.0.0.1
shell32.dll	C:\Windows\System32\shell32.dll	6.2.17134.320
SHCore.dll	C:\Windows\System32\SHCore.dll	6.2.17134.112
windows.storage.dll	C:\Windows\System32\windows.storage.dll	6.2.17134.345
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.2.17134.1
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.2.17134.112
profapi.dll	C:\Windows\System32\profapi.dll	6.2.17134.1
powrprof.dll	C:\Windows\System32\powrprof.dll	6.2.17134.1
fltLib.dll	C:\Windows\System32\fltLib.dll	6.2.17134.1
wsock32.dll	C:\Windows\System32\wsock32.dll	6.2.17134.1
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.2.17134.1
steam_api.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\steam_api.dll	3.62.82.82
vstdlib.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\vstdlib.dll	1.0.0.1
tier0.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\tier0.dll	1.0.0.1
filesystem_stdio.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\filesystem_stdio.dll	1.0.0.1
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.2.17134.1
engine.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\engine.dll	1.0.0.1
wininet.dll	C:\Windows\System32\wininet.dll	11.0.17134.345
inputsystem.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\inputsystem.dll	1.0.0.1
materialsystem.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\materialsystem.dll	1.0.0.1
datacache.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\datacache.dll	1.0.0.1
studiorender.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\studiorender.dll	1.0.0.1
vphysics.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\vphysics.dll	0.0.0.0
vguimatsurface.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\vguimatsurface.dll	1.0.0.1
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.2.17134.48
vgui2.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\vgui2.dll	1.0.0.1
shaderapidx9.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\shaderapidx9.dll	1.0.0.1
d3d9.dll	C:\Windows\System32\d3d9.dll	6.2.17134.81
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.2.17134.1
D3DX9_40.dll	C:\Windows\System32\D3DX9_40.dll	9.24.950.2656
nvldumd.dll	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_54bd1f10ac116cd5\nvldumd.dll	25.21.14.1616
version.dll	C:\Windows\System32\version.dll	6.2.17134.1
crypt32.dll	C:\Windows\System32\crypt32.dll	6.2.17134.1
msasn1.dll	C:\Windows\System32\msasn1.dll	6.2.17134.1
wintrust.dll	C:\Windows\System32\wintrust.dll	6.2.17134.81
imagehlp.dll	C:\Windows\System32\imagehlp.dll	6.2.17134.1
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.2.17134.1
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.2.17134.254
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.2.17134.112
nvd3dum.dll	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_54bd1f10ac116cd5\nvd3dum.dll	25.21.14.1616
steamclient.dll	C:\Program Files (x86)\Steam\steamclient.dll	4.70.72.78
setupapi.dll	C:\Windows\System32\setupapi.dll	6.2.17134.1
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.2.17134.1
tier0_s.dll	C:\Program Files (x86)\Steam\tier0_s.dll	4.70.72.78
vstdlib_s.dll	C:\Program Files (x86)\Steam\vstdlib_s.dll	4.70.72.78
mswsock.dll	C:\Windows\System32\mswsock.dll	6.2.17134.1
secur32.dll	C:\Windows\System32\secur32.dll	6.2.17134.1
Steam.dll	C:\Program Files (x86)\Steam\Steam.dll	0.0.0.0
Steam2.dll	C:\Program Files (x86)\Steam\Steam2.dll	2.0.2117.156
NapiNSP.dll	C:\Windows\System32\NapiNSP.dll	6.2.17134.1
pnrpnsp.dll	C:\Windows\System32\pnrpnsp.dll	6.2.17134.1
nlaapi.dll	C:\Windows\System32\nlaapi.dll	6.2.17134.1
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.2.17134.165
nsi.dll	C:\Windows\System32\nsi.dll	6.2.17134.1
winrnr.dll	C:\Windows\System32\winrnr.dll	6.2.17134.1
wshbth.dll	C:\Windows\System32\wshbth.dll	6.2.17134.1
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.2.17134.1
rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.2.17134.1
dbgcore.dll	C:\Windows\System32\dbgcore.dll	6.2.17134.1
CSERHelper.dll	C:\Program Files (x86)\Steam\CSERHelper.dll	4.50.0.0
XInput1_3.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\XInput1_3.dll	9.15.779.0
devobj.dll	C:\Windows\System32\devobj.dll	6.2.17134.1
dinput.dll	C:\Windows\System32\dinput.dll	6.2.17134.254
inputhost.dll	C:\Windows\System32\inputhost.dll	0.0.0.0
WinTypes.dll	C:\Windows\System32\WinTypes.dll	6.2.17134.112
CoreUIComponents.dll	C:\Windows\System32\CoreUIComponents.dll	6.2.17134.112
CoreMessaging.dll	C:\Windows\System32\CoreMessaging.dll	6.2.17134.345
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.2.17134.1
hid.dll	C:\Windows\System32\hid.dll	6.2.17134.1
stdshader_dbg.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\stdshader_dbg.dll	1.0.0.1
stdshader_dx6.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\stdshader_dx6.dll	1.0.0.1
stdshader_dx7.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\stdshader_dx7.dll	1.0.0.1
stdshader_dx8.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\stdshader_dx8.dll	1.0.0.1
stdshader_dx9.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\stdshader_dx9.dll	1.0.0.1
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
wbemprox.dll	C:\Windows\System32\wbem\wbemprox.dll	6.2.17134.1
wbemcomn.dll	C:\Windows\System32\wbemcomn.dll	6.2.17134.1
wbemsvc.dll	C:\Windows\System32\wbem\wbemsvc.dll	6.2.17134.1
fastprox.dll	C:\Windows\System32\wbem\fastprox.dll	6.2.17134.1
game_shader_generic_garrysmod.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\game_shader_generic_garrysmod.dll	1.0.0.1
unicode.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\unicode.dll	0.0.0.0
msctf.dll	C:\Windows\System32\msctf.dll	6.2.17134.319
TextInputFramework.dll	C:\Windows\System32\TextInputFramework.dll	6.2.17134.191
DiscordHook.dll	C:\Users\kulcr\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook.dll	0.0.0.0
userenv.dll	C:\Windows\System32\userenv.dll	6.2.17134.1
nvSCPAPI.dll	C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI.dll	7.17.14.1616
nvspcap.dll	C:\Windows\System32\nvspcap.dll	3.15.0.164
gpapi.dll	C:\Windows\System32\gpapi.dll	6.2.17134.1
cryptnet.dll	C:\Windows\System32\cryptnet.dll	6.2.17134.1
dcomp.dll	C:\Windows\System32\dcomp.dll	6.2.17134.1
dxgi.dll	C:\Windows\System32\dxgi.dll	6.2.17134.112
D3DCompiler_47.dll	C:\Windows\System32\D3DCompiler_47.dll	6.2.17134.1
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.2.17134.1
propsys.dll	C:\Windows\System32\propsys.dll	7.0.17134.112
AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.2.17134.137
avrt.dll	C:\Windows\System32\avrt.dll	6.2.17134.1
Windows.UI.dll	C:\Windows\System32\Windows.UI.dll	6.2.17134.1
client.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\client.dll	1.0.0.1
server.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\server.dll	1.0.0.1
soundemittersystem.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\soundemittersystem.dll	1.0.0.1
scenefilecache.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\scenefilecache.dll	1.0.0.1
lua_shared.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\lua_shared.dll	1.0.0.1
menusystem.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\menusystem.dll	1.0.0.1
resources.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\resources.dll	1.0.0.1
gmod_audio.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\gmod_audio.dll	1.0.0.1
bass.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\bass.dll	2.4.13.11
msacm32.dll	C:\Windows\System32\msacm32.dll	6.2.17134.1
html_chromium.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\garrysmod\bin\html_chromium.dll	1.0.0.1
libcef.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\libcef.dll	3.3325.1746.0
comdlg32.dll	C:\Windows\System32\comdlg32.dll	6.2.17134.1
comctl32.dll	C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.345_none_40ff7c964511edcf\comctl32.dll	5.82.17134.48
netapi32.dll	C:\Windows\System32\netapi32.dll	6.2.17134.1
oleacc.dll	C:\Windows\System32\oleacc.dll	7.2.17134.1
usp10.dll	C:\Windows\System32\usp10.dll	6.2.17134.1
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	6.2.17134.1
ncrypt.dll	C:\Windows\System32\ncrypt.dll	6.2.17134.1
urlmon.dll	C:\Windows\System32\urlmon.dll	11.0.17134.345
winhttp.dll	C:\Windows\System32\winhttp.dll	6.2.17134.137
DWrite.dll	C:\Windows\System32\DWrite.dll	6.2.17134.1
d3d11.dll	C:\Windows\System32\d3d11.dll	6.2.17134.112
wtsapi32.dll	C:\Windows\System32\wtsapi32.dll	6.2.17134.1
winspool.drv	C:\Windows\System32\winspool.drv	6.2.17134.319
dxva2.dll	C:\Windows\System32\dxva2.dll	6.2.17134.1
iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.17134.320
ntasn1.dll	C:\Windows\System32\ntasn1.dll	6.2.17134.1
cryptui.dll	C:\Windows\System32\cryptui.dll	6.2.17134.319
credui.dll	C:\Windows\System32\credui.dll	6.2.17134.1
chrome_elf.dll	E:\LargeGames\SteamLibrary\steamapps\common\GarrysMod\bin\chrome_elf.dll	65.0.3325.146
netutils.dll	C:\Windows\System32\netutils.dll	6.2.17134.1
samcli.dll	C:\Windows\System32\samcli.dll	6.2.17134.1
GameUI.dll	e:\largegames\steamlibrary\steamapps\common\garrysmod\bin\GameUI.dll	1.0.0.1
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	6.2.17134.1
mscms.dll	C:\Windows\System32\mscms.dll	6.2.17134.1
ColorAdapterClient.dll	C:\Windows\System32\ColorAdapterClient.dll	6.2.17134.1
icm32.dll	C:\Windows\System32\icm32.dll	6.2.17134.1
DiscordHook.dll	C:\Users\kulcr\AppData\Roaming\discordcanary\0.0.215\modules\discord_hook\16\DiscordHook.dll	0.0.0.0
dsound.dll	C:\Windows\System32\dsound.dll	6.2.17134.1
`
### Steps to reproduce
have discordcanary  (beta version of discord), start garrysmod. 
I do not know if the fact that i upgraded my video card has anything to do with it or if it was an update to discord that causes it.

I was able to start garrysmod by closing discord

I have also reported this to discord.

**Comment by mcNuggets1** [comment]
I have a 1080 ti too and for me it works fine also mit discord installed.

**Comment by FarukGamer** [comment]
Revert back to normal Discord ( Stable ) and try it again.

**Comment by kulcris** [comment]
Seems it was an issue with running 2 discord clients at once, with only one running the issue does not happen
