### ISSUE TITLE
SWEP.ViewModelFlip makes the viewmodel immovable

### ISSUE THREAD

**Issue by ZenkakuHiragana** [Facepunch/garrysmod-issues#3633]
### Details
When I use context menu and move the cursor, the scripted weapon's viewmodel usually moves as well.
But if SWEP.ViewModelFlip is set to true, it doesn't move.

I've checked the problem in both live branch and pre-release branch.

### Screenshots
The cursor is around the red cross in the screenshots.

SWEP.ViewModelFlip = false, the viewmodel goes up.
![SWEP.ViewModelFlip = false](https://user-images.githubusercontent.com/12111138/46855167-e5e33600-ce3d-11e8-8538-75aa16839a01.jpg)

SWEP.ViewModelFlip = true, the viewmodel doesn't.
![SWEP.ViewModelFlip = true](https://user-images.githubusercontent.com/12111138/46855174-eaa7ea00-ce3d-11e8-8e2d-ee3695c2692f.jpg)

### Step to reproduce
- Load a map and enter the following into the console.

```
sv_cheats 1
give weapon_base
lua_run_cl LocalPlayer():GetWeapon("weapon_base").ViewModelFlip = true
```
- Switch from Physics Gun to Scripted Weapon.
- Enter the context menu and move the cursor around, and you will see the viewmodel not move.

**Comment by robotboy655** [comment]
Fixed.

I have also made so that 2nd and 3rd view models use their own variables (```ViewModelFlip1```, etc) for view model flip for these animations, instead of all 3 using ```ViewModelFlip```.
