### ISSUE TITLE
Issue with the new ragdoll-igniting in the Pre-Release branch.

### ISSUE THREAD

**Issue by Peeppeepii** [Facepunch/garrysmod-issues#3634]
### Detail 

When killing a npc (citizen, zombie, combine soldier, etc.), and you have keep ragdolls on, you can't ignite the ragdoll. The option IS there, but you cant ignite them. Pressing ignite won't do anything.

### Steps to reproduce

1. Get on a sandbox server.
2. Spawn in any npc that has a ragdoll upon death.
3. Make sure you have keep ragdolls on in the Context menu.
4. Kill the npc.
5. In the context menu, hover over the ragdoll, rightclick on the ragdoll and press ignite.
6. Notice how it doesn't work.

**Comment by robotboy655** [comment]
It definitely works on my end without any mods.

![image](https://user-images.githubusercontent.com/3299036/46931041-e2c09380-d051-11e8-93ef-00b51c11505a.png)
