### ISSUE TITLE
SpawnIcons digregard size when cached or rebuilt

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#3636]
### Details
Creating a 64px SpawnIcon and then a 128px SpawnIcon will cause the 128px SpawnIcon to always load the 64px cached image. 

Calling ` SpawnIcon:RebuildSpawnIcon()` also causes the SpawnIcon to rebuild at 64px regardless of size.

**Comment by robotboy655** [comment]
Should be fixed in Dev, make sure to call SetModel **after** any size changes. Wiki was updated to include this information as well.
