### ISSUE TITLE
The new net message changes

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3639]
### Details
With the new net message changes we got error codes, but we don't know which file, line and net message made this error popup.
Could we please get more info on that?
It's not very informative.

### Steps to reproduce
-

**Comment by REAZN** [comment]
Whats the error?

**Comment by mcNuggets1** [comment]
Lua Error: Warning! A net message is already started! Discarding...

**Comment by robotboy655** [comment]
It will now display both the new message name and the previous message name, that should be enough for you to pinpoint the source.

**Comment by SuchtClub** [comment]
Yeah he is Start ever new is already started! Discarding in favor of the new message! (URPC)

**Comment by Kefta** [comment]
> It will now display both the new message name and the previous message name, that should be enough for you to pinpoint the source.

**Comment by meepen** [comment]
Can't you add a traceback to the print for the old call or new call?

**Comment by robotboy655** [comment]
It is there, I don't know what @SuchtClub is even talking about, looks like gibberish to me.
