### ISSUE TITLE
Linux x64 Crash Missing swiftshader

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3640]
OS: Ubuntu 18.10
Branch: x86-64

Gmod launches, loads and displays the main-menu background and crashes. No menu is displayed.

Log: https://paste.ee/p/uDDlo

It looks like a file is misplaced. The game wants
`GarrysMod/bin/linux64/swiftshader/libGLESv2.so`
but there's no folder named "swiftshader" and the file is in the folder "linux64".

Local files already verified.

**Comment by superE03** [comment]
Same issue here.

**Comment by MinIsMin** [comment]
Seems fixed.

**Comment by MilkGames** [comment]
This is not fixed for me.

**Comment by Bo98** [comment]
I think the error is normal (for now at least), and should not be the cause of the crash.
