### ISSUE TITLE
joinleave messages are not surpressed using the ChatText hook.

### ISSUE THREAD

**Issue by Xytime** [Facepunch/garrysmod-issues#3641]
### Details
The following code from the wiki supposedly will hide the 'XXXX has joined the game' messages, however recently, this bit of code has ceased to function on my server. The type of message is still 'joinleave' and everything else is as expected, however the green message is still printed to chat and I am unable to remove it using this hook or any other means I can think of.
`hook.Add( "ChatText", "hide_joinleave", function( index, name, text, typ )
	if ( typ == "joinleave" ) then return true end
end )`

### Steps to reproduce

1) Put the above code in a lua file and place it in lua/autorun/client
2) Have a friend or somebody join the server

Expected results:
The join message is not shown

Actual results:
The join message is shown.

**Comment by thegrb93** [comment]
what does print(typ) give?

**Comment by Xytime** [comment]
It gives 'joinleave'

**Comment by thegrb93** [comment]
My server returns true in chattext to override the chat text colors so I'm sure it does work. Not sure what's going on for you.

**Comment by robotboy655** [comment]
Either there's already a hook named "hide_joinleave" on your server overriding your code or the messages are being printed by an addon.

It does work fine in my test I just did using your code:
```
hook.Add( "ChatText", "fafawefafwf", function( index, name, text, typ ) if ( typ == "joinleave" ) then print( "BLOCKING: ", index, name, text, typ) return true end end )
```
![image](https://user-images.githubusercontent.com/3299036/47363054-8c50f600-d6de-11e8-911a-7bbcb6a6574a.png)

![image](https://user-images.githubusercontent.com/3299036/47363129-b4d8f000-d6de-11e8-8c1e-ba9e4e616bd4.png)

I've tested both local multiplayer and dedicated server.
