### ISSUE TITLE
Lerp_Hermite may produce whacky results

### ISSUE THREAD

**Issue by daunknownfox2010** [Facepunch/garrysmod-issues#3645]
### Details
There is an issue that involves **Lerp_Hermite** which causes interpolated pose parameters to have visual issues (such as twitching like crazy). The reason it does this is because it's unreliable and will eventually result in a massive overshoot and/or NaN. The issue was reported in the Source SDK 2013 repository and a fix was found, as seen here: https://github.com/ValveSoftware/source-sdk-2013/issues/404#issuecomment-405042224

While it's not as common to see the twitching happen in Garry's Mod, there are still similar cases where I've seen this happen (I've recorded the player's eyes doing this before). I'm unsure whether this has been recently fixed in Garry's Mod or not, but feel free to make mention of it and close this issue report if so.

**Comment by neico** [comment]
Uhm? #3010
