### ISSUE TITLE
New Crash when trying to browse multiplayer servers

### ISSUE THREAD

**Issue by FindabairGaming** [Facepunch/garrysmod-issues#3646]
### Details
When opening Gmod there are no problems getting into the home screen.  Then when you click on multiplayer servers you see it start to load servers and then after 5 or so it crashes. So within 3 seconds after clicking multiplayer it crashes. I checked if there are any .mdmp files and there are no files from the day it happened 10/23.  I decided to restart gmod and that did not work. I restarted my computer and that did not work. I then reinstalled gmod without getting rid of my addons and that did not work. I then deleted all my addons (permanently using Windurstat) and tried restarting gmod and that did not work. I then reinstalled Gmod again and that did not work. I will try to update my network card to see if it causing any issues but all other apps using the network are working fine.
Steps:
Open GMOD
Click Multiplayer.

**Comment by HeyJack1** [comment]
I have the same issue just closes no .mdmp file. No resource usage spike or anything. just crashes.

**Comment by FindabairGaming** [comment]
I found the problem, its something to do with the Steam Beta. Users will have to opt out of the beta. Then the server browser works.

**Comment by josephlbj** [comment]
> I found the problem, its something to do with the Steam Beta. Users will have to opt out of the beta. Then the server browser works.

Still happens for me when I am opted out of the Steam Beta.

Only way to be able to join servers is through friends

**Comment by willox** [comment]
This does seem to be caused by the Steam beta. I had a look and don't see anything I can actually do about it myself.

**Comment by robotboy655** [comment]
Steam relased a fix for the issue
