### ISSUE TITLE
Player:SetGravity() is not predicted

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3648]
Try player:SetGravity(0.5) with fakelag and you'll notice some jitter in air (depending on ping ofc)
Setting this clientside doesn't seem to do anything

**Comment by mcNuggets1** [comment]
Setting nwvars/entity nwvars on players serverside (on listen servers), lags the movement also for some reason.

**Comment by Kefta** [comment]
@mcNuggets1 You must set NWVars shared in a predicted environment or else you'll get prediction errors which is the cause of movement lag.

**Comment by mcNuggets1** [comment]
But these NWVars aren't affecting Movement, so why are they causing jitter?

**Comment by Brassx** [comment]
Yeah to get around the jitters, network it, or use a NWVar, then use a SetupMove hook on the client, calling ply:SetGravity(<yourgravityvarhere>) inside it. This removes all the jitters for me on the client end, even with fakelag 500.

**Comment by RaphaelIT7** [comment]
@robotboy655 shouldn't this have the label Net-Compat-Breaking since `m_flGravity` would need to be networked to fix it?

**Comment by robotboy655** [comment]
Will be networked in the next update, seems to work well.
