### ISSUE TITLE
Player:Say() produces an unexpected leading space in its resulting chat message

### ISSUE THREAD

**Issue by MatthewWid** [Facepunch/garrysmod-issues#3650]
### Details
When invoking the `Player:Say()` method on the server the outputted message in the chat box, client-side console and the server-side console produces an unexpected space character appended to the message.

This happens when invoking the `:Say()` method on humans and bots, equally.

The following image demonstrates first sending a message with the `Player:Say()` method and then afterwards sending the same "`Message`" text manually through the chat box (the preceding logged number being the length of the sent message).

<img src="https://i.imgur.com/BcyPL7B.png" />

This issue does not occur when using the `chat.addText()` method on the client-side.

### Steps to reproduce
1. Start a new singleplayer game.
2. Run the following Lua code on the server side (Eg, `lua_openscript spacebug.lua`):
    ```lua
    if SERVER then
	    hook.Add("PlayerSay", "Listen for message", function (ply, text)
		    print(string.len(text))
	    end)

	    player.GetAll()[1]:Say("Message")
    end
    ```
3. Manually type and send into chat the text "`Message`" (Without the quotation marks).
4. Notice that the first chat message sent has a trailing space, and is one character longer when logging it's length (Highlighting both chat messages makes this comparison obvious).

### Game Version

```
2018.10.10
Exe version 18.10.17 (garrysmod)
```

### Operating System

```
Windows 8.1 64bit
```

**Comment by siasur** [comment]
maybe not really helpful, but that's an **trailing** space

**Comment by robotboy655** [comment]
Resolved.
