### ISSUE TITLE
Lua Panic "Not Enough Memory"

### ISSUE THREAD

**Issue by HeyJack1** [Facepunch/garrysmod-issues#3652]
So Basically i'm trying to join my server and just crashes with no dump file with the Engine Error "Lua Panic "Not Enough Memory"" and it is nothing to do with my memory as i see it. [http://heyjack.info/dab11.PNG](url)

**Comment by robotboy655** [comment]
It's not about your memory, its about the amount of addons you or the server are trying to load. The only way you will "fix" your problem is to reduce amount of addons, etc you have installed.
