### ISSUE TITLE
can't spawn toolgun related entities

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3653]
### Details
Tell us exactly what happens, every single detail that you can think of
after selecting a model from the tool panel, the tool won't spawn the entity
first encountered on chromium, seems to affect all branches. 
### Steps to reproduce
Tell us how to reproduce the problem, step by step
choose a tool that spawns entities whose model is determined by the tool panel setting(balloons,button,etc)
then click away

### other
it seems like it expects
(balloon_model normal_skin2)
but got
(balloon_model 'normal_skin2'  )
an apostrophe before and an apostrophe and two spaces after

**Comment by robotboy655** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/3299036/47728327-ce41e500-dc66-11e8-8ea8-bc1e789e0f97.png)

Check your mods, etc, etc.

**Comment by joeyjumper94** [comment]
mount cstrike, ep2, episodic, hl1, hl2, lostcoast, and tf

**Comment by thegrb93** [comment]
Those are content. He is talking about addons or workshop mods you've installed.

**Comment by joeyjumper94** [comment]
i found out what was wrong, it was an addon i made that was doing it
