### ISSUE TITLE
prop_effect entities are not dupe-spawnable unless user is in the Admin/SuperAdmin usergroup

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-issues#3654]
### Details

The **prop_effect** entity does not have a registered entity class and is also marked as [ENT.Spawnable = false](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/base/entities/entities/prop_effect.lua#L10)

As a result, unless the player passes a PLAYER:IsAdmin() check (shown below), they cannot spawn in a duplicated prop_effect via **Duplicator** or **Advanced Duplicator 2** (see wiremod/advdupe2#155)

[duplicator.lua/GenericDuplicatorFunction](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/includes/modules/duplicator.lua#L419-L424):
```lua
if ( IsValid( Player ) && !Player:IsAdmin() ) then -- not an admin
  -- not Spawnable, so this line fails and blocks spawning the effect
  if ( !scripted_ents.GetMember( data.Class, "Spawnable" ) ) then return end
  if ( scripted_ents.GetMember( data.Class, "AdminOnly" ) ) then return end

end
```

### Potential solution
As mentioned in the AdvDupe2 issue, registering the prop_effect class via [duplicator.RegisterEntityClass](http://wiki.garrysmod.com/page/duplicator/RegisterEntityClass) with a callback function would prevent the issue by [not having to call](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/includes/modules/duplicator.lua#L612-L620) `GenericDuplicatorFunction` shown above.

This would allow regular users to spawn in duplicated prop_effects while still allowing limit checking and all of that like [many other entities do with duplicator.RegisterEntityClass](https://github.com/search?utf8=%E2%9C%93&q=duplicator.RegisterEntityClass+user%3Afacepunch+repo%3Agarrysmod+path%3Agarrysmod%2Fgamemodes%2Fsandbox%2Fentities%2Fweapons%2Fgmod_tool%2Fstools&type=Code&ref=advsearch&l=&l=).

**Comment by thegrb93** [comment]
Would also be nice if the prop effect used PhysicsInitSphere or something for its collision model.

**Comment by robotboy655** [comment]
Fixed
