### ISSUE TITLE
Addons randomly disappearing and/or not self implementing to the game 

### ISSUE THREAD

**Issue by TTT2866** [Facepunch/garrysmod-issues#3657]
(I know you said not to post about addons but this isn't for a specific one so I can't contact one creator) 

### Details
Basically, some addons aren't implementing to the game from the addon folder. Otherwise if they are they randomly disappear sometimes. I had a whole category of snipers just disappear one time, and they aren't in singleplayer or multiplayer. And after my last crash I lost 2-3 entire addon packages, along with a addon not even ever getting added to the game.

(I actually just checked and one addon seems to have automatically unsubscribed itself from the workshop, perhaps a whole new issue)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

Reproduce like purposely create the problem? It seems to be randomly removing stuff

**Comment by robotboy655** [comment]
Have to close this since there's nothing to work with here.
I imagine newly installed addons or addon update just break themselves or other addons, or you disabled the addons on purpose and forgot about it or whatever.
