### ISSUE TITLE
Tau cannon decals stay forever.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3658]
### Details
The decals left by the Tau cannon do not fade away like they are supposed to with the 2004 Engine version. Even Half-Life 2 is currently affected by the same bug, would be kinda nice to have this working again so it won't leave lots of shitty glowing decals around.

### Half-Life 2 (2004 Engine)
![ezgif-1-aa64bd6da5f9](https://user-images.githubusercontent.com/5415177/47945175-5db5f500-df00-11e8-8f3e-4e211bad7b77.gif)

### Garry's Mod
![ezgif-1-261fb75def26](https://user-images.githubusercontent.com/5415177/47945215-b5546080-df00-11e8-9b17-1ccbe42a5c91.gif)

![hl2_2018-11-03_00-42-05305b7048e8901d5bf](https://user-images.githubusercontent.com/5415177/47945305-580cdf00-df01-11e8-8534-046af61f5d9e.jpg)

### Steps to reproduce
Shoot the Tau cannon 🔢

**Comment by ZehMatt** [comment]
Perhaps this is the reason why its not working, assuming its the same in GMod: https://github.com/VSES/SourceEngine2007/blob/master/se2007/studiorender/r_studiodecal.cpp#L1174 is because everything for that is commented.

**Comment by robotboy655** [comment]
That code is commented out because the entire decal fade system no longer exists in the engine.
`decal.m_FadeStartTime` & co are never used anywhere.

I honestly am not sure it's worth the time to re implement it from scratch for this 1 decal.

**Comment by thegrb93** [comment]
If someone pr's the fix on that repo, would you pull it?

**Comment by Kefta** [comment]
Can't the fade code from https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/r_decal.cpp just be adapted for ``Decal_t``s? It uses the same basic data structure just under a different name.

**Comment by robotboy655** [comment]
Oh the linked above code was only for model decals, good find.

I have made it work on world brushes and displacements.

**Comment by thegrb93** [comment]
Nice one

**Comment by ZehMatt** [comment]
Great, thanks.
