### ISSUE TITLE
Gmod Textures missing?

### ISSUE THREAD

**Issue by jacobdcooper** [Facepunch/garrysmod-issues#366]
![2013-08-07_00001](https://f.cloud.github.com/assets/5183709/925838/1bbce254-ff80-11e2-80d8-9529a185809c.jpg)

I'm only getting that and no character models. Reinstalled twice. Any way to fix?
Edit: Also seems none of the animations are working, either, Please take note this is all standard gmod. That was the map that comes with it.

**Comment by nevel850** [comment]
Hi, I'm from 2020 😃
