### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Eistee02** [Facepunch/garrysmod-issues#3660]
### Details
my users of my server frequently crashes, i cant find the cause, crashdump: "https://www.dropbox.com/s/8hl67ldcuehyett/hl2_181010_crash_2018_10_24T19_56_47C0.mdmp?dl=0"

### Steps to reproduce
unknown

**Comment by Eistee02** [comment]
Crashlog2: "https://www.dropbox.com/s/0c7rwvuj1m1f3a2/hl2_181010_crash_2018_11_9T20_25_10C0.mdmp?dl=0"

**Comment by robotboy655** [comment]
One of the crashes is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3159

**Comment by robotboy655** [comment]
The other one seems to be caused when changing player models. A way to reproduce either, or at least paths to the player models would be great.

**Comment by Eistee02** [comment]
https://www.dropbox.com/s/3xllvt6o39bs575/playermodels.rar?dl=0

**Comment by robotboy655** [comment]
Going to close this as stale. If the issue happens again, open a new report.
