### ISSUE TITLE
Several Chromium Branch Lua Errors

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3662]
I'll probably install chromium branch later today to investigate, but seems like some change is breaking things. If you could tell me what change it is, it would make fixing them easier.

https://github.com/wiremod/wire/issues/1752

https://github.com/wiremod/advdupe2/issues/157

**Comment by willox** [comment]
I'm not aware of any change that'd cause an issue like this.

**Comment by robotboy655** [comment]
I will look into it tomorrow, I think I know what's up.

**Comment by robotboy655** [comment]
Resolved on Dev, Chromium will be done later.
