### ISSUE TITLE
Rendering PNGs to RT fails with MSAA turned on.

### ISSUE THREAD

**Issue by Rusketh** [Facepunch/garrysmod-issues#3664]
### Details
I have been trying to create a screen entity that uses render targets. I draw to the render target and then use that rt as a material to draw the screen inside a cam2d3d. When drawing png files to the render target some players could see the png file whilst other could not, 

After some digging we managed to figure out that those who could not see the png file rendered in the rt where on windows with MSAA turned on. turning MSAA off will then allow them to see the image.

### Steps to reproduce
Run the following code client-side on windows with MSAA turned off.

```
local TEST_MAT = CreateMaterial("TEST_MAT","UnlitGeneric",{ ["$vertexcolor"] = 1, ["$vertexalpha"] = 1, ["$translucent"] = 1, ["$ignorez"] = 1, ["$nolod"] = 1})
local TEST_RT = GetRenderTargetEx("TEST_RT", 512, 512, 0, 0, 0, 0, IMAGE_FORMAT_RGBA8888)
local MAT = Material("materials/icon16/car.png")

hook.Add("HUDPaint", "TEST", function()
  local w, h, old = ScrW(), ScrH(), render.GetRenderTarget()

  render.SetRenderTarget(TEST_RT)
  render.SetViewPort(0, 0, 512, 512)
  render.Clear(0, 0, 0, 0)

  cam.Start2D()
    surface.SetDrawColor(255, 255, 255, 255)
    surface.SetMaterial( MAT )
    surface.DrawTexturedRect(0, 0, 512, 512)
  cam.End2D()

  render.SetViewPort(0, 0, w, h)
  render.SetRenderTarget(old)

  local base = TEST_MAT:GetTexture("$basetexture")
  TEST_MAT:SetTexture("$basetexture", TEST_RT)

  surface.SetDrawColor(255, 255, 255, 255)
  surface.SetMaterial( TEST_MAT )
  surface.DrawTexturedRect( (w*0.5)-256, (h*0.5)-256, 512, 512)
  TEST_MAT:SetTexture("$basetexture", base)
end)
```

,with MSAA turned off you should see a car rendered in the center of your screen.

Now turn MSAA on and the car will disappear until you turn MSAA off again.

**Comment by thegrb93** [comment]
Your script doesn't draw anything to the rendertarget for me either.

Oddly, works fine in starfall in HUDPaint with MSAA on.
```lua
local mat = material.createFromImage("materials/icon16/car.png", "smooth")
render.createRenderTarget("RT")
hook.add("drawhud","",function()
    render.selectRenderTarget("RT")
    render.clear(Color(0,0,0,0))
    render.setMaterial(mat)
    render.drawTexturedRect(0,0,1024,1024)
    render.selectRenderTarget()
    
    render.setRenderTargetTexture("RT")
    render.drawTexturedRect(0,0,512,512)
end)
```

**Comment by thegrb93** [comment]
The only difference I could find between starfall and your code is it does
```lua
render.PushFilterMag(TEXFILTER.ANISOTROPIC)
render.PushFilterMin(TEXFILTER.ANISOTROPIC)
```
but there's probably something I missed

**Comment by Rusketh** [comment]
I have tried adding those filters and got nothing, maybe i used them wrong but I honestly don't think they are the issue.

**Comment by Rusketh** [comment]
Solved this by adding a true at the end of render.Clear();.
