### ISSUE TITLE
ProjectedTexture() clientside ragdoll crash

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-issues#3665]
### Details
Recently, I've been playing around with the ProjectedTexture() object, and found out when a clientside ragdoll is freshly created in a PT()'s frustum, the game, after a few seconds will crash without reason.  This only happens if you don't constantly update the PT().  It doesn't happen to already made clientside ragdolls, only freshly made ones for some reason.  I'm playing on the current version of GarrysMod.

A .mdmp dump is in the zip file below, along with a clientside lua script I used to produce the crash.

### Steps to reproduce
1. Open the .zip I posted, and then put the lua file in the Lua folder.
2. Open GarrysMod, and load up gm_construct.
3. Go to the building with the holes in it's ceiling, the one that has the doors to the dark room and the mirror room.
4. Put in the console "lua_openscript_cl projectedtexture_crash.lua".
5. Kill any Nextbot or NPC in the ProjectedTexture()'s frustum, and the game will close out instantly within a few seconds.

### Files
[projected_texture_crash.zip](https://github.com/Facepunch/garrysmod-issues/files/2597612/projected_texture_crash.zip)

**Comment by robotboy655** [comment]
Should be fixed in Dev.
