### ISSUE TITLE
64-Bit GNU/Linux 

### ISSUE THREAD

**Issue by gmod64bit** [Facepunch/garrysmod-issues#3668]
![screenshot-2018-11-26_12-17-57](https://user-images.githubusercontent.com/45379805/49058342-72f90900-f1b8-11e8-9283-11977a0bba80.png)

Help! Thanks!

**Comment by robotboy655** [comment]
64 bit support on linux is still in development, this is not a place to get help.

**Comment by CaptainPRICE** [comment]
Relatives to #3758

**Comment by CaptainPRICE** [comment]
Solved, see my comment in #3758 ([here](https://github.com/Facepunch/garrysmod-issues/issues/3758#issuecomment-480611407)).
