### ISSUE TITLE
$alphatest 1 in materials on displacements prevents traces from hitting it

### ISSUE THREAD

**Issue by CheezusChrust** [Facepunch/garrysmod-issues#3669]
### Details
If you give a WorldVertexTransition or LightmappedGeneric material $alphatest 1 (haven't tried other shader types) and apply it on a displacement (have not tested on regular brushes) it doesn't get hit by any form of traces - you can toolgun through it, spawn props through it, etc.

I use alphatest to create displacements that don't cast shadows and this issue has been bugging me for a long time. Is this intended behavior or is this fixable?
### Steps to reproduce
1. Give a WorldVertexTransition or LightmappedGeneric material the $alphatest 1 property.
2. Apply it to any displacement.
3. Try to use the toolgun or spawn a prop (or any other kind of trace) towards the displacement. In my testing it will always pass through it.

**Comment by robotboy655** [comment]
I have added a workaround so this won't happen. The issue is coming from `vbsp.exe`, so it only matters during map compile. 

I also don't know why you'd ever use a material with `$alphatest` on a displacement though.
