### ISSUE TITLE
APC laser's strange behavior

### ISSUE THREAD

**Issue by DanilaFoxPro** [Facepunch/garrysmod-issues#3670]
### Details
**Combine APC**'s laser dot follows player all around the map until the player is forgotten by the APC. After that, the laser just floats in the air.

### Steps to reproduce
Create prop_vehicle_apc and npc_apcdriver. Give APC a targetname, set apcdriver's "Vehicle" keyvalue to APC's name. Run around the map, laser dot will follow you everywhere.

**Comment by robotboy655** [comment]
Fixed on Dev branch.
