### ISSUE TITLE
DTextEntry removes first character if it's '#' and set with SetText()

### ISSUE THREAD

**Issue by AirBlack** [Facepunch/garrysmod-issues#3672]
### Details

If you call DTextEntry:SetText("#anytext") it will remove '#' from the start.

### Steps to reproduce
Call DTextEntry:SetText("#any") on any dtextentries
For example

```
local frame = vgui.Create("DFrame")
frame:SetSize(200, 200)
local entry= frame:Add("DTextEntry")
entry:SetText("#TEXT")
```

Text in text entry after this code execution will be "TEXT".

**Comment by meepen** [comment]
This is because of localization.

**Comment by AirBlack** [comment]
Then why # doesn't get removed if it isn't at the start? I still think that's an issue.

**Comment by robotboy655** [comment]
Not a bug. This is how Source Engine localization works.
