### ISSUE TITLE
monster_human_grunt and monster_houndeye use the same squad name

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3674]
These NPCs create their squad with name "squad*", * is an auto generated number. The issue is that grunt and houndeye squad names are conflicting. So it spams in console something like this and lags the server (mostly in On a Rail chapter)
> ERROR: Squad 'squad7
> ' has enemies in it!
> monster_human_grunt doesn't like monster_houndeye

**Comment by robotboy655** [comment]
Should be fixed in Dev
