### ISSUE TITLE
GMod crashed after using bone manipulation

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3676]
### Details
For a moment I saw the model spazzing out.
For some reason it entered T pose either, though it is valid and worked the whole day.

This maybe not fixable.

Here is the crashlog:
https://ufile.io/t5z8k

### Steps to reproduce
-

**Comment by robotboy655** [comment]
Going to close this as stale. If the issue happens again, open a new report.
