### ISSUE TITLE
Model() precaches invalid models

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3681]
Model() currently precaches everything you give to it, even invalid models. so it will be always a red ERROR for that path until you restart the game. Can something be done so it won't precache invalid models?

**Comment by Kefta** [comment]
I think it's to prevent repetitive disk lookups so missing models don't cause the game to constantly try to precache or get model data for something that doesn't exist. Something like the command described in https://github.com/Facepunch/garrysmod-requests/issues/957 or a way to manually dump the model cache (or better yet, the ability to remove a specific cache entry) could solve this. A similar implementation for sound and material caches would be great too.

**Comment by robotboy655** [comment]
not a bug

**Comment by eLeCtrOssSnake** [comment]
oof. Nice fixing
