### ISSUE TITLE
srcds crash

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3685]
My server crashes for no reason sometimes, I think it's somehow related to HL1 entities

Two last dumps:
https://puu.sh/CjgBU/a7a8bbe751.mdmp
https://puu.sh/CjgC8/f2dbce7b3d.mdmp

**Comment by TheMostUpset** [comment]
Here are dumps from another server owner, same issue: http://gamedata.quadranote.com/dumps.zip

**Comment by robotboy655** [comment]
Should be fixed in Dev.
