### ISSUE TITLE
Gravity Gun weapon messing up viewmodel claws of other weapons.

### ISSUE THREAD

**Issue by Shadowysn** [Facepunch/garrysmod-issues#3689]
The Gravity Gun in Garry's Mod appears to be conflicting with other weapons using the same or similar viewmodels.
When in the player's inventory, it sets the pose parameter of the claw's "active" state to whatever it wants. It does this every frame and **even when not being held.** 

The result will have claws in gravity-gun-viewmodel SWEPs always closed, regardless of SetPoseParameter, unless the Gravity Gun is removed from the player's inventory.

Special thanks to [Jvz](https://forum.facepunch.com/u/cwqw/Jvs/) for notifying me of this in my [issue post.](https://forum.facepunch.com/gmoddev/buopq/New-way-of-opening-closing-Gravity-Gun-claws/1/)
_How to reproduce:_
1. Acquire lua weapon code from this [facepunch forum post.](https://forum.facepunch.com/f/gmoddev/luiv/Gravity-Gun-Claws/1/)
2. Have the gravity gun in your inventory, and use the aforementioned SWEP.
3. Remove the gravity gun. 
(You can do this in vanilla by typing 'sbox_weapons 0' in the console and then respawning.)
4. Use the claw SWEP again.
The result should be: 
Claw testing weapon's claws always closed. After gravity gun is removed, the claw testing weapon is able to move the claws.

_OR_

Use Jvz's method [here.](https://forum.facepunch.com/gmoddev/buopq/New-way-of-opening-closing-Gravity-Gun-claws/1/)

**Comment by robotboy655** [comment]
Should be fixed.
