### ISSUE TITLE
My game crashed when shooting a HUMMER z1 by LW cars

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3691]
### Details
Even after the decal crashes update, you can still crash shooting specific LW cars.
I crashed shooting the HUMMER z1, no crash log were generated.
The game just froze and windows reported it wouldnt respond.

(I used CW2 weapons to shoot at the car, which support ricochet, could be related)

### Steps to reproduce
Sadly I dont know.

**Comment by robotboy655** [comment]
If you cannot reproduce the crash, and there are no .mdmp dumps or an error message or anything, there's nothing that can be done.

**Comment by mcNuggets1** [comment]
I was with a friend.

We shot the car with a CW2 weapon (ricochet) and it crashed us both.

On reconnect he shot the car again, and it crashed him again.

Using a CW2 weapon to shoot a HUMMER Z1 from LW cars does indeed crash the game for us.

**Comment by Kefta** [comment]
If you can get it to consistently hang, boil it down to code and models that we can run and reproduce.

**Comment by mcNuggets1** [comment]
I can't reproduce the crash again.
I tried on 3 different maps, with various car models.

I will create a new issue if this happens again.
