### ISSUE TITLE
Using the old source browser

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3694]
### Details
Using the old server browser, whenever I add an server to favorites, it gets automatically added to the list, but I can't join until I refresh the list, because all it says is "Add server to favorites".
Also I can't search using actual names, just gamemodes.

Does source have a new source browser version, because I never encountered the issue in other source games?
Would be nice if it gets updated then.

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by robotboy655** [comment]
Legacy server browser will not be updated to support search by name, or any other new features.

And I'd rather improve the current browser rather than fix the old one.
