### ISSUE TITLE
GetModel can return no value

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3695]
Code:
```
hook.Add("OnEntityCreated", "", function(pEntity)
	print(pEntity:GetModel() == nil)
end)
```

A number of entities when the map spawns don't have models on the server nor client. Spawning NPCs in single-player will result in them having a nil model serverside but a string clientside. Credit to @Earu for noticing this.

**Comment by ZehMatt** [comment]
I think the reason for this is that OnEntityCreate doesn't mean its fully spawned yet, just got created, equivalent of calling ents.Create(class) and then calling this function right away before setting any model or position yet. I normally wait one frame to make sure all the data is set.

**Comment by robotboy655** [comment]
I would imagine its point entities which cannot have a model.

**Comment by Earu** [comment]
@ZehMatt Even so the behavior is different on server and client for this, which should not be the case.
@robotboy655 My tests were made with normal props no fancy brush entity or whatsoever.

**Comment by ZehMatt** [comment]
Its different because the client will initialize the entity from a snapshot and will be created on the client with all data set already, thats just how source works.

**Comment by thegrb93** [comment]
That's fine and everything, but empty string would be more appropriate than nil/novalue imo.

**Comment by robotboy655** [comment]
Which would break every script that uses nil to test if the entity has a model or not, unfortunately.

Even the base game itself https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/entities/effects/propspawn.lua#L18

**Comment by thegrb93** [comment]
Then the wiki page needs to be updated.

**Comment by Kefta** [comment]
This is intentional behaviour.
