### ISSUE TITLE
ITexture:IsError() doesnt work properly

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#3697]
http://wiki.garrysmod.com/page/ITexture/IsError I dont think this is working as intended
https://i.imgur.com/tDUH2o0.png

As you can clearly see in my example basetexture2 shader is a a missing texture yet IsError returns false.

**Comment by thegrb93** [comment]
I don't think undefined texture should be error, seems more like an issue with GetName. Assuming it is undefined.

**Comment by thegrb93** [comment]
Is basetexture2 undefined? My guess is it returns a valid texture pointing to the error texture.

**Comment by thegrb93** [comment]
Probably easily fixed by setting the 'error' flag or whatever on that returned texture.

**Comment by robotboy655** [comment]
Well, it is not broken.

It tests for the internal error flag, which is set for textures that are attempted to be loaded from dist and failed, but it is not set for the error texture itself. Setting the flag on the error texture may have unexpected results.

Also if the texture returned by GetTexture() is an error texture no value will be returned instead.

**Comment by neico** [comment]
well on the C++ side there's a `IsErrorTexture` function with the following expression: `return !pTex || pTex->IsError()` (where for IMaterial there's a `IsErrorMaterial` function with `return !pMat || pMat->IsErrorMaterial()`)
There is also a `SetErrorTexture` method for ITexture with the comment: `//Set that this texture should return true for the call "IsError"`

exposing those is probably the smartest approach to handle it

**Comment by robotboy655** [comment]
There is no such thing as `SetErrorTexture` and the `IsErrorTexture` is pointless, as it will just call `IsError` which we already have bound.

`IMaterial.IsError` already calls to `IsErrorMaterial`.

I have added `ITexture.IsErrorTexture`
