### ISSUE TITLE
Too many folders in garrysmod/addons/ causes broken text in Garry's mod.

### ISSUE THREAD

**Issue by Havocking1992** [Facepunch/garrysmod-issues#3699]
I found strange bug with Garry's mod. When you have over 158 folders in garrysmod/addons (and i do) it mess up text in game. Options window is covered with #GameUI_ shortcuts. It appears to fail to load some txt files from Resources/ folder when folder count in Addons folder hits 149 and more seen with 158+ folders. I tried this just by making new empty folders, but content appear to doesn't matter. 
*If it helps, i have czech version of Windows so those folders contains diacritic (for ex. Nová složka (151) ),
but problems appears even with just english text with   _   key used.
*I am using no beta version

Pictures taken at 158 folders created:
[Console](https://imgur.com/a/4RqyLQL)
[Options](https://imgur.com/a/t2bsYij)

Steps i have done:
Reinstalled Garry's mod, before that opened FactoryReset-GMod.bat 
Unsubscribed ALL workshop addons, deleted .gma files
1. Make new folder
2. Start Garry's mod, check in console at main menu
3. Close Garry's mod
Repeated 1,2 and 3 until i hit errors.
-------------------------------------------------------
**Errors related to issue:**
Folder count 149 	
`CLocalizedStringTable::AddFile() failed to load file "Resource/valve_english.txt".`

Folder count 149 - 158
some key bindings named like #Valve_Move_Forward
`CLocalizedStringTable::AddFile() failed to load file "Resource/valve_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "Resource/valve_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "resource/chat_english.txt".`

Folder count 158+	
whole Options window have bugged text like #GameUI_ etc
`CLocalizedStringTable::AddFile() failed to load file "Resource/valve_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "Resource/gameui_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "Resource/valve_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "resource/chat_english.txt".`
`CLocalizedStringTable::AddFile() failed to load file "resource/closecaption_english.txt".`

**Comment by robotboy655** [comment]
Fixed in Dev. The problem was with too many search paths, I'd expect some other systems failing in the same manner.

**Comment by Havocking1992** [comment]
Nice, good work, thank you :)
