### ISSUE TITLE
Consistent crash log with nothing inthe crash log'

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#3702]
### Details
I retired a server a few months ago, but recently brought it back up. when It was running months ago, running stably with all of it's addons and systems the same as they are now. While there have been some new addons added, these were soon removed in order to debug this issue, but I've been struggling with this for weeks now and it's really my last resort to put my crash logs here

Basically, the server will crash after about an hour or so with players and it's really impossible for me to figure out what could be doing it. I have a collection of crash logs, but that's really it. I've tried looking at the lua stack in them, but there's nothing so I'm hoping someone can look at these Crash logs and shed some light on it for me. 

Here are the .mdmp files.
https://dl.dropboxusercontent.com/s/i8ik6kw091yyj79/srcds_2117156_crash_2018_12_31T0_36_38C0.zip

### Steps to reproduce
This is a specific issue with my server and while I've tried disabling addons in order to fix it, yet the game still crashes. I'm hoping the crash logs will be able to shed light on this issue.

Mainly what I'm asking for is for devs to look at the crash logs with their tools and give me any relevant information on what happens leading up to the crash. Thank you.

**Comment by robotboy655** [comment]
2 of them are vphysics crash, cannot be diagnosed, the other 3 are from ```GetSequenceMoveDist``` calls likely on a bad model.

Perhaps add print out what model the entity has before calling ```Entity.GetSequenceMoveDist```

**Comment by robotboy655** [comment]
Closing as stale.
