### ISSUE TITLE
ScalePlayerDamage not called

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3704]
### Details
When the player gets hit by the stunstick it will only call EntityTakeDamage instead of ScalePlayerDamage then EntityTakeDamage.

### Steps to reproduce
Go to some map like d1_canals_01 with metropolice and stunsticks.
```
lua_run hook.Add("EntityTakeDamage", "test", function(target, dmg) print("EntityTakeDamage", target, dmg:GetAttacker(), dmg:GetInflictor(), dmg:GetDamage()) end)
lua_run hook.Add("ScalePlayerDamage", "test", function(target, hg, dmg) print("ScalePlayerDamage", target, dmg:GetAttacker(), dmg:GetInflictor(), dmg:GetDamage()) end)
```
Get hit by the stunstick and get hit by a bullet, when you get hit by a bullet it does what I would expect otherwise its not called.

**Comment by robotboy655** [comment]
This is true for all damage done to the player not through bullets, and there really isn't a way around this. We cannot get which body part was hit if we insert this hook into all sources of melee damage, and it will still leave out direct calls to `Player:TakeDamage()`. If we call this hook for players from/before `EntityTakeDamage`, `ScalePlayerDamage` will be called twice for bullet damage.

**Comment by ZehMatt** [comment]
Too bad, thanks for the info.
