### ISSUE TITLE
Prediction errors due to noclip.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3706]
### Details
When you noclip in water and fly out the server will still hold the the FL_INWATER flag on the player while the client removes it naturally causing prediction errors.

### Steps to reproduce
Load something like gm_construct jump into the water start to noclip and fly out, you will notice the hitching during hard resets and cl_showerror 2 will spit out a bunch of errors.

## Temporary fix
```
-- Shared
hook.Add("StartCommand", "NoClipPredictionFix", function(ply, cmd)
	-- Fixes a prediction error when starting noclip in water and flying out.
    if ply:GetMoveType() == MOVETYPE_NOCLIP and ply:WaterLevel() == 0 then
        ply:RemoveFlags(FL_INWATER)
    end
end)
```

**Comment by mcNuggets1** [comment]
I saw this too happening in my game.

**Comment by robotboy655** [comment]
Should be fixed in Dev.
