### ISSUE TITLE
Cleanup or same tick props removal will cause GetCount("props") to report incorrect values

### ISSUE THREAD

**Issue by Splash-Atox** [Facepunch/garrysmod-issues#3707]
Spawn for example 5 props
Run this in console `lua_run_cl for k, v in pairs(player.GetAll()) do print(v:GetCount("props")) end`
It will return 5 which is the correct prop count but if you do a cleanup or clean up all props the same tick
And run the console command again it will return 4 instead of 0

**Comment by mcNuggets1** [comment]
This is handled in Lua as far as I know.

**Comment by robotboy655** [comment]
It's just a matter of NWVars not being updated on client. Not really too much to worry about, but I will look into it.

**Comment by robotboy655** [comment]
Fixed
