### ISSUE TITLE
Toolgun ghost gets left behind still in dedicated server

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3709]
Just making this issue so its not forgotten.

https://github.com/Facepunch/garrysmod/commit/0883499dd17f15eb2061a37bc755250a0dc67238 isn't working. Probably due to prediction and CurTime. More details in that commit's comments.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3709

**Comment by thegrb93** [comment]
Gotta reopen this... still not fixed

**Comment by robotboy655** [comment]
Should be fixed for good by https://github.com/Facepunch/garrysmod/pull/1674
