### ISSUE TITLE
Convar flag FCVAR_ARCHIVE_XBOX does not exist on XBOX x64 version of Gmod

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#3710]
### Details
When coding an XBOX addon for the x64 bit branch the [flag](https://wiki.garrysmod.com/page/Enums/FCVAR) does not exist
```lua
local iFlag = bit.bor(FCVAR_ARCHIVE, FCVAR_ARCHIVE_XBOX)
```
You receive `bad argument #2 to 'bit.bor' (number expected, got nil)`

I had to [literally remove it from my addon](https://github.com/dvdvideo1234/TrackAssemblyTool/commit/be8ac05934885f4705bad748072c7d3901f40801) so it stops crashing.

### Steps to reproduce
1. Install Gmod on XBOX
2. Go to the x64 experimental branch
3. Use FCVAR_ARCHIVE_XBOX in a custom addon

**Comment by willox** [comment]
A good joke, but this is something that needs fixing.

**Comment by robotboy655** [comment]
Pretty sure @willox ended up fixing this.

**Comment by dvdvideo1234** [comment]
Perfect. I had a user who was missing this convar flag and he was crushing, so I ended up removing it.
