### ISSUE TITLE
Sniper Range

### ISSUE THREAD

**Issue by DanilaFoxPro** [Facepunch/garrysmod-issues#3715]
### Details
Snipers become blind at a certain distance, even with long range flag set. They still can shoot past the distance of their vision and their laser can move there, but they are blind to the any objects past approximately 5500 units.

### Steps to reproduce
Place npc_sniper on any map, move approximately 5500 units away.

**Comment by robotboy655** [comment]
I am not that sure we want snipers to have infinite range. I could add a function that will affect maximum distance NPCs can see for, but the function will need to be ran after ```:Spawn()``` because the defaults are being set there.

**Comment by Kefta** [comment]
Maybe just add an entity input to set the maximum distance so mappers can change it as well?
