### ISSUE TITLE
Killicons with unconventional letters not working

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-issues#3716]
### Details
I'm working on Zombie Panic: Source SWEPs that were originally made by AnonymoScoot, primarily updating their kill icons to use those in the actual mod. However, the Sledgehammer uses the right-slash '\' letter, which in turn spews an error message that leads to the Sledgehammer not working

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
[1. Download the Workshop addon here.](https://steamcommunity.com/sharedfiles/filedetails/?id=286983120)
2. Use GMAD to unpack the Workshop addon.
3. Edit the weapons' LUA files to create the ZPDeath font `surface.CreateFont("ZPDeath", {font = "ZPDeath", size = ScreenScale(30), weight = 500, antialias = true, additive = true})`, then replace the killicon.Add code with killicon.AddFont. The Sledgehammer uses the \ letter, you should see an error message when starting a map.

**Comment by robotboy655** [comment]
Why are you linking a portal 2 screenshot?
Why have you not posted the error message?

**Comment by BreakinBenny** [comment]
I fucked up.

This is how the error message reads `[ERROR] addons/zombie_panic_source_weapons_286983120/lua/weapons/weapon_sledgehammer.lua:98: unfinished string near '"", Color(255, 80, 0, 255))'
  1. unknown - addons/zombie_panic_source_weapons_286983120/lua/weapons/weapon_sledgehammer.lua:0
`

And here's the code: `killicon.AddFont( "weapon_sledgehammer", "ZPDeath", "\", Color(255, 80, 0, 255))`

**Comment by Kefta** [comment]
The error is not from killicon.AddFont but Lua strings themselves. \ is an escape character and requires something to come after the backslash, thus "\" is a malformed string. If you just want a single blackslash in a string, you must write two in the string's construction ("\\") or use multi-line strings and avoid escaping all together ([[\]]).
