### ISSUE TITLE
Need Entity.StopSound to work with paths

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3717]
lua_run 
local e=Entity(1):GetEyeTrace().Entity 
e:EmitSound("ambience/wind1.wav") 
e:StopSound("ambience/wind1.wav")

Related https://github.com/Facepunch/garrysmod-issues/issues/794

**Comment by robotboy655** [comment]
Should now work on Dev.

There's one caveat with this, it will stop the sound on all channels, since there's no way to know which channel you played the sound on.

**Comment by Kefta** [comment]
Could you provide a second argument to StopSound to specify the channel?
