### ISSUE TITLE
Linux x64 No such sound

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3720]
OS: Ubuntu 18.04
Branch: x86-64, 2019.01.22

Playing terrortown or sandbox (only tested those), sometimes, I can't pinpoint it, the following errors are shown in console. Only happens in x86_64.

```
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Hud.Hint
```
```
CSoundEmitterSystemBase::GetParametersForSound:  No such sound common/null.wav
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
```

Started with `-noworkshop -noaddons`.

**Comment by willox** [comment]
iirc this was a case of some new code outputting these messages even when the developer convar was not set. It's back to the same behaviour as the normal branch now.
