### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3723]
### Details
https://www.dropbox.com/s/xjphyuwvpcd8rz9/hl2_181215_crash_2019_1_23T18_44_44C0.mdmp?dl=0

### Steps to reproduce
Game randomly crashed in local multiplayer while shooting zombie.

**Comment by robotboy655** [comment]
Crashed when decals were trying to render, but the cached render data somehow became invalid.

Again, I will need a way to reproduce it on demand if this is to be fixed.

**Comment by mcNuggets1** [comment]
There is no way to reproduce this, it happened occasionally.
I never had this happening, until now.

This is all I know:
My friend were shooting zombies while I was trying to copy the material of the gmod egg with the material tool.
Then it crashed, while he fired onto a zombie, possibly missing the zombie, unknown.

I will close this and reopen it, when I have it crash again.
