### ISSUE TITLE
Problem with special characters in strings

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3724]
### Details
When going through a string like a table, a strings special character is always a "?".

### Steps to reproduce
] lua_run local str = "aä" for i=1, #str do print(str[i]) end
> local str = "aä" for i=1, #str do print(str[i]) end...
a
?
?

**Comment by willox** [comment]
Your code is equivalent to `local str= "\97\195\164" for i=1, #str do print(string.sub(str, i, i)) end` (unless i just made a typo.)

This behaviour can't be changed.

**Comment by mcNuggets1** [comment]
So is there any way to fix them not to display a question mark instead something I could potentially work with?

**Comment by willox** [comment]
You can use the utf8 library

**Comment by mcNuggets1** [comment]
Hmph, alright.
I'll figure something out, I guess.

Thanks for answering. Have a nice day.

**Comment by mcNuggets1** [comment]
I did it, thanks for giving us this master piece of an library. <3
