### ISSUE TITLE
Some leftover HL2 code causing NPC issues

### ISSUE THREAD

**Issue by Blixibon** [Facepunch/garrysmod-issues#3725]
This is a collection of small issues rather than a single large issue. I am very sorry if this doesn't fall within any issue formatting guidelines. All of these have been tested in the `2018.12.15` version of Garry's Mod.

## Details
Technically, most of these problems are difficult to encounter or cannot be encountered in a completely vanilla Sandbox session, but they're easy to reproduce and in my erratic sandbox play I have been frustrated with them.

Unfortunately, I have not been able to test these issues without any addons enabled, but I recognize them from Source 2013 (and previous versions of Source) and most of them can already be found there, so I am confident that these can happen regardless of a user's setup. I don't really have many addons enabled anyway, and most of them wouldn't affect this kind of stuff.

### Citizens fire rockets away from gunships
In Half-Life 2, there is some leftover code for citizens to try to maneuver their rockets around npc_combinegunships to avoid getting shot down. I think this code is broken to begin with, but it's designed to be used with the RPG's laser guide, which citizens in Gmod don't use. (I assume there's a good reason for that unless it's just disabled by default) As a result, citizens almost never hit gunships with their rocket launchers, even if they're looking directly at one. This probably wouldn't be encountered in a regular Sandbox session since citizens don't attack gunships by default, but it's still a big issue for trying to get citizens to shoot down gunships in a NPC battle or something.

In Source 2013, the code for this can be found in `CNPC_Citizen::GetActualShootPosition()`. They do not use this behavior against hunter-choppers or dropships.

### Allies cannot be damaged by default vehicles?
I'm not too sure about this one since this seems like a really big thing to miss, but I've seen signs of it for a long time.

In vanilla Sandbox, Combine APC NPCs from HL2 can usually only be found in maps that already have them spawned. I use an addon that can create them from the spawn menu:
https://steamcommunity.com/sharedfiles/filedetails/?id=182901638

Before I discuss the full extent of the issue, I've always noticed that these APCs can't damage any of the player's allies, particularly citizens. This is the case in HL2 as well and stems from a piece of code that most likely prevents the player from, say, bailing from the jeep so the runaway car can kill a citizen. This is part of the same code that prevents the player from killing allies in HL2, so I figured this would've been disabled in Gmod as well, but sure enough, I can't get default vehicles to damage these allies. It can kill if it lands on them from above, but it can't run them over. Vehicle weapons like the buggy's tau cannon do not seem to have any issues. Certain addon vehicles like SCars don't seem to have this problem either, but I haven't tested it with any other addons that act more like the default cars.

I know for a fact the Combine APC's issue stems from the same code that prevents vehicles from damaging allies, having fixed it before in HL2 mods. I've had that APC addon and the ally damage immunity for years, so I don't think this issue only popped up recently. I apologize if this is intentional behavior, but since it's identical to what happens in HL2, I'm sure this issue applies to anyone's game.

In Source 2013, the code for this can be found in `CAI_BaseNPC::PassesDamageFilters()`, particularly where `bHitByVehicle` is handled.

### Combine Elites only fire combine balls against player allies
This is intentional behavior in HL2, so it's more of an annoyance than an issue. Combine Elites can only use the AR2's energy balls on the player and their allies, unable to fire it at anything like zombies, hostile soldiers, or SNPCs which don't like the player. (I'm also not sure if friendly SNPCs register as "player allies" to soldiers internally, but don't quote me on that.) It's annoying when Combine Elites are fighting these kinds of NPCs since they never use their energy balls while regular soldiers can use grenades on any enemy, giving regular soldiers a major advantage and leaving one of the Elites' hallmark features unused.

This isn't as much of a problem as the other issues I've listed here, but you can easily "encounter" it in a vanilla Sandbox session with zombies and the like. I'm not sure if there would be any major repercussions from removing this check outright, but it's not a very important issue (or a very important check) and you don't have to bother if you don't think it's worth it.

In Source 2013, the code for this can be found in `CNPC_Combine::CanAltFireEnemy()` at the end of the first check that evaluates the enemy.

### Citizens fire rockets away from gunships
1. Spawn a citizen with a default weapon_rpg.
2. Spawn a npc_combinegunship.
3. Make the citizen hostile to the gunship. This can be done through addons or by typing `ent_fire npc_citizen setrelationship "npc_combinegunship D_HT 0"` into the console. The issue can be more apparent with multiple RPG citizens attacking at the same time.

### Allies cannot be damaged by default vehicles
For reproducing default vehicles not damaging allies:
1. Spawn a friendly NPC that would have friendly fire disabled in HL2, e.g. a citizen.
2. Spawn a vehicle. The default HL2 ones (including the EP2 jalopy) appear to be the main ones affected.
3. Attempt to run over the friendly NPC.

For reproducing the Combine APC not damaging allies:
1. Spawn or encounter a Combine APC through a map that already has one or an addon that spawns them, like [this](https://steamcommunity.com/sharedfiles/filedetails/?id=182901638).
2. Spawn a friendly NPC that would have friendly fire disabled in HL2, e.g. a citizen.
3. The APC should attack them by default. In doing so, it should be unable to damage the NPC.

### Combine Elites only fire combine balls against player allies
1. Spawn a Combine Elite soldier and a regular Combine soldier that both have at least one "grenade". All soldiers in the vanilla spawn menu should have at least 5 grenades stocked by default.
2. Spawn a NPC that is hostile to both the player and the Combine, like a zombie or an antlion or some kind of SNPC.
3. The Elite should not be able to fire energy balls at the enemy while the regular soldier should be able to throw grenades normally. You can test the regular soldier and the elite separately as well, or also test against player allies (like citizens) to make sure Elites can use energy balls against them.

-----

Overall, these issues aren't very pressing except for maybe the allies unable to get run over by vehicles, but the roots of these problems and the options to fix them are already known, so I hope you consider looking into these in the future.

**Comment by robotboy655** [comment]
Fixed the first two issues.

You can now run over friendly NPCs (This can be disabled by mods via GM:EntityTakeDamage)
Citizens can now properly guide their rockets into the gunships.

Will look into the 3rd issue later.

**Comment by robotboy655** [comment]
I don't think the Elites encounter any non player allies in the base campaign so I don't see any "problems" making them be able to shoot the balls at any NPC.
