### ISSUE TITLE
ToolToggle error. 

### ISSUE THREAD

**Issue by AaronHughes** [Facepunch/garrysmod-issues#3727]
### Details
I have never seen this error before. It is causing a weird glitch on the screen where there is a very small box on the top left of my screen appearing part of the spawn menu. I cannot open it at all. This is the error, it appears from the moment I spawn in.
[ERROR] gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:149: attempt to index field 'ToolToggle' (a nil value)
  1. unknown - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:149

### Steps to reproduce
I have no clue. It appeared out of nowhere. From a fresh server install at that.

**Comment by thegrb93** [comment]
Your fresh server install isn't fresh.

**Comment by robotboy655** [comment]
I don't see how this could happened for you unless your server doesn't have the ```.lua``` file for ```DImageButton```.

What branches are your client and server?
