### ISSUE TITLE
Nextbots can't AcceptInput() from model events (Event 1100)

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#3729]
### Details
AcceptInput() _does_ work on nextbots, but _only_ if you fire ENT:Input() on them. It doesn't work if you're using a model that fires animation events to the entity, which kinda sucks. I assume this is a bug since animation events work for every other entity, and other events such as sounds, bodygroups, and even particle effects work just fine.

### Steps to reproduce
Simply have a nextbot that uses a model which fires animation events and have the appropriate AcceptInput() code in the nextbot, it doesn't even print() which indicates the function isn't being called.

**Comment by robotboy655** [comment]
What do you mean by ```AcceptInput()```? ```GM:AcceptInput```? ```ENT:AcceptInput```?

Why are you talking about ```AcceptInput``` and animation events, which is not handled by ```AcceptInput``` hook?

**Comment by Roachdaripper** [comment]
Animation events are handled by AcceptInput as far as I'm aware? The event 1100 specifically.
It works for NPC's and other entities, just not nextbots

**Comment by robotboy655** [comment]
Please visit the wiki page for the hook definition:
https://wiki.garrysmod.com/page/ENTITY/AcceptInput

It is called for Map I/O, not animation events. For animation events you want https://wiki.garrysmod.com/page/ENTITY/FireAnimationEvent
or
https://wiki.garrysmod.com/page/ENTITY/HandleAnimEvent

**Comment by Roachdaripper** [comment]
That only works on "anim" type entities as the wiki dictates, which is why i was trying to use AcceptInput(), is there no alternative for nextbots?

**Comment by robotboy655** [comment]
Not at the moment.

**Comment by Roachdaripper** [comment]
I suspect I should add this to the suggestions repo?

**Comment by robotboy655** [comment]
No need, I will be adding support for FireAnimationEvent to Nextbots.
