### ISSUE TITLE
undo library can't see difference between LAN-Instances 

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#3730]
When running several instances of GMod (-multirun + sv_lan 1) the undo library thinks that they're the same person.
This is because Player:UniqueID() is same for these players

Left is second GMod instance, right is main GMod
![ezgif com-optimize 5](https://user-images.githubusercontent.com/5685050/51915054-3da4ad80-23eb-11e9-8648-6edad24d3581.gif)

**Comment by thegrb93** [comment]
I don't think this is a bug, -multirun isn't intended for normal game use. There are hundreds of cases where the same issue arises.

**Comment by thegrb93** [comment]
UniqueID comes from your steamid so the main problem is two players with the same steamid.

**Comment by meepen** [comment]
Why do we track by steamid instead of player instance or index

**Comment by thegrb93** [comment]
Because it persists if the player disconnects and reconnects

**Comment by GitSparTV** [comment]
Then I need to override it for tests.
I've already override SteamID and SteamID64 for testing, seems like UniqueID doesn't use them

**Comment by GitSparTV** [comment]
But yeah. Why UniqueID?
This is from [wiki](https://wiki.garrysmod.com/page/Player/UniqueID):
> This function has collisions, where more than one player has the same UniqueID.
