### ISSUE TITLE
1100 Event not passed into ENTITY:FireAnimationEvent()

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-issues#3731]
### Details
I'm running on the "dev" build, and I've tested this on anim, ai, and nextbot entities. None of the above when animating with animations that call the `1100` event seem to pass into the function.

### Steps to reproduce
Tested using:
```
if CLIENT then
function ENT:FireAnimationEvent(pos, ang, evt, key)
	if evt == 1100 then
		print(key)
		
		if key == "Step" then
			self:EmitSound("player/footsteps/concrete1.wav")
		end
	end
	return false
end
end
```
```
{ event 1100 9 "Step" }
{ event 1100 25 "Step" }
```

_EDIT:_ The reason I assumed the function to be AcceptInput() last time is because the Valve Dev Wiki and SSDK Source Code describes the event as such:
`SCRIPT_EVENT_FIRE_INPUT	1100	// Fires named input on the event handler`

**Comment by Roachdaripper** [comment]
Also, aren't nextbots serversided entities?
Isn't FireAnimationEvent a clientsided hook?

_Am I missing something here?_

**Comment by robotboy655** [comment]
https://developer.valvesoftware.com/wiki/Animation_Events

1100 is not a clientside animation event, it's serverside only.

It would be fired into https://wiki.garrysmod.com/page/ENTITY/HandleAnimEvent

It also has nothing to do with footsteps. It fires a Map I/O event which are serverside only, hence why the event is serverside only.

Put a print() call in ENT:FireAnimationEvent to see what events are being fired. For example with the default nextbot example NPC I get this:
```
Entity [123][npc_tf2_ghost]	anim	-740.356567 329.842773 -149.693741	0.000 -25.796 0.000	6006	NPC_Citizen
Entity [123][npc_tf2_ghost]	anim	-706.596008 313.522705 -149.978027	0.000 -25.801 0.000	6007	NPC_Citizen
Entity [123][npc_tf2_ghost]	anim	-670.038208 295.850220 -150.240417	0.000 -25.801 0.000	6006	NPC_Citizen
```

6006 is the left footstep, 6007 is the right one.
