### ISSUE TITLE
Bugs with ai nodes on gm_construct, gm_flatgrass

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#3732]
Most of ai_nodes don't work on map gm_flatgrass
And some issues with gm_construct
![construct](https://user-images.githubusercontent.com/10911451/52071120-68316a80-2593-11e9-9d96-ffe6baa7d634.jpg)
![flatgrass](https://user-images.githubusercontent.com/10911451/52071121-68ca0100-2593-11e9-81f3-b5f994e12170.jpg)
![construct3](https://user-images.githubusercontent.com/10911451/52071123-68ca0100-2593-11e9-9581-0f8b3e5c9e71.jpg)
![construct2](https://user-images.githubusercontent.com/10911451/52071124-68ca0100-2593-11e9-84f7-0e127b8a2628.jpg)
![constuct4](https://user-images.githubusercontent.com/10911451/52071319-c3635d00-2593-11e9-9c56-80fd7373f01c.jpg)

**Comment by Cthutq295** [comment]
https://github.com/Facepunch/garrysmod-issues/issues

**Comment by Combine900** [comment]
i would recommend too node the whole map on gm_flatgrass i do it on every l4d map i push.. on flatgrass it would take me 2-5 mins? not that much time ^^,

**Comment by robotboy655** [comment]
This took way too much time, but I adjusted the nodegraph on gm_construct and remade it for gm_flatgrass, altho NPCs on the latter may still fail to pathfind, possibly due to the distance between nodes.

**Comment by thegrb93** [comment]
Can you also https://developer.valvesoftware.com/wiki/Func_viscluster gm_flatgrass? Greatly increases performance.

**Comment by thegrb93** [comment]
I put that one https://github.com/Facepunch/garrysmod-issues/issues/3799
