### ISSUE TITLE
Water overlay not updating while entering airboat/chairs

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/garrysmod-issues#3733]
If you are underwater and enter an airboat that is above water, you will see underwater overlay.
If you are above water and enter an airboat that is underwater, you will not see underwater overlay.

This happens with the airboat, pod, and chairs.
This does not happen with the jeep or jalopy.

**Comment by robotboy655** [comment]
I cannot confirm this. The water overlay texture updates properly on my end, both in singleplayer and multiplayer.

Still, player's WaterLevel() was not updating in those vehicles so I have fixed that.
