### ISSUE TITLE
Linux x64 Can not import spray

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3735]
OS: Ubuntu 18.04
Branch: x86-64

Importing a custom spray from the option menu results in the following error:

![error](https://user-images.githubusercontent.com/18466226/52127619-7ed6d080-262a-11e9-96d3-39896134e1a7.png)

On master it works with the same image (even though there the image preview is also the black-
purple error image, but it works ingame).

Started with `-noworkshop -noaddons`.

**Comment by willox** [comment]
Should be fixed after the next update
