### ISSUE TITLE
Lua: Case-sensivity regarding DFileBrowser, file.Rename and File.Exists

### ISSUE THREAD

**Issue by Wuerstchen** [Facepunch/garrysmod-issues#3736]
"file.Rename" and "file.Exists" seem to ignore case-sensivity on Linux, causing them to not find or find the wrong files. file.Rename wrongly expects file names to be lowercase.
DFileBrowser also doesn't care about case-sensivity. I'm not sure, but I think that was different some time ago.

### An example with file.Rename:

It's especially an issue here, because file.Write can write uppercase files, but file.Rename cannot rename them.

Code snippet:

    print( "Attempting to rename file: "..SelectedFile.." to "..CurrentRenameFilePath..CurrentRenameFile )
    file.Rename( string.sub( SelectedFile, 6 ), CurrentRenameFilePath..CurrentRenameFile )

Console output:

    Attempting to rename file: data/Neue Datei.txt to Neu.txt
    Unable to rename **/media/wd5000aakx/Steam/steamapps/common/GarrysMod/garrysmod/data/neue datei.txt to /media/wd5000aakx/Steam/steamapps/common/GarrysMod/garrysmod/data/Neu.txt!

**Comment by robotboy655** [comment]
This is intentional for ```file.Rename``` and ```file.Exists```, I guess there's a problem with ```file.Open``` (```file.Write```)

**Comment by robotboy655** [comment]
I have forced file.Open to always look for lower case path. Please test this and let me know if it causes any problems, may need to restrict this to writing only.

**Comment by Wuerstchen** [comment]
Yes, this fixes the issue. Thank you!
