### ISSUE TITLE
Linux x64 Strange colors

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3738]
OS: Ubuntu 18.04, Nvidia 415.27
Branch: x86-64

On the x86_64 branch some colors of objects are different in contrast to master where they are fine.
One example is map ttt_forest_final (happens with every gamemode):

Bushes intended (master):
![green](https://user-images.githubusercontent.com/18466226/52175799-30980d80-27a1-11e9-8289-b045569286f2.jpg)

Bushes on x86_64:
![red](https://user-images.githubusercontent.com/18466226/52175801-37268500-27a1-11e9-976e-32db37570aa3.jpg)

**Comment by willox** [comment]
Does it happen in the same places as https://github.com/Facepunch/garrysmod-issues/issues/3551?

**Comment by MinIsMin** [comment]
I don't have Half-Life 2: Episode 2 so I can't test this, sorry.
