### ISSUE TITLE
weapon_pistol has wrong bullet spread when used by NPCs

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-issues#3742]
In Gmod, weapon_pistol has the same base bullet spread when used by NPCs as when used by players, but in HL2, that's not the case. 

I noticed that the singleplayer HL2 version of the pistol [has code for an NPC cone of fire](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/weapon_pistol.cpp#L63) that's [missing in the HL2MP version](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/hl2mp/weapon_pistol.cpp#L57), is that the cause? This issue wasn't always in Gmod, I think it appeared around the same time as the update that removed the separate ai_weapon_X entities, so it might've been an oversight when switching over to the new system.

To compare the spread in both games, I used the console to spawn an NPC and a bullseye on the map d2_coast_09:
`sv_cheats 1`
`setpos -108.632599 -6932.147461 -685.910156;setang 0.081161 -1.075717 0.000000;ent_create npc_bullseye targetname bullseye spawnflags 196608;ent_teleport bullseye`
`setpos -135.262466 -7134.390137 -437.659729;setang 84.721230 113.399162 0.000000;ent_create npc_metropolice targetname cop additionalequipment weapon_pistol`
`ent_fire cop setrelationship "bullseye D_HT 99"; setpos 182.249054 -6782.438965 -615.038635;setang -1.326636 -33.278183 0.000000;noclip;notarget`
![proficiency testing](https://user-images.githubusercontent.com/12566919/52250382-7d1c3f80-28ac-11e9-8821-0216c5984355.jpg)

I also checked to make sure it wasn't a problem with weapon proficiency instead, and it's not, the proficiency is still being applied:
```
local npc = ents.FindByName("cop")[1]
npc:SetCurrentWeaponProficiency(WEAPON_PROFICIENCY_POOR) //change this
```
![proficiency testing 2](https://user-images.githubusercontent.com/12566919/52252048-033c8400-28b5-11e9-80a8-00e84b428812.jpg)

**Comment by robotboy655** [comment]
Fixed
