### ISSUE TITLE
PVS Crash (Overflow?)

### ISSUE THREAD

**Issue by oninoni** [Facepunch/garrysmod-issues#3744]
### Details

I'm currently working on a "Camera" System using render.RenderView. For this to work i need to add PVS for the places where my cameras are. This seemed to work but when placed on a server with a lot of players it seemed to create crashes:

The end of the console log reads:

```
[16:31:00] area(1==50462976, 2==18) >= numareas (36):  Check if engine->ResetPVS() was called from ClientSetupVisibility
[16:31:00] Segmentation fault (core dumped)
[16:31:00] cat: hlds.8.pid: No such file or directory
[16:31:00] email debug.log to linux@valvesoftware.com
[16:31:00] Tue Feb  5 16:31:00 UTC 2019: Server Quit
```

### Steps to reproduce

You can probably reproduce it by adding a lot of PVS to a server full of people. (Bots don't work because they don't seem to trigger PVS Calls)

```lua
hook.Add("SetupPlayerVisibility", "EGMRPHolocam.PVSVisibility", function(ply, viewEntity)
    local cameras = EGMRPHolocam:GetCamerasInRange(ply:GetPos())
    for _, cameraId in pairs(cameras) do
        local camera = ents.GetByIndex(cameraId)
        if IsValid(camera) then
            local pos = camera:GetPos()
            if not util.IsInWorld(pos) then continue end
            if ply:TestPVS(pos) then continue end

            AddOriginToPVS(pos)
        end
    end
end)
```

This was the code i used. In our full server enviroment (~80-90 Players) there were about 20 cameras max being returned for the "EGMRPHolocam:GetCamerasInRange" Function. It seemed to work for some time but random crashes did happen a few times until we removed the Addon.

PS: The mentioned debug.log does not contain anything useful. Just:

```
----------------------------------------------
Start Line: ./srcds_linux -game garrysmod <Rest Of Start Command>
End of Source crash report
----------------------------------------------
```

**Comment by robotboy655** [comment]
This may not be fixable considering what you are doing and the error
```area(1==50462976, 2==18) >= numareas (36):  Check if engine->ResetPVS() was called from ClientSetupVisibility```

In the mean time you can try map_noareas 1 but I do not know how that will affect server performance.
Also could just use less AddOriginToPVS calls.

**Comment by oninoni** [comment]
Could you maybe expose more functions from the engine PVS Functionality so we are able to prevent this?

**Comment by Noiwex** [comment]
So, we've got yet another bullshit limit in the engine.

**Comment by oninoni** [comment]
I've just run into this problem again on a map i'm working on.
I'm using a lua integration for linked_portal_doors (Doors Addon) and it crashes, when i noclip outside the visleafes of the map. 
I've added the above validation, to check if a PVS is already loaded. This fixes it, since when you are are outside the visleafs alls PVS Areas are loaded.
My current suspicion is, that TestPVS does not include manually added Areas. This might explain why the above code crashes, since it might have 2 cameras in the same area and the system does not seem to like having the same area added more than once.

**Comment by robotboy655** [comment]
I think this was recently fixed.
