### ISSUE TITLE
Post processing effects screw up some HL1 textures

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3745]
Enable Color Modification and you'll see this
![default](https://user-images.githubusercontent.com/7527872/52426027-0470e980-2b1f-11e9-85e4-95c804804fa6.png)

**Comment by robotboy655** [comment]
Well I don't.

![image](https://user-images.githubusercontent.com/3299036/52483676-3173d980-2bbd-11e9-8044-f57900fdf876.png)

No matter what settings/presets I used.

Either share your video settings and the settings you used in the post processing tab (or the code) or there's nothing I can do about it.

**Comment by TheMostUpset** [comment]
![default](https://user-images.githubusercontent.com/7527872/52487762-267e7080-2be0-11e9-834d-c679361b01a3.png)

Post processing settings don't affect anything actually, it happens when the effect is enabled. Some people noticed that too, makes me think it depends on videocard or something (mine is Intel HD)

**Comment by thegrb93** [comment]
Yeah Intel HD is not ideal at all. Driver problem most likely.
