### ISSUE TITLE
Hitting button limit before brush/entity limit.

### ISSUE THREAD

**Issue by HelixCT** [Facepunch/garrysmod-issues#3747]
### Details
I am using 254 buttons on my map and when I try to run the map some of the buttons do not appear. As in they do not appear after compiling the map, when the map is compiled and I go to where the button should be it is not there and is not usable.

I will add the compile log after in a separate comment.

### Steps to reproduce
Create a quite a few buttons on the map on the development branch and see how many buttons appear and how many do not.

**Comment by robotboy655** [comment]
No compile log, no sample vmf.

Please add all the info you can when you report an issue. This report is near useless.

There is no limit on "buttons" as far as I know.

Also you didn't even specify what you mean by buttons. func_button? sandbox buttons? ???????
??????
