### ISSUE TITLE
MAX_MAP_BRUSHSIDES Limit Bug

### ISSUE THREAD

**Issue by veydart** [Facepunch/garrysmod-issues#3748]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by veydart** [comment]
in new update you add 
Increased limits:
MAX_MAP_ENTITIES - 8k to 20k
MAX_MAP_AREAS - 256 to 1024
MAX_MAP_BRUSHES - 8192 to 16384
MAX_NODES - 1500 to 4096
Displacements - 2048 to 5500
but when i start compile map - I`ve got an error MAX_MAP_BRUSHSIDES

**Comment by veydart** [comment]
Я не очень хорошо знаю английский, но получается суть вопроса в том, что я начал компилировать карту в pre relis ветке, мне выдало ошибку об ограничении

**Comment by Kefta** [comment]
MAX_MAP_BRUSHSIDES is a separate limit from those raised.

**Comment by veydart** [comment]
какой толк увеличивать те лимиты на которые влияют старые?
