### ISSUE TITLE
Face poser : not including the last flex controller

### ISSUE THREAD

**Issue by sabre12112** [Facepunch/garrysmod-issues#3749]
### Details
so, the problem start after the new update for garry's mod in 2017/2018 , don't remember which month, but remember that the last time i used the face poser on one of the tf2's model classes, noticed that the last flex isn't showing in the face poser option menu, even if i used the search bar for the flex, it won't show, but the flex is working as well!!

so, we found a new method to fix that option, but still gmod needs to be fixed for the face poser.

that's pretty much it for now, thank you for reading this topic! ^^

**Comment by robotboy655** [comment]
Fixed in Dev.

I will make sure this will get into the next update next week.

**Comment by sabre12112** [comment]
> Fixed in Dev.
> 
> I will make sure this will get into the next update next week.

Thanks for the response! ^^

**Comment by sabre12112** [comment]
Hello again Rubat! 👋 😊
how are you?
hope your doing well

I got a question about the Finger Poser tool, since the updates has came
and i've been thinking.

is there a specific names for the Finger poser can recognize, besides
"ValveBiped.Bip01_R/L_Finger0/1/2/3/4", cause i've noticed for the tf2
models, they have "bip_(the name of the finger)_0/1/2" name and the finger
pose can recieve that from the fingers.

if there was, can u give me the list of the Fingers that finger poser can
recognize?

and also, if there's an method, can you try to Update or make a new finger
poser tool, that it can recieve any finger name when the model does have
finger? and that would be much appreciated.

thanks a lot for reading the message, and have a wonderful day! 😁
.

**Comment by robotboy655** [comment]
There's no way to detect hands on all models automatically. That's why we do it manually.

You can find the full source code for the Finger Poser tool here:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/finger.lua

**Comment by sabre12112** [comment]
Jesus christ thats a lot of source coding.
Welp, i think i'll stick with porting models rather just setting down here
learning for tool source coding for about 24 hours, and getting the same
lua error coding.


But thanks for the information about tge fingers names, i'll add it to the
list.

**Comment by sabre12112** [comment]
hello there Rubat, good to contact you again! ^_^
i have came to ask something in the workshop has been going on recently
with other users as they upload addons to all source engine game, such as
garry's mod, l4d, l4d2, etc....
some of them are able to upload GIF instead of jpeg/jpg for the thumbnail,
and i kinda thought that if there's a specific way to do that.
so that's why i came here to you.

hope your having a wonderful day, enjoy :]

**Comment by Kefta** [comment]
@sabre12112 https://steamcommunity.com/sharedfiles/filedetails/?id=727014963

This repository is not for these kinds of questions though - in the future, ask in the Garry's Mod Discord server: https://discord.gg/gmod
