### ISSUE TITLE
Compile errors with new brush limit

### ISSUE THREAD

**Issue by waffles187** [Facepunch/garrysmod-issues#3751]
### Details
When compiling a map with over 8192 brushes, other limits pop up like "MAX_MAP_BRUSHSIDES" or "MAX_MAP_VERTS" and probably some others.

### Steps to reproduce
Compile a map with more than 8192 brushes.
[example vmf](https://drive.google.com/open?id=1YsHUBV9oKL-1fWcS8plwwVt0k9iaxVT4)

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1269

**Comment by waffles187** [comment]
didnt see that. whoops
