### ISSUE TITLE
Binary modules not working on Linux

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#3753]
### Details
Binary module file can not be found (run using `require`).
> Couldn't include file 'includes/modules/whynotfound.lua' (File not found)

### Steps to reproduce
- Compiled a blank binary module, exporting `int gmod13_open(void*)` and `int gmod13_close(void*)`.
[gmcl_whynotfound_linux.zip](https://github.com/Facepunch/garrysmod-issues/files/2867036/gmcl_whynotfound_linux.zip)
- Placed the `gmcl_whynotfound_linux.so` file into `./GarrysMod/garrysmod/lua/bin` folder.
- Make sure `gmcl_whynotfound_linux.so` has executable attribute/permission.
- Start singleplayer game (without any addons).
- Execute `sv_allowcslua 1;lua_run_cl require("whynotfound");` command from client console.

**Comment by willox** [comment]
name it `gmcl_whynotfound_linux.dll`` (i know)
