### ISSUE TITLE
Deleting barnacle while player is grabbed by tongue breaks player entity

### ISSUE THREAD

**Issue by doomtaters** [Facepunch/garrysmod-issues#3754]
### Details
This bug occurs when a player is caught on a barnacle NPC, and the barnacle is deleted.
Once this happens the player will be unable to enter vehicles or be hit by ray traces, until they rejoin the server.

### Steps to reproduce

1. Spawn barnacle on a ceiling somewhere
2. Get caught by its tongue
3. Delete the barnacle

**Comment by robotboy655** [comment]
Which barnacle? hl2 or hl1?

**Comment by doomtaters** [comment]
> 
> 
> Which barnacle? hl2 or hl1?

This is just using the vanilla hl2 barnacle. Where is the hl1 barnacle? I have hl:source mounted.

**Comment by Kefta** [comment]
It's not in the spawnmenu but its entity name is ``monster_barnacle``.

**Comment by robotboy655** [comment]
Fixed
