### ISSUE TITLE
util.KeyValuesToTable reads floating point numbers imprecisely

### ISSUE THREAD

**Issue by VortixDev** [Facepunch/garrysmod-issues#3755]
When util.KeyValuesToTable reads a floating point number, it does so with imprecision. To see this for yourself, you can run the following:
```lua
PrintTable(util.KeyValuesToTable[["test"{"test" "1.8"}]])
```
The 1.8 value is printed as 1.7999999523163.

**Comment by bigdogmat** [comment]
This is normal floating point inaccuracy due to `util.KeyValuesToTable` casting the number to a `float` internally. Guess it could be changed to use `double` to create less imprecision, though it's never going to be exactly `1.8`.

**Comment by VortixDev** [comment]
Agreed, though if double precision is used then at least the pre-display rounding performed by Lua will make it appear as if it is when printed.

**Comment by VortixDev** [comment]
Something else I notice:
```lua
PrintTable(util.KeyValuesToTable[["test"{"test" "1.08"}]])
```
Provides a result of 1.0799999237061, which does not seem to be the correct single precision representation of 1.08.

**Comment by robotboy655** [comment]
https://www.h-schmidt.net/FloatConverter/IEEE754.html

Floating point math is like that. The value shown is correct.

**Comment by VortixDev** [comment]
@robotboy655 When I try 1.08 for myself in the calculator, I get 1.08000004291534423828125. I get the same result printing 1.08 in C.
