### ISSUE TITLE
Changelevel doesn't call -> Client "Nyaaa" connected (IP) so i know if i connected or not to my server!

### ISSUE THREAD

**Issue by Nyaaaa** [Facepunch/garrysmod-issues#3757]
Changelevel doesn't call -> Client "Nyaaa" connected (IP) so i know if i connected or not to my server!

It just shows
] changelevel gm_construct
---- Host_Changelevel ----
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
Executing dedicated server config file server.cfg

**Comment by robotboy655** [comment]
I don't remember anything by default displaying IP addresses.

**Comment by VortixDev** [comment]
Changelevel doesn't disconnect clients, it just transitions them to a new map, so you wouldn't be expected to see the connection message appear. You should, however, see disconnection messages for those who don't see the map transition through. Additionally, if someone joins the server during a changelevel transition (i.e. someone connects who wasn't in the server prior to the changelevel), you will see their connection printout.

**Comment by Nyaaaa** [comment]
Yeah will it be added Robotboy? I mean on the server not clientside when changing map it's the default connect msg! I would've liked to see it!

**Comment by robotboy655** [comment]
No? there's literally no point in that message on a changelevel.
