### ISSUE TITLE
trigger_vphysics_motion always starts enabled.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3759]
### Details
trigger_vphysics_motion always starts enabled even if it has the key value "StartDisabled 1"

### Steps to reproduce
Run following code:
```
map ep1_citadel_01
lua_run for k,v in pairs(ents.FindByClass("trigger_once")) do if v:GetPos() == Vector(-2658, 1377, 2576.86) then v:Remove() end end
setpos -2684.800781 1312.121338 2528.031250;setang 1.187993 94.161545 0.000000
```
This removes the trigger that would normally enable it and then puts you at the right pos and then try to move.

**Comment by ZehMatt** [comment]
I believe this line is missing
```
pPhysics->EnableCollisions(m_bDisabled == false);
```
after this line https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/triggers.cpp#L4360

**Comment by robotboy655** [comment]
I am supposed to move very slowly after I enter those commands right?

Because I don't move slowly if I enter those commands.

I do see prediction errors in that trigger in multiplayer tho when jumping

**Comment by ZehMatt** [comment]
The prediction errors are natural since it never had MP support. But the issue is that it has collisions enabled when its spawned with "StartDisabled" key value set to 1. Currently to compensate the issue I'm doing this:
```
trigger:Fire("Enable") -- Sets m_bDisabled = false, pPhysics->EnableCollisions(true)
trigger:Fire("Disable") -- Sets m_bDisabled = true, pPhysics->EnableCollisions(false)
```
If you were to just fire "Disable" it will not disable the collisions because the state is already set but it never set the collision state.

**Comment by ZehMatt** [comment]
Demonstration of the whole thing https://share.epic-domain.com/2019-02-22_15-42-59c02246d4aeb19142d.webm
As you can see in the video its not supposed to do that, it will vanish by firing Enable,Disable

**Comment by robotboy655** [comment]
Applied the proposed fix, lets see if it breaks anything else.

**Comment by ZehMatt** [comment]
Thank you, I will test it and see if anything weird shows up.

**Comment by ZehMatt** [comment]
Working as intended now. Thanks again.
