### ISSUE TITLE
Linux ingame news unclickable

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3760]
OS: Ubuntu 18.04
Branch: public

When clicking a link in the ingame news feed nothing happens.

Probably the browser should open with the news.

**Comment by robotboy655** [comment]
Do you have Steam Overlay enabled?

Does pressing the version number open anything?

**Comment by MinIsMin** [comment]
No Steam Overlay 

Nothing happens

If it should open via Steam browser, probably a fallback would be good (just launching the url as "process" and let the os handle the url)

**Comment by robotboy655** [comment]
It's meant to open in the overlay. If you do not have that enabled, obviously it will not work. Maybe a fallback should be added

**Comment by Python1320** [comment]
Can you provide us with a function that returns whether overlay is installed or not? gui.OpenURL is wholly useless without it.

**Comment by robotboy655** [comment]
gui.OpenURL now uses a fallback derma HTML panel when Steam overlay is not available.
