### ISSUE TITLE
Alt ammo display clips with numbers >= 10

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3762]
![xdntbpp](https://user-images.githubusercontent.com/4593679/53039191-3a2da080-3444-11e9-9dde-4d2def46ac0c.png)

Probably since no HL2 weapons were intended to have alt ammo > 8 with old max ammo limits. I'm on 1920x1080.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/66418220-47ff5880-ea0a-11e9-968b-f9334608fa7e.png)
This is the best I can do with the static configuration. (ignore the ammo type icons)
Side effect is it doesn't look exactly like the HL2 HUD does and it looks off with single digits now:
![image](https://user-images.githubusercontent.com/3299036/66418339-8c8af400-ea0a-11e9-8493-bf4c8464f550.png)

**Comment by Kefta** [comment]
Shame the dimensions are hardcoded so the box can't resize with the numbers.
