### ISSUE TITLE
OnEntityCreated Issues for LocalPlayer After Feb 2019 Update

### ISSUE THREAD

**Issue by 3Pills** [Facepunch/garrysmod-issues#3763]
### Details
Previously the LocalPlayer() variable used to return the LocalPlayer entity when that entity was being created on the clientside. Now LocalPlayer() is [NULL Entity] during this hook in this scenario.

### Steps to reproduce
1. Create a custom gamemode
2. Place the following hook inside your shared.lua:
```lua
function GM:OnEntityCreated(ent)
        if (CLIENT and ent == LocalPlayer() ) then
		-- Do something special for LocalPlayer()
                -- No longer works after February 2019 Update!
	end
end
```

**Comment by robotboy655** [comment]
Yeah it is because of the player class changes, OnEntityCreated is called earlier than it used to.

Not sure what to do about this one, but I can tell you one thing, OnEntityCreated is a terrible horrible hook and you should avoid using it, it is not called when an entity is ACTUALLY created, its called when an entity is first pushed to Lua.

**Comment by WinterPhoenix96** [comment]
What would you suggest to use instead, for when an Entity is created after InitPostEntity is run, on the Client?

https://wiki.garrysmod.com/page/GM/NetworkEntityCreated ?

**Comment by Kefta** [comment]
Is this resolved now with https://github.com/Facepunch/garrysmod-requests/issues/1290?

**Comment by robotboy655** [comment]
No, the hook still has problems with clientside entities, namely players which I will need to resolve asap.

**Comment by mcNuggets1** [comment]
So are all lua functions available without a 0 timer now?

**Comment by Kefta** [comment]
What functions aren't? And what does that have to do with this issue?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3127 is not fixed by these changes.

**Comment by mcNuggets1** [comment]
Okay, thanks.

**Comment by robotboy655** [comment]
Should be solved on Dev.
