### ISSUE TITLE
HTTP Requests broken, sends everything as GET

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#3764]
This issue started around 11th or 12th of February 2019. All http requests sent via either http.Post or HTTP are being sent as GET despite specifying POST.

Might be false alarm, hold on.

**Comment by robotboy655** [comment]
As I already said, nothing about it was changed. The changes on 11th and 12th were hls related.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/53105460-dab1bc80-3539-11e9-9483-c9dff3e74f38.png)

It just is most definitely not a problem on GMod's end.
