### ISSUE TITLE
render.DrawScreenQuad(Ex) throws a Lua error when there's no active material

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3767]
```
] lua_run_cl render.DrawScreenQuadEx()
render.DrawScreenQuadEx - No Material!
[code_gs|2|STEAM_0:0:32955110] Lua Error:
render.DrawScreenQuadEx - No Material!
```

This is inconsistent with other render functions which will DevErr ``Programming error: CMatRenderContext::Bind: NULL material`` and allow execution to continue. I don't think being unable to draw should be a halting error.

**Comment by robotboy655** [comment]
It doesn't look like a halting error to me. 
```
local ourMat = Material( "models/wireframe" )
hook.Add( "HUDPaint", "example_hook", function()
	//render.SetMaterial( ourMat )
	render.DrawScreenQuad( )
	render.DrawScreenQuadEx( 100, 100, 256, 256 )
	
	surface.SetDrawColor( 255, 255, 255, 255 )
	surface.SetMaterial( ourMat	) -- If you use Material, cache it!
	surface.DrawTexturedRect( 0, 0, 512, 512 )
end )
```

The textured rect does get drawn for me. Neither does this code produce the "Something is creating script errors" pop up.

Without this message there's no way for people to figure out why it is not drawing as the DevErr you mention does not apply to these functions.
