### ISSUE TITLE
ENT:OnTakeDamage() crash

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [Facepunch/garrysmod-issues#3769]
If u use entity:TakeDamageInfo(damage) in ENT:OnTakeDamage instead of ENT:TakePhysicsDamage(damage) it will crash server

**Comment by bigdogmat** [comment]
`TakeDamageInfo` will call `OnTakeDamage`, so I imagine you're creating in infinite loop.

**Comment by Kefta** [comment]
``TakePhysicsDamage`` doesn't call ``OnTakeDamage`` for whatever reason, but @bigdogmat is right about ``TakeDamageInfo``. I've added warnings to all the relevant wiki pages and put an example of how to avoid crashes on [OnTakeDamage](https://wiki.garrysmod.com/page/ENTITY/OnTakeDamage)'s page.

**Comment by eLeCtrOssSnake** [comment]
I think it solved so I'll close it.
