### ISSUE TITLE
Entity:TakePhysicsDamage doesn't call ENT:OnTakeDamage

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3770]
Test entity:
```
AddCSLuaFile()

ENT.Type = "anim"
ENT.Spawnable = true
ENT.Model = "models/props_c17/oildrum001.mdl"

function ENT:Initialize()
	self:SetModel(self.Model)
	
	if (SERVER) then
		if (self:PhysicsInit(SOLID_VPHYSICS)) then
			self:GetPhysicsObject():Wake()
		end
	end
end

function ENT:OnTakeDamage()
	print("took damage")
end
```

When looking at the entity:
```
] lua_run Entity(1):GetEyeTrace().Entity:TakePhysicsDamage(DamageInfo())
> Entity(1):GetEyeTrace().Entity:TakePhysicsDamage(DamageInfo())...
] lua_run Entity(1):GetEyeTrace().Entity:TakeDamageInfo(DamageInfo())
> Entity(1):GetEyeTrace().Entity:TakeDamageInfo(DamageInfo())...
took damage
```

**Comment by mcNuggets1** [comment]
Take Physics Damage is reducing health?

**Comment by Kefta** [comment]
How would fixing this break addons? It just means the OnTakeDamage hook would actually be called for all kinds of damage instead of everything but physics damage.

**Comment by mcNuggets1** [comment]
As far as I know, the function doesnt deal damage at all, just accelerates the physics object, however I might be mistaken and if it really does damage, it will destroy half of the workshop, because nearly every addon including darkrp is calling TakePhysicsDamage within the OnTakeDamage hook.

**Comment by robotboy655** [comment]
It's not supposed to. As @mcNuggets1 stated, the function doesn't deal damage and is only used to move the physics object based on the Damage Force and Damage Position.
