### ISSUE TITLE
Entity:GetModelContents always returns CONTENTS_SOLID for studio models

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3772]
[This](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/ModelInfo.cpp#L465) line should be ``return modelinfo->GetStudiomodel(pModel)->contents;``

Fixing this also allows some engine hacks to be removed. [The studio model workaround in the gravgun](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/hl2/weapon_physcannon.cpp#L106-L116) can be removed and use the same method as brush models, and [physics objects can initialize their contents](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/physics_shared.cpp#L328) if they're tied to a studio model.

**Comment by robotboy655** [comment]
Changed GetModelContents to return the actual value.
