### ISSUE TITLE
Ragdoll Pick up / Intense Server Lag

### ISSUE THREAD

**Issue by SouthpawAnex** [Facepunch/garrysmod-issues#3775]
### Details
So about half an hour ago, whilst playing a normal round on TTT everyone started lagging as if we were being DDos'd, the pings tripled, the server would lag spike tremendously and occasionally begin to time out, but then cancel.

### Steps to reproduce
After some experimenting my server host provider CEO and some friends found out that whenever you pick up a ragdoll corpse everyone begins to lag and if you hold it too long the server slowly begins to crash via connection loss.

I have no idea where this came from as the only thing I have changed was enabling ttt_highlight_admins, but that couldn't be the cause. I have just run a Steam update (even though I was already up to date) and am about to check if the issue is still happening because a server restart didn't seem to resolve it.

Any help would be appreciated.

**Comment by mcNuggets1** [comment]
This is not a help forum.

**Comment by SouthpawAnex** [comment]
Could you direct me to the help forum then, please?

**Comment by mcNuggets1** [comment]
https://forum.facepunch.com/gmodhelp

**Comment by thegrb93** [comment]
@SouthpawAnex people are just going to tell you to uninstall mods until you figure out which one was causing it though.
