### ISSUE TITLE
Non-brush models don't initialize their physics object contents

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3777]
[This line](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/shared/physics_shared.cpp#L328) and [this line](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/physics_shared.cpp#L385) have to be removed. This will allow studio models to have matching physical contents to their model for more accurate ShouldCollide behaviour.

**Comment by robotboy655** [comment]
What do you expect to change from this? Anything in particular I can test?

**Comment by Kefta** [comment]
This will only be useful for ShouldCollide implementations that use physics object content comparison which will apply for the planned standalone physics objects.
