### ISSUE TITLE
Can't get off from the Airboat

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-issues#3779]
### Details
When I use the Airboat (usually for fun), I can't get off that whenever I press the Use key.

### Steps to reproduce
Spawn "Airboat" from Spawn Menu and get in, then try to get off by pressing Use key.

**Comment by Kefta** [comment]
This is not the place for support, go to https://forum.facepunch.com/gmodhelp

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://forum.facepunch.com/f/gmodhelp

**Comment by KirbyJoe** [comment]
@Kefta @robotboy655 I'm actually talking about a glitch that needs to be fixed, not asking for a help.

**Comment by Kefta** [comment]
Could you give more info on how to replicate it then? A video?
