### ISSUE TITLE
gmod window resizes to a very small window out of nowhere

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-issues#3784]
### Details
after i reloaded a map i was working on, the gmod window resized to this:
![image](https://user-images.githubusercontent.com/42521608/53960116-14fc8b80-40ee-11e9-8ae5-0886186caf3d.png)

before that i clicked on the window and it had 0 size.
this has happened twice, one in a server i mostly go on, months ago.

### Steps to reproduce
i have no way of reproducing this, it happened by itself, but it did happen after reloading a map or joining a server (twice)

**Comment by thegrb93** [comment]
Windows/Windows app issue? Never seen it.

**Comment by Andrew-Eathan** [comment]
can't be third party, it happened on two different computers (my house has two) but they both had windows 7
it can't be an update either since the first time it happened was somewhere in autumn

**Comment by thegrb93** [comment]
Hm, I use windows 10 so maybe that's why.
