### ISSUE TITLE
Game takes up 6+ gb of ram and then crashes.

### ISSUE THREAD

**Issue by taavilahti** [Facepunch/garrysmod-issues#3792]
### Details
When i try to join a server, the game freezes during loading and starts taking up almost 7Gb of ram. The game then crashes with no error messages.

System specs:
OS: Arch Linux
CPU: i5 8300H
GPU: GTX 1050 Mobile
RAM: 8gb

### Steps to reproduce
1. Join a server

**Comment by thegrb93** [comment]
AWsomium probably. Turn off add pac_enable 0 to your cfg/client.vdf

**Comment by Taavettiii** [comment]
pac_enable 0 did not help, still crashing.

**Comment by LarryTheBoss** [comment]
How many addons do you have installed?

**Comment by thegrb93** [comment]
I crash a ton when I use Linux too. I just use Windows.

**Comment by Bo98** [comment]
6+GB? I take you are using the 64-bit branch?

**Comment by Taavettiii** [comment]
i have ~250 addons installed.
i'm using no betas

**Comment by Taavettiii** [comment]
Tried using proton, game is still crashing but no longer takes up that much ram

**Comment by robotboy655** [comment]
Closing as stale and no information to work with.
