### ISSUE TITLE
ply:SendLua() results in a server crash

### ISSUE THREAD

**Issue by KiwontaTv** [Facepunch/garrysmod-issues#3794]
### Details
Tell us exactly what happens, every single detail that you can think of

When you send an empty SendLua to a player the server will crash.

### Steps to reproduce
Example:

ply:SendLua() (serverside)
---Server Crash---

**Comment by neico** [comment]
`lua_run print( player.GetByID( 1 ):SendLua() )`:
```
[ERROR] lua_run:1: bad argument #1 to 'SendLua' (string expected, got no value)
  1. SendLua - [C]:-1
   2. unknown - lua_run:1
```

`lua_run print( player.GetByID( 1 ):SendLua( "" ) )`:
![Engine Error - UserMessageBegin: New Message started before matching call to EndMessage](https://puu.sh/D4Zz0/68f6215fa9.png)

using x86-x64 branch on Windows 10 x64 running x64 gmod.exe

so it's at least still present in recent builds

**Comment by robotboy655** [comment]
Fixed
