### ISSUE TITLE
SWEP.DrawAmmo is ignored by engine HUD.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#3795]
### Details
Default HUD displays weapon's ammo regardless of what value SWEP.DrawAmmo is set to.
Affects both stable and dev branches.

### Steps to reproduce
1. (Optional) Launch GMod with `-noworkshop` and `-noaddons` parameters to make sure no addon interferes with that value.
2. Load into singleplayer, sandbox, any map.
3. Give yourself `weapon_medkit` since it's the only Lua weapon with ammo display that available without addons.
4. Type `sv_allowcslua 1; lua_run_cl LocalPlayer():GetActiveWeapon().DrawAmmo = false` in console to disable ammo drawing
5. Game still draws the ammo counter, ignoring the DrawAmmo value we set in the previous step.

**Comment by robotboy655** [comment]
Fixed

**Comment by YuRaNnNzZZ** [comment]
Yeah, it's working properly now on the dev branch. Thank you!
