### ISSUE TITLE
scripted_ents.GetList doesn't return ClassName vars for some reason

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3797]
### Details
] lua_run for _, v in pairs(scripted_ents.GetList()) do print(v.ClassName) end
> for _, v in pairs(scripted_ents.GetList()) do print(v.ClassName) end...
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil

The wiki says it returns the ENT table which should include ClassName.
weapons.GetList doesn include ClassName.
TESTED on vanilla sandbox.

### Steps to reproduce
lua_run for _, v in pairs(scripted_ents.GetList()) do print(v.ClassName) end

**Comment by robotboy655** [comment]
Literally all you had to do is PrintTable( v ) to see why that is.

The wiki documentation is a bit wrong ( I will fix it in a moment ), scripted_ents.GetList() is a bit different from weapons.GetList() because reasons.
