### ISSUE TITLE
Viscluster gm_flatgrass

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3799]
Can you also https://developer.valvesoftware.com/wiki/Func_viscluster gm_flatgrass? Greatly increases performance.

Large open environments should be visclustered because without it, the max leaf size is 1024 and creates tons of leafs. mat_leafvis 1 to see the hundreds of leafs in gm_flatgrass

**Comment by robotboy655** [comment]
We do not have sources for either of the default maps (ikr) so not really without degradation.

**Comment by thegrb93** [comment]
gm_flatgrass is the only one that needs it and is easy enough to decompile to its original state. I can do it and then you have it's source again (seriously how did you guys lose it?).

**Comment by thegrb93** [comment]
The valve dev page says it doesn't affect in-game visleafs, but I very well remember it improving a map before. I'll double check later tonight.

**Comment by thegrb93** [comment]
It doesn't affect the visleaf size, but it makes all of them assume visibility which I'm guessing reduced complexity of visibility calculations on the map I used it on. Don't think gm_flatgrass would benefit.

**Comment by thegrb93** [comment]
Cubemaps and a map boundary are needed still though

**Comment by thegrb93** [comment]
Makes compiling a hell of a lot faster though

**Comment by thegrb93** [comment]
[gm_flatgrass.zip](https://github.com/Facepunch/garrysmod-issues/files/3050145/gm_flatgrass.zip)
Here it is fully restored. Had to fix some things, made the spawn a func_detail, and added the viscluster

**Comment by thegrb93** [comment]
Can't benchmark because both reach 300fps cap
