### ISSUE TITLE
npc_metropolice won't respond to other players other than local one.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3800]
### Details
It will always use the first player index rather than the activator, see:
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/npc_metropolice.cpp#L3900
and 
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/npc_metropolice.cpp#L5159

### Steps to reproduce
Spam use on the cop not being the first player index.

So it would be cool if the actual activator would be passed.

**Comment by robotboy655** [comment]
Should be fixed, altho they still sometimes chase the wrong player and the teleport/overlay stuff on trainstation_02 is applying to all players, but I imagine that is more of a problem with the map.

**Comment by ZehMatt** [comment]
Yeah, thanks.
