### ISSUE TITLE
npc_metropolice won't chase players in multiplayer

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3801]
### Details
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/npc_metropolice.cpp#L3954

**Comment by robotboy655** [comment]
Should be fixed

**Comment by ZehMatt** [comment]
Thanks a lot, I already started hacking up my own together.
