### ISSUE TITLE
VRAD Incorrect lightmaps

### ISSUE THREAD

**Issue by dhog10** [Facepunch/garrysmod-issues#3803]
### Details
When compiling my modified version of downtown which I have iterated over for the past 4 years, strange lighting artifacts appeared all over the lightmap. The compile log was done in -fast and -final mode and neither logs produced any errors or warnings related to lighting. The lightmaps have huge dark areas resembling a large shadow covering huge areas of the map, however with further investigation it turns out that the ambient lighting information is bright in those areas.

It appears that the lightmaps are shaded in areas where they should be bright, and sometimes bright in areas where they should be dark. Compiling the map with no entities what so ever other than the sun still produces these ghost shadow artifacts, although less of them appear.

I have compiled this map using the CSS hammer and it works fine.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
I have failed to find any repro steps for making a map which demonstrates these issues, however I detailed my attempts to fix it and screenshots of the issue in a facepunch thread: https://forum.facepunch.com/gmodgd/bvrag/Huge-map-shadow-bug-dark-lightmaps-using-garrysmod-VRAD

You can analyse my compile logs in that thread to get an idea of how many brushes and entities are in my map, I can say that the map pushes limits such as the entdata and LDR ambient.

I am sure that this is a problem with the garrysmod VRAD because when i overrode it with the HL2 vrad.exe and vrad_dll.dll the problem was solved.

**Comment by robotboy655** [comment]
Can you send the .vmf my way? robotboy655@facepunchstudios.com

I can be however gutted/cut down as you want as long as the issue you are describing is happening.

**Comment by robotboy655** [comment]
Should be fixed in Dev.
