### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3804]
### Details
Error Vertex File for 'props_c17/light_domelight02_on.mdl' checksum 397824940 should be -935408350

This error extremely often appears and makes specific props invisible.
Especially after playing on a map and then visiting another.

### Steps to reproduce
Unknown how to reproduce

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2650

**Comment by Doommarine1991** [comment]
Error Vertex File for 'props_c17/door01_left.mdl' checksum 145318345 should be 972034250 (x264) spamms now......

**Comment by mr8109956-oss** [comment]
seems its still a bug.............this needs to be fixed its 2026
