### ISSUE TITLE
Crash: "Getting a dynamic mesh without resolving the previous one"

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#3805]
### Details
Not really sure what the crash message means or how it could be fixed, so I'm asking for insight here.

Crash Dump: https://winteris.moe/share/2019-04-05_14-03-13.mdmp

### Steps to reproduce
No apparent way found to reproduce, except that it happens **_sometimes_** after joining [GMod Cruise Line](https://www.gmodcruiseline.com/connect.html) and being on the server for a short while.

**Comment by robotboy655** [comment]
Crash dump is unfortunately useless, I'd imagine the error is caused by an addon messing about with the mesh library.

**Comment by robotboy655** [comment]
Closing as stale. If the issue happens again, please open a new report.
