### ISSUE TITLE
Crash (x86-64): "Client Lua Stack Leak [-1]"

### ISSUE THREAD

**Issue by WinterPhoenix96** [Facepunch/garrysmod-issues#3807]
### Details
Crash Dump 1: https://winteris.moe/share/2019-03-14_22-55-44.dmp

Crash Dump 2: https://winteris.moe/share/2019-04-03_16-18-39.dmp

### Steps to reproduce
Not entirely sure what causes it, but it seems to become more likely the longer GMod has been running, and when joining a server.

**Comment by willox** [comment]
Any suspicions at all on what causes this? Maybe HTTP requests, main-menu's addon browser, or changing level after something specific? I've not encountered this at all yet.

**Comment by WinterPhoenix96** [comment]
I've only found it to happen when GMod has been open for a long time (might literally be multiple days), its been connected to a server, and that server is changelevel-ing.

At least I think that's the scenario because honestly most of the time I've not been there to see it happen.

The generated TXTs aren't particularly useful, they're just:
```
Executable: F:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    *Not in Lua call OR Lua has panicked*

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*
```

If you want, you'll probably be able to recreate it if you have a GMod client sitting connected to [GMod Cruise Line](https://www.gmodcruiseline.com/connect.html) for long enough, but that's kind of a garbage way to go about it.

Let me know if I can do anything on my end to help.

**Comment by WinterPhoenix96** [comment]
Okay so quick update on this with some information that might be interesting; I just had it crash with this a couple of minutes after joining the server, so it wasn't _during_ changelevel-ing or joining but rather shortly after.

Furthermore, the Private Bytes in use by GMod at the time was suspiciously close to 8GB, so maybe that has something to do with it:
![image](https://user-images.githubusercontent.com/2799393/58150562-ff025f80-7c34-11e9-98f1-e061268c7bc2.png)

**Comment by willox** [comment]
I've added some code to catch the cause of this. You'll hopefully start seeing a different error message that'll result in useful dumps.

**Comment by WinterPhoenix96** [comment]
I finally got a crash for this again. The message was "Lua Stack underflow, boo"

Here's the crash dump:
https://winteris.moe/share/2019-06-12_07-52-12.dmp
https://winteris.moe/share/2019-06-12_07-52-16.txt

**Comment by willox** [comment]
Oh, I fixed this on the dev branch a while back. It'll be fixed on x86-64 next time I merge it (not too soon.)

**Comment by WinterPhoenix96** [comment]
Ah, alright, good to hear.
