### ISSUE TITLE
Crash (x86-64): Various Crashes that occur after GMod has been running for a while

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#3808]
### Details
Crash Dump 1: https://winteris.moe/share/2019-03-14_22-55-08.dmp
 
Crash Dump 2: https://winteris.moe/share/2019-03-25_16-42-07.dmp

Crash Dump 3: https://winteris.moe/share/2019-03-27_15-07-35.dmp

### Steps to reproduce
These seem to happen after GMod has been running for a while, as in multiple days, staying in a single server and rejoining that server every 2-8 hours. Might be something as simple as running out of memory, but I'm not sure, so I'm posting them here.

**Comment by robotboy655** [comment]
2 of the crashes are vphysics, maybe related to source save/load system, last one is a memory related crash

**Comment by robotboy655** [comment]
Closing as stale.
