### ISSUE TITLE
env_projectedtexture does not affect on entities with ENTITY:SetNoDraw( true )

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#3809]
On right entity `ENTITY:SetNoDraw` set to `true`. Used `ENTITY:DrawModel()` for drawing.

https://youtu.be/j9BafUbeuEA

**Comment by thegrb93** [comment]
Makes complete sense. Maybe use engine/writez material on the entity instead. It will provide needed depth for the projected texture and won't draw anything else.

**Comment by ShadowBonnieRUS** [comment]
Basically, it is used to display cached clientside models only in certain positions more than 1 time without render.Model.

**Comment by robotboy655** [comment]
Related issues: https://github.com/Facepunch/garrysmod-issues/issues/2301 https://github.com/Facepunch/garrysmod-issues/issues/3029

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/render.RenderFlashlights

Added this function (example included) that should solve the issue for you.
