### ISSUE TITLE
Linux libgpg-error.so.0 wrong ELF class CLASS64

### ISSUE THREAD

**Issue by x7rgaming** [Facepunch/garrysmod-issues#3812]
### Details
On game startup I get this error message:
`Couldn't load: garrysmod/bin/client.so
Reason: libgpg-error.so.0: wrong ELF class: CLASS64`

There are no logs in /tmp/dumps
But i enabled strace in hl2.sh:
[strace.log](https://github.com/Facepunch/garrysmod-issues/files/3077975/strace.log)

### Steps to reproduce
1. Start Garry's mod
2. Crash

**Comment by robotboy655** [comment]
What OS? (version, 32/64bit), have you tried or are you on any Beta branches for Garry's Mod?

If not, try the x86-64 branch on Steam for Garry's Mod.
If you are running outdated OS, update it and try again.

**Comment by x7rgaming** [comment]
Ubuntu 18.04.2 LTS 64bit.
Reinstalling my OS fixed the issue thanks.
