### ISSUE TITLE
PlayerLeaveVehicle not called on disconnect

### ISSUE THREAD

**Issue by Badger9** [Facepunch/garrysmod-issues#3813]
### Details
When a player is inside of a vehicle then disconnects without exiting the vehicle PlayerLeaveVehicle is not called.

### Steps to reproduce
Get in a vehicle and disconnect.

**Comment by ArnyDaHamsta** [comment]
Can you not do a check on disconnect and call PlayerLeaveVehicle with hook.call?

**Comment by thegrb93** [comment]
You could, but if every addon that needed it do so, you'd get a bunch of PlayerLeaveVehicle calls when a player disconnects. It should be part of gmod's core instead.

**Comment by Kefta** [comment]
@thegrb93 It's already called when the vehicle is deleted with ent:Remove(), so I think it should also be called on disconnect.

**Comment by thegrb93** [comment]
The player does leave the vehicle when the vehicle is deleted though. I think trying to do the same the other way around might lead to too many issues, but idrk.

**Comment by Kefta** [comment]
No animation, some vehicles play a stop engine sound but that would just not be played during shutdown anyway.

**Comment by DBotThePony** [comment]
was about to report this but found this report

**Comment by robotboy655** [comment]
Should be fixed.
