### ISSUE TITLE
Issuing the command map after being on a MP server crashes the game

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#3814]
### Details
When you attempt to start a singleplayer game via the 'map' concommand after being on a multiplayer server, the game will crash with the following error:

> Error loading gamemode!
> Gamemode "xxx" doesn't exist!

### Steps to reproduce
Join a MP server, then do "map gm_construct" at any point and your game should crash with the above error. 

This happens in live and at time of writing, dev.

**Comment by neico** [comment]
This also happen in a lot of source games, I believe that's a GameUI issue.
Tough I'd expected GMod not to have that since most of that stuff is in-Lua / JS by now.

**Comment by robotboy655** [comment]
Should be fixed. Has nothing to do with GameUI
