### ISSUE TITLE
Cannot set background color on DCategoryList

### ISSUE THREAD

**Issue by ElectricityMachine** [Facepunch/garrysmod-issues#3815]
### Details
I am in the process of experimenting with Derma and VGUI. I am trying to create a DCategoryList with DCollapsibleCategory members. However, every time I create this panel, I am unable to set the background color. The print function returns the correct color value, however this is not the case when looking in game. Screenshot and code attached.

```
--DPanel is a passed panel. It is of type DScrollPanel
DPanel:SetSize(600, 355)

local list = vgui.Create("DCategoryList", DPanel)
list:SetBackgroundColor(Color(0,0,0,0))
print(list:GetBackgroundColor())

```

Console Output:
![image](https://user-images.githubusercontent.com/47489506/56311910-0eb1f400-611d-11e9-8743-ae832bbab58e.png)

Version:

![image](https://user-images.githubusercontent.com/47489506/56312017-4751cd80-611d-11e9-98c0-da9539acd056.png)

In-game GUI:

![image](https://user-images.githubusercontent.com/47489506/56312317-e2e33e00-611d-11e9-85c7-f7d90349576a.png)

### Steps to reproduce

1. Create a new "DCategoryList" parented to a DPanel.
2. Try to set the background color of the "DCategoryList".
3. View the "DCategoryList" and confirm that the changes have not been made.

**Comment by neico** [comment]
It's actually using a internal DPanel as canvas to draw the list, and SetBackgroundColor isn't passed trough, try this:

```lua
list:GetCanvas():SetBackgroundColor( Color( 0, 0, 0, 0 ) )
```

**Comment by ElectricityMachine** [comment]
Hello! Thanks for your suggestion. Unfortunately, this didn't work with the function being a nil value. Seems strange to me.

"attempt to call method 'SetBackgroundColor' (a nil value)"

**Comment by Kefta** [comment]
Can you print out what GetCanvas returns? SetBackgroundColor is a function that should exist on all DPanels.

**Comment by robotboy655** [comment]
@Kefta https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/vgui/dscrollpanel.lua#L9 It ain't a DPanel
