### ISSUE TITLE
Crash dump (game suddenly crashed)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3817]
### Details
The game suddenly crashed for several people.
Multicore Rendering was enabled.
On a live dedicated server.

Crashed 3 times in 2 hours.
https://www.dropbox.com/sh/wblq8xw52wd07y2/AADXk7JvtDPnNVPMOeMNcDDta?dl=0

### Steps to reproduce
Unknown

**Comment by robotboy655** [comment]
2 of them are seemingly random different decal crashes, maybe related to models becoming invalid or something?
Last one is useless.

Again, dumps without steps to reproduce are mostly pointless.

**Comment by mcNuggets1** [comment]
There were no points to reproduce.
They just happened on a live server.

**Comment by thegrb93** [comment]
'related to models becoming invalid or something' sounds like outfitter/pac3

**Comment by mcNuggets1** [comment]
Nothing pac3/outfitter related.

**Comment by thegrb93** [comment]
Are you saying neither is installed?

**Comment by mcNuggets1** [comment]
Yes, nothing is mounted via game.MountGMA either.
It's just FastDL + Workshop content preinstalled.

**Comment by Potatosayno** [comment]
I'm not sure but on my server we have multicore enabled too and people crash quite often.
I'll test this out for myself.
