### ISSUE TITLE
Constraints cannot be undone + undo.AddFunction malfunctions

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3819]
### Details
When creating a winch with just clicking twice on the world, a undeletable undo object appears in the undo list.

This also happens if a function is added using undo.AddFunction.
But this time, it just doesn't hide in the Undo Panel.

### Steps to reproduce
Create a winch on the world.
Try to delete the non existing winch or whatever constraint.

2. 
Add a function using undo.AddFunction.
Undo via Panel => Not removing the undo.

**Comment by robotboy655** [comment]
Both cases should be fixed on Dev.
