### ISSUE TITLE
PLAYER:SendLua() causes instant server crash.

### ISSUE THREAD

**Issue by eprosync** [Facepunch/garrysmod-issues#3820]
So i accidentally had SendLua to target myself without any arguments in it.
The result is it throws an error in lua for no string provided and then proceeds to crash the server.

Steps to reproduce:
```lua
PLAYER:SendLua()
```

**Comment by neico** [comment]
related and possible duplicated of #3794

**Comment by Kefta** [comment]
Fixed on the dev branch.
