### ISSUE TITLE
Problem with point_spotlight / SetParentAttachment

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#3821]
### Details
I'm trying to create an animated spotlight. I created a model, an animation and attached to the model env_projectedtexture + point_spotlight
### Steps to reproduce
With env_projectedtexture there are no problems, the movement is identical to the movement of the animation.
Point_spotlight behaves completely inadequate. The more animation oscillations occur, the more out-of-sync begins with the animation. For demonstration I attach the link to video.
https://www.youtube.com/watch?v=aaSuTVamZgQ
[bug.zip](https://github.com/Facepunch/garrysmod-issues/files/3109311/bug.zip)

**Comment by robotboy655** [comment]
I am not sure this can be fixed without making a new entity, which you are better off making yourself in Lua, it is just seems to be limited by the fact that it is a serverside only entity which spawns 2 other entities for the beam, and it just cannot update them quickly enough, while env_projectedtexture's effects are updated clientside.

I think the beam_spotlight entity from #1201 might work better for what you want, but it's only available in L4D so you can only test there.

**Comment by MARK2580** [comment]
> 

> I think the beam_spotlight entity from [Facepunch/garrysmod-requests#1201](https://github.com/Facepunch/garrysmod-requests/issues/1201) might work better for what you want, but it's only available in L4D so you can only test there.

Yes, I know about the existence of beam_spotlight, it was just made for such a purpose as in my case. In aliens swarm it is not ??? And I honestly did not understand the meaning of the new input "ForceUpdate" that says "Force an update of the spotlight position and orientation" but nothing happens in the game, should this input be used somehow specifically?

**Comment by robotboy655** [comment]
Yeah it would seem beam_spotlight works well for this in my test on that map, so I will do my best to not forget to include it into the next update.

**Comment by robotboy655** [comment]
The new entity is in the next update.
