### ISSUE TITLE
Rollermine and Barnacle crash on contact

### ISSUE THREAD

**Issue by Rowdye** [Facepunch/garrysmod-issues#3822]
### Details

**If the player puts a rollermine directly underneath a barnacle (without it getting caught by the tongue) and the rollermine zaps it, it'll crash all connected players to desktop, but not the server (this means a crash log cannot be produced)**

### Steps to reproduce

**Spawn a barnacle on any ceiling
Spawn a rollermine
Grab the rollermine with the physgun
Move the rollermine to where it'll get caught in the barnacle's tongue but also hit the actual barnacle itself
Congratulations, you just caused a server to lose all of its players within seconds!**

This issue has been around for quite a while, me and a friend were messing around in our P2P sandbox game and we discovered this on complete accident. We then used it on some public servers to see if it actually works, and it does.

**Comment by Kefta** [comment]
Do the clients that crashed not produce a crash log?

**Comment by Hyrogenic** [comment]
I was able to reproduce this crash issue. It's valid. 

![Alt Text](https://media.giphy.com/media/l0jnkxPg9FG1RpmLYy/giphy.gif)

**Comment by robotboy655** [comment]
Fixed
