### ISSUE TITLE
surface.CreateFont refuse to create fonts with size > 128

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3823]
### Details
I know this size is insane, but i actually use HalfLife2 font to draw default weapon's icons

### Steps to reproduce
```lua
surface.CreateFont('testfontsize', {
	font = 'HalfLife2',
	size = 128
})

surface.CreateFont('testfontsize2', {
	font = 'HalfLife2',
	size = 244
})

hook.Add('HUDPaint', 'fonts', function()
	surface.SetTextColor(255, 255, 255)
	surface.SetTextPos(100, 100)
	surface.SetFont('testfontsize')
	surface.DrawText('q')
	
	surface.SetTextColor(255, 255, 255)
	surface.SetTextPos(200, 100)
	surface.SetFont('testfontsize2')
	surface.DrawText('q')
end)
```

![hl2_22-35-34-3347ad6](https://user-images.githubusercontent.com/6339511/56748666-749c1c80-67aa-11e9-9170-2a31f1c4db36.png)
![hl2_22-34-34-77840b3](https://user-images.githubusercontent.com/6339511/56748639-664e0080-67aa-11e9-8d4b-a5980b392eea.png)
![hl2_22-34-45-610658e](https://user-images.githubusercontent.com/6339511/56748640-66e69700-67aa-11e9-9fff-66fc5ad634d3.png)
![hl2_22-35-05-7cee406](https://user-images.githubusercontent.com/6339511/56748641-66e69700-67aa-11e9-819f-8011df52c2d1.png)

**Comment by robotboy655** [comment]
Not a bug, this is done intentionally, although I will increase the maximum value to its absolute limit, which is 255.

**Comment by roboderpy** [comment]
I am super late, but after your changes when some symbols inside fonts become a bit bigger than they were previously at font limit just don't render at all.
