### ISSUE TITLE
NPCs dont respect SWEPs data.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3827]
### Details
It seems as NPCs dont quite respect the data specified for
```
AccessorFunc( SWEP, "fNPCMinBurst",     "NPCMinBurst" )
AccessorFunc( SWEP, "fNPCMaxBurst",     "NPCMaxBurst" )
AccessorFunc( SWEP, "fNPCFireRate",     "NPCFireRate" )
AccessorFunc( SWEP, "fNPCMinRestTime",  "NPCMinRest" )
AccessorFunc( SWEP, "fNPCMaxRestTime",  "NPCMaxRest" )
```

### Steps to reproduce
Create a SWEP that has autofire and give it to the NPC, setting any value for those variables makes no difference.

**Comment by Kefta** [comment]
Rubat mentioned they didn't work a while back in https://github.com/Facepunch/garrysmod-requests/issues/933.

**Comment by ZehMatt** [comment]
I see, would nice to get it fixed, closing it as its a dupe.
