### ISSUE TITLE
FastDL map case-sensitiveness

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#3829]
### Details
The map reported by the server should have the same case as the loaded filename, rather than what was input by the map or changelevel concommands

### Steps to reproduce
1. Have map gm_testmap (lowercase)
2. `changelevel gm_TestMap` (with wrong casing, on windows)

Outcome: Clients try to download gm_TestMap
Expected: Clients download gm_testmap

**Comment by robotboy655** [comment]
There isn't a way that I can see to get the real filename, so I ended up just force lowercasing it, since 99% of the maps are all lowercase anyway.
