### ISSUE TITLE
npc_barnacle never dies technically

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3830]
### Details
`npc_barnacle` never die

### Steps to reproduce
1. Spawn a barnacle
2. Kill it
3. Use anything to determine whenever it is dead or something.

https://wiki.garrysmod.com/page/NPC/GetNPCState return `NPC_STATE_NONE` when barnacle is dead (when it should `NPC_STATE_DEAD`)
Barnacle does not fire `OnNPCKilled` hook
Barnacle has negative health
Attempting to `:GetSaveTable()`, removing the barnacle, then

```lua
local barnacle = ents.Create('npc_barnacle')

for key, value in pairs(previousSaveTable) do
	barnacle:SetSaveValue(key, value)
end

barnacle:Spawn()
barnacle:Activate()
```

will spawn immortal, negative healthed barnacle
(example above on any builtin NPC within `NPC_STATE_DEAD` will produce expected results. For example on zombie: if you do this copy while zombie is in `NPC_STATE_DEAD`, on respawn using code above it will die in-place, probably even spawning a jumping headcrab from his head)

**Comment by Kefta** [comment]
It's because ``CNPC_Barnacle::Event_Killed`` doesn't call the baseclass and the method itself doesn't set the NPC state. This can be fixed by just adding ``m_NPCState = NPC_STATE_DEAD;`` somewhere in the method. Really simple fix.

**Comment by GT-77** [comment]
yeah

**Comment by robotboy655** [comment]
Fixed
