### ISSUE TITLE
String table changes.

### ISSUE THREAD

**Issue by Kapppa** [Facepunch/garrysmod-issues#3832]
### Details
In todays update (30/4/19) the string table for a couple of weapons were updated. This includes Toolgun, Medkit, Fists, Manhack and, Flechette Gun. These are now all uppercase for their print names, making the look out of place.

I would recommend changing the string table follow the old version in the string table or make a new string table for the printname.

### Steps to reproduce
Update game.

**Comment by Kefta** [comment]
I agree, I didn't realise how they looked in the spawnmenu when I made the PR. However, this is not a "string table," that's not what that term means.

**Comment by mcNuggets1** [comment]
Yeah it's terrible.
