### ISSUE TITLE
Change list not working

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3833]
https://gmod.facepunch.com/blog/april-2019-update

**Comment by robotboy655** [comment]
FFS, define "not working", how is that not obvious? At least attach a picture...

Either way, it appears perfectly fine on my end.

**Comment by thegrb93** [comment]
Seems to be the proxy for the network I'm on. Opening it on my phone works.

**Comment by Bo98** [comment]
The page is kinda slow to load. The paint operation takes 1.5 seconds to run and is done 4 times. Though that doesn't explain how the proxy affected it.
