### ISSUE TITLE
OnEntityCreated hook on client is no longer called when "class C_ClientRagdoll" is created

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#3834]
Title says it all, the OnEntityCreated hook no longer is called for "class C_ClientRagdoll"

Make an OnEntityCreated hook and simply call print(OBJ) when killing an npc, it won't print the object for the client ragdoll.

**Comment by MagentaIris** [comment]
Can be fixed and rectified by simply using CreateClientsideRagdoll instead.

**Comment by PYROTEKNIK** [comment]
this doesn't work for nextbots. the OnKilled function only happens serverside.
