### ISSUE TITLE
RemoveAllDecals does nothing on func_doors

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3838]
### Details
I've tried removing decals from a func_door surface.
But the function did nothing, on the client or the server.
I called it on both realms multiple times.

### Steps to reproduce
lua_run for k,v in pairs(ents.FindByClass("func_door")) do v:RemoveAllDecals() end
lua_run_cl for k,v in pairs(ents.FindByClass("func_door")) do v:RemoveAllDecals() end

**Comment by robotboy655** [comment]
What decals are you expecting to be removed.

**Comment by mcNuggets1** [comment]
The decals on the surface of the entity im calling it on.
That's what the function is supposed to do, I guess.

**Comment by robotboy655** [comment]
I mean map decals, or bullet holes or what?

**Comment by mcNuggets1** [comment]
Bullet decals, Blood etc.

**Comment by mcNuggets1** [comment]
So I've tested.
It only doesn't work with func_doors.

**Comment by robotboy655** [comment]
Yeah Valve never implemented this for brush models.

**Comment by Kefta** [comment]
Here's a brush model implementation:
```
// Put in engine/decal.h and engine/r_efxextern.h
void R_DecalRemoveEntity( int entity );

// Put in engine/r_decal.cpp
void R_DecalRemoveEntity( int entity )
{
	for ( int i = 0; i < s_aDecalPool.Count(); ++i )
	{
		decal_t* pDecal = s_aDecalPool[i];
		
		if ( (int)pDecal->entityIndex == entity )
			R_DecalUnlink( pDecal, host_state.worldbrush );
	}
}

// Put in c_baseentity.cpp
void C_BaseEntity::RemoveAllDecals( void )
{
	int modelType = modelinfo->GetModelType( model );
	
	if ( modelType == mod_studio )
	{
		CreateModelInstance();
		modelrender->RemoveAllDecals( m_ModelInstance );
	}
	else if ( modelType == mod_brush )
	{
		// This should probably run through another abstraction layer in r_efx
		// but whatever, Valve is inconsistent anyway
		R_DecalRemoveEntity( entindex() );
	}
}
```

**Comment by mcNuggets1** [comment]
You should get hired by FP. <3

**Comment by Kefta** [comment]
Whoops I dereferenced a nullptr, fixd

**Comment by KingofBeast** [comment]
![image](https://user-images.githubusercontent.com/6315796/57348761-e49c9200-711c-11e9-9b7a-58b8433a988a.png)

**Comment by robotboy655** [comment]
Seems to work.
