### ISSUE TITLE
Weld tool doesn't have "nocollide" ConVar

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#3841]
According to SpawnMenu, Weld tool has "No Collide" checkbox.
![hl2_2019-05-07_01-31-12](https://user-images.githubusercontent.com/5685050/57259308-caed4300-7067-11e9-9b3a-0cc78410c43f.png)

But it's not defined in BuildPanel.
```lua
function TOOL.BuildCPanel( CPanel )
	CPanel:AddControl( "Header", { Description = "#tool.weld.help" } )
	CPanel:AddControl( "Slider", { Label = "#tool.forcelimit", Command = "weld_forcelimit", Type = "Float", Min = 0, Max = 1000, Help = true } )
end
```

So tool just use constant `false` instead of real CVar

```lua
-- Get client's CVars
local forcelimit = self:GetClientNumber( "forcelimit" )
local nocollide = false
```

[Source Code](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/weld.lua)

@robotboy655 
Was it intended?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/weld.lua#L281

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/weld.lua#L49

In the Source Code link.
