### ISSUE TITLE
Game crashed after using sound.PlayURL()

### ISSUE THREAD

**Issue by art-gur** [Facepunch/garrysmod-issues#3842]
### Details
After receiving a few errors from the bass and running a valid code, the game is crushed.
Dumps:
— https://drive.google.com/open?id=1AERsF83Lj10cFuYT73DXUZ2QXk-4gjg2
— https://drive.google.com/open?id=1lvxd-LNvQdSGMqu3U9E4116HCbCjBjpI

### Steps to reproduce
1) Start a singleplayer game or run local server
2) Run (lua_run_cl) invalid code a several times
```
sound.PlayURL("https://www.youtube.com/watch?v=MVITXvCuqeU", "mono", function(station, eid, emsg)
print(eid, emsg) -- eid: 41
end)
```
3) Run (lua_run_cl) valid code, minimal two times(Waiting for completion after the first time, run second)
```
sound.PlayURL("https://unrefs.me/BtcVvB:urd2rB", "mono", function(station, eid, emsg)
print(eid, emsg) -- nil, nil
station:SetPos(LocalPlayer():GetPos())
station:Play()
end)
```

**Comment by robotboy655** [comment]
I cannot reproduce this. Can you reliably reproduce this problem? If so, please try the Dev branch.

**Comment by ShadowBonnieRUS** [comment]
Yep, new bass can sometimes make crashes with errors. But this is randomly/there some chance to catch this. Metrostroi use often bass sounds, there is much easier to catch.

**Comment by robotboy655** [comment]
Please try the Dev branch.

**Comment by art-gur** [comment]
I got crush again without dump file.
Tried get crush on Dev, but It's works fine, also thx for commit which fixed invalid errors description.

**Comment by robotboy655** [comment]
So I am assuming the issue is fixed then.
