### ISSUE TITLE
EngTask for base_ai broken

### ISSUE THREAD

**Issue by ts-co** [Facepunch/garrysmod-issues#3844]
### Details
[EngTask](https://wiki.garrysmod.com/page/Schedule/EngTask) no longer works for NPC's that use base_ai. I read a few places on the Facepunch forums that this was caused due to Nextbot. If so, it would be nice for schedules to have full functionality again.

### Steps to reproduce
Anything that uses EngTask or EngineRunTask does not work. It won't produce any errors, it just simply will not work when doing StartSchedule.

**Comment by robotboy655** [comment]
I don't see anything obvious that would indicate that something doesn't work. Post code of what you are doing and explain how it is failing.

I even downloaded some very old NPCs and they still seem to work after fixing up the syntax errors for pre GMod 13 code. (Specifically this: https://garrysmods.org/download/5105/half-life-renaissance-v12 )

**Comment by ts-co** [comment]
So I have this in my init file in an NPC that uses the "base_ai" base and "ai" type:

```lua
function ENT:doFace(pos)
	print(pos)
	self:SetLastPosition(pos)
	local Schedule = ai_schedule.New( "Face" )
	Schedule:EngTask( "TASK_STOP_MOVING", 0 )
	Schedule:EngTask( "TASK_FACE_LASTPOSITION", 0 )
	self:StartSchedule( Schedule )
	debug.Trace()
end
```
pos returns in console: 784.244873 -473.402588 -83.906250
and the debug.Trace:
```
Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 85	"doFace"		gamemodes/fallout/plugins/pointnclick/entities/entities/class_base/init.lua
	3: Line 82	"nil"		gamemodes/fallout/plugins/pointnclick/sv_plugin.lua
	4: Line 54	"nil"		lua/includes/modules/concommand.lua
```

I call this in a regular function and nothing happens, not even an error message. I can even put in my own vector position just to make sure and it won't work. I can also give you my NPC code if that'll help.

**Comment by robotboy655** [comment]
Solved, everything was working as intended, ```ai.GetTaskID``` was returning IDs on the wrong scale. Let me know if this change causes any other problems.

Also keep in mind best way to fire off these schedules is in ```ENT:SelectSchedule```.

**Comment by ts-co** [comment]
Just to clarify. `ai.GetTaskID` was returning wrong IDs and was fixed in a new commit on the dev branch? Or it was always working fine, and there was a problem on my end?
