### ISSUE TITLE
Issue after gmod update

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3847]
### Details
Right after the gmod update I have the issue in local multiplayer and sometimes on my server, when I right click and a DMenu appears, it instantly fades away again.
This affects the spawn menu also.

It only happens after playing sometime.
On server it happens to every player.

I also tried with -noaddons and -noworkshop and after some time, the issue there appeared too.

### Steps to reproduce
I don't know how to reproduce the issue, but the update most likely caused it.

Players with similiar issues maybe could approve this.

**Comment by ReverendV92** [comment]
Try deleting the `cache`, `download`, `downloadlists`, and `downloads` folders from your `steamapps/common/garrysmod/garrysmod/` folder. Might've joined a server that sent some crap to your client, and it might not've been cleaned up/work properly.

**Comment by mcNuggets1** [comment]
I've only joined my own servers which suddenly after the gmod update began having this bug.
Just like my addon free local game.

**Comment by robotboy655** [comment]
Nothing about DMenu was changed. What are you right clicking? Context menu properties? Something in spawnmenu? What specifically? What do you mean by "fade away"? DMenu is not supposed to "fade away", it has no animations.

This isn't your first issue created here, why do you keep omitting details?

**Comment by mcNuggets1** [comment]
Alright, I'm gonna explain it different. After some uptime of your local game, it can gaopen dir both single and multiplayer, when you right click anything which opens the spawn menu, that it instantly closes it next frame. Of this once happened, it happens untill you restart your map/game. Its cause is unknown, but it doesn't happen rare. It happened after the update game out.

**Comment by Kefta** [comment]
Can you record a video?

**Comment by mcNuggets1** [comment]
I'm sure it will appear again and then I could.

**Comment by robotboy655** [comment]
You also could try recording CurTime() when it first happens and comparing it over multiple times it first happens to see if there's a link to a certain amount of uptime, also if in multiplayer, does rejoining the server help, or does the server need to restart? Does it persist from multiplayer into a singleplayer game?

**Comment by mcNuggets1** [comment]
I've told my players to record it.
I didn't have the time to find a way to reproduce it in single player, especially because the cause is unknown.

Video: https://youtu.be/ZM3TwB3B0bw
Sorry for the german, it wasnt recorded by me.

Current CurTime: 3201.1970214844

Player & Game Infos:
Gamemode: Sandbox
Addons: All selfmade or heavily modified (nothing is affecting anything regarding DMenus), except VCMod (but also happened in Singleplayer with no addons for me, didn't think I would have needed a video back then)
Version: Current (Not Dev-Version)
OS: Windows 10
Specs:
GTX 1080 Ti, i7 7700k, 16GB DDR4

**Comment by mcNuggets1** [comment]
My local game is up for like 30 minutes now and the issue started occuring again.
I didn't do anything, tabbed a few times out.

**Comment by mcNuggets1** [comment]
I now know why the issue occurs.

It occurs, because the DermaMenu is the same as g_ContextMenu and I close the Context Menu every frame to block the context menu usage while using my weapon base.

So why is a DermaMenu classified as g_ContextMenu?

**Comment by robotboy655** [comment]
You are doing something incredibly wrong, if you want to prevent right clicks on entities you should use the appropriate hook: https://wiki.garrysmod.com/page/ENTITY/CanProperty

Also how is it not obvious yet to post the goddamn code?

**Comment by mcNuggets1** [comment]
if IsValid(g_ContextMenu) then
	g_ContextMenu:Close()
end

In a SWEP:Think()

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/blob/098473c481adcd1c6d5d89c68a7d500f88c592d3/garrysmod/gamemodes/sandbox/gamemode/spawnmenu/contextmenu.lua#L75

This is your problem.

**Comment by mcNuggets1** [comment]
Yeah, I see.
This isn't a gmod issue after all.
I'm sorry for misleading.
