### ISSUE TITLE
GM/EntityRemoved is sometimes wrongfully called clientside upon login to server

### ISSUE THREAD

**Issue by Marco888** [Facepunch/garrysmod-issues#3848]
When you join a server (mostly when there is an ongoing game/round), some entities get GM:EntityRemoved called right after GM:OnEntityCreated/GM:NetworkEntityCreated hooks was ran, even though the entities were not removed.

**Comment by robotboy655** [comment]
It is normal on map spawn, this is how Source Engine precaches models and sounds, etc of different entities.
