### ISSUE TITLE
net.BytesLeft() (or len argument in net.Incoming) return wrong value when receiving message while joining to server.

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#3850]
### Details
I use some code to get information about length of data in net.Incoming
```Lua
local bleft = net.BytesLeft
local incoming = net.Incoming
net.Incoming = function(len,ply)
	local l = bleft()
	
	pcall(incoming,len,ply)
	
	print("StartBits: "..len,"ComputedStartBytes: "..len/8,"StartBytes: "..l,"LeftBytes:"..bleft())
end
```
But when i rejoin on server and look in console, i see this 
![image](https://user-images.githubusercontent.com/49488893/57749285-b9e2a880-76dd-11e9-9ef9-9ff4a90482e3.png)
and after fully loading other messages looks like this
![image](https://user-images.githubusercontent.com/49488893/57749317-d979d100-76dd-11e9-8d6c-dd87881222ca.png)

For some reason in loading len/8 != net.ReadBytes(), after loading all okay (but not always).
Wiki says len argument in net.Incoming in bits, not bytes.

### Steps to reproduce
Put code above to file in autorun/client folder, prepare some net messages that sends in hook like PlayerInitialSpawn to player and join to your server/singleplayer.

**Comment by robotboy655** [comment]
Should be fixed in Dev.

**Comment by ShadowBonnieRUS** [comment]
net.BytesWritten maybe also works wrong, value returned after writing all (but before sending) not equal with len argument on receive.

**Comment by robotboy655** [comment]
```net.BytesWritten``` also includes data unrelated to the net message data you wrote such as the name of the net message. In total its 3 extra bytes.

1 is stripped in C before ```net.Incoming``` and 2 are stripped in ```net.Incoming``` before your code gets to read the data.

**Comment by ShadowBonnieRUS** [comment]
Okay, thanks.
