### ISSUE TITLE
Searching Spawnmenu Error

### ISSUE THREAD

**Issue by C0D3GREEN** [Facepunch/garrysmod-issues#3851]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)
- This error has been appearing on my server quite frequently for the past month or so.

### Steps to reproduce
Tell us how to reproduce the problem, step by step
- Just searched in the search bar.

### The error
```
[ERROR] gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:60: attempt to call method 'RefreshResults' (a nil value)
  1. fn - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:60
   2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
    3. unknown - gamemodes/sandbox/gamemode/cl_search_models.lua:41

Timer Failed! [search_models_update][@gamemodes/sandbox/gamemode/cl_search_models.lua (line 41)]
```

**Comment by robotboy655** [comment]
If it happens every time you search something, verify your server files.

I cannot reproduce this.

Also look into addons that overrides default .lua files:
```
whereis gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua
whereis gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsidebar.lua
whereis gamemodes/sandbox/gamemode/cl_search_models.lua
```
