### ISSUE TITLE
Crash (Dev/Chromium): Lua Panic, Not Enough Memory

### ISSUE THREAD

**Issue by WinterPhoenix96** [Facepunch/garrysmod-issues#3853]
### Details
After a recent change to the Dev/Chromium branches, some players in my community have been reporting crashing while joining [YukiTheater](https://www.yukitheater.org/connect.html), with a Not Enough Memory Lua Panic.

Crash Dumps:
https://winteris.moe/share/2019-05-17_14-46-22.mdmp
https://winteris.moe/share/2019-05-17_14-46-31.mdmp
https://winteris.moe/share/2019-05-17_14-46-41.mdmp

### Steps to reproduce
1. Switch to the Chromium or Dev branch
2. Join [YukiTheater](https://www.yukitheater.org/connect.html) or, I assume, any other Cinema server
3. Crash

To clarify, this was **not** happening on the Chromium branch prior to `Garrys Mod/main/chromium/6035`.

It may have been occurring on the Dev Branch prior to that Merge, however it only became visible to us once it was brought over to the Chromium branch.

**Comment by robotboy655** [comment]
Let me know if it still happens after the update on Chromium

**Comment by WinterPhoenix96** [comment]
It appears as though the issue is fixed. I'll let you know if it breaks again. Thanks!
