### ISSUE TITLE
64-Bit Build Does not Launch on macOS

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#3855]
### Details
When attempting to play the 64-bit beta version of Garry's Mod on macOS, the game always crashes during launch with the error, "Platform Error: bad module 'ServerBrowser', not loading". This dialog appears above the blue loading screen.
<img width="532" alt="Screen Shot 2019-05-18 at 11 05 32 AM" src="https://user-images.githubusercontent.com/13911970/57972263-9332a500-795d-11e9-94d9-5d8d1bcd28e0.png">

I have attached a full crash log: 
[GM64MacCrash.txt](https://github.com/Facepunch/garrysmod-issues/files/3194263/GM64MacCrash.txt)

### Steps to reproduce

1. On a macOS computer, update to the latest Steam client, download and install the latest release version of Garry's Mod.
2. Configure the game to use the beta 64-bit builds.
3. Attempt to launch the game normally, observe that the game will crash during launch.

### Configuration
MacBook Pro (Retina, 13-inch, Early 2015)
macOS 10.14.5 (18F132)

Steam Client (April 29, 2019)
Garry's Mod x86-64 (Latest as of 18 May 2019)

**Comment by Bo98** [comment]
64-bit builds are not currently available for macOS. It's still in development.

I would guess 32-bit builds are broken on that branch for whatever reason, but that's not important.

**Comment by Jake3231** [comment]
Thanks @Bo98 . Do you know when macOS build would be available?

**Comment by Bo98** [comment]
No, I haven't heard anything in a few weeks. I think it's still the main focus of development on the 64-bit branch at the moment.

I'm sure I'll be told when it's ready so I can ping you when I am made aware.
