### ISSUE TITLE
Crash on missing mp3 sound

### ISSUE THREAD

**Issue by 0fuckthesystem0** [Facepunch/garrysmod-issues#3856]
Step 1: lua_run_cl  surface.PlaySound( 'rubat_bleat_wtf.mp3' )
Step 2: ???

Profit

P.S Chromium version
CreateSound , surface.PlaySound, entity:EmitSound, sound.PlayUrl crash client when mp3 sound is missing or broken.

**Comment by Python1320** [comment]
Same with ogg. Sometimes gives no error, sometimes gives OOM:

```lua
Engine Error
---------------------------
Lua Panic! Something went horribly wrong!

"not enough memory"
```
no crashdump?

**Comment by 0fuckthesystem0** [comment]
no crashdump and OOM msg, just permanent freeze.

**Comment by robotboy655** [comment]
Should be fixed.
