### ISSUE TITLE
"Sensitivity" RunConsoleCommand Blocked.

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#3857]
Running RunConsoleCommand("sensitivity", "1") is blocked.

I find this to be a bit silly, instead of blocking it, can we constraint it instead, say 1-10.
I want to modify the users mouse sensitivity/acceleration to create a weapon system similar to Mordhau and Chivalry for better melee combat, but that's not possible with this silly constraint.

**Comment by biorisk2** [comment]
And I do know about the AdjustMouseSensitivity for the weapon & the gamemode Hook, however, these don't perform like I need them to.

**Comment by Kefta** [comment]
What doesn't AdjustMouseSensitivity do what you like to?

**Comment by biorisk2** [comment]
both of those let you scale the sensitivity, not set it,

So lets say I want a max sens. of 1.5

If the user has 3 I set it to 1.5, if the user has 4 I set it to 1.5

But this, if the user has 3, I can slow it down by percentage, meaning if the desired is 2 sensitivity,

The user could have 6 sens. and they'd be over the sensitivity if I did 0,5

**Comment by Kefta** [comment]
Just divide your desired sensitivity value by the user's sensitivity value to get the scale that achieves that. Though sensitivity is a blocked concommand, you can still read it.

**Comment by robotboy655** [comment]
Use AdjustMouseSensitivity, we don't want you or servers/addons modifying user settings which affects the user on all servers and singleplayer.
