### ISSUE TITLE
Entities with particle systems causing CTD

### ISSUE THREAD

**Issue by Taylor9701** [Facepunch/garrysmod-issues#3863]
### Details
When utilizing entities that use CreateParticleSystem, clients often crash when 10+ of these entities exist provided the particles are a bit complicated. These particle systems typically put a very light load on the system, and can have 250+ of them in a game without lag. CTD occurs when the client renders an area with 10+ of these entities with particle systems all at once.

Issue is more prevalent on the 64-bit version but can still occur on 32-bit.

### Steps to reproduce
1) Place down multiple entities that use CreateParticleSystem on a server. Preferably somewhat more complicated particle systems such that many are not required.
2) Exit render distance for these entities
3) Re-enter render distance
4) Should crash or at least heavily stutter here. If it doesn't crash, add more entities.

[Dump files](https://cdn.discordapp.com/attachments/396500908390875150/581227579256864769/dumpfiles.zip)

**Comment by willox** [comment]
This can't be fixed unless you can tell us which particles are causing issues.
