### ISSUE TITLE
Lua spamming IsWorldClicker (a nil value) in server console

### ISSUE THREAD

**Issue by Tataki-Guritchi** [Facepunch/garrysmod-issues#3864]
### Details
Every time I create a server, and someone joins, it decides to spam the server console and connected players:
`[Playername|#|SteamID] Lua Error:

[ERROR] lua/includes/modules/properties.lua:181: attempt to call method 'IsWorldClicker' (a nil value)
  1. v - lua/includes/modules/properties.lua:181
   2. Run - lua/includes/modules/hook.lua:84
    3. v - lua/includes/modules/halo.lua:149
     4. unknown - lua/includes/modules/hook.lua:84`

### Steps to reproduce
For me, it is to create a dedicated server, and have someone else join, then view the log to see the errors incoming.

**Comment by robotboy655** [comment]
You are creating a dedicated server on a beta branch, which causes problems when non beta clients join you server.
