### ISSUE TITLE
ControlPanel doesn't use "Controls" key in FillViaTable

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3866]
The control panel is initialized [here](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/includes/modules/spawnmenu.lua#L287) by the spawn menu, but [FillViaTable](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua#L78-L93) does nothing with the Controls key.

**Comment by Kefta** [comment]
Should be removed from the call then.

**Comment by robotboy655** [comment]
Yes that is the plan, i got sidetracked with something else.
