### ISSUE TITLE
hook PlayerDeathSound not working

### ISSUE THREAD

**Issue by TheCocasio** [Facepunch/garrysmod-issues#3868]
Use this code for disable the death sound but its not working for clientside ! :(

Please create Hook clientside or modify this hook in Shared

```
hook.Add("PlayerDeathSound","mutethedeathsound",function()

	return true

end)
```

**Comment by Kefta** [comment]
The hook is serverside only like all other PlayerDeath-related hooks since the client doesn't handle kills at all. You can use EntityEmitSound to block it clientside.
