### ISSUE TITLE
JSONToTable has problems

### ISSUE THREAD

**Issue by TimGoll** [Facepunch/garrysmod-issues#3869]
### Details & Steps to Reproduce
The function `util.JSONToTable` has problems with json files created with the windows text editor. Files created with notepad ++ work though

An easy way to test is by using `util.TableToJSON` and saving the output in a `*.txt`-file. Opening and edit it with notepad++ and you're still able to read and parse the file as a table. But once you open, edit and save it with the windows text editor, it stops working. Reading the file still works and a print shows, that it is read correct, but `util.JSONToTable` returns `nil` when passed the JSON string without any errors.

It seems like `util.JSONToTable` is not that robust to formating.

**Comment by willox** [comment]
I can't reproduce this.

**Comment by TimGoll** [comment]
That's very strange, since multiple users on our server can confirm this issue
we're using the TTT gamemode if that matters

**Comment by willox** [comment]
Show us the JSON file

**Comment by TimGoll** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1367128301
this addon creates the file in `garrysmod/data/ctc/`. I can post the file later today when I'm back home.

But the file does work. It only stops working when edited with the windows text editor

**Comment by TimGoll** [comment]
(Is suspect it has something todo with the file ending or the line ends, since I know that the windows text editor behaves differently in this case than other editor

**Comment by TimGoll** [comment]
Sorry, wrong addon! This one: https://steamcommunity.com/sharedfiles/filedetails/?id=1755840967

**Comment by willox** [comment]
I can reproduce it with the CTC_DEFAULT table. I'll look into it a little more.

**Comment by willox** [comment]
Yes, notepad is adding a BOM. Probably some automatic thing because of the text in the file. We can probably change JSONToTable to skip it without any issues.

**Comment by robotboy655** [comment]
This is weird because new version removes the BOM mark by default, not adds it as far as I know.
Or you could just save the file without a BOM mark in the in the save dialog in newer version, or use np++, no reason not to.

**Comment by TimGoll** [comment]
it's no problem for me since I always use np++. But ther ewere a few users already that reported to me that the addon wasn't working since they used the windows text editor even though I have a warning at the top of the docu.

**Comment by robotboy655** [comment]
Fixed, util.JSONToTable now skips the UTF-8 BOM mark.

**Comment by TimGoll** [comment]
nice, thank you!
