### ISSUE TITLE
Trails with size near max float limit causes crash?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3870]
https://github.com/wiremod/advdupe2/issues/241

**Comment by thegrb93** [comment]
The clamp is done only in the tool and not the duplicator function so the size can be unlimited

**Comment by Raklatif** [comment]
I noticed in my fix i don't check if the entity actually has a trail or not, it will create errors in console if that table value doesn't exist. @thegrb93

**Comment by Raklatif** [comment]
`local myTable = Queue.EntityList

	
	for k,v in next, myTable do
		if type(v) == "table" then
			if v.EntityMods then
				if EntityMods.trail.EndSize || EntityMods.trail.StartSize then 
					if (v.EntityMods.trail.EndSize > 128 || v.EntityMods.trail.StartSize > 128 ) then
						v.EntityMods.trail.EndSize = 16
						v.EntityMods.trail.StartSize = 16
					end
				end
			end
		end
	end`

**Comment by Raklatif** [comment]
I added the If statement to check if trails exist.

**Comment by thegrb93** [comment]
I already added my own fix that checks it https://github.com/wiremod/advdupe2/commit/0f60503ef61c86761f89c764699dc01cddef7890

**Comment by robotboy655** [comment]
Fixed.
