### ISSUE TITLE
Auto Refresh breaks after using "retry" command

### ISSUE THREAD

**Issue by chuteuk** [Facepunch/garrysmod-issues#3871]
### Details
Since the February update the Auto Refresh system breaks on a local Multiplayer server (not Singleplayer) after using the "retry" command in console. 

Previously you could continue to develop and refresh files as normal. This is very frustrating for developing, as it takes significantly longer to change map or disconnect and restart the multiplayer server. 

The retry command is very useful for developing as it allows you to quickly re-join and refresh the client state, remove broken derma off the screen and test certain events and hooks are working correctly.

### Steps to reproduce
1. Start a local Multiplayer server (not Singleplayer) from the Main Menu 
2. Edit a file, auto refresh works as normal and your changes are reloaded live 
3. Type "retry" in console
4. Edit a file again, the changes are not refreshed

**Comment by robotboy655** [comment]
I wonder why it took you 4 months to report this, if you know it was a problem since February.

Anyway, fixed on Dev.
