### ISSUE TITLE
Hitting "downloadables" prevents workshop downloads

### ISSUE THREAD

**Issue by UltimateByte** [Facepunch/garrysmod-issues#3872]
### Details
Upon hitting the max downloadables table size (adding too many files for fastdl), workshop addons are prevented from downloading to server clients.

This causes any workshop addon, even if forced to download from the server (via resource.AddWorkshop) to be missing for players.
More importantly, even the map the server is running on won't be downloaded which causes a bad experience for admins and players.

Upon searching, I've seen many users complaining about similar issues without finding the cause. Well, this is at least one of them.

### Steps to reproduce
1) Make a server with at least 8000 files to download
With LinuxGSM (Linux servers), run` ./gmodserver mods-install`
Install ACF and ACF weapons, and as many plugins with loads of textures that you have, to have a good amount of files to download.
Run `./gmodserver fastdl` ; then follow the assistant and enable the force download feature.

Server logs should show this kind of entries on boot:
```
Warning:  Table downloadables is full, can't add models/gmod_tower/suitetv_large.vvd
```
If not, you need to add more addons to reproduce the error.

2) Use a map from Workshop and start the server on it
3) Don't be subscribed to this map as a client/user
4) Connect to the server and you should get the error
Player logs show:
```
Missing map maps/gm_functional_flatgrass3.bsp,  disconnecting
Host_Error: Map is missing
```

Server logs show this upon player connection:
```
Player ./ultimatebyte (STEAM_0:1:10260243) disconnected (Map is missing)
```

Note:
* I'm hitting the limit even if addons added by myself are only made of 4443 files, so I assume either the limit is 4000, or other addons (possibly from workshop) are already adding files themselves.
* The max downloadables are pretty low compared to actual use made of servers, a single addon such as ACF can make the server hit the limit. I would suggest hugely increasing this value or adding svar for that, if technically possible.

**Comment by robotboy655** [comment]
FastDL and resource.AddWorkshop use the same system and therefore share same limitations. If you are hitting the limit, this is a problem on your end. Do not add content from Workshop addons onto FastDL, etc, etc.

The limit is indeed 4096 for some reason, has been since 2014 apparently, something to investigate.

**Comment by UltimateByte** [comment]
"FastDL and resource.AddWorkshop use the same system and therefore share same limitations"

And this sounds fine to you?

Well... At least I tried. Hm.

**Comment by robotboy655** [comment]
Why shouldn't it?

If your server collection has a workshop addon that has the map your server runs, it will be automatically added into downloadables before much else is, ensuring it will be always in the downloads list.

**Comment by UltimateByte** [comment]
One shall add potatoes to something else.

The current behavior, according to what you're saying, adds up resource.AddWorkshop and resource.AddFile as a whole total and therefore, they share a common limitation, which is absurd.
I thought my first post was clear:
The current behavior penalizes entire Workshop **addons**, compared to non workshop **files**!

It means if you have too many files to FastDL (which is a shame in the first for many reasons IMO), then you can't download the workshop map from the server, and therefore you can't even join the server (missing map).

Don't you see how silly the experience is for players as well as server owners encountering this?

**Comment by thegrb93** [comment]
Not to mention workshop tends to have downtimes which makes fastdl as a backup seem like a good idea.

**Comment by UltimateByte** [comment]
I think it should be up to server owners to decide what they want to use without ambiguous restrictions.

For my part (and I believe it's the most common scenario), I will use Workshop whenever available, and regular addons with FastDL when I have no other choice... And that case scenario is highly restricted by the current behavior.

So hopefully the issue can be re-opened and some more consideration given to this request.
