### ISSUE TITLE
Constant crash at map load with x64 version of gmod

### ISSUE THREAD

**Issue by glebqip** [Facepunch/garrysmod-issues#3873]
### Details
Crashing at load state
dumps.metastruct.uk.to shows vphysics.dll crash
### Steps to reproduce
Launch [gm_metrostroi_b50](https://steamcommunity.com/sharedfiles/filedetails/?id=306834272)

[Dumps.zip](https://github.com/Facepunch/garrysmod-issues/files/3253708/Dumps.zip)

**Comment by willox** [comment]
this should be fixed
