### ISSUE TITLE
(x86-64) Kaspersky Total Security possible false positive

### ISSUE THREAD

**Issue by dottiekh** [Facepunch/garrysmod-issues#3874]
### Details
Kaspersky Total Security has identified the 64-bit version of Garry's Mod as a Trojan. Not sure if this is a false positive on Kaspersky's end (I had launched it successfully before with no issue), an actual trojan that got into the gmod.exe, or that the 64-bit branch isn't properly "cleared" in the sense that it doesn't set off any antivirus alarms.

### Steps to reproduce
Launch Garry's Mod 64-bit with Kaspersky Total Security.
![image](https://user-images.githubusercontent.com/34873184/59072775-f2a71500-8878-11e9-9a49-6f4bf5f3e6a2.png)

**Comment by thegrb93** [comment]
I don't think steam games' executable have write protection so could have been infected. Just delete it and verify game files.

**Comment by dottiekh** [comment]
I tried your suggestion but it is still being identified as a trojan. It's highly likely it is a false positive. I will add it to an exclusion list, but it would be nice if there was some way to mitigate this so exclusions wouldn't be necessary.

**Comment by robotboy655** [comment]
There's nothing we can do about this, some AVs just do this, you will have to wit for virus db update that hopefully addresses this issue. You also should report it as false positive via you AV.

You can also scan the .exe with something like VirusTotal.com
