### ISSUE TITLE
[dev] AI and weapon_pistol broken

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3875]
They don't seem to be firing any bullets only thing that works is the muzzle flash.

https://share.epic-domain.com/2019-06-08_19-17-0250d2d034ffae3261c.webm

This happens only with the pistol as far as I'm aware.

**Comment by robotboy655** [comment]
My bad, should be fixed now.

Animation events work in mysterious ways, some just have to be hardcoded with magic numbers.
