### ISSUE TITLE
Gmod's VVIS ignoring -radius_override parameter

### ISSUE THREAD

**Issue by Noctara** [Facepunch/garrysmod-issues#3881]
It seems Gmod's VVIS completely ignore  "-radius_override" parameter or env_fog_controller's "Far Z Clip Plane (farz)" line. I used that parameter in another SDK to compile large maps by sacrificing render distance ([on this map](https://steamcommunity.com/sharedfiles/filedetails/?id=237313732)), but now i noticed the vvis just stuck on "0" of PortalFlow. When i tried using TF2's VVIS this trick start working again.

**Comment by robotboy655** [comment]
Well, no, it is not ignored looking at the code. Broken? maybe.

The farZ can be overwritten by addons easily, so test with `-noworkshop -noaddons` before posting here. (You should test without addons at all times anyway)

**Comment by Noctara** [comment]
Well... it not about game, it about map compilation only. Same .vmf and same parameters = Gmod vvis stuck - TF2 vvis run perfect. Later i will check it ,more carefully and post screens of result here.

**Comment by robotboy655** [comment]
The farZ comment was a reply to this;
 

> env_fog_controller's "Far Z Clip Plane (farz)" line.

**Comment by Noctara** [comment]
Oh... i'm about "vvis" should using FarZ from fog controller as visibility limit when calculating. Or it using override instead...

**Comment by Noctara** [comment]
So... i create small map and test tf2 vvis vs gmod vvis. On small map is no difference. But on giant one gmod's vvis stuck and any another vvis is finished correctly. I know vvis stuck on giant maps, but small Vis Radius in usually should fix even max-hammergrid map.

tf2 vvis
![C__WINDOWS_system32_cmd exe 22 06 2019 10_12_46](https://user-images.githubusercontent.com/15330810/59960998-c8d92980-94d9-11e9-96cd-50d6ae0cb635.png)

gmod vvis
![C__WINDOWS_system32_cmd exe 22 06 2019 10_14_54](https://user-images.githubusercontent.com/15330810/59960999-cc6cb080-94d9-11e9-9937-6ba4dfe9d945.png)

Sorry for grammar errors, i'm not so good in english.

**Comment by Noctara** [comment]
NEVERMIND --- I just run gmod's vvis for 35 min and it successfully finished. It seems the problem in progress bar, all 35 mins PortalFlow show "0". 

I tried run vvis many times with different settings and it look like both progress bars can show only "0" and "0...1...2...3...4...5...6...7...8...9...10", it not display intermediate states for me. Gmod's vvis is only vvis where i can see that behavior.

**Comment by robotboy655** [comment]
So it's working properly. I don't know why it would be different from other versions, ours is literally exactly the same as TF2s code-wise.

**Comment by Stiffy360** [comment]
> 
> 
> NEVERMIND --- I just run gmod's vvis for 35 min and it successfully finished. It seems the problem in progress bar, all 35 mins PortalFlow show "0".
> 
> I tried run vvis many times with different settings and it look like both progress bars can show only "0" and "0...1...2...3...4...5...6...7...8...9...10", it not display intermediate states for me. Gmod's vvis is only vvis where i can see that behavior.

Sometimes the window doesn't update when doing a compile. This is normal and there's not much you can do about it.

**Comment by neico** [comment]
Those tools aren't properly utilizing multi-threading, so most of the time they run stuff on a single thread, which makes it look like they are frozen...
One could improve on that quite a bit (those tools are mostly C code too), but I'm unsure if it's worth the time you need to spend on it. (would probably equal on a rewrite)

**Comment by robotboy655** [comment]
Better name for this would be this: https://github.com/Facepunch/garrysmod-issues/issues/4053
