### ISSUE TITLE
You can close users' games with RunConsoleCommand("gamemenucommand", "quitnoconfirm")

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3882]
The entire command should just be blacklisted, none of these look safe: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/gameui/BasePanel.cpp#L672-L692

**Comment by robotboy655** [comment]
Blocked

**Comment by TheMostUpset** [comment]
RIP custom menus

**Comment by Kefta** [comment]
I forgot that's how custom menus functioned, I guess quitnoconfirm should be the only blocked argument then.

**Comment by robotboy655** [comment]
You mean menu state custom menus or custom menus for servers?

**Comment by Bo98** [comment]
@Kefta Doesn’t regular “Quit” behave the same as “QuitNoConfirm” in GMod?

Of course, such behaviour change could be reverted.

**Comment by Kefta** [comment]
Custom server pause menus, and yes you're correct @Bo98

**Comment by joeyjumper94** [comment]
did you block all of it? cause i want some way to cleanly close users games

**Comment by robotboy655** [comment]
Unblocked the command and blocked only quitnoconfirm.
