### ISSUE TITLE
Striders don't explode 

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3884]
### Details
Striders don't explode when killed with a strider buster, or the AR2 altfire, instead they will just ragdoll. Occurs in the pre-release branch, 2019.06.24.

### Steps to reproduce
Kill any strider with a strider buster or combine ball.

**Comment by robotboy655** [comment]
Fixed, was caused by https://github.com/Facepunch/garrysmod-requests/issues/1306
