### ISSUE TITLE
NPCs cannot pickup weapons

### ISSUE THREAD

**Issue by teh-player** [Facepunch/garrysmod-issues#3885]
I remember NPCs being able to pickup dropped half life 2 weapons when dropped by another NPC on death. This is no longer the case and NPCs will never pick up dropped weapons. Even with use of the extended properties addon allowing weapon pickup, NPCs will never pickup weapons.

**Comment by robotboy655** [comment]
It appears you are correct, it wasn't working because we are using the HL2MP version of the weapons and the code expected the HL2 non-multiplayer versions. Fixed.
