### ISSUE TITLE
crash the game using game.MountGMA

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3887]
steamworks.FileInfo(ID_OF_ADDON_THAT_CONTAINS_A_BSP,function(R)
		steamworks.Download(R.fileid,true,function(N)
			game.MountGMA(N)
		end)
	end)
my guess is that this happens cause it tries to reload all models/materials
this probably causes the worldspawn entity to be messed with if the GMA contiained a bsp,
that is what is probably causing the crashes
probably the cause of https://github.com/Facepunch/garrysmod-issues/issues/2476

**Comment by robotboy655** [comment]
Could not reproduce with the following:
```
steamworks.DownloadUGC(3195287999,function(N)
	game.MountGMA(N)
end)
```

So closing as stale. If it still happens, please provide working reproduction code.
