### ISSUE TITLE
NPCs cannot pickup weapons in multiplayer

### ISSUE THREAD

**Issue by teh-player** [Facepunch/garrysmod-issues#3888]
NPCs cannot pickup dropped weapons in multiplayer, even with extended properties.

**Comment by Kefta** [comment]
Is this different than https://github.com/Facepunch/garrysmod-issues/issues/3885?

**Comment by teh-player** [comment]
Yes #3885 has been solved.

**Comment by robotboy655** [comment]
It works in multiplayer for me, just make sure the map has nodes so NPCs can move about, such as gm_construct.
