### ISSUE TITLE
changing sv_gravity does not affect non-player entities

### ISSUE THREAD

**Issue by hellokittyhoodie** [Facepunch/garrysmod-issues#3889]
### Details
Non-player entities use sv_gravity value, that server started with 
### Steps to reproduce
Start New Game -> Change sv_gravity to anything

**Comment by thegrb93** [comment]
You have to use physenv.SetGravity( Vector gravity )

**Comment by hellokittyhoodie** [comment]
> You have to use physenv.SetGravity( Vector gravity )

But isnt it world gravity

**Comment by hellokittyhoodie** [comment]
Well i got it, sv_gravity description is confusing
