### ISSUE TITLE
NW2 vars sometimes don't initialize properly in multiplayer

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-issues#3891]
### Details
While debugging my nextbots for multiplayer, I found a bug relating to NW2 vars. When the nextbot first spawns I initialize a bunch of values that are shared using NW2 vars. In singleplayer there is no issue, everything works as expected, however in multiplayer sometimes the values aren't sent to the client. NW2 vars that are set after the entity was initialized work as expected though, this bug only seems to happen during initialization.

This doesn't always happen, and also this doesn't seem to affect specific entities, it either seems to affect every entity that spawns or none of them, as far as my testing goes.

I've encountered this bug in both listen and dedicated servers, but never in singleplayer.

### Steps to reproduce
Create an entity and set one or more NW2 vars on the server, then print it on both the client and the server, sometimes, everything will work as expected, but every now and then it will break and the values returned on the client will be the default values.

```lua
function ENT:Initialize()
  if SERVER then
    self:SetNW2Entity("NW2TestEntity", self)
    self:SetNW2Float("NW2TestFloat", 500))
  end
  print(self:GetNW2Entity("NW2TestEntity"))
  print(self:GetNW2Float("NW2TestFloat"))
end
```
As expected, on the server, it will always print this:
```
Entity[entIndex][class]
500
```
However, every now and then it would print this on the client instead:
```
[NULL Entity]
0
```

**Comment by robotboy655** [comment]
You are not really giving them much time to update like that, have you tried adding a timer for those prints? Something bigger than 0, more like 100ms or 1 second?

**Comment by Dragoteryx** [comment]
Yes, this still happens using a timer. I even tried printing the vars inside the Think hook instead, this still happens. This isn't just the vars not updating quick enough.

**Comment by Dragoteryx** [comment]
I ran a few more tests just to make sure this wasn't a nextbot related issue, and created an entity just to test this bug.
```lua
AddCSLuaFile()
ENT.Base = "base_entity"
ENT.Type = "anim"
ENT.PrintName = "Debug NW2 Vars"
ENT.Spawnable = true
function ENT:Initialize()
  if SERVER then
    self:SetNW2Entity("TestSelf", Entity(1))
    self:SetNW2Float("TestFloat", 500)
  end
end
function ENT:Think()
  print("==============")
  print(self:GetNW2Entity("TestSelf"))
  print(self:GetNW2Float("TestFloat"))
end
```
On the server it always prints this:
```
==============
Player [1][DragoTeryx]
500
```
But on the client sometimes it prints this instead:
```
==============
Player [1][DragoTeryx]
0
```

Seems like it the same bug as #2992, searched for similar issues but for some reason it didn't appear in the search results so I didn't find it.
