### ISSUE TITLE
The problem with the properties of materials on the model

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#3892]
### Details
I noticed one problem: when you do damage with hand-to-hand weapons, such as crowbar, then sound and decals of the same material, when you do damage with bullets, then sound and decals are completely different. For example, wood and metal on the doors of Left 4 Dead 2 or metal and metal (on a ragdoll) place metal and tire.

### Steps to reproduce
Just watch the video.
https://youtu.be/RU9qaU3HgNI

**Comment by robotboy655** [comment]
I have fixed it for the doors, but you'll need to provide me with models/maps and positions to test the other stuff.

**Comment by MARK2580** [comment]
This is a model from my recent pack. Here is a link to the workshop.
https://steamcommunity.com/sharedfiles/filedetails/?id=1766175209
models/mark2580/gtav/garage_stuff/wheel_balancer_01a_ragdoll.mdl

**Comment by mcNuggets1** [comment]
https://i.imgur.com/Os6ZkKF.png
This happens when shooting with shotguns on func_doors haha

**Comment by robotboy655** [comment]
That is unrelated I think, and there's an issue open for it already, can't find it tho. Also don't hold your breath for this issue to be fixed, there's a reason valve use separate models entirely for this on things like car windshields, even in L4D:
![image](https://user-images.githubusercontent.com/3299036/60595525-d92db600-9daf-11e9-9602-516077202c90.png)

**Comment by robotboy655** [comment]
Ok nevermind the above, it will work for ragdolls now.
