### ISSUE TITLE
nav_generate is insanely slow

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3893]
in TF2, nav_generate will take about 50 seconds for a map like ctf_2fort
in gmod the same command takes about 110 seconds on the same map.
nav_analyze is also affected by this

**Comment by joeyjumper94** [comment]
update, here's the commands i used to test

`//prep
map ctf_2fort
sv_cheats 1
nav_edit 1
nav_snap_to_grid 1
//generate test 1
nav_generate//record number printed after
//generate test 2
ent_fire func_d* kill
nav_generate//record number printed after
//generate_incremental test
setpos -35 400 255;setang 55.4 0 0
nav_mark
nav_generate_incremental//record number printed after
//analyze test 1
nav_analyze//record number printed after
//analyze test 2
nav_analyze//record number printed after` the bench tests reveal that gmod takes 50% to 60% more time to run these commands

**Comment by robotboy655** [comment]
Cannot confirm.

Using same video settings (both with no mcore), both multiplayer, sv_cheats 1, blah blah, nav_quicksave 0 and your snap_to_grid 1 these are the results:
![gmod](https://user-images.githubusercontent.com/3299036/60429965-e195bd80-9c04-11e9-9fcf-e0529d859b92.png)
![tf2](https://files.facepunch.com/rubat/1b0111b1/rs2client_2019-07-01_13-27-04.png)

Make sure you are running with no addons, don't alt tab out, etc, etc, etc.
