### ISSUE TITLE
"math.Clamp efficiency" change breaks cases where input is the max

### ISSUE THREAD

**Issue by Cynosphere** [Facepunch/garrysmod-issues#3895]
[This commit/PR](https://github.com/Facepunch/garrysmod/commit/e416d41810637456d3c799ec81846af8a4f48652) broke math.Clamp operations that try to keep the input value to a minimum while having the input as a max

Example:
```lua
local x = 100
print(math.Clamp(x,200,x))
-- should print 200, but prints x, which in this case is 100
```

**Comment by robotboy655** [comment]
Why are you giving the function a minimum value that is higher than the maximum value?

You are doing something not smart, i'd consider this an undefined behavior. You should not be doing this, it shouldn't print anything. 200 is bigger than the maximum value you are giving it.

**Comment by Cynosphere** [comment]
I'll just close this since it is unintended behavior and i was pretty much using math.Clamp like math.max in the past.

**Comment by Cynosphere** [comment]
Reopening to clarify some things.

1. The example I gave was poorly representative of the use case I had. I was using dynamic variables to try and essentially do what math.max does because I didn't know any better. This can also be extended to two dynamic variables.

Say I have `x` and `y` that get set every so often, and I want to clamp `x` based on `y` being the smallest value.

What if `y` becomes bigger than `x`? It should return `y`, but with this optimization change, it returns `x`. It is stated on the wiki:
> The minimum value, this function will never return a number less than this.
This is now false.

2.
> You should not be doing this, it shouldn't print anything.
There is no check in place in the function to prevent this.

3.
> You are doing something wrong.
What if I didn't find my answer elsewhere and only came here for help? I would've been lost and probably would've given up because you're wanting to be ignorant and not wanting to at least suggest something to someone no matter their skill level. I find this really unacceptable, especially compared to other projects.

Please be considerate in the future where I don't feel like I'm backhandedly being called a fucking retard, thanks.

**Comment by thegrb93** [comment]
That's a lot of math functions that can behave weirdly if given garbage inputs.

**Comment by thegrb93** [comment]
To solve your proposed case, you would want to do math.Clamp(var, x, math.max(x,y))

**Comment by Cynosphere** [comment]
I've already solved MY problem, you're just missing the point I was trying to get across, that it could be a **potential issue in the future, especially for beginners** (not saying I'm a beginner at all), let alone how the issue was generally handled.

**Comment by thegrb93** [comment]
I know, but like I said, other math functions will give you garbage too if you give them garbage.

**Comment by thegrb93** [comment]
The previous implementation also had the same issue as well, so you can't blame it on the change.
