### ISSUE TITLE
Minor issue returns (Context menu cursor stays after closing the menu)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3896]
### Details
https://github.com/Facepunch/garrysmod-issues/issues/2780

This issue I reported 2 years earlier seems to be back.

### Steps to reproduce
1. Open the context menu.
2. Hold any mouse button while letting go of the context menu button to close the context menu to make it stay forever until you click somewhere.

**Comment by robotboy655** [comment]
Yeah it was unfixed (in September 2016) because it broke DNumberScratch apparently

**Comment by robotboy655** [comment]
Well I couldn't make it break DNumberScratch again so I am re enabling it for now.
