### ISSUE TITLE
HL:S spas 12 and crossbow ammo don't register

### ISSUE THREAD

**Issue by PriceMeme** [Facepunch/garrysmod-issues#3897]
When going into the game, the recently added HL:S spas 12 and crossbow ammo don't load into the clip. For example, if there are 4 spas 12 shells in the clip, you can't get anymore ammo, and when you run out, you have to get another weapon. The same issue applies to the crossbow. This isn't an addon issue; I tried disabling all addons and it still didn't work. The issue applies to both the chromium beta and regular edition of Garry's Mod.

**Steps to reproduce**
Open the spawn menu.
Go to Weapons.
Go to Half-Life: Source
Click on either the HL:S spas 12 or crossbow.
Go to Entities
Go to Half-Life: Source
Click on either SPAS-12 Ammo or Crossbow Bolts
Walk near them to use.

**Comment by robotboy655** [comment]
Fixed on Dev branch, the actual problem was that the ammo boxes were giving the wrong ammo type. You can get more by simply spawning/pickup the same gun again. (If the gamemode allows for it)
