### ISSUE TITLE
HTTP library rejects ports with ip addresses

### ISSUE THREAD

**Issue by BlackCetha** [Facepunch/garrysmod-issues#3900]
### Details
The HTTP global function will not accept IP addresses with a port as a parameter for the URL field since the last update.
I've just updated my server, changed no code whatsoever and the HTTP requests stopped working.
The error message provided to the failure callback is "invalid url".

This only happens when both a ip address instead of a DNS name is used and a port is specified.

### Steps to reproduce
Update to July 2019 version and run a HTTP request with ip address and port, for example:
`lua_run HTTP({failed=function (e) print(e) end, success=function (b) PrintTable(b) end, method="GET", url="http://10.8.0.1:8080"})`

**Comment by robotboy655** [comment]
It's not the port, its the IP. You cannot make requests to private IP addresses anymore.

**Comment by BlackCetha** [comment]
Can you explain why you changed that?

**Comment by robotboy655** [comment]
You have no business or reason for doing that.

**Comment by BlackCetha** [comment]
I can understand why disabling this on the client makes sense, however on the server this severely limits functionality.
I'm syncing some data via VPN and this change makes the entire module that has worked for yeaars unusable.

**Comment by meepen** [comment]
Can't you just make any domain point to any up?

**Comment by meepen** [comment]
Ip* sorry

**Comment by BlackCetha** [comment]
I haven't tested that yet, but if the implementation is any good the IP check will happen after the DNS name is resolved.

**Comment by BlackCetha** [comment]
@robotboy655

**Comment by robotboy655** [comment]
What? It doesn't check it after DNS because that's not an option for Steam's HTTP stuff as far as I am aware. That should allow you to do what you need to do on the server.

If I disable the blocking on server, it would probably be behind a convar.
