### ISSUE TITLE
Current implementation of BASS doesn't support libssl 1.1

### ISSUE THREAD

**Issue by Sophie-bear** [Facepunch/garrysmod-issues#3901]
### Details
Tested on x86-64 branch:
When using a newer version of a given Linux distribution, problems may arise from the currently implemented version of libbass not supporting libssl 1.1, which is the default used version of libssl in Manjaro and possibly other distributions. This can be addressed by the user by replacing the symlink "libssl.so" with one that points to libssl 1.0.0 for now, but this is not ideal.
Currently, attempting to play media using BASS with libssl 1.1 will result in Code 10: BASS_ERROR_SSL.
More information regarding this problem can be found on un4seen forums here: http://www.un4seen.com/forum/?topic=18405.0

### Steps to reproduce
Attempt to playback media using BASS while "libssl.so" points to libssl 1.1.

**Comment by robotboy655** [comment]
The version presented there most definitely has the crashing problem (because its older) which was fixed in our version, so there's not much that can be done here but to wait for a full new release.

**Comment by robotboy655** [comment]
I am assuming this was fixed in the many updates since this was opened.
