### ISSUE TITLE
Another problem with materials

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#3902]
### Details
I checked the July update and found a very strange problem.
Looking around one of the CS: GO (de_cache) maps, I suddenly stepped into the water, although it is not there anywhere. I specifically entered CS: GO and opened this card. In the original, there is no water, wood, concrete and grass. In Garry's Mod, it’s as if water is everywhere in these places.

### Steps to reproduce
Walk on the map de_cache. For clarity, videos from cs:go and garry's mod. Actual for x86 and x64 bit versions.
https://youtu.be/ZwgZNLx_g_M

**Comment by robotboy655** [comment]
Yes, I am aware of the problem, as I have previously said, there are many problems still unsolved on newer engine maps.

**Comment by robotboy655** [comment]
Fixed.
