### ISSUE TITLE
npc_missiledefense multiple bugs

### ISSUE THREAD

**Issue by Aaron2550** [Facepunch/garrysmod-issues#3903]
### Details
The npc_missiledefense **a)** doesnt have a model, **b)** only shoots a rocket down once and then stops working and **c)** doesnt shoot down hl1 missiles 

### Steps to reproduce
add a npc_missiledefence to a map, compile it and shoot a rocket in front of it (the front is the same direction as "setang 0 0")

Im on chromium build 7522 btw

EDIT: its supposed to only shoot in one direction.

**Comment by Kefta** [comment]
Was this fixed?

**Comment by Aaron2550** [comment]
Nope, i just dont expect any change anymore, found this when going through my old issues

**Comment by Kefta** [comment]
I'll reopen it then I guess; this isn't even that old of an issue.

**Comment by Aaron2550** [comment]
Damn... if this isnt "old" then how long is the backlog?!

**Comment by Kefta** [comment]
![jbtFF6V](https://user-images.githubusercontent.com/4593679/74613641-ada8d300-50d5-11ea-8038-cc73ce49c1b5.png)

**Comment by robotboy655** [comment]
There are almost 700 reported issues (not even talking about requests) and they are being reported at a faster rate then we can resolve them.

An obscure entity like this, which can be in its entirety replicated using the modding API would hardly be on the top of the priority list.

That being said:
a) What do you want us to do about this? We do not have a modeler on our team, nor would we know what it should look like.
b) ok
c) It was never designed to do so

**Comment by thegrb93** [comment]
Not to mention this can be achieved with lua. No need to fix valve's issues

**Comment by Aaron2550** [comment]
Y'all could've told me that in July, well thanks anyway. Guess I'll close this then? For a) we do know what it looks like from hl2 beta leaks and b) it's (afaik) supposed to shoot down rockets more than once and c) well that's true, just a thing that could've been added
