### ISSUE TITLE
monster_osprey error on death

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3906]
```
CSoundPatch::Update:  Removing CSoundPatch (apache/ap_rotor4.wav) with NULL EHandle
```

The sound handle is cleaned up in StopLoopingSounds but the error still occurs.

**Comment by robotboy655** [comment]
Should be fixed assuming by "on death" you mean "it was deleted with the message `osprey error: no grunts to resupply`".

**Comment by Kefta** [comment]
No, I know the purpose of that error, I meant the soundpatch issue.
