### ISSUE TITLE
Shift + F2 shortcut stops working after joining any server

### ISSUE THREAD

**Issue by deinferno** [Facepunch/garrysmod-issues#3907]
### Details
In July update 2019, change list 1 specified that " Disabled SHIFT+F2 opening "demoui" in multiplayer" , but in reality it's just cripples shortcut after joining any server.
P.S. I am only tried that on linux version of game.

### Steps to reproduce
Join any server then disconnect and shortcut won't work until you restart the game

**Comment by robotboy655** [comment]
You can start a singleplayer game and that would make it work again, but I can see how it not working in main menu can be annoying, so it's fixed on the Dev branch.
