### ISSUE TITLE
Player:Say() silently fails

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#3908]
### Details
Player:Say() seems to fail silently when the passed string begins with `^//.*`

### Steps to reproduce
```lua
hook.Add("PlayerSay", "test", print)
for k, v in ipairs(player.GetAll()) do 
    v:Say("Hi, this works")
    v:Say("/ This too")
    v:Say("// but this doesn't")
    v:Say("/// Neither does this")
    v:Say("And no it's not rate-limited")
end
```

**Comment by thegrb93** [comment]
You sure you don't got an admin mod intercepting the message?

**Comment by xaviergmail** [comment]
Absolutely. No other PlayerSay hooks either, plain sandbox

**Comment by Kefta** [comment]
Tested on vanilla local multiplayer sandbox on the dev branch and xavier is correct

**Comment by robotboy655** [comment]
Should be fixed on dev.
