### ISSUE TITLE
64-bit Server Displacements Broken

### ISSUE THREAD

**Issue by LtTaylor97** [Facepunch/garrysmod-issues#3910]
### Details
When running a 64-bit dedicated linux server, most maps have a recurring issue that ragdolls, props, etc., however not NPCs or Players, fall through the displacements. Does not effect 64-bit clients playing in singleplayer.

### Steps to reproduce
Start up a 64-bit version of SRCDS, load up your preferred map with plenty of displacements, and spawn some props. Confirmed to occur on the rp_zaton_remaster map and rp_ineu_valley2_v1a. Both maps function perfectly fine on a 32-bit Server.

**Comment by willox** [comment]
This is something I'm aware of but won't be able to provide a fix for until a few weeks time. There's no workaround until then.

**Comment by willox** [comment]
finally fixed
