### ISSUE TITLE
Half-Life Deathmatch: Source doesn't mount the Half-Life data included with it

### ISSUE THREAD

**Issue by Spyro201** [Facepunch/garrysmod-issues#3911]
### Details
Mounting Half-Life Deathmatch: Source doesn't mount any of the Half-Life data, causing the maps to not load any of Half-Life's textures or models. Having Half-Life: Source mounted alongside Deathmatch would probably fix it, however Gmod should still mount the Half-Life file included with the game, at least if one doesn't have Half-Life: Source.
### Steps to reproduce
Simply mount Half-Life Deathmatch: Source, most likely without Half-life: Source, then load one of the game's maps.

**Comment by robotboy655** [comment]
Fixed
