### ISSUE TITLE
SoundInfo Structure Entity returns LocalPlayer() clientside

### ISSUE THREAD

**Issue by nykez** [Facepunch/garrysmod-issues#3916]
### Details
Tell us exactly what happens, every single detail that you can think of

https://wiki.garrysmod.com/page/GM/EntityEmitSound
https://wiki.garrysmod.com/page/Structures/EmitSoundInfo

SoundInfo Structure Entity returns LocalPlayer() client-side. I am not sure if this is intended or how Source Engine behaves -- all sounds client-side are created by the LocalPlayer() despite being emitted by another entity? It would be nice to actually get the real entity that the sound is coming from. Currently a workaround is getting the SoundInfo vector and searching entities around that vector (which is the LocalPlayer() position), of course this is bad when multiple entities are in the same area.

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

1. Spawn a Zombie NPC
2.

Run: 

```
hook.Add("EntityEmitSound", "test123", function(soundData)
    print(soundData.Entity == LocalPlayer())
end)
```

**Comment by robotboy655** [comment]
I'd imagine this is just due to how it works, and I am having trouble reproducing this consistently, I was only able to do it once.

I am assuming this only happens in multiplayer?

**Comment by robotboy655** [comment]
Cannot reproduce this.
