### ISSUE TITLE
func_breakable_surf shattering sounds play at map origin

### ISSUE THREAD

**Issue by DanilaFoxPro** [Facepunch/garrysmod-issues#3917]
### Details
When a func_breakable_surf is shattered, it plays an additional shattering sound in addition to regular impact sounds. The problem is that sound is always played at the origin of the map, instead of the surface location.

### Steps to reproduce
Find or create a map where there is func_breakable_surf glass, shatter it.

**Comment by robotboy655** [comment]
Fixed
