### ISSUE TITLE
mat_fillrate regression

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#3918]
### Details
I'm not entirely sure when this happened, but I know for a fact it worked flawlessly 1-2 years ago.

### Steps to reproduce
Sandbox, gm_construct, spawn a load of spammy translucent texture particle emitters.

Bind a key to `incrementvar mat_fillrate 0 1 1` and toggle it on/off manually to notice that it becomes a dark red after only a few frames.

You can see what the "expected" behavior is by using this: `lua_run_cl local t = false hook.Add("PreRender", "asd", function() RunConsoleCommand("mat_fillrate", t and 1 or 0) t = !t end)`

**Comment by robotboy655** [comment]
Fixed.
