### ISSUE TITLE
ClientSideModel Matrix Invalid after creation until non-zero angles given to SetAngles.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3919]
Here's the work-around
https://github.com/thegrb93/StarfallEx/blob/hologram-rework/lua/starfall/libs_sh/holograms.lua#L146
(Note: 'null angle' in that comment means Angle(0,0,0))

Without it, the rotation matrix is all 0s
[0.00000,	0.00000,	0.00000,	372.32327]
[0.00000,	0.00000,	0.00000,	-110.91928]
[0.00000,	0.00000,	0.00000,	-12287.71875]
[0.00000,	0.00000,	0.00000,	1.00000]

This causes LocalToWorld, GetMatrix, and other stuff dependent on it to not work.

**Comment by robotboy655** [comment]
Fixed.
