### ISSUE TITLE
Rollermine doesn't blow up when ignited underwater

### ISSUE THREAD

**Issue by Dobbi124** [Facepunch/garrysmod-issues#3924]
### Details
If you ignite a rollermine, and put it underwater, it won't explode, and it has weird behavior overall.

I'm unsure if this happens in multiplayer or not.
### Steps to reproduce
1. Spawn a Rollermine
2. Right click on the Rollermine, and press the Ignite button
3. Put the Rollermine underwater

**Comment by robotboy655** [comment]
This is the exact same behavior as Half-Life 2, you just never see them on fire.

Changed it so it extinguishes itself which makes it explode.
