### ISSUE TITLE
Duplicatior does not store large contraptions properly

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#3927]
### Details
Garry's mod regular duplicator is unable to store large rail loops created by the track assembly tool. The Icon of the dupe is not created when `Save Dupe` is clicked. The Icon flashes, but it is not added to the list of the dupes. There is no error present only as far as I know of. The duplicator just won't store the large dupe.

### Steps to reproduce
1. Install the [Track assembly tool](https://github.com/dvdvideo1234/TrackAssemblyTool)
2. Create a fairly large rail loop with `150-200` props
3. Pick up the `regular` Gmod duplicator tool
4. Right-click on the contraption
5. Hit `Q` and go to `Dupes`
6. Click on `Save Dupe`

### Console output
ServerLog: Player [1][[Sk$Bh]Trick or treat KID!] requested a Dupe. Size: 150933 ( 8347 compressed, 1 parts )
Received dupe. Size: 8347
Saved!

**Comment by robotboy655** [comment]
Have you tried updating the list of dupes?

**Comment by dvdvideo1234** [comment]
So far I sis not. I will write you as soon as I get home.. Does the dupe has to be save first to be uploaded later second ??

**Comment by robotboy655** [comment]
I have no idea what you are talking about, but yes, the Dupe needs to be saved first before it can be uploaded to workshop.

I will fix the list not updating automatically when saving a dupe, which I assume is the problem here.

**Comment by dvdvideo1234** [comment]
@robotboy655 

> 6. Click on Save Dupe

It is right there ;) The issue is about saving the dupe.

**Comment by dvdvideo1234** [comment]
@robotboy655

I noticed that that menu is not updated when you click `Save Dupe`, but is updated when you click something else. You can see the following video, where the bug is reproduced at exactly 2:23 when the button is clicked. When other link is clicked, the dupes list is refreshed normally.

https://drive.google.com/file/d/1Y59_rb6RZgccOKvl1YYOrSvphlxGUcyi/view?usp=sharing

**Comment by robotboy655** [comment]
The menu not updating is already fixed in Dev
