### ISSUE TITLE
constraint library crash with players due to phys_constraint_system

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3928]
Using ropes on players will eventually crash the game after removing the rope and roping again. Solution is to not add the player entity to a phys_constraint_system when roping.

**Comment by robotboy655** [comment]
You cannot use ropes on players by default.

**Comment by thegrb93** [comment]
You can actually, I was just as surprised lol

**Comment by robotboy655** [comment]
Well I just tested it with a bot, and no you can't.

**Comment by thegrb93** [comment]
I was roping props to myself last night, but I'll verify my constraint library is unaltered tonight.

**Comment by robotboy655** [comment]
You should be looking at your tools, not the library I think.

**Comment by thegrb93** [comment]
No, I did it with lua_run constraint.Rope()

**Comment by robotboy655** [comment]
Well I may look into it, but just don't do it on players.

**Comment by thegrb93** [comment]
From what I was told, a player check here, https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L139 will resolve the crash, but I'll have to test that.

**Comment by neico** [comment]
Wouldn't it be better to use `CanConstrain` [here](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L278)?

**Comment by thegrb93** [comment]
No, because we want ropes to work on players still, which they do, just don't want it to crash.

**Comment by robotboy655** [comment]
Well I can't make it crash, here's what I have tried:
```
concommand.Add( "constrain",function( ply,cmd, args )
local tr = ply:GetEyeTrace()
if ( !IsValid( tr.Entity ) ) then print("Can't constrain to that") return end
	local sys, rope = constraint.Rope( ply, tr.Entity, 0, 0, Vector(0, 0, 36), tr.Entity:WorldToLocal( tr.HitPos), ply:GetPos():Distance( tr.HitPos), 0, 0, 1, "cable/rope", true )
	timer.Simple( 5, function()
		sys:Remove()
		rope:Remove()
	end )
end )
```

**Comment by thegrb93** [comment]
Maybe that sys:Remove() is preventing the crash? My test only had one Remove. I'll test it out again.

**Comment by robotboy655** [comment]
Well if you are only removing the rope, then you are never removing the constraint itself, so basically you will eventually have a billion constrains.

**Comment by thegrb93** [comment]
Can't reproduce the crash anymore. Weird
