### ISSUE TITLE
hl1 npc gib problems

### ISSUE THREAD

**Issue by marigi64** [Facepunch/garrysmod-issues#3930]
- hl1 alien controller's gibs are hl2 skulls when blown up.

- Barnacles also spit out hl2 skulls rather than the proper gibs
![gm_construct0037](https://user-images.githubusercontent.com/53112738/62680400-7fe22380-b9fa-11e9-9c75-4f4ba860c794.jpg)

- one of the hl1 skull gibs textures uses the hl2 skull
![gm_construct0033](https://user-images.githubusercontent.com/53112738/62680440-97211100-b9fa-11e9-8b40-91ed1f582be2.jpg)

- gibs from hl1 npcs still cast shadows from lamps after fading away
![gm_construct0035](https://user-images.githubusercontent.com/53112738/62680421-8d97a900-b9fa-11e9-9916-9d595b86bda0.jpg)

**Comment by robotboy655** [comment]
All should be fixed except for the hl2 skull in hl1 model, don't think its too big of a problem and it will take longer to fix than everything else here combined.
