### ISSUE TITLE
Hl1 weapons still spawnable when content isn't mounted by server

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3933]
gm_giveswep weapon_gauss

**Comment by thegrb93** [comment]
print(IsMounted( "hl1" ))

is returning true despite mount.cfg having

//  "hl1"              "hl1"

**Comment by thegrb93** [comment]
mountdepots.txt
```
"gamedepotsystem"
{
	"cstrike"	"1"
	"tf" "1"
	"hl1"		"0"
	"hl1_hd"	"0"
	"hl2"		"1"
	"hl2mp"		"1"
	"episodic"	"1"
	"ep2"		"1"
	"lostcoast"	"0"
}
```

**Comment by robotboy655** [comment]
"0"s in mountdepots.txt still count as "I want that to be mounted" because reasons.

**Comment by thegrb93** [comment]
I see, I'll remove it then.

**Comment by robotboy655** [comment]
I have fixed this behavior for next update.
