### ISSUE TITLE
move_rope visual bug on x86-64

### ISSUE THREAD

**Issue by B-Xerxes** [Facepunch/garrysmod-issues#3935]
when placing a rope entity in the x86-64 build of GMod (on both the x32 and x64 executables) every odd node in the rope will be significantly brighter than it should be resulting in an odd banded appearance

this doesn't happen on the regular build of GMod and only happens in the x86-64 build
![move_ropebug](https://user-images.githubusercontent.com/6752026/62822581-687f7380-bb7d-11e9-98c7-50f90ef87d20.png)

**Comment by willox** [comment]
The fix for this will be on Steam in a bit.
