### ISSUE TITLE
SWEP:DoDrawCrosshair not called when spectating

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-issues#3936]
### Details
SWEP:DoDrawCrosshair is not called when spectating someone with the swep in question

### Steps to reproduce
add 
```lua
function SWEP:DoDrawCrosshair(x,y) surface.SetDrawColor(color_black) surface.DrawRect(0, 0, 300, 300)
```
and then spectate someone with the swep

**Comment by robotboy655** [comment]
Do you know if https://wiki.garrysmod.com/page/WEAPON/DrawHUD works?

**Comment by meepen** [comment]
Yeah I used that for a sniper scope with the lines in the dodrawcrosshair
and the scope textures rendered

**Comment by robotboy655** [comment]
Well it is not called for a very simple reason which is that the HUD is disabled when you are dead. Same goes for Health & Ammo, and I am not sure what's the best approach here. I have made a fix, but I won't be including that into the Septembers update.

**Comment by mcNuggets1** [comment]
So?
