### ISSUE TITLE
Dying while under the influence of trigger_playermovement's auto-crouch breaks crouching

### ISSUE THREAD

**Issue by gooball60** [Facepunch/garrysmod-issues#3939]
If you die while inside of a trigger_playermovement with auto-crouch flagged, your crouch ability is bricked until the server is restarted.

**Comment by Kefta** [comment]
Maybe EndTouch is not being called when the player dies, thus https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/triggers.cpp#L4195 isn't ran. If that were the case, you wouldn't be stuck crouched forever but rather until the next time you touched and untouched the trigger_playermovement.

**Comment by gooball60** [comment]
Even if you re-touch the trigger_playermovement, the crouching is still bricked. As far as I can tell, a disconnect/reconnect is the only way to fix it.

**Comment by robotboy655** [comment]
In my testing retouching the brush does fix it. (on exiting the brush)

`EndTouch` is running, but `UnforceButtons` is not because it doesn't pass `IsAlive` check in the filter.

But anyway, fixed it by unforcing all buttons on death, just before `PostPlayerDeath` hook is called.
