### ISSUE TITLE
Some blood colors do not seem to display correctly

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#3940]
### Details

It seems that some blood colors cause a display error (red crosses). I tested all the colors as it is written in the [documentation](https://wiki.garrysmod.com/page/Enums/BLOOD_COLOR), but only the first 4 seem to work, the others cause the problem.

**Screenshots** : [1](https://cdn.discordapp.com/attachments/454995467151867905/611519684327637016/Screen-1.png) [2](https://cdn.discordapp.com/attachments/454995467151867905/611519685946507274/Screen-2.png) [3](https://cdn.discordapp.com/attachments/436575988231569410/608975798166355980/unknown.png)
(The last screenshot was taken on my multiplayer server on the DarkRP gamemode).

I tested this in singleplay with sandbox gamemode with the launch parameters "-noaddons" and "-noworkshop". This problem is also present on a multiplayer server.
Counter-Strike: Source, Half-Life 2 Episode 1 & 2 are mounted on my game.

I tried to find a solution to my problem on the internet, discord servers about Garry's Mod scripting or about the issues reported on this github, but I don't think I found anything.

I think it's a game bug because I did several tests on games without addons or anything but I still have the same problem. I have also asked other people to do the same test as me but they also have the same problem. As far as missing content is concerned, I don't think the blood of antlions or zombies comes from games other than Half-Life 2.

### Steps to reproduce

- Start singleplayer on sandbox gamemode.
- Run "sv_cheats 1" then "thirdperson" in developer console (for see the problem).
- Change the color of the blood like `lua_run Entity(1):SetBloodColor(BLOOD_COLOR_ZOMBIE)` or in any other way.
- Get shot by an NPC.
- Enjoy !

If you need more details or a temporary solution to bring me, I would be happy. Thank you! 👍

**Comment by robotboy655** [comment]
As a workaround you can use the following on the server:
`
PrecacheParticleSystem("blood_impact_antlion_01")
PrecacheParticleSystem("blood_impact_zombie_01")
PrecacheParticleSystem("blood_impact_antlion_worker_01")
`

I will ensure the effects get precached for you automatically in a future update..
