### ISSUE TITLE
Grenades, RPG and SLAMs' ammo problem

### ISSUE THREAD

**Issue by wasplay** [Facepunch/garrysmod-issues#3941]
Running the code below serverside with the weapons listed above doesn't update the weapon's ammo count clientside (The HUD displays 0 ammo, but you can throw a grenade anyway)

ply:Give("weapon_frag", true)
ply:GiveAmmo(1, "Grenade")

Tested on an empty custom gamemode based on "base"

**Comment by robotboy655** [comment]
The ammo count is updated properly on the client as far as I can tell with `lua_run_cl print(Entity(1):GetAmmoCount("Grenade"))` it seems to be a problem with only the default HUD, your custom HUDs should not be affected.

**Comment by robotboy655** [comment]
Actually ended up a bit more serious than HUD, but fixed anyway.
