### ISSUE TITLE
stunstick sparks on crowbar

### ISSUE THREAD

**Issue by marigi64** [Facepunch/garrysmod-issues#3943]
When picking up a stunstick (not equipping it) the crowbar emits sparks when swinging. This gets fixed after equipping the stunstick.

![ezgif-4-206ad4da9767](https://user-images.githubusercontent.com/53112738/63137129-3d32d380-c018-11e9-83ec-26b8de1bd18c.gif)

**Comment by robotboy655** [comment]
Should be fixed in Dev.
