### ISSUE TITLE
need more MAX_DOWNLOADABLE_FILES 

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-issues#3945]
we need more MAX_DOWNLOADABLE_FILES 
my server have 50000 files
and in my country , workshop download speed is really low(10kb/s)because there are no workshop servers

**Comment by robotboy655** [comment]
If you need 50k files, you are doing something. I will not be changing it to 50k.Optimize your content.

**Comment by wackod** [comment]
what for?

**Comment by wackod** [comment]
Downloading files costs my server traffic anyway

**Comment by wackod** [comment]
a sandbox server that have more than 50 addons will have more than 8k files
example  a swep addon  it will have  about 50 files    mat model  sounds
a mat will have a lot of vmt vtf     a model will have mdl vtx phy   and weapon will have a lot of sound file  like  fire  reload  ...

**Comment by wackod** [comment]
and use lua can download files in game without limit too [https://www.gmodstore.com/market/view/4868](url) (but it will lag game) 
so why limit it in loading?

**Comment by thegrb93** [comment]
I hate workshop as well due to relying on its servers being up, but its a necessary evil.
