### ISSUE TITLE
Nextbots have weird shadows

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-issues#3947]
For as long as I remember, shadow have always looked weird on nextbots. The level of detail seems to change from very detailed to very ugly without any transition.

When you are close to the nextbot they look normal: (the zombie on the ~~left~~ right (hi Roach) is a NPC to compare how the shadows look)
![normal shadow](https://cdn.discordapp.com/attachments/275292955475050496/612280000602701824/unknown.png)

If you move away a bit they still look normal:
![still normal shadow](https://cdn.discordapp.com/attachments/275292955475050496/612280111517138944/unknown.png)

But if you move a little more:
![ugly shadow](https://media.discordapp.net/attachments/275292955475050496/612280171843551283/unknown.png)

Notice how the zombie's shadow still looks normal, but for some reason the nextbot's shadow now became a weird black smudge.

**Comment by thegrb93** [comment]
That's shadow LOD and it's model dependent. Try with each as the same model.

**Comment by Dragoteryx** [comment]
Nextbot on the left and NPC on the right, both using the HL2 zombie model:
![same model](https://cdn.discordapp.com/attachments/275292955475050496/612641345932099625/unknown.png)

**Comment by robotboy655** [comment]
`nb_shadow_dist 4000`

**Comment by robotboy655** [comment]
I think I will increase the default to like 3k, even tho the rest of the entities do not have a distance limit, i don't know why it exists for nextbots, but I don't feel like getting rid of it.

**Comment by Dragoteryx** [comment]
Seems like a good idea yes.

**Comment by Kefta** [comment]
Can you make -1 display the shadow from all distances?

**Comment by robotboy655** [comment]
I feel that would be pointless, just set to 16k for same result, you probably will never be able to tell above 3-5k mark anyway.
