### ISSUE TITLE
TF2 Phoneme Data Support

### ISSUE THREAD

**Issue by Seamusmario** [Facepunch/garrysmod-issues#3948]
### Details
When a voice sound file plays on a tf2 model/player the lip sync does not work.

### Steps to reproduce
Try to replace the npc's model with a tf2 player model, let the npc talk.

**Comment by Jvs34** [comment]
I believe you have to [use this function ](http://wiki.garrysmod.com/page/Entity/SetupPhonemeMappings)manually to make them work, I remember _Kilburn using this for the TF2 gamemode.

You might have to do something like `player:SetupPhonemeMappings( "heavy/phonemes" )` but I don't remember if that's correct or not.

**Comment by Seamusmario** [comment]
Alright. i'll try that.

**Comment by Seamusmario** [comment]
I have tried it, and it does not work. Lip-sync for tf2 playermodels don't work well..

**Comment by Jvs34** [comment]
I investigated it, the correct paths are "player/heavy/phonemes/phonemes", however it seems like the tf2 voicelines don't contain phoneme data anymore, so the mouth movement on tf2 models will only work if you play hl2 sounds or if you use tf2 vcd scenes.

**Comment by Jvs34** [comment]
I investigated it, the correct paths are "player/heavy/phonemes/phonemes", however it seems like the tf2 voicelines don't contain phoneme data anymore, so the mouth movement on tf2 models will only work if you play hl2 sounds or if you use tf2 vcd scenes.

**Comment by Seamusmario** [comment]
I've tried the phoneme thing with lua and tried it with HL2 voice lines. the lip sync works. however the TF2 voicelines's phoneme data don't work for Garry's Mod since their file type is MP3 and hl2's file type is WAV.

**Comment by robotboy655** [comment]
As per @Jvs34's post above, the TF2 sound files do not contain any phoneme data, there's nothing here that can be fixed.

**Comment by Seamusmario** [comment]
oof

**Comment by Seamusmario** [comment]
i can try adding phoneme data to the files.
