### ISSUE TITLE
Language.Add() Can't Override, Even After Map Reload

### ISSUE THREAD

**Issue by Steeveeo** [Facepunch/garrysmod-issues#3949]
### Details
The `language.Add()` function does not seem to be able to override existing strings, persisting so hard as to require a full game restart before changes can be seen.

I am trying to add some language support to my game mode, but currently I am unable to make any sort of swapping UI element work due to this bug. This also means that Lua Autorefresh doesn't reload my strings if I have to fix any typos.

A short version of the issue can be seen using `lua_run_cl`:
```
] lua_run_cl language.Add("test_string", "Test String 1")
] lua_run_cl print("#test_string")
Test String 1
] lua_run_cl language.Add("test_string", "Test String Override")
] lua_run_cl print("#test_string")
Test String 1
```

### Steps to reproduce
1. Create a clientside Lua file that uses `language.Add()` to set a placeholder string.
1. Print out the placeholder string.
1. Change the language string in the file from Step 1.
1. Reload the game into a new map.
1. Print out the placeholder string.
1. Observe that the string is unchanged.

**Comment by robotboy655** [comment]
This was 100% intentional, but I don't see why it should be that way, so I changed it.
