### ISSUE TITLE
Command menu_cleanupgmas can't delete unused .gma files.

### ISSUE THREAD

**Issue by michak89** [Facepunch/garrysmod-issues#3950]
Hello
It happens often, not allways. 
Usually when I run gmod console says there are some unused gma files:

```
Detecting unused .gma files...
Found unused .gma addon: sandbox_content_#p1_1524592263.gma
Found unused .gma addon: sandbox_content_#p2_1760859757.gma
Found unused .gma addon: server_content_#1_1434099778.gma
Found unused .gma addon: server_content_#2_1475054952.gma
Found unused .gma addon: server_content_#3_1693878469.gma
Finished! Run menu_cleanupgmas to clean up said files
```

After 'menu_cleanupgmas' command: 

```
Fetching subscribed addons...
Received 14 addons!
Deleting unused .gma files...
Removing addon that we are no longer subscribed to: sandbox_content_#p1_1524592263.gma
Removing addon that we are no longer subscribed to: sandbox_content_#p2_1760859757.gma
Removing addon that we are no longer subscribed to: server_content_#1_1434099778.gma
Removing addon that we are no longer subscribed to: server_content_#2_1475054952.gma
Removing addon that we are no longer subscribed to: server_content_#3_1693878469.gma
Finished!
```

Those files stay in addons folder and when I run gmod again first information is still there. 
I need to remove them manually. Also tested on my friends, menu_cleanupgmas not allways works propertly. 

Did anyone notice that before?

**Comment by robotboy655** [comment]
I think it may have something to do with the # in the name.

**Comment by robotboy655** [comment]
Can you tell me the full file path to where your game is installed at?

**Comment by michak89** [comment]
Of course: " C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\ "
Files permissins and system owners are default.

I tested just now on few addons with # in folder name and without, You are
right.



pon., 19 sie 2019 o 15:33 Rubat <notifications@github.com> napisał(a):

**Comment by robotboy655** [comment]
Well I cannot reproduce the problem:
![image](https://user-images.githubusercontent.com/3299036/63273712-23f38680-c2a7-11e9-8739-53bfd5a69842.png)

It works perfectly fine for me.

There's not much I can do if it happens "sometimes", it could very well be something on your end.
Maybe they are being restored by something on your system (check file change dates), maybe your AV blocks GMod or something, I can't tell. It shouldn't be only happening "sometimes".

**Comment by robotboy655** [comment]
That being said, I have put in some changes for the command in Dev/Next update, not sure if it will do anything for you.

**Comment by DreamsOfCyanide** [comment]
it's not just you - i used to have the same problem around two years ago and it seemingly fixed itself, haven't had a problem with menu_cleanupgmas for over a year now

**Comment by thegrb93** [comment]
Maybe there's a specific one it errors on and causes the rest to not be cleaned up.

**Comment by robotboy655** [comment]
.gma files for all new/updated addons since January 2020 should be automatically removed so this is no longer relevant.
