### ISSUE TITLE
Weird DarkRP bug in the server browser

### ISSUE THREAD

**Issue by wasplay** [Facepunch/garrysmod-issues#3951]
https://i.imgur.com/D3XhihN.jpg

There's already far too many RP servers but this makes it even worse

**Comment by robotboy655** [comment]
They are not actually pure DarkRP servers, they are renamed DarkRP gamemodes where the majority of servers report the wrong gamemode name. (they renamed the gamemode folder, but not the "nice" name). This is entirely server owner's faults.

I think this should be better in the next update, as it should show the correct-er name more of the time now. This is what it looks like for me after updating the server list:
![image](https://user-images.githubusercontent.com/3299036/63267873-a37b5880-c29b-11e9-939a-a8d3241ec566.png)
