### ISSUE TITLE
Combine balls do not seek NPCs

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3952]
### Details
In HL2 combine balls fired from the AR2 or launched by the gravity gun will attempt to find an angle towards an enemy NPC after bouncing off a wall. In GMod, they do not seek NPCs, but they do seek other players in multiplayer. Combine balls fired by combine elites will seek both NPCs and players.

### Steps to reproduce
- Fire a combine ball in a room full of NPCs
- Fire a combine ball in a room full of players

**Comment by robotboy655** [comment]
Fixed on Dev.
