### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [Facepunch/garrysmod-issues#3953]
what is this error and what is the cause?

[UG | M A S T E R|6|Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (ATS_WARP_FROM_CLIENT)
[UG | M A S T E R|6] Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (CraftSomething)
[UG | M A S T E R|6| Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (ts_buytitle)
[UG | M A S T E R|6| Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (cuffs)
[UG | M A S T E R|6| Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (asdasdadadasd32)
[UG | M A S T E R|6Lua Error:
Warning! A net message (textscreens_download) is already started! Discarding in favor of the new message! (atlaschat.istyping)

**Comment by robotboy655** [comment]
This is not a place to get help. Please visit our official Discord server for modding help:
https://discord.gg/gmod
