### ISSUE TITLE
Gmod Supports Over 128 bones, but its compile tools do not

### ISSUE THREAD

**Issue by Stiffy360** [Facepunch/garrysmod-issues#3954]
Should you try to compile a model with over 128 bones, studiomdl gives an "ACCESS VIOLATION ERROR" and the model is not generated.

If you compiled using say, SFM's toolset, which supports over 128 bones, and try to preview it in hlmv, that also crashes.

This same mesh created in SFM works just fine in gmod itself.

I can provide a mesh with over 128 bones if it needs further testing.

**Comment by robotboy655** [comment]
> I can provide a mesh with over 128 bones if it needs further testing.
Please do.

**Comment by robotboy655** [comment]
Should be fixed in Dev for both studiomdl.exe and hlmv.exe, possibly other places as well.
