### ISSUE TITLE
HL2 RPG animation inconsistency

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3955]
### Details

In singleplayer the first shot from the RPG will always play the reload animation instead of the correct firing animation. In multiplayer it varies, and could either use the correct animation or the reload animation, (reload mostly), when firing any shot except the last one. The last shot before running out of ammo will always play the correct animation, except it will use the deploy sound instead of the correct firing sound.

### Steps to reproduce

Observe the RPG's animations in multiplayer and singleplayer

**Comment by robotboy655** [comment]
Fixed.
