### ISSUE TITLE
Missing effects in multiplayer

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3956]
### Details
These effects appear in singleplayer, but not in multiplayer.
- Crowbar/stunstick blood impact/water splash (appears on other players)
- Underwater bullet trails
- Manhack death sprites
- Antlion gib props (gibbing effect works, but gibs are not spawned)
- Antlion grub blood (works when shot at, not when stepped on)

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3688
