### ISSUE TITLE
Fine tuning sliders get stuck on screen in the pre-release branch

### ISSUE THREAD

**Issue by jeos52** [Facepunch/garrysmod-issues#3957]
### Details
Releasing the context menu while fine tuning any slider will cause any tool to get stuck on screen, like the face poser for example 
This gets worse when using other tools like the adv bone tool

### Steps to reproduce
Spawn any model
Select up the face poser and right click on the model
Hold down the C key and fine tune any flex by holding down the left mouse button on any flex name
While holding down the left mouse button let go the C key
The slider will get stuck on the screen unless the model is removed 
And trying the bring up the slider will make the mouse stuck in place

**Comment by robotboy655** [comment]
Should be fixed whenever prerelase updates.
