### ISSUE TITLE
It Crashes without warning when i play on harry potter mod. I have a decent computer, i dont think thats the problem

### ISSUE THREAD

**Issue by mehmet111111** [Facepunch/garrysmod-issues#3958]
[hl2_190702_crash_2019_8_26T15_2_37C0.zip](https://github.com/Facepunch/garrysmod-issues/files/3542450/hl2_190702_crash_2019_8_26T15_2_37C0.zip)
[###](url

) Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

**Comment by robotboy655** [comment]
Looks like this addon is causing the problem for you: https://steamcommunity.com/sharedfiles/filedetails/?id=591966233 (It's installed on the server)

It uses sound.Generate, it could've been edited on the server to generate improper sounds.

**Comment by robotboy655** [comment]
I cannot reproduce the crashes, which means the problem is with the server's edited version of the addon I linked, and there's not much I can do without the server or someone else providing a sample code using `sound.Generate` and `surface.PlaySound` that would cause the crash.

**Comment by robotboy655** [comment]
Nah, neither one cause any problems, `sound.Generate` clamps invalid values.
