### ISSUE TITLE
HL2 RPG fire animation loop in multiplayer

### ISSUE THREAD

**Issue by theredcornflake** [Facepunch/garrysmod-issues#3959]
### Details
In multiplayer holding down the attack button during the RPG's reload sequence will cause the firing animation to loop continuously until let go. This bug sometimes doesn't occur and could take a few tries to reproduce, however switching weapons or respawning could increase the chances. When it does happen, it happens more frequently afterwards.

This was tested on a P2P server, on the chromium and pre-release branch, and is much more likely to happen on clients rather than the host.

### Steps to reproduce
- Start a multiplayer game
- Suicide then respawn
- Switch to RPG and hold down attack right before the laser turns on
- Keep holding down attack all the way through the reload animation

**Comment by robotboy655** [comment]
Should be fixed on Dev, will be in the next update.
