### ISSUE TITLE
VRAD fails if there are too many static props with -allowdynamicpropsasstatic

### ISSUE THREAD

**Issue by gooball60** [Facepunch/garrysmod-issues#3964]
I don't know the exact number, but when there are a certain number of static props and allowdynamicpropsasstatic is enabled, VRAD will not compute lighting (map is fullbright, no errors in compile log). I also encountered this problem with custom compilers before allowdynamicpropsasstatic was officially added to Gmod.

**Comment by robotboy655** [comment]
It probably has nothing to do with allowdynamicpropsasstatic  but just with the amount of static props.

**Comment by gooball60** [comment]
Upon further inspection, the problem went away when the size of the map was decreased (cordon bounds that is). More research required I guess.

**Comment by robotboy655** [comment]
Closing as there's no info on the supposed problem, which I still think was just too many static props in your map.
