### ISSUE TITLE
Active set gamemode is not saved

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3965]
### Details
It appears that on the dev branch it no longer saves the last selected gamemode, when restarting the game it will always default to Sandbox

**Comment by Kefta** [comment]
This was a deliberate change made. I'm not sure what issue it was addressing.

**Comment by robotboy655** [comment]
The countless support tickets of people getting stuck in TTT singleplayer not being able to open the Q menu.

**Comment by robotboy655** [comment]
Is there a problem SAVING it solves?

**Comment by ZehMatt** [comment]
Sorry I don't quite follow, so from what I understand that this is not a bug and I have to always manually change back each time I start the game?

**Comment by robotboy655** [comment]
Yes it is not a bug, you only need to change it when you start a new singleplayer/local multiplayer game.

**Comment by ZehMatt** [comment]
Well luckily I can just add +gamemode to the startup parameters, its pretty tedious to always change to your gamemode you are actively working on.
