### ISSUE TITLE
Wiki doesnt work

### ISSUE THREAD

**Issue by AlphaS-code** [Facepunch/garrysmod-issues#3966]
### Details
https://wiki.garrysmod.com/
![image](https://user-images.githubusercontent.com/26285012/64065238-ecc09600-cc13-11e9-9365-fe00326783df.png)
yep -_-

### Steps to reproduce
Turn on server

**Comment by VaasKahnGrim** [comment]
Currently I'm getting this in browser :/

![vkugtcvlug](https://user-images.githubusercontent.com/29955667/64066312-021ecb80-cbe6-11e9-848d-efed3bd6d139.PNG)

**Comment by VaasKahnGrim** [comment]
did some digging and found the aws status page. aparently a database issue is currently going on right now. not sure if its the one exactly used for facepunch but would be good to get a confirmation. especially when garry is prone to random shutdowns of things https://status.aws.amazon.com

**Comment by AlphaS-code** [comment]
AWS Works like: One server down? **NEXT!!!**

**Comment by VaasKahnGrim** [comment]
aparently their next button aint working maybe

**Comment by VaasKahnGrim** [comment]
also its back up now apparently! now to dig through it for stuff again

**Comment by robotboy655** [comment]
Not much can do about Amazon services being down.
