### ISSUE TITLE
Couldn't Init bass (14)!

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3967]
attempting to launch any branch other than default causes the game to exit with the message above
[crashes.zip](https://github.com/Facepunch/garrysmod-issues/files/3563746/crashes.zip)

**Comment by joeyjumper94** [comment]
here's the .mdmp from dev 
[hl2_190830_crash_2019_9_1T17_36_28C0.zip](https://github.com/Facepunch/garrysmod-issues/files/3563759/hl2_190830_crash_2019_9_1T17_36_28C0.zip)

**Comment by robotboy655** [comment]
Should be fixed on Dev and soon on the other branches.
