### ISSUE TITLE
Vector scope issues

### ISSUE THREAD

**Issue by Valkyrie121** [Facepunch/garrysmod-issues#3968]
### Details
local vectors do not adhere to scope

### Steps to reproduce
 run this example to view this bug

```lua
ExampleVector = Vector(0,0,0)

function breakVector(vector, newY) 
	local brokenLocal = vector 
	brokenLocal.y = newY
end

Msg("before: ")
MsgN(ExampleVector)
breakVector(ExampleVector, 500) 
Msg("after: ")
MsgN(ExampleVector)
```
but with a different datatype the logic works as expected
```lua
ExampleString = "test"

function breakString(str, newStr) 
	local brokenLocal = str 
	brokenLocal = newStr
end

Msg("before: ")
MsgN(ExampleString)
breakString(ExampleString, "hello") 
Msg("after: ")
MsgN(ExampleString)
```
### ExampleVector Results
Result
before: 0.000000 0.000000 0.000000
after: 0.000000 500.000000 0.000000

Expected
before: 0.000000 0.000000 0.000000
after: 0.000000  0.000000 0.000000

### ExampleString Results
Result
before: test
after: test

Expected
before: test
after: test

**Comment by willox** [comment]
This is intentional as vectors - and every other userdata in GMod - are reference types

**Comment by thegrb93** [comment]
Same goes for tables.
