### ISSUE TITLE
ambient_generics start silent whether the "Start Silent" flag is checked or not

### ISSUE THREAD

**Issue by LilyMcFluffyButt** [Facepunch/garrysmod-issues#3970]
As the title states, ambient_generics start quiet whether the "Start Silent" flag is on or not, meaning they never turn on upon spawn even when told to.

**Comment by robotboy655** [comment]
This doesn't seem to be true. Make sure to read through the BUG parts of the wiki page for the entity:
https://developer.valvesoftware.com/wiki/Ambient_generic

Attaching the .bsp and .vmf showcasing there's no problem, at least for me:
[gm_shitsticks.zip](https://github.com/Facepunch/garrysmod-issues/files/3579788/gm_shitsticks.zip)
