### ISSUE TITLE
NPC 357 fires at ground

### ISSUE THREAD

**Issue by teh-player** [Facepunch/garrysmod-issues#3971]
When forcing npcs to use the 357 npc they will pull their gun up before firing but they fire halfway through pulling up the gun. This causes them to fire at the ground instead of the target.

Spawn a citizen with the npc 357 and a combine soldier with any gun

**Comment by robotboy655** [comment]
There's not much we can do about NPC animations. Citizens were never meant to be able to shoot Pistols, they simply do not have proper animations for those.

**Comment by teh-player** [comment]
its weird though, npcs will have proper animations when at a lower host timescale

**Comment by robotboy655** [comment]
That can't possibly make sense, the citizen NPCs simply do not have pistol animations. Also the animations should not influence where the NPC is aiming at all any way.

**Comment by robotboy655** [comment]
I am going to close this as this is simply a visual problem with missing NPC animations which we cannot do anything about.
