### ISSUE TITLE
Saves Break doors at seemingly random points

### ISSUE THREAD

**Issue by BrewsterTKoopa** [Facepunch/garrysmod-issues#3972]
Ok, so for context, other than being a model porter for the game, i do YouTube work, so i make movie sets and save them if i need them for the future, anyhoo. when i loaded my save, all of the doors are gone, as if removed with the remover because of the white stuff that appears when you get too close to it. i did my own test with a save and the doors appear, i don't know what's going on, but it worries me.

![zs_scrapmetal_v2_fixed0000](https://user-images.githubusercontent.com/20007531/64179838-cb3cf580-ce31-11e9-83b5-3ae8b4e2be4f.jpg)
![zs_scrapmetal_v2_fixed0001](https://user-images.githubusercontent.com/20007531/64179839-cb3cf580-ce31-11e9-8c08-8dd1c392cebd.jpg)

**Comment by robotboy655** [comment]
Obvious question, does it happen with no addons? (`-noaddons -noworkshop` launch options)

**Comment by BrewsterTKoopa** [comment]
> 
> 
> Obvious question, does it happen with no addons? (`-noaddons -noworkshop` launch options)

It shouldn't, and i'm not certain, because again it could be random

**Comment by robotboy655** [comment]
If it doesn't happen without addons then this isn't a bug with the game but rather with one of your addons. I know my HL2 Tools addons does make the doors save, I did perform basic tests, but perhaps I missed something?

Please test with no addons.

**Comment by BrewsterTKoopa** [comment]
> 
> 
> If it doesn't happen without addons then this isn't a bug with the game but rather with one of your addons and this report doesn't belong here. I know my HL2 Tools addons does make the doors save, I did perform basic tests, but perhaps I missed something?
> 
> Please test with no addons.

i did test with no addons, but i'll try one more test to see if things work.

**Comment by BrewsterTKoopa** [comment]
Welp, i did a test... you're right its a workshop addon doing this.


now to figure out which addon ;w;

**Comment by robotboy655** [comment]
As I said, try the HL2 tools if you got that installed serverside. I am closing this as it isn't a bug with the game itself. If it is HL2 tools, let me know on the mod page with details exactly how you are making it happen, preferably on a non custom map, but if it is map dependent, do tell the map name and DL link.
