### ISSUE TITLE
September 2019 Update Game Crash

### ISSUE THREAD

**Issue by BamAdam265** [Facepunch/garrysmod-issues#3975]
### Details
Tell us exactly what happens, every single detail that you can think of

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Tell us how to reproduce the problem, step by step

After the September 2019 update the game has constant crashes. The crashes give no crash log or error code. I can't tell how to reproduce the problem because it provides me with nothing after the crash. All I do is start up the game and it crashes after about a minute. I have been using the "None" option under "betas" in the steam game properties. I have switched to the "Pre-Release" option with the same result. I also have no addons installed. The game was fine the day before the update which leads me to believe it is a bug with the update.

**Comment by robotboy655** [comment]
I cannot help you if you give me nothing to work with. At least post a conosle log, console opens by pressing SHIFT+ESC.

**Comment by robotboy655** [comment]
Going to assume this was caused by the memory leak issue that was fixed.
