### ISSUE TITLE
Micro-freezes on Linux

### ISSUE THREAD

**Issue by TheHellBox** [Facepunch/garrysmod-issues#3976]
### Details
It seems like my game now does something that causes it to do micro-freezes. It happens ~every second, on pure game setup with no addons.
I've made a small script to prove those freezes, it checks if FPS is lower than 50 every frame and it prints frame time into the chat. And in result, it detects FPS drops(From normal 300 fps to 15-20 fps) every second.
```lua
hook.Add("PostDrawOpaqueRenderables", "Check FPS", function()
	if (1 / FrameTime()) < 50 then
		LocalPlayer():ChatPrint("FPS: "..(1 / FrameTime()))
	end
end)
```
I haven't got another linux machine to prove that it's linux only bug, but I it looks like this.

### Steps to reproduce
Run pure game on linux machine
Try any map with any gamemode

**Comment by willox** [comment]
Try the x86-64 beta branch instead.

I've seen some desktop environments with super-high CPU usage when playing GMod before, so you should also check the usage of any running processes to see if anything is being dodgy while GMod is running.

**Comment by robotboy655** [comment]
Also try the `dev` beta branch and see if the stuttering issues are gone.

**Comment by TheHellBox** [comment]
Seems like switching to dev branch fixes the issue

**Comment by TheHellBox** [comment]
The CPU usage in normal branch is around ~30%, in x86-64 branch it uses only 15-20%

**Comment by robotboy655** [comment]
So assuming fixed then.
