### ISSUE TITLE
NW2 update issue

### ISSUE THREAD

**Issue by UnkN56** [Facepunch/garrysmod-issues#3978]
### Details
NW2 for now work incorrect. If NW2 vars defined before client connected(like initialize function), client will not receive them. EntityNetworkedVarChanged not called both NW and NW2. 
EDIT: It also doesn't work with NW vars.

### Steps to reproduce
Entity initialize function(f.e. SWEP)
```
function SWEP:Initialize()
	self:SetNW2Bool("test",true)
	self:SetNW2Float("foo",1312.123)
end
```
Testing (mp linux&window):
```
] lua_run print(Entity(700))
> print(Entity(700))...
Weapon [700][weapon_m4a4]
] lua_run print(Entity(700):GetNW2Bool("test"))
> print(Entity(700):GetNW2Bool("test"))...
true
] lua_run print(Entity(700):GetNW2Float("foo"))
> print(Entity(700):GetNW2Float("foo"))...
1312.123046875
] lua_run_cl print(Entity(700))
[NULL Entity]
] lua_run_cl hook.Add("EntityNetworkedVarChanged","1",print)
] lua_run Entity(1):SetPos(Entity(700):GetPos())
> Entity(1):SetPos(Entity(700):GetPos())...
] lua_run_cl print(Entity(700):GetNW2Bool("test"))
false
] lua_run_cl print(Entity(700):GetNW2Float("foo"))
0
] lua_run print(Entity(700):GetNW2Float("foo"))
> print(Entity(700):GetNW2Float("foo"))...
1312.123046875
```
After join PVS(entity was NULL), client haven't receive NW data.

**Comment by mcNuggets1** [comment]
Ah, that's the reason I was having NW bugs.

**Comment by mcNuggets1** [comment]
It's since the new update actually.
I am having extremely annoying bugs right now with these.

**Comment by robotboy655** [comment]
NWvars were not touched in this update **at all**.

**Comment by mcNuggets1** [comment]
That's extremely weird, right after the update NWVars began creating trouble.

**Comment by thegrb93** [comment]
>NW2vars were not touched in this update at all.

That just means something they depended on was changed.

**Comment by mcNuggets1** [comment]
Yeah, it's only affecting NW2Vars and it's definetely the update's fault.
I am having bugs with all NW2 dependant addons I created now.
Some people have NW2Vars assigned to them, which belong to other players, some weren't unset, some weren't set.
It really annoys me.

**Comment by UnkN56** [comment]
This is my mistake that I didn’t explain correctly. 
> It seems to be random, no errors, no nothing.

Its not randomly. First networked entities of connected player will be loaded fine, because they aren't NULL. So any entity which not loaded at first startup will never get networked variables. I've tested it again, NW variables works fine, but NW2 not.

To fix it I done temporary replacement of NW2 with lua based module. Maybe it would help to someone. https://github.com/UnkN56/gmodnw2replacement

**Comment by mcNuggets1** [comment]
No, it actually does more.
It also makes people have wrong vars set to them.

I changed UTime to use NW2 vars, after the update every player has a different time set to them for other players.
Every player sees something else.

It actually sends invalid vars.

**Comment by thegrb93** [comment]
Which gmod branch?

**Comment by mcNuggets1** [comment]
I'm on the base branch.

**Comment by mcNuggets1** [comment]
More players = more frequent disparities.
That's what I also noticed.

**Comment by robotboy655** [comment]
I can maybe see SWEPs stopping working (being outdated on client) because I fixed them causing a network update every frame so maybe that exposes how broken NW2vars actually are.

Why you would be using NW2vars in production is beyond me. There's a reason why they are not documented on wiki properly.

Do you have any actual anything useful regarding things being sent **incorrectly**? Reproduction code? 
Because that makes no sense whatsoever.

**Comment by robotboy655** [comment]
Oh and EntityNetworkedVarChanged works just fine when the NW2vars actually change for me. Obviously it won't be called when the PVS issue happens and they are not sent to the client.

**Comment by mcNuggets1** [comment]
I use them, because they function in a way which is more efficient and when i can use them, I try to do.
They worked before the update just fine, but after the update, when a lot of players are connected, NW2 vars are mixed up.

**Comment by robotboy655** [comment]
I need to be very clear here, they are only ever OUTDATED, not actually WRONG? ( wrong as in Player1 should have 22, but has 44 while Player2 should have 44 ( which was sent to Player1) but has 0.)

**Comment by mcNuggets1** [comment]
They are wrong, yes.
Player 1 has a different float sent to them, as Player 2.

**Comment by robotboy655** [comment]
What does that even mean?

Can you update your server to the Dev branch (it has next to no changes) and see if they are all magically fixed?

**Comment by mcNuggets1** [comment]
I will and will report back.

**Comment by mcNuggets1** [comment]
In the float case, playtimes of players are mixed up, everyone sees something else.
Even I see a wrong value, only the server can tell the real value.

**Comment by Kefta** [comment]
You shouldn't be using NWVars outside of prediction.

**Comment by thegrb93** [comment]
That doesn't make any sense. This whole issue makes me want to just replace all the NWVar functions with a net library wrapper though. It's been an issue for my server for the past 4 years.

**Comment by thegrb93** [comment]
Thumb me down, sure, but show me where on the wiki it says that NW functions should only be used inside prediction.

**Comment by willox** [comment]
nm2vars are predicted but you can use them where you want

**Comment by willox** [comment]
but they have always been buggy

**Comment by Kefta** [comment]
It's just that you gain nothing from using NWVars outside from prediction. They're just networked variables that rewind clientside for prediction - if you aren't using them for that purpose, you're just using a version of the net library that's tied to an entity and has more net overhead (NW1 Vars sync every few seconds even if there isn't a change, I am not sure if this has changed from a few years ago)

**Comment by willox** [comment]
They're datatable variables, they have plenty of benefits over the original nwvar system and over the net library. That's because data is networked _with_ the entity, it's always available and as up to date as any other datatable var.

Except for the fact that they're broken, of course.

**Comment by Kefta** [comment]
What benefits do they have over the net library except for being in sync with entity networking?

**Comment by willox** [comment]
The prediction you mentioned & the fact that they're tied to entity edicts rather than entity indexes (this is something that needs to be exposed to Lua properly.)

The fact that they network with the entity is super useful, especially in places such as ENT:Initialize.

**Comment by mcNuggets1** [comment]
Didn't fix anything.
NW2 vars are still completely bugging.

**Comment by ShadowBonnieRUS** [comment]
Also i think NW2 using one array of NWVars for all entities, and no way to clean up it like set var to nil, so if i run
```Lua
--Ent1

for i=1,2048 do
    Ent1:SetNW2Var("test"..i,true)
end

for i=1,2048 do
    Ent1:SetNW2Var("test"..i,nil)
end

--Ent2

for i=1,2048 do
    Ent2:SetNW2Var("test"..i,true)
end
```
I will get errors like "Too many NWVar names, could not add name test1" for Ent2 and other ents after operation.

**Comment by mcNuggets1** [comment]
i'm testing with around 10 players now, it seems to work again.
but I want to make sure, I wait until more player arrive.

**Comment by robotboy655** [comment]
I have putout the change in a hotfix:
https://steamcommunity.com/games/garrysmod/partnerevents/view/2886167663033379302

Not closing this issue because it describes a problem with NW2vars with PVS that needs addressing on all entities.

**Comment by UnkN56** [comment]
Seems to working with PVS. No more problems with addons. Thanks for hotfix. Also I did tests with some entities and players, there is no mistakes in networked values.
```
] lua_run_cl print(Entity(500))
[NULL Entity]
> lua_run Entity(500):SetNW2Float("test",12313.2312)
> lua_run Entity(500):SetNW2String("foo","bar")
] lua_run Entity(1):SetPos(Entity(500):GetPos())
] lua_run_cl print(Entity(500))
Weapon [500][weapon_deagle]
] lua_run_cl print(Entity(500):GetNW2Float("test"))
12313.231445313
] lua_run_cl print(Entity(500):GetNW2String("foo"))
bar
```
