### ISSUE TITLE
Extremley bad and unstable FPS since September 2019 Update

### ISSUE THREAD

**Issue by TrackLab** [Facepunch/garrysmod-issues#3979]
### Details
In some Maps (not all) I, and other Players now get extremely low FPS, ranging from 1 to 100 and more. It also is very unstable, as in the FPS goes from 9 to 30 in a second, then up for 21, then to 3 and so on.
Many more people complained about this Problem in Discussions already, so it definitely is a Problem many people are facing.

### Steps to reproduce
For Example when playing this map https://steamcommunity.com/sharedfiles/filedetails/?id=1841756814
a friend and I now have the bad and unstable FPS Problem. The Problem did not occur before the September Update.

**Comment by robotboy655** [comment]
This should already be fixed on all of the beta branches.

**Comment by robotboy655** [comment]
It will be fixed in live soon-ish.
