### ISSUE TITLE
npc_apcdriver / npc_vehicledriver is Broken?

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#3983]
### Details
First of, after the _NPC Improvement_ Garry's Mod update, some Vehicle Driver NPCs Entity (`npc_apcdriver` and `npc_vehicledriver`) does not seems doing anything in-game. This happens on every HL2 Maps even my basic created maps (APC, the Driver Entity, and simple Paths)

For `npc_vehicledriver`, They seems only doing nothing once triggered from `startforward` entity input, but has handbrake off and if you push with gravitygun/physgun, the steering follows to the path. However, `npc_apcdriver` completely have handbrake on, it does not even move and the steering seems to be locked.

**Branch**
Using Garry's Mod on branch x86. Haven't tried on other Branch x64 version or Beta. If anyone else is also having similar problem with this entity on x64, you can also tell it here.

### Steps to reproduce
- Create a basic flat map, with 1 `prop_vehicle_apc` OR `prop_vehicle_drivable`
- Make an entity of `npc_vehicledriver` or `npc_apcdriver`, make sure they driving the APC
- Make a simple 3 points of path and make sure they start from First Path's point
- Make a trigger entity (brush or logic_relay) with `startforward` input to the Driver
- See the action.

**Additional Proof**
on Garry's Mod (it stays there, does not move)
![gmod apcdriverbug](https://user-images.githubusercontent.com/11814682/64435749-3c5c0180-d0ed-11e9-928d-4b32780d82bc.jpg)

on Half-Life 2 (working as normally it should)
![hl2 apcdriverwork](https://user-images.githubusercontent.com/11814682/64435756-4120b580-d0ed-11e9-9de6-5e990bc0f7d8.jpg)

**Comment by robotboy655** [comment]
My bad, fixed.

It was related to the suicide via Gauss Gun in Jeeps fix.

**Comment by Vinzuerio** [comment]
Thank you!
