### ISSUE TITLE
Loading an Additional Sentence File via 'PrecacheSentenceFile' Causes All Connected Clients of a Remote Server to Incorrectly Receive Sentences

### ISSUE THREAD

**Issue by AgentAgrimar** [Facepunch/garrysmod-issues#3987]
Loading a sentence file using the 'PrecacheSentenceFile' binding will only affect the serverside of the sentences system because it can only be executed on the server, and would otherwise only work fine on the client when done on a listen server.

When a sentence is played on the server, it possibly networks an index over to the client and it will hear what's at that index, whether it's correct or not.

This is a bit of an issue for the 'Voice Packs' feature I have in my source port of Half-Life 1/2's H.E.V. Suit voice system which utilizes the sentences system and I'd like for this feature to support multiplayer.

Would it be possible to introduce a clientside version of the binding?

**Comment by robotboy655** [comment]
It is now shared
