### ISSUE TITLE
Keydown JS events do not work on x86-64 branches

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-issues#3993]
### Details

On the macOS **x86-64** branch, and the Ubuntu **[chromium]** and **x86-64** branch, keydown JS events seemingly do not work. Oddly enough, they do work on the macOS **[chromium]** branch.

I did not test this on stable, because it is my understanding that the Awesomium implementation is on a bug fix freeze. 

I'm not sure what the root cause of this issue is-- I'm doing my best to connect the dots without much visibility. At the very least, I think this issue shows that there are inconsistencies between implementation across all the OSes.

### Steps to reproduce
I tested the following code on several variants of Garry's Mod:

```lua
local browserFrame = vgui.Create("DFrame")
browserFrame:SetSize(ScrW(), ScrH())
browserFrame:SetPos(0, 0)
browserFrame:SetVisible(true)
browserFrame:SetDraggable(true)
browserFrame:SetSizable(true)

local html = vgui.Create("DHTML" , browserFrame)
html:Dock(FILL)
html:OpenURL("https://duckduckgo.com/html/")

browserFrame:MakePopup()

html:RunJavascript([[
    window.addEventListener('keydown', (function (e) {
        console.log('e.keyCode: ' + e.keyCode);
    }));
]])
```

macOS **10.14.5**, Garry's Mod **[chromium] 2019.09.05**:

![macos chromium 20190905](https://user-images.githubusercontent.com/1774125/64901855-e696d480-d66b-11e9-8704-9cc352f9eb3b.png)

macOS **10.14.5**, Garry's Mod **x86-64 2019.09.04**:

![macos x64 20190904](https://user-images.githubusercontent.com/1774125/64901858-fe6e5880-d66b-11e9-81dd-0132a7b84ff1.png)

Ubuntu **18.04**, Garry's Mod **[chromium] 2019.09.05**:
![ubuntu chromium 20190905](https://user-images.githubusercontent.com/1774125/64901862-0e863800-d66c-11e9-8ac3-b787ed7c813a.png)

Ubuntu **18.04**, Garry's Mod **x86-64 2019.09.04**:
![ubuntu x64 20190904](https://user-images.githubusercontent.com/1774125/64901866-13e38280-d66c-11e9-898a-47cd2582be60.png)

**Comment by willox** [comment]
fyi any non-64-bit macOS build is still using Awesomium. I'm surprised that this isn't a macOS only bug (the Linux implementation is quite solid), but i'll take a look into it soon.

**Comment by rbreslow** [comment]
@willox I was a bit skeptical that this would only happen on *nix-variants, so I tested on Windows 10, Garry's Mod **[x86-64] 2019.09.04**:

![image](https://user-images.githubusercontent.com/1774125/64910215-d7eb0480-d6e1-11e9-87cf-5bb9818857b3.png)

My bad for not being more thorough when opening this issue -- it just seems like a regression overall.

I also tested `document.getElementById();`:

```lua
local browserFrame = vgui.Create("DFrame")
browserFrame:SetSize(ScrW(), ScrH())
browserFrame:SetPos(0, 0)
browserFrame:SetVisible(true)
browserFrame:SetDraggable(true)
browserFrame:SetSizable(true)

local html = vgui.Create("DHTML" , browserFrame)
html:Dock(FILL)
html:SetHTML([[
    <!DOCTYPE html>
    <html>
    <head>
    <title></title>
    </head>
    
    <body>

    <input id="hello" type="text" />

    </body>
    
    </html>
]])

browserFrame:MakePopup()

html:RunJavascript([[
    document.getElementById("hello").addEventListener('keydown', (function (e) {
        console.log("e.keyCode: " + e.keyCode)
    }))
]])
```

![image](https://user-images.githubusercontent.com/1774125/64910272-6f505780-d6e2-11e9-8d1f-638607cc5822.png)

When I run that Lua snippet on Windows 10, Garry's Mod **2019.09.13**:

![image](https://user-images.githubusercontent.com/1774125/64910360-804d9880-d6e3-11e9-82c6-fbb4b37e0a1c.png)

**Comment by rbreslow** [comment]
>It might be worth mentioning that DHTML:RunJavascript immediately sends the code to the browser's process and it will try to execute with the current v8 context, which might not be ready yet.

I think that's what is happening here. After waiting for [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event), things work:

```lua
local browserFrame = vgui.Create("DFrame")
browserFrame:SetSize(512, 512)
browserFrame:Center()
browserFrame:SetVisible(true)
browserFrame:SetDraggable(true)

local html = vgui.Create("DHTML" , browserFrame)
html:Dock(FILL)
html:SetHTML([[
    <!DOCTYPE html>
    <html>
    <head>
    <title></title>
    </head>
    
    <body>

    <input id="hello" type="text" />

    </body>

    <script>
        window.addEventListener("DOMContentLoaded", function(event) {
            gmod.DOMContentLoaded()
        })
    </script>
    
    </html>
]])
html:AddFunction("gmod", "DOMContentLoaded", function()
    html:RunJavascript([[
        window.addEventListener('keydown', (function (e) {
            console.log("e.keyCode: " + e.keyCode)
        }))
    ]])
end)

browserFrame:MakePopup()
```

![image](https://user-images.githubusercontent.com/1774125/64912089-3327f180-d6f8-11e9-859c-4b88fb004d6a.png)

I would consider adding documentation for this new behavior, as it has the potential to break other folk's applications that rely on DHTML. Is it possible that `DHTML:SetHTML` was blocking beforehand?
