### ISSUE TITLE
Return value from JS method created with DHTML:AddFunction() is undefined

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-issues#3995]
### Details

The return value from a JavaScript method created with [`DHTML:AddFunction()`](https://wiki.garrysmod.com/page/DHTML/AddFunction) is `undefined` on the x86-64 branch. This is a regression from stable. 

>Everything with the Chromium panel is properly asynchronous, but the same can't really be done with Awesomium.

Not sure if this has to do with differences in CEF execution context.

### Steps to reproduce

Execute the following Lua snippet:

```lua
local frame = vgui.Create("DFrame")
frame:SetSize(ScrW(), ScrH())
frame:SetVisible(true)
frame:Center()

local html = vgui.Create("DHTML" , frame)
html:Dock(FILL)
html:OpenURL("https://duckduckgo.com/html/")
html:AddFunction("message", "get", function()
    return "Hello World!"
end)

frame:MakePopup()

html:RunJavascript([[
    console.log("Message from Garry's Mod: " + message.get())
]])
```

Windows 10, Garry's Mod **2019.09.13**:

![windows10 stable](https://user-images.githubusercontent.com/1774125/64909982-38794200-d6e0-11e9-9e4d-ffa22311a6fb.png)

Windows 10, Garry's Mod **[x86-64] 2019.09.04**:

![windows10 x64](https://user-images.githubusercontent.com/1774125/64909985-3dd68c80-d6e0-11e9-8f23-c2fcb68c6a4e.png)

**Comment by willox** [comment]
It's gonna stay like this. You can pass a callback as the last param to message.get if you want its result still.

**Comment by rbreslow** [comment]
Something like this? I tried it and it didn't work.

```javascript
message.get(function(str) {
    console.log("Message from Garry's Mod: " + str)
})
```

Is there a branch of the docs for the next update where this behavior will be described?

**Comment by willox** [comment]
It's used in `garrysmod/html/js/svc.Tranny.js` to call language.Update.

**Comment by rbreslow** [comment]
Gotcha. I don't believe there's visibility into the definition of `language.Update`, so I wonder if there's more I need to do when I execute `DHTML:AddFunction()`. 

The snippet I posted above seems to align with what's going on in [`svc.Tranny.js`](https://github.com/Facepunch/garrysmod/blob/2cecb169b958fc13602782e6294a51dab6191e8c/garrysmod/html/js/svc.Tranny.js#L14-L18), yet it doesn't work.

**Comment by willox** [comment]
It could be a case of my implementation failing if your callback is the first param, try passing something else to it before the callback.

**Comment by rbreslow** [comment]
I tried passing something else to it before the callback:

```diff
diff --git a/demo-a.lua b/demo-b.lua
index fd4fae4..5eb3adc 100644
--- a/demo-a.lua
+++ b/demo-b.lua
@@ -6,15 +6,15 @@ frame:Center()
 local html = vgui.Create("DHTML", frame)
 html:Dock(FILL)
 html:OpenURL("https://duckduckgo.com/html/")
-html:AddFunction("message", "get", function()
-    return "Hello World!"
+html:AddFunction("message", "get", function(fromJs)
+    return "fromJs: " .. fromJs
 end)

 frame:MakePopup()

 html:RunJavascript([[
-    message.get(function(str) {
+    message.get("Hello World!", function(str) {
         console.log("Message from Garry's Mod: " + str)
-    })
+    })
 ]])
```

I'd expect the output here to be:

```
Message from Garry's Mod: fromJS: Hello World!
```

However, nothing shows up in my console.

**Comment by willox** [comment]
```
] lua_run_cl A = vgui.Create "DHTML"
] lua_run_cl A:OpenURL( "https://duckduckgo.com/html/" )
] lua_run_cl A:AddFunction( "gmod", "test", function(a) return "penis" end )
] lua_run_cl A:RunJavascript( "gmod.test( console.log )" )
[HTML] penis
```
Works for me.

I'd suggest you check that your `console.log` and `DHTML:ConsoleMessage` haven't been messed with.

**Comment by rbreslow** [comment]
I was able to confirm that your testing instructions work. Not sure what's going on on my end. 

I appreciate your patience and your help 🙏

**Comment by willox** [comment]
It might be worth mentioning that DHTML:RunJavascript immediately sends the code to the browser's process and it will try to execute with the current v8 context, which might not be ready yet.

There does exist a QueueJavascript function that'll wait for the page to be loaded first, but it relies on the IsLoading function which is not great (for backwards compatibility reasons.)

I'd expect that the best approach is to have something like an OnDOMReady event on the JavaScript side to tell your Lua when it is ready.
