### ISSUE TITLE
Crash while in main menu with no error message

### ISSUE THREAD

**Issue by Ghostly082** [Facepunch/garrysmod-issues#3996]
After launching the game, when in the main menu, after about 10-15 seconds, the game crashes, with no error message.

I managed to find a crash report.  
[hl2_190913_crash_2019_9_15T17_45_49C0.zip](https://github.com/Facepunch/garrysmod-issues/files/3614087/hl2_190913_crash_2019_9_15T17_45_49C0.zip)

The crashes seem to occur every time the game has an update, or even a hotfix.

**Comment by robotboy655** [comment]
Looks like you are somehow running out of RAM in the main menu. (The game, not the PC)
I am assuming you got some hefty big Workshop addons extracting one after another.

I don't know how you achieved this, i tried installing some big addons and it doesn't crash or increase memory usage in significant amounts, as such there's nothing I can do about this.

**Comment by Ghostly082** [comment]
> Looks like you are somehow running out of RAM in the main menu. (The game, not the PC)
> I am assuming you got some hefty big Workshop addons extracting one after another.
> 
> I don't know how you achieved this, I tried installing some big addons and it doesn't crash or increase memory usage in significant amounts, as such there's nothing I can do about this.

Hi.
Thank you for getting back to me in short notice, since then, I have an update to the crashes I've been getting.

0xc0000005 is the error code that I see with hl2.exe in the Windows Event Viewer.

![gmodcrash](https://user-images.githubusercontent.com/30761068/65281507-c306da80-db00-11e9-8656-afafd77800cb.PNG)

Not exactly sure what this means, other than that, I am about to give up all hope on this issue.

**Comment by CornerPin** [comment]
Try disabling Discord overlay for Garry's Mod, it looks like it crashes the game when it tries to hook into the process.

**Comment by Ghostly082** [comment]
Hi.
I disabled the overlay, everything seems to be running without issues. Thank you two for your help!
