### ISSUE TITLE
Errors in console (Using Q menu)

### ISSUE THREAD

**Issue by Potatosayno** [Facepunch/garrysmod-issues#3997]
### Details
This one is pretty simple, I am on the DarkRP gamemode (shouldn't matter) and have found out an issue that has occured with a DarkRP feature, ended up being it also happens with the Q menu.
This simple trick will cause your console to error.

### Steps to reproduce
- Hold Q
- Go to tool search bar
- Type in there "[]" (square brackets)
- You will get errors

Garry's mod doesn't like this, and it seemed to happen with a DarkRP search bar as well.

```
[ERROR] gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:31: malformed pattern (missing ']')
  1. find - [C]:-1
   2. OnValueChange - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:31
    3. unknown - lua/vgui/dtextentry.lua:194
```

**Comment by ExtReMLapin** [comment]
disable pattern in string.find

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua#L31

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua#L42

and here

**Comment by neico** [comment]
This screams for a toggle option, I personally like how the search bar in VSCode looks like (inlined option buttons): ![VSCode Search](https://puu.sh/EhQ3s/bbc5a5a7e9.png)

**Comment by thegrb93** [comment]
Patterns are useful, but need error handling

**Comment by thegrb93** [comment]
Actually for tools pattern is unnecessary.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/f822184c3198f9c94416e42b9129fc5cf59a8a2b
