### ISSUE TITLE
http library not working (Linux?)

### ISSUE THREAD

**Issue by linkjay** [Facepunch/garrysmod-issues#3998]
### Details
Got a Linux SRCDS running on Debian 9 here. Also running on Arch Linux (latest kernel) on my desktop PC. These are the two PCs I have personally used to test this.

I have a system that posts to an ExpressJS server on my VPS. Here is the relevant code segment from my system.

```
local url = "google.com"

local function onSuccess(body, len, headers, status)
    print('successfully posted ('.. status ..')! Body: ' .. body)
end

local function onFailure(err)
    print('Error when posting! Err: ' .. err)
end

local function post() 
    local sendTbl = {
        crosser = 'true'
    }

    http.Post(url, sendTbl, onSuccess, onFailure, {
        ['Content-Type'] = 'X-www-form-urlencoded'
    })
end

post()
```

This code runs on my server and it produces this error when `url` is set to my localhost socket:

`Error when posting! Err: invalid url`

If `url` is changed to `google.com`, it produces this

`Error when posting! Err: unsuccessful`

Trying this code sample for `http.Fetch` will produce the following result:

```
local url = "google.com"

local function onSuccess(body, len, headers, status)
    print('successfully posted ('.. status ..')! Body: ' .. body)
end

local function onFailure(err)
    print('Error when posting! Err: ' .. err)
end

http.Fetch(url, onSuccess, onFailure)
```
```
httpclient.cpp (2629) : Assertion Failed: pHost && *pHost
httpclient.cpp (2629) : Assertion Failed: pHost && *pHost
Error when posting! Err: unsuccessful
```

Singleplayer on Linux produces the same results consistently.
![console image](https://i.linkjay.io/uLDbVD.png)

Here is a console command to test Fetch (should do the same thing as Post) in a server console or singleplayer console. 

```
lua_run http.Fetch("google.com", function(succ) print(succ) end, function(fail) print(fail) end)
```

My friend tested this on Windows on SRCDS and apparently it worked just fine. I'm assuming this is some Linux thing?

It's also worth mentioning that I tested my ExpressJS endpoint and it works just fine. It has to be some form of Garry's Mod issue here.

### Steps to reproduce

1. Be on Linux
2. Be either in singleplayer or SRCDS on Linux
3. Run code or command above. It should fail onto the failure function with "unsuccessful" or "invalid url"

**Comment by CornerPin** [comment]
#3980
The protocol part of the URL is required to make requests, try fetching `https://google.com`.
After the September update you can no longer make requests to localhost or IP-addresses, the workaround is to add the address to your hosts file.
