### ISSUE TITLE
Nav mesh generation seems to consistently crash the game

### ISSUE THREAD

**Issue by mandrewpowers** [Facepunch/garrysmod-issues#3999]
### Details

Been messing with nextbots again, but wanted a better test map than gm_construct. It's been some time since I generated one, but every time I enable cheats and run nav_generate it starts computing walkable space and eventually crashes failing to generate the .nav file.

_**Edit:**_ Tried to gather dumps and found out none are generating.

### Steps to reproduce

_Commands executed:_
1. `sv_cheats 1`
2. `nav_edit 1`
3. `nav_generate`

_OR_

1. `sv_cheats 1`
2. `nav_edit 1`
3. `nav_mark_walkable`
4. `nav_generate_incremental_range 500`
5. `nav_generate_incremental`

_Note:_ `nav_mark_walkable` and `nav_generate_incremental` may need a couple runs before it crashes.

_Maps I've tried on:_
* dm_runoff _(HL2DM)_
* Custom test map that is a bland cube with a skybox

_Things I tried to make it work:_
* Disabled all workshop addons
* Deleted `./lua` and `./addons`
* Removing any existing map related files and started with a .bsp by itself
* If I reduce the incremental mesh generation distance to 500 I can get it to not crash the first couple times. Once the mesh reaches a certain size it crashes.

**Comment by robotboy655** [comment]
Fixed in Dev, unfortunately had to disable the hull trace surface prop fix, it was causing this crash and I can't figure out why.
