### ISSUE TITLE
Calling BecomeRagdollOnClient() Crashes Clicnet

### ISSUE THREAD

**Issue by Pezmc** [Facepunch/garrysmod-issues#400]
I'm trying to use BecomeRagdollOnClient() to create a ragdoll of the Male_05.mdl (or any other model), I'd be using prop_ragdoll but we don't have ents.create on the client anymore.

In the following code BecomeRagdollOnClient() causes gmod to crash confirmed on both windows and osx.

```lua
function RagdollEntity(data)

    local doll = ents.CreateClientProp("models/Humans/Group01/Male_05.mdl")

    doll:SetPos( data:ReadVector() )
    doll:SetAngles( data:ReadAngle())
    doll:Spawn()
	
    if(doll:IsValid()) then
	return doll:BecomeRagdollOnClient()
    else
	print("The entity isn't valid...")
    end
end
usermessage.Hook( "RagdollEntity", RagdollEntity );
```

**Comment by Pezmc** [comment]
I'm pretty disappointed this was never looked into!

**Comment by robotboy655** [comment]
I tested your code and it didn't crash.
