### ISSUE TITLE
SetModelScale crashing server if used on ragdolls.

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4000]
### Details
When i tried to scale ragdoll to 1.5, my gmod just crashed. I tried again on flatgrass on standard ragdolls from hl2, scale to 2 also crash my gmod.

### Steps to reproduce
Spawn ragdoll, use on it :SetModelScale(2) and :Activate() serverside.

**Comment by robotboy655** [comment]
I fixed the crash, but it won't scale the ragdolls.
