### ISSUE TITLE
Calling PhysicsDestroy() on ragdolls crashing server.

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4001]
### Details
Seems to be related to traces and file:line "lua/autorun/rb655_ext_props.lua:87", but that file not exist in my lua folders

### Steps to reproduce
Spawn ragdoll and use on it :PhysicsDestroy()

EDIT:
Server crash log lua stack trace:
    0. TraceLine - [C]:-1
      1. GetEyeTrace - gamemodes/base/gamemode/obj_player_extend.lua:189
        2. fn - lua/autorun/rb655_ext_props.lua:87
          3. (null) - addons/ulib/lua/ulib/shared/hook.lua:179

I think using GetEyeTrace on player that looks on ragdoll after using :PhysicsDestroy() causes a crash.
So if you not looking at ragdoll after :PhysicsDestroy(), game will not crash, but crash if you look.

**Comment by Kefta** [comment]
"rb655_ext_props" is from one of Robotboy655's addons you have subscribed to on workshop

**Comment by ShadowBonnieRUS** [comment]
I forgot workshop subscribed addons don't start with "addons/addon_name/" in stack trace.

**Comment by robotboy655** [comment]
Fixed, but still don't do it.
