### ISSUE TITLE
shadow_control is ignored

### ISSUE THREAD

**Issue by matiasg90** [Facepunch/garrysmod-issues#4004]
since the last update, deactivating the shadows from this entity is ignored

![alt text](https://i.gyazo.com/eb882f574aa035bcb697de1c6c7710ae.png)

from the entity it is deactivated, but on the server side it is sometimes shown.
![alt text](https://i.gyazo.com/0d9fbe7d580780b3ce848a9bb5605d93.png)

And of course, this is a great impact of fps on servers with too many users.

**Comment by robotboy655** [comment]
1. The entity was not changed in the last update
2. Nothing about shadows was changed in the last update
3. It does work properly in my tests, I can attach the .bsp if you want
4. it would seem `r_shadows_gamecontrol` can override the "All shadows disabled" value if set to non 0 on client, it requires `sv_cheats` to be set to 1 however.
5. It doesn't affect shadows from Projected Textures (lamp tool, flashlight)

![image](https://user-images.githubusercontent.com/3299036/65440288-2bbbc300-de31-11e9-8aa8-f99b2553802a.png)
![image](https://user-images.githubusercontent.com/3299036/65440449-6a517d80-de31-11e9-9159-3c49980dbe0c.png)
