### ISSUE TITLE
util.TraceLine number passing number as argument in filter function leading to lua errors and then lua panic

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4006]
I'll e-mail the mdmp.

**Comment by robotboy655** [comment]
I want to see code to reproduce this, a Lua Panic minidump is just not useful.

I imagine it's a Lua Stack corruption that could've happened literally anywhere in the game, just crashed on util.TraceLine

**Comment by thegrb93** [comment]
I'll ask my friend if we can reproduce it. He was working on E2 when it happened

**Comment by thegrb93** [comment]
Not reproducible. Also seems that other lua errors were happening prior to that one.
