### ISSUE TITLE
GM:EntityEmitSound causes infinite scrape sounds

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#4008]
### Details
It appears that when one hooks/overrides EntityEmitSound and returns true in all cases it will play scrapesounds forever.

### Steps to reproduce
1.
```
function GM:EntityEmitSound(data)
    return true
end
```
2. Smash a crate.

### Examples:
Returning 'true': https://share.epic-domain.com/2019-09-29_17-18-18f07715035d345d8ba.webm
Returning 'nil': https://share.epic-domain.com/2019-09-29_17-20-37f395d3c1deca65aa2.webm

**Comment by robotboy655** [comment]
Should be fixed on Dev, as far as I could tell this was an issue only with clientside only entities, such as gibs.
