### ISSUE TITLE
Windows Defender false positive

### ISSUE THREAD

**Issue by 88MeaZZZ** [Facepunch/garrysmod-issues#4010]
### Details
When installing Garry's mod(chromium) I encountered windows defender picking up hammer.exe being a Trojan. Never had this issue up until today so I'm curious if a recent change caused this or what. VirusTotal shows only Microsoft detects it which is new. Not sure if this is something that can get changed or not...

![das](https://user-images.githubusercontent.com/56052231/66006383-575b3080-e463-11e9-8a9e-fbbd0441d6b0.png)

**Comment by robotboy655** [comment]
The last none beta update was a month ago. Nothing has changed. Its your crappy anti virus, nothing we can do about. You can use Virus Total to get the file scanned by most major AVs and see the problem is not with the file.
