### ISSUE TITLE
GetConVar():GetBool() is broken

### ISSUE THREAD

**Issue by VladUndying** [Facepunch/garrysmod-issues#4014]
### Details
GetBool() doesn't work as intended.

### Steps to reproduce
```
CreateConVar("test_cvar", "true")
print(GetConVar("test_cvar"):GetBool(), "GetBool method")
print(tobool(GetConVar("test_cvar"):GetString()),"tobool from string method")
```

![image](https://user-images.githubusercontent.com/49906580/66124309-7a214c80-e5fd-11e9-89fb-b37fd5a6a508.png)

**Comment by CornerPin** [comment]
Boolean convars use `0` as false and `1` as true, it always was this way.

**Comment by thegrb93** [comment]
GetBool looks for non zero numbers, not strings.

**Comment by neico** [comment]
ULib and ULX has a extended version of tobool, maybe you used that in the past?
https://github.com/TeamUlysses/ulib/blob/master/lua/ulib/shared/misc.lua#L423

**Comment by Kefta** [comment]
Or even the stock tobool which sees every non-"false" string as true.
