### ISSUE TITLE
HTTP cannot write body to DELETE

### ISSUE THREAD

**Issue by Zacalot** [Facepunch/garrysmod-issues#4018]
It's impossible to write an HTTP DELETE request with a body, which is useful for querying certain websites.

**Comment by bigdogmat** [comment]
If I remember correctly that's not possible with the ISteamHTTP interface which is what Gmod uses

**Comment by Zacalot** [comment]
Yeah you're correct, just looked it up. Guess I'll close this then since that's certainly not going to change.
