### ISSUE TITLE
Entity:LocalToWorld/WorldToLocal doesn't take into account the ragdoll's bone position

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4020]
Pretty much the same cause as https://github.com/Facepunch/garrysmod-issues/issues/207, the transformed position is from the origin of the ragdoll as if it were t-posed.

**Comment by thegrb93** [comment]
Can't you do physobj:localToWorld physobj:worldToLocal?

**Comment by robotboy655** [comment]
Yeah, and I don't know what result you'd expect otherwise. It uses entity position, what else do you want  it to use?

**Comment by Kefta** [comment]
I thought the normal implementation used the physobj position and wasn't just an alias of the global LocalToWorld. Guess this function is just useless then.
