### ISSUE TITLE
Combine balls generate "attempt to call string" error with props

### ISSUE THREAD

**Issue by shadow7483147** [Facepunch/garrysmod-issues#4026]
### Details
Pretty much the title.
Version 2019.09.13

Shooting a combine ball at any vphysics object that is allowed to collide with the ball will tell the user `Something is creating script errors.`
The only thing shown in console is `attempt to call a string value` every time it starts to collide.

### Steps to reproduce
Fire a combine ball at either a spawned prop, or any of the props in cs_office

**Comment by shadow7483147** [comment]
Probably something to do with an addon, retrying with -noworkshop

**Comment by shadow7483147** [comment]
Issue mysteriously went away after turning off -noworkshop

**Comment by thegrb93** [comment]
Put the whole error

**Comment by shadow7483147** [comment]
It happens both whether workshop is enable or disabled.
https://puu.sh/EsFFC.png

**Comment by Kefta** [comment]
Try -noaddons -noworkshop and verifying your game cache. I cannot reproduce the error in vanilla Sandbox on the dev branch. This looks like an addon is sending out an error that is ``pcall``ed and not printing the stack trace with it.

**Comment by shadow7483147** [comment]
You are absolutely correct. The addon was a local copy of Player Appearance Customizer from... apparently late 2016.
