### ISSUE TITLE
env_explosion sparks only appear underwater

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4027]
As reported here: https://github.com/ValveSoftware/source-sdk-2013/issues/482

https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/explode.cpp#L355

Needs to be changed to ``if ( !( UTIL_PointContents( GetAbsOrigin() ) & CONTENTS_WATER ) )``

**Comment by robotboy655** [comment]
Fixed
