### ISSUE TITLE
macOS Catalina is Broken

### ISSUE THREAD

**Issue by Tataki-Guritchi** [Facepunch/garrysmod-issues#4029]
### Details
Tell us exactly what happens, every single detail that you can think of
Due to the removal of all 32 bit support from macOS Catalina, Garry's Mod is now broken. Since the x86-64 branch has no support for macOS (even though it is a native 64-bit system), the game is unplayable.

**Comment by Woet** [comment]
As mentioned in #3894, the x86-64 branch worked great until the Garry's Mod update 2 days ago. Now it just shows the blue loading screen and crashes after "Finished!".

**Comment by Woet** [comment]
Crash dmp and txt files can be found here: [gmod_crashes.zip](https://github.com/Facepunch/garrysmod-issues/files/3747382/gmod_crashes.zip)

-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

-Console Buffer-
================
8(27.156612):  ConVarRef joystick_force_disabled doesn't point to an existing ConVar
7(27.039395):  Not playing a local game.
6(26.040516):  Convar r_flashlightdepthtexture has conflicting FCVAR_ARCHIVE flags (child: has FCVAR_ARCHIVE, parent: no FCVAR_ARCHIVE, parent wins)
5(26.040346):  Parent cvar in server.dll not allowed (props_break_max_pieces)
4(26.040246):  Convar mat_motion_blur_enabled has conflicting FCVAR_ARCHIVE flags (child: has FCVAR_ARCHIVE, parent: no FCVAR_ARCHIVE, parent wins)
3(26.040048):  Parent cvar in server.dll not allowed (p2p_enabled)
2(24.824956):  Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
1(23.341263):  Attempting to load Chromium...

**Comment by ArbyAndy** [comment]
TEMPORARY FIX FOR MACOS CATALINA x64 GMOD USERS:
Delete the html_chromium.dylib from /Contents/MacOS/html_chromium.dylib which is inside the actual package of the game, GarrysMod.

This will disable the main menu's buttons, but at least you can still load in **without it instantly crashing** & you can use console to direct connect to servers, servers like DarkRP with radios & chromium etc do not seem to cause errors, the 64 bit GMod on MacOS is actually pretty O.K.

**Comment by Kefta** [comment]
There should probably also be a Chromium milestone.

**Comment by IWillAskQuestions** [comment]
This is still happening, for me at least. Have the latest Gmod and Steam, and it seems like there's no way to go back to when it did work. Any news if it's getting fixed? Plus, I don't think the method ArbyAndy mentioned doesn't work anymore, as there is no such file, with the 64-bit branch at least. And Chromium doesn't support 64-bit either.

**Comment by ArbyAndy** [comment]
The file is inside of the application itself & should work on the x64 branch, just tested it today?

**Comment by niemtec** [comment]
I also cannot locate the file like @IWillAskQuestions. The loading screen opens up and fails after "Finished!" is displayed after which the game crashes.

**Comment by willox** [comment]
Should be fixed on the x86-64 branch
