### ISSUE TITLE
Undo'ing stuff in the middle of the undo list screws up undo ordering for new undo's

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4031]
Undo some stuff in the middle of your undo list, then spawn some props, then try to undo those with 'z' and instead, other stuff before the props were spawned gets undo'd.

**Comment by robotboy655** [comment]
I cannot confirm this following your steps with props. Are you doing this with no addons?

**Comment by robotboy655** [comment]
Nevermind, it only works with undoing one thing

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/e0898e6b2ddec877a7945f596b9c9519ebc35a88
