### ISSUE TITLE
Mirror glowing bugs

### ISSUE THREAD

**Issue by CyberOne25** [Facepunch/garrysmod-issues#4033]
Glows don't work right with mirrors. If you have a mirror in which you can see the origin of a glow but don't see the origin of the glow directly, it doesn't glow. But if you see it directly and see it in the mirror as well, it glows in the mirror. Basically, the game only counts the vectors directly to the object and not via mirrors. Glowing through portals is possible, which can be seen in the Source SDK (in glow_overlay.cpp, the code checks if the game is Portal and does some magic).

**Comment by robotboy655** [comment]
Do you have a screenshot of the issue? I also don't see what portals have to do with anything

**Comment by CyberOne25** [comment]
[gMod_Mirror_bug.zip](https://github.com/Facepunch/garrysmod-issues/files/3748118/gMod_Mirror_bug.zip)

**Comment by robotboy655** [comment]
Should be fixed in dev.
