### ISSUE TITLE
Player models issue in HG ZS(Zombie Survival)

### ISSUE THREAD

**Issue by Clancy312** [Facepunch/garrysmod-issues#4034]
### Details
So, Forrest told me that the cause of the crash is $includemodel "cs_fix.mdl". But most of my models that I remove the jiggle bones didn't have it. He said he going to find a better solution. I asked him again where do you know this problem and he said it from Robart. So, I don't know how to fix crash models neither Forrest because most of my models don't have $includemodel "cs_fix.mdl" 
My models: https://steamcommunity.com/profiles/76561198308520221/myworkshopfiles/

CrashDump:
https://www.dropbox.com/s/9v7o7cctd4b3mzx/hl2_190913_crash_2019_10_19T18_2_26C0.mdmp?dl=0

### Steps to reproduce
Just tell me how to stop the crash because some VIP models have jiggle bones and then it got removed can cause crash. And also is there any solution?

**Comment by thegrb93** [comment]
I've heard its those custom animation addons that override m_anm and f_anm that cause crashes.

**Comment by thegrb93** [comment]
Basically if you join a server with a model, then join another server with a model of the same name that has different bones or something, it crashes because something that isn't released upon disconnect.

**Comment by robotboy655** [comment]
The dump you attached doesn't seem to have anything to do with any models at all, its a particle system crash upon receiving a full update.

**Comment by Kefta** [comment]
Could you point to the specific models that cause a crash? Giving a workshop pack is not very useful.

**Comment by robotboy655** [comment]
Also all of your workshop uploads technically violate the rules.

**Comment by Kefta** [comment]
Server-specific content addons are so incredibly widespread too.

**Comment by robotboy655** [comment]
Closing as stale.
