### ISSUE TITLE
ConVar with FCVAR_ARCHIVE flag is being set to a name of another flag.

### ISSUE THREAD

**Issue by mastopgunaf** [Facepunch/garrysmod-issues#4036]
Attempting to create a ConVar with FCVAR_ARCHIVE flag when it already exists causes it to be set to a name of another flag.

1. Run this:
```CreateConVar("mastopgunaf", 42, {FCVAR_NEVER_AS_STRING, FCVAR_PROTECTED, FCVAR_ARCHIVE})```
2. Leave the server
3. Create a new game again
4. Run it one more time

What you get:
- mastopgunaf = "0" (def. 42)
- In server.vdf: mastopgunaf = "FCVAR_NEVER_AS_STRING"

**Comment by robotboy655** [comment]
Fixed on Dev.
