### ISSUE TITLE
srcds_linux ED_Alloc: no free edicts Crash/Segfault

### ISSUE THREAD

**Issue by storm37000** [Facepunch/garrysmod-issues#4038]
### Details (Last few lines of server console that look relevant)
```
Bad SetLocalOrigin(6366.594727,20160.187500,0.000008) on gmod_hands
Bad SetLocalOrigin(-13195.927734,-20368.851562,4555.648926) on player
Lag Detected!
[UH-OH!] Invalid HitboxSet on something.
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-process
Server is behind! (1)
Server is behind! (2)
ED_Alloc: no free edicts
ED_Alloc: no free edicts
Segmentation fault
```

---------Custom addon messages-------
- Lag detected means large ticrate drop for 1 second has been detected, but lua isnt frozen as it wouldn't have been able to run the code to print that.
- Server is behind message is a custom dll i made that detects if the server is totally frozen, that means that lua has failed to run a function once per second, indicating a total or temporary freeze.  If it got to 60 seconds, it would kill the process so it can restart and not be stuck at 100% cpu indefinitely.

### Steps to reproduce
Not sure, this issue isn't caused by e2 or Starfall as constraint APIs in those were disabled prior.  It also doesn't look like anything suspicious in log before this exists.  If you want more of the console log let me know.  We are theorizing it is due to constraints since entities are blocked from being created near max edicts.  Server never goes above 2000 edicts and is rarely even that high naturally.

**Comment by robotboy655** [comment]
You have got too many networked entities on your server, reduce/control their amount to avoid `ED_Alloc: no free edicts` crashes.

**Comment by Kefta** [comment]
Shouldn't entities be failed to be created instead of crashing?

**Comment by storm37000** [comment]
they should, and this isnt natural i said, its a malicious player causing crashes.

**Comment by storm37000** [comment]
also i have
```
sv_lowedict_action "3"
sv_lowedict_threshold "1024"
```
so it should restart map if it gets near the max.

**Comment by robotboy655** [comment]
The absolute edict limit is 8192, which is the limit you are hitting.

I haven't heard of `sv_lowedict` convars, I don't know if they actually work.
Considering you said `Server never goes above 2000` and your threshold is set at 1024 maybe they don't work?

And no, it doesn't appear it is made to not crash when running out of edicts looking at `ED_Alloc`.
From VDC: `If the game tries to assign a 2049th edict it will exit with an error message, but if it tries to create a 2049th non-networked entity it will merely refuse and print a warning to the console.`

It's true for entities, but not actual edicts, and it seems CServerNetworkProperty can spawn edits too, although I am not sure when that happens.

Also I doubt your logs contain EVERY entity created, they probably only log those that are spawned by players via spawnemnu or tools.

**Comment by storm37000** [comment]
the edict threshold is how many edicts left before it does the action, which is set to reload map.

**Comment by storm37000** [comment]
It was a hacker doing it somehow, they got banned when the boasted about it.  It was actually filling up edicts without anything in the console saying so.  On a simpler map with less edicts that are spawned with the map it was actually causing the map to reload as it had gotten near the threshold.
