### ISSUE TITLE
Player speed is broken in latest branch

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#4040]
So, because of those gmod_suit stuff (even if it is set to 0) player speed is broken now. My gamemode uses specific speed parameters like this:
```
ply:SetRunSpeed(160)
ply:SetWalkSpeed(320)
```
If HEV is not equipped, speed is always capped to 160. After equipping one, it becomes normal (320-160) when you press shift key just one time. If you respawn again without HEV, speed is always 320.
Also, +walk is broken as well. You press the bind for one time and your speed will always be low until shift key is pressed.

**Comment by vingard** [comment]
Just tested the new update with my game mode, similar issues are occurring (with gmod_suit 0) with the new speed logic. 

I have a game mode based slow-walk override using the GM:Move hook which breaks with the new update. It uses functions SetForwardSpeed and SetSideSpeed when IN_WALK is pressed. This performs perfectly however after IN_WALK is released and the player moves they walk at the defined game mode run speed for some reason. This only stops when the player uses sprint and then returns to normal walking.

**Comment by TheMostUpset** [comment]
Commits page says that chromium and prerelease branches are merged with this fix, but in fact it isn't true, the bug still occurs

**Comment by Kefta** [comment]
Is it fixed on the dev branch?

**Comment by TheMostUpset** [comment]
Yup, works fine on dev

**Comment by robotboy655** [comment]
It should work fine on those 2 branches as well.
