### ISSUE TITLE
[x86-64] Garry's Mod still supports Windows XP? (u no say)

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#4042]
> [Starting on January 1 2019, Steam will officially stop supporting the Windows XP and Windows Vista operating systems](https://support.steampowered.com/kb_article.php?ref=1558-AFCM-4577).

![Store screenshot](https://user-images.githubusercontent.com/9789070/68029888-80681e80-fcb8-11e9-9d08-8bc0556a4367.png)

So, at present, you *must* be running Windows 7 or later version in order to receive new updates?
Anyways, the question is: could you provide instructions on how do you run GMod on Windows XP?
Apparently there is an executable in there:
> .\Steam\steamapps\common\GarrysMod\bin\gmod_xp.exe

Can you confirm this executable still runs on Windows XP?

**Comment by willox** [comment]
Nope. It either works or it doesn't.
