### ISSUE TITLE
Crossbow bolts fired by NPCs go in a random direction.

### ISSUE THREAD

**Issue by teh-player** [Facepunch/garrysmod-issues#4043]
When an NPC, combine or rebel fires a crossbow the bolt will go in a random direction instead of where they are looking. Works when given spawned with or picked up a crossbow. Fired bolts will remain upright.

Spawn a citizen with the crossbow and an unarmed combine soldier, the bolt will fly in a random direction.

**Comment by robotboy655** [comment]
That is simply not true.

![image](https://user-images.githubusercontent.com/3299036/68152236-f1733480-ff4b-11e9-9696-57e236edc42b.png)

One or more of your addons are most likely causing your problem.

**Comment by robotboy655** [comment]
Actually it would appear you are correct, but this doesn't happen always, seems to only happen when the NPC is moving.

Anyway, this should be fixed in the Dev version of the game, and in the next update.
