### ISSUE TITLE
Trigger Player Weapon Pickup while also Keeping the Data

### ISSUE THREAD

**Issue by TimGoll** [Facepunch/garrysmod-issues#4049]
For our gamemode we try to write our custom weapon pickup and ran into a problem. Therefore this is sort of a mix of a question, featurerequest and a bugreport. Maybe this feature already exists and we were just not able to find it.

When a player should pick up a weapon, there are two possibilities:
- Using the `GM:PlayerCanPickupWeapon` hook. We could make our checks inside this hook and return true if they are all valid, however this seems like a not so nice way to do this since we could trigger the code on keypress
- The other way would be using `ply:Give(wepCls)`. This is exactly what we want with just one major drawbag: Custom entity data is destroyed since this creates a new entity in the players inventory. Iterating over the old entity to copy the data to the new one also does not work, since the weapon is a `userdata` object. And even if the iteration would work, clientside data would be lost this way too.

Therefore we'd like to know if there is a possibility to Give a player a weapon with all its custom attributes without using the hook. It seems inconstent that there is a `ply:DropWeapon` function that drops an entity with all its attributes, but not `ply:PickupWeapon`.

**Comment by robotboy655** [comment]
There's already a request for  a function to equip an existing weapon via Lua:
https://github.com/Facepunch/garrysmod-requests/issues/1235

I don't see what the problem is with `GM:PlayerCanPickupWeapon`, you can easily make a USE pickup script using `Player.KeyDown()`

**Comment by TimGoll** [comment]
Like I said, this would work. But our system has a few more features. It would be way better to have a callable function and to not to rely on a hook. Just because something works doesn't mean it is a good solution.

Thank you nevertheless.

**Comment by TimGoll** [comment]
Okay, to be hones, the hook solution is really ugly. I've implemented it, but it has some problems we've all seen in the past. Sometimes weapons are not picked up or need a few frames to be picked up.

To overcome the range issue, on keypress we teleport the weapon to the player. Most of the times the player instantly picks up the weapon. Sometimes it needs a few ticks and sometimes he does not pick it up at all. Is there a solution to this?
