### ISSUE TITLE
PhysicsSimulate & SetModelScale

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#4055]
### Details
**SetModelScale doesn't scale down, only up**
I am attempting to change the model scale of an entity with SetModelScale (followed by Activate)
The collisions box doesn't update on the entitiy when setting the number below 1, however setting it higher does make it update, I have attempted to work around this but have not found a solution.

**PhysicsSimulate breaking**
SetModelScale also breaks the PhysicsSimulate function on custom entities.
self:SetModelScale(1.01) makes PhysicsSimulate break and not run at all.
self:SetModelScale(0.5) runs normally

-

**Comment by Jvs34** [comment]
The PhysicsSimulate behaviour is normal, model scaling recreates the physics object so you need to follow the description of [Entity:StartMotionController](http://wiki.garrysmod.com/page/Entity/StartMotionController)

`This function should be called every time you recreate the Entity's PhysObj. Or alternatively you should call Entity:AddToMotionController on the new PhysObj.`

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/73287831-8e1f3880-4202-11ea-9893-1227693d8931.png)

I could not reproduce the first issue, and for the second issue what @Jvs34 said does apply.
