### ISSUE TITLE
SetShouldServerRagdoll(true) makes ragdoll that can't be shot or physgunned.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4056]
Normal traces work, so can use toolgun, but not physgun or bullets. Anyone know a work-around? It has the same SolidFlags, Movetype, and Collision group as normal ragdoll so I'm stuck.

**Comment by thegrb93** [comment]
Also GetRagdollEntity seems to return NULL.

**Comment by robotboy655** [comment]
Are you sure its not being replaced by some mod(s)?

**Comment by thegrb93** [comment]
Yeah it's the [C] SetShouldServerRagdoll

**Comment by thegrb93** [comment]
Found the CreateEntityRagdoll hook which works so I don't need GetRagdollEntity anymore. Just need to figure out this issue now.

**Comment by thegrb93** [comment]
I know other mods such as pac3, and outfitter might need GetRagdollEntity to work though.

**Comment by robotboy655** [comment]
I didn't mean SetShouldServerRagdoll, I mean the ragdoll could be replaced by mods via CreateEntityRagdoll or something, TTT does it for example.

But the issue you are experiencing (the trace stuff) might be also just intentional by Valve.

**Comment by thegrb93** [comment]
You're saying CreateEntityRagdoll can override the ragdoll? That's not documented in the wiki.

**Comment by thegrb93** [comment]
Checked hook.GetTable().CreateEntityRagdoll and didn't find anything off. and Player.CreateRagdoll is [C].

**Comment by thegrb93** [comment]
Any idea whats making the ragdolls un-shootable? I'd like to fix that at least.

**Comment by Kefta** [comment]
Try setting the collision group.

**Comment by thegrb93** [comment]
It's already COLLISION_GROUP_NONE. Setting to something else and then back didn't help.

Bullets and physgun-beam won't hit it but other traces will. Seems like it has a collision mask set or something.

**Comment by thegrb93** [comment]
Props can push the ragdoll around as well.

**Comment by robotboy655** [comment]
It's because of `SetOwner`.

**Comment by thegrb93** [comment]
Any chance of getting GetRagdollEntity to return this ragdoll?

**Comment by robotboy655** [comment]
The state of player death ragdolls is a mess.

If we make GetRagdollEntity return the serverside ragdoll, it will be deleted on player respawn, which is I imagine is not what you'd actually want.

Also the clientside ragdoll is being created 2 times on each death, one of which is in the base gamemode:
https://github.com/Facepunch/garrysmod/blob/33d8843923c79f09ffc3c5d3fbbb9e645b6952f8/garrysmod/gamemodes/base/gamemode/init.lua#L41
And the other is in engine on death. The base gamemode one results in 2 ragdolls when SetShouldServerRagdoll is set to true.

**Comment by thegrb93** [comment]
I did notice that yea, I have the gamemode DoPlayerDeath overrided as well.
