### ISSUE TITLE
Steam Overlay doesn't work for 64-bit branch MacOS 10.15

### ISSUE THREAD

**Issue by SuperStik** [Facepunch/garrysmod-issues#4058]
### Details

The title of it is self-explanatory, but when trying to open up the Steam Overlay, nothing happens, like it was turned off in the settings.

### Steps to reproduce
Launch Garry's Mod
Run the Shift+Tab shortcut, and watch as nothing occurs.

**Comment by robotboy655** [comment]
Probably duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3925
