### ISSUE TITLE
*.dll's not working on x86_64

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/garrysmod-issues#4059]
x64 branch  disallow to load custom modules (like -[g15](https://github.com/willox/archive/releases/download/v1/garrysmod.7z) in startup parameters), and also native lua modules (like [turbostroi](http://metrostroi.net/turbostroi), native module for better [metrostroi](https://steamcommunity.com/workshop/filedetails/?id=1095130789) server performance)

**Comment by xDShot** [comment]
You can't load 32bit libraries in 64bit appliction.

**Comment by SupinePandora43** [comment]
oh god...
okay, i'll try to find x64 versions of turbostroi and -g15

**Comment by thegrb93** [comment]
I run several x64 modules and they work fine. This can be closed.

**Comment by willox** [comment]
Yeah... even if the -g15 parameter is broken it isn't exactly a big deal for us.

You might be able to make it work by having your module in another folder called 'bin'.
