### ISSUE TITLE
Dedicated Server from November 2019 update is flagged as malware by several antivirus products

### ISSUE THREAD

**Issue by Visual-Vincent** [Facepunch/garrysmod-issues#4060]
### Details
For some reason the Dedicated Server executable `srcds.exe` from the November update (2019-11-12) is flagged as malware by several antivirus products. I, personally, use BitDefender Internet Security 2019, which reports it as a `Gen:Variant.Fugrafa.6175`.

Here's the report on VirusTotal:
https://www.virustotal.com/gui/file/7c872c3ac72eb618454fed6b42693d77da88eab0ebbd606ef3259636bbdbafc9/detection

### Steps to reproduce
Install one of the antivirus/antimalware products that detects the file (shown on VirusTotal) and try running the server.

### Screenshots
**BitDefender**

![BitDefender Internet Security 2019](https://camo.githubusercontent.com/b461a255b0cc9256610fb88e61b399b01bb07335/68747470733a2f2f692e696d6775722e636f6d2f705437357142352e706e67)

**VirusTotal**

![VirusTotal](https://camo.githubusercontent.com/cf2a37742f066b9eca1b63f559842ef214cc2bdb/68747470733a2f2f692e696d6775722e636f6d2f416d74356a59762e706e67)

**Comment by robotboy655** [comment]
Report it as false positive, I guess, there's not much we can do about this.

**Comment by Visual-Vincent** [comment]
@robotboy655 Thanks for your feedback. I just thought I'd report here as well in case it was something you were aware of. I thought it was rather odd that 16 different products all react to it.

**Comment by thegrb93** [comment]
That's always a possibility when there's write permission on an executable. @robotboy655 can you see if this is reproducible? I will when I get home. If not then perhaps you got a virus

**Comment by robotboy655** [comment]
This usually happens with free AVs and hl2.exe, which was always a false positive, my own local build of srcds gets picked up by only 2:
![image](https://user-images.githubusercontent.com/3299036/68802328-663e2100-0666-11ea-90fc-c8b5aeb3b309.png)

**Comment by thegrb93** [comment]
I get the same result as @Visual-Vincent . Windows defender doesn't have any problem with it so I'm not too concerned

**Comment by robotboy655** [comment]
The VirusTotal link now shows only 7 hits so the AVs are getting it handled, and it is a false positive as usual.

**Comment by Visual-Vincent** [comment]
Thanks for looking into it, and sorry for the late reply. Ever since the CCleaner incident I've been extra paranoid regarding things like these.
