### ISSUE TITLE
Why doesn't the x64 branch contain specific tools on Linux?

### ISSUE THREAD

**Issue by Comminux** [Facepunch/garrysmod-issues#4061]
Such as gmad and gpublish?

**Comment by willox** [comment]
They should be in `bin/linux64/gmad` and `bin/linux64/gmpublish`.

**Comment by OhDaeto** [comment]
That's not true.
![Снимок экрана от 2019-11-15 01-27-14](https://user-images.githubusercontent.com/14937307/68901524-20a55500-0747-11ea-8f97-df6c3dfafcd2.png)

**Comment by thegrb93** [comment]
verify integrity of game cache?

**Comment by OhDaeto** [comment]
@thegrb93 These tools are only available on stable and dev branches.

**Comment by willox** [comment]
You're right. I'll fix it this week.

**Comment by willox** [comment]
This might have been fixed a couple of days ago, I haven't had a chance to test it yet but let me know if it is.

**Comment by Comminux** [comment]
@willox Yes. I understand. Give me 3 days and I will then close this issue.

**Comment by Comminux** [comment]
@willox Tested the archiving and publication of addons. Everything seems to work correctly.
