### ISSUE TITLE
New november update broke runspeed modification

### ISSUE THREAD

**Issue by leroy5100** [Facepunch/garrysmod-issues#4063]
I have a SWEP that changes movement speed for the players when they use the primary attack.
After the november update the following issue arose. While a player is holding the shift key and presses the primary fire to change their runspeed wit the swep, it does not change the runspeed untill they release the shift key. Then when they press the shift key again the runspeed changes like normal. So it seems that the shift key became sticky because if the swep is enabled and they disable it while running it does not change the movement speed untill they release the shift key.

At first I thought it was a problem with the SetRunSpeed function but after removing that function and only changing SetWalkSpeed the issue still appeared. I will include my

 code just to be sure.
https://pastebin.com/QN6afFWS

**Comment by Kefta** [comment]
You should be using a SetMaxSpeed multiplier in a Move hook: your solution is easily broken by other addons, and even by default in gamemodes like DarkRP. Check example 2 on https://wiki.garrysmod.com/page/CMoveData/SetMaxClientSpeed . Make sure you define the hook shared.

**Comment by leroy5100** [comment]
It wasn't broken by other addons is the thing. It broke after the new update and made the shift key sticky.

**Comment by Kefta** [comment]
I'm saying that addons can break your SWEP just by calling SetRun/WalkSpeed themselves. The issue should still be looked into for compatibility reasons, but either way, you should be using a more proper solution.

**Comment by leroy5100** [comment]
Alright, I'll try using the hook instead. Thanks for the advice :3

**Comment by robotboy655** [comment]
This should be "fixed" on Dev, and with this dies any hope of `StartSpritning`/`StopSprinting` Lua bindings ever being useful.
