### ISSUE TITLE
GMod appears in the bottom hot bar and then immediately disappears on startup.

### ISSUE THREAD

**Issue by igolvach** [Facepunch/garrysmod-issues#4064]
### Details
Recently, I have been occupied more than and as such haven't played gmod in around 3-4 months, since about July. Recently, I wanted to start the game up to up to play a bit, however upon clicking launch the game appears in the bottom for a bit and then disappears.

I figured I had too many addons so I tried reducing addons and still it wouldn't start up, even after I rid myself of all addons, I tried all of the methods on the Common start up Problems and most online guides, such as trying to force in windows or change the DirectX level, the only head-way I have being the screen turning black for 3 seconds when I forced a DirectX level.

I deleted the entirety of my gmod file and reinstalled, and yet it still would not start. 
So I did the 'factory reset' and the game still wouldn't run, even after I ran all the previous methods again.

I don't know what wrong with my game, but I very much love this game and would greatly appreciate any help that would make it so that I could once again play.

NOTE:  I will email all the crash-dump files from my attempts under the title of "igolvach gmod issue crashdumps"

### Steps to reproduce
Honestly, I'm not sure how to reproduce the crash. Personally for me I just hadn't touched the game in 3 months and then installed one or two addons.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

If you are getting crash dumps, you can email them at the addresses in the `README.md`.
