### ISSUE TITLE
Entity:SetSaveValue does not check entity types

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4065]
```
> print(Entity(1):SetSaveValue("m_hLastWeapon", true))...
true
```

Compare with ints:
```
> print(Entity(1):SetSaveValue("spawnflags", true))...

[ERROR] lua_run:1: bad argument #2 to 'SetSaveValue' (number expected, got boolean)
  1. SetSaveValue - [C]:-1
   2. unknown - lua_run:1
```

It interprets any non-entity argument as NULL.

**Comment by robotboy655** [comment]
This affects every single function that allows NULL entities. Changing this might and probably will break a lot of poorly coded addons.

**Comment by robotboy655** [comment]
I have added proper type checking, (nil and no value will still fallback to "NULL" for functions that accept NULL), let see what it breaks.
