### ISSUE TITLE
gm_flatgrass nodraw bug

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/garrysmod-issues#4066]
overworld
![image](https://user-images.githubusercontent.com/36124472/69005784-aa704080-0948-11ea-8e9e-188cf1e3f80a.png)
underbrushes
![image](https://user-images.githubusercontent.com/36124472/69005796-cbd12c80-0948-11ea-8f5e-cc1c9264c237.png)
in skybox box
![image](https://user-images.githubusercontent.com/36124472/69005801-dbe90c00-0948-11ea-92d2-cfdfd3b93fb5.png)
looking up in overworld
![image](https://user-images.githubusercontent.com/36124472/69005816-063ac980-0949-11ea-9d03-a00e5f2b1905.png)

**Comment by thegrb93** [comment]
you're talking about the duplicate media player screen? I think that's because the author isn't using https://wiki.garrysmod.com/page/GM/PostDrawOpaqueRenderables correctly.

**Comment by thegrb93** [comment]
https://github.com/samuelmaddock/gm-mediaplayer/blob/master/lua/mediaplayer/players/entity/shared.lua#L49

**Comment by SupinePandora43** [comment]
* simfphys          // try to look little bit from sun, you'll see two(four) points, it's headlights
* mediaPlayer
* The Aperture
and much more

**Comment by Kefta** [comment]
They're still not but with gm_flatgrass, they're with how the addons draw their entities.

**Comment by robotboy655** [comment]
Not a bug with the game, but with the addons.

**Comment by SupinePandora43** [comment]
oh, okay
