### ISSUE TITLE
GMOD Crashes while ingame or connecting to a server without error often

### ISSUE THREAD

**Issue by karl-police** [Facepunch/garrysmod-issues#4067]
### Details
So I have GMOD alt tabbed and I sometimes try to alt tab back in while loading into the server.

I use this command to connect to the server steam://connect/208.103.169.58:27015
It worked fine at the beginning then I crashed with stuff like CMDLCache:: Out of Memory but my memory looks fine, then I removed some addons tried again, and I don't know if it made worser but it's just confusing.

So what happens sometimes is that GMOD while I'm alt tabbed in that server crashes without any message, it just closes and goes away.

MDMP's have been mailed to robotboy655@facepunchstudios.com and willox@facepunchstudios.com

If I look in the MDMP file somewhere it says EXCEPTION_ACCESS_VIOLATION

I'm alt tabbed while stuff starts to load then I often timeout then I retry in console and alt tab again, then the game just crashes.

**Comment by robotboy655** [comment]
` CMDLCache:: Out of Memory` means you are running out of VRAM, not a problem with the game.

**Comment by karl-police** [comment]
> ` CMDLCache:: Out of Memory` means you are running out of VRAM, not a problem with the game.

new error
can't load lump 53, allocation of 79758205 bytes failed

**Comment by karl-police** [comment]
> ` CMDLCache:: Out of Memory` means you are running out of VRAM, not a problem with the game.

When not alt tabbed I see the error which is can't load lump 53, allocation of 79758205 bytes failed
