### ISSUE TITLE
can't load lump 53, allocation of the same bytes fail

### ISSUE THREAD

**Issue by karl-police** [Facepunch/garrysmod-issues#4068]
### Details
So I have GMOD alt tabbed and I sometimes try to alt tab back in while loading into the server.

I use this command to connect to the server steam://connect/208.103.169.58:27015 which uses these addons https://steamcommunity.com/sharedfiles/filedetails/?id=932041100

It worked fine at the beginning now without having the addons subscribed but now I crash at every second time at attempting to reconnect with this message can't load lump 53, allocation of 79758205 bytes failed

Doesn't matter if alt tabbed or not the same thing will happen first I timeout and then ``can't load lump 53, allocation of 79758205 bytes failed`` appears
restarting didn't fix it

Which makes it hard to believe that this is a memory issue. I tried to delete downloads and cache folder but didn't work.

MDMP has been mailed to robotboy655@facepunchstudios.com

**Comment by robotboy655** [comment]
You are running out of memory (This time I believe that would be your RAM), what do you want us to do? The problem is with your PC.

**Comment by karl-police** [comment]
but I don't know where I thought you could tell me?

**Comment by karl-police** [comment]
How is it possible that I was able to play on the server before and now suddenly not?

**Comment by robotboy655** [comment]
Background processes? Increased amount of addons the server forces you to mount?

**Comment by karl-police** [comment]
I reduced the background processes

**Comment by karl-police** [comment]
Isn't there any specific folder I can check for this issue?

**Comment by karl-police** [comment]
now it just crashed but without anything it just crashed an my RAM wasn't even completly used, there was a few GB left and also going down after reaching starting lua

@robotboy655 how can I get enough information out of a MDMP file

**Comment by gochev** [comment]
Hello everyone it is because of 32bit apps, the way to fix is is to use this handy app. https://www.techpowerup.com/forums/threads/large-address-aware.112556/ 

don't forget to read the spoilers section
