### ISSUE TITLE
Failed to lock vertex buffer in CMeshDX8::LockVertexBuffer is this a issue?

### ISSUE THREAD

**Issue by karl-police** [Facepunch/garrysmod-issues#4069]
![image](https://user-images.githubusercontent.com/12023782/69012609-f7b7d680-0977-11ea-865d-d283072e9623.png)

same question like this but another error https://github.com/Facepunch/garrysmod-issues/issues/4067

is this also RAM or?

**Comment by Kefta** [comment]
Yes it's related to you running out of VRAM. It's a DirectX error.

**Comment by robotboy655** [comment]
Please stop opening new issues for every tiny question. You can ask them at our Discord server, or on your previous 2 issues.

**Comment by karl-police** [comment]
What channel is appropriate for that on the Discord server?
