### ISSUE TITLE
People re-download workshop at every Login !

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4071]
I own a +800 players daily gmod community.

On some of my servers players need to Redownload all the Workshop Files before joining the server.

Even though they do have the Workshop files. and they already have joined the server.

They need to download the workshop addons of my server everytime. and I have +600 Addons, so they need to wait 30 Minutes to join my server every time !

https://image.noelshack.com/fichiers/2019/47/1/1574033848-prp.png

Please fix this ASAP ! makes me loose players + community

**Comment by thegrb93** [comment]
The fact it runs at all is a god damn miracle

**Comment by anyome** [comment]
Any help ???

**Comment by robotboy655** [comment]
Server IP?

**Comment by anyome** [comment]
PLAY.TEAMFRENCH.NET:27015

**Comment by robotboy655** [comment]
I cannot reproduce this, so I will need console logs after it "redownloads" some addons for you.

**Comment by Wgis** [comment]
I also have same problem, also some working models for me, being error if my friend see

**Comment by anyome** [comment]
Any solution to this problem??

I lost all my players now because of it!!

Everytime people redownload 400 Addons !! !At each connection

It started to happens after the new Update of gmod (the one on november)

Plz fix this bug !! everyone left my server ....

**Comment by anyome** [comment]
> 
> 
> I cannot reproduce this, so I will need console logs after it "redownloads" some addons for you.

I lost all my players now because of this problem...

Please fix this !
it started to happens after the new update of gmod !! and a lot of gmod servers are concerned.

When you join the server, and then you restart your gmod, you need to redownload addons.

**Comment by Kefta** [comment]
![](https://i.imgur.com/fELwlsB.png)

**Comment by robotboy655** [comment]
I doubt it is at each connection. It will be a one time thing, which is unfortunately necessary to switch to the new system.

**Comment by thegrb93** [comment]
Yeah, I noticed that it redownloaded once. No biggy

**Comment by Wgis** [comment]
What mean closed? You fix ut?

**Comment by Kefta** [comment]
No console log was provided so it couldn't even be verified

**Comment by robotboy655** [comment]
And there have been updates to the system is question on Dec 22nd on all versions of the game which should have fixed whatever problems there were.
