### ISSUE TITLE
Incorrect ladder mount sounds

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/garrysmod-issues#4073]
You can change the surfaceprop of a ladder. It plays that surfaceprop's footstep sounds. However, the default ladder surfaceprop sounds are played when the player mounts the ladder.
I've only tested this with func_useableladder.

https://www.youtube.com/watch?v=LkiMwJgodRw

**Comment by robotboy655** [comment]
So what would be the "correct" behavior then?

**Comment by MARK2580** [comment]
> So what would be the "correct" behavior then?

He is right, these sounds are not true. There should be sounds of a metallic nature, similar to that which is reproduced at the first touch (in the video).

**Comment by robotboy655** [comment]
If he wanted default sounds, he would not have gone through the trouble of changing surfaceprop of the ladder.

**Comment by MARK2580** [comment]
> If he wanted default sounds, he would not have gone through the trouble of changing surfaceprop of the ladder.

Perhaps ... I did not even remember that there is such an option. For a long time I did not use stairs.

**Comment by gvarados1** [comment]
> So what would be the "correct" behavior then?

The default ladder "footstep" sounds are played played when mounting. Correct behavior would be the footstep sounds for the set surfaceprop playing. This or being able to define a mount sound in the ladder entity.

**Comment by robotboy655** [comment]
Can you tell me how exactly you changed the ladder's surfaceprop?

**Comment by gvarados1** [comment]
![image](https://user-images.githubusercontent.com/39461072/69579837-e9ca0d00-0f98-11ea-938e-3086971461eb.png)

**Comment by gvarados1** [comment]
I haven't tested, but I assume the same bug happens with %compileladder in the vmt for a ladder texture. Also, func_ladder is missing this surface properties option.

**Comment by robotboy655** [comment]
Sounds now match
