### ISSUE TITLE
Client downloads addons but don't mount models/materials

### ISSUE THREAD

**Issue by SupinePandora43** [Facepunch/garrysmod-issues#4075]
# Steps To Reproduce:
1. start gmod
2. connect to metrostroi server (for example)
3. spawn train
4. saw ERROR model

why i get error if i downloaded this addon while connecting?!

**Comment by Comminux** [comment]
Did you read [that](https://wiki.garrysmod.com/page/resource/AddWorkshop)?

**Comment by SupinePandora43** [comment]
@Comminux 
oh god
now i know why i download "PL REDUX" when map isn't pl_redux, and why download not whole collection
thanks!
###### P.S.  если ты `id/Comminux` в стиме, добавь, пж
