### ISSUE TITLE
Running stopsound on server is blocked for players

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-issues#4076]
### Details
You can run in client stopsound but if server tries to run it on client it will display
_FCVAR_SERVER_CAN_EXECUTE prevented server running command: stopsound_

### Steps to reproduce
Run on server
player.GetByID(1):ConCommand("stopsound") --Will print that red text error on client
player.GetByID(1):SendLua("RunConsoleCommand('stopsound')") --Will work as intended

Seems like someone forgot to remove this command from the blocked commands list
https://wiki.garrysmod.com/page/Blocked_ConCommands

**Comment by robotboy655** [comment]
stopsounds

**Comment by robotboy655** [comment]
Apparently `stopsounds` doesn't exist anymore, I will make sure `ConCommand` works on `stopsound` in the next update.

To be clear, it never was in the blocked commands list.
