### ISSUE TITLE
Half-life: Source Chrome Textures don't work (x64)

### ISSUE THREAD

**Issue by HLRaven** [Facepunch/garrysmod-issues#4080]
The chrome is treated as a cubemap (from what i once saw in the console) which makes them look really bad

![image](https://user-images.githubusercontent.com/53531499/69494920-b79daa00-0ec9-11ea-968c-fafb4a68742f.png)

**Comment by robotboy655** [comment]
I don't think this is exclusive to x64 branch, and it won't be properly fixed until x64 releases proper.

**Comment by robotboy655** [comment]
Fixed on x64 branch
