### ISSUE TITLE
sound.Generate doesn't clear the registry

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4082]
`sound.Generate` spews this type of message ![image](https://user-images.githubusercontent.com/5685050/69901090-f336e900-138d-11ea-9f53-38bae4aa8838.png) 
when you overwrite sound with the same identifier.
Wiki says: >  You cannot override already existing ones.
But `sound.Generate` doesn't clear sound registry after disconnecting.

Also, when the sound is created for the first time it spews its address with white text. Maybe this should be moved to `developer 1`
![image](https://user-images.githubusercontent.com/5685050/69901266-604b7e00-1390-11ea-90e0-b29b72641b63.png)

(x86-64, Win, 191125)

**Comment by GitSparTV** [comment]
@robotboy655 Any updates?

**Comment by GitSparTV** [comment]
The white text was moved to `developer 1`, but the red text persists in `developer 0`

**Comment by robotboy655** [comment]
That is intentional for now.

**Comment by GitSparTV** [comment]
:       )
![image](https://user-images.githubusercontent.com/5685050/74785192-c7573f80-52ba-11ea-89b4-cd17a14ebc04.png)

**Comment by thegrb93** [comment]
Pretty much any resource doesn't clear registry. Why valve, why

**Comment by Kefta** [comment]
>Valve
>Lua registry
?

**Comment by GitSparTV** [comment]
If this is still itentional, should be closed?

**Comment by robotboy655** [comment]
That was a response to your comment about the red text.

**Comment by robotboy655** [comment]
Should be fixed on dev.
