### ISSUE TITLE
CSoundPatch:SetDSP() fails silently if the sound is not stopped

### ISSUE THREAD

**Issue by hiddencoders** [Facepunch/garrysmod-issues#4086]
Trying to run CSoundPatch:SetDSP(n) on an object that is current playing will fail silently - you'll need to stop the sound, set the effect, and start playing again.

```lua
local obj = CreateSound(LocalPlayer(), "test_sound")
obj:Play()
obj:SetDSP(111) -- this will fail

obj:Stop()
obj:SetDSP(111) -- this will work
obj:Play()
```
Added to this is the fact that you can neither fast-forward sound files, nor can you create another hidden CSoundPatch on the entity to fake the effect by fading it out, and this becomes an apparent issue when trying to utilize sound effects, making PLAYER:SetDSP() the only viable alternative.

This was tested on the client. SetDSP fails with any number.

**Comment by thegrb93** [comment]
Maybe that should just be noted on the wiki

**Comment by Kefta** [comment]
It should be noted on the wiki either way.

**Comment by robotboy655** [comment]
So a fix is definitely possible, but it will require networking changes, otherwise it might cause sounds in other places unexpectedly change their DSP when their volume changes.

**Comment by hiddencoders** [comment]
To be fair, the entire CSoundPatch class is a mess along with CreateSound. Apart from the lack of control, AddPlayerPost doesn't do it's job, and newly connected players need a newly created sound for CSoundPatch to work. Also, there is a flag that's set on all ticks(?) (SND_CHANGE_VOL) so the sound obeys the volume setting, but for some reason they don't do it SND_CHANGE_PITCH, and there is - as far as I can tell - unspecified behavior when it comes to pitches: when using a sound script's value, :PlayEx()'s second argument or a different sound's pitch all comes into play. Oh and let's not forget about CSoundPatch's garbage collection - I swear I've even had global variables garbage collected (I thought _G was preserved lmao), let alone local ones or those created from some callback function.

And god, don't even get me started on the unearthly sounds that earrape the living ____ out of you and your headphones when you do dsp on multiple sounds.

**Comment by robotboy655** [comment]
Fixed.
