### ISSUE TITLE
x86-64 server apps cause steam to think the game is running

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#4087]
### Details
if your server is running the x86-64 branch, running srcds.exe or srcds_win64.exe will cause steam to thing that the client app for gmod is running.,
### Steps to reproduce
install a server using the x86-64 branch then launch the server app
look at steam, it should then say that garrysmod is running. If you click stop, the server will close because steam thinks the running server is the client app.

**Comment by joeyjumper94** [comment]
by the way, it happens with BOTH server apps on this branch

**Comment by willox** [comment]
This was happening because it was trying to look for Steam Controllers.
