### ISSUE TITLE
setRunSpeed and setWalkSpeed don't reset once conditions are no longer met

### ISSUE THREAD

**Issue by cdymlr** [Facepunch/garrysmod-issues#4088]
### Details
For example, If you SetRunSpeed to 300% for 30 seconds , the increased speed will persist beyond the 30 seconds until the player releases their "run" key.

### Steps to reproduce

timer.Create(ply:SteamID().."adrenaline",20,1,function() 
		if IsValid(ply) then
			ply:SetWalkSpeed(160) 
			ply:SetRunSpeed(80)
			ply:SetJumpPower(200)

Do not release RUN key and you will keep speed buff until you release 

[https://streamable.com/ka8j4](https://streamable.com/ka8j4)

**Comment by cdymlr** [comment]
[https://streamable.com/ka8j4](url)

**Comment by Kefta** [comment]
Did you test on the dev branch?

**Comment by Kefta** [comment]
Also you really shouldn't use timers or SetWalk/RunSpeed for this kind of thing - use a Move move hook SetMaxSpeed override with a predicted player variable (NetworkVar/NWVar/manually networked variable) to determine when the override needs to occur. See example on http://wiki.garrysmod.com/page/CMoveData/SetMaxClientSpeed

**Comment by cdymlr** [comment]
This issue is resolved as of the 12.5.19 dev branch.

**Comment by Kefta** [comment]
This can be closed then.
