### ISSUE TITLE
Marlett font not being rendered 

### ISSUE THREAD

**Issue by CGDoctor8** [Facepunch/garrysmod-issues#4090]
Sorry for making a second issue but i now understand the problem

### Details
When trying to render marlett as well as other fonts defined in ClientScheme.res with surface.CreateFont it will fail on windows clients and just resort to Arial (note linux clients do not fail to render the font or fonts defined in ClientScheme.res)
https://wiki.garrysmod.com/page/Default_Fonts

### Steps to reproduce
Step 1 load client side lua file
```lua
surface.CreateFont( "test", {
    font = "marlett",
    size = 50,
    weight = 500,
    extended = true,
})

hook.Add( "HUDPaint", "HelloThere", function()
    draw.DrawText( "py34hinih56ox", "test", ScrW() * 0.5, ScrH() * 0.25, Color( 255, 0, 0, 255 ), TEXT_ALIGN_CENTER )
end )
```

### Screen Shots
What is displayed
![image](https://user-images.githubusercontent.com/39572468/70475541-a27d6980-1acc-11ea-8ae5-9538858516b0.png)

What it should look like
![image](https://user-images.githubusercontent.com/39572468/70475052-a361cb80-1acb-11ea-89a4-bf4c4bdfd815.png)

**Comment by robotboy655** [comment]
https://wiki.garrysmod.com/page/Structures/FontData

![image](https://user-images.githubusercontent.com/3299036/70484300-1848fb80-1af4-11ea-84aa-06a173e1223d.png)

You cannot base your game font on another game font.

Are you specifically on the Dev branch by chance?

**Comment by CGDoctor8** [comment]
No both linux and windows 10 where on 64 bit non dev build i guess its by the wiki intended but dosn't have the same behaviour on linux where it will happly will allow such a CreateFont

by this logic this code works on both windows and linux
```lua
hook.Add( "HUDPaint", "HelloThere", function()
    draw.DrawText( "py34hinih56ox", "marlett", ScrW() * 0.5, ScrH() * 0.25, Color( 255, 0, 0, 255 ), TEXT_ALIGN_CENTER )
end )
```



but this bit finds that the font is one of the defaults and falls back to arial but on linux it dose no such thing.
```lua
surface.CreateFont( "test", {
    font = "marlett",
    size = 50,
    weight = 500,
    extended = true,
})

hook.Add( "HUDPaint", "HelloThere", function()
    draw.DrawText( "py34hinih56ox", "marlett", ScrW() * 0.5, ScrH() * 0.25, Color( 255, 0, 0, 255 ), TEXT_ALIGN_CENTER )
end test
```

I guess at that point any addon that dose make a createfont like that should just change it to arial but it dose cause issues with some larger addons
![image](https://user-images.githubusercontent.com/39572468/70463389-ba48f380-1ab4-11ea-99d0-7af95cafeb78.png)
![image](https://cdn.discordapp.com/attachments/132840548653334528/653533837195739136/unknown.png)
![image](https://cdn.discordapp.com/attachments/132840548653334528/653470526626594816/unknown.png)

**Comment by robotboy655** [comment]
You should use `symbol = true` to get the symbols working, but there's a little bug with that will be fixed.
