### ISSUE TITLE
Portal 2 maps are completely broken

### ISSUE THREAD

**Issue by pivotman319-owo** [Facepunch/garrysmod-issues#4091]
### Details
The majority of Portal 2 maps are non-functional; I'm assuming part of it is due to the lack of proper VScript functions in the GMod/Source engine binaries as generic_actors like `@glados` are requested to trigger non-existent `CBaseEntity` functions.

Projected textures/lights also give off improper lighting and flicker on certain materials like [unportalable black metal tile surfaces](https://lithi.io/file/R9cd.png), which are are also broken since they display an RGB cubemap according to the player's position/world offset. ((this is what they're supposed to look like)[https://lithi.io/file/FSxV.png]) There are also soundscripts which are not mounted in-game.

Certain scripted maps like sp_a4_finale4 (Wheatley boss fight) have broken sequences. Button sequence is unplayable and requires a recompilation of certain P2 models to fully work. (see video)

https://www.youtube.com/watch?v=cmt29IzDZPw

### Steps to reproduce
1. Open any Portal 2 map.

**Comment by robotboy655** [comment]
Portal 2 maps will never be playable in GMod due to vscript, which will not be added.
