### ISSUE TITLE
Servers not showing up in the List ! [A2S_INFO]

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4093]
Hello !
I own a Big Garry's mod Community (TeamFrench) (600 Players everyday base)
All my servers are in one Category: [http://teamfrench.net/serveurs.png](url)

My problem is that Players can't see All the servers (They can only see 7-8 Servers) instead of 11 Servers.

Players can only see Full Servers And so Empty servers are not shown in the List
This bug happens to almost 80% of the Players, and i loose players everyday because of It !

Can you fix the A2S_INFO not working properly ? It happens a lot when my Servers are empty they are not shown in the List so players can only join them from (Favorites)

This bug made me loose 70% of my player base

**Comment by robotboy655** [comment]
It has nothing to do with A2S_INFO. The server browser first queries populated servers, and then the empty ones to mitigate Steam's regional stuff, so everything your players have to do is just wait a bit more, or you should have your server(s) populated.

**Comment by anyome** [comment]
Even The Populated Servers don't show up Sometimes for my Players!
It's a problem that makes me loose players every time!

**Comment by anyome** [comment]
How the servers are going to be populated if they don't even "show" in the servers list
