### ISSUE TITLE
Servers not showing up

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4094]
I'm sorry but i forgot to mention that evens Full Servers don't show up for some players due to unknown reasons.

Can you fix that? 
My servers: http://teamfrench.net/serveurs.png

**Comment by anyome** [comment]
And how can i get my servers populated if Players don't even see Them you should explain to me this shit --'

**Comment by robotboy655** [comment]
You have not provided any proof of your claims, as far as I am concerned there's nothing wrong, all your 11 servers show up fairly quickly for me.
