### ISSUE TITLE
PaintAt doesn't update internal x, y positions for surface library

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-issues#4095]
### Details
Using PaintAt will erroneously break surface libraries position internally after being called, leading to surface calls not running at the correct positions afterwards

### Steps to reproduce
Call PaintAt on a panel and it will paint at the wrong position, or appear to not paint at all.

**Comment by robotboy655** [comment]
Post actual code? Sounds to me you are not resetting position to draw at before your `surface.*` calls

**Comment by meepen** [comment]
Sorry, this issue was wrong and I should have posted code to replicate. I'll post the actual issue I found later in another issue with code. I apologize.
