### ISSUE TITLE
Can't make HTTP requests to the local server

### ISSUE THREAD

**Issue by fiveseven7** [Facepunch/garrysmod-issues#4096]
### Details
I can't make http requests to the local server (both POST and GET)
[https://i.imgur.com/u67suJU.png](https://i.imgur.com/u67suJU.png)

### Steps to reproduce
1.Run a local http server
2.Try to make http request to it

**Comment by deadmonstor** [comment]
This is intentional
Issue: [https://github.com/Facepunch/garrysmod-issues/issues/3684](Github)

**Comment by fiveseven7** [comment]
Ok

**Comment by fiveseven7** [comment]
Thanks for breaking my game chat <-> IRC bridge
