### ISSUE TITLE
[HELP ME PLEASE] Servers Not Showing UP !

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4097]
Hey RubatBoy.
My Big Gmod Community is suffering from this big problem : Servers not showing up for everyone.

Here are the proofs: (I Have 11 Servers)
Player 1 : https://i.imgur.com/pGQCHs0.png  (Only sees 5 servers)
Player 2 : https://i.imgur.com/SjYQuPV.jpg (Only sees 8 Servers)
Player 3: https://i.imgur.com/ach9dqA.png (Sees all the servers)
Player 4: https://i.imgur.com/DuNl9wL.png (Only sees 2 Servers)

I'm loosing 70% of my player rate, and all of this problems started after the Last Update.
Is it because of the : sv_region ?

I'm using : "sv_region 3" and my Servers are French Servers. And My Dedicated Server is Located in France. (ip: play.teamfrench.net)
My UDP Rule is set to accept all traffic

Community Link: http://teamfrench.net/
And My Servers: https://www.gametracker.com/search/?query=play.teamfrench.net&sort=3&order=DESC

Please help us Rubat Boy / Willox ! You're my last chance to get 1000 Players again like in the past. I used to have full servers in the past and now i'm loosing everything !

My servers were Full before the Update + (PROOF:) : https://i.imgur.com/qfnTRTo.png

Help Me please ! I'm begging you on my Knees !

**Comment by anyome** [comment]
Okey I found out what's causing the issue:
https://i.imgur.com/TZhQ7RX.png

Only Servers with 1 Player or More appear on People Servers List.

The problem is that: 
How can Players join my Servers if they don't even see them ???

This need to be Fixed please. Make Empy servers showing up in the Servers List ! please

**Comment by robotboy655** [comment]
They do show up AFTER all populated servers are shown. All you gotta do is wait for server list to stop refreshing.

It's either this, or servers away from you not showing at all.

There's nothing that can be done here.
