### ISSUE TITLE
Panel:GetText() is limited to 1023 B and Panel:GetValue() is limited to 8091 B for TextEntries and 1023 B for other controls

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4102]
Recreating from https://github.com/Facepunch/garrysmod-issues/issues/1569

Both starfall editor and expression2 editor suffer from copy/paste issues due to this.

**Comment by thegrb93** [comment]
It looks like TextEntry is used as a buffer to receive inputs, but copying or pasting something greater than the limit causes it to get cut off.

**Comment by robotboy655** [comment]
Panel:GetText() is not limited. Used it.

**Comment by thegrb93** [comment]
Thanks, I updated https://wiki.garrysmod.com/page/Panel/GetValue
