### ISSUE TITLE
can't turn head

### ISSUE THREAD

**Issue by DezFlameFox** [Facepunch/garrysmod-issues#4105]
Here is all of the code I have from running the game.

Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Initializing Awesomium..
Parent cvar in server.dll not allowed (p2p_enabled)
Parent cvar in server.dll not allowed (props_break_max_pieces)
Failed creating font 'Roboto'!
Addons have changes - remounting
Got Subscription details!
Got Subscription details!
END: DownloadAddons
Addons have changes - remounting
Unmounting addons/winter_solstice_1944734598.gma
Addons have changes - remounting
Restoring gamemode to sandbox
Restoring gamemode to sandbox
PREP OK
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
Using map cycle file cfg/mapcycle.txt.
Error: Material "models/humans/female/pupil_r" uses unknown shader "Eyeball"
Error: Material "models/humans/female/pupil_l" uses unknown shader "Eyeball"
Restoring gamemode to sandbox
Garry's Mod

sandbox
gm_construct
1
76561198947720344
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
InitFastCopy: only 26% fast props. Bug?
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/bloomadd)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/no_pixel_write)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/lumcompare)
clientside lua startup!
Failed creating font 'Roboto'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "models/humans/female/pupil_r" uses unknown shader "Eyeball"
Error: Material "models/humans/female/pupil_l" uses unknown shader "Eyeball"
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/bloomadd)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/no_pixel_write)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/lumcompare)
Failed creating font 'Roboto'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Failed creating font 'Roboto'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
Failed creating font 'Roboto Bk'!
Redownloading all lightmaps
--- Missing Vgui material vgui/crosshair_bg
ConVarRef hap_HasDevice doesn't point to an existing ConVar
'userconfig.cfg' not present; not executing.
Host_WriteConfiguration: Wrote cfg/config.cfg
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized

I don't know the source or how it was produced. My game was fine for awhile, but then the camera stopped working once I changed my model. Ive tried re-dowloading the game and changing the mouse sensitivity, but other than that, I don't know what to do. Its happened to other people too, but nobody has a solution to the problem.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
