### ISSUE TITLE
Trouble with extracting bz2 files

### ISSUE THREAD

**Issue by Crionis** [Facepunch/garrysmod-issues#4106]
Players sometimes have error - missing map. 
I found massive problem, when client sucessufuly downloaded map from fastDL server, but something going wrong and client trying to get uncompressed map from fastDL server, then got 404 and still missing map.

Meanwhile GMOD just have trouble with extract bz2 files in downloads/maps, there is no extracted .bsp, bz2 files have 0 bytes and still exist in folder, game still thinking bz2 is already downloaded and trying to get uncompressed map.

Fix it please!

**Comment by Verideth** [comment]
BZ2 is a file extension not everyone has, why are you using that? They probably cannot extract it.

**Comment by Kefta** [comment]
Because that's what GMod uses for FastDL. The 0 bytes problem is from the file failing to download, not with decompression.

**Comment by Crionis** [comment]
> The 0 bytes problem is from the file failing to download, not with decompression.
1. Apache log says it uploaded sucessful.
2. Why GMod is not trying to download it again?

Apache log:
[26/Dec/2019:23:24:33 +0300] "GET /fastdl/maps/zs_ravine.bsp.bz2 HTTP/1.1" 200 50941447 "hl2://****:27015" "Half-Life 2"
[26/Dec/2019:23:25:22 +0300] "GET /fastdl/maps/zs_ravine.bsp HTTP/1.1" 404 526 "hl2://****:27015" "Half-Life 2"
[26/Dec/2019:23:25:51 +0300] "GET /fastdl/maps/zs_ravine.bsp HTTP/1.1" 404 527 "hl2://****:27015" "Half-Life 2"

On client:
[Screen shot of downloads/maps](https://sun9-14.userapi.com/c855416/v855416729/1b57c4/EhGH4ndO_08.jpg)

**Comment by robotboy655** [comment]
Should be fixed on Dev branch - when it finds a 0byte file it will be redownloaded if possible.
