### ISSUE TITLE
Extremely low FPS/Crashes

### ISSUE THREAD

**Issue by jakkuedits** [Facepunch/garrysmod-issues#4107]
### Details
Whenever I go into a populated area (30-50) people I get extremely low FPS and my console gets spammed with CUtlLinkedList overflow! (exhausted index range) After this, if I start moving around my game will freeze for a solid second or two and then continue, until another 10 seconds and it will freeze again.

### Steps to reproduce
Go into an area with a good amount of people. Switch to normal branch with exact same setup and everything is fine.

**Comment by robotboy655** [comment]
This is a problem with the server you are playing on, and/or the addon it is running.
