### ISSUE TITLE
Post respawn flashlight-toggle causes premature AUX-Power Element

### ISSUE THREAD

**Issue by Mailer99** [Facepunch/garrysmod-issues#4109]
### Details
The HUD-element responsible for showing AUX-Power levels can still be prompted to show prematurely, despite the fact that the suit-option may be disabled. Through the use of the flashlight and the act of respawning. 
The element will appear in the moment of respawning, as soon as the flashlight feels that it is possible to toggle itself on, hence the player being dead, of course. It will never fade from the screen despite the fact that it is always displaying full energy, and will likewise never drain from the flashlight or through oxygen supplement in water. It also does not react to sprinting, and will only last until the player dies, assuming that the player does not follow the same procedure in order to make it appear yet again.

Tested on the dev-branch; Multiplayer, Sandbox
Flashlight Key: "MOUSE5"

### Steps to reproduce
1. Fall into a dead playerstate, obviously.
2. Hold your designated flashlight-key while in the dead state.
3. Respawn with any remaining eligible key while holding the aforementioned flashlight button down.

Post-death-and-respawn after a while. Note that the energy level is still full:
![2019-12-27_22-23-21](https://user-images.githubusercontent.com/31503866/71533147-86186400-28f7-11ea-8bf5-5dc4f6ba389a.png)

**Comment by robotboy655** [comment]
Should be resolved on Dev,
