### ISSUE TITLE
Silent crashes

### ISSUE THREAD

**Issue by FiG-Scorn** [Facepunch/garrysmod-issues#411]
Garrysmod is repeatedly generating silent fatal errors, that cause the game to crash unexpectedly. No error logs, no "hl2.exe has stopped working" unless the crash occurs at connection... Nothing.

This is very disruptive to gameplay, take for instance just now. I was about to start up a round of Zombie survival while typing this out, I didnt even get a chance to say Hi before my sound cuts out, the game starts to jump as if the connection to the server had been lost, and then the game just closes. Sometimes it doesnt even close properly. On the other end, players report me to have had me disconnect for the reason: "Steam Auth ticket has been Canceled".

This has been a plague for the last 3 versions, and has reached an unacceptable point now. Please fix this ASAP. I've had it up to here with these crashes.

FYI there is no consistency between them, other than the fact that on gamemodes other than Sandbox, these crashes occur more frequently.

**Comment by robotboy655** [comment]
#590
