### ISSUE TITLE
func_remove crash

### ISSUE THREAD

**Issue by pizzadox11** [Facepunch/garrysmod-issues#4111]
not much info to provide.. when you spawn a ragdoll inside func_remove the game/server crashes. same if you try to move the ragdoll from outside the trigger to the trigger.
func_remove need to disable the spawn of props inside the trigger and delete them on contact-which is working.

**Comment by Kefta** [comment]
Entity spawning can't be prevented on a positional basis since the position is set after creation, and removal always happens at least one tick after creation. The crash should be fixed tho

**Comment by pizzadox11** [comment]
> Entity spawning can't be prevented on a positional basis since the position is set after creation, and removal always happens at least one tick after creation. The crash should be fixed tho

Thanks and I didnt know that, But its not critical.
I was looking for a way to block players spawning props inside a lift to prevent stuck lift, So i applied func_remove to the entire lift room and after some testing i found the bug out.
You must use sbox_maxragdolls 0 if you use any map with func_remove. Annoying!

**Comment by robotboy655** [comment]
Should be fixed on Dev branch.
