### ISSUE TITLE
Custom particles wont load automatically

### ISSUE THREAD

**Issue by pizzadox11** [Facepunch/garrysmod-issues#4112]
Hello once again.
If you use custom particles on hammer and apply them ingame. You must refresh your game settings inorder for them to display ingame-change resolution/Type record in console.
My map uses custom particles and they dont work unless silly as its sounds I run this on the clients on my server to fix the issue
`hook.Add( "InitPostEntity", "refreshcoms", function()
timer.Simple( 60, function() RunConsoleCommand("record", "rp_downtown2020") end )
timer.Simple( 63.5, function() RunConsoleCommand("stop") end )
end)`
Its not critical to fix but its a stupid waste of time until you notice whats wrong with your map if you decide to use custom particles.
btw
swaying trees are flickering on dynamic light

**Comment by robotboy655** [comment]
Sounds like you are doing something wrong. You are meant to embed a file like this:
![image](https://user-images.githubusercontent.com/3299036/71669655-16322f80-2d76-11ea-8ff2-4fb798b7da74.png)

as well as the .pcf files In your .bsp, you can find the format example in GMod's `maps/` folder.

**Comment by pizzadox11** [comment]
> Sounds like you are doing something wrong. You are meant to embed a file like this:
> ![image](https://user-images.githubusercontent.com/3299036/71669655-16322f80-2d76-11ea-8ff2-4fb798b7da74.png)
> 
> as well as the .pcf files into your .bsp, you can find the format example in GMod's `maps/` folder.

I did pack the .pcf files and added the text file, I didnt test it in singleplayer, I think it works fine. However on multiplayer I must use game.AddParticles() to make it work for the clients. But after adding it, the clients still dont see it, only after doing the record thing to display it

**Comment by robotboy655** [comment]
Link the map?

**Comment by pizzadox11** [comment]
> Link the map?

https://steamcommunity.com/sharedfiles/filedetails/?id=1932491380
check the video i made http://rp2020.nn.pe/Recording%20%231.mp4

**Comment by robotboy655** [comment]
Yeah this isn't how you do it:
![image](https://user-images.githubusercontent.com/3299036/71733544-8ada9c00-2e52-11ea-99c3-d9742c1f8542.png)

You need to do it like this:
![image](https://user-images.githubusercontent.com/3299036/71733670-cd9c7400-2e52-11ea-9f76-965cb45001bf.png)
