### ISSUE TITLE
Gmod is Dying ! A LOT OF PROBLEMS

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4114]
A lot of servers are dying because of fakes servers, and americans server and chinese servers

RubatBoy, can you please for this new year, fix sv_region back again (like before) and make all the servers show up in the list even if they're Empty?

i'm loosing my players ! man i had 800 Players daily (Proof: http://teamfrench.net/222.png)
And now my servers are dying because of the Shitty Load of servers (10k servers of 10k players) man and 50% are fake and russians servers.

So what you need to fix:
1) Make empty servers show up for people (because 80% of players don't see empty servers) : Happens with switzerlands players.
2) Fix sv_region, so people see servers in their regions Only (so we won't see chineese and russians shit servers (like back in 2015-2016)
3) Fix The workshop (people need to wait more time before joining Servers) : People join the server after 30 minutes instead of 30 seconds (Something is Wrong with the new GMOD UPDATE)

**Comment by anyome** [comment]
The new gmod update made the workshop sooo long, and people need to wait like Half an hour to join my server because i have (300 addons) but before the new idiot Update people was joining in 30 Seconds with +300 addons

Dude you're killing Gmod can you just stop updating this game? You make it worse every time, why don't you just focus on Multi threading serverside and clientside and stop the other things

**Comment by thegrb93** [comment]
RP killed gmod if anything

**Comment by Kefta** [comment]
The sv_region changes were by Valve, not Facepunch. It all goes through the Steam.

**Comment by mcNuggets1** [comment]
You just proclaim, because your shit server is dying, that gmod is dying.
Nah, it's not, just your shitty workshop server.

**Comment by anyome** [comment]
How do you explain fake servers and shitty servers like monolith that uses fake players to get more people on their servers

**Comment by Kefta** [comment]
Monolith doesn't use fake players but alright

**Comment by FlorianLeChat** [comment]
TeamFrench is a french community that has a very bad reputation in France, they have done a lot of trouble to other french servers/communities (DDoS, hacking, server theft, etc..). @anyome if I'm not wrong, it's not very cool to compare yourself to other communities that don't do this kind of things. And one more thing, you clearly don't have more than 800 players per day...
