### ISSUE TITLE
DataTable variables are not correctly updated.

### ISSUE THREAD

**Issue by TomatoCo** [Facepunch/garrysmod-issues#4115]
### Details

Some DataTable variables are not synchronized correctly on reconnect. Some do not synchronize even when the client does not disconnect.

### Steps to reproduce

From the Server's GM:Think(): Set some variables. 
From the Client's GM:HUDPaint(): Print those variables.
The client has an inconsistent view. Sometimes they all sync, sometimes *ONLY SOME OF THEM* sync.

Set up an entity with some DataTable variables.
Permute them in some way.
Reconnect. Only some variables will match the server's.

Entities after initialization:
```
Entity [679][tf_cappoint]	false	0	10	0  
Entity [680][tf_cappoint]	false	0	0	0  
Entity [687][tf_cappoint]	false	0	0	0

```

Entities after interaction:
```
Entity [679][tf_cappoint]	true	785.55999755859	10	1  
Entity [680][tf_cappoint]	false	0	0	0  
Entity [687][tf_cappoint]	true	51.474998474121	10	1
```

Entities after reconnect:
```
Entity [679][tf_cappoint]	true	785.55999755859	10	1  
Entity [680][tf_cappoint]	true	161.06500244141	0	1  
Entity [687][tf_cappoint]	false	51.474998474121	10	0
```

**Comment by robotboy655** [comment]
You are probably encountering the PVS thing, which is normal. Make sure your transmit state on those entities is set to TRANSMIT_ALWAYS.

If an entity is visible to the clientside Lua, doesn't mean it is in PVS and is receiving updates.

Also in your report you talk about a single entity, but in your "example" you show multiple entities with 1 variable each.

**Comment by TomatoCo** [comment]
The entity remains inconsistent even if I walk up to it. It is set to
always transmit. Each of those variables are DT vars, only some are being
updated.

**Comment by robotboy655** [comment]
Can you find a reliable way to reproduce it on demand? Can you show your code?

**Comment by TomatoCo** [comment]
It is reproducible on demand. However, since opening this issue I found
that it may be caused by my own error. When I get home from work I'm going
to add debug to my last commit and see if I can recreate the problem. If I
can, I'll try making a minimal demo to upload.

**Comment by TomatoCo** [comment]
[junk.zip](https://github.com/Facepunch/garrysmod-issues/files/4017513/junk.zip)
Please start this on the map gm_flatgrass

Every 20 seconds an entity with the PointsLeft variable (4th from top) <= 0 will be reinitialized to 10 points left and other default status. If you hit Use on one of the points it will initialize the entity to a bunch of random things, and decrement the PointsLeft variable.

Reconnecting to the server sees all but the PointsLeft variable reset.

**Comment by willox** [comment]
In `ENT:Initialize` you only want to initialize your DT vars on the server (as the client may have already received them and will then be overwriting them.)

**Comment by TomatoCo** [comment]
Glad to know I was right about one thing: It _was_ my fault.
