### ISSUE TITLE
Game crashes randomly while playing DarkRP 

### ISSUE THREAD

**Issue by RobinCirex** [Facepunch/garrysmod-issues#4117]
### Details
There isn't much to say, it just crashes. I don't know why. I have tried reinstalling everything and stuff, but it doesn't work

### Steps to reproduce
Basically I just have to tab out / go into the pause menu. Sometimes it crashes out of nothing

**Comment by Verideth** [comment]
What is your dump file showing? We need more info than it "just crashes." For all we know this could be completely unrelated to Garry's Mod, and 100% related to your CPU.

**Comment by robotboy655** [comment]
Looks like you are crashing due to Awesomium, **possibly** by running out of VRAM.

You should try Chromium or x86-64 branches and see if its any better.
