### ISSUE TITLE
Fonts are not downloaded on x84-64 - Chromium

### ISSUE THREAD

**Issue by adamnejm** [Facepunch/garrysmod-issues#4118]
Materials have downloaded fine, but I had no luck with fonts.
I've tried:
bz2 compression;
AddFile and AddSingleFile, executed from garrysmod/addons/test/lua/autorun and from garrysmod/lua/autorun;
~10 different fonts (all .ttf);
Workshop Collection;
AddWorkshop;
Not using the resource lib;
lowercase, camelCase, UPPERCASE, Matching Case;
HTTP / HTTPS

To make fonts download I need to switch to default Garry's Mod branch (opt out of any betas). Then everything works correctly, `ttf` and `bz2` are downloaded.

You might think to mark it as duplicate, but other threads don't mention the branch and authors stopped responding after promises to test.

**Comment by robotboy655** [comment]
Please post the console log after download fails.

**Comment by adamnejm** [comment]
After extensive testing turns out its not the branch, but whether you use addon or non-addon structure to run your files and where you put the resources.
I'm closing this issue, but please check out my comment on this post: https://github.com/Facepunch/garrysmod-issues/issues/3406
