### ISSUE TITLE
Infinite lag with igniting a set of props

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4119]
### Details
This works on dedicated servers, listen servers and single player.

Spawning 100 props in each other which are ignitable and then casting an explosion nearby infinitely hangs any server, client infinietely.
I don't know the reason for it to infinite hang servers, tho I might understand the reason for it to infinite hang clients.

### Steps to reproduce
`lua_run for i=1, 100 do local e = ents.Create("prop_physics") e:SetModel("models/props_phx/construct/glass/glass_curve360x2.mdl") e:SetPos(Entity(1):GetPos()) e:Spawn() e:GetPhysicsObject():EnableMotion(false)  end`

`lua_run util.BlastDamage(Entity(1), Entity(1), Entity(1):GetPos(), 100, 1)`

**Comment by robotboy655** [comment]
I don't know what you expect the physics engine to do when you spawn 100 objects inside each other

**Comment by mcNuggets1** [comment]
They are frozen.
It's the fire which does the crashing.

**Comment by robotboy655** [comment]
Well yeah, but when the flames do radial damage it all goes back to vphysics. This isn't something I can see happen naturally in game, and just having props near each other on fire doesn't cause this problem.

**Comment by mcNuggets1** [comment]
Naturally its using stacker to spawn frozen props in each other or just ya know weld and then spawn a prop, which can explode and make it explode => crash

**Comment by robotboy655** [comment]
Well then its a problem for stacker to solve. I don't see a fix here without removing fire damage.

**Comment by mcNuggets1** [comment]
For sure it is really expensive fire then.
