### ISSUE TITLE
print, MsgC, etc limited to 2048 characters in x86-64 branch

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#4120]
Run `lua_run print(("A"):rep(4000))` in console on regular vs x86-64 branch and spot the difference. Also, at the place it cuts off it seems to print 4 random bytes.

Same issue on both 32 and 64 bit.

![image](https://user-images.githubusercontent.com/2332094/72066550-2d769d00-32e1-11ea-8878-a82ffc311b3c.png)

**Comment by robotboy655** [comment]
This is the case on all branches as far as I can tell.

**Comment by Donkie** [comment]
Just to clarify, it does not cut off on the stable release gmod.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/72071783-44bf8580-32f5-11ea-9f38-a8b73212a762.png)

It is, just at twice the length.

**Comment by robotboy655** [comment]
Will be fixed soon.
