### ISSUE TITLE
Triggers do not fire with non 0 0 0 angles property

### ISSUE THREAD

**Issue by metrotyranno** [Facepunch/garrysmod-issues#4121]
### Details
Brushes with the angles property set to anything other than 0 0 0 do not trigger ENT:StartTouch and ENT:EndTouch.

Tested on: 
Dedicated server (current version)
x86-64 2020.01.09
(no beta) 2019.12.18

### Steps to reproduce
- Create a small map in hammer with 3 brushes, apply tools/toolstrigger to these brushes
- make the class of the brush a custom entity
- Leave 1 brush alone, on 1 brush set angles property with 0 0 0, and on the last set angles 0 180 0
- Create a custom entity on the client with the starttouch and endtouch event printing something (for debugging)
- Load the map & walk through the brushes

Brush 1 and brush 2 will trigger, brush 3 (with the 0 180 0 angles applied) will not

Custom ent:
`
ENT.Base = "base_brush"
ENT.Type = "brush"

function ENT:Initialize() 
	print('hello brush')
end

function ENT:StartTouch( Ent )
	print('start touch')
end

function ENT:EndTouch( Ent )
	print('stop touch')
end
`

**Comment by bigdogmat** [comment]
Try calling `self:SetSolid(SOLID_OBB)` in Initialize

**Comment by metrotyranno** [comment]
@bigdogmat Unfortunately no change

**Comment by metrotyranno** [comment]
When setting the angle with self:SetAngles(Angle(0,180,0)) in ENT:INITIALIZE it also stops triggering the starttouch and endtouch events. When subsequently calling self:SetAngles(Angle(0,0,0)) they start firing again.

**Comment by robotboy655** [comment]
That's not exactly what's going on.

What is happening is that you are not setting the "origin" key on your brush, which makes it rotate around the 0,0,0 point of the map, rather than around where you'd expect its center to be.

**Comment by metrotyranno** [comment]
When I use SetPos prior to setting the angle the trigger brush goes invisible. It's not visible at the GetPos or OBBCenter

**Comment by metrotyranno** [comment]
Correction, I just found that the Brush has moved, But when using its' getpos it spawns at the correct location. How do I set the position of the brush?

**Comment by robotboy655** [comment]
You need to set the "origin" key of the brush in Hammer, before compiling. That sets the origin of rotation for the brush. If you don't do that, you have to SetPos and SetAng with some non trivial math to get the same result, which I will not explain here, you can learn that yourself.
