### ISSUE TITLE
[SUGGESTION] Adding CSS/HL2 EP1/HL2 EP2 Content to Gmod by Default

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4123]
My suggestion is to Add: CSS Textures + HL2 EP1-EP2 Textures (Materials + Models) By default to garry's Mod

Why?
90% Of Players leave garry's mod because when they first buy the game they don't have the textures, they see everything in Pink and Black + Errors, so they think that gmod is a shitty game.

Why not adding CSS + HL2 EP1 AND EP2 textures by default to garry's mod?

Like this we can have a load of players ! People won't be forced to download the CSS content everytime they buy the game + more people will stay longer on gmod

**Comment by anyome** [comment]
And in my opinion instead of adding new Updates to gmod that serve on Nothing, you can start by putting my Suggestion because this suggestion is the one that will make Gmod live again.

This is the most important Update that gmod need to have in the History, This update can increase the players rate by: 80%.

I never saw a game in my life that comes without textures.
And all the mappers are retarded and they only use CSS + HL2 textures.

Add this update ,as it is the most important shit update in the gmod history and this update can accomplish 80% of gmod needs.

Stop thinking about any other update, and just add this one.

**Comment by FoksVHox** [comment]
This repo is for issues such as error etc. Use https://github.com/Facepunch/garrysmod-requests for feature requests.

**Comment by robotboy655** [comment]
We legally cannot do this.
