### ISSUE TITLE
rp_newexton train control bug

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4125]
### Details
Using a prop inside a train, pressing E on it opens an old HL1 interface for controlling trains.
It can be hidden again by pressing E on the train again, but the train itself can be controlled using W and S.
I don't think this should work.

### Steps to reproduce
Spawn a prop inside the train of rp_newexton.
Hold it via Physics Gun and press E on it.
Hopefully open the interface.

https://i.imgur.com/dcz5FoZ.jpg

**Comment by Kefta** [comment]
func_tracktrains are user controlled by default; if you want it disabled, set spawnflag 2 on the ent. Your use trace is hitting the train, not the prop.

**Comment by mcNuggets1** [comment]
Odd, if its not a bug, then it is weird, it never closes by default.
Well I close this ,then.

**Comment by Kefta** [comment]
HL1 train controlling is very buggy in general.

**Comment by robotboy655** [comment]
Furthermore I couldn't reproduce this which makes it possible its a problem with that specific map.

**Comment by mcNuggets1** [comment]
Grab a prop in the new exton train, press E while not looking at the prop, otherwise it wont work.

**Comment by robotboy655** [comment]
Hm I think I see what's going on here. This is only a problem with the physgun right? Can you actually do this without holding a prop with physgun?

Physgun internally uses a flag related to trains to stop the player from moving while allowing mouse look and still receive keyboard inputs.

**Comment by mcNuggets1** [comment]
Its only possible with physgun, yes and only while using it.

**Comment by robotboy655** [comment]
Should be fixed in Dev.

**Comment by mcNuggets1** [comment]
thanks
