### ISSUE TITLE
GetNWVarTable question

### ISSUE THREAD

**Issue by R4K0** [Facepunch/garrysmod-issues#4126]
### Details
Given that we're going to have x64 bit released - It's been a while since we heard about when https://wiki.garrysmod.com/page/Entity/GetNWVarTable is going to be merged into master - Are there any current issues that prevent this feature to be merged in? It'd be hugely helpful for any systems implementing load/save and persistence of entities, for example.

**Comment by robotboy655** [comment]
It definitely not coming in any updates this month at the moment, maybe I shall re implement it with current system though.

**Comment by R4K0** [comment]
Yeah

**Comment by robotboy655** [comment]
You can use https://wiki.garrysmod.com/page/Global/BuildNetworkedVarsTable in the mean time.

**Comment by robotboy655** [comment]
Added to Dev branch.
