### ISSUE TITLE
x86-64 update: no steam overlay on Linux

### ISSUE THREAD

**Issue by LiamDawe** [Facepunch/garrysmod-issues#4127]
Testing out the new x86-64 branch on Steam, that has 64bit and Chromium, there's now no Steam Overlay.

Fine other than that so far.

Full system info: https://pastebin.com/vhfjTN98

Whatever other info/tests you need, let me know. Happy to help.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3925 and https://github.com/Facepunch/garrysmod-issues/issues/4058
