### ISSUE TITLE
Gmod DarkRP Server Crash

### ISSUE THREAD

**Issue by SunsetFlare017** [Facepunch/garrysmod-issues#4128]
### Details
So I used to play a Dark RP server for hours without a crash today the 14/1/2020 Gmod Updated and I started to crash a lot more while in game the crash report I'm getting is always the same:
 Problem Event Name:	BEX64
  Application Name:	gmod.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5dd07f01
  Fault Module Name:	engine.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5e1ccec3
  Exception Offset:	0000000000328c66
  Exception Code:	c0000417
  Exception Data:	0000000000000000
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	c24a
  Additional Information 2:	c24a81338d1152e2975d7e13e72fe878
  Additional Information 3:	646a
  Additional Information 4:	646a7412535fb0827eb281a906797284

Crash file attached 

[3be4eb7a-ec5f-44a0-8b79-f9af8bd5a616.txt](https://github.com/Facepunch/garrysmod-issues/files/4057513/3be4eb7a-ec5f-44a0-8b79-f9af8bd5a616.txt)

**Comment by robotboy655** [comment]
You will need to attach the .dmp file (or sent it to either one of the email addresses here: https://github.com/Facepunch/garrysmod-issues

Without there's nothing to look into.

**Comment by robotboy655** [comment]
This should be fixed within the hour.

**Comment by SunsetFlare017** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/47861176/72383217-ab90d480-3723-11ea-8ecb-e12581cf0486.png)
I'm getting this error now and crash

**Comment by willox** [comment]
I think I know what's wrong. I'll fix it soon.

**Comment by willox** [comment]
Should be double fixed?

**Comment by SunsetFlare017** [comment]
I'll check

**Comment by SunsetFlare017** [comment]
So far no crashes Thank you both I'll update if something changes

**Comment by SunsetFlare017** [comment]
My game crashed again today for the same issue...I can send the DMP file if you need it

**Comment by willox** [comment]
please send it to willox@facepunchstudios.com
