### ISSUE TITLE
CW 2.0 Addon Errors

### ISSUE THREAD

**Issue by CorinTheGreat** [Facepunch/garrysmod-issues#4131]
I am having problems with the addon called Customizable Weaponry 2.0. There are a few errors that I have. Here is the error:

[ERROR] addons/customizable weaponry 2.0 rev75/lua/weapons/cw_base/shared.lua:1553: attempt to call method 'FireBullet' (a nil value)
  1. unknown - addons/customizable weaponry 2.0 rev75/lua/weapons/cw_base/shared.lua:1553

and this one:

[ERROR] addons/customizable weaponry 2.0 rev75/lua/weapons/cw_base/sh_bullets.lua:7: table index is nil
  1. unknown - addons/customizable weaponry 2.0 rev75/lua/weapons/cw_base/sh_bullets.lua:7
   2. include - [C]:-1
    3. unknown - addons/customizable weaponry 2.0 rev75/lua/weapons/cw_base/shared.lua:85

Here are the files:
[shared.txt](https://github.com/Facepunch/garrysmod-issues/files/4064290/shared.txt)
[sh_bullets.txt](https://github.com/Facepunch/garrysmod-issues/files/4064299/sh_bullets.txt)

Can you help me how to fix these errors please?

**Comment by Donkie** [comment]
This github is not for errors in addons, contact the owner/maintainer of CW instead.
