### ISSUE TITLE
TFA Base Addon Errors

### ISSUE THREAD

**Issue by CorinTheGreat** [Facepunch/garrysmod-issues#4132]
I had another problem with another Customizable Weapons addon. Literally every single weapons addon had errors with my game. Here are the errors:

nt progress for GMA_BADCODER

[ERROR] addons/tfa base/lua/tfa/modules/tfa_meta.lua:42: attempt to call method 'SetNW2Bool' (a nil value)
  1. TFA_SetZoomKeyDown - addons/tfa base/lua/tfa/modules/tfa_meta.lua:42
   2. v - addons/tfa base/lua/tfa/modules/tfa_hooks.lua:257
    3. unknown - lua/includes/modules/hook.lua:84

[ERROR] addons/tfa base/lua/tfa/modules/tfa_hooks.lua:373: attempt to call method 'GetNW2Bool' (a nil value)
  1. v - addons/tfa base/lua/tfa/modules/tfa_hooks.lua:373
   2. unknown - lua/includes/modules/hook.lua:84

[ERROR] addons/tfa base/lua/tfa/modules/tfa_meta.lua:42: attempt to call method 'SetNW2Bool' (a nil value)
  1. TFA_SetZoomKeyDown - addons/tfa base/lua/tfa/modules/tfa_meta.lua:42
   2. v - addons/tfa base/lua/tfa/modules/tfa_hooks.lua:257
    3. unknown - lua/includes/modules/hook.lua:84

[ERROR] addons/tfa base/lua/tfa/modules/tfa_hooks.lua:373: attempt to call method 'GetNW2Bool' (a nil value)
  1. v - addons/tfa base/lua/tfa/modules/tfa_hooks.lua:373
   2. unknown - lua/includes/modules/hook.lua:84

[ERROR] addons/tfa base/lua/tfa/modules/tfa_hooks.lua:125: attempt to call field 'WriteBool' (a nil value)
  1. v - addons/tfa base/lua/tfa/modules/tfa_hooks.lua:125
   2. unknown - lua/includes/modules/hook.lua:84

Achievements disabled: Steam not running.
Achievements disabled, ignoring achievement progress for GMA_BADCODER

[ERROR] addons/tfa base/lua/tfa/modules/tfa_meta.lua:42: attempt to call method 'SetNW2Bool' (a nil value)
  1. TFA_SetZoomKeyDown - addons/tfa base/lua/tfa/modules/tfa_meta.lua:42
   2. v - addons/t

And here are the files:

[tfa_hooks.txt](https://github.com/Facepunch/garrysmod-issues/files/4064502/tfa_hooks.txt)
[tfa_meta.txt](https://github.com/Facepunch/garrysmod-issues/files/4064503/tfa_meta.txt)

PLS FIX THESE ERRORS OTHERWISE ILL NEVER BE ABLE TO TEST WORKSHOP WEAPONS IN GMOD.

**Comment by robotboy655** [comment]
Addon errors need to be reported to addon authors, not here.
