### ISSUE TITLE
Local HTTP block catching wrong URL's

### ISSUE THREAD

**Issue by deadmonstor** [Facepunch/garrysmod-issues#4133]
### Details
Some urls are being caught as local even though they should be perfectly allowed. 

Without -allowlocalhttp:
https://i.imgur.com/mUjxD3L.png

With -allowlocalhttp:
https://i.imgur.com/me5zTSe.png

### Steps to reproduce
Run this code serverside with and without -allowlocalhttp: https://pastebin.com/UEHmekAs

**Comment by Donkie** [comment]
Yup I'm getting same results with your test code

**Comment by robotboy655** [comment]
There's nothing that can be done here.

**Comment by joeyjumper94** [comment]
it seems that if there is a 
> 10.
in the URL, it will think that it is al local address

**Comment by neico** [comment]
The following regex (source1 & VS2013+ supports C++11, which has `#include <regex>` available) would be more accurate and only capture local addresses after `://` which is the start of a `<host>` identifier (as per URI/URL specification):
`:\/\/(127\.|\[(?:::|(?:(?:0|0{4}):){7})(?:0{3})?1\]|10\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.|192\.168\.|\[[fF][cCdD])`
As of note is that the regex doesn't enforce the limit of 0-255 or 0000-ffff per section, as it's not relevant for the purpose of detecting local addresses

Captured IP ranges (IPv6 IP's are identified by brackets surrounding them in URL's):
Local Loopback IPv4 + IPv6 (`127.0.0.0` - `127.255.255.255` / `[::1]` or `[0:0:0:0:0:0:0:1]` or `[0000:0000:0000:0000:0000:0000:0000:0001]` )
Private Class A (`10.0.0.0` - `10.255.255.255`)
Private Class B (`172.16.0.0` - `172.31.255.255`)
Private Class C (`192.168.0.0` - `192.168.255.255`)
IPv6 unique local address (ULA), aka IPv6 Private Class (`[fc00::1]` or `[fc00:0:0:0:0:0:0:0]` or `[fc00:0000:0000:0000:0000:0000:0000:0000]` - `[fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff]`)

So yes, there is something that could be improved here.

**Comment by meepen** [comment]
At that point you might as well add a url parse library then DNS query the
domain and check against private and restricted addresses lol

**Comment by DBotThePony** [comment]
![gmod_QevMtJqbIJ](https://user-images.githubusercontent.com/6339511/76919878-b7a03a80-68fc-11ea-862e-24732ba8987d.png)
![Discord_IM1aNwssUj](https://user-images.githubusercontent.com/6339511/76919896-bf5fdf00-68fc-11ea-92d6-b9a6994ada49.png)
![Discord_Mm404bvCiB](https://user-images.githubusercontent.com/6339511/76919910-c686ed00-68fc-11ea-9bcf-de8b146ae813.png)
![Discord_BeFDWjAbDa](https://user-images.githubusercontent.com/6339511/76919936-d3a3dc00-68fc-11ea-8e4c-2cbc505ac5b9.png)

**Comment by robotboy655** [comment]
this will be addressed with x64

**Comment by IFN3T** [comment]
same problem with srcds...

can u fix it ? it's very problematic..
lot of addons has been affected with this crap hotfix...

**Comment by robotboy655** [comment]
Should be fixed on `dev` and `x86-64` betas.
