### ISSUE TITLE
gmpublish

### ISSUE THREAD

**Issue by pizzadox11** [Facepunch/garrysmod-issues#4134]
I dont sure whats wrong with version 1.2 but after updating it from 1.1(maybe im mistaken with gmad.exe? version 1.1?), gmpublish wont compress any gma files, it wont even mention now "Compressing.. [filesize]"
i ended up uploading 270mb instead of 65mb

**Comment by robotboy655** [comment]
It is intentional, you are still uploading the compressed version, it is just handled by Steam.
