### ISSUE TITLE
Setting angles on a prop_vehicle_jeep doesn't actually set them

### ISSUE THREAD

**Issue by LambdaGaming** [Facepunch/garrysmod-issues#4135]
### Details
Tested with the normal branch on an empty dedicated server running the sandbox gamemode. Using entity:SetAngles() on any vehicle using prop_vehicle_jeep as a base will make it turn, but only until it's touched by something, or until a player gets into the vehicle. Then it will snap back to the original angles it had before they were changed. The vehicle won't change angles at all if they're set while there's a driver. Originally I thought it was affecting other types of vehicles but I did more testing and found that air boats and prisoner pods were unaffected.

### Steps to reproduce
1. Spawn the HL2 jeep.
2. Set the vehicles angles. (I used `lua_run for k,v in pairs(ents.GetAll()) do if v:IsVehicle() then v:SetAngles(angle_zero) end end` through the server console.)
3. Touch the vehicle with the physgun or get into the vehicle and the angle should snap back to what it was before the change.

**Comment by robotboy655** [comment]
Fixed.
