### ISSUE TITLE
Linux x64 Module crash when lua error in GMOD_MODULE_OPEN

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4136]
https://github.com/danielga/gmod_luasocket/pull/8/files#diff-1f3a5491ca952250eb592e31637b6043R22

These ThrowErrors crash in x64 linux but not x64 windows. Dunno if it's a quirk with the garrysmod_common interface or with linux gmod.

**Comment by DaDamRival** [comment]
[The dmp](https://u.teknik.io/vhUov.dmp)

**Comment by willox** [comment]
The crash dump makes me suspect your module is at fault.

The following works fine:
```cpp
GMOD_MODULE_OPEN()
{
    LUA->ThrowError( "Test" );
    return 0;
}
```

I'll check your stuff out in a bit though.

**Comment by thegrb93** [comment]
@willox I suspect it's the interface https://github.com/danielga/garrysmod_common/blob/master/include/GarrysMod/Lua/LuaBase.h

**Comment by willox** [comment]
The interface seems fine and your code doesn't appear to be calling into lua_shared.

**Comment by thegrb93** [comment]
Maybe some kind of compiler flag causing the longjmp to fuck up. I actually don't use Linux so no can do, but I'll let you know if we find it to be gmod's fault. Hopefully metaman can get around to looking at it. Thanks for verifying it though.

**Comment by thegrb93** [comment]
I have a hunch it's something to do with the -O3 optimization but @DaDamRival will see if -O0 helps any
