### ISSUE TITLE
Face Poser : Multi_ Flex Controller

### ISSUE THREAD

**Issue by sabre12112** [Facepunch/garrysmod-issues#4139]
alright, were do I begin with......

recently, me and my friend were working on tf2 femsniper model to improve it for gmod.
my task is to make that model have HWM flexes, and by that, I had to go into the text edit in blender, do that steps that I've followed, and compile the model.

now, here's were the part is confusing :
in HLMV (Half-Life Model Viewer), I tested the model and it's eyelid flexes that have three controllers :
one for the right flex controller, and the second is for the left flex controller, and the third one is the multi flex controller, by multi it changes the flexes transition, so example : shape_1 to shape_2

in gmod, however, when I move that multi flex controller, it only sticks to one shape, so it only closes to one of the eyelid shapes, either top or lower.

now, this is not exactly focused on TF2 Models, but generally on all the models that have HWM flexes.

however, there's is another face poser improved tool is around the workshop, but I'm not really used to it, I prefer to stick with the default one from gmod itself.

I was wondering if there's a fix for that, hope that would be precised enough.

if you need some images, please do reply so I can send some with proper and clarifying, I would love to do that ^_^

**Comment by robotboy655** [comment]
Alright, have you tested said improved faceposer tool, does it handle those flexes?

But either way, I will need any model that has one of such flexes to look into this. If there isn't one built-in/in TF2 by default, I will need one linked to me. You can send it to my email in the readme of this repo.

**Comment by sabre12112** [comment]
I'll send you the model today when I get back home from school. but while
that, if you have TF2 game, let Gmod mount it, and spawn one of the 8
classes, suggest you to start from scout to the last one, there are
standard and Hardware Morphs (aka HWM), choose Hardware Morphs and look for
the eyelid flexes, once you use the face poser on it, you'll see that the
eyelids close only from the bottom and not the top.

**Comment by sabre12112** [comment]
by the way, I tried to do another test with those improved faceposer tools.
Turns out that they don't affect the multi flex controller to work,
instead, it add negative values for the flex controllers.

**Comment by robotboy655** [comment]
How are you defining these flexes in the .qc? I cannot find any information about this.

**Comment by sabre12112** [comment]
well um, I don't do that in the qc file, I only add the flexes in the qc
file if there was non HWM flexes, so lemme clarify;
there .SMD and .DMX format for the model to be exported from blender, by
using BST (aka Blender Source Tools), the version of BST i'm using is
v2.10.2, for blender v2.79b.
now, I've found a guide on how to make advanced shapekeys in blender for
SFM (although SFM and GMOD do have some common system), a guide made Pte
Jack.
here's the link :
https://steamcommunity.com/sharedfiles/filedetails/?id=245723825

now, I've also realized, there's that part of lines that says :
"rawControlNames" "string_array" ["CloseLidUp" "CloseLidLo"]
"eyelid" "bool" "0"

this part is the one that makes the two shapes for the eyelids have
mutli_flexcontroller, but also after we put 1 instead of 0 for the "eyelid"
"bool", it suddenly creates another flex controller called "Blink", which
doesn't do anything at all!!!

and from here, I'm still confused why the multi_flexcontroller works fine
in hlmv, but not in GMOD.
I've found already a solution for that, but I want to keep that "Blink"
flex for some cases. but if you can't fix the issue, than I understand.
it's not that big of an issue, but seeing it works in SFM and not in GMOD
makes me go crazy to fix it!

**Comment by sabre12112** [comment]
oh, in another words, go into the "Advanced Shapekeys" Tab, and from there
you can read what it produce.

**Comment by robotboy655** [comment]
I know you are eager to hear progress on this, I have been narrowing down the issue but I don't have a fix. What's even more perplexing is that the exact same code works properly on clientside only models. (For example the spawnicon editor has those flexes working correctly)

**Comment by sabre12112** [comment]
understandable. thank you for trying and I really appreciate it ^_^
thanks again for your help and for the respond.

hope to see you next time, have a wonderful day/night! 👋😁

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/74456188-19e5c580-4e8f-11ea-8528-76a6af662951.png)

Ok I figured it out.

It wasn't broken in the engine after all, it was the Faceposer tool itself. There are certain flex controllers that are hidden because they were deemed useless since they seemingly didn't do anything, so they were forced to 0 which was the problem.

I will change the built-in Faceposer to no longer force those flexes to 0 and instead leave them to their default values.

This change will hit the "Dev" beta branch within a few hours.

**Comment by sabre12112** [comment]
YES!!! THANK YOU SO MUCH!!!

now this is going to be very very exciting!!!

again thanks a lot, you are the best ^_^ <3

**Comment by sabre12112** [comment]
please, let me known the fix is applied, thanks again c:

**Comment by sabre12112** [comment]
hi again Rubat.
I tested out the change you did for the face poser tool in the "Dev" beta
branch, and it's working very well, especially for this issue I showed you
since then.
here just to make sure that they are working well and that I'm in the "Dev"
beta branch :
 Screenshot (23412).png
<https://drive.google.com/file/d/1B07wTE5xXwKMN3KL6nLxhkEOurv1MvK3/view?usp=drive_web>
 Screenshot (23413).png
<https://drive.google.com/file/d/17H-aihzk-OEdGsDN2sETeHo8oMM7ChrF/view?usp=drive_web>
 Screenshot (23414).png
<https://drive.google.com/file/d/1fvhGQXsdYZtMBfywcsSmPftqnBpDpDSP/view?usp=drive_web>
 Screenshot (23415).png
<https://drive.google.com/file/d/15NlgIhU0JsbmFbglHPMxCMcmJ14O8nuy/view?usp=drive_web>
 Screenshot (23416).png
<https://drive.google.com/file/d/1Q5CMUZnWjgnFEivJ3N74kiyDvmrOcmH_/view?usp=drive_web>
 Screenshot (23417).png
<https://drive.google.com/file/d/1gEEm2pvjdRpLPtHBRy3T2fjaupXfxfKC/view?usp=drive_web>
 Screenshot (23418).png
<https://drive.google.com/file/d/1-advU_BrkKeuAoZRShxOcVvQRKo1d2nn/view?usp=drive_web>
 Screenshot (23419).png
<https://drive.google.com/file/d/1wBFYTYgHrVaVi0EBoWstiI2G-Pai3TBF/view?usp=drive_web>
 Screenshot (23420).png
<https://drive.google.com/file/d/1W0v8IlE5zDXR5aU1pD9VyiaNqMmuLYbp/view?usp=drive_web>
 Screenshot (23421).png
<https://drive.google.com/file/d/1EVG48yXgIskTzwCzFzk0CGvT6EemWu-I/view?usp=drive_web>
 Screenshot (23422).png
<https://drive.google.com/file/d/1x9AOhaaQLNAUMR_iJh4kRc9ouJJ6cuh4/view?usp=drive_web>
 Screenshot (23423).png
<https://drive.google.com/file/d/1239_JYhhCFknm8FIRiq9m41vMvk7h4pg/view?usp=drive_web>
 Screenshot (23424).png
<https://drive.google.com/file/d/1irc0yEcr6Uj-J3Q8-Duh8PptVGQqmdrV/view?usp=drive_web>
 Screenshot (23425).png
<https://drive.google.com/file/d/1H4jjnZW0myrUi3-QANC4Z5tHlabfsnGm/view?usp=drive_web>
 Screenshot (23426).png
<https://drive.google.com/file/d/1Rrrj5qiWfgLqAwevYfgnSAZ4En3MWxaZ/view?usp=drive_web>
 Screenshot (23427).png
<https://drive.google.com/file/d/14UCihDv7V4D4dzkDpnoIv2b0tXVHSDjV/view?usp=drive_web>
 Screenshot (23428).png
<https://drive.google.com/file/d/137HcslcfoU15hBsRMhmHR7nsgD9r2b3w/view?usp=drive_web>
 Screenshot (23429).png
<https://drive.google.com/file/d/1abi0l09So1Ce-iBDeQH8SdB4hccRGHqw/view?usp=drive_web>
 Screenshot (23430).png
<https://drive.google.com/file/d/1Op3Z6gAUHo8BuSMBgOPM6CYNycwfvQNL/view?usp=drive_web>
 Screenshot (23431).png
<https://drive.google.com/file/d/1MJp3XdmbVd6IIUZ9qiOSQvBcYTvdotyE/view?usp=drive_web>
 Screenshot (23432).png
<https://drive.google.com/file/d/1ZpO0WxZRbdnsjmZeAOzI_M8WIgKG-46E/view?usp=drive_web>
 Screenshot (23433).png
<https://drive.google.com/file/d/1wwakO19bdSF3SCnAK71sq8p3QiWdYWto/view?usp=drive_web>
 Screenshot (23434).png
<https://drive.google.com/file/d/1hUMLkY28ErQQkP6a-Ryx1fCNSJ9lP_hx/view?usp=drive_web>
 Screenshot (23435).png
<https://drive.google.com/file/d/1iq-MrxfmM82QcgOdyFLV8F2WGXutWpgm/view?usp=drive_web>
 Screenshot (23436).png
<https://drive.google.com/file/d/1uPmkBcFnFCu3hWYm8HmNQA7Z-j361X5k/view?usp=drive_web>
 Screenshot (23437).png
<https://drive.google.com/file/d/1EydlN1wuhxQE67bkESRHHQL-ByMmYDKF/view?usp=drive_web>
 Screenshot (23438).png
<https://drive.google.com/file/d/1sz66ZT_cpvZXkaD8rtVpBrLoCLyQoV9u/view?usp=drive_web>
 Screenshot (23439).png
<https://drive.google.com/file/d/1Wchn_jvW28_PxGvREYVQwaswZrsGF0R7/view?usp=drive_web>
 Screenshot (23440).png
<https://drive.google.com/file/d/1ehvzGJw95Ic7HJ3FWGSWVTiAECNnx76Z/view?usp=drive_web>
 Screenshot (23441).png
<https://drive.google.com/file/d/1EMSCaYnNFa7hTInun-KrFDRQStPcylzg/view?usp=drive_web>
 Screenshot (23442).png
<https://drive.google.com/file/d/1EkS_9OnLKJeTpHAZLkbUMTqihmpW2VFf/view?usp=drive_web>
 Screenshot (23443).png
<https://drive.google.com/file/d/1tPudtey2tYzZboRPAVEQnNWlcu7J_ope/view?usp=drive_web>


they are working excellent on tf2 models, but generally the face poser tool
now working great one every model that have these kind of flexes. thanks
again Rubat, I'm so honored to interact and be patient with you on this.

please let me know when the next update for the face poser is coming, I'm
soo excited to work on my animation project this year ^_^
