### ISSUE TITLE
Chinese can't be drawn with the font created with surface.CreateFont

### ISSUE THREAD

**Issue by ArknightsTexas** [Facepunch/garrysmod-issues#4140]
### Details
I used `surface.CreateFont` to create a font with `Microsoft YaHei` family, then I draw text with `draw.DrawText` and used my created font. But the drawn text's Chinese part is drawn with `Simsun（宋体）`, not `Microsoft YaHei`, the English part is drawn with `Microsoft YaHei`.

### Steps to reproduce
Create a font use `surface.CreateFont` with `font = "Microsoft YaHei"` then draw a text in Chinese and English with the created font.

You can see Chinese texts are all rendered with `Simsun`
![Image](https://user-images.githubusercontent.com/18556014/72723646-23e01580-3bbc-11ea-8fb9-0862bb44f6ba.png)

**Comment by robotboy655** [comment]
Have you set `extended` on the font to true?

https://wiki.garrysmod.com/page/Structures/FontData

**Comment by ArknightsTexas** [comment]
didn't know what is `Latin-1 range` :P but it works. (it's weird for no Chinese knows this solution.) :/
and thx
