### ISSUE TITLE
Weapons will reset their position when recieving "clearparent" input when "Start Constrained" Spawnflag is set

### ISSUE THREAD

**Issue by Pacca64** [Facepunch/garrysmod-issues#4143]
### Details
   When a weapon of any kind that has been dropped/spawned/placed in the world has the spawnflag "Start Constrained" (keyvalue is "spawnflags" "1") and is parented, it moves alongside its' parent as intended. However, when you use the input "clearparent" to disconnect the weapon from its' parent object, the weapon suddenly snaps back to it's original position. The Keyvalue also makes it impossible to move or rotate the weapon with the physgun, which doesn't seem like intended behavior either. I'm also certain that a few years ago, this did function as intended, so an update to gmod may have broken this.

   The "clearparent" input is supposed to leave the entity in it's previous position, rather then resetting it back to where the entity spawned. 2 of Valves official maps in Portal ("testchmb_a_01" and "testchmb_a_07") heavily rely on the intended functionality, and it is breaking addons made with the intention of restoring those maps. I tried to make a fix myself, but I don't know if I can counteract the behavior, or if I even should; it's clearly not what should be happening.

   The issue has been tested with the vanilla gmod SWEP "weapon_flechettegun" and the HL2 weapon "weapon_ar2" with workshop addons disabled and all legacy addons removed, so I know it's not just limited to any particular addon; this issue affects all weapons and SWEPs. This was discovered in version "Source Engine 24 (build 7737), although I had noticed some of the effects of the issue in prior builds.

### Steps to reproduce
Video showing the issue being recreated from scratch: https://youtu.be/tbDV-wu1-dg

1. Open Hammer and make a new map (File->New)
2. Save the map and give it any name and file location (it needs to be saved to be compiled)
3. Make a large box to stand in out of brushes with no leaks in it.
4. Add a prop_physics or any other mobile entity to be the parent object. Open it's properties (alt+enter). Give it a model if necessary (Click on "WorldModel", then click on browse and choose a physics prop model, then hit "ok"). Then name it "parent" (Click on "name", type in the text field to the middle-upper right of the window "parent"). Then hit "apply" to close the properties window.
5. place a "weapon_ar2". Disable SmartEdit (hit the button in the upper right that says "SmartEdit") and then click the "Add" button. In the window that comes up, set the "Key" field to "parentname" and the "Value" field to "parent". Click Ok.
6. Click the "Flags" tab in the properties window. Check "Start Constrained".
7. Place an "info_player_start" some distance away from the weapon (so the player doesn't accidentally pick it up when spawning).
8. Hit F9 to open the "Run Map" window. Click ok. After a short wait, Garrys' Mod should open.
9. Move the parent object with the physgun. Note how the weapon moves alongside it, as intended.
9. open the console and type/paste "ent_fire weapon_ar2 clearparent" into it. Note how the weapon suddenly and erroneously snaps back to it's initial spawn position.
10. Try to move and rotate the weapon with the physgun. Note how it has no effect.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
