### ISSUE TITLE
Workshop addons failing to download on server

### ISSUE THREAD

**Issue by Cherry** [Facepunch/garrysmod-issues#4144]
After the update today, and after clearing the `/garrysmod/cache` and `/steam_cache/content/4000` folders, some addons are seemingly not downloading from the workshop. This is on a Linux server, specifically in a Docker container running Debian Jessie.

The specific collection I'm using is https://steamcommunity.com/workshop/filedetails/?id=1640282781, with: `+host_workshop_collection 1640282781`. It's a rather small collection for demonstration purposes.

With this collection, during the server start I see:

```
WS: Waiting for Steam to log us in...
WS: Fetching collection info...
Processing collection 1640282781...
   Collection 'Nodecraft Garry's Mod Server'
   11 new addons
WS: Finished!

WS: Processing 11 addons...
Processing addon 11: [Official] Precision Tool (104482086)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 10: Check 'Em (104768448)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 9: SmartSnap (104815552)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 8: 3D2D Textscreens (109643223)...
   Mounted!
Processing addon 7: Fading door tool (115753588)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 6: NYPD 1940's Model-Group (121961644)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 5: Wiremod (160250458)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 4: PermaProps (220336312)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 3: DarkRP (248302805)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 2: ObjHunt (302390067)...
   Addon file cache missing, redownloading...
   Downloaded!
   Error! Failed to read the downloaded file
Processing addon 1: rp_genova_v3_b4 (1627330883)...
   Mounted!
WS: Finished!
```

The server itself is online and working - no network issues to be seen. Adding `developer 1` doesn't seem to yield any additional debug information. The results are extremely inconsistent.

After this, both the `/garrysmod/cache` and `/steam_cache/content/4000` folders remain empty.

If I revert to a backup of the server I created prior to updating, all of the workshop addons download just fine, without this inconsistency. (Obviously I'm unable to join the outdated server, but the workshop addons are downloaded fine and present in the server filesystem).

Is there a possible rate limiting issue? Is there a way to look at the file it downloaded and failed to read? Or was there a problem saving the file? Some more verbose logs would be very beneficial here, and aid in debugging if this is an issue on my end.

**Comment by Cherry** [comment]
Update: It seems that if I remove the `/steam_cache/` folder in its entirety, things improve and more addons successfully download, but I'm still seeing intermittent `Error! Failed to read the downloaded file` errors.

Is there a way to get more verbose logs for the exact error that's occurring here, be it network, permissions, hash mismatch, etc?

**Comment by robotboy655** [comment]
As I said on the Discord server, do not delete or touch Steam files (steam_cache/). We have no control over any of that if you somehow break something and Steam will think a file is downloaded while it isn't.

There is no more verbose error available, if there were, it would've been given to you. The error means the downloaded file could not be read by GMod's filesystem. It can only happen for non updated addons as well in this instance, as it happens during the manual extraction phase, which did not change. All of this must mean the problem is that the file for this addon in steam_cache/ does not exist.

**Comment by GEAMER007** [comment]
Had that problem after manual steam_cache cleaning. Its actually pretty easy to fix! find file steam_cache/appworkshop_4000.acf and delete everything from line 9 (included) to the end of file. After you did this create a new line 9 and copypaste this:
	"WorkshopItemsInstalled"
	{
		
	}
	"WorkshopItemDetails"
	{
	
	}
}

**Comment by Andrew-Eathan** [comment]
had the same issue on my server, thanks for sharing the fix

**Comment by RoofLee** [comment]
> Had that problem after manual steam_cache cleaning. Its actually pretty easy to fix! find file steam_cache/appworkshop_4000.acf and delete everything from line 9 (included) to the end of file. After you did this create a new line 9 and copypaste this:
> 
> ```
> 	"WorkshopItemsInstalled"
> 	{
> 		
> 	}
> 	"WorkshopItemDetails"
> 	{
> 	
> 	}
> }
> ```
> 
> after you save the file you should start the server and it will redownload everything that it has to

you're best
