### ISSUE TITLE
Severe addon update failure

### ISSUE THREAD

**Issue by BrewsterTKoopa** [Facepunch/garrysmod-issues#4145]
The new Workshop update won't allow me to update specific addons, i merged the textures within them and they are not even 1 GB, there is several errors that occur, one of which being the biggest is, the addon will say it's published, updated, etc, on the tool and workshop page, however it will not do so, infact, it now won't even download for new users, the gmas will not be produced. now three of my packs refuse to properly download now, or update for that matter,  If there is anything i can do, let me know.

**Comment by robotboy655** [comment]
Link the addon? Console logs from affected users? How are they testing if an addon is downloaded? Any useful info at all?

**Comment by BrewsterTKoopa** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1814403819
https://steamcommunity.com/sharedfiles/filedetails/?id=1097325393
https://steamcommunity.com/sharedfiles/filedetails/?id=1165118899

They all update, the tools i had used to update even said the updates were a success, when i boot up gmod, they do appear, and even say they downloaded, but they do not appear in the game, when i went to find their respective GMAs, they are gone.

**Comment by robotboy655** [comment]
Yeah they do not work because you didn't use the tools shipped with Garry's Mod to upload the addon.

**Comment by BrewsterTKoopa** [comment]
> 
> 
> Yeah they do not work because you didn't use the tools shipped with Garry's Mod to upload the addon.

Wrong, i used the tools i know use GMPublish, and most of my other updated addons worked fine. it was just those three specific addons, because

OH I KNOW prior they all had the error of "..."  buffer size, because they were all 600-900 MB, the only way i got them to publish was because of updating to 64-bit ala beta

**Comment by robotboy655** [comment]
The addons you uploaded have no .gma which is why they do not work.

**Comment by BrewsterTKoopa** [comment]
Yes, however. its strictly those three out of like.. the seven i had updated. i have never used a gma for any of those addons, but they still had worked fine.

**Comment by robotboy655** [comment]
There must be something different you did for those 3 then, because the other addon of yours I tried has a .gma like it should. (https://steamcommunity.com/sharedfiles/filedetails/?id=1962337523), while this one has just files https://steamcommunity.com/sharedfiles/filedetails/?id=1814403819 which shouldn't happen with gmpublish.exe

**Comment by BrewsterTKoopa** [comment]
> 
> 
> There must be something different you did for those 3 then, because the other addon of yours I tried has a .gma like it should. (https://steamcommunity.com/sharedfiles/filedetails/?id=1962337523), while this one has just files https://steamcommunity.com/sharedfiles/filedetails/?id=1814403819 which can't happen with gmpublish.exe

i think i might know. though i cannot be certain... I'll test something and come back when i am done.

**Comment by BrewsterTKoopa** [comment]
Alright it's offically closed, nothing worked, i tried switching branches, i tried using the command prompts, and i tried literally everything, nothing has worked. so i'm just gonna revert to the old updates. Thanks anyway, rubat.

**Comment by robotboy655** [comment]
You can't really revert. Just use gmpublish.exe to upload the .gma and it should work just fine.
