### ISSUE TITLE
x86_64 HLMV breaks custom cubemaps lower than VTF 7.5

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#4146]
### Details
Custom cubemaps don't display in HLMV from x86_64.
Default cubemap work fine on both stable and x86_64 (no `materials/hlmv/cubemap.vtf` file):
![default cubemap](https://user-images.githubusercontent.com/5104603/73037059-9e2fc480-3e5e-11ea-9087-07f20b68d1a3.png)
If i add a custom cubemap to HLMV, it works fine on stable:
![cubemap yes](https://user-images.githubusercontent.com/5104603/73037082-bf90b080-3e5e-11ea-9ba1-2bb3a94c642d.png)
But not on x86_64:
![cubemap no](https://user-images.githubusercontent.com/5104603/73037091-c91a1880-3e5e-11ea-8d25-ed85c8b22cb8.png)

### Steps to reproduce
1. Switch to `x86_64` branch
2. Place any cubemap into `materials/hlmv` folder and name it `cubemap.vtf` ([example file i used for screenshots](https://github.com/Facepunch/garrysmod-issues/files/4106397/cubemap.zip))
3. Load any model with envmap reflections in HMLV. You can see that cubemaps don't work anymore.

**Comment by YuRaNnNzZZ** [comment]
Actually it seems like it's a cubemaps's issue itself.
![изображение](https://user-images.githubusercontent.com/5104603/73037424-121e9c80-3e60-11ea-89dc-4e153bd43438.png)
![изображение](https://user-images.githubusercontent.com/5104603/73037426-13e86000-3e60-11ea-8e55-2601055a27ef.png)

It's strange that x86_64 HLMV can't read VTF 7.0 cubemaps but can use 7.5 ones.

**Comment by YuRaNnNzZZ** [comment]
I've compiled same cubemap for all versions (7.0 to 7.5) and HLMV seem to only accept VTF 7.5 cubemaps:
![изображение](https://user-images.githubusercontent.com/5104603/73038048-0f24ab80-3e62-11ea-8e27-b188fdc32439.png)

**Comment by willox** [comment]
I'm not sure I am understanding correctly, but I believe this would be an issue that only effects versions 7.1, 7.2, 7.3, and 7.4. Do you have Problems with 7.0 too?

**Comment by YuRaNnNzZZ** [comment]
yes, 7.0 doesn't work either

**Comment by robotboy655** [comment]
Should be fixed.
