### ISSUE TITLE
PlayerButtonDown only detects one key - must release first key to show others.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#418]
If a key is pressed, no other key will fire this until the initial key has been released. 

Additionally: Chat keys will trigger once, and only once. After the initial trigger, they will cease to show up again.

```lua
hook.Add( "PlayerButtonDown", "BindsManager:PlayerButtonDown", function( _p, _key )
	print( "BUTTON Press: " .. _key )
end )
hook.Add( "PlayerButtonUp", "BindsManager:PlayerButtonUp", function( _p, _key )
	print( "BUTTON Release: " .. _key )
end )

```

**Comment by willox** [comment]
This issue only exists clientside and for certain key combinations. Will fix.
