### ISSUE TITLE
CompileString fails to load bytecode with confusing message

### ISSUE THREAD

**Issue by Elemecca** [Facepunch/garrysmod-issues#432]
When [`CompileString`](http://wiki.garrysmod.com/page/Global/CompileString) is passed LuaJIT bytecode produced by [`string.dump`](http://wiki.garrysmod.com/page/string/dump) it invariably returns one of two errors: "cannot load incompatible bytecode" or "cannot load malformed bytecode". The error message appears to be chosen at random; running the same code multiple times in a row will produce both errors in no discernible pattern. See the test code below. 

``` lua
function hex_dump (str)
    local len = string.len( str )
    local dump = ""
    local hex = ""
    local asc = ""

    for i = 1, len do
        if 1 == i % 8 then
            dump = dump .. hex .. asc .. "\n"
            hex = string.format( "%04x: ", i - 1 )
            asc = ""
        end

        local ord = string.byte( str, i )
        hex = hex .. string.format( "%02x ", ord )
        if ord >= 32 and ord <= 126 then
            asc = asc .. string.char( ord )
        else
            asc = asc .. "."
        end
    end

    return dump .. hex
            .. string.rep( "   ", 8 - len % 8 ) .. asc
end

function foo()
    print( "test" )
end

local bc = string.dump( foo, false )
print( hex_dump( bc ) )

local bar = CompileString( bc, "baz" )
--bar()
```

Here's a log of that code being run twice:

``` text
0000: 1b 4c 4a 01 00 0a 40 52 .LJ...@R
0008: 75 6e 53 74 72 69 6e 67 unString
0010: 2a 00 00 02 00 02 00 04 *.......
0018: 05 1e 02 34 00 00 00 25 ...4...%
0020: 01 01 00 3e 00 02 01 47 ...>...G
0028: 00 01 00 09 74 65 73 74 ....test
0030: 0a 70 72 69 6e 74 01 01 .print..
0038: 01 02 00 00             ....

[ERROR] baz: cannot load malformed bytecode
  1. unknown - baz:0

0000: 1b 4c 4a 01 00 0a 40 52 .LJ...@R
0008: 75 6e 53 74 72 69 6e 67 unString
0010: 2a 00 00 02 00 02 00 04 *.......
0018: 05 1e 02 34 00 00 00 25 ...4...%
0020: 01 01 00 3e 00 02 01 47 ...>...G
0028: 00 01 00 09 74 65 73 74 ....test
0030: 0a 70 72 69 6e 74 01 01 .print..
0038: 01 02 00 00             ....

[ERROR] baz: cannot load incompatible bytecode
  1. unknown - baz:0
```

If `true` is passed for the second parameter of `string.dump` the output is always as below; the "incompatible" message is never used.

``` text
0000: 1b 4c 4a 01 02 22 00 00 .LJ.."..
0008: 02 00 02 00 04 34 00 00 .....4..
0010: 00 25 01 01 00 3e 00 02 .%...>..
0018: 01 47 00 01 00 09 74 65 .G....te
0020: 73 74 0a 70 72 69 6e 74 st.print
0028: 00                      .

[ERROR] baz: cannot load malformed bytecode
  1. unknown - baz:0
```

I would very much like it if this could be corrected so that bytecode can be loaded successfully. If you don't want to support bytecode the error message should at least be changed to be clearer, possibly "loading bytecode is not supported"

See also [this forum thread](http://facepunch.com/showthread.php?t=1278012).

**Comment by Kefta** [comment]
RunString has the same message -- I agree that the message is unclear.

**Comment by NathanX-S** [comment]
Seems like this could be easily closed. Just a little string edit @robotboy655

**Comment by meepen** [comment]
fun fact: it only says malformed bytecode because it uses strlen instead of getting the size of the lua string properly

**Comment by meepen** [comment]
(this also means in the future if there was a possible way to load lua bytecode without null bytes it would be possible but i don't think it is)
