### ISSUE TITLE
.sw.vtx extension not downloaded using resource.AddFile()

### ISSUE THREAD

**Issue by Kuma96** [Facepunch/garrysmod-issues#4351]
### Details
After using resource.AddFile("models/modelname.mdl") in order to download a model via FastDL, .vvd, .dx80.vtx, .dx90.vtx, etc files with the same name are properly downladed, but .sw.vtx files are not added to the download list.

### Steps to reproduce
By setting up a FastDL with any model.

**Comment by robotboy655** [comment]
It's intentional, sw.vtx files are not used by the game, all the default models do not are not shipped with those files.

**Comment by shadowscion** [comment]
@robotboy655 So if I had an addon with thousands of these files I'd be safe in deleting them next time I update it?

**Comment by robotboy655** [comment]
yes
