### ISSUE TITLE
RunConsoleCommand from timer broken

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4355]
I think started happening with early Jan or late Dec update;

RunConsoleCommand seems to do nothing when in timer callback
`timer.Simple(1, function() RunConsoleCommand("changelevel","gm_flatgrass") end)`

Works fine outside of timer.
This is on dedicated server.

Will remove timer for now.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/73556915-ff582900-4458-11ea-83af-d790f94be3e5.png)

Would you say that you are trying to do it on an empty server?

**Comment by thegrb93** [comment]
Oh right, timers don't work when its empty. Lame

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/73557139-5eb63900-4459-11ea-85b2-f2072a5ee22d.png)

**Comment by thegrb93** [comment]
I'll add that to the wiki

**Comment by robotboy655** [comment]
It was already is on it for timer.Create, just wasn't for timer.Simple, which I have already rectified.
