### ISSUE TITLE
Unable to connect to servers with over 4k props

### ISSUE THREAD

**Issue by GranPC** [Facepunch/garrysmod-issues#436]
When you try to connect to a server with too many props, something goes wrong and seemingly random error messages are printed to the console - after which you are disconnected from the server with the reason "Disconnect by user". This is the most prominent one:

Server returned version -26816, expected 24.

Where the version number returned by the server is actually pretty much random every join. I've also seen datatable issues.

I can set up another server to constantly reproduce this, but I believe it's because the first snapshot packet is way too huge or something.

Receiving a full packet update while you are in the server will not cause a disconnect like back in the days of 'reliable snaphsot overflow'.

**Comment by willox** [comment]
TWENTY THIRTEEN
