### ISSUE TITLE
64-bit Branch Crashes

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [Facepunch/garrysmod-issues#4361]
### Details
I own a sandbox server and lately some of my players have been complaining about crashes. All of those who have crashed are on the 64-bit branch and according to the dumps, it's caused by shaderapidx9.dll. I will email the dumps to robotboy655[at]facepunchstudios.com. The issue does not seem limited to a specific brand or model of CPUs or graphics cards.

### Steps to reproduce

1. Switch to the 64-bit branch.
2. Join my Sandbox server.
3. Wait 5-10 minutes.
4. Crash.

**Comment by nazarbaev** [comment]
exactly the same thing

**Comment by pizzadox11** [comment]
maybe its addon related? give a list of all addons and any modules you use so maybe i can help you track it

**Comment by sarry13** [comment]
> maybe its addon related? give a list of all addons and any modules you use so maybe i can help you track it

https://steamcommunity.com/workshop/filedetails/?id=1803708544

**Comment by BLEEPBLOOPforLife** [comment]
-fullwindowsdump doesn't seem to increase the crash dump size, like you said over email @robotboy655. Also, I sent the crash dumps to @willox, as requested by you.

**Comment by BLEEPBLOOPforLife** [comment]
So, this crash seems to be as a result of using TFA CS:O weapons when not all weapons have been downloaded. Crashes occur when an explosion occurs and the player does not have the proper texture downloaded.

According to the addon author:

"We increment the frame of the texture via lua. Source really doesn't like using a frame that doesn't exist and crashes"

**Comment by robotboy655** [comment]
Could the author maybe post their code to reproduce the crash? Or at least link the addon here.

**Comment by BLEEPBLOOPforLife** [comment]
Here is a collection containing the addons in question.

https://steamcommunity.com/sharedfiles/filedetails/?id=1442640920

The issue arises when you don't have all of TFA CS:O Parts 1-4 downloaded and mounted because there are some missing explosive textures. (Ignore the other two addons in the collection.)

**Comment by robotboy655** [comment]
Should be fixed on Dev, and on x64 soon-ish, its not an x64 exclusive crash.
