### ISSUE TITLE
Duplicator fails to load workshop dupes

### ISSUE THREAD

**Issue by Fasteroid** [Facepunch/garrysmod-issues#4362]
![20200202043131_1](https://user-images.githubusercontent.com/29342750/73606165-6bc84a80-4575-11ea-909f-9eaaf8c1cf83.jpg)
`[HTML] asset://garrysmod/html/dupes.html#/list/mine//:1: Uncaught TypeError: dupe.ReceiveVoteInfo is not a function`
As of around two months ago, this started showing up in my console.  I can't get workshop dupes to work, but regular dupes stored locally seem to work fine.  I tried both verifying my game cache and using a friend's (working) copy of `dupes.html`, and neither seem to have done anything.  I know at least one other person experiencing this problem, and it's beginning to become frustrating.

I don't know exactly how to reproduce this.  All I know is Garry's Mod spams this error about 20 times and then doesn't dupe anything.  Guidance in fixing this would be much appreciated, even if it ends up being the case that I'm stupid and missing something obvious.

Thanks!
-Fast

**Comment by robotboy655** [comment]
Your server is out of date, which is what is causing the problem.

https://github.com/Facepunch/garrysmod/search?q=ReceiveVoteInfo&unscoped_q=ReceiveVoteInfo
GMod doesn't called or use `ReceiveVoteInfo`.
