### ISSUE TITLE
SteamUGC update broke addon extraction

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-issues#4363]
Details:
New update seems to have broken gma extraction. When extracting a gma using only gmad.exe and no additional tools it produced file contents with a file size of 0 bytes. Effectivly making it impossible to look inside any addons now and making it very difficult to properly update them

Steps to reproduce
1. Download any addon that was updated after the steamUGC update
2. Attempt to extract it using gmad.exe
3. filesize ends up being 0 bytes for content inside the addon

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/73662830-299e2680-46a5-11ea-9e9a-dba00ab34a82.png)

What addons _exactly_ you are extracting?

**Comment by VaasKahnGrim** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1490547138

This being the addon in question, I've now tried recreating the gma(I'm quite glad I kept a backup from before I updated it) I've tried using the tool that DefyTheRush has made and shared in the discord, I've tried with GMPU and I've even tried using gmad.exe via commandline but same results

**Comment by VaasKahnGrim** [comment]
I figured out the issue, gma header got fucked up. in game addons work fine, just seems the extraction is the only time its an issue

**Comment by robotboy655** [comment]
Are you sure you used `gmad.exe` to **create** the `.gma` file? If so, which platform and which version you used? (64bit one or 32 bit one?)

**Comment by VaasKahnGrim** [comment]
It should be the default branch, tho it seems specifically related to what ever is installed to my laptop.

basically it makes the gma, the gma has the file size expected but in the header the map file was listed as 0 bytes in size. I confirmed this after getting some help from somebody else and then looking and seeing it myself when I opened my gma in a hex editor and dug through the header myself.

Just in case I'll go ahead and upload my gmad.exe
[gmad.zip](https://github.com/Facepunch/garrysmod-issues/files/4157507/gmad.zip)

**Comment by robotboy655** [comment]
No, it's not your `gmad.exe`. If you can still reproduce it, try the `gmad.exe` from dev branch. if you will get an error with it, look for problems in your setup. I can't think of anything that would cause this though.

**Comment by VaasKahnGrim** [comment]
I seem to be unable to figure out how to recreate the issue again, my only guess is maybe another program currently accessing the file. But logicaly that shouldn't happen if gmad.exe is only reading the files and then copying the data into a gma file

**Comment by robotboy655** [comment]
I am going to close this then. gmad.exe was updated to bail if it cannot get proper file size (instead of writing 0) with an error that should help pinpoint the problem if it happens again.
