### ISSUE TITLE
DListView_Column DButton inside PresetEditor

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#4365]
A button behind DListView column never get focus inside PresetEditor (DFrame based) and therefore has no purpose
![gmod_EmBDJ4mS14](https://user-images.githubusercontent.com/6339511/73734326-0f7d4a80-4770-11ea-9cf9-58cb18f75d98.png)
![gmod_uNSP51yTH0](https://user-images.githubusercontent.com/6339511/73734441-3b98cb80-4770-11ea-99b4-d2d953a90af7.png)

It seems to be created as `DListView_Column.Header`, but does not get removed in progress, since it's DoClick function is:
![gmod_9BH14LaOab](https://user-images.githubusercontent.com/6339511/73735666-38064400-4772-11ea-9ac0-b5c7c893a33b.png)

Parent:
![gmod_PnuqIi74MW](https://user-images.githubusercontent.com/6339511/73734492-4b181480-4770-11ea-97b3-f27a16aea7cf.png)

Removing it doesn't seem to impact functionality:
![gmod_50dTuYOWBG](https://user-images.githubusercontent.com/6339511/73734687-9c280880-4770-11ea-847f-240ad31778b8.png)
![gmod_MbQBMqWeKw](https://user-images.githubusercontent.com/6339511/73734691-9cc09f00-4770-11ea-8b8f-6ce89f00753c.png)

However, other use-cases of DListView does not suffer from this issue:
![gmod_ZRImsMJS4W](https://user-images.githubusercontent.com/6339511/73734975-15bff680-4771-11ea-87da-ed45d49b4fe6.png)
![gmod_QV7oNm38mw](https://user-images.githubusercontent.com/6339511/73735038-34be8880-4771-11ea-8eed-9e2799337bc6.png)
![gmod_pscOQOnheo](https://user-images.githubusercontent.com/6339511/73735032-32f4c500-4771-11ea-80c3-11f346099b9a.png)

This is annoying

**Comment by robotboy655** [comment]
The issue turns out to be a bit more interesting.

**Comment by roboderpy** [comment]
i knew it were calling :Init() twice, but had no idea why
