### ISSUE TITLE
SetSortable generates undesirable "DLabel"

### ISSUE THREAD

**Issue by pilot22** [Facepunch/garrysmod-issues#4370]
### Details
![image](https://user-images.githubusercontent.com/43100943/74176734-929f1480-4c38-11ea-85b2-322a46c921aa.png)
As you can see, the dlistview has the property SetSortable(true).
Without it:
![image](https://user-images.githubusercontent.com/43100943/74176792-b6625a80-4c38-11ea-9d4e-c59b130c1109.png)

### Steps to reproduce
Use an DListView like that:
```lua
    local list = vgui.Create("DListView", frame)
    list:SetSortable(false)
    list:SetDrawBackground(false)
    list:SetDataHeight(32)
    list:Dock(FILL)
    list:AddColumn("reporter")
    list:AddColumn("reported_player")
    list:AddColumn("reason")
    list:AddColumn("waiting_time")
    list:AddColumn("claimed")
    list:AddColumn("actions")
```

**Comment by robotboy655** [comment]
That was already fixed like last week.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/b55ce5c06bcccc60daf835e152a5062082cf018b
https://github.com/Facepunch/garrysmod-issues/issues/4365

**Comment by pilot22** [comment]
If this is expected to be applied, this is not in hame

**Comment by pilot22** [comment]
Sorry I didn’t got it. So i need to use DListView_Column to have the SetSortable ?

**Comment by robotboy655** [comment]
Yeah sorry, our build server was broken for a bit, it should get fixed on Dev soon enough. You can apply the fix I linked above yourself.
