### ISSUE TITLE
Workshop isn't able to update file of already deleted addon

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4372]
### Details
I manually subscribed to an addon, uninstalled the addon and the server i'm trying to connect forces me to redownload it, but instead of redownloading it errors and isn't able to redownload the addon, nor mount it.

This is the error message:

Unable to rename C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\cache\workshop\769399970885611931.gma to C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod/cache/workshop/728328781.gma!

### Steps to reproduce
As explained above.

**Comment by robotboy655** [comment]
I couldn't reproduce this, but I have made it mount the old file (`workshop\769399970885611931.gma` in your case) when the rename fails.
