### ISSUE TITLE
Can't download addon added by resource.AddWorkshop("728328781")

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4373]
### Details
My server manually adds aMenu Content to download list.
When entering my server with a clean gmod copy (didn't clear workshop cache outside of gmod folder), it errors and doesn't mount the addon.

WorkshopDL: Failed to read addon file for 'aMenu Content' (728328781)
WorkshopDL: There is no file to mount!

### Steps to reproduce
Guess add a workshop addon to your server which uses the old system.

**Comment by robotboy655** [comment]
I have already tested that exact addon in your last issue, it works fine. Can you check if you actually have the `769399970885611931_legacy.bin` file in your `steamapps/workshop/content/4000/728328781`?

**Comment by mcNuggets1** [comment]
nah thats a different one.
The last one was a map.

**Comment by mcNuggets1** [comment]
The folder 728328781 doesnt exist.

**Comment by robotboy655** [comment]
No it wasn't? (https://github.com/Facepunch/garrysmod-issues/issues/4372 has that exact ID)

Anyway, can you CTRL+F the id `728328781` in your `appworkshop_4000.acf`, do you find it there?

**Comment by mcNuggets1** [comment]
I searched in steamapps/workshop/content/4000 for 728328781 and it didnt exist.

**Comment by robotboy655** [comment]
Open the file `steamapps/workshop/appworkshop_4000.acf ` in a text editor and search for `728328781`.

**Comment by mcNuggets1** [comment]
"728328781"
		{
			"size"		"0"
			"timeupdated"		"1495898664"
			"manifest"		"-1"
			"ugchandle"		"769399970885611931"
		}

**Comment by robotboy655** [comment]
So, the Steam files were tampered with and that is the problem.

**Comment by mcNuggets1** [comment]
I don't know about anything.
I didn't touch anything.

But I deleted cache, download, downlaods, downloadlists previously to save disk space, maybe this made the problem occur.

**Comment by robotboy655** [comment]
Try validating your game, it should also validate Steam content.

**Comment by mcNuggets1** [comment]
Verified, didn't do anything.
Still: WorkshopDL: Failed to read addon file for 'aMenu Content' (728328781)
WorkshopDL: There is no file to mount!


		"728328781"
		{
			"size"		"0"
			"timeupdated"		"1495898664"
			"manifest"		"-1"
			"ugchandle"		"769399970885611931"
		}

		"728328781"
		{
			"manifest"		"-1"
			"ugchandle"		"769399970885611931"
			"timeupdated"		"1495898664"
			"timetouched"		"1581612489"
		}

**Comment by robotboy655** [comment]
Well there's physically nothing we can do from the API to force Steam to recheck/redownload the addon in this case unfortunately. The fact that you got 2 entries for the same addon now is also confusing.

You could try exiting Steam, deleting those 2 blocks and start it back up, but I cannot predict if that will work or what side effects it might have.

Just make sure you don't delete shit from that folder, ever, including any 3rd party programs you might be running.

**Comment by mcNuggets1** [comment]
Cant even remove it.

Failed to read addon 728328781!
Extraction failed.. Oh oh! (C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/amenu_content_728328781.gma)
Addons have changes - remounting
Not loading addon 'addons/amenu_content_728328781.gma' - file doesn't exist
Couldn't mount addon file 'addons/amenu_content_728328781.gma' from 'aMenu Content' (728328781)
Removing bad addon addons/amenu_content_728328781.gma

**Comment by robotboy655** [comment]
...obviously it cant delete files that don't exist.

**Comment by mcNuggets1** [comment]
Got it to work, steam needed a complete restart.
