### ISSUE TITLE
Constant "Starting Lua" Crash

### ISSUE THREAD

**Issue by IanTheMemeMan** [Facepunch/garrysmod-issues#4374]
So, this all started yesterday while I was playing on a sandbox server, when out of the blue, my GMod system completely crashed without even giving me a white screen, I relaunched GMod to face a problem. Every single time I loaded into a server, it would download all the mods and the go to the "Starting Lua" page, then would freeze for about 2 seconds, then crash. I looked at a whole BUNCH of YouTube, and forums to find nothing would work. I have no idea what's going on, and I just want to play GMod again...
[3a47abe8-37f3-41ba-b1a0-6e8707961bd1.txt](https://github.com/Facepunch/garrysmod-issues/files/4200292/3a47abe8-37f3-41ba-b1a0-6e8707961bd1.txt)

Edit: Yes, the game starts completely fine, loads all my mods, and is stable, except of course, when I go into a server.

Edit 2: If you need more crash logs, I can try and find another.

**Comment by IanTheMemeMan** [comment]
Regarding above, to make the crash "crash", you have to pick any server, even singleplayer, launch it, wait for everything to download, then wait for the "Starting Lua" page to pop up, then boom, it freezes, and then fatally crashes.

**Comment by robotboy655** [comment]
You will need to send the .dmp files not the .txt one.

**Comment by IanTheMemeMan** [comment]
"This type of file is not supported"

**Comment by robotboy655** [comment]
You can send it to the email addresses in the README.md of this repository:
https://github.com/Facepunch/garrysmod-issues/blob/master/README.md

**Comment by IanTheMemeMan** [comment]
Alright, it's done. Do you want to email you as well?

**Comment by MagentaIris** [comment]
This issue still persists with the new update, Loading specific maps just outright CTD's the game, namely Minerva, metastasis_1.bsp to be precise.

Was stable a while back but not anymore, Here's a mdmp, just rename the format. I managed to fix a couple of these issues by using an lump editor and removing all the dynamic props and ropes, but even then it still sometimes does itself in.

[hl2_200623_crash_2020_6_25T22_45_44C0.txt](https://github.com/Facepunch/garrysmod-issues/files/4834186/hl2_200623_crash_2020_6_25T22_45_44C0.txt)

**Comment by MagentaIris** [comment]
Canals_13 is crashing due to the new update too.

**Comment by robotboy655** [comment]
None of those HL2 maps crash without any addons.

**Comment by robotboy655** [comment]
The original crash here is the netchannel somehow becoming nullptr.

@MagentaIris Yours is a vphysics crash. Perhaps you have addons overriding default models or something?

**Comment by MagentaIris** [comment]
Having a Fast Headcrab ragdoll on any map, and having the Default HL2 fast headcrab model extracted from base HL2 in your gmod causes it to crash.

Now that's pretty fucked up, i'll look into fixing it personally.

**Comment by robotboy655** [comment]
Thanks, I will see if this is fixable or if we gotta rollback r_flushlod and look for a different fix for vertex CRC error

**Comment by MagentaIris** [comment]
Mayhaps, I tried a couple of recompiles of the normal headcrab with the original qc's and source animations, it seems the Ragdoll animation when playing it in HLMV sometimes just crashes, and of course, if this happens in HLMV, it crashes gmod if you spawn the ragdoll server side but not client side.

Pretty weird.

**Comment by robotboy655** [comment]
So extracting ragdolls from the vpk did not cause any crashes for me, and at first you were claiming it's the physics props that doing the crash, now its ragdolls, the dump you linked shows a vphysics crash, but now you claim it happens in HLMV which doesn't even use vphysics, I don't know what to believe anymore. You are also seemingly the only person having these issues.

**Comment by MagentaIris** [comment]
Yeah i couldn't lock it down to the exact entity, but it was 100% the fast headcrab being a server side ragdoll, Extracting the model from the VPK may have freaked out, After re-extracting it safely the issue isn't there anymore.

Pretty sure that issue can just be ignored now.

**Comment by robotboy655** [comment]
Closing as stale. If the issue persists, please open a new report.

**Comment by Cirexd** [comment]
Just put on 64 bit. You find it under betas, then you just have to launch it as 64 bit. That helped me at least :)
