### ISSUE TITLE
Welded prop_combine_ball crashes game when touching wall and exploding after producing it's bounce sounds.

### ISSUE THREAD

**Issue by Shadowysn** [Facepunch/garrysmod-issues#4376]
### Details
So far, I have only achieved this using my [addon](https://steamcommunity.com/sharedfiles/filedetails/?id=1641305846).

A constraint is used to emulate the Super Gravity Gun's pickup system, also making use of _SimulateGravGunPickup_ and _SimulateGravGunDrop_.
The crash occurs if a combine ball is held against a wall using the custom gun, and emits 'bouncing sounds'. It happens a second after the glitched ball explodes, coincidentally lining up with when my SCGG is supposed to drop the ball. _SimulateGravGunDrop_ maybe?

You can look at the SCGG's code [here](https://github.com/Shadowysn/GMOD_SCGG_Fixed/blob/master/lua/weapons/weapon_superphyscannon/shared.lua).

### Steps to reproduce
_This can take multiple attempts to reproduce._

**Step 1. ** Equip the custom SCGG.
**Step 2. ** Spawn a ball using the AR2's altfire.
**Step 3. ** Grab the ball using the SCGG and hold it, and yourself, to lean against a wall.
**Step 4. ** Wait for it to explode. If bouncing sounds occur for at least 2 or more times, you are guaranteed to crash. Otherwise, repeat steps 2 and 3.

EDIT: I've attached a crash log into this zip file.
[hl2_200125_crash_2020_2_15T6_54_41C0.zip](https://github.com/Facepunch/garrysmod-issues/files/4209570/hl2_200125_crash_2020_2_15T6_54_41C0.zip)

**Comment by Shadowysn** [comment]
Well, atleast I tried. Don't really update my stuff nowadays.

**Comment by thegrb93** [comment]
Can you reproduce the issue by just simply welding a ball with the weld too? I feel like the addon is doing something else that's causing the crash. Otherwise the constraint library will need to block constraints to these entities (if it can't be fixed. probably will block it meanwhile to stop minges). Will test myself later.

**Comment by robotboy655** [comment]
The only thing I can reproduce with your addon is this:
```
[ERROR] addons/sgg/lua/weapons/weapon_superphyscannon/shared.lua:1802: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. Drop - addons/sgg/lua/weapons/weapon_superphyscannon/shared.lua:1802
    3. unknown - addons/sgg/lua/weapons/weapon_superphyscannon/shared.lua:683

```

**Comment by robotboy655** [comment]
Ok after a while of fucking with walls it should be fixed on Dev.
