### ISSUE TITLE
Running console command "buildcubemaps" crashes game when used on main menu

### ISSUE THREAD

**Issue by Stiffy360** [Facepunch/garrysmod-issues#4377]
To reproduce this issue, simply run the command "buildcubemaps" while on the main menu and the game will instantly crash.

I don't expect this command to ever work on the main menu for obvious reasons, but it's still something that instantly crashes the game, so some kind of error handling to prevent that would be great.

**Comment by ExtReMLapin** [comment]
when are we getting support back for bsp menu
