### ISSUE TITLE
SurfacePropertyData haven't all fields

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4378]
### Details
I tried get footsteps sound for specific surface and i see that table dont have left and right foot sounds. But they are in surfaceproperties.txt

I use `concrete` for example
```Lua
local surface = --`concrete` surface id
PrintTable(util.GetSurfaceData(surface))
```
I get 
![image](https://user-images.githubusercontent.com/49488893/74613512-23d22780-5120-11ea-97b4-335a4660b903.png)

In surfaceproperties.txt
![image](https://user-images.githubusercontent.com/49488893/74613533-4e23e500-5120-11ea-8fe1-5dff9138016e.png)

**Comment by robotboy655** [comment]
But it is there for me?
![image](https://user-images.githubusercontent.com/3299036/74675769-f1c2d300-51bc-11ea-85b0-b976982417a3.png)

Using the example code from https://wiki.facepunch.com/gmod/util.GetSurfaceData

**Comment by ShadowBonnieRUS** [comment]
![image](https://user-images.githubusercontent.com/49488893/74717757-fe3d3f00-5241-11ea-9977-d4b3c16046d6.png)
triend with `surfprop` like you on flatgrass

**Comment by robotboy655** [comment]
Should be fixed.
