### ISSUE TITLE
User cannot download freshly uploaded addon

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4379]
### Details
Not loading addon 'C:\Program Files (x86)\Steam\steamapps\workshop\content\4000\2000240781/mg_m9k_content.gma' - addon header invalid
Couldn't mount addon file 'C:\Program Files (x86)\Steam\steamapps\workshop\content\4000\2000240781/mg_m9k_content.gma' from 'Modern Gaming - M9K Inhalte' (2000240781)

### Steps to reproduce
Automatic downloading and downloading via workshop results in this FOR THE specific user.

**Comment by robotboy655** [comment]
Do we gotta do through this again?

Tell em to verify game cache integrity of Garry's Mod.

**Comment by mcNuggets1** [comment]
This doens't work they have to manually remove the addon from the appworkshop_4000 file.
But this error in the first place never should have occured, because the addon is newly uploaded and secondly the user downloaded it for the first time, well atleast they tried doing it while connecting to the server.

**Comment by robotboy655** [comment]
I got an email with this exact error and verifying the game helped them. Just try before dismissing it and stop fucking with Steam files how many times I gotta repeat this?

**Comment by mcNuggets1** [comment]
I never tampered the steam files until you told me too, because verifying didn't work.
This bug appears to happen quite frequently now, nearly a quarter of my player base is affected and it's happening even with freshly added addons.

**Comment by robotboy655** [comment]
Well if Steam fails to download the file properly, there's nothing we can do about it. Verifying the game cache is supposed to fix this unless you fuck with the files. (Or Steam fucks something up even more?)

The error they are getting means the first four bytes are not ASCII `GMAD`. I cannot say anything else without seeing the file, logs, etc,etc or a way to reproduce it on demand.
