### ISSUE TITLE
PVS issues recently popped up, happens in vanilla gmod with no addons.

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-issues#4380]
So I first noticed this when my world portal entities stopped working propperly on my server, later I noticed the same behavior with the mirror in gm_construct.

![gm_construct0008](https://user-images.githubusercontent.com/29955667/74692224-e1562c80-51ab-11ea-8c2f-6faea2b06e44.jpg)

**Comment by robotboy655** [comment]
Have you considered its your configuration? You can use debug_dump to see all the changed convars

**Comment by VaasKahnGrim** [comment]
I highly doubt it, I litterally setup a seperate install of the game just to figure out weird issues like this happening

**Comment by thegrb93** [comment]
Clear your cfg and verify integrity of game cache. I think this would be a lot more widespread of an issue if the vanilla build had these issues.

**Comment by VaasKahnGrim** [comment]
cfg is clear and the thing is technically a fresh install of the game. its also kept disconnected from the internet to ensure no addon BS happens

**Comment by robotboy655** [comment]
Would it hurt you attach the `debug_dump.txt` (created via `debug_dump` console command)?
Can you maybe at least tell us which beta branch you are on? have you maybe tried a different beta branch? No beta branch? Have you tried running the `FactoryReset.bat` file?

**Comment by VaasKahnGrim** [comment]
I only use default branch since thats what most players will be using already, and I'll try and get aa debug_dump.txt tonight for you
