### ISSUE TITLE
Apply Multiple Skins to a Model?

### ISSUE THREAD

**Issue by cwca99** [Facepunch/garrysmod-issues#4381]
I'm not sure if this is the right place to ask this question but what the heck.
     I'm in the process of making a model. Its a soldier, and I want to give the feller different 'skins' for his uniform rather than creating lots of different models for the same purpose. The question is, how do I do this?
     I've looked at other models that I know have different 'skins', and in their QC files they just have multiple "$cdmaterials 'blah/blah/'" lines. Being the genius that I am, I copied this feat only to have it not work in the game. So I'm guessing there's more to it.
     Any help would be appreciated.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
