### ISSUE TITLE
HSVToColor and HSLToColor freezes with large hue

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4382]
The hue should be `% 360` anyway since >360 hue makes it misbehave.

**Comment by thegrb93** [comment]
Don't know if it matters, but on x64 branch.

**Comment by thegrb93** [comment]
Also this function returns a table rather than a Color

**Comment by thegrb93** [comment]
HSLToColor also freezes with extreme values.

**Comment by Kefta** [comment]
Same as the table.insert crash probably; it's from attempting to convert inf to an int.

**Comment by thegrb93** [comment]
@Kefta you better watch out, you're starting to sound like Verideth lol

Other functions that take int do not freeze with inf so this makes no sense.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
