### ISSUE TITLE
Server's report Unlisted Steam Workshop Collections as inaccessible.

### ISSUE THREAD

**Issue by viral32111** [Facepunch/garrysmod-issues#4384]
### Details
Servers don't seem to be able to understand "Unlisted" Steam Workshop Collections. As an unlisted item, it's only hidden through searches and profile lookups. (I think) it should still be accessible through API lookups, therefor servers likely check the visibility status and if it's anything but public it automatically stops the workshop addons from being downloaded/mounted. I even set my Steam Web API Key in the `-authkey` startup option to see if having my API key would make it visible to the server, but it still results in the same issue. ([this](https://steamcommunity.com/sharedfiles/filedetails/?id=1125031047) is the workshop collection, as you can see it's publicly viewable by everyone but if you try to find it under my collections it won't appear as it's unlisted. [Screenshot](https://i.imgur.com/5o9lgY1.jpg))

Server version: 2019.11.12.
Branch: Default (for servers).

### Steps to reproduce
1. Create a Steam Workshop Collection.
2. Add a few addons to it.
3. Set the visibility status to "Unlisted".
4. Copy the Collection ID and put it inside the argument for the `host_workshop_collection` convar (e.g. `host_workshop_collection "123456789"`.
5. Start the server, WS should report the item as not public ([Screenshot](https://i.imgur.com/KJt6Xno.jpg)).

**Comment by robotboy655** [comment]
Should be fixed on Dev.
