### ISSUE TITLE
Entity:StartLoopingSound() doesn't work

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4386]
### Details
On x86-64 branch, tested on 32-bit and 64-bit Gmod launches.

Tried an .ogg file to see if it would do anything different but same thing.

### Steps to reproduce
```lua
self.ScanningSoundID = self:StartLoopingSound("npc/turret_floor/ping.wav")
print(self.ScanningSoundID)
```
This doesn't print `-1`, and prints a normal looping sound ID, but the sound plays once and doesn't play again.

Nothing else gets printed to console other than that.

**Comment by robotboy655** [comment]
Tried checking the wiki before complaining? 
![image](https://user-images.githubusercontent.com/3299036/75047663-d236ed80-54cf-11ea-9700-175cd71e5002.png)
