### ISSUE TITLE
Edge case in invalid URLs

### ISSUE THREAD

**Issue by Cynosphere** [Facepunch/garrysmod-issues#4387]
`https://twemoji.maxcdn.com/v/latest/72x72/1f910.png` triggers the "invalid url" error when fetched when it shouldn't. Other URLs from this domain and path style do not trigger this as far as I know.

**Comment by robotboy655** [comment]
There really isn't much we can do about it while we use Steam's stuff, it will likely get resolved with x64 going live,

**Comment by joeyjumper94** [comment]
may be related to https://github.com/Facepunch/garrysmod-issues/issues/4133
as i said in there, it seems to think the url is a local host due to it containing 
> 10.
