### ISSUE TITLE
After gmod update contents not download

### ISSUE THREAD

**Issue by azuspl** [Facepunch/garrysmod-issues#4390]
Hey!
After new gmod update, i uploaded new contents and map to workshop
And now players downloading my contents (content have 1,2gb) and then they have still errors
After download my new added map from workshop, players still have missing map

In console all players (with me) have something like this:
`Couldn't mount addon file 'C:\TF2\steamapps\workshop\content\4000\756053909/756053909_via_crowbar.gma' from 'Breach 2: Remaster #1' (756053909)
Not loading addon 'C:\TF2\steamapps\workshop\content\4000\1986876323/new_item_via_crowbar.gma' - addon header invalid
Couldn't mount addon file 'C:\TF2\steamapps\workshop\content\4000\1986876323/new_item_via_crowbar.gma' from 'br2remaster3fixed' (1986876323)
Not loading addon 'C:\TF2\steamapps\workshop\content\4000\756053909/756053909_via_crowbar.gma' - addon header invalid
Couldn't mount addon file 'C:\TF2\steamapps\workshop\content\4000\756053909/756053909_via_crowbar.gma' from 'Breach 2: Remaster #1' (756053909)
Not loading addon 'C:\TF2\steamapps\workshop\content\4000\1986876323/new_item_via_crowbar.gma' - addon header invalid
Couldn't mount addon file 'C:\TF2\steamapps\workshop\content\4000\1986876323/new_item_via_crowbar.gma' from 'br2remaster3fixed' (1986876323)`

Before gmod update, all contents and map works properly, now after adding new map or content, contents, maps not load for players
I tested on all gmod versions with my players, and we see this problem in all versions

**Comment by robotboy655** [comment]
We do not support usage of 3rd party tools to upload content to Steam Workshop.

You can try verifying game cache of GMod in Steam, but if that doesn't work, then there's nothing I can do for you due to you using Crowbar to upload content to the workshop.
