### ISSUE TITLE
Downloading addons from server is a bit broken.

### ISSUE THREAD

**Issue by CultistKun** [Facepunch/garrysmod-issues#4391]
So many ppl have already reported this issue, so nothing new here. While sometimes it feels like a problem not with the new workshop system but rather the way ppl upload their addons, its not true or at least not completly true.  I've test this problem myself and this is what I got.

_Here is what was done before joining_:
1) I disabled all my subscribed addons.
2) Deleated dowload(s)\Cache folders in my GM.
3) Deleated workshop 4000 folder.
4) Game set to beta patch x64-x86 (ppl I've invited to test it with me didnt have it)

_What my server had and what were thouse addons:_
1) Around 6 addons uploaded by me, using new Gmad and GMpublish through the CMD. Official ones from bin folder.
2) Addons have different sizes, few over old limit, few below old limit.
3) All addons have obscure names. By that I mean only windows symbols, without latters or numbers.
4) .GMA files which were uloaded had name of out.gma

_What was the result_:
1) Out of 6 addons, only 3 were successfully downloaded
2) Few of them were the ones which are ~1gb and one was even below old file size limit.

_What I've tryed after that._
1) Restart gmod and rejoin (didnt help)
2) Deleated dowload(s)\Cache folders in my GM. (didnt help)
3) **Verify game Cache**  (Did help)

After veryfing, gmod dowloaded thouse addons which were missing and it fixed the problem.

Also I want to mention, that I've invited other people to try it out and it was a bit random for them, few of them couldn't even download the map, while others had all addons downloaded except 1 or 2.

So yeah, problem exists, even if you upload everything correctly and even if you have your gmod crisp and clear from garbage.

**Comment by azuspl** [comment]
Yeah, players on my server too have this problem with contents, map

**Comment by robotboy655** [comment]
> Deleated workshop 4000 folder.

**DO NOT DELETE THE GODDAMN STEAM FILES.**

**Comment by CultistKun** [comment]
> > Deleated workshop 4000 folder.
> 
> **DO NOT DELETE THE GODDAMN STEAM FILES.**

Folder gets automatically created afterwards, also even after deleting it few addons were dowloaded.

But lets pretend it coased some issues, alright. Other ppl who I've invited didnt delete it, and they still had the same problems. All they did is unsubscribed from everything and clear GM folders, but didnt touch the 4000 folder.

**Comment by robotboy655** [comment]
The folder may get recreated but the files won't be redownloaded, we already had many reports of this, and I tested it myself. I cannot help you or anyone who messes with Steam files.

If you think it will happen to be if I join your server, sure, send me the IP address and I will try.

**Comment by CultistKun** [comment]
> The folder may get recreated but the files won't be redownloaded, we already had many reports of this, and I tested it myself. I cannot help you or anyone who messes with Steam files.
> 
> If you think it will happen to be if I join your server, sure, send me the IP address and I will try.

Alright, what the best way to sent the IP

**Comment by robotboy655** [comment]
My email is on my profile and in the readme of this repo.

**Comment by CultistKun** [comment]
> My email is on my profile and in the readme of this repo.

Alright it should be on your email now.

**Comment by robotboy655** [comment]
Unfortunately my internet connection is not good enough to download all of the addons in on go:
![image](https://user-images.githubusercontent.com/3299036/75183484-5517ac80-574b-11ea-8fb3-131d3cfb8cd5.png)

But they do seem to work properly other than that. If you are actually looking to be helpful, send console logs of affected people.

**Comment by CultistKun** [comment]
Here is what we got asking one guy who never joined our sever before

![opera_YigOtdecsY](https://user-images.githubusercontent.com/27511187/75187359-f5290200-575a-11ea-91a6-a9cd47581d95.png)

**Comment by robotboy655** [comment]
Ok I can see it happen for those failed downloads, but I don't see why it would, GMod never even touches the files unless they are fully downloaded, so it has to be a problem with Steam.

Perhaps we shouldn't bail if the download feels slow.

**Comment by azuspl** [comment]
Yeah, on my servers, players too have these problems
This problem is since month

**Comment by CultistKun** [comment]
> Ok I can see it happen for those failed downloads, but I don't see why it would, GMod never even touches the files unless they are fully downloaded, so it has to be a problem with Steam.
> 
> Perhaps we shouldn't bail if the download feels slow.

Alright seems like a found one major thing. 

When you asked to give you a console screen, I desided to ones again clear my addons, and give you my log. But no luck, I was always dropping with missing map and I wasnt able to dowload it, at all.

So I went to workshop, and sub to our map (it didnt dowload) and then I unsub from it and after that tryed to connect to the server. And it downloaded it.

In otherwords, it feels like when you downloading server content for GM its the same as if you are subscribe to thouse addons and if you at any state fail to download them during the loading, it simply wont start dowloading them for you because it would think that you already have them installed and subscribed to. 

Thats why veryfing cache fixes it, because it checks your subscriptions and if filed are missing it will dowload them and the same reason un-subing works, because GM stops thinking that this addon is already installed.

**Comment by CultistKun** [comment]
Yeah this is the problem. I started game, subed to all addons in the collection (without downloading them) un-sub from them, restarted the game and tried to connect and it dowloaded all out addons and skiped the ones which were in server dowloading list but from which I didnt sub\unsub.

**Comment by robotboy655** [comment]
I think I found an issue with the stuck download detection and will resolve it soon. This still won't fix Steam fucking up the .gma files, but it shouldn't try to go to the next download after a minute of trying to download the current file.

Basically it should work better on Dev and x64 beta branches within an hour.

Also I really don't appreciate your black image/no description/no title addons not being at least in the servercontent category. I'd even say that goes against our Workshop rules.
