### ISSUE TITLE
PostDraw2DSkyBox doesn't work in x64 with any zFar value

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#4398]
### Details
The hook PostDraw2DSkyBox doesn't render or get called in the x64 branch.

### Steps to reproduce
You can reproduce the problem with any PostDraw2DSkyBox hook.
`hook.Add("PostDraw2DSkyBox", "ExampleHook", function() print("Running") end`
or if you want visually
`local Mat = Material( "dev/graygrid" )
hook.Add("PostDraw2DSkyBox", "ExampleHook", function()
    render.OverrideDepthEnable( true, false )
    cam.Start3D( Vector( 0, 0, 0 ), EyeAngles() )
        render.SetMaterial( Mat )
        render.DrawQuadEasy( Vector(1,0,0) * 200, Vector(-1,0,0), 64, 64, Color(255,255,255), 0 )
    cam.End3D()
    render.OverrideDepthEnable( false, false )
end)`

**Comment by robotboy655** [comment]
It does work on my end and your second example produces this:
![image](https://user-images.githubusercontent.com/3299036/75568421-eb094b00-5a5b-11ea-85e3-dc2f9f4f250f.png)

`hook.Add("PostDraw2DSkyBox", "ExampleHook", function() print("Running", jit.arch) end )`

**Comment by Nak2** [comment]
After doing some testing, I've come to the conclusion that it is the farZ in cam.Start3D that causes the problems.
Try: `cam.Start3D( Vector( 0, 0, 0 ), EyeAngles() ,nil,nil,nil,nil,nil,0,32000 )` and the box shouldn't render anymore.

**Comment by robotboy655** [comment]
it is infact the nearZ value when you set it to 0, which you shouldn't do.

**Comment by Nak2** [comment]
It somehow works without problems on the x32 version and if you leave farZ nil, nearZ can be any value without problems.

**Comment by robotboy655** [comment]
If you don't give both farZ and nearZ, neither work, unless you use `cam.Start` directly.

**Comment by Nak2** [comment]
I see, thanks for taking a look. 
I'll update the wiki with the info.
