### ISSUE TITLE
surface.DrawPoly crashes when no table provided

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4399]
### Details
surface.DrawPoly crashes if not table was provided.
I am aware it spews DevMsg but it should either not crash or spew the lua_error
`dev`, Win 64, 200227, .mdmp exists

### Steps to reproduce
```lua
hook.Add("PostDrawOpaqueRenderables","crash",function()
    surface.DrawPoly()
end)
```
Run in the console and wait for console buffer fill. (around 15 seconds of opened console)

**Comment by robotboy655** [comment]
Apparently you found yet another problem with RichText.

**Comment by GitSparTV** [comment]
Wow, I see no connection between them, how is that possible? :0

**Comment by robotboy655** [comment]
`surface.DrawPoly` with no arguments does nothing after printing a warning, that warning however had no newlines, and RichText with no format changes (i.e. the same color for every message) and no newlines and A LOT of text will crash the game.
