### ISSUE TITLE
Localization for Kill Names Issue

### ISSUE THREAD

**Issue by d10sfan** [Facepunch/garrysmod-issues#44]
In Gmod, when the kill messages come up, they're saying things like #npc_manhack or #npc_combine_s instead of Manhack and Combine Soldier. 

It looks like this is the file that contains those: GarrysMod/garrysmod/resource/language/npc-ents_english.txt

**Comment by Bo98** [comment]
To put it simply any string in `npc-ents_english.txt`, `sandbox-cleanup_english.txt` or `sandbox-settings_english.txt` does not work properly on OS X and Linux (`sandbox-undo_english.txt` works fine).

**Comment by robotboy655** [comment]
This should be fixed on Dev beta.
