### ISSUE TITLE
ManipulateBone don't work with players.

### ISSUE THREAD

**Issue by Heyter** [Facepunch/garrysmod-issues#4402]
### Details
ManipulateBoneAngles and ManipulateBonePosition doesn't work with bone fingers.

Branch: x86-64
OS: Windows 10
Tested on x86 result same.

Video: https://dropmefiles.com/N8zf1

### Steps to reproduce
Setup pac3 and change angles or position bone fingers.

code: https://hastebin.com/jojibakila.cs

**Comment by robotboy655** [comment]
It does, it is simply your model quality setting.
