### ISSUE TITLE
Garry's Mod (64-bit) trying to access Documents folder.

### ISSUE THREAD

**Issue by viral32111** [Facepunch/garrysmod-issues#4404]
(I'm not sure if this is actually a bug or not, but it seems very strange which is why I'm reporting it.)

### Details
I recently turned on Controlled Folder Access in Windows Defender and realised every time I launch Garry's Mod, the game would attempt to access the Documents folder of the current user (specifically `%userprofile%/Documents/Downloads`). This happens on the 64-bit (`x86_64`) branch, not the default branch as far as I can tell from testing. I had no workshop or legacy addons installed while testing, just a barebones Garry's Mod installation.

### Steps to reproduce
1. Switch to the 64-bit branch
2. Turn on Windows Defender's Controlled Folder Access (or use another folder access watching program)
3. Load Garry's Mod - 64-bit
4. You should get a notification similar to the screenshots below.

![Notification](https://user-images.githubusercontent.com/19510403/75688871-209a7800-5c98-11ea-9051-b01ed54a7fc2.png)
![Protection History](https://user-images.githubusercontent.com/19510403/75688861-1f694b00-5c98-11ea-88bd-3008f6d2bc6a.png)

**Comment by willox** [comment]
Should be fixed by the end of tomorrow. It's only creating the directory, so nothing will be placed in there by GMod.
