### ISSUE TITLE
NULL ragdoll passing global IsValid() checks and crashing clients

### ISSUE THREAD

**Issue by minin43** [Facepunch/garrysmod-issues#4405]
### Details
Running Garry's Mod v. 2020.01.25, Source Engine 24 (build 7737), release version.
Playing on a custom gamemode. 

Client is crashing to desktop. I have multiple crash logs available should they be needed.
Code causing the crash:
`timer.Simple( dTime + 2.5, function()
    if ragdoll ~= NULL then
        SafeRemoveEntity( ragdoll )
    end
end)`

Lua Stack Traces in the crash dump has this:
  Client
    0. Remove - [C]:-1
      1. SafeRemoveEntity - lua/includes/util.lua:221
        2. (null) - addons/nzombies/gamemodes/nzombies/gamemode/ragdoll/sh_zombierags.lua:42
(line 42 is SafeRemoveEntity())

Custom gamemode is Zet0r's nZombies gamemode, found here: https://github.com/Zet0rz/nzombies. This crash problem is a well-known bug in the community. Temporary work-arounds have been to disable ragdolls. The crashing itself occurs intermittently, and seems to be worse on some maps than others (dunno why).

**Comment by thegrb93** [comment]
You might also specify the class of ragdoll it is

**Comment by robotboy655** [comment]
>I have multiple crash logs available should they be needed.

So where are they?

**Comment by GitSparTV** [comment]
Rubat, I told him to say only that they exist. In README it says not to post here. But I forgot it say to email them instantly, sorry.
> If you are going to post crash dumps (.mdmp or .dmp files), please email them to robotboy655@facepunchstudios.com or willox@facepunchstudios.com rather than linking to them from your issue.

**Comment by willox** [comment]
why do you think the ragdoll is null?

**Comment by minin43** [comment]
I've sent the latest crash dump to robotboy655@facepunchstudios.com

**Comment by robotboy655** [comment]
I don't see in that code any reference to `ClientsideRagdoll` function, yet the crash dump specifically references `C_ClientRagdoll` being deleted by crazy physics.

There's definitely a crash problem with `ClientsideRagdoll` being deleted by crazy physics.

**Comment by thegrb93** [comment]
Are they death ragdolls?

**Comment by robotboy655** [comment]
No, that would be HL2MP ragdolls.

**Comment by minin43** [comment]
For full disclosure, if it wasn't clear: **I edited the gamemode's default line** of SafeRemoveEntityDelayed into the what I posted in the initial comment. **Previous crash messages did not reference a specific line in the Lua stack trace** and looked like:
`-Lua Stack Traces-
  Client
    0. Remove - [C]:-1
      1. SafeRemoveEntity - lua/includes/util.lua:221
        2. (null) - lua/includes/util.lua:232`

It was only after I edited that code that the Lua Stack Traces gave me line 42.

Is there anything else you need from me, or will this be put down as "bug to fix in a future update"? Or is it something on my/the gamemode's end?

**Comment by robotboy655** [comment]
It might be fixed on Dev branch. I fixed a crazy physics related crash, which might be the cause of your crashes.

If you can, please try running Dev branch **clients** on your server and seeing if the problem goes away.

**Comment by minin43** [comment]
I'll give it a go here soon, and report back if I run into the issue

**Comment by minin43** [comment]
Due to the inconsistent nature of the bug, it **appears** the fix on the Dev branch **may** have solved the problem. I didn't run into it, and the second person I got to test said they experienced no crashing (it could just be a coincidence, it could be the problem is fixed).

For now, I'll close the issue. If I continue running into it post-March-update, I'll re-open this thread.
