### ISSUE TITLE
steamworks.RequestPlayerInfo callback doesn't get called

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4406]
### Details
steamworks.RequestPlayerInfo works, but the callback never gets called.

x86-64 64-bit.

### Steps to reproduce
```lua
local steamid64 = "76561198040894045"
print("1", steamworks.GetPlayerName(steamid64))

steamworks.RequestPlayerInfo(steamid64, function(steamName)
    print("2", steamName)
end)

timer.Simple(3, function()
    print("3", steamworks.GetPlayerName(steamid64))
end)
```

**Comment by robotboy655** [comment]
It does work?
![image](https://user-images.githubusercontent.com/3299036/75813447-ad2c5f80-5d98-11ea-8b6a-f6b773f7ec16.png)

**Comment by WilliamVenner** [comment]
Wtf. Guess I needed to restart my game.
