### ISSUE TITLE
Lines in kick message

### ISSUE THREAD

**Issue by michak89** [Facepunch/garrysmod-issues#4411]
Good day
Last time I tried to modify my server ban message (I'm using ulx which uses :kick(reason) to display ban message) and found out that long kick reasons do not display correctly:
![hl2_j7djSbTuDg](https://user-images.githubusercontent.com/40716529/76233841-1a247700-6229-11ea-8419-c7448a84e102.png)

Kick reason can only display 22 lines of text while text box scales to all lines. Would it be possible to increase the number of displayed lines?

:question: 

Edit: Screen was taken on clean gmod, kicked by :Kick() function, not ulx.

**Comment by GitSparTV** [comment]
The bigger problem is the limit of the kick message. Especially with Cyrillic characters

**Comment by robotboy655** [comment]
Should be fixed on Dev.
