### ISSUE TITLE
game.MountGMA return true, {} (empty table) when GMA is mounted second (or more) time

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4412]
I know, someone changed behavior of GMA mount (e.g.)

```
Addon 'data/pac3_cache/downloads/4186165812.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/4186165812.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/3705727011.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/3705727011.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/2235994233.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/3378368349.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/3378368349.dat' is already mounted, ignoring...
Addon 'data/pac3_cache/downloads/3378368349.dat' is already mounted, ignoring...
```

But new behavior create issues. One of them is that on second and further mount attempts filelist returned from game.MountGMA() is empty.

Please review new behavior (i like that it doesn't mount the same file for second time, but it should return cached table of files inside that GMA), thank you.

Game branch: x64
![gmod_mRqbFm6u24](https://user-images.githubusercontent.com/6339511/76270415-c73dd480-62a7-11ea-9f61-94ec01650b00.png)

**Comment by robotboy655** [comment]
Don't know why the F PAC3 has its own cache, but this really isn't something that can happen due to how data is stored internally, so I have to disable this for MountGMA

**Comment by DBotThePony** [comment]
Pac3 has cache for **zip** archives with models. When you specify zip archive (without compression) as model path, it download the said archive and reassemble it as gma file and write it to cache.

**Comment by ExtReMLapin** [comment]
stop spamming github with your pony shit
