### ISSUE TITLE
DHTML related crashes on macOS x64 branch

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-issues#4416]
### Details

I am on the macOS x64 branch, version `2020.03.14`. 

I am writing an addon that is JavaScript heavy and whenever the DHTML panel is created my game crashes now. Because I depend on some third party dependencies that make it into the static bundle, I'm having difficulty tracking down what's causing the crash. 

This is a regression. This was not happening on prior versions of the x64 branch.

I tried to track things down with the MetaStruct dump analyzer but that is throwing an exception when I try to upload my dumps. If I simply instantiate a regular DHTML panel and open https://google.com, a crash does not occur.

See my crash dumps: [dumps.zip](https://github.com/Facepunch/garrysmod-issues/files/4338799/dumps.zip)

Hoping folks can help unblock my investigation. Also, I'll try to test on a Windows VM later today.

### Steps to reproduce
TBD.

**Comment by willox** [comment]
I'm able to reproduce this thanks to the crash dumps, no further information required.
