### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Rami-Pastrami** [Facepunch/garrysmod-issues#4418]
### Details
Server running on linux does not start: Console spammed with "Segmentation fault" error

Full output:

Segmentation fault
Add "-debug" to the /serverdata/serverfiles/srcds_run command line to generate a debug.log to help with solving this problem
Mon 16 Mar 2020 09:50:39 PM EDT: Server restart in 10 seconds
tcmalloc: large alloc 4289052672 bytes == (nil) @
tcmalloc: large alloc 4289052672 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4289052672 bytes == (nil) @
Segmentation fault
Add "-debug" to the /serverdata/serverfiles/srcds_run command line to generate a debug.log to help with solving this problem
Mon 16 Mar 2020 09:50:51 PM EDT: Server restart in 10 seconds
tcmalloc: large alloc 4288200704 bytes == (nil) @
tcmalloc: large alloc 4288200704 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4288200704 bytes == (nil) @
Segmentation fault
Add "-debug" to the /serverdata/serverfiles/srcds_run command line to generate a debug.log to help with solving this problem
Mon 16 Mar 2020 09:51:04 PM EDT: Server restart in 10 seconds
tcmalloc: large alloc 4288200704 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4288200704 bytes == (nil) @
Segmentation fault
Add "-debug" to the /serverdata/serverfiles/srcds_run command line to generate a debug.log to help with solving this problem
Mon 16 Mar 2020 09:51:04 PM EDT: Server restart in 10 seconds
tcmalloc: large alloc 4292902912 bytes == (nil) @
tcmalloc: large alloc 4292902912 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4292902912 bytes == (nil) @

(loops)

### Steps to reproduce
Install Gmod Server via SteamCMD on a linux system (no addons or anything else)
When starting receive this error

**Comment by Verideth** [comment]
How did you install it? That's allocating wayyy too much bytes. Especially for concurrency. Yikes.

**Comment by doggogoesbork** [comment]
Hey, sorry for the delay.

unfortunately, I dont think -debug is going to be very helpful....

Server output:

`Connecting anonymously to Steam Public...Loaded client id: 2525591099655688901
Listening for IPv4 broadcast on: 27036
Logged in OK
Waiting for user info...OK
Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Update state (0x5) validating, progress: 10.58 (242227499 / 2288547467)
Update state (0x5) validating, progress: 35.81 (819455096 / 2288547467)
Update state (0x5) validating, progress: 60.74 (1389998773 / 2288547467)
Update state (0x5) validating, progress: 84.71 (1938682511 / 2288547467)
Success! App '232330' fully installed.
WARNING: No map specified! Defaulting to gm_construct
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
/opt/garrysmod/srcds_run: 182: ulimit: error setting limit (Operation not permitted)
Server will auto-restart if there is a crash.
tcmalloc: large alloc 4287209472 bytes == (nil) @
tcmalloc: large alloc 4287209472 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4287209472 bytes == (nil) @
Segmentation fault
cat: hlds.1.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Wed Apr 1 23:32:35 America 2020: Server restart in 10 seconds
tcmalloc: large alloc 4293156864 bytes == (nil) @
tcmalloc: large alloc 4293156864 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4293156864 bytes == (nil) @
Segmentation fault
cat: hlds.1.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Wed Apr 1 23:32:47 America 2020: Server restart in 10 seconds
tcmalloc: large alloc 4287700992 bytes == (nil) @
tcmalloc: large alloc 4287700992 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4287700992 bytes == (nil) @
Segmentation fault
cat: hlds.1.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Wed Apr 1 23:33:00 America 2020: Server restart in 10 seconds
tcmalloc: large alloc 4287700992 bytes == (nil) @
Setting breakpad minidump AppID = 4000
tcmalloc: large alloc 4287700992 bytes == (nil) @
Segmentation fault`

Log attached:

[debug.log](https://github.com/Facepunch/garrysmod-issues/files/4418105/debug.log)

**Comment by doggogoesbork** [comment]
Anything Else I can provide?

**Comment by robotboy655** [comment]
Closing as stale. If the issue persists, please open a new report. The issue likely is/was with your particular Linux install. The dedicated server obviously works for most people, and I have tested it without addons on ubuntu 21 with no issues.

**Comment by EricZhang456** [comment]
I encountered this issue with setting up my GMod server today. This error seems to be caused by SourceMod. When I uninstalled SourceMod from my server I don't get this error anymore.
