### ISSUE TITLE
Error in x86-64 (spawnmenu)

### ISSUE THREAD

**Issue by AlphaS-code** [Facepunch/garrysmod-issues#4420]
### Details
Hello! Bad news, i have some errors in x86-64 build = )

I just join to server.

![image](https://user-images.githubusercontent.com/26285012/76976226-c0b4fa00-6944-11ea-8c3b-048b00107085.png)
![image](https://user-images.githubusercontent.com/26285012/76976467-096cb300-6945-11ea-9817-7573f5be8c58.png)

[console.txt](https://github.com/Facepunch/garrysmod-issues/files/4349734/console.txt)

**Comment by GitSparTV** [comment]
Is it singleplayer?

**Comment by AlphaS-code** [comment]
Multiplayer

**Comment by GitSparTV** [comment]
Looks like your server didn't update

**Comment by AlphaS-code** [comment]
updated (then how i join server?)

**Comment by robotboy655** [comment]
One or more files on your server are either not updated or are overwritten by an addon,
