### ISSUE TITLE
RichText panel wrong "signal value" in clickable text segments

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#4421]
If you create a RichText panel insert several clickable text segments, until of of them is out of view (e.g you need to scroll to see it) and then click on one of the clickable text segment, you will find out that it passes the previous clickable segment value instead of the one your clicked on.

Tested on x64. Confirmed by other players and @Python1320.

**Comment by GitSparTV** [comment]
Any code to test?

**Comment by Earu** [comment]
```lua
local url_1 = "https://cdn.discordapp.com/attachments/596038290738774016/690646924751274004/2985548990_a5bdc12f3f_b.png"
local url_2 = "https://cdn.discordapp.com/attachments/296410226742263809/690645507030384680/35513897623_65310284a8_b.png"

local frame = vgui.Create("DFrame")
frame:SetSize(400, 400)
frame:Center()
frame:MakePopup()

local richtext = frame:Add("RichText")
richtext:Dock(FILL)
richtext:InsertColorChange(255,255,255,255)

richtext:InsertClickableTextStart(url_1)
richtext:AppendText(url_1)
richtext:InsertClickableTextEnd()

local test_str = "LOLOLOLOLOOLOLOL"
for _=1, 300 do
    richtext:AppendText(test_str)
end

richtext:InsertClickableTextStart(url_2)
richtext:AppendText(url_2)
richtext:InsertClickableTextEnd()
```

Notice that the link it tries to open with this code changes with the line you click on.

**Comment by GitSparTV** [comment]
Tested on dev 200320. The second link leads to first link

**Comment by robotboy655** [comment]
Should be fixed, including the links going off panel bounds in that example.
