### ISSUE TITLE
env_entity_dissolver blames a player for the kill.

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4422]
```lua
ED = ents.Create("env_entity_dissolver")
ED:Spawn()
ED:Activate()
```

Run on any NPC: `Entity(1):GetEyeTrace().Entity:SetName("ds") ED:Fire("Dissolve", "ds")`

You are attacker and inflictor, even if you hold physgun.
This works correctly on props and players, but not NPCs

**Comment by GitSparTV** [comment]
EntityTakeDamage:
```
GetAmmoType     =       -1
GetAttacker     =       Player [1][Spar]
GetBaseDamage   =       10000
GetDamage       =       10000
GetDamageBonus  =       0
GetDamageCustom =       0
GetDamageForce  =       Vector(0.00, 0.00, 0.00)
GetDamagePosition       =       Vector(0.00, 0.00, 0.00)
GetDamageType   =       33540137
GetInflictor    =       Player [1][Spar]
GetMaxDamage    =       10000
GetReportedPosition     =       Vector(0.00, 0.00, 0.00)
IsBulletDamage  =       false
IsExplosionDamage       =       false
IsFallDamage    =       true
```

**Comment by GitSparTV** [comment]
Tested on `npc_combine_s`. Some NPCs works correctly, seems like an combine issue

**Comment by robotboy655** [comment]
Its on purpose.
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/EntityDissolve.cpp#L347

**Comment by GitSparTV** [comment]
But why not a worldspawn?

**Comment by robotboy655** [comment]
How would I know? I didn't make it.

**Comment by GitSparTV** [comment]
I mean can it be changed to worldspawn or could it break maps?

**Comment by robotboy655** [comment]
Don't know if it could break maps, so I guess we will find out.
