### ISSUE TITLE
Gmad fails to create .gma files now.

### ISSUE THREAD

**Issue by Ex-Syndicate** [Facepunch/garrysmod-issues#4423]
### Details
After a recent update to Garry's Mod, i notice changes were made to Gmad.exe
Since these changes i can't use Gmad.exe anymore to make .gma files.
It instantly closes down now, i have everything in my addon folder correct, i also have my addon.json so why is it not working now?

### Steps to reproduce
Just try use Gmad.exe after the update, i bet the same results will occur.

**Comment by GitSparTV** [comment]
Have you tried to open cmd.exe put gmad path, the folder path and run?

**Comment by robotboy655** [comment]
Your are probably encountering an error and you just don't get to see it due to how you use the tool.

As mentioned above, try using the Command Prompt to run the program, or use the `pause` command in a `.bat` file after running `gmad.exe` to see if the program finished successfully or not.

**Comment by Verideth** [comment]
Doesn't GMad give off an error log? I recall it doing that back when I was using it ages ago. What does that say?

**Comment by Ex-Syndicate** [comment]
Ok turns out my Gmad was giving me Whitelist errors, but it would not stay open long enough to tell me.
