### ISSUE TITLE
tools/toolsplayerclip material uses metal surfaceprop

### ISSUE THREAD

**Issue by gooball60** [Facepunch/garrysmod-issues#4424]
It seems that the tools/toolsplayerclip material has acquired the metal surfaceprop somehow resulting in it using metal footstep sounds when walked over (it always used to be the default "concrete" footstep sounds). This of course can be worked around in new maps, but existing maps often have random metal footstep sounds in areas clipped with the material in question.

**Comment by robotboy655** [comment]
Examples?

**Comment by gooball60** [comment]
On further inspection... it seems to be a bit more elusive. Here's my scenario:

I'll use this map as an example (the [stairs](https://pasteboard.co/J0z5jMf.jpg) in it are clipped with tools/toolsplayerclip): https://steamcommunity.com/sharedfiles/filedetails/?id=1907653798

-Start up Gmod and load gm_conglomerate, the stairs have the usual concrete footstep sounds.
-Load up a different map (I tested with gm_flatgrass and gm_construct).
-Load up gm_conglomerate again and the stairs now use metal footsteps.

**Comment by gooball60** [comment]
It also looks like simply restarting the map produces the same result.

**Comment by robotboy655** [comment]
I cannot reproduce this. Are you sure its not one of your addons/mountable games/mount.cfg overwriting that material?

Try `whereis materials/tools/toolsplayerclip.vmt` in your client console. It should be in `hl2_misc.vpk`.

**Comment by gooball60** [comment]
Looks like the problem was being caused by something in my lua folder. Might it be worth investigating further to see exactly what script caused it?

**Comment by robotboy655** [comment]
Well do it, if it is a problem on your end, its not a problem with the game and this issue should be closed.

**Comment by gooball60** [comment]
Yep, I had a few blocks of physenv.AddSurfaceData in a lua/autorun script, must have messed up the surface properties because of the limit on those in GMod.
