### ISSUE TITLE
Clients crashing on server when shooting specific parts of a vehicle

### ISSUE THREAD

**Issue by LambdaGaming** [Facepunch/garrysmod-issues#4425]
### Details
Clients on my server have been crashing when getting into gunfights recently. I originally thought it was something with the weapons themselves (we use CW 2.0) but after doing some testing I realized it was actually the impact of the bullet causing the crash, not the weapons themselves, as it only happened when shooting vehicles. All affected clients were running the x86-64 branch on 64 bit mode. During my tests I was unable to reproduce the crash in 32 bit mode.

### Steps to reproduce
After seeing it happen with a certain vehicle I tested it on an empty server with that same vehicle to make sure it wasn't exclusive to that server. The vehicle I used was [SGM's 2021 Tesla Cybertruck.](https://steamcommunity.com/sharedfiles/filedetails/?id=1919853563) I left out the CW weapons just in case they were the cause and used the HL2 SMG for all of my tests. I was able to get it to crash every time by shooting either of the two back windows. I know other vehicles can also cause this crash because this started happening before the Cybertruck was even uploaded to the workshop. (Although I'm not 100% certain that this goes beyond SGM's addons.)

### Crash dump
https://drive.google.com/open?id=1RUrfaC-n36BE7vfO_PGYVCCg4bMdBNPg

**Comment by robotboy655** [comment]
Ok, try again when it updates, I was not able to reproduce your exact crash, but I was able to reproduce a freeze which should now be fixed.

Now, a fair warning the decals on that vehicle will have graphical glitches, I am not sure if this is something with the Source's decal system, or very poor optimization of that model.
