### ISSUE TITLE
game.GetMapVersion() is not available in the client realm

### ISSUE THREAD

**Issue by hiddencoders** [Facepunch/garrysmod-issues#4427]
Hey!

The shared function `game.GetMapVersion()` doesn't exist on the client, although it should - clients should have access to the hammer build number.

Tested with maps with and without lmp files, including gm_construct in vanilla sandbox.

**Comment by robotboy655** [comment]
It is not a shared function. Also it is not the "hammer build version", it is the BSP version, which would be 20 or 21 in most cases. Not sure why this function even exists.

**Comment by Kefta** [comment]
I use it in scripts for detecting CS:GO/Portal 2 branch maps, but I have to use a BSP reader clientside as it's unavailable.

**Comment by robotboy655** [comment]
I am afraid there isn't a good way around this without breaking binary modules that use gpGlobals

**Comment by Kefta** [comment]
Perhaps when x64 is officially released since everyone will have to recompile anyway?
