### ISSUE TITLE
Attachments & Bones Returning Wrong Position

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#4429]
### Details
Hello, there is a long standing bug with attachments and bones for NPCs, especially scripted ones. When retrieving an attachment or a bone position on an NPC (server-side), half the time it returns the correct position and half the time it offsets it by couple hundred world units (The offset seems to be consistent somehow). The issue is also present when a weapon's owner is an NPC and the game tries to retrieve the weapon's attachments or bones. 

Other details:
- Has been tested by multiple people.
- Issue is only present server-side (As expected).
- Seems to be exactly every other tick.

### Steps to reproduce
Most of the tests were done using the `base_entity` as the base and `ai` as the type. Reproducing it is very simple. Retrieve the position of an attachment or a bone, you can even try to spawn a ragdoll using the NPC's position and angle. Half the time it will return a random offset value.

Here is a very simple code to reproduce the issue:
`ent:SetPos(self:GetAttachment(self:LookupAttachment("attachment_name")).Pos)`

### Visual
Took couple of photos to help demostrate the issue.
`red outline` = wrong position
`green outline` = correct position

Scripted NPC's range attack position is returning with a random offset half the time:
![bug1](https://user-images.githubusercontent.com/6934542/77689840-c334d680-6f78-11ea-86f2-d4a8bf524d97.jpg)

NPC's weapon returning incorrect attachment position, also half the time:
![bug2](https://user-images.githubusercontent.com/6934542/77689866-cb8d1180-6f78-11ea-9567-511c4b5d001f.jpg)

_Thank you, if more details are required feel free to ask!_

**Comment by DrVrej** [comment]
**Important Update:** After more testing, the issue seems to arise from the following command: `sv_pvsskipanimation`. Setting this variable to 0 fixes the issue. It seems to be enabled by default. It's causes many serious issues aside from attachments and bones returning wrong position.

The description for the command (Copied from online) says "Skips SetupBones when npcs are outside the PVS", which doesn't make sense, because the NPC is in the player's sight (visible), my guess is the command is bugged. Either the bug should be fixed or this should be turned off by default for all users.

**Comment by Jvs34** [comment]
Seems to be related to #3602? Although you did say that it happens to non-hl1 npcs too.

Maybe it happens to HL2 npcs because their AI seems to be frozen in the last picture and they need to constantly think to set COND_IN_PVS for bone calculations, which does relate to the issue I mentioned.

**Comment by Kefta** [comment]
This is a duplicate of #3602, and I already provided a solution in that issue.

**Comment by DrVrej** [comment]
> This is a duplicate of #3602, and I already provided a solution in that issue. The same COND_IN_PVS problem I mentioned in that comment applies to some HL2 NPCs, as well.

Although that post is about HL:S, the fix might work for SNPCs. I will post results here if that fixes the issue with SNPCs.

**Comment by DrVrej** [comment]
I have now tested `COND_IN_PVS` by running `self:SetCondition(1)` in the Think function of the SNPCs, and it worked perfectly! Thank you @Kefta and @Jvs34 for pointing out the alternative solution! I will now close the issue and provide the fix for it.

### FIX
Issue can be fixed by either by disabling `sv_pvsskipanimation` or applying the condition, `COND_IN_PVS` to the NPC.

Thanks again everyone!
