### ISSUE TITLE
PLAYER:GetEyeTraceNoCursor variable typo preventing trace caching usage

### ISSUE THREAD

**Issue by tehbiga** [Facepunch/garrysmod-issues#4430]
### Details
Was doing a file search for the `GetEyeTrace` cache to reuse the code and noticed `GetEyeTraceNoCursor` has a typo; was totally by happenstance.

### Steps to reproduce

1. Look at existing code: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L209

### Code in GMod

```lua
function meta:GetEyeTraceNoCursor()

	if ( CLIENT ) then
		local curtime = CurTime()

		if ( self.LastPlayerAimTrace == curtime ) then 		-- Conditional "Player"
			return self.PlayerAimTrace
		end

		self.LastPlayertAimTrace = curtime 					-- Assignment "Playert" <-
	end

	local tr = util.TraceLine( util.GetPlayerTrace( self, self:EyeAngles():Forward() ) )
	self.PlayerAimTrace = tr

	return tr

end
```

**Comment by Kefta** [comment]
Good catch, I missed it myself when updating the function a while back: https://github.com/Facepunch/garrysmod/commit/6db574ead6bfdcc31a271c9cb9506e9a0091b495#diff-1e206fc49a2e196fc2902bb0c5514e79

Fixed in https://github.com/Facepunch/garrysmod/pull/1645.
