### ISSUE TITLE
Entity:GetSequenceInfo() returns nil after calling Weapon:SendWeaponAnim() before Weapon:Think()

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4433]
### Details
This is a bug with swep viewmodels.
- On the client only, both `GetSequenceInfo()` and `GetSequenceInfo()` return nil if called after `SendWeaponAnim()` before the swep's Think hook has been run.
- If `SendWeaponAnim()` is *not* called before the swep's Think hook has been run, however, then `GetSequenceInfo()` and `GetSequenceInfo()` return valid data.

In other words, it seems like this bug occurs in the space between `Intialize()` and `Think()`. If you use `SendWeaponAnim()` in the swep's think hook, it will *not* cause `GetSequenceInfo()` and `GetSequenceInfo()` to return nil.

Among other things, this bug affects sweps that play a different pull out animation (e.g. `ACT_VM_DRAW_EMPTY`) instead of the engine default `ACT_VM_DRAW`.

#### The following code is affected by the bug
```
function SWEP:Initialize()
	if CLIENT then self:Deploy() end
end
function SWEP:Deploy()
	local vm = self.Owner:GetViewModel()
	self.Weapon:SendWeaponAnim(ACT_VM_DRAW)
	local seqInfo = vm:GetSequenceInfo(vm:GetSequence())
	local seqList = vm:GetSequenceList()
	print("seqInfo: ", seqInfo)
	print("seqList: ", seqList)
end
```
Both prints will show nil values.

#### This code, however, is NOT affected by the bug
```
function SWEP:Initialize()
	if CLIENT then self:Deploy() end
end
function SWEP:Deploy()
	local vm = self.Owner:GetViewModel()
	-- self.Weapon:SendWeaponAnim(ACT_VM_DRAW) -- Only this line is omitted
	local seqInfo = vm:GetSequenceInfo(vm:GetSequence())
	local seqList = vm:GetSequenceList()
	print("seqInfo: ", seqInfo)
	print("seqList: ", seqList)
end
```
Both prints will show valid table references.

### Environment
Confirmed on dev 2020.03.31, on x86-64 2020.03.25, and on vanilla 2020.03.21

**Comment by robotboy655** [comment]
Should be fixed on Dev.
