### ISSUE TITLE
Env_fade with spawnflag "Activator only" will close the game if is not called directly

### ISSUE THREAD

**Issue by MaestroFenix** [Facepunch/garrysmod-issues#4437]
### Details

When sending an input to an `env_fade` to fade with the `Activator only` spawnflag from another entity which has no means to check the original activator ( like a `trigger_teleport` calling a `logic_relay` and then this relay calling the fade ), usually on Source it will make the fade to don't work.

However, on GMod it will freeze and close down the program ( not really a crash since it doesn't generate dumps, nor errors of any kind at the console when checked with `Developer 2` and `con_log` / `-condebug` ).

Of course, while mappers can solve this issue very easily, it would be good if GMod doesn't do this and stick to the default Source behavior.

Garrysmod version: Build 7794
Tried both normal and Dev branches. Vanilla content, no addons.

### Steps to reproduce

1. Place on a map an `env_fade` with `Activator Only` spawnflag checked.
2. Use another entity that will call that fade, for example a `logic_relay`.
3. With a trigger, call the intermediary entity so this one calls the fade.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
