### ISSUE TITLE
Crashing upon changing resolution

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#4438]
As the title says I keep crashing with this error whenever I change my resolution on the **dev branch**: ![crash](https://i.imgur.com/o4qFkMM.png)

I didn't do anything in particular except reload my files live, that's all. 
(I also tested in p2p with HEV on)

**Comment by GitSparTV** [comment]
It looks like new hook forgot to pop up itself

**Comment by robotboy655** [comment]
Should be fixed.
