### ISSUE TITLE
GM:ShouldCollide now broken?

### ISSUE THREAD

**Issue by I-Am-Extra** [Facepunch/garrysmod-issues#4439]
### Details
When using the hook ShouldCollide I can never get it to print (or work at all) for some reason after the March Update. I asked 3 other people to do it and they were not able to get anything to print via hook.Add("ShouldCollide"). 

I have added screenshots showing I have the hook, and also return a table of all hooks using "ShouldCollide" (being 0 as it's on my own gamemode). Before I hear the usual "SetCustomCollisionCheck" to true I would like to point out it has been done on both entities.

The hook itself appears to not be called at all (even though it is apparently a valid hook)
-No prints
-Returning does nothing

[Image 1](https://cdn.discordapp.com/attachments/412430064140156928/696026160236068914/1.PNG)

[Image 2](https://cdn.discordapp.com/attachments/412430064140156928/696026163260162148/2.PNG)

### Steps to reproduce
hook.Add("ShouldCollide", "CollisionT333", function(ent1, ent2)
	print("collision")
end)

Try that code and I guarantee it will not work. 
Thanks!

**Comment by Kefta** [comment]
![](https://i.imgur.com/kDPy4Kj.png)
```Lua
hook.Add("PlayerSpawn", "foo", function(p)
	p:SetCustomCollisionCheck(true)
end)

hook.Add("ShouldCollide", "foo", print)
```

**Comment by I-Am-Extra** [comment]
How is it that it doesn't work on my end?

**Comment by robotboy655** [comment]
An addon/some code is likely returning non nil somewhere from that hook.

**Comment by I-Am-Extra** [comment]
Sorry for the late reply

I'll provide my evidence below

**Comment by I-Am-Extra** [comment]
Here is my entity file:
https://i.postimg.cc/wBJ3NVqP/ent.png

Here is the code (hook + command that also sets my customcheck to true):
https://i.postimg.cc/Hsxwyffh/code.png

Here is a video of it in action
https://cdn.discordapp.com/attachments/280079217021026314/696021231920480297/part_04.mp4

Here is the console:
https://i.postimg.cc/fLfPJ66b/1.png

Here is my frameworks hook function (before calling any plugins):
https://i.postimg.cc/j5MGMpvF/hook.png

As you can see it is never even triggered in the hook.Call, I have no workshop addons, my code is the only thing being run as there are no extra lua addons (I only have serverguard in which I disabled for this testing) and I am certain that nothing else could be messing with ShouldCollide as I've been working on this for a long time and know all the ins and outs of the code (as it's also on my own dev base).

**Comment by I-Am-Extra** [comment]
If this is an issue with only me I'm willing to move it onto possibly another titled thread to get some assistance, sorry about the lack of information prior, I was under the assumption this hook really was broken in the update

**Comment by robotboy655** [comment]
PLEASE very carefully read by previous comment. Very. Carefully. Or the wiki page for the function you are using.

**Comment by I-Am-Extra** [comment]
Oh damn I just realised I've been using ::EnableCustomCollisions as opposed to :SetCustomCollisionCheck

Damn I guess sorry for wasting your time haha I really have no idea how I didn't notice this at all.

Thank you very much.
