### ISSUE TITLE
Models spawning causing instant crash

### ISSUE THREAD

**Issue by AutismoPiggo** [Facepunch/garrysmod-issues#4442]
### Details
This bug origionally didn't happen last year, instead the models only crashed when faceposing was applied to the flexes. This happened to a large number of SFM models, not one or two in particular. Now, these models crash gmod instantly when the spawn icons or the models themselves are being spawned.

### Steps to reproduce
Download one of the models below
Place in garrysmod>garrysmod>addons as a legacy addon (or in materials/models)
Spawn on any map or simply let the spawnicon attempt to render
https://steamcommunity.com/sharedfiles/filedetails/?id=2029281983
https://steamcommunity.com/sharedfiles/filedetails/?id=1967707064

(For context, ArachnitCZ knows about this issue so its not just his models, plenty of SFM ones do this. It also isn't a phys file issue, same happens without one.)
Crashdumps:
https://mega.nz/file/o7wRBQqR#pp4Q1qy-8QDCgLSsHNRU356Z6gdAH7CJBXWKQdlDl3U
https://mega.nz/file/Bu5RGQBR#Is-gGcaROFGU-6J1cCTx67nf0mGtDVD_RqdxDfEB8No

**Comment by robotboy655** [comment]
Should be fixed on Dev. (When it updates)
