### ISSUE TITLE
CLuaParticle does not render when start size is less than 1.0

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4443]
### Details
CLuaParticles with a starting size less than 1.0 are not rendered. If the starting size is >= 1.0, then it renders fine.

Interestingly, if `SetStartSize()` is set >= 1.0 and `SetEndSize()` is set to < 1.0, the particle will actually render smaller than 1.0 as it transitions.

I imagine this is probably related to the hammer unit; however, if so, this is a poor restriction, because not all particles simulate physics. Many particles exist as viewspace effects (such as sparks or glows on viewmodels), and thus have no collisions. These particles should *not* be required to be at least 1 hammer unit in size.

### Steps to reproduce
1. Make a CLuaEmitter in 2D mode.
2. Make a particle, use `SetStartSize()` and specify any value under 1.0. The particle will not render.

### Environment
Confirmed on dev 2020.04.07

**Comment by robotboy655** [comment]
That's because particle sizes could only be a whole number, not a fraction. Should be fixed on Dev now.
