### ISSUE TITLE
Bad Decal Failure

### ISSUE THREAD

**Issue by thelumaster** [Facepunch/garrysmod-issues#4444]
During when NPCs are spawned ever since the update myself and the server I play on have been having our gmods close and a pop up saying 'bad decal list'. Any fix?
i send the dmp file to robotboy655@facepunchstudios.com

**Comment by robotboy655** [comment]
Try the "Dev" beta branch.

**Comment by thelumaster** [comment]
I have try the dev beta branch and the crash continues, little less but continues, it only happens when i put npc and the npc starts shooting. all my users has the same crash

**Comment by robotboy655** [comment]
When have you tried it? It was updated yesterday.

**Comment by thelumaster** [comment]
i have tried yesterday , i will see today if the crash continúes

**Comment by thelumaster** [comment]
Still having crashes !!, i send to your email the two dmp crashes that i have today!

**Comment by robotboy655** [comment]
Is it the same "bad decal list" crash though? One of the dmp files you sent isnt even from "Dev" beta branch.

**Comment by thelumaster** [comment]
Yes , it is the same crash with the same message (Bad decal list) , the another crash that i send to You is a chronium branch error. The Bad decal crash is with Dev beta branch

**Comment by GarnetGaming** [comment]
Hi there! just joining in the discussion. I very recently launched a StarwarsRP server, and many of my players are reporting the occasional "bad decal" crash as well, with supposedly no crash logs available. This is utilize VJ base

**Comment by Kefta** [comment]
Are you testing on dev branch?

**Comment by GarnetGaming** [comment]
No, my clients are not utilizing the dev branch.
