### ISSUE TITLE
gmod studiomdl.exe -game no longer controls where the outputs of compiled models go

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#4447]
### Details
Until recently, the gmod version of studiomdl.exe found in garrysmod/garrysmod/bin, which is nice because it has some things like bodygroup limits raised, ect, used to be able to compile to different folders with the -game <path> option, meaning you could compile your models into a specific folder. In my case, this allowed me to keep projects separate by automatically compiling them to the right place, but now it will compile them directly to the garrysmod/garrysmod/models folder no matter what.

### Steps to reproduce
I use crowbar as a gui to compile all of my models, but essentially just compile with 
-game some/folder/path

I'm also compiling with -nop4 -verbose

**Comment by robotboy655** [comment]
It was changed recently so could it be a problem on your end?

**Comment by robotboy655** [comment]
In my tests it works perfectly fine, using this .bat script:
```
@echo off

:COMPILE

set studiomdl="path/to/studiomdl.exe" -game "path/to/game" -quiet -nox360 -nop4

echo Compiling...

%studiomdl% %1

echo Finished compiling!

PAUSE

goto COMPILE
```

**Comment by bizzclaw** [comment]
I know you closed this but I made a mistake with this report.

I failed to mention that I was on the x86-64 - Chromium + 64bit binaries beta. I've been on that beta for so long I honestly forgot, but I tried opting out of the beta and I'm having no more issues with this, so if that beta is even still being maintained it might be worth looking into there.

**Comment by robotboy655** [comment]
Should be fixed on x64 when it updates.
