### ISSUE TITLE
User defined localizations are not loaded

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-issues#4448]
### Details

@robotboy655 [commented](https://github.com/Facepunch/garrysmod-requests/issues/687#issuecomment-200783032):

>Your addons should use the .properties files for localization, which will be automatically loaded depending on what language the user has set. See the file structure in resources/ folder.

However, it doesn't appear that this functionality works. Attempting to translate a string with `language.GetPhrase(phrase)` yields the inputted phrase, not the translation.

### Steps to reproduce

See: https://github.com/rbreslow/localization-test

**Comment by robotboy655** [comment]
Should be fixed on Dev.
