### ISSUE TITLE
Weapon:Holster() is not called clientside when equipping a new weapon from the spawnmenu

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4451]
### Details
The title pretty much sums it up. When a client spawns himself a weapon from the spawnmenu (and thus triggers a weapon switch), the `Weapon:Holster()` hook is only called on the server. The client viewmodel will play the engine default `ACT_VM_HOLSTER`, but the hook is never called.

This causes problems with weapons delay the holster (such as to play a full length sequence) and then finish it with a clientside `input.SelectWeapon()`. Because the `Holster` hook is not called clientside, the client is unaware that the holster started (on the server) and will never reach the logic where it uses `input.SelectWeapon()` to complete the holster. Thus, the server thinks the client is holstered, but the client is still holding the weapon. The client is unable to shoot or otherwise operate the weapon because of the desync.

#### Regarding the counterargument of "just do it serverside":
Clientside `input.SelectWeapon()` seems like the most reliable way (regarding prediction and connection latency) to delay a holster and then complete it when desired. Completing the holster server-side is possible, but is subject to the client's connection latency, and thus incurs a variable time penalty before the client actually completes the holster. With `input.SelectWeapon()`, the client holsters immediately with prediction in effect - which, of course, provides a smoother and superior play experience.

**Update:**
This glitch also occurs when switching to any of the various toolguns from the Tools panel in the spawnmenu.

### Steps to reproduce
1. Make a SWEP with ```function SWEP:Holster(target) print("holster") return false end``` for the sake of demonstration purposes.
2. Equip and deploy a copy of that SWEP.
3. While holding the SWEP, open the spawn menu and give yourself a different weapon. Both left-clicking to spawn the weapon and right-click -> Spawn With Toolgun will trigger the bug.
4. Notice "holster" in the server's console, but no such print in the client's console.
5. The client's viewmodel will play `ACT_VM_HOLSTER` and become unusable.

### Environment
Confirmed on dev 2020.04.13

**Comment by Kefta** [comment]
It's because Deploy and Holster are only called serverside when using player:SwitchWeapon instead of input.SelectWeapon as the weapon is being swapped out of prediction. This is intended behaviour.

**Comment by TiberiumFusion** [comment]
@Kefta 
Thank you for clarifying that.
I now see the blue note regarding this on [https://wiki.facepunch.com/gmod/Player:SelectWeapon](https://wiki.facepunch.com/gmod/Player:SelectWeapon), but the [https://wiki.facepunch.com/gmod/WEAPON:Holster](https://wiki.facepunch.com/gmod/WEAPON:Holster) page doesn't have a similar note. I suggest one ought to be added there.

But this doesn't make sense to me. Since the client is making the decision to switch weapons (by clicking on things in their spawnmenu), why is the weapon switched out of prediction using `Player:SelectWeapon`? Why cant `input.SelectWeapon()` be used instead? The action intent originates from the client, after all. This is a rather weird inconsistency.

**Comment by Kefta** [comment]
Because player:SelectWeapon's expected behavior is to immidiately switch the weapon while input.SelectWeapon queues the switch until the player's ucmd is processed. I'll add a note to the wiki page.

**Comment by TiberiumFusion** [comment]
@Kefta 
Because of the divergent weapon switch behavior, surely there must be a way to detect which path is in effect (i.e. `input:SelectWeapon` vs `Player:SelectWeapon`) so that user code can properly diverge as well and handle the different paths appropriately. I cannot find any information on the wiki regarding how to detect which weapon switch path is currently in effect.

Can you describe how to detect this? Ideally, such a check could be performed at the start of WEAPON:Holster(), such that the server will know the what path is being taken and can thus instruct the client appropriately.

**Comment by Kefta** [comment]
You can use this in the next update/on the dev branch:
```Lua
local bMultiPlayer = not game.SinglePlayer()

-- Serverside
function SWEP:PredictedFunction()
	local pOwner = self:GetOwner()

	-- SWEP:Think will be called on the client in singleplayer too
	-- so the bMultiPlayer check doesn't apply there
	if (bMultiPlayer and pOwner:IsValid() and GetPredictionPlayer() == pOwner) then
		-- Clientside version will be called
	end
end
```

**Comment by TiberiumFusion** [comment]
@Kefta 
Thanks, I've been wondering what that new `GetPredictionPlayer()` method was useful for.

On a side note, do you know when the next update will ship?

**Comment by Kefta** [comment]
No, but it will be announced a week before it's released thru Steam and the GMod Discord.
