### ISSUE TITLE
Crash CUtlRBTree overflow

### ISSUE THREAD

**Issue by Belloxy** [Facepunch/garrysmod-issues#4452]
### Details
My gmod client crashed multiples times and it only show "CUtlRBTree overflow", i don't know why, i tested with default and x64 branch, It only crash on a gamemode which is round based and spawning props.
Sended dumps via email.

### Steps to reproduce
To reproduce it, juste play on my server on a specific gamemode and it will crash multiple times

**Comment by robotboy655** [comment]
Looks like you are crashing due to font rendering, specifically too many materials (the limit is 65k). Don't know how you are managing this, but the best way to solve this is to starting reducing on that.

**Comment by FrezZyyyx** [comment]
@robotboy655 what materials do you mean? like workshop content packs? or the material list for applying on props?
