### ISSUE TITLE
Console doesn't support Cyrillic characters 

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4454]
srcds doesn't support Cyrillic characters in input both on Windows (dev) and Windows (x86-64).
However it can display them normally on Windows (dev), but not Windows (x86-64).

The support of Cyrillic characters on main branch happened in 2017, but I used support subforum on Facepunch.

Willox said to try x86-64 branch so I'm reporting that it has the same issue.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1545

**Comment by WilliamVenner** [comment]
Workaround

https://github.com/WilliamVenner/gmsv_concolormsg
