### ISSUE TITLE
The game crashes on Linux when using the x86-64 branch

### ISSUE THREAD

**Issue by Comminux** [Facepunch/garrysmod-issues#4456]
### Details
**OS:** Arch Linux
**PC spec:** Ryzen 3600, 16 GB RAM, RX 570 8GB
**Used Beta Branch:** x86-64
**Steam Build ID:** 4881163

One of my favorite modes in the game is TTT and I am very depressed by the frequent crashes of the game.

**Video example of crash:** https://youtu.be/OZHms6nKB1Y?t=53
**Link to my crashes on Yandex.Disk:** https://yadi.sk/d/cTfACgb1t53gGw
_(Crash files were also sent via email to robotboy655 and willox)_

### Steps to reproduce
Previously, such problems were caused by one add-on, but it was recently removed from the game server: https://github.com/Facepunch/garrysmod-issues/issues/936#issuecomment-549172136

**Comment by willox** [comment]
Can you run with queued rendering disabled (`gmod_mcore_test 0`) and see if the problem still occurs?

**Comment by Comminux** [comment]
Game doesn't crahes with `gmod_mcore_test 0`
