### ISSUE TITLE
sound.PlayURL ignore sound option "Mute on Minimize"

### ISSUE THREAD

**Issue by Comminux** [Facepunch/garrysmod-issues#4457]
### Details
**OS:** Arch Linux
**Used Beta Branch:** x86-64
**Steam Build ID:** 4881163

sound.PlayURL function ignores the setting in the sound menu and continues to be heard when the game is minimized.

**Comment by robotboy655** [comment]
It's already addressed in the next update, currently only available on "dev" development branch.
