### ISSUE TITLE
Lua FindUseEntity returns different entity to engine

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4458]
### Details
*There are no FindUseEntity hooks on the server I'm testing this on*

When manually calling the `FindUseEntity` via Lua, the returned value is different to the entity the engine returns. I do not believe this is related to the base gamemode's [`GM:FindUseEntity`](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/base/gamemode/player_shd.lua#L109) as the `ent` is valid when this issue occurs.

### Steps to reproduce
The doors on [gm_site19](https://steamcommunity.com/workshop/filedetails/?id=290599102) are where I found this issue.

![](http://i.venner.io/gmod_2020-04-20_16-25-35.jpg)

Here I am staring at a `prop_dynamic`. The engine returns the `func_button` as the use entity. However, when calling `FindUseEntity` via Lua, the `prop_dynamic` is returned instead.

```lua
hook.Add("FindUseEntity", "FindUseEntity.Debug", function(ply, defaultEnt, mute)
    if (not mute) then
        print("FindUseEntity", ply, defaultEnt)
    end
end)
```

```lua
lua_run print(hook.Run("FindUseEntity", player.GetByID(1), nil, true))
```

You should notice that running the above command returns a different entity to when the engine calls FindUseEntity.

**Comment by WilliamVenner** [comment]
I should also probably note `FindUseEntity` is not used in DarkRP (which I am running in the screenshot)

https://github.com/FPtje/DarkRP/search?q=FindUseEntity&unscoped_q=FindUseEntity

**Comment by robotboy655** [comment]
You are doing something inherently invalid. The `FindUseEntity` hook allows you to override the engine use entity, so calling the hook manually will only return the desired use entity override.

Calling the hook manually will not magically do whatever you want it do, i.e. returning the entity that would be used if no Lua override is given.

Engine's use behavior is not a simple straight-line trace, and there's already a requested function to get the "use" entity that would actually be "used" when you press your `+use` bind: https://github.com/Facepunch/garrysmod-requests/issues/883

**Comment by WilliamVenner** [comment]
thank you :) I had a feeling that was the case. +1 for that function request.
