### ISSUE TITLE
-tools does nothing on x86-64 - Chromium + 64bit binaries beta

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-issues#4459]
### Details
If you add **-tools** to your launch options, you get access to the particle editor which can be useful in-game for viewing particle files and finding out what you need to precache, however, this does nothing when playing on the x86-64 - Chromium + 64bit binaries beta.

### Steps to reproduce
- switch to the beta "x86-64 - Chromium + 64bit binaries beta"
- add _-tools_ to launch options to garrysmod on steam
- launch garrysmod

**Comment by robotboy655** [comment]
You can access `-tools` with the 32bit binaries on the x86-64 or Chromium branches. Not sure if 64bit ones will be built for tools.

**Comment by robotboy655** [comment]
Added 64bit builds for the particle editor.
