### ISSUE TITLE
Gmod instacrash on loading some SFM models

### ISSUE THREAD

**Issue by AutismoPiggo** [Facepunch/garrysmod-issues#4460]
This crash occurs when the game tries to render the spawn icon OR spawn the model if the spawn icon is already rendered

Crash dump and an MDL that causes the crash here:
https://mega.nz/file/dyhXXJzZ#tQEzMMPD-1TPL9qZGnzxD4XsfE0GgRyzsW1DTUxz4sA

**Comment by robotboy655** [comment]
I am fairly certain its the exact same crash you already reported, and just the .mdl is not enough, the other files are very much necessary as they contain the actual mesh data.

Always test the crashes on Dev branch as it may be already fixed.
