### ISSUE TITLE
Synchronously removing entity in OnEntityWaterLevelChanged crashes game/server

### ISSUE THREAD

**Issue by linkjay** [Facepunch/garrysmod-issues#4461]
### Details
When using the OnEntityWaterLevelChanged function, attempting to remove the entity provided at any point synchronously will crash the server. If in singleplayer, this crashes the game.

Tested this on 64bit branch and 32bit (no betas selected) on Arch Linux `5.6.5-arch3-1` and confirmed this working on singleplayer with the code shown below. Also had a friend on Windows test this in singleplayer, he crashed as well.

When done in Singleplayer and output running from hl2.sh : `Segmentation fault (core dumped)`
When done in Ubuntu 16.04-LTS SRCDS : ![https://i.linkjay.io/lGapMr.png](https://i.linkjay.io/lGapMr.png)

This is the code that will cause a crash if ran serverside:

```
if SERVER then
    local entsToBother = {
        prop_physics = true 
    }

    hook.Add('OnEntityWaterLevelChanged', 'propWaterLevelRemover', function(ent, old, new)
        if not IsValid(ent) then return end

        if entsToBother[ent:GetClass()] and new >= 2 then
            --timer.Simple(0, function()
                PrintMessage(3, ent:GetClass() .. ' removed for being underwater!') 
                ent:Remove()
            --end)
        end
    end) 
end
```

If the timer.Simple block is uncommented there, it will actually fix this problem.

### Steps to reproduce

1. Run that code above on server
2. Spawn any `prop_physics`. Submerge it mostly and game/server should crash immediately.

**Comment by robotboy655** [comment]
As the message `Changing collision rules within a callback is likely to cause crashes!` suggests
, don't do it. Not something that can be properly fixed without removing the hook, or internally delaying it due to it being a vphysics issue.

**Comment by robotboy655** [comment]
Ok I did fix it for Entity.Remove, but I imagine `SetSolidFlags` and other functions will still cause crashes
