### ISSUE TITLE
Garry's mod Crash on Startup

### ISSUE THREAD

**Issue by monikulapl** [Facepunch/garrysmod-issues#4462]
I have an issue where when i launch Garry's mod i see a black screen for a brief moment before my game crashes and leaves a mini dump file

https://www.dropbox.com/s/u9gkdqt0yr4c2bg/hl2_2117156_crash_2020_4_21T19_56_55C0.mdmp?dl=0

**Comment by robotboy655** [comment]
You are crashing in your nvidia drivers, nothing we can do about it.
