### ISSUE TITLE
Crashing on game.CleanUpMap()

### ISSUE THREAD

**Issue by Dimantio** [Facepunch/garrysmod-issues#4463]
### Details
Affect prerelease branch and dev branch, the game crash to desktop after map cleanup. Doesn't affect gm_construct / gm_flatgrass 

Here's the dump: https://i.qcgames.org/cjjqa.mdmp

### Steps to reproduce
Load this [map](https://steamcommunity.com/sharedfiles/filedetails/?id=187437437) and simply run this in singleplayer `lua_run game.CleanUpMap()` a few times.

**Comment by robotboy655** [comment]
Fixed.
