### ISSUE TITLE
Add Black Mesa Mounting support

### ISSUE THREAD

**Issue by ecumber** [Facepunch/garrysmod-issues#4466]
As of now, you have to mount it manually via the config file and you have to browse the files in the all games list.

**Comment by Kefta** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/599 and on the wrong repo. Someone already asked the BM devs and they said no.

**Comment by ecumber** [comment]
Sorry, didn't see that

**Comment by CybrFox-CC** [comment]
Hey everyone, I'm replying on behalf of Crowbar Collective.  We are okay with having Black Mesa be apart of this, as long as it's used in a non-commercial/non-retail usage.  Feel free to reach out to me on our official Discord if needed.
