### ISSUE TITLE
Half-Life Source Model Conflicts

### ISSUE THREAD

**Issue by ecumber** [Facepunch/garrysmod-issues#4467]
### Details
Models such as the barnacle, the regular poly count GMan model, and hgibs become corrupted when HLS/HLDMS is mounted

### Steps to reproduce
Spawn a model that has the same filename name in HLS and HL2

For example, HLS and HL2 both have a gman.mdl, if you load the gman.mdl from HL2 the HL1 model will appear

![image](https://user-images.githubusercontent.com/14047530/80042820-e63da200-84b4-11ea-813f-887b8a6e4ff4.png)

**Comment by Kefta** [comment]
Related to https://github.com/Facepunch/garrysmod-issues/issues/3961 and https://github.com/Facepunch/garrysmod-issues/issues/4445.

**Comment by robotboy655** [comment]
Are you sure you are not running some addon that cause this, like "HLS fix addon" or a pirated content pack for HLS content? HL2 models should override any other model by default.

**Comment by ecumber** [comment]
I started the game without addons, and that worked, however I can't find anything that would cause a conflict. Still looking

**Comment by robotboy655** [comment]
`whereis models/gman.mdl`

**Comment by ecumber** [comment]
I found it, it was in a content pack for a map but it was disabled? I don't know why it loaded
