### ISSUE TITLE
Voice Chat Audio Quality Upgrade Caused Issue With Receive Volume

### ISSUE THREAD

**Issue by BobFromBuufs** [Facepunch/garrysmod-issues#4468]
Since the latest upgrade to the Garry's Mod voice chat, which improved audio quality to 44100hz, players can no longer lower receive volume without causing lots of noise in the signal. At full receive volume, voices are clear and noise-free. However, this makes most players' voices far too loud in comparison with other game audio. Turning down the receive volume under the voice tab in settings does not lower volume, but instead introduces distortion proportionate to how far below 100% you set the receive volume. This has been reported by every player I've spoken to about it. It is making the experience very unenjoyable, as I can barely hear the sound of my car engines over players' voices. This is a major issue that should be fixed immediately, as it makes the game far less enjoyable.

To replicate this problem, simply join a multiplayer server with voice chat enabled, lower the voice receive volume, and listen to the extreme distortion and lack of actual volume control. Please fix this issue as soon as possible. It began immediately after the latest update, so it must be related to that.

On a personal note, the highly compressed voice chat has been a part of Gmod since I can remember. Having this new 44100hz quality sounds kind of awkward, as you can hear every subtle noise of a person speaking, such as lips smacking, spit squishing around, etc. Very uncomfortable experience and also very trebly and unpleasant to the ears. A good part of my complaint in that area is due to the fact that I have to keep voice receive volume at max now. It's all awful. Please fix! Thank you!

**Comment by robotboy655** [comment]
Please try the Dev beta branch and let me know if its better there.

**Comment by BobFromBuufs** [comment]
Alright. I'll try that, however, I'm not sure if I can join a server on
that branch. I'll let you know.

**Comment by BobFromBuufs** [comment]
I need the beta access code, please.

**Comment by BobFromBuufs** [comment]
Nevermind about the code. I'm in.

**Comment by BobFromBuufs** [comment]
Alright, I'm on the dev branch and the voice chat is completely fixed. In
fact, it sounds excellent.
Turning down the receive volume also works exactly as it should, with no
added distortion.
Thank you for making this effort to fix the issue. It's very much
appreciated.
