### ISSUE TITLE
Garry's Mod crashes upon opening "player" or "playermodels" folder of Fistful of Frags in the spawnmenu

### ISSUE THREAD

**Issue by TheLEGObrick** [Facepunch/garrysmod-issues#4471]
Details
The recent prerelease update, 2020.04.24 has added mounting support for Fistful of Frags. However this has not come without issues; in the spawnmenu, selecting either "player" or "playermodels" folder in the Fistful of Frags subfolder causes the game to crash shortly after loading the folder.

[Link to three .mdmp files created due to said bug](https://1drv.ms/u/s!AkZIBhTDfXq_ikmL5eBJlCIFCrwN?e=j8HEM9)

Steps to reproduce
(0. Install Garry's Mod and Fistful of Frags)
1. Open Garry's Mod
2. Mount Fistful of Frags
3. Go into a map
4. Open the spawnmenu
5. Scroll down to the "Browse/Games" folder
6. Expand the Fistful of Frags subfolder
7. Open either the folder named "player" or the folder named "playermodels"

Notes
This crashing seems to _only_ upon opening a folder that supposedly contains playermodels, which is likely related to the reason of the crashing

**Comment by robotboy655** [comment]
Couldn't reproduce crashes with models in `playermodels`, but `player` should no longer crash, it has one very broken model file.

**Comment by TheLEGObrick** [comment]
I just went and checked, and... supposedly `playermodels` folder doesn't anymore crash the game, so you can count that as being solved as well
