### ISSUE TITLE
Swedish Characters (Å, Ä, Ö) not working on custom addons

### ISSUE THREAD

**Issue by MokaAkashiya85** [Facepunch/garrysmod-issues#4472]
I'd like to note that this worked previously and I only noticed it now not working.

Swedish characters (Åå, Ää, Öö) has stopped working on any font (even those that support them) on any custom addons. My weapon addons support Swedish as a localized language and I only now noticed that they stopped working entirely. Any suggestions?

![unknown (1)](https://user-images.githubusercontent.com/4171878/80287963-e64bd500-8734-11ea-97a1-f73dc749426e.png)
![unknown (2)](https://user-images.githubusercontent.com/4171878/80287965-e6e46b80-8734-11ea-9267-839fbc00b39b.png)
![unknown](https://user-images.githubusercontent.com/4171878/80287966-e6e46b80-8734-11ea-9ce1-3ac3f1ad61a5.png)

**Comment by Kefta** [comment]
Set the "extended" key to true in your surface.CreateFont calls. See https://wiki.facepunch.com/gmod/Structures/FontData

**Comment by GitSparTV** [comment]
In the second screenshot it's spawnmenu, it doesn't work even there

**Comment by MokaAkashiya85** [comment]
Third one is also in the default weapon select.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/80372133-b3702100-889b-11ea-9c62-ae1cec2ecf7e.png)

That looks like it is working?

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/80372173-c682f100-889b-11ea-8b35-2d675c2beb9a.png)

Make sure your file is saved as UTF-8, etc, etc
![image](https://user-images.githubusercontent.com/3299036/80372211-d69ad080-889b-11ea-94a6-dc2a33b03ff1.png)

**Comment by MokaAkashiya85** [comment]
Well, my addons use a LUA-based localization system that uses GMod's "Properties" files for its localizations. It worked previously, but yes, using regular non-localized names does work:
![image](https://user-images.githubusercontent.com/4171878/80372850-75233380-8894-11ea-8056-39287cc83b93.png)

But the localization stuff doesn't, even though they have worked before:
![image](https://user-images.githubusercontent.com/4171878/80372950-9e43c400-8894-11ea-87f3-f1f561e4bd90.png)
(Taken 2020-04-16)
But they don't anymore, which causes me confusion...
![image](https://user-images.githubusercontent.com/4171878/80373021-b7e50b80-8894-11ea-8491-340c3be814a9.png)
(Taken now)

**Comment by robotboy655** [comment]
Check your localization files? The built-in Swedish localization seems to work just fine.

**Comment by MokaAkashiya85** [comment]
The one that contains the above localizations has not been edited since way before that time, so it hasn't changed. It's in UTF-8 format, alongside the new and old ones.

**Comment by robotboy655** [comment]
Which version of the game are you testing, can you show the localization file?

**Comment by MokaAkashiya85** [comment]
I'm on the "x86-64 - Chromium + 64-bit binaries" Beta of Garry's Mod and this is a screenshot from the localization file (updated last 2020-04-20):
![image](https://user-images.githubusercontent.com/4171878/80377756-f6ca8f80-889b-11ea-8356-cffa50d29212.png)

**Comment by robotboy655** [comment]
First of all, try no betas, secondly, please look at the proper formatting in `.properties` in base game files.

**Comment by MokaAkashiya85** [comment]
I'll try without the beta, but the characters has always worked otherwise, which is confusing...

**Comment by MokaAkashiya85** [comment]
I'll change my topic then. The Swedish characters do not work on that specific beta. Also, that formatting doesn't work on the localization system I use:
![image](https://user-images.githubusercontent.com/4171878/80378838-8c1a5380-889d-11ea-9dfb-5f2df1614d20.png)
But the regular characters returned... weird...

**Comment by robotboy655** [comment]
Is that an addon or a server? How are you loading the files?

**Comment by MokaAkashiya85** [comment]
It's an addon. The files are loaded via an autorun LUA file.

**Comment by robotboy655** [comment]
Link the addon.

**Comment by MokaAkashiya85** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2057348832 This is one of them that uses the system.

**Comment by robotboy655** [comment]
Yeah I think I see what is going on, basically, `.properties` were not loaded before from addons, and now they are, but they expect a different format to what you are using, causing the problem.

it should be fixed on Dev beta branch now.

Basically I'd suggest dropping your localization code as it is all done for you after the update on 29th.

**Comment by MokaAkashiya85** [comment]
So from the Dev beta and forward, localizations will be loaded automatically? Will I need to swap the format around, such as characters on all languages? If so, is there some automatic way of doing it?

**Comment by robotboy655** [comment]
It should work with your format as well now. Localization files will be loaded automatically after the upcoming update on 29th.

All beta branches load the files automatically already. Dev contains the changes that allow for your format, which will be put onto other beta versions and into the next update.

**Comment by MokaAkashiya85** [comment]
Amazing. What changes do I need to do to get this localization system to apply?

**Comment by robotboy655** [comment]
As I said, it is all done for you already, and as I said, you should get rid of your Lua code that loads the .properties files after the update. That's it.

You can test all the upcoming changes on Dev beta branch of Garry's Mod.

**Comment by MokaAkashiya85** [comment]
No no, I meant if I'm meant to change my current "loc('CODE')" lines to for example the default Gmod's "#CODE" or similar on everything.

**Comment by robotboy655** [comment]
Oh, yeah you will need to do that. Again the update is on 29th so you have some time to mess around with this. I assumed you already did it the GMod way since you use `language.Add`

**Comment by robotboy655** [comment]
You could also just make `loc` call `language.GetPhrase()`, that should also do the trick.

**Comment by MokaAkashiya85** [comment]
That way, either loc("CODE") or "#CODE" will work, yes?

**Comment by robotboy655** [comment]
Yes.

**Comment by MokaAkashiya85** [comment]
I loaded up the dev branch and this is the end result: My localizations load but I still got that character issue related to the creation of this entire thread. I tried the "#CODE" but that doesn't work natively apparently. The old code still works (as the script is there, just not the one which'd load the 'correct' properties file) but as said...
![image](https://user-images.githubusercontent.com/4171878/80399724-f4772e00-88b9-11ea-9b86-def74cd3186a.png)
Apologies if I seem incompetent.

**Comment by MokaAkashiya85** [comment]
Apart from that, looks like it works just fine, apart from that the characters still don't load natively and that you are unable to have multiple localizations for one asset name.
![image](https://user-images.githubusercontent.com/4171878/80400341-f097db80-88ba-11ea-9206-2cbbba1eb42a.png)

**Comment by robotboy655** [comment]
Let it update.

**Comment by MokaAkashiya85** [comment]
I use a heavily modified "Customizable Weaponry 2.0" weapon base right now and this is currently happening:
![image](https://user-images.githubusercontent.com/4171878/80402180-d14e7d80-88bd-11ea-8946-75cdb7a665ec.png)
However, if I only have one of them... it works:
![image](https://user-images.githubusercontent.com/4171878/80402219-e5927a80-88bd-11ea-9bc3-61fd05c5da7b.png)
But it also seems like that it does not register accessory category names (might be a problem with the base however): 
![image](https://user-images.githubusercontent.com/4171878/80402578-60f42c00-88be-11ea-80dd-2ad4f25eafe5.png)

I do appreciate that the characters work fine now:
![image](https://user-images.githubusercontent.com/4171878/80402614-6d788480-88be-11ea-8586-877e8afc4740.png)

**Comment by robotboy655** [comment]
You can't use `#text` format for multiple strings. use `language.GetPhrase()`.

Please move all discussion of this to the Discord server now, this is now clearly no longer related to game's development.
