### ISSUE TITLE
Stanley Parable map crash

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4473]
When loading map1:
![](https://user-images.githubusercontent.com/4593679/80295311-81de4500-8737-11ea-92cc-f7267a3cc991.png)

Probably because GMod lacks portal_linked_door. I'm not sure the best way to fix this without adding the entity which obviously requires a lot of internal engine changes to function.

Credit to whatisoven from the Garry's Mod Discord for discovering this.

**Comment by robotboy655** [comment]
Potentially duplicate or related: https://github.com/Facepunch/garrysmod-issues/issues/3744

**Comment by robotboy655** [comment]
Loads perfectly fine for me, but it is a black screen because all the map scripts are broken.

**Comment by robotboy655** [comment]
It probably is fixed with https://github.com/Facepunch/garrysmod-issues/issues/3744
