### ISSUE TITLE
GMPublish Fails to Update Addons

### ISSUE THREAD

**Issue by Darken217** [Facepunch/garrysmod-issues#4475]
### Details
GMPublish (workshop publisher v1.2, compiled March 10th, 2020) is consistently abandoning update processes with an "Update filed! Generic failure" error message when attempting to update an existing addon.

Further, neither dupes nor saves are uploaded and published to the workshop from in-game, printing "steamworks.Publish failed to update file - Generic failure!" into console.

I tested this on default branch, pre-release and x64 on two different PCs with independent Garry's Mod installs (no steam-cloud synch) and experienced these issues consistently.
I tried two .gma files, both for already existing addons. The one I initially wanted to upload is rather large (~450MBs), so I tested a smaller one (~12MBs), however, there was no apparent difference.

Subscribing to and downloading addons from the workshop seems to work as intended.

At the time of writing, I'm not aware of any steam workshop issues or account restrictions.

After thorough research, I was unable to find other reports of the same or similar issues, except for a single steam forum post, released a couple days ago. 
It appears that the issue is obviously not effecting every player, as addons are still being published to the workshop today, though I'm not sure if 3rd-party publishing tools are the reason for that.

### Steps to reproduce
Update existing addon using gmpublish in command line, following the instructions on the gmod wiki page or attempt to publish a dupe or save from within the game.

![image](https://user-images.githubusercontent.com/47533651/80410920-9ce1be00-88cb-11ea-9929-aab2a9b792f5.PNG)

**Comment by robotboy655** [comment]
There's nothing we can do about "Generic Failure" error codes. It comes from Steam. It's a problem on your end.

**Comment by Darken217** [comment]
Ah, I see. 
Unfortunate, but I appreciate the reply.

**Comment by robotboy655** [comment]
You can try using `steamcmd.exe` to upload content to Steam Workshop, simply put a .gma into a folder and point `steamcmd.exe` to that folder. Google for details on how to do the rest.
