### ISSUE TITLE
Gmod Crashing

### ISSUE THREAD

**Issue by Geass321123** [Facepunch/garrysmod-issues#4478]
So i have been having problem with crashing and i was wondering if anyone could help me out by reading the crash dump and tell me what is causing the crashes. Thank you

https://cdn.discordapp.com/attachments/668570666118676506/705628551738556456/hl2_200430_crash_2020_5_1T3_45_3C0.mdmp

**Comment by robotboy655** [comment]
It's a vphysics crash, which we can't really fix due to not having access to its licensed sources.

**Comment by MagentaIris** [comment]
This seems to be a new issue with the beta branch or an update, as this seems to happen with stuff like metastasis_1.bsp when it never used to happen during older updates.

Removing all the prop_dynamics, ropes and overrides using a LUMP editor to edit the bsp fixes this crash although this method is should not be required for maps to simply not crash.

More info here - https://github.com/Facepunch/garrysmod-issues/issues/4374

**Comment by MagentaIris** [comment]
Canals_13 is crashing due to the new update too.
