### ISSUE TITLE
ents.FindInBox() inaccurate on the client

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4480]
### Details
I am doing a simple call to ents.FindInBox to discover entities that are stuck inside a prop.

It works flawlessly on the server, but does not return players on the client.

Weirdly, ents.FindInBox discovers the player in a box of (-9999, -9999, -9999), (9999, 9999, 9999).

I tested this on both the master branch and x86-64 branch with the same results.

### Steps to reproduce
```lua
local ent = Entity(69)
local boxMins, boxMaxs = ent:GetCollisionBounds()
PrintTable(ents.FindInBox(ent:LocalToWorld(boxMins), ent:LocalToWorld(boxMaxs)))
```

**Server**
![](https://cdn.discordapp.com/attachments/567617926991970306/705911692030115851/unknown.png)

**Client**
![](https://cdn.discordapp.com/attachments/567617926991970306/705911767309484063/unknown.png)

**Comment by WilliamVenner** [comment]
OK, even weirder -- if you swap the player and the entity round, it works:

![image](https://user-images.githubusercontent.com/14863743/80847781-c753b400-8c08-11ea-8d68-45a2196664d8.png)

**Comment by WilliamVenner** [comment]
OK things are getting spooky now.

**Server**
```
lua_run print(ME():GetPos())
> print(ME():GetPos())...
861.814636 -222.754791 -90.973106
lua_run print(ME():GetCollisionBounds())
> print(ME():GetCollisionBounds())...
-16.000000 -16.000000 0.000000  16.000000 16.000000 72.000000
lua_run local min,max = ME():GetCollisionBounds() print(ME():LocalToWorld(min), ME():LocalToWorld(max))
> local min,max = ME():GetCollisionBounds() print(ME():LocalToWorld(min), ME():LocalToWorld(max))...
852.328857 -243.297928 -90.973106       871.300415 -202.211655 -18.973106
```

**Client**
```
] lua_run_cl print(ME():GetPos())
861.814636 -222.754791 -90.973106
] lua_run_cl print(ME():GetCollisionBounds())
-16.000000 -16.000000 0.000000	16.000000 16.000000 72.000000
] lua_run_cl local min,max = ME():GetCollisionBounds() print(ME():LocalToWorld(min), ME():LocalToWorld(max))
855.735840 -242.043381 -80.824280	910.750061 -187.685364 -45.459766
```

The values returned by LocalToWorld differ on the client.

**Comment by WilliamVenner** [comment]
**Server**
```
lua_run print(ME():GetAngles())
> print(ME():GetAngles())...
0.000 20.215 0.000
```

**Client**
```
] lua_run_cl print(ME():GetAngles())
39.368 20.215 0.000
```

Must be caused by this

**Comment by WilliamVenner** [comment]
**Server**
```
lua_run print(ME():EyeAngles())
> print(ME():EyeAngles())...
50.104 84.455 0.000
lua_run print(ME():GetAngles())
> print(ME():GetAngles())...
0.000 84.455 0.000
```

**Client**
```
] lua_run_cl print(ME():EyeAngles())
50.104 84.455 0.000
] lua_run_cl print(ME():GetAngles())
50.104 84.455 0.000
```

And here's the fix!

**Comment by robotboy655** [comment]
So basically it does work properly, and the issue is actually on of these: 
https://github.com/Facepunch/garrysmod-issues/issues/2764
https://github.com/Facepunch/garrysmod-issues/issues/3106

**Comment by WilliamVenner** [comment]
That looks pretty major and is unfixed since 2016... rubat plz fix :D

**Comment by robotboy655** [comment]
Wouldn't call it major, but yeah, I also don't know why it was changed to be this way back in 2013 with GMod 13, which is why I never bothered, it might have been for a reason.

**Comment by WilliamVenner** [comment]
@robotboy655 Couldn't you fix this by changing the `ents.FindIn*` functions to use yaw-only angles on the client?

**Comment by WilliamVenner** [comment]
Actually, player collision boxes are always Angle(0,0,0)

**Comment by robotboy655** [comment]
That really just isn't a good solution, and can affect other parts of the engine.
