### ISSUE TITLE
Garry's Mod crushing

### ISSUE THREAD

**Issue by thescs** [Facepunch/garrysmod-issues#4482]
Hello. Help me please. During the game, the game can crash at any moment. Immediately after loading the map, or after 1.5 hours of play, or 10 minutes after loading. FPS is excellent, there are no lags. I tried participating in different beta versions in Steam. Nothing helps. I will attach a link to the last dump, although I already have 197 of them.

[GarrysMod.zip](https://github.com/Facepunch/garrysmod-issues/files/4568182/GarrysMod.zip)

**Comment by robotboy655** [comment]
You are crashing in your nvidia drivers, so update or rollback them.
