### ISSUE TITLE
Server crash on executing AddRelationship( "npc_rollermine" ) on rollermine

### ISSUE THREAD

**Issue by LordofCreepers** [Facepunch/garrysmod-issues#4484]
That's it. When I use Entity:AddRelationship( "npc_rollermine D_LI 1" ) on rollermine, server just crashes

Here's the crashlogs
[crashlogs.zip](https://github.com/Facepunch/garrysmod-issues/files/4574428/crashlogs.zip)

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/80989898-3bc36880-8e3e-11ea-925d-757d35d93179.png)

Yeah thanks 😆 

I couldn't reproduce this. Can you reproduce this in singleplayer?

**Comment by LordofCreepers** [comment]
I didn't try it in singleplayer, but I'll check it later04.05.2020, 20:35, "Rubat" <notifications@github.com>:

Yeah thanks 😆
I couldn't reproduce this. Can you reproduce this in singleplayer?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Баранов
