### ISSUE TITLE
string.sub can't work well with UTF8 chars

### ISSUE THREAD

**Issue by gordonwalkedby** [Facepunch/garrysmod-issues#4486]
### Details
For example: `string.sub("我们都是中国人",1,3)` 
the correct result is "我们都", but in fact , it is "我?".
It's really a problem in our Chinese servers' scripts.

**Comment by GitSparTV** [comment]
Welcome to ASCII.
Lua doesn't support utf8 naturally.
To sub the string (basically any string manipulation) that contains wider characters use utf8 library.

Example:
```lua
local s = string.sub(text, utf8.offset(text, 3))
```

**Comment by robotboy655** [comment]
This would essentially be solved by https://github.com/Facepunch/garrysmod/pull/1400 but yeah, the original string.sub is not going to change to support utf8 properly out of the box.
