### ISSUE TITLE
Game crashed while playing on server

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4487]
### Details
My game closed without any errors when entering a map area on a server.
https://www.dropbox.com/sh/mjicrm18y4yeyf7/AABn9oatcNg3JrVtqYaJbe2Na?dl=0

### Steps to reproduce
I don't know

**Comment by robotboy655** [comment]
Well, again, random dumps are not that helpful.

All I can tell you is that it crashed when trying to render a static prop, and that you seemingly have many model incomatiblities that you should look into:
```
3536(1948.555479):  Error Vertex File for 'props\cs_militia\MailBox01.mdl' checksum -475164032 should be -1411328667
3523(1948.553688):  Error Vertex File for 'props_interiors\Bathtub01.mdl' checksum -1149843431 should be -547076015
3522(1948.553162):  Error Vertex File for 'props\de_nuke\light_red2.mdl' checksum 1304602635 should be -135287182
```

**Comment by mcNuggets1** [comment]
Was on the map rp_southside_day.

**Comment by robotboy655** [comment]
Closing as stale.
