### ISSUE TITLE
crash while joining server

### ISSUE THREAD

**Issue by breezymarie** [Facepunch/garrysmod-issues#4488]
[problem report dump.pdf](https://github.com/Facepunch/garrysmod-issues/files/4582750/problem.report.dump.pdf)

server devs think it might be a new model problem.
we wanted to ask on here just in case.
the only way to reproduce would be to join the server.

**Comment by robotboy655** [comment]
Switch your game to the x86-64 beta branch on Steam.

**Comment by robotboy655** [comment]
Essentially duplicate of https://github.com/Facepunch/garrysmod-issues/issues/888
