### ISSUE TITLE
util.Base64Decode does not work properly

### ISSUE THREAD

**Issue by ZakBlystone** [Facepunch/garrysmod-issues#4489]
### Details
On version `2020.05.01` util.Base64Decode does not fully decode strings generated by util.Base64Encode

Based on some experiments it appears that the newline character emitted every 72 characters by util.Base64Encode causes the decoder to stop. If I encode strings which are less than 55 bytes in length or manually remove the newline characters, the decoder produces the correct output.

Here are my tests:
```
-- Passes
bytes = string.rep("_", 54)
assert( util.Base64Decode( util.Base64Encode(bytes) ) == bytes )

-- Passes
bytes = string.rep("_", 55)
assert( util.Base64Decode( util.Base64Encode(bytes):gsub("\n", "") ) == bytes )

-- Fails
bytes = string.rep("_", 55)
assert( util.Base64Decode( util.Base64Encode(bytes) ) == bytes )
```

**Comment by robotboy655** [comment]
Should be fix
