### ISSUE TITLE
Privacy Policy and TOS on the settings menu return a blank page

### ISSUE THREAD

**Issue by Redbully14** [Facepunch/garrysmod-issues#4491]
### Details
On the latest version (2020.05.08) The Privacy Policy and Terms of Service on the settings menu opens a derma menu, however, it only has a blank white page with no content.

An example of how it looks like can be found here: [https://i.imgur.com/gMRRw6Q.jpg](https://i.imgur.com/gMRRw6Q.jpg).

### Steps to reproduce
- Go into options on the main menu
- Go under Legal
- Press either the Privacy Policy button or the TOS button

**Comment by robotboy655** [comment]
Opens in Steam overlay now, I expect the problem here is Awesomium's support for HTTPS, or lack there of.
