### ISSUE TITLE
Vector __div does not type check its second arg

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4492]
Basically the same issue as https://github.com/Facepunch/garrysmod-issues/issues/2752. ``Vector() / "foo"`` will return ``nil`` instead of throwing an error. Angles do not have this problem.

As a separate but related issue, ``Vector * Vector`` is a valid operation but ``Vector / Vector`` is not. ``Vector:Mul`` and ``Vector:Div`` both only accept numbers, so ``Vector * Vector`` seems to be the odd operation out (it's a nonsense operation really). ``Vector * Vector`` should either be removed or deprecated. ``Angle * Angle`` and ``Angle / Angle`` don't exist as expected.

**Comment by robotboy655** [comment]
Fixed.
