### ISSUE TITLE
Vector/Angle.__newindex does not type check its second arg

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4493]
Non-numbers will be treated as zero.

```Lua
local v = Vector(1, 2, 3)
v[1] = "foo"
print(v) -- 0.000000 2.000000 3.000000
```

I understand fixing this might have issues with breaking prior code, but compatibility was just as big of a concern with https://github.com/Facepunch/garrysmod-issues/issues/2752 which seemed to cause no issues. It should definitely not silently fail.

**Comment by GitSparTV** [comment]
I don't understand the concern of breaking code that is intendedly wrong, it's wrong

**Comment by thegrb93** [comment]
![image](https://user-images.githubusercontent.com/6713261/81488966-24212100-923e-11ea-8dd8-bd69e8ef18c6.png)

**Comment by thegrb93** [comment]
@GitSparTV do you need the joke explained?

**Comment by robotboy655** [comment]
Lets see if it does break something.
