### ISSUE TITLE
Toolgun ghost sometimes getting classified as crazy physics

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4502]
This one took me a while to figure out, but finally realized it was the toolgun ghost.

Crazy origin on entity [68][prop_physics]
	Origin:           [0.000000, 0.000000, -16655.744141]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, -921.915771]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!

**Comment by thegrb93** [comment]
I'm thinking maybe it got unfrozen and fell below the lower bounds of the map.

**Comment by thegrb93** [comment]
This is singleplayer only evidently.

**Comment by robotboy655** [comment]
Do you have a way to reproduce it?

**Comment by thegrb93** [comment]
Equip the toolgun in singleplayer on gm_flatgrass. You can also see its physicsobject falling with :
> print(Entity(68):GetPos(), Entity(68):GetPhysicsObject():GetPos())...
14.826614 23.452156 -12287.718750	0.000000 0.000000 -431.146973

**Comment by thegrb93** [comment]
I'm on x64 branch btw. I haven't tested on default branch.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
