### ISSUE TITLE
OnCursorEntered is breaking DMenu’s SubMenu

### ISSUE THREAD

**Issue by feelingnothing** [Facepunch/garrysmod-issues#4503]
### Derails
Just wanted to edit paint func and add onhover and then i used OnCursor my SubMenu doesn’t open
(im can be dumb and this solves in 1 line on code)

### Steps to reproduce
1. Create DermaMenu
2. Add SubMenu to DermaMenu
3. Edit paint func with OnCursorEntered in it
4. Hover works but SubMenu doesn’t

**Comment by feelingnothing** [comment]
checked: OpenSubMenu does’t improve

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/blob/96b7f5f4c80904098a8674f88db083cc66565ab3/garrysmod/lua/vgui/dmenuoption.lua#L42
As you can see here, `OnCursorEntered` is used to open the submenu, so obviously if you overwrite that the panel is not going to work properly any longer. So don't do it.
