### ISSUE TITLE
Premature removal of dropped weapons in the citadel strippers can crash the game.

### ISSUE THREAD

**Issue by Shadowysn** [Facepunch/garrysmod-issues#4505]
### Details
If a weapon force-dropped by a _**trigger_weapon_strip**_ is removed via outside sources, when a _**trigger_weapon_dissolve**_ attempts to dissolve the now-missing weapon, it crashes the game.

I'm not experienced with getting into the actual nitty-gritty of the source code of HL2, but I did take a look at it, and found no validation checks for the weapons already included into the table.
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/hl2_triggers.cpp#L223

As for the cause, I think it's either a _the-chosen-entity-was-not-valid-to-access-so-I'm-crashing_ situation, accidental _**worldspawn**_ or other _**essential entities**_ fuckery, or an infinite loop _(probably unlikely)_.

### Steps to reproduce
1. Load up a map with a quick-access citadel weapon stripper, either _d3_citadel_03_ or a workshop map.
2. Let your weapons be stripped, then remove at least one weapon.
3. Wait for it to crash.
4. Cleanup map, suicide-respawn and repeat step 2 if it doesn't crash.

Here's a crash dump:
[hl2_200511_crash_2020_5_15T11_40_39C0.zip](https://github.com/Facepunch/garrysmod-issues/files/4634149/hl2_200511_crash_2020_5_15T11_40_39C0.zip)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
