### ISSUE TITLE
GSLT Does not work as described in the wiki

### ISSUE THREAD

**Issue by Bryantdl7** [Facepunch/garrysmod-issues#4512]
### Details
While looking at the wiki for GSLT, we can see the following quote: 

"This feature verifies game ownership, makes sure your clients can connect to your server after IP changes and helps keep fake servers at bay."
https://wiki.facepunch.com/gmod/Steam_Game_Server_Accounts

### Steps to reproduce
0. Ensure all servers involved in testing are running the latest stable branch & my client is up to date
1. Create one vanilla server with GSLT configured correctly 
2. Confirm Steam says the server has logged in with the key 
3. Join the server
4. Favorite the server using the in-game gold star icon visible on the ESC menu 
5. Shut down the server properly 
6. Make necessary firewall port forwarding, copy over necessary files to new server box, etc. 
7. Start server up again under a different IP (this time on my house's internet vs my hosting provider) 
8. Refresh server listing of your favorite servers
9. The same "server" will no longer be in your favorites, as it has a different IP. 

Maybe I am misunderstanding this feature, but I did confirm with booting under each individual server that the last logged in time did indeed update, making me feel something is not working properly. I have feeling more explanation on the implementation of this feature may be necessary. 

This testing was performed on a Garry's Mod server containing no addons. Both servers were able to be connected to without issue, and visible from the server browser.

**Comment by robotboy655** [comment]
It has been confirmed to work by other people already, I imagine it may take time for the server IP to update or w/e, it is entirely handled by Steam, we have no control over it.
