### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Smitfs** [Facepunch/garrysmod-issues#4514]
hi, it's not the first time in 2 days that my server freezes with spam of this line:
NET_BufferToBufferDecompress with improperly sized dest buffer (67108863 in, 134217726 needed)

It is possible that one of the users uses a bug that causes the server to lag.

**Comment by viral32111** [comment]
This is a duplicate of #4483. A fix has already been made for this bug, so make sure your server is updated to the latest version.
