### ISSUE TITLE
Empty error duplicates the previous error

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4515]
### Details
if `error()` or `error(nil)` is run it will return previous raised error without traceback.

### Steps to reproduce
`lua_run error("something")`
after this
`lua_run error()` or `lua_run error(nil)`
![image](https://user-images.githubusercontent.com/5685050/82831574-75c5de80-9ec1-11ea-9a6c-03fca77285c8.png)

**Comment by robotboy655** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/3299036/100011239-1e55ec00-2dda-11eb-931c-8e8b212a59eb.png)

**Comment by GitSparTV** [comment]
Unknown type? Why can't it just __tostring the object like plain Lua does?

**Comment by robotboy655** [comment]
First of all, there's no use for this, you are not meant to send non string errors, secondly the simpler we keep this the less chance something goes nuclear like a custom __tostring erroring.
