### ISSUE TITLE
GetServers Memory Leak

### ISSUE THREAD

**Issue by FunnyCraft** [Facepunch/garrysmod-issues#4516]
I did a little test and found out that with each update of the list of servers my memory increases by 3-10 mb, I use your code as api, but the leak does not allow me to do this efficiently

**Comment by FoksVHox** [comment]
Follow the template when creating issues

**Comment by FunnyCraft** [comment]
Steps to reproduce:
find network game ->
while(true) {
   Refresh internet list servers -> Stop Refresh
}
observe the increase in memory ...

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.
