### ISSUE TITLE
[Sandbox] Dead players still able to move via movement keys.

### ISSUE THREAD

**Issue by Shadowysn** [Facepunch/garrysmod-issues#4517]
### Details
It seems like dead players are not locked out of their movement keys, and are still able to move their invisible player around if their movement puts them into air.
**(looking down and using the backwards key, looking up and using the forwards key, etc.)**
This behavior also allows dead players to somewhat fly.

Normally, this doesn't seem to be really noticeable due to the ragdoll.

Tested on latest non-Dev branch, singleplayer, and with -noworkshop and -noaddons launch parameter.
Also tested on after-steampipe **HL2:DM**. It is not present there.

### Steps to reproduce
1. Suicide.
2. Type **ent_remove_all hl2mp_ragdoll** into the console to remove your ragdoll.
3. Move camera to look down on the ground, then use the backwards key.

Result should be a very noticeable movement of your camera and location.

**Comment by Kefta** [comment]
This is intentional behaviour so spectators can move around in certain gamemodes. This can be fixed on a per-gamemode basis.

**Comment by robotboy655** [comment]
@Kefta Not sure what you are referring to. This can be easily fixed by setting the movetype to MT_OBSERVER and it doesn't break any of the spectate modes.

**Comment by robotboy655** [comment]
This was fixed.
