### ISSUE TITLE
A2S_Info received but server not appearing on Gmod Servers List

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4520]
Hello, @robotboy655 ; @willox 

My Community http://teamfrench.net/ was Very Big in the past proof: https://i.imgur.com/dcRBYko.png
But theses last month we are losing a constant amount of Players, and i Noticed a Huge bug on garry's mod.

The Bug is that Some of Our Servers doesn't appear in the Gmod Servers List !!!
This bug wasn't present in the past, and now is present everytime.

I receive the A2S_Info in my Dedicated Server, but the server doesn't appear in the Gmod Server List

So the only Solution is: To join the server from : Server History

So a lot of our players join the server from server history cause they don't find it most of the time on the Gmod Servers List.

Is that normal? or a Bug?? We lost like 80% of our players community (we had 800 Players daily in the past) and now we are just dying because of this Huge Bug

sv_region is set to 3, and our servers are always optimal and working fine.

I really hope that this bug would be fixed in the next update since our community is dying!

All Our Servers List: http://teamfrench.net/serversboard.php

**Comment by CornerPin** [comment]
Do your servers use Steam tokens?
https://steamcommunity.com/games/garrysmod/announcements/detail/1716372156967158715

**Comment by anyome** [comment]
Yes they do.

**Comment by GitSparTV** [comment]
did you use the same token for all servers?

**Comment by viral32111** [comment]
> sv_region is set to 3, and our servers are always optimal and working fine.

I don't know how the steam region system fully works, but it's probably best to set it to 255 so it shows for everyone, in case any users are using VPNs or any other sort of proxy that's making them appear outside of Europe.

**Comment by GitSparTV** [comment]
@anyome 
> did you use the same token for all servers?

**Comment by anyome** [comment]
> 
> 
> @anyome
> 
> > did you use the same token for all servers?

No, i'm using a different and unique token for each server.

**Comment by robotboy655** [comment]
Attach logs of your server, everything from start up.

**Comment by robotboy655** [comment]
Pretty much all of them are in fact in the server browser:
![image](https://user-images.githubusercontent.com/3299036/83442414-ce145780-a450-11ea-9102-9d6b8ed30fd5.png)
I am too lazy to find the rest.
