### ISSUE TITLE
Issue with WEAPON:OwnerChanged hook

### ISSUE THREAD

**Issue by danx91** [Facepunch/garrysmod-issues#4522]
### Details
When you drop weapon, GetOwner will return "NULL Entity" in OwnerChanged hook - as expected.
When you pick up this weapon, it will return you as owner - also as expected

Problem occurs when you drop weapon, move away (so weapon is no longer in your PVS), then go back. Once weapon appears in your PVS, OwnerChanged hook will be called and GetOwner will return "NULL Entity" (ok, this is understandable because weapon has no owner). OwnerChanged is not called when weapon is picked up.

I'm using the newest version of Garry's Mod, standard branch.

### Steps to reproduce
1. Create simple weapon containing:
`function SWEP:OwnerChanged()
	print( "Owner changed!", self:GetOwner() )
end`
2. Start Sandbox gamemode (it also happens on other gamemodes)
3. Give yourself this weapon
4. Write `lua_run Entity(1):DropWeapon( Entity(1):GetActiveWeapon() )` in console - weapon will be dropped and you will see "Owner Changed! [NULL Entity]" in console.
5. Move away, so weapon is no longer in your PVS
6. Approach this weapon, as soon as weapon is in your PVS, you will see "Owner Changed! [NULL Entity]" in console
7. Pick up weapon, nothing is printed to console.

**Comment by robotboy655** [comment]
Turns out there's two sets of "Owner" functions, one for all entities (`SetOwner` in Lua, `SetOwnerEntity` in engine) and one `SetOwner` in engine which only exists for weapons and `OwnerChanged` hook was mixing them up.

Fixed on Dev.
