### ISSUE TITLE
Clipping issues with drawing a panel in cam3d2d

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4523]
### Details
Drawing panels in 3d world doesn't allow proper clipping.
When turning NoClipping on the panel to false, it works, but corrupts all other drawing.

https://i.imgur.com/tFFnIQv.png

### Steps to reproduce
This code adds an entity to your spawnlists under the GMod category, it pretty much highlights the issue.
https://www.dropbox.com/sh/4bbq5qyrc0c2hes/AADa9vkDLRnsOszo1G1m_MFBa?dl=0

**Comment by robotboy655** [comment]
```
    local oldState = DisableClipping( false )
			self.frame:PaintManual()
    DisableClipping( oldState )
```
That seems to fix it

**Comment by mcNuggets1** [comment]
Could you document it on the wiki somehow?
This behaviour is extremely unpredictable for users trying to render this sort of stuff.

**Comment by thegrb93** [comment]
Pretty much all surface functions exhibit this behavior so its not that unpredictable.
