### ISSUE TITLE
CNavArea:GetClosestPointOnArea can return nil

### ISSUE THREAD

**Issue by lolleko** [Facepunch/garrysmod-issues#4524]
Not sure if this is a bug or just not documented corectly (https://wiki.facepunch.com/gmod/CNavArea:GetClosestPointOnArea does not mention a possible nil return), but GetClosestPointOnArea can return nil instead of a Vector.

**Comment by robotboy655** [comment]
The only way it could return nil is if either you have it overwritten in Lua and that causes issues, or you give it a NULL `CNavArea`, in which case it would error about trying to use a NULL `CNavArea`.

Can you provide steps to reproduce? Show code that you are using?

**Comment by lolleko** [comment]
> The only way it could return nil is if either you (or a mod you have) have it overwritten in Lua and that causes issues

I definitely do not overwrite that function myself. `debug.getinfo(FindMetatable("CNavArea"). GetClosestPointOnArea)` returns `source = [C]` and `lastLineDefined = -1`, so im pretty sure it isn't overwritten by one of my admins either.

> Can you provide steps to reproduce? Show code that you are using?
You can find the code here: https://github.com/lolleko/guesswho/blob/ca5013e2824746db3f64070918b3e23db658cb19/gamemodes/guesswho/entities/entities/gw_npc_walker.lua#L392

Just clone https://github.com/lolleko/guesswho/tree/final-update into our admins folder set
`gw_minseeking 0`, `gw_hideduration 120` and start a round by joining the hiding team.
You will also need to remove the if statement in https://github.com/lolleko/guesswho/blob/ca5013e2824746db3f64070918b3e23db658cb19/gamemodes/guesswho/entities/entities/gw_npc_walker.lua#L394 in order for errors to occur. (Or assert on the return value...)

You might also be able to reproduce it by spam calling the function with random positions? That way you don't have install my addon.

> in which case it would error about trying to use a NULL CNavArea

I doubt that is the case, because I added a print with the return value directly after the `GetClosestPointOnArea` call. That print function reported a vector most of the time and sometimes `nil`. Errors where only reported after that print call once I actually try to use the return value.

No more Lua errors occurred, once I added the if statement in https://github.com/lolleko/guesswho/blob/ca5013e2824746db3f64070918b3e23db658cb19/gamemodes/guesswho/entities/entities/gw_npc_walker.lua#L394

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/84043758-5d6cbe00-a9af-11ea-8c49-247e09a68de7.png)


Apparently it won't complain, but yeah, like I said, the problem is you trying to use the function on an invalid nav area.

**Comment by Kefta** [comment]
Shouldn't it error from using a NULL nav area instead of just returning nil?

**Comment by robotboy655** [comment]
Yes it should, but apparently the internal stuff for Lua bindings is such a massive clusterfuck or many functions that do similar things this went under the radar and changing this now might cause problems for many addons - case and point the addon above.

**Comment by lolleko** [comment]
I think it is fine leaving it this way, but I think it has to be documented. That everything that returns a CNavArea has to be valid/nil checked immediately after the call.

**Comment by lolleko** [comment]
![image](https://user-images.githubusercontent.com/4759511/84195939-b025a300-aa9f-11ea-9af8-8abd807011d7.png)

I tried validating the NavArea isntead of the Vector.
Seems like GetClosestPointOnArea can return nil after all. Very infrequent... but sometimes it returns nil.

**Comment by robotboy655** [comment]
You need to use `IsValid`, man...

**Comment by lolleko** [comment]
Whoops, I am sorry! Like I said it has been a while.
