### ISSUE TITLE
Gmod Font? Launch Crash

### ISSUE THREAD

**Issue by BesKes** [Facepunch/garrysmod-issues#4525]
Whenever I launch Garry's Mod it bring me to the loading screen for a few seconds telling me its adding custom fonts then the game crashes to desktop every time. 
I was using chromium when I launched it then I disabled it and just launched regular Gmod, still crashes. I unsubbed from all addons from steam and it still crashes, I finally reinstall the game and it still crashes. 
Integrity of the game tells me everything is fine.
The crash logs tell me this. 

Executable: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
5(45.915829):  Failed to load custom font file 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\cache\workshop\resource\fonts\clearsans-medium.ttf'
4(44.126742):  Failed to load custom font file 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\download\resource\fonts\clearsans-medium.ttf'
3(16.017013):  	Addon contain game scripts?! Lowering mount priority. (2)
2(15.992752):  Adding Filesystem Addon 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\addons\css_game_content'
1(14.536548):  Attempting to load Chromium...

The font it cannot load is in the place it should be.

**Comment by viral32111** [comment]
>  Failed to load custom font file `c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\cache\workshop\resource\fonts\clearsans-medium.ttf`

> Failed to load custom font file `c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\download\resource\fonts\clearsans-medium.ttf`

Have you tried clearing the cached & downloaded files from servers by deleting the `cache` & `download` folders? (In my experience it's totally safe, but your game will have to redownload files from any servers you play on). Only saying this because it appears to be trying to load the fonts from those folders.

**Comment by robotboy655** [comment]
You need to provide the actual .mdmp/.dmp files if you want this crash looked into.

**Comment by BesKes** [comment]
> You need to provide the actual .mdmp/.dmp files if you want this crash looked into.

https://cdn.discordapp.com/attachments/552958376263286798/719258142017454100/950ccea2-7de1-462c-9da6-f2c2c85fb92f.dmp

**Comment by robotboy655** [comment]
You are crashing when trying to load some language files.
Things you can try in the meantime:
1. Try not using the x64-86 beta branch
2. Try launching the game without any addons: `steam://run/4000//-noaddons%20-noworkshop`
3. Verify game cache ingtergrity: `steam://validate/4000`

The `steam://` links should work in your browser.

**Comment by BesKes** [comment]
> You are crashing when trying to load some language files.
> Things you can try in the meantime:
> 
> 1. Try not using the x64-86 beta branch
> 2. Try launching the game without any addons: `steam://run/4000//-noaddons%20-noworkshop`
> 3. Verify game cache ingtergrity: `steam://validate/4000`
> 
> The `steam://` links should work in your browser.

1. Didn't work crashes the same way.
2. Didn't work crashes the same way.
3. Tells me 6 files failed to validate after they are back game crashes the same and I check the integrity again it tells me 6 files failed again.

**Comment by robotboy655** [comment]
Alright, can you switch to "NONE" beta and give me another crash dump, should be an .mdmp file.

**Comment by BesKes** [comment]
https://cdn.discordapp.com/attachments/552958376263286798/719636076175556629/hl2_200522_crash_2020_6_8T19_35_14C0.mdmp

**Comment by robotboy655** [comment]
It should be fixed on Dev beta branch. Can you confirm?

**Comment by BesKes** [comment]
> It should be fixed on Dev beta branch. Can you confirm?

Dev Branch does work!

**Comment by robotboy655** [comment]
Good.
