### ISSUE TITLE
func_tanklaser + env_laser beam causing weird visual effect upon impact

### ISSUE THREAD

**Issue by MaestroFenix** [Facepunch/garrysmod-issues#4526]
### Details
As seen on the image attached below, the beam fired by a `func_tanklaser` ( which at the same time requires an `env_laser` to work ) causes briefly the original beam sprite to be shown on impact:
![bug](https://user-images.githubusercontent.com/1515562/83977838-ba129f00-a903-11ea-8a21-278551b9ea57.PNG)

( Is easier to be seen on thirdperson / other players - surfaces and with low host_timescale values ).
We can consider this bug to be common on Source as is present on different games and branches.

Garrysmod version: Build 7851
Tried both normal and Dev branches. Vanilla content, no addons.

### Steps to reproduce

1. Load c3a1b or any other map with `func_tanklaser`, and get into range.
2. You don't need the beam to impact on you, it happens with any surface the beam touches.
3. Use `host_timescale 0.4` in case is harder to see the bug.

**Comment by robotboy655** [comment]
This is the exact 1:1 behavior of the original Half-Life, just bigger

![image](https://user-images.githubusercontent.com/3299036/84038159-3ced3580-a9a8-11ea-8058-71f22b22a237.png)

**Comment by MaestroFenix** [comment]
Oh so it happens on GoldSrc too? I guess somehow I missed it.
Well, is kinda "not intended" so if you can look around and see if an easy fix is possible...

**Comment by robotboy655** [comment]
This definitely is an intentional part of the entity.

You can disable that sprite by blocking the `EndSprite` keyvalue on the `env_laser` entity: (before `Spawn`)
```
-- TODO: Select env_lasers that belong to env_tanklaser
hook.Add( "EntityKeyValue", "remove_unwanted_decals", function( ent, key, value )
	if IsValid( ent ) && ent:GetClass() == "env_laser" && key:lower() == "endsprite"  then
		return "" -- Override to nothing
	end
end )
```
