### ISSUE TITLE
Derma model panel modifies the model when it is set on the internal entity.

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#4534]
### Details
Consider the following code
```lua
-- Create `DModelPanel` object
local pnModelPanel = vguiCreate("DModelPanel")
if(not IsValid(pnModelPanel)) then pnFrame:Close()
  asmlib.LogInstance("Model display invalid",gtArgsLogs); return nil end
pnModelPanel:SetParent(pnFrame)
pnModelPanel:SetPos(xyPos.x,xyPos.y)
pnModelPanel:SetSize(xySiz.x,xySiz.y)
pnModelPanel:SetVisible(true)
pnModelPanel:SetName(asmlib.GetPhrase("tool."..gsToolNameL..".pn_display_lb"))
pnModelPanel:SetTooltip(asmlib.GetPhrase("tool."..gsToolNameL..".pn_display"))

-- Go 80 rows down and reference the `DModelPanel`
-- Apply the model on the object by referencing it in another panel element `DListView`
pnListView.OnRowSelected = function(pnSelf, nIndex, pnLine)
  local uiMod =  tostring(pnLine:GetColumnText(5)  or "") -- Actually the model in the table
  local uiAct = (tonumber(pnLine:GetColumnText(2)) or 0); pnModelPanel:SetModel(uiMod) -- Active points amount

  print("OnRowSelected(1)", uiMod)
  print("OnRowSelected(2)", pnModelPanel:GetEntity():GetModel())

end
```
The output is:
```lua
OnRowSelected(1)	models/joe/jtp/throw/harpstand_2_pos.mdl
OnRowSelected(2)	models/harpstand_2_pos.mdl
```
Gmod version is the following running on Windows 7 x64 with beta option set to `NONE`:
![image](https://user-images.githubusercontent.com/9112662/84429137-5acccb80-ac30-11ea-8921-30baa65967b7.png)

### Steps to reproduce
1. Open Gmod
2. Create a frame with `DListView` and `DModelPanel`
3. Code `DListView.OnRowSelected(pnSelf, nID, pnLine)` to call `DModelPanel:SetModel()`
4. `DModelPanel` entity model is set to `models/harpstand_2_pos.mdl`

Where does the `/joe/jtp/throw` go from the model path ?

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/84532033-33d4cf00-acee-11ea-94ad-e015f81543df.png)

So after wasting my time removing all the stuff in your code so I could actually run it, I ended up with this:
```
concommand.Add( "fucking", function( ply )
	local frame = vgui.Create( 'DFrame' )
	frame:SetSize( 500, 500 )
	frame:Center()
	frame:MakePopup()

	local pnListView = vgui.Create( "DListView", frame )
	pnListView:Dock( TOP )
	pnListView:SetTall( 200 )
	pnListView:SetMultiSelect( false )
	pnListView:AddColumn( "Shit" )
	pnListView:AddColumn( "Model" )

	for i=0,200 do
		pnListView:AddLine( "Fuck1" .. i, "models/joe/jtp/throw/harpstand_2_pos.mdl" )
		pnListView:AddLine( "Fuck2" .. i, "models/props_junk/wood_crate001a.mdl" )
		pnListView:AddLine( "Fuck3" .. i, "models/breen.mdl" )
	end

	local pnModelPanel = vgui.Create("DModelPanel", frame)
	pnModelPanel:Dock( FILL )

	pnListView.OnRowSelected = function( self, nIndex, pnLine )
		local uiMod =  tostring(pnLine:GetColumnText(2)  or "") -- Actually the model in the table
		pnModelPanel:SetModel(uiMod) -- Active points amount
		print("uiMod=)", uiMod)
		print("GetModel=", pnModelPanel:GetEntity():GetModel())
	end
end )
```
And I cannot reproduce this problem.

**Comment by dvdvideo1234** [comment]
Hello,

I used your code and created a concmd client side like you did:
![image](https://user-images.githubusercontent.com/9112662/84536385-6a164c80-acf6-11ea-9030-214bfbba00d9.png)

I tried deleting the cache and validating gmod.

**Comment by GitSparTV** [comment]
What is the model? Can you send the workshop link to it

**Comment by dvdvideo1234** [comment]
I think that. 
https://steamcommunity.com/sharedfiles/filedetails/?id=1658816805

**Comment by viral32111** [comment]
> Can I do something to be 100% sure?

Load the game with only that addon enabled and see if it exists in singleplayer, or extract the addon and check if the file for the model exists.

**Comment by dvdvideo1234** [comment]
@viral32111 

I am just gonna extract all the Gma and `dir /s` in the addons/extract folder 😀

**Comment by dvdvideo1234** [comment]
@GitSparTV @viral32111 

```
Garry's Mod Addon Creator 1.1
Opening "F:\Games\Steam\steamapps\common\GarrysMod\garrysmod\addons\joes_track_pack_1658816805.gma"
Extracting Files:
	models/joe/jtp/throw/harpstand_2_pos.dx80.vtx [155.0 KB]
	models/joe/jtp/throw/harpstand_2_pos.dx90.vtx [155.0 KB]
	models/joe/jtp/throw/harpstand_2_pos.mdl [2.8 KB]
	models/joe/jtp/throw/harpstand_2_pos.phy [699 B]
	models/joe/jtp/throw/harpstand_2_pos.sw.vtx [155.0 KB]
	models/joe/jtp/throw/harpstand_2_pos.vvd [770.3 KB]
```

**Comment by mcNuggets1** [comment]
Are you running mac/linux or is your font in general fucked up like this?

**Comment by dvdvideo1234** [comment]
> Are you running mac/linux or is your font in general fucked up like this?

I have unstalled an addon that draws all the text as monospace made by a friend. Super eaay to read. 😊 I did say that I am on Windows 7

https://steamcommunity.com/sharedfiles/filedetails/?id=2110536137

**Comment by robotboy655** [comment]
So yeah, it's a problem with that specific model, specifically this specific part of that specific model:
![image](https://user-images.githubusercontent.com/3299036/84785541-46078380-aff4-11ea-8749-dd098df8644a.png)

This is what GetModel() returns (Because models are stored as indexes internally)
This is what happens when a model gets renamed after compilation.

This is what this looks like on a good model:
![image](https://user-images.githubusercontent.com/3299036/84785678-6e8f7d80-aff4-11ea-901e-10b73f6f5c0f.png)

Here's a relevant function:
https://wiki.facepunch.com/gmod/Entity:SetModelName

**Comment by dvdvideo1234** [comment]
Thank you for finding this. I will leave my addon using the model panel as it is just for such cases.

**Comment by robotboy655** [comment]
Use either `pnModelPanel:SetModel(uiMod); ` which will call SetModelName internally by recreating the entity, or use `:GetEntity():SetModel(uiMod)` + SetModelName on the entity

**Comment by dvdvideo1234** [comment]
I will go for all three, just to be on the safe side. Call `pnModelPanel:SetModel(uiMod);` to create the entity and the other two to configure it.

**Comment by dvdvideo1234** [comment]
@robotboy655 Hmm, do you think that the entity will be created with the model panel ?

**Comment by NickPackham** [comment]
Wanted to update this issue since it seems this is still an occurring issue with Models. Sometimes Models can return differently on Client than on Server, from what I've been told this is because it doesn't use the File-Path of the Model, it uses the MDL path.

Here's a Model Pack to reproduce, just set your Model to 501st Medic then do GetModel() on Server and Client and you'll see different results.
https://steamcommunity.com/sharedfiles/filedetails/?id=2129541240

My results:
![image](https://user-images.githubusercontent.com/46549847/90471508-52cb5500-e0d3-11ea-8bd8-85a6427f56a6.png)
