### ISSUE TITLE
Material new light1 has bad reference count XX after map changed.

### ISSUE THREAD

**Issue by Headshotz** [Facepunch/garrysmod-issues#4535]
I can reproduce it, only you need is download the map link: https://gamebanana.com/dl/365678
its will happen with depend the gamemode for zs link: https://steamcommunity.com/sharedfiles/filedetails/?id=105462463

Firstly, load map called gm_construct then change the map ze_l0v0l_v1_4 with using changelevel command on the console. then changelevel back to gm_construct again then go to under the water and you will have it.

Picture:
https://i.imgur.com/ZH2oCrG.png
https://i.imgur.com/LDhwoym.png

**Comment by robotboy655** [comment]
Should be fixed on Dev.
