### ISSUE TITLE
Models mounting differences to workshop/local addons and steam

### ISSUE THREAD

**Issue by TheNickSkater** [Facepunch/garrysmod-issues#4536]
### Details
This is a rather weird issue I think, but I'm still gonna report it as I now have tested this with 15 Players and everybody had the same issue.

So, everyone knows that we need CSS for many maps and weapons to correctly show their textures and models, many people mount CSS via GMOD ingame if they have CSS installed on steam.. But, and yes I know this is "piracy" of the CSS content, some people have the content installed via Workshop addons or localy..

Problem I, and like I said 15 other people I tested with, had:
When we install the content localy or via an addon from the workshop, some Models are different or at least messed up with their positions.

For example: If I play TTT and buy a C4 and drop it on the ground (not placing it, actually droping with Q) the C4's hitbox is not correctly displayed for me, I do see the C4 but aiming at it and calling GetEyeTrace().Entity on the Server returns nil or worldspawn, because the players client is seeing the model somewhere else as it actually is.. This does NOT happen if you install CSS and mount it via GMOD directly..

**Comment by viral32111** [comment]
Does it happen if you mount cstrike from a CS:S server's content using the mount.cfg config too? Just curious, if it's the case then I might add this to my steam guide.

**Comment by TheNickSkater** [comment]
> Does it happen if you mount cstrike from a CS:S server's content using the mount.cfg config too? Just curious, if it's the case then I might add this to my steam guide.

Hey, I actually did test this. No it does not happen.

**Comment by viral32111** [comment]
Great to know, thanks.

As to why this issue is happening, I've got no idea. Although... I'm just gonna go out on a whim and say the CS:S content you're getting from workshop addons or other websites may simply be corrupted, missing files or straight up edited to make other people's lives more difficult. Ideally content for CS:S should only be aquired through the official sources (the game itself, dedicated server tools, etc.)

I'm kind of curious about this now (and since I've got time to kill :P) do you mind providing a link to which workshop addons/sources you used to get the CS:S content so I can compare it to the actual game shipped content?

**Comment by TheNickSkater** [comment]
> Great to know, thanks.
> 
> As to why this issue is happening, I've got no idea. Although... I'm just gonna go out on a whim and say the CS:S content you're getting from workshop addons or other websites may simply be corrupted, missing files or straight up edited to make other people's lives more difficult. Ideally content for CS:S should only be aquired through the official sources (the game itself, dedicated server tools, etc.)
> 
> I'm kind of curious about this now (and since I've got time to kill :P) do you mind providing a link to which workshop addons/sources you used to get the CS:S content so I can compare it to the actual game shipped content?

I can actually can debunk your theory.. I extracted the whole content out of the original game I have installed with gcfscape and tried it with that.

**Comment by viral32111** [comment]
Huh, so the files from the workshop/other sources do actually match the original game one for one? (I'm unsure how gcfscape works, but I was just going to run a bash script to generate a checksum for every file in the game source and custom source, then just view the diff of it)

**Comment by TheNickSkater** [comment]
> Huh, so the files from the workshop/other sources do actually match the original game one for one? (I'm unsure how gcfscape works, but I was just going to run a bash script to generate a checksum for every file in the game source and custom source, then just view the diff of it)

I dont know if they are exactly the same, but I also dont think that matters, because with the original files it 100% works when mounting it from gmod directly, but it doesnt when installing it localy.. 

But I'm pretty sure there are some addons that actually did the same like me and just made a gma out of it and uploaded it in the workshop.

**Comment by viral32111** [comment]
> because with the original files it 100% works when mounting it from gmod directly, but it doesnt when installing it localy..

When you say "installing it locally", what exactly do you mean? are you adding it as if it was a legacy addon? adding the path to the mount.cfg? etc.

**Comment by TheNickSkater** [comment]
> > because with the original files it 100% works when mounting it from gmod directly, but it doesnt when installing it localy..
> 
> When you say "installing it locally", what exactly do you mean? are you adding it as if it was a legacy addon? adding the path to the mount.cfg? etc.

No I dont. I put the content folder in my Addons folder.
I also tried to upload it in the steam workshop and test it as an addon, but it did not work either.

**Comment by viral32111** [comment]
> No I dont. I put the content folder in my Addons folder.

I'm pretty sure GMod can't mount .vpk files from the addons folder. Though judging by what you said earlier I take it gcfscape is able to extract the resources from those packed files? (If this is the case, then is it possible gcfscape isn't extracting the files properly?)

**Comment by TheNickSkater** [comment]
> > No I dont. I put the content folder in my Addons folder.
> 
> I'm pretty sure GMod can't mount .vpk files from the addons folder. Though judging by what you said earlier I take it gcfscape is able to extract the resources from those packed files? (If this is the case, then is it possible gcfscape isn't extracting the files properly?)

Yes gcfscape is extracting the contents, so no I dont use the vpk files.
Also, yes sure gcfscape could mess something up.. but I am pretty sure it doesnt, cause everything else look normal and works fine.. I mean, how would someone be able to test that.

**Comment by viral32111** [comment]
> I mean, how would someone be able to test that.

No idea how someone could test it, and I just read up a bit on GCFScape & VPK file format, it is litterely just compressed content and GCFScape performs checksum validation of the files so it's pretty safe to assume that the files are exactly as they were in the VPK.

***

> Also, yes sure gcfscape could mess something up.. but I am pretty sure it doesnt, cause everything else look normal and works fine..

> For example: If I play TTT and buy a C4 and drop it on the ground (not placing it, actually droping with Q) the C4's hitbox is not correctly displayed for me, I do see the C4 but aiming at it and calling GetEyeTrace().Entity on the Server returns nil or worldspawn, because the players client is seeing the model somewhere else as it actually is..

Considering these two points, if all the content is visually file and that example stands up then it sounds like an issue with the the entity's/model's collision bounds. The only thing I know that affects this is the model's .phy file and dynamically changing the collision bounds from Lua. But I doubt it's those things (again given what's already been discussed).

Anyway, I should probably shutup and leave this to the people who know what they're talking about 😆

**Comment by TheNickSkater** [comment]
> > I mean, how would someone be able to test that.
> 
> No idea how someone could test it, and I just read up a bit on GCFScape & VPK file format, it is litterely just compressed content and GCFScape performs checksum validation of the files so it's pretty safe to assume that the files are exactly as they were in the VPK.
> 
> > Also, yes sure gcfscape could mess something up.. but I am pretty sure it doesnt, cause everything else look normal and works fine..
> 
> > For example: If I play TTT and buy a C4 and drop it on the ground (not placing it, actually droping with Q) the C4's hitbox is not correctly displayed for me, I do see the C4 but aiming at it and calling GetEyeTrace().Entity on the Server returns nil or worldspawn, because the players client is seeing the model somewhere else as it actually is..
> 
> Considering these two points, if all the content is visually file and that example stands up then it sounds like an issue with the the entity's/model's collision bounds. The only thing I know that affects this is the model's .phy file and dynamically changing the collision bounds from Lua. But I doubt it's those things (again given what's already been discussed).
> 
> Anyway, I should probably shutup and leave this to the people who know what they're talking about 😆

I'm happy you gave out some nice points here still :). I dont know exactly how models and their collision boxes work. But I will point it out here again just in case someone gets confused:
The model works, but just seems to be a bit "off" of where it SHOULD be on the client, NOT the Server, the Server handles everything fine, only the client is not.

**Comment by robotboy655** [comment]
Don't use pirated game content. We cannot help you with any issues if you do. The issue here likely is that GMod ships some of the fixed CSS models, so they appear in your player's hands properly, etc.
