### ISSUE TITLE
Error when deleting an category and revert

### ISSUE THREAD

**Issue by pilot22** [Facepunch/garrysmod-issues#4540]
### Details & steps to reproduce
When you are on the spawn menu, just right click on a category, then click delete.
Then press the green arrow to revert, then this error occurs: 

```
[ERROR] gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua:222: attempt to index upvalue 'CustomizableSpawnlistNode' (a nil value)
  1. func - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua:222
   2. Run - addons/sam-133/lua/includes/modules/hook.lua:198
    3. DoClick - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsidebar.lua:70
     4. unknown - lua/vgui/dlabel.lua:237
```

**Comment by robotboy655** [comment]
This is related to one or more of your addons. I cannot reproduce this without addons.

**Comment by pilot22** [comment]
> This is related to one or more of your addons. I cannot reproduce this without addons.
> 
> Perhaps its your `addons/sam-133`? Perhaps something else.

I will try this without any addons

**Comment by pilot22** [comment]
Can't reproduce without addons, sorry
