### ISSUE TITLE
Projected Texture Positions

### ISSUE THREAD

**Issue by EnderChan7** [Facepunch/garrysmod-issues#4543]
Projected textures don't update their position reliably. This applies to the stock Lamp entities and flashlight as well as any addons that use projected textures. The console doesn't provide any valuable information about this problem. Projected textures don't update the majority of the time, and I believe it has something to do with the new changes to how projected textures are updated.

I found this issue on the "x86-64 - Chromium + 64-bit binaries" beta branch. It occurs on both the 32 and 64 bit versions. It did not occur before the latest prerelease update and when switching to the standard branch, it does not occur.

After switching between versions, verifying game cache, etc, the problem still appears.

**Comment by robotboy655** [comment]
No?

https://files.facepunch.com/rubat/1b1911b1/2020-06-19_21-36-42.mp4

This is recorded on the current x64-64 beta branch.

**Comment by EnderChan7** [comment]
I uninstalled my game and all my addons (because Steam was being awkward) and the problem's gone. I'm not sure what caused it.
Very sorry for wasting your time, good luck with the update.
