### ISSUE TITLE
Unreliable game.MountGMA

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [Facepunch/garrysmod-issues#4545]
### Details
game.MountGMA does not mount all of the GMA's content. The content that isn't mounted include textures used for the UI such as kill icons, weapon icons in the weapon selector, etc. In addition, it seems some particles also aren't being mounted.

### Steps to reproduce
1. Use steamworks.DownloadUGC and game.MountGMA to download/mount something like M9K Specialties.
2. Try to throw some Nitro Glycerine from M9K Specialties.
3. See how the particle effect doesn't show.
4. Scroll to see the weapon icon in the weapon selector for some of M9K's weapons.
5. See how the weapon icon in the weapon selector is purple and black.
6. Kill someone using a weapon from M9K.
7. See how the kill icon is also purple and black.

### More information
M9K is just one of many examples that this mounting bug happens to. Most, if not all addons that contains textures used for the UI or particles will not have those mounted.

**Comment by thegrb93** [comment]
I've noticed this too. Some addons intermittently will have missing textures. I've noticed it commonly happen with @robotboy655 's lightsaber mod.

**Comment by BLEEPBLOOPforLife** [comment]
I've seen it happen with the Lightsabers as well. The lightsaber itself shows up as black with that addon no matter what color it is set to.

**Comment by robotboy655** [comment]
So what you are doing is using `game.MountGMA` on addons that are already on server? No surprise it doesn't work then for certain things, when addons precache models and materials when the player loads before you actually `game.MountGMA` the addons. You should use resource.AddWorkshop like all normal people.

**Comment by thegrb93** [comment]
It's done to allow clients to join faster. Although the addons it doesn't work on currently have to be done with resource.AddWorkshop.

**Comment by robotboy655** [comment]
Join faster to see errors? Or to then sit in a menu telling you to wait for addons to download and also experience issues mentioned above?

I do not see any reason to believe there's a problem with `game.MountGMA`, the suggested "it doesn't load some specific files" issue is nonsensical if you think about it for a second. It's a problem with specific addon's code, not `game.MountGMA`.

There's nothing that I can realistically do about how addons are coded.

**Comment by thegrb93** [comment]
I'm assuming it's because Material() returns an error material if it's called before the mountGMA. I think that's a reasonable limitation. It would be good to document on the mountGMA wiki

**Comment by thegrb93** [comment]
Added the notes https://wiki.facepunch.com/gmod/game.MountGMA
