### ISSUE TITLE
Weird flashlight behavior while DModelPanel is on screen on chromium branch

### ISSUE THREAD

**Issue by EmperorSuper** [Facepunch/garrysmod-issues#4547]
### Details
Whenever there's a DModelPanel on screen in the chromium branch the flashlight gets stuck on different parts of the map, I can't really describe it so here's a [video example](https://www.youtube.com/watch?v=5QzxUG30DfA). I did this with `-noaddons -noworkshop` set and the scripts I ran were for creating and removing the DModelPanel.
I've also tested this on the default branch and the flashlight behaves normally.
Also tried it with models other than the player's current model and it still occurs.

### Steps to reproduce
- Create a model panel.
- Try shining the flashlight on the parts of gm_construct shown in the [video](https://www.youtube.com/watch?v=5QzxUG30DfA) (idk where else this happens).

Here is the code I used to create the panel in the video:
```lua
function CreatePlayerModelPanel()
	if IsValid(PlayerModelPanel) then
		PlayerModelPanel:Remove()
	end
	PlayerModelPanel = nil
	local Size = 130
	PlayerModelPanel = vgui.Create( "DPanel" )
	PlayerModelPanel:SetPos(40, ScrH() - 170)
	PlayerModelPanel:SetSize(Size, Size)
	PlayerModelPanel:SetVisible(true)
	PlayerModelPanel:ParentToHUD()
	PlayerModelPanel:MoveToBack()
	PlayerModelPanel.Paint = function(s, w, h) end

	PlayerModelPanel.PlayerModelPanelModel = vgui.Create("DModelPanel" , PlayerModelPanel)
	PlayerModelPanel.PlayerModelPanelModel:SetModel(LocalPlayer():GetModel())
	PlayerModelPanel.PlayerModelPanelModel:SetSkin(LocalPlayer():GetSkin())
	PlayerModelPanel.PlayerModelPanelModel:SetSize(Size-2, Size)
	function PlayerModelPanel.PlayerModelPanelModel:LayoutEntity( Entity ) return end 
	PlayerModelPanel.PlayerModelPanelModel:SetCamPos(Vector( 16, 0, 65 ))
	PlayerModelPanel.PlayerModelPanelModel:SetLookAt(Vector( 0, 0, 65 ))
end
CreatePlayerModelPanel()
```

**Comment by robotboy655** [comment]
Related issue https://github.com/Facepunch/garrysmod-issues/issues/4543

**Comment by robotboy655** [comment]
Should be fixed on Dev beta branch, other will follow shortly.
