### ISSUE TITLE
Model porting issue

### ISSUE THREAD

**Issue by Ex-Syndicate** [Facepunch/garrysmod-issues#4548]
So when i do porting of a model or a few models all the icons appear as an error and they can't be spawned in, when i load up a map that includes the models i am porting they will be errors, i check the console for something but i always get nothing, I am normally on Chromium but this also happens when i opt out of all betas, I've done all i could to fix this myself, even opening the factory reset .bat and doing a full reset failed to fix my issue.

### Steps to reproduce
Download this example addon and see for yourself: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2137611401

**Comment by Kefta** [comment]
``Model models/kuro/hla/advisor.mdl not a .MDL format file!``
Seems like your model is invalid.

**Comment by Ex-Syndicate** [comment]
But this happens for a lot of models, for example i've tried to port some Black Mesa models and they had the same problems, same with Portal Stories: Mel, so have all of the models i've been trying to port been invalid?
And if so what could be making them invalid?

**Comment by Kefta** [comment]
The header isn't correct, all models start with the constant string ``IDST`` or ``MDLZ`` but yours starts with ``VTF\0``. Crowbar can't decompile it and MDLViewer can't open it - I don't know anything about HL:A's new model format but this won't work with any mainline Source 1 game.

It needs to be compiled to v48 or v49.

**Comment by Ex-Syndicate** [comment]
I just took it from SFM and ported it to Gmod without using Blender or any other program.
I only used GMPT to upload the addon

**Comment by Kefta** [comment]
It must be an issue with how you're porting it, it's unusable in Source games.
