### ISSUE TITLE
I have some general issues and a random segfault that occured when someone left.

### ISSUE THREAD

**Issue by Synkstar** [Facepunch/garrysmod-issues#4550]
### Details
ServerOS: Ubuntu server 20.04
Using pterodactyl so its in a docker container

https://hastebin.com/ifamulajas.shell(This is a gdb stack trace, I had it attached to see what was causing these random segfaults)
Laser tool shadows broke(Shadows render and crash games/cause lag). This update broke many things(More than it fixed)

**Comment by robotboy655** [comment]
"this update" is not released yet. It did not break more than it fixed.

What is "laser tool"?
That segfault couldn't have happened when someone left (or you attached the wrong one), it's a crash when loading a model for the player who just joined. It also doesn't even look like it crashed in GMod code. Potentially an out of memory crash.

**Comment by Synkstar** [comment]
Idk some strange stuff has been happening. I dont think I can really give any info because its fully random.
