### ISSUE TITLE
Segmentation fault on server shutdown

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4551]
### Details

When my server shuts down, a segmentation fault appears. This happens since today's update (24/06/2020).
I'm on a dedicated server running CentOS 7 without any Gmod beta/dev version.
Here is the debug file output : https://cdn.discordapp.com/attachments/701943520302465124/725432719634333786/core.26635

![image](https://user-images.githubusercontent.com/26360935/85619858-32e35c00-b663-11ea-9fbd-2d46305d3d4f.png)

### Steps to reproduce
Type "exit" or "quit" in server console.

**Comment by robotboy655** [comment]
Should be fixed, update your server.

**Comment by FlorianLeChat** [comment]
Works perfectly, thanks!
