### ISSUE TITLE
Special chars in data file names. 

### ISSUE THREAD

**Issue by michak89** [Facepunch/garrysmod-issues#4552]
Good day
I found out that file.Delete() and file.Rename() can't touch files with special chars in their names. 
file.Delete("gęś.txt") - does not work.  I'm not sure if it's a bug. 

Have a nice day, thanks

**Comment by GitSparTV** [comment]
Such files are supported by Windows only, aren't they?

**Comment by viral32111** [comment]
Works perfectly fine for me on Linux.

```
viral32111@lpt:~/Desktop$ echo "gęś gęś gęś" > gęś.txt
viral32111@lpt:~/Desktop$ cat gęś.txt 
gęś gęś gęś
viral32111@lpt:~/Desktop$ file gęś.txt 
gęś.txt: UTF-8 Unicode text
```

**Comment by michak89** [comment]
> Works perfectly fine for me on Linux (xubuntu 20.04).
> 
> ```
> viral32111@lpt:~/Desktop$ echo "gęś gęś gęś" > gęś.txt
> viral32111@lpt:~/Desktop$ cat gęś.txt 
> gęś gęś gęś
> viral32111@lpt:~/Desktop$ file gęś.txt 
> gęś.txt: UTF-8 Unicode text
> ```

Viral, it's about gmod lua not system shell, I do run all servers on linux. I did not mention it's clientside problem, those functions can't touch files like "gęś.txt" on windows, windows client, tested on myself and 3 windows players.

**Comment by viral32111** [comment]
I was responding to Spar's comment: "such files are only supported by Windows only, aren't they?", showing him that Linux also supports filenames like that.

**Comment by Grocel** [comment]
What filenames are supported depend mainly on the filesystem in general. Applications however can have a more limited support for non-English chars either intentionally or unintentionally. GMod's limits are probably a source engine thing. Having support for large charsets in filenames can be a huge can of worms especially in cross platform projects or for data security.

In my projects I generally assume that filenames can be English only with chars that match this regex expression`[a-zA-Z0-9_-]` and have no space characters or any kind of umlauts. That works everywhere. Any exceptions from that (if can not be avoided) needs to be well tested and has to have a well defined error handling (don't let it just throw errors and call it a day).

**Comment by michak89** [comment]
I was convinced that file.Write() can make files with special characters in names cause I found some my data folder.
Now I remembered those were created by my hand years ago. 

Closing this now.
