### ISSUE TITLE
Server crash and restart on shutdown (linux)

### ISSUE THREAD

**Issue by zizou34500lopez** [Facepunch/garrysmod-issues#4555]
### Details
When the server shutdown, it's generate a "Segmentation Fault" and the server restart...

### Steps to reproduce
Type "exit" or "quit" in server console

**Comment by zizou34500lopez** [comment]
![image](https://user-images.githubusercontent.com/26242417/85719436-b8145280-b6ef-11ea-91ea-068c184d0913.png)

**Comment by viral32111** [comment]
Coredumps/minidumps, debug logs and console logs generally help with solving these, so if you could upload those here then that would be great.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4551
