### ISSUE TITLE
If you dock a panel, then try to get it's size, it would get the size as if I was not docked at all.

### ISSUE THREAD

**Issue by phixmeplease** [Facepunch/garrysmod-issues#4559]
### Details
This is pretty much as the title says, when you dock a panel the size stays the same.

### Steps to reproduce
1. Make a (fr )DFrame
2. Make a (frpnl) DPanel, dock fill to DFrame
3. Make a (btn) DButton, dock to frpnl
4. Attempt to center button by doing:
`btn:SetPos(frpnl:GetWide() / 2 - btn:GetWide() / 2, 5)`

It would work just fine if the frpnl sized according to it's dock, but it doesn't. You would still need to manually set the size of the DPanel

**Comment by robotboy655** [comment]
It's not a bug. Docking only updates position/size on the next frame in the PerformLayout hook. So if you need to get the size change immediately, invoke a layout re validation via InvalidateLayout( true )

**Comment by robotboy655** [comment]
This info is even mentioned on the wiki: https://wiki.facepunch.com/gmod/Panel:Dock
