### ISSUE TITLE
BoneLength returns wrong value

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#4563]
[Entity:BoneLength](https://wiki.facepunch.com/gmod/Entity:BoneLength) doesn't seem to return the length of the bone you pass but the length of its parent bone.

**Comment by KingDavidW** [comment]
I believe this is a note on the wiki but doesn't specifically say it takes the parent bone:

> The ID of the bone you want the length of. You may want to get the length of the next bone ( boneID + 1 ) for decent results

**Comment by thegrb93** [comment]
Explains why the root bone has a length of 0.

**Comment by thegrb93** [comment]
I think more bones in the npc bone editor would be messed up if this were the issue though.

**Comment by Ramalayha** [comment]
> Explains why the root bone has a length of 0. I think this function just gets the distance from the selected bone to its parent bone. So since the root bone has no parent, it's 0.

Any bones that have the root bone as parent will also return a length of 0 (for example the thighs on human models) so I don't think it's a distance thing.

**Comment by thegrb93** [comment]
Oh weird. Is this a new issue? I recall the bone editor working fine before (it uses BoneLength). Perhaps make sure an addon hasn't overwritten it.

**Comment by robotboy655** [comment]
The function was not changed and yes, all it does is get the distance between positions of given bone and its parent. Wiki was updated to properly indicate how this function works.

Can't really change what it returns because it will break everything that uses this function.
