### ISSUE TITLE
Secondary ammo visibility is not updated in realtime for default HUD.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#4564]
### Details
Default HUD doesn't update secondary ammo type until weapon is switched (as opposed to primary ammo type, which is updated instantly.)

### Steps to reproduce
1. Get the weapon i've used to test the issue: https://gist.github.com/YuRaNnNzZZ/f3513b3f6f54608a0c23778fa6d687e8
2. Start a game with local server (the example changes ammo types on predicted hooks)
3. Spawn the weapon, Left click changes primary ammo type, right click - secondary, reload key shows current ammo types.
4. Observe that reserve ammo count for primary ammo updates instantly (you can change `smg1` to `none` in weapon code and see that even ammo panel visibilty is updated in real time), while secondary ammo count requires weapon switch first.

https://yurie.thigh-high.club/ts4fivgb.mp4

**Comment by robotboy655** [comment]
Should be fixed on Dev, hopefully without sideeffects.

**Comment by YuRaNnNzZZ** [comment]
Thank you.
