### ISSUE TITLE
Servers cant load png/jpg with Material

### ISSUE THREAD

**Issue by Benn20002** [Facepunch/garrysmod-issues#4566]
I want to use a png with util.SpriteTrail but I found that when I try loading a png with Material() it does not work serverside ("Material [___error]") however it does work clientside.
I am sure that my path is correct as it works with a vtf and vmt in the same folder.

How to reproduce: 
Add a png to the materials folder and run `print(Material("path/to/image.png"))` serverside

Server version: 2020.03.17/24 7794 (windows)
Client version: 2020.06.26 (windows)

**Comment by robotboy655** [comment]
> I want to use a png with util.SpriteTrail

You can't, even if Material() worked with .png textures serverside, which would be completely useless, even in your case.

All `util.SpriteTrail` does is send the string you give it to the client (through the entity it creates), and the client then uses that string to actually draw with the material.
Doing something like `Material("path/to/image.png"):GetName()` or whatever you wanted to do will not do anything for you, the clientside part of util.SpriteTrail simply will not find the material. It **must** be a .vmt material.

You might be able to get away with making a material clientside with a name like "obviouslyfakeVMTforTrail1" that points to a .png texture and then using that name serverside for `util.SpriteTrail` but I doubt that will work.
