### ISSUE TITLE
issue with weapon_357

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-issues#4571]
when you use weapon_357 and shot, then quickly move your camera to something, the camera will move back to the same position, here is example of this old video in HL2DM:
https://youtu.be/pVt5aUOBckg
this issue exist in all games that use Source SDK 2013, and caused by SnapEyeAngles

**Comment by robotboy655** [comment]
Have you actually tested it in GMod? That is, in multiplayer?
