### ISSUE TITLE
Calling Player:PickupObject on an entity already being held will put the entity in an invalid state

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#4574]
The entity will be constrained to a specific spot (not frozen, just constantly jump back to it) and it cannot be picked up again. This was noted on the old wiki: https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index03af.html
```
If called for a player while an entity is already held, the first entity will still be stuck mid air and cannot be held again.
```

**Comment by robotboy655** [comment]
Fixed, force drops the object before trying to pick it back up.
