### ISSUE TITLE
Many lua things need to be fixed

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-issues#4575]
```lua
-- https://wiki.facepunch.com/gmod/ents.FindInPVS

local ply1 = player.GetAll()[1]
local pvs_tb = ents.FindInPVS(ply1)
PrintTable(pvs_tb) -- wtf? PVS?

-- Returns all entity?
```
https://i.imgur.com/xLsgG1K.png
https://i.imgur.com/wyBqm6V.png

---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/Global.SoundDuration

function SWEP:Reload(  )
	if not IsFirstTimePredicted() then return end

    local snddur = SoundDuration("sw_weapons/dlt20a_fire.wav") --Return x2 duration on server if using in Weapon Reload, wtf?
    print(snddur)
end
```
https://i.imgur.com/ikepOJ7.png

---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/render.SetLightingMode -- Example 2
-- Display everything the same way as when you set mat_fullbright to 1. This does not work as it should.
-- Problems with textures, screenshots below
-- FIX THIS PLS!

local LightingModeChanged = false
hook.Add( "PreRender", "fullbright", function()
	render.SetLightingMode( 1 )
	LightingModeChanged = true
end )

local function EndOfLightingMod()
	if LightingModeChanged then
		render.SetLightingMode( 0 )
		LightingModeChanged = false
	end
end
hook.Add( "PostRender", "fullbright", EndOfLightingMod )
hook.Add( "PreDrawHUD", "fullbright", EndOfLightingMod )
```
https://i.imgur.com/EduzsJV.png
https://i.imgur.com/LP3ySYT.png

---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/Global.ClientsideRagdoll

local ragdoll = ClientsideRagdoll("models/sw_playermodels/droids/bx/bx.mdl")
ragdoll:SetNoDraw(false)
ragdoll:DrawShadow(true)

local lply = LocalPlayer()
ragdoll:SetPos(lply:GetPos() + lply:GetUp() * 250)

print(ragdoll)
-- Created but not drawing
-- If use half life models it works correctly
-- Also I did this on server side util.PrecacheModel("models/sw_playermodels/droids/bx/bx.mdl") 
```
---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/NPC:NavSetGoal -- Not warking at all

-- ENUMS
GOALTYPE_NON					= 0
GOALTYPE_TARGETENT				= 1
GOALTYPE_ENEMY					= 2
GOALTYPE_PATHCORNER				= 3
GOALTYPE_LOCATION				= 4
GOALTYPE_LOCATION_NEAREST_NODE	= 5
GOALTYPE_FLANK					= 6
GOALTYPE_COVER					= 7
GOALTYPE_INVALID				= 8

function NPC:NavSetGoal( origin ) -- My fix
	self:SetSaveValue("m_vecStoredPathGoal", origin)
	self:SetSaveValue("m_nStoredPathType", GOALTYPE_LOCATION)
	self:SetSaveValue("m_fStoredPathFlags", 0)
	self:SetSaveValue("m_hStoredPathTarget", nil)
end
```
---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/NPC:SetNPCState -- It works incorrectly

function NPC:SetNPCState( state ) -- My fix
	self:SetSaveValue("m_NPCState", state)
	self:SetSaveValue("m_IdealNPCState", state)
end
```
---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/Entity:GetBonePosition -- It works incorrectly if model have many bones or? 

-- https://wiki.facepunch.com/gmod/Entity:InvalidateBoneCache -- Doesn't help
-- https://wiki.facepunch.com/gmod/Entity:SetupBones -- Doesn't help

-- https://wiki.facepunch.com/gmod/Entity:FollowBone -- Strange fix 

ent:FollowBone(parent, bone_id)
ent:SetParent(nil)

-- After that the Entity:GetBonePosition works correctly
```
---------------------------------------------------------------
```lua
-- https://wiki.facepunch.com/gmod/WEAPON:ShootEffects -- Example on whis page works incorrectly if next fire faster than animation
-- https://wiki.facepunch.com/gmod/Weapon:SendWeaponAnim -- It works incorrectly


function SWEP:ShootEffects( vmact ) -- Very strange fix
    local vm = self.Owner:GetViewModel()
    local idle = vm:SelectWeightedSequence(ACT_VM_IDLE)
    local fire = vm:SelectWeightedSequence(vmact or ACT_VM_PRIMARYATTACK)

    idle = idle == -1 and 1 or idle

    vm:SendViewModelMatchingSequence(idle)
    vm:SetPlaybackRate(0)
    vm:SetCycle(0)

    timer.Simple(0, function() -- Need a different context??? but its working
        vm:SendViewModelMatchingSequence(fire)
        vm:SetPlaybackRate(1)
        vm:SetCycle(0)
    end)

    self.Owner:MuzzleFlash()
    self.Owner:SetAnimation(PLAYER_ATTACK1)
end
```

**Comment by robotboy655** [comment]
One "thread" per problem please.

1) That's not how PVS works. Try going into the secluded room on flatgrass and run it from there. It will only "see" entities inside the room.
2) Duplicate of #936
8) Duplicate of #3229

**Comment by arkayden** [comment]
> One "thread" per problem please.
> 
> 1 - That's not how PVS works. Try going into the secluded room on flatgrass and run it from there. It will only "see" entities inside the room.
> 2 - Duplicate of #936
> 8 - Duplicate of #3229

Должен ли я заново отправить эти проблемы разделив их или это информация на будущее?

1 - Странно, не знал что это так работает, спасибо.

2 - Про дубликаты, это неверно, так как в нашем примере имеет значение контекст вызова функции, это отличается от того что скидывал тот человек. Различаются значения на сервере и на клиенте. Автор того сообщения не использовал util.PrecacheSound или данного звука не было на сервере, поэтому функция возвращала неверное значение. 

8 - Это иная проблема связанная с той же функцией. Есть решение вызвать эту же функцию в это же время из другого контекста, обратите внимание на код. Возможно этот кусок поможет вам решить эту проблему.

**Comment by Kefta** [comment]
The causes of 2 and 8 are probably the same, regardless of your differing code.

**Comment by robotboy655** [comment]
I have looked into the others and:
3) Could not reproduce, your code does not cause the issues pictured on the maps I have tried (gm_construct for example), and you didn't provide a map name.
4) Could not reproduce again, you didn't provide a link to the model, or describe your testing environment. I tried with a non precached TF2 ragdoll
5) Can confirm
6) Your "fix" does the exact same thing as the function does internally, so I am not sure what the issue here is
7) There's probably an issue with it yeah, I remember having a conversation about a similar thing with Spar on Discord

**Comment by arkayden** [comment]
3) Как пример - https://steamcommunity.com/sharedfiles/filedetails/?id=1829795551, работает и на других.
gm_construct for example?
mat_fullbright 0 - https://i.imgur.com/axLdW2a.png
mat_fullbright 1 - https://i.imgur.com/K4WMKEr.png
example - https://i.imgur.com/akMwypI.png

4) Это действительно работает со всеми моделями, похоже что проблема с SetPos для CSEntity [class C_ClientRagdoll].

6) Я не могу вспомнить на каком именно этапе происходит проблема. Связана она с какими-то engine schedules где происходит возврат в m_IdealNPCState. Ниже превел строчки из sdk которые помогли мне понять в чем проблема.
**Lines 102 and 126**
https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/mp/src/game/server/ai_basenpc_movement.cpp

----------------------------------------------

Спасибо за то, что вы делаете для Gmod'a. Возможно эти ошибки не столь серьезны, однако они доставили нам много проблем.
