### ISSUE TITLE
util.TableToJSON seems to round down numbers when they are small enough

### ISSUE THREAD

**Issue by diogo464** [Facepunch/garrysmod-issues#4576]
Running `lua_run_cl print(util.TableToJSON({number = 0.00001}))` outputs `{"number":0.0}` 
but running `lua_run_cl print(util.TableToJSON({number = 0.0001}))` will output `{"number":0.0001}`

I expected `lua_run_cl print(util.TableToJSON({number = 0.00001}))` to output `{"number":0.00001}`  or `{"number":1e-5}`

**Comment by robotboy655** [comment]
Should be fixed on Dev.
