### ISSUE TITLE
DScrollPanel's canvas call parent's PerformLayout without arguments

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4577]
Not exactly a bug but a design fault (since it is unknown what to pass to said function, if garry didn't specified parent's GetSize())

![Code_MkwqhHTPdW](https://user-images.githubusercontent.com/6339511/87246931-ce096d80-c47a-11ea-9fc4-14a055dab7af.png)
![Code_no9xvbex9E](https://user-images.githubusercontent.com/6339511/87246932-cf3a9a80-c47a-11ea-9802-1bc77bd082f4.png)
![gmod_D7POX89DpK](https://user-images.githubusercontent.com/6339511/87246933-d06bc780-c47a-11ea-93b9-7821790bd5d7.png)

https://github.com/Facepunch/garrysmod/blob/3aaf6d460f4be91788908c18586ce1476dfd01c4/garrysmod/lua/vgui/dscrollpanel.lua#L14

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/5293fd836025b796d67a4554c2bf9bcc6d6e2944

https://github.com/Facepunch/garrysmod/commit/59d10671adcb17e24e568bd21faca931e9e371fb
