### ISSUE TITLE
sound.PlayUrl not working correctly on linux(x64)

### ISSUE THREAD

**Issue by Synkstar** [Facepunch/garrysmod-issues#4579]
### Details
OS: Arch linux
Branch: x86-64(Using 64 bit)

If you try and play mp3s or .wavs(Tested it) using sound.PlayUrl it does not play. Even the media player doesnt play mp3s but works correctly with youtube videos. 

Doesnt work on regular 32 bit either

**Comment by robotboy655** [comment]
What URL(s) are you testing? What is the "media player" you are talking about? Some addon? How do YouTube videos come into play with sound.PlayUrl which can't and won't be able to play them?

**Comment by Synkstar** [comment]
Its strange. Its direct mp3 like it comes up with a raw file. Its very strange.

**Comment by Synkstar** [comment]
Works on windows perfectly.

**Comment by Kefta** [comment]
Could you link it directly?

**Comment by Synkstar** [comment]
It is linked directly off my own webserver and I tried drop box like I said people on windows can hear it perfectly fine. I tried the stream core e2 aswell and people on windows can hear that too but not me.

**Comment by Kefta** [comment]
No, could you link them on this GitHub issue?

**Comment by Synkstar** [comment]
https://nasulex.net/xfiles.mp3
For dropbox I was using ?raw=1 
My urls are correct doesnt work with pac either but works on windows.

**Comment by robotboy655** [comment]
It's likely due to the HTTPs, but I am not sure.

**Comment by viral32111** [comment]
If he's using x64 branch, shouldn't modern HTTPs *not* be a problem because the branch uses Chromium?

**Comment by Synkstar** [comment]
It loads images, html, etc from https perfectly fine so it cant be that.

**Comment by Synkstar** [comment]
[PAC3] Failed to load (INSERT URL) (3d noplay noblock) - BASS_ERROR_NO3D
I get these if I try to use them with pac3 but works perfect on windows

**Comment by robotboy655** [comment]
BASS and Chromium are completely unrelated to each other.

**Comment by Synkstar** [comment]
[console.log](https://github.com/Facepunch/garrysmod-issues/files/4963305/console.log)

**Comment by Synkstar** [comment]
Yeah this is strange. I also have a laptop with arch and it works on the 32 bit version but on the 64 bit it breaks all of the audio. 
Guessing that has something to do with #3326

**Comment by Synkstar** [comment]
This is something related to linux and is outside of the game so im going to close this issue. I got it to play by updated the bass binary and first loading it without the bluetooth then switching it. Kind of strange

**Comment by MonkaSC** [comment]
jarvis, show me what 0 pussy looks like
