### ISSUE TITLE
Invisible cursor 

### ISSUE THREAD

**Issue by DorkyWasTaken** [Facepunch/garrysmod-issues#4580]
I can't see my mouse in [x86-64 - chromium] and other versions I tried everything and every guide on steam that I could find but no use, https://youtu.be/timgQg4btbc

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

Make sure you have no cursor trails enabled, etc, etc.
