### ISSUE TITLE
Auto disconnected every time I join a server 

### ISSUE THREAD

**Issue by DorkyWasTaken** [Facepunch/garrysmod-issues#4581]
Basically everytime I join into a server it tells me that it's going to auto disconnect me, my internet is fine and everything is good but the problem is game just keeps saying "auto disconnecting in [number] seconds" like bruh I just want to play Tt
TT in peace, I've also looked everywhere in every single guide and still no answer. And so basically I'm trying to say is Fix It please

**Comment by viral32111** [comment]
If your internet is working perfectly fine, then it's probably an issue with the server (in which case all players on that server would also get it). The auto-disconnect in *x* seconds popup occurs when you unexpectedly lose connection to the server.

If this is happening with you on all servers though, then it's more likely that it is infact an issue with your internet stability/connection. I've never come across a bug in the game where the auto-disconnect popup has been wrong.

**Comment by FoksVHox** [comment]
The only time have I come across this is when I first join a new server, but it goes away as soon as I'm fully loaded into the server. This seems like an issue at your end.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
