### ISSUE TITLE
spawnmenu.SaveToTextFiles() and dupe save functions are being abused.

### ISSUE THREAD

**Issue by AppleVegas** [Facepunch/garrysmod-issues#4584]
Hello! Not really used to filling bug reports, but this one really made me want to do it.
Today i discovered that some piece of crap server is making people's lifes hell by saving files outside of DATA directory. 
It saves files in /garrysmod/settings/spawnlist using spawnmenu.SaveToTextFiles(table) function. And that leads to corrupted spawnmenu (see attached image)
![unknown](https://user-images.githubusercontent.com/40367739/87470423-69d6dd00-c625-11ea-94bd-21f832bccb2d.png)
Also it saves files in /garrysmod/dupes/ directory abusing dupe save functions that also cause corruptions. (second attached image)
![Screenshot_125](https://user-images.githubusercontent.com/40367739/87470581-a276b680-c625-11ea-9e7d-7104de5fe51a.png)
Please ban this server's iP and restrict these functions so they can't be used outside of the spawnmenu.

![Screenshot_126](https://user-images.githubusercontent.com/40367739/87470733-e073da80-c625-11ea-8953-fa56ea85a8f7.png)

### Steps to reproduce
Join 46.174.55.241:1337 - server that breaks stuff intentionally.

**Comment by NeptuneOkayasu** [comment]
thanks for screwing up ur gmod setup to help us out, lets hope this russian gets his server banned

**Comment by viral32111** [comment]
Couldn't functions like this be possibly moved over to menu state? Addons that add their own model spawnlists would still use the .txt files, and players could still customise their personal spawnlists.

**Comment by GitSparTV** [comment]
They can't be moved because you can edit spawnmenu directly from it.

**Comment by robotboy655** [comment]
Not really anything we can do about the abuse, only to discourage it. I have blacklisted that server.
