### ISSUE TITLE
Parent to bone interpolation issue

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4586]
### Details
I make shield and parent it to bot. But it moving jittery. Then I create ragdoll and parent prop to ragdoll bone. Still moving jittery. But this will not appear if GUI active or i held ragdoll with physgun. I cannot imagine this behaviour.

I think this related to interpolation, because it trying move entity to compensate latency. **cl_interp** will affect on that.

See this to understand: https://youtu.be/fzSPYakf2LE

### Steps to reproduce
1. Create ragdoll
2. Create other prop
3. Parent prop to ragdoll using this

	_prop_:SetParent(_ragdoll_,4)
	_prop_:AddEffects(EF_FOLLOWBONE)
	_prop_:PhysicsDestroy()
	_prop_:SetLocalPos(vector_origin)
	_prop_:SetLocalAngles(angle_zero)

4. Try move ragdoll

**Comment by robotboy655** [comment]
You can solve this by reading the note on this page: https://wiki.facepunch.com/gmod/Entity:FollowBone

You should also use the function directly instead of imitating it, AddEffects and SetParent are not the only things it does.

**Comment by ShadowBonnieRUS** [comment]
Using FollowBone does not help. Also wiki says use SetPredictable(true), it solves problem, but predictable ragdolls has other issue (it start moving like low framerate and there shadow problems from projectedtextures) and also #4593 with nextbots.

**Comment by robotboy655** [comment]
Solved in https://github.com/Facepunch/garrysmod-issues/issues/4821
