### ISSUE TITLE
Weapon:SetClip does nothing on newly spawned weapons which provide extra ammo on initial pickup

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4589]
Minimal code to reproduce:
```lua
local wep = ents.Create('weapon_shotgun_hl1')
wep:SetPos(Entity(1):EyePos())
wep:Spawn()
wep:SetClip1(0)
```
![gmod_SDBqfK6eFe](https://user-images.githubusercontent.com/6339511/87794389-bf52fa00-c870-11ea-94b9-348b21cb21ff.png)

Minimal code to prove that weapons without extra ammo work as expected:
```lua
local wep = ents.Create('weapon_pistol')
wep:SetPos(Entity(1):EyePos())
wep:Spawn()
wep:SetClip1(0)
```
![gmod_F1yOlJuoVC](https://user-images.githubusercontent.com/6339511/87794189-7ac75e80-c870-11ea-8860-5ccef90d5c67.png)

It also applies to scripted weapons (e.g. scripted weapons which do not provide extra ammo on pickup work as expected too)

This applies **only** to newly spawned weapons. Calling SetClip on weapons which were dropped by players after initial pickup (e.g. using Player:DropWeapon will behave as expected)

**Comment by robotboy655** [comment]
This is how DefaultClip works in Source Engine, it sets the Clip1 to min( MaxClip1, DefaultClip ) on initial pickup and the rest is awarded as reserve ammo.

**Comment by DBotThePony** [comment]
But when clip is initially set as MaxClip1 bug does not occur

**Comment by robotboy655** [comment]
You can see the code yourself here:
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/basecombatcharacter.cpp#L2106-L2110

"when clip is initially set as MaxClip" means the weapon does not have DefaultClip set, like weapon_pistol

This is normal behavior. It's not a bug.

**Comment by DBotThePony** [comment]
According to code you provided it gonna **always** award extra ammo when gun is picked up, which means gmod has this function modified to not award ammo when weapon already did that.

What does stop you from doing the same when someone modified clip? (also you can see that weapon's clip after creation is **already** set to DefaultClip. Why can't you just utilize clip's value directory instead of always checking for DefaultClip?)

**Comment by robotboy655** [comment]
Kinda afraid this will negatively impact some weapons, but we shall see I guess. Make SetClip1/2 not give out reserve ammo/reset the clips on pickup.
