### ISSUE TITLE
ENT:GetRenderMesh() matrix lighting issue

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#4590]
The render mesh always uses the lighting at the entity's origin but it would make more sense if it used the lighting at the matrix's position when one is provided.

**Comment by robotboy655** [comment]
You can offset your model/matrix so that the center of the entity is inside where you want the lighting origin to be.

You also have this, albeit serverside only: https://wiki.facepunch.com/gmod/Entity:SetLightingOriginEntity

**Comment by Ramalayha** [comment]
Any possibility to get SetLightingOrigin clientside then?

**Comment by robotboy655** [comment]
You have this https://wiki.facepunch.com/gmod/render.SetLightingOrigin which you can use in your `ENT:Draw`

**Comment by Ramalayha** [comment]
I see, thanks.
