### ISSUE TITLE
People crashed when joined Server

### ISSUE THREAD

**Issue by baptiste-fourmont** [Facepunch/garrysmod-issues#4595]
Lua Stack Traces-
==================
  Client
    Not in Lua call OR Lua has panicked

  Server
    Lua Interface = NULL

  MenuSystem
    Not in Lua call OR Lua has panicked

Hello, recently I noticed a drastic drop in players on several since the new update of Gmod. Several communities have the same problem of player crashes during connection. (About 1/3 of player logins crash and receive this error)

**Comment by baptiste-fourmont** [comment]
Precisely at the end of the connection

**Comment by Kefta** [comment]
Can you post actual crash dumps?

**Comment by baptiste-fourmont** [comment]
Yes

**Comment by baptiste-fourmont** [comment]
Fucked, I'm stupid it's because we didn't update hosting servers and it actually provocates that

**Comment by robotboy655** [comment]
The crash is already fixed.
