### ISSUE TITLE
Some NPCs have incorrect health

### ISSUE THREAD

**Issue by Dobbi124** [Facepunch/garrysmod-issues#4597]
### Details
Certain NPCs have max health issues. I am currently using an addon made by myself to track the health of entities. Certain ones are buggy with some having their max health exceed their actual health, or some with no max health at all. Just to prove that this addon is working and functional, I included a picture of a Combine Soldier at the bottom along with the other photos to show that its health is correctly displayed and that this addon is not causing the problems. I'll also describe every picture to clarify what's wrong with the entity in question.

**Combine Camera:** Has 50/0 health when it should have 50/50 HP.
**Combine Ceiling Turret:** Has 1000/0 health when it should have 1000/1000 HP.
**Combine Dropship:** Has 100/0 health when it should have 100/100 HP.
**Combine Helicopter:** Has 600/5600 health when it should have 600/600 HP.
**Antlion Grub:** Has 1/0 health when it should have 1/1 HP.
**Barnacle:** Has 35/0 health when it should have 35/35 HP.
**The Magnusson:** Has 14/1 health when it should have 14/14 HP
**Combine Mine:** Has 100/0 health when it should have 100/100 HP
**Zombine Grenade:** Has 1/0 health when it should either have 1/1 HP or no HP at all

### Steps to reproduce
1. Download any health and spawn in the entities mentioned to verify the health or look into their code and look at their health

![20200724001113_1](https://user-images.githubusercontent.com/34899129/88360454-bfa53680-cd43-11ea-924c-2edd671ab57a.jpg)
![20200724001121_1](https://user-images.githubusercontent.com/34899129/88360460-c2079080-cd43-11ea-9698-65f46f940aa3.jpg)
![20200724001233_1](https://user-images.githubusercontent.com/34899129/88360464-c3d15400-cd43-11ea-9505-5822fe765ded.jpg)
![20200724001321_1](https://user-images.githubusercontent.com/34899129/88360466-c59b1780-cd43-11ea-9997-4ee2a2f49007.jpg)
![20200724001631_1](https://user-images.githubusercontent.com/34899129/88360467-c6cc4480-cd43-11ea-971f-79351252c4ae.jpg)
![20200724001635_1](https://user-images.githubusercontent.com/34899129/88360468-c8960800-cd43-11ea-96ef-561253d82f54.jpg)
![20200724001641_1](https://user-images.githubusercontent.com/34899129/88360470-c9c73500-cd43-11ea-81ee-cdeb29ed04ce.jpg)
![20200724001650_1](https://user-images.githubusercontent.com/34899129/88360473-cb90f880-cd43-11ea-9052-e7c88de68004.jpg)

![20200724002545_1](https://user-images.githubusercontent.com/34899129/88360603-5114a880-cd44-11ea-89f1-419c3168031c.jpg)

**Comment by ShadowBonnieRUS** [comment]
I think MaxHealth value not used in entity logic, so there no reason to set MaxHealth value.

**Comment by robotboy655** [comment]
I have added max health for most of these and some more, but not for grenades and the mine, they are not NPCs.

**Comment by Kefta** [comment]
They're still technically BaseCombatCharacters
