### ISSUE TITLE
DScrollPanel issue

### ISSUE THREAD

**Issue by Dimantio** [Facepunch/garrysmod-issues#4598]
This change [here](https://github.com/Facepunch/garrysmod/commit/59d10671adcb17e24e568bd21faca931e9e371fb#diff-617e814d298fcc0907b06f35920cd0abR14) is preventing DIconLayout's childs from updating properly. Changing it to wait for the next frame fix the issue.

### Steps to reproduce

Try the example from the wiki itself

```
local Frame = vgui.Create( "DFrame" ) -- Create a Frame to contain everything.
Frame:SetTitle( "DIconLayout Example" )
Frame:SetSize( 365, 240 )
Frame:Center()
Frame:MakePopup()

local Scroll = vgui.Create( "DScrollPanel", Frame ) -- Create the Scroll panel
Scroll:Dock( FILL )

local List = vgui.Create( "DIconLayout", Scroll )
List:Dock( FILL )
List:SetSpaceY( 5 ) -- Sets the space in between the panels on the Y Axis by 5
List:SetSpaceX( 5 ) -- Sets the space in between the panels on the X Axis by 5

for i = 1, 20 do -- Make a loop to create a bunch of panels inside of the DIconLayout
	local ListItem = List:Add( "DPanel" ) -- Add DPanel to the DIconLayout
	ListItem:SetSize( 80, 40 ) -- Set the size of it
	-- You don't need to set the position, that is done automatically.
end

local ListLabel = List:Add( "DLabel" ) -- Add a label that will be the only panel on its row
ListLabel.OwnLine = true -- The magic variable that specifies this item has its own line all for itself
ListLabel:SetText( "Hello World!" )

for i = 1, 5 do
	local ListItem = List:Add( "DPanel" )
	ListItem:SetSize( 80, 40 )
end
```

**Comment by Dimantio** [comment]
I've found a few addons who are breaking due to this change as well, they end up in a loop of updating itself over and over. Maybe undoing this change would be best for compatibility?

**Comment by DBotThePony** [comment]
Those changes fix https://github.com/Facepunch/garrysmod-issues/issues/4577

**Comment by DBotThePony** [comment]
Actually commenting out `self:InvalidateLayout( true )` or passing `layoutNow` as `false` fix the issue

**Comment by Dimantio** [comment]
Yeah that's what I said altho, I also noticed some addons having some issues with returning false for layout as well. I guess we can't have best of both world I would assume compatibility would be best but it's not my call.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
