### ISSUE TITLE
Tick, Think hooks and timers run even sv_hibernate_think is set to 0

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4599]
### Details
The `Think`/`Tick` hooks and `Timers` keep running when `sv_hibernate_think` ConVar is set to `0` and there are no more players on the server. However, the wiki says the opposite clearly : [GM:Think](https://wiki.facepunch.com/gmod/GM:Think), [GM:Tick](https://wiki.facepunch.com/gmod/GM:Tick), [Timers](https://wiki.facepunch.com/gmod/timer.Create).

**=> Tested without addons in Sandbox gamemode.**

### Steps to reproduce

- Start a dedicated server.
- Run this code :
```lua
hook.Add("Think", "test1", function()
    print("GM:Think", CurTime())
end)

hook.Add("Tick", "test2", function()
    print("GM:Tick", CurTime())
end)

timer.Create("test3", 0, 0, function()
    print("Timer", CurTime())
end)
```
- Connect to the server.
- After few seconds or whenever you want, disconnect.
- These two hooks and the timer will continue to display the CurTime.

**Comment by robotboy655** [comment]
It still holds true when the server just starts, but it should be fixed for when people leave the server on Dev.
