### ISSUE TITLE
Crash on changelevel.

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#460]
This crash is rather random, sometimes it happens and sometimes not. This can be easily reproduced by changing levels around in the HL2 Campaign.

Also here are some dumps:
https://dl.dropboxusercontent.com/u/29407915/hl2_130707_crash_2013_9_9T2_42_25C0.mdmp
https://dl.dropboxusercontent.com/u/29407915/hl2_130707_crash_2013_9_9T2_56_6C0.mdmp
https://dl.dropboxusercontent.com/u/29407915/hl2_130707_crash_2013_9_9T4_14_6C0.mdmp
https://dl.dropboxusercontent.com/u/29407915/hl2_130707_crash_2013_9_9T4_17_6C0.mdmp

Would be nice if this could be fixed, working on a Coop game that can't properly changelevel kinda sucks.

**Comment by robotboy655** [comment]
You'll need to post new crashdumps if this is to be looked into. Otherwise assuming fixed/related to the workshop crash.
