### ISSUE TITLE
Absent engine entities: func_instance_io_proxy & func_instance_origin

### ISSUE THREAD

**Issue by distributivgesetz** [Facepunch/garrysmod-issues#4603]
### Details
Clear by the title. 
They aren't recognized by the FGD and the console will print `Attempted to create unknown entity type func_instance_io_proxy!` on dev/stable.

The IO proxy is a very big quality-of-life feature for mappers using instances, since it's the only easy way of letting the outside communicate with the instance.

The origin helper isn't nearly as important as the proxy, plus the entity itself is only present in Portal 2.
### Images
 
![hammer_lgb7LhUJqH](https://user-images.githubusercontent.com/47710522/88700316-ceefff80-d108-11ea-88e4-28f96bfc318b.png)
 
![hammer_CnQrqTdJFs](https://user-images.githubusercontent.com/47710522/88700269-bb449900-d108-11ea-89c5-b8a688fd953b.png)

**Comment by Kefta** [comment]
In the future, requests for new entities should go on https://github.com/Facepunch/garrysmod-requests.

**Comment by robotboy655** [comment]
`func_instance_io_proxy` was added but without Hammer support.

`func_instance_origin` doesn't work in CS:GO (so I am assuming this is the case for every game) so I don't see any point in adding it.

**Comment by robotboy655** [comment]
func_instance_io_proxy support was added to Hammer/vbsp.exe
