### ISSUE TITLE
SpawnIcons don't rebuild when larger than the cached SpawnIcon

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#4605]
If you have a 64px SpawnIcon cached and then create a 128px SpawnIcon it will load the cached 64px image.

I assume this is more of an oversight than a bug since `SpawnIcon:RebuildSpawnIcon()` exists and it wasn't fixed in #3636 but that is not a solution there is no nice way to know when it needs rebuilding.

**Comment by robotboy655** [comment]
Can you provide code to reproduce? I can't seem to make it happen if I understand your issue correctly.

```

concommand.Add( "testvgui", function( ... )
	local Panel = vgui.Create( "DFrame" ) -- Main Frame
	Panel:SetPos( 200, 200 )
	Panel:SetSize( 500, 500 )
	Panel:SetTitle( "Spawn Icon Test" )
	Panel:MakePopup()

	local SpawnI = vgui.Create( "SpawnIcon" , Panel )
	SpawnI:SetPos( 75, 75 )
	SpawnI:SetModel( "models/props_borealis/bluebarrel001.mdl" ) 

	local SpawnI = vgui.Create( "SpawnIcon" , Panel )
	SpawnI:SetPos( 75+64+5, 75 +64+5)
	SpawnI:SetSize( 128, 128 )
	SpawnI:SetModel( "models/props_borealis/bluebarrel001.mdl" )

	local SpawnI = vgui.Create( "SpawnIcon" , Panel )
	SpawnI:SetPos( 75+64+5+128, 75 +64+5+128)
	SpawnI:SetSize( 256, 256 )
	SpawnI:SetModel( "models/props_borealis/bluebarrel001.mdl" )
end )
```
Tried `SetSize` both before and after `SetModel`, restarting the game and deleted the spawnicon files, it just regenerates the higher res version for me.

**Comment by aStonedPenguin** [comment]
My code was actually calling `SetSize` after `SetModel`. My bad.
