### ISSUE TITLE
All player recipient filter causing sounds' updating stuttery

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4606]
Apparently isolated by https://github.com/wiremod/wire/commit/833cb6bb89daa7a0ef32a150084c28f23b5d5627

https://github.com/wiremod/wire/issues/2073

Simple to reproduce with E2: code in the wire issue.

**Comment by sammyt291** [comment]
Maybe expand this to also cover sounds being stuck positionally where their parent became dormant/entered another PVS?

**Comment by thegrb93** [comment]
I think it might be because it's incorrectly getting sent via the reliable channel when the filter is set. Can't be certain, but the choppiness is a characteristic of the reliable channel.

**Comment by robotboy655** [comment]
RecepientFilter() is automatically reliable.

**Comment by robotboy655** [comment]
CreateSound no longer forces the internal filter to be reliable
RecipientFilter global now as a new optional argument - make unreliable (defaults false)

This should satisfy this bugreport.
