### ISSUE TITLE
Using Player:Spectate( mode ) in player's own ragdoll teleports it to the center of the map

### ISSUE THREAD

**Issue by Bagellll** [Facepunch/garrysmod-issues#4608]
Alright, so I was working on a system in this gamemode and I needed the player to spectate it's own ragdoll, like a death camera with extra steps. Only [Player:Spectate( mode )](https://wiki.facepunch.com/gmod/Player:Spectate) seems to be broken, and after some more testing I found that [Player:SetObserverMode( mode )](https://wiki.facepunch.com/gmod/Player:SetObserverMode) **does** work for my purpose. This only happens on the client of the player spectating the ragdoll and is purely client-side.

In my custom player meta function the bugged code:
```lua
function meta:DoSomething()
    self:CreateRagdoll()
    self:Spectate( OBS_MODE_CHASE )
    self:SpectateEntity( self:GetRagdollEntity() )
end
```

Result:
![unknown](https://user-images.githubusercontent.com/29413192/89030646-e09af800-d2fe-11ea-9e48-0c036395989a.png)

And this is what works:
```lua
function meta:DoSomething()
    self:CreateRagdoll()
    self:SetObserverMode( OBS_MODE_CHASE )
    self:SpectateEntity( self:GetRagdollEntity() )
end
```

Result:
![unknown](https://user-images.githubusercontent.com/29413192/89030691-f8727c00-d2fe-11ea-8fbe-0aed71caef1a.png)

**Comment by robotboy655** [comment]
Cannot reproduce in Sandbox listen server without any addons, using your first code in a serverside console command.

**Comment by Bagellll** [comment]
Try using the base gamemode. The gamemode I'm currently working on is custom so that may contribute to the problem?

**Comment by Bagellll** [comment]
> Cannot reproduce in Sandbox listen server without any addons, using your first code in a serverside console command.

Try using the base gamemode. The gamemode I'm currently working on is custom so that may contribute to the problem?

**Comment by robotboy655** [comment]
None of the functions in the example come from Sandbox. That being said, why don't you try to replicate it in Sandbox/Base without any addons?
