### ISSUE TITLE
Unhandled exception in vguimatsurface.dll 

### ISSUE THREAD

**Issue by KGoodale13** [Facepunch/garrysmod-issues#4610]
My game crashed due to an unhandled exception in vguimatsuurface.dll

`Unhandled exception at 0x79F84863 (vguimatsurface.dll) in hl2_200626_crash_2020_8_1T2_1_59C0.mdmp: 0xC0000005: Access violation writing location 0x00000000.`

I am not able to reproduce this as it seems to happen randomly.

Here is the mdmp file:
[hl2_200626_crash_2020_8_1T2_1_59C0.zip](https://github.com/Facepunch/garrysmod-issues/files/5009706/hl2_200626_crash_2020_8_1T2_1_59C0.zip)

**Comment by robotboy655** [comment]
Font crash, not much I can do with "it happens randomly", could be the game just running out of RAM, so try the x86-64 beta branch.

**Comment by ShadowBonnieRUS** [comment]
_Access violation writing location 0x00000000._

Maybe there attempt to use null pointer that desired to be not null.

**Comment by Kefta** [comment]
That really narrows it down.
