### ISSUE TITLE
_G.EmitSound doesn't like lua sound scripts

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-issues#4611]
### Details
when creating a soundscript with sound.Add, ENT:EmitSound() uses it just fine, but _G.EmitSound fails to play it
it prints in console: 
sv `SV_StartSound: soundscriptname not precached (0)`
cl `Failed to load sound "soundscriptname", file probably missing from disk/repository`

### Steps to reproduce
```lua
sound.Add({
	name = "soundscriptname",
	sound = Sound"vo/npc/alyx/no01.wav",
	channel = CHAN_VOICE
})

local p = Entity(1)
EmitSound("soundscriptname", p:GetPos(), 1)
```

**Comment by robotboy655** [comment]
Added basic support for soundscripts to that function.
