### ISSUE TITLE
respawn_entities command make weapons silent/broken

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4614]
### Details
The console command `respawn_entities` seems to make the weapons silent. It also seems that the decals no longer appear when firing on the ground. I think there are other bugs after the command is executed, but I haven't found any when I write this.

**Note**: The issue can be solved by changing the shortcut keys to trigger some tools like wheel or light.

➔ Tested in singleplayer with Sandbox gamemode and the following launch parameters : `-noaddons` and `-noworkshop`.

### Steps to reproduce
- Go to singleplayer.
- Run `respawn_entities` in console.
- Take a HL2 weapon and do what you want.

**Comment by robotboy655** [comment]
Fixed on Dev.
