### ISSUE TITLE
Unhandled exception in GameUI.dll 

### ISSUE THREAD

**Issue by KGoodale13** [Facepunch/garrysmod-issues#4615]
My game crashed due to an unhandled access violation exception in GameUI.dll 

I am not able to reproduce this as it just randomly happens when I'm AFK on servers.

Here is the mdmp:
[hl2_200626_crash_2020_8_2T16_44_42C0.zip](https://github.com/Facepunch/garrysmod-issues/files/5012468/hl2_200626_crash_2020_8_2T16_44_42C0.zip)

**Comment by robotboy655** [comment]
Again, "it happens randomly" is not exactly helpful because we can't test any fixes. It's a crash with RichText element. I will try a blind fix on Dev beta branch, but I cannot guarantee a fix without being able to reproduce it.
