### ISSUE TITLE
Hammer editor crash

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-issues#4617]
### Details
If you place any "item_xyz" as example "item_healthvial" with the "Entity Tool" the editor crashes immediately.

dump was send to "robotboy655@facepunchstudios.com" -> "_accessviolation"

### Steps to reproduce
Take the "Entity Tool" choose any entity called "item_xyz" as example  "item_healthvial" try to create it somewhere on your map thats it your work is gone (better enable autosave).

**Comment by robotboy655** [comment]
No?
![image](https://user-images.githubusercontent.com/3299036/89325556-a54b5100-d691-11ea-94e4-3e88841a5a25.png)

Maybe your .fgd is malformed? Have you tried verifying game cache?

**Comment by Combine900** [comment]
Hmm, i reinstalled gmod and used the "FactoryReset-GMod.bat" the problem is gone.

The problem is if you add the "ttt.fgd" from "$SteamUserDir\GarrysMod\garrysmod\gamemodes\terrortown" to "Hammer -> Tools -> Options... -> Game Data files..." this crash(es) will appear any "fix" for that? or do i make something wrong?

**Comment by robotboy655** [comment]
Yeah can confirm it crashing with TTT's fgd

**Comment by robotboy655** [comment]
It's due to this:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/ttt.fgd#L9

I will get it fixed.
