### ISSUE TITLE
Hammer Editor - Some ammo types are displayed as errors

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#4618]
So while making maps for gmod, I noticed some ammo types are displayed as errors and therefore make it difficult to work with them in the hammer editor.
The problem comes from a few lines of code in [GarrysMod > bin > halflife2.fgd]

@PointClass base(Item) studio("models/items/boxsrounds.mdl")= item_ammo_pistol : "Box of Pistol ammo" [] --- This one is fine and its displayed right in hammer editor.

@PointClass base(Item) studio("models/items/largeBoxSRounds.mdl")= item_ammo_pistol_large : "Large Box of Pistol ammo" [] --- This one is displayed as an error, its basically a large pistol ammo counterpart, the id of this entity is "models/items/largeBoxSRounds.mdl" but its displayed as an error, to fix this I just copied the id from the other pistol ammo entity "models/items/boxsrounds.mdl".

@PointClass base(Item) studio("models/items/BoxMRounds.mdl")= item_ammo_smg1 : "Box of SMG1 ammo" [] --- This one is fine and its displayed right in hammer editor.

@PointClass base(Item) studio("models/items/LargeBoxMRounds.mdl")= item_ammo_smg1_large : "Large Box of SMG1 ammo" [] --- Same thing as the large pistol, its an error, to fix it I copy pasted
"models/items/BoxMRounds.mdl" from the other smg ammo counterpart.

@PointClass base(Item) studio("models/items/BoxBRounds.mdl")= item_ammo_ar2 : "Box of AR2 ammo" [] --- While not being large ammo, its actually an error, I fixed this by assigning this entity's id to "models/items/combine_rifle_cartridge01.mdl".

@PointClass base(Item) studio("models/items/LargeBoxBRounds.mdl")= item_ammo_ar2_large : "Large Box of AR2 ammo" [] --- Same as former, fixed by using this id: "models/items/combine_rifle_cartridge01.mdl".

![Untitled](https://user-images.githubusercontent.com/69215350/89332237-54d4f300-d693-11ea-94cc-ed1a76e0f6b5.png)

**Comment by robotboy655** [comment]
Fixed on Dev.

**Comment by BlueLambda1A** [comment]
I'm in the halflife2.fgd how much do i have to scroll to find these lines of code?

**Comment by Kefta** [comment]
Just Ctrl + F

**Comment by BlueLambda1A** [comment]
Thanks
