### ISSUE TITLE
Calling HTTP() after second `map` concommand too early crashes the server

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4620]
### Details
![putty_jCoySVY33k](https://user-images.githubusercontent.com/6339511/89488025-20675100-d7d1-11ea-92e3-50837e2d41f3.png)
![browser_PxBDrOVDwB](https://user-images.githubusercontent.com/6339511/89487942-f44bd000-d7d0-11ea-8666-a123bf5e12c7.png)
![putty_aA9aXqRZuP](https://user-images.githubusercontent.com/6339511/89487920-e302c380-d7d0-11ea-81e8-e4487dbd6412.png)

**Comment by robotboy655** [comment]
Should be fixed on Dev, other branches will follow later as usual.
