### ISSUE TITLE
Old server browser bug

### ISSUE THREAD

**Issue by Harryols** [Facepunch/garrysmod-issues#4621]
Hi.
I have problems with adding a server to favorites in the old server browser via domain&port.
There is two domains for the server with exactly the same DNS record setups, one is working and the other is not.
1. Working: DOMAIN.com:25576
2. Not working: 5DOMAIN.com:25576
I think it is a bug in the server browser or gmod, here is my theory:
When the domain starts with a number (e.g. 5 in this case) the server browser automatically thinks it must be a IP-address and therefore fails, because it isn't.
e.g.
var VarDomorIP = "5DOMAIN.com:25576"
if (VarDomorIP.match(/^\d/)) {
   window.alert("This must be an IP, not a domain");
}
How do I add the server to favorites, in the old server browser, with the domain beginning with 5?

**Comment by robotboy655** [comment]
Should be fixed on Dev and in the next update.
