### ISSUE TITLE
Garry's Mod overwrites Steam game presence and always shows over other games.

### ISSUE THREAD

**Issue by smashiee** [Facepunch/garrysmod-issues#4622]
Occasionally I like to leave Garry's Mod open while playing another game. While I would like my Steam status to show the game I'm actually playing, Garry's Mod has consistently overwrited that Steam status for many many years now. With any other game (even other Source games like CSS), Steam shows the most recent game you launched as your status.

I was wondering if perhaps there is any way to fix this small issue, if there was any personal workaround I could do, or if maybe you guys had an idea of how to fix it via the game.

**Comment by robotboy655** [comment]
This isn't really something we can do anything about, we are not Steam. Contact Steam Support or something.
