### ISSUE TITLE
Ragdolls with COLLISION_GROUP_DEBRIS_TRIGGER crashes server

### ISSUE THREAD

**Issue by Benn20002** [Facepunch/garrysmod-issues#4623]
### Details
Today my server started with nearly no changes except changing the collision group of ragdolls from COLLISION_GROUP_WEAPON to COLLISION_GROUP_DEBRIS_TRIGGER.
The server crashed twice within like 1 or 2 hours after each startup.
As soon as I changed it back to the old collision group it stopped crashing.
I am pretty sure this is related to the collision group as my server did not crash once in like over a month or two.

The server didn't really crash, it just hung up (like if it's in a infinite loop) and because of that I don't have any crash logs.

This is the code I've been creating the ragdolls with:
```
local rag = ents.Create("prop_ragdoll")
rag:SetModel(ply:GetModel())
rag:SetPos(ply:GetPos())
rag:SetAngles(ply:GetAngles())
rag:SetSkin(ply:GetSkin())
rag:SetDTEntity(10,ply)
rag:Spawn()
rag:Activate()
rag.Player = ply
rag:SetCollisionGroup(COLLISION_GROUP_WEAPON)
rag:SetCollisionGroup(COLLISION_GROUP_DEBRIS_TRIGGER)

local phys = ply:GetPhysicsObject()
local vel
if IsValid(phys) then
	vel = phys:GetVelocity()
else
	vel = VectorRand(-10,10)
end

local num = rag:GetPhysicsObjectCount() - 1
for i = 0, num do
	local bone = rag:GetPhysicsObjectNum(i)
	if IsValid(bone) then
		local bp, ba = ply:GetBonePosition(rag:TranslatePhysBoneToBone(i))
		if bp and ba then
			bone:SetPos(bp)
			bone:SetAngles(ba)
		end
		bone:SetVelocity(vel)
	end
end

local col = ply:GetPlayerColor()
rag.GetPlayerColor = function()
	return col
end
```

When trying it on my testserver without any players on it, it didn't crash.
I can't try it on a different branch or figure out what exactly causes the crash on my main-server as it'd annoy my players pretty bad.

**Comment by robotboy655** [comment]
The server is on the default beta branch right? Not on any other beta branches?

**Comment by Benn20002** [comment]
Newest version of x86-64, not started on 64bit - just the 32bit beta branch.

**Comment by robotboy655** [comment]
You could try using https://github.com/Metastruct/valvekiller to force a dump

**Comment by Benn20002** [comment]
Yea but as I said I cant reproduce it on a server without any players on it and I dont really wanna risk a crash with like 80-100 players on the server..
Thought you might be able to fix it without a dump.
If I happen to find a way to reproduce it on a empty server Ill give valvekiller a try.

**Comment by Kefta** [comment]
This has been known since 2014 with the TTT crazy physics ragdoll crashes, and it originates from inside vphysics, so this may not be fixable.

**Comment by robotboy655** [comment]
I thought you said the server freezes, not crashes? If it freezes, what's the point of just keeping it up? It's unplayable either way?

**Comment by Benn20002** [comment]
Yea I meant freeze, just used the wrong word. It freezes.
I solved the problem in my case by switching back to COLLISION_GROUP_WEAPON. With that one the freeze did not occur in months.
Of course this isnt a real solution to the problem but it works for now and I dont have to deal with those freezes.
The only reason why I wanted to switch was to make ragdolls not collide with eachother but its also not a big problem if they do.

**Comment by Benn20002** [comment]
I've experienced another freeze, not sure if its related to ragdolls but I'd still like to get a crash report.
My server is running on linux so how would I run valvekiller in case of another freeze?

**Comment by thegrb93** [comment]
dump a core when it freezes and send to dev

**Comment by Benn20002** [comment]
how do I do that? I'm not that experienced with linux

**Comment by thegrb93** [comment]
ctrl+\ or, if it's not in a terminal, kill it with a SIGQUIT. google if you need more info. If you don't get a core then you also need `sudo ulimit -c unlimited`
