### ISSUE TITLE
Issue with RPG and +use pickup

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-issues#4624]
If you have 1 RPG rocket, sometimes you can't guide missile if you have 0 RPG rockets, happens if you get one rocket then switch to another weapon, and switch back to RPG

+use pickup doesn't works on npc_grenade_frag and on weapons

**Comment by GitSparTV** [comment]
You should create separate issues

**Comment by robotboy655** [comment]
Cannot reproduce issues with the HL2 RPG, not matter how many times I switch.

**Comment by weaponcubemap** [comment]
this bug happens randomly, if you have 1 rockets, and switching to random weapon, then switch back to RPG

**Comment by Kefta** [comment]
I also experienced the RPG bug years ago, but I cannot reproduce it now even once.

**Comment by robotboy655** [comment]
oh i can now all of a sudden, it happens when you try to shoot before the deploy anim finishes or something like that.

**Comment by robotboy655** [comment]
I fixed the RPG thing.

**Comment by weaponcubemap** [comment]
Good
