### ISSUE TITLE
Value dragging of `PANEL:NumSlider()` is displayed out of the dedicated area

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#4626]
### Details
When the user creates a [`NumSlider`][ref-ns] menu object, it can be selected with the left click on the slider label name When the mouse cursor `<-->` appears, the user can select a slider value with using the mouse `X` and `Y`
![image](https://user-images.githubusercontent.com/9112662/89711270-e09b9780-d991-11ea-8cb2-a536ccc2b87d.png)

### Steps to reproduce
1. Open Gmod
2. Create a tool with [`CPanel`][ref-cp]
3. Populate the [`CPanel`][ref-cp] with [`NumSlider`][ref-ns] element with `7` decimal places
```lua
  pItem = cp:NumSlider(language.GetPhrase("tool."..gsUnit..".force_con"), gsUnit.."_force", 0, varFireForce:GetFloat(), iDecm)
  pItem:SetTooltip(language.GetPhrase("tool."..gsUnit..".force"))
```
4. Left click on [`the scratch slider label`][ref-ns] until `<-->` comes out
5. Drag mouse `X` and `Y` to show the value selection grid
6. Select `7543.5673828`
8. The value goes outside the blue draw area
![image](https://user-images.githubusercontent.com/9112662/89711395-b72f3b80-d992-11ea-9b4e-50bd0a241e2b.png)

[ref-ns]: https://wiki.facepunch.com/gmod/DForm:NumSlider
[ref-cp]: https://wiki.facepunch.com/gmod/DForm
[ref-ns]: https://wiki.facepunch.com/gmod/DNumberScratch

**Comment by robotboy655** [comment]
Solved on Dev beta branch.
