### ISSUE TITLE
Web : loading screens, images from internet

### ISSUE THREAD

**Issue by Marlbogaro** [Facepunch/garrysmod-issues#4628]
Anything web related (loading screens, images from internet) doesn't display if the web host is the same as my gmod host

I have the same problem as this person I performed several tests and putting my Garry's mod in chromium version or in it works or in X64.

Has anyone already found a solution ?

**Comment by viral32111** [comment]
It's probably an issue with your webserver configuration, not GMod itself.

**Comment by Marlbogaro** [comment]
I gave you the urls but with friends we tried on different web servers because we each have a different configuration me Apache them Nginx is the problem is always the same we also tried to change the cipher and change the encryption length ssl key
config :

SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2
SSLHonorCipherOrder On
SSLCipherSuite ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:HIGH:!MD5:!aNULL:!EDH:!RC4
SSLCompression off

url : 
https://blackofgame.fr/gmod/loadingscreen/
https://www.hyloserv.fr/
https://ifnet.fr/

**Comment by Marlbogaro** [comment]
> It's probably an issue with your webserver configuration, not GMod itself. Could you provide the public URLs to the webserver and images?
> 
> > putting my Garry's mod in chromium version or in it works or in X64.
> 
> Are you saying it works in Chromimum/x86-64? Because that would be reasonable, since Awesomium is hella outdated. If this is the case then not much can be done aside from adjusting your webserver configs to allow for "older" traffic (afaik Awesomium requires TLS 1.0/1.1 connections which is considered insecure by today's standards)

I gave you the urls but with friends we tried on different web servers because we each have a different configuration me Apache them Nginx is the problem is always the same we also tried to change the cipher and change the encryption length ssl key
config :

SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2
SSLHonorCipherOrder On
SSLCipherSuite ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:HIGH:!MD5:!aNULL:!EDH:!RC4
SSLCompression off

url :
https://blackofgame.fr/gmod/loadingscreen/
https://www.hyloserv.fr/
https://ifnet.fr/

**Comment by viral32111** [comment]
Try disabling SSL/TLS temporarily and accessing it over regular HTTP, that should work.

In my experience, leaving all the SSL/TLS options for Apache at their default allows Awesomium to connect. Also be aware that if your SSL/TLS certificate is using complex and more modern encryption & signing algorithms such as EC, or more modern hashing algorithms such as SHA3, may cause Awesomium to not be able to negotiate a handshake too.

Enable debugging for the Apache SSL module by setting the LogLevel of SSL to trace3, then look through the logs and see what's happening.

**Comment by viral32111** [comment]
Also since this isn't a bug and more of a support question, it's probably best to continue in the Garry's Mod discord.

**Comment by Marlbogaro** [comment]
> De plus, comme ce n'est pas un bug et plutôt une question d'assistance, il est probablement préférable de continuer dans la discorde de Garry's Mod.


but before the update at the end of 2019 it works fine and now rip

**Comment by Marlbogaro** [comment]
> Essayez de désactiver temporairement SSL / TLS et d'y accéder via HTTP normal, cela devrait fonctionner.
> 
> D'après mon expérience, laisser toutes les options SSL / TLS pour Apache à leur valeur par défaut permet à Awesomium de se connecter. Sachez également que si votre certificat SSL / TLS utilise des algorithmes de cryptage et de signature complexes et plus modernes tels que EC, ou des algorithmes de hachage plus modernes tels que SHA3, Awesomium ne pourra pas non plus négocier une poignée de main.
> 
> Activez le débogage pour le module SSL Apache en définissant LogLevel de SSL sur trace3, puis parcourez les journaux et voyez ce qui se passe.
> 
> (En général, j'éviterais simplement SSL / TLS lors de l'utilisation d'Awesomium, j'ai dû faire de même pour les écrans de chargement de mon serveur et FastDL. Bien que ce soit ennuyeux, c'est la meilleure option à moins que vous ne puissiez garantir que tous vos joueurs seront sur le x86 -64 succursale.)


I'm going to test this tonight I thank you I tell you what

**Comment by Marlbogaro** [comment]
> > Essayez de désactiver temporairement SSL / TLS et d'y accéder via HTTP normal, cela devrait fonctionner.
> > D'après mon expérience, laissez toutes les options SSL / TLS pour Apache à leur valeur par défaut permet à Awesomium de se connecter. Sachez également que si votre certificat SSL / TLS utilise des algorithmes de cryptage et de signature complexes et plus modernes tels que EC, ou des algorithmes de hachage plus modernes tels que SHA3, Awesomium ne pourra pas non plus négocier une poignée de main.
> > Activez le débogage pour le module SSL Apache en définissant LogLevel de SSL sur trace3, puis parcourez les journaux et voyez ce qui se passe.
> > (En général, j'éviterais simplement SSL / TLS lors de l'utilisation d'Awesomium, j'ai dû faire de même pour les écrans de chargement de mon serveur et FastDL. Bien que ce soit ennuyeux, c'est la meilleure option à moins que vous ne pouvez garantir que tous vos joueurs seront sur le x86 -64 succursale.)
> 
> Je vais tester ça ce soir je te remercie je te dis quoi

I managed to solve the problem by changing my lestencrypt configuration thank you for your help.

`# This file contains important security parameters. If you modify this file
# manually, Certbot will be unable to automatically provide future security
# updates. Instead, Certbot will print and log an error message with a path to
# the up-to-date file that you will need to refer to when manually updating
# this file.

SSLEngine on

# Intermediate configuration, tweak to your needs

_#old config#

#SSLProtocol             all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
#SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

#old config#_

SSLProtocol             -all +TLSv1 +TLSv1.1 +TLSv1.2
SSLCipherSuite          EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GC$
SSLHonorCipherOrder     off

SSLOptions +StrictRequire

# Add vhost name to log entries:
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common `

new: ![new](https://user-images.githubusercontent.com/38571731/89827646-243ffe00-db58-11ea-8e85-85b549ffe234.png)
old : ![old](https://user-images.githubusercontent.com/38571731/89827650-24d89480-db58-11ea-8c41-d5e3739b7d04.png)
