### ISSUE TITLE
Nextbot performance SIGNIFICANTLY worse on upcoming pre-release update

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-issues#4630]
I don't know what the exact problem is or how to find it, but I've demonstrated it in this [youtube video](https://www.youtube.com/watch?v=A3hGoc-W0Vk)

**Comment by robotboy655** [comment]
You you provide me your code for testing? You can send it to the email address you already reported this issue to.

**Comment by Jova1106** [comment]
Sent what you need.

**Comment by robotboy655** [comment]
Should be fixed on Dev and on pre release soon, although not without setbacks to the new functions unfortunately.
