### ISSUE TITLE
Client permanently stuck on "Downloading X of Y lua files"

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4632]
## Details
Depending on the specific folder structure, file names, and content of an addon, some lua files will freeze the client in its tracks and prevent it from fully connecting. The client doesn't actually become unresponsive, though, instead it remains stuck on the "Downloading X of Y lua files" message and will never progress further.

## Steps to reproduce
I can very reliably reproduce the issue; however, the circumstances are rather specific.
1. Create the following addon structure:
  * `cstest/lua/autorun/cstest.lua` (file contents: [https://pastebin.com/2pCTzky4](https://pastebin.com/2pCTzky4))
  * `cstest/lua/testfiles/application_cl_000.lua` (file contents: [https://pastebin.com/u3wSy7VY](https://pastebin.com/u3wSy7VY))
  * `cstest/lua/testfiles/application_sh_000.lua` (file contents: [https://pastebin.com/HwbKFATa](https://pastebin.com/HwbKFATa))
2. Start server. I am using `-noworkshop` and the test addon is the only addon.
3. Connect with a client.
4. Upon reaching the "Downloading X of Y lua files" stage, the first file will download as expected.
5. However, the client will get stuck on file no. 2 indefinitely and never complete connecting. There are no messages in the console the may indicate what has gone wrong.

### What doesn't matter
* The folders that I have named `cstest` and `testfiles` can be any arbitrary name.
* The autorun file `cstest.lua` can have any arbitrary name.

### What _does_ matter
* The file names `application_cl_000.lua` and `application_sh_000.lua` are extremely important. Using different names does *not* replicate the issue. For example, if the file contents are unchanged, but the files are renamed to `application_cl_AA000.lua` and `application_sh_BB000.lua`, the issue will no longer reproduce.
* The contents of `application_cl_000.lua` must be "similar" to the 200KB file contents I provided. I say "similar" because a similar file (+/- any arbitrary 1000 bytes) reproduces the issue, while a vastly smaller file (i.e. 1KB) does not reproduce the issue.

### What _kind_ of matters
* In contrast to the previous point, the contents of `application_sh_000.lua` can be anything and the issue will reproduce; however, the client will freeze on a different message depending on the file contents. With the 200KB file contents that I provided, the client freezes on the "Downloading X of Y lua files" message. However, if you were to replace the file contents with a very small amount of data (for example, `local a = "I am some code"`), the client _might_ freeze on the "Requesting lua files message" instead.

## Addendum
There is also a slight degree of chaos to this issue. Sometimes, the client will say "Downloading 1 of 3 lua files", then get stuck on the "Downloading 2 of 3 lua files" message. Sometimes, the client will say downloading 1 of 2 lua files, then get stuck on the "Received all lua files we needed!" message.

### Background
I was sending large files to the client with AddCSLuaFile, which started failing around >250KB with a "lua file is larger than 65535" kind of message (I assume this is related to the `net` library's limitations). My workaround has been to chunk the large files into 200KB pieces with _001-style naming - which lead me to discover this issue. It is important to note that gmod does *not* complain about the 200KB files I am using in this example. There is no console message about oversized lua files. The connection process just silently halts and catches fire.

Perhaps either the name generation technique for cached AddCSLuaFiles and/or the LZMA compression of those files may be related to this issue.

## Environment
x64 2020.08.07
Vanilla 2020.06.26

**Comment by robotboy655** [comment]
So yeah, the issue is the filesize of the files, its simply too large which causes bugs with Source's networking system. As far as I could tell, it has nothing to do with the filename, as changing the filename to "a.lua" and "2.lua" still causes the same issue.

**Comment by robotboy655** [comment]
Alright, it should no longer get stuck but instead just not send those big files to clients. I know this isn't ideal and you can create a request to increase the maximum filesize for Lua file networking.

**Comment by TiberiumFusion** [comment]
@robot655 Thank you. Will the client and/or server produce some kind of console message if an addon tries to send a file that is too large? Or, if the max filesize might be changed in the future, will some Lua function be added to report the max filesize? I can put an arbitrary limit of 65KB on my file chunks, but it would be much nicer to get an exact size limit from the engine at runtime.

FWIW, with the test files I provided, they transmit successfully (despite being 200KB) on my particular test server when they have longer/more unique file names (i.e. application_cl_AA000.lua instead of application_cl_000.lua). This was verified by simply checking the length and unique ending of each of the long strings returned by the test files on the client.

**Comment by robotboy655** [comment]
Yes there will be a message (and will display the compressed size), and no, there is no set limit. The limit is 64*1024 compressed, which does not directly translate to uncompressed filesize. The fact it worked for you is quite perplexing, unless the compressed size was simply under 65k.
