### ISSUE TITLE
Screenclicking

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4633]
### Details
I've disabled screen clicking (using weapons) when using the context menu by using this snippet of code.

hook.Add("PreventScreenClicks", "PreventScreenClicks", function()
	local pnl = vgui.GetHoveredPanel()
	if IsValid(pnl) and pnl:IsWorldClicker() then
		return true
	end
end)

hook.Add("OnContextMenuOpen", "PreventScreenClicks", function()
	RunConsoleCommand("-attack")
	RunConsoleCommand("-attack2")
end)

Yet it still works if you hold mouse 1 and hover over the bar with the NPC settings.

### Steps to reproduce
Hold mouse 1 on screen.
Hover upwards, until you reach the NPC bar.
Now you can shoot, even with it being disabled.

**Comment by robotboy655** [comment]
Why not just do... ```g_ContextMenu:SetWorldClicker( false )```?

**Comment by mcNuggets1** [comment]
Why is prevent screenclicking not working as a hook?
I only wanna disable it for weapons..

**Comment by robotboy655** [comment]
The whole WorldClicker thing is only for weapons?

Why is your code not working? I'd think it's sort of your job to figure that out, but the thing is you check if the hovered panel is a world clicker, but you know the menubar thing is not a world clicker and you do not test for panel's parents.. so the result is pretty self explanatory.

World clicker (and panel dragging, which is what happens when you press and hold and move your mouse) is based off of internal mouse focused panel, not off of vgui.GetHoveredPanel.

**Comment by mcNuggets1** [comment]
It's code from the wiki literally, saying it would do so.

**Comment by mcNuggets1** [comment]
Setting world clicker on g_ContextMenu to false doesn't fix it also.
The desktop windows still enable it.

I just wanna disable shooting using the world clicker, thats it...

**Comment by robotboy655** [comment]
I have updated the example on the wiki.

**Comment by mcNuggets1** [comment]
The new code disables any interaction in those menus.

**Comment by robotboy655** [comment]
Ah, now I see what you mean by "only disable shooting".

**Comment by FlorianLeChat** [comment]
Any solution please ?

**Comment by robotboy655** [comment]
Why are you expecting me to write your code for you?

```
hook.Add( "PreventScreenClicks", "DisableWorldClicker", function()
	local pnl = vgui.GetHoveredPanel()
	if ( IsValid( pnl ) ) then
		if ( pnl:IsWorldClicker() ) then return true end

		while ( IsValid( pnl:GetParent() ) ) do
			pnl = pnl:GetParent()
			if ( pnl:IsWorldClicker() ) then return true end
		end
	else
		-- For when the cursor is outside of the game's window, there can be potential edge cases here
		return true
	end
end )
```

Here you go, I guess

**Comment by FlorianLeChat** [comment]
Thanks Rubat! 😄 
I'm updating the wiki...
