### ISSUE TITLE
The "sv_gamename_override" ConVar doesn't seem to work

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4637]
### Details
Even when filling arguments in this command, the name of the gamemode always seems to be the one defined by default. This problem seems to affect all gamemodes (**Sandbox**, **DarkRP**, **TTT**...).

I tried to workaround this issue with the [GetGameDescription](https://wiki.facepunch.com/gmod/GM:GetGameDescription) hook but it doesn't work on some gamemodes but others do (works on **Helix** and **Basewars**, but doesn't work on **DarkRP**/**Sandbox**).

Here is the code for the hook :

```lua
hook.Add("GetGameDescription", "Github", function()

	print("GetGameDescription hook called")

	return "Test Github"

end)
```

➔ Tested in fresh install in a dedicated server with several gamemodes (won't work in singleplayer).

### Steps to reproduce
- Type `sv_gamename_override <whatever you want>` in a dedicated server console

**OR**

- Put my code in a file located in `lua/autorun`.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/90809432-22312880-e32a-11ea-92af-9b139a8eb6b1.png)

It does work.

**Comment by FlorianLeChat** [comment]
![image](https://user-images.githubusercontent.com/26360935/90810547-6ec53580-e323-11ea-815c-65bef59a26d3.png)
![image](https://user-images.githubusercontent.com/26360935/90810709-b21fa400-e323-11ea-8cbb-3ad1a40621f6.png)

Okay, that's kind of weird, but the "GetGameDescription" hook is working again, so... thanks !
However the command `sv_gamename_override` works partially. The list of servers by Steam displays the name I entered but the list of servers by Garry's Mod still displays the old one.

![image](https://user-images.githubusercontent.com/26360935/90810617-8f8d8b00-e323-11ea-8c0b-405a5100421f.png)

So I think there's a problem with Steam (if not with Gmod).

**Comment by GitSparTV** [comment]
Because this is the different name, it's a display name

**Comment by FlorianLeChat** [comment]
I didn't understand. The `sv_gamename_override` command and the `GetGameDescription` hook should change the name of the category at any time normally (on Steam and on Gmod) ? The problem is that the Gmod doesn't update it (like using a cache).

**Comment by robotboy655** [comment]
So here's the thing, it does all update properly, but the GMod's serverbrowser will show the name of the gamemode if you have the gamemode already installed. If you, the client don't have the gamemode installed, then it will use the gamemode NAME the server is transmitting, and yeah, caches it, with the assumption that each gamemode can have only 1 name. So it works in a way that the name of the category will be chosen based on which name is transmitted by most servers in the category. The categories are still grouped by the gamemode folder name, so for TTT it would be put into "terrortown" category regardless of what your Gamemode Display Name is, if that makes sense.

I am not sure this is something we'd be interested in changing.

**Comment by Ethorbit** [comment]
> So here's the thing, it does all update properly, but the GMod's serverbrowser will show the name of the gamemode if you have the gamemode already installed. If you (the client) don't have the gamemode installed, then it will use the "nice" gamemode display name the server is transmitting for that gamemode, and yeah, caches it, with the assumption that each gamemode can have only 1 name.
> 
> So it works in a way that the name of the category will be chosen based on which name is transmitted by most servers in the category. The categories are still grouped by the gamemode folder name, so for TTT it would be the `terrortown` category, **not** `Trouble in Terrorist Town` category, so if you are running TTT, you cannot be in a different category, even if you change your server's GetGameDescription or sv_gamename_override.
> 
> I am not sure this is something we'd be interested in changing.

This is abuseable for small games.

If I run the most servers in a category, I get to choose what the game is called. I can call it anything I want and everyone has to click on my name to play.
