### ISSUE TITLE
Missing? new features 

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-issues#4640]
https://cdn.discordapp.com/attachments/510876702600069140/746153636383686666/Capture.PNG
This feature was added a while back, in the dev branch it was working alright but now with the new update it doesnt work,or the devs removed it for some reasons

**Comment by Kefta** [comment]
Test in the current dev branch, I'm pretty sure it just didn't make it into the last update.

**Comment by robotboy655** [comment]
What he said.
