### ISSUE TITLE
player:DropObject() and player:SelectWeapon() cause prop to freeze

### ISSUE THREAD

**Issue by Benn20002** [Facepunch/garrysmod-issues#4641]
### Details
When having a prop picked up with the gravity gun and running player:DropObject() and player:SelectWeapon() it freezes the prop wherever it is.
The collision of the prop seems to move as expected but clientside the model still shows frozen where it was when the functions have been run.
I also found that sometimes the model unfreezes and reattaches to the physics after a few seconds.
This does not occur when picking a prop up with E or the physics gun.

This works on both normal branch and x86-64.

Video: https://drive.google.com/uc?id=113ZZGXyo7VgU6THaBkGdPbbwkcxrbrqc

### Steps to reproduce
Start Sandbox
Create a prop with a model thats not too heavy to lift with the gravity gun (models/props_c17/chair02a.mdl)
Pick it up with the gravity gun
Run `lua_run local ply = player.GetAll()[1] ply:DropObject() ply:SelectWeapon("weapon_pistol")`

**Comment by robotboy655** [comment]
Should be fixed.
