### ISSUE TITLE
 steamworks.DownloadUGC currently not working?

### ISSUE THREAD

**Issue by X-Coder** [Facepunch/garrysmod-issues#4642]
Hi I tried to run https://wiki.facepunch.com/gmod/game.MountGMA

`steamworks.DownloadUGC( 104548572, function( name )
	game.MountGMA( name )
end)`

But I get the following errors and I'm unable to solve it:

Playable Piano addon:
steamworks.DownloadUGC: Failed to read addon file 'S:\Steam\steamapps\workshop\content\4000\104548572\938133153078523127_legacy.bin' for 104548572

With wiremod I get something similar:
steamworks.DownloadUGC: Failed to get SteamUGC file for 160250458

I don't have a folder called S:\Steam\steamapps\workshop\content\4000\104548572 because I manually cleared the workshop\content folder a while ago because it was getting to big.

Could this have been the cause for the error? -is there any other file I need to clean to restore steamworks.DownloadUGC to a working state? Or is  steamworks.DownloadUGC currently just broken for every one?

**Comment by robotboy655** [comment]
>I don't have a folder called S:\Steam\steamapps\workshop\content\4000\104548572 because I manually cleared the workshop\content folder a while ago because it was getting to big.

There's your problem. You deleted Steam files and you are now complaining that something doesn't work. Verify your game cache integrity, and DO NOT DELETE FILES OUTSIDE OF THE GAME'S DIRECTORY!

**Comment by X-Coder** [comment]
Instead of pointing fingers at me, please tell me what can be done to clean up the garrysmod steamworks cache folder without corrupting garrysmod steamworks implementation.

The whole S:\Steam\steamapps\workshop\content\4000 was like ~90 GB with old data, the oldest one of 2015. If it's a cache (indirectly) owned by garrysmod, if I'm not allowed to cleanup a cache directory, you are responsible to clean up unused files regulary, so this problem would never happened in first place.

**Comment by robotboy655** [comment]
The cache is not handled by Garry's Mod. Old files are being deleted after ~2weeks of not being used, if you have filed from 2015 it means either it's a subscribed addon, or that file is being used on some server that you are playing on.

**Comment by X-Coder** [comment]
That could be the case, thank you for your help.
