### ISSUE TITLE
VRad crashes on 'Invalid model version' static props with -StaticPropLighting and console message typo

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4644]
### Crash details
When I try to compile map with props from Portal 2 (e.g. `models/props_bts/metal_truss_16x32_512a.mdl`), lighting compiler 
sends following messages: 
> Error! Invalid model version "models/props_bts/metal_truss_16x32_512a.mdl"

But when -StaticPropLighting parameter present, it crashes

Setting `Disable Vertex lighting` to Yes on all `prop_static`s with bad-versioned models prevents the compiler from crashing and the level loads correctly.

Memory dump: [vrad_20200824_233014_1.mdmp.zip](https://github.com/Facepunch/garrysmod-issues/files/5120125/vrad_20200824_233014_1.mdmp.zip)

### Typo details
"_Computing static prop lighting : 0_" message probably has no newline at the end so 
"_Computing static prop lighting : 0ThreadComputeStaticPropLighting: 0...1...2...3...4...5...6...7...8...9...10 (1)_" line usually appears

**Comment by robotboy655** [comment]
VRAD no longer crashes with invalid model versions on static props (i.e. Portal 2/CSGO models)
VRAD no longer bails compiling vertex lighting for static props with invalid model versions
VRAD now uses DX90 vertex format for vertex lighting of static props

**Comment by a-straight-white-male** [comment]
Bump, looks like it's back now with -StaticPropPolys instead. 

[vrad_20250615_212637_1_x000000D55CF7D028.zip](https://github.com/user-attachments/files/20746984/vrad_20250615_212637_1_x000000D55CF7D028.zip)
