### ISSUE TITLE
Metrostroi crashes on x64

### ISSUE THREAD

**Issue by LennDoMations** [Facepunch/garrysmod-issues#4645]
http://www.mediafire.com/file/jlnw6kg7wyh7dzh/196f8b7e-11cb-4992-9810-9124f0efb361.dmp/file
first crash random crash after 20 minutes of playtime

http://www.mediafire.com/file/tk3w42ihd3vi5yh/f1e081c7-0d86-4e0c-848d-dc8469da1cb1.dmp/file
second crash: first short freeze then freezes as soon as i get out of the game into another programm or on desktop.

http://www.mediafire.com/file/0qxps7qyjyt5si8/f542bbbb-00ae-421e-b9c9-c3514d1b5a82.dmp/file
Third crash after spawning a train.

i tryed changing system settings and gmod settings. nothing worked.

**Comment by LennDoMations** [comment]
Can this be a Problem of my heapsize settings?

**Comment by Kefta** [comment]
No

**Comment by robotboy655** [comment]
All 3 are the same `bass.dll` crash

**Comment by LennDoMations** [comment]
ok this crashing only happens when i use opengl mode or 64 bit branch

**Comment by LennDoMations** [comment]
Update: Crashes happen also on normal versions

**Comment by LennDoMations** [comment]
Anything new to the crash?

**Comment by LennDoMations** [comment]
luckly i found a fix for now

**Comment by Kefta** [comment]
What is it?

**Comment by LennDoMations** [comment]
Standard bass.dll from Bass audio lib

**Comment by robotboy655** [comment]
So potentially solved by https://github.com/Facepunch/garrysmod-requests/issues/1549

**Comment by LennDoMations** [comment]
hmm

**Comment by LennDoMations** [comment]
So you mean your using original Version Off the Bass dll? Just older version.?

**Comment by robotboy655** [comment]
No, I mean if we update BASS.DLL to the latest version if should no longer crash for you? Isn't that what you did in the first place when you said `Standard bass.dll from Bass audio lib`?

**Comment by LennDoMations** [comment]
Yes newest Version fixes all Bass related crashes

**Comment by LennDoMations** [comment]
So Update to new Version would fix this

**Comment by LennDoMations** [comment]
Notice: I also helped another player with the same crash. also fixed his crashes with newest Version

**Comment by LennDoMations** [comment]
http://www.mediafire.com/folder/3qbau3h0ysm8w/crash_logs Could you check these crash logs?

**Comment by robotboy655** [comment]
It's the same/similar BASS.DLL crash. Are you sure you are updated? Or are these dumps from "Chromium" beta and not "x86-64"?

**Comment by LennDoMations** [comment]
No but These are almost all Same Case crashes. When i Press a Button that Plays a series of sounds then it Sometimes crashes

**Comment by LennDoMations** [comment]
[1.zip](https://github.com/Facepunch/garrysmod-issues/files/5675086/1.zip)

**Comment by LennDoMations** [comment]
these are the 2 sounds played crash happens

**Comment by CrIcKeT98** [comment]
Same problems with loop sounds and bass.dll
Version: production
[dumps.zip](https://github.com/Facepunch/garrysmod-issues/files/5889497/dumps.zip)

**Comment by LennDoMations** [comment]
Crashes get more and more scince the last update. not for me but most people joining the public server i join on crash

**Comment by robotboy655** [comment]
I have pushed another updated BASS.DLL that should fix all issues.

**Comment by LennDoMations** [comment]
So i guess its now modified :D

**Comment by Kefta** [comment]
It's not, it's just a new version.
