### ISSUE TITLE
error() inside ProtectedCall() inside xpcall callback will throw an error thrown in previous ProtectedCall block

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4646]
Behavior is same as https://github.com/Facepunch/garrysmod-issues/issues/4515
but traceback *is* present and level argument *do* work

Example of code which will throw undefined previously error (you can't predict which error it will throw:)

```lua
error('some error') -- prove that this error won't appear in error below

-- somewhere after

local function broke(err)
	ProtectedCall(function()
		print(err)
		error(err, 4)
	end)
end

local function funcwitherror()
	error('bad')
end

xpcall(funcwitherror, broke)
```

Code above will throw error with unpredictable message, but this:
```lua

ProtectedCall(function()
	error('hey, i will be there!')
end)

local function broke(err)
	ProtectedCall(function()
		print(err)
		error(err, 4)
	end)
end

local function funcwitherror()
	error('bad')
end

xpcall(funcwitherror, broke)
```

error message inside callback of xpcall will be the one in first ProtectedCall's

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/100139800-ac90a780-2e98-11eb-8e80-1aedf832800a.png)

Should be all fixed up.
