### ISSUE TITLE
Hammer grid size in information strip is not updated on switching between VMFs

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4647]
### Details
When you switch between maps in Hammer, grid size indicator is not updated but grid size itself is changed.

### Steps to reproduce
1. Create two empty maps.
2. Switch to map 1 using `Window` menu and set grid size to 16
3. Switch to map 2 using `Window` menu and set grid size to 64
4. Open map 1 back.
You can see indicator showing "Snap: On Grid: 64" (or Off grid: 64), but incrementing grid size shows 32, that means it was changed from 16 units

**Comment by robotboy655** [comment]
Fixed.
