### ISSUE TITLE
gmpublish: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by felixactually** [Facepunch/garrysmod-issues#4648]
### Details
When attempting to use gmpublish from the terminal, I get the following output: 
./gmpublish: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

gmad works correctly, but gmpublish does not. libsteam_api.so is present in the linux64 folder, I have also tried copying gmpublish to the linux32 folder, this also doesn't work.

UPDATE: Using "LD_LIBRARY_PATH=" before the command works. Should the executable not be setting this itself?

### Steps to reproduce
Open terminal and cd to [steamlibrary]/GarrysMod/bin/linux64/
Do ./gmpublish

**Comment by neico** [comment]
If gmpublish is compiled (linked to be precise) with `-rpath` then this can be fixed without relying on `LD_LIBRARY_PATH` which is not recommended these days
it can be done like this:
`LDFLAGS=-Wl,-rpath,/path/to/bin`

**Comment by viral32111** [comment]
Duplicate of #4542

**Comment by robotboy655** [comment]
Please test and let me know if it is resolved on Dev beta branch.

**Comment by felixactually** [comment]
> Please test and let me know if it is resolved on Dev beta branch.

Hi, I just switched to the Dev branch, the linux64 and linux32 folders are now empty, I assume that's intentional? Regardless though, I tried the gmpublish_linux executable in GarrysMod/bin/ but it returned the same output as in the original post, using LD_LIBRARY_PATH again allowed it to work.

**Comment by robotboy655** [comment]
This should be fixed on `dev` beta.
