### ISSUE TITLE
Tall grass textures

### ISSUE THREAD

**Issue by Demotana** [Facepunch/garrysmod-issues#465]
So, I've been having an issue with a tall grass bug or something like that, the textures are messed up, no clue why. It happens on every map with the tall grass.
You can see the bug here.
http://cloud-2.steampowered.com/ugc/1099165943081101670/6683D8955C8E53F7DC1411E17F92520B8712445C/
And here...
http://cloud-2.steampowered.com/ugc/1099165943080961265/9B4797DF3AE07DD0A7C5A7A23B4E54A268ED4558/
Is there any way to solve that problem?

**Comment by robotboy655** [comment]
Fairly certain this was at least partially addressed. Unfortunately the pictures are dead so I don't know what exactly this was about.

**Comment by viral32111** [comment]
I guess steam changed their content URLs from `cloud-*.steampowered.com` to `steamuserimages-*.akamaihd.net` at somepoint in the past.

https://steamuserimages-a.akamaihd.net/ugc/1099165943081101670/6683D8955C8E53F7DC1411E17F92520B8712445C/

https://steamuserimages-a.akamaihd.net/ugc/1099165943080961265/9B4797DF3AE07DD0A7C5A7A23B4E54A268ED4558/

**Comment by robotboy655** [comment]
Yeah those issues should be mostly solved. at least for the ep2 tallgrass textures
