### ISSUE TITLE
Need an Up-to-Date guide on how to port models to gmod?

### ISSUE THREAD

**Issue by NOT-EVEN-FAZED** [Facepunch/garrysmod-issues#4653]
### Details
I started taking a model and its textures and tried porting it into gmod. So far any guide i ran into has barely helped, Or given a sign that it's been updated. So the problem here is that i got so far to the point where i have a folder containing my model(.OBJ) and my textures which are .VTF. So the problem i am at is i go on milkshape 3d and it won't let me apply the .VTF textures onto the import .OBJ file, after i made a .VMT file. So, I'm stuck and don't know what else their is to do. I tried looking it up on google but google isn't giving me solid results. Please help.
### Steps to reproduce
All i need is a Up-to-Date guide directing me what i need to do, Including any software that is needed. Please provide feedback, I figured this would be the best place to be cause no-one on discussion on steam is answering and is dead. Thank you...

**Comment by viral32111** [comment]
The [official Garry's Mod discord](https://discord.gg/gmod) is where you should go to get support. I honestly didn't think people still used Steam discussions lol.

**Comment by NOT-EVEN-FAZED** [comment]
> The [official Garry's Mod discord](https://discord.gg/gmod) is where you should go to get support. I honestly didn't think people still used Steam discussions lol.
> 
> Also [it's on the readme](https://github.com/Facepunch/garrysmod-issues#help-and-support).
> ![](https://user-images.githubusercontent.com/19510403/91758957-5aedbf00-ebc0-11ea-967d-90bf93a14fd0.png)

Thank you, Didn't know they had a discord lol, Fist time using this github too, so far i like it, Thanks again.
