### ISSUE TITLE
Any way to detect crash physics engine with Lua?

### ISSUE THREAD

**Issue by Crionis** [Facepunch/garrysmod-issues#4655]
As known, physics engine can crash sometimes and all physics objects start flying and bouncing on the map.
There is one way to fix it - restart the server, but I can't restart server automaticly because can't find a way how to detect when physics crashed from Lua, any physics parameters of prop getting as normal.

**Comment by Kefta** [comment]
Physics objects "flying and bouncing" does not mean the physics engine has crashed - if the physics engine had actually crashed, the server would crash. You should instead try debugging the root of the issue, which is typically misconfigured ShouldCollide hooks. Try removing all of your custom ones to see if this resolves the issue.

**Comment by Crionis** [comment]
For debuging I need detect with Lua when that bug happened.

**Comment by Kefta** [comment]
There's no real way to since it happens inside the physics engine, and there is no vphysics interface function for detection.
