### ISSUE TITLE
Inconsistent caching of what resources the client has obtained from the server?

### ISSUE THREAD

**Issue by TomatoCo** [Facepunch/garrysmod-issues#4657]
### Details
Garrys Mod version 2020.08.18

### Steps to reproduce
Connect to a server, then disconnect without restarting gmod.
Change the code on the server so that is is doing resource.AddFile("sound/somesound.ogg"), and that something in the gamemode uses it via Sound("somesound.ogg")
Your client will say "failed to load sound etc etc, file probably missing from disk/repository.
Restart your client, reconnect, and your client will not redownload the file but will play the sound fine.

I tested this with two different oggs and with one material (png). However, the material (used via Material("material/etcetc")) did *not* require a client restart. I also tested one ogg and the png with another client (had a friend connect to see if he was getting the same behavior, he does).

**Comment by robotboy655** [comment]
Does this only happen with .ogg files or .wav/.mp3 too?

**Comment by TomatoCo** [comment]
Just tested. It also happens with .mp3. I saw my client download the mp3 file from the server, but got

testgamemode\slash6.mp3 has 0 samples, refusing to load
Failed to load sound "testgamemode\slash6.mp3", file probably missing from disk/repository

when it went to play it. Restarted my client, plays fine.

**Comment by robotboy655** [comment]
Should be fixed on Dev, now should act just like .wav files.
