### ISSUE TITLE
tau cannon hl:s wrong behaviour

### ISSUE THREAD

**Issue by Ultimum-Aeternum** [Facepunch/garrysmod-issues#4658]
### Details
Basically hl:s tau cannon kills your self even if it should not.

### Steps to reproduce
Hl:s content is needed obiviously i suppose
Lets just take gm_construct
If you go to grass ramp left to spawn, shot under yourself(on grass displacement not concrete ramp brush), you die/get damaged by explosion even if you should not be.
If you go furher up the ramp and shoot at closest to spawn towers colunm closest again to spawn corner looking at oppoiste direction of sunlight not the shadow part of corner and crouch(that just gives highest probability to get killed), you gonna get killed by own energy beam even if you should be still immune to own damage.

For those who wanna test out write in console
lua_run hook.Add("EntityTakeDamage","c",function(a,b)print(b:GetDamageType())end
You gonna get damage type 64 which is explosion and 1024 which is energy beam.

I would be really happy to see this fix, so much happy as fellow tau masters from good old days...
Just few entity filter arguments? or idk, im no really good "koder" when it comes to C...

**Comment by robotboy655** [comment]
Have you tried loading gm_construct in HL:S and testing if the same issue happens there? This behavior should be identical to HL:S DM, the code is literally from it.

**Comment by Ultimum-Aeternum** [comment]
I litteraly know that nobody would write new code cause existing one is probably good enough :), but the thing is that i wrote "wrong behaviour" and all the fellow tau masters would agree on that quote.
The thing is that valve fucked a bit up with hl port to source and most of people who i know and who they know and forums, etc. agree on that fact.
It is so that in hl you would not die because of own beam if you are the attacker, apparently they forgot to implement that in hl:s.
So it would be pretty neat to get it patched up closer to original, also would make many old-school gamers who play gmod bit happy.
I think nobody would mind... but actuallty i am convinced that nobody should be against such returning back to source(not the engine) change.
But i understand that my argument is weak cause hl is not hl:s, but hope is hope that it will be fixed to be more like original. 
o((>ω< ))o
I want to beleve. Like Mulder does.

**Comment by Kefta** [comment]
The weapons will stay consistent to HL:S behaviour - you can write accurate HL ports yourself in Lua using the goldsrc sdk/engine code. Pretty sure someone on the workshop has already.

**Comment by robotboy655** [comment]
The issue is specifically with displacements and the penetration code, it doesn't take into account the fact that traces from below the displacement doesn't stop the trace.
