### ISSUE TITLE
Late Precache console spam due to the new update.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#4659]
Title says it all, simply using Sound() and even just a raw string without Sound() causes the console to spam with
**Late Precache of "SOUNDPATH/SOUNDFILE.EXT"** errors. (Red text)

Definitely has to do with the "Client side precaching finally does something" update. _(Yes this only happens on the client, playing sound server side doesnt output this error)_

**Comment by robotboy655** [comment]
Don't call it every frame/time you play a sound?

**Comment by MagentaIris** [comment]
> Don't call it every frame/time you play a sound?

I just told you even without the Sound() function wrapper it still happens.

I don't call sounds every frame either, it's every time the sound plays on the client realm.

**Comment by datae-git** [comment]
2 Player Local Server (sandbox)
![image](https://user-images.githubusercontent.com/51032699/92412175-38711e00-f14b-11ea-8166-d7e2eaf0fd4e.png)
SinglePlayer Server (sandbox too)
![image](https://user-images.githubusercontent.com/51032699/92412191-46bf3a00-f14b-11ea-8a8b-a1007faac9cc.png)
