### ISSUE TITLE
util.GetModelMeshes returns mesh of models/error.mdl for missing models first time

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#4660]
### Details
This only happens the first time the model mesh is requested, after that it returns nil which is what I think should happen.

On x86-64 - Chromium + 64-bit binaries branch

### Steps to reproduce
```
local model = "nonexistent_model_string.mdl"
for i = 1, 10 do
	print(util.GetModelMeshes(model) or false)
end
```

```
table: 0x02f3358dd3d0
false
false
false
false
false
false
false
false
false
```

**Comment by robotboy655** [comment]
Should be fix on Dev (other branches soon enough)
