### ISSUE TITLE
Latest change to `Spawn_Weapon` broke everything

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4661]
lmoa
![gmod_SHTd3bDZcH](https://user-images.githubusercontent.com/6339511/92612618-3c847380-f2e4-11ea-9928-c45b949c73a0.png)
![gmod_tZ1cSdHSdt](https://user-images.githubusercontent.com/6339511/92612647-41e1be00-f2e4-11ea-9e6b-74a59289dab7.png)

**Comment by YuRaNnNzZZ** [comment]
yea i wondered why weapons are not spawning with middleclick anymore

**Comment by KingTerrytheTerrible** [comment]
nice code pacefunch
