### ISSUE TITLE
Anti-Aliasing breaks Alpha/Textures on RenderTargets

### ISSUE THREAD

**Issue by theopathy** [Facepunch/garrysmod-issues#4662]
### Details
I'm using `GetRenderTargetEx` to draw the player HUD to a texture which I then use to draw to a curved surface, I also have another use for it that is broken as well but believe that both of these are related.
Anti-Alias On
![image](https://user-images.githubusercontent.com/24654131/92800320-7c169280-f3ac-11ea-8cd2-5fc23841578e.png)
Anti-Alias Off
![image](https://user-images.githubusercontent.com/24654131/92800579-b8e28980-f3ac-11ea-972c-14115f681e70.png)

```lua
local tex = GetRenderTargetEx(tex_name, ScrW(), ScrH(), RT_SIZE_FULL_FRAME_BUFFER_ROUNDED_UP, MATERIAL_RT_DEPTH_SHARED, 0, 0, IMAGE_FORMAT_RGBA8888)
local myMat = CreateMaterial(mat_name, "UnlitGeneric", {
    ["$basetexture"] = tex:GetName(),
    ["$translucent"] = "1", 
    ["$model"] = 1,
})

```

Drawing using DrawRect works fine however using DrawTextureRect is where it no longer seems to draw anything anymore.

**Comment by DBotThePony** [comment]
Do you clear depth buffer of rendertarget before drawing anything onto it?

**Comment by theopathy** [comment]
Yeah

**Comment by theopathy** [comment]
```lua
        render.PushRenderTarget(tex)
        cam.Start2D()
        render.Clear(0, 0, 0, 0)

        DrawTheHUD()
        hook.Run("HudPaintToCurve", true)
        cam.End2D()
        render.PopRenderTarget()
```

Its either affecting images or transparency because my stencils aren't working too, but that might just be the images that are not working rather than transparency which was my first case, after finding out DrawRect works fine.

**Comment by thegrb93** [comment]
I'm pretty sure I've never ran into this issue. I'll try it to be sure in a little bit. Might be something in DrawTheHUD() doing something bad.

**Comment by theopathy** [comment]
To quickly test your theory I done this 
```lua
        render.PushRenderTarget(tex)
        cam.Start2D()
        render.Clear(0, 0, 0, 0)

       -- DrawTheHUD()
      --  hook.Run("HudPaintToCurve", true)
       surface.SetDrawColor(HUD_VISOR_COLOR)
       surface.SetMaterial(helmet)
       surface.DrawTexturedRect(0, 0, ScreenWidth, ScreenHeight)
       cam.End2D()
       render.PopRenderTarget()
```

Works fine without AA but turning it on seems to break it. 

It breaks on both Radeon RX 580 and Gtx 1060 and I think a Gtx 1660 (have to double verify both gtx cards as they was other people). 
I play with AA off, so I never realized this was an issue until people was complaining about having no Hud.

**Comment by DBotThePony** [comment]
`render.SetWriteDepthToDestAlpha(false)` (reset to true after you are done) and `render.OverrideAlphaWriteEnable(true, true)`!

https://wiki.facepunch.com/gmod/render.OverrideAlphaWriteEnable
https://wiki.facepunch.com/gmod/render.SetWriteDepthToDestAlpha

**Comment by theopathy** [comment]
I was last on render.Clear on the wiki before making this issue, I hate that so much.

Thank you I added the override alpha but the render.clear(x,x,x,true) is what fixed it.
