### ISSUE TITLE
gui.OpenURL limited to 512 characters

### ISSUE THREAD

**Issue by Creekie1337** [Facepunch/garrysmod-issues#4663]
### Details
gui.OpenURL will silently fail if the URL provided is more than 512 characters.
Branch: x86-64.

### Steps to reproduce
`gui.OpenURL("https://"..string.rep("A", 500)..".com")`

Above example will work just fine, producing a "Do you really want to open this website" dialog.

`gui.OpenURL("https://"..string.rep("A", 501)..".com")`

Above example will silenty fail.

**Comment by GitSparTV** [comment]
Try to test on menu state.
If the limitation happen only with clientside function I guess it's a event queue limit

**Comment by MilkGames** [comment]
It seems to happen with the menu state aswell. 500 opens in Steam overlay, 501 doesn't do anything

**Comment by robotboy655** [comment]
Why do you need URLs that long anyway?

**Comment by MilkGames** [comment]
Our payment gateway uses quite long URLs for the checkout page, and we'd like to open them in the Steam Overlay.

**Comment by Kefta** [comment]
You absolutely should not be processing payments in the Steam overlay, that's very insecure.

**Comment by meepen** [comment]
Is there a way to add something that opens a url in a default browser?

**Comment by MilkGames** [comment]
+1 to the idea of allowing URLs to be opened in the default browser if Steam Overlay is not an option. Of course would have the same confirmation dialog as the overlay.

**Comment by WilliamVenner** [comment]
> +1 to the idea of allowing URLs to be opened in the default browser if Steam Overlay is not an option. Of course would have the same confirmation dialog as the overlay.

Huge +1 for this. This would be massively useful.

**Comment by biorisk2** [comment]
> +1 to the idea of allowing URLs to be opened in the default browser if Steam Overlay is not an option. Of course would have the same confirmation dialog as the overlay.

PLEASE do this.

**Comment by Torbikini** [comment]
> Why do you need URLs that long anyway?
They're probably URL encoding a bunch of data or something -- I don't see a use-case for that personally. I do love the other suggestions in this thread to allow opening a link in the user's default browser (or at least provide the uesr a choice) as a way of letting us connect the game to a website with a more modern browser.

**Comment by robotboy655** [comment]
Bumped to 2000.

**Comment by Kefta** [comment]
Can it be bumped up to exactly 8000 to be complaint with https://www.rfc-editor.org/rfc/rfc9110#section-4.1-5 ?

**Comment by meepen** [comment]
Can it be increased to an indefinite amount of characters to support
everything?

**Comment by Kefta** [comment]
Can this be reopened for the further raising? I don't want to create a new issue but it should not be forgotten about.

**Comment by robotboy655** [comment]
You don't need more than 2k. I will not be increasing it further.

**Comment by biorisk2** [comment]
I actually found the old limit and current one as a limitation for creating custom rest api's & other url-based data communication, sometimes you need to transmit long strings or encoded data that exceeds these limits, and when configuring a webhost to support it - the actual hold up is some rinky dink number on the gmod client that force-fails, resulting in the wacky need to open multiple urls (or ultimately abandon the project)

**Comment by meepen** [comment]
Again, why does there even need to be a limit when we have stuff like std
string and bootil string backing everything in gmod??

**Comment by biorisk2** [comment]
idk seems stubborn not to make it industry standard, literally an artificial limitation introduced by the devs.
