### ISSUE TITLE
Incorrect bodygroups being toggled at 65+, game hard crashes at 70+

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-issues#4665]
### Details
Gmod Version: any / all

* Models with >64 bodygroups are not usable beyond that point within Garry's Mod.
* At bodygroup 65-69, incorrect bodygroups will be toggled instead of the correct ones.
* At bodygroup 70 (or was it 71 I forget...) and higher the game will instantly crash when toggled.
* Bodygroups 0-64 still work perfectly as intended.

### Steps to reproduce
Set a model to one with more than 64 bodygroups and use bodygroup 65 (66) or higher.

**Comment by robotboy655** [comment]
Can you link any models that are affected by this?

**Comment by Vuthakral** [comment]
Sorry for the slow response; honestly forgot I even submitted this.

[Here's a version of my halo elite playermodel with just an absurd amount of bodygroups compiled into it](https://cdn.discordapp.com/attachments/364089893900648470/759050127506931742/sangheili_with_fucktons_of_bodygroups.7z)

If this is a hard cap then well shit; I had just hoped/assumed that the game would have been able to handle more with the old [update back in 2019](https://gmod.facepunch.com/blog/february-2019-update) which made gmod's studiomdl able to handle quote "infinite bodygroups"

**Comment by robotboy655** [comment]
It's hard for me to tell without textures, but does the first bodygroup only has 3 different models despite having 12 options? And the second bodygroup (head) has only 2 models out of 4 options, 1 of which is invisible head? I just need to confirm I am seeing this correctly.

If this is correct then I may have a fix for the crashing for your model. There will always be a limit on bodygroup count (for performance/network reasons), but I think with this fix it should be higher in-game. It may be even higher on x64 builds, but I am not sure.

**Comment by Vuthakral** [comment]
Oh sorry, it slipped my mind and I forgot to link the workshop addon which has the materials for that model.

Yeah you are seeing it correctly, The seemingly duplicate entries call on different materials for skintones of the alien character. The invisible head one was to hide the head for helmets it did not fit in.

The body & undersuit materials can be found in [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=1550974781), the different armours are in different addons in which are linked in the description if it.

Honestly I'm probably the only person in history who will benefit from an increased bodygroup limit, I value heavy customization with playermodels and try to crank it as high as I can without breaking anything.

**Comment by robotboy655** [comment]
Should be fixed on Dev.

**Comment by KaesarZZ** [comment]
What was fixed here? models with more than 64 bodygroups are still going crazy showing randoms bodygroups and crashing, any chance to get this fixed?

**Comment by robotboy655** [comment]
Is your game 4 years out of date? If you are still experiencing crashes, open a new issue with steps to reproduce the crash and a link to the model. But the limit will not be removed.
