### ISSUE TITLE
noclamp on a material created with CreateMaterial

### ISSUE THREAD

**Issue by theopathy** [Facepunch/garrysmod-issues#4668]
As title said, I can't find anything on the source wiki or gmod wiki. It mentions flags for the other types of Material Png parameters but not for noclamp.

This is the code im using

```lua
local mat =   CreateMaterial(
    maNme,
    "UnlitTwoTexture",
   
    {
        ["$basetexture"] =  "materials/halo/halo_grid_bg_gray2.png", -- Make the material use our render target texture
        ["$translucent"] = "1", -- make the drawn material transparent 
        ["$texture2"] = "materials/halo/nebula.png",
        ["Proxies"] = {
            ["TextureScroll"] = {
                ["texturescrollvar"] = "$texture2transform",
                ["texturescrollrate"] = 0.01,
                ["texturescrollangle"] = 0
            }
        }
    }
)
```

**Comment by theopathy** [comment]
Solved by adding binary flags to the start of the material string
`"0000110materials/halo/halo_grid_bg_gray2.png"`

**Comment by thegrb93** [comment]
Where the fuck is that documented?

**Comment by theopathy** [comment]
What adding the binary?
I just got every data about the material and compared them

**Comment by robotboy655** [comment]
You are meant to use the Material() function to load .png textures.

**Comment by Kefta** [comment]
@robotboy655 But doing so doesn't allow you to set vmt parameters on that png as CreateMaterial allows you to.

**Comment by robotboy655** [comment]
1) It creates a material which you can copy and edit
2) I meant solely for the purpose of getting the $basetexture of a .png

**Comment by theopathy** [comment]
Im already doing loading it with material as it's on the wiki and tells you
to do so

**Comment by thegrb93** [comment]
Where is putting binary flags at the start of material path documented?

**Comment by robotboy655** [comment]
It's not and you are not supposed to do it/use it/think about it.

**Comment by theopathy** [comment]
Then how would I solve my problem without it?

**Comment by robotboy655** [comment]
As I said, you use Material() function.
`Material( "halo/halo_grid_bg_gray2.png", "noclamp" ):GetTexture( "$basetexture" ):GetName()`

**Comment by theopathy** [comment]
That's what im doing, and I just didn't include it as part of the code as
that wasent the problem that was causing me errors
