### ISSUE TITLE
localization .properties files don't support escapes correctly

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-issues#4669]
### Details
```none
Protocol version 24
Exe version 2020.03.17 (garrysmod)
Exe build: 19:51:57 Aug  7 2020 (7891) (4000)
GMod version 2020.08.18, branch: unknown, multicore: 1
Windows 32bit
```

- The character sequence `\n` is not supported
- Line continuation with `\` is not supported

Based on [the wiki page](https://en.wikipedia.org/wiki/.properties) and [the 'spec'](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#load(java.io.Reader)) for `.properties` files, I assumed I would be able to embed newlines with something along the lines of

```properties
foo=\
	this is a very\n\
	long line of\n\
	text that has\n\
	line breaks in it
```

However lines that end with `\` are truncated and `\n` sequences are turned into `n`

### Steps to reproduce
Input:
```properties
test1=aa\nbb
test2=aa\
	bb
test3=\
	aa\
	bb
```
Output:
```properties
test1=aanbb
test2=aa
test3=
```
Expected:
```properties
test1=aa\nbb
test2=aabb
test3=aabb
```

**Comment by robotboy655** [comment]
Both \ and \n should now work properly on Dev.
