### ISSUE TITLE
GetModel returning differently on Client and Server.

### ISSUE THREAD

**Issue by NickPackham** [Facepunch/garrysmod-issues#4670]
Sometimes Models can return differently on Client than on Server, from what I've been told this is because it doesn't use the File-Path of the Model, it uses the MDL path.

Here's a Model Pack to reproduce, just set your Model to 501st Medic then do GetModel() on Server and Client and you'll see different results.
https://steamcommunity.com/sharedfiles/filedetails/?id=2129541240

![image](https://user-images.githubusercontent.com/46549847/93229684-b3c66700-f72b-11ea-8dd2-578d991901a9.png)

**Comment by robotboy655** [comment]
Should be fixed on dev.
