### ISSUE TITLE
TTT Scoreboard alignment for Karma, Score and Deaths is broken on portuguese translation

### ISSUE THREAD

**Issue by r47orr** [Facepunch/garrysmod-issues#4672]
![image](https://user-images.githubusercontent.com/64384760/93528872-673c8080-f911-11ea-9824-b1ff2ae49c8e.png)

I've tested it using the TTT original Portuguese translation but might happen with other translations as well.

**Comment by robotboy655** [comment]
Please read the readme of this repository.
