### ISSUE TITLE
Half-Life Satchel won't explode on dev branch nor x86-64 branch.

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4678]
The Half-Life satchel won't explode via player input. I found this bug on the dev branch and the x86-64 branch.

The bug doesn't exist on the other branches.

Steps to recreate:
1, Go to the dev branch or the x86-64 branch of Garry's Mod
2, Give yourself a weapon_satchel
3, throw a satchel and press the button.

[https://www.youtube.com/watch?v=QptIBt6bWLQ&ab](url)

**Comment by robotboy655** [comment]
Fixed.
