### ISSUE TITLE
Why the object returned by `ToScreen` does not have the same data structure for X and Y like `Vector()`

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#4681]
### Details
I was coding and tried to index `Vector():ToScreen()` result with indexes `1` and `2` just like the vector. I am on the normal steam branch and my GMod version is:
![image](https://user-images.githubusercontent.com/9112662/94172673-74bab300-fe9b-11ea-98d9-6441c9e22b5e.png).

### Steps to reproduce
1. Give Gmod to execute the following code snippet
```lua
local test = true

function TOOL:Think()
  if(CLIENT) then
    if(test) then
      test = false
      local v = Vector(0,0,0)
      local s = v:ToScreen()
      local x1 = s[1]
      local x2 = s["x"]
      print(v, x1, x2)

      print(("1"):rep(20))
      PrintTable(s)
      print(("2"):rep(20))
    end
  end
end
```

2. You receive nil value after indexing
```lua
0.000000 0.000000 0.000000	nil	450.71765136719
11111111111111111111
visible	=	true
x	=	450.71765136719
y	=	347.96237182617
22222222222222222222
```

**Comment by GitSparTV** [comment]
> Should be called from a 3D rendering environment or after cam.Start3D or it may not work correctly.

**Comment by Kefta** [comment]
Read https://wiki.facepunch.com/gmod/Vector:ToScreen, specifically the return section - it returns a table, not a vector.

**Comment by dvdvideo1234** [comment]
@Kefta I `know` that it returns a table... I am asking `why` it returns a table.

**Comment by WilliamVenner** [comment]
> @Kefta I `know` that it returns a table... I am asking `why` it returns a table.

@dvdvideo1234 So that the `visible` field can be provided

**Comment by Kefta** [comment]
And because 2D vectors aren't binded to Lua.

**Comment by dvdvideo1234** [comment]
Thank you very much ! I guess I cannot swap them around for drawing unless I index the vectors with x, y and z.

**Comment by WilliamVenner** [comment]
"Swap them around for drawing"?

**Comment by Kefta** [comment]
It's a table not a vector, and there's no z key in it.

**Comment by dvdvideo1234** [comment]
@Kefta Exactly. I will need to make a function that uses vector/table as line starting / end  point.
