### ISSUE TITLE
Hammer crashes when moving camera in Portal 2's sp_a4_finale4.vmf

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4686]
### Details
Hammer build 8538

This error also occurs on some other Portal 2 vmfs.

### Steps to reproduce
Decompile sp_a4_finale.bsp
Open decompiled map in Hammer.
Move camera around (in map in zip-archive, move camera up)

[CrashData.zip](https://github.com/Facepunch/garrysmod-issues/files/5292247/CrashData.zip)

**Comment by MARK2580** [comment]
For starters, there is no such map. There are only 1/2/3 and 4. I checked them all and there are no departures.

**Comment by robotboy655** [comment]
It's crashing due to the `models/player/chell/headless_player.mdl` model, you can manually edit it out of the .vmf in the mean time.

**Comment by robotboy655** [comment]
Should be fixed.
