### ISSUE TITLE
Bug with explosive barrel (props_c17\oildrum001_explosive.mdl)

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-issues#4687]
if you throw explosive barrel (models\props_c17\oildrum001_explosive.mdl), then grab it with weapon_physcannon or player pickup (+use), and then let it touch the ground, barrel will explode. Happens in all source-1 games

**Comment by robotboy655** [comment]
Fixed for gravgun/+use pickup, physgun and water interactions are not affected

**Comment by thegrb93** [comment]
This was every noob's favorite bug. rip

**Comment by weaponcubemap** [comment]
> This was every noob's favorite bug. rip

Yes, bugs can't live longer. R.I.P.
