### ISSUE TITLE
m_bDisableTabbing locks keyboard input on the DTextEntry.

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4689]
`entry:SetTabbingDisabled(true)` is causing DTextEntry to keep the keyboard focus forever even when any of parents is invisible or a mouse click was pressed on other panel.
It releases the focus if `SetKeyboardInputEnabled` is set to false.

**Comment by robotboy655** [comment]
Makes perfect sense, m_bDisableTabbing disables FocusNext/FocusPrevious which are used to kill focus because Source Engine is very special this way and doesn't have a kill focus functionality.

**Comment by GitSparTV** [comment]
Damn, I wanted to use tab to switch to the next field and also have the ability to unfocus it by a click

**Comment by GitSparTV** [comment]
https://wiki.facepunch.com/gmod/Panel:KillFocus
Doesn't work as well, I guess intended as well

**Comment by GitSparTV** [comment]
How does ChatBox work then? it has OnTab hook

**Comment by GitSparTV** [comment]
nvm it unfocus when I click RichTExt
