### ISSUE TITLE
Half-Life 2: Episode 2 Crash

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4693]
I was going through Half-Life 2: Episode 2 and when I tried to close the silo in ep_outland_11a, the game freezes and crashes.

I must let you know that I had to use a model replacement addon because some parts of HL2:Ep2 required Ep2 models and GMod's models don't have the required animations to progress through the campaign.

I tried using all of the branches of GMod but none of them helped.

Instructions to recreate:
Try to close the silo in ep_outland_11a

**Comment by robotboy655** [comment]
Should be fixed on Dev and in the next update.
