### ISSUE TITLE
Certain entities falsely report EntIndex == 0

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#4695]
### Details
From my testing, `phys_constraintsystem` and `logic_collision_pair` falsely return 0 on :EntIndex(), breaking addons that rely on EntIndex 0 being the world (e.g in OnEntityCreated / EntityRemoved)

**Comment by thegrb93** [comment]
Source engine does this. Those entities don't exist on client/aren't networked/don't need networked id (something like that).

**Comment by robotboy655** [comment]
You have `game.GetWorld` and `Entity:IsWorld` to test whether the entity is the world or not. You are falsely assuming that entity index 0 should be only the world.
