### ISSUE TITLE
net.SendOmit does nothing when given NULL as omit argument

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4699]
### Details

Client branch is x86_64, server branch is main.

net.SendOmit does nothing when given `NULL` as omit argument.

This means if a NULL player is somehow passed into net.SendOmit then it will simply silently fail and the net message will not be received by any clients. This could introduce bugs into networking code if the omitted player somehow ends up invalid by the time the net message is sent to clients.

net.SendOmit should simply broadcast the net message if passed `NULL`, as this also allows for conditional omittance.

This behaviour contradicts passing a table of `NULL`s into net.SendOmit -- it actually works as expected.

### Steps to reproduce
```lua
util.AddNetworkString("test_SendOmit")
util.AddNetworkString("test_SendOmit2")

if SERVER then
    timer.Create("test_SendOmit", 4, 0, function()
        net.Start("test_SendOmit")
        net.SendOmit(NULL)

        net.Start("test_SendOmit2")
        net.SendOmit({NULL})

        print("Broadcast", "test_SendOmit")
    end)
else
    net.Receive("test_SendOmit", function()
        print("Received", "test_SendOmit")
    end)

    net.Receive("test_SendOmit2", function()
        print("Received", "test_SendOmit2")
    end)
end
```

You will see that the client receives `test_SendOmit2` but not `test_SendOmit`.

**Comment by robotboy655** [comment]
Fix
