### ISSUE TITLE
Modal hierarchy only works on EditablePanel and derivatives

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4700]
### Details

I am trying to open a DermaMenu over a DFrame that has had `DoModal()` called on it.

The DermaMenu draws over the DFrame but you cannot click on it. The hovered panel remains the DFrame. Even calling `MakePopup()` and `DoModal()` on the DermaMenu does nothing. Notably, if you wait until the next frame before calling these, the DermaMenu will have mouse focus for a single frame before it returns back to the DFrame.

I noticed after a bit of playing around that EditablePanel is not vulnerable to this issue.

**Comment by robotboy655** [comment]
This is in a sense intentional.

https://wiki.facepunch.com/gmod/Global.DermaMenu has a parent argument which you are meant to use in this case, but it doesn't completely solve the problem.

I have pushed changes to Dev that should make code like this work properly:
```

concommand.Add( "testmodal", function( ... )
	local Panel = vgui.Create( "DFrame" )
	Panel:SetPos( 200, 200 )
	Panel:SetSize( 500, 500 )
	Panel:SetTitle( "Test" )
	Panel:MakePopup()
	Panel:DoModal()

	local Whatever = vgui.Create( "DButton" , Panel )
	Whatever:Dock(TOP)
	Whatever.DoClick = function( s )

		local m = DermaMenu( nil, Panel ) -- Notice the second arg
		m:AddOption( "DUCK", print )
		m:AddOption( "DUC2K", print )
		m:Open()

	end

	local Whatever = vgui.Create( "DTextEntry" , Panel )
	Whatever:Dock(TOP)
	Whatever:SetText(2)

end )
```

**Comment by WilliamVenner** [comment]
Awesome thank you :D

**Comment by WilliamVenner** [comment]
@robotboy655 I'm still getting this problem on dev:

![image](https://user-images.githubusercontent.com/14863743/99700351-f8071800-2a8a-11eb-8182-d7b677071605.png)

**Comment by robotboy655** [comment]
Both the server (Sends the updated Lua files to client) and client (Has the needed Lua functionality) must be on Dev/x86-64.
