### ISSUE TITLE
CheckPassword not interpolating predefined messages

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#4701]
### Details
If you attempt to return one of the predefined messages in the example for [CheckPassword](https://wiki.facepunch.com/gmod/GM:CheckPassword) you don't end up with the interpolated message, but instead you just get the string returned without the prefixed hash. 

### Steps to reproduce
Below should reproduce this. 

```lua
local function Example(strSteamID64, strIp, strPassword, strProvidedPassword, strPlayerName)
	return false, "#GameUI_ServerRejectLANRestrict"
end
hook.Add("CheckPassword", "Example" , Example)
```

User will end up getting `GameUI_ServerRejectLANRestrict` as the disconnection error. 

Tested on live & x86-64 client.

**Comment by thegrb93** [comment]
interpreted*

**Comment by robotboy655** [comment]
It's on purpose.

**Comment by GitSparTV** [comment]
@robotboy655 The example on the wiki still uses it

**Comment by TeddiO** [comment]
Exactly why I posted this issue, seems to be a conflict of information there.

**Comment by Kefta** [comment]
It's kind of silly to not allow it since it can be hardcoded. The VAC ban message issue was never really an issue.

**Comment by meepen** [comment]
I believe the problem with the vac message was that it actually showed the
symbol

**Comment by Kefta** [comment]
Ah, perhaps that should be resolved separately then.
