### ISSUE TITLE
Gravity Gun is not fully functional.

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4702]
I don't know if this bug was left unnoticed, left in because fixing broken codes is a pain in the hinny, or I'm just being a butt. However,

The Gravity Gun can not pick things up through certain fences. It can pick stuff up from other fences because I think those fences models are actually full of holes, while the fence seen in the video the model is quite solid and only bullets can go through it.

Again, I don't know I'm just being a butt about this, but the Gravity Gun from Half-Life 2 can pick stuff up through all fences and stuff and GMod's Gravity Gun doesn't. 

Please let me know if I'm just being a butt or if this is an actual issue.

I was using the dev branch of GMod

Instructions:
Spawn a physics object, then spawn a fence. 
(Something like props_c17/fence01a.mdl, and not props_c17/gate_door02a.mdl)
Try to pick the physics object through the fence with a weapon_physcannon

https://www.youtube.com/watch?v=EQqBV5XFCME&ab_channel=TheBillinator3000

**Comment by TheBillinator3000** [comment]
EDIT: Added what branch I was using

**Comment by robotboy655** [comment]
This behavior seems to be consistent with Half-Life 2, at the very least the fences on the very first map of Half-Life 2, so yeah.

**Comment by WilliamVenner** [comment]
I think it's a HL2 EP2 thing:

![](https://i.venner.io/hl2_kzYvIrjAYQ.jpg)

Loading this map on Gmod did not let me use the gravity gun through the fence.

**Comment by WilliamVenner** [comment]
I'm curious as to how they went about doing this... did they add a new collision group, or did they change the behavior of the gravity gun entirely?

Imo, the behavior of the EP2 gravity gun is much better.

**Comment by TheBillinator3000** [comment]
It was a thing in Half-Life 2: Episode 1 where you had to grab the gun from behind the fence. Since I played a few Half-Life 2 mods that had that mechanic I thought Half-Life 2's gravity gun worked just as well. 

After experimentation from both me an Rubat, Garry's Mod's gravity gun's inability to grab things through fence  is consistent with the gravity gun from Half-Life 2.

So that means there's an 80% chance the devs aren't going to do anything about it.

🙃

**Comment by WilliamVenner** [comment]
```cpp
//-----------------------------------------------------------------------------
// Purpose: Trace a line the special physcannon way!
//-----------------------------------------------------------------------------
void UTIL_PhyscannonTraceLine( const Vector &vecAbsStart, const Vector &vecAbsEnd, CBaseEntity *pTraceOwner, trace_t *pTrace )
{
	// Default to HL2 vanilla
	if ( hl2_episodic.GetBool() == false )
	{
		CTraceFilterNoOwnerTest filter( pTraceOwner, COLLISION_GROUP_NONE );
		UTIL_TraceLine( vecAbsStart, vecAbsEnd, (MASK_SHOT|CONTENTS_GRATE), &filter, pTrace );
		return;
	}

	// First, trace against entities
	CTraceFilterPhyscannon filter( pTraceOwner, COLLISION_GROUP_NONE );
	UTIL_TraceLine( vecAbsStart, vecAbsEnd, (MASK_SHOT|CONTENTS_GRATE), &filter, pTrace );

	// If we've hit something, test again to make sure no brushes block us
	if ( pTrace->m_pEnt != NULL )
	{
		trace_t testTrace;
		CTraceFilterOnlyBrushes brushFilter( COLLISION_GROUP_NONE );
		UTIL_TraceLine( pTrace->startpos, pTrace->endpos, MASK_SHOT, &brushFilter, &testTrace );

		// If we hit a brush, replace the trace with that result
		if ( testTrace.fraction < 1.0f || testTrace.startsolid || testTrace.allsolid )
		{
			*pTrace = testTrace;
		}
	}
}
```

Even if you do `hl2_episodic 1` it has no effect.

```cpp
bool HasContentsGrate( CBaseEntity *pEntity )
{
	// FIXME: Move this into the GetModelContents() function in base entity

	// Find the contents based on the model type
	int nModelType = modelinfo->GetModelType( pEntity->GetModel() );
	if ( nModelType == mod_studio )
	{
		CBaseAnimating *pAnim = dynamic_cast<CBaseAnimating *>(pEntity);
		if ( pAnim != NULL )
		{
			CStudioHdr *pStudioHdr = pAnim->GetModelPtr();
			if ( pStudioHdr != NULL && (pStudioHdr->contents() & CONTENTS_GRATE) )
				return true;
		}
	}
	else if ( nModelType == mod_brush )
	{
		// Brushes poll their contents differently
		int contents = modelinfo->GetModelContents( pEntity->GetModelIndex() );
		if ( contents & CONTENTS_GRATE )
			return true;
	}

	return false;
}
```

![image](https://user-images.githubusercontent.com/14863743/101808245-04244980-3b0e-11eb-9479-31ded04c5f2c.png)

**Comment by thegrb93** [comment]
Given that the graviton beam flux would be attenuated considerably through the diffraction effects of a wire gate, the current behavior is far more realistic.

**Comment by WilliamVenner** [comment]
> Given that the graviton beam flux would be attenuated considerably through the diffraction effects of a wire fence, the current behavior is far more realistic.

Tell that to the super gravity gun

**Comment by robotboy655** [comment]
Ported more episodic behavior for the gravity gun - including being able to pickup props behind a grate-type props (behind hl2_episodic)
Fixed gravity gun sounds only being audible for its owner
Fixed weapons sometimes trying to play their sounds from underground, resulting them in not playing any sounds
