### ISSUE TITLE
sound.Add (CHAN_STATIC and CHAN_AUTO undocumented behaviour)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4705]
### Details
When creating a sound using sound.Add which channel is set to CHAN_STATIC or CHAN_AUTO, those sounds sound different (cleaner, clearer) than sounds not created by using those two.
This behaviour is not documented and there is no way to replicate this behaviour somehow.
All sounds cuts off if played CHAN_STATIC or CHAN_AUTO sounds are played too frequently.

### Steps to reproduce
Create a sound with soundchannel CHAN_STATIC with the help of the wiki: https://wiki.facepunch.com/gmod/sound.Add
See the difference for every other sound channel, like CHAN_WEAPON.

**Comment by robotboy655** [comment]
There's no audible difference, unless you start playing multiple sounds at the same time which doesn't count.
```
sound.Add( {
	name = "enzo_engine_idle",
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 80,
	pitch = 100,
	sound = "phx/explode03.wav"
} )

sound.Add( {
	name = "enzo_engine_idle2",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = 80,
	pitch = 100,
	sound = "phx/explode03.wav"
} )

concommand.Add( "123123", function( ply, cmd, args )
	ply:EmitSound( "enzo_engine_idle" )
end )
concommand.Add( "1231232", function( ply, cmd, args )
	ply:EmitSound( "enzo_engine_idle2" )
end )
```

**Comment by mcNuggets1** [comment]
It seems like CHAN_STATIC doesn't stop previous sounds, but CHAN_WEAPON does.
Non the less, playing sounds rapidly for example in weapons sounds different for both of these soundchannels.

**Comment by robotboy655** [comment]
Documented this then.

https://wiki.facepunch.com/gmod/Enums/CHAN

**Comment by mcNuggets1** [comment]
But why does it do that and how to get channels doing the same thing?
And especially how to stop the sound stuttering when too many sounds are emitted?

**Comment by robotboy655** [comment]
That's just how Source Engine works, use channels that allow sound stacking. They are pointed out on the wiki page linked above.
