### ISSUE TITLE
SetMaxArmor doesn't reset on death like SetMaxHealth

### ISSUE THREAD

**Issue by timothybvf** [Facepunch/garrysmod-issues#4707]
### Details
I made a hook that added 10 max hp and armor on kill, the hp resets when you die but when you respawn and use suit batteries, it's still whatever it was before and the max hasn't been reset to 100. 

### Steps to reproduce
Use setmaxarmor to set someones armor above 100, have them die and check.

**Comment by timothybvf** [comment]
This was linked in the discord, all credit to tanknut

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/player_manager.lua#L438

**Comment by DBotThePony** [comment]
Because max health is (re)set by PlayerManager on spawn. In my opinion, it is not a bug.

![Code_jVJVGX9uNG](https://user-images.githubusercontent.com/6339511/97069387-316a7600-15fa-11eb-829f-9bcc98ebdf70.png)

**Comment by Jvs34** [comment]
Yes, missing features are not "bugs", but the issue is still valid.

**Comment by timothybvf** [comment]
It seems more like something that was overlooked when this was released and not intentional to be left like this. I guess you could call it either or.

**Comment by robotboy655** [comment]
Should act like maxHealth now
