### ISSUE TITLE
Entity:NetworkVarNotify super scuffed

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [Facepunch/garrysmod-issues#4708]
### Details
1) NetworkVarNotify can get called with an another entity's DT values.
2) NetworkVarNotify can get called with a corrupted(???) entity, whose EntIndex matches the correct entity's, but its' class is wrong.
3) NetworkVarNotify can get called multiple times following this order:
Correct value -> Wrong value
Wrong value -> Correct value

All of these render NetworkVarNotify pretty much unusable.

### Steps to reproduce
Load the entities from the .zip file and play around with spawning & removing them. Eventually they'll start messing up, badly. Doesn't seem to work on a local server with no fakelag, but works on either srcds or having fakelag set to even 10. The most surefire way to reproduce this is spawn ent №1, remove it, wait for 2 seconds and spawn ent №2.

[test_ents.zip](https://github.com/Facepunch/garrysmod-issues/files/5432960/test_ents.zip)

**Comment by robotboy655** [comment]
Already tracked in https://github.com/Facepunch/garrysmod-requests/issues/324
