### ISSUE TITLE
Half-Life: Source glock weapon bodygroup issue.

### ISSUE THREAD

**Issue by malortie** [Facepunch/garrysmod-issues#4709]
### Details

Please note that debugging this issue requires you to have Half-Life: Source installed and mounted in Garry's mod.

#### Test branches

The following issue has been tested on the branches below. Game cache integrity has been verified for each branch.

NONE - Opt out of all beta programs

```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.10.23, branch: unknown, multicore: 0
Windows 32bit
```

dev

```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 19:40:25 Oct 12 2020 (7851) (4000)
GMod version 2020.10.23, branch: dev, multicore: 1
Windows 32bit
```

prerelease

```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.10.23, branch: prerelease, multicore: 0
Windows 32bit
```

#### Context

I am the creator of an addon that is a port of the They Hunger weapons to Gmod. In the original They Hunger, it is possible to toggle silencer on the glock. This behavior is also replicated in my addon.

Recently, a user has reported that my addon would cause the model of the original Half-Life: Source glock (weapon_glock_hl1) to display the silencer.

The TH glock uses it's own weapon class (weapon_th_glock). To enable the silencer, I set the viewmodel's bodygroup to a different value. This is done in the 'Deploy' method. When deploying the TH glock (weapon_th_glock) and switching to the HL1 Source (weapon_glock_hl1), the weapon_glock_hl1 displays the silencer.

At first, I believed this might happen because the viewmodel state would not be fully reset before deploying a different weapon, but after performing switches between different weapons other than the TH glock, the viewmodel bodygroup value was eventually reset to 0. Then, after switching to the HL1 glock (weapon_glock_hl1), the viewmodel still shows the silencer as if the bodygroup was set, even if the bodygroup value is set to 0.

I also respawned and equipped with the HL1 glock (weapon_glock_hl1) and it still shows the silencer, even if the bodygroup value is set to 0.

I created a minimalistic weapon to reproduce the behavior. Please note that debugging this issue requires you to have Half-Life: Source installed and mounted in Garry's mod. The weapon uses the same model as the Half-Life: Source glock and sets the viewmodel bodygroup to (2,1) 'silencer'. I also use a hook to display the viewmodel bodygroup when switching between weapons.

### Steps to reproduce

(**1**) Download and extract the [following addon](https://github.com/malortie/gmod-bodygroup-issue) to your Garry's mod addons folder.

(**2**) Launch Garry's mod.

(**3**) Open up the Start Game menu and choose Sandbox gamemode. Enable 'Give weapons on spawn', then start a singleplayer game.

(**4**) In the console, type the following commands:

```
sv_cheats 1
developer 1
```

(**5**) Open the spawn menu and equip with the 'Half-Life 1 glock' from the category 'Half-Life: Source'. 

Ensure you see the following in the console:
``` 
Switching from weapon_physgun to weapon_glock_hl1. Current bodygroup at index 2: 0
Giving <player> a weapon_glock_hl1
```
Ensure you see that the viewmodel shows the glock model without the silencer. (ok)

(**6**) Open the spawn menu and equip with 'Weapon test 1' from the category 'Other'

Ensure you see the following in the console:
```
Switching from weapon_glock_hl1 to weapon_test1. Current bodygroup at index 2: 0
[weapon_test1] Current bodygroup at index 2: 1
Giving <player> a weapon_test1
```
Ensure you see that the viewmodel shows the glock model with the silencer. (ok)

(**7**) Switch back to the Half-Life 1 glock, (weapon_glock_hl1)

Ensure you see the following in the console:
```
Switching from weapon_test1 to weapon_glock_hl1. Current bodygroup at index 2: 1
```
Ensure you see that the viewmodel shows the glock model with the silencer. (wrong)

(**8**) Switch to the SMG1 (weapon_smg1) 

Ensure you see the following in the console:

```
Switching from weapon_glock_hl1 to weapon_smg1. Current bodygroup at index 2: 1
```

(**9**) Switch to the AR2 (weapon_ar2)

Ensure you see the following in the console:

```
Switching from weapon_smg1 to weapon_ar2. Current bodygroup at index 2: 0
```

(**10**) Switch back to the Half-Life 1 glock, (weapon_glock_hl1)

Ensure you see the following in the console:
```
Switching from weapon_ar2 to weapon_glock_hl1. Current bodygroup at index 2: 0
```
Ensure you see that the viewmodel shows the glock model with the silencer. (wrong)

(**11**) In the console, type the following commands:

```
kill
```

(**12**) Respawn, open the spawn menu and equip with the 'Half-Life 1 glock' from the category 'Half-Life: Source'.

Ensure you see the following in the console:
``` 
Switching from weapon_physgun to weapon_glock_hl1. Current bodygroup at index 2: 0
Giving <player> a weapon_glock_hl1
```
Ensure you see that the viewmodel shows the glock model with the silencer. (wrong)

**Comment by robotboy655** [comment]
The real issue here is that you are not resetting the view model after altering it.

**Comment by robotboy655** [comment]
Ok it should not reset for you automatically.
