### ISSUE TITLE
gravity gun punts the +use prop after throwing it

### ISSUE THREAD

**Issue by TotallyARussian** [Facepunch/garrysmod-issues#4710]
when you pick up a prop using +use and throw it while holding the gravity gun, the gravity gun automatically punts the thrown item.
steps to reproduce:
step 1: equip the gravity gun
step 2: spawn a soda can
step 3: pick it up using +use and throw it

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4572
