### ISSUE TITLE
weird N on the right side of the screen

### ISSUE THREAD

**Issue by veritism** [Facepunch/garrysmod-issues#4711]
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.10.23, branch: unknown, multicore: 0
Windows 32bit

whenever i start the game, this weird un-interactable N is on the side of the screen

how i get it to appear is by starting the game
screenshots:

![Screenshot (277)](https://user-images.githubusercontent.com/73498320/97222849-f05e9700-179c-11eb-85e8-96735e73cddd.png)
![Screenshot (278)](https://user-images.githubusercontent.com/73498320/97222861-f5234b00-179c-11eb-9d29-88b6a9c70e77.png)
![Screenshot (279)](https://user-images.githubusercontent.com/73498320/97222880-fa809580-179c-11eb-9c3b-0a1fc8890072.png)
![Screenshot (275)](https://user-images.githubusercontent.com/73498320/97222906-079d8480-179d-11eb-8367-925d64428e44.png)

**Comment by GitSparTV** [comment]
Have you tried to run the game with `-noaddons -noworkshop`?

**Comment by veritism** [comment]
yes

**Comment by GitSparTV** [comment]
Have you verified the game integrity in steam game options?

**Comment by veritism** [comment]
?

**Comment by GitSparTV** [comment]
Read the first paragraph
https://support.facepunchstudios.com/hc/en-us/articles/213577689-Common-start-up-Problems-and-Solutions?mobile_site=true

**Comment by veritism** [comment]
that doesn't work

**Comment by veritism** [comment]
@GitSparTV 
still doesn't work

**Comment by robotboy655** [comment]
Enter `mat_texture_list 1` into your console and find that texture there, it should point you to the path of the texture. Post it here.

**Comment by veritism** [comment]
its not there
![Screenshot (280)](https://user-images.githubusercontent.com/73498320/97230283-af1fb480-17a7-11eb-8025-7c93b58c62f1.png)
![Screenshot (281)](https://user-images.githubusercontent.com/73498320/97230296-b2b33b80-17a7-11eb-9340-834246324c3b.png)
![Screenshot (282)](https://user-images.githubusercontent.com/73498320/97230310-b777ef80-17a7-11eb-8dc1-6c1c51ae9415.png)

**Comment by GitSparTV** [comment]
are you sure this texture is not a some kind of a overlay from a 3rd party app?

**Comment by GitSparTV** [comment]
also, you said you tried with `-noaddons`, but the screenshots has addons, so I have a doubt

**Comment by veritism** [comment]
A, no

and B, i turned them back on

**Comment by thegrb93** [comment]
You got N'd by the N malware. Feel the N

**Comment by veritism** [comment]
?

**Comment by zffs** [comment]
It means you have the N word pass, no reason to be alarmed.

**Comment by robotboy655** [comment]
https://www.youtube.com/watch?v=F7bbCOkNRBg

**Comment by WilliamVenner** [comment]
That's it, we've reached the peak of crappy software. Literally nothing can top how awful that is. To think a team of people somehow came up with that.
