### ISSUE TITLE
Custom engine.LightStyle parameters and explosions cause chunks of a map's lightmap to update

### ISSUE THREAD

**Issue by spaztron64** [Facepunch/garrysmod-issues#4719]
### Details
When using an engine.LightStyle parameter other than a map's default one without issuing render.RedownloadAllLightmaps(true,true), explosions will lighten or darken (depending on the current LightStyle) all brushes that were lit by the explosion.

Here's what, for example, arena_well looks like before doing anything
![normal](https://user-images.githubusercontent.com/24372691/98226731-b6d51b00-1f56-11eb-8b6e-9851e57cf376.png)

After changing LightStyle to "z" and firing an SMG nade, this area brightens up considerably
![explosion](https://user-images.githubusercontent.com/24372691/98226922-f7349900-1f56-11eb-8683-6ed8f2837b55.png)

Brushes not affected by the explosion's light will have a noticeable cut-off.
![cutoff](https://user-images.githubusercontent.com/24372691/98227145-395dda80-1f57-11eb-958f-4ee97a3dce86.png)

This is not a branch specific issue. It happens on all of them.
This is also not an addon issue, as it happens even with all addons disabled (Although it is worth mentioning that weapons based on TFA or CW 2.0 do produce the same effect).

### Steps to reproduce
1. Start up any map.
2. In the console, type engine.LightStyle(0,"whichever value from a-z you prefer") and hit Enter
3. Produce any type of explosion that hits a solid brush or group of brushes.

**Comment by robotboy655** [comment]
Uh, its not a bug? If you don't force lightmaps to rebuild, they will rebuild as needed, which would cause issues like this.

**Comment by spaztron64** [comment]
Oh of course, I didn't think of that!
Using "r_dynamiclights 0" seems to be a reasonable mitigation.
