### ISSUE TITLE
ShouldCollide/CustomCollisionCheck on a thin entity breaks collisions for all entities

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4724]
### Details
[Video](https://i.venner.io/ch1mktUdjh.mp4)

In this video I am using ShouldCollide to disable collisions with players who the keycard on the ground has been hidden from:

```lua
hook.Add("ShouldCollide", "bKeypads.Keycards.ShouldCollide", function(ent1, ent2)
	local ply, keycard

	if ent1:GetClass() == "bkeycard_pickup" then
		keycard = ent1
		if keycard:GetID() == 0 then return end
		if ent2:IsPlayer() then
			ply = ent2
		else
			return
		end
	elseif ent2:GetClass() == "bkeycard_pickup" then
		keycard = ent2
		if keycard:GetID() == 0 then return end
		if ent1:IsPlayer() then
			ply = ent1
		else
			return
		end
	else
		return
	end
	
	if bKeypads.Keycards.Inventory:IsHoldingKeycard(ply, keycard:GetID()) then
		return false
	end
end)
```

The problem stops occurring when switching to a thicker model, such as `models/hunter/blocks/cube025x05x025.mdl`. I confirmed this a bit further by calling `ENTITY:PhysicsInitBox()` using the model bounds of `models/hunter/blocks/cube025x05x025.mdl`, which stopped the problem occurring as well.

Additionally, the problem stops occurring when changing all the no value `return` into `return true`.

Fiddling with the physics object's mass has no effect.

Notably, it doesn't break physics completely - I have noticed that the keycards float in water. Also, after the problem starts to occur, any entity that is spawned in is also afflicted and falls through the world.

A further detail that could be of note is that the keycard entity's CustomCollisionCheck is being set by a NetworkVarNotify.

No entities collide with each other after the problem occurs.

### Steps to reproduce

Here's the model:

[shouldcollide_fuckery_model.zip](https://github.com/Facepunch/garrysmod-issues/files/5504973/shouldcollide_fuckery_model.zip)

**Comment by WilliamVenner** [comment]
Actually I don't even know what causes this anymore. Even a `Vector(3, 3, 3), Vector(-3, -3, -3)` bounding box suffers this.

**Comment by LeQuackers** [comment]
If entities are falling through the world and it affects entities that you spawned in it's probably related to https://github.com/Facepunch/garrysmod-issues/issues/642.

Are you sure that other hooks aren't messing with the return values? You mentioned that changing ```return``` to ```return true``` fixes the issue, which leads me to suspect it could be other hooks interfering (returning nil allows hooks to continue processing). Have you tried overriding ```GM:ShouldCollide``` to see if the issue still occurs?

**Comment by WilliamVenner** [comment]
It does sound related to #642 actually, considering that the collision rules change when the keycard is actually physically touched - "if I were to change my team well standing in another player there is a high chance source engine's physics will totally fail and objects will start floating around."

But yeah, I've tried it with my ShouldCollide being the only ShouldCollide hook (other than `GM:ShouldCollide`) to no avail :(

**Comment by LeQuackers** [comment]
Can you try overriding ```GM:ShouldCollide``` just to test it?

**Comment by WilliamVenner** [comment]
I don't see how that would change anything, the `GM:ShouldCollide` on my server is the same one as in the base gamemode, it just returns true.

**Comment by DBotThePony** [comment]
> Additionally, the problem stops occurring when changing all the no value return into return true.

Maybe you misuse [this](https://wiki.facepunch.com/gmod/Entity:CollisionRulesChanged)? Because DPP/2 utilize `ShouldCollide` for anti prop push for entire contraptions, and nobody ever experienced a physics engine crash.

**Comment by WilliamVenner** [comment]
I've tried every combination of calling CustomCollisionRulesChanged under the sun, including caching the ShouldCollide return value and calling CustomCollisionRulesChanged every time that cached value changes. Made no difference :(

gs said this, too:

![image](https://user-images.githubusercontent.com/14863743/100630439-7634ab80-3322-11eb-94e7-25b9cbd974d4.png)

**Comment by WilliamVenner** [comment]
Yup this has nothing to do with the size of the entity. ShouldCollide just does this in general now.

**Comment by thegrb93** [comment]
As it always has. Don't use it.

**Comment by WilliamVenner** [comment]
I've never known it to until recently.

There should just be an object-oriented API for this instead of a hook.

e.g.
```lua
ent1:EnableCollisionsWith(ent2, true/false)
```
