### ISSUE TITLE
Half Life 2 maps are extremely broken

### ISSUE THREAD

**Issue by DocVonTacos** [Facepunch/garrysmod-issues#4725]
### Details
Eli's maps in HL2 are extremely broken when loaded in, a lot of the HL2 maps are broken in general, I've just came back to the game after a few years and these are what still is broken from what all I've tested
1. Eli's lab has all its triggers visible, which, wouldn't be a problem, but they also have collision 
https://cdn.discordapp.com/attachments/229478441072721921/775085440780075038/unknown.png
https://cdn.discordapp.com/attachments/229478441072721921/775088700832743474/unknown.png
First image is with addons, second is without any. 
2. The streets in the 2nd map are all white.
3. In map trainstation_01 the citizens do not move at the checkpoint meaning progress is impossible without noclip
this is all I've tested
### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
If it is a modding API issue, please include minimal code to reproduce the issue on demand.
Just load up the HL2 maps

**Comment by GitSparTV** [comment]
Have you running them in HL2 not GMod?

**Comment by robotboy655** [comment]
All of these issues are on your end only. I have tested all the maps in singleplayer and they all work perfectly. I am assuming by "streets in the 2nd map" you mean you mean `d1_trainstation_02`

Are you by any chance pirating either game? If not, verify cache integrity of both games. Make sure you did **not** extract any files into Garry's Mod yourself.
Post console logs after opening the maps.

![image](https://user-images.githubusercontent.com/3299036/98559453-4ceaa780-22af-11eb-913f-08e9bbb606f5.png)
![image](https://user-images.githubusercontent.com/3299036/98559642-891e0800-22af-11eb-9604-976d25417863.png)
![image](https://user-images.githubusercontent.com/3299036/98560237-385adf00-22b0-11eb-8c8c-efef1d58dc1b.png)

**Comment by DocVonTacos** [comment]
The d1_trainstation_02 was just a one time thing, it seems, but the eli's lab one still happens. The entrance to the lab has visible triggers I own the games all on steam. The bit with Eli's lab has been going on for a few years now.

**Comment by DocVonTacos** [comment]
> Have you tried running them in HL2 not GMod?

Yes, they work in half life 2, but gmod was at first a mod for half life 2 and seems to be a bug with gmod, Eli's lab is just completely unplayable because of this

**Comment by robotboy655** [comment]
>If not, verify cache integrity of both games. Make sure you did not extract any files into Garry's Mod yourself.

>**Post console logs after loading the maps.**

**Comment by DocVonTacos** [comment]
> > If not, verify cache integrity of both games. Make sure you did not extract any files into Garry's Mod yourself.
> 
> > **Post console logs after loading the maps.**

I don't ever really mess with the files directly, verified them both and nothing was amiss with them.

**Comment by DocVonTacos** [comment]
![image](https://user-images.githubusercontent.com/48135088/98622219-fd1fd680-22d6-11eb-8aaa-6a2f3d6f00af.png)
Disabled all the addons, here you go

**Comment by DocVonTacos** [comment]
also, the bit about the train station is the line leading to where Barney is, those citizens don't move for some reason

**Comment by MARK2580** [comment]
I agree with @Rubat, you broke something yourself. Try disabling all hl2 mods and addons in gmod. Also completely reset all gmod settings using FactoryReset-GMod.bat at the root of the game.

![gmod Screenshot 2020 11 12 - 17 33 30 58](https://user-images.githubusercontent.com/11617079/98953794-2d9d8580-250e-11eb-8596-027a8057db95.jpg)
![gmod Screenshot 2020 11 12 - 17 33 42 50](https://user-images.githubusercontent.com/11617079/98953798-2eceb280-250e-11eb-9261-ff3e211f6601.jpg)
![gmod Screenshot 2020 11 12 - 17 37 05 81](https://user-images.githubusercontent.com/11617079/98953800-2f674900-250e-11eb-92fd-c6809f01a967.jpg)

**Comment by robotboy655** [comment]
> also, the bit about the train station is the line leading to where Barney is, those citizens don't move for some reason

If you use noclip, you may break the maps logic.
They definitely do move through eventually like expected in singleplayer at least.
![image](https://user-images.githubusercontent.com/3299036/98961013-c4b60d80-250d-11eb-8461-c814597e020a.png)

Type `whereis maps/d1_eli_01.bsp` into your console and post the results here. Maybe you have some shitty recompiled version of the map installed.

**Comment by MARK2580** [comment]
> If you use noclip, you may break the maps logic.
By the way, yes. Today when I checked, I flew there using noclip and they really stood still. But when I wanted to capture it on video, restart map and went there "officially", everything worked correctly.

**Comment by DocVonTacos** [comment]
> > also, the bit about the train station is the line leading to where Barney is, those citizens don't move for some reason
> 
> If you use noclip, you may break the maps logic.
> They definitely do move through eventually like expected in singleplayer at least.
> ![image](https://user-images.githubusercontent.com/3299036/98961013-c4b60d80-250d-11eb-8461-c814597e020a.png)
> 
> Type `whereis maps/d1_eli_01.bsp` into your console and post the results here. Maybe you have some shitty recompiled version of the map installed.

![image](https://user-images.githubusercontent.com/48135088/98978849-865a2780-24e8-11eb-9b0e-0a734556c7e8.png)

**Comment by DocVonTacos** [comment]
and when I first reported the issue was after a fresh install of both games, including deleting the left behind bits of both games when uninstalling from steam

**Comment by DocVonTacos** [comment]
![image](https://user-images.githubusercontent.com/48135088/98981418-e900f280-24eb-11eb-8cbe-a7a492574825.png)
I ran the bat file, it didnt' fix the issue and now im missing stuff like the construction prop spawn list. All that stuff is gone

**Comment by robotboy655** [comment]
Well I don't know why your `d1_eli_01.bsp` does that then. Its definitely NOT the triggers, I know it says TRIGGER on the texture, but it's not an actual trigger, those can be seen with `showtriggers_toggle` and there isn't one there for me, looks more like an areaportal that's broken somehow. I guess you could try attaching your `debug_dump.txt` (Generated by console command of the same name) but factory reset `.bat` should've already reset all that.

As for your spawnlists, deleting all of them and saving changes will restore the default ones.

**Comment by MARK2580** [comment]
> I ran the bat file, it didnt' fix the issue and now im missing stuff like the construction prop spawn list. All that stuff is gone

This bat completely erases all game and user settings.

**Comment by DocVonTacos** [comment]
> Well I don't know why your `d1_eli_01.bsp` does that then. Its definitely NOT the triggers, I know it says TRIGGER on the texture, but it's not an actual trigger, those can be seen with `showtriggers_toggle` and there isn't one there for me, looks more like an areaportal that's broken somehow. I guess you could try attaching your `debug_dump.txt` (Generated by console command of the same name) but factory reset `.bat` should've already reset all that.
> 
> As for your spawnlists, deleting all of them and saving changes will restore the default ones.
> 
> have you tried loading that map in HL2 and seeing if the issue persists? Also you should really try running `-noaddons -noworkshop`, not just disabling all addons.

Except it *is* the trigger. I can't walk past it at all, but if i disable its collisions and walk though the cutscene that happens in the beginning doesn't happen. If I remove it and walk in the cutscene never occurs, but if i noclip into it the cutscene where they scan you does happen. Past that it breaks again. There's also the triggers for the laser which are also solid. Regular HL2 works perfectly fine. This is launched with the no addons and no workshop commands. Even after the scanning sequence, the little cutscene that happens after is broken where she walks you down to eli. The later maps also straight up don't load. Ravenholm's entire chapter is completely unplayable still along with nova prospekt part of the game.

![image](https://user-images.githubusercontent.com/48135088/215295196-ab28dc64-105e-4ab4-8363-3f59c995e229.png)

[debug_dump.txt](https://github.com/Facepunch/garrysmod-issues/files/10528481/debug_dump.txt)

**Comment by robotboy655** [comment]
It has to be an issue on your end, because you are the only person who has the issue. Either your game has some addon that breaks this, you have installed some file into the game that breaks the game, or there's something in one of your mounted games (The controller icon in the main menu, and the cfg/mount.cfg file both) that causes the issue. I don't know.
