### ISSUE TITLE
buildcubemaps crash to desktop ( Out of memory in render data! )

### ISSUE THREAD

**Issue by m4rkey** [Facepunch/garrysmod-issues#4726]
### Details
Before the October update, I have been compiling and modifying the lighting of a map with no problems, to come to find out that I have now settled on all my changes done the entire compile and ready to build cubemaps. Upon building cubemaps, it fails about half way through give or take and after logging the console output I'm provided with the following output.

`bounce: 1/1 sample: 261/359
MaterialSystem: Out of memory in render data!`

I believe this to be something that the map itself is causing, however upon looking up anything relating to the MaterialSystem error, I'm left without any information. I went ahead and emailed two mdmp files from when I tried to compile cubemaps but I will provide them again here with an additional mdmp from my friends PC, Hopefully with the mdmp/error, I can get some more information on why the game is crashing and or running out of memory where as before it did not.

Just to see if this is a result of my changes what used to compile correctly before on a older version of the map no longer does on the current update of garrysmod. I also have tried using the x64 bit branch of the game and to no avail.

To add on, I have tried building on two different PCs as well as having one of my other developers try to build the cubemaps as well and all of them crash at the same point with the same error.

System specs also would indicate I'm no where near out of memory when I'm compiling cubemaps I'm sitting at 15GB/32GB.
Ryzen 7 3700x
32GB of RAM

Dumps: https://drive.google.com/file/d/1yaLfMJy0K9VAowazMT_E20UDvNX_lWMW/view?usp=sharing

Version: October 2020 (2020.10.23)

### Steps to reproduce

- Load up my map (with or without content)
- Insert normal cube map commands (mat_specular 0, building_cubemaps 1, buildcubemaps)
- Let the cubemap process continue until crash

**Comment by DevulTj** [comment]
I had the same issue on my PC with the same cubemap bsp.
32 GB RAM, Ryzen 9 3900X, GTX 1080 Ti.

**Comment by robotboy655** [comment]
Uh maybe link/email the map so I can actually test it?

From the looks of the crash dumps it might be related to a particular model, that may have changed since you last rebuilt cubemaps.

**Comment by m4rkey** [comment]
Thank you for the response,

I went ahead and sent you a follow up email with the bsp, and more information regarding with/without content.

**Comment by robotboy655** [comment]
I have tried rolling back to the August update and it still happens. So its not the October update.

Apparently it's a minor memory "leak". TF2 probably also has it. Either way, should be all fixed on Dev beta (within an hour from this message), so test on that and let me know if it's all good now.
