### ISSUE TITLE
Global.Material() does not create VertexLitGeneric materials correctly when importing PNG

### ISSUE THREAD

**Issue by MagnumMacKivler** [Facepunch/garrysmod-issues#4727]
When using Material() to import a PNG file, using the second parameter to ask for a VertexLitGeneric shader does not work.
```
concommand.Add("testmat", function(ply)
	--Cache material & texture from png
	local png_mat = Material("test_logo.png", "vertexlitgeneric smooth noclamp")
	local tex = png_mat:GetTexture("$basetexture")
	print("PNG Material name: ", png_mat:GetName())
	print("PNG Material shader: ", png_mat:GetShader())
	print("PNG Material $basetexture: ", tex, tex:GetName())
		
end)
```

Console Output:
```
] testmat
PNG Material name: 	1000110test_logo
PNG Material shader: 	UnlitGeneric
PNG Material $basetexture: 	Texture [1000110test_logo]	1000110test_logo
```

As expected of an UnlitGeneric material without `$model 1`, the material is invisible when applied to a model.

A workaround is possible by creating a new material using CreateMaterial(), then waiting (until the new materials have time to cache?) and transplanting the first material's itexture into the second. This seems to only work if one re-retrieves the first and second materials again using Material().

```
concommand.Add("testmat", function(ply)
	local png_mat = Material("test_logo.png", "vertexlitgeneric smooth noclamp")
	local name = png_mat:GetName()
		
	local params = {}
	local new_mat = CreateMaterial("pootis", "VertexLitGeneric", params)
		
	timer.Simple(0.1,function()
		local png_mat = Material("!"..name)
		local new_mat = Material("!pootis")
		local tex = png_mat:GetTexture("$basetexture")
			
		new_mat:SetTexture("$basetexture", tex)
		new_mat:Recompute()
			
		--Apply the material to the entity under the player's crosshair
		local ent = ply:GetEyeTrace().Entity
		if ent and ent:IsValid() then ent:SetMaterial("!pootis") end
	end)
end)
```

It may also be worthwhile to add the ability for the Material() function to accept a table of shader parameters similar to CreateMaterial(). I guess you could set the other parameters manually using imaterial:SetInt() etc, but you won't be able to set the shader (since [imaterial:SetShader()](https://wiki.facepunch.com/gmod/IMaterial:SetShader) is nonfunctional). This way users could get what they want from the material the first time instead of wasting a material index for no good reason.

**Comment by robotboy655** [comment]
Apparently VertexLitGeneric never actually worked as a parameter for Material() despite references to it in the code. Should be fixed.

> It may also be worthwhile to add the ability for the Material() function to accept a table of shader parameters similar to CreateMaterial(). 

No, not really. Material() doesn't create a new material every time it is called, it uses a cached one. (each combination of those parameters in 2nd arg is a separate material though) If you edit that material, or initialize it with custom values, it will affect every other mod that uses the same material. This is exactly where CreateMaterial comes in.

I guess a better solution here would be the ability to create textures from .pngs without also creating a material.
