### ISSUE TITLE
PNG Materials do not sort depth correctly when applied to models

### ISSUE THREAD

**Issue by MagnumMacKivler** [Facepunch/garrysmod-issues#4728]
I tried applying a PNG texture to a model, and discovered that materials created in this manner suffer from a nasty depth sorting bug.
```
concommand.Add("testmat", function(ply)
	local png_mat = Material("test_logo.png", "vertexlitgeneric smooth noclamp")
	local name = png_mat:GetName()
		
	local params = {}
	local new_mat = CreateMaterial("pootis", "VertexLitGeneric", params)
		
	timer.Simple(0.1,function()
		local png_mat = Material("!"..name)
		local new_mat = Material("!pootis")
		local tex = png_mat:GetTexture("$basetexture")
			
		new_mat:SetTexture("$basetexture", tex)
		new_mat:Recompute()
			
		--Apply the material to the entity under the player's crosshair
		local ent = ply:GetEyeTrace().Entity
		if ent and ent:IsValid() then ent:SetMaterial("!pootis") end
	end)
end)
```

Result:
![image](https://i.imgur.com/x4cZptZ.png)

Works fine when applied to a simple, convex model like the 1x1 PHX cube. But when applied to a model with interior geometry like the HL2 Lamarr crate, it causes depth sorting issues that remind me of $translucent sorting issues, but much more aggressive.

**Comment by robotboy655** [comment]
You are setting $vertexalpha onto your material, which is causing the issue. I know it doesn't appear in the code, it's probably a result of your previous messing around, ultimately it comes from `Material()`.
