### ISSUE TITLE
Weird bass errors

### ISSUE THREAD

**Issue by LennDoMations** [Facepunch/garrysmod-issues#4731]
got a lot of error bass_error_fileform code 41 with audio files of an addon.

and why tf does extracting the addon an putting it into the addons folder fix this issue?

**Comment by LennDoMations** [comment]
btw its on x64 branch

**Comment by robotboy655** [comment]
Link addon? Try a different branch?

**Comment by LennDoMations** [comment]
all branches addon is: https://steamcommunity.com/sharedfiles/filedetails/?id=1095111608 
 and operating system is win10 x64 2004

**Comment by robotboy655** [comment]
```
Unsupported 32-bit wave file subway_trains\common\pneumatic\parking_brake_stop.wav
Failed to load sound "subway_trains\common\pneumatic\parking_brake_stop.wav", file probably missing from disk/repository

*** Invalid sample rate (48000) for sound 'subway_announcers\asnp\pyaseckaya\loopline\to_morskaya.mp3'.
*** Invalid sample rate (48000) for sound 'subway_announcers\asnp\pyaseckaya\loopline\next_park.mp3'.
*** Invalid sample rate (48000) for sound 'subway_announcers\asnp\pyaseckaya\loopline\arr_morskaya.mp3'.
```

These errors are all pretty self explanatory. And extracting these sounds will most definitely not magically make them work.

That being said, you must have mp3 codec installed on your PC for the game to be able to play mp3 files.

The correct format for the game is 16 bit PCM for `.wav`, 44100Hz for all sounds

**Comment by LennDoMations** [comment]
these were not the only errors. there are some errors while driving. these seem to get magically fixed when extracting the addon and importing it into addons folder.

**Comment by LennDoMations** [comment]
https://app.mediafire.com/uxka4c0i2tbd9
these are the sounds and there are more

**Comment by LennDoMations** [comment]
these are the only ones that dont cause errors on spawn only

**Comment by robotboy655** [comment]
All of them work perfect fine for me. Verify your game cache to fix any potentially broken addon downloads.

**Comment by LennDoMations** [comment]
ima try that

**Comment by LennDoMations** [comment]
nah just my 2 edited bass.dll files....

**Comment by LennDoMations** [comment]
Sound:subway_trains/common/other/radio/vpr_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,

**Comment by LennDoMations** [comment]
as i know im not the only one with these errors

I will ask few players about it

**Comment by robotboy655** [comment]
Those messages are not coming from Garry's Mod. I have searched the entire source code and there's 0 mentions of `ErrName`.

**Comment by LennDoMations** [comment]
maybe from server?

**Comment by thegrb93** [comment]
I remember someone before saying it had to do with valve's custom loop points in the .wav files, but not entirely sure.

**Comment by LennDoMations** [comment]
but the files have errors and i hear the distorted sounds

**Comment by LennDoMations** [comment]
and @thegrb93 i think that is true

**Comment by LennDoMations** [comment]
1. does the game handle audio files different if they are from a filesystem addon from addons folder?

**Comment by LennDoMations** [comment]
and i think the game decodes the wav files

**Comment by LennDoMations** [comment]
i have extracted the addons and disabled them and now its working fine again 😄
