### ISSUE TITLE
x64 branch clientside SENT Initialize not called?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4732]
Starting today, getting lua errors on clientside SENT due to it not getting Initialize. Will investigate further soon.

**Comment by thegrb93** [comment]
By clientside, I mean ents.CreateClientside

**Comment by robotboy655** [comment]
Are you calling Spawn on the entity?

**Comment by thegrb93** [comment]
Guess that's the problem. Worked before funnily, but I guess that's been fixed since.

**Comment by robotboy655** [comment]
Yeah it was changed to mimic networked entities.

https://github.com/Facepunch/garrysmod-issues/issues/4720
