### ISSUE TITLE
Weird wireframe look trough some glass materials

### ISSUE THREAD

**Issue by LennDoMations** [Facepunch/garrysmod-issues#4733]
![image](https://user-images.githubusercontent.com/70099729/99084640-80874380-25c7-11eb-942b-e497217f3c0b.png)

The image shows this wire frame look. 

never this. 

this has occured a first a few months ago.

i this is the same on all branches

**Comment by robotboy655** [comment]
Map? Location? Disable addons?

**Comment by LennDoMations** [comment]
every map addons doesnt matter. have tested all enabled and disabled. and location off map doesnt matter

**Comment by robotboy655** [comment]
Well, that is the opposite of being helpful. I cannot help you if you do not cooperate. Since you are the only one with this issue, I am assuming it's a problem on your end. Either an addon, GPU drivers or your configuration. Make sure your `mat_wireframe` convar is set to 0.

**Comment by LennDoMations** [comment]
yeah i have a guess its gpu drivers. ima revert to older version and try again

**Comment by LennDoMations** [comment]
yes it was.... amd amd amd.....
