### ISSUE TITLE
NEXTBOT.OnSightEntity / NEXTBOT.OnSightEntityLost doesn't trigger in some scenarios

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#4734]
### Details
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 17:22:36 Nov  2 2020 (7881) (4000)
GMod version 2020.11.09, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
_Example Entity Code_
```lua
ENT.Base		= "base_nextbot"
ENT.Model		= Model("models/humans/group01/male_01.mdl")

if SERVER then
	AddCSLuaFile()

	function ENT:Initialize()
		self:SetModel(self.Model)
		self:SetFOV(180)
		self:SetMaxVisionRange(1000)
	end

	function ENT:OnEntitySight(ent)
		print("OnEntitySight", ent)
	end

	function ENT:OnEntitySightLost(ent)
		print("OnEntitySightLost", ent)
	end

	function ENT:OnOtherKilled(ent)
		print("OnOtherKilled", ent)
	end

	function ENT:RunBehaviour()
		while true do
			self:StartActivity(ACT_IDLE)
			coroutine.yield()
		end
	end
end
```
1. Place the Entity Example Code in `GarrysMod/garrysmod/gamemodes/sandbox/entities/entities` as `sight_bug.lua`
2. Start GMod and start a game of Sandbox in Singleplayer
3. Run `ent_create sight_bug` in console to create the entity

### Actual behavior
- If you walk into the NextBot's field of vision after it has spawned for the first time, `OnEntitySight` won't trigger, but if you walk out of its vision afterward, `OnEntitySightLost` will trigger
- If you die while you're "sighted" by the NextBot, `OnEntitySightLost` won't trigger upon death and `OnEntitySight` won't trigger upon walking back into their field of vision. You have to walk back into, and then back out of, their field of vision for Sight hooks to trigger properly again

### Expected behavior
- Walking into a Nextbot's field of view from not being inside of it, should always trigger `OnEntitySight`
- Dying or otherwise leaving a Nextbot's field of view, should always trigger `OnEntitySightLost`

`nb_debug VISION` may be a helpful command for debugging

**Comment by robotboy655** [comment]
This might be why it was commented out in the first place.

It appears to be a race condition internally for `OnSight`. Don't have a fix yet. For `OnLoseSight` that is an easy fix though.

**Comment by robotboy655** [comment]
Should be all fixed on Dev.

**Comment by WinterPhoenix** [comment]
This unfortunately appears unfixed on Multiplayer Servers once more than one player is on. It might be only working with `Entity(1)`?

**Comment by robotboy655** [comment]
What specifically?

**Comment by TwistedTail** [comment]
Been trying this on multiplayer using the example code. Bots seem to be unable to "see" players after they die. If I run the `kill` command, `NEXTBOT:OnEntitySight` won't be called for my player afterwards no matter what. This happens no matter if I'm being sighted by the bot or not when I die. `NEXTBOT:OnEntityLostSight` is called on bots that were able to see me when I die, so that part works fine at least.

I wasn't able to replicate the other issue about bots not calling `NEXTBOT:OnEntitySight` for players that were initially outside its view range.

Using the latest version of the x86-64 branch on Windows.
