### ISSUE TITLE
CreateMaterial cleanup does not work properly

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4736]
This commit
![browser_rlkczXIyZG](https://user-images.githubusercontent.com/6339511/99181728-fd025980-2762-11eb-9a25-4e56aba26261.png)
Introduced this
![Code_w2de0alezU](https://user-images.githubusercontent.com/6339511/99181735-08558500-2763-11eb-8cc2-2e6e2614d939.png)
![gmod_K6jGAP32Q1](https://user-images.githubusercontent.com/6339511/99181736-0ab7df00-2763-11eb-897c-964c0667e16e.png)
![gmod_ZZj0IIpzK6](https://user-images.githubusercontent.com/6339511/99181738-0c81a280-2763-11eb-947e-8ef8c58c0507.png)
![gmod_P76kOgFbn2](https://user-images.githubusercontent.com/6339511/99181740-0ee3fc80-2763-11eb-9603-685309165fec.png)
![gmod_a2ylZr4hSa](https://user-images.githubusercontent.com/6339511/99181948-47380a80-2764-11eb-8e3f-17133717598d.png)
It appears that materials created using `CreateMaterial` bound to models using `SetSubmaterial` being "deallocated" improperly on map shutdown (disconnect from host/map change) (correct me if it happen constantly without being bound to anything), producing weird situation where `Material('!name')` return and as well as `SetSubmaterial` set *old* material, not the one created by `CreatedMaterial` in current game session.

**Functions which take IMaterial userdata argument directly do not suffer from this issue if you managed to retrieve proper material object from CreateMaterial (e.g. passing object returned from CreateMaterial to render.MaterialOverrideByIndex), so this is very likely material pool issue**

**Comment by robotboy655** [comment]
Cannot reproduce with the following code from a previous issue:
```
concommand.Add("testmat", function(ply)
	local png_mat = Material("test.png", "vertexlitgeneric smooth noclamp")
	local name = png_mat:GetName()
		
	local params = {}
	local new_mat = CreateMaterial("pootis", "VertexLitGeneric", params)
		
	timer.Simple(0.1,function()
		local png_mat = Material("!"..name)
		local new_mat = Material("!pootis")
		local tex = png_mat:GetTexture("$basetexture")
			
		new_mat:SetTexture("$basetexture", tex)
		new_mat:Recompute()
			
		--Apply the material to the entity under the player's crosshair
		local ent = ply:GetEyeTrace().Entity
		if ent and ent:IsValid() then ent:SetMaterial("!pootis") end
	end)
end)
```

Are you sure your code is not simply being affected by this? https://github.com/Facepunch/garrysmod-issues/issues/1531

**Comment by WilliamVenner** [comment]
![image](https://user-images.githubusercontent.com/14863743/99284815-a4988e00-282e-11eb-9803-fc01861a6936.png)

**Comment by robotboy655** [comment]
Can you post actual code that reproduces the issue? Or at the very least link to an addon that is affected?

**Comment by WilliamVenner** [comment]
The addon is unreleased so far and there's way too much code for this anyway. I posted a little snippet in #1531 which you could use with `TOOL:DrawToolScreen()` to reproduce.

I think I might've found the problem anyway?

```
] var_dump Material("!bKeypads_Keycard_1344137971_1"):GetName("$basetexture")
Material("!bKeypads_Keycard_1344137971_1"):GetName("$basetexture") = "bkeypads_keycard_1344137971_1"
```

The $basetexture should be something like `bkeypads_keycardrt_xxx`

The RTs are being rendered to:

![image](https://user-images.githubusercontent.com/14863743/99285429-651e7180-282f-11eb-91e2-34c2f9c8c3ed.png)

**Comment by WilliamVenner** [comment]
Changing that code to this fixed it:

```lua
CreateMaterial("bKeypads_Keycard_" .. textureID, "VertexLitGeneric", { ["$surfaceprop"] = "Plastic" })

local mat = Material("!bKeypads_Keycard_" .. textureID)
mat:SetTexture("$basetexture", RT:GetName())
mat:Recompute()
```

**Comment by robotboy655** [comment]
Sometimes you just run onto Source Engine spaghetti, where it never actually clears unreferenced materials and never checks if a procedural material already exists when creating one.

Anyway, should be all fixed. Also found out that Entity.Set(Sub)Material was leaking material reference counts, so fixed that as well thanks to this.

**Comment by DBotThePony** [comment]
Thanks
