### ISSUE TITLE
Garry's Mod has no audio on Debian

### ISSUE THREAD

**Issue by CommanderNeon10** [Facepunch/garrysmod-issues#4737]
I'm trying to play Garry's Mod on Debian, however there is no sound output from the game or from the computer while the game is running. I've already done a lot of fix attempts, such as setting launch options so it tries to use a different audio driver and restarting Steam and my entire computer, but have not had any luck at all.
This seems to affect ONLY Garry's Mod as other Source games don't have this issue.
I'm completely lost.

**Comment by robotboy655** [comment]
Since so far you are the only person with this problem, its likely an issue on your end. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

**Comment by robotboy655** [comment]
Cannot confirm on Ubuntu 20.10. Works as intended, tested with a USB headset.
