### ISSUE TITLE
Connect Prompt not sending people to servers with a password.

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-issues#4738]
As the title says, it says incorrect password when being send to a server with a prompt, despite the server console showing identical connect messages with the same password for two people with and without the prompt, so I don't think it's being passed through correctly.

**Comment by robotboy655** [comment]
connect command itself does not carry a password. You must set the password manually beforehand with the `password` console command.

**Comment by Jova1106** [comment]
So, specifically run password before the connect command now? Because, you used to be able to run them in the same command and separate them with a semicolon, and set the password after. That is what's not working anymore.

**Comment by Jova1106** [comment]
It doesn't work.

**Comment by robotboy655** [comment]
You need to do it in separate Lua calls, due to how console command blocking works.

**Comment by Jova1106** [comment]
I am running it separately. I run the password command first, then the connect command on the line below.

**Comment by thegrb93** [comment]
Is password not a blocked convar? You could just use this hook instead of whatever ur trying to do. https://wiki.facepunch.com/gmod/GM:CheckPassword

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/99408847-60be8b00-28f9-11eb-8388-c1e76c6ce44c.png)

You clearly did it wrong then.
