### ISSUE TITLE
Server crash in SetModelScale

### ISSUE THREAD

**Issue by NoSharp** [Facepunch/garrysmod-issues#4739]
### Details
Using https://wiki.facepunch.com/gmod/Entity:SetModelScale and providing 0 as the model scale will cause a process termination, in what I can only guess is a division by 0 issue.

### Steps to reproduce
```lua
player.GetAll()[1]:SetModelScale(0)
```

**Comment by Kefta** [comment]
Test on the dev branch.

**Comment by robotboy655** [comment]
It's already fixed for the next update. Thank you for using the search function.
