### ISSUE TITLE
Errors that occur before File:Close() cause file.Open to return nil sometimes

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4743]
### Details
If an error occurs before the script gets a chance to call `File:Close()`, subsequent calls for file.Open with this file will return `nil`.

My assumption was that it should automatically close the file when it's garbage collected, but I seem to be experiencing this problem in some cases indefinitely, even though the File object in question is just a local variable inside a function that's only called once. Whatever the case, I will be using pcall to solve this for now.

If this is intentional (well, to be honest, this is probably more of a halting problem meme) then a `file.Close` function would be useful for defensive programming purposes.

**Comment by WilliamVenner** [comment]
### Reproduction

Seems to only affect file.Open in read mode

```lua
lua_run_cl file.Write("test.dat", "lol")
lua_run_cl local f = file.Open("test.dat", "rb", "DATA") error("XD") f:Close()
lua_run_cl file.Delete("test.dat")
lua_run_cl print(tostring(file.Open("test.dat", "rb", "DATA")))
```

```
[ERROR] LuaCmd:1: bad argument #1 to 'tostring' (value expected)
  1. tostring - [C]:-1
   2. unknown - LuaCmd:1
```

**Comment by robotboy655** [comment]
Uh, in your example you are deleting the file, how do you expect `file.Open` to give you anything after you delete the file?

The file IS being closed on GC.

![image](https://user-images.githubusercontent.com/3299036/99576397-9a1ef580-29e2-11eb-8837-f6f56dcd6dad.png)

**Comment by WilliamVenner** [comment]
Sorry you're right, I wasn't thinking straight with that example :S

I don't really know how to reproduce this - all I know is that file.Open _was_ returning nil when being opened with `wb` under similar circumstances. I'm not storing the file object in any table or anywhere in Lua so I can't understand why it wasn't being garbage collected.

**Comment by robotboy655** [comment]
There IS a case for what you are experiencing, but it's just due to the fact that garbage collection is not instant.

![image](https://user-images.githubusercontent.com/3299036/99580603-4fa07780-29e8-11eb-9ef6-1d7d2462900c.png)

**Comment by WilliamVenner** [comment]
gotcha thanks :)

**Comment by WilliamVenner** [comment]
Still occurring

This file is always closed in my script, but an error before that causes it to not actually close.

![image](https://user-images.githubusercontent.com/14863743/117398306-fb397780-aef5-11eb-8f18-48582d53c986.png)

**Comment by WilliamVenner** [comment]
Map change closes the files.

**Comment by thegrb93** [comment]
All references to your file object need to be gone before garbage collection will collect it and close the file. Why don't you just fix the lua errors?

**Comment by WilliamVenner** [comment]
There are no references to the file stored anywhere. It's a local variable and isn't put anywhere else other than the function body's scope.

> Why don't you just fix the lua errors?

This would be a lot easier to do if I didn't have to keep renaming the file because it won't close it.

**Comment by thegrb93** [comment]
```lua
local file = file.Open(...

xpcall(--[[function that's erroring]], debug.traceback)

file:Close()
```
