### ISSUE TITLE
Crashing on linux 64bit when joining/making a server 

### ISSUE THREAD

**Issue by brightersun99** [Facepunch/garrysmod-issues#4744]
### Details
After the last update to 64bit + chromium branch, I cannot join any servers.  here's what happens: 
Upon spawning, I will crash as soon as I focus the game. It will not crash if the game remains running in the background out of focus. 
The game will hang, seconds after. 

I have tried multiple servers, another machine, another install, account (different cloud) and also having 0 addons of any kind (workshop or therwise) 

I have sent crash dumps via email.

### Steps to reproduce
In linux, launch garry's mod 64bit + chromium development branch, join or create a server.  Focus the game when it finishes loading, the crash should occur. 

Testing was done on ubuntu64bit and archlinux, on two machines.

**Comment by robotboy655** [comment]
> I have sent crash dumps via email.

I dont see nothing on my email.

**Comment by brightersun99** [comment]
Hi, gmail shows it as sent. I will send it again.

**Comment by brightersun99** [comment]
I have sent it again, I hope it has made its way to you.

**Comment by gmod64bit** [comment]
Crashes for me too as of this morning. On Gentoo running xmonad 

[fc67fb34-4f91-4afa-c03af990-072c6604.txt](https://github.com/Facepunch/garrysmod-issues/files/5567892/fc67fb34-4f91-4afa-c03af990-072c6604.txt)

**Comment by robotboy655** [comment]
You can use "chromium" beta branch in the mean time to avoid the crashing.

**Comment by brightersun99** [comment]
I've confirmed it to be a non user specific issue with other users of 64bit linux, it seems to happen as soon as the mouse takes control.

**Comment by robotboy655** [comment]
This makes absolutely no sense.

**Comment by shestifled** [comment]
x86-64 - crash
i can't find 32bit binaries on x86-64 branch
chromium - no crash
dev - no crash

**Comment by robotboy655** [comment]
Let me know if it is fixed.

**Comment by Comminux** [comment]
> Let me know if it is fixed.

The game still crashes when I click the close button in the motd ULX menu.

Video example: https://youtu.be/38bDI5qNT-E

**Comment by robotboy655** [comment]
You said before `it will not crash if the game remains running in the background out of focus.`, does this mean the behavior changed?

**Comment by brightersun99** [comment]
It seems to crash as soon as the mouse takes control.

**Comment by MilkGames** [comment]
Same issue here. Chromium branch indeed works fine. 64 bit crashes.
[18ffac5a-7a7a-4286-592d5499-30fa99ba.txt](https://github.com/Facepunch/garrysmod-issues/files/5578011/18ffac5a-7a7a-4286-592d5499-30fa99ba.txt)

**Comment by banksymate** [comment]
> You said before `it will not crash if the game remains running in the background out of focus.`, does this mean the behavior changed?

I'm assuming that's if he joins the server and tabs out of the game, the mouse never "takes control" and it doesn't crash - but once tabbed back in the game would crash.

**Comment by brightersun99** [comment]
the crash is unavoidable either way

**Comment by iatrogenic** [comment]
I have the same issue. Chromium branch works but x86-64 crashes. I noticed it 6 days ago as well, when this thread was posted.
[ee85a8d9-4e45-4994-d7472092-8c56a170.txt](https://github.com/Facepunch/garrysmod-issues/files/5598183/ee85a8d9-4e45-4994-d7472092-8c56a170.txt)

**Comment by Blazzy12** [comment]
Hey i was looking for something like this I'm on linux Chromium + 64-bit binaries. This is a issue that you can solve very easily but it's really annoying because you cant play on any servers with "helix". Hopefully they fix it so i can play with my friends but here is the temp fix.
![Screenshot from 2020-11-25 18 28 17](https://user-images.githubusercontent.com/75049152/100291533-07cfa200-2f4c-11eb-8ff8-8ea6dde6d92c.png) Anyways change it to that and it should fix the issue, but again please fix this issue so i can play with my friends.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by MilkGames** [comment]
Confirmed fixed for me. Thanks!
