### ISSUE TITLE
SetBoneMatrix breaks bodygroups on weapon worldmodel

### ISSUE THREAD

**Issue by PYROTEKNIK** [Facepunch/garrysmod-issues#4745]
### Details
Entity:SetBoneMatrix() seems to break bodygroups on a SWEP's worldmodel. When used, it seems to set the bodygroups all to the second option. 
I am specifically experiencing it while trying to move the root bone of a model to follow the player's hand

**Comment by robotboy655** [comment]
Please post link to an addon/model that can be used for testing.

**Comment by PYROTEKNIK** [comment]
the addon i'm working on where i experienced it isn't uploaded anywhere. i'm still working on it

**Comment by Kefta** [comment]
Can you provide reproduction code and models then?

**Comment by PYROTEKNIK** [comment]
```
SWEP.ViewModel = Model("models/pyroteknik/v_spraypaint.mdl")
SWEP.WorldModel = Model("models/pyroteknik/w_spraypaint.mdl")
SWEP.CapModel = Model( "models/pyroteknik/w_spraypaint_cap.mdl" )

function SWEP:DrawWorldModel()
	local ply = self:GetOwner()
	local matrix
	local modelpos = self:GetPos()
	local modelang = self:GetAngles()
	if IsValid(ply) then
		local bn = "ValveBiped.Bip01_R_Hand"
		local bone = ply:LookupBone(bn) or 0
		
		local bp, ba = ply:GetBonePosition(bone)
		if bp then
			modelpos = bp
		end
		if ba then
			modelang = ba
		end
		
		self:SetupBones()
		matrix = self:GetBoneMatrix(0) --comment this out and the model will render inside the character, but bodygroups should work again
			if matrix then
				matrix:SetTranslation(modelpos)
				matrix:SetAngles(modelang) 
				self:SetBoneMatrix(0, matrix)
			end	
	end 
	
	self:DrawModel()
end

function SWEP:Deploy()
self:SetBodygroup(2,math.random(0,1))
end
```

model renders fine as long as SetBoneMatrix doesn't happen. when it does, it seems like bodygroup information is discarded.
setting bodygroup anywhere else seems to give the exact same result

[spraycan.zip](https://github.com/Facepunch/garrysmod-issues/files/5571368/spraycan.zip)

**Comment by PYROTEKNIK** [comment]
Hold on, sorry. I don't think i compiled the model properly. The cap seems to be part of a separate bone, as i didn't skin either part model to anything.
