### ISSUE TITLE
Win10 Defender does not like gmod analytics library

### ISSUE THREAD

**Issue by Garrysman232** [Facepunch/garrysmod-issues#4747]
### Details
Win10 defender detects a threat in gmod dedicated server(x86-64 branch) 
bin\analytics.dll
"Trojan:Win32/Zpevdo.B"
### Steps to reproduce
type "steamcmd.exe +login anonymous +force_install_dir anydir +app_update 4020 -beta x86-64 validate +quit" and enjoy win10 Defender alerts

**Comment by robotboy655** [comment]
What do you want me to do about it? The file hasn't changed since it was first introduced. Wait for the false positive to get fixed.

**Comment by Garrysman232** [comment]
idk, it did not happen before.
Just have checked CRC between two of these, they're equal, sry for false alarm
