### ISSUE TITLE
Hammer Transform (Ctrl+M) moves objects in undesired directions

### ISSUE THREAD

**Issue by MagnumMacKivler** [Facepunch/garrysmod-issues#4748]
When using the Transform/Ctrl+M tool to move objects in Hammer, leaving the default "0" in the box tends to move them in unwanted directions in addition to the specified one (usually Up).

Before moving:
![Imgur](https://i.imgur.com/BmqA2N4.png)

After moving:
![Imgur](https://i.imgur.com/nJYTysl.png)

You can see that the model has been moved upwards by 68 units despite the Z box in the transform menu reading 0.
When I put -1024 into the Y box, it moves the model up by 24 units. When I put -256 into the Y box, it moves the model up by 56 units. The bug also occurs with positive values, and when moving objects in the X direction. I suspect it's just a problem with string processing on Hammer's back end.

As a workaround, you can manually type 0.0 in the Z box and it will work correctly:
![Imgur](https://i.imgur.com/y9Fp4qj.png)

**Comment by robotboy655** [comment]
It appears to be a bug in Microsoft's MFC library, specifically `DDX_Text`'s usage of `_sntscanf_s`.

The exact issue:
https://stackoverflow.com/questions/43679807/microsoft-specific-sntscanf-s-function-acting-strangely

**Comment by robotboy655** [comment]
Should be fixed on dev.
