### ISSUE TITLE
MOUSE_WHEEL_UP/DOWN isn't detected by PlayerButtonUp/Down

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-issues#4749]
As the title says. Workarounds for this exist, but it's still unexpected behavior.

**Comment by kem008** [comment]
```
hook.Add('Move','test_MouseWheel', function( pl, mv ) 
    if input.WasMousePressed( MOUSE_WHEEL_DOWN ) then
        MOUSE_WHEEL_DOWN_ = true
    else
        MOUSE_WHEEL_DOWN_ = false
    end
    if input.WasMousePressed( MOUSE_WHEEL_UP) then
        MOUSE_WHEEL_UP_ = true
    else
        MOUSE_WHEEL_UP_ = false
    end
end)
```
I used this. Move can detect it. Its from my chatbox.

**Comment by robotboy655** [comment]
Honestly suprised `PlayerButtonUp/Down` even works considering  its internals.

@kem008 solution will not catch 100% of cases. Your best bet is to use https://wiki.facepunch.com/gmod/CUserCmd:GetMouseWheel

**Comment by robotboy655** [comment]
PlayerButtonUp/Down doesn't work as an event, it is basically identical to manually checking `input.IsButtonDown` in `CreateMove` and then networking the data. It WILL miss keypresses, and this is exactly why it cannot catch MOUSE_WHEEL_UP, it happens too fast. It also will only track 5 keys at a time.

Either way, made it use WasMousePressed for mouse events, should fix it as best as it is fixable.
