### ISSUE TITLE
Strange crash specifically on ULX map change

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4750]
### Details
My server is crashing when using the `ulx map` command.

Internally, it doesn't do anything special:

https://github.com/TeamUlysses/ulx/blob/a8b31ffb3ec6ae1e7bbcea35019312d1b2ca52e1/lua/ulx/modules/sh/util.lua#L56

And yet, _only_ changing the map via ulx causes this crash. Direct use of changelevel in console works fine. Even running `lua_run game.ConsoleCommand("changelevel mapname\n")` works fine too.

Emailed the .dmp file to Rubat.

**Comment by robotboy655** [comment]
Cannot reproduce it on my own dedicated/listen server, and the dump is not useful unfortunately. It either crashes in vphysics, which we can't do anything about, or in Windows's networking (according to Visual Studio), which we can't do anything about.

**Comment by mcNuggets1** [comment]
I experience the same, but I don't think the fault's ULX.

**Comment by Xamats** [comment]
I have same problem on my TTT server.

**Comment by Kefta** [comment]
Dumps?

**Comment by mcNuggets1** [comment]
Its a linux server, so no dumps from me.

**Comment by thegrb93** [comment]
Turn them on, doofus. `sudo ulimit -c unlimited`

**Comment by mcNuggets1** [comment]
Since when does Linux crescendo proper crash dumps?

**Comment by thegrb93** [comment]
Always?
