### ISSUE TITLE
Ragdoll interact incorrect with triggers

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#4752]
Ragdolls will hit a trigger if its bounding box overlaps it even if none of the parts are actually in it, and additionally trigger_push will always apply the force to physobj 0 regardless of which part touched it.

[VIDEO](https://www.youtube.com/watch?v=_FaMePCfEEk)

**Comment by robotboy655** [comment]
Essentially duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1445

`trigger_push` will have a flag to treat multi-physics object entities properly. You can see progress for newer engine entity features here:
https://github.com/Facepunch/garrysmod-requests/issues/1577

https://developer.valvesoftware.com/wiki/Trigger_push (See spawnflags)

**Comment by Ramalayha** [comment]
Oh neat. Are these available in the dev branch then?

**Comment by Kefta** [comment]
Yes.
