### ISSUE TITLE
Material constructor game crash

### ISSUE THREAD

**Issue by ventz-lgtm** [Facepunch/garrysmod-issues#4757]
### Events
On my server we often use a (questionably coded) image utility file to download images off the internet via URL, save them into a data folder "vderma/images" in ./png format, then create Materials for use in our UI. Once the image is downloaded it is turned into a material using the Material constructor, with the data filepath to the .png file, and the parameters "noclamp smooth".

It has become quite common for client's games to "randomly" crash during play, and produce dumpfiles which include a stack trace pointing to the line which calls the Material constructor. I have made several changes to this file in the past to attempt to stop this, such as moving the call out of a timer context and into a Think hook, and adding a larger delay between the file being read and using the Material constructor but to no avail.

Due to the nature of the on-demand image fetching is has been impossible for me to create a reliable repro which causes this crash, and unfortunately it simply happens randomly, perhaps 3-4 times a day for various clients.

### Dumps
I have emailed two crash dumps and the file which the crash originates in. Both of which originated on the regular 32 bit version.

### Version
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.10.23, branch: unknown, multicore: 1
Windows 32bit

**Comment by robotboy655** [comment]
Can you get a crash dump from the "x86-64" or "dev" beta branches. It should help with identifying the exact problem.

**Comment by dhog10** [comment]
Have told the person which those mdmp files originated from to switch to
the "x86-64" branch and I will get back to you as soon as a new crash from
this cause happens.
