### ISSUE TITLE
Context menu exposes players with GetNoDraw set to true

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4760]
### Details
If you hover over a player, it adds an halo around the player's body, even if SetNoDraw(true) is set to true to them.
This can be used to easily identify invisible admins for example.

### Steps to reproduce
Hover over something, that is NoDraw and see it being outlined.

**Comment by thegrb93** [comment]
Also this would be good. https://github.com/Facepunch/garrysmod/pull/1751

**Comment by thegrb93** [comment]
Something to make prop_effect ring full invisible too pls.

**Comment by mcNuggets1** [comment]
Yeah, but the most important is, that you actually cant expose admins lol

**Comment by robotboy655** [comment]
> Something to make prop_effect ring fully invisible too pls. Properties menu option would be great.

There should be an option for this in C > Menubar on top > Drawing and in the Q > Utilities > Sandbox Settings

**Comment by thegrb93** [comment]
> > Something to make prop_effect ring fully invisible too pls. Properties menu option would be great.
> 
> There should be an option for this in C > Menubar on top > Drawing and in the Q > Utilities > Sandbox Settings

You have to tell other people to do that. I would prefer if everyone could just see my work without the rings and without having to be told to do that.

**Comment by thegrb93** [comment]
I'll add that and a new dupe modifier for it in a bit.

**Comment by mcNuggets1** [comment]
People abuse it a lot to expose invisible objects, which kind of sucks right now.
This is very different to the stuff, thegrb93 is pointing out.

**Comment by thegrb93** [comment]
I'd say yours is higher priority, but all of it can be fixed super easily.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/ae8e6145481ccc4fb39fb432d3e25c575aae7646

**Comment by mcNuggets1** [comment]
Thanks rubat.

**Comment by mcNuggets1** [comment]
But maybe add an IsDormant check too.
