### ISSUE TITLE
Chromium + 64bit Binaries on linux crashes at "Adding Custom Fonts"

### ISSUE THREAD

**Issue by Blazzy12** [Facepunch/garrysmod-issues#4761]
### Details
On the Chromium + 64bit Binaries the game just crashes on "Adding Custom Fonts" this only started to happen today. 

https://cdn.discordapp.com/attachments/759606030895284255/785867661749780480/408dca31-31f8-44e4-7f8011af-62a233ac.dmp. <<<<< Crash DMP

https://www.youtube.com/watch?v=V93dTfTGAbI&feature=youtu.be. <<<<< Crash in action

### Steps to reproduce
Chromium + 64bit Binaries on linux

**Comment by robotboy655** [comment]
Should be fixed soon.
