### ISSUE TITLE
Strange info_ladder_dismount Properties on Player Death

### ISSUE THREAD

**Issue by b0rdie** [Facepunch/garrysmod-issues#4766]
If a player dies in the middle of interacting with/dismounting a ladder (specifically ones that slide you towards the info_ladder_dismount point) then the player will re-spawn on said point for that death. There's not much else to this, and I couldn't find any error logs produced, it's just a strange spawn issue for deaths during ladder interaction.
This was only tested in sandbox, no idea if other game-modes have this issue.

(Video for reference)
[ladderspawn.zip](https://github.com/Facepunch/garrysmod-issues/files/5683792/ladderspawn.zip)

**Comment by robotboy655** [comment]
Should be fixed
