### ISSUE TITLE
32 bit integer overflow in id variable in gmpublish

### ISSUE THREAD

**Issue by Kirschi94** [Facepunch/garrysmod-issues#4767]
The workshop ids I'm getting are all above 2.300.000.000, but when hitting the 32 bit integer limit, the id variable overflows to -2.147.483.648 and goes up from there, therefore I can't upload anything to the workshop. See here for picture: https://i.imgur.com/sMv1bg6.png

**Comment by robotboy655** [comment]
it only affects that message, not any internal workings, but fixed nonetheless.
