### ISSUE TITLE
Hammer Orphaned Objects Found error

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4769]
### Details
Loading old (HL2 Leak) vmfs with visgroups in modern Hammer versions (including Source 2013 and Garry's mod ones) causes "Orphaned Objects Found" messagebox to appear.
![изображение](https://user-images.githubusercontent.com/24942438/102350785-81d8d100-3fb6-11eb-8594-7575887e871b.png)
Such objects become bugged: it is impossible to toggle them with visgroups, checking for probems shows 
"Hidden object group with no visible children" errors for such objects, but fixing them does not restores the original visgroup assignment. 

### Steps to reproduce
Map with an Orphared Objects error: [wasteland_depot_outside.zip](https://github.com/Facepunch/garrysmod-issues/files/5702722/wasteland_depot_outside.zip)

**Comment by robotboy655** [comment]
Looks like an issue with loading files generated by extremely old Hammer versions.

You can fix it on a per-file basis by manually deleting groups that have a visgroup:
![image](https://user-images.githubusercontent.com/3299036/102377877-dd628900-3fcd-11eb-876f-8440486cf3c1.png)

**Comment by stepa2** [comment]
Will it keep objects' visgroup assignment?

**Comment by robotboy655** [comment]
Probably not, but it doesn't matter - I have made it work on Dev beta branch.

This probably wasn't worth the hours I spent on this though.
