### ISSUE TITLE
x64 Build: BecomeRagdollOnClient broken

### ISSUE THREAD

**Issue by ForrestMarkX** [Facepunch/garrysmod-issues#4770]
### Details
On the x64 build of the game all ragdolls created through ENT:BecomeRagdollOnClient will become broken and t-pose, it seems to happen on any model on any npc.

### Steps to reproduce
Spawn a NPC
Call BecomeRagdollOnClient on the NPC on the clientside
Ragdoll will be t-pose and not simulate physics at all

**Comment by robotboy655** [comment]
Not exclusive to x64, will be fixed soon.
