### ISSUE TITLE
Slider's created but they don't work properly.

### ISSUE THREAD

**Issue by Jackboy317** [Facepunch/garrysmod-issues#4771]
### Details
So the Slider Constraint Tool has been bugged out for a long while. As it keeps screwing up the direction it's supposed to go in. 
And I'm not the only one that's having this issue, Many of my friends are having the same bug.

### Steps to reproduce
1: Go into any sandbox game (Either Singleplayer or Multiplayer)
2: Try to create a horizontal slider, as in, make it so one of the objects attached moves horizontally instead of vertically, using any tool that has a slider function.
3: You'll immediately see that the "horizontal" slider doesn't move horizontal at all, it instead goes up and down instead of left to right/right to left.

This has been an issue since either the September or October Update. and it's been a huge problem for me since.

**Comment by robotboy655** [comment]
It should be fixed on x86-64 and dev beta branches and in the next update.
