### ISSUE TITLE
Running IGModAudioChannel:SetTime on large MP3 files causes freezing

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#4772]
### Details
> Protocol version 24
> Exe version 2020.10.14 (garrysmod)
> Exe build: 17:22:36 Nov  2 2020 (7881) (4000)
> GMod version 2020.12.11, branch: x86-64, multicore: 1
> Windows 64bit

As said in the title, any sufficiently large MP3 file using `IGmodAudioChannel` seems to make GMod freeze when `SetTime` is called on it.

### Steps to reproduce
1. Download the attached audio file `10min.mp3` and place it in your GMod `sound/` folder
2. Start Profiling using [FProfiler](https://github.com/FPtje/FProfiler) or use some other tool (could just be `SysTime()`)
3. Run the code below
4. Observe it takes quite a while, ~30ms in my case, for `SetTime` to run, causing visible stuttering/freezing

```lua
sound.PlayFile("sound/10min.mp3", "", function(soundChannel)
	soundChannel:SetTime(120)

	timer.Simple(5, function()
		soundChannel:Stop()
	end)
end)
```

### Attached Files
[10min.zip](https://github.com/Facepunch/garrysmod-issues/files/5720488/10min.zip)

**Comment by robotboy655** [comment]
Added second argument to `SetTime()` (optional, defaults `false`) - set to `true` to skip the DECODETO flag which is expensive but necessary for some streams.

**Comment by WinterPhoenix** [comment]
Confirmed, that fixes it right up. Thanks!
