### ISSUE TITLE
When you change a model with Hammer Model Browser, skin is reseted to 0

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4773]
### Steps to reproduce
1. Create empty VMF
2. Create `prop_static`
3. Set World Model to `models/props_pipes/pipe01_straight01_long.mdl` with skin 1 using Model Browser
4. Set World Model to `models/props_pipes/pipe02_straight01_long.mdl` using Model Browser (without changing skin)

Excepted: model has Skin = 1 (rusty)
Actual: model skin is reset to 0 (white painted)

**Comment by robotboy655** [comment]
I don't really understand how this is unexpected behavior. Yeah, it may be useful for similar models, but the program cannot assume the model will be similar.

**Comment by stepa2** [comment]
Is it possible to make this behavior configurable then?

**Comment by robotboy655** [comment]
I am not interested in doing that.
