### ISSUE TITLE
gmod timeout on arch linux 

### ISSUE THREAD

**Issue by tomekb530** [Facepunch/garrysmod-issues#4774]
### Details
When the server has big load of addons , I can't connect (getting timeout).

### Steps to reproduce
Have latest arch linux
Some old radeon 1gb card
8gb ram
hdd

Connect to random server with shitton of content
Timeout

The thing i've found is if I use strace on gmod process i can somehow normally connect...

**Comment by robotboy655** [comment]
You are loading too slow. Uninstall/disable addons, get a better PC or join a server with less addons.
