### ISSUE TITLE
Question about File endianness

### ISSUE THREAD

**Issue by Cheatoid** [Facepunch/garrysmod-issues#4775]
(No idea where to ask questions since the forums are gone... and I can't sign up for Discord... So guess here it is.)
GMod wiki doesn't say anything about endianness with File methods such as [`WriteULong`](https://wiki.facepunch.com/gmod/File:WriteULong)/etc.
I have run the following code on my little-endian computer:
```lua
local f = file.Open("_.txt", "wb", "DATA")
if not f then return error("failed to open file") end

f:WriteULong(0x12345678)
f:WriteFloat(math.pi)

f:Close()
```
And it has produced the file with 8 bytes, the data is written in little-endian format:
![output](https://user-images.githubusercontent.com/13347909/102903568-d1b10f80-4470-11eb-8faf-efb666d51ad6.png)

So, the question goes, is File API using platform-specific endianness *or* is it always using little-endian?

**Comment by viral32111** [comment]
> No idea where to ask questions since the forums are gone...

https://forum.facepunch.com/c/gmod/9

**Comment by robotboy655** [comment]
https://stackoverflow.com/questions/31938282/is-there-any-bigendian-hardware-out-there

It's unlikely you will ever find a big endian system out there.
