### ISSUE TITLE
Server Redirect Pop-Up Doesn't Redirect

### ISSUE THREAD

**Issue by Clone5184** [Facepunch/garrysmod-issues#4776]
### Details
The pop-up that appears when you're being redirected to another server does not seem to redirect players as it should. After the pop-up appears, I click "yes" to be redirected, only to have the pop-up disappear and nothing to happen. Upon checking the console, help text has appeared as though the "connect" command was typed without anything following it. If I manually type the command that appears on the pop-up, the redirect works just fine. 
I have tested this on the "Chromium + 64-bit binaries" beta branch. I have only tested this on the Gmod Tower: Reunion server, as I am unaware of any other servers that redirect you like this, and can confirm the server's redirects work perfectly fine on the regular, non-beta branch.

### Steps to reproduce
1. Do something that prompts a server redirect pop-up.
2. Agree to the server redirect.
3. The box will close and nothing will happen.

**Comment by robotboy655** [comment]
The server owners are doing something wrong then. I cannot really look into this without knowing the exact code they are running.

**Comment by geemayn** [comment]
can you create an option for servers to disable it entirely? would help easily fix the problem for servers with these issues

**Comment by geemayn** [comment]
can you create an option for servers to disable it entirely? would be a very nice easy fix

**Comment by geemayn** [comment]
can you create an option for servers to disable it entirely? itd be much easier than trying to work around it

**Comment by geemayn** [comment]
can you create an option for servers to disable it entirely? itd be much easier than trying to work around it

**Comment by robotboy655** [comment]
That would defeat its purpose entirely, so no. You are not meant to work around it.

**Comment by geemayn** [comment]
whats the purpose of it? it doesn't work very well as a security measure nor is very necessary to be honest.

**Comment by viral32111** [comment]
The purpose is to give the option for players to accept/deny getting redirected to another server, which sounds perfectly reasonable to me. Maybe they don't want to be sent to another server, it all depends on how/where its used.

**Comment by Clone5184** [comment]
How about instead of making it a server option, make it a client option? Have it enabled by default, but if someone wants to disable it, they have the ability to. Maybe a console command or something if you're worried about people disabling it by accident.

**Comment by robotboy655** [comment]
> How about instead of making it a server option, make it a client option? Have it enabled by default, but if someone wants to disable it, they have the ability to. Maybe a console command or something if you're worried about people disabling it by accident.

That is the plan with a permissions system.

Either way this is off-topic, if your original issue of "Server Redirect Pop-Up Doesn't Redirect" is resolved, I will be closing this.
I am still yet to see any actual information like a server IP that has this problem, console logs perhaps, or code to reproduce and it does work in my tests.

**Comment by geemayn** [comment]
the client permissions would work perfect too
the gmod tower reunion servers have this issue, id test it there if you have the time. if not the permissions would work too
thank you
