### ISSUE TITLE
UTIL_TranslateSoundName its useless if not translate the soundname

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#4777]
I think mounted games like hl2 ep1 or ep2 got many text files inside scripts folder about making sound files for UTIL_TranslateSoundName to be able to get the source file from sound folder. Im sure garrysmod doesnt use these level sounds text files well. So while I this issue remains I will load these text files and translate them in lua and replace all ambient_generic or any entity that use this way of playing sounds.

**Comment by robotboy655** [comment]
Can you please better explain what the actual issue here is?

**Comment by kem008** [comment]
> Can you please better explain what the actual issue here is?

Garrysmod is not looking for sound scripts you need to add them manually...
[https://wiki.facepunch.com/gmod/sound.AddSoundOverrides](https://wiki.facepunch.com/gmod/sound.AddSoundOverrides)

**Comment by robotboy655** [comment]
That's exactly why that function exists. Some of the most popular mountable games are automatically supported, the rest you can load yourself via that function. Doing this automatically would make map loading slower.
