### ISSUE TITLE
SetSubMaterial fills up NetworkStrings with material names

### ISSUE THREAD

**Issue by jadeharley2** [Facepunch/garrysmod-issues#4778]
### Details
ENTITY:SetSubMaterial(id, material) called on server adds new NetworkString with material name as value. 
This can create a lot of NetworkStrings and fill up their limit.
Also it does so without calling util.AddNetworkString function.
garrysmod version: 2020.12.11

### Steps to reproduce
1. set sub material
`lua_run Entity(1):SetSubMaterial(1, "anything")`

2. list networkstrings
`lua_run for k=0, 3000 do
    local v = util.NetworkIDToString( k )
    if v then
        MsgN(" - ",v)
    end
end`

3. at the end of the list this will appear:
` - anything `

**Comment by WilliamVenner** [comment]
This makes it difficult to create dynamic textures on the client and reliably set them on entities.

**Comment by robotboy655** [comment]
It is not a bug.

**Comment by robotboy655** [comment]
Related issues: https://github.com/Facepunch/garrysmod-requests/issues/1741, https://github.com/Facepunch/garrysmod-issues/issues/3362

**Comment by thegrb93** [comment]
Is SetSubMaterial actually consuming network string ids or is it an addon?

**Comment by robotboy655** [comment]
It is Set(Sub)Material, it networks IDs, not strings.
