### ISSUE TITLE
Server name bug 

### ISSUE THREAD

**Issue by ledusa** [Facepunch/garrysmod-issues#4780]
Server's name gets random characters. That's really much it.
![unknown (1)](https://user-images.githubusercontent.com/35780740/103430583-ac41a580-4bd6-11eb-9752-15c1d7febc32.png)

**Comment by robotboy655** [comment]
Not really a bug. The server just does it itself.

**Comment by ledusa** [comment]
What do you mean by server just does it self ? It gets fixed if you refresh server list.

**Comment by robotboy655** [comment]
Exactly what I said. The server can change the host name very frequently. It's not a bug.
