### ISSUE TITLE
sound.PlayFile is affected by server tickrate

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#4783]
### Details
It appears that the callback (and possibly playback) for sound.PlayFile() is called only when the server thinks, rather than calling immediately on the next frame as soon as the stream has actually loaded. This can cause huge delays, especially if the server you are playing on has a low tickrate or very inconsistent tick times.

This should not be the case for a clientside only function that does not need to involve the server at all and signinficantly degrades the experience in many cases (for example playing piano, where the timing of notes is extremely important). 

### Steps to reproduce 
On the clientside run the following:
```LUA
local start = SysTime()
sound.PlayFile("sound/buttons/button10.wav", "noblock", function(ch)
    print(SysTime() - start) -- Always prints a time greater than the frametime of the server
end)
```

**Comment by Synatec** [comment]
This is a very serious issue, please fix

**Comment by SC3-Gazzy-Gaming** [comment]
This issue is causing many serious problems within the community I play. This needs sorting as soon as possible to help make GMOD Great again!

**Comment by robotboy655** [comment]
Decoupled sound.PlayURL/File's threads and the timer library clientside from server's tickrate.

Lets see if this breaks anything.
