### ISSUE TITLE
Garrys Mod Crashing on startup

### ISSUE THREAD

**Issue by Jornv1** [Facepunch/garrysmod-issues#4784]
Hi,

My Garrysmod has been crashing on startup lately after I installed again after some years,

Have tried numerous things like reinstalling Gmod, Steam
Installing TF2 and CSS
Tried al fixes from: https://support.facepunchstudios.com/hc/en-us/articles/213577689-Common-start-up-Problems-and-Solutions?mobile_site=true

Unfortunately nothing helps,

I do have crash reports to share, hope these can be used for some useful information:
https://drive.google.com/file/d/1X-XrzGEMI17F8E75Fu2A_TLokJC9GWwV/view?usp=sharing

Thanks in advance!

**Comment by robotboy655** [comment]
It crashes in your AMD drivers, nothing we can do about it. (amdxn32.dll)
