### ISSUE TITLE
Frequent TTT Server Crashes

### ISSUE THREAD

**Issue by ThatAintFalco444** [Facepunch/garrysmod-issues#4786]
### Details So I'm playing on a TTT server called Velkon Gaming TTT and we keep constantly getting server crashes for unknown reasons. I have told the owner about it and he says he can't find the issue and he's been looking for a long time but I don't think he is. It's definitely not on client side because everyone on the server crashes at the same time and we are forced to move to another one of the servers. At first I thought it had to do with ragdolls traveling at high velocity but that part of the code is already there. I am running the chromium beta and this is my game version:
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.12.11, branch: unknown, multicore: 0
Windows 32bit
Don't exactly have crash dumps because they are server side crashes and I don't have access to the crash logs.

### Steps to reproduce
Play the server and wait until one of the servers crash.

**Comment by mcNuggets1** [comment]
Most likely the ragdolls.
There is a fix to make them COLLISION_GROUP_WEAPON to circumvent it.

**Comment by ThatAintFalco444** [comment]
It isn't the ragdolls though it's already put in the server code it just happens randomly.

**Comment by mcNuggets1** [comment]
What is in the server code?
What do you even mean?
Do you have a crash dump, a console debug or anything?

**Comment by Yogpod** [comment]
why are you reporting this, seems like something for velkon to do instead
