### ISSUE TITLE
"Authenticating with Steam..." problem.

### ISSUE THREAD

**Issue by Comminux** [Facepunch/garrysmod-issues#4787]
### Details

Periodically, players (clients) have a problem with connecting to our servers (or reconnect after changing the map on the server). 

![QY58tub](https://user-images.githubusercontent.com/14937307/103489203-c1f7da80-4e23-11eb-9d51-6dfafe32ec02.png)

When this problem occurs, players will remain on the download screen for an indefinite period of time (from a few seconds to half an hour), waiting for authorization from Steam. Until the host reconnects to the Steam servers, players will not be able to connect.

```
3374 L 12/25/2020 - 22:54:14: Round ended.
3375 L 12/25/2020 - 22:54:14: Result: innocent win.
3376 L 12/25/2020 - 22:54:16: "H0ll0w<65><STEAM_0:0:79305627><>" disconnected (reason "Disconnect by user.")
3377 L 12/25/2020 - 22:54:21: "H0ll0w<69><STEAM_0:0:79305627><>" connected, address "2.133.253.55:25985"
3378 L 12/25/2020 - 22:54:29: "H0ll0w<69><STEAM_0:0:79305627><>" disconnected (reason "Disconnect by user.")
3379 L 12/25/2020 - 22:54:49: Round proper has begun...
3380 L 12/25/2020 - 22:55:32: 00:43.15 - DMG:     MR.BoterO [traitor] damaged Per [innocent] for 7 dmg
3381 L 12/25/2020 - 22:55:32: 00:43.38 - DMG:     MR.BoterO [traitor] damaged Per [innocent] for 7 dmg
3382 L 12/25/2020 - 22:55:33: 00:43.83 - DMG:     MR.BoterO [traitor] damaged Per [innocent] for 7 dmg
3383 L 12/25/2020 - 22:55:37: 00:47.85 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 25 dmg
3384 L 12/25/2020 - 22:55:40: 00:51.11 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 6 dmg
3385 L 12/25/2020 - 22:55:40: 00:51.30 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 4 dmg
3386 L 12/25/2020 - 22:55:40: 00:51.30 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 5 dmg
3387 L 12/25/2020 - 22:55:40: 00:51.30 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 6 dmg
3388 L 12/25/2020 - 22:55:41: 00:51.70 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 5 dmg
3389 L 12/25/2020 - 22:55:41: 00:52.29 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 5 dmg
3390 L 12/25/2020 - 22:55:42: 00:52.48 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 6 dmg
3391 L 12/25/2020 - 22:55:42: 00:52.88 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 5 dmg
3392 L 12/25/2020 - 22:55:44: 00:55.24 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 4 dmg
3393 L 12/25/2020 - 22:55:45: 00:55.83 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 6 dmg
3394 L 12/25/2020 - 22:55:45: 00:56.03 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 6 dmg
3395 L 12/25/2020 - 22:55:47: 00:57.45 - DMG:     MR.BoterO [traitor] damaged Per [innocent] for 19 dmg
3396 L 12/25/2020 - 22:55:47: 00:57.61 - DMG:     Per [innocent] damaged MR.BoterO [traitor] for 4 dmg
3397 L 12/25/2020 - 22:55:47: 00:58.18 - DMG:     MR.BoterO [traitor] damaged Per [innocent] for 140 dmg
3398 L 12/25/2020 - 22:55:47: 00:58.18 - KILL:    MR.BoterO [traitor] killed Per [innocent]
3399 L 12/25/2020 - 22:55:48: Round ended.
3400 L 12/25/2020 - 22:55:48: Result: traitors win.
3401 L 12/25/2020 - 22:56:14: "Per<7><STEAM_0:1:456615790><>" disconnected (reason "Disconnect by user.")
3402 L 12/25/2020 - 22:56:36: Connection to Steam servers lost. (No internet connection)
3403 L 12/25/2020 - 22:56:42: Connection to Steam servers successful.
3404 L 12/25/2020 - 22:56:42:    Public IP is 95.165.140.109.
3405 L 12/25/2020 - 22:56:42: Assigned persistent gameserver Steam ID [G-1:2794875].
3406 L 12/25/2020 - 22:56:42: VAC secure mode is activated.
3407 L 12/25/2020 - 22:57:32: "MR.BoterO<47><STEAM_0:0:501617774><>" disconnected (reason "Disconnect by user.")
3408 L 12/25/2020 - 23:08:10: "Milan<70><STEAM_0:1:73797168><>" connected, address "81.161.69.74:38243"
3409 L 12/25/2020 - 23:08:11: "Milan<70><STEAM_0:1:73797168><>" STEAM USERID validated
3410 L 12/25/2020 - 23:08:14: "Milan<70><STEAM_0:1:73797168><>" disconnected (reason "Disconnect by user.")
3411 L 12/25/2020 - 23:10:09: "H0ll0w<71><STEAM_0:0:79305627><>" connected, address "2.133.253.55:26514"
3412 L 12/25/2020 - 23:10:10: "H0ll0w<71><STEAM_0:0:79305627><>" STEAM USERID validated
3413 L 12/25/2020 - 23:10:27: "H0ll0w<71><STEAM_0:0:79305627><>" entered the game
3414 L 12/25/2020 - 23:11:59: "H0ll0w<71><STEAM_0:0:79305627><>" disconnected (reason "Disconnect by user.")
3415 L 12/25/2020 - 23:18:42: [ULX] (Консоль) сменил карту на текущую.
3416 L 12/25/2020 - 23:18:44: Loading map "ttt_skyscraper"
3417 L 12/25/2020 - 23:18:44: server cvars start
3418 L 12/25/2020 - 23:18:44: "sbox_persist" = ""
3419 L 12/25/2020 - 23:18:44: "sbox_bonemanip_misc" = "0"
3420 L 12/25/2020 - 23:18:44: "sbox_bonemanip_player" = "0"
3421 L 12/25/2020 - 23:18:44: "sbox_bonemanip_npc" = "1"
```

We have two servers on the same IP address. In general, I am worried that this problem occurs due to errors in the server configuration or in the router's routing table.

**Host operating system:** Ubuntu 18.04.1
**Server launch options:** "screen -AmdS run_terrortown ~/NewTerrortown/srcds_run -game garrysmod -strictportbind -ip 192.168.0.104 -port 27017 -tickrate 66 +host_workshop_collection XXXXXXXXXXXXX -authkey XXXXXXXXXXXXXXXXXXXXXXXXX +clientport 27007 -steamport 28017 +tv_port 27022 +gamemode terrortown +map ttt_anymap +sv_setsteamaccount XXXXXXXXXXXXXXXXXXXXXXXX +servercfgfile server.cfg -maxplayers 28 -debug -condebug"
**Netstat:**
![unknown — cleaned](https://user-images.githubusercontent.com/14937307/103489702-47c95500-4e27-11eb-9b59-5b72809c7c47.png)

**Comment by Xamats** [comment]
Maybe its because you have ~30 addons in download list?

**Comment by Comminux** [comment]
> Maybe its because you have ~30 addons in download list?

Maybe, but then how to find a problematic addon?

**Comment by Xamats** [comment]
Delete your addons and downloads folders in garrysmod on your computer and try to join your server.

See if it will affect to you.

**Comment by robotboy655** [comment]
`Authenticating with Steam...` has nothing to do with addons. It's simply waiting for Steam to authenticate the player's SteamID. The game uses Steam services, so if they are currently unavailable, players won't be able to join.

**Comment by Flapchik** [comment]
I believe the problem is not with the Steam servers. The above problem occurs on both servers, but at different intervals. When one server is down, I can connect to the second. The servers have the same IP address but different ports.
Possibly the problem is misconfigured ports, but we don't know how to check.

**Comment by Flapchik** [comment]
Connection to Steam servers lost. (No internet connection)
Connection to Steam servers lost. (No internet connection)
{
}
{
}
src/common/tcpconnection.cpp (1036) : Assertion Failed: Tried to initiate an outbound connection to 155.133.250.146:27020, bound to local address 192.168.0.104:28016.  An ephemeral local port should be used for outbound TCP conections!  How does this work?
src/common/tcpconnection.cpp (1036) : Assertion Failed: Tried to initiate an outbound connection to 155.133.250.146:27020, bound to local address 192.168.0.104:28016.  An ephemeral local port should be used for outbound TCP conections!  How does this work?
Connection to Steam servers successful.
   Public IP is 95.165.140.109.
Assigned persistent gameserver Steam ID [G-1:2629658].
VAC secure mode is activated.

**Comment by Flapchik** [comment]
```Connection to Steam servers lost. (No internet connection)
Connection to Steam servers lost. (No internet connection)
src/common/tcpconnection.cpp (1036) : Assertion Failed: Tried to initiate an outbound connection to 155.133.250.146:27020, bound to local address 192.168.0.104:28016.  An ephemeral local port should be used for outbound TCP conections!  How does this work?
src/common/tcpconnection.cpp (1036) : Assertion Failed: Tried to initiate an outbound connection to 155.133.250.146:27020, bound to local address 192.168.0.104:28016.  An ephemeral local port should be used for outbound TCP conections!  How does this work?
Connection to Steam servers successful.
   Public IP is 95.165.140.109.
Assigned persistent gameserver Steam ID [G-1:2629658].
VAC secure mode is activated.```
