### ISSUE TITLE
config & language problem

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-issues#4788]
If you want to reset your controls the game doesnt reset everything correctly, but the game did that in the past.
https://streamable.com/09x1as

Also there is a console error that belongs to the curret set steam language. I noticed that this bug exist for a while now, came with one of the last updates.
CLocalizedStringTable::AddFile() failed to load file "resource/garrysmod_SteamLanguage.txt".

**Comment by robotboy655** [comment]
Some addon or pirated game content you have put into the game is breaking a certain file that dictates the default config.

You can find out which addon/where the file is with this command: `whereis scripts/kb_def.lst`
By default it will be in the garrysmod.vpk
Validating the game may fix it.
