### ISSUE TITLE
[Workshop Addons] Download Failed! Timed Out!

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4790]
Hey!

I tried running my game Server today with a new Collection and suddenly, i started getting this message:

https://i.imgur.com/TAebfei.jpg
"
Addon need downloading...
Download Failed! Timed out!
"
I can't run my workshop on my server anymore!
I just started having this Issue starting today, i didn't had it before !

Can anyone help me?

**Comment by FlorianLeChat** [comment]
Rubat is currently working on a fix. You can follow the progress on Discord but I think there will be an update soon.

**Comment by robotboy655** [comment]
Should be fixed, update your servers.
