### ISSUE TITLE
Error with numbers in DListViews

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4792]
### Details
Using a number instead of a string results in this error upon sorting.

[ERROR] lua/vgui/dlistview.lua:483: attempt to compare number with string
1. unknown - lua/vgui/dlistview.lua:483
2. sort - [C]:-1
3. SortByColumn - lua/vgui/dlistview.lua:474
4. DoClick - lua/vgui/dlistview_column.lua:93
5. DoClick - lua/vgui/dlistview_column.lua:74
6. unknown - lua/vgui/dlabel.lua:237

### Steps to reproduce
Create a DListView with 2 columns, for one insert a number instead of a string.
Now it errors upon sorting.

**Comment by robotboy655** [comment]
Fixed, even tho you shouldn't be doing this.
