### ISSUE TITLE
Half-Life: Source maps crashes the game.

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4801]
When ever I try to load a map from Half-Life: Source, the game crashes. I don't know if its on my end or not.

I was using the dev branch, I had no addons, I reinstalled Garry's Mod twice, and I made sure I had Half-Life: Source installed.

Steps to reproduce:
Load a map from Half-Life: Source

An email containing the .mdmp file will be sent to you.

**Comment by robotboy655** [comment]
Will be fixed soon.
