### ISSUE TITLE
Hammer 3D and 2D views are broken when editing using external games' gameinfo.txt

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4804]
### Details
I want to configure Hammer to create levels for my Source 2013 modification, but Hammer is not working correctly.

Messages window contents from Garry's mod hammer:
![изображение](https://user-images.githubusercontent.com/24942438/105580909-4d6be800-5da0-11eb-8a7c-3a724f3c44fe.png)
(Once it worked, but I did not noticed the conditions. As I remember, search paths list was similar to Source 2013 one)

Message window contents from Source 2013 hammer:
![изображение](https://user-images.githubusercontent.com/24942438/105581371-99b72800-5da0-11eb-96c0-3712a518c3a2.png)

Bugged Hammer window (resized):
![изображение](https://user-images.githubusercontent.com/24942438/105582709-f9adce80-5da0-11eb-961d-197426b4c53d.png)

### Gameinfo.txt contents

"GameInfo"
{
	game 		"My Episodic Mapbase Mod"
	title 		"HALF-LIFE'"
	title2		""
	type		singleplayer_only

	GameData	"bin/halflife2.fgd"

	icon		"resource/icon1"
	
	// Source 2013 mods run on the EP2 version of the flashlight by default,
	// but you could use this setting to make it run on the HL2/EP1 version of the flashlight,
	// which runs on the player's own aux power.
	// This can also be overridden on a per-map basis using hl2_gamerules.
	use_legacy_flashlight 0

	FileSystem
	{
		SteamAppId				243730		// This sets the app ID in Steam
		
		//
		// Mapbase has a fairly unique file system that needs some explanation.
		// In its rawest form, it is spread out across 2-3 folders:
		// 
		// mapbase_shared - Shared Mapbase content, like editor icons, that are not unique to Half-Life 2.
		// mapbase_hl2 - Original HL2 branch of Mapbase.
		// mapbase_episodic - Episodic branch of Mapbase.
		// 
		// Each folder relies on the previous, meaning mapbase_episodic cannot function without mapbase_hl2 and
		// mapbase_hl2 cannot function without mapbase_shared.
		// 
		// mapbase_episodic > mapbase_hl2 > mapbase_shared
		// 
		// Each Mapbase folder has its own "content" subfolder contianing VPKs.
		// These are mounted similar to the "custom" folder in which everything is mounted without listing out their names.
		// 
		SearchPaths
		{
			// First, mount all user customizations.  This will search for VPKs and subfolders
			// and mount them in alphabetical order.  The easiest way to distribute a mod is to
			// pack up the custom content into a VPK.  To "install" a mod, just drop it in this
			// folder.
			//
			// Note that this folder is scanned only when the game is booted.
			game+mod			|gameinfo_path|custom/*
			//game+mod			|gameinfo_path|../mapbase_episodic/custom/*
			//game+mod			|gameinfo_path|../mapbase_hl2/custom/*
			game+mod			|gameinfo_path|../ep2/custom/*
			game+mod			|gameinfo_path|../episodic/custom/*
			game+mod			|gameinfo_path|../hl2/custom/*

			// Now search loose files.  We'll set the directory containing the gameinfo.txt file
			// as the first "mod" search path (after any user customizations).  This is also the one
			// that's used when writing to the "mod" path.
			game+mod+mod_write+default_write_path		|gameinfo_path|.
			gamebin				|gameinfo_path|bin
			
			
			// Mount any mod content (VPKs, etc.) in this space.
			
			
			// Get our shared Mapbase files.
			// They should be right next to this mod.
			gamebin				|gameinfo_path|../mapbase_episodic/bin
			game+mod			|gameinfo_path|../mapbase_episodic
			game+mod			|gameinfo_path|../mapbase_episodic/content/*
			game+mod			|gameinfo_path|../mapbase_hl2
			game+mod			|gameinfo_path|../mapbase_hl2/content/*
			game+mod			|gameinfo_path|../mapbase_shared/*
			gamebin				|gameinfo_path|../mapbase_shared/shared_misc/bin

			// Now mount all of the base HL2 stuff.
			// See a vanilla gameinfo.txt file for more information on what this stuff does.
			game_lv				|gameinfo_path|../hl2/hl2_lv.vpk
			game+mod			|gameinfo_path|../ep2/ep2_english.vpk
			game+mod			|gameinfo_path|../ep2/ep2_pak.vpk
			game				|gameinfo_path|../episodic/ep1_english.vpk
			game				|gameinfo_path|../episodic/ep1_pak.vpk
			game				|gameinfo_path|../hl2/hl2_english.vpk
			game				|gameinfo_path|../hl2/hl2_pak.vpk
			game				|gameinfo_path|../hl2/hl2_textures.vpk
			game				|gameinfo_path|../hl2/hl2_sound_vo_english.vpk
			game				|gameinfo_path|../hl2/hl2_sound_misc.vpk
			game				|gameinfo_path|../hl2/hl2_misc.vpk
			platform			|gameinfo_path|../platform/platform_misc.vpk

			game+game_write		|gameinfo_path|../ep2
			gamebin				|gameinfo_path|../episodic/bin

			game				|gameinfo_path|../episodic
			game				|gameinfo_path|../hl2
			platform			|gameinfo_path|../platform
		}
	}
}

### Steps to reproduce
1. Install Source SDK Base 2013 Singleplayer
2. Run Garry's mod Hammer
3. Create Hammer configuration pointing to SDK 2013 ep2 game folder
4. Restart Hammer
5. Create empty VMF

Expected: empty 3D view (or with origin), grid on 2D views
Actual: several lines on all the views.

**Comment by MARK2580** [comment]
Why are you even trying to connect the ep2 content from the SDK 2013 to hammer garry's mod ????? If you need the content of this game, you should unpack it in a separate folder, only materials, models and sounds. Other files will 100% break both the editor itself and the game.

**Comment by robotboy655** [comment]
>  If you need the content of this game, you should unpack it in a separate folder, only materials, models and sounds

You should just use mount.cfg

**Comment by MARK2580** [comment]
> > If you need the content of this game, you should unpack it in a separate folder, only materials, models and sounds
> 
> You should just use mount.cfg

By the way, yes, I forgot to mention mount.cfg to connect the folder )))

**Comment by stepa2** [comment]
I want to create modifications for Source 2013 using fixed hammer (without model browser bug)

**Comment by robotboy655** [comment]
Ok, the issue happens with the shaders/ folder is missing on has incorrect shaders. I can try to make it display a warning, but it's not fixable.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/106782901-62276600-6653-11eb-8816-09fa3aa0a209.png)

The middle option must point to gmod's folder, or folder with gmod's shader/ folder.
