### ISSUE TITLE
Sending large data in the PlayerDisconnected hook prevents disconnect chat messages from being shown

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-issues#4805]
Sending net messages larger than **7250** bytes prevents disconnect chat messages from being shown.
This bug doesn't affect the `player_disconnect` game event.

### Steps to reproduce

1. Run this script on the server side:
```lua
local dataLen = 7251
local data = string.rep(".", dataLen)

util.AddNetworkString("7250-bug")

hook.Add("PlayerDisconnected", "7250-bug", function()
	net.Start("7250-bug")
		net.WriteData(data, dataLen)
	net.Broadcast()
end)
```
2. Kick a bot;
3. _No disconnect message in the chat_;
4. Change `dataLen` value to `7250` and run the script again;
5. Repeat step 2;
6. _The disconnect message appears in the chat_.

**Comment by robotboy655** [comment]
I will fix it not appearing for that case, since the player name is sent with the game event anyway.
