### ISSUE TITLE
[Windows] Couldn't create BASS audio stream (unsupported file format)

### ISSUE THREAD

**Issue by jacklollz2** [Facepunch/garrysmod-issues#4806]
I have a deployment of Windows that does not contain media features. Windows Media Player and Windows Multimedia Platform did not come with the image file, the Store provider does not supply Groove music, and more.
I need an alternative to supply the codecs for mp3 file playback on Garry's mod.

**Comment by Kefta** [comment]
Finding proprietary codecs is your job:  we cannot recommend anything due to them all being licensed.

**Comment by jacklollz2** [comment]
The codecs have already been installed, including Opus and Lame. Do I place them in the bin directory of the game? As, installing them doesn't change anything.

**Comment by jacklollz2** [comment]
Also I must mention that it was removed using MSMG toolkit, and the edition is Pro N, not Pro.
