### ISSUE TITLE
env_fog_controller breaks 2d skybox

### ISSUE THREAD

**Issue by Anteik** [Facepunch/garrysmod-issues#4807]
### Details
If you use Z Clip in env_fog_controller, then the 2d skybox texture will start rendering 3d skybox
### Steps to reproduce
- Create any 3d skybox with sky_camera
- Build a box with a 2d skybox texture
- Use env_fog_controller with Z Clip
- Compile the map

**Comment by robotboy655** [comment]
I really don't understand what problem you are reporting here. A picture or a video would be helpful.

What I can say thought is that it seems `env_fog_controller`'s `Far Z` setting will affect how VVIS cuts the map up for visibility.

**Comment by robotboy655** [comment]
Can you attach a sample .vmf? or send one to my email? On my test map the 3d skybox renders even if I put every single sky texture on the map to `tools/toolsskybox2d` and without the fog entity at all.

**Comment by Anteik** [comment]
I sent it to your email

**Comment by robotboy655** [comment]
It's an issue with vrad.exe. Temporary solution for you would be to set the FarZ with entity I/O (SetFarZ from logic_auto or something)

**Comment by robotboy655** [comment]
Should be fixed if you compile the map on Dev beta branch.
