### ISSUE TITLE
 monster_barnacle Half-Life: Source One + missing from spawnmenu

### ISSUE THREAD

**Issue by Doomkills** [Facepunch/garrysmod-issues#4809]
Hello, i have noticed that hl:s barnacle is not spawnable via spawnmenu (but it is through console) but its also not spawnable via toolgun which gives a  Sorry! You can't spawn that NPC! warning

Gmod Version: 2020.12.11

i dont think steps to reproduce are needed here since he is not spawnable in the spawnmenu but only via console.

Screenshot with the toolgun when trying to spawn monster_barnacle: https://imgur.com/w4pyXmU

**Comment by robotboy655** [comment]
It's missing because it broken and does not function properly.

https://github.com/Facepunch/garrysmod-requests/issues/1140
