### ISSUE TITLE
Gmod crashes at Verifying workshop (MacOS)

### ISSUE THREAD

**Issue by EthanLeitch** [Facepunch/garrysmod-issues#4813]
### Details
Tell us exactly what happens here, every single detail that you can think of.
Please include information such as which Beta Branch your game is on, the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.

As soon as I join a server, it gets to "Checking workshop files" then crashes.
Error log: https://pastebin.com/WUH6x8nX

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link.

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
1. Open Gmod on MacOS
2. Join a server
3. Crash

**Comment by robotboy655** [comment]
If you are playing on OSX you should try the `x86-64` beta.

I am not sure sure why it crashes where it does for you, looks like it's trying to convert a `double` to a string but there are none in the code.
