### ISSUE TITLE
[BUG] Npc Damage are Enabled after the new Update !!! 

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4815]
Hey!!
After the new Gmod Update, Players on my Server can Kill all the Npcs in the Map!! (The CarDealer, Donator NPC, And all the others !) 
Image: https://i.imgur.com/82XaxjY.png

How can i make them in GodMod like before??

I tried to add this script server-side but it doesn't works !

function AntiFFMain( vic, dmginfo )

	if vic:IsNPC() then
		dmginfo:SetDamage(0)
	end
	
	
end
hook.Add("EntityTakeDamage", "AntiNpcKillHook", AntiFFMain )

**Comment by robotboy655** [comment]
Read the documentation.

https://wiki.facepunch.com/gmod/ENTITY:OnTakeDamage
