### ISSUE TITLE
Pre-spawned Half-Life: Source weapons crashes the game

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4816]
Whenever a weapon is preloaded on the map it becomes invisible and unusable. When I used the spawn menu to make myself use the weapon, the view model is invisible. When I used the console command 'givecurrentammo' the game crashed.

NPCs who use HL:S weapons don't have this issue. The crowbar from HL:S doesn't crash the game when used, but it doesn't make sounds.

EDIT: I checked to see if this problem persisted on other branches.  x86-64, pre-release, and the main branch. The problem doesn't appear in the chromuim branch.

I was using the dev branch and I had no addons.

Video proof:
https://www.youtube.com/watch?v=n7YHSyhcsAo&ab_channel=TheBillinator3000

I sent the .mdmp file via email

Steps to reproduce:
Go into a HL:S map with weapons in it.
Find a weapon and try to use it from the selection menu.
(steps to cause crash:)
Find the HL:S weapon you picked up from the map.
type 'givecurrentammo' in the developer console.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
