### ISSUE TITLE
Transitioning levels will freeze on 'Initializing world...'

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4817]
I was sitting on this, hoping someone else would have the same problem, but apparently that is not the case.

When I transition from one map to the next using trigger_changelevels or the console command 'changelevel MAPNAMEHERE', the loading screen would get stuck on 'initializing world'.

No addons, factory reseted, even tried -noaddons -noworkshop.

I was using the dev branch. The other branches worked fine.

Steps to reproduce:
Go to any map/ or a map with trigger_changelevels.
Type 'changelevel <MAPNAMEHERE>' into the console/ activate the trigger_changelevel by walking into it.
Wait and see if the problem is in fact on my side or not.

🙃

**Comment by robotboy655** [comment]
Should be fixed.
