### ISSUE TITLE
Health and Armor issues

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4818]
Sorry to bother you again.

When I start the game with Half-Life 2 unmounted, I am unable to take damage from bullets from NPCs from Half-Life 2, unable to use health kits when my health is not full, pick up an infinite amount of batteries, one shot the vast majority of NPCs, and instantly drain health and armor chargers.

Video proof:
https://www.youtube.com/watch?v=ZQ-wWoRtgEs&feature=emb_title&ab_channel=TheBillinator3000

I was using the dev branch and I had no addons.

Other NPCs from other games are working just fine. Mounting Half-Life 2 does fix the issue.

Steps to reproduce
Start Garry's Mod and unmount Half-Life 2.
Go onto any map.
(these steps can be done in any order.)
Shoot an NPC made of flesh with one bullet.
Spawn a charger and use it.
Use a health kit/vial and/or a battery.

**Comment by robotboy655** [comment]
Look at your game files for any extra addon files, I cannot reproduce this. Maybe even do a full reinstall.

`debug_dump` can also help identify any convars with non default values.

**Comment by TheBillinator3000** [comment]
I tried re-installing and the dump.txt didn't really give me helpful information

🙃

[debug_dump.txt](https://github.com/Facepunch/garrysmod-issues/files/5907869/debug_dump.txt)

**Comment by robotboy655** [comment]
Have you tried deleting ALL files when reinstalling? Steam won't delete any files it didn't install.

**Comment by robotboy655** [comment]
The issues you are experiencing are consistent with the `sk_` convars not being set.

**Comment by robotboy655** [comment]
They are meant to be set from cfg/skill.cfg which IS shipped with every base GMod.

**Comment by robotboy655** [comment]
Hmm, perhaps is that same bug from Steam where if you delete it manually it won't get restored.

**Comment by mcNuggets1** [comment]
I had this bug a week ago.
I deleted it manually and IT NEVER recovered it.

**Comment by TheBillinator3000** [comment]
I tried verifying the cache and skill.cfg did not come with installation.

**Comment by robotboy655** [comment]
I bumped valve again about this, hopefully they resolve it soon.

**Comment by robotboy655** [comment]
Steam beta should now have the fix, so the next steam client update will get this fixed.
