### ISSUE TITLE
Workshop Maps not appearing in Dev Beta Mode.

### ISSUE THREAD

**Issue by TyrakatheDragonFan** [Facepunch/garrysmod-issues#4819]
When running Garry's Mod in Dev/Beta Testing Mode, none of the maps I'm currently subscribed to on the workshop appear in the Start New Game menu:

![Snapshot0000](https://user-images.githubusercontent.com/77705209/106539824-55283c80-64c4-11eb-94bf-41b290ae7113.png)

![Snapshot0001](https://user-images.githubusercontent.com/77705209/106539827-56f20000-64c4-11eb-8f1e-0aea05fa322f.png)

When a map is open, all the subscribed non-map addons appear, but any maps do not. I hope to see this fixed soon, as the Dev/Beta mode is currently the only version where the L4D maps work.

**Comment by robotboy655** [comment]
I see at least 3 non default maps in your picture. How are you reproducing this? I can't seem to make it happen, the maps just show up after workshop mounts the content.

Can you make a picture of an addon in your Addons menu that doesn't work for you? Can you make a picture of the console after opening the maps menu? (SHIFT+ESC to open console)

**Comment by TyrakatheDragonFan** [comment]
Those are maps I've manually installed directly into the game folders, not through workshop subscriptions.

**Comment by robotboy655** [comment]
How are you reproducing this?

Can you make a picture of an addon in your Addons menu that doesn't work for you? Can you make a picture of the console after opening the maps menu? (SHIFT+ESC to open console)

**Comment by TyrakatheDragonFan** [comment]
You can see a good amount of the gm_something maps I'm currently subscribed to here: ![image](https://user-images.githubusercontent.com/77705209/106631809-babb0e00-6542-11eb-94bd-39a75b45078a.png)

![Snapshot0000](https://user-images.githubusercontent.com/77705209/106632753-b6432500-6543-11eb-991c-5e841308c2dd.jpg)

**Comment by robotboy655** [comment]
The fact that they appear in addons/ folder is meaningless. They won't disappear if you unsub from the addons.

Does the "mounting workshop content" window appear for you at all? Does it appear and disappear before you press "Start new game"?

**Comment by TyrakatheDragonFan** [comment]
Yes.

**Comment by TyrakatheDragonFan** [comment]
![gm_flatgrass0001](https://user-images.githubusercontent.com/77705209/106635196-2783d780-6546-11eb-85c9-aa3adaa2ffcd.jpg)

Is this what you meant?

**Comment by robotboy655** [comment]
Should be fixed on Dev soon.

**Comment by TyrakatheDragonFan** [comment]
Fixed. Thanks.
