### ISSUE TITLE
OSX crash when connecting to servers using workshop addons. 

### ISSUE THREAD

**Issue by ShyAnimeGirl** [Facepunch/garrysmod-issues#4820]
### Details
OSX GMod seems to crash when connecting to servers that use workshop addons. This does not occur when connecting to servers without any workshop addons. 
crashlog: https://pastebin.com/HQURVRes
### Steps to reproduce
Connect to any server using workshop addons, right after the 'retrieving server info' stage the game will crash.

**Comment by robotboy655** [comment]
Try the 'dev' beta branch for Garry's Mod and let me know if that fixes it for you.

**Comment by ShyAnimeGirl** [comment]
I have confirmed dev branch fixes workshop downloading issues 100% and I am able to connect and load into various servers.
However there are some which seem to crash after 'mounting workshop addons'.
Log of that crash : https://pastebin.com/XYKUGfa4
This may be a totally unrelated thing to the original problem, and may just be a server specific issue.

**Comment by robotboy655** [comment]
That's unrelated, and the fix should be live on "NONE" beta now.

The crash you are experiencing is similar or the same as https://github.com/Facepunch/garrysmod-issues/issues/2206

**Comment by robotboy655** [comment]
You should be able to avoid that crash by using the "x64" beta branch of the game.

**Comment by ShyAnimeGirl** [comment]
Yup can confirm 64 beta fixes that one too. Thanks!!
