### ISSUE TITLE
DTVar_ReceiveProxyGL return nil new value

### ISSUE THREAD

**Issue by 0fuckthesystem0** [Facepunch/garrysmod-issues#4823]
## Details

after feb update `DTVar_ReceiveProxyGL` return `nil` in `val` parameter on `x86-64 - Chromium + 64-bit binaries` version.

## Steps to reproduce

1.  Add debug print in DTVar_ReceiveProxyGL function

```
function DTVar_ReceiveProxyGL( ent, name, id, val )
	print( ent, name, id, val ) -- val is nil
	if ( ent.CallDTVarProxies ) then
		ent:CallDTVarProxies( name, id, val )
	end
end
```

2. Just see in console
```
Weapon [130][weapon_swep]	Float	0	nil
```

**Comment by robotboy655** [comment]
Should be fixed
