### ISSUE TITLE
DMenu isn't properly closed under certain conditions

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4824]
### Details
Actually, I'm creating some custom panels which close by themselves when the game UI is open. However, when one of my panels has an open DMenu (such as when using the built-in auto-completion system) the DMenu is always open and doesn't close as it should. This is linked to the issues I met during my last issue: https://github.com/Facepunch/garrysmod-requests/issues/1738.

This issue can be solved pretty easily but it happens to default panels and I suspect there are other ways to make it appear. I tried on the chromium/64 bits branches and on the dev branch but I still see the same issue.

`version`:
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 18:02:01 Jan 19 2021 (8097) (4000)
GMod version 2021.02.05, branch: unknown, multicore: 1
Windows 32bit
```

### Steps to reproduce
Test code (source: https://wiki.facepunch.com/gmod/DTextEntry:GetAutoComplete)
```lua
concommand.Add( "test_textentry", function(ply)
    local frame = vgui.Create( "DFrame" )
    frame:SetSize( 300, 300 )
    frame:SetTitle( "Autocompletion Example" )
    frame:Center()
    frame:MakePopup()
    frame.Think = function(self)
        -- Close the frame when the game UI is open.
        if gui.IsGameUIVisible() then
            self:Remove()
        end
    end

    local label = vgui.Create( "DLabel", frame )
    label:SetText( "Type a player..." )
    label:Dock( TOP )

    frame.textentry = vgui.Create( "DTextEntry", frame )
    frame.textentry:Dock( TOP )
    function frame.textentry:GetAutoComplete( text )
        local suggestions = {}

        for _, v in ipairs( player.GetAll() ) do -- For every player,
            if string.StartWith( v:Nick(), text ) then -- if the player's name starts with it...
                table.insert( suggestions, v:Nick() ) -- ... insert it into the list.
            end
        end

        return suggestions
    end
end )
```

Thank you in advance! 👍

**Comment by robotboy655** [comment]
This will need to be handled on a case by case basis.

**Comment by robotboy655** [comment]
You can use https://wiki.facepunch.com/gmod/Global.CloseDermaMenus to close all derma menus.
