### ISSUE TITLE
Some models return bad model bounds when created with ClientsideModel after lod is flushed

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-issues#4826]
### Details
After a map change or `r_flushlod` is ran, the model provided below stops rendering when generated with `ClientsideModel`; in addition `GetModelBounds` returns `vector_origin, vector_origin` is returned on that `ClientsideModel`

### Steps to reproduce
```lua
local mdl = ClientsideModel("models/cod4/weapons/w_g3.mdl")
mdl:SetNoDraw(true)

hook.Add("DrawOverlay", "test", function()
	local x, y = 64, 64
	local w, h = 128, 128
	local lookup = {2, -3}
	local mins, maxs = mdl:GetModelBounds()
	local size = mins:Distance(maxs) / 2.5 * 1.1

	render.SetColorModulation(1, 1, 1)
	cam.Start3D(vector_origin, Angle(0, -90), 90, x, y, w, h)
		cam.StartOrthoView(lookup[1] + -size, lookup[2] + size, lookup[1] + size, lookup[2] + -size)
			render.SuppressEngineLighting(true)
				mdl:SetAngles(Angle(-40, 10, 10))
				render.PushFilterMin(TEXFILTER.ANISOTROPIC)
				render.PushFilterMag(TEXFILTER.ANISOTROPIC)
					mdl:DrawModel()
				render.PopFilterMag()
				render.PopFilterMin()
			render.SuppressEngineLighting(false)
		cam.EndOrthoView()
	cam.End3D()

	surface.SetFont "BudgetLabel"
	surface.SetTextPos(0, 64 + 128 + 4)
	surface.SetTextColor(255, 255, 0)
	surface.DrawText(string.format("Model: %s; mins: %s; maxs: %s; size: %.2f", mdl:GetModel(), mins, maxs, size))
end)
```

![image](https://user-images.githubusercontent.com/6186313/107131623-1e786a80-68a6-11eb-9948-f85e590d1fdf.png)
type r_flushlod
![image](https://user-images.githubusercontent.com/6186313/107131625-2932ff80-68a6-11eb-9990-a1b3d080f026.png)

[weapons.zip](https://github.com/Facepunch/garrysmod-issues/files/5937846/weapons.zip)

don't think you need textures, but if you do let me know

**Comment by meepen** [comment]
note: changing the mins and maxs to the previous values will render it properly still

**Comment by robotboy655** [comment]
Don't much care about r_flushlod but map disconnects SHOULD be fixed on Dev.

**Comment by robotboy655** [comment]
Fuck it wasn't fixed.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by meepen** [comment]
Is this on current dev branch or x86-64 branch by chance?

**Comment by robotboy655** [comment]
It should be on both of those.
