### ISSUE TITLE
debug.traceback's parameters are acting strange

### ISSUE THREAD

**Issue by sanny-io** [Facepunch/garrysmod-issues#4827]
### Details
The wiki shows the signature as `string debug.traceback( thread thread = current thread, number level = 1, string message = "nil" )`, but this doesn't make sense with the behavior below.

### Steps to reproduce
![](https://i.imgur.com/hyDjCPr.png)

**Comment by robotboy655** [comment]
If you do not provide it a thread, the first argument acts as if it is the second argument.

https://wiki.facepunch.com/gmod/debug.traceback

I have also fixed the 2nd and 3rd arguments having the wrong order.

**Comment by thegrb93** [comment]
> If you do not provide it a thread, the first argument acts as if it is the second argument.
> 
> https://wiki.facepunch.com/gmod/debug.traceback
> 
> I have also fixed the 2nd and 3rd arguments having the wrong order.

What the fuck, that explains some past weird shit
