### ISSUE TITLE
gmod doing weird things at spawn menu since update

### ISSUE THREAD

**Issue by javierlovessylvie** [Facepunch/garrysmod-issues#4829]
since the new update came up my gmod has suffer a weird bug at spawn menu and at the playermodel selector its because some of the previews of my props and ragdolls appear as an error and the worst thing is that it keeps loading forever i mean it appears the loading models thing at the right bottom of screen but it just freezes and gives me a fps die it goes from 60fps to 4fps just for the load it always happens but its since this new update the props y ragdolls are totally spawnable without errors and when i close the spawn menu it magically starts loading and when i open it back it does it again! im playing in the most recent version of gmod without branches i mean no chromium etc i tried using other branches and still the same

**Comment by robotboy655** [comment]
Can you record a video of the issue? I am having a hard time understanding the issue.

**Comment by javierlovessylvie** [comment]
@robotboy655

**Comment by javierlovessylvie** [comment]
![Sin título 126_1080p_exported_5851_1612909457196](https://user-images.githubusercontent.com/69820049/107437224-44934a00-6af4-11eb-878b-ffc7d1f944de.jpg)

**Comment by javierlovessylvie** [comment]
It doesn allow me to put a video its a screenshot of what is happening while i try to put video

**Comment by Kefta** [comment]
Upload it to youtube.

**Comment by robotboy655** [comment]
Generating spawnicons is a one time process. You can re-render ERROR spawnicons with the following option by right clicking:
![image](https://user-images.githubusercontent.com/3299036/107526408-7ffb4a80-6bc0-11eb-97b8-f78a0e2fef32.png)

If it happens to the same models every time, it means the game somehow fails to save the icons. They are usually saved in `SteamApps\common\Garrys Mod\garrysmod\materials\spawnicons`. Check if you have enough Disk space on your PC where the game is installed, nothing is deleting those files and no (anti malware) programs are blocking the game from saving files to disk.

You can open your console (SHIFT+ESC) to see if there are any errors.

**Comment by javierlovessylvie** [comment]
I fixed it finnaly i just installed again gmod and all my addons thanks for help facepunch :D
