### ISSUE TITLE
[FIX] sv_region 3

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4830]
Hey! I run a big gmod community,
After the sv_region got Broken, we noticed a big Loss on our Server players base.
The sv_region "3" was giving us a Lot of Players, but now, it seems like all the Servers from all the Regions are appearing in the Gmod Server List.

For example, in the past only 4000 DarkRP server would show up. but now it show up more than 13k Servers, and our servers are Dead because of it.

We can see Chineese servers, American Servers, etc.. and not only European Servers.

Can you just fix the sv_region like before? It was only showing the servers that are in Europe to european players, and American servers to American players! Maybe it was Ping based servers? and Only server with low Ping were shown on the Servers list i guess. or it depends on the Country, and it was Working great.

Now after the sv_region got Broken, and All servers from all countries are shown in the Gmod List, New servers have no chance to Survive, because they aren't priviliged on the servers list. so Only servers with a lot of players can Survive, and others will just Die.

New communities die immediately and this will just Kill the game. because People can't even start their own community because they would Die instantly for the lack of players..

Only big Communities as IceFuse and SuperiorServers that are the worst Gmod Servers can survive, and other communities that want to Innovate the game and make special Addons die instantly because only the Big servers are put forward. while the others are not put forward and just Die after 1 month or 2

That would be so nice, and our player base will be back !

**Comment by robotboy655** [comment]
The server browser will still display the closest servers based on Ping and all servers are search-able in the search bar.

**Comment by karmakarmakarmakarmakarmakarmakarma** [comment]
![image](https://user-images.githubusercontent.com/76236523/109835097-ce898b00-7c3a-11eb-8c46-c294b07de3b4.png)
@robotboy655 Are you telling me that these servers are the closest to me? I live in England. Ping doesn't matter when you live in a European country because there will be plenty of foreign countries that don't speak English while also taking up the entire server list. And, the list is obviously not sorted by ping but by some black box 'rating' characteristic

**Comment by GrandpaTroll** [comment]
Would like to mention people still like to mask their A2S_INFO ping to be on top on the ratings as well.

**Comment by ThatLing** [comment]
Ban anycast when?

**Comment by ThatLing** [comment]
The regions don't matter because server hosts use anycast to cheat themselves to the top of the server list
