### ISSUE TITLE
PhysicsInitBox produce very buggy result, source engine and vphysics have a dispute over several things

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4833]
# How to reproduce

0. Spawn any prop
1. `Entity(...):PhysicsInitBox(Vector(-10, -10, -20), Vector(10, 10, 20))`

# Description

`PhysicsInitBox` produce very weird  and buggy result, where:
* PhysObj is properly created with box collision, and properly calculate collisions
* Worldspace BB reported by `Entity:WorldSpaceAABB` return incorrect result when rotating entity (it behave like entity was never rotated) and
* Traces (util.TraceLine, ents.FindAlongRay, util.TraceHull, *except* physgun trace) behave like entity was also never rotated (it intersect **only** with unrotated bounding box). Moreover, traces won't hit entity unless it intersect **both** worldspace BB and model bounds
* Physgun trace properly hit PhysObj and entity with it **only** when it intersect with unrotated bounding box

![gmod_2TqfxIOGvY](https://user-images.githubusercontent.com/6339511/107629621-fbc6c700-6c94-11eb-8e44-c3352a54309c.png)
![gmod_iCyLZR2i86](https://user-images.githubusercontent.com/6339511/107629628-fcf7f400-6c94-11eb-9f52-ead7f4df0ec6.png)
![gmod_nHFMOoJMn1](https://user-images.githubusercontent.com/6339511/107629635-fec1b780-6c94-11eb-835d-5e284703862a.png)
![gmod_nQK0x8hvHW](https://user-images.githubusercontent.com/6339511/107629640-ff5a4e00-6c94-11eb-98b4-a8d203fab802.png)
![gmod_9OB8bQQ7FA](https://user-images.githubusercontent.com/6339511/107629733-1e58e000-6c95-11eb-8d2b-494186fe7d68.png)
![gmod_XBUuZePcO7](https://user-images.githubusercontent.com/6339511/107629740-2022a380-6c95-11eb-8f81-1e596a448b38.png)
![gmod_V9xESCP1wv](https://user-images.githubusercontent.com/6339511/107629745-2153d080-6c95-11eb-8998-05124e1399be.png)
![gmod_utl37ohb2V](https://user-images.githubusercontent.com/6339511/107629749-2284fd80-6c95-11eb-8a11-257f2525c699.png)
![gmod_78yiug8sYn](https://user-images.githubusercontent.com/6339511/107629867-4cd6bb00-6c95-11eb-8d23-723e491b77db.png)
![gmod_9mTn9I4idN](https://user-images.githubusercontent.com/6339511/107629871-4ea07e80-6c95-11eb-991a-7ef6b3ddc701.png)

**Comment by robotboy655** [comment]
That's because `PhysicsInitBox`, just like `PhysicsInitSphere`, sets the solid type to SOLID_BBOX, which is documented as "Axis Aligned Bounding Box" which is exactly what is happening. 

The functions setting SOLID_BBOX is also documented on the wiki.

```
self:SetSolid( SOLID_VPHYSICS )
self:SetMoveType( MOVETYPE_VPHYSICS )
self:EnableCustomCollisions( true )
```
You can do something like this to get it sort of working.

What is used internally for PhysicsInitBox is only ever used for player's physics objects.
