### ISSUE TITLE
Custom Entities nolonger showing up in hammer

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-issues#4834]
Basically in hammer I had a entity named "ammo_gonk_droid" and I'm currently centered on the entity in 3D view and all 4 grids. The outline shows up on the grid but the entity doesn't show the obsolete icon anymore and the entity class doesn't show on the grids next to it.

I have no way to really tell where the entity is in 3D View and the only way to select it is to use the entity report window.

**Comment by VaasKahnGrim** [comment]
![image](https://user-images.githubusercontent.com/29955667/107683017-b095bf80-6c66-11eb-8704-91dcae20eeae.png)

**Comment by robotboy655** [comment]
Your .fgd configuration for that entity must be incorrect.

**Comment by VaasKahnGrim** [comment]
stock gmod .fgd as far as I'm aware
this is my base, garrysmod and halflife2 fgd files
http://www.filedropper.com/fgsfiles

**Comment by VaasKahnGrim** [comment]
as for the entity itself, it was never in an fgd file. it has always just been put in manually and has never been an issue till now

**Comment by robotboy655** [comment]
Are you on any beta branch?

**Comment by robotboy655** [comment]
And just to clear up, you simply put in a custom entity class in the text box of the entity properties? Nothing else?

**Comment by VaasKahnGrim** [comment]
I only ever work with main branch since thats where most players are usually at and I try to keep things as close to what they run as much as possible. And yes, the entity class manually put in and keyvalues normally are blank and I just manually add them when needed

**Comment by robotboy655** [comment]
It that case it has to be a setting somewhere.

**Comment by VaasKahnGrim** [comment]
I just checked through the sections on the top of the window for hammer and in hammers options section. I can't see anything that would indicate anything related to it. The closest thing would be displaying entity names, but other entities show up as normal

**Comment by robotboy655** [comment]
Send the .vmf I guess, might be some bug you have in there,

**Comment by VaasKahnGrim** [comment]
I can't do that unfortunatly. its a private only map. I'll just see about spawning the entities via lua for now instead

**Comment by robotboy655** [comment]
You can send it to my email (in readme) I have no intention to sharing it with anyone.

**Comment by robotboy655** [comment]
Delete all the brushes for all i care, just make sure the problematic entities are intact.

**Comment by robotboy655** [comment]
Alternatively, load a different .vmt with custom entities that is known to work and see if they work there.

**Comment by robotboy655** [comment]
You have them hidden in a visgroup....
