### ISSUE TITLE
Fonts Issues (Failed to create Font Error)

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4837]
Hey ! when i start my server i get Theses Errors:

[bodygroupr-master] Failed to create font 'bodyman_3d2d_large' from 'Roboto'!
  1. unknown - addons/bodygroupr-master/lua/entities/bodyman_closet/cl_init.lua:3

[ERROR] Failed to create font 'PaperFontText3D' from 'Learning Curve'!
  1. unknown - lua/entities/editable_paper.lua:61

[arcade2] Failed to create font 'arcade2_font_17' from 'Lato'!
  1. unknown - addons/arcade2/lua/entities/gamebox/cl_init.lua:12
  2. 
Couldn't find windows font 'Lato', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Lato' or 'Tahoma'!

[arcade2] Failed to create font 'arcade2_font_15' from 'Lato'!
  1. unknown - addons/arcade2/lua/entities/gamebox/cl_init.lua:19

[sh_accessory_system] Failed to create font 'SH_ACC_VENDOR' from 'Circular Std Bold'!
  1. unknown - addons/sh_accessory_system/lua/entities/npc_accessory_vendor/cl_init.lua:3
Couldn't find windows font 'Franklin Gothic', falling back to 'Tahoma'..
Couldn't find windows font 'Circular Std Bold', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Circular Std Bold' or 'Tahoma'!
Couldn't find windows font 'Lato', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Lato' or 'Tahoma'!

How can  i fix this Issue ??

**Comment by anyome** [comment]
Also i get this error: 

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!


[sh_accessory_system] Failed to create font 'SH_ACC_VENDOR' from 'Tahoma'!
  1. unknown - addons/sh_accessory_system/lua/entities/npc_accessory_vendor/cl_init.lua:5


Even the font Tahoma doesn't Works !!

**Comment by anyome** [comment]
Font Tahoma is not working on Gmod

**Comment by robotboy655** [comment]
You probably have too many addons that create fonts. Like you had a few months ago. Please use the Discord server for general help.

**Comment by anyome** [comment]
> 
> 
> You probably have too many addons that create fonts. Like you had a few months ago. Please use the Discord server for general help.

I'm not using a lot of addons i just have a few ones (3-4).

How can i get this issue fixed??

**Comment by robotboy655** [comment]
It takes only 1 addon to break it. Look at addons that use fonts and delete them one by one and see if the issue goes away.

It is also possible people who get those errors are simply running insanely old computers.

**Comment by thegrb93** [comment]
Or your windows system is busted and missing fonts

**Comment by anyome** [comment]
I removed a lot of addons and now i get this:

[ERROR] Failed to create font 'VC_Name' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Regular_S' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Regular_Ms' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Cruise' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_DEV_lower' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

**Comment by anyome** [comment]
[beekeepingsystem] Failed to create font 'BeekeepingMod_Regular' from 'Abel'!
  1. unknown - addons/beekeepingsystem/lua/beekeeping_system/client/cl_beekeeping_init.lua:20
   2. include - [C]:-1
    3. unknown - addons/beekeepingsystem/lua/beekeeping_system/shared/sh_beekeeping_load.lua:44

**Comment by anyome** [comment]
Please how can i fix this?

My darkrp is finished, i only need to fix this Font issue so i can Open it to the public!

I can't see fonts on my server :/ that's the only thing that's missing !

**Comment by anyome** [comment]
My players have the same problem!

Ouverture de la console


[Pasha|2|STEAM_0:1:20234815] Lua Error:

[beekeepingsystem] Failed to create font 'BeekeepingMod_Large' from 'Abel'!
  1. unknown - addons/beekeepingsystem/lua/beekeeping_system/client/cl_beekeeping_init.lua:21
   2. include - [C]:-1
    3. unknown - addons/beekeepingsystem/lua/beekeeping_system/shared/sh_beekeeping_load.lua:44


[Pasha|2|STEAM_0:1:20234815] Lua Error:

[beekeepingsystem] Failed to create font 'BeekeepingMod_Big' from 'Abel'!
  1. unknown - addons/beekeepingsystem/lua/beekeeping_system/client/cl_beekeeping_init.lua:22
   2. include - [C]:-1
    3. unknown - addons/beekeepingsystem/lua/beekeeping_system/shared/sh_beekeeping_load.lua:44


[Pasha|2|STEAM_0:1:20234815] Lua Error:

[ERROR] Failed to create font 'VC_Dev_Text' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29


[Pasha|2|STEAM_0:1:20234815] Lua Error:

[ERROR] Failed to create font 'VC_Big' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

**Comment by anyome** [comment]
@robotboy655 @garrynewman @willox  Please fix this!
My server is ruined i can't start it because of this Issue !

All the players have the same problem !

**Comment by anyome** [comment]
The main issue is this: 
(Even if the font is not Found the Tahoma Font don't works too)

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

**Comment by anyome** [comment]
> 
> 
> It takes only 1 addon to break it. Look at addons that use fonts and delete them one by one and see if the issue goes away.
> 
> It is also possible people who get those errors are simply running insanely old computers.

@robotboy655 Here is my collection : https://steamcommunity.com/sharedfiles/filedetails/?id=2385652346
The problem is coming from my collection but i can't figure out which addon is causing it !
Can you please tell me which one i need to remove so i can fix this Bug !? Please ! i want to open my server today.

**Comment by ShadowBonnieRUS** [comment]
Do not ping developers to fix not default gmod problem. Disable ALL addons and enable each one by one to detect which addon creates your issue.

And there enough dark rp servers, that kill other gamemodes.

**Comment by anyome** [comment]
I deleted all my addons, and started from cratch, and here i go again i have the same error again that Happened for no reasons.

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Big' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Big_Italic' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Logo' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'.. (x2)
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Menu_Side_Focused' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'.. (x2)
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Menu_Header_Focused' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Name' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'.. (x2)
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Info_Smaller' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Couldn't find windows font 'Tahoma', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'Tahoma' or 'Tahoma'!

[ERROR] Failed to create font 'VC_HUD_Bisgs' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Regular_S' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Regular_Ms' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_Cruise' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

Couldn't find windows font 'MenuLarge', falling back to 'Tahoma'..
Error! Couldn't find windows fonts 'MenuLarge' or 'Tahoma'!

[ERROR] Failed to create font 'VC_DEV_lower' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

**Comment by FoksVHox** [comment]
If you did as said before, then you would know what addon that is causing a problem. This isn't really a Gmod problem.

**Comment by anyome** [comment]
I removed the addons that are causing the issue, put them back, and removed them again. and the Issue started again.

**Comment by FoksVHox** [comment]
> I removed the addons that are causing the issue, put them back, and removed them again. and the Issue started again.

You don't put them back... Noone has told you to put them back afterward...

**Comment by FlorianLeChat** [comment]
Honestly, this issue should just be closed. It's clearly not a Gmod problem and you started to solve it on the Discord.

**Comment by FoksVHox** [comment]
> Honestly, this issue should just be closed. It's clearly not a Gmod problem and you started to solve it on the Discord.

He has started multiple issues like this one. but yeah it should be closed

**Comment by robotboy655** [comment]
I am assuming you fixed your issue. Would be useful to know the details but whatever.

If anyone else comes across this issue, try using `lua_dumpfonts` and see if you have just too many fonts registered.
