### ISSUE TITLE
"toggle_duck" does not work online/is bugged on listen servers

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-issues#4839]
### Details
The console command you should ideally be able to use for toggle-crouching, `toggle_duck`, does not work online and is bugged on listen servers. 

On both, your camera will rapidly jitter up and down when you crouch. On the former, though, you literally cannot move - if you do, you'll jitter in your desired direction, only to snap right back where you were once you stop.

This jittery movement is characteristic of prediction errors, so I set `cl_showerror 2` on a listen server and crouched, [et voila](https://pastebin.com/TG5fgPKY). Looks like `toggle_duck` doesn't set `CPlayerLocalData::m_bDucked` for prediction?

I experienced this while using the most recent x86-64 branch, and haven't tested it on the others, but I have zero reason to believe this isn't a global issue across all branches.

### Steps to reproduce
- Type `bind ctrl toggle_duck` in console.
- Start a singleplayer game; it should work perfectly.
- Join a multiplayer game or listen server. The above described behaviour should occur.

**Comment by mcNuggets1** [comment]
It should if fixed also be in the options menu

**Comment by robotboy655** [comment]
Fixed more or less.
