### ISSUE TITLE
Server can't start anymore

### ISSUE THREAD

**Issue by baptiste-fourmont** [Facepunch/garrysmod-issues#4841]
[debug.log](https://github.com/Facepunch/garrysmod-issues/files/5988043/debug.log)
Hi,
I own two gmodservers since yesterday I use the last version of pterodactyl and  Ubuntu 18.04.4 LTS
And my gmodservers crashed with this error:

Segmentation fault (core dumped)
cat: hlds.36.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Tue Feb 16 10:59:22 CET 2021: Server Quit

**Comment by robotboy655** [comment]
I need something I can actually work with.
https://wiki.facepunch.com/gmod/Crash_Reporting

Either a core dump or a stack trace from the crash.

Did you update your server yesterday?

**Comment by FlorianLeChat** [comment]
I don't know if it has anything to do with that but some C++ modules like ServerSecure are causing segmentation faults (https://github.com/danielga/gmsv_serversecure/issues/60) since the last update, so if you have it installed on your server, you might want to remove it.
