### ISSUE TITLE
Collection -> (Failed to Create Font)

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4842]
@robotboy655 My collection: https://steamcommunity.com/sharedfiles/filedetails/?id=2385652346
Create a bug for all my Players and they can't see most of the Text huds on my server!

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:PInfos' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:5
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:SrvInfos' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:6
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:SrvInfosDesc' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:7
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:PInfos' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:5
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:SrvInfos' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:6
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Pasha|2|STEAM_0:1:20234815

[kadabra_f4] Failed to create font 'KadabraF4:Font:SrvInfosDesc' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:7
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

[ERROR] Failed to create font 'VC_Big_Italic' from 'Tahoma'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

[ERROR] Failed to create font 'VC_Logo' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

[ERROR] Failed to create font 'VC_Menu_Side_Focused' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

[ERROR] Failed to create font 'VC_Menu_Header_Focused' from 'MenuLarge'!
  1. unknown - vcmod?menu:1
   2. unknown - [C]:-1
    3. Include - loader_cl:1
     4. unknown - vcmod??init_shared:1
      5. unknown - [C]:-1
       6. Include - loader_cl:1
        7. unknown - loader_cl:1
         8. e - [C]:-1
          9. onsuccess - pl:1
           10. unknown - lua/includes/modules/http.lua:29

[kadabra_f4] Failed to create font 'KadabraF4:Font:SrvInfos' from 'Arial'!
  1. CreateF4Menu - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:6
   2. func - addons/kadabra_f4/lua/autorun/client/kadabra_f4_base.lua:127
    3. unknown - lua/includes/extensions/net.lua:32

Any help please?

**Comment by robotboy655** [comment]
Stop creating duplicate issues.
