### ISSUE TITLE
Clientside issue with lua

### ISSUE THREAD

**Issue by Dragotiger** [Facepunch/garrysmod-issues#4844]
### Details
As it was fine a while ago started to break on my side, other servers are fine as working but if any solution is available for this.

![Screenshot 2021-02-19 065757](https://user-images.githubusercontent.com/79160983/108420674-d67f1d80-727f-11eb-881c-5524e427e19d.png)

Is this even normal, because as soon as I type in pac_restart this lua comes up and forces me in pac3 editor and autoload will not load for odd reasons. Other pacs will break, and groups breaks puts things out of place.

**Comment by robotboy655** [comment]
This is not a place to get help with 3rd party addons. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

Really though you should be contacting the author of whatever mod is breaking.
