### ISSUE TITLE
Game Crash: Longitude & Latitude of surface.DrawShpere when set to 0

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-issues#4845]
https://wiki.facepunch.com/gmod/render.DrawSphere

### Details
Was curious how a 0,0 longitude and latitude sphere looked. The game engine didn't like that much, Only idiots will crash their game when messing with this, however if server owners start sending lua with this (similar to how they use file.Write & while true do end) it'll crash ya game.

### Steps to reproduce
render.DrawSphere(Vector(0,0,0), 1, 16, 0, Color(255,0,0,255))

Yes, i'm aware it's stupid, but its another vector of attack from bad people to crash ya game.

**Comment by robotboy655** [comment]
Fixed.
