### ISSUE TITLE
Manhack crash

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-issues#4846]
Removing a manhack that has had its sprites removed will crash the game in various ways.

steps:
- spawn manhack
- ```ent_remove_all env_sprite``` in console
- remove or destroy manhack

interesting notes:
- After ```ent_remove_all env_sprite```, if you spawn two more sprites (two antlion grubs in my case) you won't crash immediately, and they will actually inherit the traits of the manhack's sprites when you get near it.
- After ```ent_remove_all env_sprite```, if you spawn one grub then spawn several props then the other grub both will still inherit form the manhack's sprites.
- For this one you must keep your distance form the manhack so it doesn't update its sprites early. If you spawn grubs then the manhack then ```ent_remove_all env_sprite``` then remove the grubs and spawn several props and then two more grubs, they don't inherit the traits of the manhack's sprites or it causes an insta-crash when you approach the manhack. It might have something to do with arbitrary code execution (specifically type confusion), but I don't know for sure.

```CHandle<>``` should probably be used here:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_manhack.h#L253-L254

notes 1:
![image](https://user-images.githubusercontent.com/16133099/108931233-4e00d400-7615-11eb-82d6-afe2088dd0e3.png)

notes 2:
![image](https://user-images.githubusercontent.com/16133099/108931288-653fc180-7615-11eb-8313-a7a22e199aa4.png)

**Comment by robotboy655** [comment]
Should be fixed.
