### ISSUE TITLE
Problems with map compilers.

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#4848]
1.
There is an error in the compiler (possibly `vbsp`) in assembly `x64` that randomly selects one of the objects in `func_instance` and says that it is "`leaked`". This problem is not present in the `dev` assembly (`x32`)

![3jHf5qhlQB](https://user-images.githubusercontent.com/11617079/109336126-0461f480-7874-11eb-9031-2aa4d3e7a7d3.png)

2.
All `x32` compilers still have a very annoying error: they do not display compilation progress `0...1...2...3...` etc.
Progress always stands at `0` and then goes directly to `10`.
There is no such problem in the `x64` assembly.

**Comment by robotboy655** [comment]
Figured it out regarding instances being broken. @Aarik1 would want to know as well.

Well, its not broken. The issue is that it cannot find the .fgd files. Copying the `.fgd` files from `bin/` to `bin/win64/` allows the instance entity merging to work correctly as a temporary solution.

**Comment by robotboy655** [comment]
Next update will find the `.fgd` correctly
