### ISSUE TITLE
Hammer keyvalues copy/paste does not copies spawnflags

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4849]
### Details
Spawnflags are reset to default values.

### Steps to reproduce
1. Create empty VMF level
2. Create `func_door` brush
3. Set `Toggle` flag on and `Touch Opens` flag off
4. Press Copy button on Class Info tab
5. Create `func_detail` brush
6. Press Paste button on Class Info tab

Expected: Second entity has only `Toggle` flag on, all others off.
Actual: Second entity has only `Touch Opens` flag on, all others off (default).

**Comment by MARK2580** [comment]
As far as I remember, flags were never copied, only class and properties.

**Comment by robotboy655** [comment]
Fixed.
