### ISSUE TITLE
WeaponColor matproxy "hack" for physcannon limits SWEPs based on that from using the same functionality

### ISSUE THREAD

**Issue by knoxed** [Facepunch/garrysmod-issues#4851]
### Details
```
-- A hack for the mega gravity gun
local wep = owner:GetActiveWeapon()
if ( IsValid( wep ) && wep:GetClass() == "weapon_physcannon" ) then
	col = Vector( 0.4, 1, 1 )
end
```
[Link to this commit ^](https://github.com/Facepunch/garrysmod/commit/4f37a3df2968a41bdfaea2bef933cf6fbabc4985#diff-3fbb3cf95d917f44999e0fdd1a79864e9b5a08e72cdde459ad91c574393d6e1e)

The code that was added to the WeaponColor matproxy awhile ago (probably while fixing the engine version of the super physcannon) limits scripted weapons that override/are based on the engine weapon from using WeaponColor.

Now this is a very rare case since you don't see engine weapons replaced that often, let alone the gravity gun but it is still kind of a dirty hack which you then need to unhack the hack if you want it back as it was before.  Is there a reason this was fixed like that and not in the actual engine weapon code?

### Steps to reproduce
Create a SWEP with the same classname and models/materials as the engine one and changing the weapon color will not affect it.

![matcolor](https://user-images.githubusercontent.com/1338733/109435081-dcf85c80-7a18-11eb-8d79-e023934bc3e2.png)
Before and after example of a scripted physcannon with no changes to its code in a while.

**Comment by robotboy655** [comment]
You fixed it
