### ISSUE TITLE
Reloading a map with custom models will cause the models to error out (x64)

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#4852]
### Details
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 21:06:29 Feb 19 2021 (8140) (4000)
GMod version 2021.02.19, branch: x86-64, multicore: 1
Windows 64bit
```
This issue only affects the x86-64 branch.

If the same map is reloaded and the bsp is packed with custom models, the models on the next load will fail to load and instead will display the error.mdl model. Loading a different map and then back to the original map will correct the issue until the same map is reloaded. 

### Steps to reproduce

1. Take any map that is packed with custom models and load it.
2. Either rejoin or changelevel <map name>
3. Behold in the glory that is errors everywhere

**Comment by robotboy655** [comment]
http://speedy.bbroleplay.co.uk/maps/surf_summit_gmod.bsp.bz2

**Comment by robotboy655** [comment]
Should be fixed.
