### ISSUE TITLE
Model shipped with map fails to load (x86-64)

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#4854]
### Details
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 17:56:13 Mar  1 2021 (8140) (4000)
GMod version 2021.03.01, branch: x86-64, multicore: 1
Windows 64bit
```

Map with issue: http://speedy.bbservers.co.uk/maps/surf_ravine.bsp.bz2
To instantly get to the location: `setpos -3798.027100 -9841.582031 -1054.810181;setang 6.203936 -172.872314 0.000000`

On x86-64, there's a model at the specified location above which fails to load in for reasons that aren't obvious to myself. This issue isn't present in the 32 bit version and the model functions as intended. 

This issue was present prior to https://github.com/Facepunch/garrysmod-issues/issues/4852 being an issue so I'm inclined to believe is unrelated. 

### Steps to reproduce
1. Load the map `surf_ravine`
2. sv_cheats 1 and setpos the location above
3. Model is missing.

**Comment by robotboy655** [comment]
It's likely not being decompressed successfully/properly.

Model models/surf_ravine/surf_ravine_ramp10.mdl not a .MDL format file!

**Comment by robotboy655** [comment]
Kinda weird that it only happened on x64, maybe the order of files internally somehow is different when loading BSP pack on 64bit builds, but anyways, should be fixed soon.
