### ISSUE TITLE
Failed To find any models for this addon (what??)

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/garrysmod-issues#4855]
![image](https://user-images.githubusercontent.com/50423227/109707034-98440100-7b91-11eb-9ff5-4c10ae410e28.png)
This happens to every addon im subscribed to, the models exist, as i can load saves that use them without issue but i just cant see the models on my addon list,

my gmod version is on the beta x32-x64 build thats also using chromium, ive only just noticed it happening today

Edit: i think it might have to do with this change
![image](https://user-images.githubusercontent.com/50423227/109708339-2cfb2e80-7b93-11eb-8883-1df933c5edcc.png)
im using your old spawnmenu addon so it mightve broke something on how it searchs for models or something idk

Ok ive just checked after relaunching gmod twice, still broken after unsubscribing, your new code is broken. rubat, pls fix

**Comment by robotboy655** [comment]
Debug code strikes again, sorry about that. Will get it fixed asap.
