### ISSUE TITLE
Hammer is broken again !

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#4865]
Due to change #7959, it is no longer possible to make an entity from a regular brush, for example, just func_detail.  
You are a great coder. 😊  https://commits.facepunch.com/379945
![AmDeinPAm1](https://user-images.githubusercontent.com/11617079/110990776-d78a0300-8384-11eb-8916-2e94a665856d.png)

**Comment by thegrb93** [comment]
You don't have to be a cunt about it.

**Comment by MARK2580** [comment]
> You don't have to be a cunt about it.

Don't defend him. He makes changes that often only make things worse. At this point, again, my work has stopped. I cannot create entities from the brush.

**Comment by robotboy655** [comment]
> At this point, again, my work has stopped. I cannot create entities from the brush.

You can always switch your game to the stable version. This is what unstable beta branches are for. To catch errors before release.

**Comment by MARK2580** [comment]
> > At this point, again, my work has stopped. I cannot create entities from the brush.
> 
> You can always switch your game to the stable version. This is what unstable beta branches are for. To catch errors before release.

Okay, but I'm still waiting for this fix. Please be careful and do not repeat such fatal mistakes.

**Comment by robotboy655** [comment]
Should be fixed whenever it updates.

**Comment by MARK2580** [comment]
> Should be fixed whenever it updates.

Yes. Fixed.
