### ISSUE TITLE
BSP.exe does not compile Local Light Shadows

### ISSUE THREAD

**Issue by JimbobweSmells** [Facepunch/garrysmod-issues#4876]
### Details
  With "Enable Local Light Shadows" set to "Yes" in a maps shadow_control entity, lights with "Cast entity shadows" enabled do not affect entity shadow angles as they should when compiled with Garry's Mod build programs as shown in [the following screenshots](https://imgur.com/a/mSMnNvD) which shows a comparison of the same map compiled in Left 4 Dead 2 and Garry's Mods Hammer.

No addons are enabled, the same compile options are used for both games, and the screenshots show the same map (with missing texture changes) compiled in both the L4D2 Hammer editor, and the Garry's Mod Hammer editor.

Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 21:15:31 Mar 17 2021 (8140) (4000)
GMod version 2021.03.17, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
Create shadow_control entity
Enable local light shadows in the entity
Create light entities
Enable cast entity shadows in light entities.
Create physics prop entities
Compile map

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1458
