### ISSUE TITLE
quit concommand blocked on server

### ISSUE THREAD

**Issue by Aws0mee** [Facepunch/garrysmod-issues#4877]
### Details
When trying to run "quit" with RunConsoleCommand you get the message RunConsoleCommand: Command is blocked! (quit). It makes sense that this would be blocked on the client to prevent server owners from closing a client's game, but it doesn't make sense to block it on the server(especially since killserver is not blocked).

### Steps to reproduce
RunConsoleCommand("quit")

**Comment by robotboy655** [comment]
What's exactly wrong with using `killserver` instead?

**Comment by Aws0mee** [comment]
> What's exactly wrong with using `killserver` instead?

nothing, but it doesn't make sense to block one and not the other. It would make more sense to either block both or neither.

**Comment by robotboy655** [comment]
Thing is, in singleplayer that does quit the client. `killserver` does not.
