### ISSUE TITLE
HDR Being off is apart of the problem tab?

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/garrysmod-issues#4879]
Hdr in gmod being off is apart of the problems tab why? its annoying to use and is poorly coded, and only really works on the two default maps. why is it counted as a problem if its a setting in the advanced options menu? bumpmapping i understand since you need to use console to disable it but HDR is literally an OPTIONAL thing, and especially on some maps like Mobenix_V3 where everything is an eyesore to look at. can you please remove hdr being off from the problems tab, almost noone uses hdr anyway

**Comment by robotboy655** [comment]
It's a problem because some maps (Like CS:GO, some HL2 maps, community maps) are not compiled to support LDR lighting, so they will appear as if mat_fullbright is turned on.

If disabling it your conscientious choice, then you can just ignore that problem.
