### ISSUE TITLE
(Dev) SRCDS output: Falling back to 4:3 aspect ratio. This should never happen!

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#4881]
### Details

```version
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 21:12:22 Mar 15 2021 (8137) (4000)
GMod version 2021.03.24, branch: unknown
Windows 32bit Dedicated Server
```

When booting a server on dev, a new line of output occurs that doesn't really make sense for srcds which is 
`Falling back to 4:3 aspect ratio. This should never happen!`. Appreciate it's a low effort report but figured just in case. 

### Steps to reproduce
Boot a server up on srcds, see the output.

Live srcds: 
![image](https://user-images.githubusercontent.com/1713740/112362939-e3eb5580-8ccc-11eb-988b-172a230b203a.png)

New srcds:
![image](https://user-images.githubusercontent.com/1713740/112362923-e0f06500-8ccc-11eb-9002-f59b2241144c.png)

**Comment by robotboy655** [comment]
Fixed.
