### ISSUE TITLE
Poster function not handling sun glare (and probably other effects) properly - segments lit unevenly

### ISSUE THREAD

**Issue by RavMahov** [Facepunch/garrysmod-issues#4883]
### Details
As seen on attached screenshot, once some sort of light filter is applied (tested with sun), image parts (rectangles) are not evenly bright. Top-left rect will have light applied, most of the others will have none, and apparently, some can get slightly brighter (example image proves that).
![poster-21-03-30 23-29-55](https://user-images.githubusercontent.com/9891611/113059611-f1627d00-91af-11eb-9b9e-47192ac6b170.png)

### Steps to reproduce
Settings: HDR disabled, Bloom disabled, Motion blur enabled, Multicore rendering enabled, everything else on highest setting.
1. Load gm_skylife map from workshop.
2. Look at the sun enough that the viewport gets lit
3. Open console
4. Run `poster 2` then `poster 4` command
5. Check out resulting screenshots
6. Top-left rect will be lit, rest is often at least much darker, but most often just regular non-lit color (the attached image also found the problem with bottom-left rectangle

**Comment by robotboy655** [comment]
Unfortunately this is unavoidable due to how the poster command works. It renders each part of your image separately at your screen resolution. So when it renders the part that has the sun entity in it, the effects will be there, for all other parts the sun entity will not be in your view port so naturally the effect cannot render.

**Comment by RavMahov** [comment]
It might be unavoidable (though maybe it could be avoided somehow), but personally, I'd rather have consistent screenshot without glare than inconsistent one with. Can you somehow disable the effects like these during poster function operation? Maybe while figuring it out, it will turn out that you can somehow just copy camera overlay settings from one segment to another or some other workaround.
But still, with no effect, it would be better than with inconsistently applied effect.

**Comment by robotboy655** [comment]
I have looked into it and yeah, turns out its not caused by what I thought it was caused by, so I fixed it.

You can test it on the 'dev' beta branch of the game on Steam.

**Comment by RavMahov** [comment]
Many thanks! The fix seems to work both on no HDR and HDR too!

Out of curiosity, what exactly was causing it?
