### ISSUE TITLE
Garry's Mod crashes when loading a save of a map with a crane entity on it

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#4884]
### Details:
I loaded into a map with a crane in it, I saved the game then loaded that save and the game crashed.

### Steps to reproduce:
Load into d2_coast_04, save the game then load that save.

### Version:
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 03:58:53 Mar 30 2021 (8173) (4000)
GMod version 2021.03.30, branch: unknown, multicore: 1
Windows 32bit

### Crash dump:
[hl2_210330_crash_2021_4_1T3_35_33C0.txt](https://github.com/Facepunch/garrysmod-issues/files/6240927/hl2_210330_crash_2021_4_1T3_35_33C0.txt)

**Comment by robotboy655** [comment]
Should be fixed on Dev beta.
