### ISSUE TITLE
engine.GetGamemodes() does not get updated when (un)mounting addons in menu

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#4886]
### Details
x86_64 branch, output of engine.GetGamemodes() is unchanged when mounting or unmounting addons, causing new gamemodes added by said addons not appear in the map (and gamemode) selection list until game restart.

### Steps to reproduce
1. Install any addon that includes a gamemode
2. Disable it through addons menu
3. The gamemode is still shown in the selector and if any maps for the gamemode are available, they would still show up under that gamemode name.
4. Restart the game
5. Enable the addon through addons menu
6. Maps for the gamemode are listed under "Other" category, gamemode does not appear in the selection list.

Simple code inserted after [this line](https://github.com/Facepunch/garrysmod/blob/0f72e8aac8f64f0d519f4c5cfdfc01d713d8c1d9/garrysmod/lua/menu/getmaps.lua#L187) shows that engine does not output updated gamemodes list:
https://user-images.githubusercontent.com/5104603/113333026-9d2fd800-932a-11eb-8362-106aaee311f6.mp4
https://user-images.githubusercontent.com/5104603/113333209-d405ee00-932a-11eb-9cdb-feb801006b74.mp4

**Comment by robotboy655** [comment]
Should be fixed on Dev (others will follow soon)
