### ISSUE TITLE
Softlock caused by loading a save on testchmb_a_00

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#4889]
### Details:
I loaded into testchmb_a_00, I saved the game then loaded that save and the wakeup animation plays and look I can't move.
(This used to work in an earlier version of Garry's Mod about a year or two ago)

### Steps to reproduce:
Load into testchmb_a_00, save the game then load that save.

### Version:
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 03:58:53 Mar 30 2021 (8173) (4000)
GMod version 2021.04.02, branch: unknown, multicore: 1
Windows 32bit

**Comment by robotboy655** [comment]
There isn't a good way around this with the current save system, so I just had to disable animations like that when loading a save.
