### ISSUE TITLE
Creating a new manifest crashes hammer (new bug since update 2021.04.02)

### ISSUE THREAD

**Issue by js1251** [Facepunch/garrysmod-issues#4892]
### Details
Since the latest gmod and hammer update (which is great!) hammer will crash when trying to create a new manifest for any vmf.
This has not been an issue before. 

### Steps to reproduce
1. Open any .vmf map with at least some stuff in it
2. Go to "Instancing">"Create Manifest">"Yes"
3. Hammer will crash

**Comment by robotboy655** [comment]
Huh, I was wondering what that manifest window was for. Should be fixed on Dev beta.
