### ISSUE TITLE
Hammer Editor: Collision wireframe preview not drawn in 3D view in a .vmm file

### ISSUE THREAD

**Issue by js1251** [Facepunch/garrysmod-issues#4893]
#### The collision wireframe preview does not show in the 3D view of hammer when working in a manifest .vmm file. Note that this is an issue with older hammer versions or hammer versions from other games too so its not strictly gmod only.

When creating a manifest you no longer open up a .vmf in hammer but a .vmm which then has .vmfs as submaps.
Since manifests arent common practise I'll link to the dev wiki just in case:
https://developer.valvesoftware.com/wiki/Instance#Manifests
___
When toggeling the collision wireframe preview on it no longer shows it in the 3D view as shown here:
![image](https://user-images.githubusercontent.com/57368720/113848143-78a78600-9798-11eb-978f-3efa11e125a6.png)

Opening this submap directly as a .vmf will show the collision preview just fine:
![image](https://user-images.githubusercontent.com/57368720/113848328-a4c30700-9798-11eb-8e88-81522246c6ba.png)

### Steps to reproduce

1. Create a new map in hammer
2. Place any model that has a collision mesh
3. Verify that you can see the collision mesh in the 3D viewport by enabling:
![image](https://user-images.githubusercontent.com/57368720/113851171-8579a900-979b-11eb-80f1-362e3253d558.png)
4. Create a manifest verison of a map (Go to "Instancing">"Create Manifest">"Yes"). (**This in it self is broken since update 2021.04.02!** see #4892)
5. Note that the collision wireframe preview no longer shows up in the 3D viewport

**Comment by robotboy655** [comment]
Should be fixed on 'dev' beta.
