### ISSUE TITLE
VMatrix:SetAngles can cause the matrix's scale to shrink slightly

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-issues#4897]
A simple example:

```lua
local m = Matrix()
assert(m:GetScale().x == 1)
m:SetAngles(Angle(0, 250.7578, 0))
assert(m:GetScale().x == 1)
```
x scale becomes 0.99999994039536 after SetAngles.

It doesn't happen with all angles.

Maybe related to https://github.com/Facepunch/garrysmod-issues/issues/2222 ?

**Comment by thegrb93** [comment]
Scale and rotation share components so this makes sense. It's just a floating point precision discrepancy.

**Comment by CapsAdmin** [comment]
I'm convinced this is expected by thegrb93.

The reason I was running into this issue was because I was using a cached matrix where I only called SetAngles and SetTranslation. The proper way to do that is calling VMatrix:Identity() first since SetAngles might modify the scale.

This behavior should be mentioned on the wiki instead.
