### ISSUE TITLE
Picking up special case lua setup vehicles causes the server to crash

### ISSUE THREAD

**Issue by jacklollz2** [Facepunch/garrysmod-issues#4898]
**Spawning of the car:**
local Car = ents.Create("prop_vehicle_jeep")
Car:SetPos(...) -- Insert testing pos
Car:SetModel("models/buggy.mdl")
Car:SetCreator(...) -- Player who spawned it in
Car:SetName("Vehicle")
Car:Spawn()
Car:PhysicsInit(SOLID_BBOX)
Car.VehicleTable = list.Get("Vehicles")["Vehicle"]
Car:Activate()
Car:SetMaxHealth(1000)
Car:SetHealth(1000)
Car:Fire("addoutput","explodedamage 0",0)
Car:Fire("addoutput","exploderadius 0",0)

When the physgun picks up the car, its collision group is set to COLLISION_GROUP_DEBRIS.

[Crash Files](https://mega.nz/folder/Q0ckBbCD#jjvmrJrd1mTZxeEWDLbIIg)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
