### ISSUE TITLE
GetSoundInterests 713.219971 (x4)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4900]
### Details
This spams my console infinitely on the map rp_downtown_evilmelon_v1.
I don't know what it causes.
I'm on 64 bit.

Edit:
Does now happen on more than only one map.

### Steps to reproduce
Not entirely sure, just visit the map maybe?
If there would atleast be a hint to what the error even means.

**Comment by robotboy655** [comment]
Should be fixed.
