### ISSUE TITLE
engine.GetAddons: "tags" key is empty on Dedicated Server addons

### ISSUE THREAD

**Issue by iguneesu** [Facepunch/garrysmod-issues#4901]
### Details
When executing engine.GetAddons() on a Dedicated Server, the "tags" table key that contains a given addon's Steam Workshop tags is empty. 
![image](https://user-images.githubusercontent.com/14958008/114465932-157a8100-9be8-11eb-955b-e1aae1d94c02.png)
The issue isn't present in the game client.
![image](https://user-images.githubusercontent.com/14958008/114466021-3511a980-9be8-11eb-9dd5-54c5aba40298.png)

### Steps to reproduce
1. Set up a Garry's Mod SRCDS instance
2. Configure and run the instance with `host_workshop_collection` pointing to a valid Steam Workshop collection ID
3. Execute `lua_run PrintTable(engine.GetAddons())` inside the server console

**Comment by robotboy655** [comment]
Should be fixed on Dev.
