### ISSUE TITLE
Material does not load KeyValues properly on Linux

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-issues#4902]
### Details
Map that contains issue: [ttt_crummycradle_a4](https://steamcommunity.com/sharedfiles/filedetails/?id=264864627)
Inside the area on top, where the glass is.

Tested on Windows x86-64 branch (client) and Linux dev (server) and Windows dev (server) to see differences

### Steps to reproduce

Go inside this area of the map and look at this glass pane:
![image](https://user-images.githubusercontent.com/6186313/114491899-73f23000-9be5-11eb-9e2c-6c65ee099bbd.png)

Run:

`lua_run PrintTable(Material(player.GetHumans()[1]:GetEyeTrace().HitTexture):GetKeyValues())`

On windows, this will be properly showing the patched material, while on Linux it will not properly get the correct keyvalues. `$surfaceprop` will be set to the same value as `$flags` on Linux for some reason.

![image](https://user-images.githubusercontent.com/6186313/114492134-ecf18780-9be5-11eb-9969-d44786c55d6f.png)

**Comment by meepen** [comment]
note: this does not just affect `GetKeyValues`, it also affects `TraceResult.SurfaceProp` and other things like that.

**Comment by robotboy655** [comment]
Should be fixed on Dev. It's not going to be the same as it is on client/windows srcds, but it will not be incorrect like that.

**Comment by meepen** [comment]
If you don't mind could you share what the problem was? I'm very curious

**Comment by robotboy655** [comment]
Shaders not existing on linux srcds, which exposes some bad engine code that did not account for the 4 shader parameters it sets for all materials.
