### ISSUE TITLE
GM:Initialize() freezes my dedicated server after spawning a prop

### ISSUE THREAD

**Issue by Xalalau** [Facepunch/garrysmod-issues#4903]
### Details

I'm running the default GMod branch and playing in my updated dedicated server (alone).

> Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 03:58:53 Mar 30 2021 (8173) (4000)
GMod version 2021.04.02, branch: unknown, multicore: 0
Windows 32bit

> Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 03:58:53 Mar 30 2021 (8173) (4000)
GMod version 2021.04.02, branch: unknown
Windows 32bit Dedicated Server

Apparently my addon [NPC Battle Cleanup](https://steamcommunity.com/sharedfiles/filedetails/?id=2120936972) no longer worked for people (subscribers dropping, a complaint today), and when I went to test it in the reported circumstances my server froze.

At the moment I just have another simple script installed, called [Ultimate Workshop Downloader](https://steamcommunity.com/sharedfiles/filedetails/?id=2214712098).

The problem ended after [this simple replacement](https://github.com/Xalalau/NPCBattleCleanup/commit/748a009560f8e489bd0f18eebb43235632f411ce).

### Steps to reproduce

I isolated the cause as follows:

1) Create the file */lua/autorun/server/anyfile.lua* in the dedicated server with this example:
```lua
hook.Add( "Initialize", "some_unique_name", function()
    print( "Initialization hook called" )
end )
```

2) Spawn any prop on the map.

3) The server freezes and the game keeps running.

**Comment by thegrb93** [comment]
My server has tons of initialize hooks and I've never seen this.

**Comment by thegrb93** [comment]
Your addon probably has some hook ordering dependence and your adding a new hook has thrown it off and is now infinite looping.

**Comment by robotboy655** [comment]
Lots of servers have s tons of initialize hooks and I've never seen this either.

Most likely you have some other addon that basically puts the server into an infinite loop.

I could not reproduce the issue on an empty dedicated server.

**Comment by robotboy655** [comment]
I also tried installing both your and the downloader addons, and running server with that, still nothing.

**Comment by Xalalau** [comment]
I know this one would be too serious to go unnoticed, but I froze my server about 30 times before I came here. Today I can't lock anything anymore, the only difference is that I restarted the PC. Thank you for your attention, but I think it remains only to close this report.
