### ISSUE TITLE
Gamemode Search Bar Bug

### ISSUE THREAD

**Issue by atlasuprising** [Facepunch/garrysmod-issues#4905]
### Details
Branch - x86-64 - Chromium + 64 bit binaries
Version - 2021.04.12
Operating System - Windows 10.0.19041 Build 19041

Whenever I use capital letters to search for a gamemode, for example: "SCP", it doesn't find SCPRP gamemode. But if I search "scp" it finds the SCPRP gamemode.

### Steps to reproduce
1 - Find Multiplayer Game
2 - Click the "Search gamemodes" textbox
3 - Type any gamemode name in full capital letters
4 - You will find that no gamemode appears.

**Comment by robotboy655** [comment]
Should be fixed on Dev beta and in the future update.
