### ISSUE TITLE
Using Player:SetDSP( 0 ) with 	RunConsoleCommand("stopsound") will fail the DSP reset

### ISSUE THREAD

**Issue by creatoxx** [Facepunch/garrysmod-issues#4909]
### Details
I'm using both functions in a code block executed on keypress hook. Initially I would set the DSP to 4, and reset it to 0 after I press my toggle key. Using said console command anywhere after, or before the DSP, will fail, so the DSP will stay with the value I gave it, when I initially turned on my keypress function.

### Steps to reproduce
Just use the two functions anywhere in your code together.

Player:SetDSP( 0 )
RunConsoleCommand("stopsound")

**Comment by robotboy655** [comment]
Cannot confirm.
```
lua_run_cl Entity(1):SetDSP(4)
```
And then
```
lua_run_cl Entity(1):SetDSP(0) RunConsoleCommand("stopsound")
```
Works as expected, when no mods are running.
