### ISSUE TITLE
prop_physics respawnable

### ISSUE THREAD

**Issue by vjnxhen** [Facepunch/garrysmod-issues#4912]
### Details
prop_physics respawnable will only spawn once when they are partially inside of a wall

### Steps to reproduce
place a prop_physics respawnable partially inside the world and it will only spawn once

if this is intentional then why does the prop spawn only once but not again?

**Comment by robotboy655** [comment]
prop_physics_respawnable will not respawn if its spawn position is blocked by something, so the player won't get stuck inside it etc. The initial map load does not count as respawn.
