### ISSUE TITLE
Re-render all icons returns a script error

### ISSUE THREAD

**Issue by Yunpol** [Facepunch/garrysmod-issues#4914]
### Details

Clicking on the all icons sub-option in the Re-render option returns this script error below. I have verified the game cache after encountering this error and the error still persists after doing so.

```
[Other] lua/vgui/spawnicon.lua:267: attempt to call method 'RebuildAll' (a nil value)
    1. DoClick - lua/vgui/spawnicon.lua:267
        2. OnMouseReleased - lua/vgui/dlabel.lua:237
            3. unknown - lua/vgui/dmenuoption.lua:76
```
Version: 2021.04.02, branch: none, Windows 10 64-bit

### Steps to reproduce
1. Load up spawnlist
2. Right click on any icon
3. Select Re-render, then click on All icons.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/ae690a17b82fc3fd82a1e47daa04dfe0a4d8b17f

The issue is already fixed for a future update and on dev/x86-64 betas
