### ISSUE TITLE
mat_showlightmappage not behaving as intended.

### ISSUE THREAD

**Issue by zxz41** [Facepunch/garrysmod-issues#4915]
The lightmap preview material don't seem to update properly when drawn. It can offen be fixed by placing down (multiple) dynamic light sources or loading in new areas.

This can easily be tested by loading up a map I.E. d1_canals_01 and drawing a lightmap page (in this case page 4, since it highlights visible masks) without having moved around or loaded any new geometry.

Here's the expected behavior from Half-Life 2, the lightmap page is rendered correctly. (Build 5377866)
![Lightmap page from Half-Life 2](https://user-images.githubusercontent.com/11709919/115263819-050d5d80-a136-11eb-8b1b-f57a5f29593c.png)

And here's the lightmap page rendered in Garry's Mod. (GMod version 2021.04.19, branch: dev, multicore: 0)
![image](https://user-images.githubusercontent.com/11709919/115264361-8664f000-a136-11eb-8bc5-60ce1e7761d8.png)

Something noticeable is that the texture dev/twenty.vtf is never shown in the texture list, implying that the debug/debuglightmap material is never being applied?

**Comment by robotboy655** [comment]
Should be fixed on Dev.
