### ISSUE TITLE
New Servers are Dying because of this BUG. 👎💯 

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4917]
Hey !

I noticed that the Gmod Browser don't show all the Server when you click on "Find Multiplayer Games" for the first Time
It only shows Server that are not Empty or Full servers.

So people need to do: "Refresh Listing" in order to see the Others Servers.

We are a New Community, and we want to bring Players to our Servers, but they don't see Them in the Server Browser List and need to do "Refresh Listing" everytime in order to be able to see our Servers cause they are New Servers.

When they press : Find Multiplayer Servers it only shows 2000 Servers.
After clicking on Refresh Listing it start Showing +7000 servers.

This is a Bug that needs to be Fixed.

Bug => Empty Servers are not Shown on the Server Browser List.
How are we Supposed to make our Servers Successful if they don't even get Shown on the Browser List if they are Empty?.
Please fix this ASAP. it's only this that makes our Community not able to rocket launch.

Thank you 
@willox 
@robotboy655

**Comment by FlorianLeChat** [comment]
Willox didn't work anymore for Facepunch.

**Comment by robotboy655** [comment]
It first polls not empty servers, then only empty ones, to circumvent limitations set by Valve.

As for the issue you are having, it seems to be on your end. I have been using the server browser extensively when developing and testing all the new features recently, it always gets to 7k without clicking refresh listings.

That being said, if you can't be bothered to join your own server, maybe you shouldn't host one.

**Comment by MARK2580** [comment]
@anyome  teach users how to use the console, it's not so difficult to open it and enter connect ip

**Comment by anyome** [comment]
> 
> 
> It first polls not empty servers, then only empty ones, to circumvent limitations set by Valve.
> 
> As for the issue you are having, it seems to be on your end. I have been using the server browser extensively when developing and testing all the new features recently, it always gets to 7k without clicking refresh listings.
> 
> That being said, if you can't be bothered to join your own server, maybe you shouldn't host one.

Hey! @robotboy655 
Thanks for your Reply!

Empty servers are not Shown when people refresh the server browser List and this is a Big problem because "Our" community can never become Popular if players can't even see Servers..

Can you at least bring back the sv_region thing, and only show Servers that are Ping based even if they are empty?

Like that , European players won't have to deal with Americans and Russian Servers.

In 2018, The server browser was showing only the Servers that are in Europe for european servers
and American servers for American players.

Can you bring back this Fix??

It's better to Show empty servers than to show Russian/Americans servers for European Players.

And communities will have More Luck to Become successful cause our Community Started Dying after the Update of 2020 when the sv_region was Broken.

We had 700 players back then, and now we turn at 40-50 players... and we had a big community

all of this because of the Massive : Russian and americans servers that were not shown before for the French Community.

**Comment by robotboy655** [comment]
I removed the server browser bypass for valve's master server limit now that they increased it, on the off chance it somehow somewhy breaks for someone.

We have no control over what Valve does with sv_region data. You can still set it, and is still sent to Valve.
