### ISSUE TITLE
gmod

### ISSUE THREAD

**Issue by Wilbur642** [Facepunch/garrysmod-issues#4918]
In developer console there are bunch of LUA errors for the menu when i try to click "Drawing" nothing works and more errors show up in the console;
: attempt to call global 'CanAddServerToFavorites' (a nil value)

lua/menu/mainmenu.lua:79 \[\]
MENU ERROR: lua/menu/mainmenu.lua:79: attempt to call global 'CanAddServerToFavorites' (a nil value)

lua/menu/mainmenu.lua:79 \[\]
MENU ERROR: lua/menu/mount/mount.lua:91: attempt to call method 'SubscriptionsProgress' (a nil value)

lua/menu/mount/mount.lua:91 \[v\]

lua/includes/modules/hook.lua:84 \[\]

[ERROR] gamemodes/base/gamemode/animations.lua:333: attempt to index local 'ply' (a nil value)

unknown - gamemodes/base/gamemode/animations.lua:333

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
