### ISSUE TITLE
GetTouchTrace's last trace crashes the game when the HitEntity no longer exists

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-issues#4919]
It is known that GetTouchTrace actually returns last collision trace used, but it crashes the game when the last entity that got hit no longer exists. This is bad in cases where we try to retrieve the last touch trace in other hooks than ENTITY:Touch(), mostly for C++ entities, 

Steps to reproduce: 

While in gm_flatgrass: 

1-) Turn on noclip 
2-) Spawn a prop_physics from the context menu (preferably something that you can stand on) 
3-) Freeze the prop mid-air 
4-) Land on the prop (turn off noclip) 
5-) Call GetTouchTrace on player (lua_run Entity(1):GetTouchTrace()) 
6-) Turn on noclip 
7-) Remove the prop 
8-) Call GetTouchTrace on player (lua_run Entity(1):GetTouchTrace()) 

Which will then result in a crash. 

This could also be related to nextbot's OnContact hook, which causes my projectiles to crash my game when they hit nextbots in some cases, even though I use GetTouchTrace() in StartTouch(). I don't have investigated NextBot entity touch behavior yet, so I can't tell anything much about that, thought it would worth mentioning.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
