### ISSUE TITLE
string.find()

### ISSUE THREAD

**Issue by AuroraSpellman** [Facepunch/garrysmod-issues#4920]
### Details
Not sure If I'm doing something wrong, however, string.find() function doesn't seem to bother searching if the needle contains a hyphen (-)

### Steps to reproduce
print(string.find("test-test@hotmail.com", "test-test@hotmail.com")) -- Returns nil

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

Please also use the wiki before posting: https://wiki.facepunch.com/gmod/string.find

**Comment by WilliamVenner** [comment]
It's because `string.find` uses [Lua Patterns](https://wiki.facepunch.com/gmod/Patterns)

If you want to string.find without using a pattern, pass `true` as the fourth argument:

```lua
print(string.find("test-test@hotmail.com", "test-test@hotmail.com", 1, true)) - Returns 1	21
``
