### ISSUE TITLE
Player:IsBot() returns false incorrectly in OnEntityCreated

### ISSUE THREAD

**Issue by swampservers** [Facepunch/garrysmod-issues#4923]
### Details
In `OnEntityCreated` hook for a bot player, :IsBot() returns false.

Using latest x86-64 branch server.

### Steps to reproduce
`hook.Add("OnEntityCreated", "sneed", function(ply) print(ply:IsBot()) end)`
Then `bot` in console

**Comment by robotboy655** [comment]
This isn't really something that is fixable without some shitty hacks, and then you will complain how every single other property of an entity is not initialized in `OnEntityCreated`. Fact of the matter is, `OnEntityCreated` on server is ran as soon as the entity object is called, before any methods were called on it.

Consider this pseudo code:
```
CBaseEntity* ent = CreateNewEntity( "player" ) // OnEntityCreated is called from this function
ent->SetFlag( BOT ) // IsBot returns true after this call
...
```

This is the reason `PlayerInitialSpawn` and hooks like it exist. This is the reason a lot of entities require `Spawn()` or `Activate()` called on them to update them in certain cases.
