### ISSUE TITLE
Map IVP Issue on Garry's Mod 64bit

### ISSUE THREAD

**Issue by Elloer** [Facepunch/garrysmod-issues#4924]
### Details
I am reposting this bug as I made a temporary github and the post got deleted as I didn't have a personal account set up as I rarely find the need to have a github account. Anyhow, the crash seems to be caused by launching the map sde_a08_underground_a, a snowdrop escape map. 

Example of Map Crashing on 64bit:
![3IB7WOmKVu](https://user-images.githubusercontent.com/83121314/115958100-f7f4c380-a4d3-11eb-8007-14a382136444.gif)
Example of Map Starting on 32bit:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/83121314/115958016-90d70f00-a4d3-11eb-9cfd-6bcebd274806.gif)

### Steps to reproduce
Start the map and it will immediately produce this error, but it only occurs on the 64bit branch, not 32 bit.
![bug gmod](https://user-images.githubusercontent.com/83121314/115957829-b6afe400-a4d2-11eb-9f4e-207ef119e34c.png)

Crash Dump: https://cdn.discordapp.com/attachments/335283604957560833/835474533376720906/8d741465-768c-4849-8b02-000a647b7f13.dmp

Map file in question: https://file.io/bNumcUuzCeKq

**Comment by robotboy655** [comment]
Should be fixed.
