### ISSUE TITLE
3D2D Textscreens => Crash 80% of Players !!

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4925]
Hey,

This addon: https://steamcommunity.com/sharedfiles/filedetails/?id=109643223

Makes all my Gmod Players crash when they try to Join my server for some Mysterious reasons !

A lot of players their Gmod crash because of this Addon when they first Join.

So i can't get 70-80% of players to join my Server because of the 3D2D Textscreens addon!

The problem is that this addon is a MUST-HAVE and is so Important, and no body can run his Server without it! (because it's Important for : Rules / Informations / Forum Link etc..)

Can you please fix it?

@robotboy655

**Comment by robotboy655** [comment]
If you have an problem with an addon, you should be contact the addon author for help.

If you want to be actually useful for once, please read how to properly report crashes:
https://wiki.facepunch.com/gmod/Crash_Reporting
