### ISSUE TITLE
SetParent() collisions dont work compared to hammer parented collisions

### ISSUE THREAD

**Issue by js1251** [Facepunch/garrysmod-issues#4931]
### Parented Objects do not cause physics interaction (but they can!)

First of all **I know this is a recorded warning on the wiki**. Im hoping to find out why it DOES work when parenting via hammer and if its possible to get that across ingame.

In all three examples the horizontal bar (func_brush) is parented to the little extension above (func_rotating) which spins.
1: using lua with ent:SetParent()
2: using OnPressed>bar>SetParent>spinner in hammer with a button
3: setting the parent in the entity properties in hammer

![image](https://user-images.githubusercontent.com/57368720/116780075-7aecbf80-aa7a-11eb-95b7-956f2d3f287b.png)

Situation 1 and 2 do not collide with the crates **however 3 does.**

Whats behind this and why cant 1 and 2 also behave like 3 ? I understand ofc if this is an engine limitation

Hers a map download (vmf and bsp): https://drive.google.com/file/d/12tSzT4RxIwopzwplbCYS1bmAhU0vhJCR/view?usp=sharing

**Comment by MARK2580** [comment]
@js1251
Usually, from the beginning I will check similar problems on Half-Life 2. If this problem is not there, I start kicking Rubat so that it can fix it)))
In this case, the 2nd test works fine in Half-Life 2, it turns out this is a problem with Gmod, not tools (as noted by rubat). Unfortunately, the Lua version in Half-Life 2 cannot be tested in any way.

**Comment by js1251** [comment]
Interesting! It working in hl2 is great news! Thanks for testing in HL2.
I suspect that the lua functions does something very similar to how parenting is done via mapping I/O so getting the second test to work in gmod might allow it to work with lua too.
Which would be huge imo. There are many situations where parenting would have been the best option but couldnt be used due to the physics not working anymore.

**Comment by MARK2580** [comment]
@js1251 
Just do not forget to check this in hl2 or some similar game, for example, SDK 2013 SP/MP, there are some bugs in these builds.

**Comment by MARK2580** [comment]
Protocol version 17
Exe version 1.0.25.0 (garrysmod)
Exe build: 11:27:17 Jun 30 2011 (4617) (4000)
the second option works the same (gmod 10)  😁

**Comment by robotboy655** [comment]
Apparently it is disabled in GMod's parent on purpose.

**Comment by robotboy655** [comment]
Let's see if this breaks anything. Made `SetParent()` not disable collisions for brush entities.

It was simply doing GetPhysicsObject():EnableCollisions( false ), you can revert it with Lua.

**Comment by js1251** [comment]
Great thanks! Interesting that its diabled like that. Must have been a reason for it at some point.

Parented entities that are not brush entities will still disable their collisions ? 
If its just doing EnableCollisions(false) I will try to revert that manually if thats all that there is to it.

**Comment by robotboy655** [comment]
My guess it is this way because for non brush entities the physics object just falls down to ground, so in order for that to not be a problem for other physics entities it has its collisions disabled.

The way these things work is that the visual mesh follows the physics object's position, not the other way around. It's literally just `Entity:SetAbsPos( PhysObj:GetPos() )` internally, which can't really work when the object is parented.

**Comment by robotboy655** [comment]
You may be able to workaround this by making the physics object into a physics shadow, and move the shadow to the child entity's position.

**Comment by js1251** [comment]
Thanks for the hint that's definitely worth a try.

I might also do some more experiments with parenting behavior.
Expanding it to entities other than non-physics brush entities. Both in gmod and hl2.

If I want to share results should I still share them here even tho this issue is closed?

Is this topic even worth taking a deeper look into or would you say this is done and just how it is. I don't want to bloat the issues more than they already are.
