### ISSUE TITLE
With r_3dsky 0, draw hooks think the skybox is always being drawn

### ISSUE THREAD

**Issue by swampservers** [Facepunch/garrysmod-issues#4936]
### Details
When you are on a map with no skybox, or you have r_3dsky 0 set, Draw hooks like PostDrawOpaqueRenderables always pass skybox=true even though they are drawing the screen

### Steps to reproduce
```
hook.Add("PostDrawOpaqueRenderables","test", function(depth,sky)
    if sky then print("SKY!") end
end)
```
Then run console command `r_3dsky 0` if the map has a skybox and observe that it still thinks the sky is being rendered (it's actually drawing the world)

If there is a skybox on the map, and you're doing `r_3dsky 0`, this only happens in parts of the map where the skybox should be visible. If there is no skybox it happens everywhere.

Pretty annoying for optimizing draw hooks when you are skipping the draw if the sky is being drawn; it skips your intended draw in the world.

**Comment by robotboy655** [comment]
As you might expect it is being called for the 2D skybox. Not much I can really do about it. It will not be always `true` if the skybox is not being rendered.

**Comment by swampservers** [comment]
If you set it to just `print(sky)`, it never prints false. Should have said that initially. I added that check to some PostDrawOpaqueRenderables hooks and then people with the skybox disabled complained about stuff dissapearing.

**Comment by robotboy655** [comment]
Yes, it will never print false as long as the 2D skybox is in your view. The 2D skybox still has to be drawn if the 3D one isn't, and there's no point in drawing the 2D skybox in its own view.

**Comment by swampservers** [comment]
I see, I understand why this happens now. Wouldn't it be more friendly to pass false though? People typically use PostDrawOpaqueRenderables for drawing stuff in the world and this is a weird failure case to need to address. Maybe just redefine the "sky" argument as meaning "3d skybox". Besides isn't PostDraw2DSkyBox more appropriate for drawing things in the 2D sky?

**Comment by robotboy655** [comment]
Added a 3rd argument to Pre/PostDrawTranslucent/OpaqueRenderables - isRendering3DSky

I guess we will try this for the time being. Don't wanna change the default behavior of the 2nd argument to prevent any unexpected problems with existing addons.

The new argument will be true when the 3D skybox view is being rendered. The existing arguments' description was updated on the wiki.
