### ISSUE TITLE
Sprinkle tool replacing all items with same class.

### ISSUE THREAD

**Issue by LennDoMations** [Facepunch/garrysmod-issues#4938]
Sprinkle tool in gmod hammer replaces all props although it should only do it with props placed with the sprinkle tool.

Tested with class prop_static.

**Comment by robotboy655** [comment]
There's physically no way to differentiate between an entity placed with sprinkle tool and an entity that was not. I imagine this is exactly how it works in CS:GO as well, since that's where the tool is from.

**Comment by MARK2580** [comment]
> There's physically no way to differentiate between an entity placed with sprinkle tool and an entity that was not. I imagine this is exactly how it works in CS:GO as well, since that's where the tool is from.

Most likely yes, tk. this tool simply sets prop_static, which has no distinctive properties.

**Comment by JokerR3310** [comment]
Maybe if Model is not in the list of selected Type file, Sprinkle tool should ignore it.
