### ISSUE TITLE
Game crashes on hl2 ep1 first map 

### ISSUE THREAD

**Issue by marigi64** [Facepunch/garrysmod-issues#4946]
on "ep1_citadel_00" the game crashes right after the intro with the chapter title "undue alarm" with no message.

This happens on the dev and x86-64 branches.

here's the crash dump:
https://cdn.discordapp.com/attachments/717209616202727498/841898740938833952/e1bea876-49e3-4dae-b927-63a0b5e6a8e9.dmp

**Comment by robotboy655** [comment]
Fixed on Dev, x86-64 will follow soon.
