### ISSUE TITLE
Disconnect: client left game (steam auth ticket canceled)

### ISSUE THREAD

**Issue by HeroSoul12** [Facepunch/garrysmod-issues#4947]
### Details
Tell us exactly what happens here, every single detail that you can think of.
Please include information such as which Beta Branch your game is on, the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.
Please try running a different(dev)/none beta branch and verifying your game cache integrity before reporting an issue. 

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link. 

My beta branch is in the last one the 84-64 anyway I am tryong to join any server i can with my acc atm because i cant join because of an error i will post picture below if i am able to and it will only give me this error when i am almost done loading in i have tried uninstalling reinstalling gmod logging out logging back in i have also tried to validate files that also wont work so i am just wondering what else I can do to try to fix this i dont know how it started nor how to recreate it otherwise i would be able to figure out what the problem is but idk how to fix it please let me know thank you 
sincerely, HeroSoul

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
If it is a modding API issue, please include minimal code to reproduce the issue on demand.

**Comment by HeroSoul12** [comment]
![image](https://user-images.githubusercontent.com/84101596/118037358-5a065300-b333-11eb-96a3-88033233cb5d.png)

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
