### ISSUE TITLE
Spawnmenu addons folder missing models

### ISSUE THREAD

**Issue by keketiger** [Facepunch/garrysmod-issues#4948]
Hello, i have a problem with my spawn menu in addons folder.
When i click in a workshop addon i can't look at every models inside packs however my friends can see them all.
I cleared my game caches folder but it didn't changed anything at all.
I tried to refresh all icons in menu with right click but same result, nothing changed...

Do have any idea how to solve this issue ?
Thanks in advance.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
