### ISSUE TITLE
Linux server crashing

### ISSUE THREAD

**Issue by Minc3** [Facepunch/garrysmod-issues#4954]
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 13:18:33 Apr 20 2021 (8140) (4000)
GMod version 2021.04.20, branch: unknown
Linux 32bit Dedicated Server
64 BIT BRANCH (X32)
gamemode TTT

Crashing just after game.CleanUpMap is called.
The crashes happen randomly.
My console has nothing in it that would help.

Crash Log:
GDB:
https://pastebin.com/USBgc8dU

**Comment by robotboy655** [comment]
It crashes in vphysics, so that's not very good for fixing the issue, but tell me, how often does this happen when game.CleanUpMap is ran? is it every time or is it uncommon? The stack trace does not indicate game.CleanUpMap is involved. It seems to crash when trying to delete an Entity:Remove()'d SWEP.

**Comment by Minc3** [comment]
> It crashes in vphysics, so that's not very good for fixing the issue, but tell me, how often does this happen when game.CleanUpMap is ran? is it every time or is it uncommon? The stack trace does not indicate game.CleanUpMap is involved. It seems to crash when trying to delete an Entity:Remove()'d SWEP.

I was getting this crash daily but now it seems to only be 2/3 times a week.

Just to be clear, i was saying it happens just after game.cleanup(). It's not crashing while running game.cleanup().

Going off it not crashing while running game.cleanup it's safe to say it not a weapon on the ground.
So most likely a weapon a player still has on them.

So the only solution is to find the weapon(s) that are causing this?

Below code is from terrortown/init.lua:
`local function CleanUp()
   local et = ents.TTT
   -- if we are going to import entities, it's no use replacing HL2DM ones as
   -- soon as they spawn, because they'll be removed anyway
   et.SetReplaceChecking(not et.CanImportEntities(game.GetMap()))

   print("[TTT]: Starting Pre Map Clean Up!")
   et.FixParentedPreCleanup()
   print("[TTT]: Finsihed Pre Map Clean Up!")
   print("[TTT]: Starting Map Clean Up!")
   game.CleanUpMap()
   print("[TTT]: Finsihed Map Clean Up!")
   print("[TTT]: Starting Post Map Clean Up!")
   et.FixParentedPostCleanup()
   print("[TTT]: Finsihed Post Map Clean Up!")

   -- Strip players now, so that their weapons are not seen by ReplaceEntities
   for k,v in ipairs(player.GetAll()) do
      if IsValid(v) then
         v:StripWeapons()
      end
   end

   -- a different kind of cleanup
   hook.Remove("PlayerSay", "ULXMeCheck")
end`

**Comment by robotboy655** [comment]
If that stacktrace is correct, its not `StripWeapons` or `game.CleanUpMap()`. It is specifically `Entity.Remove()` on SWEPs. Yes, there is an actual difference.

You could try detouring that function on your server and printing out a Lua stack trace if its called on SWEPs to see where the entities are being removed just before the crash.
