### ISSUE TITLE
Choppy animation on other players that are transitioning from moving to standing animation.

### ISSUE THREAD

**Issue by DivideAndRule** [Facepunch/garrysmod-issues#4956]
### Details
In multiplayer, when you look at another players animation transitioning from moving -> standing the animation looks choppy/laggy. I have tested this on the latest main and x64 branches on multiple servers and even on a dedicated private one that has zero addons enabled. I confirmed this by asking four other players on different servers to look at me and other players transitioning animation by moving back and forth like seen in the video. Only the animation from moving -> standing seems to be effected. The animation is smooth on yourself when looking at yourself with the camera tool.
Video: https://streamable.com/5fjw4q

### Steps to reproduce
Look at the animations of another player that is transitioning from moving to standing animation.

**Comment by robotboy655** [comment]
Likely related to issues https://github.com/Facepunch/garrysmod-issues/issues/3067 and https://github.com/Facepunch/garrysmod-issues/issues/3322

**Comment by robotboy655** [comment]
Should be fixed on Dev.
