### ISSUE TITLE
Linux - steam overlay doesn't work

### ISSUE THREAD

**Issue by unixquuw** [Facepunch/garrysmod-issues#4961]
### Details
Upon trying to press `shift + tab` gmod doesn't open steam overlay.
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 16:03:34 May 26 2021 (8236) (4000)
GMod version 2021.05.26, branch: x86-64, multicore: 1
Linux 64bit [arch linux]
```
**I do have steam overlay enabled.** I tried to verify the game files, disabling and enabling the steam overlay. Nothing helped.

### Steps to reproduce
Try to press your keybind for the steam overlay.

**Comment by FlorianLeChat** [comment]
The Steam overlay is disabled on your branch: https://github.com/Facepunch/garrysmod-issues/issues/3925#issuecomment-516651044

**Comment by unixquuw** [comment]
But why :disappointed:

**Comment by unixquuw** [comment]
nvm duplicate thanks florian
