### ISSUE TITLE
CreateClientProp(<arg>) with argument makes prop lag 

### ISSUE THREAD

**Issue by alexander-trifonov** [Facepunch/garrysmod-issues#4963]
### Details
Creating clientside prop within a model path in the function's arguments leads to buggy and laggy behavior for the prop upon :SetPos()  
It can be simply fixed by creating the prop without args in  `CreateClientProp` and setting the model later
[Video](https://steamusercontent-a.akamaihd.net/ugc/1765953960104386223/F997DADA614017AD985A5304B215B170783B71FB/
)

### Steps to reproduce
```lua
function SWEP:Initialize()
       self.Ent = ents.CreateClientProp("models/props_c17/FurnitureChair001a.mdl")
...
end

function SWEP:Think()
	if (CLIENT) then
             self.Ent:SetPos(self:GetOwner():GetEyeTrace().HitPos));
	end
end
```

### How to fix
self.Ent = ents.CreateClientProp()
self.Ent:SetModel(<model)

**Comment by robotboy655** [comment]
You probably want to remove the physics objects or otherwise disable physics on the created entity.
