### ISSUE TITLE
point_camera messes with "End Fade Pixels" render position

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-issues#4967]
### Details
If there is an active `point_camera` with `func_monitor` at the level and prop_physics inside camera FOV, then `minpropscreenwidth` are calculated not from the player's position but from the `point_camera` position. which leads to visual problems like this:

![1 — копия](https://user-images.githubusercontent.com/14869831/120907103-934a8e00-c667-11eb-8668-965f33f65a5c.png)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
