### ISSUE TITLE
JSONToTable

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-issues#497]
lua_run PrintTable(util.JSONToTable("{\"test\":[[255,0,0]]}"))

It gives {255,255,0,0,0,0} , that JSON was generated by php json_encode

**Comment by edgarasf123** [comment]
@Acecool You do realize that json use javascript table syntax? [[255,0,0]] is just a 2d table (table inside another table)

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/6197360/ae6f76da-b3ec-11e4-9f72-8f48ffad0812.png)

I think I got it fixed.
