### ISSUE TITLE
64 bit servers unable to be connected to through legacy browser

### ISSUE THREAD

**Issue by Pendred** [Facepunch/garrysmod-issues#4972]
### Details
Servers that are running the x64 branch cannot be connected to via the legacy browser, the playercount is displayed as a -, and connecting prompts you that the server is full. You can still connect through console commands, and using the main server browser, it's also been reported that trying to join through a friends "view server info" doesn't work either. See images below. I was running x64 at the time tested.

https://imgur.com/KCwDZwY
https://imgur.com/lB0adza

### Steps to reproduce
All relevant information is above.

**Comment by tochnonement** [comment]
The problem is with slot count, decrease it to 127, it happened cause of steam client's update
![gmod_mQ5SLtkxpp](https://user-images.githubusercontent.com/48033052/121163508-87bdb980-c857-11eb-86a1-e411c6889df9.png)

**Comment by robotboy655** [comment]
Yeah it's an issue with Steam, wait for an update that fixes this.
