### ISSUE TITLE
window.DownloadingFile in loading screen became useless

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#4975]
### Details
Loading screen calls lua func **PANEL:StatusChanged** and run js func **window.DownloadingFile**.
`local startPos, endPos = string.find( strStatus, "Downloading " )`

After the last update, the lines look different and the function does not parse them.
`1/62 - path/filename/file.ext is downloading`
`1/62 (35.3 KB) - path/filename/file.ext is downloading`

However, the new information is much more useful than just the bare filename. I propose to either remake the function call to be called from the engine (so that it is not necessary to parse strings) or completely remove **window.DownloadingFile**.

### Original code from `loading.lua`
```
function PANEL:StatusChanged( strStatus )

	local startPos, endPos = string.find( strStatus, "Downloading " )
	if ( startPos ) then
		-- Snip everything before the Download part
		strStatus = string.sub( strStatus, startPos )

		-- Special case needed for workshop, snip the "' via Workshop" part
		if ( string.EndsWith( strStatus, "via Workshop" ) ) then
			strStatus = string.gsub( strStatus, "' via Workshop", "" )
			strStatus = string.gsub( strStatus, "Downloading '", "" ) -- We need to handle the quote marks
		end

		local Filename = string.gsub( strStatus, "Downloading ", "" )

		self:RunJavascript( "if ( window.DownloadingFile ) DownloadingFile( '" .. Filename:JavascriptSafe() .. "' )" )

		return

	end

	self:RunJavascript( "if ( window.SetStatusChanged ) SetStatusChanged( '" .. strStatus:JavascriptSafe() .. "' )" )

end
```

**Comment by robotboy655** [comment]
Fixed `DownloadingFile` not being called for FastDL/ServerDL downloads.

`SetStatusChanged` is still called for `1/62 (35.3 KB) - path/filename/file.ext is downloading` statuses (unless there's a download error, don't quite me on that though). Workshop downloads also have other `SetStatusChanged ` calls during their download process.
