### ISSUE TITLE
game.MountGMA unmounts content on the listen server host when changing levels

### ISSUE THREAD

**Issue by Foohy** [Facepunch/garrysmod-issues#4977]
### Details

Previous to the latest gmod update (2021.06.09), executing game.MountGMA() on the server realm (both dedicated and listen servers), will keep that content mounted on map transition, which is useful for a server to pre-load maps before changing to them dynamically. This behavior has been broken on listen servers, where even if game.MountGMA() is called on the server realm, the listen server host will unmount it on map transition. 

(This is unrelated to *clients* unmounting GMAs, which I see was a purposeful change. While that has raised other issues, I've created a separate feature request here to address them: #Facepunch/garrysmod-requests/issues/1838 ) 

### Steps to reproduce
In order to reproduce, you'll need the gma of an addon currently hosted on workshop. I've attached a script that will automatically download and mount it on the server for you, and what the following console command will requires.

1. Install "sv_mountgma_repro.lua" into `garrysmod/lua/autorun/server/`
2. Start a new Sandbox listen server (so player count > 2. I'm not bothering with singleplayer games).
3. `lua_run mountgma_repro.DownloadAndInstallGMA(104793138)`, which is the workshopid for [gm_supersizeroom_v2](https://steamcommunity.com/sharedfiles/filedetails/?id=104793138). Make sure you aren't already subscribed, we don't want it to be already mounted.
4. When the content downloads and mounts on the server, execute `changelevel gm_supersizeroom_v2`
5. Client realm unmounts server-mounted content, level transition fails and you're bumped back into the main menu.

![image](https://user-images.githubusercontent.com/1835056/121790186-a1ca0580-cb91-11eb-8bd3-46c83c4e9f78.png)
sv_mountgma_repro.lua: https://pastebin.com/Ke3JdiTy (and also attached as a .zip file) [sv_mountgma_repro.zip](https://github.com/Facepunch/garrysmod-issues/files/6642963/sv_mountgma_repro.zip)

**Comment by robotboy655** [comment]
As far as I am concerned this is intentional. If you want a map to be available to be played, you either subscribe to it, or put it into dedicated server's collection.

**Comment by Foohy** [comment]
On dedicated servers it doesn't unmount. Is that intentional too, or will that eventually become parity with listen server behavior?

Apologies for keeping this chain going and pestering, but I've got a whole gamemode built around this feature with no (feasible) workaround. Subscribing to the entirety of workshop is not an option, and asking users to host a dedicated server isn't either (assuming that behavior isn't changing too).

**Comment by robotboy655** [comment]
You don't subscribe to the whole of workshop, just the maps you want to play on, which should be fairly obvious, it works like that with the rest of the game since day 1 of workshop support.

As for dedicated servers, there isn't any point in unmounting content on it. The point of doing this on clients is to unload content 
 from servers when switching servers or going to singleplayer. Unfortunately there isn't really a good way to distinguish if a client a local server host and doing this on disconnect only is also unfortunately not an option.

I will see what I can do about this for you, but can't promise anything.

**Comment by Foohy** [comment]
I do really appreciate that -- it goes without saying that in any other situation unmounting those other cases makes total sense here, but the behavior turned out to be extraordinarily useful when you don't know ahead of time what maps you'll want to play (And "all of workshop" was just me exaggerating, but subscribing to "all of workshop's map category" would be more accurate :) ). 

Even if there's a bit of song and dance to get equivalent functionality back, I think it'll go a long way. It might make sense that the client keeps content mounted through Host_Changelevel events explicitly? Since that's what the server's doing anyway. 

Again, thanks for your time here, I appreciate it a lot.

**Comment by robotboy655** [comment]
I have done some changes on Dev beta, it should work for you even though it's really just incorrect behavior.

**Comment by Foohy** [comment]
Just tested, it works perfectly! You've been extremely helpful here, thank you very much. Is there anything I should plan around with the latest changes?
