### ISSUE TITLE
Propdrive bugs when two players are involved

### ISSUE THREAD

**Issue by thebubster** [Facepunch/garrysmod-issues#4978]
### Details
When prop driving with two players and deleting a prop you can bug a player until server rejoin with weird side effects such as third person but behind the head and up close and "spectating random entities once a player spawns a prop (probably some value being overwritten like a prop from one player replacing anothers deleted prop)

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link.

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
Owner of prop (player 1) spawns prop 

player 2 (bugged person) drives prop

player 1 also drives prop

player 1 deletes prop

player 2 is now bugged until rejoin or map change

**Comment by robotboy655** [comment]
This should be fixed on Dev beta and in future game update. (By disallowing driving entities that are already being driven)
