### ISSUE TITLE
Hogwarts servers crashing (not only mine...)

### ISSUE THREAD

**Issue by Alexx03** [Facepunch/garrysmod-issues#4981]
Hello, I'm just gonna repost what I've sended on the facepunch support which only tell me that's it's the problem of the different servers or that i need to come here...

As an owner of a French community which is based on Hogwarts, since the last update of Gmod,
I've seen problems. In fact, with many other communities based on the same gamemode, we are seeing many crashes.
Since the last update, for no reason, our servers keep crashing at different moments of the day.
We've made an investigation on client side & server side errors, checking every net and nothing can be seen on it.
We are really aware about this problem because even by trying to optimize as much as we can our servers, nothing can be seen from our perspective.
Since you've fixed the M9K problem in 20minutes after the release of this update, I really hope that you could also fix our problem.

Have a good day,
Best regards.

Hello,
Since the last message I sended you about the crashes I found this on Github (which is really nice btw) : https://github.com/Thomasims/GCrash

Thanks to it i can detect the crash, make the server restart alone (without humain action).
Here is what it logs if you can make something about it....

Seg fault occured.

Main Lua stack:

Lua crash handler:

/gcrash.lua:27 in anonymous function() <27-46>

Lua crash handler:

Frame #0:
write = function: 0xe46d4450

**Comment by robotboy655** [comment]
I cannot do anything without at least a stack trace of the crash.

https://wiki.facepunch.com/gmod/Crash_Reporting

**Comment by Alexx03** [comment]
Even with gcrash, I have no crashlog or anything ...

**Comment by Comminux** [comment]
What OS is using on the host?

**Comment by robotboy655** [comment]
Are you sure it's a crash and not a hang/freeze?

**Comment by Alexx03** [comment]
We are on Debian 9, and yeah it's more likely a hang/freeze which completly freeze the user and prevent me from doing any action.
I need to kill the process to get through it (or now with gcrash it will restart automatically)

**Comment by Comminux** [comment]
Do you use ulx and ulib?

**Comment by Alexx03** [comment]
The other big community that have the same freeze doesn't have it. They use SAM but we both have the same problem.
We spent 4 days working on every addons that we had in common but there were nothing in it...

**Comment by robotboy655** [comment]
So it's an infinite loop somewhere, either in your Lua code or in C++. Either way you will need to generate a core dump ( https://sourceware.org/gdb/onlinedocs/gdb/Core-File-Generation.html ) and send it to my email so it can be debugged.

**Comment by Alexx03** [comment]
The fact is that we had no problem before the last update which broke many things (even M9K that you've fixed).
Even by checking every addons that we have in common we cannot find anything suspicious...
Gonna try this at least...

**Comment by FlorianLeChat** [comment]
> The fact is that we had no problem before the last update which broke many things (even M9K that you've fixed).

That's why there is a pre-release phase where modders and **server owners** can test the changes (especially for servers with a large number of players). An update may break some things but only with testers of all kinds this can be limited. 👍

**Comment by Alexx03** [comment]
That's why it's only working with aserver a full load
