### ISSUE TITLE
Holster crash

### ISSUE THREAD

**Issue by michak89** [Facepunch/garrysmod-issues#4982]
Hello,

1. Spawn npc_metropolice. 
2. npc_metropolice:Give('weapon_frag')
3. npc_metropolice:Give('weapon_357') // or any other weapon. 

Crashdump:  https://pastebin.com/JXVrfeH5

No matter if it's a dedicated server or a singleplayer game, works also with other npcs. 
Looks like a problem with granade switch animation. 

I found it with this addon: https://steamcommunity.com/sharedfiles/filedetails/?id=104607712
It allows me to change npc weapon in context menu, with the same result. 

Client: version: 2021.06.09, normal branch, Windows. 
Server version 2021.06.09, x86, Debian. 

Have a nice day!

**Comment by robotboy655** [comment]
It's already fixed last week, update your server.
