### ISSUE TITLE
Setting both Parent and MoveParent freezes game

### ISSUE THREAD

**Issue by danx91** [Facepunch/garrysmod-issues#4983]
### Details
Setting both _SetParent_ and _SetMoveParent_ to **the same entity** on single entity causes the game to freeze. I discovered this by accidentally setting MoveParent to an entity that already had Parent. I tested it on sandbox without any addons (it also occurs on other gamemodes). I tested several different models and types of entity.

Yes, I know this issue is stupid and can be easily avoided, but I think it's still worth reporting.

Branch: standard
OS: Windows 10

### Steps to reproduce
Run the following code:

```
local ent = ents.Create( "base_anim" ) --tested with few other types of entity
ent:SetModel( "models/props_junk/PopCan01a.mdl" ) --tested with other models

ent:SetParent( Entity( 1 ) )
ent:SetMoveParent( Entity( 1 ) ) --at this moment game hangs
```

**Comment by robotboy655** [comment]
Should be fixed on Dev beta.
