### ISSUE TITLE
Server Console sometimes spamming "[UH-OH!] Invalid HitboxSet on something."

### ISSUE THREAD

**Issue by nerzlakai96** [Facepunch/garrysmod-issues#4985]
Dear Garry's Mod community,
since a few weeks, a get my server console sometimes spammed with the message from above "[UH-OH!] Invalid HitboxSet on something.". It happens after a certain event or interaction with an entity or something. As this message doesn't point to an entity which might cause it makes it really difficult to find the mistake there.

Any help appreciated :)

Thanks in advance and kind regards,
nerzlakai96

**Comment by robotboy655** [comment]
Added some info to the message on Dev beta:
```
[UH-OH!] Invalid HitboxSet 22 of 1 on model player/group01/male_07.mdl.
```
Not much else to do here. Something is trying to access a hitbox set out of bounds.

**Comment by nerzlakai96** [comment]
So does it mean that this function is responsible for this error message or can it have more possible reasons:
https://wiki.facepunch.com/gmod/Entity:SetHitboxSet

**Comment by robotboy655** [comment]
I believe Lua functions have internal safeguards against this, but you can try it and see for yourself.
