### ISSUE TITLE
PLAYER:EyePos bad behavior when you getting into vehicle

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4986]
### Details
When the camera animation plays after you have started getting into vehicle, server side function `PLAYER:EyePos` returns position that goes from vector_center to actual eye position. This causes issues with PVS, so you cannot see entities near vehicle if you cannot see vehicle from map center because of PVS.

I tested it on dev branch, but I notice that problem month ago on dev branch, so maybe last update broke default behavior.
Also, I disabled all addons to make sure it is not addon problem.

https://www.youtube.com/watch?v=J6D14Gd56lw

### Steps to reproduce
You can go to place with mirror entity on gm_construct, create vehicle (for example, chair) and sit into it, and look at mirror, it should disappear for second while you getting into vehicle.

**Comment by robotboy655** [comment]
Should be fixed on Dev.
