### ISSUE TITLE
Net messages not discarded by reconnect

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#4987]
### Details
If you call `net.Start` with pooled name and reconnect to server you got
`Warning! A net message (gman.sw.vtx) is already started! Discarding in favor of the new message! (myName)`

**gman.sw.vtx** is trash. There may be a random model name, it seems to be just a random network string.
I expect that started network message will be discarded when reconnecting or changing the map.

### Steps to reproduce
```
SV
util.AddNetworkString("myName")

CL
net.Start("myName")

reconnect to server
```

**Comment by robotboy655** [comment]
Should be fixed on Dev.
