### ISSUE TITLE
util.Decompress crash with multiline args contains utf-8

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-issues#4990]
### Details
main branch

Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 18:09:33 Jun  2 2021 (8243) (4000)
GMod version 2021.06.09, branch: unknown, multicore: 0
Windows 32bit

### Steps to reproduce
lua_run util.Decompress[[рубат почини\n\n\n]]

**Comment by klen-list** [comment]
For some reason, this may not work for others, so I'll leave my crash dump
https://dropmefiles.com/dmmvw

**Comment by CornerPin** [comment]
It only happens to me when I join the game a second time.

**Comment by thegrb93** [comment]
I couldn't reproduce it in the main branch, but I could in x86-64 branch

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/124486736-c1081d00-dd62-11eb-9990-3a7981825023.png)

Cannot confirm on either version of the game.

**Comment by CornerPin** [comment]
Have you tried to rejoin the game?

**Comment by robotboy655** [comment]
What in the flying heck

**Comment by meepen** [comment]
It crashed on first run for me, I believe it's just creating a giant chunk
of memory and falling, then trying to free it

**Comment by robotboy655** [comment]
It's not as simple as that as far as I can tell, but I don't see what the cause is. It has something to do with Source's memory management, but I don't know why it happens. So it's kinda fixed, as in the code above will not crash, but this might reappear in the future.
