### ISSUE TITLE
Panel:DoModal() breaks child DComboBoxes

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4991]
### Details
`Panel:DoModal()` breaks child DComboBoxes. The child DComboBox will open correctly when clicked, but it is impossible to select any of the options.

### Steps to reproduce
1. Create a panel.
2. Create a DComboBox in the panel.
3. Call `DoModal()` on the panel.
4. Try to change the combo box selection and fail.

### Environment
x86-64 2021.06.09

**Comment by robotboy655** [comment]
Should be fixed on Dev.
