### ISSUE TITLE
$frame and $frame2 material parameters crash if index is invalid

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4993]
Material shader parameters $frame and $frame2 crash if index not valid.

**Comment by robotboy655** [comment]
Do you have something to reproduce this with? I tried setting `$frame` in `models/XQM/LightLinesRed`'s .vmt (without the matproxy naturally) as well as using the code below and nothing happened.

```
local wave = Material( "models/XQM/LightLinesRed" )
print( wave )
print( wave:SetInt( "$frame", 99999999 ) ) 
print( wave:GetInt( "$frame") ) 
```

**Comment by thegrb93** [comment]
@robotboy655 It's a user created UnlitGeneric happens very easily with a starfall chip someone attempted.

```lua
--@client
local tx = render.createMaterial("https://dl.dropboxusercontent.com/s/8b3s1olby7imxy3/yoshi.gif")
local c = 1
hook.add("render", "main", function()
    c = (c % 10) + 1
    render.setMaterial(tx)
    tx:setInt("$frame", c) -- This wouldn't work anyway because we don't decode gif into frames but this discovered the crash
    render.drawTexturedRect(0,0,512,512)
end)
```

**Comment by thegrb93** [comment]
I imagine all you need for it in GLua is CreateMaterial and in a `ENT:Draw` set the $frame flag.

**Comment by thegrb93** [comment]
Maybe the $basetexture needs to be set to a rendertarget

**Comment by thegrb93** [comment]
I found it's when the $basetexture is set to a rendertarget. The material also has to draw.

Here's a simple starfall snippet
```lua
--@client

render.createRenderTarget("F")
local tx = material.create("UnlitGeneric")
tx:setTextureRenderTarget("$basetexture", "F")
tx:setInt("$frame", 1000)

hook.add("render", "", function()
    render.setMaterial(tx)
    render.drawTexturedRect(0,0,512,512)
end)
```

**Comment by robotboy655** [comment]
Should be fixed.
