### ISSUE TITLE
TTT Autokick bug

### ISSUE THREAD

**Issue by MyDimeIsUp** [Facepunch/garrysmod-issues#4996]
Updated our x64 GMod server and the latest TTT autokick evasion doesn't work.

https://github.com/Facepunch/garrysmod/pull/1803

```
[ERROR] gamemodes/terrortown/gamemode/init.lua:652: attempt to call field 'CheckAutoKickAll' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/init.lua:652

Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/init.lua (line 490)]
```

I'm too busy rn to figure out why this is happening, so I'm just reporting here. I commented out 652 for the time being.

**Comment by robotboy655** [comment]
Sounds like your gamemode is out of date, or some file is being overwritten by addon or something, but either way, please do not report TTT issues here.

Contact @svdm for any TTT issues.
