### ISSUE TITLE
Entity:SetColor with SetColor4Part present without an argument no longer clear color

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#4997]
### Details
![browser_H4wnzbSiRA](https://user-images.githubusercontent.com/6339511/124064771-a894bb80-da5f-11eb-86da-02cee52a9764.png)

[everyone's addons with SetColor4Part present right now](https://media.discordapp.net/attachments/519463352125227010/827989003109924904/106.mp4)

```lua
local SetColorOriginal4 = meta.SetColor4Part
local SetColorOriginal = meta.SetColor
function meta:SetColor( col )

	-- Backwards comp slower method
	if ( !SetColorOriginal4 ) then
		return SetColorOriginal( self, col )
	end

	SetColorOriginal4( self, col.r, col.g, col.b, col.a )

end
```

??? ???

**Comment by DBotThePony** [comment]
~~make github gmod repo always match game's Lua code~~
~~rubat pls fix~~

**Comment by robotboy655** [comment]
Another unintentional "feature" shows up...

**Comment by robotboy655** [comment]
Should be fixed.
