### ISSUE TITLE
DTreeNode lua error

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4998]
https://github.com/Facepunch/garrysmod/commit/6173cd5961712b64a220d40e4873e96e29012858#diff-b4cd4a7c387602ed950803e21daac4bf23f7ff7df03232a912609fdc90a18bf9

Seems to be causing an error. I'm having trouble understanding it myself

[ERROR] lua/vgui/dtree_node.lua:519: attempt to index field 'ChildNodes' (a nil value)
  1. PopulateChildren - lua/vgui/dtree_node.lua:519
   2. PopulateChildrenAndSelf - lua/vgui/dtree_node.lua:536
    3. unknown - lua/vgui/dtree_node.lua:432

Timer Failed! [Simple][@lua/vgui/dtree_node.lua (line 430)]

https://github.com/wiremod/wire/issues/2189

**Comment by robotboy655** [comment]
Should be fixed on Dev.
