### ISSUE TITLE
Garry's Mod x86_64 is crashing (windows 10)

### ISSUE THREAD

**Issue by Ogg100** [Facepunch/garrysmod-issues#5003]
I don't know what's changed but all of a sudden my gmod is crashing quite frequently.
The crashes seem to be random.

branch: x86_64 beta
mcore enabled: gmod_mcore_test 1

[crashes.zip](https://github.com/Facepunch/garrysmod-issues/files/6780604/crashes.zip)

**Comment by robotboy655** [comment]
Switch to `dev` beta branch and tell me if crashes are fixed or not.

**Comment by Ogg100** [comment]
After playing for about 8 hours over the weekend i haven't crashed on the dev build.
So i'll be leaving it on dev until the x86-64 build gets an update.
