### ISSUE TITLE
server browser issue

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-issues#5004]
hello,  i am a player from China
after last update of gmod
all of the Chinese players can not see CN servers in server browser
can only use "add ip to favorite" to see the server

**Comment by wackod** [comment]
i ask a lot of my friends  they all have this issue    they can not see a full CN server list      for example  there are 4 darkrp servers   but  we can only see 1 or 2 of them and different people can see different servers   but no one can see a full list  ,and we are sure the servers are all opened     before this update   everything is normal

**Comment by wackod** [comment]
and servers are not blacklisted
and all have STEAM GSLT

**Comment by robotboy655** [comment]
The server's in game are directly what Steam gives the game. You can check it yourself with Steam's built-in server browser.

![image](https://user-images.githubusercontent.com/3299036/124965354-e43b0280-dfd6-11eb-9eaa-5ec2fd13efbf.png)

**Comment by wackod** [comment]
i have notice that Steam's built-in server browser have no full list too ,  Do some server settings affect this?

**Comment by wackod** [comment]
It's strange that some people can see the same server, but some people can't, but it's normal after adding to the favorites

**Comment by wackod** [comment]
and i got this
