### ISSUE TITLE
Team Fortress 2 Ragdolls broke with latest Garry's Mod updates

### ISSUE THREAD

**Issue by TyrakatheDragonFan** [Facepunch/garrysmod-issues#5005]
Ever since the last update in June, something odd has happened to the ragdolls of the TF2 Mercenaries that has left them broken and unusable: 

![gm_flatgrass00045](https://user-images.githubusercontent.com/77705209/124979627-e7df8100-dff8-11eb-9b65-fb8611f7de82.jpg)

The meshes of the models appears to have dropped in number (best seen in the hands and feet), and both the face and fingerposer tools to don't work; no matter what combination of flexes and bone movement, they remain stationary. Even using the Advanced Bone Tool doesn't work. And it is impossible to bonemerge objects to them without them all ending up at either the feet or above the head.

The closest thing I can describe it to is if they are permanently out of range of the r_lod effect, no matter what it's set to. And yes, I have removed any and all addon/workshop files relating to the TF2 Merces from my game in my attempts to fix these (even they have the same issues as the game ones). I even uninstalled/reinstalled both Gmod and TF2, to no avail.

Is anyone else having this issue, or is it just me? If yes, then is there a fix to be seen soon? And if no, then does anyone have any idea what could be causing this on my end? Please answer soon, as I need them back in working order to continue my webcomic series.

**Comment by robotboy655** [comment]
It's your in-game model quality setting.

**Comment by TyrakatheDragonFan** [comment]
...now I just feel stupid.

Thanks, I guess.
