### ISSUE TITLE
HUDShouldDraw actually does not hide CHudMenu

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-issues#5006]
### Details
working at main and dev

### Steps to reproduce
hook.Add("HUDShouldDraw", "HideMenu", function(name)
	if name == "CHudMenu" then print"CHudMenu exist" return false end
end)

**Comment by thegrb93** [comment]
You're sure you don't have another hook somewhere returning true?

**Comment by DeffOS** [comment]
Even overriding GM:HUDShouldDraw() to always return false will fail Menu hiding

**Comment by FlorianLeChat** [comment]
Yes because hooks will be called **BEFORE** gamemode calls.

**Comment by robotboy655** [comment]
CHudMenu is not the main menu like the wiki states (corrected), it's the CSS/HL2 DM left 1,2,3,4,5,6,etc menu that many mods there use.
