### ISSUE TITLE
Game crashes when removing _firesmoke entities with stopped particle emission.

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#5009]
### Details
lua_run ents.FindByClass(„_firesmoke“)[1]: StopParticleEmission()
For stopping the particle emission of a env_fire entity can crash the game, if clean upped.

Tested on 64 bit, mcore enabled.

### Steps to reproduce
> Create an env_fire
> lua_run ents.FindByClass("_firesmoke")[1]: StopParticles()
> Clean map

Crash dumps sent to rubats mail, sorry for the 3 mails lol

**Comment by robotboy655** [comment]
Wasn't a consistent reproduction case, but it crashed often enough that I think it should be fixed now on `dev` beta, x86-64 will follow soon.
