### ISSUE TITLE
Clients forced to download non-existent mapname.ain files from Servers

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#501]
If the mapname.ain doesn't exist on the server for the current map and the client doesn't have it either, 
the client will be delayed into downloading it, which then skips a few seconds later.

This is an old issue, I'd like to see fixed.

**Comment by robotboy655** [comment]
Is this still a problem? I couldn't make it download any fake .ain files, when connecting to a local srcds and deleting the files before starting the srcds and the client.

The file seems to be automatically regenerated when I join the server, not downloaded.

**Comment by Kefta** [comment]
Yes, with FastDL, the client will attempt to download the map and graph (ain) file, even if the ain isn't on the FastDL server

**Comment by robotboy655** [comment]
So its only with FastDL? It doesn't happen with serverdl?

**Comment by Kefta** [comment]
I personally haven't tested with ServerDL, but I will try.

**Comment by robotboy655** [comment]
This seems to be a problem on the FastDL configuration rather than anything else.

```.ain``` files are automatically generated by the server for every map it runs, and it is automatically added for download just like the ```.bsp``` is. The game server obviously has no clue if the file exists on the FastDL.

**Comment by Kefta** [comment]
Could https://github.com/Facepunch/garrysmod-requests/issues/508 be looked into?

**Comment by besenyei** [comment]
This still happens, here's steps I believe will replicate it.

Host a dedicated server (in my test I have a dedicated server on the same computer).
Join that server.
Change level to a map that doesn't have a <mapname>.ain in the maps/graphs folder (for both server/client).
After that map has loaded, disconnect, and reconnect to the server.
Your client is forced to download a <mapname>.ain for the current map.

I don't even have a fastdl for my local srcds and I have set sv_allowdownload to 0.

**Comment by besenyei** [comment]
Even if you have sv_allowdownload 0, the .ain files still download.

**Comment by besenyei** [comment]
Clients seem to request downloads for <mapname>.ain, even if the server has sv_allowdownload 0 and no fastdl.

I've believe the issue occurs when the server is started, has sv_allowdownload 0 in server.cfg and you join it. If it doesn't happen for the current map, it should on the next, as long as you don't have the .ain on the client.

**Comment by besenyei** [comment]
https://forum.facepunch.com/f/gmoddev/btjva/Avoid-sending-graph-files-to-the-client/1/
