### ISSUE TITLE
Setting water detail to Simple reflections or Reflect world doesn't work and keeps Reflect all

### ISSUE THREAD

**Issue by Yetoo1** [Facepunch/garrysmod-issues#5015]
### Details
Setting water detail to Simple reflections or Reflect world doesn't work and still Reflects all. I have restarted the game, disabled all addons, and verified cache and this issue still occurs.

Screenshot:
![20210724070434_1](https://user-images.githubusercontent.com/12403440/126871270-9edb0119-e44b-400a-85ac-8b568d7627a6.jpg)

### Steps to reproduce
1. Start game
2. Go into advanced video settings and set water reflections to be anything other than Reflect all
3. Press Ok/Apply so that the settings apply
4. Feast

Gmod version:
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 14:40:17 Jul 12 2021 (8283) (4000)
GMod version 2021.07.12, branch: unknown, multicore: 0
Windows 32bit

System info:
https://pastebin.com/HWK9HE22

**Comment by robotboy655** [comment]
The water on gm_construct forces itself to be expensive and to always render the entity reflections. It will not be the same on maps that do not this.

![image](https://user-images.githubusercontent.com/3299036/126990283-40e52b9e-bd85-4882-860f-cb2e7d4e0664.png)
This is what it would look like if it did not force itself expensive.

I do not see any point in "fixing" this for `gm_construct`.
