### ISSUE TITLE
Sandbox Server Crash

### ISSUE THREAD

**Issue by costin88boss** [Facepunch/garrysmod-issues#5016]
### Details
So I own a Sandbox GMod server and I don't know why or how, but it crashed. i wasn't in the game, so I don't know what was going on, and the ULX Logs didn't log anything about the crash.

I however have the crash dump here (first time attaching smth so hope it works): [srcds_crash_2021_7_25T13_52_50C0.zip](https://github.com/Facepunch/garrysmod-issues/files/6874121/srcds_crash_2021_7_25T13_52_50C0.zip)

There is no such "beta branch" on my server. and I can't give any console information.

Also I did create a permanent attachment link above. (I hope I did not screw it up cuz I'm new)

### Steps to reproduce
As I said, it's a server and I wasn't on it, but I'm very sure someone lagged the server and it crashed, Idk how he did that because Duplicator was restricted..

**Comment by robotboy655** [comment]
It's an npc_fastzombie crash that was fixed in July update. Update your server.

https://steamcommunity.com/games/garrysmod/announcements/detail/2961661843692383386
