### ISSUE TITLE
Some bug with WAC aircraft.

### ISSUE THREAD

**Issue by Kagoule** [Facepunch/garrysmod-issues#5019]
Crazy angular velocity on entity [147][wac_hitdetector]
	Origin:           [-651.821472, -96.437408, 515.365295]
	Angles:           [-1.551870, 4.638813, 0.801119]
	Velocity:         [-4422.117676, 1313.887451, 824.294312]
	Angular Velocity: [6503.087402, 6236.456543, 296755.125000]
Defusing!
Removing!
I tried "sv_crazyphysics_remove 0", "sv_crazyphysics_defuse 0", and anything like tha didn't work, I just need somebody to help me with that, please.
![unknown (1)](https://user-images.githubusercontent.com/88163238/127556055-418f0794-58bd-4547-b8d5-268cc3e94b96.png)

**Comment by FlorianLeChat** [comment]
I think you should find help on the [official Discord](https://discord.gg/gmod) than here.

**Comment by Kagoule** [comment]
> I think you should find help on the [official Discord](https://discord.gg/gmod) than here.

Alright.
