### ISSUE TITLE
Fonts stay in memory until game is closed and re-launched ( Users/Bad Coding complains of crashes ).

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#502]
I did a few tests with surface.CreateFont. It involved creating them, modifying the server and rejoining without the fonts being created again on join. It also involved closing the server, rejoining without the fonts being recreated.

Fonts created using surface.CreateFont are not purged on Disconnect or on GM:ShutDown( ).

I've seen a few people complaining about fonts causing them issues / crashing ( They said usually when they leave their server and join another ). I tried creating fonts over 1 million times times 3 fonts but had no luck in crashing. I did have luck though in proving that the fonts stay in memory

Pretty simple, please purge fonts on disconnect or when GM:ShutDown is called!.

**Comment by robotboy655** [comment]
Covered by https://github.com/Facepunch/garrysmod-issues/issues/3465
