### ISSUE TITLE
StopLoopingSound() ignores even-numbered looping sounds

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#5025]
### Summary
`StopLoopingSound()` does not work if the same soundscript is playing multiple times. If multiple looping instances of a soundscript are currently playing, `StopLoopingSound()` ignores the even-numbered instances.

### Steps to reproduce
1. Use `StartLoopingSound()` 4 times to start playing 4 instances of the same soundscript. Save the looping playback instance IDs.
2. Listen and verify that all 4 are playing.
3. Use `StopLoopingSound()` on the 4 looping playback instance IDs **while all 4 are still playing**.
4. Only instances 1 and 3 will stop. Instances 2 and 4 will continues to play.
5. Repeat with 2, 3, 5, etc simultaneously playing sounds and observe the same pattern.

### Environment
2021.07.12

**Comment by robotboy655** [comment]
Should be fixed on 'dev' beta.
