### ISSUE TITLE
Error message in the material file does not display the material

### ISSUE THREAD

**Issue by JarosLucky** [Facepunch/garrysmod-issues#5026]
### Details
If there is an error in the material, then when parsing the .vmt file we get a message in the console about some incorrectly set texture parameter, and supposedly it should display the name of the material itself, but it repeats the name of the parameter where the error was made.

Like that:
`Error in .VMT file: error parsing vector element "$AmbientOcclColor" in "$AmbientOcclColor"`
![image](https://user-images.githubusercontent.com/19414192/128873170-e748741b-9cb8-49f4-850f-5c37e3c6479a.png)

I use x86-64 banch 2021.08.09

### Steps to reproduce
Have any used material with incorrectly set data in any material. Optionally perform a reload of the material(s)

**Comment by robotboy655** [comment]
Should be working correctly on 'dev' beta.

**Comment by JarosLucky** [comment]
Warning in .VMT file ($envmaptint): no ']' or '}' found in vector key "$envmaptint".
Error in .VMT file: error parsing vector element "$envmaptint" in "$envmaptint"

Similar problem in compile tools

**Comment by robotboy655** [comment]
They should be also fixed, it should be the same code. Let me know if that is not the case, but yeah. If you are using 3rd party stuff, it obviously won't have the fix.

**Comment by JarosLucky** [comment]
Thanks you ❤️

ср, 11 авг. 2021 г., 01:29 Rubat ***@***.***>:
