### ISSUE TITLE
GetBloodColor on client

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-issues#5030]
While trying to implement the bleeding effect ("BloodImpact") from the predicted function PrimaryAttack, I encountered the fact that the GetBloodColor function is not present on the client, although the blood indices are shared. Most likely this is a network variable and should be available on the client. Sorry for bad English.

```lua
local bc = ent:GetBloodColor()

if bc != DONT_BLEED then
	local effectdata = EffectData()
	effectdata:SetOrigin(tr.HitPos + tr.HitNormal)
	effectdata:SetNormal(tr.HitNormal)
	effectdata:SetColor(bc)

	util.Effect("BloodImpact", effectdata)
end
```

https://wiki.facepunch.com/gmod/Entity:GetBloodColor
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/fx_blood.cpp
https://wiki.facepunch.com/gmod/Enums/BLOOD_COLOR

**Comment by robotboy655** [comment]
Made it shared.
