### ISSUE TITLE
VortWrap shader crash

### ISSUE THREAD

**Issue by Anneke-Aardwolf** [Facepunch/garrysmod-issues#5032]
### Details
VortWrap shader causes game crash when underwater or in contact with water (VMT material)
both version below has this problem:

1.
(Default gmod: no beta)

Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 14:40:17 Jul 12 2021 (8283) (4000)
GMod version 2021.07.12, branch: unknown, multicore: 0
Windows 32bit

crashes silently without error (silently)

2.
(beta: x86-64 - Chromium + 64-bit binaries)

Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 10:34:03 Jul  6 2021 (8277) (4000)
GMod version 2021.08.09, branch: x86-64, multicore: 1
Windows 64bit

crashes with this error message:

Engine Error
!!!!!!Using invalid shader combo!!!!!! Consult a programmer and tell them to build debug materialsystem.dll and stdshader*.dll. Run with 'mat_bufferprimitives 0' and look for CMaterial in the call stack and see what m_pDebugName is. You are likely using a shader combo that has been skipped.

### Steps to reproduce
make material with VortWrap shader, using ANY texture, as example:

"VortWarp"
{
	"$baseTexture" "models\things\bar\liquids\choco"
    "$warpparam" "1"
}

or

"VortWarp"
{
	"$baseTexture" "models\things\bar\liquids\choco"
	$flowmap	shadertest/cloud
	"$bumpmap"		"models\bar_things\glass_normal"
	$selfillummap	shadertest/lump

    $selfillummap "models\things\bar\liquids\choco"
    $selfillumtint    "{ 45 45 45 }"

    $warpparam    1
}

then put prop \ npc \ thing with this material underwater and it will cause crash

im using this shader in modding to make props and equipment:
-animated coffee in cup
-visor glasses

**Comment by LoveRenamon** [comment]
I would recomend use VertexLitGeneric shader with [EmissiveBlend](https://developer.valvesoftware.com/wiki/$emissiveblend) as workaround since it have same behaviour, and I don't think Facepunch made some changes in the game shaders.

**Comment by robotboy655** [comment]
The crash should be fixed.
