### ISSUE TITLE
Chromium log is allowed to grow to very large size

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-issues#5033]
### Details
The `Chromium.log` file (located in `~/Library/Application Support/Steam/steamapps/common/GarrysMod/chromium.log` on macOS) is evidently allowed to grow to a very large size, and can take up a significant amount of storage relatively quickly. This log should be cleared on some interval to prevent it from growing to an unnecessarily large size.

<img width="377" alt="Screen Shot 2021-08-22 at 1 51 25 PM" src="https://user-images.githubusercontent.com/13911970/130366655-1b69db33-8ce3-46df-86aa-d8088185e2c8.png">

### Steps to reproduce
1. Occasionally play Garry's Mod for a few months.
2. Observe the file size of `Chromium.log`.

### Configuration
Garry's Mod build 7160738 (x86-64)
Steam (Jul 20 2021)
macOS 11.5.2

**Comment by FlorianLeChat** [comment]
[Someone requested the change to fix this problem a while ago now](https://github.com/Facepunch/gmod-html/pull/2), but we still have to wait for Rubat's approval to apply it to Gmod.

**Comment by robotboy655** [comment]
While that might be a good idea, it doesn't really solve the problem, just delays/slows it down. I made the game delete the file if its over 100MB on startup. Should solve it for everyone.

**Comment by TiberiumFusion** [comment]
@robotboy655
It'd be nice if this 100MB threshold could be changed via a menu convar.
There are times where I have to dig out a URL from the log and I don't want to have to consciously back up that file every time I want to start gmod.
