### ISSUE TITLE
Engine Error, FAQ Solution not working

### ISSUE THREAD

**Issue by TheJukeboPyro** [Facepunch/garrysmod-issues#5034]
### Details
Garry's Mod, in past versions of the game, worked just fine, in fact, surprisingly well. Even at points with 900+ addons, it could do almost anything, even extreme things like NPC Wars. Recently, it has become very unstable, giving me an "Engine Error" crash a lot. The most recent one I can think of is as follows. I tried to load into a workshop map called "gm_liminal_space" and while the game loaded, it crashed with an "Engine Error" message. It crashes and a tab titled with "Engine Error" popped up.  The tab is small, and has a blank button at the bottom. Other than the text "Engine Error," the tab is just an empty, white tab with a button. The button closes the tab. There a few things I've done, just today (the crash happened right after).
1. I validated the files of all of my games
2. I deleted and reinstalled Garry's Mod
3. I deleted and reinstalled all of my addons
4. I deleted all my dupes and saves
One possible problem is that I play regularly on 3 separate Computers, because I live at multiple houses. So far, it has only crashed on Singleplayer. This is not an addon report, this happens with a lot of other stuff, opening this map just seemed like a good example. Garry's Mod is now generally unstable and crashes with the message over a lot of things. This is on 2021.07.12.
### Steps to reproduce
You can do a lot of things to reproduce it. As mentioned, I simply opened "gm_liminal_space," and I haven't seen any other crash complaints on it's description. I have around 200 addons, and 0 dupes, and 0 saves. 

I can't paste the file of the crash dump here, so I'm gonna paste the contents here.
I believe this is the most recent Dump
----------------------------------------------------------------------------------------------------------------------------------------------
Loading Dump File [D:\Steam\steamapps\common\GarrysMod\hl2_210712_crash_2021_8_7T17_47_17C0.mdmp]
Comment: '-No Error Message-

-General-
  Uptime: 3.073096
  Map: 
  CommandLine: D:\Steam\steamapps\common\GarrysMod\hl2.exe -steam -game garrysmod

-Graphics-
  Driver Name: NVIDIA GeForce GTX 1070
  Driver Version: 27.21.14.6611
  VendorId / DeviceId: 0x10de / 0x1b81
  SubSystem / Rev: 0x37011458 / 0xa1
  DXLevel: 95
  Resolution: 1920x1200

-System Memory-
  Usage: 34%
  Total: 16309.72MB Physical, 25013.72MB Paged, 4095.88MB Virtual
  Free: 10709.34MB Physical, 15035.37MB Paged, 2975.48MB Virtual

-Process Memory-
  Working Set: 207.27MB
  Quota Paged Pool Usage: 0.66MB
  Quota Non-Paged Pool Usage: 0.10MB
  Pagefile Usage: 255.80MB

-Lua Stack Traces-
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
6(5.519475):  Stopping Awesomium.. 5(5.503381):  Host_WriteConfiguration: Wrote cfg/config.cfg
4(4.014860):  No Kinect SDK
3(3.579462):  Parent cvar in server.dll not allowed (p2p_enabled)
2(3.387357):  Failed to load custom font file 'd:\steam\steamapps\common\garrysmod\garrysmod\cache\workshop\resource\fonts\clearsans-medium.ttf'
1(3.093740):  Initializing Awesomium..
'
User Mini Dump File: Only registers, stack and portions of memory are available

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 19042 MP (16 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406
Machine Name:
Debug session time: Sat Aug  7 12:47:17.000 2021 (UTC - 5:00)
System Uptime: not available
Process Uptime: 0 days 0:00:06.000
................................................................
................................................................
.....................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(27ac.d4c): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
eax=00000000 ebx=364a1ca8 ecx=ffffffff edx=fffffffa esi=364a1c58 edi=364a1c68
eip=776d38fc esp=004fb3f0 ebp=004fb3fc iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00200216
ntdll!NtGetContextThread+0xc:
776d38fc c20800          ret     8

**Comment by Kefta** [comment]
Could you provide a DL to the dump file?

**Comment by robotboy655** [comment]
Yeah without the dump file there's nothing to do here. You should be able to upload it in a .zip here or just use google drive/dropbox/whatever else.

**Comment by TheJukeboPyro** [comment]
Alrighty, I'll do that when I get home.

**Comment by Dadaskis** [comment]
Hey man, maybe i should not "bump" that issue, but as creator of gm_liminal_space i'm really interested if you will provide the dump file to the contributors, because that might help them resolve issues of gm_liminal_space that were appeared not because of me (maybe)

**Comment by jorjic** [comment]
@TheJukeboPyro You pasted the summary. The entire dump file is needed to diagnose the issue.

**Comment by TheJukeboPyro** [comment]
Recently started working idk why
