### ISSUE TITLE
Brush entities 'break' when exceeding a certain limit. 

### ISSUE THREAD

**Issue by ShyAnimeGirl** [Facepunch/garrysmod-issues#5036]
### Details
During creation of my new Hogsmeade map I ran into quite the strange issue; brush entities such as trigger_teleport, trigger_hurt, trigger_multiple, etc all stopped working. The solution to this issue was reducing my total brush count to below 8192, as any time I exceeded that number (the original source engine brush limit) most if not all brush based entities (with player collision detection) would stop working. Going lower than 8192 allowed for everything to work as intended. The broken brush entities still exist inside of the bsp, and will show up in the ent_fire auto completion list if they have a name but players cannot interact with them. 

### Steps to reproduce
While I can't share Hogsmeade, I have created a test map that CAN reproduce this issue. The brush count in this test environment that causes this problem to happen is somewhere above 10326 and below 11350. Not 100% sure why but I assume it has something to do with the order things were added to the map and not actually related to the original brush limit as I originally thought. 
[instance_tests.zip](https://github.com/Facepunch/garrysmod-issues/files/7034722/instance_tests.zip)
The compiled bsp included is set up to have things not working. To fix the problem simply open the master_test.vmf and delete or hide one of the instances in the top left which contains a cluster of brushes. Recompile (with no vis for speed) and now all of the brush entities will function correctly. The map also showcases a few other instance related bugs but nothing worth wasting time on, imo.  I run mainline version 2021.07.12

**Comment by ShyAnimeGirl** [comment]
I've done a little more looking into this, It seems like this problem comes from exceeding the original BRUSH SIDE limit of 65535. This isn't directly a gmod issue because I have also modified the test map to work in csgo and the same behavior happens.
[master_test_csgo.zip](https://github.com/Facepunch/garrysmod-issues/files/7575675/master_test_csgo.zip)
I made a [video](https://youtu.be/fRlsqA__7Y0) showcasing the issue, skip to 5 minutes into the video to actually see what is going on.

**Comment by robotboy655** [comment]
I think it should now be fixed on `dev` beta and in the next update.
