### ISSUE TITLE
Ingame Multiplayer Server crashes [ExceptionCode.EXCEPTION_ACCESS_VIOLATION]

### ISSUE THREAD

**Issue by Ayumix3** [Facepunch/garrysmod-issues#5048]
### Details
Whenever we let a listend(Ingame Multiplayer server) run for a while, the server crashes with no error. just straight to desktop.
The .dmp file hints at an "Memory Access Violation".

Additional info: We have a lot of props and NPCS on the map. This issue only started appearing in the last 2-3 days.
We're using the 64bit Beta.

Link to .dmp file: https://ufile.io/bjk3m145

### Steps to reproduce
Open a Server via the ingame Multiplayer.
Wait a while.
Crash.

**Comment by robotboy655** [comment]
From the looks of it you are possibly running out of memory or hitting some other memory issue. The particular crash is from an NPC when trying to create a bone cache.

> This issue only started appearing in the last 2-3 days.

Then look into what you changed in this time.
