### ISSUE TITLE
Material doesn't create relative to data without materials folder

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-issues#5052]
### Details
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 14:56:57 Jul 12 2021 (8283) (4000)
GMod version 2021.07.12, branch: unknown
Linux 32bit Dedicated Server

main branch
Probably works only with linux srcds

### Steps to reproduce
0. Remove garrysmod/materials folder if exists
1. Create folder addon with materials/testing/testmat.vtf
2. Create testmat.vmt in data folder
```
vertexlitgeneric { $basetexture "testing/testmat" }
```
3. Make console tests:
```lua
lua_run print(Material"../data/testmat":IsError())
> print(Material"../data/testmat":IsError())...
true
```
4. Create materials folder in garrysmod/
5. Make test again:
```lua
lua_run print(Material"../data/testmat":IsError())
> print(Material"../data/testmat":IsError())...
false
```

**Comment by klen-list** [comment]
@robotboy655, still relevant in the latest versions of linux srcds
![изображение](https://user-images.githubusercontent.com/49125075/212415957-2d225b95-6b83-48f6-bc8e-14a6bcd78a4e.png)

**Comment by robotboy655** [comment]
I have looked into this more thoroughly, and the issue seems to stem from Linux's `fopen`. Windows and OSX may also have been affected, but I did not test.

I have applied a workaround fix on `dev`.
