### ISSUE TITLE
$boneflexdriver issues: frame mismatch between HLMV and in-game 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-issues#5054]
I try to establish a full vertex anim based model since $boneflexdriver has been included and they work, but animations never truly match between in-game and HLMV. 

When viewing vertex anims in HLMV, they are all fine and play all the intended frames. But the same model have very different start times and frame movement rates when I put the model in game. The in game vertex animations should match to HLMV animations. 

An example model has been attached below: 
[v_quadshot.zip](https://github.com/Facepunch/garrysmod-issues/files/7149794/v_quadshot.zip)
Spawn it with "ent_create cycler model models/v_quadshot_vertex1.mdl". Monitor the difference between HLMV and in-game.

**Comment by robotboy655** [comment]
Resolved. See https://github.com/Facepunch/garrysmod-issues/issues/5895 for details.
