### ISSUE TITLE
OpenSuse; AppFramework : Unable to load module engine_client.so

### ISSUE THREAD

**Issue by SparkizX** [Facepunch/garrysmod-issues#5056]
### Details
Garry's Mod won't start on OpenSuse Tumbleweed, I use x86-64 branch. It only gives the error: "AppFramework : Unable to load module engine_client.so", upon further investigation I decided to run it using hl2.sh which gave me this output:
```
parsec@localhost:~/.local/share/Steam/steamapps/common/GarrysMod> ./hl2.sh
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
 failed to dlopen engine_client.so error=/home/parsec/.local/share/Steam/steamapps/common/GarrysMod/bin/linux64/engine_client.so: undefined symbol: SSL_CTX_set_srp_password, version OPENSSL_1.0.1
Failed to load engine_client.so: (null)
AppFramework : Unable to load module engine_client.so!
Segmentation fault (core dumped)
```
But if I switch to 32 bit it will start but won't show, so basically it's like in the background, no window no nothing.
My dump file (yes I have used discord for that): https://cdn.discordapp.com/attachments/439148149207072768/887746957039263814/55ceab0d-b86f-4e7d-01fe689c-44db20bb.dmp

### Steps to reproduce
1. Install OpenSuse Tumbleweed.
2. Install steam from official repos.
3. Install Garry's Mod and switch x86-64 branch.
4. Try to start it.

**Comment by robotboy655** [comment]
We can't possibly support every random linux distro. It works with Ubuntu and SteamOS last I time checked.

From the looks of it your OS's `libssl.so` version is incompatible with what the game requires.

**Comment by SparkizX** [comment]
Which version of libssl.so is required?
Because installing additional version or switching version is not a problem for me.

**Comment by chinoto** [comment]
@SparkizX It pretty clearly says it's expecting OpenSSL 1.0.1. I think I'll have to manually compile it given that there are no openSUSE packages for it and there isn't much mention of it online. https://www.openssl.org/source/old/1.0.1/

**Comment by chinoto** [comment]
That did it! Download the first/latest one on the [list](https://www.openssl.org/source/old/1.0.1/), unpack it somewhere, open the folder in a terminal and run these commands:
```sh
./config shared
make -j4
make test #unnecessary, but quick relative to compiling
sudo make install
```
It will be installed to a path the linker doesn't check, so you'll need to change your Garry's Mod launch options to `LD_LIBRARY_PATH=/usr/local/ssl/lib %command%`. You could add the path system-wide, but I worry that could be a security concern given that it is an older version (why is it being used in the first place?!).

**Comment by Someone567123** [comment]
I have tried this, step by step, and got it to run, but unfortunately, after the loading screen, it doesn't even get to the title screen because it automatically closes (or crashes).

**Comment by RealParSec** [comment]
> I have tried this, step by step, and got it to run, but unfortunately, after the loading screen, it doesn't even get to the title screen because it automatically closes (or crashes).

Can you send your logs?

**Comment by Someone567123** [comment]
I could, but unfortunately, the logs came out as blank, so I am unable to
provide them. Fortunately, though, I have found a workaround, but I have
forgotten the name of it. I apologize for not being much help.

**Comment by wayzaction** [comment]
2025. If anyone's wondering - this may not work for some people, to make it work select Steam Linux Runtime in Compatibility option on Steam for gmod
