### ISSUE TITLE
Server.vdf doesn't generate on new server installs

### ISSUE THREAD

**Issue by ElectricityMachine** [Facepunch/garrysmod-issues#5064]
### Details
When creating a fresh, brand-new Garry's Mod server, with no addons or anything changed, server.vdf in garrysmod/cfg/ is not generated. This only happens on new servers and old servers work fine with a previously generated server.vdf file, even after forcing an update through SteamCMD.

### Steps to Reproduce
1. Run app_update 4020 validate in SteamCMD to make a fresh server
2. Make a simple serverside script that runs `CreateConVar("new_convar", "test", {FCVAR_ARCHIVE})
3. Observe that server.vdf is nowhere to be found, therefore no convars are actually saved.

Again this only applies to new builds. I found this by helping a friend get up to speed on gamemode development, and we found out that his convars didn't save because he lacked the server.vdf file.

**Comment by ElectricityMachine** [comment]
SOLUTION:

You need to soft-close srcds.exe by typing "exit" into the console for it to generate.

**Comment by UAVXP** [comment]
Shouldn't host_writeconfig do the thing without closing the server?
