### ISSUE TITLE
HTTPS requests fail on sites using Let's Encrypt

### ISSUE THREAD

**Issue by esmolkowski** [Facepunch/garrysmod-issues#5065]
### Details
Requests sent using [HTTP()](https://wiki.facepunch.com/gmod/Global.HTTP) fail for any website using Let's Encrypt.
As far as I can tell, this only happens on linux dedicated servers, although I have not tried it on Windows servers.
Linux listen servers and clients do not have this issue.

I am assuming this is due to Let's Encrypt's [DST Root CA X3 certificate expiring a few days ago](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). 

I have tested this on up to date versions of Debian 11 and Ubuntu 20.10.
This is a duplicate of #5063, but the poster closed the issue without it being resolved.

### Steps to reproduce
Send a serverside request to any site using Let's Encrypt for SSL.
HTTP() requests will fail with reason `unsuccessful`.

**Comment by robotboy655** [comment]
I have updated Steamworks SDK on `dev` beta, that should fix the issue.

**Comment by FlorianLeChat** [comment]
> I have updated Steamworks SDK on `dev` beta, that should fix the issue.

This is still the case after https://commits.facepunch.com/399143 ?

**Comment by robotboy655** [comment]
Steamworks may have nothing to do with it and I may have wrongly assumed people reporting this issue made sure the affected webservers were not the problem. In any case the Steam client binaries are up to date on all branches which would be the part that makes the requests.

**Comment by FlorianLeChat** [comment]
I will update the wiki in this case, thanks for the update Rubat!
