### ISSUE TITLE
Hammer: Too many verts for a dynamic vertex buffer.

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#5067]
### Details:
I was trying to add a prop_dynamic to my map with the model of "models/citadeldestruction/citadelpart7.mdl" Hammer closes with a dialog that says "Too many verts for a dynamic vertex buffer (42712>32768) Tell a programmer to up VERTEX_BUFFER_SIZE"

The reason why I'm putting this in as a bug report and not a feature request is because models/citadeldestruction/citadelpart7.mdl is a bog standard animated prop in Half-Life 2: Episode 2 and should work in Hammer without it booting you out.

### Steps to reproduce:
1. Make sure you have Half-Life 2: Episode 2 mounted
2. Open Hammer.
3. Create a new map.
4. Create a dynamic prop entity.
5. Make it's World Model: models/citadeldestruction/citadelpart7.mdl
6. Press apply and close the entity properties window.
7. Try dragging the dynamic prop in any 2D view.

### Version:
Hammer version: 4.1 (Build 8506)

Game version:
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 10:34:03 Jul  6 2021 (8277) (4000)
GMod version 2021.08.23, branch: x86-64, multicore: 1
Windows 64bit

**Comment by LillyWho** [comment]
Any chances of this being fixed?

**Comment by robotboy655** [comment]
I will fix the crash, but this does mean that models that are affected will not render at all. This only affects wireframe rendering, so the 2D views when the model is unselected in Hammer, and `mat_wireframe 1` while in-game.

I was unable to find a better fix for this, the issue has to do with software mesh skinning.

**Comment by LillyWho** [comment]
Some supplemental info, in case it's useful: The crash also occurs when a relatively complex model (but still not more complex than the default studioverts limit) is on screen in Hammer, as long as it was compiled with GMod's own Studiomdl. If compiled with the SFM version, the model doesn't cause any issues (probably some optimisations done by the SFM compiler).

**Comment by robotboy655** [comment]
Please open a new issue with example model(s) causing the issue if you wish to report it and have me look into it.
