### ISSUE TITLE
Downloading Lua files crashes my whole network

### ISSUE THREAD

**Issue by Blockmaster99** [Facepunch/garrysmod-issues#5069]
The game seems to make too many requests too fast at once when it tries to download Lua files. 

Every time I try to join a RP server my whole internet shuts down for a moment.

**Comment by FlorianLeChat** [comment]
Did you read the **README**?

**Comment by Blockmaster99** [comment]
So support changes stuff like that?

Like optimization? It's not a simple connection issue. It crashes my whole internet.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
