### ISSUE TITLE
SetImage became slower on chromium beta.

### ISSUE THREAD

**Issue by owltaver** [Facepunch/garrysmod-issues#5072]
### Details
Chromium:
![image](https://user-images.githubusercontent.com/52373664/137310802-6ed6e6d0-685b-48f5-88d4-33f9323cbfcc.png)
Default:
![image](https://user-images.githubusercontent.com/52373664/137310825-4d38a497-b185-403e-84d7-70ab85ee77ca.png)
### Steps to reproduce
```
local DFrame = vgui.Create("DFrame")
DFrame:SetSize(500,500)
DFrame:SetTitle("Test")
DFrame:MakePopup()
local DP = vgui.Create("DPanel",DFrame)
DP:Dock(FILL)
DP:DockMargin(0,0,0,2)
for i=0,58 do
	local but = vgui.Create("DImageButton",DP)
	but:Dock(FILL)
	but.Paint = function(s)
        but:SetImage("icon16/delete.png")
	end
end
```
P.S. Guess its because of recent filelib update and file.Exist check [here](https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/lua/vgui/dimage.lua#L93). I think result atleast must be cached.

**Comment by robotboy655** [comment]
Should be resolved.
