### ISSUE TITLE
couldn't include math/ease.lua, even when the file exists

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-issues#5075]
getting this error, apparently regarding that new ease.lua library.

```
[ERROR] Couldn't include file 'math\ease.lua' - File not found (@lua/includes/extensions/math.lua (line 2))
  1. unknown - lua/includes/extensions/math.lua:2
   2. include - [C]:-1
    3. unknown - lua/includes/init.lua:102
```

I checked my lua folder, and there was no math folder or ease.lua file inside. I grabbed it off of the gmod repo and put it where it should go. that eliminated the error on the server and menu, but i still get it on the client.

64 bit branch

**Comment by robotboy655** [comment]
I guess you will want to not include it in nosend.txt on the server because not all clients have the file yet.
