### ISSUE TITLE
PrePlayerDraw bug

### ISSUE THREAD

**Issue by GeraltFromDystopia** [Facepunch/garrysmod-issues#5086]
Hello brothers, i have met a really unpleasant problem regarding to gmod internal functions that i can't solve yet. I'm creator of gmodstore addons, currently i would like to talk about one of them - https://www.gmodstore.com/market/view/geralt-s-cybernetic-implants-2-0 
As you can see, i hiding player bones with ManipulateBoneScale to draw augmentations over them. But there's problem - when i installing augmentations and any lamp with **EnableShadows** (that's important) hits player or even in visible zone - that's what happens https://imgur.com/a/PdXl0zD Even with flashlight. So, this "bug" occurs only when ProjectedTexture that casts shadows is being rendered. Without shadows that doesn't happens. As you can see, augmentations doesn't completely disappear, just bones breaking or smth. I already tested it on multiple of clients and servers, with clean ones, this problem exists and happens because of lamp's shadows. I tried to disable shadows by writing **self:DrawShadow(false)** in Init function of entity, but after that augmentations appear always with hidden bones even without lamp. I guess it's really problem in internal functions so if you can please tell me what i can do with that or shall i wait for update

Here's part of code of it: https://pastebin.com/qTX5tsdG

If someone from facepunch would like to test addon, i can give license so you can test it on your own

**Comment by GeraltFromDystopia** [comment]
> Have you tried asking on the Discord, maybe someone has the solution to your problem there?

I have ban in gmod discord, however i doubt someone got this problem before, because i don't think someone using this function or this kinda of script

**Comment by GeraltFromDystopia** [comment]
@garrynewman @robotboy655 brothers give attention on this please

**Comment by Kefta** [comment]
Do not bump issues without new relevant info, they'll be addressed when they're addressed.

**Comment by robotboy655** [comment]
Have you tried using https://wiki.facepunch.com/gmod/GM:PrePlayerDraw 's second argument (STUDIO flags) to only do your rendering when certain flags are present? Just print out the values and see how they change when the bug occurs and go from there.

**Comment by GeraltFromDystopia** [comment]
> Have you tried using https://wiki.facepunch.com/gmod/GM:PrePlayerDraw 's second argument (STUDIO flags) to only do your rendering when certain flags are present? Just print out the values and see how they change when the bug occurs and go from there.

I solved it by re-parenting, because recently it just stopped working even without lamps lol, i dunno why, i haven't made any changes in code. Well, now it just works, i guess it's okay now
