### ISSUE TITLE
Missing textures or models in Linux [SOLVED]

### ISSUE THREAD

**Issue by Akrai** [Facepunch/garrysmod-issues#509]
To Garry's mod Linux players:
if you download other valve game's content for garry's mod (for example from here http://mc.mindhackers.org/cscheater/downloads.html) you may experience missing textures and models.
This is caused by uppercases: windows does not discriminate uppercase from lowercase, so if the game have to look into "abcd" folder, it is gonna look into "abcd" or "Abcd" or whatever, but in linux, if the game have to look into "abcd", it is gonna look into, and only into, "abcd" folder, and if the folder is called "Abcd" the game won't find it, but in windows it will.

This is a bug (i think it is) and this is my solution:

open terminal and go to addons folder of garrys mod:

~ $ cd .local/share/Steam/SteamApps/common/GarrysMod/garrysmod/addons/

~/.local/share/Steam/SteamApps/common/GarrysMod/garrysmod/addons $

this command will list all folders with uppercases (if you want to use it, not necessary):
find ./ -type d -name "_[A-Z]_"

and this command will remane all folders with uppercase to lowercase:
find ./ -depth -type d -exec rename 'y/[A-Z]/[a-z]/' {} ";"

so if you downloaded content from the website i said, you first would have folders like CSS Content Addon, HL2 Ep1 Content Addon, etc, and won't load textures (will appear pink and black texture, that means missing texture, where map requires it, and also will appear ERROR models), and when doing this you will have those folders with lowercases (css content addon) with all subfolders with lowercases, and wont have any missing texture (if you have downloaded all content required) or ERRORs models.

I think it is a bug of garry's mod, that can't go into any uppercase folder.

**Comment by Sithlocks** [comment]
In my use of fixed most of the purple and black textures but the error models are still everywhere, no t like anyone is gonna see this though xD
