### ISSUE TITLE
New findings about "Linux cannot display Chinese"

### ISSUE THREAD

**Issue by RainbowFunny826** [Facepunch/garrysmod-issues#5093]
依然是那个问题
Linux无法显示中文 我通过一次修改文件 发现到 如果把zh-CN的文件夹名改成zh-cn 就可以加载出中文
因此 我这次认为 是Linux文件系统的问题 在Linux中 大小写是严格的
同理 把其他带有大写名称的文件夹名 全部替换小写就可以正常加载
但是这并不是完美解决 依然有起源引擎无法显示中文的问题 也就是设置和游戏内语言失效
当然如果改文件有新进展我会在这回复

// Next is the English translated by Google //

Still the problem
Linux can’t display Chinese. I modified the file once and found that if the folder name of zh-CN is changed to zh-cn, Chinese can be loaded.
So this time I think it’s a problem with the Linux file system. In Linux, capitalization is strict.
In the same way, replace all other folder names with uppercase names in lowercase to load normally.
But this is not a perfect solution. There is still the problem that the Source Engine cannot display Chinese, that is, the settings and the in-game language are invalid.
Of course, if there are new developments in the file modification, I will reply here
![image](https://user-images.githubusercontent.com/53068513/140627756-bf122249-1038-4819-a4d8-9750d7fdae8b.png)
![image](https://user-images.githubusercontent.com/53068513/140627788-e61e382d-9eaa-4ea4-9873-4c0581753def.png)
![image](https://user-images.githubusercontent.com/53068513/140627793-90bce6df-e3ed-4e88-b6ff-aac750d1814e.png)

**Comment by RainbowFunny826** [comment]
通过一次最新的测试中
我创建了一个source.conf 加入了以下内容(文末)
并且通过Steam启动设置添加了
FONTCONFIG_FILE=/path/to/source.conf %command%
启动后它终于可以显示出中文了
此issus关闭

// Next is the English translated by Google //

Passed the latest test
I created a source.conf and added the following content (at the end of the article)
And added via Steam launch settings

FONTCONFIG_FILE=/path/to/source.conf %command%

After startup, it can finally display Chinese
This issus closed

// End
`<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test name="family" qual="any">
      <string>Helvetica</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>WenQuanYi Micro Hei</string>
      <string>Noto Sans CJK TC</string>
      <string>Noto Sans CJK JP</string>
      <string>Noto Sans CJK KR</string>
      <string>Noto Sans</string>
      <string>Noto Color Emoji</string>
      <string>sans-serif</string>
    </edit>
  </match>
  <dir>/usr/share/fonts</dir>
</fontconfig> 
`
![image](https://user-images.githubusercontent.com/53068513/144052805-c002406e-8b94-4fd4-91a2-7a8aeb0c6b00.png)

**Comment by RainbowFunny826** [comment]
using [https://github.com/ValveSoftware/portal2/issues/346](url)

**Comment by Cubicle6455** [comment]
> 通过一次最新的测试中 我创建了一个source.conf 加入了以下内容(文末) 并且通过Steam启动设置添加了 FONTCONFIG_FILE=/path/to/source.conf %command% 启动后它终于可以显示出中文了 此issus关闭
> 
> // Next is the English translated by Google //
> 
> Passed the latest test I created a source.conf and added the following content (at the end of the article) And added via Steam launch settings
> 
> FONTCONFIG_FILE=/path/to/source.conf %command%
> 
> After startup, it can finally display Chinese This issus closed
> 
> // End `
> Helvetica WenQuanYi Micro Hei Noto Sans CJK TC Noto Sans CJK JP Noto Sans CJK KR Noto Sans Noto Color Emoji sans-serif /usr/share/fonts ` ![image](https://user-images.githubusercontent.com/53068513/144052805-c002406e-8b94-4fd4-91a2-7a8aeb0c6b00.png)

我这边会出现豆腐块

**Comment by Headcrabed** [comment]
> 通过一次最新的测试中 我创建了一个source.conf 加入了以下内容(文末) 并且通过Steam启动设置添加了 FONTCONFIG_FILE=/path/to/source.conf %command% 启动后它终于可以显示出中文了 此issus关闭
> 
> // Next is the English translated by Google //
> 
> Passed the latest test I created a source.conf and added the following content (at the end of the article) And added via Steam launch settings
> 
> FONTCONFIG_FILE=/path/to/source.conf %command%
> 
> After startup, it can finally display Chinese This issus closed
> 
> // End `
> Helvetica WenQuanYi Micro Hei Noto Sans CJK TC Noto Sans CJK JP Noto Sans CJK KR Noto Sans Noto Color Emoji sans-serif /usr/share/fonts ` ![image](https://user-images.githubusercontent.com/53068513/144052805-c002406e-8b94-4fd4-91a2-7a8aeb0c6b00.png)

@RainbowFunny826 请问您这边用的conf是怎么写的？我用的上面链接里的conf不但无效还会导致原来能正常显示的文字也不能显示了
