### ISSUE TITLE
(Make sure the file is AddCSLuaFile'd and there aren't any errors!)

### ISSUE THREAD

**Issue by mei2011** [Facepunch/garrysmod-issues#5097]
It started happening out of nowhere. uninstalled recently installed mods but i can't fix it.
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 14:40:17 Jul 12 2021 (8283) (4000)
GMod version 2021.07.12, branch: unknown, multicore: 0
Windows 32bit

Steps to reproduce
N/A

https://user-images.githubusercontent.com/77690808/142746879-51f0d3d6-486f-4710-abe3-915e33235435.mp4

More details:
Running Normal Beta Branch
Windows 11 Pro 64 Bit
NVIDIA GeForce RTX 3070
AMD Ryzen 3700X
16GB RAM

**Comment by FlorianLeChat** [comment]
This issue is persistent even when all addons are disabled? I have strong doubts, otherwise it would have been reported a long time ago.

**Comment by mcNuggets1** [comment]
Same happening for me.
Fucking came out of nowhere.
64 bit

**Comment by mei2011** [comment]
@mcNuggets1 Sad. For me i just uninstalled some of my tfa addons and it worked

**Comment by mcNuggets1** [comment]
Don't have TFA or any addons besides content addons and shit I been using since 2016.
It just doesnt refresh files very often.

**Comment by mei2011** [comment]
@mcNuggets1 I would uninstall recently installed mods see if that would help or maybe ask people if your mods conflict with one another. Or seek mental help

**Comment by mcNuggets1** [comment]
I rather search mental health, because I didn't add anything. ^^"
