### ISSUE TITLE
prop_vehicle_airboat cause console spam in multiplayer when drive backward

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5098]
### Details

If you drive backward on **prop_vehicle_airboat** playing in **multiplayer**, your server console will be completely filled with one error.
`DataTable warning: (class prop_vehicle_airboat): Out-of-range value (-0.049740) in SendPropFloat 'm_flCycle', clamping.`

This occurs when the propeller spins backwards and its cycle hits a negative value. You may notice that the propeller in **multiplayer** stops abruptly and no longer rotates until the cycle returns to the positive range.

This error occurs even with console variable `developer 0`

https://user-images.githubusercontent.com/7351599/142762521-cd64cc26-0922-4a18-802c-43584fd0361d.mp4

If you play in a **singleplayer**, then everything is fine, the propeller spins backward correctly, no errors.

https://user-images.githubusercontent.com/7351599/142762603-6772d592-f216-4593-959e-b8c5293779d6.mp4

I found one very old ticket #3312, but there is little information there

### Steps to reproduce

Get in the Airboat and drive backward.
Reproduced on everything in **multiplayer** (dedicated server and local multiplayer), for many years)

**Comment by robotboy655** [comment]
Should be fixed on Dev  beta and in the next update.
