### ISSUE TITLE
func_movelinear with momentary_rot_button play moving sound in each frame

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5103]
### Details
I found that now in the game the sounds of a moving gates are played every frame, which creates a weird sound glitch (unmute sound in the video):

https://user-images.githubusercontent.com/7351599/143617734-8590a9e2-cdbe-4101-b09a-f134c5fe918b.mp4

**func_movelinear** brush has Keyvalues:
```
Sound played when the brush starts moving. (startsound) <sound>
    The sound to play when the brush starts moving.
Sound played when the brush stops moving. (stopsound) <sound>
    The sound to play when the brush stops moving.
```
and has Input
```
SetPosition <float>
    Move the brush to a specific position, where 0 is the starting position and 1 is the starting position + (move direction * move distance).
```

This is caused by a combination with **momentary_rot_button** that use `Position > func_movelinear > SetPosition`. If I use `ent_fire !picker open` on the gate then the sound will play normally.

I do not know at what point it broke, but I can confirm that it happened in 2021

### Steps to reproduce
Load anything map with valve gates in singleplayer or multiplayer (**d1_canals_05** for example) and use it.

**Comment by robotboy655** [comment]
Will be fixed in the next update.
