### ISSUE TITLE
notification library doesn't work on menu state

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#5106]
`notification` library [is loaded on menu state](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/init_menu.lua#L44), however errors due to `RealFrameTime` being nil.

Should it be fixed or removed from menu state?

**Comment by robotboy655** [comment]
Yeah I don't see any point in having it in menu state.

**Comment by GitSparTV** [comment]
It could be used in some way. But if we look at error popup, permissions prompts, main menu itself, everything is custom. We can just make special menu notification on demain.

**Comment by GitSparTV** [comment]
But it's useless for now

**Comment by robotboy655** [comment]
If we will need it, we will fix it. For the time being it is not useful in the menu state, and I don't see how that would change.
