### ISSUE TITLE
pcalling require triggers script errors

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#5107]
As mentioned in the title doing:
```lua
pcall(require, "module_name")
```

Running that code when the module is not available did not use to trigger script errors, now it does.

**Comment by Kefta** [comment]
Semi-related to https://github.com/Facepunch/garrysmod-requests/issues/813

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498
