### ISSUE TITLE
retry on listen server quits the server and when trying to open up a new one, crashes the game

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#5109]
### Details
Create a listen server, invite a player over peer to peer and then type retry in the console.
You will be exited and when trying to open up a new game, the game will crash.
There once was a behaviour which allowed the reconnection to your own listen server, it broke some day.
64 bit - chromium on

### Steps to reproduce
- Create listen server
- Invite someone?
- Type retry

**Comment by robotboy655** [comment]
Duplicate or related to https://github.com/Facepunch/garrysmod-issues/issues/880

**Comment by robotboy655** [comment]
Cannot reproduce any crash, only that it kicks you as per #880
