### ISSUE TITLE
Keep the old console command for one more update cycle

### ISSUE THREAD

**Issue by TimGoll** [Facepunch/garrysmod-issues#5112]
In the coming update `+voicerecord` is added to the blocked command list. While we can understand that this is a useful change, this will break many addons. In general it is no problem for us to switch to `permissions.EnableVoiceChat` however this is really problematic since you removed the old method in the same update that you added the new one. This means we (and probably many other devs) have to update our addons in the very moment you update the game. And let's not forget all those servers that will lack the updates for a day or so. I can already see the loads of bugreports that will come because of this.

Therefore I'd like to suggest keeping *both* ways for one update cycle with the command being listed as deprecated. Then everyone can update their addons in time and you can remove it in the next update. This will prevent many issues that you created for no specific reason anyway.

See more: https://github.com/TTT-2/TTT2/issues/953

I would like to add that it is already causing problems right now. There are many people out there that are using the GMod beta. We can't update TTT2 for them though because this would break it for every non-beta user. I really don't understand what you guys thought of it.

**Comment by Kefta** [comment]
```Lua
if (not istable(permissions) or not isfunction(permissions.EnableVoiceChat)) then permissions = {EnableVoiceChat = function(b) RunConsoleCommand((b and "+" or "-") .. "voicerecord" end} end
```

A temporary solution you can add immediately.

**Comment by robotboy655** [comment]
I'd normally agree, but I don't know when the next update will be, and it is a pretty serious privacy issue.
