### ISSUE TITLE
EntityTakeDamage not called on damage to prop_vehicle_prisoner_pod

### ISSUE THREAD

**Issue by 1darky** [Facepunch/garrysmod-issues#5113]
### Details
`EntityTakeDamage` hook is not called on any damage given to `prop_vehicle_prisoner_pod` except physical damage.
Damage to any other entities including vehicles are calling this hook as expected. 

https://user-images.githubusercontent.com/95997959/145705252-5a8e3f78-b961-4a9b-aa29-ba1aa2d92e6e.mp4

You can see every call of hook in top left corner on video

### Steps to reproduce
```
hook.Add("EntityTakeDamage", "calltest", function(ent, dmginfo, took)
  print(ent, "EntityTakeDamage call")
end
```

**Comment by robotboy655** [comment]
Should be fixed on Dev beta when it next updates.
