### ISSUE TITLE
Mic getting stuck on

### ISSUE THREAD

**Issue by j3kawesome** [Facepunch/garrysmod-issues#5125]
### Details
In multiplayer, mic shows that it is enabled at all times and will transmit voice even without pressing push to talk button. Checked to make sure that it was not a button issue with it being sticky, not the case

### Steps to reproduce
I honestly do not know how to reproduce it - It will happen randomly and not log anything to console. Will try to update with a video if possible when it is caught again

**Comment by FlorianLeChat** [comment]
Already reported here: #5008
