### ISSUE TITLE
Unable to flush stale spawnmenu search index

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#5126]
The wiki does not document any possible way to reset the cached asset index of the spawnmenu search function. There also does not appear to any such undocumented concommand or Lua method or what have you to do achieve this.

This is an annoyance since the spawnmenu asset index appears to be cached permanently after the first search attempt. If I introduce a new model into a mounted folder while running around in singleplayer, that model will not appear in the spawnmenu search, despite said model appearing in its folder while manually browsing the directory tree for assets. The only way to clear out this stale asset index is to do something which changes the map and presumably restarts the entire client Lua state.

I report this here in issues and not requests, since this behavior is inconsistent with the rest of the spawnmenu and the engine, both of which accept new assets that are added hot.

**Comment by robotboy655** [comment]
Spawnmenu search now resets its model cache when `GameContentChanged` hook is called.

Should cover this.
