### ISSUE TITLE
server crash method with constraints

### ISSUE THREAD

**Issue by Aws0mee** [Facepunch/garrysmod-issues#5127]
I found a method to instantly crash a server, the video is pretty self explanatory. I have sent the dupe in an email to robotboy655@facepunchstudios.com to avoid people abusing this.

https://youtu.be/804-mHp94GQ

**Comment by robotboy655** [comment]
It crashes in the physics engine, and it seems to be related to how AdvDupe2 pastes constraints, as I cannot reproduce this by copying the dupe with normal duplicator.

**Comment by thegrb93** [comment]
Is any of that parented? Normal dupe doesn't support parenting.

**Comment by robotboy655** [comment]
Doesn't look like it is.

**Comment by thegrb93** [comment]
@robotboy655 I reproduced it and narrowed it to phys_constraintsystem. Sent u an e-mail with minimal repro

**Comment by robotboy655** [comment]
Seems to be the case. Good work.
