### ISSUE TITLE
Hammer: cannot open texture browser without freeze/crashing

### ISSUE THREAD

**Issue by Fennecai** [Facepunch/garrysmod-issues#5130]
### Details
Hammer cannot open the texture browser without simply freezing; and I have to force close it with task manager.

it doesn't ever finish loading the textures or whatever its doing- I left it in it's frozen state for over an hour before killing it.

this happens on all branches, even after verifying the files multiple times.

### Steps to reproduce
1. open hammer from the gmod bin folder
2. open literally any map
3. attempt to browse textures
4. hammer buries itself in the permafrost so deep that only task manager can unfreeze it...by killing it.

**Comment by robotboy655** [comment]
Cannot reproduce any crashes, I can reproduce a small freeze when first opening the texture browser after not opening Hammer for days. I expect the amount of time it is frozen for be directly affected by amount of content you have installed and your disk performance. For me it takes like 5 seconds with EP1, EP2 (mount.cfg) and all the base materials to load up.

You can see how much content you have mounted in Hammer in the "Messages" window on startup.

**Comment by Fennecai** [comment]
thats not the problem.

even if i unmount ALL content, it still permanently freezes.

**Comment by robotboy655** [comment]
Yeah, that does not happen for me using Garry's Mod's Hammer. I tried both normal version and the one on "x86-64" beta.

You can try sending me the process dump (robotboy655@facepunchstudios.com) while it is frozen, maybe it can tell me what is going on for you.
![image](https://user-images.githubusercontent.com/3299036/147969585-7cfd5e1a-8c5d-40f9-bca7-f7637207f23c.png)

**Comment by Fennecai** [comment]
i'll send you the email with the .dmp file shortly

**Comment by Fennecai** [comment]
nvm, im gonna close the issue, i sent the dmp file anyways but the actual problem seems to have self-resolved somehow
