### ISSUE TITLE
GPU load exploaded since the last update

### ISSUE THREAD

**Issue by LennDoMations** [Facepunch/garrysmod-issues#5133]
### Details
Garry´s Mod increased gpu load a lot since the last update for some models.
![image](https://user-images.githubusercontent.com/70099729/147967209-630911c2-ecf4-4944-af21-da4b0e78aa02.png)

### Steps to reproduce
Install metrostroi addon to the game. place a 10 signals in render distance.

**Comment by LennDoMations** [comment]
these models dont have many vertexes or hq textures but even 2 of these props in view can increase gpu load by 5-10 percent
AMD Radeon RX 5700 XT 8GB VRAM 1750MHZ

**Comment by robotboy655** [comment]
Nothing about the rendering has changed to my knowledge, but okay, what is this "metrostroi addon"? What is the model path I need to spawn?

**Comment by robotboy655** [comment]
Possibly related/duplicate? https://github.com/Facepunch/garrysmod-issues/issues/5129

**Comment by LennDoMations** [comment]
> Nothing about the rendering has changed to my knowledge, but okay, what is this "metrostroi addon"? What is the model path I need to spawn?

use the signalling tool to spawn the entites

**Comment by LennDoMations** [comment]
https://www.mediafire.com/folder/r2njung69jlaa/signals there are the lua files if you wanna check them

**Comment by LennDoMations** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=261801217&searchtext=metrostroi

**Comment by LennDoMations** [comment]
![image](https://user-images.githubusercontent.com/70099729/147979149-4d41e051-22b4-43a2-b651-0e76eead4ce5.png)
when one area with those entites is rendered(arround 20 of them (low number of vertexes per model))

**Comment by LennDoMations** [comment]
![image](https://user-images.githubusercontent.com/70099729/147979287-f558a214-730f-404e-a4aa-6306b255f26b.png)
when the enites are removed

**Comment by robotboy655** [comment]
I am fairly certain its not that model, if there's a GPU load increase.
![image](https://user-images.githubusercontent.com/3299036/148255444-d5fa1c78-1dfc-41a2-a703-6d1bea4cc995.png)

Like there's next to no difference for me on a 1060 between hundreds of those and 0:
![image](https://user-images.githubusercontent.com/3299036/148255686-7d7bac21-0f9a-49f2-90a3-2cf220a423c4.png)

I don't have an AMD GPU to test.

**Comment by LennDoMations** [comment]
It´s not the models. It´s the entities. check the signalling tool when you have metrostroi installed and spawn a few on the map gm_metrostroi_b50 with the following config :  
![image](https://user-images.githubusercontent.com/70099729/148656565-5ca80056-42b2-4a26-9510-fe8588f5230f.png)

**Comment by LennDoMations** [comment]
> I am fairly certain its not that model, if there's a GPU load increase. ![image](https://user-images.githubusercontent.com/3299036/148255444-d5fa1c78-1dfc-41a2-a703-6d1bea4cc995.png)
> 
> Like there's next to no difference for me on a 1060 between hundreds of those and 0: ![image](https://user-images.githubusercontent.com/3299036/148255686-7d7bac21-0f9a-49f2-90a3-2cf220a423c4.png)
> 
> I don't have an AMD GPU to test.

It may be because of a change in how one of the functions in the entites script runs with garry´s mod or it uses outdated methods that are very inefficent since the last update.

**Comment by robotboy655** [comment]
I can't get those addons to work, I installed everything and it still errors every time:
![image](https://user-images.githubusercontent.com/3299036/148785058-1037bd80-ef29-4ab3-bee7-0ea573a345eb.png)
