### ISSUE TITLE
`lua_getmetatable` call not popped correctly in `GMODLUA_GetUserType`

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#5134]
### Details

Whilst working on a binary module I noticed that `luaL_typename` was pushing a value onto the stack erroneously.

The call to `lua_getmetatable` on line 6 pushes a metatable onto the stack but does not pop it.

![image](https://user-images.githubusercontent.com/14863743/147986219-7dc89c5e-3559-404f-8ae7-b699cece7e51.png)

**Comment by Kefta** [comment]
Potentially related to https://github.com/Facepunch/garrysmod-issues/issues/4100.

**Comment by WilliamVenner** [comment]
> Potentially related to #4100.

I don't think it is unfortunately. This function is not called by TypeID as this is only related to string names of types.

**Comment by robotboy655** [comment]
Should be fixed on Dev beta.
