### ISSUE TITLE
Add scripts/soundscapes_*.txt to the AddonWhiteList

### ISSUE THREAD

**Issue by js1251** [Facepunch/garrysmod-issues#5135]
Currently the workshop addon whitelist does not allow for soundscape scripts. They are located in 
`scripts/` and need to follow this naming syntax: `"soundscapes_<mapname>.txt"`

Currently soundscapes need to be packed into the .bsp pakfile which results in soundscapes not always playing.

**Comment by robotboy655** [comment]
Embedding the file into the map file should be the correct way. If there is a case of "soundscapes not always playing", please provide further details, such as steps to reproduce on demand.

**Comment by js1251** [comment]
You are absolutely right about there being no problems with "soundscapes not always playing". Ive just made a stupid mistake.

When packing its important to set the location to "/scripts" instead of "scripts/" (at least in Pakrat).

I understand the reason for not whitelisting it otherwise. Can be closed if you want.
