### ISSUE TITLE
surface.DrawLine rounds to integers in 3d2d context

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#5136]
## Demonstration

- The transparent cyan circle is drawn with `surface.DrawPoly`.
- The solid cyan lines are drawn with a series of `surface.DrawLine` calls. They are the exact same vertices used by DrawPoly, so it should be a perfect outline on the transparent circle. Instead, DrawLine appears to be rounding the verts to integers, despite being called in a 3d2d context, and despite DrawPoly proving that `surface` is capable of drawing non-integer verts.

![gmod surface 3d2d rounding](https://user-images.githubusercontent.com/6332277/148024505-7e323c89-ada7-4435-8dda-d8f1adf6f530.png)

### Addendum
This would be far less of a problem if some `render.DrawPoly` or similar method for drawing basic 3d surfaces (not wireframes) existed. Being forced to use both `surface` and `render` in tandem, and thus having to transform verts from 3d2d to 3d and vice versa, in order to draw arbitrary polygons in 3d is annoying.

**Comment by thegrb93** [comment]
all surface functions do that. that's intended behavior

**Comment by TiberiumFusion** [comment]
@thegrb93
Since you can't be assed to spend 20 seconds to read the issue in its entirety, let alone test your incorrect claim before posting misinformation, let me spell it out for you with some code. This seems to be a bad habit with you.
[surface_vertex_rounding_demo.zip](https://github.com/Facepunch/garrysmod-issues/files/7811234/surface_vertex_rounding_demo.zip)

Actually read the issue description, run the test code for yourself, and observe the issue. It is obvious that not all surface functions treat vertices the same way, and that DrawPoly accepts non-integers while DrawLine always rounds. Now tell me again that "all surface functions do that".

**Comment by thegrb93** [comment]
suck my balls nerd. I've reported it before and gmod devs didn't care. so goodluck

**Comment by TiberiumFusion** [comment]
@thegrb93
Can't suck what doesn't exist.
Do you have a link to where you previously reported this issue? There may be useful information there, and I am curious as to how long Facepunch has been ignoring this issue in their trademark fashion.

**Comment by thegrb93** [comment]
@TiberiumFusion https://github.com/Facepunch/garrysmod-issues/issues/3433

Cool beans @robotboy655
