### ISSUE TITLE
Question about "do_constraint_system: Couldn't invert rot matrix!" and another commonly spammed messages

### ISSUE THREAD

**Issue by Synkstar** [Facepunch/garrysmod-issues#5141]
Everyonce and awhile in my server console it would spam `do_constraint_system: Couldn't invert rot matrix!`
another one thats commonly spammed is caused by out of range values on the position of an entity say if a crossbow shoots through the map.
Is there anyway to disable this message and also delete entities with out of range values  ?

**Comment by robotboy655** [comment]
The `do_constraint_system` thing is either coming from the physics engine or from your Lua, can't help you there.

As for out of range values for position/angles/velocity specifically, `sv_crazyphysics*` convars are meant to help delete such objects, if its thresholds are not good enough for you, you can always just write your own code do delete such entities.

**Comment by Synkstar** [comment]
The thing is the out of range values isnt a crazy physics warning. This is a 64 bit server as well. sv_crazyphysics_warning is set to 0. The couldn't invert rot matrix is definitely a physics engine warning because there is nothing in the lua of the server that mentions it. Might just have to detour console logging somehow and make it not print them or like rate limit it.

**Comment by robotboy655** [comment]
> The thing is the out of range values isnt a crazy physics warning. 

Yes, but crazy physics deletes stuff outside of the map, stuff with crazy coordinates/angles/velocity, etc.

**Comment by Synkstar** [comment]
crossbow_bolt[358]:SetAbsOrigin( -25405.349609 -72095.835938 -131098.015625 ): Ignoring unreasonable position

**Comment by robotboy655** [comment]
Ah, I just checked and crazy physics only checks for REALLY crazy values, so your best bet for now would be to make your own script that checks all entities every few seconds and deletes them if they are like lower than `-100000` on the z axis. 

131072 in any direction is when it will start saying that message.

**Comment by Synkstar** [comment]
https://github.com/Synkstar/gmsv_hush -- Modified this module to remove the do_constraint_system: Couldn't invert rot matrix! spam incase anyone is interested. Pretty sure this only occurs on an x86-64 server. It happens when using the Jeep and is rather annoying.
