### ISSUE TITLE
file.Find does not work with resource files on clientside

### ISSUE THREAD

**Issue by Vurv78** [Facepunch/garrysmod-issues#5146]
### Details
You can't use file.Find with files you ``resource.AddFile`` or ``resource.AddSingleFile`` on clientside. Not sure if this is documented anywhere or intended behavior, so sorry if this is a dupe. This is pretty awful when the only alternatives are to manually network the files, or set their extensions to .lua and AddCSLuaFile them.

I am using this for programming language files, same reason I bumped file.Write extension restriction being lifted

### Steps to reproduce
```lua
if SERVER then
	resource.AddSingleFile("lua/foo/bar.txt")
else
	print( #file.Find("foo/*.txt", "LUA") ) -- 0
end
```

**Comment by robotboy655** [comment]
resource.Add(SingleFile) has a whitelist of file paths and file types you are allowed to send. This is not a bug.

**Comment by garryspins** [comment]
Can we get this whitelist documented?
