### ISSUE TITLE
Extreme network load when manipulating a single bone

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#5148]
> _"The repeated use of bone manipulation in multiplayer games is highly discouraged due to the huge produced network traffic."_

Yes, I am well aware of this. Yes, streaming animation over the network can quickly get out of hand. Yes, this is to be avoided whenever possible.

However, I find it very strange for the server to dump **_183 KB/sec_** on the client just to animate the angle of **one bone** (at 66 tps) with `ManipulateBoneAngles()`. I could watch a youtube video in 360p with that.

Yes, I know that 183 kb/s figure is the uncompressed payload, but I doubt the compression is 95% efficient or similar. Regardless of the compression, the client still has to chew on all of that data that it might not even need. At scale, this could greatly impact the client's framerate (e.g. animating translation + rotation for a full valve biped over the network),

One `Angle()` is 12 bytes (or maybe 16). Entity indices are surely no more than 4 bytes. A bone index can fit in a single byte. Let's ignore any headers in this figure since they will be negligible. Naively sending that all data per tick, at 66 tps, we have a 1122 bytes/second payload. That is only 0.5% of the massive 183 **kilo**bytes/second stream that the engine is generating.

What is in the remaining 99.5% of that giant chunk of data? I am not deeply intimate with Source's networking methodology or with gmod's changes on top of that, but I have a hard time believing it is necessary to use bandwidth equivalent to a youtube video just to animate 3 floats. Whatever the current strategy is, it seems deeply flawed.

### Demo addon

[bone_manip_network_thrashing_demo.zip](https://github.com/Facepunch/garrysmod-issues/files/7920116/bone_manip_network_thrashing_demo.zip)

1. `-noworkshop`
2. Start a new multiplayer game.
3. Open the netgraph.
4. Spawn any entity.
5. Look at the entity. The server will animate its first bone by calling `ManipulateBoneAngles()` once per tick, which ofc will be networked to the client.
6. Hold right click while looking at the entity. The server will simply send the bone index and manip angle to the client with a net message, then the client will apply the bone manipulation locally.
7. Observe the extreme difference in network load.
8. Modify the demo addon so that it manipulates a different bone index. Notice that the network load remains unchanged.

### Demo video

[Watch on Youtube, too big for github attachment](https://www.youtube.com/watch?v=Op7nhWjMCbA)

`ManipulateBoneAngles()` is compared with the previously described naive net message strategy for 3 different entities. You can briefly see at the beginning that idle network load is about 5 KB/sec, Strangely, the extreme network load produced by ManipulateBoneAngles is the same for all 3 entities, regardless of their type and how many bones their model has.

The point of the demo is _only_ to make it evident that vastly more data is sent than what is needed to network only the bone manipulation angle. There may be additional data which is legitimately needed. However, just networking the manip angle is sufficient for the client to accurately set up the model's pose and hitboxes (prediction notwithstanding). There may be data beyond animation and hitboxes that is left out of sync with this strategy, but it wouldn't make sense to _constantly_ network 200x more data just to cover some edge cases.

It is also worth mentioning that in similar tests, I have animated the angles of 12 bones over the network, and the extreme network load is strangely identical to when animating a single bone.

**Comment by robotboy655** [comment]
Fixed for the next update.
