### ISSUE TITLE
PhysicsInitShadow instant crash when used serverside on hl2 jeep or airboat.

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5156]
### Details
Whenever :PhysicsInitShadow( true, true ) is called on the hl2 jeep or airboat through serverside the server instantly crashes, easy to replicate. This instant crash is being abused massively in advanced dupe where players with a few tricks can instant crash servers on spawning in a vehicle, im reporting this here and not on advdupe2 because i feel like this might be a bigger issue.

### Steps to reproduce
Spawn hl2 jeep or airboat, use :PhysicsInitShadow( true, true ) on it.

**Comment by robotboy655** [comment]
I have fixed the crash, but really this feels like a much bigger problem with the addon you are using, being able to run random code like that.

**Comment by wrefgtzweve** [comment]
> I have fixed the crash, but really this feels like a much bigger problem with the addon you are using, being able to run random code like that.

Advanced duplicator 2 does it

**Comment by thegrb93** [comment]
This spot I guess https://github.com/wiremod/advdupe2/blob/c95f7b65d57781675cf19a8514f32b6c3f0a4247/lua/advdupe2/sv_clipboard.lua#L1378

I'm not sure myself what that code is trying to do
