### ISSUE TITLE
util.FilterText returns an empty string for TEXT_FILTER_CHAT context if the player is blacklisted

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5161]
### Details
I tested the **util.FilterText** function and noticed that if the player who is passed the third argument is in the Steam blacklist, the function will return an empty string. Is this a bug?

The chat filtering settings have no effect on this behavior.
It is expected that chat filtering will not hide the entire text.

### Steps to reproduce
Add a player to the Steam blacklist. Filter the text with this player.

**Comment by robotboy655** [comment]
I guess it is expected behavior, if you block someone, you don't want to see their messages.

**Comment by TIMONz1535** [comment]
I understand this is done by the Steam library, and it can't be configured right?
It's easy to workaround this in Lua, I just wanted to clarify. It is enough to add a Note to the wiki about this and close.

**Comment by TIMONz1535** [comment]
Sorry for the delay. I tested with a different context and it turned out that this only applies to **TEXT_FILTER_CHAT** content.
**TEXT_FILTER_UNKNOWN** keeps to work and filtering exactly the same as **TEXT_FILTER_CHAT**

**Comment by FlorianLeChat** [comment]
A note has been added to the Wiki to clarify this behavior with today's update. You can easily close this issue @TIMONz1535.
