### ISSUE TITLE
DrawSpriteModel Shader Warnings

### ISSUE THREAD

**Issue by ShyAnimeGirl** [Facepunch/garrysmod-issues#5163]
### Details
When using a material with any shader besides "Sprite" your console will get spammed with this warning: 
`Warning! DrawSpriteModel/env_sprite is rendering a material (materials/sprites/blueglow2_rendermode_9) with a non sprite shader UnlitGeneric! Expect crashes! `
This will continue as long as the sprite is being rendered. The material used here is a default source engine sprite. UnlitGeneric is essentially a sprite shader, detail sprites require UnlitGeneric and UI 'sprites' use it too. This warning doesn't occur in any other game I've tested. 

Ideally if the warning needs to exist it should be a single one time warning and not every single (frame?) that the sprite is rendered. 

Personally I've had sprites with LightmappedGeneric which is absolutely not a sprite shader, in extremely popular production maps and I've never had a single person report a crash related to these. (afaik)

### Steps to reproduce
Create a map with an env_sprite using a material with any shader besides "Sprite" using any rendermode.

**Comment by robotboy655** [comment]
The warning is behind `developer 1` developer mode. Disable it if you do not wish to see the warnings.

**Comment by ShyAnimeGirl** [comment]
That's fair, I just felt the spam of the message was excessive and to someone who didn't know any better might look like a much bigger problem than it is. Especially considering there is little documentation about this warning when searching it so hopefully this will somewhat serve that purpose.
