### ISSUE TITLE
EntityEmitSound does not work for npc_metropolice and npc_combine_s

### ISSUE THREAD

**Issue by ilovedumps** [Facepunch/garrysmod-issues#5164]
### Details
When you hook EntityEmitSound it does not pick up any sounds from those npcs I just mentioned except for the guns they shoot, let alone modify their sounds. Why is that and is there a fix? I've been searching for an answer since september so please help.

### Steps to reproduce

put in server
hook.Add ( "EntityEmitSound", "soundnames", function (data) PrintTable (data) end)

**Comment by FlorianLeChat** [comment]
Duplicate of #1021
