### ISSUE TITLE
Binary module error messages aren't displayed correctly with non-English characters

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#5169]
### Details
Since the last update (related to https://github.com/Facepunch/garrysmod-requests/issues/1942), C++ modules which fail on loading will give an error with a possible reason of the failure. However, this message doesn't seem to be displayed correctly if it contains non-English characters.

Here is an example of what I am describing with an error in French:
![image](https://user-images.githubusercontent.com/26360935/154562668-7ddec064-6eff-4916-a8f3-3b3861fc43aa.png)

```
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 15:23:05 Jan 27 2022 (8482) (4000)
GMod version 2022.02.02, branch: unknown, multicore: 0
Windows 32bit
```

I know that the console can suffer from this kind of issue and there are probably issues created about it but since this is a recent addition, I'm hoping you can fix that at least.

### Steps to reproduce
You just need to load a module which does not work and set the language of your operating system to a non-English one.

**Comment by FlorianLeChat** [comment]
Small update: this bug is still applicable today and seems particularly annoying for languages like Russian or Japanese which use only non-English/Latin characters.

An example:
![image](https://cdn.discordapp.com/attachments/567672652714475530/961326994753192006/unknown.png)

**Comment by NoSharp** [comment]
@FlorianLeChat A quick fix would be to change your system locale, no? I don't see it being feasible for the console to support anything above ascii. I'm not familiar with the text rendering inner-workings but I imagine this won't be worth the time or effort.

**Comment by CornerPin** [comment]
On Windows, the game uses [FormatMessage](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage) to convert [system error codes](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes) to text messages. `FormatMessage` accepts the language identifier as its 4th parameter which can be used to only retrieve messages in English.

Example:
```cpp
WCHAR buffer[512];

DWORD languageID;
GetLocaleInfoEx(L"en_US", LOCALE_RETURN_NUMBER | LOCALE_ILANGUAGE, reinterpret_cast<LPWSTR>(&languageID), sizeof(languageID));

DWORD tcharsWritten = FormatMessage(
    FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
    nullptr, errorCode, languageID, buffer, sizeof(buffer) / sizeof(*buffer), nullptr
);
```

Another way of fixing this could be converting the `WCHAR` buffer to a UTF-8 string.

```cpp
std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
std::string message = converter.to_bytes(buffer);
```

**Comment by robotboy655** [comment]
I have applied a fix on Dev beta branch, would appreciate if someone who is having issues could confirm it works.

**Comment by FlorianLeChat** [comment]
The bug is still present unfortunately. I used the version of this module to test that (sorry Billy) : https://github.com/WilliamVenner/gmsv_workshop/releases/tag/v2.0.1

<img width="371" alt="Capture d’écran 2022-04-11 à 20 16 30" src="https://user-images.githubusercontent.com/26360935/162803595-0d4b5e47-af8c-4f73-a037-043792c7348b.png">

```
] version
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 14:41:56 Feb 18 2022 (8504) (4000)
GMod version 2022.04.11, branch: dev, multicore: 1
Windows 32bit
```

**Comment by robotboy655** [comment]
Alright, I have applied a different fix which now forces the error to English.

**Comment by FlorianLeChat** [comment]
<img width="351" alt="Capture d’écran 2022-04-12 à 19 39 57" src="https://user-images.githubusercontent.com/26360935/163021792-011be472-25f9-46b1-ba62-8a0478865b17.png">

Yep, it seems to work better than last time, thanks Rubat!

**Comment by robotboy655** [comment]
I guess you must have English US installed in Windows to see forced language error strings? Sigh.

**Comment by FlorianLeChat** [comment]
Oh right, I thought the previous result was the right one but when I thought about it, it was true that it had no relevance to the message I had in my native language.

I installed the English (United States) language pack without using it as default language and yes, the message is displayed correctly now.
<img width="415" alt="Capture d’écran 2022-04-13 à 20 57 59" src="https://user-images.githubusercontent.com/26360935/163250988-4bf3d3a9-427a-4ce5-933b-b11fa73dfeee.png">
