### ISSUE TITLE
Servers show an "Outdated" label with the x86-64 beta branch

### ISSUE THREAD

**Issue by Tiagoquix** [Facepunch/garrysmod-issues#5170]
### Details
Servers show an "Outdated" label when playing with the x86-64 beta branch, even if they are not actually outdated.
![image](https://user-images.githubusercontent.com/30274161/154697658-7e412035-20a5-469d-8495-f5981862ac6b.png)

This does not happen when playing without any beta branch.

Version:
```
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 21:16:15 Feb  7 2022 (8482) (4000)
GMod version 2022.02.07, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
Go to the server list using the x86-64 beta branch.

![image](https://user-images.githubusercontent.com/30274161/154698037-8742c2e7-18d0-4814-bbc0-af37656e93a9.png)

**Comment by Tiagoquix** [comment]
> This is not a bug. Using a beta branch obviously means your game client is going to be newer than the majority of servers out there.

Should not it be hidden then (to avoid confusions)?

**Comment by StupidRepo** [comment]
Yeah, it's so annoying seeing it.

**Comment by StupidRepo** [comment]
What I find funny is that some don't.
