### ISSUE TITLE
ENTITY:SetNPCClass/m_iClass crash

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-issues#5173]
### Details
Setting an NPC's class to any value outside of the predefined [CLASS_ enums](https://wiki.facepunch.com/gmod/Enums/CLASS) will crash the game outright, [even though there's a function seemingly meant for that exact purpose](https://wiki.facepunch.com/gmod/Global.Add_NPC_Class)
```
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 21:16:15 Feb  7 2022 (8482) (4000)
GMod version 2022.02.07, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
```lua
AddCSLuaFile()
DEFINE_BASECLASS("base_ai")

ENT.Base = "base_ai"
ENT.Type = "ai"

ENT.Spawnable = true

if CLIENT then
	return
end

Add_NPC_Class("CLASS_EXAMPLE")

function ENT:Initialize()
	BaseClass.Initialize(self)

	--self:SetNPCClass(CLASS_EXAMPLE)
end

```

Spawning the entity with the comment in place works fine, removing the comment or calling SetNPCClass on an existing NPC with the example value immediately crashes the game

**Comment by robotboy655** [comment]
Should be fixed on dev.
