### ISSUE TITLE
Nodegraphs in maps/graphs not working as expected.

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-issues#5174]
### Details
Valid, custom nodegraphs placed in garrysmod/maps/graphs often do not apply.
This is especially an issue when a map has an invalid default nodegraph. (no links, no nodes)
Even though this is only a problem when trying to create workshop content, it's definitely a base Garry's mod issue.

### Steps to reproduce
This has happened many times to me, and others. A specific instance of it happening was with [this map's](https://steamcommunity.com/sharedfiles/filedetails/?id=1527403485) invalid graph.

First, I made an insignificant, but valid nodegraph with [this addon. ](https://steamcommunity.com/sharedfiles/filedetails/?id=2004023752)
I placed the new nodegraph into maps/graphs.
I restarted my game.
I opened up the map and used ai_show_connect.
No nodes or links existed

I remember doing this with, and without, ai_norebuildgraph 1

###Notes
The nodegraph creator works perfectly fine on some maps.
My theory is that this happens because, on load, a map blindly prioritizes packed-in content. 
Thanks in advance!

**Comment by robotboy655** [comment]
Embedded files in the map files will always take precedence over any other files. It's not a bug, it is intended to function that way.

**Comment by StrawWagen** [comment]
Yeah, not a bug, but it sucks :(
