### ISSUE TITLE
Steam reconnects to wrong IP

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-issues#5176]
### Details
When steam loses connection it reconnects to the wrong IP.

Server startup:
![img](https://i.imgur.com/u78mecj.png)

The next day:
![img](https://i.imgur.com/9X6DD17.png)

Issue observed on Debian 11 on the latest gmod server build as of posting this.

### Steps to reproduce
- Setup a server with multiple IPs & bind your server to a secondary IP
- Wait for steam to reconnect

**Comment by robotboy655** [comment]
Can you try the 'dev' or 'x86-64' beta? If that doesn't work, try updating `steamclient.so/dll` and the accompanying `_s.so/dll` files with the ones from a steamcmd install.

**Comment by aStonedPenguin** [comment]
dev branch:
Updated as of posting the original issue, forgot to save the version before reverting.
![img](https://i.imgur.com/jnJDpUG.png)

Using the `steamclient.so` from a steamcmd install seems to be working fine.

**Comment by robotboy655** [comment]
Should be solved as long as server's up to date.
