### ISSUE TITLE
GetPhysicsObject() changes for ragdolls when shot

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#5177]
When shooting a ragdoll the object returned by GetPhysicsObject() gets set to whichever object was shot.
You can check this with this line of code `lua_run local e=Entity(1):GetEyeTrace().Entity for i=0,e:GetPhysicsObjectCount()-1 do if e:GetPhysicsObjectNum(i)==e:GetPhysicsObject() then print(i) end end`

[As can be seen here it is most noticeable with push triggers](https://streamable.com/55mqlc)

Expected behaviour: always return physobj 0 (or a function to set it maybe?)

**Comment by spankyyy** [comment]
i think its because ragdolls have a seperate physics object for each limb

**Comment by thegrb93** [comment]
^, although he does say he would expect it to always return the 0th physics object which makes sense, but is an arbitrary assumption unless the wiki says otherwise

**Comment by robotboy655** [comment]
Ragdolls do this on purpose, possibly for some game code elsewhere.

**Comment by Ramalayha** [comment]
What about the issue with push triggers?

**Comment by Ramalayha** [comment]
> Ragdolls do this on purpose, possibly for some game code elsewhere.

I only see it used here https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/physics_prop_ragdoll.cpp#L816

And it just seems like an oversight on valve's part to not swap it back after calling the baseclass function.

**Comment by robotboy655** [comment]
trigger_push has a flag to treat ragdolls properly, by applying the force to each physics object. I don't know why it needs a separate flag, ask valve.

**Comment by Ramalayha** [comment]
> trigger_push has a flag to treat ragdolls properly, by applying the force to each physics object. I don't know why it needs a separate flag, ask valve.

I guess that's sufficient. Now that I think about it this quirk is actually kinda useful for determining which part was damaged since DamageInfo doesn't specify it.
