### ISSUE TITLE
npc_apcdriver and npc_vehicledriver mystery

### ISSUE THREAD

**Issue by 0xadg** [Facepunch/garrysmod-issues#5180]
For some reason, npc_vehicledriver created by Lua instantly disappears after calling Spawn() on it, and calling Spawn() on npc_apcdriver created by same means crashes the game with exception code 0xC0000005. developer 3 doesn't show anything while spawning nor after it finishes.
The version is 2022.03.09
### Steps to reproduce
1. Create an npc_vehicledriver or npc_apcdriver via ents.Create()
2. Spawn it
3. Get no driver spawned or crash
Here's the code I'm using to spawn an APC, some path_corners and a driver:
```
spawnAPC = function(pos)
        local apc = ents.Create("prop_vehicle_apc")
        apc:SetPos(pos + Vector(0, 0, 50))
        apc:SetModel("models/combine_apc.mdl")
        apc:SetKeyValue("vehiclescript", "scripts/vehicles/apc_npc.txt")
        apc:SetName("apc_test1")
        apc:Spawn()

        for i=1, 5 do
            local path = ents.Create("path_corner")
            path:SetPos(apc:GetPos() + Vector(i * 30, 0, 0))
            path:SetName("apc_test_path" .. tostring(i))
            if i ~= 5 then
                path:SetKeyValue("target", "apc_test_path" .. tostring(i + 1))
            end
            path:Spawn()
        end
        local driver = ents.Create("npc_apcdriver")
        driver:SetPos(apc:GetPos())
        driver:SetKeyValue("vehicle", "apc_test1")
        driver:SetKeyValue("target", "apc_test_path1")
        driver:SetName("apc_test_driver1")
        driver:Spawn()
        print("safe driver (not)spawned!")
    end
```

**Comment by robotboy655** [comment]
Because you are not calling `:Activate()` on the driver which loads in the "vehicle" key value. I will fix the crashing though.
