### ISSUE TITLE
Can't copy and paste

### ISSUE THREAD

**Issue by Mremenar** [Facepunch/garrysmod-issues#5182]
Inside the "Problems" tab, there is no ability to copy and paste the Lua errors.  It does have the button to "Open on Workshop" but this is useless when we can't tell them what the problem is.

The Lua error is printed text, why don't you make it so we can copy and paste the error and alert the addon creators?

Since the last update of 2021, we now have 72 problems in our game.  The vast majority of players are not programmers.  How about you make it easier for us to report the problems that are created every time you update the game?

Thank you,
M

### Details
Tell us exactly what happens here, every single detail that you can think of.
Please include information such as which Beta Branch your game is on, the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.
Please try running a different(dev)/none beta branch and verifying your game cache integrity before reporting an issue. 

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link.

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
If it is a modding API issue, please include minimal code to reproduce the issue on demand.

**Comment by robotboy655** [comment]
This is why this button exists:
![image](https://user-images.githubusercontent.com/3299036/157759779-22243d90-cd15-437d-90b6-6a3e771dc9e1.png)

**Comment by Mremenar** [comment]
Dear Rubat,

Thank you!   Good to know!
Now for the lengthy process of letting all the add-on authors know about their addons’ errors…

JMAS



“Fall seven times; stand up eight.”
—Japanese proverb
