### ISSUE TITLE
Default weapon selector (and probably other engine VGUI elements) doesn't abide localization files

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#5186]
### Details
Just as in #4652, default weapon selector doesn't localize strings added by .properties files.
Manually overriding string with `language.Add` makes it use that string even after language change.

### Steps to reproduce
1. Make SWEP with localized name (`#somephrase`)
2. Add that phrase to a .properties file
![2022-03-18_00-39-28_7d8a9eeb-140b-4ec2-8a79-c77d723dc8e6](https://user-images.githubusercontent.com/5104603/158899379-23e6fb20-ca45-49e9-9c5f-e9ee4b1ab315.png)
3. Notice that localization file was loaded by the game properly
![2022-03-18_00-39-36_b4d1d53f-c71f-4ebc-b2e0-ed6e81b2b85b](https://user-images.githubusercontent.com/5104603/158899391-d7ad1812-3744-4bbb-a48c-f4ee1eff6a0b.png)
4. Equip the SWEP and open the weapon selector: the name is still unlocalized there
![2022-03-18_00-40-28_29e3cf35-bec0-408b-8633-21cfa99708d7](https://user-images.githubusercontent.com/5104603/158899576-8f9fc287-dd04-48ee-8b40-9eb784636158.png)
5. Add an override with `language.Add`
![2022-03-18_00-42-05_afe547e7-834b-4b06-99d0-e669b5153eea](https://user-images.githubusercontent.com/5104603/158899798-7ab9e86c-489e-4ce4-810b-e779f6ff171b.png)
![2022-03-18_00-42-14_71e0b437-ea20-4279-af82-f9c228f47794](https://user-images.githubusercontent.com/5104603/158899800-87c0fb57-7b84-47df-8a0a-7b7764ef579a.png)
This override perists across language changes.

```
] version 
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 21:16:15 Feb  7 2022 (8482) (4000)
GMod version 2022.03.10, branch: x86-64, multicore: 0
Windows 64bit
```

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
