### ISSUE TITLE
Some Workshop Addons Crash the game / servers on Startup.

### ISSUE THREAD

**Issue by oninoni** [Facepunch/garrysmod-issues#5188]
### Details
When subscribing to a specific addon or having that addon in your collection for a server the game crashes directly after "WS Finished"!

### Steps to reproduce
1. You have to run the x64 Branch
2. Subscribe to or add as server collection a big collection with some problem about it (For us it was our Server Collection: https://steamcommunity.com/sharedfiles/filedetails/?id=2674687587)
3. Start the game / sever.

It does not seem to be 100% reproduceable, since identifying an addon that causes it does not seem to be possible?
We seem to have many prolems with some addons tho. One of them:
https://steamcommunity.com/sharedfiles/filedetails/?id=2586111527
But there is no determinable pattern or anything and having "just that addon" in your game does not actually crash it.

Crash Dumps / Logs of our Server:
https://www.dropbox.com/s/xlrmjova267baf5/ccf664d4-425f-439a-a6ac2086-b7352baa.dmp?dl=0
https://www.dropbox.com/s/4peq9qhcwvapj9o/ccf664d4-425f-439a-a6ac2086-b7352baa.txt?dl=0

**Comment by robotboy655** [comment]
Should be fixed.
