### ISSUE TITLE
util.TableToJson problem

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-issues#5189]
```
[ERROR] gamemodes/rts/gamemode/nodegraph/cl_nodegraph.lua:294: attempt to serialize structure with cyclic reference
  1. TableToJSON - [C]:-1
   2. SaveNodeGraph_JSON - gamemodes/rts/gamemode/nodegraph/cl_nodegraph.lua:294
    3. unknown - gamemodes/rts/gamemode/nodegraph/cl_nodegraph.lua:303
     4. unknown - lua/includes/modules/concommand.lua:54
```

I'm nesting tables 3 layers deep, like this example (Chunks (the base table) > Nodes > neighbors):

```
{
		"pos": "[1000 86.5 25]",
		"Captured": 0.0,
		"color": {
			"r": 255.0,
			"b": 0.0,
			"a": 255.0,
			"g": 0.0
		},
		"Chunk": 11.0,
		"shouldDraw": false,
		"Nodes": [
			{
				"basecolor": {
					"r": 255.0,
					"b": 255.0,
					"a": 255.0,
					"g": 255.0
				},
				"markedcolor": {
					"r": 255.0,
					"b": 255.0,
					"a": 255.0,
					"g": 255.0
				},
				"Captured": 0.0,
				"color": {
					"r": 255.0,
					"b": 255.0,
					"a": 255.0,
					"g": 255.0
				},
				"Chunk": "[1000 86.5 25]",
				"shouldDraw": false,
				"IsImmune": false,
				"neighbors": [],
				"IsTraversable": true,
				"marked": false,
				"Node": "[976 78.5 0.0313]",
				"texture": "VACCINERT/VMTZ/DYS_VACCORPFLOOR5"
			},
```

As that is, it converts an entire table of that kind of data with util.TableToJson and writes to a file just fine, as long as "neighbors" is empty. I can run a command to add up to 8 vectors to each node's "neighbors" table, then util.TableToJson gives me the cyclic reference error. Is this something that can be fixed, or am I just screwed to never be able to nest and save this many layers? I can't use vON due to the same limitation, and the alternative json library that I found on google doesn't work either. I'm stuck.

Please let me know if there is something I can do. Thanks

**Comment by robotboy655** [comment]
You have a reference to the parent table somewhere inside of it self, trying to serialize such a structure would result in an infinite loop which is why it throws the error.

**Comment by Jova1106** [comment]
Thank you, I actually managed to get it working the way I needed it to, with both vON and util.TableToJson, because of your comment.
