### ISSUE TITLE
Vehicle:GetMaxSpeed() crashes server if used on a seat/pod!

### ISSUE THREAD

**Issue by 24v5v34v45f** [Facepunch/garrysmod-issues#5190]
# Details
Vehicle:GetMaxSpeed() crashes server if used on a seat!
I can't see a work around because Entity:IsVehicle() and Vehicle:IsValidVehicle() returns true for seats and pods also

## Server Information
version
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 17:57:22 Mar 10 2022 (8524) (4000)
GMod version 2022.03.17, branch: unknown
Windows 32bit Dedicated Server

## Steps to reproduce
Make a serverside lua file with this code
`hook.Add("PlayerSpawnedVehicle", "spawncar", function(ply, car)
    print(car:GetMaxSpeed())
end)`
now spawn any seat or pod, and the server will instantly crash

### Crash information
about to perform blocking dns call from the main thread.  consider refactoring.
src\tier1\fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
src\tier1\fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
src\tier0\threadtools.cpp (3580) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools.cpp (3580) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools.cpp (3580) : Assertion Failed: Illegal termination of worker thread 'Thread(0x2C4171F8/0x0000062C/0x'
src\tier0\threadtools.cpp (3580) : Assertion Failed: Illegal termination of worker thread 'Thread(0x2C4171F8/0x0000062C/0x'
src\tier1\fileio.cpp (5191) : Assertion Failed: CFileWriterThread already exited
src\tier1\fileio.cpp (5191) : Assertion Failed: CFileWriterThread already exited
src\tier1\fileio.cpp (5191) : Assertion Failed: CFileWriterThread already exited
src\tier1\fileio.cpp (5191) : Assertion Failed: CFileWriterThread already exited

### Dump information
The thread tried to read from or write to a virtual address for which it does not have the appropriate access

**Comment by robotboy655** [comment]
Should be fixed when the `dev` beta of the game and in future update.
