### ISSUE TITLE
Please stop ruin this game more than you do and put x64 by default 

### ISSUE THREAD

**Issue by MrDiaboloz** [Facepunch/garrysmod-issues#5191]
So much crash into gmod due to 32bit players doesn't know and its to hard for new players to go 64bit without help so they keep crashing every hours for nothing

**Comment by robotboy655** [comment]
If you are experiencing crashes, please see this article:
https://wiki.facepunch.com/gmod/Crash_Reporting

It will tell you solutions to common problems as well as how to properly report crashes so they can be fixed.
