### ISSUE TITLE
Death by worldspawn after crouch-walking into front of oven prop

### ISSUE THREAD

**Issue by 24v5v34v45f** [Facepunch/garrysmod-issues#5194]
### Details
Death by worldspawn after crouch-walking into front of oven prop (models/props_c17/furnitureStove001a.mdl)
Tried on multiplayer and singleplayer with no addons installed

### Steps to reproduce
Spawn an oven (models/props_c17/furnitureStove001a.mdl)
(Do not constraint or freeze it)
Crouch and walk into the front of the oven
You may have to wiggle a little, but will kill you instantly by "worldspawn"

**Comment by robotboy655** [comment]
Yeah, you bump the prop slightly so it would stand on one edge and it crushes you on its way down due to its insane mass and the lip protruding from the top. It's not a bug, it's physics.
