### ISSUE TITLE
cookie.Set will not save during a timeout / an immediate reconnect!

### ISSUE THREAD

**Issue by SnisnotAl** [Facepunch/garrysmod-issues#5195]
### Details
~~cookie.Set will not save the cookie if you rejoin immediately after~~
cookie.Set will not save the cookie during a timeout / an immediate reconnect!

(This is due to the 0.1 second timer in https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/cookie.lua#L57
which is seemingly pointless as removing the timer and calling the CommitToSQLite function directly has solved my problem!)

### Steps to reproduce
run in the same script, not seperate
```lua
cookie.Set("TestCookie", "peanuts")
RunConsoleCommand("retry")
```

then run after rejoining
```lua
print(cookie.GetString("TestCookie"))
```
it will show nil

#### My current workaround
~~To use archiving client convars with the values of what you want to save,
as they save with no problem before an immediate reconnect~~

Removed the timer in https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/cookie.lua#L57
Calling the CommitToSQLite function immediately has solved the saving problem!

**Comment by Kefta** [comment]
This is expected since you have to wait a tick(?) before the database saves its query before a reset happens. Do not expect the client to cache anything before it leaves unless you can confirm it.

**Comment by 24v5v34v45f** [comment]
> This is expected since you have to wait a tick(?) before the database saves its query before a reset happens. Do not expect the client to cache anything before it leaves unless you can confirm it.

Trouble is, i cant use something like a timer to wait, since i am trying to save something while the server has timed out, just before a reconnect, and timers do not work during timeout since CurTime doesn't progress!

And i'm confused, why do the convar archives save but not the cookies?

Any way to delay during timeout, using the actual cookies beacuse im not too keen on using convars?

**Comment by Kefta** [comment]
Other hooks like rendering (and maybe Think) still run so you can use those instead of timers. You can use RealTime or FrameNumber to check if time has passed.

**Comment by 24v5v34v45f** [comment]
It actually looks like cookie saving uses timers internally
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/cookie.lua#L57

So, that explains why its not working during a timeout?

**Comment by thegrb93** [comment]
It's there to reduce the performance impact of querying the database but it's really stupid. Just avoid the cookie library and query it manually.

**Comment by robotboy655** [comment]
Should be fixed on Dev and in the next update.
