### ISSUE TITLE
Allow run console commands from Blocked ConCommands on server.

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-issues#5196]
Why does [game.ConsoleCommand](https://wiki.facepunch.com/gmod/game.ConsoleCommand) not run console commands that are on the blocked list even though the wiki says otherwise? But on the wiki, in the [list of blocked commands](https://wiki.facepunch.com/gmod/Blocked_ConCommands), it is written that this function also blocks commands, why, after all, there is a [RunConsoleCommand](https://wiki.facepunch.com/gmod/Global.RunConsoleCommand) for these needs.
Please remove the blacklist from [game.ConsoleCommand](https://wiki.facepunch.com/gmod/game.ConsoleCommand) so that it can execute all console commands. This is a server function and should have access to all commands.

Or give a server variable that will allow running any console commands on the server, like, "sv_allowblockedcommands".

These issues talk about this too, and recently it worked.
[#969](https://github.com/Facepunch/garrysmod-issues/issues/969)
[#963](https://github.com/Facepunch/garrysmod-issues/issues/963)

**Comment by robotboy655** [comment]
No, I don't think so.
