### ISSUE TITLE
What will happen to Russian servers?

### ISSUE THREAD

**Issue by StupidRepo** [Facepunch/garrysmod-issues#5199]
### Question details
Hey! I was wondering... with all this news about Russia and Ukraine, what will happen to Russian servers? Will they be blocked? Will they still be allowed?

I'm asking this question because stores and such are taking down Russian products and Discord soon blocking Russian payments, so will Garry's Mod have any Russian restrictions?

**Comment by FlorianLeChat** [comment]
![image](https://user-images.githubusercontent.com/26360935/160669097-f2c74fa0-1812-4ba6-aba5-84b7e7323afb.png)

https://github.com/Facepunch/garrysmod-issues#read-this-before-doing-anything

**Comment by robotboy655** [comment]
There are no plans to block anything.
