### ISSUE TITLE
Gmod crash with no .dmp file.

### ISSUE THREAD

**Issue by teakatt** [Facepunch/garrysmod-issues#5201]
### Details
Attemped to run gmod (March 2022 second patch) with no beta versions, and addons after hard factory-reseting the game (Removing all workshop subscriptions and completely resetting all steamcloud data). It launched but crashed after 5 seconds with no dmp file created. As i said, no add-ons or beta branches.

**Comment by robotboy655** [comment]
Please see this article regarding common startup problems and their solutions:
https://support.facepunchstudios.com/hc/en-us/articles/213577689-Common-start-up-Problems-and-Solutions

**Comment by teakatt** [comment]
No response/Outdated issue
