### ISSUE TITLE
Render contexts aren't cleared on reload

### ISSUE THREAD

**Issue by SnisnotAl** [Facepunch/garrysmod-issues#5203]
### Details
if you do cam.Start3D2D(Vector(),Angle(),0) it will break everything, even if you rejoin or change maps/server it will still be broken until you restart garrysmod

(tested on development and 64 chromium branch)

### Steps to reproduce
Run this:
```lua
cam.Start3D2D(Vector(),Angle(),0)
```

**Comment by Kefta** [comment]
Does ending the cam instance not fix it?

**Comment by SnisnotAl** [comment]
yes it does, if someone had malicious intent, you can run that function 100 times, you will have to end it 100 times for it to return to normal (or restart the game),

**Comment by Kefta** [comment]
Should rename the issue to "Render contexts aren't cleared on reload". Could really even dump them every frame. The Lua workaround would be to override cam.Start* to count instances and end any excess ones in PostRender. DarkRP already does an override like this to prevent cam.End* crashing.

**Comment by robotboy655** [comment]
I have applied fixes for this and the cam.End crashes to `dev` beta, let me know if that causes any problems.
