### ISSUE TITLE
SetInertia causes entities to be in a sleep-like state

### ISSUE THREAD

**Issue by Stooberton** [Facepunch/garrysmod-issues#5204]
### Details
Running on main 2022.03.22

Whenever `SetInertia` is called on a frozen entity, it puts it into a sleep-like state. movetype, isFrozen, isAsleep all return the same values as before, but bumping into the entity causes it to float off through the world.

This causes a lot of trouble in building communities as entire contraptions will float off through the world never to be seen again.

For some reason, calling `SetMass` on the same entity immediately afterwards fixes the issue.

### Steps to reproduce

1. Call `SetInertia` with any value on a frozen entity
2. Bump into the entity

**Comment by robotboy655** [comment]
Looks like `SetMass` calls does the `EnableMotion` trick mentioned on the wiki page for `SetInertia` function, so I went ahead and applied it to the Lua binding itself so you don't have to do it yourself.
