### ISSUE TITLE
Warning! Calling cam.End2D because someone forgot to!

### ISSUE THREAD

**Issue by Dragotiger** [Facepunch/garrysmod-issues#5205]
This is spamming my console for no reason. I might check to disable most of my addons to see if it affects such thing.

Warning! Calling cam.End2D because someone forgot to! (9218)
![image](https://user-images.githubusercontent.com/79160983/163660313-6f2d7614-9e1b-4f85-8304-e985f4e10c39.png)

Possible duplicates? https://github.com/Facepunch/garrysmod-issues/issues/1091

**Comment by Dragotiger** [comment]
After disabling every addon this comes up only once 
![image](https://user-images.githubusercontent.com/79160983/163660431-ac604902-7f8f-41bc-8887-70745441cc00.png)

**Comment by Kefta** [comment]
Override cam.Start2D and print a stacktrace to find what's creating and not ending it.

**Comment by Dragotiger** [comment]
and how do I do that exactly?

**Comment by Kefta** [comment]
```Lua
cam._Start2D = cam._Start2D or cam.Start2D

function cam.Start2D(...)
   debug.Trace()
   return cam._Start2D(...)
end
```
