### ISSUE TITLE
GNU/LINUX GMOD 64 BIT BROKEN - AGAIN --- HERES A FIX

### ISSUE THREAD

**Issue by GabenCrying** [Facepunch/garrysmod-issues#5206]
https://github.com/solsticegamestudios/GModCEFCodecFix/

ALSO UNBAN ME FROM THE COMMUNITY HUB, I HAD TO SPAM 1000 POSTS LAST TIME TO GET 64  BIT FIXED ON GNU/LINUX

https://steamcommunity.com/id/freebsd/    - Mr.Weegeeman

**Comment by GitSparTV** [comment]
It won't be merged due to the license conflicts

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5092

**Comment by GabenCrying** [comment]
> It won't be merged due to the license conflicts

can you please unban my account, i had to mass spam to get 64 bit working on gnu/linux a few years ago but i miss being albe to upload screenshots/comment on anythinbg garrrysmod
