### ISSUE TITLE
Missing "/" in detail.vbsp

### ISSUE THREAD

**Issue by benloz10** [Facepunch/garrysmod-issues#5212]
Output from vbsp.exe log:
Error loading studio model "modelsperftest/Grass_tuft_001b.mdl"!

lines 161-165 in garrysmod\detail.vbsp
161`Model2`
162`{`
163`		    "model" "modelsperftest/Grass_tuft_001b.mdl"`
164`		    "amount" "0.1"`
165`	}`
"modelsperftest" should be "models/perftest"

**Comment by robotboy655** [comment]
Fixed.
