### ISSUE TITLE
Make Gmod ignore .git folder in my addon

### ISSUE THREAD

**Issue by BloodWolf542** [Facepunch/garrysmod-issues#5214]
Hello Guys
Im currently working on a simple addon for Garry's Mod and having some issues with Github synchronization.
Im working on two devices and tried to synchronize the versions using Github. Seemingly Gmod doesn't like the automatic generated .Git folder or some of it's data and doesn't load the addon.

I know moving the .Git folder for testing and moving it back for synchronization works but Im looking for a more clean version if possible.

Looking forward for answers

**Comment by CornerPin** [comment]
Add `.git*` to your ignore list in `addon.json`.
https://wiki.facepunch.com/gmod/Workshop_Addon_Creation#addonjson

**Comment by robotboy655** [comment]
GMod does not load or care about your `.git` folder, or any other folder random folder. It has no effect on addon loading. I personally have multiple symlinked github folders in my `addons/` folder, they all work fine.
