### ISSUE TITLE
Give Weapons On Spawn Bug

### ISSUE THREAD

**Issue by Concon1231** [Facepunch/garrysmod-issues#5217]
When joining a server that has the _give weapons on spawn_ setting disabled, when you start up your own server it also disables it on your end.

Before joining server:
![image](https://user-images.githubusercontent.com/72584590/167305613-7fb2a176-a091-4d8b-9672-085a64bed8b7.png)

After joining server:
![image](https://user-images.githubusercontent.com/72584590/167305635-a266397c-cb0d-40ac-925a-23a9c0d2a495.png)

This happens on every version as far as I know, and it probably happens vice versa if you have the setting disabled and the server has it enabled. It's a minor inconvenience but it'd be nice if the game has that setting personally set instead of based on your last server.

But if you really need my version:
![image](https://user-images.githubusercontent.com/72584590/167305753-faf0584c-c554-4f76-ac64-6ccf19a40b5a.png)

**Comment by SuperStik** [comment]
I've noticed that after joining a server with certain sandbox ConVars set, that afterwards my game appears to have "copied" the server settings, and it's certainly a bit of a nuisance

**Comment by WhatAreThose** [comment]
@SuperStik also the same with Addons, you actually are forced to download them and then they stay in your addons folder cluttering it up. (Although I think they are deleted when the game next launches?)

**Comment by Kefta** [comment]
You can clean them up thru console. Read the print when you first launch the game for more info.

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
