### ISSUE TITLE
Humanoid Animations from CSGO, Left 4 Dead 2, and other newer games do not work correctly

### ISSUE THREAD

**Issue by siobhan-saoirse** [Facepunch/garrysmod-issues#5218]
### Details
When i try to use an animation from a Left 4 Dead 2 survivor model, it only moves some bones unlike the original animation.
For example, when i use the animation tool on Nick,  use the "idle_standing_fry_pan" animation, it does not look right.

### Steps to reproduce
Spawn a ragdoll that has animations, use the easy animation tool and make sure it is from Counter-Strike: Source, Left 4 Dead or newer games.
Pick an random animation from the model.
It may look like this if you chose the animation.
![image](https://user-images.githubusercontent.com/33694155/167314831-4c3c6d55-dd00-4b64-8f75-94fad45b85c8.png)
This is what it's supposed to look like:
![image](https://cdn.discordapp.com/attachments/855101766298632192/972960260308484156/unknown.png)

**Comment by Seamusmario** [comment]
This issue is also present in Source 2013 (excluding Counter-Strike: Source, with only their humanoid models) and other older source engine branches.

**Comment by Seamusmario** [comment]
An animated counter-terrorist model with the animation "Idle_Aim_Pistol", a-posing 
![image](https://user-images.githubusercontent.com/33694155/167487898-7b9a1e13-4766-484f-ad8c-97c990102491.png)

**Comment by Seamusmario** [comment]
![image](https://user-images.githubusercontent.com/33694155/167488064-6e761da4-3e39-46ac-ac3f-0bd20c889173.png)
An CS:GO Animated Model with the animation "Idle_Aim_TMP"

**Comment by Seamusmario** [comment]
![image](https://user-images.githubusercontent.com/33694155/167488356-d783beda-cd28-4a5d-a5eb-d126a815c0db.png)
Animated Prop with the Coach model using the animation "CalmRun_Sniper", some bones are moving properly than the others.

**Comment by Seamusmario** [comment]
Decompiling the animation models may fix the problem, but it mostly results in a "too many g_numsources" error

**Comment by Seamusmario** [comment]
This probably has something to do with the ".ani" files, it is using a newer version of the animation file that the HL2 Engine does not recognize properly, unlike newer games like Left 4 Dead and CS:GO.

**Comment by UAVXP** [comment]
It's probably because Gmod is not loading blendlayers properly for those models

**Comment by Seamusmario** [comment]
Counter-Strike and L4D has a much more advanced blend layer system that the hl2 engine doesn't recognize

**Comment by ZH-Hristov** [comment]
> Decompiling the animation models may fix the problem, but it mostly results in a "too many g_numsources" error

You can split the animations into multiple SMDs then include them in the .QC file iirc. Either that or multiple QCI files or w/ever it was. Pretty sure that's what I did when I had ported a large chunk of the survivor animations for use in a WOS extension. They looked p bad on the gmod rig tho since they had misplaced bones and some extra bones which stood in one place, so be mindful of that.

**Comment by robotboy655** [comment]
I think this should now be fixed on `dev` beta.

![Image](https://github.com/user-attachments/assets/53349a67-9232-4488-b27f-2625aff93986)

**Comment by ZH-Hristov** [comment]
Ok now this is epic
