### ISSUE TITLE
snd_buildcache forcibly quits the game and it's not blacklisted

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-issues#5219]
### Steps to reproduce
RunConsoleCommand("snd_buildcache", "test")

![firefox_Jdj0iIpzkc](https://user-images.githubusercontent.com/49125075/167497318-b84822ac-5544-4fd1-93fd-d75dd8269c29.png)

**Comment by robotboy655** [comment]
Added to blocked list.
