### ISSUE TITLE
convar gmod_language is empty and cannot be changed

### ISSUE THREAD

**Issue by jordanamr** [Facepunch/garrysmod-issues#5220]
### Details
I'm coming from that issue : https://github.com/FPtje/darkrpmodification/issues/167#issuecomment-1124190183
It seems like on both Rocky Linux 8 and Windows 11, I am not able to change the gmod_language convar.
I've tried editing both the server.cfg file and typing in the console but it stays empty.
I've tried that on the latest gmod dedicated server version on 2 different OSes, both downloaded via steamcmd.
The issue even happens on a blank, clean, out of the box server with no addons or custom gamemodes installed.
![image](https://user-images.githubusercontent.com/55905781/167944004-dce29713-f20c-489c-8fea-8a5826662b29.png)

### Steps to reproduce
Setup a blank server and try setting the gmod_language convar to "fr"

**Comment by robotboy655** [comment]
Are you trying to set it on server?

**Comment by jordanamr** [comment]
> Are you trying to set it on server?

Yeah, everything works fine on the client.
This is the way translation is handled by some addons (DarkRP for example), that generate and send notifications using an i18n table that uses the gmod_language convar.

**Comment by robotboy655** [comment]
I guess I will fix it.
