### ISSUE TITLE
The downfall of Gmod Servers [TIME OUT ISSUE] [-90% Of Player Base]

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#5228]
I'm just wondering why in Today's time we all need to buy this Addon: 

https://www.gmodstore.com/market/view/gluapack

In order to be able to have players in Our Gmod servers, or elsewhere, they all Time out and can't join our Servers.
So if we don't buy an addon That costs $30 All our players won't be able to join our Gmod Server.. i don't understand why this Addon isn't included in Gmod by it self??
Without this addon, it became impossible for Players to join your server.

Why this isn't included by Gmod ?

**Comment by FlorianLeChat** [comment]
It's probably because you don't know how this addon works that you are asking for it to be added directly into the game.

**Comment by Kefta** [comment]
Write your own version for free. All you have to do is override AddCSLuaFile, take the file text and compress it, network it to joining players (spreading it out over multiple ticks), override include on the client to look for your networked files in virtual paths, and you've done exactly what the engine does but bypassed the loading screen.

**Comment by mgetJane** [comment]
@WilliamVenner you will have to host every lua file for every gmod server (as reparations for all the damage you caused to this community)

**Comment by WilliamVenner** [comment]
Surely nothing could go wrong with a single entity hosting everyone's clientside Lua files 🙂

**Comment by LordofCreepers** [comment]
This is just the essence of DarkRP user to ask the game devs to add script of the third party they don't have rights to just so servers with infinite bloatware won't shit themselves and refuse connection upon an attempt to establish it

**Comment by Leystryku** [comment]
> I'm just wondering why in Today's time we all need to buy this Addon:
> 
> https://www.gmodstore.com/market/view/gluapack
> 
> In order to be able to have players in Our Gmod servers, or elsewhere, they all Time out and can't join our Servers. So if we don't buy an addon That costs $30 All our players won't be able to join our Gmod Server.. i don't understand why this Addon isn't included in Gmod by it self?? Without this addon, it became impossible for Players to join your server.
> 
> Why this isn't included by Gmod ?

Because the fault is your server. If you bootstrap 300 or 500 addons into a game, forcing users to download 20 to 40 gigs of content alone just to join your server - It is unsurprising that the engine or the games dev environment starts to struggle.

A few years ago people complained due to slow loading times, which led to the addition of workshop downloads into Garry's Mod. Fast forward a few years and the same complaints are being repeated, as people, or more specifically RP Server owners will always try to force more content down players throats.

**Comment by WicopeeDot** [comment]
This just feels like a social experiment.

**Comment by robotboy655** [comment]
You can adjust loading screen timeout via `sv_timeout_signon` convar if you have so much content that the default 5 minutes is not long enough.

It's a problem only your server seems to have. No, you are not required or expected to buy 3rd party addons for the server to function.
