### ISSUE TITLE
[Lua error] Spawnmenu error

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5231]
### Details
Getting this error when opening my spawnmenu sometimes, it's apparently a common error as many people i've talked to have gotten it in the past day. Its new and didn't appear before.

```
[ERROR] RunConsoleCommand: Command is too short, bailing! ()
  1. ActivateTool - lua/includes/modules/spawnmenu.lua:111
   2. DoClick - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:131
    3. unknown - lua/vgui/dlabel.lua:237
```

### Steps to reproduce
Not sure how to replicate but it happens on all sandbox / darkrp servers i've played on

**Comment by FlorianLeChat** [comment]
I recently got this error on the `dev` branch, but I think Rubat fixed it yesterday in one of his commits.

**Comment by robotboy655** [comment]
It should be fixed. If you still get it - it's because your server/client is not up to date.
