### ISSUE TITLE
Spawned npc_citizen get bad bounding box when model path has upper case

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#5232]
### Details
windows x86-64 branch
![barbara](https://user-images.githubusercontent.com/10217833/171618517-64d05c9a-877f-414d-acd0-5198358a4d4e.jpg)

### Steps to reproduce
I'm fixing this by

function FixNpcModelPath()
	local npcs = list.GetForEdit( "NPC")
	for k, v in pairs( npcs ) do
		local s = v["Model"]
		if s then
			local sz = string.lower(s)
			if s == sz then 
			else
				v["Model"] = sz
				print("Fixed "..k.." model "..s)
			end
		end
	end
end
timer.Simple( 1, function() FixNpcModelPath() end )

Just `--v["Model"] = sz` and find npc-class in console, spawn it by spawn menu, enter `developer 1`  `ent_bbox`, or just step near the npc

**Comment by robotboy655** [comment]
Fixed on Dev beta.

**Comment by ExboCooope** [comment]
@robotboy655 Fixing confirmed on dev beta.
Note: 
ENT:SetModel after ENT:Spawn (addon npc_tools_104486597, obj_npcspawner) get the same bad bounding box on most npc_citizen models
ENT:Spawn after ENT:SetModel is fine.

**Comment by robotboy655** [comment]
Yes, SetModel sets the bounding box to that of the model. It's up to each mod to handle it properly.
