### ISSUE TITLE
PreDrawHUD alters the colour of viewmodel

### ISSUE THREAD

**Issue by BullyHunter32** [Facepunch/garrysmod-issues#5234]
### Details
Viewmodel's appearance gets overwritten by PreDrawHUD + HUDShouldDraw
![image](https://user-images.githubusercontent.com/60613196/171658542-8e96c527-3c74-4999-9cfe-64afca33fdcc.png)
<img width="973" alt="image" src="https://user-images.githubusercontent.com/60613196/171659086-eb8cfe9e-5e4a-4537-b3d6-6cb6f61f4e9f.png">

I don't think that the ViewModel is meant to render after PreDrawHUD either, might be wrong about that though.

### Steps to reproduce
```lua
local mat = Material("icon16/heart") -- works with errors and non errors
hook.Add("PreDrawHUD", "", function()
    local scrw = ScrW()
    local scrh = ScrH()
    cam.Start2D()
        surface.SetDrawColor(255, 0, 0) -- this determines the colour of your viewmodel
        surface.DrawRect(0, 0, scrw*0.5 + ((scrw*0.5)*math.sin(CurTime()*4)), scrh) -- applies the modification
        surface.SetDrawColor(255, 255, 255)
        surface.SetMaterial(mat)
        surface.DrawTexturedRect(0, 0, scrw, scrh)
    cam.End2D()
end)

hook.Add("HUDShouldDraw", "", function(name)
    -- without this, your viewmodel will render with its default appearance
    if name == "CHudGMod" then
        return false -- Seems to be responsible for overwriting the viewmodel to a colour
    end
end)
```

**Comment by robotboy655** [comment]
What actually happens as far as I can tell is that the texture you draw is affected by the depth buffer to some capacity.

This can be easily solved by calling `render.ClearDepth()`.
