### ISSUE TITLE
EntityTakeDamage Hook doesn't work with func_ entities

### ISSUE THREAD

**Issue by Kurome76** [Facepunch/garrysmod-issues#5236]
### Details
Hammer brush entities such as func_door, func_door_rotating & func_movelinear don't get called in the GM:EntityTakeDamage() hook when attempting to damage those by any means. (tested both on the x86-64 branch & default)

### Steps to reproduce
1. Write in a autorun lua file:
```
hook.Add( "EntityTakeDamage", "MyHook", function( v )
	print(v)
end)
```

3. Shoot the white room in gm_construct, or the mirror.
4. From that it can be observed that neither func_brush or func_reflective_glass gets printed into the console.

**Comment by robotboy655** [comment]
If an entity doesn't take damage, like `func_brush` and `func_reflective_glass`, the hook will not be called for it. Internally this is dictated by the `m_takedamage` field.
