### ISSUE TITLE
Default skeleton player model invisible from certain angles.

### ISSUE THREAD

**Issue by callumok2004** [Facepunch/garrysmod-issues#5238]
https://user-images.githubusercontent.com/35779365/171971764-e46540f8-377c-4c3f-895f-fb6cc3920e59.mp4

This issue happens for players on both the 64bit and 32bit versions.

**Comment by FlorianLeChat** [comment]
Can you reproduce this bug in Sandbox gamemode without any of your addons? If not, then it's on your side.

**Comment by callumok2004** [comment]
Fixed from https://github.com/Facepunch/garrysmod/commit/4aefc7d7f468998cd3239c0baa560a389f27d884
