### ISSUE TITLE
freezes when I disable a workshop item.

### ISSUE THREAD

**Issue by jefferybe** [Facepunch/garrysmod-issues#5240]
Every time I disable an item in my subscribed stuff it freezes for about 1-2 seconds.

**Comment by robotboy655** [comment]
It is completely normal and will depend on how fast your PC can remount/reload all your enabled addons. You can use the multi-selection tool to bypass this:
![image](https://user-images.githubusercontent.com/3299036/172145635-5018166e-46f3-4e33-8104-067eb8631b63.png)
