### ISSUE TITLE
Exceeding a brushside count of 65536 causes strange map behaviour

### ISSUE THREAD

**Issue by gooball60** [Facepunch/garrysmod-issues#5243]
This is a follow-up to issue #5198, where I describe some strange behaviour that started appearing on a map I've been working on. I will be referring to it occasionally here, as I believe I have found the cause of that behaviour.

A patch note from June 9 of last year stated that MAX_MAP_BRUSHSIDES was increased to around 163k (up from the previous limit of 65536). However, it seems as though that is not actually the case. While a map will appear to compile just fine with brushsides exceeding well above 65536, strange things start to happen when that magic number of 65536 is exceeded. I describe these weird things in issue #5198.

Attached is a map (brushside_test.vmf) which has a very high density of brushes that, when compiled, results in a brushside count of 65503 - just barely under 65536. No anomalies are found in the map at this point. If you want to confirm this, compile the map with vvis and rad (preferably with -fast). **Make sure the "Exceed brushside limit" visgroup is disabled for now.** Observe the fullness chart entry for brushsides:
`brushsides           65503/163840     524024/1310720  (40.0%)` 

Now, enable the "Exceed brushside limit" visgroup and compile again. The fullness chart now reads:
`brushsides           65709/163840     525672/1310720  (40.1%)`

Of course this is now exceeding 65536, and you can see that a portion of the half-cylinder in front of the info_player_start is non-solid, essentially exhibiting the same behaviour as what I described in the other issue. You can add more cylinder segments to observe how the anomalies get worse the more you exceed the limit of 65536 brushsides.
 
[brushside_test.zip](https://github.com/Facepunch/garrysmod-issues/files/8861843/brushside_test.zip)

**Comment by robotboy655** [comment]
Why make a new issue about the same issue?

**Comment by gooball60** [comment]
Sorry, I suppose it would have been more appropriate to post this with the old issue. To me it seemed like the issue evolved from a problem with func_detail brushes to a problem with brushside limits.
