### ISSUE TITLE
ENTITY:TriggerOutput("OutputName",self) doesn't work

### ISSUE THREAD

**Issue by Matsilagi** [Facepunch/garrysmod-issues#5246]
### Details
Not a bug with addons per-se, but i have looked and tested with multiple stuff and TriggerOutput isn't doing anything. The function gets called, but it doesn't do what its supposed to.
### Steps to reproduce
Have a map with an output set, can be anything.
Create an ent to trigger that output, and watch as nothing happens.

**Comment by robotboy655** [comment]
The function only works for Scripted Entities. See the wiki for info:
https://wiki.facepunch.com/gmod/ENTITY:TriggerOutput
