### ISSUE TITLE
The `sorting` argument of `file.Find` is not working

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#5250]
### Description ℹ️ 

Everything is in the title. It seems the third argument of the `file.Find` function just doesn't work. This issue is present both on client as well on server side and doesn't depend on the platform used (Windows, Linux, singleplayer, dedicated server, etc.).

### Game info 💻 

```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 11:56:47 May 30 2022 (8605) (4000)
GMod version 2022.06.10, branch: dev, multicore: 1
Windows 32bit
```
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 19:30:41 Jun  1 2022 (8607) (4000)
GMod version 2022.06.10, branch: unknown
Linux 32bit Dedicated Server
```

### Tests 🧪 
✔️ Tested in singleplayer (Windows) / dedicated server (Linux).
✔️ Tested in the default/development branches.
✔️ Tested with `-noaddons -noworkshop` launch parameters.

### Reproduction steps 📑 

Retrieve files and sort by **ascending** name order:
```lua
] lua_run local files = file.Find("autorun/*", "LUA", "nameasc") PrintTable(files)
> local files = file.Find("autorun/*", "LUA", "nameasc") PrintTable(files)...
1	=	base_npcs.lua
2	=	base_vehicles.lua
3	=	developer_functions.lua
4	=	game_hl2.lua
5	=	menubar.lua
6	=	properties.lua
7	=	utilities_menu.lua
```

Retrieve files and sort by **descending** name order:
```lua
] lua_run local files = file.Find("autorun/*", "LUA", "namedesc") PrintTable(files)
> local files = file.Find("autorun/*", "LUA", "namedesc") PrintTable(files)...
1	=	base_npcs.lua
2	=	base_vehicles.lua
3	=	developer_functions.lua
4	=	game_hl2.lua
5	=	menubar.lua
6	=	properties.lua
7	=	utilities_menu.lua
```
The result is similar even if the argument for sorting the files has been changed.

**Comment by robotboy655** [comment]
That being said, fixed `namedesc` not working.
