### ISSUE TITLE
this bug literally makes the game unplayable (no server is safe!)

### ISSUE THREAD

**Issue by SneakySquid** [Facepunch/garrysmod-issues#5252]
I can't believe such a bug would exist within such an otherwise perfect game. I've been a fan of this game for over half a decade at this point, but this bug I've just discovered has changed my perception of the game for the worse. I find it genuinely unfathomable that something such as this could even make it through quality assurance. How incompetent must the dev team be to let this fall through the cracks? How has nobody noticed that console prints and console errors are different colours? It's the same on both the client and server realms. At first after I noticed it I didn't think much of it, I thought "surely this won't impact my gameplay at a perceptible level" but how wrong I was. After a few days, just looking at the colour difference started making me nauseous. I've not played the game for almost 2 years since discovering this bug and I'm afraid to come back; just writing this issue report is making me anxious. I've seen 3 seperate therapists about the issue but they don't get it, they just keep prescribing me more and more drugs. At first they worked nicely, I forgot about the issue at hand for a while, but then came the nightmares. I've dreamt almost daily about this bug for a little over one year. I'm questioning why I ever even started playing this game in the first place; if I knew about this bug beforehand I definitely would've avoided Garry's Mod like the plague. Please do something about it before I do something rash. I'm not sure how much more I can take, I'm at my mental and physical limit.

**Comment by Kefta** [comment]
Hope you get better mate. Drugs can really fuck with a man's head.

**Comment by SneakySquid** [comment]
> Hope you get better mate. Drugs can really fuck with a man's head.

Can you please be serious about this? I feel like I'm losing my mind. This bug is slowly depleting my sanity and I'm not sure how much more I can endure.
