### ISSUE TITLE
Background Blur causing massive GPU heat increase

### ISSUE THREAD

**Issue by dotCore-off** [Facepunch/garrysmod-issues#5258]
### Details
For some reasons, when **creating background blur**, my GPU legit panics and **reaches high temperature**. 
I know that my **GPU is quite old nowadays** _(RX 580 8 Go)_ and that it's probably due to AMD _(so it can't go bellow 40°C even w/ a watercooling + fans lmao)_, but **it only happened so far with Gmod background blur**.
**There's no FPS drops nor freezes**, and it happens whatever the branch I'm using so I'm guessing it's somehow linked to the game.

### Steps to reproduce
1. Get an **RX 580** _(will be hard otherwise)_
2. Create a ``DFrame`` and call ``SetBackgroundBlur(true)``
3. Notice how **GPU temperature will skyrocket the longer frame remains opened**
4. **Close the frame** and GPU should **calm down** _(OPTIONAL)_

Tried to search all around the web if it has something to do with the hardware itself, but couldn't find any resources linked to that kind of issue. **If you have any hint, let me know.**

**Comment by robotboy655** [comment]
Your GPU is being used more with the blur (blurs are expensive) - it's temperature goes up.
