### ISSUE TITLE
Crashes on M1 Mac (macOS 12/Montery)

### ISSUE THREAD

**Issue by StupidRepo** [Facepunch/garrysmod-issues#5263]
### Details
I know this is kind of a duplicate of my other post #5001, but it's still present to this day! I am on the latest macOS version, and Garry's Mod is still crashing/hanging at the Main Menu.
I have tried them CEF fixes and stuff but then I don't get a main menu which I'd really, really like.
Please fix it for macOS 12. You don't have to support M1 Macs to do that.

**Comment by FlorianLeChat** [comment]
Opening duplicated issues will not help speed up its resolution.

**Comment by StupidRepo** [comment]
I know but I feel like this needs to be brought up and gain more attention.

**Comment by FlorianLeChat** [comment]
No Rubat will just close your issue and put the "duplicate" label, your initiative is great but considering the development state of the game, you will have to be **very** patient.

**Comment by StupidRepo** [comment]
Hm. True. I really wish they'd try and fix this though.

**Comment by StupidRepo** [comment]
I'll close it anyways.
