### ISSUE TITLE
GMod won't load up properly macOS x86-64 beta

### ISSUE THREAD

**Issue by FredsMedia** [Facepunch/garrysmod-issues#5265]
### Details
I have recently bought GMod from Steam (Yay!) but I run into an issue when I load up the game. It seems to loop pictures forever. According to my friends over the phone that is what the background of the title screen looks like. I open the console and sometimes it says cannot find 'Quick', file missing or failed to dlopen the server browser.dylib (no such file)

I am on macOS Monterey version 12.4

CONSOLE LOG
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/lua_shared.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/menusystem.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/materialsystem.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/resources.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/gmod_audio.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/client.dylib' (no such file)
Attempting to load Awesomium...
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib' (no such file)
 failed to dlopen /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib error=dlopen(/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib, 0x0002): tried: '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib' (no such file)
Failed to load /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib: (null)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib' (no such file)
 failed to dlopen /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib error=dlopen(/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib, 0x0002): tried: '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib' (no such file)
Failed to load /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium.dylib: (null)
 failed to dlopen /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/html_awesomium.dylib error=dlopen(/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/html_awesomium.dylib, 0x0002): tried: '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/html_awesomium.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib' (no such file), '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_awesomium.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS/html_awesomium.dylib error=dlopen(GarrysMod.app/Contents/MacOS/html_awesomium.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS/html_awesomium.dylib' (no such file)
 failed to dlopen html_awesomium.dylib error=dlopen(html_awesomium.dylib, 0x0002): tried: 'html_awesomium.dylib' (no such file), '/usr/lib/html_awesomium.dylib' (no such file), '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/html_awesomium.dylib' (no such file)
Failed to load html_awesomium.dylib: (null)
Attempting to load Stub...
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/html_stub.dylib' (no such file)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/GameUI.dylib' (no such file)
 failed to dlopen /Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/GameUI.dylib error=dlopen(/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/GameUI.dylib, 0x0002): tried: '/Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/bin/GameUI.dylib' (no such file)
x86-64: gmod_mcore_test=1
Parent cvar in server.dll not allowed (p2p_enabled)
Parent cvar in server.dll not allowed (props_break_max_pieces)
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Not playing a local game.
DEBUG: Clearing CSoundPatches after soundsound... (x2)
 failed to dlopen GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib error=dlopen(GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib, 0x0002): tried: 'GarrysMod_Signed.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib' (no such file)
 failed to dlopen GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib error=dlopen(GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib, 0x0002): tried: 'GarrysMod.app/Contents/MacOS//Users/freddy/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/MacOS/ServerBrowser.dylib' (no such file)
Addons have changes - remounting

VERSION
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:52:27 May 30 2022 (8605) (4000)
GMod version 2022.06.27, branch: x86-64, multicore: 1
macOS 64bit

Chromium (x86 but the version before) has the same issue and no beta selected doesn't let it run (macOS doesn't support 32 Bit Apps😡)

### Steps to reproduce
- Select either x86-64 beta or chromium beta on a Mac
- launch game
- wait
- Watch the slideshow ensue!

Btw I notice you are adding tags in other issues, how can I do that (if I can of course!)

Thanks in advance for any help I get!

Let me know if I have missed something, I am happy to provide.

**Comment by FlorianLeChat** [comment]
Probably duplicate of #5001

**Comment by FredsMedia** [comment]
If I use the html launcher the game never opens. It shows up in the bottom bar (forgot the name at the worst time possible lol) but even when I click it nothing happens. I will do some more experimenting soon but until then more help will be greatly appreciated!

**Comment by FredsMedia** [comment]
Update: it opens but I just get stuck on a blue screen.

**Comment by FredsMedia** [comment]
And should I keep the lua launcher or switch back?

**Comment by FredsMedia** [comment]
when I type map gm_construct this comes u
<img width="372" alt="Screen Shot 2022-07-07 at 7 11 09 pm" src="https://user-images.githubusercontent.com/106362296/177737590-a3b14534-ba92-4ba1-b7b2-f33c7dfe5374.png">
p

**Comment by FredsMedia** [comment]
I got rid of the no lua thing (file integrity helped!) and typing in the console seems to work for now. Please update if anything comes up!
