### ISSUE TITLE
Crash when checking PVS towards env_sprite without sprite 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-issues#5266]
Both Entity:TestPVS and ents.FindInPVS crashes when a sprite without any "model" keyvalue assigned is being checked by TestPVS. 

Steps to reproduce: 

1-) ent_create env_sprite model materials/sprites/orangecore1.vmt -- test group with a model / sprite 
2-) lua_run ents.FindInPVS(Entity(1)) -- related function, no crash 
3-) ent_create env_sprite -- without a model / sprite 
4-) lua_run ents.FindInPVS(Entity(1)) -- related function, crash occurs

Crash file: https://cats.iku.edu.tr/access/content/user/n.yaman/uploads/hl2_220610_crash_2022_7_3T20_10_17C0.mdmp

**Comment by robotboy655** [comment]
The crashing should be fixed on Dev beta.
