### ISSUE TITLE
Hammer: Duplicated output names in UI

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5268]
### Details

**halflife2.fgd** has duplicated class inheritances. Because of this, the outputs is displayed duplicated. 
It seems that for the engine, the last declared output overwrites all the previous ones with the same name. Maybe I'm wrong.
The **Half-Life 2** Hammer editor has same issue.

```
@BaseClass base(BaseNPC ) = RappelNPC
@BaseClass base(BaseNPC, RappelNPC) = BaseCombine
@NPCClass base(BaseNPC,RappelNPC) studio("models/Police.mdl") = npc_metropolice : "MetroPolice"
```

![изображение](https://user-images.githubusercontent.com/7351599/177218959-d15bb02b-275e-498f-9ef4-b1650550dd8e.png)

```
@BaseClass base(BaseNPC) = TalkNPC
@BaseClass base(BaseNPC) = PlayerCompanion
@NPCClass base(BaseNPC,Parentname, TalkNPC, PlayerCompanion ) studio() = npc_citizen : "Citizen"
@NPCClass base(TalkNPC, BaseNPC, PlayerCompanion) studio("models/Barney.mdl") = npc_barney : "Barney"
@NPCClass base(BaseNPC, TalkNPC, PlayerCompanion) studio() = npc_vortigaunt : "Vortigaunt"
@NPCClass base(TalkNPC,Parentname, PlayerCompanion) studio() = npc_alyx : "Alyx"
```

![изображение](https://user-images.githubusercontent.com/7351599/177219228-a06ed11e-8194-4a1e-85b2-17fb088dfd1f.png)

### Steps to reproduce
Create an `npc_vortigaunt` in Hammer and check its thrice-declared outputs.

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
