### ISSUE TITLE
Broken visuals with CustomAmmoDisplay

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-issues#5270]
### Details
SWEP:CustomAmmoDisplay seems to be causing incorrect visuals when weapons are switched in certain cases.

https://user-images.githubusercontent.com/1381265/177575639-1765bd8d-fbb1-4656-87eb-d6304048c848.mp4

This only happens if the weapon uses SWEP:CustomAmmoDisplay with both PrimaryClip and PrimaryAmmo, weapons only using PrimaryClip or that use SecondaryAmmo as well work fine (Though the secondary ammo display's visibility is determined by `SWEP.Secondary.Ammo` being set to a valid ammo type regardless of what value is used for SecondaryAmmo in CustomAmmoDisplay)

### Steps to reproduce
1. Give yourself a weapon implementing the code below
2. Switch to any weapon that doesn't use an ammo display and back (Physgun, crowbar, toolgun ect.)
3. Check the ammo display
4. Switch to a weapon that does use ammo and back
5. Check the ammo display again

Code used when testing:

```lua
function SWEP:CustomAmmoDisplay()
		return {
			Draw = true,
			PrimaryClip = 1,
			PrimaryAmmo = 5
		}
end
```

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.
