### ISSUE TITLE
Disabled collisions (Properties) in Chairs/Vehicles do not save with Dupes.

### ISSUE THREAD

**Issue by ShinexWipex** [Facepunch/garrysmod-issues#5273]
So here's how this bug works:

First you need to disable collisions on chairs/vehicles by using Properties (by holding C button and then right-mouse-clicking on the chair/vehicle, and then left-clicking-selecting "Disable Collisions").

After that you should copy your chairs/vehicles with Dupe tool and then try to re-deploy it and you will see that the chair has collisions once again (touches the player and other props).

 It doesn't matter if you save this as a Dupe (and spawn it afterwards) or re-deploy it instantly without saving it. It has the same effect/impact. I've tested that.
 
The models and amount of chairs/vehicles, or, other linked contraptions/creations/props/etc. makes no difference to this also, because I've tested that too.

**Comment by robotboy655** [comment]
Will be fixed in next update.
