### ISSUE TITLE
Suppressing do_constraint_system: Couldn't invert rot matrix!

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/garrysmod-issues#5274]
Hey! Would be nice if there was an option to suppress this message, I've tried a lot of things and nothing seems to fix these warnings. Suppressing seems the only option at this point, any advice on how this could be done?

Related to: https://github.com/Facepunch/garrysmod-issues/issues/5141

**Comment by Kefta** [comment]
Use gm_enginespew to hide specific console messages. The print is from vphysics so there's really no other way to suppress it.
