### ISSUE TITLE
FakeOnline fix

### ISSUE THREAD

**Issue by c0nfusecode** [Facepunch/garrysmod-issues#5276]
Hello, you can fix a fake online by making requests not to a2s but to steam api
https://api.steampowered.com/IGameServersService/GetServerList/v1/?key=yourkey

**Comment by robotboy655** [comment]
You are genius! Why haven't we thought about it before? All it takes is to buy the game x amount of times to bypass it, which is being done.

**Comment by Eld3rly** [comment]
### **_c0nfuse obkak_**
