### ISSUE TITLE
engine.ServerFrameTime() serverside

### ISSUE THREAD

**Issue by bewflast** [Facepunch/garrysmod-issues#5278]
How do you do!

There is very useful function on client-side  named "engine.ServerFrameTime()" which shows up server's current tickrate

It would be very useful to have it on server-side too :pleading_face: (e.g detecting server's low performance and do some manipulations to stabilize it)
I know, that there are few ways do detect it through time's functions or binary module, but getting current tickrate on server-side is a more accurate and simple method :smile:

**Comment by awesomeusername69420** [comment]
```
engine.ServerFrameTime()

Returns an estimate of the server's performance.
Equivalent to calling FrameTime() from the server, according to source code.
```

![image](https://user-images.githubusercontent.com/24661212/179337038-41c6c86b-5ef3-451d-a7de-8f7a1f807edf.png)
![image](https://user-images.githubusercontent.com/24661212/179337047-95dfa724-660c-47b0-8634-33b85a2265d6.png)

What's wrong with just using `FrameTime()` ?

**Comment by Kefta** [comment]
Wrong repo + duplicate of https://github.com/Facepunch/garrysmod-requests/issues/482 - Lua solution available inside.

**Comment by awesomeusername69420** [comment]
> That's client FrameTime, not the server's

What? FrameTime() is being ran on the server, my client's frame time is way different than the server's.

![image](https://user-images.githubusercontent.com/24661212/179338040-38fcf39d-4d01-4c9d-859c-bb75fde813e6.png)

**Comment by Kefta** [comment]
> It would be very useful to have it on **server-side** too

**Comment by awesomeusername69420** [comment]
FrameTime() is not only available serverside, it is unaffected by `host_timescale` on the server effectively making it the same as RealFrameTime() but on the server

![srcds_win64_RhhHYD7iEx](https://user-images.githubusercontent.com/24661212/179338946-c7119a98-6471-449c-b6e5-e5fe49bd573b.png)

**Comment by bewflast** [comment]
sorry, closing this cos didnt know about `Facepunch/garrysmod-requests`
ill move it
