### ISSUE TITLE
Cannot crouch after dying

### ISSUE THREAD

**Issue by SylvesterPlayz** [Facepunch/garrysmod-issues#5282]
i am not able to crouch after dying, and i fly slow and i dont know how did i do it but it has been happening constantly,
please fix

**Comment by Kefta** [comment]
Try launching the game with -noaddons -noworkshop in your command line parameters.

**Comment by SylvesterPlayz** [comment]
I tried thhat but it didnt work

**Comment by Kefta** [comment]
What gamemode is this happening in? Singleplayer or multiplayer?

**Comment by SylvesterPlayz** [comment]
both multiplayer and singleplayer

**Comment by robotboy655** [comment]
Please seek help with issues on the official Discord server listed in the README of this repository.
