### ISSUE TITLE
TOOLs don't have an IsValid() method, causing IsValid(Tool) to always return false

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-issues#5283]
### Details
Tools don't have an IsValid() method, and judging by the code for the global IsValid(), it's permanently returning false because of that

### Steps to reproduce
```lua
function TOOL:Think()
    print(self.IsValid, IsValid(self)) -- prints "nil false"
end
```

**Comment by robotboy655** [comment]
Should it? At what point can you get an invalid tool object?

**Comment by Andrew-Eathan** [comment]
It doesn't really matter whether or not you can get an invalid tool object,
the issue is in the title: IsValid(Tool) always returns false, which is a
flaw

**Comment by Andrew-Eathan** [comment]
> Should it? At what point can you get an invalid tool object?

It doesn't really matter whether or not you can get an invalid tool object, the issue is in the title: IsValid(Tool) always returns false, which is flawed

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/util.lua#L229

This condition could be changed to true but who knows what that would break. Just don't send tools into IsValid: know what types you are dealing with instead of blindly sending data in.
