### ISSUE TITLE
Request: Create Panel:AvatarImage() equivalent for surface or draw Library.

### ISSUE THREAD

**Issue by Noname12345GER** [Facepunch/garrysmod-issues#5287]
Hello Facepunch.

I want to create an "I.D.-Addon" for Security Guards.

The Security Guards have a Badge on their Chest.
The Badge is dynamic and contains infos like Name, Security Clearance, etc.

I want to Render the Players Steam Profile Picture on it, but the only function involving Avatar Images is a Derma based one. (Panel:AvatarImage())

Is it possible to implement the rendering of a profile picture using the draw or surface library? Ideally, the Function should be able to handle being called repeatedly, like the HudPaint Hook.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/493 and https://github.com/Facepunch/garrysmod-requests/issues/1717

**Comment by Noname12345GER** [comment]
> Duplicate of [Facepunch/garrysmod-requests#493](https://github.com/Facepunch/garrysmod-requests/issues/493) and [Facepunch/garrysmod-requests#1717](https://github.com/Facepunch/garrysmod-requests/issues/1717)

The duplicate posts are serveral years old. Is this feature planned at all?
