### ISSUE TITLE
SetVelocity, speed gets clamped to a very low value

### ISSUE THREAD

**Issue by EntityinArray** [Facepunch/garrysmod-issues#5295]
### Details

Good day! Thank you for developing this amazing sandbox!

I'm currently trying to make a physical bullet system, where EntityFireBullets hook replaces all bullets with physical SENTs that behave like "realistic" bullets.

I decided to purely use Source's VPhysics for the bullets, but run into an issue:
Upon spawning the bullet, I apply SetVelocity of 8192 units, but speed gets clamped, GetVelocity reports speed of only ~4900 units upon spawn.

Why is does the speed gets clamped and is there any way to bypass this?

Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
Issue can be reproduced with this little code snippet:
```
local prop = ents.Create("prop_physics")

prop:SetModel("models/props_interiors/BathTub01a.mdl")
prop:SetPos(Entity(1):GetPos()+Vector(0,0,96))
prop:Spawn()

local physobj = prop:GetPhysicsObject()

physobj:SetVelocityInstantaneous(Vector(0,0,8192))

timer.Simple(0.1,function()

    local speed = physobj:GetVelocity():Length()

    print("Applied speed: 8192")
    print("Factual speed: " .. speed)
end)
```
Factual speed will be clamped at ~5000

**Comment by robotboy655** [comment]
The physics engine has sane limits set for performance and stability reasons.

https://wiki.facepunch.com/gmod/physenv.SetPerformanceSettings
