### ISSUE TITLE
64-bit doesn't work at all on Linux Mint 21 Cinnamon

### ISSUE THREAD

**Issue by tredI9100** [Facepunch/garrysmod-issues#5297]
### Details
I recently upgraded to Linux Mint 21 from 20.3 (both Cinnamon edition). On 20.3, the `main` branch of Gmod worked fine. ~~but scrolling through equipped weapons crashed the game.~~ Switching to `x86_64` made the game work perfectly. However, on Mint 21, the `main`-branch game ~~crashes when I load a map (crashes at "Lua Started!", when using -debug manages to say that it's ready before crashing and doesn't fully close)~~ _works fine after uninstalling SCars, it's a really old addon after all, but the game collapses when loading bigger maps_, and on x86_64, it crashes on "Initializing Serverside..." every time. I've tried -noworkshop and verifying game files, even updating my laptop's firmware, and this still happens. (Dell Inspiron 14-5418, Core i5-11300H@3.1GHz, 4 cores, 8GB RAM, TigerLake-LP GT2 Iris XE graphics, Cinnamon 5.4.9, kernel 5.15.0-43-generic, Garry's Mod v2022.06.10)
[This ZIP file](https://github.com/Facepunch/garrysmod-issues/files/9245378/crashes.zip) contains the entirety of my current Gmod `crashes` folder _as of posting_, since I don't know what files do what in there, _and apparently that's where all of the `x86_64` crash data is stored._
### Steps to reproduce
Launch _64-bit_ Garry's Mod on the specified hardware and software.

**Comment by gmod64bit** [comment]
Yeah, haha, the devs often break 64 bit and don't do anythnig for up to a year! Just have to wait till the developers can figure out how to 

`cp /usr/lib/libGLESv2.so.2.1.0 /usr/lib/libEGL.so.1.1.0 ~~~steam/GarrysMod/bin/swiftshader (remove everything after .so)`

**Comment by tredI9100** [comment]
> Yeah, haha, the devs often break 64 bit and don't do anythnig for up to a year! Just have to wait till the developers can figure out how to
> 
> `cp /usr/lib/libGLESv2.so.2.1.0 /usr/lib/libEGL.so.1.1.0 ~~~steam/GarrysMod/bin/swiftshader (remove everything after .so)`

Interesting, i guess we need to wait
