### ISSUE TITLE
In TF2 map 'pl_pier', game crashed when shoot at map props

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#5300]
Engine Error:
UserMessageBegin: Unregistered message 'BreakModel'

x86-64 branch, addons on
Team fortress 2 : pl_pier
shot at this
![20220807122133_1](https://user-images.githubusercontent.com/10217833/183275254-011d1405-58c0-4390-b219-6d355c98d653.jpg)

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
