### ISSUE TITLE
Localization for Kill Names: make it use translations from localization folder if language forder has no strings.

### ISSUE THREAD

**Issue by Blueberryy** [Facepunch/garrysmod-issues#5301]
### Details
You can localize spawn menu strings and almost everything but not deathnotice if you're using localization folder for npc/entity name. For example ```#supercoolnpc``` will be shown on deathnotice as it IS.

**Comment by robotboy655** [comment]
It already works as you'd expect it to work.

```
npc_tf2_ghost=Hello GitHub
```

```lua
list.Set( "NPC", "npc_tf2_ghost", {
	Name = "#npc_tf2_ghost",
	Class = "npc_tf2_ghost",
	Category = "Nextbot"
} )
```

![image](https://user-images.githubusercontent.com/3299036/183900337-d4b7d776-920d-40ab-96f2-93fcd4b8da57.png)
![image](https://user-images.githubusercontent.com/3299036/183900363-b789c7f9-5bfb-4c60-9cf3-4238a8aca462.png)

**Comment by Blueberryy** [comment]
Oh thank you. I will test that out

**Comment by Blueberryy** [comment]
Yeah it works perfectly for default npcs! Thanks.
Why it's not implemented for base npcs? It works with them too and i've never seen any problems with it

**Comment by robotboy655** [comment]
I am not sure what you mean.

**Comment by Blueberryy** [comment]
I mean there's no official localization file like **npc_names.properties** for them already. May i just create one and make pull request?

**Comment by robotboy655** [comment]
`resource/language/npc-ents_english.txt`

**Comment by Blueberryy** [comment]
But i mean files (in **.properties** format) that available for public translations from crowdin :p

**Comment by Blueberryy** [comment]
Plus, translation file ```resource/language/npc-ents_english.txt``` has "Alyx" Instead of "Alyx Vance"
