### ISSUE TITLE
CLuaParticle Lighting Issue

### ISSUE THREAD

**Issue by Volantarius** [Facepunch/garrysmod-issues#5302]
Particles don't receive light unless the velocity or gravity is set to a magnitude over 0.001 or so. At the lowest 0.001 is darker than if the magnitude was 0.1. I'm sure its the way the particles interpolate the lighting when moving, but I would think static particles would still receive light.

Tested with various materials and types, the best was "particle/particle_smokegrenade".

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
