### ISSUE TITLE
Long strings on SWEP tables are truncated through level transitions

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-issues#5304]
my CSGO weapons port uses a string to store the weapon attributes from csgo
on a level transitions, the length of the string is truncated to 1023 characters (+1 for null byte), where normally they're ~2000 characters long.
i think the issue lies with https://wiki.facepunch.com/gmod/ISave:WriteString

**Comment by robotboy655** [comment]
Are you specifically using [ISave:WriteString](https://wiki.facepunch.com/gmod/ISave:WriteString) in your code?

**Comment by homonovus** [comment]
no, i'm not using any code for level transitioning. just letting gmod do it for me
issue is that strings longer than 1024 on a SWEP's table won't be saved in their entirety when a level transition happens
https://gitlab.com/cynhole/swcs/-/blob/master/lua/weapons/weapon_swcs_deagle.lua#L152

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta and in the next game update.
