### ISSUE TITLE
file.Find Wildcard does not return folders

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5306]
## Details
If you use file.Find with a wildcard, it does not return any folders.
It doesn't work on all Garry's Mod branches.

### Works
local files, folders = file.Find("lua/autorun/*", "GAME")
PrintTable(folders)

Output:
```
1	=	client
2	=	properties
3	=	server
```

### Doesn't Work
local files, folders = file.Find("lua/autorun/*.lua", "GAME")
PrintTable(folders)

Output:
``````

**Comment by Kefta** [comment]
This is expected behaviour. No folders match *.lua

**Comment by RaphaelIT7** [comment]
it would be better when it returns folders containing targeted files

**Comment by robotboy655** [comment]
file.Find does not recursively check folder contents. You can do it yourself. This is intentional behavior.
