### ISSUE TITLE
`poster` command crashes players when high number is used.

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5307]
### Details
The poster console command can crash players games when a too high multiplier is used.
I've tested this on 64x, the big issue with this is that poster is not a blacklisted command and thus can be used to forcefully crash players.
I'm not sure if this affects 32 bit too.

Even if the crash is fixed, servers can theoretically spam the command to fill the targets pc up with screenshots. Might want to blacklist this command entirely from being ran through lua.

### Steps to reproduce
1. run `ply:ConCommand( "poster 512")` on a 64x player from server or client side
2. client crashes

**Comment by brandonsturgeon** [comment]
`poster` should probably just be added to the Blocked Console Commands - the Camera weapon uses `jpeg` which should be all any addon needs.

**Comment by colemclaren** [comment]
It looks like the game is smart enough to check the maximum amount of memory available to allocate before performing the command. So this doesn't crash for me:
```
] poster 512
Allocating 1.0 GB for poster
Couldn't allocate memory for poster.
] poster 256
Allocating 2.3 GB for poster
Couldn't allocate memory for poster.
] poster 100
Allocating 1.2 GB for poster
Couldn't allocate memory for poster.
```
Also, when running this command from the server using ConCommand, the client's console says:
```
FCVAR_SERVER_CAN_EXECUTE prevented server running command: poster
```

**Comment by wrefgtzweve** [comment]
Instantly crashes my and multiple friends games when used on 64x

**Comment by colemclaren** [comment]
Yup, this has done it for me. This crashes the game: `lua_run_cl LocalPlayer():ConCommand( "poster 512" )`

Why is the ConCommand behavior different than the regular console behavior? Why doesn't ConCommand perform the same check for the maximum amount of memory available to allocate before it performs the command?

**Comment by wrefgtzweve** [comment]
Running it directly in the console also crashes it for everyone i know, i don't get why it doesn't do that in the first place for you.

**Comment by colemclaren** [comment]
> Running it directly in the console also crashes it for everyone i know, i don't get why it doesn't do that in the first place for you.

I don't know why either. I guess it crashes for me too now as well. Last night it did not, but after restarting my computer this morning, the command crashes me too now as well. This makes zero sense. I don't know how I replicate the memory allocation being checked before it performs the command either. I thought it was default behavior.

**Comment by robotboy655** [comment]
Hopefully fixed.
