### ISSUE TITLE
Strange http.Fetch invalid url error

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5308]
### Details
The http.fetch and HTTP functions seem to have some very strange URL verifiers that block some valid URLs.
For example, it seems that any URL containing `10.` will get flagged as an invalid URL, even though it is definitely a valid URL. (For example, useful if IPs are encoded in the URL). `20.1` works while any string after `10.` will cause this error.

### Steps to reproduce
```LUA
http.Fetch("https://google.com/10.1", function()
    print("success")
end, print)

HTTP({
    url = "https://google.com/10.1",
    method = "GET",
    success = function() print("DONE") end,
    failed = print
})
```

**Comment by FlorianLeChat** [comment]
Probably a duplicate of #4133

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4133
