### ISSUE TITLE
EntityFireBullets hook returns invalid bullet data

### ISSUE THREAD

**Issue by EntityinArray** [Facepunch/garrysmod-issues#5309]
### Details
Good day! Thank you for working on this legendary sandbox game!
I've ran into an issue with EntityFireBullet hook, that seems to be a bug.
EntityFireBullets hook always returns bulletData.Damage = 0 at all times (when bullets are fired by anything)
and also returns bulletData.Attacker = [NULL Entity] when bullets are fired by NPCs only

Issue occurs on both serverside and clientside, with HL2 weapons and SWEPS (i tested ARCCW)
I disabled all addons and emptied the addons folder

Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit

Console log:
[console.log](https://github.com/Facepunch/garrysmod-issues/files/9386586/console.log)
Video demonstrating the problem:
[bug.webm](https://user-images.githubusercontent.com/18554021/185738639-783252ee-7f37-4f1b-bb12-a0766d42b81f.webm)

### Steps to reproduce

1. Execute this code in game on the server and on the client:
```
hook.Add("EntityFireBullets","bulletdamagetest",function(ent,bulletData)
  print(ent)
  PrintTable(bulletData)
end)
```
2. Notice how bulletData returns invalid data, its bulletData.
Damage is 0 at all times, and bulletData.Attacker is [NULL Entity] when fired by NPCs

**Comment by robotboy655** [comment]
Damage = 0 means use the ammo type's convars for the damage, which is used by all base weapons except for `weapon_base`.
I have added this info to the wiki.

As for `Attacker` being null for NPCs, you literally have the entity which shot the bullet as an argument, but I guess it is something that can be looked into.

**Comment by robotboy655** [comment]
The `Attacker` issue should be fixed on `dev` beta and in the next game update.
