### ISSUE TITLE
While scrolling - Mouse4 & Mouse5 Activate Randomly

### ISSUE THREAD

**Issue by gmod64bit** [Facepunch/garrysmod-issues#5318]
### Details
```

Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 19:04:48 Jun  1 2022 (8607) (4000)
GMod version 2022.06.10, branch: unknown, multicore: 0
Linux 32bit
```

So, when scrolling, mouse4 binds and mouse5 binds activate randomly. This is irrirating as a professional propkiller, this has been a problem for many years across every propkiller I know on 32 bit. Is there a cure? (64 bit gnu is still broken otherwise I'd use that)

### Steps to reproduce

Have something bound to mouse4 and/or mouse5
Scroll a lot till it activates itself

**Comment by robotboy655** [comment]
And this is definitely game's fault and not your mouse's or you accidentally hitting those keys? I personally never had this issue or heard of it before now.

**Comment by gmod64bit** [comment]
> And this is definitely game's fault and not your mouse's or you accidentally hitting those keys? I personally never had this issue or heard of it before now.

Oh yeah, it's not just me either, this is a wide known problem in the propkill community, when 64 bit came out (at least on the gnu linux client) it seemed to have resolved itself, but on 32 bit it's still like this. Kind of odd but I could never figure it out.
