### ISSUE TITLE
engine error crash

### ISSUE THREAD

**Issue by Minc3** [Facepunch/garrysmod-issues#5321]
Crash when joining certain servers.

It's random so all I can really do is provide the crash log.

https://cdn.discordapp.com/attachments/609605739534614557/1015843079607042148/hl2_220610_crash_2022_9_4T4_33_33C0.mdmp

**Comment by robotboy655** [comment]
The game is likely just running out of memory, it being 32bit puts limits, Try the `x86-64` beta.

**Comment by Minc3** [comment]
What can be done to fix this on the server?
Changing to 64 bit is a work around but other people are having the same issue.

**Comment by Minc3** [comment]
The server I play frequently is having this problem.
Looks like it's mostly on join this issue.

**Comment by Kefta** [comment]
Ask them to switch to 64 bit or use less client memory with your scripts and resources.
