### ISSUE TITLE
Registration of "PlayerUse" Hook on Server restart does not work.

### ISSUE THREAD

**Issue by Noname12345GER** [Facepunch/garrysmod-issues#5322]
The PlayerUse hook does not work if added to a script normally.

**Example:**

```
hook.Add("PlayerUse", "SomeUseHook", function(ply, target)
	ply:ChatPrint("You left a Fingerprint on the Button...")
end);
```

You need to hook InitPostEntity and from that hook trigger a 10 second timer that will then initialize PlayerUse.

**Workaround:**

```
hook.Add("InitPostEntity", "SomeHookLoader", function()
	timer.Simple(10, function()
		hook.Add("PlayerUse", "SomeUseHook", function(ply, target)
			ply:ChatPrint("You left a Fingerprint on the Button...")
		end);
	end)
end)
```

**Comment by robotboy655** [comment]
No, you are most likely overwriting the hook you are adding somewhere else with the same hook name.
