### ISSUE TITLE
ent:StartTouch() ignores worldspawn entity

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-issues#5323]
### Details
An entity using start touch and properly setup will detect when it collides with any entity other than worldspawn. This is making it rather difficult to make entities that instantly stop moving when they hit a wall/ground/ceiling. It does however still detect when hitting entities that are part of the world such as door entities

### Steps to reproduce
litterally puting print(ent) at the start of ent:StartTouch(ent)

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/ENTITY:PhysicsCollide ?

**Comment by VaasKahnGrim** [comment]
Unfortunately thats what I'm trying to avoid using due to the "changing collisions within a callback may cause crashes" warning.

I'm trying to make a sticky throable item that when it hits something it "sticks" to it. I tried to solve the problem with timer.Simple() inside PhysicsCollide which stopped some of it but the warning does occassionally still show up.

I was told to try using StartTouch which works for everything besides the worldspawn.

**Comment by VaasKahnGrim** [comment]
I should also mention that using StartTouch seemed to work slightly better since it didn't have a delay due to a timer, so the object stuck instantly instead of moving slightly after touching

**Comment by Kefta** [comment]
> Unfortunately thats what I'm trying to avoid using due to the "changing collisions within a callback may cause crashes" warning.

You can use PhysicsCollide for this, just queue any operations you want to perform until after the physics tick is done (0 second timer).

> I'm trying to make a sticky throable item that when it hits something it "sticks" to it. I tried to solve the problem with timer.Simple() inside PhysicsCollide which stopped some of it but the warning does occassionally still show up.

You are doing something else then to cause the error.

> I was told to try using StartTouch which works for everything besides the worldspawn.

It works completely differently - Touch hooks operate off trigger bounds and don't represent real physics-based collisions. Adding support for worldspawn wouldn't be possible without tying the two systems together which would defeat its purpose.

**Comment by VaasKahnGrim** [comment]
I managed to get it working on PhysicsCollide tho oddly enough it was the same exact code as from before so it makes no sense why its working now without problems. Timer on 0 delay also made it stick instantly too where as before 0.1 had a slight noticable delay.

Marking resolved
