### ISSUE TITLE
Unknown command "rate"

### ISSUE THREAD

**Issue by FarikLoL** [Facepunch/garrysmod-issues#5324]
rate command is missing on my Linux server
On the server that the command is present on Windows

Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 19:30:41 Jun  1 2022 (8607) (4000)
GMod version 2022.06.10, branch: unknown
Linux 32bit Dedicated Server

**Comment by Wryyyong** [comment]
`rate` is intended to be a client-sided command, IIRC.

If you're looking to add limits to what your players have `rate` set to, you'd want `sv_minrate` and `sv_maxrate`.
