### ISSUE TITLE
Env skypaint flickering on big maps

### ISSUE THREAD

**Issue by Midlou** [Facepunch/garrysmod-issues#5327]
### Details
I have two maps that have an issue with the Env skypaint, the sky keeps flickering. This issue only happens on maps with big skybox. When the player spawns a Sky Editor, the sky stops flickering.

On my tests, I have no addons enabled. The console has no errors.
You can check what I'm talking about in this video:
https://youtu.be/AkxtJcBlMXo

The first map is in the Workshop, gm_edge.
https://steamcommunity.com/sharedfiles/filedetails/?id=2143662013

The skybox has a size of ~30000x30000 hammer units.
These are the env_skypaint parameters:

```
entity
{
        "id" "164894"
        "classname" "env_skypaint"
        "bottomcolor" "0.204 0.263 0.306"
        "drawstars" "1"
        "duskcolor" "0 0 0"
        "duskintensity" "0"
        "duskscale" "0"
        "fadebias" "0.5"
        "hdrscale" "0.56"
        "starfade" "0.5"
        "starscale" "2"
        "starspeed" "0.03"
        "startexture" "skybox/clouds"
        "suncolor" "0 0 0"
        "sunnormal" "0 0 0"
        "sunposmethod" "1"
        "sunsize" "0"
        "topcolor" "0.102 0.106 0.133"
        "origin" "0 0 344"
        editor
        {
                "color" "220 30 220"
                "visgroupshown" "1"
                "visgroupautoshown" "1"
                "logicalpos" "[9000 10500]"
        }
}
```

The second map is one I haven't released yet. 
Env_skypaint has the same parameters. 
Skybox size is ~22,000 x 22,000 hammer units

### Steps to reproduce
Create a map with big skybox (+ 22000x22000 hammer units) and add a env_skypaint with startexture skybox/clouds.

**Comment by robotboy655** [comment]
The issue was lack of env_sun entity. Fixed on `dev` beta and in future update.
