### ISSUE TITLE
Hard landing view punch causes Prediction errors despite it being part of the base game code.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5330]
`001 CPlayerLocalData::m_vecPunchAngle - vec[] differs (1st diff) (net 0.000000 0.000000 4.187500 - pred 0.000000 0.000000 0.000000) delta(0.000000 0.000000 -4.187500)`

cl_showerror 2 in console
Hard land so your view teleport tilts, check the console.
I am in MULTIPLAYER.

To fix it I completely nuked ViewPunch functions from the game and it was fine afterwards.

Doesn't bother me because of work arounds, but I wanted to report it.

EDIT:

Didn't notice it was from 5 years ago. #2887

**Comment by robotboy655** [comment]
Fixed.

**Comment by Kefta** [comment]
The issue linked is different but I'm glad to finally see this specific case fixed.
