### ISSUE TITLE
"ToolTracer" effect can start at Weapon Muzzle even if GetStart is set to something else

### ISSUE THREAD

**Issue by Zaurzo** [Facepunch/garrysmod-issues#5331]
### Details
The "ToolTracer" effect can start at the weapon's muzzle the player is currently holding, regardless if it's :SetStart() was set to a different position.

I believe the issue is "self:GetTracerShootPos" on Line 11 in the lua file of the effect. As when I replace it with just "self.Position", it works fine.

It happens on both Singleplayer and Multiplayer. I'm on the x86 - 64 branch, and on version 2022.07.13.

### Steps to reproduce
```
if CLIENT then return end

local ent = ents.Create('prop_physics')
ent:SetModel('models/props_junk/TrashBin01a.mdl')
ent:Spawn()

hook.Add('Think', ent, function()
    local ef = EffectData()
    ef:SetStart(ent:GetPos())
    ef:SetOrigin(Entity(1):GetPos())

    util.Effect('ToolTracer', ef)
end)
```
Running this, it should work fine. Simply firing the Toolgun seems to make the issue happen. The issue seems to have something to do with the Toolgun.
https://user-images.githubusercontent.com/101999193/190879712-0199cf00-908b-47db-8a35-e6a280fdfa4b.mp4

**Comment by robotboy655** [comment]
Make sure to set all the variables the effects expects. Not setting them is the problem.

https://wiki.facepunch.com/gmod/Global.EffectData
https://wiki.facepunch.com/gmod/CEffectData:SetEntity 
https://github.com/Facepunch/garrysmod/blob/e147111b1e5add3853b61efe021c01be0ee10cbd/garrysmod/gamemodes/base/entities/effects/tooltracer.lua#L7
