### ISSUE TITLE
All L4D2 maps break when loading with no HDR

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#5332]
X86-64 branch, Addons on
disable "Settings - Video - Advanced - HDR" then loads a L4D2 map

This might be a feature, but closing HDR after the map loaded does help with some lighting presents, so is there any walkaround not to switching HDR settings?

Windows7  Nv1650S Fullscreen
btw on my computer x64 gmod crashs when starting with "window" or "borderless window", but can switch display modes in game, seems to be a 64bit driver issue.

**Comment by robotboy655** [comment]
It's hard to understand what you are saying, but I think L4D2 maps do not have non HDR lighting, so you can't have non HDR lighting on them.
