### ISSUE TITLE
The properties skip loading the first line from the file

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#5333]
### Details
After you create *.properties file and store it in its proper folder, the game skips loading the first translation from the file when you skip inserting empty line in the first row.

### Steps to reproduce
1. Create tool-name *.properties file for your native in the proper folder
2. Load gmod x64 branch in steam
3. Load a map and click on your tool
4. The first row of the *.propertues file is not translated to your native.
5. Insert one empty row in the *.properties file
6. Reload the spawn menu
7. The first row of your *.properties file is translated now.

More info: https://discord.com/channels/565105920414318602/1020741536511705098

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/211818507-27149f93-c513-42c3-acd2-8174671a69a2.png)
![image](https://user-images.githubusercontent.com/3299036/211821985-314abba6-89a6-4081-909a-db811f70e326.png)

Cannot confirm.

**Comment by dvdvideo1234** [comment]
Hello, @robotboy655

What's to confirm ?
