### ISSUE TITLE
DListView causes crash when fixed-width columns overflow with decimal numbers

### ISSUE THREAD

**Issue by luca1197** [Facepunch/garrysmod-issues#5334]
### Details
When adding columns to a `DListView` and calling `SetFixedWidth` on them, the game will crash if the columns total width exceeds the width of the `DListView` and the width has decimal places. The example below demonstrates the behavior better than my description, I think.

Occurs on the default and x86-64 branch.
Tested default branch game version: `2022.06.10`
Tested x86-64 branch game version: `2022.07.13`

At first this may not seem important since you would seemingly have to cause this crash intentionally, but that is not true. This sometimes happens when calculating the width for each column e.g. by multiplying a number. In this case for example, you could also cause a crash by not using fixed numbers in the `SetFixedWidth` function, but instead something like `listViewW * 0.25`. This is a common way to space out the columns of a table in my opinion, and I experienced crashes because of this issue several times during normal development already. This is not consistent though, because you have to kind of get unlucky with how the numbers turn out, I think. 

### Steps to reproduce
The following example demonstrates the behavior described above. The column labeled "Column A" will crash the game, the one labeled "Column B" (Commented out) will not crash the game. Setting the fixed width to something like `389.123456` which is less than the `DListView` width in this case, does not cause a crash.

```lua
concommand.Add("dev_dlistview_overflow", function()
	local frame = vgui.Create("DFrame")
	frame:SetSize(400, 300)
	frame:Center()
	frame:MakePopup()

	local listView = vgui.Create("DListView", frame)
	listView:Dock(FILL)
	listView:InvalidateParent(true) -- Update panel bounds from docking

	local listViewW = listView:GetWide() -- 390px (5px docking margin on each side)
	listView:AddColumn("Column A"):SetFixedWidth(390.123456) -- Overflow, crash
	-- listView:AddColumn("Column B"):SetFixedWidth(391) -- Overflow, no crash
end)
```

**Comment by robotboy655** [comment]
Will be fixed in the next update.
