### ISSUE TITLE
render.Capture

### ISSUE THREAD

**Issue by TTMACInfinity** [Facepunch/garrysmod-issues#5336]
render.Capture always prints a black screen for me when i try and use my code and other peoples code!

**Comment by CornerPin** [comment]
You are using it outside of a render hook. From the Garry's Mod Wiki description of [`render.Capture`](https://wiki.facepunch.com/gmod/render.Capture):

> Since the pixel buffer clears itself every frame, this will return a black screen outside of. To capture the user's final view, use [GM:PostRender](https://wiki.facepunch.com/gmod/GM:PostRender).
