### ISSUE TITLE
SetNWFloat and SetNWVector have floating point precision errors

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5337]
### Details
SetNWFloat and SetNWVector both have a floating point precision error after 10 seconds.

#### floating point precision error
```lua
Entity(1):SetNWFloat("Key", 1.1)

timer.Simple("10", function ()
	print(Entity(1):GetNWFloat("Key"))
end)
```
Server: 1.1
Client: 1.1000000238419

```lua
Entity(1):SetNWVector("Key", Vector(1.1, 1.1, 1.1))

timer.Simple("10", function ()
	print(Entity(1):GetNWVector("Key"))
end)
```
Server: 1.100000 1.100000 1.100000
Client: 1.093750 1.093750 1.093750

**Comment by Kefta** [comment]
This is intentional - they're not the same size as Lua floats and Vectors are especially compressed.
