### ISSUE TITLE
help this thing keeps spamming my console and i dont know how to fix it...

### ISSUE THREAD

**Issue by EmmaDev170** [Facepunch/garrysmod-issues#5343]
![imagen_2022-10-27_080706614](https://user-images.githubusercontent.com/114527329/198292746-ec17bc0c-8223-45dc-ba81-f551c39fd00b.png)

**Comment by robotboy655** [comment]
If you are a developer, look for code that uses `cam.Start` and its variants. If you are a player, you will have to find what addon causes it and get rid of it.
