### ISSUE TITLE
EFL_KEEP_ON_RECREATE_ENTITIES is ignored by CleanUpMap

### ISSUE THREAD

**Issue by mushroom-guy** [Facepunch/garrysmod-issues#5344]
### Details
Adding EFlag EFL_KEEP_ON_RECREATE_ENTITIES to an entity won't stop it from being removed when restarting entities.

### Steps to reproduce
lua_run Entity(1):GetEyeTrace().Entity:AddEFlags(EFL_KEEP_ON_RECREATE_ENTITIES)
gmod_admin_cleanup

**Comment by shadow7483147** [comment]
Pretty sure game.CleanupMap is intended to fully reset the map without having to restart it. It's not a "round clear" like after a game end in something like Counter Strike. If the entity didn't exist on the map when the map started up, it's deleted, and KEEP_ON_RECREATE_ENTITIES is probably never even referred to unless through lua. (CleanupMap does have a table of ents not to clean as its second arg)

**Comment by robotboy655** [comment]
Should be respecting that flag now, on Dev beta.
