### ISSUE TITLE
propspawn effect removes RenderOverride function

### ISSUE THREAD

**Issue by mushroom-guy** [Facepunch/garrysmod-issues#5345]
### Details
propspawn does not keep the previous RenderOverride value before setting its own. When the effect dies it sets ParentEntity's RenderOverride to nil. This can be avoided if you set cl_drawspawneffect to 0 or if you manually check if your entity has SpawnEffect (removing it if so).

**Comment by robotboy655** [comment]
Will be fixed in the next update. 

https://github.com/Facepunch/garrysmod/commit/7a9f7c50953a4c669efbd4cf3e5b48427ff9f41f
