### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by LitteraryUser** [Facepunch/garrysmod-issues#5347]
IDK WTH happends. MiniDump is pinned (rename from txt to mdmp)
[Steam_2022_11_05__08_28_11_999.txt](https://github.com/Facepunch/garrysmod-issues/files/9943591/Steam_2022_11_05__08_28_11_999.txt)

**Comment by robotboy655** [comment]
By the looks of it, the crash is in `NvFlexReleaseD3D_x86.dll` which is not part of the game.
