### ISSUE TITLE
Entity:GetModelBounds() returns wrong values for some models

### ISSUE THREAD

**Issue by Kuma96** [Facepunch/garrysmod-issues#5356]
**Details**
As far as I am concerned, Entity:GetModelBounds() is supposed to return the same values that are defined in $bbox within a model's QC file (sorry if I am mistaken).

This works correctly for most models, but I have run into a situation where, for certain models, one or more of the output values provided by this function are incorrect.

For example, I have two different models for which I have used the following bounding box:
mins = (-30, -30, 0)
maxs = (30, 30, 44)
 
When those models are spawned, the values provided by GetModelBounds are the following:
Model 1: (-36.596565, -30.000000, 0.000000), (30.000000, 30.000000, 44.369152)
Model 2: (-30.000000, -30.000000, -9.308764), (30.000000, 30.000000, 44.000000)

I have used HLMV to verify that $bbox was correctly defined in the QCs. I have decompiled the models as well and the $bbox lines were normal. Basically, it appears that, in Gmod, the $bbox values are not being read from the mdl files "as is".

**Version of Gmod**
2022.06.10 (latest)

**Steps to reproduce**

1. Spawn an entity using ents.Create.
2. Set its model to one of the affected models.
3. Call GetModelsBounds for this entity and print the values.

Again, sorry if I have misunderstood the use of this function.
Will provide the source files of the models upon request.

**Comment by robotboy655** [comment]
IIRC model bounds also includes all sequences/animations of the model. You can try https://wiki.facepunch.com/gmod/Entity:GetModelRenderBounds

**Comment by Kuma96** [comment]
Yes, GetModelRenderBounds returns the original bounding box.
I would appreciate that this info were on the wiki though.
