### ISSUE TITLE
steamworks.DownloadUGC downloads a extremely large gma (over 4 gigabytes) from this (or some) very small addon(s)

### ISSUE THREAD

**Issue by Zaurzo** [Facepunch/garrysmod-issues#5357]
### Details
**Branch: x84 - 64
Version: 2022.07.13**

An Addon (Blur UI) seems to really hate steamworks.DownloadUGC, because it downloads an extremely large gma from it even though the addon is 3kb. This is only one addon I've found that DownloadUGC does this on, not sure if there is more.

https://user-images.githubusercontent.com/101999193/202045253-f9f0784e-afd5-4c75-9b3a-576b3b1f29ff.mp4

### Steps to reproduce
Simply use **steamworks.DownloadUGC** and provide "1782190410" (Blur UI Spawn Menu Workshop ID) as the ID. Checking the cache/workshop folder reveals it's over 4 gigabytes. Yikes.

**Comment by robotboy655** [comment]
Apparently that addon has its size header set to 0xFFFF which translates to 4GB. I will switch DownloadUGC to use the same system as subscriptions, so it should work correctly (and use less memory when extracting)
