### ISSUE TITLE
Downloading extremely large workshop files displays size incorrectly

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5360]
### Details
Downloading workshop files whose _uncompressed_ size is greater than 2^31-1 bytes will lead to integer overflow and display incorrectly. Oddly, this can result in download sizes of ~2^64 bytes being displayed incorrectly.

Presumably this occurs due to size of individual addons being obtained as signed 32 bit integers, which are then summed up as 64 bit unsigned integers (or while converting them to a human readable GB size?).

It should be noted that while displaying the size is incorrect, it appears that downloading such a large file still works as expected.

**Comment by robotboy655** [comment]
Where exactly is this a problem? Which UI element? Server loading screen? Subscriptions UI at the bottom? steamworks.DownloadUGC UI?

**Comment by FredyH** [comment]
Sorry, I should've been more specific. I am referring to the server loading screen that goes from connecting to downloading workshop content, loading lua, etc.

**Comment by robotboy655** [comment]
It's kind of a Steam issue, but it should be fixed for addons up to 4GB, which you should never have anyway.
