### ISSUE TITLE
ents.FindByModel ignores CS:S breakable props

### ISSUE THREAD

**Issue by ReverendV92** [Facepunch/garrysmod-issues#5364]
### Details
When using [ents.FindByModel](https://wiki.facepunch.com/gmod/ents.FindByModel) and putting a breakable prop from CS:S (such as `models/props/cs_office/radio.mdl`), it will always return no results.

If you put a non-breakable prop from CS:S into the search (such as `models/props/de_nuke/LifePreserver.mdl`) , or even recompile the model with no changes, it works instantly.

### Steps to reproduce
Here's the code I'm currently using which can be used to debug.
```
-- Create our model table
local RadioModelTable = {}

-- Find the common HL2 radio
for k , v in pairs( ents.FindByModel( "models/props_lab/citizenradio.mdl" ) ) do

	print("HL2")
	-- Add it to the table
	table.insert( RadioModelTable , v )

end

-- Find the CS_Office radio
for k , v in pairs( ents.FindByModel( "models/props/cs_office/radio.mdl" ) ) do

	print("office")
	-- Add it to the table
	table.insert( RadioModelTable , v )

end

-- Print our radio models
PrintTable( RadioModelTable )
```

**Comment by robotboy655** [comment]
I would imagine it's more of a case sensitivity issue.

**Comment by ReverendV92** [comment]
The path `models/props/cs_office/radio.mdl` is the exact casing used in CS:S. Swapping it for `models/props/de_nuke/LifePreserver.mdl` (exact original casing) works, and converting that to `models/props/de_nuke/lifepreserver.mdl` or `MODELS/PROPS/DE_NUKE/LIFEPRESERVER.MDL` also works.

I did more testing and have discovered it also affects every other breakable prop in CS:S. Using breakable props from HL2 or DoD:S works fine. I also forced the case to all lowercase or uppercase to confirm. 

Other CS:S props such as `models/props/CS_militia/bottle01.mdl` or `models/props/cs_office/coffee_mug.mdl` have the same issue, but DoD:S props such as `models/props_foliage/potted_plant1.mdl` or `models/props_misc/claypot03.mdl` work flawlessly.

**Comment by robotboy655** [comment]
Ok, I think I know what's going on here, if used clientside, the function would immediately quit if the model name is not networked from server to client, and I think they are networked only lowercase. I don't know why this is, so I will be getting rid of this behavior for the next update. Serverside it works perfectly for me.
