### ISSUE TITLE
Changes made to the SubMaterials of a bonemerged entity are not saved by the duplicator

### ISSUE THREAD

**Issue by kuma7X** [Facepunch/garrysmod-issues#5365]
### Details
After setting the parent of an entity, we can still change the SubMaterials of the child entity. However, those changes are not saved/stored. That means that when the parent is duplicated, the duplicated constraint used for the child entity won't keep the changes made to the SubMaterials of the original entity.

### Steps to reproduce
Even though I didn't experience this problem with the Easy Bonemerge Tool, the easiest way of reproducing it is changing the following code of such a tool:

```
function TOOL:LeftClick( tr )
	local ent = self:GetSelectedEntity()
	if ( IsValid( tr.Entity ) && tr.Entity:GetClass() == "prop_effect" ) then tr.Entity = tr.Entity.AttachedEntity end

	if ( !IsValid( ent ) || !IsValid( tr.Entity ) || tr.Entity == ent || tr.Entity:IsPlayer() || tr.Entity:IsNPC() || tr.Entity:GetModel():StartWith( "*" ) ) then return false end

	if ( CLIENT ) then return true end

	--[[print( "side-by-side", CountEntitysBonemergeAmount( ent ) )
	print( "depth", CountEntitysBonemergeDepth( ent ) )
	if ( GetConVarNumber( "rb655_easy_bonemerge_maxmerges" ) < CountEntitysBonemergeAmount( ent ) ) then
		// error message
		return false
	end]]

	local newEntity = rb655_ApplyBonemerge( tr.Entity, ent )
	
	--NEW CODE
	newEntity:SetSubMaterial(0, "models/shiny")

	undo.Create( "bonemerge" )
		undo.AddEntity( newEntity )
		undo.SetPlayer( self:GetOwner() )
	undo.Finish()

	return true
end
```

By doing this, the first SubMaterial of the child entity is set to "models/shiny" as soon as it is bonemerged to its parent. When the parent is duplicated, said SubMaterial reverts back to its default value.

Note that this problem does not happen if SubMaterials are set before bonemerging.

### Version of the game
Latest (no beta branch)

**Comment by robotboy655** [comment]
I will make the default duplicator save submaterials by default, if they are overridden.
