### ISSUE TITLE
util.JSONToTable doesn't read array elements more than 15,000

### ISSUE THREAD

**Issue by ZenkakuHiragana** [Facepunch/garrysmod-issues#5366]
### Details

Running the following code shows that tables constructed by `util.JSONToTable` won't have more than 15,000 elements.

I think `util.TableToJSON` is fine because the output of `file.Write( "test.txt", json )` seems no problem.

```Lua
local t = {}
for i = 1, 20000 do
  t[i] = i
end

local json = util.TableToJSON( t )
print( #t ) -- 20000
print( #util.JSONToTable( json ) ) -- 15000
```

Tested on default branch and x86-64 branch.

**Comment by CornerPin** [comment]
This is due to #3526. Some possible solutions would be to upgrade LuaJIT or to apply one of these fixes:

- https://github.com/LuaJIT/LuaJIT/pull/294
- https://github.com/LuaJIT/LuaJIT/commit/ff34b48ddd6f2b3bdd26d6088662a214ba6b0288

Though, it doesn't make sense to have this limit for JSON arrays, as they shouldn't be affected by hash DoS.

**Comment by ZenkakuHiragana** [comment]
A possible workaround I have is to split the array into multiple small arrays with 15,000 elements, but it looks awful to me.

```Lua
local function split( source )
    local result = {}
    for chunk = 1, math.ceil( #source / 15000 ) do
        local t = {}
        for i = 1, 15000 do
            local index = ( chunk - 1 ) * 15000 + i
            if index > #source then break end
            t[ #t + 1 ] = source[ index ]
        end
        result[ chunk ] = t
    end
    return result
end

local function merge( source )
    local result = {}
    for _, chunk in ipairs(source) do
        for _, value in ipairs(chunk) do
            result[ #result + 1 ] = value
        end
    end
    return result
end

local t = {}
for i = 1, 20000 do
  t[i] = i
end

local json = util.TableToJSON( split( t ) )
print( #t ) -- 20000
print( #merge( util.JSONToTable( json ) ) ) -- 20000
```

**Comment by robotboy655** [comment]
Added 2 optional arguments to util.JSONToTable:
* first - true to ignore the depth and breadth limits, use at your own risk.
* second - true to ignore string to number conversions
