### ISSUE TITLE
Reloading game doesn't reset render.SetLightingMode

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5368]
Setting render.SetLightingMode to 1 or 2 and reloading the game causes the LightningMode to persist. Tested in Chromium + 64-bit binaries

**Comment by robotboy655** [comment]
It is now reset on map shutdown/reload. I decided against resetting it every frame to avoid breaking addons relying on this behavior.

**Comment by RaphaelIT7** [comment]
Could this please also be done for https://github.com/Facepunch/garrysmod-issues/issues/3105?
