### ISSUE TITLE
Entity:GetMaxHealth does not updates automatically

### ISSUE THREAD

**Issue by aL1NaZ4R** [Facepunch/garrysmod-issues#5372]
### Details
When I was coding my HUD addon, I realized that Entity:GetMaxHealth does not updates immediately after Entity:SetMaxHealth.
You have to jump to update the value.

### Steps to reproduce
Create a lua file in autorun directory, and paste these:
```
if SERVER then
	AddCSLuaFile()
	Entity( 1 ):SetMaxHealth(1000)
end

if LocalPlayer then
    local function Test()
        local myplayer = LocalPlayer()
        print(myplayer:GetMaxHealth())
    end
    hook.Add( 'HUDPaint', 'Test', Test )
end
```
Save.
Then type in console: `developer 1`
Modify the player's Maximum health (the number 1000) to anything you want, and save the file to apply them in game.
Now watch the `developer 1` logs. The number will not change until you jump (jump is working for all weapons, if you have Crowbar, then you can do it by left clicking too.)

**Comment by aL1NaZ4R** [comment]
> This is expected behaviour - you need to set it shared otherwise the client won't know about the value until a fullupdate.

so, i should run this code in `if SERVER` ?

**Comment by Kefta** [comment]
No the opposite, it should be called shared in a predicted context if possible.

**Comment by robotboy655** [comment]
You can learn about prediction here: https://wiki.facepunch.com/gmod/Prediction
