### ISSUE TITLE
weapon_pistol bypasses SetNextPrimaryFire

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5373]
### Details
The standard HL2 weapon **9mm pistol** `weapon_pistol` resets his `m_flNextPrimaryAttack` every frame. It sets the variable to **-0.1s** (`CurTime() - 0.1`) after Lua call. So the weapon will always shoot, despite of the `SetNextPrimaryFire`.

### Steps to reproduce
- Call `weapon:SetNextPrimaryFire(CurTime() + 60)` on `weapon_pistol`
- Call `print(weapon:GetNextPrimaryFire() - CurTime())` or `print(weapon:GetInternalVariable("m_flNextPrimaryAttack"))` and you will see that it has been reset.
- You still can shoot.

```
hook.Add(
	"Think",
	"5373_test",
	function()
		local weapon = Entity(1):GetActiveWeapon()
		print(
			weapon,
			weapon:GetNextPrimaryFire(),
			weapon:GetInternalVariable("m_flNextPrimaryAttack"),
			weapon:GetNextPrimaryFire() - CurTime()
		)
	end
)
```

```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

**Comment by robotboy655** [comment]
It's not a bug,

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/weapon_pistol.cpp#L313-L317

**Comment by TIMONz1535** [comment]
I tried `weapon:SetSaveValue("m_flSoonestPrimaryAttack", CurTime() + 60)` but it does nothing on SV, also `weapon:GetInternalVariable("m_flSoonestPrimaryAttack")` returns `nil` on SV

**Comment by Kefta** [comment]
m_flSoonestPrimaryAttack is not an exposed entity variable.
