### ISSUE TITLE
do_constraint_system: Couldn't invert rot matrix!

### ISSUE THREAD

**Issue by nutellabrot2** [Facepunch/garrysmod-issues#5374]
Hi,

do_constraint_system: Couldn't invert rot matrix!

This error is spammend in my Console when i spawn a car or anything, The props also just freeze in the air

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5274

**Comment by nutellabrot2** [comment]
so i cant fix it or what?!

**Comment by Kefta** [comment]
Read my comment on the duplicate issue.
