### ISSUE TITLE
Crash during navmesh SAMPLE_WALKABLE_SPACE 

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-issues#5375]
### Details
I start generating a navmesh on a huge, huge map.
Game gets into the process, but then crashes after say 11 "sampling walkable space" messages.
The actual count of messages differs between maps.

### Steps to reproduce
Load into a very large map.
This happens repeatedly for me, on [gm_harborside](https://steamcommunity.com/sharedfiles/filedetails/?id=815824352),
[rp_mezs](https://steamcommunity.com/sharedfiles/filedetails/?id=2810787481),
And [gm_dark forest](https://steamcommunity.com/sharedfiles/filedetails/?id=2902463492)

Run nav_generate ( harborside needs a new seed position )
Wait...
Your game session should get stuck, showing "Sampling walkable space..."

Here's what this looks like for me. Specifically gm_dark forest.
![image](https://user-images.githubusercontent.com/64710817/209448780-2410bff0-ab47-48db-b8fe-d55719bb1403.png)

Hope this is fixable!

**Comment by StrawWagen** [comment]
Can workaround this with nav_generate_incremental but it's a pain.

**Comment by StrawWagen** [comment]
Been generating lots of navs.
This only ever happens on maps with displacements.

If a map has no displacements, it never crashes.
Maps with displacements sometimes crash.

I'm not as sure about this part aswell, but i think that this only happens when displacements but-up against the "sides" of maps.

Hope this can help!

**Comment by robotboy655** [comment]
I cannot reproduce any crashes on those maps, gm_harborside and gm_dark forest are the ones I tried.
Both pass the `Sampling walkable space..` stage and move onto a very slow `Computing mesh visibility..` stage.

Given that there are no dumps for me to look at, I have to assume the issue is you simply running out of memory, so try without any addons but the map.
