### ISSUE TITLE
Gmod crashing on Chromium x64 branch

### ISSUE THREAD

**Issue by Knuwing** [Facepunch/garrysmod-issues#5378]
I am using Linux Mint 21.1 Cinnamon. I got Gmod to work perfectly fine normally on x32, but when I switch to the x64 chromium branch it crashes on the facepunch logo saying "Initiliazing serverside". No idea what is causing this, but I want to preferrably use the x64 branch as the x32 runs out of memory alot, therefore causing a lua panic.

**Comment by ExtReMLapin** [comment]
poor rubat will soon have 1000 issues stacked up

**Comment by Foxxy-01** [comment]
same i have this issue too

**Comment by thennothinghappened** [comment]
have a look into [GModCEFCodecFix](https://github.com/solsticegamestudios/GModCEFCodecFix)... not sure why this is still an issue with the base game, but this patch fixes it.

**Comment by thennothinghappened** [comment]
hmm?
