### ISSUE TITLE
string.StartsWith

### ISSUE THREAD

**Issue by c0nfusecode** [Facepunch/garrysmod-issues#5379]
gmod wiki
![firefox_RxX2Gfdgaj](https://user-images.githubusercontent.com/55307836/210369654-5bbd94ec-80e7-450d-b2dc-0babfaa3feea.png)
Real life
![WindowsTerminal_hYNKa7EZDy](https://user-images.githubusercontent.com/55307836/210369756-02a91b0d-e684-4ce9-bfb1-90aa69077b82.png)

lol string.StartWith work xd
![WindowsTerminal_Z3tWMuptNi](https://user-images.githubusercontent.com/55307836/210370530-90215e92-329a-43af-bec5-c85ecb9b4932.png)

**Comment by CornerPin** [comment]
This function is currently in the dev branch.

**Comment by c0nfusecode** [comment]
whoops my bad
