### ISSUE TITLE
os.date() doesn't show %y or %Y on the Server

### ISSUE THREAD

**Issue by SparkleArts** [Facepunch/garrysmod-issues#5384]
I don't know if this is a bug, but I try to add Time on the HUD for a Server where I'm a Developer.

It works well but it doesn't show the Year at all. It just blank.

This is the Code Snippet I use:

`local Timestamp = os.time()`
`local TimeString = os.date( "%H:%M:%S - %d.%m.%y" , Timestamp )
`
`return TimeString`
			
I'm using HUD-Maker Addon from gmodstore and I added a new Text Variable that I can use in game for the HUD. Above is this snappet of this Variable.

**Comment by SparkleArts** [comment]
It seems that %y can only show only with %d.%m.%Y in the String Format wwithout other Variables.

**Comment by robotboy655** [comment]
Cannot confirm it being an issue:
![image](https://user-images.githubusercontent.com/3299036/212340195-a0577c42-6dd8-49cb-b02b-1e6e3999119d.png)

If you are having an issue with a paid addon, perhaps you should contact the addon developer instead.

**Comment by Kefta** [comment]
Probably OS-specific
