### ISSUE TITLE
CallOnClient "Reload" doesn't work on gmod_tool in singleplayer

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#5387]
### Details
Both "PrimaryAttack" and "SecondaryAttack" work fine, but "Reload" seems to fail at the KeyPressed check [here.](https://github.com/Facepunch/garrysmod/blob/213deeabbee280251464f55567090fcaba6655fd/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua#L264) 

### Steps to reproduce
```
function TOOL:Reload( tr )
    if game.SinglePlayer() then
        self:GetWeapon():CallOnClient( "Reload", "" )
        if CLIENT then print( "Reload" ) end
    end
    return true
end
```

**Comment by robotboy655** [comment]
So `CallOnClient` does work then..

**Comment by Wryyyong** [comment]
If I may...

Is there any specific reason you're trying to run `CallOnClient` for the SWEP's `Reload` function... _within the SWEP's `Reload` function_?

**Comment by robotboy655** [comment]
Presumably to have it be called on client, which can be achieved with a simple net message (call the Tool's Reload method directly, or just run whatever code you need directly).

**Comment by Wryyyong** [comment]
Riiight, forgot that `Reload` was predicted.
