### ISSUE TITLE
workshop download display error when join server

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-issues#5389]
![image](https://user-images.githubusercontent.com/36387604/213288215-c6fe9804-6340-4931-9220-7ac867c6fd5e.png)

when download a workshop addon that is chinese title  like https://steamcommunity.com/sharedfiles/filedetails/?id=2916324308
the text display on progress bar is error

**Comment by GrayWolf64** [comment]
Does any other source engine MP games which have this kind of loading bar have the same localization bug?
You should ensure that whether this is a sdk problem, or steamworks bug, or something else.

**Comment by robotboy655** [comment]
Will be fixed.
