### ISSUE TITLE
+gamemode launch option doesnt work

### ISSUE THREAD

**Issue by fazmade** [Facepunch/garrysmod-issues#5393]
### Details
using +gamemode in the steam launch options will still load into the sandbox gamemode

### Steps to reproduce
1. add +gamemode (gamemode name) to the launch options
2. start gmod
3. the game mode is sandbox

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/214124280-578da6f5-f25e-42ae-aed7-5b5e2832f1fd.png)

That looks like it works just fine to me? I imagine it work very well with workshop gamemodes because those are mounted after the game launches.

**Comment by fazmade** [comment]
weird, it didnt work before but now it does
