### ISSUE TITLE
January 2023 update caused unwanted behaviour in TOOL:Holster

### ISSUE THREAD

**Issue by kuma7X** [Facepunch/garrysmod-issues#5398]
### Details
I've seen that in the recent January 2023 update, some changes were made to TOOL:Holster and TOOL:Deploy. Well, it seems that TOOL:Holster isn't called after WEAPON:Holster or when switching between different tools anymore (it was before and that's what the wiki says). I used this feature in one of my addons in order to detect when a tool's owner has changed his currently equipped tool, but the changes introduced in this update are causing it to fail. I'm not sure if TOOL:Deploy is still working as intended or it's affected by the bug too.

### Steps to reproduce
Simple example that illustrates this problem:

```
function TOOL:Holster()
	if not IsValid(self:GetOwner()) then return end
	local mytool = self:GetOwner():GetTool("mytool_name")
	
	print(mytool)
	print(self:GetOwner():GetTool()) --currently equipped tool, which is always equal to mytool
	
	if mytool and mytool != self:GetOwner():GetTool() then
		--this code isn't running anymore
	end
end
```

### Version of the game
Latest at the time of submission of this report (no beta branch)

**Comment by robotboy655** [comment]
It is most definitely still being called in those scenarios, but it is no longer called clientside when switching tools. This mimics behavior of `TOOL:Deploy`.

If you want to detect tool changes, your best option is to adding an on-change hook to `gmod_toolmode` via https://wiki.facepunch.com/gmod/cvars.AddChangeCallback clientside.
