### ISSUE TITLE
January 2023 Update Broke Access to scriptedpanels.lua

### ISSUE THREAD

**Issue by Bryantdl7** [Facepunch/garrysmod-issues#5399]
Hello! 

There appears to be a severe issue with the January 2023 update, which is only reproducible when certain addons try and call the /garrysmod/lua/includes/extensions/client/panel/scriptedpanels.lua file, any addon which requires this file is erroring saying File not found. 

**For instance:** 
[acf-custom] Couldn't include file 'acf\client\cl_acfcustom_gui.lua' - File not found (@lua/includes/extensions/client/panel/scriptedpanels.lua (line 116))
  1. RegisterFile - lua/includes/extensions/client/panel/scriptedpanels.lua:116
   2. func - addons/acf-custom/lua/weapons/gmod_tool/stools/acfcustom.lua:55
    3. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:134
     4. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:126
      5. ActivateTool - lua/includes/modules/spawnmenu.lua:116
       6. DoClick - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:131
        7. unknown - lua/vgui/dlabel.lua:237

Now, the instant thought would be to complain to the developer about this problem, but the error itself is that the addon is no longer able to access the file in question, outside of the scope of the addon. 

Furthermore, this issue does not occur on any servers who have been slow to update, and are on the older version of gmod server. We have a test server where we test changes, and we were unable to make this error occur, until we realized the server was out of date, once the latest "stable" update was installed, this error is reproducible on all of our servers. 

I would love to be told that this is a problem with our addons and be pointed to the place we need to fix it, but our developer keeps coming to the same conclusion that the issue lies within gmod itself. Here's the source code if anyone wants to take a stab at proving me wrong: https://github.com/bouletmarc/ACF_CustomMod

**Is there any way we can roll our server back? to the last update?** Since this update is optional and all, we are now at a massive disadvantage over anyone who just simply forgot to update. This addon is one of the most important ones to our community and is a massive problem that will further stem into other servers once they update themselves. 

Thank you in advance facepunch team!

**Comment by Bryantdl7** [comment]
Further confirming the issue is in the update, when forcing a server to the chromium branch, which I have come to know as one update behind latest, the issue goes away

**Comment by robotboy655** [comment]
From what I can tell, the actual issue it would appear is due to your addon giving `string.ToTable` a number instead of a string like it is expecting, here:
https://github.com/bouletmarc/ACF_CustomMod/blob/d0f436d05e4b4427065e3ab54ffdde2404a4a059/lua/autorun/acf_globals_custom.lua#L13

Which causes a Lua error which causes other code in that file to not execute and not send the file `cl_acfcustom_gui.lua` to clients, hence why the game can't find it.
