### ISSUE TITLE
I can take out weapons and items in the car. How can I disable it?

### ISSUE THREAD

**Issue by RealDuckteam** [Facepunch/garrysmod-issues#5401]
I can take out weapons and items in the car

![image](https://user-images.githubusercontent.com/69460253/216768715-57530e0a-5ce8-4897-ac09-a659c9886f10.png)
![image](https://user-images.githubusercontent.com/69460253/216768734-55f6604f-5fa9-4ef8-b144-48cb867015f6.png)

**Comment by robotboy655** [comment]
This is not default behavior. It's one of your mods doing it. This is not a place to get help with mods.
