### ISSUE TITLE
_modded Gamemodes Not Being Listed Correctly in In-Game Server Browser

### ISSUE THREAD

**Issue by Hazbelll** [Facepunch/garrysmod-issues#5403]
### Details
It seems the method to modify an existing gamemode, but keep it under the original gamemode's category in the list of gamemodes of the in-game server browser [as documented on the Wiki](https://wiki.facepunch.com/gmod/Gamemode_Creation#moddinggamemodes) doesn't seem to work. Although the modded gamemode will successfully load and appear in the in-game server browser, it'll do so under [its own (Duplicate) gamemode category](https://i.imgur.com/J447VHI.png) and not the one belonging to the original gamemode.

Server Version:
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown
Windows 32bit Dedicated Server
```

Client Version:
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce

1. On the server, copy the [`sandbox` gamemode folder](https://github.com/Facepunch/garrysmod/tree/master/garrysmod/gamemodes/sandbox) and its contents to `addons/my_gamemode/gamemodes/`.
2. Rename the `sandbox` gamemode folder to `sandbox_modded` and rename the `sandbox.txt` inside it to `sandbox_modded.txt`.
3. Set the server's `+gamemode` parameter to `+gamemode sandbox_modded` and start the server.
4. On the client, check which gamemode category the server gets listed under in the in-game server browser.

**Comment by Hazbelll** [comment]
Can also confirm this issue exists on the `main` branch for the client (Assuming it's relevant).
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown, multicore: 0
Windows 32bit
```

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/218484199-1efa6981-7f29-4367-bfae-c3b05f5b9b22.png)

Cannot reproduce. Did everything as you said.

**Comment by Hazbelll** [comment]
Thank you for confirming. I did some further digging and it seems this incorrect behaviour is caused by the [gmsv_serversecure](https://github.com/danielga/gmsv_serversecure) binary module. Will report there.
