### ISSUE TITLE
January 2023 update caused Server list refresh issue

### ISSUE THREAD

**Issue by TEGTainFan** [Facepunch/garrysmod-issues#5405]
### Details
Starting from the 26th January update, players in China will not be able to refresh out of the Chinese servers as a priority
Chinese servers can appear on the list, but not until other servers have been retrieved

[Recorded video](https://www.heprgryph.cn/file/test.mp4)

**Comment by robotboy655** [comment]
This is not an issue with the game update. Facepunch can not control the order in which servers appear in the server list, as we are using Valve's Steamworks API to retrieve the server list.

**Comment by robotboy655** [comment]
Here's a report of this on the Steam Community Discussions:
https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3763356482612086141/

**Comment by TEGTainFan** [comment]
Ok, thank you very much!
