### ISSUE TITLE
resource.AddWorkshop limit of 200 addons

### ISSUE THREAD

**Issue by Kapppa** [Facepunch/garrysmod-issues#5409]
### Details
Recently there has been an issue with the workshop download if there are more than 200 workshop items added to the server. All the addons after the ~200 mark will be ignored as they take too long to response the FileInfo request. Meaning they are not mounted and ignored causing issues on the server. They are all added via the resource.AddWorkshop function. 

This could be resolved by reducing the amount of addons added but, I would not want to repack other peoples addons into a one large pack as it doesn't give them credit or be against their chosen license. 

I was wondering if this was a limit on Steam's end or something was changed recently in the latest update as it seems to have come from there. 

### Steps to reproduce
Run Clientside, majority of players on the server effected by the issue. 

```lua
for i = 1, 210 do
    steamworks.FileInfo( 21197, function( result )
        print(""..i.." "..CurTime())
    end)
end
```
<details>
  <summary>Example Output</summary>

```
1 897.375
2 897.375
3 897.375
4 897.375
5 897.375
6 897.375
7 897.375
8 897.375
9 897.375
10 897.375
11 897.375
12 897.375
13 897.375
14 897.375
15 897.375
16 897.375
17 897.375
18 897.375
19 897.375
20 897.375
21 897.375
22 897.375
23 897.375
24 897.375
25 897.375
26 897.375
27 897.375
28 897.375
29 897.375
30 897.375
31 897.375
32 897.375
33 897.375
34 897.375
35 897.375
36 897.375
37 897.375
38 897.375
39 897.375
40 897.375
41 897.375
42 897.375
43 897.375
44 897.375
45 897.375
46 897.375
47 897.375
48 897.375
49 897.375
50 897.375
51 897.375
52 897.375
53 897.375
54 897.375
55 897.375
56 897.375
57 897.375
58 897.375
59 897.375
60 897.375
61 897.375
62 897.375
63 897.375
64 897.375
65 897.375
66 897.375
67 897.375
68 897.375
69 897.375
70 897.375
71 897.375
72 897.375
73 897.375
74 897.375
75 897.375
76 897.375
77 897.375
78 897.375
79 897.375
80 897.375
81 897.375
82 897.375
83 897.375
84 897.375
85 897.375
86 897.375
87 897.375
88 897.375
89 897.375
90 897.375
91 897.375
92 897.375
93 897.375
94 897.375
95 897.375
96 897.375
97 897.375
98 897.375
99 897.375
100 897.375
101 897.375
102 897.375
103 897.375
104 897.375
105 897.375
106 897.375
107 897.375
108 897.375
109 897.375
110 897.375
111 897.375
112 897.375
113 897.375
114 897.375
115 897.375
116 897.375
117 897.375
118 897.375
119 897.375
120 897.375
121 897.375
122 897.375
123 897.375
124 897.375
125 897.375
126 897.375
127 897.375
128 897.375
129 897.375
130 897.375
131 897.375
132 897.375
133 897.375
134 897.375
135 897.375
136 897.375
137 897.375
138 897.375
139 897.375
140 897.375
141 897.375
142 897.375
143 897.375
144 897.375
145 897.375
146 897.375
147 897.375
148 897.375
149 897.375
150 897.375
151 897.375
152 897.375
153 897.375
154 897.375
155 897.375
156 897.375
157 897.375
158 897.375
159 897.375
160 897.375
161 897.375
162 897.375
163 897.375
164 897.375
165 897.375
166 897.375
167 897.375
168 897.375
169 897.375
170 897.375
171 897.375
172 897.375
173 897.375
174 897.375
175 897.375
176 897.375
177 897.375
178 897.375
179 897.375
180 897.375
181 897.375
182 897.375
183 897.375
184 897.375
185 897.375
186 897.375
187 897.375
188 897.375
189 897.375
190 897.375
191 897.375
192 897.375
193 897.375
194 897.375
195 897.375
196 897.375
197 897.375
198 897.375
199 897.375
200 897.375
201 897.375
207 917.125
209 917.125
204 917.125
208 917.125
210 917.125
202 917.125
206 917.125
203 917.125
205 917.125
```
</details>

**Comment by robotboy655** [comment]
I have reworked how the timeout works on the `dev` beta, it should work better now. The timeout has to be there in case it actually gets stuck.

I would appreciate if you could confirm it being fixed for you as well by testing the `dev` beta client joining your server.

**Comment by Kapppa** [comment]
I have check and the changes seem to be working. I was able to join the server with all the content mounted.

**Comment by oninoni** [comment]
Dev Branch fix seems to fix the issue that is reuccuring today.

**Comment by oninoni** [comment]
@robotboy655 could you apply that change you made in dev to the main branch? It would help a lot of servers right now since steam change something today.
It still delays addon 101/102, but your change allows the game to continue loading afterwards.

**Comment by crosscoder1** [comment]
If not possible to push it to main yet, can the change in the dev branch also be pushed to the x86_64 version too for now?

**Comment by FlorianLeChat** [comment]
The fix is already on `dev` branch according to other people, regarding the `x86-64` branch, the build server doesn't exist anymore and so this branch has a pretty old version of Garry's Mod (even before the January 2023 update) so it's impossible for Rubat to do any update right now.

**Comment by crosscoder1** [comment]
I see,  I wasn't aware the x64 branch was abandoned.  That's very disappointing.

**Comment by Nononshidanku** [comment]
I switched the server version to Dev, but for some reason it doesn't seem to improve. If the collection exceeds 101, the client's console will display

`WorkshopDL: Took too long to get item info for 2873768237!`

Incidentally, the message appears and the file is not downloaded.
Switching to dev on both server and client doesn't help.

By the way, the server is in Asia. Is there a timeout time that varies by region?

**Comment by robotboy655** [comment]
It's a client issue. Changing server configuration will not achieve anything. No, the timeout is not different between regions. Steam servers are just more loaded than usual I imagine.

**Comment by TuXEKRO** [comment]
Hello, same problem with several of my clients (in which I include myself), when switching to the DEV branch the solution works. Couldn't this small change be urgently added to the main branch?
I guess it must be affecting multiple servers, and in my case I have more than 200 addons because mainly the majority are maps that I don't want to force clients to download since they only use one or two.

Could you implement it in the main branch @robotboy655 ?

**Comment by joeyjumper94** [comment]
so when will this issue be fixed in the x86 x64 branch?

**Comment by robotboy655** [comment]
It already was weeks ago.

**Comment by crosscoder1** [comment]
Was this patch reverted for some reason on the last update?  The issue, or one similar, seems to have returned.

**Comment by robotboy655** [comment]
No.

**Comment by crosscoder1** [comment]
Thank you.  I'll will open a new ticket then.
