### ISSUE TITLE
Garry's Mod Auto Disconnect Bug [HELP DESPERATLEY NEEDED}

### ISSUE THREAD

**Issue by Sharkgamer999** [Facepunch/garrysmod-issues#5412]
So every time I try to join one of my friends on a Gmod multiplayer game, what my game does is take about 10-20 minutes to load and when I DO manage to get in, the game lets me move an inch or two or sometimes not at all and then in the top right corner it says "WARNING: Connection problem Auto Disconnecting" with a timer next to it. I HAVE TRIED EVERYTHING, reinstalled the game, checked my internet, uninstalled all my addons, done the retry command, verified the game cache, EVERYTHING! Yet to no avail nothing fixed the problem. I even disabled my antivirus because one time that was preventing me from joining and that didn't work either. I'm starting to lose all hope and I'm wanting to give up and just delete the game entirely. You're also probably asking "Well why don't you just host the server for your friends?" Well, I can but there's also problems there. The server gets more and more laggy when more people join and it eventually gets to the point to where even spawning in a car or ragdoll crashes the game. EVEN SWITCHING PLAYER MODELS CRASHES THE GAME! It's happened every time. I know there's nothing wrong with my internet, I know there's nothing wrong with my PC since it can run Minecraft, Fortnite, GTA, Doom Eternal, and even VR games on max specs perfectly fine, and I know for a FACT that it's none of the addons in the game itself. This sounds like something that the devs need to go in and fix. If anyone knows ANYTHING AT ALL that might help then please tell me.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

**Comment by Kefta** [comment]
Get a grip.
