### ISSUE TITLE
Garrys Mod Freezing when Joining blank Server

### ISSUE THREAD

**Issue by mleem97** [Facepunch/garrysmod-issues#5415]
Lately my complete Game Freezes, when joining a TTT Server. 
As soon as all addons an LUA Files are loaded and the gamemode is displayed, the game freezes completely.

I looked for Dumps, but in the Garrys Mod folder there are no Dumps. 

I tried Removing any 3rd Party Addons, and also all Workshop addons. Even when the server is blank the game Freezes.
So i have set up a new server, but added the TTT2 Base, and the server works. 

I have absolutely no clue, what it could be, because my client doesnt drop any useful information, and the server only shows
Client "Die Frikadelle" connected (**.**.***.*:27005).
Dropped Die Frikadelle from server (Disconnect by user.)
or
Client "Die Frikadelle" connected (**.**.***.*:27005).
Dropped Die Frikadelle from server (Timeout)

The error occurs since yesterday 05:00am (German Time)
No Addons are Subscribed in Workshop.

Server is running on Ubuntu 22.04 / Server Build is the latest build from SteamCMD. 

] version
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown, multicore: 0
Windows 32bit

I tried setting up the server several times, and tested with 3 different clients on 3 different systems.

**Comment by robotboy655** [comment]
Server version and beta branch? Game version and beta branch?

I tried joining a local dedicated TTT server and it worked just fine.

**Comment by mleem97** [comment]
Server is running on Ubuntu 22.04 / Server Build is the latest build from SteamCMD. 

] version
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown, multicore: 0
Windows 32bit

I tried setting up the server several times, and tested with 3 different clients on 3 different systems.

**Comment by mleem97** [comment]
The Error could be fixed by Subscribing to our Steam Collection - Which is weird because i didnt have any plugin on the blank server.
