### ISSUE TITLE
weld won't work correctly on loaded dupe

### ISSUE THREAD

**Issue by EnderGamerXPnew** [Facepunch/garrysmod-issues#5418]
### Details
when whe create he building in gmod and save it as he dupe actualy every objet bind with the weld tool will act when loaded like ball join instead. that result most of time on the dupe turning into useless massive blob

### Steps to reproduce
just make he building/machine with the weld tools and save it, the more layer of object welded the more this bug will take effect in spatially if when trusters are used

### Version
Gmod Steam (last)

**Comment by robotboy655** [comment]
Are you sure it's not an addon you have is doing it?

**Comment by EnderGamerXPnew** [comment]
yes it is on vanilla gmod, perhaps with the overballl

**Comment by EnderGamerXPnew** [comment]
i use the phys gun to accelerate the prosses but is't append gradualy when whe drive the drone
