### ISSUE TITLE
Ambient Generic - Incorrect radius in-game

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5420]
### Details
Ambient Generic has an incorrect radius in-game, no matter what value you set it in Hammer Editor, it wont be heard correctly in-game. 
### Steps to reproduce
[ambientgeneric_radius.zip](https://github.com/Facepunch/garrysmod-issues/files/10863765/ambientgeneric_radius.zip)
There is a looped alarm sound when you load the map, the transparent orange dome represents the value that was typed in Hammer Editor while the gray dome represents how far that radius actually goes in-game (note that the gray dome is about 90% accurate due to how annoying it is to create spheres in Hammer Editor).
You can see this for yourself, the ambient_generic has a maximum radius of 400 within Hammer Editor, yet it can be heard outside that radius in-game.
That small func_detail with ambient_generic texture is just a point of reference in-game.
This was tested in both normal and chromium branch, no difference.

**Comment by robotboy655** [comment]
The engine does not support arbitrary radiuses for sounds, it's all based on the "sound level" stuff. 
https://wiki.facepunch.com/gmod/Enums/SNDLVL

The radius you input will be approximated to one of those enums.

Don't ask me why, I didn't make it this way.

**Comment by Battlefieldkille** [comment]
> The engine does not support arbitrary radiuses for sounds, it's all based on the "sound level" stuff. https://wiki.facepunch.com/gmod/Enums/SNDLVL
> 
> The radius you input will be approximated to one of those enums.
> 
> Don't ask me why, I didn't make it this way.

I see, I dont blame you, you didnt make the engine, thanks for the reply.
