### ISSUE TITLE
Filenames containing "Copy (" aren't listed by file.Find

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#5425]
### Details
```
] version
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
1. Create two files in an empty folder `garrysmod/data/copy_test/`. Name one `Copy.txt`, name another `Copy (1).txt`
![image](https://user-images.githubusercontent.com/2799393/224204544-bd46ef2c-c95f-45df-87be-4f0433075e74.png)

2. Start a Singleplayer game in Sandbox
3. Run the following in console:
```
lua_run local files = file.Find("copy_test/*", "DATA") PrintTable(files)
```
4. The output should be the following, and `Copy (1).txt` won't be seen:
![image](https://user-images.githubusercontent.com/2799393/224204405-2812d0eb-7d44-4bbc-b505-0d2056374071.png)

### Regarding file.Exists
`file.Exists` correctly returns `true` in either case:
```
lua_run print(file.Exists("copy_test/Copy.txt", "DATA"), file.Exists("copy_test/Copy (1).txt", "DATA"))
```
![image](https://user-images.githubusercontent.com/2799393/224205137-28065099-36ff-4ed8-8da7-7d4a274b2288.png)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
