### ISSUE TITLE
resource.AddWorkshop() & terrible load times for guests

### ISSUE THREAD

**Issue by Bryantdl7** [Facepunch/garrysmod-issues#5426]
### Details
The function resource.AddWorkshop() https://wiki.facepunch.com/gmod/resource.AddWorkshop allows for content creators to mandate their content is installed on all joining users, much like how https://wiki.facepunch.com/gmod/resource.AddFile was heavily utilized in the pre-gmod13 days. 

The age-old problem, is developers use this function too often, and anyone not knowing about cl_downloadfilter (such as new gmod players) are at mercy of insane load times, simply because the developer opted to use the function. 

### Steps to reproduce
1. Subscribe a server to a workshop collection of addons which contain a lot of resource.AddWorkshop 
2. Join on a clean install of gmod while not subscribed to any addons 
3. In our case, on multiple rounds of testing, users are easily forced to download 3GB+ of addons, purely thanks to this function being unregulated, making for anyone on a slower internet connection taking forever to even join a server and see if they like the community. 

Of course, we (server owners) could decompile every single offending .gma, modify the source code to remove this hook, and solve the issue, but there is an easier way. Simply adding a cvar for sv_forceworkshop 0/1 or something similar, would allow server managers to choose when they want to use this function or not, effectively cutting load times in half. 

I completely understand the importance of this function for some communities, and some may desire to keep forcing addons on their players without subscribing to an addon pack, but quite frankly walking in the shoes of someone new to the game, this is a terrible user experience, which could quite easily be solved by giving communities the power to decide if they want this for their servers or not. 

**This is a bit of a gray area of a feature request and a bug report**, because while this is a request to have a feature changed, it is also becoming a real problem for many server owners, myself included. 

Thank you for your consideration Rubat and team, this would be a game changer for many.

**Comment by robotboy655** [comment]
I don't understand how you expect the addons to function if you force clients to NOT download their assets.
Sounds to me that the actual issue is that you have too many addons on the server.

What is better user experience, waiting ONCE to download addons, or seeing missing textures and errors everywhere on your server?

I do not think adding this option makes any sense at all.
If you really want to control when `resource.AddWorkshop` runs and for which addons, you can easily detour it on your server before addons call it. (by modifying a .lua file on the server that is ran before autorun, such as `includes/init.lua`)

**Comment by Bryantdl7** [comment]
Addons would still function by users consenting to install their content, this is common practice with many addons, such as ACF, sProps, etc. Don't have the content? You can't see it. This is the same logic of needing CSS installed to see CSS content. If you don't have it, that's on the user. 

I can confirm we do not have too many addons, anyone who is subscribed to all our addons (or who has them cached by this function) loads in within a minute or so, with no lua errors. I know what too many addons looks like, and the issue simply comes down to new players. Our established members have zero issues, but if I go on another gmod account on a fresh pc with no workshop cache, I don't get those load times. 

I will say to your point of which is better downloading everything once vs errors, not every addon has this coded in. Only about 40 of our addons we run even utilize it, of course being the biggest ones storage wise. 

Not every person who joins a server will like the server, not every person who joins a server has the bandwidth to download several gigs of addons, even moreso to simply end up deciding they dislike the server, only to go to the next one and spend another half hour loading in. 

I appreciate you taking the time to tell me there is a way to disable it though, that is greatly appreciated.
