### ISSUE TITLE
Incorrect rendering of Portal material concrete/concrete_modular_wall001e

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#5431]
### Details:
concrete/concrete_modular_wall001e is rendered incorrectly in Garry's Mod
This occurs on all branches

### Screenshots:
Portal:
Correct rendering
![image](https://user-images.githubusercontent.com/47306808/228702358-f4a9ef09-7e6b-4894-bee1-a950a829b911.png)

Garry's Mod:
Incorrect rendering
![image](https://user-images.githubusercontent.com/47306808/228701528-df998802-0173-4a69-a0ab-7e74f4c9ffb0.png)

### Steps to reproduce:
Open almost any Portal map and look at the material concrete/concrete_modular_wall001e

**Comment by robotboy655** [comment]
That material in Portal uses the same name as Half-Life 2. There isn't much that can be done about it. This will not be looked into. You can use 3rd party addons to try to remedy this while on Portal maps.

**Comment by wolfestridershooter** [comment]
So that is incorrect, those textures don't show up in Half-Life 2 anywhere. I looked in HL2 Hammer to EP2 Hammer and the modular wall textures are no where to be found. Just to make sure I unmounted Portal and Portal 2 from Garry's Mod and I got this:

![image](https://user-images.githubusercontent.com/47306808/228733314-a9fda6e0-f44a-4b94-98f5-097ba8a08d0a.png)

So yeah I'm 100% sure those textures don't exist in Half-Life 2

**Comment by wolfestridershooter** [comment]
Welp, I'm sorry for wasting your time
