### ISSUE TITLE
Portal maps don't work

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#5432]
### Details:
Now I'm aware that adding the Portals from Portal into Garry's Mod is likely a herculean task especially for what is probably just one person, I understand if that will likely never happen. Although I think what is a possibility is for the entities to be ported over into the engine like npc_portal_turret_floor, prop_energy_ball, func_portal_detector, etc. From my very limited knowledge I don't think the Portal entities conflict with HL2s because Portal is "basically" and HL2 "mod" and there aren't a whole lot of entities to port over so it shouldn't be too bad but idk. I just thought I should throw this out there because this is something I've wanted to see in Garry's Mod for a very long time although I'm aware the response is will likely be a no (for understandable reasons). Also I would gladly make spawnicons and whatever else can be done on the publicly available side of things to facilitate this.

**Comment by 1nfameArts** [comment]
Portal maps work for me, go and **factory reset** your gmod.
![изображение](https://user-images.githubusercontent.com/102991955/232055828-db39921d-345b-4e8c-8144-83e67219f68d.png)

**Comment by 1nfameArts** [comment]
> Portal maps work for me, go and **factory reset** your gmod. ![изображение](https://user-images.githubusercontent.com/102991955/232055828-db39921d-345b-4e8c-8144-83e67219f68d.png)

forgot mention: run FactoryReset-GMod.bat

**Comment by wolfestridershooter** [comment]
> > Portal maps work for me, go and **factory reset** your gmod. ![изображение](https://user-images.githubusercontent.com/102991955/232055828-db39921d-345b-4e8c-8144-83e67219f68d.png)
> 
> forgot mention: run FactoryReset-GMod.bat

That's not the problem I'm talking about the entities within the maps not working like the energy ball launchers and the cameras not spawning, it's because the ents were never ported to Garry's Mod but most of them should be pretty easy to port as long as Rubat has the source code available to him.

**Comment by robotboy655** [comment]
Superseded by https://github.com/Facepunch/garrysmod-requests/issues/2151
