### ISSUE TITLE
Cyclic parent crash in clientside with clientside entities

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#5436]
> I'm not sure why your method of reproducing this issue is so complicated compared to:
> 
> ```lua
> A:SetParent( B ); B:SetParent( A )
> ```
> 
> So it'd be nice if you could make sure the fix for this works as it should. It should be on the dev branch by tomorrow.
> 
> It just unlinks any parts of the parent-list that are cyclic, don't expect it to let you parent entities to themselves.

Regarding the parent fix that was added a while ago, it seems clientside entities don't have the same protection.

**Comment by wrefgtzweve** [comment]
Can be replicated using
SV:
```
lua_run ent1 = ents.Create("prop_physics") ent2 = ents.Create("prop_physics") ent1:SetModel("models/props_borealis/bluebarrel001.mdl")  ent2:SetModel("models/props_borealis/bluebarrel001.mdl") ent1:Spawn() ent2:Spawn()
```

CL:
```
lua_run_cl props = ents.FindByClass("prop_physics") props[1]:SetParent(props[2]) props[2]:SetParent(props[1])
```

**Comment by robotboy655** [comment]
Fixed on Dev.
