### ISSUE TITLE
Custom fonts do not apply to Russian characters

### ISSUE THREAD

**Issue by HellCatcher** [Facepunch/garrysmod-issues#5444]
I've tried many fonts, but only the Latin characters change.
But if you use a custom font in DHTML, then all the characters are displayed correctly.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Structures/FontData

See `extended` field.

Also duplicate of https://github.com/Facepunch/garrysmod-issues/issues/842
