### ISSUE TITLE
SetHealth does nothing on the client

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#5449]
It should set m_iHealth like the server does, similar to how GMod has changed the default GetHealth/GetMaxHealth impl on the client.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3572 can be closed by this.

**Comment by Goldermor** [comment]
why should it do anything?

**Comment by Kefta** [comment]
So that prediction errors don't occur every time the player's health is set.

**Comment by Goldermor** [comment]
how the hell do you get prediction errors from thing that is on the server side?

**Comment by Kefta** [comment]
That's the entire point of prediction errors. Server does something, client doesn't expect it because it didn't do the same thing = misprediction
