### ISSUE TITLE
Some Issues with the HL2 NPCs

### ISSUE THREAD

**Issue by vcf55** [Facepunch/garrysmod-issues#5451]
- APCs use the "cannon_muzzle" attachment for its machine gun instead of the "muzzle" attachment, [the issue might be here.](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/vehicle_apc.cpp#L200)
- Gunships are unable to hit players both standing still and using certain weapon hold types as it will fire over the player's head
- The Fisherman from Lost Coast doesn't have the "ragdoll.smd" animation causing him to T-Pose on death
GMod version 2023.04.19

**Comment by Goldermor** [comment]
what the hell does The Fisherman have to do with Gmod? the rest is ok, but The Fisherman?? you're talking about model from another game, seriously?

**Comment by Kefta** [comment]
I think he's just noting a bug with a built-in NPC which GMod has chose to implement. Nothing to fix there without recompiling the model though.

**Comment by vcf55** [comment]
Pretty much what Kefta said, If it wasn't included in GMod I wouldn't have put it in here.

**Comment by Panzerhandschuh** [comment]
I am noticing the same issue with the gunships shooting just above the player's head. Unfortunately it is making the gunship battles less exciting on my coop server and I could not find a fix/workaround.

**Comment by robotboy655** [comment]
I have adjusted the Combine Gunship and Combine APC rockets to aim at player's center. I have also corrected the combine APC tracer source position.

The lost coast fisherman is a "problem" with Lost Coast, we don't have the source files for that model, so there's no good way to add ragdoll to the model without breaking it in some way from decomplication.
