### ISSUE TITLE
:Frags() behaving weirdly

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-issues#5453]
### Details
ply:Frags() does not have correct functionality on client.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/64710817/235555596-294eb214-16be-43bd-b86c-db54966c313c.png)
`lua_run Entity( 1 ):SetFrags( 9000 ) print( Entity( 1 ):Frags() );lua_run_cl print( Entity( 1 ):Frags() )`

I expect the clientside print to be 9000, but it's 808

Not _exactly_ sure, but this seems to be an issue on all branches.

**Comment by Kefta** [comment]
It's because of this https://github.com/VSES/SourceEngine2007/blob/master/se2007/game/server/player_resource.cpp#L20 - the lower 12 bits of 9000 in binary == 808. These bit count specifications here should just be removed and allow the full int to be networked.

**Comment by robotboy655** [comment]
Limits removed.
