### ISSUE TITLE
Game hangup when performing a smooth changelevel.

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#5456]
When performing a smooth changelevel, for example, from the d1_canals_01 map to the d1_canals_01a map, the game hangup on a black-and-gray screen with an empty loading indication window. (There is no message about the loading steps of the level.)
Version command output:
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

**Comment by robotboy655** [comment]
I cannot reproduce this at all. I suspect it may be related to how many addons you have, perhaps it is loading something and you are not patient enough to let it do its thing.

**Comment by robotboy655** [comment]
I don't know why it takes so long for you, for me it takes like 10 seconds with no addons, but I imagine it could be related to saving entities from old map, and then loading them after loading the map. Perhaps your disk drive is slow to make that save game? I can't really know. Overall, it should be nearly identical to `changelevel` command, as it uses pretty much the same code internally.

Keep in mind, that each mounted game will also increase loading times significantly.
