### ISSUE TITLE
Strange issue with ParticleEffect and ParticleEffectAttach

### ISSUE THREAD

**Issue by Dimentio** [Facepunch/garrysmod-issues#5458]
### Details
I came across this issue from #3607 where as, the recommended way to precache particles would be to only do it client-side. As per my comment 5 years ago, this doesn't work very well for [ParticleEffect ](https://wiki.facepunch.com/gmod/Global.ParticleEffect) and [ParticleEffectAttach](https://wiki.facepunch.com/gmod/Global.ParticleEffectAttach). For some reason these functions if ran client-side will output missing particles (red 'x') until the server run it at least once. Obviously if you precache the particles server-side they will work just fine. This issue does NOT happen with [CreateParticleSystem](https://wiki.facepunch.com/gmod/Global.CreateParticleSystem) or [CreateParticleEffect](https://wiki.facepunch.com/gmod/Entity:CreateParticleEffect).

### Steps to reproduce
```
game.AddParticles( "particles/explosion.pcf" )

if CLIENT then
    PrecacheParticleSystem( "ExplosionCore_wall" )
    ParticleEffect( 'ExplosionCore_wall', LocalPlayer():GetPos(), angle_zero )

    -- This should run just fine
    -- CreateParticleSystem( LocalPlayer(), 'ExplosionCore_wall', 0, 0 )
else
    -- If uncommented, client should be able to use ParticleEffect after
    -- ParticleEffect( 'ExplosionCore_wall', Entity(1):GetPos(), angle_zero )
end
```

**Comment by robotboy655** [comment]
That some reason is because the function relies on network (stringtable) IDs to function, even clientside. It's directly aimed at networked uses, so it uses IDs over direct strings as it's cheaper. As you have pointed out, there are already clientside-only alternatives to these 2 functions.

**Comment by robotboy655** [comment]
I will add a new function that will allow you to create a particle system without tying it to an entity.

```
local pos = Entity(1):GetEyeTrace().HitPos
PrecacheParticleSystem("explosion_huge_g")
CreateParticleSystemNoEntity( "explosion_huge_g", pos, angle_zero )
```
