### ISSUE TITLE
Game hangup on "Epic Quest of AJ 2" map.

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#5459]
I noticed another hangup on the "Epic Quest of AJ 2" map, when crossing the trigger indicated by the crosshair in the screenshot.
The map must be completed completely, otherwise if just fly over part of the map with a noclip and touch this trigger, it will not hangup.
Link to the map itself:
https://steamcommunity.com/sharedfiles/filedetails/?id=2973202889
Version command output:
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```
![unnamed](https://github.com/Facepunch/garrysmod-issues/assets/126508037/cf16fe20-f7b5-4a07-8fa4-c72b6f1233d9)

**Comment by robotboy655** [comment]
Does this happen on the "NONE" beta of the game?
