### ISSUE TITLE
Entity:SetPhysicsAttacker doesn't work with func_physbox (but it works fine with Entity:SetSaveValue)

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-issues#5460]
this code:
```lua
ent:SetPhysicsAttacker(ply, 5)
```
is identical to this:
```lua
ent:SetSaveValue("m_hPhysicsAttacker", ply)
ent:SetSaveValue("m_flLastPhysicsInfluenceTime", 5)
```

however, for func_physbox, only the 2nd method works

it seems that the Entity:SetPhysicsAttacker gmod function specifically only checks if the entity's class is prop_physics or prop_physics_multiplayer and does nothing otherwise, even though the m_hPhysicsAttacker and m_flLastPhysicsInfluenceTime fields exist for a lot of other classes like func_physbox, func_physbox_multiplayer, npc_manhack, npc_turret_floor, prop_ragdoll, etc

this is most noticeable in the ttt gamemode since you can use func_physbox props to propkill players without it showing up on any logs, or grab a manhack out of the air and use it to kill someone without having it be logged

**Comment by robotboy655** [comment]
Fixed on `dev` beta, it should now work for all entities that have `m_hPhysicsAttacker` property.
