### ISSUE TITLE
Dev Branch seems to be Broken

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5463]
### Details
The Dev branch seems to be missing a lot of changes like the clientside function CreateParticleSystemNoEntity or the bug fixes for
render.EnableClipping and render.SetLightingMode and the serverside functions NavArea:GetSpotEncounters, CNavArea:GetVisibleAreas( bool ).

There are many other changes that seem to be missing, so I think maybe one of the latest commits broke the Branch?

My Version:
```lua
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 15:56:23 May  8 2023 (8948) (4000)
GMod version 2023.05.10, branch: dev, multicore: 1
Windows 32bit
```

### Steps to reproduce
Switch to the Dev branch and search for some functions that have been added or try to check if a bug fix is present.

**Comment by robotboy655** [comment]
Should be fixed now.
