### ISSUE TITLE
Localization Caching Interferes with Live Files

### ISSUE THREAD

**Issue by SageJFox** [Facepunch/garrysmod-issues#5466]
It seems that there's some sort of localization caching that can mess things up if new files have shared tokens with files that are no longer present. I'm not positive on all the details but will share the specific details of what we were working on, and attempt to hazard a guess at why it's happening that way.

Steps to reproduce:
Create a localization properties file and populate it with some tokens that get used. Ours was `jazztonauts.properties`

Run the game and see the localization being used.

If localization caching doesn't immediately happen, wait for it to. (I make note of this because our file was renamed roughly nine months after it was initially created.)

Rename the file (seemingly to something that would come after the original name alphabetically but this isn't a confirmed part of this). We've renamed to `jazztronauts.properties` mind the new 'r'.

In the newly renamed file, change some of the localization text. In ours, we switched, among other things, `jazz.death.killer` from `R.I.P. %1%, killed by %2%` (the tokens being replaced by 1-player name and 2-killer) to `R.I.P. %1%, %2% by %3%` (tokens being updated to be 1-player name, 2-verb based on the damage type, and 3-killer)

> A potentially important note, this was actually changed _six days_ before the file was renamed on our setup, so it seems the cache is potentially never updated after it's initially created. This text worked correctly prior to the file name change. In our test case, prior to the renaming it would cause the death message to correctly display `R.I.P. Sierra Foxtrot, clobbered by The Trolley`

Restart the game and check the localization. It'll be using the old version still. In our test, it would display `R.I.P. Sierra Foxtrot, killed by clobbered` (since the killer was moved from %2% to %3%, the verb took its place, with the killer name being left out.)

Now, create a new properties file with the original name. I put `###` in mine to make sure it wasn't totally blank, but it contained no tokens.

Restart the game, and check the localization again. It'll be using the renamed file's now. In our test case, it once again displayed the correct  `R.I.P. Sierra Foxtrot, clobbered by The Trolley`

Delete the blank file with the old name, restart, and check the localization again. It'll be using the old version again. (`R.I.P. Sierra Foxtrot, killed by clobbered`)

It *seems* that (whether alphabetical or by first time loaded), these cached localization files have precedent over live ones, even if they lack a matching live file. It seems the load order is Live file, cache, live file, cache, etc. like so
```
[#1 Live] (the deleted file/original name in our example)
[#1 Cache] (the cache seeming to be whatever the first instance of that token was set to)
[#2 Live] (the new/renamed file in our example)
[#2 Cache]
...
...
```
when it should be all live files before cache files, i.e.
```
[#1 Live]
[#2 Live]
...
[#1 Cache]
[#2 Cache]
...
```

**Comment by robotboy655** [comment]
There is no file caching done by the game, not across sessions at any rate. Perhaps you had the same string in the same file multiple times? Or you had a file with the original name somewhere else? (Some other addon, or in the base game?)

**Comment by SageJFox** [comment]
The only other location this file exists/this token could be defined is in the Jazztronauts addon that is on the workshop, which is currently disabled. Unless GMod is pulling the localization from the disabled workshop addon over the loose folder addon, my current work file is the only one defining it in English.

I should note the example string wasn't the only one with this problem, edits to any existing token, even simple string ones, weren't taking on the renamed file. I also wasn't the only one able to reproduce these on our base... but he also had the disabled workshop addon on disk, hm.

I'll attempt completely uninstalling the workshop addon and see if that changes things.

**Comment by robotboy655** [comment]
` steamapps/workshop/content/4000/` is managed completely by Steam. As far as I know, the files from there would only be deleted if the game is not running. It will also not delete files that you put there youself (i.e. extracting an addon for example), but GMod does not put files there itself.

And no, GMod does not load anything from disabled addons (unless perhaps the addon was enabled at the game's start and was disabled later in the same session?)

**Comment by SageJFox** [comment]
The workshop version has been disabled since I joined in on working on the addon, which has been almost a year now.

**Comment by Commenter25** [comment]
I can confirm, I was having the same issue. [I was the one who changed the file](https://github.com/Foohy/jazztronauts/pull/159), and it would not work even with `-noworkshop`; unless I removed the workshop ID from `gamemodes/jazztronauts/jazztronauts.txt`, or I removed my locally downloaded file from `steamapps/workshop/content/4000/1452613192`

**Comment by robotboy655** [comment]
Ah I think I see what is happening, it is simply downloading and mounting the workshop gamemode when you join the server via `resource.AddWorkshop`, which is automatically called for the gamemode.

`cl_downloadfilter none` would be the solution there.
