### ISSUE TITLE
lua/includes/extensions/entity.lua:240: bad argument #3 to 'SetFunc' (number expected, got nil)

### ISSUE THREAD

**Issue by d4kir92** [Facepunch/garrysmod-issues#5467]
### Details
lua/includes/extensions/entity.lua:240: bad argument #3 to 'SetFunc' (number expected, got nil)
[C]: in function 'SetFunc'
lua/includes/extensions/entity.lua:240: in function '__newindex'
lua/includes/extensions/entity.lua:328: in function 'SetForm'
[string "--[[-------------------------------------------------------------------]]--[[..."]:937: in function 'SetStandard'
[string "--[[-------------------------------------------------------------------]]--[[..."]:240: in function <[string "--[[-------------------------------------------------------------------]]--[[..."]:236>

### Steps to reproduce
ply:Give function can cause this sometimes, i dont know why

**Comment by Kefta** [comment]
Those line numbers don't match up with the latest version of entity.lua, and "SetForm" is not a function referenced anywhere I'm the file. Do you have any addons that modify that file?

**Comment by d4kir92** [comment]
it is lining up with my server files i have and updating server files dont give me the latest ones that are here in the github

**Comment by d4kir92** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/23246564/c6c3509c-e705-427e-9826-62b806fff447)

**Comment by d4kir92** [comment]
also from linter in that file:
![image](https://github.com/Facepunch/garrysmod-issues/assets/23246564/158b3ba2-cc65-43df-8b5d-0d7242069b9c)

**Comment by d4kir92** [comment]
with

login anonymous
app_update 4020 -beta dev validate
quit

i have the same lua file

**Comment by d4kir92** [comment]
the problem is that i dont had that error another server owner has this error
i only got the error from there

it is in my gamemode that only calls "ply:Give(ClassName)"
full error:
lua/includes/extensions/entity.lua:240: bad argument #3 to 'SetFunc' (number expected, got nil)
[C]: in function 'SetFunc'
lua/includes/extensions/entity.lua:240: in function '__newindex'
lua/includes/extensions/entity.lua:328: in function 'SetForm'
[string "--[[-------------------------------------------------------------------]]--[[..."]:937: in function 'SetStandard'
[string "--[[-------------------------------------------------------------------]]--[[..."]:240: in function <[string "--[[-------------------------------------------------------------------]]--[[..."]:236>
[C]: in function 'Give'
gamemodes/yourrp/gamemode/yrp/sv/db/players/db_players.lua:161: in function <gamemodes/yourrp/gamemode/yrp/sv/db/players/db_players.lua:159>
[C]: in function 'pcall'
gamemodes/yourrp/gamemode/yrp/sv/db/players/db_players.lua:240: in function 'YRPSetRole'
gamemodes/yourrp/gamemode/yrp/sv/gm/sv_gamemode.lua:279: in function 'YRPPlayerLoadout'
gamemodes/yourrp/gamemode/yrp/sv/gm/sv_gamemode.lua:336: in function <gamemodes/yourrp/gamemode/yrp/sv/gm/sv_gamemode.lua:334>

**Comment by robotboy655** [comment]
Whatever this is:
```
[string "--[[-------------------------------------------------------------------]]--[[..."]:937: in function 'SetStandard'
[string "--[[-------------------------------------------------------------------]]--[[..."]:240: in function <[string "--[[-------------------------------------------------------------------]]--[[..."]:236>
```
is coming from one of your addons and could be causing the issue.

Also the `SetForm` is probably a function defined on some custom entity via https://wiki.facepunch.com/gmod/Entity:NetworkVar and is set to accept a number, but is called with a `nil`.

So either way, as far as I am concerned, the issue with your code, not the game's.

**Comment by d4kir92** [comment]
ok, so its an addon fault, thx :D
