### ISSUE TITLE
DynamicLight brightness changes depending on FOV

### ISSUE THREAD

**Issue by edenoftheware** [Facepunch/garrysmod-issues#5468]
### Details
I am using DynamicLight inside of an entity draw function to add light to the entity. While tweaking the code I noticed that when I tabbed out of the game the DynamicLight would start to [flicker rapidly. (seizure warning)](https://cdn.discordapp.com/attachments/861870369874116638/1112950458110197761/gmod_H9Zasd7kIJ.gif) If this is a massive issue for you, you can mitigate it by putting the DynamicLight in an `if system.HasFocus() then` block.
DynamicLight's brightness seems to be dependent on the client's FPS. Lower FPS makes DynamicLight's brightness visibly darker. Changing the dlight to an elight still causes the brightness to be dependent on the client's FPS. 

### Steps to reproduce
[**GIF Showcasing the bug (this one is easy on the eyes)**](https://cdn.discordapp.com/attachments/861870369874116638/1112947357240270949/hl2_k0kpEQlBaX.gif)
Here is code you can use to immediately reproduce it. 
```lua
function ENT:Draw()
	local dlight = DynamicLight(self:EntIndex())
	if dlight then
		dlight.pos = self:GetPos()
		dlight.r = 255
		dlight.g = 0
		dlight.b = 0
		dlight.brightness = 2
		dlight.decay = 1000
		dlight.size = 150
		dlight.dietime = CurTime() + 1
	end
end
```

**Comment by robotboy655** [comment]
Both of your issues are caused by your value of the  `decay` parameter. It makes the light fadeout by reducing brightness. You refresh the brightness every frame, but obviously if the time between the refreshes (your FPS) is different, the brightness will look different.

Setting `decay` to 0 will fix these issues for you.
