### ISSUE TITLE
Missing Main Menu (OSX)

### ISSUE THREAD

**Issue by Ari-Memer** [Facepunch/garrysmod-issues#5470]
Its in the tittle, the main menu is missing and I have no clue what to do. Verified integrity of files, reinstalled. Nothing has worked. I'm also on the x86 chromium version of the game (nochromeium launch options)

**Comment by robotboy655** [comment]
`-nochromium` launch options is why its missing.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Comment by Ari-Memer** [comment]
> `-nochromium` launch options is why its missing.
> 
> Duplicate of #5001

My game won't launch without `-nochromium`
Any other advice?
