### ISSUE TITLE
render.Spin can cause crashes

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5472]
### Details
I was testing a bit around and when used render.Spin in a HUDPaint hook, it caused the game to freeze permanently (and on 64bit it crashes)

Crash dump (rename it to .dmp):
[87d87678-dd52-4cda-8f31-5477e161fb06.txt](https://github.com/Facepunch/garrysmod-issues/files/11667550/87d87678-dd52-4cda-8f31-5477e161fb06.txt)

### Steps to reproduce
Using this script, the game will crash as soon as you loaded in: 
```lua
hook.Add( "HUDPaint", "Example_Crash", function()
	render.Spin()
end )
```

**Comment by robotboy655** [comment]
I have tried the script on both `dev` and `x86-64` and there were no crashes, just a lot of flickering
