### ISSUE TITLE
Setmaterial won't go away upon respawn in chronium + 64bit.

### ISSUE THREAD

**Issue by Diaz0410** [Facepunch/garrysmod-issues#5473]
### Details
			surface.SetDrawColor( 255, 255, 255, 255 )
			surface.SetMaterial(Material("example/example.png"))
			surface.DrawTexturedRect(0, 0, ScrW(), ScrH())

width=1202&height=676](url)
_I ran on the major issues for the nextbots everytime kills me. the killscreen material won't go away upon respawn.

The Version used is chromium 64bit_

**Comment by Diaz0410** [comment]
https://media.discordapp.net/attachments/1036587405836300349/1116017733151244328/image.png?width=1202&height=676

**Comment by Diaz0410** [comment]
Solved already: due to https://steamcommunity.com/sharedfiles/filedetails/?id=2787599150&searchtext=garbage

**Comment by robotboy655** [comment]
This is not a place to get help with individual addons. You should be contacting the addon author about any bug reports with a specific addon.
