### ISSUE TITLE
PlayX's Navigator stopped working 2 years ago

### ISSUE THREAD

**Issue by juliocoliveira** [Facepunch/garrysmod-issues#5474]
Hi, I'm a developer for PlayX, an add-on for Garry's Mod located https://github.com/ZionDevelopers/playx, used to play youtube and other provider videos, Our HTML browser for is located here: https://github.com/ZionDevelopers/playx/blob/master/lua/autorun/client/cl_html.lua and here https://github.com/ZionDevelopers/playx/blob/master/lua/playx/client/vgui/playx_browser.lua, it stopped working about 2 years ago, and nobody managed to fix it.

Can you please take a look?
The issue is that the URL is no longer being detected, well, it does, twice!, but then it stops working.
I don't know what was changed, or is a bug, and I don't really know much of lua, tried to seek help on the wiki, Didn't got any luck in finding out what is the issue.

Our navigator broke, and Sam's Media Player Browser also broke, not detecting URLs anymore.

You can check out our issue here: https://github.com/ZionDevelopers/playx/issues/124

Please help!

**Comment by juliocoliveira** [comment]
I'm using the x86-64 branch.

**Comment by Kefta** [comment]
This is not a support repo. Ask specific questions in the Discord.

**Comment by juliocoliveira** [comment]
OK
