### ISSUE TITLE
DListView crashes on dev

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5475]
### Details
Currently on the dev branch there seems to be a regresssion regarding #5334 and DListView crashes my game whenever using fixed columns.
Inside the loop in dlistview.lua:160, it appears that the math.floor was removed and the math.ceil in line 166 was changed too.
I could not find the change in the GitHub repository so I believe it must be somewhere on a private branch.

**Comment by RaphaelIT7** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/64648134/dc290866-167a-4455-b102-8e631d2f2178)

**Comment by FredyH** [comment]
>btw heres the commit from #5334 [Facepunch/garrysmod@213deea](https://github.com/Facepunch/garrysmod/commit/213deeabbee280251464f55567090fcaba6655fd)
The commit you linked actually fixes the issue, but for whatever reason the DListView.lua that is included in the dev branch is different from the version in this repo, which is why it crashes. The version on master works perfectly fine and was already included in the last gmod update.

**Comment by robotboy655** [comment]
Fixed.
