### ISSUE TITLE
RunConsoleCommand does not work with `removeid`

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5478]
### Details
RunConsoleCommand does not work with removeid as removeid doesn't support `"` around the steamid as can be seen here:
![image](https://github.com/Facepunch/garrysmod-issues/assets/69946827/335097a4-0dc9-43ef-b1a1-149a774e4eb4)

### Steps to reproduce
```
banid 0 STEAM_0:1:712246363;lua_run RunConsoleCommand( "removeid", "STEAM_0:1:712246363" );lua_run game.ConsoleCommand( "removeid STEAM_0:1:712246363\n" )
```
![image](https://github.com/Facepunch/garrysmod-issues/assets/69946827/7e34823b-0495-4577-b73c-3eb53e0c7534)

**Comment by wrefgtzweve** [comment]
I've come up with a jank fix for now if anyone is interested:
```lua
local allowedCharsStr = "STEAM_:1234567890"
local allowedCharsIndex = string.Explode( "", allowedCharsStr )
local allowedChars = {}

for _, char in ipairs( allowedCharsIndex ) do
    allowedChars[char] = true
end

-- later in the code
for i = 1, #steamid do
    if not allowedChars[steamid[i]] then
        return
    end
end

local safe = util.SteamIDFrom64( util.SteamIDTo64( steamid ) )

game.ConsoleCommand( "removeid " .. safe .. "\n" )
```

**Comment by robotboy655** [comment]
Should be fixed on dev
