### ISSUE TITLE
Saving with cameras makes cameras permanent

### ISSUE THREAD

**Issue by GearsofTime** [Facepunch/garrysmod-issues#5482]
When saving and cameras are present, upon loading the save the cameras cannot be accessed or removed, they become a permanent part of the map.

Default cameras are affected, as well as other camera addons.

**Comment by robotboy655** [comment]
Cannot reproduce. I am assuming you mean `Spawnmenu > Saves` tab saving.

1. Do you get any Lua/script errors when saving or loading the save?
2. Does it happen when you disable all addons and then start a new map?
3. Are you sure you a not accidentally using the `Static Camera` option?
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/9ca6d601-e472-46dd-87c4-ecd400719d9d)
