### ISSUE TITLE
Chromium is outdated

### ISSUE THREAD

**Issue by TheArtemMaps** [Facepunch/garrysmod-issues#5485]
### Details
When i am on Chromium branch of Garry's Mod, i can't use VJ Base addon and Half-Life Resurgence either. This also happens to other addons, not only VJ Base and Half-Life Resurgence. It creates a lot of Lua errors, and addon developers cannot fix this unless you update the Chromium bracnh to the last version, because it's outdated. Please fix this.

### Steps to reproduce
Update the Chromium bracnh to the last version, because it's outdated.

**Comment by Kefta** [comment]
Use x86-64(-temp, though this will be going away soon) instead - Chromium is a dead branch.
