### ISSUE TITLE
When bsp contains a packed ain file, ain file in maps\graphs will not load

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#5489]
Is this a feature?
For example, map ttt_bf3_ziba_tower, when I try to node this map, I have to
1.Extract the gma addon to get ttt_bf3_ziba_tower.bsp
2.Rename ttt_bf3_ziba_tower.bsp to ttt_bf3_ziba_tower1.bsp so the ain file name in bsp does not match the map name (there is no tool that can erase a zipped file in bsp)
3.Noding the ttt_bf3_ziba_tower1.bsp with nodegrapheditor, test the nodes as usual, save ttt_bf3_ziba_tower1.ain (renaming the map breaks its cubemap)
4.Rename ttt_bf3_ziba_tower1.ain to ttt_bf3_ziba_tower.ain, pack it into ttt_bf3_ziba_tower.bsp using bspzip (Note: bspzip is not included in GMOD, find it in HL2 bin)
5.Play ttt_bf3_ziba_tower.bsp

**Comment by robotboy655** [comment]
Not a bug, files packed in the .bsp take precedence over any other file locaitons.
