### ISSUE TITLE
Phong lighting issue in chromium

### ISSUE THREAD

**Issue by yourtoast4** [Facepunch/garrysmod-issues#5490]
### Details
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 20:05:06 Jun 21 2023 (8992) (4000)
GMod version 2023.06.21, branch: x86-64, multicore: 1
Windows 64bit

x86-64 Chromium Branch

There appears to be a bug with the phong lighting in the chromium branch.
It looks like it is causing $phongboost on materials to be ramped up to a really high value if undefined, causing models to appear super shiny or practically white, where as in the release build, materials with no phong parameters rather than just having it be enabled, would not appear this way.
This is breaking existing models on the workshop which have these material parameters, causing them to look really bad.

### Steps to reproduce
no particular steps required, only spawning or viewing a model which is affected.
if there are no models available, creating a material with $phong set to 1 with no additional parameters such as $phongexponent or $phongboost should be able to reproduce the effect when it is applied to a model, if it doesn't try adding a light warp texture to the vmt.

**Comment by robotboy655** [comment]
It was already fixed on Friday. Your game is out of date.
