### ISSUE TITLE
Bug with Static Prop Lightmaps

### ISSUE THREAD

**Issue by qwerty-gm** [Facepunch/garrysmod-issues#5493]
### Details
When compiling a prop with Lightmap, it gets dimmed
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/0cad3888-64a9-4f0d-b309-255086edb0a6)

### Steps to reproduce
Set key values:
generatelightmaps > 1
lightmapresolutionx > 16
lightmapresolutiony > 16

**Comment by robotboy655** [comment]
1. The resolution is probably too small
2. The model cannot have overlapping UV coordinates.

**Comment by qwerty-gm** [comment]
okay
