### ISSUE TITLE
Problem with $phong on brushes

### ISSUE THREAD

**Issue by qwerty-gm** [Facepunch/garrysmod-issues#5494]
### Details
$Phong does not work as it should, if you compare the same material settings in CS:GO and in Garry's Mod, they are different

CS:GO:
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/d623af58-569d-418c-a1bd-cb97e9ea81c1)

GMOD:
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/565ce6c2-3d74-449f-a572-f87219c7e738)

### Steps to reproduce
Create a material with these parameters:

"lightmappedgeneric"
{
    "$basetexture" "tile/hr_t/inferno/tile_a"
    "$bumpmap" "tile/hr_t/inferno/tile_a_normals"
    "$surfaceprop" "tile"
    "$normalmapalphaenvmapmask" "1"
    "$envmap" "env_cubemap"
    "$envmaptint" "[.6 .6 .6]"
    "$detail" "detail/plaster_detail_01"
    "$detailscale" "[5 5]"
    "$detailblendfactor" ".4"
    "$envmaplightscale" "1"
    "$phong" "1"
    "$phongexponent" "80.0"
    "$phongmaskcontrastbrightness" "[2 .7]"
    "$phongamount" "[1 1 1 1]"
}

**Comment by robotboy655** [comment]
Have you tried actually testing the map in CS:GO rather than using the picture from Valve Developer Wiki?

**Comment by qwerty-gm** [comment]
ладно закрывай
