### ISSUE TITLE
Steam Voice Settings button does not function

### ISSUE THREAD

**Issue by vqzz** [Facepunch/garrysmod-issues#5498]
I noticed that my voice was not being picked up so I attempted to change my input microphone using the button within the game options, I noticed It wasn't working. I assume its due to the steam overlay update more than the garry's mod update but I will report it here anyway.

Within the game options -> voice -> Steam Voice Settings.

This button does not function as intended and instead just opens the steam overlay.
I am on the x86-64 - Chromium + 64-bit Binaries beta ( 2023.06.28 )
Version output:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:00:04 Jun 28 2023 (8999) (4000)
GMod version 2023.06.28, branch: x86-64, multicore: 1
Windows 64bit

![gmod](https://github.com/Facepunch/garrysmod-issues/assets/84771445/6662f7ef-3357-44e6-ba7b-240fff49ed72)

**Comment by robotboy655** [comment]
Made it open "Steam Settings" in the overlay, best I can do with what Valve game us.
