### ISSUE TITLE
disableflashlight on static props

### ISSUE THREAD

**Issue by qwerty-gm** [Facepunch/garrysmod-issues#5500]
### Details
disableflashlight keyvalue not working on prop_static
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/eec3d717-4308-432b-a98f-04113b072215)

### Steps to reproduce
1. add key disableflashlight with value 1
2. compile the map
3. point your flashlight at this prop_static

**Comment by robotboy655** [comment]
Static props are not entities.

**Comment by qwerty-gm** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/8b21b813-1a0c-455b-ae41-9abbdb0fdac8)

**Comment by robotboy655** [comment]
The fact that someone classified it as such on publicly editable wiki is meaningless. Their whole purpose to exist is because they are cheaper (more performant) than just having `prop_physics` entities.

That being said, I think I can make this happen for you.

**Comment by qwerty-gm** [comment]
This would be very useful to me, because when you turn on the flashlight on the trees with $treeSway, they start flashing and noticeable drop in fps
