### ISSUE TITLE
-multirun stuck at "Authenticating with Steam..."

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5502]
### Details
If you try to join a server with `sv_lan 1` you'll get stuck at "Authenticating with Steam..."
https://www.youtube.com/watch?v=l_t1klAs9-Q

### Steps to reproduce
1. Start a Game and host a server with `sv_lan 1`
2. Start another game with -multirun
3. Try to join the local server
4. See that you're stuck.

**Comment by robotboy655** [comment]
I literally tested this today and it was working perfectly fine.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/783e866f-dd20-4954-b6a2-261d99825924)

Just to make sure, I tested it again using your exact steps. Any "Authenticating with Steam..." issues are due to Steam and are temporary.

**Comment by RaphaelIT7** [comment]
I had this issue first like 2 months ago and since then It never worked for me again.
And just to be sure that it's stuck I let it connect while I was sleeping and after 8 hours I saw that It was still connecting.
(a 10-min Video of a Gmod loading screen 8 hours sped up 50 times)  https://www.youtube.com/watch?v=m9b9pjGhk58

**Comment by RaphaelIT7** [comment]
it's btw still broken for me. Just looked a bit into it, and it seems like the ServerInfo is not sent to the client for some reason
(Seems like the same issue as https://github.com/Facepunch/garrysmod-issues/issues/5635 but for multirun because the SignonState gets set to `SIGNONSTATE_CONNECTED` but the ServerInfo is just not send).

**Comment by robotboy655** [comment]
You are not connecting to a local server?

**Comment by RaphaelIT7** [comment]
```
] sv_lan
"sv_lan" = "1" ( def. "0" )
 - Server is a lan server ( no heartbeat, no authentication, no non-class C addresses )
```
I verified everything, and I'm using a local server and -multirun as far as I can see properly.
I really don't know why this is broken for me, but for a few friends it's broken for them as well

Maybe it is cause by the address the multirun clients connects with not being loopback?
(I saw that in SendPeningServerInfo it's checked if the address is localhost, loopback or a reservedadr so this could maybe cause it? idk)
```
L 01/11/2024 - 17:00:08: "Raphael<4><STEAM_0:1:219468665><>" connected, address "loopback"
L 01/11/2024 - 17:00:45: "(1)Raphael<6><STEAM_ID_LAN><>" connected, address "26.160.xxx.xxx:27006"
```

**Comment by robotboy655** [comment]
Yes that would be why you are getting stuck on this step, for some reason in your network configuration the client address is not a local IP, but seemingly your public IP?

**Comment by RaphaelIT7** [comment]
My public IP starts with 176.xxx.xx.xx, but it could be that it's a subnetwork. Wouldn't it be possible to just get a reference of the sv_lan convar and just to check if it's enabled, and then skip these checks to allow anyone to connect?

**Comment by robotboy655** [comment]
I will look into it when I get time.

**Comment by RaphaelIT7** [comment]
I looked a bit into all my adapters and found that I got one that used the 26.160.*** ip.
Maybe an approach like this would fix it (You would need to call `isAdapterIP`):
```cpp
#include <iostream>
#include <windows.h>
#include <iphlpapi.h>
#include <vector>

#pragma comment(lib, "IPHLPAPI.lib")
std::vector<std::string> getIPAddressList() {
	std::vector<std::string> ipAddresses;

	PIP_ADAPTER_INFO adapterInfo = nullptr;
	ULONG bufferSize = 0;
	if (GetAdaptersInfo(adapterInfo, &bufferSize) == ERROR_BUFFER_OVERFLOW) {
		adapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(malloc(bufferSize));
		if (adapterInfo) {
			if (GetAdaptersInfo(adapterInfo, &bufferSize) == NO_ERROR) {
				for (PIP_ADAPTER_INFO currentAdapter = adapterInfo; currentAdapter != nullptr; currentAdapter = currentAdapter->Next) {
					IP_ADDR_STRING* ipAddress = &currentAdapter->IpAddressList;
					while (ipAddress) {
						ipAddresses.push_back(ipAddress->IpAddress.String);
						ipAddress = ipAddress->Next;
					}
				}
			}
			free(adapterInfo);
		}
	}

	return ipAddresses;
}

bool isAdapterIP(const char* ipAddress) {
	for (const auto& adapterIP : getIPAddressList()) {
		if (strcmp(ipAddress, adapterIP.c_str()) == 0) {
			return true;
		}
	}

	return false;
}
```
The client should also not wait forever to receive a ServerInfo.
Maybe you could add a time limit that if it takes longer than 5 or 10 minutes to receive one, the client will disconnect with an error message `Failed to receive ServerInfo`.
It would make identifying an Issue like this far easier, where it's again just the Server not sending the ServerInfo

**Comment by robotboy655** [comment]
Should be fixed on `dev` soon.
