### ISSUE TITLE
sound.PlayURL(url, "3d") playback (rarely) stops prematurely 

### ISSUE THREAD

**Issue by Rubik7711** [Facepunch/garrysmod-issues#5503]
### Details
Playing a remote mp3 file with sound.PlayURL(url, "3d") and calling IGModAudioChannel:GetLength() returns the length of the audio track. During playback, there is a rare chance that the audio will stop prematurely and IGModAudioChannel:GetLength() will instead return the timestamp when the audio stopped. It seems to only happen when audio is streamed in blocks.  

### Steps to reproduce
```
sound.PlayURL(url,"3d",function(station)
		local ts = 0
		timer.Create("timestamp",1,0,function()
			ts = ts + 1
			print(ts, station:GetLength())
		end)
	end)
```

**Comment by FlorianLeChat** [comment]
You need to keep a reference of the audio object to prevent it from being garbage collected, which will cause your sound to stop. See the Wiki example: https://wiki.facepunch.com/gmod/sound.PlayURL. I think this is probably your issue.

**Comment by biorisk2** [comment]
I am finding this same issue when running something similar to the wiki.

local currentAudio
	sound.PlayURL("http://localhost/audio/"..audioID..".mp3", "3d", function(a)
		if (IsValid(a)) then
			a:SetPos(npc:GetPos()+Vector(0,0,48))
			a:Play()
			currentAudio = a
		end
	end)
	
	The file plays then stops early.

**Comment by FlorianLeChat** [comment]
> I am finding this same issue when running something similar to the wiki.
> 
> local currentAudio sound.PlayURL("[http://localhost/audio/"..audioID..".mp3](http://localhost/audio/%22..audioID..%22.mp3)", "3d", function(a) if (IsValid(a)) then a:SetPos(npc:GetPos()+Vector(0,0,48)) a:Play() currentAudio = a end end)
> 
> ```
> The file plays then stops early.
> ```

Have you tried storing the audio object in a global variable instead of a local one (as illustrated in the wiki example)? I assume variables in `_G` are not garbage collected.
