### ISSUE TITLE
Problem With The Level Initialization Process.

### ISSUE THREAD

**Issue by ProgrammingToast** [Facepunch/garrysmod-issues#5506]
It seems that Garry's Mod and the worldspawn entity are currently bugged in the latest Chromium branch. 
When a level is loaded, all of the npcs that spawn with the world will have null HP values, as they each die from one bullet. This is then fixed afterwards after running a gmod_admin_cleanup.

To replicate the problem, run Garry's Mod and load a level with npcs that spawn with the world, they will then have null HP. In order to get the same issue again, you have to close Garry's Mod and open it again.

Video demonstration of the bug: https://youtu.be/w4ZH2aUrzlA

**Comment by robotboy655** [comment]
It is because of this: https://github.com/Facepunch/garrysmod-requests/issues/1148

**Comment by robotboy655** [comment]
Should be fixed on Dev beta. Other versions will be updated later.

**Comment by ProgrammingToast** [comment]
Thank you for your hard work!
