### ISSUE TITLE
RunConsoleCommand no work pls help

### ISSUE THREAD

**Issue by Miguelito223** [Facepunch/garrysmod-issues#5508]
What happens is that in my mod with the day and night cycle when I enter a map without env_skypaint it doesn't work but I put in my mod that an env_skypaint is generated and execute the RunConsoleCommand( "sv_skyname", "painted " ) and also game.ConsoleCommand( "sv_skyname painted\n" ) but it doesn't seem to work and I'm trying to find a solution to this but it seems to be a game problem because before it worked before the last update and I don't know anymore what to do please fix this

![image](https://github.com/Facepunch/garrysmod-issues/assets/82764240/b510035b-98dd-4f97-8f84-f50d87f73ea8)
![image](https://github.com/Facepunch/garrysmod-issues/assets/82764240/e45f2891-c882-4a22-ac9e-fb76419b0725)
![image](https://github.com/Facepunch/garrysmod-issues/assets/82764240/e7159b93-a265-4616-bb94-705e92d9fd62)

**Comment by Miguelito223** [comment]
I had to change to PlayerInitialSpawn to make it work please fix it
![image](https://github.com/Facepunch/garrysmod-issues/assets/82764240/e7035c1b-bc0a-438d-9bd3-5ea5cc53e9b5)

**Comment by robotboy655** [comment]
This is not a place to get help. You can ask generic Lua questions on our official Discord server (https://discord.gg/gmod).
