### ISSUE TITLE
NPCs and Weapons spawning the wrong Particles.

### ISSUE THREAD

**Issue by petetheman23** [Facepunch/garrysmod-issues#5509]
### Details
This happened on the chromium beta branch. It should be noted beforehand that I do have a lot of addons installed, _however_ the problem is similar to the table_particleffectnames is full that I've been having before this update. The addons I've had have not changed from the two versions, and this issue seems to have replaced the old one, looking at the console. Instead of the "table_particleffectnames is full" error appearing from the last update, it shows a similar error. "info_particle_system (PARTICLE) has no particle system name specified!" 

Since you guys are taking steps to remove limitations on how many addons somebody could have installed, this was one of the first things I deliberately tested, so I hope this report helps!

### Steps to reproduce
Making or installing enough addons/particle effects will recreate the problem.

**Comment by robotboy655** [comment]
Without some kind of reliable way of making this happen on my end, there's not much I can do.

From what I can see, the warning happens when `info_particle_system` entity does not have a particle system name set at all, on the server. So it should not even be related to the changes in the update.

**Comment by funkynuggets** [comment]
Can confirm this is an issue. With enough particle inducing mods (with NPCS I assume) will make them give the incorrect particle effect. The particles do seem to change depending on addon count, which makes me assume it's somehow wrapping around the particle table rather then extending it? Not a programmer but that's my best guess. Issue is extremely repeatable as long as you have enough addons for it.
![image](https://github.com/Facepunch/garrysmod-issues/assets/4592402/52637f07-dc41-4769-b637-195eb2150d41)

**Comment by robotboy655** [comment]
I think it should be fixed on `dev` beta. Can you confirm?

**Comment by funkynuggets** [comment]
> I think it should be fixed on `dev` beta. Can you confirm?

Tried to check but seems to crash to desktop on any map I load. Can't really disable the addons since that... well, defeats the point.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Crash_Reporting

I have also updated the `x86-64` if you were using that before.

**Comment by funkynuggets** [comment]
Whatever you did seems to have fixed it. I appreciate your support!

**Comment by robotboy655** [comment]
Sorry, x86-64 failed to build yesterday, it should be up to date now, and contain the fix for this issue.

**Comment by robotboy655** [comment]
Ok, this cannot be fixed without a network compatibility breaking update. Could've been avoided if people tested this before the June update, but oh well.

**Comment by funkynuggets** [comment]
You're doing great work that garry's mod has benefited from a lot in the last year. I don't think anyone's gonna complain about waiting another month for it.

**Comment by evilpigeonlol** [comment]
I can back up OP's post, not sure how to fix it for myself in the meantime
