### ISSUE TITLE
Picking up a jeep with a charged gravity gun lags the game

### ISSUE THREAD

**Issue by yurkapotam** [Facepunch/garrysmod-issues#5510]
### Details
Picking up a jeep with a charged gravity gun lags the game, and sometimes makes the jeep go flying

### Steps to reproduce
"global_set super_phys_gun 1" into the console to charge the gravity gun, then spawn a jeep and pick it up with the charged gravity gun

**Comment by robotboy655** [comment]
You can no longer do that.
