### ISSUE TITLE
Additional ai-nodes in ain file do not link with the original ones

### ISSUE THREAD

**Issue by ExboCooope** [Facepunch/garrysmod-issues#5514]
When try to add nodes in some map to fix connection issues, new added nodes will not link with the buildin ones.
In really old version (2016) it was fine, and now the added node maps are broken. 

![20230707204821_1_info](https://github.com/Facepunch/garrysmod-issues/assets/10217833/561c9390-f186-4b38-8c31-7cc7e60065ac)
In map d1_canals_08, about the picture, the left side's origin nodes have broken links so i removed them all and added my own node.
The green lines "ai_show_connect" indicate the links are successfully loaded, but the purple lines "ai_show_graph_connect" indicate that only the new nodes themself are linked with each other, and the npc_go will fail between origin node and new node

[d1_canals_08.txt](https://github.com/Facepunch/garrysmod-issues/files/11987140/d1_canals_08.txt)
rename the file to d1_canals_08.ain and put into maps/graphs/

**Comment by robotboy655** [comment]
I don't know where you are getting this idea of "old nodes" and "new additional nodes". All of the nodes are stored in that file. There are no "additional nodes" loaded from elsewhere.

The green lines are the "allowed connections". The purple lines are possible connections. If you didn't notice, there are objects that cannot be walked through in the way of your purple lines that do not have an accompanying green line.

Since the NPCs would not be able to walk on those lines, obviously the connection cannot be made or "allowed".
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/148b8b62-abf5-4023-b975-2b3cbe75c0d8)

The NPCs can walk around the obstacles using the green lines, which they do:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/c9a0c96c-1fb1-46a8-8f4e-3c88ba0d7454)

**Comment by ExboCooope** [comment]
> I don't know where you are getting this idea of "old nodes" and "new additional nodes". All of the nodes are stored in that file. There are no "additional nodes" loaded from elsewhere.
> 
> The green lines are the "allowed connections". The purple lines are possible connections. If you didn't notice, there are objects that cannot be walked through in the way of your purple lines that do not have an accompanying green line.
> 
> Since the NPCs would not be able to walk on those lines, obviously the connection cannot be made or "allowed". ![image](https://user-images.githubusercontent.com/3299036/252373592-148b8b62-abf5-4023-b975-2b3cbe75c0d8.png)
> 
> The NPCs can walk around the obstacles using the green lines, which they do: ![image](https://user-images.githubusercontent.com/3299036/252372367-c9a0c96c-1fb1-46a8-8f4e-3c88ba0d7454.png)

This is the old graph if you delete the ain file and the game recreates one.
![20230711223435_1](https://github.com/Facepunch/garrysmod-issues/assets/10217833/1e4d64ee-010c-4089-b091-381d614737ea)

Remove nodes using nodegraph editor 
![20230711223625_1](https://github.com/Facepunch/garrysmod-issues/assets/10217833/8faae6af-edc9-4e65-858c-770566c9c28b)

Plot some new nodes and links
![20230711223704_1](https://github.com/Facepunch/garrysmod-issues/assets/10217833/4da91bfb-b3e7-403c-942d-6bfec4e2adb0)

Save the ain file and reload map, those links between new nodes and old nodes are not working
![20230711224857_1](https://github.com/Facepunch/garrysmod-issues/assets/10217833/597c2215-fcd7-4cbb-bc26-9e3462819acd)


[d1_canals_08.txt](https://github.com/Facepunch/garrysmod-issues/files/12016295/d1_canals_08.txt)

**Comment by ExboCooope** [comment]
Thanks, fixed by setting all node to zone 0

**Comment by robotboy655** [comment]
That's a bad idea, as NPCs will now try to walk through unwalkable places (or the pathfinding will timeout and fail), but do as you like.

**Comment by ExboCooope** [comment]
Actually noding a map mostly means to make a single connected graph so it doesn't matter
But I really think in the old version the 'zone' might not fuctioning because I fixed the gm_floatingworlds_3 (2015/10/2) broken node network near the castle and played with npc, in that day the ain file in game folder still can override the one in bsp
