### ISSUE TITLE
'Screenshot' command naming is broken on certain maps

### ISSUE THREAD

**Issue by Thespikedballofdoom** [Facepunch/garrysmod-issues#5516]
### Details
Screenshotting using the 'screenshot' command outputs incorrect numbers for the first few screenshot names. For instance pl_frontier_final creates screenshot names in the order
```
pl_frontier_final0007.tga
pl_frontier_final0010.tga
pl_frontier_final0011.tga
```
and then continues incrementing normally. ctf_2fort starts at ctf_2fort0009.tga and then ascends normally. 
This happens on x86-64 beta and None.
I am running windows 10 with an Nvdia GPU and AMD CPU.

### Steps to reproduce
Use the screenshot command on any map you want and check the order that appears in garrysmod/garrysmod/screenshots. The issue is with the first couple screenshot names so make sure you don't have any on the map you screenshot before you test.
It doesn't happen on gm_construct for me. I would test on pl_frontier_final or just a map renamed to it if you don't have TF2

**Comment by robotboy655** [comment]
You have screenshots of those maps in TF2, so the game tries to avoid those names to not overwrite the existing files.

This is a non-issue.
