### ISSUE TITLE
Two SetPos calls on a panel child inside PerformLayout cause PerformLayout to be called again in the next frame

### ISSUE THREAD

**Issue by bydlocodd** [Facepunch/garrysmod-issues#5519]
### Details
If SetPos is called twice within `PANEL:PerformLayout` for the same child (whether explicitly or implicitly) and at least one of the arguments is different, it will cause PerformLayout to be called again in the next frame. If the arguments are consistently different (they often are), PerformLayout will be called every frame.

### Steps to reproduce
```lua
local PANEL = {}
PANEL.Base = 'EditablePanel'

function PANEL:Init()
    local button = vgui.Create('DButton', self)
    button.DoClick = function()
        self:Remove()
    end
    self.button = button
end

-- the issue part
function PANEL:PerformLayout(w, h)
    self.button:SetPos(0, 1)
    self.button:SetPos(1, 1)

    print(SysTime())
end

local panel = vgui.CreateFromTable(PANEL)
panel:SetSize(400, 400)
panel:Center()
```
After running the code, the current `SysTime` will be displayed in the client console each frame.
Obviously there is no reason to explicitly call `SetPos` twice on the same panel, but there are cases where it is done implicitly (e.g. `SetPos` with one zero argument + `CenterVertical`/`CenterHorizontal`).
Tested on `x86-64`, however, I have encountered this problem many times and on different versions, plus heard about it from others.

**Comment by Be1zebub** [comment]
is this happens when changing `panel.x, panel.y` directly?

**Comment by bydlocodd** [comment]
Yes
```lua
function PANEL:PerformLayout(w, h)
    self.button.x = 1
    self.button.x = 2

    print(SysTime())
end
```

(the same with `self.button.y`)

**Comment by robotboy655** [comment]
This is intentional, I imagine for cases where child panels affect size of a container panel, such as scrollable panels.
