### ISSUE TITLE
language.Add(placeholder, fulltext) silently failes for very long texts

### ISSUE THREAD

**Issue by Grocel** [Facepunch/garrysmod-issues#5524]
### Details
The function `language.Add(placeholder, fulltext)` silently fails when `fulltext` >= 1024 bytes long. The limit also affects UTF8 strings. When the text for the `placeholder` is retrieved with `language.GetPhrase(placeholder)`, the result will be an empty string.

Please make it error/warn about too long strings and add the information to the documentation (https://wiki.facepunch.com/gmod/language.Add), if not done yet. In addition I would also like to request the limit to be raised if possible.

#### Version
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:37:54 Jul 13 2023 (9013) (4000)
GMod version 2023.07.14, branch: x86-64, multicore: 1
Windows 32bit
```
### Steps to reproduce
Test in Console. The top two cases are the error cases. The bottom one is the working case.
```
lua_run_cl language.Add("test1024-1", string.rep("a", 1024)) local a = language.GetPhrase("test1024-1") print(#a, a)
> 0 (empty string)

lua_run_cl language.Add("test1024-2", string.rep("a", 5000)) local a = language.GetPhrase("test1024-2") print(#a, a)
> 0 (empty string)

lua_run_cl language.Add("test1024-3", string.rep("a", 1023)) local a = language.GetPhrase("test1024-3") print(#a, a)
> 1023 aaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaa (1023 times)
```

**Comment by robotboy655** [comment]
Fixed on dev. Limit increased to 4k, if limit is hit, the string is truncated, not emptied
