### ISSUE TITLE
Trigger_hurt set to Doubling with forgiveness isn't so forgiving

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#5525]
### Details
trigger_hurt brushes can be made to do damage that grows exponentially using the model "Doubling w/ forgiveness"
Hammer says that upon steping out of the trigger, the damage should reset back to base, but this isn't actually true.

### Steps to reproduce
make a map and place a trigger_hurt set the damage model to "Doubling w/forgiveness"
set the damage to 1 and the cap to 128.
compile the map.

in game, go stand in the trigger until it kills you.
go back into the trigger and you see that you are taking 64 damage every half second

### Other
if i was allowed to, i'd send a simple example map with a trigger hurt of every damage type set to doubling with forgiveness

**Comment by joeyjumper94** [comment]
issue needs to be reopened as trigger hurts still do not forgive

**Comment by robotboy655** [comment]
I just tested it for you, and it is definitely fixed. It takes 3 seconds for it to reset the damage. The damage is NOT per player.
