### ISSUE TITLE
Reporting about DTextEntry

### ISSUE THREAD

**Issue by BleueBear** [Facepunch/garrysmod-issues#5528]
Reporting about DTextEntry only working in DFrame and not DPanel
```[tasklist]
### Tasks
- [ ] To fix DTextEntry to work in dPanel
```

**Comment by robotboy655** [comment]
As the [wiki page for DTextEntry](https://wiki.facepunch.com/gmod/DTextEntry) states:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/12b344b1-3290-40fb-a0fb-15ee54839404)

Your DTextEntry must be parented to an EditablePanel somewhere in its hierarchy to work correctly. It is not a bug.
