### ISSUE TITLE
Linux dedicated server core dump - libtcmalloc

### ISSUE THREAD

**Issue by crosscoder1** [Facepunch/garrysmod-issues#5529]
### Details
Initially we were on the -dev branch when this started occurring late in late June when we switched back to the public branch to resolve.  Then since, I believe the first July update, our dedicated server began crashing again in the same way.  The following is displayed  :
 
`src/tcmalloc.cc:283] Attempt to free invalid pointer 0xf7cb43fc 
Aborted (core dumped)
`

I've attempted a fresh, vanilla install with steamcmd with the public branch which produced the same results.  The debug log gives no indication of the issue but I am attaching a gdb backtrace.  I did attempt to substitute the library mentioned with other versions and even built my own to try but all crashed in the same manner.  (The backtrace is using the original library downloaded with the steamcmd install.)

Rolling back the server to our previous backup with build 21:15:08 Jun 27 2023 (8998) (4000), allows the server to start again.

The server VPS host is running Ubuntu 22.04.2, 2 Core CPU, 4GB RAM, kernel 5.15 .

### Steps to reproduce
Update to the latest public branch for the Linux dedicated server and launch as normal.

[libtcmalloc-gdb.txt](https://github.com/Facepunch/garrysmod-issues/files/12130827/libtcmalloc-gdb.txt)

**Comment by robotboy655** [comment]
Can you please test the `dev` beta on your server in an hour or so from this message and let know if that fixes the issue?

**Comment by crosscoder1** [comment]
I updated to the dev branch and the crash has been resolved.   Thank you for you impressively quick response!
