### ISSUE TITLE
Having  -tools parameter prevents clicking on any non pop up vgui

### ISSUE THREAD

**Issue by GrandpaTroll** [Facepunch/garrysmod-issues#5530]
### Details
Having the tools parameter overrides gmod's mouse focus, thus preventing you from interacting panels that aren't popup.

### Steps to reproduce
Go to steam and edit gmod properties and select properties 
![NVIDIA_Share_07-21-2023_1689963470](https://github.com/Facepunch/garrysmod-issues/assets/28169447/a2649b53-78f7-48dd-b15d-4b18c241ff36)
and add -tools to the parameter
![NVIDIA_Share_07-21-2023_1689963271](https://github.com/Facepunch/garrysmod-issues/assets/28169447/f3b9e08b-b001-4b99-ac96-551f2a9dfd14)

Then just join any game and try to click on any interactable non popup uis (scoreboards, gun mods (arccw,fas,cw2.0),etc)
![NVIDIA_Share_07-21-2023_1689963497](https://github.com/Facepunch/garrysmod-issues/assets/28169447/ab8277de-e560-45e8-9ba4-b094fab3e0c5)
![NVIDIA_Share_07-21-2023_1689963526](https://github.com/Facepunch/garrysmod-issues/assets/28169447/d3b9a8de-c524-4881-89f1-47d8ae760c4e)

**Comment by robotboy655** [comment]
You are most definitely not supposed to play the game with `-tools` option enabled. I consider this to be user error. `-tools` is only used to access the Source Engine's built-in particle/commentary and faceposer tools, which do not function on the 64bit build of the game. (https://github.com/Facepunch/garrysmod-issues/issues/4459)
