### ISSUE TITLE
mess up font render

### ISSUE THREAD

**Issue by chenbuyi2019** [Facepunch/garrysmod-issues#5531]
### Details
Our server runs DarkRP mode. 
Server environment: 
```
Exe version 2023.06.28 (garrysmod)
Exe build: 16:44:59 Jul 13 2023 (9014) (4000)
GMod version 2023.07.14, branch: unknown    in fact, it is default branch.
Windows 32bit Dedicated Server

OS: Windows Server 2019 x64
```

after June 2023 update, we got a new problem.  
some players found font,text render messed up.   
usually, it happens after the player joined our server after 1-3 hours.  

the fonts, models, textures we used didn't increase much.  
but the problem keep happening randomly in the server.  

some of them only saw the text messed up. and some saw it quickly happen and then their game crashed.   
also,we found that when the game crashed, the GPU Memory was used up.

many fonts we used are Chinese fonts.

screenshot:   
![image](https://github.com/Facepunch/garrysmod-issues/assets/26303007/fa72561f-3163-4c61-a345-899c4e27c9a0)
![image](https://github.com/Facepunch/garrysmod-issues/assets/26303007/e295ea1f-ed3e-43fc-9e84-905bf9b8d644)
![image](https://github.com/Facepunch/garrysmod-issues/assets/26303007/941a1288-afe1-417c-a79e-083d9f9e971e)

the messed part is different each time.    
some times it happens in 3D2D hook like nickname over players' head.   
some are in the HUDPaint like chatbox or console or menu.

### Steps to reproduce
sorry i dont know how to excatly make it happen.   

I got this problem this before. 
I used `AMD RX 6600 (8GB)` and i didnt crash.  
As i am a developer of server, when i hot reload to re-create a font in using, the text render became well again.   

I asked two players in my server who meet this problem.   
their GPU is `GTX 950 (2GB)` and `RTX 4060 (8GB)`.  
but their game didn't crash.

**Comment by robotboy655** [comment]
There were some changes to the game so that when the game runs out of memory, instead of just crashing it tries to handle the issue more gracefully.

This is likely why instead of crashing your players are now seeing missing textures. The underlying problem is still the same - running out of memory, that that RAM or VRAM.
