### ISSUE TITLE
Instant server crash when using PhysicsInitSphere

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5535]
### Details
After searching around why some addons interacting with each other was crashing the server i've found that `PhysicsInitSphere` will crash the server when used on a prop with `EnableCustomCollisions` enabled. This can currently be abused in some larger gmod addons, i won't list which ones as that'd make abusing it too easy.

### Steps to reproduce
1. Spawn a regular prop_physics
2. Run the following code on it:
```lua
ent:EnableCustomCollisions(true)
ent:PhysicsInitSphere(10)
```
3. Crash

**Comment by brandonsturgeon** [comment]
Temporary mitigation for this issue (serverside):
```lua
-- lua/autorun/server/phsics_init_sphere_fix.lua

local function hasCustomCollisions( ent )
    local solidFlags = ent:GetSolidFlags()
    return bit.band( solidFlags, bit.bor( FSOLID_CUSTOMRAYTEST, FSOLID_CUSTOMBOXTEST ) ) == bit.bor( FSOLID_CUSTOMRAYTEST, FSOLID_CUSTOMBOXTEST )
end

local EntityMeta = FindMetaTable( "Entity" )

EntityMeta._GMS_PhysicsInitSphere = EntityMeta._GMS_PhysicsInitSphere or EntityMeta.PhysicsInitSphere

function EntityMeta:PhysicsInitSphere( ... )
    if hasCustomCollisions( self ) then
        print( "[WARN] Attempted to call PhysicsInitSphere on an entity with custom collisions. Ignoring." )
        self:EmitSound( "buttons/button10.wav" )
        return
    end

    self:_GMS_PhysicsInitSphere( ... )
end
```

Simply prevents `PhysicsInitSphere` from being run on an entity that has custom collisions enabled.
This might not fix _every_ case, but according to the issue, this would otherwise crash the server 100% of the time.

So until a proper fix is implemented, this solution should work 👍

**Comment by robotboy655** [comment]
Should be fixed on dev beta

**Comment by brandonsturgeon** [comment]
Thanks Rubat I love you
