### ISSUE TITLE
Some JPGs cannot be loaded from data folder anymore

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5542]
### Details
Since a few days some JPGs that are located in the data folder do not load anymore and calling `Material()` on them returns an error texture. Replicated on both x64 and x86.

### Steps to reproduce
I have attached the same image as JPG and PNG that you can use to test.
- Place the two images in the data folder, call them `testpng.png` and `testjpg.jpg` respectively
- In LUA run
```lua
print(Material("../data/testjpg.jpg")) -- outputs: Material [___error]	0.00085337508455951
print(Material("../data/testpng.png")) -- outputs: Material [../data/testpng]	0.01329018831338
```

It should be noted that somehow, some of the JPGs do still work (not sure why) and that if placed in the regular materials folder, both seem to load fine.

![1](https://github.com/Facepunch/garrysmod-issues/assets/1258762/fcc9beec-b3d6-4d91-8f64-a77803c6e770)
![1](https://github.com/Facepunch/garrysmod-issues/assets/1258762/04122211-c193-4d32-961e-95d25bbe37c5)

**Comment by garryspins** [comment]
I have _witnessed_ this issue too, it _blows_, hope it gets fixed soon

**Comment by robotboy655** [comment]
Cannot reproduce on `dev` beta, and it also makes no sense. The system was not touched, especially not during "since few days".

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/354795c8-e2d6-46d1-b23c-768576ec81fe)

**Comment by FredyH** [comment]
You are right, it turned out my server host overwrote those functions and blocked loading jpgs from the data folder.
