### ISSUE TITLE
Failed to read addon file: There is no file to mount

### ISSUE THREAD

**Issue by Sigilmare** [Facepunch/garrysmod-issues#5543]
WorkshopDL fails to read the addon file 'Toothless Playermodel' (696201828) for some reason
![image](https://github.com/Facepunch/garrysmod-issues/assets/94254206/9135890e-b37a-45d6-98ff-5176f23be679)

I tested this on the x84-64 branch, still failed, tested on the "None" branch, still failed
![image](https://github.com/Facepunch/garrysmod-issues/assets/94254206/72f2b210-1eb7-4cea-b1ad-7ea04e9e1753)

Factory reset gmod, didn't fix. Verified game files, didn't fix. I have no idea how to fix this.

How to Reproduce: No idea. It works fine for everyone else, and on my other PC. It just says there's no file to mount. (The resource.AddWorkshop is properly done in a serverside file)

**Comment by Sigilmare** [comment]
Update: Tried subscribing to the addon on the workshop and it said this, something is missing/deleted?
![image](https://github.com/Facepunch/garrysmod-issues/assets/94254206/15ee9908-5327-409c-bed4-12d639e19534)

**Comment by robotboy655** [comment]
When you subscribe and go to the path if shows you in console (`steamapps/workshop/content/4000/...`), does the `.bin` file actually exist?

I suspect it does not because the download failed, or you have corrupted your workshop cache by deleting files manually from the aforementioned folder.

**Comment by Sigilmare** [comment]
I looked at a previous issue that had this problem before and deleted all of the existing lines from that one acp file I think, but I have never deleted files from any Steam folder which is strange.

Regading the folder location, the folder does not even exist nor does the bin file.

**Comment by robotboy655** [comment]
So yeah, this is a Steam issue. You should report it to Steam, via their Support. You should never touch internal Steam files, that's how you get into situations like this. 

There's nothing I can do about Steam not downloading the files. It's an issue on their end. In my testing, subscribing to the addon and then verifying Garry's Mod files though Steam does restore the addon. If it does not for you - it's another fault of Steam that you should report to them.
