### ISSUE TITLE
CNavArea:SetParent doesn't accept nil

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-issues#5547]
### Details
While I was recreating NavAreaBuildPath in lua, I noticed that when trying to set the parent of a CNavArea to nil creates the error 
bad argument #1 to 'SetParent' (CNavArea expected, got nil)
    1. SetParent - [C]:-1
        2. unknown - lua_run:1
If you look at Line 120 in https://github.com/sr2echa/TF2-Source-Code/blob/master/tf2_src/game/server/nav_pathfind.h it shows that it is possible to set a CNavArea's parent to nil or NULL.

### Steps to reproduce
1. Go to a map with at least one CNavArea, "gm_construct is a good example"
2. Enter this into your console: `lua_run navmesh.GetAllNavAreas()[ 1 ]:SetParent( nil, 9 )`

**Comment by robotboy655** [comment]
Made it work on `dev`.
