### ISSUE TITLE
lua_find/lua_findhooks can be used clientside to lag servers

### ISSUE THREAD

**Issue by callumok2004** [Facepunch/garrysmod-issues#5548]
### Details
Similar to the issue last year where people could spam `lua_dumptimers_sv`, the `lua_findhooks <query>` can also be spammed to very easily massively lag any server.

### Steps to reproduce
Join any server
Open your console
Type `lua_findhooks a`
Notice the server will lag. The server will lag more depending on how many hooks are registered serverside.

#### Note:
This is limited to server admins (meta:IsAdmin()), but considering there is no log showing who ran the command on the server, it can be very easy for an admin to decide to mess about without anyone knowing who is doing it

**Comment by robotboy655** [comment]
If you are afraid your admins would do this, you have a bigger problem.

That being said, I have made its access restrictions be more like `lua_dumptimers_sv`.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/efd9ae16c948e0d6df406e9ad85f1c4646c96072 Related commit
