### ISSUE TITLE
Panel:SetCursor not working.

### ISSUE THREAD

**Issue by Idol11112222** [Facepunch/garrysmod-issues#5551]
I just want to replace it.

**Code for reproduce the issue:**
`
local frame = vgui.Create("DFrame")
frame:SetSize(512,256)
frame:Center()
frame:MakePopup()
frame:SetCursor("blank")
`
There are no warnings in the console.
Its possible that this is my problem...

**Comment by Idol11112222** [comment]
i think you should mark it on the page https://wiki.facepunch.com/gmod/Panel:SetCursor thanks anyway

**Comment by robotboy655** [comment]
I am not sure that's feasible, its not going to be the only panel doing this, and its not going to be the only function affected like this. It's just something you always have to have in mind what something doesn't work at first try.
