### ISSUE TITLE
npc_vortigaunt dispel effect bug

### ISSUE THREAD

**Issue by combinesoldier2006** [Facepunch/garrysmod-issues#5552]
when the vortigaunt makes the dispel attack,it leaves behind a weird glowing effect.
![gm_construct0003](https://github.com/Facepunch/garrysmod-issues/assets/141918797/bc4e04d5-fb23-4dfb-a7e8-6e52dcd978f3)

**Comment by robotboy655** [comment]
Cannot confirm any effects being left behind, assuming you mean the effect stays forever and doesn't go away.

It's likely an addon issue.

Here is what it looks like on my end:

https://github.com/Facepunch/garrysmod-issues/assets/3299036/9ec455fb-3869-4fad-b6ac-2ffe37534afe

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
