### ISSUE TITLE
Crash in debugoverlay.EntityTextAtPosition() when called with a bad strings.

### ISSUE THREAD

**Issue by Grocel** [Facepunch/garrysmod-issues#5554]
### Details
This crashes the game, when you look at Vector(0,0,0):
```
lua_run_cl debugoverlay.EntityTextAtPosition(Vector(0,0,0), 1, [[%f%s]], 10, color_white)
```

I isolated the bad string to be `%f%s` and all strings containing it. It also happens when `%f` and `%s` is separated by other content as like as `%f crowbar %s`, etc. It did not happen with `%s%f` (reversed) in my tests, though.

Needs `developer 1` to reproduce.
For me it happens around 90% of the time. I had different results on different maps.

### Version
```
] version
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:38:19 Aug  8 2023 (9040) (4000)
GMod version 2023.08.09, branch: unknown, multicore: 1
Windows 32bit
```

### Crash Dumps
[debugoverlay_crash_dumps_20230811.zip](https://github.com/Facepunch/garrysmod-issues/files/12323394/debugoverlay_crash_dumps_20230811.zip)

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.
