### ISSUE TITLE
HTTP PUT request

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-issues#5555]
If send PUT request using [HTTP](https://wiki.facepunch.com/gmod/Global.HTTP) method PUT replaced with POST.

![image](https://github.com/Facepunch/garrysmod-issues/assets/50295867/12926edb-8f06-41c3-a4bd-4484af7b3fdf)

About half a year ago it worked correctly.

**Comment by arkayden** [comment]
I'm sorry I was wrong

**Comment by arkayden** [comment]
I closed it because I thought I made a mistake, but no, it really doesn't work. With libraries garrysmod/bin version 28.06 it's work correctly

**Comment by DotShark** [comment]
I have the same issue on the `2023.08.09` version of the default branch.

I have a few details to add:
- As far as I know, it only occurs when Garry's Mod runs on Windows, Linux version seems to not be concerned
- It can happen both server-side and client-side

I wanted to know exactly which HTTP methods are not working as expected so I created a simple express.js server with a  `/testMethod` route that returns the method use by the HTTP request, here is the javascript code I wrote:
```JS
const express = require("express")
const app = express()
app.use( express.json() )

app.all("/testMethod", (req, res) => {
    res.json({method: req.method})
})
```
(you can use it at this URL [https://api.dotshark.ovh/testMethod](https://api.dotshark.ovh/testMethod))

Then I wrote some lua code to test every HTTP method in Gmod, here is the lua code I wrote:
```Lua
-- Place this file in lua/autorun
local loadsInState = SERVER -- Set it to SERVER or CLIENT depending on whether you want to run it server-side or client-side

if not loadsInState then return end

local function isAllowedToTest(ply)
    if CLIENT then return true end
    if not IsValid(ply) then return true end
    if ply:IsAdmin() then return true end
    return false
end

local methods = {
    "GET",
    "POST",
    "HEAD",
    "PUT",
    "DELETE",
    "PATCH",
    "OPTIONS"
}

concommand.Add("run_http_methods_test", function(ply)
    if not isAllowedToTest(ply) then
        ply:PrintMessage(HUD_PRINTCONSOLE, "[WARNING] You're not allowed to run this command")
    end 

    print("The HTTP client should send the right HTTP method")
    for _, expectedMethod in ipairs(methods) do
        HTTP {
            url = "https://api.dotshark.ovh/testMethod",
            method = expectedMethod,
            type = "application/json",
            success = function(code, json)
                local data = util.JSONToTable(json)
                if (not data) and expectedMethod == "HEAD" then
                    data = {method = "HEAD"}
                end
                if data.method == expectedMethod then
                    print(expectedMethod .. " HTTP method works as expected")
                else
                    print("[ERROR] The HTTP client replaced " .. expectedMethod .. " by " .. data.method)
                end
            end,
            failed = function() end
        }
    end
end)
```

Here is the output I had using both server-side and client-side running the game on Windows 10:
```
run_http_methods_test
The HTTP client should send the right HTTP method
GET HTTP method works as expected
[ERROR] The HTTP client replaced HEAD by GET
[ERROR] The HTTP client replaced PUT by POST
[ERROR] The HTTP client replaced DELETE by GET
POST HTTP method works as expected
[ERROR] The HTTP client replaced PATCH by POST
[ERROR] The HTTP client replaced OPTIONS by GET
```

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta. Other betas will follow soon.

**Comment by yogwoggf** [comment]
> Should be fixed on `dev` beta. Other betas will follow soon.

How does this even happen?? What was the thought process behind the change??

**Comment by robotboy655** [comment]
It was obviously an unintentional side effect of recent changes to the security of that function.
