### ISSUE TITLE
Player:Alive returns false in (Do)PlayerDeath

### ISSUE THREAD

**Issue by NickCloudAT** [Facepunch/garrysmod-issues#5556]
I noticed that in the "(Do)PlayerDeath" hook, the "player:Alive()" return false, instead of true. In the wiki it is clearly stated that it should return true.

Somebody on the discord also testet it and had the same issue and gave me permission to use his screenshots:

![image](https://github.com/Facepunch/garrysmod-issues/assets/20370962/567c513e-17e9-45c4-853d-0752601616b0)

![image](https://github.com/Facepunch/garrysmod-issues/assets/20370962/67a8564c-1f19-49c7-bf20-937575f8caf4)

**Comment by FlorianLeChat** [comment]
> In the wiki it is clearly stated that it should return true.

[Wiki has no mention of what you say](https://wiki.facepunch.com/gmod/GM:DoPlayerDeath) but the behavior you describe *seems* to have been changed with #4785 to fix an issue.

**Comment by NickCloudAT** [comment]
> > In the wiki it is clearly stated that it should return true.
> 
> [Wiki has no mention of what you say](https://wiki.facepunch.com/gmod/GM:DoPlayerDeath) but the behavior you describe _seems_ to have been changed with #4785 to fix an issue.

Ok sorry I may have not mentioned it clear enough. It only states it on the "PlayerDeath" hook:
![image](https://github.com/Facepunch/garrysmod-issues/assets/20370962/2f36f182-ff0a-41cf-8067-f83565ee8074)

**Comment by FlorianLeChat** [comment]
I've just removed the outdated notes on [PlayerDeath](https://wiki.facepunch.com/gmod/GM:PlayerDeath)/[PostPlayerDeath](https://wiki.facepunch.com/gmod/GM:PostPlayerDeath) pages, they hadn't been updated like DoPlayerDeath.

**Comment by NickCloudAT** [comment]
> I've just removed the outdated notes on [PlayerDeath](https://wiki.facepunch.com/gmod/GM:PlayerDeath)/[PostPlayerDeath](https://wiki.facepunch.com/gmod/GM:PostPlayerDeath) pages, they hadn't been updated like DoPlayerDeath after the [January 2021 update](https://gmod.facepunch.com/news/january-2021-update) release.

Thanks. Ok I guess I can close this than.
