### ISSUE TITLE
Folders don't exist in the Lua VFS in the client. 

### ISSUE THREAD

**Issue by PrikolMen** [Facepunch/garrysmod-issues#5561]
### Details
Folders sent by the server do not exist on the client of the connected player, while the file on the specified path exists.
Basically, he can't check an obviously existing dirrictory for existence.

### Steps to reproduce
Player who connected to server
```lua
print( file.Exists("packages/drawing-kit/init.lua", "LUA" ) )
-- true

print( file.IsDir( "packages/drawing-kit", "LUA" ) )
-- false
```

Player who hosted server
```lua
print( file.Exists( "packages/drawing-kit/init.lua", "LUA" ) )
-- true

print( file.IsDir( "packages/drawing-kit", "LUA" ) )
-- true
```

**Comment by robotboy655** [comment]
Should be fixed on `dev`.
