### ISSUE TITLE
Permanently stuck on black screen if unexpectedly disconnected from the server 

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-issues#5562]
### Details
there's a random chance of gmod getting stuck on a black screen permanently if disconnected from the server by the server itself (like getting kicked, the server closing down, or the server changing maps without changelevel)
most of the time i can click ESC to exit the black screen and it shows the disconnect message box, but sometimes it gets stuck that way permanently

https://github.com/Facepunch/garrysmod-issues/assets/42521608/f7da2776-13a8-4f0b-b9ad-d731faab6d7a

i'm on x86-64

**Comment by Yarukon** [comment]
might caused by console window

**Comment by robotboy655** [comment]
I think this was fixed recently on `x86-64` and `dev` betas.
