### ISSUE TITLE
Using color tool on entities makes them not cast shadows/interact with projected textures

### ISSUE THREAD

**Issue by penolakushari** [Facepunch/garrysmod-issues#5563]
Using current live version of gmod, checked with all of the addons turned off as well.

It appears like using Color tool on physics props, ragdolls and prop_effects/dynamic props makes them not cast shadows from projected textures/lamps if their alpha is not set to 0, although before it would  also keep shadows if alpha was set to 255 (or 0). I'm not sure after which update it might have started happening, although I assume it must be related to summer ones. I have not tried factory resetting my gmod so far. Could it be related to the way source handles rendering transparent and opaque models, in separate passes?

I've happened to get another player to try to reproduce that error, and they got same results.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/1b65c082-b17d-4000-a81f-8f46f91a528e)
Make sure your color tool options are set up correctly.
