### ISSUE TITLE
Incorrect buckshot limit for 0 ammo limit (aka HL2 values)

### ISSUE THREAD

**Issue by UMP45GFL** [Facepunch/garrysmod-issues#5564]
### Details
The HL1 Source Buckshot limit overrides the HL2 buckshot limit.
So instead of having a max of 30, you get a max of 125.

### Steps to reproduce
Check the skill and skill1/2/3.cfg, and then check sk_max_buckshot ingame.
![20230825193319_1](https://github.com/Facepunch/garrysmod-issues/assets/138188821/307d63cc-fd0c-43b8-9675-c31a2698d9ea)

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta. HL1 stuff now has `hl1` prefix, i.e. `sk_max_hl1buckshot`
