### ISSUE TITLE
DTextEntry:OnLoseFocus() + DTextEntry:KillFocus()

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-issues#5565]
### Details
Calling DTextEntry:KillFocus() inside DTextEntry:OnLoseFocus() crashes GMod **immediately** (not like doing while(true)do end).

### Steps to reproduce
Just call DTextEntry:KilLFocus() inside DTextEntry:OnLoseFocus()

**Comment by robotboy655** [comment]
You are creating an infinite loop, `Panel:KillFocus` calls the `OnLoseFocus` panel hook.

**Comment by robotboy655** [comment]
I have made `DTextEntry:OnLoseFocus` not run when called from itself.
