### ISSUE TITLE
Alyx doesn't have all of her episodic capabilities

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#5566]
### Details:
When the cvar "hl2_episodic" is set either 1 or 0 Alyx doesn't have all of her episodic capabilities, for example when your in the chapter Lowlife in ep1 she doesn't cover her face when you look at her with your flashlight on. Another example is she won't melee fight zombies in the Lowlife chapter.

### Steps to reproduce:
1. Open the map ep1_c17_00
2. Shine your flashlight in her face
3. Observe Alyx not covering her face

(You can also go into any of the tunnels and observe Alyx not do any of her melee behaviors)
(This is also a problem in the main branch too)
### Version:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:22:22 Aug  8 2023 (9033) (4000)
GMod version 2023.08.09, branch: x86-64, multicore: 1
Windows 64bit

**Comment by robotboy655** [comment]
Likely related to missing animations on the base Alyx model. Related issues - https://github.com/Facepunch/garrysmod-issues/issues/793 https://github.com/Facepunch/garrysmod-issues/issues/1518

**Comment by wolfestridershooter** [comment]
This was tested with all of her animations from hl2, ep1, and ep2

**Comment by J4ckTh3R1pper** [comment]
also in ep2 she won't be able to use gravity gun when gordon's trapped inside the train

**Comment by wolfestridershooter** [comment]
Now that's because of missing animations, I'm talking about capabilities that she doesn't perform with all her required animations.

**Comment by robotboy655** [comment]
Alyx now covers her face. The melee attacks work just fine.

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/299ff0e8-ab04-4524-89e8-5568a5455c71)
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/b458d7c1-60cf-48a0-9e3a-b8e9ceab3b82)
