### ISSUE TITLE
SWEP.ViewModel and SWEP.WorldModel break for paths longer than 79 characters

### ISSUE THREAD

**Issue by mrbooboostank** [Facepunch/garrysmod-issues#5568]
### Details
**Version command output**
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:22:22 Aug  8 2023 (9033) (4000)
GMod version 2023.08.09, branch: x86-64, multicore: 1
Windows 64bit

SWEP.ViewModel and SWEP.WorldModel break for paths longer than 79 characters. While this is simple to work around for custom models by shortening file and folder names, these variables' truncation block multiple mounted models from use

I'll use TF2 for this example, but this problem is unavoidable for any mounted model with a path longer than 79 characters

### Steps to reproduce
**Create an SWEP with this code**
```
SWEP.Spawnable = true
SWEP.ViewModel = "Put model path of your choice here"
SWEP.WorldModel = "Put model path of your choice here"
```

**Replace either SWEP.ViewModel or SWEP.WorldModel with any of these examples, I've included their errors as well**

`"models/workshop/weapons/c_models/c_invasion_sniperrifle/c_invasion_sniperrifle.mdl"`
Precache of models/workshop/weapons/c_models/c_invasion_sniperrifle/c_invasion_sniperrifle. ambigious (no extension specified)

`"models/workshop/weapons/c_models/c_battalion_buffbanner/c_battalion_buffbanner.mdl"`
Precache of models/workshop/weapons/c_models/c_battalion_buffbanner/c_battalion_buffbanner. ambigious (no extension specified)

`"models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas.mdl"`
Precache of models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas ambigious (no extension specified)

`"models/workshop/weapons/c_models/c_xms_cold_shoulder/c_xms_cold_shoulder_festivizer.mdl"`
Precache of models/workshop/weapons/c_models/c_xms_cold_shoulder/c_xms_cold_shoulder_festiv ambigious (no extension specified)

**Comment by mrbooboostank** [comment]
The SWEP.ViewModel and SWEP.WorldModel strings themselves don't get truncated, but functions such as Weapon:GetWeaponViewModel(), Weapon:GetWeaponWorldModel(), and Entity:GetModel() called on an SWEP return the truncated paths

**Comment by robotboy655** [comment]
Will be fixed in the next update.
