### ISSUE TITLE
Random print added to player_extension.lua causing console spam

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-issues#5570]
So I started the game today and was trying to debug something only to notice my console was being spammed with garbage prints printing the toolgun on client.

I did a quick debug trace and it traced them to TileBuild and Random Array Tool, neither of which have been updated recently enough to be in time with this issue.

Further up the trace it said it was coming from the player_extension script in the sandbox gamemode files, so I opened that up and noticed there was a random print(wep) on line 108 in it, which is causing the spam.

Was this unnoticed in a recent update that you pushed out or?

**Comment by robotboy655** [comment]
Sorry my bad.

**Comment by ZH-Hristov** [comment]
Glad to know it wasn't a malicious addon at least
