### ISSUE TITLE
Player:IsBot returns false for SourceTV

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5571]
### Details
[IsBot](https://wiki.facepunch.com/gmod/Player:IsBot) returns false for SourceTV while SteamID returns `BOT`

### Steps to reproduce
1. Run `tv_enable 1`
2. Host a game
3. Run this `lua_run print(Entity(1), Entity(1):IsBot())`
4. See this `Player [1][SourceTV]	false`

**Comment by robotboy655** [comment]
Should be fixed.
