### ISSUE TITLE
`tv_enable` allows one to go up to `129` slots

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5572]
### Details
`tv_enable` allows one to go up to `129` slots Currently, if you have maxplayers set to 128 and use `tv_enable` it will add an additional slot. Because of this, it will go above 128 and cause all clients connecting to crash.

Fix: 
```cpp
// engine/sv_main.cpp (SetupMaxPlayers)
void SetupMaxPlayers(int iDesiredMaxPlayers)
{
	sv.m_nMaxClientsLimit = clamp( sv.m_nMaxClientsLimit, minmaxplayers, MAX_PLAYER ); // This line got added
	newmaxplayers = clamp( newmaxplayers, minmaxplayers, sv.m_nMaxClientsLimit );
}
```

### Steps to reproduce
1. Set `tv_enable` to `1`
2. Host a game with 128 slots
3. Crash
![image](https://github.com/Facepunch/garrysmod-issues/assets/64648134/35cc3117-0fbf-41ef-8f8a-926b77caa793)

**Comment by robotboy655** [comment]
Should be fixed.
