### ISSUE TITLE
NPC:TaskFail has wrong argument type

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#5576]
### Details
The function in the NPC class, `TaskFail`, found [Here](https://wiki.facepunch.com/gmod/NPC:TaskFail) takes a string as an argument, which eventually results in a useless converted integer, below I explain why this is happening.

### Steps to reproduce
1. From Lua we call the function found [Here](https://wiki.facepunch.com/gmod/NPC:TaskFail) in the NPC, `self:TaskFail("hello")`.
2. It goes to C++, calling the `TaskFail( const char *pszGeneralFailText )` found [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L685).
3. This function then calls `MakeFailCode( const char *pszGeneralError )` found [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_task.h#L66), which converts the string into an integer with **lost precision** by casting `(int)pszGeneralError` and returning it.
4. It then calls `TaskFail( AI_TaskFailureCode_t )` found [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L684).
5. Which then calls back to Lua the newly added function `NPC:OnTaskFailed(fail_code)`.
6. Retrieving the value for `fail_code` will give you an integer with lost precision, making it useless and impossible to know what the original failure code was.

Best way to fix this is to make the argument type integer, this will allow `NPC:TaskFail` to be called from Lua with whatever number and have the ability to retrieve it when `NPC:OnTaskFailed(fail_code)` is called. This will also allow us to call one of the 29 predefined task codes [Found here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_task.h#L26). Until this is fixed, this function cannot call a custom fail code OR one of the predefined fail codes, making it completely useless.

**Comment by robotboy655** [comment]
`NPC:OnTaskFailed(fail_code, string)`

**Comment by DrVrej** [comment]
It's still failing on my side (dev branch), the second parameter is always nil. To test it, make a simple NPC run the following code:
```lua
function ENT:Initialize()
	self:SetModel("models/humans/group01/male_01.mdl")
	self:SetHullType(HULL_HUMAN)
	self:SetSolid(SOLID_BBOX)
	self:CapabilitiesAdd(bit.bor(CAP_ANIMATEDFACE, CAP_TURN_HEAD, CAP_MOVE_GROUND))
	self:SetSaveValue("m_debugOverlays", 1) -- To allow NPC debug prints
end

function ENT:OnTaskFailed(fail_code, string)
	print("task failed:", fail_code, string)
end

function ENT:SelectSchedule()
	for _, v in ipairs(ents.FindInSphere(self:GetPos(), 120)) do
		if v:IsPlayer() && v:Alive() then
			self:SetTarget(v)
			self:SetSchedule(SCHED_IDLE_STAND)
			self:SetSchedule(SCHED_TARGET_FACE)
			return
		end
	end
	self:TaskFail("fail_no_target")
end
```
Once the NPC is spawned, look at it and execute `npc_task_text` in the console (with cheats enabled)
Example print:
```
task failed:	1933240000	nil
      TaskFail -> fail_no_target (npc_github_test: 49/<unnamed>) [81732]
```

If anymore information is needed let me know, thank you!

**Comment by robotboy655** [comment]
I see the problem, it should be fixed on `dev` within a few hours.

**Comment by DrVrej** [comment]
> I see the problem, it should be fixed on `dev` within a few hours.

Just tested, it's now working as intended, thank you!
