### ISSUE TITLE
`render.PopRenderTarget()` Crash when used by itself.

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5577]
### Details
Running `render.PopRenderTarget()` by itself instantly crashes to desktop, might be neat if it triggered an error instead of full out crashing the game.

### Steps to reproduce
1. Run `render.PopRenderTarget()` on clientside, doesn't need to be in or outside of a render hook as both work.
2. Crash

**Comment by robotboy655** [comment]
Fixed, applied same rules as other Push/Pop functions
