### ISSUE TITLE
+lookup/+lookdown don't work

### ISSUE THREAD

**Issue by marchc1** [Facepunch/garrysmod-issues#5578]
### Details
Given that +left and +right are concommands, and that there's a convar for cl_pitchspeed, I was expecting the ability to move my mouse up/down with console commands using +lookup/+lookdown. But they seem to do nothing. Also had two friends test it just in case it was a misconfiguration with my game, and it didn't work for them either.

### Steps to reproduce
Type +lookup/lookdown in the console

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3071

**Comment by weaponcubemap** [comment]
+lookup/+lookdown works if you use cl_mouselook 1. By the way, the ConVar will disable your mouse, so you will have to use keybinds to move your view.

**Comment by PrikolMen** [comment]
Here's a fix: https://steamcommunity.com/sharedfiles/filedetails/?id=2806290767
