### ISSUE TITLE
Broken materials on the map

### ISSUE THREAD

**Issue by qwerty-gm** [Facepunch/garrysmod-issues#5579]
### Details
CS:GO:
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/62c092e1-a3c3-45fa-9986-ec4ed3fa3faf)

GMOD:
![image](https://github.com/Facepunch/garrysmod-issues/assets/136369264/f655802e-b3b7-4996-a1be-5b0f5220fda8)

### Steps to reproduce
1. Mount CS:GO
2. Execute "map de_mirage" in console

**Comment by robotboy655** [comment]
CS:GO is getting deleted soon, so there's no point in reporting issues with its maps in GMod.
