### ISSUE TITLE
GetTracerOrigin() ignores worldmodels

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5580]
### Details
What it says in the title, it's impossible to set up tracers for worldmodels, however they work fine in first person. The attachment IDs are the same, so it's not a problem on my end:
![image](https://github.com/Facepunch/garrysmod-issues/assets/11159125/e456233e-dad3-4f96-87d7-77d124383c08)
![image](https://github.com/Facepunch/garrysmod-issues/assets/11159125/691b94b0-73a8-4dc0-a51f-1e840cc047b5)

### Steps to reproduce
Set a different attachment in GetTracerOrigin() and observe yourself in third person
The code I used is this:
```
function SWEP:GetTracerOrigin()
	if !self.Dual then return self.Owner:GetViewModel():GetAttachment("1").Pos end
	if self.Tracer == 1 then
		self.Tracer = 2
		return self.Owner:GetViewModel():GetAttachment("1").Pos
	elseif self.Tracer == 2 then
		self.Tracer = 1
		local second_att = self.Owner:GetViewModel():GetAttachment("3") or self.Owner:GetViewModel():GetAttachment("2")
		return second_att.Pos
	end
end
```

**Comment by robotboy655** [comment]
Your code would never work outside of first person view, but you are correct in that `GetTracerOrigin` was not called for 3rd person view. It is now.
