### ISSUE TITLE
On hook EntityEmitSound return false, the subtitle of the sound still plays

### ISSUE THREAD

**Issue by Chtidino** [Facepunch/garrysmod-issues#5581]
### Details
I came across this, during a modification of an addon that I make... By making sure that the Hook "GM:EntityEmitSound" returns false, (activate subtitle), this results in that if the the sound in question has a subtitle and it is displayed, even though the sound does not play (in my case the fact that the sound does not play is desired, but the subtitle which is displayed is not).

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:57:28 Sep  4 2023 (9033) (4000)
GMod version 2023.09.04, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
I create a .lua file in the "autorun" folder...
I edit it and put this:

```
hook.Add( "EntityEmitSound", "no_sound_for_citizen", function( t )
	
	if IsValid(t.Entity) and t.Entity:GetClass() == "npc_citizen" then
	
		return false
	
	end
	
end )
```

i launch the game, activate subtitles if not already done.
Begin game in single or server
Spawn a citizen, shoot him and see subtitle appear without sound

**Comment by FlorianLeChat** [comment]
If Rubat comes around and can fix this issue, it would be nice to have better Close Captions support on Lua side like described here: https://github.com/Facepunch/garrysmod-requests/issues/1745 (this would make it possible to control how they are displayed, add new ones dynamically...) 👍

**Comment by robotboy655** [comment]
Should be fixed on `dev`.
