### ISSUE TITLE
How to properly remove client-side prop

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#5583]
Hello,

I am removing an array of client-side entities `Entity [-1][class C_PhysPropClientside]`, but they continue to stay visible, That's why I've started this ticket as I can [no longer use Discord](https://support.discord.com/hc/en-us/requests/39454352) to ask the forum:
https://github.com/dvdvideo1234/TrackAssemblyTool/issues/50

The ghosts stay visible why my TA tool is switched to another tool. Already tried with delayed removes and it did not work.

**Comment by dvdvideo1234** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/9112662/9fb62c33-9fad-47f0-b9b9-95778b491180)

**Comment by dvdvideo1234** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/9112662/7f1b6441-2e72-4a2c-9365-1e7fef80d0a0)

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

**Comment by dvdvideo1234** [comment]
> This is not a place to get help. You can try asking for modding help from the community on our official Discord server: https://discord.gg/gmod

As I mentioned above I am physically unable to use the discord server. It it worked I would be more than happy to, but it doesn't
![image](https://github.com/Facepunch/garrysmod-issues/assets/9112662/aa1e86fd-40fc-45d8-8224-b44bdd6a4fb6)

**Comment by dvdvideo1234** [comment]
Closing for now as I am currently using my dad's phone to temporary solve the issue

**Comment by Kefta** [comment]
We cannot due to recent raids, but if you give me your username I can give you a role that will let you talk.

**Comment by dvdvideo1234** [comment]
Hello,

Feel free to do so. Currently I use my dad's phone, because he is not a discord user :) which is also not OK :P

User ID: 447129399989633024
User name: dvd_video
Display name: dvd_video

**Comment by Kefta** [comment]
Role given

**Comment by dvdvideo1234** [comment]
Fixed in: https://github.com/dvdvideo1234/TrackAssemblyTool/commit/78c496accdf0f201b4fa4fe52d16c12165db2360
