### ISSUE TITLE
Sprinting doesn't change speed with "gmod_suit 1"

### ISSUE THREAD

**Issue by dounai2333** [Facepunch/garrysmod-issues#5585]
### Details
This issue only exist on dev and x86-64 branch.
Current if you set "gmod_suit" command to 1, the sprinting doesn't actually change your speed, your speed are keeping 200 (same as run speed).
ply:IsSprinting() still returning true in this case.

### Steps to reproduce
Start a sp/mp game, execute "gmod_suit 1" in console, and try to sprint, that's all ¯\_(ツ)_/¯

**Comment by robotboy655** [comment]
Will be fixed.
