### ISSUE TITLE
Setting sk_ally_regen_time to very low values freezes the game and the desktop environment.

### ISSUE THREAD

**Issue by ThGrSoRu** [Facepunch/garrysmod-issues#5587]
### Details
Arch Linux 6.5.6-arch2-1

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:23:31 Sep 25 2023 (9033) (4000)
GMod version 2023.10.02, branch: x86-64, multicore: 1
Linux 64bit

Using [GModCEFCodecFix](https://github.com/solsticegamestudios/GModCEFCodecFix).

### Steps to reproduce
Load any map.
Set `ai_disabled 0`.
Spawn Alyx or Barney or Gman or Grigori as npc.
Set `sk_ally_regen_time 0`. (Setting low, non-zero values like `0.001`, freezes the game AND desktop environment.)
Hurt any of these npcs.
The game freezes instantly.

**Comment by robotboy655** [comment]
I don't know about your desktop environment, sounds like a Linux issue to me, but I have fixed the game freeze caused by invalid values, by limiting the convar to a minimum value of `0.01`.

**Comment by Kefta** [comment]
I think FLT_EPSILON can be used as an absolute lower bound for all of these convars that need to be above 0, not that it really matters.
