### ISSUE TITLE
Fonts in Gamemode Workshop Addons do not load at all, even on Windows. (X86)

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5588]
Get https://steamcommunity.com/sharedfiles/filedetails/?id=3047746641

Load into the Gamemode

Fonts aren't loaded at all despite existing.

Using the Legacy Version of my gamemode works fine.

**Comment by robotboy655** [comment]
Will be fixed on `dev` and so on
