### ISSUE TITLE
Gmod not reconizing navmesh files.

### ISSUE THREAD

**Issue by Dragotiger** [Facepunch/garrysmod-issues#5589]
### Details
I was moving backup for gmod maps and the mesh I made quite a while back, gmod started to have problems and had to undergo reinstallation and cleaning up any junk files in the gmod directory. But when I put the map files into the map directories some maps will not reconize the .nav file and comes up as an error invalid or out of date, something like that.

Is there a way to fix by the way?

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
If it is a modding API issue, please include minimal code to reproduce the issue on demand.
1. Boot up Gmod and Load the map.
2. Type Nav_edit 1 in console, if none and says Invalid as the screenshot below
3. If you have the mesh and type nav_check_file_consistency, will come as an error or invalid. 

These are the screenshots on how many files are on.
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/bf1c9f0a-5f47-42fa-ab0e-a027a55b6bd9)
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/0ffbf70f-0ca8-4e03-9fbc-42f47b14e558)
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/311fa6d2-a3ee-4c34-916a-14130934e508)
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/395d9c36-4023-4f84-9af9-f52a430df635)
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/9e193320-efc2-436b-bc15-c015ee290596)
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/544b05f7-9f85-4391-951d-4f4217fc13f6)

**Comment by Dragotiger** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/79160983/b4d09530-30c4-4c72-8bd7-9222f30d6f83)
Navmesh seems to work on d2_coast_03. Others are non functional as I already have the mesh made for em.

**Comment by robotboy655** [comment]
Invalid file means either it failed to be read entirely (i.e. empty file I guess? OS/file permission issue?) or the first 4 bytes are not what they are supposed to. Since you have not provided any of the files to test with, not much else I can do or say.

Generating a nav mesh on one of the maps affected for you works for me, so it leads me to believe the issue is on your end/with your files.

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/26093254-5b70-49c3-9f1a-42f516c45708)

**Comment by Dragotiger** [comment]
> Invalid file means either it failed to be read entirely (i.e. empty file I guess? OS/file permission issue?) or the first 4 bytes are not what they are supposed to. Since you have not provided any of the files to test with, not much else I can do or say.
> 
> Generating a nav mesh on one of the maps affected for you works for me, so it leads me to believe the issue is on your end/with your files.
> 
> ![image](https://user-images.githubusercontent.com/3299036/276212149-26093254-5b70-49c3-9f1a-42f516c45708.png)

Well, turns out during recovery on my files seems the navmesh got corrupted. Fortunately, I had uploaded those navmesh files on steam for sharing which had restored said files. I got confused for a sec why gmod couldnt recognize these files. Feel free to close this
