### ISSUE TITLE
Passing Vector containing nan value in :ApplyForce() crashes server.

### ISSUE THREAD

**Issue by Isemenuk27** [Facepunch/garrysmod-issues#5594]
Having nan value in vector applyed on physical object causes server to crash.
`
lua_run Entity( PropID ):GetPhysicsObject():ApplyForceCenter( Vector( math.sqrt( -1 ), 0, 0 )  )
`

gmod version: x86-64 ( 2023.10.20 )
.dmp file: https://pastebin.com/F7ZBRGic

**Comment by Kefta** [comment]
All functions that take Vector arguments should probably check Vec:IsValid()
