### ISSUE TITLE
NPCs' health isn't stored for saves/dupes

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5596]
### Details
Self-explanatory. Even if max health was changed via code, it still reverts to default values. It's a big problem for course saves because it misrepresents the creator's intended difficulty. It's especially noticeable when loading a save on HL2 campaign maps (d1_canals_01a) where metrocops had less health set by Valve

### Steps to reproduce
Duplicate or save an NPC with health values different from original

Before/After
![image](https://github.com/Facepunch/garrysmod-issues/assets/11159125/c31bd25e-222a-489f-92a9-39ad3a42fd52)
![image](https://github.com/Facepunch/garrysmod-issues/assets/11159125/16d186eb-9299-4d91-bfa4-49288abcb2ac)

**Comment by robotboy655** [comment]
NPC health will now be saved.
