### ISSUE TITLE
headshot a SNPC makes too much damage. 

### ISSUE THREAD

**Issue by chenbuyi2019** [Facepunch/garrysmod-issues#5597]
I found that if I shoot on a SNPC's head (HITGROUP_HEAD).
The damage amount would be as the same as the npc's health. 
(or 2xHP since it is defined in base gamemode ScaleNPCDamage.)

test code:
```lua
hook.Add(
    "ScaleNPCDamage",
    "scalea1jaf",
    function(npc, b, dmg)
        print("ScaleNPCDamage", npc, "hitgroup:", b, "amount:", dmg:GetDamage(), "left hp: ", npc:Health())
    end
)

local all = ents.GetAll()
for _, ent in ipairs(all) do
    if IsValid(ent) and ent:IsNPC() then
        ent:SetHealth(9999)
        ent:SetMaxHealth(9999)
        print("set max health ", ent)
    end
end
```

some log i got:
```
set max health 	NPC [189][npc_sniper_rebel2]
ScaleNPCDamage	NPC [189][npc_sniper_rebel2]	hitgroup:	3	amount:	5	hp: 	9999
ScaleNPCDamage	NPC [189][npc_sniper_rebel2]	hitgroup:	3	amount:	5	hp: 	9994
ScaleNPCDamage	NPC [189][npc_sniper_rebel2]	hitgroup:	2	amount:	5	hp: 	9989
ScaleNPCDamage	NPC [189][npc_sniper_rebel2]	hitgroup:	1	amount:	9984	hp: 	9984
```
as you can see, i shoot on the npc's body, it only takes 5. but on head, it takes 9984.
I was settings the npc's hp to 9999.

This only effects SNPC on bullet damage. (including VJ Base and not any based "pure" ones)
Engine defined NPC or nextbot npc are not effected. 

NPC i tested:
[sniper (no base)](https://steamcommunity.com/sharedfiles/filedetails/?id=2510873639)
[Assassin (no base)](https://steamcommunity.com/sharedfiles/filedetails/?id=2773146725)
[VJ Zombies](https://steamcommunity.com/sharedfiles/filedetails/?id=152529683)

i hope this could be fixed. headshot damage should and could be calculate correctly in LUA.

**Comment by robotboy655** [comment]
It's 100% your addons that do this. It's not part of the base game.

https://github.com/Facepunch/garrysmod-issues/assets/3299036/17babfd4-9112-4396-b644-aed4059ac7aa

Please make sure to test without addons before you post an issue here.

**Comment by robotboy655** [comment]
I figured out what it is. Apparently HL2 has code to "sneak attack" NPCs that are unaware of you. I will disable it for non hostile NPCs like it was intended. (since you cannot attack friendly NPCs in HL2), as well as when the AI is disabled, or ignore players is enabled.

**Comment by chenbuyi2019** [comment]
sorry, i dont understand.
you mean you will disable "sneak attack" for friendly NPCs? not hostile NPCs?

**Comment by robotboy655** [comment]
Yes, as it is intended to function.
