### ISSUE TITLE
tr.HullTrace ignores all world geometry

### ISSUE THREAD

**Issue by LillyWho** [Facepunch/garrysmod-issues#5599]
I'm currently trying to write an entity that depends on hull tracing, and for some reason the hull trace seems to ignore any and all world geometry, be that prop or brush.

```
    local result = util.TraceHull({
        start = pos,
        endpos = pos + dir * 117,
        mask = -1,
        filter = { self }, --filter out the panto itself
        mins = Vector( -24,-3,0 ),--box should be 48 units wide and 120 units tall, in order to detect the full range of where catenary can be
        maxs = Vector(24,3,2),
    })
```
The trace works on props that have been spawned in manually. Even if via scripting I manually set things like the collision group of the props to (COLLISION_GROUP_PLAYER_MOVEMENT) I still have no luck

Meanwhile the mod I'm writing an Add-on for [has got it working perfectly fine.](https://github.com/metrostroi-repo/MetrostroiAddon/blob/d17cb74904a78da08acead6248aca69398aa3178/lua/entities/gmod_train_bogey/init.lua#L373). Theirs is a detection for a third rail on a train, while mine is a pantograph for overhead wire. Same concept, different tools. https://github.com/GingerTeaOrg/metrostroi-frankfurt/blob/main/lua/entities/gmod_train_uf_panto/init.lua https://www.youtube.com/watch?v=BRh4CreT-Uw

**Comment by robotboy655** [comment]
Have you tried the example on the wiki?
https://wiki.facepunch.com/gmod/util.TraceHull

**Comment by LillyWho** [comment]
I derived my code from Metrostroi and as you can see, did not change much at all. Since I'm doing the same thing they're doing, and they've got it working, I doubt it's due to my implementation.

**Comment by robotboy655** [comment]
You have pasted a non working piece of code that does not reproduce the claimed issue.

You say the issue is about world geometry collisions, but then say "Even if via scripting I manually set things like the collision group of the props to (COLLISION_GROUP_PLAYER_MOVEMENT) I still have no luck". What do prop collisions have to do with world geometry collisions?

Throwing your values into a piece of working code shows no issues with props OR world geometry, try it yourself:
```lua
local color_blu = Color( 0, 0, 255 )

hook.Add( "PostDrawTranslucentRenderables", "trace_visualize", function()
	local eyePos = Entity( 1 ):EyePos() + Entity( 1 ):GetRight() * -5
	local eyeDir = Entity( 1 ):GetAimVector()

	eyePos = Entity( 1 ):EyePos() + Entity( 1 ):GetRight() * 5
	local tr2 = util.TraceHull( {
		start = eyePos,
		endpos = eyePos + eyeDir * 117,
		filter = Entity( 1 ),
		mask = -1,
		mins = Vector( -24,-3,0 ),--box should be 48 units wide and 120 units tall, in order to detect the full range of where catenary can be
		maxs = Vector(24,3,2)
	} )
	render.DrawLine( eyePos, tr2.HitPos, color_blu, true )
	render.DrawWireframeBox( tr2.HitPos, Angle( 0, 0, 0 ), Vector( -24,-3,0 ), Vector(24,3,2), color_blu, true )
end )
```

https://github.com/Facepunch/garrysmod-issues/assets/3299036/8f3cbc8d-c1fd-4839-9910-0467d134bb14



What else do you wish me to do here with what you have given me?

**Comment by LillyWho** [comment]
> You have pasted a non working piece of code that does not reproduce the claimed issue.

I can continuously reproduce the issue. Any prop that was either spawned by a Lua script or part of the map, or any brush is not being registered.

> You have pasted a non working piece of code
Also, I have linked to the full script and to the script I derived it from, as well as to a demo video showing how the process definitely works for props that have been spawned in by the player. At that point the pose parameter wasn't fully adjusted yet, but the box that I used as a visual aid clearly shows it working.

The messing with collision groups came about as a suggestion from someone, since props that are part of the map and props that are spawned in are supposedly different collision groups, and never yielded any results.

Does tracing behave differently on the client as opposed to on the server? Because both Metrostroi and I are running the trace [serverside](https://github.com/metrostroi-repo/MetrostroiAddon/blob/d17cb74904a78da08acead6248aca69398aa3178/lua/entities/gmod_train_bogey/init.lua#L373), whereas your hook as well as the wiki examples are clientside.

And yes, I have read the wiki entry, and it doesn't help in this case.
It's not even due to some silly oversight such as the trace direction, because I'm using ``self:GetUp()`` as the parameter as you can [see](https://github.com/GingerTeaOrg/metrostroi-frankfurt/blob/fe712849fe15f1c712b7bc0d79b85143d3216673/lua/entities/gmod_train_uf_panto/init.lua#L123), plus the trace does work on any player-created prop.

**Comment by LillyWho** [comment]
Okay, so this time it is indeed mea culpa. It turns out, the tracing box does not care about the entity's orientation. Leading to the box being potentially too narrow when facing down, say, west-east, instead of north-south. My debugging box did however automatically reorient itself, which was the source of the confusion.

**Comment by LillyWho** [comment]
It would be a good idea to mention on the Wiki that the coordinates for the box are not local to the entity in terms of angles though.

**Comment by robotboy655** [comment]
It is.

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/78e862d7-a539-4f84-be14-22259a88ac9d)

Including this GIF in the examples:
![image](https://files.facepunch.com/wiki/files/HullTrace.gif)
