### ISSUE TITLE
Model precache limit crash

### ISSUE THREAD

**Issue by tomasas** [Facepunch/garrysmod-issues#56]
So, if you spawn more than 1024 different models in one game session, the server crashes.
This makes running any server that allows players to spawn props impossible without a model whitelist. The server will crash in about a day when it hits the limit.

You asked what size should it be increased to, but you never replied. It would be a good idea to increase it to at least 4096, so servers could run without crashing from the precache limit for something close to a week.

**Comment by Noiwex** [comment]
Please implement this!

**Comment by sirsavary** [comment]
+1, having this limit removed (or raised) would be extremely helpful.

**Comment by mcNuggets1** [comment]
Is this still a thing?

**Comment by Kefta** [comment]
I believe the cache might have been raised, but I'm not 100% on that

**Comment by Noiwex** [comment]
The limit has been raised.

**Comment by Kefta** [comment]
Can the cache list please be converted to an LFU cache at least so people don't crash?

**Comment by Noiwex** [comment]
no

**Comment by Kefta** [comment]
Thanks Noi

**Comment by Noiwex** [comment]
no problem, you're welcome

**Comment by NathanX-S** [comment]
@Kefta

**Comment by robotboy655** [comment]
Related: https://github.com/Facepunch/garrysmod-requests/issues/2119

**Comment by ddos-pro** [comment]
It's time to add the ability to manually change the value

**Comment by Grocel** [comment]
> Related: [Facepunch/garrysmod-requests#2119](https://github.com/Facepunch/garrysmod-requests/issues/2119)

Nice you raised it 8192 as you told in #2119. I guess you can close this issue as duplicate?
