### ISSUE TITLE
lua_error_url Still persisting on clients that start a singleplayer server after joining multiplayer server

### ISSUE THREAD

**Issue by callumok2004** [Facepunch/garrysmod-issues#5600]
We have some clients joining our server, then leaving and starting their local/single-player server straight after - lua_error_url is not being cleared and our own error logs are being filled with invalid errors.

Related:
https://github.com/Facepunch/garrysmod-issues/issues/5348

Rubat states in the above thread that it does get cleared for single-player/local servers, but that does not seem to be the case, at least not anymore.

**Comment by SteChron** [comment]
I can confirm this is a valid case as we also came across this very issue just recently.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/assets/3299036/7123850a-c934-4aa2-a552-d3cdeabd7f1d

**Comment by callumok2004** [comment]
> hl2_fYRckxxXPm.

https://github.com/Facepunch/garrysmod-issues/assets/35779365/a12e2d5a-6be8-4add-b070-e0c0e14f6345

**Comment by robotboy655** [comment]
I will reapply the old fix for this for x86-64 for now.

**Comment by callumok2004** [comment]
This still occurs from time to time (though more rare), so there seems to be some cases where the cvar is not getting cleared still?

Maybe a better solution is to completely remove `lua_error_url` from being shared with clients, and let the server send client error events too, given servers already receive client errors anyways?
