### ISSUE TITLE
NPC names are not saved for dupes

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5601]
### Details
Duplicating an NPC resets their name in the kill feed.

### Demonstration
https://puu.sh/JTtd3/dd05c77a1f.mp4

### Steps to reproduce
Duplicate any NPC that has a custom name set

**Comment by robotboy655** [comment]
They were, but the duplicator code was spawning incorrect NPCs, now it should work good.
