### ISSUE TITLE
Non-working GetName() function

### ISSUE THREAD

**Issue by ideall2** [Facepunch/garrysmod-issues#5607]
### Details
This function should output the name of the entity. But nothing happens.
It always returns empty.
I tried to use "Initialize()", "OnEntityCreated()", "InitPostEntity" in hooks.
I also paid attention to the GetKeyValues() function. I think GetName() should output the name of the entity from "targetname", which should be in GetKeyValues(), but I didn't see it.
Also tried to get the name of the entity, sweps and NPCs.
### Version GMOD (X32)
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:21:29 Oct 31 2023 (9033) (4000)
GMod version 2023.10.31, branch: x86-64, multicore: 1
Windows 32bit
### Version GMOD (X64)
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:22:35 Oct 31 2023 (9033) (4000)
GMod version 2023.10.31, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
```
-- This code should be executed in the autorun/"name_file".lua folder
-- On the result, it should show for each npc the attributes found and **write** the name. Not in the format "npc_combine_s" but --exactly as from Spawnmenu similar to "CombineElite".
hook.Add("InitPostEntity", "NPCInfoPrinter", function()
    if SERVER then
        for _, npc in pairs(ents.FindByClass("npc_*")) do
            if IsValid(npc) and npc:IsNPC() then
                local keyValues = npc:GetKeyValues()
                
                if keyValues and keyValues["targetname"] then
                    local targetname = keyValues["targetname"]
                    print("NPC targetname: " .. targetname)
                    print(npc:GetName())
                else
                    print("NPC does not have a targetname attribute.")
                end
            end
        end
    end
end)
```
### Another example
```
-- It's trivial to try to output all the entities to the console.
--Just a lot of blank lines.
--Don't forget to place in the folder autorun/server/"name_file".lua
hook.Add("OnEntityCreated", "Replacingents", function(ent)
    print(ent:GetName())
end)
```
## The results
I've tried many times to work with this function in some way. But nothing works. 
If there is another function that can get the name from the npc not as "npc_combine_s" but as "CombineElite" in Spawnmenu, I would be very happy.

**Comment by robotboy655** [comment]
Most entities do not have a `targetname` set, so it's very much expected to print nothing for such cases.

[Initialize](https://wiki.facepunch.com/gmod/GM:Initialize) and [OnEntityCreated](https://wiki.facepunch.com/gmod/GM:OnEntityCreated) hooks are ran too early to have all entity data initialized. (This is mentioned on the wiki page for `OnEntityCreated` at least, there'd be pretty much no entities at the time `Initialize` is called.)

`InitPostEntity` would be a good place to test this, but the map must have NPCs with `targetname` set.

Now `targetname` is not a real keyvalue as far as the engine is concerned. ([This is also documented on the wiki](https://wiki.facepunch.com/gmod/Entity:GetKeyValues))

If we change your `InitPostEntity` hook to print out `GetName()` at all times, you will see that it does, in fact, function properly on maps such as Half-Life 2's `d2_coast_11`
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/f50acf5f-eaa2-4c17-bcfc-90fc6d1b293a)

**Comment by ideall2** [comment]
Thank you for the detailed explanation. I'll be aware of that.
