### ISSUE TITLE
Hardware filtering for projected textures is not applying/functioning.

### ISSUE THREAD

**Issue by goodusername123** [Facepunch/garrysmod-issues#5609]
### Details
The Source engine has two different types of filtering that it applies to projected textures at the same time, One of which being the bilinear filtering that is applied hardware side in the GPU's texture mapping unit (same filtering that is used on lightmaps and standard textures to make them not pixelated), The other filtering being a grainy looking filter that is applied shader side (usually a 16 tap poisson filter) and can be toggled via `r_projectedtexture_filter`

The issue is the first type of filtering is not being applied at all leading to projected texture shadows looking lower quality then they should.

### Steps to reproduce

1. Load up a map and either find or create a projected texture (using the light tool should be enough).
2. Change `r_projectedtexture_filter` to 0 (the problem still occurs no matter what this cvar is but it's more noticeable with it off).
3. Look at the edges of the projected texture shadows/outlines and notice they are pixelated and don't have bilinear filtering applied to them.

### Possible cause and solution

A likely cause is inside of `clientshadowmgr.cpp` there may be somewhere that is using `MATERIAL_RT_DEPTH_ONLY` which should instead be `MATERIAL_RT_DEPTH_NONE`.

There are no Source engine games that use `MATERIAL_RT_DEPTH_ONLY` inside of `clientshadowmgr.cpp` and [`MATERIAL_RT_DEPTH_ONLY` forces nearest neighbor filtering](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/materialsystem/MaterialSystemUtil.cpp#L189), The only reason I could see `MATERIAL_RT_DEPTH_ONLY` being inside of `clientshadowmgr.cpp` is that it was likely picked up by accident from a older incorrect version of a fix present on the [VDC](https://developer.valvesoftware.com/wiki).

**Comment by robotboy655** [comment]
Ok, fair enough, I have changed it to `MATERIAL_RT_DEPTH_NONE`.

**Comment by goodusername123** [comment]
@robotboy655
After testing on the `dev` branch I can confirm this change does fix the issue and makes edges of projected textures look noticeably better, **However** a new issue has came up as a result due to GMod's default values for the cvars `mat_depthbias_shadowmap` and `mat_slopescaledepthbias_shadowmap` being too low compared to most other Source engine games leading to visual issues at higher resolution projected textures defined with `r_flashlightdepthres` when `r_projectedtexture_filter` is set to 1 (seems to be extremely noticeable on AMD GPUs but hard to notice on NVIDIA GPUs).

### Garry's Mod:
- `mat_depthbias_shadowmap` = `0.0001`
- `mat_slopescaledepthbias_shadowmap` = `2`
### "Older" branches of Source such as current day HL2, TF2, and 2013:
- `mat_depthbias_shadowmap` = `0.0005`
- `mat_slopescaledepthbias_shadowmap` = `16`
### Newer branches of Source such as ASW, L4D, L4D2, and CS:GO:
Newer branches seem to all define `mat_depthbias_shadowmap` and `mat_slopescaledepthbias_shadowmap` differently so they end up pretty inconsistent however *almost* none of them define the cvars as low as GMod does with some (not all) values seen in the list below:
- `mat_depthbias_shadowmap` = `0.002` OR `.000025`
- `mat_slopescaledepthbias_shadowmap` = `3` OR `4` OR `8`



### (Below is an image with `r_flashlightdepthres` set to `8192` on a AMD GPU with GMod's current default values of `mat_depthbias_shadowmap` and `mat_slopescaledepthbias_shadowmap`, Not shown in the image is also the issue of projected textures making the area they project onto darker which is also due to the mentioned depth bias cvars being too low.)
![169951637114954774 webp](https://github.com/Facepunch/garrysmod-issues/assets/61405538/abda70c8-e571-49c5-ab88-295b66b0dd6d)

A probable safe bet would be to just set the values to the ones used in TF2/2013 or something close to prevent issues on AMD GPUs (might also help Intel GPUs? no clue since I don't have a way to test any at the moment.)
