### ISSUE TITLE
gui.HideGameUI hides UI after next frame

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5614]
When i call gui.HideGameUI in PreRender, DrawOverlay hooks, and if user clicked an esc button and ui should be rendered (but supposed to be cancelled with HideGameUI), ui shown for one frame then gets closed. 
This bug make custom chat/esc menu experience worse.

To reproduce this bug, use this code and try to open esc menu
`hook.Add("PreRender", "disableESC", function()
if input.IsKeyDown(KEY_ESCAPE) and gui.IsGameUIVisible() then
        gui.HideGameUI()
end
end)`

<s>If this information will be helpful: i use Linux x86_64 build.</s> Windows build has this problem too

**Comment by StarLight-Oliver** [comment]
You can bypass this issue now with this [hook](https://wiki.facepunch.com/gmod/GM:OnPauseMenuShow)

**Comment by robotboy655** [comment]
I am closing this, as gui.HideGameUI  will be disabled in the future.
