### ISSUE TITLE
NPC:SetSquad(string) does not work

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#5615]
### Details
The function `NPC:SetSquad(string)` doesn't work (at least on scripted NPCs).
_WIki link: https://wiki.facepunch.com/gmod/NPC:SetSquad_

One way to fix it is by calling `self:Fire("setsquad", "test_squad")`, in fact you can tell this is running the code because if you don't apply `CAP_SQUAD` it will print `SetSquad Input received for NPC npc_test, but that NPC can't use squads.` where calling `self:SetSquad("test_squad")` will not cause that error to appear.

### Steps to reproduce
1. Make a simple NPC
2. Apply the following code:
```lua
ENT.Base = "base_ai"
ENT.Type = "ai"
ENT.PrintName = "Test NPC"
ENT.AutomaticFrameAdvance = true

function ENT:Initialize()
	self:SetModel("models/humans/group01/male_01.mdl")
	self:SetHullType(HULL_HUMAN)
	self:SetHullSizeNormal()
	self:SetSolid(SOLID_BBOX)
	self:SetMaxYawSpeed(20)
	self:CapabilitiesAdd(bit.bor(CAP_SQUAD, CAP_MOVE_GROUND))
	self:SetSquad("test_squad")
end

function ENT:Think()
	print(self:GetSquad())
end
```
Console result: `nil`

**Comment by robotboy655** [comment]
Fixed. It was only working when NPC already had a squad.
