### ISSUE TITLE
PlayerBindPress doesn't fires on -command

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5618]
PlayerBindPress doesn't fires on -command but fires on +command.

To reproduce it, create hook PlayerBindPress (with print, for debug) then press c key (+menu_context, for example) , then when u release key, hook will not fired

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1176
