### ISSUE TITLE
m_eDoorState is not present at prop_door_rotate

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5619]
door:GetInternalVariable("m_eDoorState") returns nothing (GetSaveTable too).

this is worked sometimes ago, because i saw this variable in wiki

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/01c33ee7-0276-46ce-9962-e0d0f3296bfc)

It still works as expected in my tests.
