### ISSUE TITLE
input.LookupBinding("menucontext") not working

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5622]
input.LookupBinding("menucontext") not working

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/2b2c652a-476c-4d33-a80e-5fa8a507f215)

Please, pay more attention to what you are doing. Perhaps ask for help on the official Discord before making a new issue.
