### ISSUE TITLE
File:Skip() fails on certain game files

### ISSUE THREAD

**Issue by Bonyoze** [Facepunch/garrysmod-issues#5628]
### Details
`File:Skip()` will set the file pointer to `file length - 1` on certain game files. This bug exists on both server and client.

Server:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:16:30 Oct 31 2023 (9034) (4000)
GMod version 2023.10.31, branch: unknown
Windows 32bit Dedicated Server

Client:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:22:35 Oct 31 2023 (9033) (4000)
GMod version 2023.11.22, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
Code used:
```lua
local f = file.Open("models/props_c17/oildrum001.mdl", "rb", "GAME")
print(f:Tell(), f:Size())
f:Skip(1)
print(f:Tell(), f:Size())
f:Close()
```
Console output:
```
0       1976
1975    1976
```
`f:Tell()` should've returned 1 but it returned 1975

Files tested:
`models/props_c17/oildrum001.mdl` - broken
`models/props_interiors/BathTub01a.mdl` - broken
`materials/brick/brickwall003a.vtf` - broken
`sound/garrysmod/balloon_pop_cute.wav` - broken
`models/player.mdl` - works (what?)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
