### ISSUE TITLE
IGModAudioChannel:SetPan() only works with integer values when it should work with floats.

### ISSUE THREAD

**Issue by bluemetaknight** [Facepunch/garrysmod-issues#5630]
A bug with AudioChannel:SetPan() causes it to only accept integer values. BASS documentation seems to suggest that you should be able to use float values.

https://documentation.help/BASS/BASS_ATTRIB_PAN.html

GMod Ver: x86-64 2023.11.22

**Comment by robotboy655** [comment]
Fixed on `dev` beta.
