### ISSUE TITLE
os.time() causes crash on Windows

### ISSUE THREAD

**Issue by LillyWho** [Facepunch/garrysmod-issues#5631]
### Details
Running os.time() with either the flags %H%M or I%M% crashes both the server and the client. This seems to especially occur when the function is run early on in the engine's runtime as occasionally I was able to pass the function via lua_run from the console without a crash when the server had been running for a while. I am aware of the bug notice on the wiki page, however the flags are on the list of implemented flags on Microsoft's KB page.

branch: x86_64-chromium
revision: latest available on this branch
OS: Windows 11 25314.1010
occurs on both server and client

### Steps to reproduce
Run a script or manually run the function via ``lua_run``: ``os.date("H%M%",os.time())``

**Comment by robotboy655** [comment]
You are misusing the function. The formatting starts with a `%` sign, it does not end with it.

Correct usage would be `os.date("%H%M",os.time())`

**Comment by LillyWho** [comment]
Ah shite. I checked my code and you're right. Simple typo.
It would be a good idea however, to implement a sanity check on the function that errors out when the flags are mistyped. A whole crash I would consider severe enough of a reaction to merit this. This could also be expanded with a platform check, in order to avoid the crash when someone uses the wrong flags on Windows. Or perhaps you've already thought of this and I'm stating the obvious.
