### ISSUE TITLE
Fixed navmesh.Load crashing the Server

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5632]
### Details
Currently, running navmesh.Load before the Map->GameRules have been created, it crashes the Server. 
This is documented in the Wiki, but it still should be fixed.

There are 2 possible crashes. Currently, it crashes because of this line:
```
// file: game/server/nav_file.cpp CNavMesh::Load
GameRules()->OnNavMeshLoad();
```
This is because `GameRules()` will return a nullptr when it's called before the GameRules have been created.

The second crash would occur if we would ignore the first one.
```
// file: game/server/nav_file.cpp CNavArea::Load
CheckWaterLevel();
```
`CNavArea::CheckWaterLevel` will call `CNavArea::GetGroundHeight` internally which tries to do some traces but because nothing exists yet it will cause a crash.

The easiest way to fix it would be to just return if the GameRules don't exist because we can't really fix the second crash that would occur otherwise.
How my approach would look like:
```
// file: game/server/nav.h enum NavErrorType
    [...]
    NAV_CORRUPT_DATA,
    NAV_OUT_OF_MEMORY,
    NAV_MISSING_GAMERULES, // Added a new Error Type.
```
```
// file: game/server/nav_file.cpp CNavMesh::Load
if (GameRules())
{
    GameRules()->OnNavMeshLoad();
}
else
{
    return NAV_MISSING_GAMERULES;
}
```

**Comment by robotboy655** [comment]
Will be fixed on `dev`.
