### ISSUE TITLE
Inconsistent behavior of projected texture shadows on props and toolgun-spawned entities

### ISSUE THREAD

**Issue by penolakushari** [Facepunch/garrysmod-issues#5634]
Happened to notice that using color tool with alpha set between 254-1 doesn't remove projected texture (aka light from lamps) shadows from entities that were spawned with a toolgun, like lamps, lights, thrusters and such, and ragdolls, although I recall before it used to do that. If using those tricks on usual physics props, shadows from projected textures will go away as they did before. I did happen to test this without any of my addons enabled, and I did happen to check all modes of color tool, and all of them had same result of shadows still being present. Was it changed intentionally, or perhaps it could be made as it was before? I mostly used this for some soft lamp setups, but I could also live without it.

Running on current live version of gmod, no betas.

Exe version 2023.06.28 (garrysmod)
Exe build: 16:34:46 Sep  4 2023 (9040) (4000)
GMod version 2023.09.06, branch: unknown, multicore: 0
Windows 32bit

**Comment by robotboy655** [comment]
Should work more consistently now (on `dev` beta and in future update) between some of those tool spawned entities and normal props.
