### ISSUE TITLE
Entity trigger_changelevel return no name map

### ISSUE THREAD

**Issue by Chtidino** [Facepunch/garrysmod-issues#5636]
### Details
In Hammer, we must enter the name of the map to which we want the trigger_changelevel to send us. But if I try to list the keyValues with the function "entity:GetKeyValues()", (I also tried with the function "entity:GetSaveTable(true)"), there is no keyvalue which gives the name of the map.

(I'm trying to simulate a map change, with a new entity, since in multiplayer the trigger_changelevel doesn't work. But you would need to be able to get the name of the map that the trigger_changelevel is supposed to have.)

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:22:35 Oct 31 2023 (9033) (4000)
GMod version 2023.11.22, branch: x86-64, multicore: 1
Windows 64bit

Same result with no beta active

### Steps to reproduce
Create lua file in autorun with this inside:
```
hook.Add( "InitPostEntity", "check_keyvalues", function()
	for k, v in pairs( ents.FindByClass( "trigger_changelevel" ) ) do
		PrintTable(v:GetKeyValues()) -- or v:GetSaveTable(true)
	end
end )
```
launch a map with trigger_changelevel available on it, (in sandbox)  
i try with half-life 2 map, "d1_canals_01" for exemple
And check console command, you will see no map name

**Comment by robotboy655** [comment]
You can use https://wiki.facepunch.com/gmod/GM:EntityKeyValue to catch the keyvalues for that entity and store it whereever you'd like.
