### ISSUE TITLE
Game crashes on specific map

### ISSUE THREAD

**Issue by danx91** [Facepunch/garrysmod-issues#5639]
### Details
Game crashes on [gm_site19](https://steamcommunity.com/sharedfiles/filedetails/?id=290599102) map on `x86-64` branch (all 3 launch options tested) both on singleplayer and multiplayer. Crash also occurs on `dev` branch, however it works fine on default branch. Crash occurs with and without `-noaddons -noworkshop` options. Game crashes straight into desktop without any error, prompt or anything. I don't know if any other maps are affected by this issue, but `gm_site19` is the only map that managed to crash my game (I tested few other maps and they work just fine) but map hasn't been updated since 2019. I believe it's caused by the recent game update because 2 days ago everything worked just fine. Friend of mine is also experiencing crash on this map on `x86-64` branch.

Memory dump file: [1219ebf0-b0d7-4692-87cf-64e6ff391491.dmp](https://github.com/Facepunch/garrysmod-issues/files/13664734/1219ebf0-b0d7-4692-87cf-64e6ff391491.dmp)

### Steps to reproduce
* Use x86-64 or dev branch
* Load map `gm_site19`
* Game crashes during final stage of loading or shortly after player spawn

### PC Specs
OS: Windows 10 64bit
CPU: AMD Ryzen 7 5700X
GPU: AMD Radeon RX 6700 XT
RAM: 32GB DDR4 3200MHz

**Comment by robotboy655** [comment]
Will be fixed when the game next updates.
