### ISSUE TITLE
spawnicon_queue has no effect

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5640]
x86_64

There's no difference between 0 and 1 value, game is still very lagging while rendering icons.

**Comment by robotboy655** [comment]
Lagging when rendering spawnicons for the first time is unavoidable. The game has to load the model from your disk, and then write a file to your disk.

`spawnicon_queue` is more for massive spawnlists of already pre-rendered spawnicons, it should avoid a complete freeze when opening a spawnlist with like a thousand icons, instead it will load them gradually, looking at the code I think it targets 10 fps at minimum. (100 ms for spawnicon loading per frame)
