### ISSUE TITLE
RichText link clicking detection no longer functional

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-issues#5645]
[`Panel.ActionSignal`](http://samuelmaddock.github.io/glua-docs/#?q=ActionSignal) is used by RichText to detect `TextClicked` events for example.

Example:

https://github.com/Metastruct/EPOE/blob/654b048f0e666bd9eb392b42aa17e98f5b7a9a14/lua/epoe/client_gui.lua#L369

**Comment by robotboy655** [comment]
I will restore `PANEL:ActionSignal` for RichText only for the time being, but I will be also adding a dedicated hook for this event with `PANEL:OnTextClicked( id )` as the intended replacement for legacy `PANEL:ActionSignal`.
