### ISSUE TITLE
GMod holds onto mounted GMA files

### ISSUE THREAD

**Issue by Bonyoze** [Facepunch/garrysmod-issues#5647]
### Details
Windows GMod dedicated server and client will hold onto a GMA's file handle after mounting. This makes it not possible to: write a GMA to the data folder, mount it, then clean it up without needing the process to be fully ended. This has not been tested on other platforms.

It is beyond my knowledge if GMod requires these files on disk for the entire duration of the process, but if this is not the case this would be a useful fix. This also affects the PAC3 addon which attempts to delete the GMA files it creates for loading models but fails to.

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:38:11 Dec  6 2023 (9034) (4000)
GMod version 2023.12.07, branch: unknown
Windows 32bit Dedicated Server

### Steps to reproduce
- Take any GMA file and place it in the data folder, can be on dedicated server or client
- Run `game.MountGMA("path/to/gma")`
- Run `file.Delete("path/to/gma")` (it will fail) or try to delete it with File Explorer (it will complain it is in use by another process)

**Comment by robotboy655** [comment]
This is necessary for when something actually needs to read the data from the file. No, we are not loading gigabytes of addons into memory.

**Comment by Bonyoze** [comment]
I see. Would this also be not doable on map change?
