### ISSUE TITLE
Can't read txt or json files in BSP file

### ISSUE THREAD

**Issue by osiris-plus** [Facepunch/garrysmod-issues#5649]
### Details
With recent public branch update clientside Lua can no longer access files inside BSP files.

### Steps to reproduce
![image](https://github.com/Facepunch/garrysmod-issues/assets/65327967/861b6a00-fbd5-41f8-82cd-96d00db4fb78)
The map these files in its archive.

Neither BSP nor GAME as a path works

```
file.Read("maps/rp_rockford_nx_build488.json", "GAME") -- nothing
file.Read("maps/rp_rockford_nx_build488.json", "BSP") -- nothing
```

**Comment by Bonyoze** [comment]
This also seems to have affected my addon which needs to read some binary data (this was before data_static).
The code for reading it can be found here: https://github.com/Bonyoze/gm_8800blr/blob/main/lua/8800blr/pano.lua#L23
The map bsp can be found in the repository.

**Comment by FlorianLeChat** [comment]
#5648

**Comment by robotboy655** [comment]
Right, I think allowing `json` or `txt` files inside `data_static/` in the BSP would be sufficient for this. Basically equivalent of `.gma`'s `data_static/` folder.

Yes, it means you will have to update your map(s).
