### ISSUE TITLE
BulletInfo is wrong in PostEntityFireBullets hook

### ISSUE THREAD

**Issue by spankyyy** [Facepunch/garrysmod-issues#5654]
It appears that the hook ( **PostEntityFireBullets** ) is returning the first bullet fired out of the hl2 shotgun when suppressing the bullet, this might be the case for every weapon that fires multiple bullets (only tested for hl2 shotgun).

Happens in 64bit branch, have not tested in others.
Pretty sure it happens in all branches.

Here's a snippet of code for testing:
```
hook.Add("PostEntityFireBullets", "Testing", function(Entity, BulletInfo)
    print(BulletInfo.Trace.Normal)
    -- Suppress the bullet
    return false
end)
```

Output from the code snippet
![image_2023-12-18_230614578](https://github.com/Facepunch/garrysmod-issues/assets/75406797/5a5c73fe-6aea-48bf-8f2f-b979e9fca163)

And here's the output when not suppressing:
![image](https://github.com/Facepunch/garrysmod-issues/assets/75406797/52ac8c56-1611-4712-97c9-2b7611c828c3)

**Comment by robotboy655** [comment]
Will be fixed.
