### ISSUE TITLE
Gmod doesnt read packed lmp files in maps.

### ISSUE THREAD

**Issue by oninoni** [Facepunch/garrysmod-issues#5655]
### Details
Source Engine usually allows packing lmp files into the pakfile / bsp.
These files are put into the maps folder named "mapname.lmp"
There are maps on the workshop that use this system.
The Update breaks all these maps.
Would be great, to allow this again.

### Steps to reproduce
Install this map:
https://steamcommunity.com/sharedfiles/filedetails/?id=1257128301
Try to open in single-player
-> No Entities load.

**Comment by oninoni** [comment]
These files are also part of the normal Gmod Workshop Whitelist:
https://github.com/Facepunch/gmad/blob/master/include/AddonWhiteList.h
So it really shouldn't be a problem to have them allowed in the bsp right?

**Comment by robotboy655** [comment]
Will be fixed soon.
