### ISSUE TITLE
Stop Emission for CreateParticleSystem() seems to no longer work unless the StopEmission call is wrapped in an IsValid() check.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5657]
Using CreateParticleSystem() and tying it to an entity like for example
`Object.My_Particle = CreateParticleSystem( Object, "Particle_Effect", PATTACH_POINT_FOLLOW, 1 )`

then following it up with

`Object.My_Particle:StopEmission( false, true, false )` calls an error that it `Tried to use a NULL CNewParticleEffect!` for some reason.

However wrapping the StopEmission in an IsValid() check makes it somehow work again.

This does not work:
```
Object.My_Particle = CreateParticleSystem( Object, "Particle_Effect", PATTACH_POINT_FOLLOW, 1 )
Object.My_Particle:StopEmission( false, true, false )
```

This DOES work:
```
Object.My_Particle = CreateParticleSystem( Object, "Particle_Effect", PATTACH_POINT_FOLLOW, 1 )
if IsValid(Object.My_Particle) then
Object.My_Particle:StopEmission( false, true, false )
end
```

I'm curious why the previous non valid sanity check version is now giving errors.

**Comment by robotboy655** [comment]
Like so many Lua bindings that were implemented to do nothing if you give invalid inputs before and were changed, `CNewParticleEffect` now also throws errors when used on null objects, just like entities, panels, etc already do.

**Comment by MagentaIris** [comment]
Okay but before the update the code worked perfectly fine, It stopped the particle emission and removed it just as it should because I know its valid during that frame that it calls to stop emission.

Why require me to ask if something IsValid() if I already know it is?

**Comment by robotboy655** [comment]
That does not sound right at all.

Testing using this code, it functions as expected: (tested on `dev` beta, but that should not make a difference for this case)
```
concommand.Add( "test_particle", function( ply, cmd, arg )

	PrecacheParticleSystem( "explosion_huge_g" )

	local part = CreateParticleSystem( ply, "explosion_huge_g", PATTACH_POINT_FOLLOW )
	timer.Simple( 0.1, function() part:StopEmission( false, true, false ) end )

end )
```

Do note that `CreateParticleSystem` (and the others) **CAN** return nil if the particle failed to be created for whatever reason. (Example: `attempt to index upvalue 'part' (a nil value)`)
The particle will also become NULL when the particle emission ends on its own. (Will throw `Tried to use a NULL CNewParticleEffect!`)

You do not need to wrap the object in `IsValid` calls to make the function work, you just need to do that to make sure you are not calling the function on a NULL `CNewParticleEffect`, which used to do nothing.

**Comment by MagentaIris** [comment]
If what you say is true then why now does it spit out errors when before it was perfectly fine and worked flawlessly for me?
```
concommand.Add( "test_particle", function( ply, cmd, arg )

	PrecacheParticleSystem( "explosion_huge_g" )

	ply.PARTICLE = CreateParticleSystem( ply, "explosion_huge_g", PATTACH_POINT_FOLLOW, 1 )

end )

concommand.Add( "stoptest_particle", function( ply, cmd, arg )

	ply.PARTICLE:StopEmission( false, true, false )

end )
```

If we wait until the particle is finished, it's a "Null" particle, however StopEmission would still clean it up without an IsValid() wrap.

I don't see why the change was necessary at all in the first place because it'll just require 2 extra lines for the same effect in the end.

**Comment by robotboy655** [comment]
No, it wouldn't "still clean it up without an IsValid() wrap", it would just do nothing. The logic here is exactly the same as with entities and panels, I don't really understand what is so difficult to understand here.

Imagine implementation of `StopEmission` like this before the change:
```
function StopEmission( particle, ... )
	if ( !particle ) then return end
	StopEmission:DeleteMe()
end
```

And this is the implementation after the change:
```
function StopEmission( particle, ... )
	if ( !particle ) then Error("Trying to use a NULL particle") return end
	StopEmission:DeleteMe()
end
```

The reasoning behind this change is consistency with how other types already function, and to let you, the coder, know what you are doing something wrong, instead of doing nothing. This may not be as help with `StopEmission` functions, as it would be with something like `SetControlPoint` and others, where it doing nothing might be confusing.

**Comment by MagentaIris** [comment]
That's a better explanation, However having it give out an error means that everyone who was using a previous method now has to go about changing their setups/code to match the change, despite the issue not existing before.

There wasn't any downsides to using StopEmission before this change which is why I'm questioning the change in the first place.

Telling someone they're coding wrong, despite it still functioning and working as intended in their setups/functions creates more confusion than anything.

But whatever I guess, What's done is done, no point in me trying anymore.

**Comment by Kefta** [comment]
It's not introducing a case of wrong practices, it's making it vocal. Now the case is known.

**Comment by MagentaIris** [comment]
> It's not introducing a case of wrong practices, it's making it vocal. Now the case is known and it will lead towards better code that is aware of what it's really doing.

Which is fine. But people may have moved on from older projects and are not going to come back and fix such a small yet breaking change to the function.

Due to it spitting out an error, any code that is called AFTER the StopEmission set will no longer run when compared to previous builds.

I just personally don't feel that it's fair and would better off be throwing you issues in the console silently instead of erroring so code after the call fails to run.
