### ISSUE TITLE
Ballsocket resets linear and angular damping to 0.2

### ISSUE THREAD

**Issue by adamnejm** [Facepunch/garrysmod-issues#5659]
The **ballsocket** constraint resets both linear and angular damping to `0.2` *(approx. due to a floating point error)* when the linear damping is lower than said value. Angular damping doesn't seem to matter whatsoever.  
Only the **ballsocket** constraint is affected, I cannot reproduce it using **advanced ballsocket**.
  
### Testing environment
Linux on the `x86-64 - Chromium + 64-bit binaries` branch, single-player and a local server, but I'm pretty sure it's also reproducible on Windows *(judging from reports I've gotten on my addon)*.

### Reproduction
You don't need to uncomment anything here, because most of the vanilla props have linear and angular damping equal to `0` by default, so simply applying the **ballsocket**, will clamp them back to `0.2`.  
Models like `models/maxofs2d/logo_gmod_b.mdl` that have different default linear damping make no difference and still reset based around the `0.2` breakpoint.  
```lua
local ent = ents.Create("prop_physics")
ent:SetModel("models/hunter/blocks/cube05x05x05.mdl")
ent:SetPos(Vector(0, 0, 200))
ent:Spawn()

local phys = ent:GetPhysicsObject()
print(phys:GetDamping()) --> 0, 0

-- phys:SetDamping(0.3, -10) -- Linear damping above 0.2 will retain linear and angular damping set here
-- phys:SetDamping(0.1, -10) -- This will cause both linear and angular damping to be reset to 0.2

constraint.Ballsocket(ent, Entity(0), 0, 0, Vector(), 0, 0, false)
print(phys:GetDamping()) --> 0.2, 0.2 (approximation)
```
You can also reproduce it using just the vanilla **Ballsocket** tool. Simply spawn 2 props, apply and remove **ballsocket** from one of them and unfreeze both props at the same time. One will fall visibly slower.

**Comment by adamnejm** [comment]
If this isn't possible to fix in the engine, can we at least restore the damping properties at the end of [`constraint.Ballsocket`](https://wiki.facepunch.com/gmod/constraint.Ballsocket) function? This will of course not cover the cases where people create the `phys_ballsocket` themselves, but I think it would still be worth it.

**Comment by robotboy655** [comment]
I have looked into this, and it only does this if the damping is already below 0.2, it does not reset it if is above that value.

This is done internally as a hacky fix for HL2DM map `dm_powerhouse`, specifically so that the ceiling lamps won't get stuck in the ceiling.

As it stands, i do not see a good reason to undo this as it makes the physics less crazy when a ballsocket is involved.
