### ISSUE TITLE
Entity Thinking for XX ms spam

### ISSUE THREAD

**Issue by Nalo12** [Facepunch/garrysmod-issues#5667]
My server console (linux x64) keep getting spammed (2GO logs) with:

![image](https://github.com/Facepunch/garrysmod-issues/assets/89763856/4dc517a6-5cf7-4b96-b895-1793ea6c977f)
(it happen for all entity)

i've ask on the Garry's mod discord # lua channel and it seem that im not the only one. (my server do a changelevel everyday)

**Comment by Kefta** [comment]
You can disable the prisoner pod from thinking with an entity flag.

**Comment by Nalo12** [comment]
i've disabled their think function with a flag but im still getting spammed with this "error" and like i said it happen with all entity not only a prisoner pod

**Comment by robotboy655** [comment]
You can increase `think_limit` convar to a value that would make the warnings not appear anymore. `0` should disable these checks outright.

I think I will move the warning to `developer 1`.
