### ISSUE TITLE
Phong highlight angle is mismatched

### ISSUE THREAD

**Issue by KETALss** [Facepunch/garrysmod-issues#5669]
Build 13003553

Highlights from lights on phong brushes does not match actual reflection angles, instead phong highlight always appears under the player, only changing the intensivity.
![image2](https://github.com/Facepunch/garrysmod-issues/assets/81901907/9da4ca76-768d-44bc-9a6f-52a1f91c7204)
![image](https://github.com/Facepunch/garrysmod-issues/assets/81901907/32aae98c-a2b1-4384-9333-1e2d9ebfe380)

To reproduce:
1) make a brush with phong material
2) put light or angled sun
3) look at brush phong, reflection on it is mismatched with actual light, always showing under the player

**Comment by KETALss** [comment]
![Screenshot 2023-12-29 125451](https://github.com/Facepunch/garrysmod-issues/assets/81901907/46790177-3303-4f7e-8f8d-6c82701de3b7)
prop_static mesh in far corner - expected behavior, notice the mismatch between brushes

**Comment by MykhailKozak** [comment]
Phong reflectance angles are based on your maps env_sun entity, and aren't determined by local light sources or  the light_environment, you can see this in game if you use the sun editor. Baked lighting only operates as a mask for the phong.

**Comment by robotboy655** [comment]
That is correct, phong angles are based on your maps `env_sun` entity, nothing else.
