### ISSUE TITLE
BSP Embedded Custom Vehicle Script (and other files) not loaded will cause server/game crash due to recent December security update

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5672]
### Details
Custom Vehicle Script used for `prop_vehicle*` entities embedded inside bsp will now failed to load and causing server or game to crash

Server Crash Log:
```
BSP embedded file failed whitelist check - 'scripts/vehicles/car_nuke_npc.txt'
Vehicle (apc_npc_car) unable to properly initialize due to script error in (scripts/vehicles/car_nuke_npc.txt)!
Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Fri Dec 29 14:32:03 UTC 2023: Server restart in 10 seconds
```

Explanation: 
the `apc_npc_car` is a `npc_vehicledriver` entity that tries to drive a `prop_vehicle_apc` with a custom vehicle script embedded in the bsp. Due to recent update, this behaviour is now broken and causing game or server to crash.

Step to Reproduce:
1. Create a basic map with 1 `npc_vehicledriver` or `npc_apcdriver`, or simply without them should be fine (unless you want to make it drivable by player)
2. Create a `prop_vehicle_apc` or `prop_vehicle_driveable` or `prop_vehicle_jeep` (or whatever) with your custom vehicle scripts
3. Compile the map, Pack your custom script inside the map using BSPZip: `scripts/vehicles/custom_car.txt`
4. Run Gmod, load the map, Game/Server crashed

*This happens when map is published on workshop or using legacy addons*. This also happens when placing the map inside `garrysmod/maps` too.

Edit update 3:
- Applies both default 32-bit and 64-bit branches
- `detail.vbsp` also affected ~~but apparently I can exclude this anyway~~ might be needed for custom detail textures
- Color Correction (.raw files) won't be loaded

Should I have to use from `data_static/scripts/vehicles/*.txt` in order to prevent this from happening or is there any other way? Also if don't mind asking, is there a BSP whitelist so we can carefuly determine what embedded files that can be whitelisted in the BSP?

**Comment by Tokopisco** [comment]
I have a similar problem with [my gmod map](https://steamcommunity.com/sharedfiles/filedetails/?id=3016088831)

[ Log ]
BSP embedded file failed whitelist check - 'materials\toko_colorcorrection\c2a5.raw'

[ Explanation ]
I have 2 garrymod, one official and another that I copied with the workshop disabled for my various mapping tests. 
My test gmod doesn't have the December 2023 security update. My 2nd official gmod has the latest update.
The problem being that my .raw colorcorrection texture works on my test gmod but not on the 2nd official Gmod.

[ Step to Reproduce ]
1. Compile a map
2. Pack a .raw file into you're map with BSPZIP
3. Run Gmod & You're map, you're colorcorrection doesn't work

**Comment by Vinzuerio** [comment]
> [ Log ] BSP embedded file failed whitelist check - 'materials\toko_colorcorrection\c2a5.raw'

I totally forgot about this and indeed I tested on my existing maps that has .raw files and they don't work on December update

I think these are the files/directories might get affected:
```
detail.vbsp
scripts/vehicles/*.txt
materials/*.raw  (for color correction)
maps/*.lmp (I think it has been fixed)
```
It could be more btw but I'll update once is there anything important that may be needed

`soundscripts (w/ manifest)` and `soundscape (w/ manifest)` are working fine though.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5668
