### ISSUE TITLE
Calling GetBrushSurfaces on the world returns incomplete data

### ISSUE THREAD

**Issue by meetric1** [Facepunch/garrysmod-issues#5677]
### Details
I am trying to recreate a clientside mesh of the map. The only way (that I could find) to get its triangle data is by using SurfaceInfo:GetVertices. When debugging, the map appears to have missing surface data. (See image)
![image](https://github.com/Facepunch/garrysmod-issues/assets/73554599/72b5d671-d88b-4a56-a946-b6e6492ec94d)

### Steps to reproduce
Go on any map and run the code below to visualize the surfaces
(note that `developer 1` must be on to see it^)
```lua
for _, brush in ipairs(game.GetWorld():GetBrushSurfaces()) do
	local vertices = brush:GetVertices()
	for i = 3, #vertices do
		debugoverlay.Triangle(vertices[1], vertices[i - 1], vertices[i], 30, Color(255, 0, 0, 100))
	end
end
```

**Comment by garryspins** [comment]
GetVertices provides 3 or more vertices, could that be the issue?

**Comment by meetric1** [comment]
I don't think so, the code above takes that into account

**Comment by robotboy655** [comment]
`GetBrushSurfaces` returns the complete list, but `SurfaceInfo:GetVertices` will return 0 vertices for surfaces with displacements or 
 with non-polygon primitives (strips and lists).

I will enable it for the latter, as in my tests there appear to be no negative consequences.

As for your goal, there are still displacements and static props that you cannot really get using current API without manually parsing the BSP file, which someone already made a library for I think.
