### ISSUE TITLE
gui.OpenURL breaks when "Restore my previous browser tabs when starting a game" is disabled in the "In Game" steam settings.

### ISSUE THREAD

**Issue by JustPlayerDE** [Facepunch/garrysmod-issues#5678]
### Details

gui.OpenURL stops working when "Restore my previous browser tabs when starting a game" in the steam "In Game" settings is disabled.

https://github.com/Facepunch/garrysmod-issues/assets/19864478/cc5d82cc-9df9-4297-a931-ce5d044735dd

### Steps to reproduce

- Disable "Restore my previous browser tabs when starting a game" in the "In Game" steam settings
- Run `gui.OpenURL("https://wiki.facepunch.com/gmod/")` in Lua (e.g. `lua_run_cl gui.OpenURL("https://wiki.facepunch.com/gmod/")`)

### Steam Version

Steam Version:  1702079146
Steam Client Build Date:  Fri, Dec 8 01:36 UTC -08:00
Steam Web Build Date:  Sat, Dec 9 00:30 UTC -08:00
Steam API Version:  SteamClient021

**Comment by robotboy655** [comment]
This appears to be an issue with Steam, not the game. There's physically nothing I can do about this.

**Comment by robotboy655** [comment]
I have made Valve aware of this, so it should be fixed on their end eventually.
