### ISSUE TITLE
Disabling addons from the Properties in beta Steam Client causes GMod to redownload addons

### ISSUE THREAD

**Issue by HeadcrabsXc** [Facepunch/garrysmod-issues#5683]
### Details
The beta version of the Steam Client allowed users to enable/disable their addons via the Workshop tab in the Properties menu. 
![Screenshot 2024-01-06 172335](https://github.com/Facepunch/garrysmod-issues/assets/154742111/bf9a9dbb-d73c-4c0a-a7a5-6ef03dae0e80)

- Box w/ checkmark represents an addon that's enabled.
- Bow w/o checkmark represents an addon that's disabled.

Disabling addons via this method causes Garry's Mod to print out a message saying:
```
This should never happen: CreateQueryUserUGCRequest returned 64 items, but GetNumSubscribedItems returned 60
Please report this to the developers if you know how to reproduce this, or if this happenned at all.
```

GMod will also attempt to re-download said disabled addons from the menu.

Version:
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:38:11 Dec  6 2023 (9034) (4000)
GMod version 2024.01.05, branch: dev, multicore: 1
Windows 32bit
```
Despite being on `dev` branch, issue can be replicated on `x86_64` and `none` branches.

### Steps to reproduce

1. Switch to the beta version of the Steam Client.
2. Open up Garry's Mod's properties and select the Workshop sub-menu.
3. Uncheck some of the addons you've subscribed to.
4. Open up Garry's Mod.

Message in console should pop up.

**Comment by HeadcrabsXc** [comment]
To add: GMod will attempt to re-download Workshop addon (despite being disabled in the Steam's properties menu).

**Comment by Dacatzgoescodin5267** [comment]
Feel like either the security update messed it alot or the new workshop update did this

**Comment by robotboy655** [comment]
Such addons will now simply not appear in-game. This change currently applies only to `dev` beta, others will follow soon.
