### ISSUE TITLE
Strange bullet tracer behaviour

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5684]
### Details
![20240107221138_2](https://github.com/Facepunch/garrysmod-issues/assets/11814682/cc6a2530-7698-4200-a847-f3e62a4ad4e2)
![20240107221148_2](https://github.com/Facepunch/garrysmod-issues/assets/11814682/418cce59-1119-4512-8b18-f28fc2003879)

Video
https://github.com/Facepunch/garrysmod-issues/assets/11814682/a7784299-bdc9-4565-b813-63ee2c24a6f0

Bullet tracer effect seems to be broken on multiplayer (bullet offset cames from world origin, not from worldmodel/specific attachment of model), as far as I remember few months ago it was perfectly fine(?)
Also this happens on stock hl2 weapons, running on x64 branch *with no addons*, with January 2024 update

First thing before I found this is that I was trying to make a simple `Entity:FireBullets` but for some odd reason `bullet.Src` doesn't seem to follow worldmodel's/specific attachment ID

### Steps to reproduce
(Method 1)
1. Load a map and add bot & mimic them, tracer comes out from 0,0,0 world origin

(Method 2)
I put this code in shared realm, tho this is very dirty code to confirm if this not only `Entity:FireBullets`'s fault
```lua
local Player = FindMetaTable("Player")
if !Player then return end

function Player:ShootStuff()

	if ( self.ShootDelay > CurTime() ) then return end
	
	self.ShootDelay = CurTime() + 0.2

	local att            = self:GetAttachment(13) --13 - Anim_Attachment_RH, Try 1 (Eyes) too
	-- for somewhat reason it attaches to viewmodel/worldmodel attachment instead, not from Anim_Attachment_RH?
	local shootOrg       = att.Pos --or 1
	
	local bullet = {}
		bullet.Num          = 1
		bullet.Src          = shootOrg --Try on self:GetPos() on bots & other players
		bullet.Spread       = 0.1
		bullet.Tracer       = 1
		bullet.TracerName   = "AirboatGunTracer" --Or Any Tracer
		bullet.Force        = 1
		bullet.Damage       = 2
		bullet.AmmoType     = "smg1"
		bullet.Dir          = self:GetAimVector()
		bullet.Attacker     = self
	
	self:FireBullets( bullet )

end

-- just test, right click to shoot
hook.Add("PlayerTick", "test", function( ply, mv )
	if ply:Alive() and mv:KeyDown( IN_ATTACK2 ) then ply:ShootStuff() end
end)

hook.Add("EntityFireBullets","test", function(ent,data)
	print( data.Src ) -- for some reason the offset can be strange
end)
```

**Comment by robotboy655** [comment]
Will be fixed, it was trying to use the view models of other players when they are rendered in 3rd person after changes to make https://wiki.facepunch.com/gmod/WEAPON:GetTracerOrigin be called in 3rd person as well.
