### ISSUE TITLE
PostEntityFireBullets hook does not run serverside

### ISSUE THREAD

**Issue by spankyyy** [Facepunch/garrysmod-issues#5685]
Ive been developping an addon for a while now but never tested on a dedicated server, but today i did and found out the PostEntityFireBullets hook does not run serverside even tho its shared on the wiki

TLDR

> PostEntityFireBullets doesn't run serverside (Dedicated Server)
> PostEntityFireBullets runs serverside (Singleplayer)

**Code for testing:**

```lua
-- Shared
hook.Add("EntityFireBullets", "TESTING1", function(_, _)
    if not IsFirstTimePredicted() then return end
    
    print("EntityFireBullets", SERVER and "Server" or "Client")
end)

hook.Add("PostEntityFireBullets", "TESTING2", function(_, _)
    if not IsFirstTimePredicted() then return end -- I did test by commenting out this line and it didn't work either
    
    print("PostEntityFireBullets", SERVER and "Server" or "Client")
end)
```

> returns:

```
    Server:
        EntityFireBullets       Server
    
    Client:
        EntityFireBullets	Client
        PostEntityFireBullets	Client
```

**Comment by Kefta** [comment]
Runs on the server as expected in a listen server. I have not yet tested dedi.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/96e50c98-6371-4a53-b82b-a3bafb6d8b65)

Of course it runs on the server, dedicated or not.

You have to make sure your dedicated server is of the correct version, as the hook is not part of the main game yet, only on the beta versions, as stated on the wiki.
