### ISSUE TITLE
Tentacle corpses cannot be removed

### ISSUE THREAD

**Issue by grande1900** [Facepunch/garrysmod-issues#5686]
### Details
If you manage to kill a monster_tentacle, its corpse will spawn, but will just float there because it has no collision.
It also cannot be removed by most accessible means.

![image](https://github.com/Facepunch/garrysmod-issues/assets/54255077/754a7a7d-9af4-47b9-876e-13a2d2fba82b)

Furthermore, if you kill one with Keep Corpses enabled, the tentacle keeps living.

![image](https://github.com/Facepunch/garrysmod-issues/assets/54255077/5f446755-8a01-4548-bbd6-d6f1ca604be7)

### Steps to reproduce
1. Kill a monster_tentacle.
2. Clear the map with gmod_admin_cleanup

**Comment by grande1900** [comment]
> And how exactly are you killing it?
custom weapon that does `math.huge` damage (don't ask)

**Comment by robotboy655** [comment]
Fixed.
