### ISSUE TITLE
PANEL:PreAutoRefresh() and PANEL:PostAutoRefresh() no longer work

### ISSUE THREAD

**Issue by ischmal** [Facepunch/garrysmod-issues#5690]
### Details
Since around the 01.05.2024 update, the `PANEL:PreAutoRefresh()` and `PANEL:PostAutoRefresh()` functions are no longer being called, which I speculate may be connected to the changes in `debug.getregistry()` (since IIRC Derma would register panels there).

### Steps to reproduce
File:
`addons/derma_test/lua/autorun/client/reload_derma_test.lua`

Code:
```lua
local PANEL = {}

PANEL.AllowAutoRefresh = true

function PANEL:Init()
    self:SetSize( 300, 200 )
    self:Center()
    self:MakePopup()
end

function PANEL:PreAutoRefresh()
    print( "pre auto refresh" )
end

function PANEL:PostAutoRefresh()
    print( "post auto refresh" )
end

derma.DefineControl( "reload_derma_test", "Test", PANEL, "DFrame" )

concommand.Add( "make_test_window", function( ply, cmd, args ) 
    local window = vgui.Create( "reload_derma_test" )
end )
```

When the window is opened and the file is saved, the "reloaded control" message prints as expected, but neither auto-refresh function is called:

![Console output](https://github.com/Facepunch/garrysmod-issues/assets/5350086/d82fd868-8962-4167-9c5f-dad730e9e096)

It was working earlier in the month and I've confirmed that it doesn't work with a clean game install with no addons either.

**Comment by Grocel** [comment]
It is related to this:

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/derma/derma.lua#L28-L85

It uses the disabled `debug.getregistry()` function to implement `PANEL:PreAutoRefresh()` and `PANEL:PostAutoRefresh()`.

**Comment by Zaurzo** [comment]
I've made a PR to hopefully fix this issue.
https://github.com/Facepunch/garrysmod/pull/2042
