### ISSUE TITLE
Entity:PhysicsInit() is Broken after Recent 64-bit Update

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5698]
### Details
Build 2024.01.18, 64-bit

`Entity:PhysicsInit()` on Scripted Entity appear to be Broken on some condition
This was fine before update (Tested on dedicated server was fine)

### Steps to reproduce

1. Create `lua\entities\testentity.lua`
```lua
AddCSLuaFile()

ENT.Type 		= "anim"
ENT.Base 		= "base_anim"
ENT.PrintName	= "test"

function ENT:Initialize()
	
	self:SetModel( "models/dav0r/hoverball.mdl" )
	self:PhysicsInit(SOLID_VPHYSICS)
	self:SetMoveType(MOVETYPE_VPHYSICS)
	self:SetSolid(SOLID_VPHYSICS) --Remove or not, still the same
	
	if SERVER then
		self:SetUseType(SIMPLE_USE)
		
		local phys = self:GetPhysicsObject() 
		if IsValid(phys) then  		
			phys:Wake()
			phys:SetMass(20)
		end
	end

	self:SetHealth(100)
	
end
```

2. Create `lua\autorun\test.lua` (or `server\test.lua`)
```lua
if SERVER then

	local Add=Vector(0,0,32)
	hook.Add("PostPlayerDeath", "Drop Item", function( ply )
		
		local pos = ply:GetPos()
		local test = ents.Create("testentity")
		test:SetPos( pos + Add )
		test:SetAngles(angle_zero)
		test:Spawn()
		test:Activate()
		
	end)
	
end
```

3. Start Multiplayer, Any Map
4. Spawn `bot` via console command or invite player
5. Spawn Any Objects (heavy or not that can kill player, Breakable, Non-Breakable, Explosives)
6. Grab with Gravity Gun/Physics Gun and launch at bots/players

Result:
```
[test] Cannot create or destroy physics in a physics callback!
  1. unknown - addons/test/lua/entities/testentity.lua:10  --> points to PhysicsInit
   2. Spawn - [C]:-1
    3. v - addons/test/lua/autorun/test.lua:22
     8. unknown - lua/includes/modules/hook.lua:96
```
You can just kill bots/player with weapon just fine and item are spawned without error. Spawning the entity via give/ent_create are also fine, but when there's too much happening at once, the error will show up.

**Comment by robotboy655** [comment]
Should be fixed when it next updates.
