### ISSUE TITLE
SetMoveAngles not working at all in clientside

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5699]
This issue is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1181 (because bug hasn't been fixed for almost 10 years)

If i remember correctly this function worked in 2020-2021 but currently its not.

In every clientside hook with overridable `CMoveData` `SetMoveAngles` affects only prediction (tries to move player as expected but server ignoring change of move angles)

**Comment by robotboy655** [comment]
Please do not open duplicate issues.
