### ISSUE TITLE
Vector:ToScreen() returns non-int x and y

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5701]
![image](https://github.com/Facepunch/garrysmod-issues/assets/45038542/af569fc9-924a-4f90-aa09-1676d19053c1)

**Comment by garryspins** [comment]
Not an issue

**Comment by robotboy655** [comment]
Yeah I see no reason to touch this unless some examples can be presented where it's an issue.

**Comment by MaslovKK** [comment]
> Yeah I see no reason to touch this unless some examples can be presented where it's an issue.

Render functions ceiling x and y values if its float (though its need to truncate value)

**Comment by MaslovKK** [comment]
For example: Panel:SetSize(5.1, 5) makes real size of the created panel equal to 6, 5

**Comment by Kefta** [comment]
I don't see how that's an issue. Floor them before you send them into those functions if you don't want that behaviour.

**Comment by robotboy655** [comment]
This will not solve such issues outright, a lot of math operations can result in a float precision errory value and needs to be accounted for anyway.
