### ISSUE TITLE
Too Many Edicts! (even when not)

### ISSUE THREAD

**Issue by Batrexus** [Facepunch/garrysmod-issues#5702]
**Details**
Hello, after recent Garry's Mod Server update we encounter a pretty big issue. When cleanuping a server when about 4000 entities are spawned, we have a massive spam of one error:
_Not creating entity "XYZ" - too many edicts! (8064 current, 8192 max)_

After this, command "report_entities" shows the following output:
_Total 4027 entities (0 empty, 4021 edicts)_

Of course it disallows to spawn anything and breaks everything. Even in some cases it insta crashes the server.

**Steps to reproduce**
Well hard to say. But I see this only happening with more than 4000+ entities on map. We have some perma props addon, but I even tried disabling everything on "PostCleanupMap" hook and it doesn't work. It looks like it's spawning map entities BEFORE ending cleanup and removing old ones, but it's just my theory.

Branch: x86-64
Cleanup using: `game.CleanUpMap( false, { "env_fire", "entityflame", "_firesmoke" } )`

**Comment by Verdax1337** [comment]
i got same problem with servers

**Comment by robotboy655** [comment]
I had to undo the change as it was not as safe as I thought it would be, my current thinking is to have `game.CleanUpMap` be delayed until the end of a tick to do its thing. This does mean that scripts will break, but at least the entity count overflow can be avoided.

I have not decided yet whether there should be an argument to choose between delaying `game.CleanUpMap` until after the tick and keeping the current behavior.

On `dev` beta, it is always delayed.

**Comment by CryptAlchemy** [comment]
I have this same issue, can vouch.

**Comment by CryptAlchemy** [comment]
@robotboy655 To confirm, is this something that will come in the next update, perhaps in a hoffix? Or is this something where I have to run that function every time when cleaning up in order to avoid the crash?

**Comment by CryptAlchemy** [comment]
Appreciate your response, thanks!

**Comment by Higamato** [comment]
This function didn't fix for me
`game.CleanUpMap( false, nil, function()
end )`
also tried these
`game.CleanUpMap( false, { "env_fire", "entityflame", "_firesmoke", "phys_bone_follower" } )`
`game.CleanUpMap( false, { "env_fire", "entityflame", "_firesmoke", "phys_bone_follower" }, function()
end )`

**Comment by Higamato** [comment]
[console dump](https://www.paste.tc/too-many-edicts-2)

**Comment by robotboy655** [comment]
As I have already stated above, the 3rd argument is exclusive to the `dev` beta. It will be made available on main version of the game soon.
