### ISSUE TITLE
DXT1 One Bit Alpha is broken

### ISSUE THREAD

**Issue by Isemenuk27** [Facepunch/garrysmod-issues#5704]
Loading VTF this type is broken.
![dxt1alpha](https://github.com/Facepunch/garrysmod-issues/assets/77487254/82885bfb-390a-4556-b2ee-3f7e2f75534f)

Texture and material
[material.zip](https://github.com/Facepunch/garrysmod-issues/files/14013889/material.zip)

**Comment by robotboy655** [comment]
It is not supported by the engine as far as I can tell, but I think I found a workaround that just works (including the alpha channel), that is, forcing the format to `DXT1`.
