### ISSUE TITLE
file.Exists * operator broken after the recent update

### ISSUE THREAD

**Issue by RavMda** [Facepunch/garrysmod-issues#5705]
### Details
The server is running x64 branch of gmod
After the recent update, the * stopped working in file.Exists

Here's an example:
```lua
print(file.Exists("bin/gmsv_mysqloo_*.dll", "LUA"))
false
print(file.Exists("lua/bin/gmsv_mysqloo_*.dll", "GAME"))
false
print(file.Exists("lua/bin/gmsv_mysqloo_linux64.dll", "GAME"))
true
```

**Comment by Grocel** [comment]
It was an unintentional side effect and was removed to improve performance.

https://github.com/Facepunch/garrysmod-issues/issues/5674#issuecomment-1908148281

Please use: https://wiki.facepunch.com/gmod/util.IsBinaryModuleInstalled
It is also saver to use, as using the wildcard would also detect module files as installed, even if they are for the wrong OS or architecture. E.g. a win32 file on linux64 server, etc.

**Comment by robotboy655** [comment]
It was not intentional since it only worked for `LUA` path.
