### ISSUE TITLE
game.MountGMA No Longer Works

### ISSUE THREAD

**Issue by legacy1477** [Facepunch/garrysmod-issues#5708]
### Details
Hi, not much of a LUA coder however I seemingly can't get game.MountGMA to mount GMA files anymore.
I use to load up a map and run lua_run game.MountGMA( "D:/data/weird_delorean_prop.gma" ) then doing a map change in a single player map, but that no longer works for whatever reason. I have tried putting gma files inside of gmod's folder then the addons folder, but no dice.
I did read somewhere that back in 2020 something related to this was changed, but it was still working on a 2022 version of GMod so no idea what happened.

The reason I prefer to load GMA files directly is it's less of a mess and hassle to do it that way. 

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:18:08 Dec 14 2023 (9040) (4000)
GMod version 2024.01.23, branch: public, multicore: 0
Windows 32bit

```[tasklist]
### Tasks
```

**Comment by robotboy655** [comment]
You cannot use absolute paths to mount GMA files.

If you want to just have some `.gma`'s mounted that you have manually downloaded/created, put them either in `common/GarrysMod/garrysmod/` or
`common/GarrysMod/garrysmod/addons/thisfoldercanhaveanyname/` (this path is affected by `-noaddons`).
They will be then automatically mounted.

If you want to use `game.MountGMA` specifically to mount stuff from the `data/` folder, you just use the relative path i.e. `data/myfile.gma`.
