### ISSUE TITLE
Certain Materials dont like being applied to any submaterial id

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/garrysmod-issues#5710]
### Details
when using certain materials such as "models/props_debris/plasterwall034a" using them with sub material tool to apply them to a sub material will cause them to render completely black, even on a freshly started game with no addons (except sub material tool for applying to sub materials) enabled, doing the usual record a; stop method doesnt fix it, and if i apply the texture to the entire model in the way normal material tool would, it works fine
MAY be an AMD specific issue, i am not 100% certain as i do not have the ability to test with an nvidia gpu. could also be a specific issue with this texture, but it definitely is not a sub material tool issue as that doesnt change anything about the textures themselves

![image](https://github.com/Facepunch/garrysmod-issues/assets/50423227/18c5b39c-fc1f-4698-b999-799155eaac97)
![image](https://github.com/Facepunch/garrysmod-issues/assets/50423227/cb0fd5d1-bb48-430b-a5f6-db9267b6cbe5)
![image](https://github.com/Facepunch/garrysmod-issues/assets/50423227/d7d88056-051b-4c05-ad5a-7ca5ea489ff3)

### Steps to reproduce
spawn any prop that has submaterial slots (so basically any prop), using sub material tool, set texture to "models/props_debris/plasterwall034a" (this one seems to be the most easy to recreate the issue with) in one of the sub material ids, issue will present itself

**Comment by robotboy655** [comment]
You are trying to use a material (not a texture) intended for maps to models.

There is a distinction between them that may not be ignored. Model materials use the `VertexLitGeneric` shader, and map materials use `LightmappedGeneric` and others.

**Comment by VCSoldier** [comment]
im unsure as to how you mistook "**models/props_debris/**plasterwall034a" as a map texture, even after i showcased it working if i apply the material normally with matertial tool (material at the top of the submaterial list in submat where it renders correctly) 

i have actually figured out what is causing it after a friend helped figure the issue out. 

r_physpropstaticlighting is set to 1, "Physics props turn black when used with the PBR shader after 2-3 seconds due to Prop Sleeping. After a set time, props "bake" their lighting for optimization." 
(from valvedev wikis own description of how the command works https://developer.valvesoftware.com/wiki/Adding_PBR_to_Your_Mod#Fixes) 

my suggestion would be to set this by default to 0 as the performance impact is unnoticable through testing i have done (loading prop heavy saves/maps show no performance hit from disabling this command)
