### ISSUE TITLE
`prop_combine_ball` and `Half-Life: Source` causes game crashes

### ISSUE THREAD

**Issue by PrikolMen** [Facepunch/garrysmod-issues#5711]
### Details
If kill an NPC from `Half-Life: Source` using `prop_combine_ball` with `prop_combine_ball:GetOwner() == NULL` game will crash.
Works on any game branch.

### Steps to reproduce
1. Install [Combine Ball Damage](https://steamcommunity.com/sharedfiles/filedetails/?id=2782727352) _( **Optional** )_
2. Give any player [weapon_ar2](https://developer.valvesoftware.com/wiki/Weapon_ar2)
3. Spawn a scientist from [Half-Life: Source](https://store.steampowered.com/app/280/HalfLife_Source)
4. Make a player kill scientist using alt attack ( secondary attack ), **if you ignore the first step, the attacking player must leave the server before `prop_combine_ball` touches the NPC**
6. Got a crash

**Comment by Grocel** [comment]
Looks like it happens if the ball doesn't have a valid owner.
Also weird source code: https://github.com/PrikolMen/combine-ball-damage

**Comment by PrikolMen** [comment]
> Looks like it happens if the ball doesn't have a valid owner. Also weird source code: https://github.com/PrikolMen/combine-ball-damage
> 
> Make sure you add the crash dump to your report. Always do.

I don't want to send a crash dump, it contains my local paths and logs that I don't want to send.

The addon code is open and clean just written in a different language, if you are so interested you can check [Yuescript](https://yuescript.org/) and compile it yourself.

This bug was reported by one of the players and I told him I would report it to the game developers, which I did. There is enough information here to find problem and fix it.

Here is the `lua` code that will help in troubleshooting:
```lua
hook.Add( "OnEntityCreated", "prop_combine_ball bug", function( entity )
	
	if ( entity:GetClass() == "prop_combine_ball" ) then
		
		timer.Simple( 0, function()
			
			if entity:IsValid() then
			
				entity:SetOwner()
			
			end

		end )

	end

end )

**Comment by Kefta** [comment]
You can send a crash dump directly to rubat's email if you want to keep it private.
