### ISSUE TITLE
SENT angles different between client and server

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-issues#5712]
`ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.Spawnable = true

function ENT:Initialize()
    self:SetModel("models/hunter/blocks/cube025x025x025.mdl")
	self:SetSolid(SOLID_BBOX)
end`

Result of angle from client - 
![image](https://github.com/Facepunch/garrysmod-issues/assets/45038542/564818ac-e516-4510-8a64-f2250fa8f108)

from server - 
![image](https://github.com/Facepunch/garrysmod-issues/assets/45038542/95054b16-8b16-4e36-8734-6a1075904ceb)

I tried PhysicsInit, SetMoveType, PhysWake, nothing changes. 

![image](https://github.com/Facepunch/garrysmod-issues/assets/45038542/e66f8153-92b4-4e43-a9c3-b9d214b1d1cf)

**Comment by garryspins** [comment]
Can you stop making issues that aren't really issues?

**Comment by robotboy655** [comment]
To be more precise, 351.377-360=-8.623, i.e. the angles are identical.

**Comment by Kefta** [comment]
There is an issue with the client and server wrapping angles differently though, but it's minor.
