### ISSUE TITLE
soundscapes text file blacklisted even when packed into bsp

### ISSUE THREAD

**Issue by Anothuoretta** [Facepunch/garrysmod-issues#5715]
### Details
I made a map with a custom soundscape, everything worked fine until uploading
turns out custom soundscape txt is blacklisted! no problem, pack it into the map bsp with VIDE and reupload
I go in game to find out gmod itself blacklists it as well

"BSP embedded file failed whitelist check - 'ts\soundscapes_gm_infmap_void.txt'"
please add to whitelist if im not doing anything wrong

**Comment by robotboy655** [comment]
Are you sure you are embedding the file at correct path?

 For your information, the correct path is this:
`scripts/soundscapes_*.txt` and it IS whitelisted.

Your path looks like `ts\soundscapes_gm_infmap_void.txt`

It should be in `scripts` not `ts`.
