### ISSUE TITLE
Lua: putting self:UpdateShadow() in ENT:Draw() breaks all shadows and crashes the game.

### ISSUE THREAD

**Issue by LambdaHidden** [Facepunch/garrysmod-issues#5716]
This was tested on the dev branch and standard branch, the problem is present in both.

I made a pretty simple Lua entity with a 3D model (any model seems to work). Here is the code:

```
AddCSLuaFile()

ENT.Type = "anim"

if CLIENT then
	ENT.PrintName = "Crash test"
	ENT.Author = "Hidden"
	ENT.Category = "Other"
	ENT.Purpose = "To do figure out if UpdateShadow is what crashes the game."
end

ENT.Spawnable = true
ENT.AdminSpawnable = true

function ENT:Initialize()
	self:SetModel("models/props_c17/oildrum001.mdl")
	self:PhysicsInit(SOLID_VPHYSICS)
	self:SetSolid(SOLID_VPHYSICS)
	self:SetMoveType(MOVETYPE_VPHYSICS)
	self:SetCollisionGroup(COLLISION_GROUP_WEAPON)
	
	if SERVER then
		local phys = self:GetPhysicsObject()
		if IsValid(phys) then
			phys:Wake()
		end
	end
end

if CLIENT then
	function ENT:Draw(flags)
		self:DrawModel(flags)
		self:UpdateShadow()
	end
end
```

I spawned two of these from the spawnmenu, lifted them into the air with the physgun (so i could see their shadows better), then undid them. I repeated this until one of the shadows stopped following the entity that was casting it. This message got spammed into the console for the rest of the game's duration:

```
BuildActiveShadowList: Breaking from an infinite loop. Let the developers know if you can reproduce this message.
```
Removing the entity sometimes doesn't remove it's shadow, and also adds this to the error message:
```
Prevented Crash! pRenderable is NULL while enumerating shadows.
Material decals/rendershadow has bad reference count -211 when being bound (x2)
```

Leaving the entity's PVS or disconnecting from the server crashes the game. There were also some bizarre oddities like the entity's shadow becoming my dead body's shadow when i die and shadows becoming missing textures when entities are deleted.

Here's the crash dump: https://mega.nz/file/OUZDFAQI#LYiObkx-HrOEhkw7-JQac6bLyDPQUY2s8wTJXZfqsVk

**Comment by robotboy655** [comment]
Thanks for the repro, should be fixed on `dev`.
