### ISSUE TITLE
NPCs become invisible if you're stuck in them

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-issues#5718]
### Details
I don't know why it happens but it does, NPCs become invisible if you teleport/noclip into them. I tested it on npc_kleiner.

### Steps to reproduce
Teleport or noclip into NPCs.

**Comment by robotboy655** [comment]
This is intentional from HL2 behavior, but I guess it makes less sense in GMod, so I guess I will disable that part.
