### ISSUE TITLE
Func_tank's firerate cannot be changed after shooting with a firerate of 0

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5720]
### Details
Im working on a map project of sorts and I have been using a func_tank in it, I basically needed the player to at some point not be able to shoot anything from the func_tank, this is logically achieveable if you set the firerate to 0 via SetFireRate output and then "reenable" it by giving it SetFireRate output to anything but 0.
But this is not how it works apparently.

### Steps to reproduce
[functank.zip](https://github.com/Facepunch/garrysmod-issues/files/14101862/functank.zip)
I made a map to test/review it a bit easier. ^
In front of you is a func_tank, on your left is a green button that will set the func_tank's firerate to 20, on your right is a red button that will set the func_tank's firerate to 0. The func_tank already spawns with a firerate of 20.
If you keep switching between a firerate of 0 and 20 without firing with the func_tank, it will work as intended but the problem is **IF** you set its firerate to 0 and then **FIRE** with the func_tank - it will permanently lock it in that state. Meaning if you at that point set its firerate to 20 and fire with the func_tank, it just wont work.

Has been tested on other branches with no differences.
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:18:08 Dec 14 2023 (9040) (4000)
GMod version 2024.01.23, branch: unknown, multicore: 0
Windows 32bit

**Comment by robotboy655** [comment]
Will be fixed.
