### ISSUE TITLE
trigger hurts with doubling w/ forgiveness do max damage if they are trying to hurt another entity EG a prop

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#5721]
### Details
trigger hurt brushes when set to doubling with forgiveness will do max damage if they are they are constantly trying to hurt an entity
### Steps to reproduce
make a map and place 32 trigger_hurt brushes.
set the damage type to one of each of the [DMG enumerations](https://wiki.facepunch.com/gmod/Enums/DMG)
set the damage model to "Doubling w/forgiveness"
set the damage to 1 and the cap to 128.
compile the map.

in game, place a prop in the trigger brush and wait a few seconds.
go into the trigger and you see that you are taking 64 damage every half second.

### other
this is a map i made to test this
[gm_trigger_hurt_tests.zip](https://github.com/Facepunch/garrysmod-issues/files/14103070/gm_trigger_hurt_tests.zip)

**Comment by robotboy655** [comment]
This is intentional. As I have said previously, the damage is not PER ENTITY or PER PLAYER. Is a flat damage value for everything.
