### ISSUE TITLE
trigger_hurt seems to be incapable of doing DMG_MISSILEDEFENSE

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#5722]
### Details
trigger_hurt brushes set to do DMG_MISSILEDEFENSE or damage type 2147483648 instead do 2147483647
https://wiki.facepunch.com/gmod/Enums/DMG#DMG_MISSILEDEFENSE
### Steps to reproduce
make a map with a trigger_hurt brush
set the damage type to 2147483648
compile, or use the one linked below which i made for testing trigger_hurt brushes
[gm_trigger_hurt_tests.zip](https://github.com/Facepunch/garrysmod-issues/files/14107471/gm_trigger_hurt_tests.zip)
in game run the following command `lua
lua_run hook.Add("EntityTakeDamage","test",function(e,d)local a,b=math.IntToBin(DMG_MISSILEDEFENSE),math.IntToBin(d:GetDamageType())b=string.rep("0",a:len()-b:len())..b MsgN(a,"\n",b,"\n",a==b)end)`
it then prints
`010000000000000000000000000000000`
`001111111111111111111111111111111`
`false`
the variable "a" points to the expected bitflag
the variable "b" points to the actual bitflag

as we can see every bit is set on the actual bitflag except for the one we told our trigger hurt to do
### other
one possible theory is that DMG_MISSILEDEFENSE=2147483648
the highest number allowed in a signed 32 bit integer is 2147483647

**Comment by robotboy655** [comment]
Should be fixed on `dev`.
