### ISSUE TITLE
GMod update this morning broke Client side bone merged entities

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5723]
Boot up Temporal Assassin and I found that todays update fucked up my Clientside Bone merged arms entity. (I say entity, it's literally just a Clientside Model with EF_BONEMERGE and Parenting)

Once again, this didn't happen BEFORE this update dropped, **what in the world are you doing?**

There are **Zero Errors** happening either.

![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/ea637e53-a63e-4c26-b896-7437c41e6881)

**Comment by YuRaNnNzZZ** [comment]
even non-bonemerged clientside models are broken
![2024-01-31_18-10-29_00fa2c62-a70e-42aa-802b-d7f42b8ef94f](https://github.com/Facepunch/garrysmod-issues/assets/5104603/a1717148-ca75-4e25-a26d-427eee5a0cb9)
