### ISSUE TITLE
func_instance_io_proxy is broken

### ISSUE THREAD

**Issue by Aarik1** [Facepunch/garrysmod-issues#5725]
### Details
I tested this using the main branch. The 32 bit binaries are the only ones that has somewhat working instances.

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:18:08 Dec 14 2023 (9040) (4000)
GMod version 2024.01.23, branch: unknown, multicore: 0
Windows 32bit

When a map has an instance with func_instance_io_proxy any inputs into and out of the instance are not handled.
vbsp instead creates broken inputs and outputs.

Here's an example of a func_button calling into an instance
When I do an input to an instance and compile the map it will output this
```
"OnPressed" "test_instance,instance:instance_test_door;Open,,0,-1"
```

Here's an example of a proper instance input
```
"OnPressed" "test_instance_ioproxy,OnProxyRelay1,,0,-1"
```

The same thing also happens with outputs from an instance.

The issue is that the function CMapFile::MergeIOProxy is missing or not being called during instance merging.
This can easily be fixed by going into a more modern engine branch and copying over some functions and code snippets.
I would strongly recommend taking it from CSGO if possible.

### Steps to reproduce
1. Create an instance, place an entity in it that can accept input
2. Create a func_instance_io_proxy in the entity and hook up the io proxy to fire OnProxyRelay to the entity.
3. Create a map and place down the instance, make sure to set the fixup name.
4. Create a button in the map and setup an output into the instance.
5. Compile the map and press the button, nothing should happen.

**Comment by robotboy655** [comment]
`CMapFile::MergeIOProxy` did ran, it just wasn't fully functional due to internal differences between new VMFs and old Source VMFs.

Anyway, the issue is fixed - all VMFs (map, and each instance file) need to be re-saved for this to work properly. MapIO separators are changed from commas to `ESC` character.
