### ISSUE TITLE
`engine.ServerFrameTime()` Crash while not connected to a server

### ISSUE THREAD

**Issue by eprosync** [Facepunch/garrysmod-issues#5726]
### Details
Branch: `x64`
Occured At: `redir__engine__ServerFrameTime`
A crash occurs when calling `engine.ServerFrameTime()` in menu-state while not connected to the server.
Appears that within the subroutine of the cfunction it doesn't check if we are connected and attempts to use a net-channel that probably doesn't exist.

### Steps to reproduce
Simply call `engine.ServerFrameTime()` in menu-state while not connected to a server.

**Comment by robotboy655** [comment]
Menu state of out of scope for bug reports.
