### ISSUE TITLE
ents.FindByModel() inside PostCleanupMap hook called twice on Serverside after game.CleanUpMap() was called

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5728]
### Details
I don't know if this actually bug or intentional but for some reason `ents.FindByModel` appear to get called twice inside `PostCleanupMap` hook after `game.CleanupMap()` was called, this causing some problem when retriving something like `Entity:SkinCount()` become `nil` at some point, however it will return valid skin counts after a second loop. Something's odd between Server and Client entity IDs that has changed too soon and those previously has `nil` skin counts become non existant (but `IsValid` return `true`??) but the newer/duplicated one does.

If you found this confusing, I put a reproduction and other details to explain how this happen.
Also, This was never happened before latest 2024 february updates, I think **Happens on both x86 and x64 branches** Windows 10.

### Steps to reproduce
This problem happens if a map has more `prop_physics`, which typically always happens on prop hunt maps. Could also happens on other entities as well (prop_dynamic, or any entities has `skin`). Use attached BSP file to test out.

1. Download the attached BSP: [skin_bug_test.zip](https://github.com/Facepunch/garrysmod-issues/files/14167259/skin_bug_test.zip) - Load `map skin_bug_test` singleplayer/multiplayer doesn't matter
2. Use the following code in **Shared** realm ( `/lua/autorun/sh_test.lua` )
```lua
local function RandomiseSkin()

	local OilDrum = "models/props_c17/oildrum001.mdl"
	local Crates  = "models/props_junk/wood_crate001a.mdl"

	for _,v in pairs( ents.FindByModel( OilDrum ) ) do  -- pairs or ipairs does the same
		print( v, v:GetModel(), v:SkinCount(), v:SkinCount() == nil and "skin is nil" or "", IsValid(v) and "prop is valid" or "prop is NOT valid" )
	end
	for _,v in pairs( ents.FindByModel( Crates ) ) do  -- pairs or ipairs does the same
		print( v, v:GetModel(), v:SkinCount(), v:SkinCount() == nil and "skin is nil" or "", IsValid(v) and "prop is valid" or "prop is NOT valid" )
	end

end

hook.Add("PostCleanupMap", "randomise_test", RandomiseSkin)
```
3. Do `lua_run game.CleanUpMap()` on console
4. Result:
![image](https://github.com/Facepunch/garrysmod-issues/assets/11814682/54e59986-d655-4639-8031-e9ccb0af6768)

Extra Note: Using console command `gmod_admin_cleanup` actually works, but `game.CleanUpMap()`

As you can see Server side has weird behaviour than clients but notice the Entity IDs are changed.

Edit:
updated code

**Comment by robotboy655** [comment]
See https://github.com/Facepunch/garrysmod-issues/issues/5702#issuecomment-1917563220

**Comment by Vinzuerio** [comment]
`game.CleanUpMap(false, nil, function() end)` works, thanks!

Also does `{ "env_fire", "entityflame", "_firesmoke" }` filter still really needed or it does have automatically filtered from engine?

**Comment by robotboy655** [comment]
You only really need it if you are getting crashes. Ideally there'd be a way for me to reproduce said crashes on demand so they can be fixed. No, it is not included in the base game.
