### ISSUE TITLE
Picking up prop_physics enables their drag

### ISSUE THREAD

**Issue by EntityinArray** [Facepunch/garrysmod-issues#5729]
### Details

Picking up prop_physics with E, causes it to reenable its drag

### Steps to reproduce
1. Look at a prop_physics object and do
`this:GetPhysicsObject():EnableDrag(false)`
2. Pick up the object and drop it again and do
`print( this:GetPhysicsObject():IsDragEnabled() )`
It will return true

**Comment by robotboy655** [comment]
Will be fixed in the next update.
