### ISSUE TITLE
factory reset script parcial soft lock

### ISSUE THREAD

**Issue by EnderGamerXPnew** [Facepunch/garrysmod-issues#5730]
### version
gmod 12

### Details
the integrate batch script FactoryReset-GMod.bat had he slight programming error the "n key or wanever your option is in the user language" aren't define properly so when the user "choice" they stuck into he loop execept if they press the X top button or the yes key

## broken code:
IF ERRORLEVEL == 2 (
	ECHO Aborting.
	EXIT /B 1
)
## one way to fix it:
if %%errorlevel%%==2 echo Aborting & exit /B 1

## note:
 I know it is he very obscure script but i had to report this bug anyway

### Steps to reproduce
just press the no button and your computeur will bib instead of closing the script normaly forcing you to press x to quit

**Comment by robotboy655** [comment]
The beeps you hear are due to you not pressing one of the 2 acceptable inputs - `Y` or `N`. It's part of the `CHOICE` command in windows. There doesn't appear to be a way to disable this behavior.

The `ERRORLEVEL` code is not broken, and is functioning correctly and as expected.
