### ISSUE TITLE
Dropship gun aim fix?

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-issues#5732]
### Details
I don't know if this got mentioned or it's an obscure bug, but could this be fixed in the next update?

https://developer.valvesoftware.com/wiki/Fixing_the_Dropship_gun

### Steps to reproduce
Just go in any map that contains a Dropship with a soldier crate, the gun won't target anything, only fire in direct sight

**Comment by BREEDNKMs** [comment]
it also should be mentioned that the dropship container turret rotation was fixed in hl2 after steam deck update, but the fix was never sync'd with gmod.

**Comment by robotboy655** [comment]
Fixed on `dev`.
