### ISSUE TITLE
Taunt breaks Aim Punch

### ISSUE THREAD

**Issue by PrikolMen** [Facepunch/garrysmod-issues#5733]
### Details
If player at the moment of [`util.ScreenShake`](https://wiki.facepunch.com/gmod/util.ScreenShake) starts dancing, for example, eye angles assigned by `ScreenShake` will become permanent, eye angles returns to normal only after player's death.

### Steps to reproduce
1. Start a sandbox server with a 2 or more player limit.
2. Spawn and enter in noclip.
3. Create a `act` bind, for example `bind t "act dance"`.
4. Fly at high speed into displacement, disable noclip and crash into surface to produce a `ScreenShake` and press `t` key.
5. Enjoy your permanently broken camera.

P.S. In particularly horrible cases camera can rotate more than 90 degrees making further gameplay impossible.

**Comment by robotboy655** [comment]
Should be fixed.

https://github.com/Facepunch/garrysmod/commit/9c55af10646419a50946066228e95359be124d33
