### ISSUE TITLE
[dev] Fresh install of Garry's Mod 

### ISSUE THREAD

**Issue by DopeyPepsee** [Facepunch/garrysmod-issues#5735]
### Details
I started playing Garry's Mod earlier today on the Dev branch when I noticed I was being forced into first person when I usually spawn in using third person weapons. I assumed the error was on my side, however after enabling a HUD it immediately showed me the death screen despite me being very much alive so I realized the issue was not on the third person weapon base, but rather my player seems to not being properly initialized (_at least on the Client as you will notice below_)...

Here is the snippet of code used:
`for k,v in pairs(player.GetAll()) do
 print(v:Alive())
end
`

![image](https://github.com/Facepunch/garrysmod-issues/assets/66791985/3f1efa01-09b3-4573-a95b-0a510ca66a82)

I ran a script via luapad to check if the player is alive and on Client displays me as dead, however on Server it returns as alive.
I did a complete reinstall of Garry's Mod, disabled all addons and moved my legacy addons out as well.

![image](https://github.com/Facepunch/garrysmod-issues/assets/66791985/8d6ec14a-2d6f-4b7b-9e79-5d5d65a4fa29)

It only happens on the Dev branch as I far as I can see, I tested it on mainline, Chromium x64 bit and it seems to be all in order.
Here is what it prints for Chromium x64:
![image](https://github.com/Facepunch/garrysmod-issues/assets/66791985/cf106cd3-92f5-43ee-8ac3-eddab9847cff)
 

### Steps to reproduce

1. Download the Dev branch.
2. Launch a game.

**Comment by robotboy655** [comment]
Should be fixed when the `dev` beta next updates.
