### ISSUE TITLE
`r_maxdlights` is non-functional

### ISSUE THREAD

**Issue by noaccessl** [Facepunch/garrysmod-issues#5738]
### Details
`r_maxdlights` doesn't actually increase the maximum amount of dynamic lights.

### Steps to reproduce
1. Set `r_maxdlights` above `32`
2. Spawn more than 32 lights with a Tool Gun

**Comment by robotboy655** [comment]
It not meant to increase the limit, only lower it (for performance reasons back in 2004 I imagine)

The 32 limit comes from a compile time definition + there are some specifics with dynamic lights that limit them to 32, they make use of bit shifting on 32 bit integers in some places, for speed I imagine.
