### ISSUE TITLE
Missing spawn icons in the spawn menu (dev branch)

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#5742]
### Details
When I open the spawn menu, there are no spawn icons. I tried clicking on where the icons should be, but nothing happened. There wasn't even a noise to signify that something did happen.

I even uninstalled all of my addons, uninstalled Garry's Mod, went into the files and manually deleted any extra files, and reinstalled GMod. None of that helped.

### Steps to reproduce
Open the spawn menu and see what happens.

**Comment by robotboy655** [comment]
Sorry, my bad, I have already issued a fix for this.
