### ISSUE TITLE
CSEnt in CEffectData:SetEntity is nil when called within lua effects

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-issues#5743]
### Details
When creating lua-scripted effects, at the time of reading the entity created with `ents.CreateClientSide()` it will return & print the entity, and sets the appropriate entity in the info needed on the entity. But when the entity is set for `ed:SetEntity(info.entity)` it will read as "[NULL Entity]" in the *clientside* lua effect.

![image](https://github.com/Facepunch/garrysmod-issues/assets/4466200/5c97949b-8f03-4ac1-9daf-4729579fc0c8)

Here is the code which sets the entity for the EffectData:
![image](https://github.com/Facepunch/garrysmod-issues/assets/4466200/ab4803be-2300-4348-9c70-d513cb9cd354)

I'd hope that this isn't internally a limitation of the EntIndex system as to why it becomes null, given CSEnts have an EntIndex of -1

### Steps to reproduce
Create a lua effect with the EffectData's entity set to a CSEnt created with ents.CreateClientSide()

-----

I've been working around this the best I can, but there are some use cases for my effect that I cannot get around due to this.

**Comment by robotboy655** [comment]
I will make it accept clientside only entities properly.
