### ISSUE TITLE
NPC'S dont drop weapons anymore

### ISSUE THREAD

**Issue by BadaBingBR** [Facepunch/garrysmod-issues#5745]
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:07:32 Feb 19 2024 (9235) (4000)
GMod version 2024.02.20, branch: x86-64, multicore: 1
Windows 64bit

So, i don't know what the fuck you just broke but NPC's dont drop weapons anymore, i checked and this only happens on 64-bit branch, shit was working fine yesterday

**Comment by seacat17** [comment]
This bug still persists.
