### ISSUE TITLE
[x64/dev] 2 Save System Issues

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-issues#5748]
- Loading a save for the first time after loading a map loads the entities twice, can be seen if you try to remove a prop and there's an identical one below.

- Trying to clean up the map with gmod_admin_cleanup or through the admin cleanup menu reloads the last loaded save. Only way to remove everything is manually with the remover tool or to do it through a for loop in lua_run

**Comment by robotboy655** [comment]
My bad, I will get this fixed.

**Comment by ZH-Hristov** [comment]
@robotboy655 First issue still persists. Entities are spawned twice on first save load after map load.

**Comment by ZH-Hristov** [comment]
Doesn't seem to happen without addons. Any decent way to debug that? Maybe checking the duplicator modifiers?

**Comment by robotboy655** [comment]
I guess look for addons that change behavior of `game.CleanUpMap()` or use the "PostCleanupMap" hook.

Try `lua_findhooks PostCleanupMap` and `lua_run PrintTable(debug.getinfo(game.CleanUpMap))`.

The latter should say this:
```
["short_src"]	=	[C]
["source"]	=	=[C]
```
