### ISSUE TITLE
All serverside commands break if SourceTV is enabled.

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5749]
### Details
If SourceTV is enabled, all commands below will stop working for some reason.
There could be more commands, but these were all I currently found.
Edit: Could it be that all serverside commands are broken? `bot` also won't work
Edit2: It seems to break **all** server commands

Commands:
- `lua_run`
- `lua_dumptimers_sv`
- `lua_openscript`
- `lua_filestats`
- `lua_find`

### Steps to reproduce
1. Set `tv_enable` to `1`
2. Start a Game
3. Try to any of the commands

NOTE: This issue does not exist on a dedicated server.

**Comment by RaphaelIT7** [comment]
If it helps, it would probably fail somewhere [here](https://github.com/Source-Authors/Obsoletium/blob/master/engine/cmd.cpp#L965-L1062), or maybe it sends the NET_StringCmd to the wrong server/the wrong server processes it? (which is probably not the case)

**Comment by robotboy655** [comment]
Will be fixed.
