### ISSUE TITLE
EntityEmitSound does not work for npc_combine_s in none Beta build

### ISSUE THREAD

**Issue by lingyyyu** [Facepunch/garrysmod-issues#5751]
### Details
EntityEmitSound does not work for npc_combine_s in none Beta build. But in chromium x64 builds it works fine 

### Steps to reproduce
hook.Add( "EntityEmitSound", "NPC_SoundTest", function( sound )
if IsValid(sound.Entity) and sound.Entity:IsNPC() and sound.Entity:GetClass() == "npc_combine_s" then
print(sound.OriginalSoundName)
end
end)

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/2005

Use dev/x64 or wait for the next update.

**Comment by lingyyyu** [comment]
> [Facepunch/garrysmod-requests#2005](https://github.com/Facepunch/garrysmod-requests/issues/2005)
> 
> Use dev/x64 or wait for the next update.

Ok, thanks for the reply.
