### ISSUE TITLE
Crash when trying to destroy some dupe using dynamite.

### ISSUE THREAD

**Issue by unnamed25** [Facepunch/garrysmod-issues#5752]
When trying to destroy the dupe at the link below using dynamite, the game crashes.
https://steamcommunity.com/sharedfiles/filedetails/?id=1733125591
Steps to reproduce:
1)Place a dupe from link.
2)Place dynamite in the middle of the dupe with 500 damage.
3)Detonate dynamite using the numpad.
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:07:32 Feb 19 2024 (9235) (4000)
GMod version 2024.02.19, branch: x86-64, multicore: 1
Windows 64bit
```
[dump.zip](https://github.com/Facepunch/garrysmod-issues/files/14392503/dump.zip)

**Comment by robotboy655** [comment]
This crash is already fixed, but was rolled back due to some other changes, I will get it sorted out on monday.
