### ISSUE TITLE
Increase texinfo and texdata limit

### ISSUE THREAD

**Issue by Aarik1** [Facepunch/garrysmod-issues#5754]
### Details
When the brush limit was increased to 16k other limits such as texinfo and texdata were not increased alongside it. This is a problem, as maps grow they use up more resources and other limits start getting hit. Currently our brush count is around 8k and the texinfo is at 11379/12288. It would also be nice if other limits alongside it were upped as well but currently these are the only limits that are preventing us from going any further.

### Steps to reproduce
Reproducing this requires a giant map that is hitting the limits. I can not provide the vmf for our map as it is currently private.

**Comment by robotboy655** [comment]
Requests should go to the requests repo
https://github.com/Facepunch/garrysmod-requests
