### ISSUE TITLE
Nextbots discard paths that contain ladders

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-issues#5757]
### Details
Nextbots that support ladders, don't climb them on the x86-x64 branch.
They climb perfectly fine on the main/x32 branch.

I did some digging, and the path seemed to be getting discarded whenever `PathFollower:Update( nextbot )` was called.

### Steps to reproduce
One of the most reliable ways to reproduce this is with
[DrgBase](https://steamcommunity.com/sharedfiles/filedetails/?id=1560118657)
+[A bot](https://steamcommunity.com/sharedfiles/filedetails/?id=1794737530) with climbing support.

And any map with navmeshed ladders.
[GMod13_Hotels](https://steamcommunity.com/sharedfiles/filedetails/?id=147132515)
[Navmesh, with ladders](https://steamcommunity.com/sharedfiles/filedetails/?id=3002832599)

The issue persists as well, when using [a nextbot](https://steamcommunity.com/sharedfiles/filedetails/?id=2944078031) totally unrelated to DrgBase.

**Comment by robotboy655** [comment]
Thanks for the repro, will be fixed.
