### ISSUE TITLE
`prop_vehicle_crane` damage info on `EntityTakeDamage` hook

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5760]
### Details
Currently on x64-branch but this also affect on default 32-bit branch (on dedicated server as well).

When hitting `prop_vehicle_crane`, damage info doesn't produce anything on `EntityTakeDamage` hook, but any other vehicles like `prop_vehicle_jeep` does get called. This was working on Half-Life 2 when driving crane and get attacked by combine, and player gets damaged just like normal vehicle jeep does.

Currently it's unknown for a workaround to make this work, and I'm afraid using `Entity:TakeDamageInfo` to `prop_vehicle_crane` would cause loop/crash so I'm avoiding this.

### Steps to reproduce
- Load map `d2_coast_04` and drive the crane, or simply shoot the crane or spawn NPC/trigger the scene after taking down the bridge or Spawn a Bot/Player to attack the crane (by using `bot_mimic 1`) - Edit: It appears the player hitboxes isn't large enough to get damage, I guess this was due to crane's collission
- Console: `lua_run hook.Add('EntityTakeDamage','test',function( ent, dmginfo ) print( ent, dmginfo ) end)` (or `PostEntityTakeDamage` will do)
- Result wont print anything
![image](https://github.com/Facepunch/garrysmod-issues/assets/11814682/112a6938-2d61-4f79-834e-510b94ab990a)

I did the same step but this time with `prop_vehicle_jeep` and it does work, i did test both `EntityTakeDamage` and `PostEntityTakeDamage`
![image](https://github.com/Facepunch/garrysmod-issues/assets/11814682/31e4396d-e8ef-439e-9817-e26455e68b08)

**Edit:**
It appears the player hitboxes isn't large enough to get damage, I guess this was due to crane's collission
Sometimes it get damaged but bullet traces can't intercept enough to the player's hitbox

**Comment by Vinzuerio** [comment]
I found a workaround by using `GM:PostEntityFireBullets` instead, however this is not 100% perfect as it only works from any weapons that uses FireBullets internally, which means Projectiles, Melee, or other Explosive stuff wont work...

[crane_damageinfo_dirtyhack.zip](https://github.com/Facepunch/garrysmod-issues/files/14474443/crane_damageinfo_dirtyhack.zip)

**Comment by robotboy655** [comment]
The main issue with player not getting damaged in the crane is that the crane model does not have a hitbox for damage at all.

It is also broken in Half-Life 2 itself.

I have made the crane vehicle receive damage events, but that still won't fix player not receiving damage. I will see if I can patch the model file to fix it.
