### ISSUE TITLE
so i launched garry's mod beta and it didnt have a menu then i reloaded it then the menu loaded

### ISSUE THREAD

**Issue by Legotheclown** [Facepunch/garrysmod-issues#5762]
### Details
Tell us exactly what happens here, every single detail that you can think of.
Please include information such as which Beta Branch your game is on, the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.
Please try running a different(dev)/none beta branch and verifying your game cache integrity before reporting an issue. 

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link.

### Steps to reproduce
Tell us how to reproduce the problem here, step by step.
If it is a modding API issue, please include minimal code to reproduce the issue on demand.

**Comment by Kefta** [comment]
Can you provide more info? A video, OS+version, any console errors?

**Comment by robotboy655** [comment]
There's not much I can do with this. From what I understand this only happened to you once and I doubt it's a new issue for you.
