### ISSUE TITLE
attacker in "PropBreak" hook is sometimes NULL

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-issues#5765]
https://wiki.facepunch.com/gmod/GM:PropBreak

~~this hook never actually provides the attacker (the example in the wiki page doesnt work)~~

**Comment by mgetJane** [comment]
nvm, this is more specific, it seems like it only doesnt work if it was broken with the club damage type

**Comment by mgetJane** [comment]
actually it seems like PropBreak is trying to use the inflictor instead of the attacker

certain weapons like SWEP guns typically set the player the inflictor while others set the weapon itself or a projectile as the inflictor

**Comment by robotboy655** [comment]
I have done some adjustments, should be more consistent now. Obviously I can't fully eliminate it sometimes being NULL, because sometimes the prop is just not broken by a player.
