### ISSUE TITLE
my gmod server doesnt show on the serverlist

### ISSUE THREAD

**Issue by llidehai3** [Facepunch/garrysmod-issues#5766]
when my gmod server was first opened, it was displayed in the server list, but few minutes past it was not displayed and players could not connect,,my two servers both have this problem
gmod srcds version:Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 14:38:19 Aug  8 2023 (9040) (4000)
GMod version 2023.08.09, branch: unknown
Windows 32bit Dedicated Server

i try to change the server port,open start.bat with administrators and it seems doesnt fix this error

there is the log
L 03/01/2024 - 21:59:26: Log file started (file "logs\L0301004.log") (game "C:\Users\Administrator\Downloads\steamcmd\steamapps\common\GarrysModDS\garrysmod") (version "9040")
L 03/01/2024 - 21:59:26: Loading map "gm_green_mountains"
L 03/01/2024 - 21:59:26: server cvars start
L 03/01/2024 - 21:59:26: "ttt_namechange_bantime" = "10"
L 03/01/2024 - 21:59:26: "ttt_namechange_kick" = "1"
L 03/01/2024 - 21:59:26: "ttt_ragdoll_pinning_innocents" = "0"
L 03/01/2024 - 21:59:26: "ttt_ragdoll_pinning" = "1"
L 03/01/2024 - 21:59:26: "ttt_teleport_telefrags" = "1"
L 03/01/2024 - 21:59:26: "ttt_no_nade_throw_during_prep" = "1"
L 03/01/2024 - 21:59:26: "ttt_allow_discomb_jump" = "0"
L 03/01/2024 - 21:59:26: "ttt_detective_hats" = "1"
L 03/01/2024 - 21:59:26: "ttt_detective_karma_min" = "600"
L 03/01/2024 - 21:59:26: "ttt_detective_min_players" = "8"
L 03/01/2024 - 21:59:26: "ttt_det_credits_starting" = "1"
L 03/01/2024 - 21:59:26: "ttt_detective_pct" = "0.125000"
L 03/01/2024 - 21:59:26: "ttt_detective_max" = "32"
L 03/01/2024 - 21:59:26: "ttt_credits_starting" = "2"
L 03/01/2024 - 21:59:26: "ttt_traitor_pct" = "0.250000"
L 03/01/2024 - 21:59:26: "ttt_traitor_max" = "32"
L 03/01/2024 - 21:59:26: "ttt_postround_dm" = "0"
L 03/01/2024 - 21:59:26: "ttt_haste_minutes_per_death" = "0.500000"
L 03/01/2024 - 21:59:26: "ttt_haste_starting_minutes" = "5"
L 03/01/2024 - 21:59:26: "ttt_roundtime_minutes" = "10"
L 03/01/2024 - 21:59:26: "ttt_round_limit" = "6"
L 03/01/2024 - 21:59:26: "ttt_posttime_seconds" = "30"
L 03/01/2024 - 21:59:26: "ttt_preptime_seconds" = "30"
L 03/01/2024 - 21:59:26: "ttt_firstpreptime" = "60"
L 03/01/2024 - 21:59:26: "ttt_time_limit_minutes" = "75"
L 03/01/2024 - 21:59:26: "ttt_haste" = "1"
L 03/01/2024 - 21:59:26: "ttt_debug_preventwin" = "0"
L 03/01/2024 - 21:59:26: "sbox_persist" = ""
L 03/01/2024 - 21:59:26: "sbox_bonemanip_misc" = "0"
L 03/01/2024 - 21:59:26: "sbox_bonemanip_player" = "0"
L 03/01/2024 - 21:59:26: "sbox_bonemanip_npc" = "1"
L 03/01/2024 - 21:59:26: "sbox_noclip" = "1"
L 03/01/2024 - 21:59:26: "sbox_maxemitters" = "20"
L 03/01/2024 - 21:59:26: "sbox_maxbuttons" = "50"
L 03/01/2024 - 21:59:26: "sbox_maxhoverballs" = "50"
L 03/01/2024 - 21:59:26: "sbox_maxthrusters" = "50"
L 03/01/2024 - 21:59:26: "sbox_maxwheels" = "50"
L 03/01/2024 - 21:59:26: "sbox_maxlights" = "5"
L 03/01/2024 - 21:59:26: "sbox_maxlamps" = "3"
L 03/01/2024 - 21:59:26: "sbox_maxdynamite" = "10"
L 03/01/2024 - 21:59:26: "sbox_maxsents" = "100"
L 03/01/2024 - 21:59:26: "sbox_maxnpcs" = "10"
L 03/01/2024 - 21:59:26: "sbox_maxcameras" = "10"
L 03/01/2024 - 21:59:26: "sbox_maxballoons" = "100"
L 03/01/2024 - 21:59:26: "sbox_maxeffects" = "200"
L 03/01/2024 - 21:59:26: "sbox_maxvehicles" = "4"
L 03/01/2024 - 21:59:26: "sbox_maxragdolls" = "10"
L 03/01/2024 - 21:59:26: "sbox_maxprops" = "200"
L 03/01/2024 - 21:59:26: "sbox_playershurtplayers" = "1"
L 03/01/2024 - 21:59:26: "sbox_godmode" = "0"
L 03/01/2024 - 21:59:26: "sbox_weapons" = "1"
L 03/01/2024 - 21:59:26: "physgun_limited" = "0"
L 03/01/2024 - 21:59:26: "sv_allowcslua" = "0"
L 03/01/2024 - 21:59:26: "physgun_maxrange" = "4096"
L 03/01/2024 - 21:59:26: "ai_disabled" = "0"
L 03/01/2024 - 21:59:26: "ai_ignoreplayers" = "0"
L 03/01/2024 - 21:59:26: "mp_teamplay" = "0"
L 03/01/2024 - 21:59:26: "mp_falldamage" = "0"
L 03/01/2024 - 21:59:26: "mp_weaponstay" = "0"
L 03/01/2024 - 21:59:26: "mp_forcerespawn" = "1"
L 03/01/2024 - 21:59:26: "mp_footsteps" = "1"
L 03/01/2024 - 21:59:26: "mp_flashlight" = "1"
L 03/01/2024 - 21:59:26: "mp_autocrosshair" = "1"
L 03/01/2024 - 21:59:26: "decalfrequency" = "10"
L 03/01/2024 - 21:59:26: "mp_teamlist" = "hgrunt;scientist"
L 03/01/2024 - 21:59:26: "mp_allowNPCs" = "1"
L 03/01/2024 - 21:59:26: "mp_friendlyfire" = "0"
L 03/01/2024 - 21:59:26: "mp_fadetoblack" = "0"
L 03/01/2024 - 21:59:26: "sv_gravity" = "600"
L 03/01/2024 - 21:59:26: "sv_stopspeed" = "10"
L 03/01/2024 - 21:59:26: "sv_noclipaccelerate" = "5"
L 03/01/2024 - 21:59:26: "sv_noclipspeed" = "5"
L 03/01/2024 - 21:59:26: "sv_specaccelerate" = "5"
L 03/01/2024 - 21:59:26: "sv_specspeed" = "3"
L 03/01/2024 - 21:59:26: "sv_specnoclip" = "1"
L 03/01/2024 - 21:59:26: "sv_maxspeed" = "10000"
L 03/01/2024 - 21:59:26: "sv_accelerate" = "10"
L 03/01/2024 - 21:59:26: "sv_airaccelerate" = "10"
L 03/01/2024 - 21:59:26: "sv_wateraccelerate" = "10"
L 03/01/2024 - 21:59:26: "sv_waterfriction" = "1"
L 03/01/2024 - 21:59:26: "sv_footsteps" = "1"
L 03/01/2024 - 21:59:26: "sv_rollspeed" = "200"
L 03/01/2024 - 21:59:26: "sv_rollangle" = "0"
L 03/01/2024 - 21:59:26: "sv_friction" = "8"
L 03/01/2024 - 21:59:26: "sv_bounce" = "0"
L 03/01/2024 - 21:59:26: "sv_stepsize" = "18"
L 03/01/2024 - 21:59:26: "r_VehicleViewDampen" = "0"
L 03/01/2024 - 21:59:26: "r_JeepViewDampenFreq" = "7.0"
L 03/01/2024 - 21:59:26: "r_JeepViewDampenDamp" = "1.0"
L 03/01/2024 - 21:59:26: "r_JeepViewZHeight" = "10.0"
L 03/01/2024 - 21:59:26: "r_AirboatViewDampenFreq" = "7.0"
L 03/01/2024 - 21:59:26: "r_AirboatViewDampenDamp" = "1.0"
L 03/01/2024 - 21:59:26: "r_AirboatViewZHeight" = "0.0"
L 03/01/2024 - 21:59:26: "mp_timelimit" = "0"
L 03/01/2024 - 21:59:26: "mp_fraglimit" = "0"
L 03/01/2024 - 21:59:26: "nextlevel" = ""
L 03/01/2024 - 21:59:26: "sv_maxusrcmdprocessticks" = "24"
L 03/01/2024 - 21:59:26: "sv_alltalk" = "0"
L 03/01/2024 - 21:59:26: "sv_hl2mp_weapon_respawn_time" = "20"
L 03/01/2024 - 21:59:26: "sv_hl2mp_item_respawn_time" = "30"
L 03/01/2024 - 21:59:26: "sv_report_client_settings" = "0"
L 03/01/2024 - 21:59:26: "sv_cheats" = "0"
L 03/01/2024 - 21:59:26: "sv_pausable" = "0"
L 03/01/2024 - 21:59:26: "sv_contact" = ""
L 03/01/2024 - 21:59:26: "sv_voiceenable" = "1"
L 03/01/2024 - 21:59:26: "tv_enable" = "0"
L 03/01/2024 - 21:59:26: "sv_steamgroup" = ""
L 03/01/2024 - 21:59:26: "sv_password" = ""
L 03/01/2024 - 21:59:26: "tv_relaypassword" = ""
L 03/01/2024 - 21:59:26: "tv_password" = ""
L 03/01/2024 - 21:59:26: "deathmatch" = "1"
L 03/01/2024 - 21:59:26: "coop" = "0"
L 03/01/2024 - 21:59:26: server cvars end
L 03/01/2024 - 21:59:30: Started map "gm_green_mountains" (CRC "d71597203bd8cd7a669dda479fe5b9d1")
L 03/01/2024 - 21:59:31: server_cvar: "bsmod_killmove_minhealth" "40"
L 03/01/2024 - 21:59:33: server_cvar: "gred_sv_simfphys_suspension_rate" "0.100000"
L 03/01/2024 - 21:59:33: server_cvar: "gred_sv_isdedicated" "1"
L 03/01/2024 - 21:59:34: server_cvar: "sv_infiniteammo" "2"
L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_gbomb because it is missing Type and Base keys!

L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_grocket because it is missing Type and Base keys!

L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_gunner because it is missing Type and Base keys!

L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_jdam because it is missing Type and Base keys!

L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_mg because it is missing Type and Base keys!

L 03/01/2024 - 21:59:35: Lua Error: Refusing to load wac_pod_mis because it is missing Type and Base keys!

L 03/01/2024 - 21:59:36: Executing dedicated server config file server.cfg
L 03/01/2024 - 21:59:37: Initializing Steam libraries for secure Internet server
L 03/01/2024 - 21:59:37: Logging into Steam game server account
L 03/01/2024 - 21:59:37: server_cvar: "sbox_weapons" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_noclip" "0"
L 03/01/2024 - 21:59:37: server_cvar: "mp_falldamage" "1"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxballoons" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxbuttons" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxcameras" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxdynamite" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxeffects" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxemitters" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxhoverballs" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxlamps" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxlights" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxnpcs" "1"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxprops" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxragdolls" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxsents" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxthrusters" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxvehicles" "0"
L 03/01/2024 - 21:59:37: server_cvar: "sbox_maxwheels" "0"
L 03/01/2024 - 21:59:37: server_cvar: "physgun_limited" "1"
L 03/01/2024 - 21:59:37: server_cvar: "sv_alltalk" "3"
L 03/01/2024 - 21:59:37: Log file closed.

and these is on the server console,i think this is the internet problem so i only cut these
Addon 'The Prone Mod' (1100368137) contains file from 775573383: 'lua/autorun/prone_init.lua'
Adding Filesystem Addon 'c:\users\administrator\downloads\steamcmd\steamapps\common\garrysmodds\garrysmod\addons\sll_sllssss'
Adding Filesystem Addon 'c:\users\administrator\downloads\steamcmd\steamapps\common\garrysmodds\garrysmod\addons\ulib'
Adding Filesystem Addon 'c:\users\administrator\downloads\steamcmd\steamapps\common\garrysmodds\garrysmod\addons\ulx'
Server logging enabled.
Server logging data to file logs\L0301003.log
L 03/01/2024 - 21:59:26: Log file started (file "logs\L0301003.log") (game "C:\Users\Administrator\Downloads\steamcmd\steamapps\common\GarrysModDS\garrysmod") (version "9040")
Network: IP 0.0.0.0, mode MP, dedicated Yes, ports 31023 SV / 27005 CL
L 03/01/2024 - 21:59:26: server_cvar: "mp_flashlight" "1"
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
L 03/01/2024 - 21:59:26: Log file closed.
Server logging data to file logs\L0301004.log
L 03/01/2024 - 21:59:26: Log file started (file "logs\L0301004.log") (game "C:\Users\Administrator\Downloads\steamcmd\steamapps\common\GarrysModDS\garrysmod") (version "9040")

you can see my port is 31023.i opened all the tcp udp ports,and our server has enough“Network traffic” to open the server,my server is in china so i used a "Game Internet Booster " to connect to steam workshop in my server

**Comment by robotboy655** [comment]
This is not a place to get help. You can try asking for help on our official Discord server (https://discord.gg/gmod).

From what I can tell, the issue is on your end with your network configuration, and has nothing to do with the game.
