### ISSUE TITLE
Supercharged Gravity Gun does not work on portal turrets

### ISSUE THREAD

**Issue by Spiritwanderer3** [Facepunch/garrysmod-issues#5770]
### Details
When the supercharged gravity gun is used on the portal turret, it does not work. With a Hit Numbers mod, its shown constantly doing hundreds of damage to try to kill the portal turret, so I believe the issue is that the super gravity gun is not able to kill the turret and therefore not able to pick it up.

### Steps to reproduce

1. Spawn a regular Portal turret from the NPCs tab
2. Use the Super Gravity Gun on it (preferably with a hit numbers mod to see what it's trying to do)

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/67a39812-c42a-4482-bc42-fd85b7ebeb15)

Very clearly it works. The other turret is ground mounted, so obviously that one cannot be picked up.
