### ISSUE TITLE
NPCS that use navmesh is broken on x86-64 branch

### ISSUE THREAD

**Issue by CatWasTaken2** [Facepunch/garrysmod-issues#5771]
### Details
When I spawn a chasing NPC on a separate navmesh square from the player they won't be able to move at all unless the target player is on the same navmesh square the only NPCS I tested it on was DRGBase NPCS

### Steps to reproduce
1. Spawn any NPC on a separate navmesh square from the player

**Comment by gooama** [comment]
@CatWasTaken2 
Delete nav files in the directory
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\maps

Set 'drgbase_navmesh_error' to 0 to disable this message.

Nextbots need a navmesh to navigate around the map. You can generate a navmesh using the command 'nav_generate' in the console.

**Comment by gooama** [comment]
gmpublisher download maps。https://github.com/WilliamVenner/gmpublisher
Delete nav files in the directory
garrysmod\addons\gm_xxxxxxx\maps

**Comment by robotboy655** [comment]
Will be fixed.
