### ISSUE TITLE
Game couldn't find gmod_tool shared.lua file when it's not been requested

### ISSUE THREAD

**Issue by AnotherSpy** [Facepunch/garrysmod-issues#5772]
When i'm loading a singleplayer game or joining multiplayer server with neither sandbox nor ttt gamemode (i've actually got this error first time playing on local server with gamemode that i'm currently developing, it's completely blank, containing only init.lua and cl_init.lua with includes. But when i join multiplayer game with any other gamemode, i'm also getting this error) i'm getting this error in client console:

[AddCSLuaFile] Couldn't find 'weapons/gmod_tool/shared.lua' (\<nowhere\>)

I've tried:

1) Factory resetting gmod via bat file in its root folder and then completely re-installing game
2) Putting this specific file in given folder
3) Changing game branch
4) Deleting all addons & clearing data/cache/download folders

But none of that helped. I'm currently playing at chromium x86-64 branch, but, as i said earlier, i tried to switch branches and it didn't fix the problem.

Console log of local server join attempt:

Changing gamemode to TestGamemode (testgamemode)
WARNING: Port 27015 was unavailable - bound to port 27016 instead
WARNING: Port 27005 was unavailable - bound to port 27006 instead
WARNING: Port 27020 was unavailable - bound to port 27021 instead
Network: IP (my ip), mode MP, dedicated No, ports 27016 SV / 27006 CL
PREP OK

[ERROR] AddCSLuaFile: Couldn't find 'weapons/gmod_tool/shared.lua'

ERROR: Trying to derive entity sent_scarainode from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_aiscarcontroller from non existant entity base_gmodentity!
Initializing Steam libraries for LAN server
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
Server ranking in server browser will be negatively impacted due to sv_setsteamaccount not being set.
Unknown command "sv_tags"

[L] TestGamemode
Map: gm_construct
Players: 1 / 2
Build: 9246
Server Number: 2

Garry's Mod

testgamemode
gm_construct
2
76561198385036781
Rejected transfer of 'maps\gm_construct.nav'
WorkshopDL: Querying 1 addons for info..
Addon 'C:\Program Files (x86)\Steam\steamapps\workshop\content\4000\104605841/104605841.gma' is already mounted, ignoring...
Lua cache is up to date
Assigned anonymous gameserver Steam ID [A-1:1942000647(27449)].
InitFastCopy: only 26% fast props. Bug?
Clientside Lua startup!
Requesting texture value from var "$fbtexture" which is not a texture value (material: pp/toytown-top)
ERROR: Trying to derive entity sent_scarainode from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_aiscarcontroller from non existant entity base_gmodentity!
VAC secure mode disabled.
Redownloading all lightmaps
Another Spy joined 'Orange Team'

**Comment by robotboy655** [comment]
Your have sandbox tool addons installed, which makes the folder for the toolgun exist, which is how the game decides whether a weapon exists or not. It is intentional to work this way, and an unfortunate location for custom toolgun tools.
