### ISSUE TITLE
Rocket turret still attacking if ai_disabled 1

### ISSUE THREAD

**Issue by grisha8bit** [Facepunch/garrysmod-issues#5773]
ai_disabled 1 does not affect on rocket turret from Portal 1 and they continue aiming and shooting.

**Comment by MSchedCOM** [comment]
Make sure there is no addons that modify the AI.
If any present, disable them and then restart the game.

**Comment by grisha8bit** [comment]
At first tested without addons and lately even after Factory Reset the problem remains.
