### ISSUE TITLE
Entity.IsPlayer called with a Player returns false?

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-issues#5778]
### Details
Entity.IsPlayer returns false when calling with a Player entity.
Why?

### Steps to reproduce
1. FindMetaTable("Entity").IsPlayer(Player(SOME_PLAYER_ID)) returns false

**Comment by robotboy655** [comment]
Don't be silly and run `Player(SOME_PLAYER_ID):IsPlayer() ` like any normal human being.

**Comment by zohart75** [comment]
😂
