### ISSUE TITLE
EntityRemoved isnt working for CLuaEffect

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-issues#5779]
### Details
OnEntityCreated is called for CLuaEffect, however EntityRemoved doesnt

### Steps to reproduce
1. Spawn CLuaEffect.
2. Remove CLuaEffect.

**Comment by Deviatt** [comment]
This appears only on x86-64 branch

**Comment by zohart75** [comment]
Lol it's now working but the CLuaEffect is still broken somehow...
