### ISSUE TITLE
Doing a Clean Up while still driving Cranes will crash the game

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5781]
On branch: x64_86, not sure on `none` branch
Windows 10

### Details
When players are still driving on `prop_vehicle_crane` and doing `gmod_admin_cleanup` or `game.CleanUpMap()` will crash the game (or server). A very rare situation where it could self replicate during cleanup and soon will also crash. 

See temporary workaround to avoid this.

### Steps to reproduce
1. Load `d2_coast_04` and enter crane
2. Do `gmod_admin_cleanup` or `game.CleanUpMap()` or `game.CleanUpMap(false, nil, function() end)`

### Temporary Workaround
1. Make sure all player exits any crane vehicle before cleanup using `GM:PreCleanupMap` hook
```lua
hook.Add("PreCleanupMap", "ExitAllPlayers", function()
	
	for _,ply in ipairs( player.GetAll() ) do

		local IsInVeh = ply:InVehicle()
		local GetVeh = ply:GetVehicle()
		
		if IsInVeh and IsValid(GetVeh) and GetVeh:GetClass() == "prop_vehicle_crane" then
			ply:ExitVehicle()
		end
	end
	
end)
```
[crane_crash.zip](https://github.com/Facepunch/garrysmod-issues/files/14474509/crane_crash.zip)

**Comment by robotboy655** [comment]
Will be fixed.
