### ISSUE TITLE
render.Capture/CapturePixels should only block attempts to capture pixels of main and effects rendertargets

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#5783]
Latest update broke three my mods.

It should be completely legal to capture pixels of custom (Lua created) rendertargets even while main menu is open.

**Comment by robotboy655** [comment]
Would you please link the addons that were affected so I can test any potential fixes?

**Comment by DBotThePony** [comment]
Glaring examples:
https://steamcommunity.com/sharedfiles/filedetails/?id=933203381
https://steamcommunity.com/sharedfiles/filedetails/?id=2414242993

**Comment by robotboy655** [comment]
Should be fixed on dev.
