### ISSUE TITLE
Entity func_tankpulselaser uses non existent sounds

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5786]
### Details
While messing around with some entities I noticed that func_tankpulselaser uses sounds that dont exist in the game.

Failed to load sound ")weapons\fx\rics\laser_ric1.wav", file probably missing from disk/repository
Failed to load sound ")weapons\fx\rics\laser_ric2.wav", file probably missing from disk/repository
Failed to load sound ")weapons\fx\rics\laser_ric3.wav", file probably missing from disk/repository
These errors are shown in console after laser particles ricochet off the walls.

Now, Valve Dev Community mentioned that this entity is missing these sounds by default and that they were only present in the HL2 Beta.
So I went off and actually downloaded these sounds from a HL2 Beta project.
[lasers.zip](https://github.com/Facepunch/garrysmod-issues/files/14517467/lasers.zip)
I didnt edit these at all.

### Steps to reproduce
[functankpulselaser.zip](https://github.com/Facepunch/garrysmod-issues/files/14517472/functankpulselaser.zip)
A map for ease of review.

No difference on other branches.
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:18:08 Dec 14 2023 (9040) (4000)
GMod version 2024.01.23, branch: unknown, multicore: 0
Windows 32bit

**Comment by robotboy655** [comment]
I will replace the sounds with some of the already existing ones. We can't just take random sounds off the internet without proper licensing.
