### ISSUE TITLE
server crashing after i enter changes in gamemode/darkrp/ files in this any folder lua file

### ISSUE THREAD

**Issue by Bacring** [Facepunch/garrysmod-issues#5788]
server crashing after i enter changes in gamemode/darkrp/ files in this any folder lua file
i start gmod start.bat and after i change something for example jobs.lua  then i got server shutting down and console don't accept commands and after i try reconnect to then server then i have error connection closed or timeout

**Comment by robotboy655** [comment]
If you are getting a "Server is shutting down" message, that's not a crash, it's a graceful shutdown, specifically when something enters "quit" or "exit" or similar into the server's console.

The other errors you mention sound like generic network errors, could indicate a network configuration error on your end, but it's anyones guess.

That being said, there's nothing for me to do here, it sounds like an issue on your end, not something inherently wrong with the game given that you are the only person experiencing this. I guess try making the server from scratch, or try getting help in the official Discord server (linked in the README of this repository)
