### ISSUE TITLE
NPCs that use PVS sleepstate will glitch out

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#5795]
NPC's that rely on sleepstate `Auto PVS after PVS`, `Auto PVS`, `Waiting for PVS` will have issues when there is more than on client on the server depending on where the clients are at.

The NPCS periodically check if a client is within the PVS to determine if the NPC should go to sleep or wake up. 
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.cpp#L3883

The check of PVS is done in `CAI_BaseNPC::CheckPVSCondition`
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.cpp#L3883

The function uses `UTIL_FindClientInPVS` which just calls `UTIL_FindClientInPVSGuts`
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/util.cpp#L2288

That function uses `UTIL_GetCurrentCheckClient` which returns the current client its checking on, and here is where the problem starts. 
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/util.cpp#L2184

The client to check is determined in `UTIL_GetNewCheckClient` which just cycles the client list, the client index to check is stored in `g_CheckClient`

## The problem is following:
A call to `CheckPVSCondition` cycles the clients, so the first check will be the first player, the player that actually stands next to the NPC, that forces the NPC to be awake. The next call to this function happens after a small delay, the client to check is now the second player due to `UTIL_GetNewCheckClient`, if the second player is not near the NPC it will put the NPC to sleep which means it will be dormant and gets EF_NODRAW. The NPC will eventually wake up as soon `UTIL_GetNewCheckClient` starts at the first client again, this causes NPCs to alternate the state of sleep and awake, depending on how many players are on the server the time the NPC is asleep will vary.

Here are some videos showcasing this issue:
1 bot:
https://github.com/Facepunch/garrysmod-issues/assets/5415177/6d6da1de-788a-4e22-bf4f-5554333bbe8b
6 bots:
https://github.com/Facepunch/garrysmod-issues/assets/5415177/e218893e-585e-4dcc-bdf8-51f441ad40b2
12 bots:
https://github.com/Facepunch/garrysmod-issues/assets/5415177/f6cf1cf7-46d1-49a7-a81b-06135e18c655

There are probably more issues due to this behavior, there is more code that uses `UTIL_FindClientInPVS`. The way this currently works is probably due to performance reasons (back in 2004) or perhaps even a premature attempt of it.

There are a few ways to solve this, the easiest approach is to just query the current PVS sector and check if there is a client in it, the query is fairly cheap and doesn't really need this overcomplicated system. Also to ensure that not too many NPCs query the PVS in the same Tick one could do something like 
```cpp
bool ShouldUpdatePVSCondition(uint32_t ticks, uint32_t entIndex) {
    const uint32_t ticksPerUpdate = 16;
    const uint32_t maxEntitiesPerTick = 32;
    uint32_t entTickIndex = entIndex % ticksPerUpdate;
    uint32_t currentTickIndex = ticks % ticksPerUpdate;
    return entTickIndex == currentTickIndex && entIndex / ticksPerUpdate < maxEntitiesPerTick;
}
```
The result of `CheckPVSCondition` is useless as it sets or clears the condition, so the function can be conditionally called based on `ShouldUpdatePVSCondition`

## Steps to reproduce
1. Load ep1_c17_05.
2. `setpos 9728.988281 9654.244141 -671.968750;setang 3.959978 -84.192429 0.000000`
3. Add a bot.
4. NPC starts alternating between awake and asleep causing it to flicker.

**Comment by robotboy655** [comment]
Possibly related: https://github.com/Facepunch/garrysmod-issues/issues/3845

**Comment by robotboy655** [comment]
Added a console command `sv_npc_full_pvs_checks` (defaults to 1) that does "full PVS checks", i.e. checks if there are any clients in the NPCs PVS, instead of the old behavior.

I have not applied any throttling to the checks for now.

**Comment by ZehMatt** [comment]
This also fixes #2693

**Comment by TankNut** [comment]
Looks like this change surfaced some other issues, AI's are having trouble seeing enemies for the first time and npc_combine_s' especially seem to get stuck executing `SCHED_COMBAT_FACE` with the convar enabled.

https://github.com/Facepunch/garrysmod-issues/assets/1381265/44695fdf-4758-4396-bc92-567b9835b7b8

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by TankNut** [comment]
Looks all good on my end now yeah, AI behaving as normal.
