### ISSUE TITLE
On x86-64, a not-found model path to ents.CreateClientProp(model) causes a crash because error.mdl can't be loaded

### ISSUE THREAD

**Issue by marchc1** [Facepunch/garrysmod-issues#5798]
### Details
- The addon in question, https://github.com/dvdvideo1234/TrackAssemblyTool or https://steamcommunity.com/sharedfiles/filedetails/?id=287012681, has not been updated since January of 2024.
- All individuals experiencing the crash are on the x86-64 branch of Garry's Mod, and joined two different servers that both had Track Assembly installed. Joining on other betas of the game did not cause crashes (DEV or NONE).
- The problems started March 10th, 2024 with one individual, but two others began experiencing issues the day of the latest release of Garry's Mod (March 13th).
- The error complains that "Model models/ron/plarail/scenery/aj01.mdl not found and models/error.mdl couldn't be loaded". It's a hard-crash Engine Error. 
- A whereis for models/error.mdl before joining and crashing results in the expected VPK (garrysmod\sourceengine\hl2_misc.vpk\models\error.mdl). 
- The whereis for the aj01.mdl model says the model cannot be found, both on non-crashing and crashing clients.
- The addon aj01.mdl *should* come from(?), Plarail Advance (https://steamcommunity.com/sharedfiles/filedetails/?id=1512053748), is not installed on either of the servers causing issues, and none of the clients are subscribed to this addon.
- I've seen reports of this issue since late 2021 via searching various places, but only recently have heard of it happening via friends crashing.
- I isolated it to this addon by having one of the friends affected join the server with the addon installed, crash, then join with no other changes other than the addon removed from the server, and no longer experiencing crashes. 
- All clients are Windows with NVIDIA GPU's, both the ones that crash and don't crash. Both servers that the players join run on Windows. 
- Tried to have one of the people affected subscribe to the addon, did not resolve the issue.
- Tried to switch from "Do not download custom sounds" to "Allow all custom files from server", did not resolve the issue.

Lua trace from one of the crashes:
```
Executable: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    0. SetModel - [C]:-1
      1. MakeEntityNone - lua/trackassembly/trackasmlib.lua:2103
        2. GetTransformOA - lua/trackassembly/trackasmlib.lua:2199
          3. RegisterPOA - lua/trackassembly/trackasmlib.lua:2236
            4. (null) - lua/autorun/trackassembly_init.lua:1686
              5. pcall - [C]:-1
                6. Record - lua/trackassembly/trackasmlib.lua:2964
                  7. ImportDSV - lua/trackassembly/trackasmlib.lua:3507
                    8. ProcessDSV - lua/trackassembly/trackasmlib.lua:3771
                      9. (null) - lua/weapons/gmod_tool/stools/trackassembly.lua:95
                        10. include - [C]:-1
                          11. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:154
                            12. include - [C]:-1
                              13. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:372
                                14. include - [C]:-1
                                  15. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:11

  Server
    Lua Interface = NULL

  MenuSystem
	*Not in Lua call OR Lua has panicked*
```

I currently don't have a solid way to reproduce the problem and am using this to store the information somewhere organized. I'll update it as I get more info

**Comment by robotboy655** [comment]
It should be fixed now, thanks for all the details & work you did there.

**Comment by dvdvideo1234** [comment]
Optimized on my side also @marchc1 https://github.com/dvdvideo1234/TrackAssemblyTool/commit/f42bdcfde3a7b8a843b1e4a4deea9660a0a1103c
