### ISSUE TITLE
Map REDOWNLOADED, but remains .bz2

### ISSUE THREAD

**Issue by Shendow** [Facepunch/garrysmod-issues#58]
When joining my servers, I often have a problem where the map would be deleted (in my local /maps/ directory) and redownloaded as a .bz2.
This would lead to a "Missing map" error:

```
Missing map maps/<map>.bsp,  disconnecting
Host_Error: Bad map
```

Maybe this could apply for other content, but I am fairly sure I set up everything correctly. This hasn't happened until May 2013.

**Comment by robotboy655** [comment]
Is this still a thing?

**Comment by Shendow** [comment]
Haven't had it happen lately.

**Comment by Kefta** [comment]
Last time I had it happen was a year ago

**Comment by robotboy655** [comment]
I guess I will close this for now, if it happens again, post here and collect as much data as you can, such as filenames, where exactly file is saved to on your PC and the server (full paths), fastDL links, console logs, etc etc.
