### ISSUE TITLE
studiomdl.exe $lod removemodel fix

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-issues#5803]
This is a very old problem, but since people don't give a shit about optimization, not many people talk about it

`removemodel` parameter causes compiler to fail with an EXCEPTION_ACCESS_VIOLATION error
```
$lod 10
{
	removemodel "my.smd"
}
```
wiki says that studiomdl builds before 2006 works fine, maybe this will help you find the key

**Comment by robotboy655** [comment]
Do you have a model to test with? I tried adding the command to a random model we have and there was no crash.

**Comment by Goldermor** [comment]
> Do you have a model to test with? I tried adding the command to a random model we have and there was no crash.

[dummy.zip](https://github.com/Facepunch/garrysmod-issues/files/14829741/dummy.zip)

**Comment by robotboy655** [comment]
I think I figured out a clean fix for this. I have committed it to `dev` beta.
