### ISSUE TITLE
RunGameUICommand refusing to run engine commands

### ISSUE THREAD

**Issue by Glebux** [Facepunch/garrysmod-issues#5804]
### Details
This occurs on every branch running via Valve Proton (wasn't tested on windows, but it probably has the same issue)
When trying to invoke an engine command via RunGameUICommand it simply returns `Not running engine cmd %command%`
[Console log when tryting to start a new game with RunConsoleCommand replaced with engine commands](https://pastebin.com/HdrjBkuM)

### Steps to reproduce
1. RunString this code snippet from the wiki on the menustate
```lua
RunGameUICommand( "engine gameui_hide" )
```

**Comment by robotboy655** [comment]
Not a bug, menu state scripting is not officially supported.
