### ISSUE TITLE
PhysicsObject:GetFrictionSnapshot() only returns 1 friction data

### ISSUE THREAD

**Issue by spankyyy** [Facepunch/garrysmod-issues#5808]
The function `PhysicsObject:GetFrictionSnapshot()`  only returns 1 friction data even tho the wiki and source sdk 2013 code shows that it returns more than one

**Happens on all branches**

> Steps to reproduce:

1. place your entity in a case where it is in contact with many things
2. call the function `self:GetPhysicsObject():GetFrictionSnapshot()`
3. print the count of what it returns `print(#Snapshot)`
4. print shows theres only 1 friction data

> Other method:

use the `physics_highlight_active` command to show contact points of **Active** entities 
**(make sure the physics object is awake when running the command)**

heres what it does in the source code https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/physics.cpp#L2861

> Conclusion:

What i think is happening is that the glua function doesnt loop through all the friction data
and/or doesnt use `pSnapshot->NextFrictionData()` as shown in the link above

**Comment by robotboy655** [comment]
Well spotted, it was writing each entry to the same table index. Will be fixed.
