### ISSUE TITLE
CreateSound\FadeOut crash

### ISSUE THREAD

**Issue by robotik517** [Facepunch/garrysmod-issues#5809]
In progress of developing a server, i encountered random crashes, narrowed it down to a script, for custom ambient sounds in different places
Tore a script apart until it stops crashing, so here whats left until it stopped

### Details
- Crashes CLIENTs only
- No beta, default gmod
- Have a ton of dumps(51, some particle related, can CEmbers crash on cleanup like env_fire and such?):
- Here are related dumps
https://drive.google.com/file/d/1xckDPmyx_SJ2RlcNnhC150wW5no7j7js/view?usp=sharing
https://dumps.metastruct.uk.to/analyze/a29c6aef2a9213f7ab28701f1450a792cb3d6dfa3d31f46e22c2b65347350bd7
https://dumps.metastruct.uk.to/analyze/fb2bcbc0a6c70c11cb933f99f6a86f9c8214270036b333a4ae889526b52354b0
https://dumps.metastruct.uk.to/analyze/a6ad935189f3fd607069d4b9cae0aea03ea130ad4aae6770d828bb3985cdeec1

### Steps to reproduce
- Vid https://youtu.be/VVXd1qU7ilo
- Execute script https://drive.google.com/file/d/1pI6gLuwDc4ENP8SDbvFtA7lQisDUrUmj/view?usp=sharing
- bind MWHEELUP gmod_admin_cleanup
- Cleanup alot
- If no crash - re-run script

P.S i know this code is not optimal or can be even wrong usage, but crash is present and stable
It happens sometimes in my server tests-runs, some people crash more, some less, no dependencies, it was a 1 or 3 second timer, to highlight the effect i set 0 delay

**Comment by robotboy655** [comment]
Hey, thanks **a lot** for providing the reproduction steps. This crash has been in the game for a while and I could never find a way to reproduce it, but now I know exactly why it is happening, so I can fix it. Again, thanks for the repro.
