### ISSUE TITLE
ENTITY:TestCollision isn't taken into consideration for traces

### ISSUE THREAD

**Issue by Def-Try** [Facepunch/garrysmod-issues#5812]
I was trying to make a spherical entity with dynamically changed size (and physics). From what I saw, Entity:PhysicsInitSphere was ignoring my radius argument. Oh well.
I switched to custom collisions and implemented intercsection algorithm for my entity collisions. Here is the code:
```lua
function ENT:TestCollision(startpos, delta, isbox, extents, mask)
    local oc = startpos - self:GetPos()
    local dir = delta
    dir:Normalize()
    local a = dir:Dot(dir)
    local b = 2.0 * oc:Dot(dir)
    local c = oc:Dot(oc) - self.Radius^2
    local discriminant = b*b - 4*a*c

    if discriminant <= 0 then return false end

    local discriminant_sqrt = math.sqrt(discriminant)

    local intersection_1 = (-(b/2) - discriminant_sqrt) / a
    local intersection_2 = (-(b/2) - discriminant_sqrt) / a

    local hitdistance = intersection_1
    if startpos:Distance(startpos + intersection_2*dir) < startpos:Distance(startpos + intersection_1*dir) then
        hitdistance = intersection_2
    end

    local hitpoint = startpos + hitdistance*dir

    local normal = startpos - hitpoint
    normal:Normalize()

    return {HitPos=hitpoint, Normal=normal}
end
```
I checked it multiple times by drawing a beam from player to hitpoint. It worked. But when testing with physgun, or even a toolgun - my TestCollision got ignored and nothing got hit.

### Details
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:00:21 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: unknown, multicore: 0
Windows 32bit

Code to reproduce:
legacy addon below or custom entity with TestCollisions hook above
[black_hole.zip](https://github.com/Facepunch/garrysmod-issues/files/14732911/black_hole.zip)

**Comment by robotboy655** [comment]
From my limited testing, it would appear that you need to provide properly calculated `Fraction` value as well. In your specific case, could be done like so: `Fraction = (startpos + delta):Length()/hitpoint:Length()`

https://wiki.facepunch.com/gmod/Structures/TraceResult#Hit checks whether the fraction is less than 1 for "yes, trace hit something".

I have updated the wiki page ( https://wiki.facepunch.com/gmod/ENTITY:TestCollision ) with various additional info for how to use the hook.
