### ISSUE TITLE
Crash when trying to take damage with the "DMG_BLAST_SURFACE" type to a player if the player is underwater.

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#5813]
Actually, subject.

How to reproduce:
1)Load map gm_construct.
2)Spawn a prop with any model.
3)Pickup the prop with physgun and submerge it in the water so that it is completely submerged.
4)Enter the water as close to the submerged prop as possible.
5)Point the crosshair at the prop and execute the following Lua code:
``local ent = Entity( 1 ):GetEyeTrace().Entity local dmg = DamageInfo() dmg:SetAttacker( ent ) dmg:SetDamage( 200 ) dmg:SetDamageType( DMG_BLAST_SURFACE ) util.BlastDamageInfo( dmg, ent:WorldSpaceCenter(), 100 )``
[dump.zip](https://github.com/Facepunch/garrysmod-issues/files/14757520/dump.zip)
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:46:58 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: x86-64, multicore: 1
Windows 64bit
```

**Comment by robotboy655** [comment]
Will be fixed.
