### ISSUE TITLE
Incorrect portal turret sounds during disintegration

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/garrysmod-issues#5814]
### Details
If you apply disintegration to a turret from a portal, it will play the sound twice instead of once. Moreover, if the turret has already “turned off”, then the sound will be played after complete disintegration.

### Steps to reproduce
Create a turret - apply disintegration

Bug demonstration -> https://youtu.be/t0oLDkMdEro

**Comment by robotboy655** [comment]
Will be fixed.

**Comment by Sherlock2004** [comment]
> Will be fixed.

Should this fix be in the x86-64 build??? Because at the moment everything is as before.
