### ISSUE TITLE
Text change to bone manipulation in "Start New Game" menu

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-issues#5815]
There are three checkboxes for bone manipulation settings in the "Start New Game" menu that are in broken English and should be fixed.

![image](https://github.com/Facepunch/garrysmod-issues/assets/8369707/cfe05b07-a430-4fc2-b482-dde396e03a09)

My pitch is:
> "Allow NPC bone manipulation"
> "Allow Player bone manipulation"
> "Allow all bone manipulation"

**Comment by robotboy655** [comment]
Ok.
