### ISSUE TITLE
teamonly member in player_say game event not appearing in linux dedicated server

### ISSUE THREAD

**Issue by Bonyoze** [Facepunch/garrysmod-issues#5819]
### Details
The recently added `teamonly` member in the `player_say` game event hook seems to not appear when players chat on a Linux dedicated server. Testing in a Windows dedicated server it exists for both server console and players, but on Linux it will only exist for the server console and is missing for players.

### Steps to reproduce
```
lua_run gameevent.Listen("player_say")
lua_run hook.Add("player_say", "", function(data) PrintTable(data) end)
say my message
(then join the server as a player and try saying something)
```

My results on Windows:
```
say my message
Console: my message
["Priority"]    =       1
["teamonly"]    =       0
["text"]        =       my message
["userid"]      =       0
Bonyoze: my message
["Priority"]    =       1
["teamonly"]    =       0
["text"]        =       my message
["userid"]      =       2
Bonyoze: my team message
["Priority"]    =       1
["teamonly"]    =       1
["text"]        =       my team message
["userid"]      =       2
```

My results on Linux:
```
say my message
Console: my message
["Priority"]    =       1
["teamonly"]    =       0
["text"]        =       my message
["userid"]      =       0
Bonyoze: my message
["Priority"]    =       1
["text"]        =       my message
["userid"]      =       2
Bonyoze: my team message
["Priority"]    =       1
["text"]        =       my team message
["userid"]      =       2
```
(`teamonly` member is missing for player)

**Comment by robotboy655** [comment]
It's clientside only for now.

https://github.com/Facepunch/garrysmod-requests/issues/2294

**Comment by robotboy655** [comment]
I don't see any conceivable way why it would be different for Linux only, and for players only, there's literally no conditional statements where it is set.

Maybe it is related to https://github.com/Facepunch/garrysmod-requests/issues/2294 after all?

**Comment by robotboy655** [comment]
I cannot even reproduce this issue.
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/08c9d875-1ed0-4455-ac20-6b6029caa35e)

I suspect you may have some mod that is manually firing the hook with that field missing?

**Comment by Bonyoze** [comment]
Figured it out. You were right there was an addon firing it with the missing teamonly key. I'll inform this to the addon creator.
