### ISSUE TITLE
Network messages in ENT:Initialize cause weird clientside behavior

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-issues#5820]
### Details
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.04.01, branch: x86-64, multicore: 1
Windows 64bit
```

Bug encountered in singleplayer

Sending a net message from ENT:Initialize with `net.WriteEntity(self)` causes the entity to be available in the net message receiver on the client before GM:NetworkEntityCreated is called. In this state the entity is considered valid by IsValid but it'll be missing every single field.

```
[test] addons/test/lua/entities/test_entity/shared.lua:53: attempt to call method 'TestFunction' (a nil value)
  1. func - addons/test/lua/entities/test_entity/shared.lua:53
   2. unknown - lua/includes/extensions/net.lua:38

Entity [108][test_entity]
```

### Reproduction code
```lua
AddCSLuaFile()

ENT.Type = "anim"
ENT.AutomaticFrameAdvance = true

ENT.Spawnable = true

function ENT:Initialize()
	self:TestFunction()

	net.Start("Net_Test")
		net.WriteEntity(self)
	net.Broadcast()
end

function ENT:TestFunction()
	print("Hello World!")
end

if CLIENT then
	hook.Add("NetworkEntityCreated", "Test", print)

	net.Receive("Net_Test", function()
		local ent = net.ReadEntity()

		if IsValid(ent) then
			ent:TestFunction()
		end
	end)
else
	util.AddNetworkString("Net_Test")
end
```

**Comment by TankNut** [comment]
Addendum, seems like the same thing happens with NetworkEntityCreated where fields don't exist, though a `timer.Simple(0` works as a workaround there.

```lua
if CLIENT then
    hook.Add("NetworkEntityCreated", "Test", function(ent)
        print(ent, ent.Initialize)
    end)
end
```
```
Entity [101][test_entity]    nil
```

**Comment by robotboy655** [comment]
If I understand the issue correctly, it's unavoidable. If you manage to receive the entity in Lua before the engine initializes Lua on it, there's not much that can be done about it. 

The client needs to receive the Lua script name to run for the entity before it can initialize Lua, and the order in which information arrives to the client is dictated by Sources networking.

**Comment by TankNut** [comment]
Figured it would be something like that, it just struck me as odd that lua is able to receive the entity with it's classname and validity intact but isn't able to actually access any of the ENT fields until a tick or two later, especially with the NetworkEntityCreated hook in the second example.

Might be worth a mention on the wiki, but it's nothing that can't be worked around with some effort.

**Comment by robotboy655** [comment]
Turns out this case is fixable, it's just a case of certain code that initializes clientside Lua for entities running after net message processing.

Hopefully this causes no adverse side effects.

**Comment by TankNut** [comment]
I'll have a play with it once it shows up on dev.

**Comment by TankNut** [comment]
Have had a chance to try the change on dev branch now and it doesn't seem to work yet, using the NetworkEntityCreated hook mentioned above to test.

```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:36:52 Apr  4 2024 (9280) (4000)
GMod version 2024.05.02, branch: dev, multicore: 1
Windows 32bit
```

**Comment by robotboy655** [comment]
Looks like I screwed up and forgot to send a variable to `true`. Should be fixed when it next updates.
