### ISSUE TITLE
Gmod server doesn't autorefresh lua upon change. - LINUX, UBUNTU SERVER 22.04.04 

### ISSUE THREAD

**Issue by oiz0pwn** [Facepunch/garrysmod-issues#5825]
### Details
After launching the server, everything works fine.
It is after I edit lua files that are inside the gamemodes folder, they don't autorefresh.
I've made sure that there is no prefix in the srcds -disableluarefresh.

It boogles my mind, I've tried everything, reinstalling the server multiple times, hell, even reinstalling distributions to check if the problem still persists.

My friend who's also hosting on Linux doesn't encounter this problem at all, his lua autorefreshes like it supposed to upon any edit.

Server: Ubuntu Server 22.04.04 LTS
Virtualization: Proxmox

### Steps to reproduce

1. Launch the server
2. Join the server
3. Edit any lua plugin in the contents of any gamemode folder
4. Lua doesn't auto-refresh and has to be refreshed manually via server console.

**Comment by oiz0pwn** [comment]
> Are you sure your server is up to date?
> 
> Are you sure you are not running into some kind of limit Linux has on file watchers? (https://stackoverflow.com/questions/13758877/how-do-i-find-out-what-inotify-watches-have-been-registered)

Yes, my server is up to date.

Yes, I've already changed max watchers and users on inotify, the problem still persists..
The problem is there is nothing in the logs that could indicate a problem with inotify.

**Comment by oiz0pwn** [comment]
Okay, I made more research and here's an update:
Lua Refresh works on the sandbox gamemode, but it doesn't work for some reason on custom gamemodes, such as the helix framework alongside ixhl2rp.

It works on a local, non-linux machine, but it doesn't want to work on our server.

We've made sure all the perms are okay.

**Comment by robotboy655** [comment]
OK, that makes sense, it is already fixed on `dev` beta.
