### ISSUE TITLE
 SetMaterial broken in DX7 mode

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/garrysmod-issues#5826]
### Details
In dx7 mode, SetMaterial doesn't work, not even the material stool works. 

### Steps to reproduce
1. hl2.exe -dxlevel 70
2. try use the material tool, or set the material of something via lua.

### Other notes.
Setting a material on an IMesh still works, only Entity:SetMaterial is broken

**Comment by Xenthio** [comment]
I know this is dumb and you might think "oh just don't use dx7 mode" but it should probably still work.
(I'm using it for RTX Remix, which requires a fixed function pipeline)

**Comment by wolfestridershooter** [comment]
This will only become more important as more people play gmod via RTX Remix especially after HL2 RTX comes out

**Comment by robotboy655** [comment]
The only supported DX mode is 9.

**Comment by Kefta** [comment]
So is RTX remix officially going to be not supported for gmod?

**Comment by robotboy655** [comment]
Naturally, it's a third party tool. While I won't go out of my way to break "support" for it, at this time there's no way I can spend time on improving it for the 3 people that it is useful for.

**Comment by Kefta** [comment]
There will be far more down the line due to the reasons stated above, though I agree it's a natural low priority.
