### ISSUE TITLE
An error occurred when trying to load a save in multiplayer.

### ISSUE THREAD

**Issue by GunterSuperPenguin** [Facepunch/garrysmod-issues#5828]
I play on the x64 branch with chromium. When I try to load a save in multiplayer, this error pops up in my console:
```
[ERROR] gamemodes/sandbox/gamemode/save_load.lua:78: attempt to call method 'IsListenServerHost' (a nil value)
  1. LoadGModSave - gamemodes/sandbox/gamemode/save_load.lua:78
   2. v - gamemodes/sandbox/gamemode/save_load.lua:94
    3. unknown - lua/includes/modules/hook.lua:96
```
And the save doesn't load. This error appeared 2-3 days ago. Up to this time, everything was working fine. This error occurs even if all addons are deleted. My friends also have a this problem.
This does not happen in a singleplayer game.

**Comment by robotboy655** [comment]
It's a known issue, and will be fixed. You can use any other beta branch in the mean time.
