### ISSUE TITLE
[Lighting] dev branch causes lighting issues on certain maps 

### ISSUE THREAD

**Issue by DopeyPepsee** [Facepunch/garrysmod-issues#5830]
### Details
Essentially, I was on the [dev] branch playing on a favorite map of mine when I noticed many props having pitch black lighting.
I cleaned up all my mods to be 100% sure however it still persisted, so I swapped branches to see if the issue could be reproduced.

Here is a [link ](https://steamcommunity.com/sharedfiles/filedetails/?id=2222910384&searchtext=trandoshan)to the map in question.

Here is a picture of the landing pad area on the dev branch.
![20240409002432_1](https://github.com/Facepunch/garrysmod-issues/assets/66791985/0550016e-eb4b-43ed-b1cb-3e6425e54a6a)

Here is the same area on Chromium x64:
![42353645 19999999_image](https://github.com/Facepunch/garrysmod-issues/assets/66791985/f77dd739-2f17-40e6-833f-e12c28a26f60)

Here is a screenshot of some boulders near the edge of the map on dev:
![20240409002437_1](https://github.com/Facepunch/garrysmod-issues/assets/66791985/5796f0cb-fb4c-4f8f-8e4d-944429b029b5)

Here is a photo of the same area but on Chromium:
![42378730 600000024_image](https://github.com/Facepunch/garrysmod-issues/assets/66791985/3b9c22e2-9a06-49f4-8c20-a126b84a56ed)

### Steps to reproduce

1.  Launch a game on a map on the dev branch

Thank you for your time!
Best regards.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/452ced19-99da-47f3-9aaa-bb6d8e23dfab)

This area on `dev` beta?

**Comment by robotboy655** [comment]
Thanks, will be fixed.
