### ISSUE TITLE
Local .gma addons suddenly don't mount (error in console)

### ISSUE THREAD

**Issue by Lombaxtard** [Facepunch/garrysmod-issues#5831]
Last night for me was fine, I was using a bunch of local .gma's as usual, everything worked wondrous. First thing today I boot up GMod to finish doing something and suddenly none (except 1) of my addons initialize. The console is filled with these:
![image](https://github.com/Facepunch/garrysmod-issues/assets/75931669/d13ad314-bf18-4887-96c0-019f03af56bc)
And the only addon that shows up in the menu and works is actually random. If I have a bunch of local addons at the same time I can remove specified addon (in the menu) only for it to be replaced with another random local addon on startup
![image](https://github.com/Facepunch/garrysmod-issues/assets/75931669/375b4e32-f8d2-47c9-afc8-21da893734d1)
I checked and it has nothing to do with "freshness" of the addon, it's just incidental apparently. It says <Replacing existing addon '0'> all over the place as if it requires addon.json or something. But that's the thing, all of the addons are straight rips from Workshop that I just made to be local
P.S. Only online Workshop and extracted addons work as of now. Both with hl2.exe and gmod.exe, reload_local_addons (or something close to it) doesn't help at all

**Comment by robotboy655** [comment]
I forgot to fix this yesterday, I will get it sorted.
