### ISSUE TITLE
Missing physics impact sounds on SENTs

### ISSUE THREAD

**Issue by DoopieWop** [Facepunch/garrysmod-issues#5833]
SENTs seem to be missing physics impact sounds. Normally when a physics object collides with the ground or with another object, it plays an impact sound depending on the speed of the collision, its material and the material of the colliding object. However with entities created with Lua that have physics, there seem to be no physics impact sounds. Impact sounds from weapons work, as well as physics scrape sounds, but not physics impact sounds.

The wiki page on PhysObj:SetMaterial mentions that changing the material clientside, affects the impact sound, which implies that SENTs are meant to make physics impact sounds so I assume this is a bug and not a feature. _(Perhaps though its talking about bullet/melee impact sounds, which would still mean it's broken, as changing the material doesn't change bullet impact sounds or effects, but that's unrelated to this issue)_

I've had this issue with all of my SENTs and I've noticed the same with SENTs from the workshop. Some workshop SENTs made their own physics impact sound function in PhysicsCollide to fix this.

Here is an example SENT I wrote, that results in no physics impact sounds. It's meant to replicate a prop_physics entity with the barrel model.

```lua
AddCSLuaFile()

ENT.PrintName = "Barrel"

ENT.Spawnable = true
ENT.Base = "base_entity"

if SERVER then
	function ENT:Initialize()
		self:SetModel("models/props_c17/oildrum001.mdl")
		self:PhysicsInit(SOLID_VPHYSICS)
		self:PhysWake()
	end
	
	function ENT:OnTakeDamage(dmginfo)
		self:TakePhysicsDamage(dmginfo)
	end
else	
	function ENT:Draw()
		self:DrawModel()
	end
end
```

Steps to reproduce:
1. Slam the SENT with above code against a surface and there will be no impact sound. Compare with a prop_physics entity.

**Comment by robotboy655** [comment]
I will add an option to turn them back on as `ENT.PhysicsSounds = true`. The reason being - there are already entities that rely on this broken behavior, such as the built-in bouncy ball.

The reason they don't play is because of how `ENT:PhysicsCollide` was implemented.
