### ISSUE TITLE
Game Engine overwrites "npc_combine_s" skin.

### ISSUE THREAD

**Issue by SligWolf** [Facepunch/garrysmod-issues#5836]
Hiho!

When you spawn a "Combine Soldier" or "Prison Guard" from the NPC's tab with a shotgun as default weapon, then the game engine will set the skin always to 1.

### **GMod Branch / Version:**
![hl2_MV6PYwlHS3](https://github.com/Facepunch/garrysmod-issues/assets/17761396/84ba09d9-2b99-4638-9dad-046cc6d500b6)

### **Steps to reproduce:**
1. Open your Q-Menu.
2. Got to NPCs to the Combine spawnlist.
3. Set below the "Weapon Overwrite" to shotgun.
4. Spawn a "Combine Soldier" or "Prison Guard".

They will automatically use the second skin because of the shotgun. It seems that the game engine will overwrite the skin.
I checked the lua code from the "commnads.lua" from gmod and came to the conclusion that nothing is wrong here.
Filepath: "cd:\Steam\steamapps\common\GarrysMod\garrysmod\gamemodes\sandbox\gamemode\commands.lua"

I think that this is a bug because if we create a seperate npc_combine_s, with 6 skins for example, the game engine will always overwrite the skin if using a shotgun for the npc. That is unexpected behavior in my opinion.

### **Additional information:**
I also did my tests and noticed if you put these lines (464 - 469):
```lua
	--
	-- Does this NPC have a specified skin? If so, use it.
	--
	if ( NPCData.Skin ) then
		NPC:SetSkin( NPCData.Skin )
	end
```
**below** these lines (526 - 531):
```lua
	-- Body groups
	if ( NPCData.BodyGroups ) then
		for k, v in pairs( NPCData.BodyGroups ) do
			NPC:SetBodygroup( k, v )
		end
	end
```
you can avoid the skin change from the game engine.

This will fix custom listed "npc_combine_s" with skin parameter. 
To fix the GMod Combine's you can add the skin parameter in the "base_npc.lua" to them. 
Both mentioned combine soldiers would need "Skin = 0," to work properly.

If you need more infos or anything i'm glad to help.

Best regards
SligWolf

**Comment by Grocel** [comment]
It is likely that NPC:Spawn() or NPC:Activate() triggers the internal function in `npc_combine_s` entities that makes them change skin whenever they got spawned with a shotgun. So moving the `NPC:SetSkin()` call below spawn/activation will fix the issue.

**Comment by robotboy655** [comment]
Will be fixed on dev soon.

**Comment by SligWolf** [comment]
> Will be fixed on dev soon.

Tested it yesterday in the dev version, works perfect!
Thank you @robotboy655 ! 🥇
