### ISSUE TITLE
Misaligned animation event ID's

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-issues#5838]
### Details
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.04.11, branch: x86-64, multicore: 1
Windows 64bit
```

Bug encountered in singleplayer

I'm doing things that involve setting the player's model to that of an NPC and animating them using CalcMainActivity and related hooks, the issue occurs when the `PlayerHandleAnimEvent` hook is used to try and time events based on animation events built into the NPC model as neither the event ID passed into the hook nor the name given by `util.GetAnimEventNameByID` seem to match what the model is compiled with, or show consistency between map loads.

For example:
`models/hunter.mdl`'s walk_all sequence fires the `AE_HUNTER_FOOTSTEP_LEFT`, `AE_HUNTER_FOOTSTEP_RIGHT` and `AE_HUNTER_FOOTSTEP_BACK` events on different frames. Based on _some_ kind of load or SetModel order the event ID's fed into the hook and the associated names can differ wildly, for example:

Loading into gm_construct, spawning the hunter entity and hitting +use on it to set the player's model caused the following event ID's and names to print into the console when walking around:
```
47	COMBINE_AE_ALTFIRE
46	AE_CITIZEN_HEAL
45	CL_EVENT_EJECTBRASS1
```

Reloading the map and repeating the same process but this time spawning a zombie entity first, hitting +use on that, walking/attacking to trigger it's animation events before undoing the entity and spawning the hunter one instead caused the event ID's and names produced by the hunter model to be completely different, with seemingly no way to map them back to normal (Not that the initial event names were correct)
```
55	AE_ZOMBIE_ATTACK_LEFT
54	AE_ZOMBIE_ATTACK_RIGHT
53	AE_ZOMBIE_ATTACK_SCREAM
```

Relevant code is included below as a legacy addon, the aforementioned hunter and zombie entities are found in the `Pawns - Costumes` entity category.

The console print is in `lua/entities/pawn_costume/sh_hooks.lua` at line 40, `ENT:PlayerHandleAnimEvent` is called through `hook.Add` in `lua/pawn/shared.lua`

[pawn.zip](https://github.com/Facepunch/garrysmod-issues/files/14986373/pawn.zip)

Side note, returning true in the `PlayerHandleAnimEvent` hook doesn't seem to suppress the `Unhandled animation event X for player` console message that you get when `developer 1` is set like `ENT:HandleAnimEvent` seems to do, a fix for that would be great as it spams the console like no other.

**Comment by robotboy655** [comment]
`util.GetAnimEventNameByID` is a completely unrelated function to do with activities (ACT_), the event ID you are giving it is not an ActivityID. They are different things.

The IDs being different in some cases appears to be normal as the custom animation events are registered dynamically. I will see if I can grab you a function that can access/handle these custom animation events.

**Comment by TankNut** [comment]
I'm not working with acts here though? At least not in the bits that are causing issues. I'm trying to use `PlayerHandleAnimEvent` which passes the animation event ID to trigger functionality, `util.GetAnimEventNameByID` should work with that.

**Comment by robotboy655** [comment]
You are right, I got confused, util.GetAnimEventNameByID is right, but it appears to only work with "shared" animation events, while the ones you are trying to use are considered "private" animation events. I am looking into it.

**Comment by TankNut** [comment]
Just to throw out an idea, would it be possible to do the reverse of `util.GetAnimEventNameByID`? Something that lets you pass in the name and it just spits out the dynamic ID (or -1 if not assigned). It would require looking up the names beforehand either in the SDK or by decompiling the corresponding mdl's but that's nothing a bit of documentation couldn't solve.

**Comment by robotboy655** [comment]
Turns out it's a client vs server issue. And it's not an easy one to solve.

The issue is that on listen servers, there are 2 lists of registered animation IDs, one on client and one on server, but the model data instance is singular across both. So the server sets it to one value, and then client sets it to another.

I will make it re-set the IDs for your case, it will fix the issue, but it could crop up elsewhere on listen servers. On dedicated servers I think this is not a problem.

**Comment by TankNut** [comment]
Lovely, I'll do more testing later today and see if that solves the issue. Thanks.

**Comment by TankNut** [comment]
Tested things on my end on the `dev` branch and the names all seem to work as expected now, thanks. The `Unhandled animation event X for player` messages are still there though, would love to get a fix for that as well if possible.
