### ISSUE TITLE
prop_detail limit/error

### ISSUE THREAD

**Issue by robotik517** [Facepunch/garrysmod-issues#5839]
Hi, in progress of making custom detail.vbsp and overhaulin how my grass looks, i`ve stuck with disappearing prop_detail after some distance from map edge, lowering the density helps cover more area, but looks very underwhelming.
In Hammer increasing prop_details draw distance in settings does not result in same disappearing.
Map compiled without errors.

As i`ve searched the issue, came across this:
> Stock compilers limit the number of detail props to 65535. This is not an engine limit, and can technically be raised if necessary by modifying a sanity check in AddDetailSpriteToLump from utils/vbsp/detailobjects.
https://developer.valvesoftware.com/wiki/Detail_props#Sprites

I dont know if i can increase this limit on my side, if i can - tell me.

### Details
- All default.
- Will include everything you need, let me know.
- All related files 
vbsp - https://drive.google.com/file/d/1wIbk20_1wSjCmYQPz48wUwgD5CHoVn3C/view?usp=drive_link
materials - https://drive.google.com/file/d/1yjHGoLMWG5Uyub8uXdS_GI8erBDMJWQJ/view?usp=drive_link

### Visuals
grass03 - 11 unique sprites.
50 density.
- tech visual https://drive.google.com/file/d/19tav8Tpv9BMvFaCTu9lkx_YHBom4QvHV/view?usp=sharing
- visual https://drive.google.com/file/d/1KuRBQAxF0rHDUtlwmsc26GSPJ5z5XyDu/view?usp=sharing

300 density, is okay visually, but almost no map coverage.
- tech visual https://drive.google.com/file/d/1LHrO0B5ctvvkY2FNNy1fn416GxR7zHGR/view?usp=drive_link
- visual https://drive.google.com/file/d/12VujGHY4aPDzT-Ze7d4dsOPb6edXTNQx/view?usp=drive_link

### Steps to reproduce
- Cover map with displacements.
- Assign texture with "%detailtype" to displacement.
- Any grasstype with ~600 density will result ~15% grass coverage.

### Misc
I look how much details are there, and honestly do not believe that this is 65k detail props, in log is says:

> detail props          [variable]           1/16009980 ( 0.0%)

Is this normal? I`ve seen people complaining about such error:

> Placing detail props : 0...1...2...3...4...5...6...7...8...9...Error! Too many detail props emitted on this map! (64K max!)

But i never encountered it, full compile log: https://drive.google.com/file/d/14u6d-lH-nGiRGgVhtalY7E2DHXHJlW6n/view?usp=drive_link

**Comment by robotboy655** [comment]
The compiler detail limit is 32x65k, but the in-game limit is still 65k at the same time on screen if I remember correctly.

**Comment by robotik517** [comment]
I`ve tried to use default detail.vbsp, and it covers all map with "grass02" - density 600 with ease..
It uses only 3 different sprites, does amount of sprites affect some limit?

Cannot make a screenshot of whole map(allocate crash) to prove,

**Comment by robotik517** [comment]
Cut off most of the sprites, used grass03
- Only 2 sprite in all grass03 groups.
- Density 600, amount 0.1, like in default grass02.

Overall should be much less sprites and should cover all map, but..no,
Very different result, very strange dependencies, i dont understand.

Tested vbsp part
![1](https://github.com/Facepunch/garrysmod-issues/assets/46756485/a45bfc1d-a408-4dbf-b367-c6eaf6626463)

Visual result
![20240417160300_1](https://github.com/Facepunch/garrysmod-issues/assets/46756485/2bcb7cfa-f314-42f9-b50b-7759a30e5535)

Original bsp part(successfully covers all map)
![2](https://github.com/Facepunch/garrysmod-issues/assets/46756485/658c1311-2842-40f7-9fdb-706000a88144)

**Comment by robotboy655** [comment]
There might be a limit on specifically sprite count, but I cannot confirm or deny it really without a .bsp to test with.

**Comment by robotik517** [comment]
For some bizarre reason, there is some limit exactly for sprites, that use detailOrientation-0-1, if i use detailOrientation-2, all details create normally, all my unique sprites, all 11 of them.

**Comment by robotik517** [comment]
I figured it out, problem lies in detailOrientation, 0-1 does have a sort of limit, detailOrientation 2 fills whole map with no problem.
I really dont want only a 2d shapes without "shape" ability, i will be really grateful, if you could do something about it.

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.
