### ISSUE TITLE
Displacements with transparent materials now cast shadows (VBSP Regression)

### ISSUE THREAD

**Issue by ShyAnimeGirl** [Facepunch/garrysmod-issues#5840]
### Details
Displacements with any type of transparent material applied will now cast shadows after the latest update (march 2024). This includes materials using additive, translucent, alphatest, alpha, and vertexalpha. This also occurs no matter what displacement flags are set (hull, ray, phys).

Problem Example A: (translucent) Fake water
![20240419051215_1](https://github.com/Facepunch/garrysmod-issues/assets/18611423/be206446-5fa3-45be-a0e1-194ea7f30881)

Here is what it should look like:
![20240419044222_1](https://github.com/Facepunch/garrysmod-issues/assets/18611423/f74ce0de-e75b-473b-8833-fd7027bfd60f)

Problem Example B: (additive) Ocean waves
![20240419052457_1](https://github.com/Facepunch/garrysmod-issues/assets/18611423/7fa57a09-7920-4c37-97e4-ee3d410c2c51)

and as it should be:
![20240419050359_1](https://github.com/Facepunch/garrysmod-issues/assets/18611423/5dbd7294-d17c-4745-95fa-a6c15d516c94)

It is essential that displacements with transparent materials do NOT cast shadows like this as the vast majority if not all use cases for these displacements are for special effects purposes. These effects are very common in many maps and include things like low lying fog, waterfalls, streams, shoreline effects, skybox horizon lines, etc. 

This is a problem with VBSP, some kind of regression possibly related to the recent change: "Fixed displacements with $alphatest 1 materials not having collisions".

### Workaround
The previous version of vbsp.exe from 8/8/23 with the md5 hash of fe0dbabd98793c9ca70dc6fc0683dd6a does not have this issue. Place this old version in your GarrysMod/bin/ folder and these displacements will once again behave as expected.

**Comment by robotboy655** [comment]
Relevant issue: https://github.com/Facepunch/garrysmod-issues/issues/3669

**Comment by robotboy655** [comment]
Will be fixed. You can preview the fix in `dev` beta within the hour.

**Comment by ShyAnimeGirl** [comment]
> Will be fixed. You can preview the fix in `dev` beta within the hour.

thanks bro you are a legend.
