### ISSUE TITLE
calling :SetDSP sequentially crashes

### ISSUE THREAD

**Issue by XAYRGA** [Facepunch/garrysmod-issues#5842]
### Details
Rapidly incrementing the currently used DSP filter will cause the game to crash. 

🗑️ [https://xayr.gay/share/04-2024/1db003bc-c7cf-4e76-8eb3-a7c0c59d29b2.dmp](https://xayr.gay/share/04-2024/1db003bc-c7cf-4e76-8eb3-a7c0c59d29b2.dmp)

### Steps to reproduce

clientside, execute: 

```lua 
local s = CreateSound(LocalPlayer(),"music/mvm_start_wave.wav")
s:Play()
local dspMode = 0
timer.Create("butts",0.5,0,function()
    print(dspMode)
    s:SetDSP(dspMode)
    dspMode = dspMode + 1 
end)
 ```

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.
