### ISSUE TITLE
user generated navmesh crash the game on x86-64 branch

### ISSUE THREAD

**Issue by SCEEPWARE** [Facepunch/garrysmod-issues#5845]
Hi,

it appears that user generated navmeshes (those made directly with nav_generate) crash the game upon map loading when using x86-64 branch. It goes through with the generation of the navmesh, but when the map loads it always crashes (as long as the navmesh is in the maps folder). I switched to the normal branch, which works normally (navmeshes created with this branch doesn't crash the game), however using a navmesh generated with the x86-64 branch still causes a crash of the game. Likewise, using a navmesh generated with the normal branch works with the x86-64 branch. However editing the navmesh with nav_analyze seems to work as it should with both branches.

I verified files through steam, and factory reset the game just to be sure but the issue still remains.

Both my friend and I (we both use x86-64 branch for chromium related addons) have the same issue and we tested using only workshop maps, no other addons

**Comment by robotboy655** [comment]
Can you please attach crash dumps and the `.nav` file that's causing the issue?

**Comment by robotboy655** [comment]
Thanks for the report. It will be fixed.

Those invalidly generated navmeshes will need to be deleted and re-generated.
