### ISSUE TITLE
Child entities override the color of anim type entities

### ISSUE THREAD

**Issue by kuma7X** [Facepunch/garrysmod-issues#5847]
### Details
When you set the color of any entity and then you make that entity a child of another entity with ENT.Type set to "anim," the parent entity is rendered with the color assigned to its child entity. This is indeed a rendering bug, as evidenced by the fact that calling GetColor returns the color the parent entity had originally. However, I would like to point out that this issue doesn't occur with every child entity; it seems to only happen when child entities have specific models. For example:

models/alyx.mdl
models/gman_high.mdl
models/Kleiner.mdl

I have also tested and found that this issue does not occur with the following models, to name a few:

models/vortigaunt.mdl
models/Combine_Super_Soldier.mdl
models/Combine_turrets/Floor_turret.mdl

GMod version 2024.03.21
Windows 32bit

### Steps to reproduce
1. Set the color of entity A (type anim).
2. Set the color of entity B.
3. Make entity B a child entity of A with SetParent (any bonemerge tool will work as well).

**Comment by kuma7X** [comment]
For my tests, I turned the aforementioned models into animatable props using the Easy Animation Tool, then bonemerged one of the other models using the Easy Bonemerge Tool.

**Comment by kuma7X** [comment]
I gotta be more specific describing the steps to reproduce the issue. I performed another test and did this:

1. Spawn models/Lamarr.mdl using the spawnmenu.
2. Turn it into an animatable prop using the Easy Animation Tool.
3. Set a color with the Color Tool.
4. Spawn models/alyx.mdl using the spawnmenu.
5. Set a color with the Color Tool.
6. Set Lamarr as the parent of Alyx using the Easy Bonemerge Tool.

**Comment by robotboy655** [comment]
This is more of a bug with the Easy Animation Tool, rather than the game.

This was the fix:
https://github.com/robotboy655/gmod-addons/commit/1710ca7bb5b515d31434251e5b0638215aed9f85
