### ISSUE TITLE
Crash / Double Physics for Ragdoll

### ISSUE THREAD

**Issue by oninoni** [Facepunch/garrysmod-issues#5849]
When experimenting with ragdolls i encountered the following bug and resulting server crash:

When you try to change the model of a ragdoll (For example when a player takes armor from a dead body), you would expect :SetModel() to just work, like it does on player or other animated entities.
Due to different bone orders, this is not as simple, so a recall of :Spawn() becomes necessary to re-generate all ragdoll physics.
If you call :Spawn() on a ragdoll (no matter if you change the model or not) it seems to create a "Ghost Ragdoll" in its previous position and adds the update ragdoll on top again.

My suspicion is, that since the [ent:PhysicsDestroy()](https://wiki.facepunch.com/gmod/Entity:PhysicsDestroy) Function is marked as "Does not work with ragdolls" this function is probably internally called, to remove the old physics when respawning the ragdoll.
Since it does nothing for ragdolls the game just add the new physics, but keeps the old ones. 
Creating an entity linked partially to the physics for 2 entities.

If you now delete that entity, the server crashes after a few moments.
If Crash Logs are required, I can supply them, but it is fairly easy to reproduce.

I'm running on the default branch of gmod on a dedicated server. Haven't tested in SP, but probably also happens there.

### Steps to reproduce
1. Spawn a ragdoll.
2. Call ent:Spawn() on that ragdoll, to respawn it.
3. Move away the ragdoll with your physgun.
4. Walk into the invisible broken second collision object.
5. (Optional) Delete the ragdoll and see your server crash.

**Comment by robotboy655** [comment]
Cannot reproduce either of these issues.  Spawn ragdoll via spawnmenu, call Spawn() on it serverside, it gets respawned and old physics objects are removed. No crash on deletion.

What is your game version?

**Comment by oninoni** [comment]
version
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:44:59 Jul 13 2023 (9014) (4000)
GMod version 2023.07.14, branch: unknown
Windows 32bit Dedicated Server

Weird? I thought I had updated the server. Seems a bit old?
Ill check on my version...

**Comment by robotboy655** [comment]
Yeah, your game server is severely out of date.

**Comment by oninoni** [comment]
I am officially an Idiot...
My update Script Broke...
Thank you...
