### ISSUE TITLE
file.Find function broken on Linux

### ISSUE THREAD

**Issue by kurt-stolle** [Facepunch/garrysmod-issues#585]
The file.Find function does not work on Linux when using MOD or GAME as second argument.

**Comment by philxyz** [comment]
Or "WORKSHOP".

It just doesn't return anything at all.

**Comment by robotboy655** [comment]
Is this on Dev or all versions?

**Comment by philxyz** [comment]
I haven't tried it on dev.

I was trying to find vehicle scripts using:

local file, folder = file.Find("*.txt", "WORKSHOP")

I also tried finding model files:

local file, folder = file.Find("*.mdl", "GAME")

No joy.

This is on the current (stable) Linux client.

**Comment by robotboy655** [comment]
```
local file, folder = file.Find("models/*.mdl", "GAME")
```

**Comment by philxyz** [comment]
I'll try it, thanks - it would be useful to have a bit extra detail on how this works on the wiki since it's not so obvious that you have to specify the full path and that it doesn't recurse.

**Comment by zerfgog** [comment]
@philxyz Wiki is publicly editable ;)

**Comment by philxyz** [comment]
Sure. But one has to know something before being able to publish the details about said thing. I can't see how that function works internally, so I rely on the wiki mostly for the detail.

**Comment by philxyz** [comment]
OK, seems to work, thanks Rubat - sorry for the false report.
