### ISSUE TITLE
IGModAudioChannel:EnableLooping(true) - Causes the audio to cut off randomly.

### ISSUE THREAD

**Issue by AwertaDreams** [Facepunch/garrysmod-issues#5852]
- [X] I checked existing issues.
- [X] I tried every branch, didnt fixed my issue.
- [X] I dont use any other addons.

### Details

Hello! I tried to create a simple lua script in my gamemode to loop a sound in a certain areas. The issue is, that when I'm using ``IGModAudioChannel:EnableLooping(true)`` the audio cuts off randomly. Without it, the audio plays perfectly fine!

Video proof:

https://github.com/Facepunch/garrysmod-issues/assets/134288412/14325b39-a307-4b94-a229-93a6573a08d8

### Version of my garry's mod installation.

``
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.04.24, branch: x86-64, multicore: 1
Windows 64bit
``

### Steps to reproduce
Use this lua code to reproduce the error.

```lua
local Locations = {
    [1] = {name = "testing3", vec1 = Vector(-1000, -1000, -1000), vec2 = Vector(1000, 1000, 1000)},
    [2] = {name = "testing1", vec1 = Vector(-14544, -13381, 190), vec2 = Vector(-14007, -12744, 583), song = "000.wav"},
    [3] = {name = "testing4", vec1 = Vector(-300, -300, 0), vec2 = Vector(300, 300, 200)} -- ignore this
}
local function IsVectorInsideLocation(vec, location)
    return vec:WithinAABox(location.vec1, location.vec2)
end

local function GetPlayerLocation(playerPos)
    for _, location in ipairs(Locations) do
        if IsVectorInsideLocation(playerPos, location) then
            return location
        end
    end
    return nil -- Default return value if player is not in any known location
end

local currentPlayerLocation = nil
local currentLocationSong = nil

local function PlayLocationSong(location)
    if location and location.song then
        local soundPath = 'sound/'.. location.song
        sound.PlayFile(soundPath, "noblock", function(station, errorID, errorName)
            station:EnableLooping(true)
            
            if errorID then
                print("Error playing song:", errorName)
                return
            end

        end)
    end
end

hook.Add("Think", "CheckPlayerLocation", function()
    if IsValid(LocalPlayer()) then
        local playerPos = LocalPlayer():GetPos()
        local newPlayerLocation = GetPlayerLocation(playerPos)
        
        if newPlayerLocation ~= currentPlayerLocation then
            if currentLocationSong then
                currentLocationSong:Stop()
                currentLocationSong = nil
            end
            PlayLocationSong(newPlayerLocation)
            currentPlayerLocation = newPlayerLocation
        end
    end
end)

```
And heres the sound files:

[The sound.zip](https://github.com/Facepunch/garrysmod-issues/files/15179509/The.sound.zip)

**Comment by robotboy655** [comment]
You need to keep a reference to the sound object, otherwise it will be garbage collected and the sound will be forcibly stopped.

I.e. you need to do `currentLocationSong = station`.
