### ISSUE TITLE
Donut crashes Hammer Editor

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5853]
This might be one of the reasons why my Hammer sometimes crashes.
![donut](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0dd2146e-71cb-452b-a229-13a3b0204067)
[ **models/noesis/donut.mdl** ] Is the model in question.
[DonutOfDoom.zip](https://github.com/Facepunch/garrysmod-issues/files/15181050/DonutOfDoom.zip)
^ Map + crash log + decompiled donut files ( not sure if those were necessary )
Load up the map, click on the barrel and type in donut in the Model Browser, when you click on the model - Hammer crashes.
Interestingly, if you replace barrel's ID with the donut's ID, the prop will appear as normal. So its gotta be an issue with the Model Browser?
Consistent on other branches.

**Comment by robotboy655** [comment]
Will be fixed.
