### ISSUE TITLE
Portal1 npc_rocket_turret Input bug

### ISSUE THREAD

**Issue by ZvZPvz** [Facepunch/garrysmod-issues#5854]
### Details
The settarget input for npc_rocket_turret is broken
In any case, it will only target player

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.04.24, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
1.Spawn a npc_rocket_turret
2.ent_fire npc_rocket_turret settarget (anything)
3.The settarget doesn't work,still target player

**Comment by robotboy655** [comment]
Will be fixed.
