### ISSUE TITLE
GMod Addons failing to parse or install, What do i do : THIS ISNT ABOUT ADDONS THIS IS HAPPENING TO EVERY ADDON FOR MY COMPUTER:

### ISSUE THREAD

**Issue by TheSmartieFarty** [Facepunch/garrysmod-issues#5855]
Details
1. Incident```
Yesterday I was playing Garry's mod, I was messing with some Addons I downloaded on the workshop and I came across a YouTube video talking about a game called Unrecord and it was super realistic and I mean super realistic, so I searched on YouTube again to find some tutorials on how to make my game look good like that, so I found this YouTube video called the Final Unrecord Garry's mod Guide you will ever need, it gave me the addons it suggested so I downloaded them on a Garry's mod addon collection called The Final Unrecord collection ever, with the description of: This is a comprehensive collection of mods needed to replicate the hyper-realistic bodycam shooter game Unrecord in Garry's mod.
it had a total of 308 Addons in there and it was made by a guy named Green. Please note I did a Catche clear, and I also revalidated my files. But when I went to test the Shaders I accidentally did something I forgot what I did but it sent some steam files into the
trash, so I went to go revalidate them and bring them back but I think it corrupted my files, searched on the web for hours I was also using Copilot to help me navigate through my messy folders, I tried restarting, Reinstalling, Deleting all Gmod files and revalidating them after to make sure I didn't accidentally added anything, I logged in and out of steam and that didn't work my computers all up to date, I have no Viruses malware of any shape or form. I was going to give up so I contacted my Freind Nostrilpiper Von Headcheddar who is an Addon creator Shout out btw, all they said was to Validate integrated files so I did that didn't work I reinstalled the addons that didn't work, so now at my last ditch effort I am here and this is as much info as I remember as of rn.

**The Lua errors and Problems I got on loading in
2. Errors. Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2593047682/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2593047682/gmpublisher.gma' from 'Viewpunch Viewbob' (2593047682)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\3233720748/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\3233720748/gmpublisher.gma' from 'Smooth Out Stairs' (3233720748)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2737702541/shmovement.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2737702541/shmovement.gma' from 'Shmovment: Simple Headbob, Better Firstperson' (2737702541)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2916483614/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2916483614/gmpublisher.gma' from '[For Developers] Local Viewpunch' (2916483614)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\1560118657/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\1560118657/gmpublisher.gma' from 'DrGBase | Nextbot Base' (1560118657)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\3235436036/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\3235436036/gmpublisher.gma' from '[DRG]Scene NPC' (3235436036)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2459720887/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2459720887/gmpublisher.gma' from 'Modern Warfare Base' (2459720887)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2459723892/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2459723892/fastgmad.gma' from 'Modern Warfare 2019 SWEPS - Pistols' (2459723892)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2528829149/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2528829149/fastgmad.gma' from 'Modern Warfare 2019 SWEPS - Assault Rifles' (2528829149)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2802430252/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2802430252/fastgmad.gma' from 'Modern Warfare 2019 SWEPS - Submachine Guns' (2802430252)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2751323984/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2751323984/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - Shotguns' (2751323984)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2582142302/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2582142302/gmpublisher.gma' from 'Modern Warfare 2019 SWEPs - Minigun' (2582142302)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2502495789/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2502495789/gmpublisher.gma' from 'M**odern Warfare 2019 SWEPs - G3A3' (2502495789)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2577589751/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2577589751/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - DLC Assault Rifles' (2577589751)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2751325999/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2751325999/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - DLC Shotguns' (2751325999)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2802431672/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2802431672/fastgmad.gma' from 'Modern Warfare 2019 SWEPS - DLC Submachine Guns' (2802431672)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2802427264/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2802427264/gmpublisher.gma' from 'Modern Warfare 2019 SWEPS - Rigs' (2802427264)
**### ** 

Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2864559679/fastgmad.gma' - file doesn't exist

****
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2864559679/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - Marksman Rifles' (2864559679)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2864561323/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2864561323/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - DLC Marksman Rifles' (2864561323)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2873182630/gmpublisher.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2873182630/gmpublisher.gma' from 'Modern Warfare Base - MWII Rigs' (2873182630)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2918635913/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2918635913/fastgmad.gma' from 'Modern Warfare 2019 SWEPs - Sniper Rifles' (2918635913)
Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2960120610/fastgmad.gma' - file doesn't exist
Couldn't mount addon file 'E:\ Steam\steamapps\workshop\content\4000\2960120610/fastgmad.gma' from 'Modern Warfare 2019 SWEPS - Lightmachine Guns' (2960120610)
Failed to read addon file E:\ Steam\steamapps\workshop\content\4000\610653135\316745925528823832_legacy.bin! Does it exist?
Failed to load file for 610653135!

```

**Comment by robotboy655** [comment]
> Not loading addon 'E:\ Steam\steamapps\workshop\content\4000\2802431672/fastgmad.gma' - file doesn't exist

Your Steam client is failing to download the addons. It is very likely a result of you deleting Steam files. Validate your Garry's Mod install through Steam and let it finish, it should restore the files. If it doesn't, contact Steam Support. (https://help.steampowered.com/en/)

This is not a place to get help. You can ask for help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

**Comment by TheSmartieFarty** [comment]
My bad
