### ISSUE TITLE
Default faceposer tool is somewhat broken.

### ISSUE THREAD

**Issue by gabrie155** [Facepunch/garrysmod-issues#5856]
Hard to explain but, it seems that the faceposer tool is somewhat broken when you have a large number of ragdolls, the last slider distorts the face of the models, removing some ragdoll model addons however, fixes this issue.

i have tested this with the normal gmod branch aswell as the x86-x64 branch and yet it still happens, i found many people pointing this out here on the discussion thread here: https://steamcommunity.com/workshop/filedetails/discussion/148090220/4288062617430353889/?tscn=1714970633 (not sure if that helps, but i seen people on here having the same issue)

now im not sure if this is fixable somehow, or this is a source engine limitation, but i just wanted to point this out since i and many people have been experiencing this.

if you want me to upload images of this issue, i will gladly do so.

now i have not enabled the enhanced faceposer tool, just the ragdolls, if anyone is wondering.

**Comment by gabrie155** [comment]
now i have not enable the enhanced faceposer tool, just the ragdolls, if anyone is wondering.

**Comment by robotboy655** [comment]
I am 100% sure this is a duplicate issue, but I can't find it.

I have heard of this before being reported here, but I could not find a way to reproduce the issue on demand. If you manage to do so, it can be looked into.

**Comment by gabrie155** [comment]
@robotboy655 I will gladly reproduce the issue for you, it happens when you have slot of ragdolls for some strange reason, my theory is it happens when you have slot of legacy add-ons (folder add-ons) since I got that bug there, but I'm sure it's because of alot of ragdoll add-ons being installed, I will reproduce this issue in a few days.

**Comment by HiroFuturista** [comment]
![20240510154243_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/a472071e-a413-4964-82d0-8f4e479ba6a9)
![20240510154249_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/98148907-575d-44b1-a698-04cb6b3c7656)
![20240510154257_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/083e26ad-0827-4167-bad1-040b1bffc957)
![20240510154320_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/471d64aa-1081-4bb9-b538-b105f8a21e41)
![20240510154329_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/6a58038d-27c3-45c7-9974-c65fd22ee5bd)
![20240510154400_1](https://github.com/Facepunch/garrysmod-issues/assets/169188927/3980cf51-f5a0-45dc-b5f5-0ad69c5e200d)

My game also had the same problems. Here are some screenshots from the game showing the issue. The photos show what typically happens to ragdolls when this error appears. Some models tend to only work with eye and mouth movements, others are completely inoperable and the last option seems to activate them all at the same time, some are left with just a few options inoperative. (This depends on each different ragdolls mod, but apparently everyone is affected)

**Comment by HiroFuturista** [comment]
I had also recorded some videos showing other characters experiencing the error, but they passed the maximum limit allowed by GitHub. If you need more reproductions, I would be grateful to help.

**Comment by robotboy655** [comment]
I don't need pictures or videos, I need instructions on how to make this happen on my game every time.

**Comment by Cheesyfungoid9** [comment]
For me, it happened when I tried to put sfm models into the addons folder. I've long deleted them, but now, every time I load up the game, this bug happens.

**Comment by HiroFuturista** [comment]
Sorry for the delay, I didn't have time to provide good instructions. Well, I had tried before with the models I was using, but it was taking too long for the ERROR to occur, that's when I remembered that in the past the anime models I used also had this problem quickly, so I decided to install it them again to show the error.
I finally managed to demonstrate how to make the problem appear!

**Comment by HiroFuturista** [comment]
Instructions:
I'm using the default map from Garry's Mod (gm_construct)
I placed 10 models in this order:
1 - Virtual Youtuber - Yuzuki Choco
2 - Virtual Youtuber - Kagura Suzu
3 - Tda - Date A Live - Kurumi Tokisaki
4 - Seishun Buta - Mai Sakurajima
5 - Kancolle - Yamato
6 - Kancolle - Yahagi
7 - Kancolle - Bismarck
8 - Honkai Impact - Raiden Mei Herrscher
9 - Honkai Impact - Durandal
10 - Girlsfrontline-Type95
Note: The sixth character (Kancolle - Yahagi) was added twice, the first time I added the yahagi_player version, then I deleted that one and added the yahagi_ragdoll version.

As I spawned each character I set the "Ah" option to open their mouth.
Okay, when I placed them, the tenth character (Girlsfrontline-Type95) had the problem, some faceposing options didn't work (including the "Ah" option didn't work either) and the last one seemed to activate several of them at the same time!
All characters are in the "Make Animatable" position of the Easy Animation Tool mod.

I also use some mods from outside Steam, and there are 6 of them that always have problems when they are spawned together, if you want to check them I can send them too. But I needed to show the problem with Workshop mods too.
Therefore, all characters used in this test can be found on the Steam Workshop. (I will send the link to each mod used)

**Comment by HiroFuturista** [comment]
Here are the links to the mods used:
1- https://steamcommunity.com/sharedfiles/filedetails/?id=1989336356

2- https://steamcommunity.com/sharedfiles/filedetails/?id=2065756380

3- https://steamcommunity.com/sharedfiles/filedetails/?id=1701555138

4- https://steamcommunity.com/sharedfiles/filedetails/?id=1757257613

5- https://steamcommunity.com/sharedfiles/filedetails/?id=1524779519

6- https://steamcommunity.com/sharedfiles/filedetails/?id=1949419089

7- https://steamcommunity.com/sharedfiles/filedetails/?id=1586210122

8- https://steamcommunity.com/sharedfiles/filedetails/?id=2202042589

9- https://steamcommunity.com/sharedfiles/filedetails/?id=2108475877

10- https://steamcommunity.com/sharedfiles/filedetails/?id=1963515319

Secondary Mods:
Enhanced Faceposer:
https://steamcommunity.com/sharedfiles/filedetails/?id=148090220
Easy Animation Tool:
https://steamcommunity.com/sharedfiles/filedetails/?id=104604709

**Comment by HiroFuturista** [comment]
If you need anything else, I will be willing to help. Thank you for your attention.

**Comment by robotboy655** [comment]
Thanks, I think I know why this is happening now, should be fixed on `x86-64` beta, and in the next update.
