### ISSUE TITLE
Some GMOD props have missing skins

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5858]
A few years back I remember some props having missing textures.
So I decided to manually look through every prop to see if I was correct.
Turns out some props were from HL:S while others had missing skins from Episodic content but nevermind those.

----------------------------------------------------------------------------------------------------
`concrete_barrier00.mdl`
Skin 0:
![concrete_barrier00_good](https://github.com/Facepunch/garrysmod-issues/assets/69215350/09f6889c-ec75-4b5b-a275-4ddad45cbfe4)
Skin 1-9:
![concrete_barrier00_bad](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0d1fcbd6-7424-475b-89c0-d7f416f5493f)

----------------------------------------------------------------------------------------------------
`concrete_barrier01.mdl`
Skin 0:
![concrete_barrier01_good](https://github.com/Facepunch/garrysmod-issues/assets/69215350/dc3d1689-1a49-4974-9ac0-3a16331d866e)
Skin 1-9:
![concrete_barrier01_bad](https://github.com/Facepunch/garrysmod-issues/assets/69215350/91221688-ebd5-4e62-bbe7-7940d38de1f8)

----------------------------------------------------------------------------------------------------
`box_torpedo.mdl`
Skin 0:
![box_torpedo_good](https://github.com/Facepunch/garrysmod-issues/assets/69215350/b7375b54-051f-4b31-b93d-798ed2d05ce9)
Skin 1-4:
![box_torpedo_bad](https://github.com/Facepunch/garrysmod-issues/assets/69215350/6c4e9bd0-7d48-40f7-9162-e51073453bc1)

----------------------------------------------------------------------------------------------------
`box_amraam.mdl`
Skin 0:
![box_amraam_good](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0e9fdd80-d800-4ef3-9e8a-0a472b456011)
Skin 1-4:
![box_amraam_bad](https://github.com/Facepunch/garrysmod-issues/assets/69215350/47750879-73ef-456e-9bbd-e8fd3a4bed45)

----------------------------------------------------------------------------------------------------
[missingskins.zip](https://github.com/Facepunch/garrysmod-issues/files/15259313/missingskins.zip)
^ Map + prop models ( + their materials & decompiled QC file )

**Comment by robotboy655** [comment]
Removed the missing skins.
