### ISSUE TITLE
render.DrawWireframeSphere crash

### ISSUE THREAD

**Issue by ryanoutcome20** [Facepunch/garrysmod-issues#5861]
### Details
The game crashes at an engine level when provided with negative values on [render.DrawWireframeSphere](https://wiki.facepunch.com/gmod/render.DrawWireframeSphere)'s longitudeSteps/latitudeSteps arguments. [This is already fixed on](https://github.com/Facepunch/garrysmod-issues/issues/4845) [render.DrawSphere](https://wiki.facepunch.com/gmod/render.DrawSphere) as it will throw an assert error if you provide it with negative values.

![image](https://github.com/Facepunch/garrysmod-issues/assets/131711662/82070c12-77bb-4d0d-a824-eb1b6fea244a)

### Steps to reproduce
Execute this code (clientside).

```lua
-- Edited Version of Example:
-- https://wiki.facepunch.com/gmod/render.DrawWireframeSphere
local crashMode = true -- TRUE for longitudeSteps; FALSE for latitudeSteps

hook.Add( "PostDrawTranslucentRenderables", "CrashMe", function()
	-- Set the draw material to solid white
	render.SetColorMaterial()

	-- The position to render the sphere at, in this case, the looking position of the local player
	local pos = LocalPlayer():GetEyeTrace().HitPos

	-- Crash our game!
    if crashMode then 
        render.DrawWireframeSphere( pos, 2, -15, 15, color_white )
    else 
        render.DrawWireframeSphere( pos, 2, 15, -15, color_black )
    end
end )
```

**Comment by robotboy655** [comment]
Neither seem to be crashing me on `dev` beta. Can you confirm?

**Comment by ryanoutcome20** [comment]
> Neither seem to be crashing me on `dev` beta. Can you confirm?

![image](https://github.com/Facepunch/garrysmod-issues/assets/131711662/354076d5-87e3-464f-91f1-0df50ce7156f)

Try 64-bit.

**Comment by robotboy655** [comment]
Alright, I have applied the same checks as `render.DrawSphere`.
