### ISSUE TITLE
The game freezes when disconnecting from a map (x86-x64)

### ISSUE THREAD

**Issue by ItsJustMiaouss** [Facepunch/garrysmod-issues#5862]
### Details

When disconnecting from a map downloaded from the workshop, you are redirected to the main menu, but the game remains frozen for about 5 minutes. 

**Branch**: x86-x64 (2024.04.24)
**OS**: Windows 11
**Version**:
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.04.24, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce

1. Download one of the affected maps on workshop (e.g. [gm_boreas](https://steamcommunity.com/sharedfiles/filedetails/?id=1572373847), [gm_drystate2](https://steamcommunity.com/sharedfiles/filedetails/?id=1870721307), [rp_generators](https://steamcommunity.com/sharedfiles/filedetails/?id=2299825726) - this one freezes for 15s only).
2. Join the map.
3. Hit ``Esc`` and press ``Disconnect``.
4. You return to the main menu, but can't click anything for about 5 minutes.

### Important Notes

- Doesn't affect the main branch.
- Only occurs when using a map from the workshop, if manually downloaded and mounted with mount.cfg there's no problem.
- There are any special output in the console.
- I haven't tried on a dedicated server.
- Also affects other players (I told some friends to reproduce the issue).
- Not all maps are affected. Can't find a relation between the bugged ones.
- The CPU seem to work a bit more than usual while freezing (+13% used while freezing on the main screen).

**Comment by robotboy655** [comment]
Thanks. This affected `dev` as well, it should be fixed there, `x86-64` will be fixed when it next updates.
