### ISSUE TITLE
Problems with ep2/VolumeClouds

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/garrysmod-issues#5866]
Dev build

### Details
With the addition of additional parameters for the VolumeClouds shader, the sky portal models on episode two maps are now static, requiring a modified vmt as was done with core_sheet.vmt

models/props_combine/
combine_citadelcloud003.vmt and combine_citadelcloudcenter.vmt

**Comment by robotboy655** [comment]
Will be fixed, thanks for the report and for using the `dev` beta.
