### ISSUE TITLE
point_viewcontrol "trackspeed" keyvalue and "SetTrackSpeed" input doesn't do anything

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#5869]
On 64-bit Branch, Windows
https://developer.valvesoftware.com/wiki/Point_viewcontrol

I'm honestly unsure how to use these and it seems ported from other engines, however, It appears that `trackspeed` keyvalue and `SetTrackSpeed` does nothing or am I doing it wrong?

## Step to Reproduce

Test code:
```lua
function CreateCam()
    local b = ents.Create("prop_physics")
    b:SetName("barrel")
    b:SetModel("models/props_c17/oildrum001.mdl")
    b:SetPos(vector_origin)
    b:SetAngles(angle_zero)
    b:Spawn()
    b:Activate()

    local cm = ents.Create( "point_viewcontrol" )
    cm:SetName("cam")
    cm:SetPos( Entity(1):GetPos() ) -- Just create camera at Player's position or anywhere you want
    cm:SetAngles(angle_zero)
    cm:SetKeyValue("target","barrel")
    cm:SetKeyValue("speed","100")
    cm:SetKeyValue("acceleration","100")
    cm:SetKeyValue("deceleration","100")
    cm:SetKeyValue("trackspeed","500")
    cm:SetKeyValue("spawnflags",tostring(8+16)) --inf hold time & snap to target
    cm:Spawn()

    print("created", cm:EntIndex())
end
```
On Console type:
```
lua_run CreateCam()
ent_fire cam enable
```
Move the `barrel` or launch `barrel` anywhere to let camera follows the target, it appears to track with it's default speed (not from keyvalue)

Changing `ent_fire cam SetTrackSpeed 9999999` or `0` also does nothing

**Comment by robotboy655** [comment]
Looks like there is a bug with how it was transferred to GMod, but it should be fixed on `dev` beta soon.

**Comment by Vinzuerio** [comment]
Alright thanks for the info!
