### ISSUE TITLE
Parsing errors in detail.vbsp.

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#5871]
After last update in the x86-64 branch, any attempt to open a map in Hammer that contains textures with detail sprites, Hammer writes parsing errors in detail.vbsp in the following format:
``KeyValues Error: LoadFromBuffer: missing { in file detail.vbsp``
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 06:17:43 Apr  1 2024 (9246) (4000)
GMod version 2024.05.21, branch: x86-64, multicore: 1
Windows 64bit
```

**Comment by robotboy655** [comment]
Git ruins everything yet again.
