### ISSUE TITLE
Setting model via key values seems to have no effect on SENTs.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#5873]
### Details
It appears that SENTs placed in a map via Hammer don't seem to work when the model is set via the properties, it also doesn't work when the entity is dynamically created and then uses key values to initialize all the properties before calling Spawn. It is possible that other key values are not working as well, without the model it's hard to tell.

### Steps to reproduce
Save as `entities/prop_test.lua`
```lua
local DbgPrint = print

if SERVER then
    AddCSLuaFile()
end

ENT.Base = "base_entity"
ENT.Type = "anim"
DEFINE_BASECLASS("base_entity")

function ENT:Initialize()
    BaseClass.Initialize(self)
end

function ENT:Think()
end

function ENT:KeyValue(key, val)
    DbgPrint(self, "ENT:KeyValue", key, val)
    return BaseClass.KeyValue(self, key, val)
end

if CLIENT then
    function ENT:Draw()
        self:DrawModel()
    end
end
```

Run in console:
`lua_run foo=ents.Create("prop_test") foo:SetKeyValue("model", "models/props_junk/PopCan01a.mdl") foo:SetPos(Entity(1):GetPos()) foo:Spawn()`

**Comment by robotboy655** [comment]
Will be fixed for `anim` type SENTs.
