### ISSUE TITLE
My map started crashing peoples games for no reason.

### ISSUE THREAD

**Issue by skate6788** [Facepunch/garrysmod-issues#5879]
Hi, my map started crashing for peoples, and me for no reason, i wasn't updated since last year.
I am using 64 bit version.

Name of the map ttt_waterworld_tropical

Here are the dump files and the map that crashes:
[https://drive.google.com/drive/folders/1bSMvE1V0kEfqFag-7fmF4bZ6HFAMlTDB?usp=sharing](url)

**Comment by robotboy655** [comment]
Thanks. This is the exact type of bugs recent changes are meant to find.

You have 2 `point_template` entities that reference the same entity multiple times. The fact that it "worked" before is a miracle.
