### ISSUE TITLE
Textures/Materials loaded via GMA's on Workshop are all kinds of busted.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5882]
**Description:**

Loading into Temporal Assassin via Workshop Addons has most of the weapons appear as Wireframe because for some reason the engine is seeing their Shaders as "����" instead of them literally just saying "VertexLitGeneric"

Some VTF's are being marked as non vtfs, even though they clearly are VTFs and work perfectly fine during Legacy Loading.

**I Repeat, Legacy Loading outside of the GMA's is PERFECTLY FINE**

```
*** Tried to load a non-VTF file as a VTF file!
Error reading texture header "materials/temporalassassin/weapons/whisper/whisperofthewormflowmap.vtf"
```

```
KeyValues Error: LoadFromBuffer: missing { in file materials/temporalassassin/weapons/newomen/magazine.vmt
Error: Material "temporalassassin/weapons/newomen/magazine" uses unknown shader "����"
```

```
Error: Material "temporalassassin/weapons/shotgun2/sightfront" uses unknown shader "vmt"
```

For some reason trying to use _Material("TemporalAssassin/Music/"..DIREC.."/"..DIREC..".png")_
DIREC being the folder and sub name of the structure for the music system, Can't seem to find the image at all, Despite it existing in the GMA. It turns into a _Material [___error]_

**How To Replicate:**
1. Sub to https://steamcommunity.com/sharedfiles/filedetails/?id=3258426988 and its required 2 other files.
2. Load into gm_flatgrass, 2 player local server.
3. Witness the trash. Open the console, blah blah blah.

![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/1d066a1f-ce12-46d1-bd0a-b188786c4ad4)
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/41bbbec2-f8b4-4f06-977e-a57787b94dbd)

**Comment by robotboy655** [comment]
The issue is that your textures addon is over 2GB which is the max the game can load at the moment. I will fix the filesystem to be able to load larger files, but will artificially limit the max .gma size to 4GB with a warning in console to be safe.
