### ISSUE TITLE
Disabled Workshop addon files get mounted after a map reload

### ISSUE THREAD

**Issue by Xalalau** [Facepunch/garrysmod-issues#5885]
## Details

Hi. I'm using the normal 32 bits GMod branch under Linux Mint 21.3 and testing everything in a local sandbox game for 2 people.

I'm not sure if this is the intended behavior nor have I found much info about it, but I noticed the files of my older addon release are geting mounted after I reload gm_construct. What bothered me to discover this is that one of my library methods keeps getting overwritten out of nowhere, and when checking the load process I saw that an old folder was being imported. Obviously the problem also disappears when I uninstall the old version of my tool from workshop and deletes my steamapps/workshop/content/4000 folder, so here I am.

After adding some prints to check the loading process, I ended up with the results bellow.

## First run: IsAllowed exists until the end and the tool executes normally

Map Retexturizer v2.0.0 has a [lua/mr/player](https://github.com/Xalalau/Map-Retexturizer/tree/2a1825b239b28ace1730e77598455cbb465614ff/lua/mr) folder with a newer Ply:IsAllowed method. Here it is, loaded:

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/7a1a7def-9c47-4e28-8a43-a18631da1e54)

Checking the existence of the Ply:IsAllowed method during loading:

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/15551ef1-52af-42d1-82df-0d958507c7aa)

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/1c9221e4-2cf3-47e7-85d9-cfe579c7f9c2)

So I can use my tool.

## Second run: IsAllowed gets overwritten by the disabled addon files

Map Retexturizer rev 19 has a [lua/mr/player](https://github.com/Xalalau/Map-Retexturizer/tree/2a1825b239b28ace1730e77598455cbb465614ff/lua/mr) folder with an older Ply:IsAdmin method, which I definitely don't want back. Ply:IsAllowed is what I need. But:

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/5d965ca0-6401-486b-885e-f3deee374154)

Checking the existence of the Ply:IsAllowed method during loading:

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/af1801f4-28ac-4a64-b62f-d003f1e99171)

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/d92e3344-21cf-4df2-8af3-b3abfa18dd17)

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/4d7bb3c4-c887-4a71-b93a-d0ee10b0b2df)

The older addon files got mixed with the newer ones and ended up loaded. My tool is broken.

## Steps to reproduce

1. Have Map Retexturizer from the workshop disabled
2. Place the newer version from GitHub inside the addons folder
3. Launch the game and open gm_construct
4. Change some map materials and save them with the tool menu
5. Reload the map
6. Try to load the saved materials with the tool menu

Error:

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/60b60998-2aca-41af-86df-acbab1e5cd6d)

![image](https://github.com/Facepunch/garrysmod-issues/assets/5098527/c6f1ca89-2543-4e94-98e7-1231c7321148)

## Thoughts

I know that in my case this only affects development, since the conflict is between a workshop addon and a legacy addon. But what happens when a person is subscribed to, for example, a new version of zombie survival (activated) and an old one (deactivated)? This mixture seems explosive, it must generate terrible bugs.

**Comment by robotboy655** [comment]
It is because you add your workshop addon for downloads via `resource.AddWorkshop`, so obviously since you asked the game to mount it, it will mount the addon on server join.

On first join this happens AFTER the server starts so the Lua files are not loaded, but after disconnecting the server mounted addons do not get unloaded (to be fixed), so the Lua files end up being present when the server starts.

**Comment by robotboy655** [comment]
The issue of server addons not unmounting will be fixed on `dev` beta.

**Comment by Xalalau** [comment]
> It is because you add your workshop addon for downloads via `resource.AddWorkshop`, so obviously since you asked the game to mount it, it will mount the addon on server join.
> 
> On first join this happens AFTER the server starts so the Lua files are not loaded, but after disconnecting the server mounted addons do not get unloaded (to be fixed), so the Lua files end up being present when the server starts.

Oh, sure. As I'm doing a rewrite of an old base I totaly forgot to check the resource inclusion, but this gma mounting issue left me very confused. Thanks.
