### ISSUE TITLE
Recent GMod update is causing extreme frame hitching when the Crystal Rifle in TA is fired.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5887]
**This was not a problem before the update happened about 3 hours ago.**

How to Reproduce:
1. Get into Temporal Assassin.
2. TA_DEV_DeveloperMode 1
3. Hold F1 and goto NPCs > Temporal Assassin
4. Spawn a TEC-U Heavy
5. Let him charge up and shoot his gun
6. Wow, really big lag that never used to happen

https://steamcommunity.com/sharedfiles/filedetails/?id=3258426988

**Comment by MagentaIris** [comment]
Gonna add on another comment here, Changing the model of the crystal rifle projectile from `"models/temporalassassin/projectiles/crystalrifle.mdl"` to anything else seems to fix this.

However why in the world a GMod update would magically make my model lag like crazy whenever it is initialized or spawned is beyond me.

**Comment by robotboy655** [comment]
This is because you are calling Entity:Activate() clientside on some entity, which will now scale the physics meshes if you use SetModelScale on the entity, as part of a fix for https://github.com/Facepunch/garrysmod-issues/issues/5867

**Comment by MagentaIris** [comment]
Hilarious.

Alright, Got it.
