### ISSUE TITLE
32-bit clientside code issue

### ISSUE THREAD

**Issue by Batrexus** [Facepunch/garrysmod-issues#5888]
Hello!

Server: x86-64 branch linux

From today we are experiencing players having an issue with clientside code broken on **32bit branch**. When they join a server they get a hundreds of lua errors, most of them showing that global functions from **includes/util.lua** are missing. This is what I've found:

```
[ERROR] lua/includes/util.lua:13: attempt to call global 'RegisterMetaTable' (a nil value)
  1. __newindex - lua/includes/util.lua:13
   2. unknown - lua/includes/util/color.lua:9
    3. include - [C]:-1
     4. unknown - lua/includes/util.lua:73
      5. include - [C]:-1
       6. unknown - lua/includes/init.lua:251


[ERROR] lua/includes/util.lua:174: attempt to call global 'Color' (a nil value)
  1. unknown - lua/includes/util.lua:174
   2. include - [C]:-1
    3. unknown - lua/includes/init.lua:251
```

I see this lines named after 

> Hack for debug.getregistry

 were added on 64-bit branch, but they are missing on 32-bit. I must be clear that **server is on 64-bit** branch, but **client is on 32-bit** branch. I am assuming it's happening because serverside lua code is overwriting clientside one.

**Comment by robotboy655** [comment]
This should already be fixed, update your server.
