### ISSUE TITLE
Some Lua Panics have no description and only show number

### ISSUE THREAD

**Issue by SolsticeSpectrum** [Facepunch/garrysmod-issues#5890]
### Details
I work on experimental addon and for some reason, for two people it causes lua panics but there is nothing useful that could be used to determined what's wrong. This window should usually display some sort of error message like "not enough memory" or "attempt to call a number value" or "failed to lock index buffer". However in this case it just shows number "7" and sometimes rarely it shows "8" or "28".
Nobody in the community knows what does it mean when it shows a number. My guess is that some dev just didn't bother coming up with proper error messages for some edge cases they thought could never happen and if they do happens somehow, they can just search for like `print(7)` and figure out where it failed.
![image](https://github.com/Facepunch/garrysmod-issues/assets/38611351/92879f7d-88b0-4b33-a1ed-fc2c01fbf180)
I think only Facepunch dev with access to the codebase can tell what number "7" represents.

Anyway my suggestion is to put actual error messages in place of these non descriptive numbers if that's the case and maybe there should be more logging with Lua Panics, like at least it should show entire stack trace so it can be pinpointed what the problem is. We tried `-debug` and `-consolebug` launch options but the corresponding log files are not created with this case.

The only stacktrace it shows is this on the client bound `(null) - lua/includes/modules/hook.lua:-1`. How is it line -1 is beyond me.

**I sent the crash dump to robotboy over email**

### Steps to reproduce
I don't know because it only happens for 2 people using the addon

**Comment by robotboy655** [comment]
What is the addon?
Does the issue happen on `NONE` beta for those 2 people?
How often does the issue happen?
What are they doing exactly when this happens?

The Lua Panic messages are generated by Lua(JIT). There's not really a way to know what is happening without at least a reproduction method.

The one thing I can say from the dump, is that it was about to call GM:Think or Tick clientside.

**Comment by SolsticeSpectrum** [comment]
@robotboy655 It happens on x64 branch, it always throws this. What we also discovered is that the number changes based on which map is started. Construct is 7 and then other maps are 9 or 29. The addon is something like gwater, it also uses FleX for fluid simulation. Anyway it happens always, it will always crash if the addon is present. What we also figured out that the crash log always says something different. I feel like the game just thinks it crashes on some line but it actually just paniced while going over that line so the crash log doesn't really say anything useful. 

As what they are doing, it always happens when entering the world. It crashes on the loading screen basically.

Here is a crash dump with all addons disabled, the one I sent had all addons enabled but it doesn't have effect on the result, it still crashes:
[5c1064bf-0663-44bc-a7a2-9e7f99708d62.dmp](https://github.com/user-attachments/files/15672292/5c1064bf-0663-44bc-a7a2-9e7f99708d62.dmp)

Is it still about to call GM:Think or Tick?

Anyway as I said here are some crash logs it says but it seems to always be different so I think my hypothesis is true.
```
  Client
    0. GetNetworkVars - lua/includes/extensions/entity.lua:-1
      1. bind - lua/matproxy/sky_paint.lua:13
        2. (null) - lua/includes/modules/matproxy.lua:56
        
  Client
    0. GetTable - [C]:-1
      1. __index - lua/includes/extensions/player.lua:28
        2. v - lua/autorun/simfphys_gazelle_towtruck_sounds.lua:94
          3. (null) - lua/includes/modules/hook.lua:96
          
  Client
    0. (null) - lua/includes/modules/hook.lua:-1
```
It just always panics on different line. The null one is with all addons disabled.

**Comment by SolsticeSpectrum** [comment]
@robotboy655 We are now 100% sure that construct is 7 and flat grass is 8, other maps throw other numbers. I have no idea why but this is uniform. Construct is always 7 and flat grass always 8.

**Comment by robotboy655** [comment]
Does it happen on `NONE` beta?

**Comment by SolsticeSpectrum** [comment]
@robotboy655 the addon doesn't run on none beta, it's 64 bit only, it used the 64 bit flex

**Comment by yogwoggf** [comment]
> Does it happen on `NONE` beta?

This is my (mod)[https://github.com/yogwoggf/gelly], and it's important to know that this is a project that uses binary modules--and such errors happen once my binary module is loaded. You can close this as invalid because in all honesty it must be some oversight with my code that is causing a Lua Panic.

However, it'd be helpful if LuaJIT could print more information if possible--it's a highly difficult error I'm tackling since it is unpredictable and only happens on some machines

**Comment by yogwoggf** [comment]
One of my users captured a very nice stack trace if it helps, I bolded the most important parts, but kept the bit where you can see the stack is clean. Maybe you can shed some light on it, @robotboy655 ?

The function that we got the lua panic on takes 0 arguments and returns nothing (gelly_Composite__Imp).
It's worth noting that it happens with some other random functions, but usually this one. All are simple and don't return anything, nor do they push anything onto the stack.

```
06/06/24 21:53:51 - [INFO @ gelly_Composite__Imp]: Ending gelly_Composite__Imp
06/06/24 21:53:51 - [INFO @ DumpLuaStack]: Stack dump (gelly_Composite__Imp end):
06/06/24 21:53:51 - [INFO @ DumpLuaStack]: Stack size: 0
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Unknown exception detected! (Code: 1073807370)
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Exception address: 0x00007FF89F17BA99
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Exception flags: 0x00000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Parameter 0: 0x0000000000000030
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Parameter 1: 0x0000009979D79E80
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Parameter 2: 0x0000000000000030
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Parameter 3: 0x00000269BDD77C10
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: RIP: 0x00007FF89F17BA99
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Scene is still uncorrupted!
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Active particles: 0
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Max particles: 100000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Compute device at time of crash: NVIDIA GeForce GTX 970
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Compositor is still uncorrupted!
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Cubemap strength: 1.000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Particle radius: 2.500000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Threshold ratio: 0.144000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Diffuse motion blur: 25.000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Diffuse scale: 0.000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Filter iterations: 2.000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Thickness iterations: 13.000000
06/06/24 21:53:51 - [ERROR @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Refraction strength: 0.030000
06/06/24 21:53:52 - [INFO @ SaveLogInEmergency]: EMERGENCY EXCEPTION HANDLER: Symbol path: D:\Steam\steamapps\common\GarrysMod\garrysmod\lua\bin
```
# Stack trace log entry
```
06/06/24 21:53:52 - [INFO @ SaveLogInEmergency]: Stack trace: 
Stacktrace at 0x7ff8a16e26b1
> RtlUserThreadStart
> BaseThreadInitThunk
> DestroyCefSandboxInfo
> DestroyCefSandboxInfo
> LauncherMain
> Dump_CallWinMainFunction
> VoidFnPtrLookup_Tier0
> Unknown Symbol
> LauncherMain
> LauncherMain
> GMOD_GetNetSocket
> F
> F
> F
> F
> CBaseServer::RecalculateTags
> CBaseServer::RecalculateTags
> CBaseClientState::ConnectionStart
> CBaseClientState::ConnectionStart
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> CBaseClientState::ConnectionStart
> CBaseClientState::ConnectionStart
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> Unknown Symbol
> AdvancedLuaErrorReporter
> AdvancedLuaErrorReporter
> AdvancedLuaErrorReporter
> lua_pcall
> Unknown Symbol
> luaL_unref
> lua_sethook
> Unknown Symbol
> lua_sethook
> luaopen_jit
> lua_sethook
> lua_newstate
> AdvancedLuaErrorReporter
> Error
> Dump_RemoveCallback
> GMOD_GetNetSocket
> GMOD_GetNetSocket
> GMOD_GetNetSocket
> GMOD_GetNetSocket
> OutputDebugStringW
> RaiseException
End of stack trace
```

**Comment by robotboy655** [comment]
This number crash happens on my end as well, but on my local build it crashes in a different place - on the DLL load. With this:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/6f4534d2-1e93-4230-84b6-b560dc47decc)

Which is definitely not a standard message of LuaJIT, so I wouldn't be surprised if those unhelpful messages come from your own DLL as well. The "7" is just what was at the top of the Lua stack at the moment of the crash, forced to a string. It crashes when trying to run hooks, so I imagine the number differs based on what hook happened to be ran at/after the point it all goes to shit.

In my testing it crashes even when not running any of your Lua code, just by loading the DLL it will crash, this leads me to believe something wrong with the DLL init, not any specific function it adds.

The numbers could be a typeID of an argument, https://wiki.facepunch.com/gmod/Enums/TYPE

```
  /*
  ** A return from this function signals a corrupt C stack that cannot be
  ** unwound. We have no choice but to call the panic function and exit.
  **
  ** Usually this is caused by a C function without unwind information.
  ** This should never happen on x64, but may happen if you've manually
  ** enabled LUAJIT_UNWIND_EXTERNAL and forgot to recompile *every*
  ** non-C++ file with -funwind-tables.
  */
```
I found this at the place JIT panics.

**Comment by yogwoggf** [comment]
> This number crash happens on my end as well, but on my local build it crashes in a different place - on the DLL load. With this: ![image](https://private-user-images.githubusercontent.com/3299036/337717284-6f4534d2-1e93-4230-84b6-b560dc47decc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Nzg4NjAsIm5iZiI6MTcxNzc3ODU2MCwicGF0aCI6Ii8zMjk5MDM2LzMzNzcxNzI4NC02ZjQ1MzRkMi0xZTkzLTQyMzAtODRiNi1iNTYwZGM0N2RlY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTY0MjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgzMWRlOTFiZjUwNjI5NTdlOGIyODJjYjY2Zjg5ZDA1OTQ2ZWIyYWYzOWYwOTk1OGJhNTg4Mjg2YTg2Yjc3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kRxIh-3CS6DZP3EbZiT0LAH1Jl9Ge_FROK2E8P4FM0w)
> 
> The "7" is just what was at the top of the Lua stack at the moment of the crash, forced to a string. It crashes when trying to run hooks, so I imagine the number differs based on what hook happened to be ran at/after the point it all goes to shit.
> 
> In my testing it crashes even when not running any of your Lua code, just by loading the DLL it will crash, this leads me to believe something wrong with the DLL init, not any specific function it adds.
> 
> The numbers could be a typeID of an argument, https://wiki.facepunch.com/gmod/Enums/TYPE
> 
> ```
>   /*
>   ** A return from this function signals a corrupt C stack that cannot be
>   ** unwound. We have no choice but to call the panic function and exit.
>   **
>   ** Usually this is caused by a C function without unwind information.
>   ** This should never happen on x64, but may happen if you've manually
>   ** enabled LUAJIT_UNWIND_EXTERNAL and forgot to recompile *every*
>   ** non-C++ file with -funwind-tables.
>   */
> ```
> 
> I found this at the place JIT panics.

Thanks, this is a good place to start--I had a feeling it would be something relating to the stack, I knew someone who wrote Lua interop in Rust and couldn't make it work until Rust came out with a new ABI that added stack unwinding support.

I'll take a look at my compilation options and other things, but this is a huge help, thanks.

**Comment by robotboy655** [comment]
The number could be related to a `TraceError` ID, it could be one of these:
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_traceerr.h

I imagine they are in sequential order, starting with 0, but not sure how useful this is.

**Comment by yogwoggf** [comment]
I'll poke around more in a debugger, but the hardest part is how machine-specific this issue is. Can you tell me what CPU model you ran your local build on? We're not too sure, but we are noticing Intel CPUs have this issue far more than AMD CPUs.

**Comment by Derpius** [comment]
Specifically, we're concerned he's stack allocating more than certain CPUs allow

**Comment by robotboy655** [comment]
I have 5900x/32GB ram/4070Ti, the issue happens on my end.

**Comment by yogwoggf** [comment]
> The number could be related to a `TraceError` ID, it could be one of these: https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_traceerr.h
> 
> I imagine they are in sequential order, starting with 0, but not sure how useful this is.

Alright, turns out it was my binary module--not really anything to do with LuaJIT (obviously, this was asserted before). Basically, LuaJIT produces exception raising/handling code during native code generation and because of this, I was indirectly fucking up LuaJIT's stack (and who knows what else) by returning `EXCEPTION_CONTINUE_EXECUTION` in my custom app-wide exception handler instead of `EXCEPTION_CONTINUE_SEARCH`, essentially breaking any assumptions/invariants LuaJIT's native code held while waiting for its exception handler to be called. Oops..

**Comment by yogwoggf** [comment]
@SolsticeSpectrum Go ahead and close the issue

**Comment by SolsticeSpectrum** [comment]
Closing, since this has been solved. It's not a problem with the game itself as they have been doing something with the engine that the engine didn't like.
