### ISSUE TITLE
Fix for NPC Death Animations During Run/Idle Transition

### ISSUE THREAD

**Issue by epicplayer40** [Facepunch/garrysmod-issues#5891]
### Details

If the model of a vanilla (HL2, HL Source etc) NPC does not contain a ragdoll, the NPC code will default to trying to play a death animation. 

However, this death animation can sometimes have strange interpolation issues if it is triggered while an NPC is blending between their walking/running animation and standing idle (the locomotion effect where the NPC accelerates/decelerates), causing the death anim to incorrectly play with the final resting position combining both the death animation and idle animation.

This is a bug that is in default HL2 and is also present in every current branch of Gmod.

This can be fixed by modifying game/server/ai_basenpc.cpp's "CAI_BaseNPC::Event_Killed" function:
In between `CleanupOnDeath( info.GetAttacker() );` and `StopLoopingSounds();`, add in `GetMotor()->MoveStop();`
After doing this, NPCs can play death animations properly and this blending bug can no longer occur.

### Steps to reproduce

1. Spawn a HL2 or HL Source NPC with a custom model that does NOT have a ragdoll, but has activities for ACT_DIESIMPLE etc so it can trigger death animations.
2. Kill the NPC as it begins walking/running from idle, or when slowing down and reaching it's destination.

**Comment by robotboy655** [comment]
Related to https://github.com/Facepunch/garrysmod-issues/issues/5361?

**Comment by BREEDNKMs** [comment]
here's the [example video](https://www.youtube.com/watch?v=aJvT1qzEjDQ)

this can be performed on a cycler_actor with model models/player.mdl, npc_select, npc_go and npc_kill commands. 

calling StopMoving() in Event_Killed will not be enough because the same problem also occurs in SNPCs but they never call OnTakeDamage_Alive(), OnKilled() and Event_Killed().

**Comment by robotboy655** [comment]
Alright, I have applied the proposed fix, it seems to work with the `cycler_actor` example. Since you have not provided any other examples, I am considering this resolved.
