### ISSUE TITLE
Latest x64 branch deletes .gma files that are installed locally

### ISSUE THREAD

**Issue by rtandbk** [Facepunch/garrysmod-issues#5893]
Details
GMod version 2024.06.06, branch: x86-64, multicore: 1
No other addons subscribed to or installed into gmod locally.
Fresh reinstall

Steps to reproduce
1. Switch to x64 beta branch
2. Install locally a .gma file
3. Launch gmod x64. 
4. Addon has now been moved/deleted from the addons folder.

![image](https://github.com/Facepunch/garrysmod-issues/assets/19803636/3af17e52-2e9f-42e1-bc9b-f2659a23ecfe)

![image](https://github.com/Facepunch/garrysmod-issues/assets/19803636/13278046-e44d-45e3-804a-9ff3d4751879)

**Comment by yogwoggf** [comment]
Got this too, horribly affects the UX of my installation process

**Comment by robotboy655** [comment]
1) It doesn't delete them, it moves them to `cache/workshop/id.gma`
2) Locally installed .gma addons must be placed anywhere except in the `addons/` folder, or inside a folder in `addons/`, as they would just be ignored in `addons/` on all versions of the game. This was always the case.
