### ISSUE TITLE
Players in vehicle have the wrong rotation reported

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#5894]
After some testing and being slightly annoyed to how players die in vehicles I started digging, it appears that the bone positions reported on the server while the player is in a vehicle are offset/rotated, on the client it has the correct positions. I've tested this on dev but I'm guessing it is the same on all the other branches.

The code to show the bone position:
```lua
function ShowPlayerBones(ply)
    local color = Color(255, 0, 0, 255)
    if CLIENT then
        color = Color(0, 255, 0, 255)
    end
    for i = 0, ply:GetBoneCount() - 1 do
        local pos, ang = ply:GetBonePosition(i)
        debugoverlay.BoxAngles(pos, Vector(-1, -1, -1), Vector(1, 1, 1), ang, 10, color)
    end
end
```
Server:
![hl2_2024-06-08_00-56-299a5c97ad3919b0524](https://github.com/Facepunch/garrysmod-issues/assets/5415177/6271a6b7-bde6-4f71-854d-1c4f127ec91c)

Client:
![hl2_2024-06-08_00-58-52859266aa31d4aae65](https://github.com/Facepunch/garrysmod-issues/assets/5415177/5b9d3d65-6a69-4884-b30f-99a547f8ebb3)

A work-around I've found is by manually rotating the positions by 85 on y.
```lua
function ShowPlayerBonesCorrected(ply)
    local color = Color(255, 0, 0, 255)
    if CLIENT then
        color = Color(0, 255, 0, 255)
    end
    
    local rotation = Angle(0, 0, 0)
    if SERVER then
        rotation = Angle(0, 85, 0)
    end
    local centralPos = ply:GetPos()
    for i = 0, ply:GetBoneCount() - 1 do
        local pos, ang = ply:GetBonePosition(i)
        if pos and ang then
            local relativePos = pos - centralPos
            relativePos:Rotate(rotation)
            pos = centralPos + relativePos

            ang = ang + rotation
            
            debugoverlay.BoxAngles(pos, Vector(-1, -1, -1), Vector(1, 1, 1), ang, 10, color)
        end
    end
end
```

![hl2_2024-06-08_01-15-08cf67b0f0fd228c670](https://github.com/Facepunch/garrysmod-issues/assets/5415177/228d5707-3aa1-497b-a64b-e4baf1e40176)

**Comment by robotboy655** [comment]
I think I mostly fixed it on `x86-64`. I couldn't find what code sets it on client, but I think it should be close if not perfect now.
