### ISSUE TITLE
Insight Into .dmp File (Related to Shaders)

### ISSUE THREAD

**Issue by meetric1** [Facepunch/garrysmod-issues#5896]
### Details
I am developing a mod which uses a binary module to add custom shaders into the game. It loads the shadersystem interface and adds a few shader instances into the CShaderSystem.

Base code: `s_ShaderSystem->m_ShaderDLLS[0].m_ShaderDict.Insert("ShaderName", &ShaderInstance);`

This works fine until loading and disconnecting from a game two times, and an unrelated crash happens in tier0.dll, which I am unable to debug.
The crash started happening on the x64-86 branch a few days ago (after the edit to the materialsystem and shadersystem dlls). In the past I have never experienced this problem. The crash does not occur on the main branch.

Older versions of the mod which I *know* did not have this issue, now experience the crash.

Some insight into why the crash is happening would be much appreciated! Here is the .dmp file:
[ec6d6c7e-a7c2-4934-95d6-93e46813fdf1.dmp](https://github.com/user-attachments/files/15753481/ec6d6c7e-a7c2-4934-95d6-93e46813fdf1.dmp)

### Steps to reproduce
N/A

**Comment by meetric1** [comment]
@robotboy655 The crash only happens with my DLL.

 `gmod_mcore_test 0` seems to have fixed the issue. I am locking the materialsystem though so I'm unsure what the issue is.

**Comment by meetric1** [comment]
seems to be fixed as of this commit. Thanks!

https://commits.facepunch.com/483573

**Comment by robotboy655** [comment]
Interesting, thanks for the info.
