### ISSUE TITLE
[Dev] Clientside physics object oddities

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-issues#5898]
### Details
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:21:31 Jun  6 2024 (9340) (4000)
GMod version 2024.06.07, branch: dev, multicore: 1
Windows 32bit
```

While playing around with the new clientside physics object support in **singleplayer** I've ran into some issues.

- Using `self:PhysWake()` with a frozen prop causes the clientside physics object to sink to the floor through props at a rate dependent on your framerate (e.g. tabbing out causes it to happen faster)
- On spawning the entity the serverside physics object is set to incorrect angles. This can be fixed with PhysWake, forcing the clientside physics object to snap to the same angle though this means SetAngles won't work correctly when spawning the entity (e.g. through `base_anim`'s SpawnFunction)
```lua
this:GetPhysicsObject():GetAngles()
    -- 0x88cc8de2
    Angle(0, -36.474609, 360)
    [SERVER] -- 0xd9caaee2
    Angle(0, 0, 360)
```
- Collisions don't work correctly on a frozen entity, based on some testing it's as if the collision bounds for the entity reset themselves to an angle of 0,0,0. This is especially noticeable if you place one of the corners facing up and try to stand on said corner as you'll clip partially through and may be pushed out depending on where exactly you stand.

### Reproduction code
```lua
AddCSLuaFile()

ENT.Type = "anim"
ENT.Spawnable = true

ENT.Mins = Vector(-16, -16, -16)
ENT.Maxs = Vector(16, 16, 16)

function ENT:Initialize()
	self:SetModel("models/props_lab/cactus.mdl")
	self:PhysicsInitBox(self.Mins, self.Maxs)
end

function ENT:Think()
	self:PhysWake()
	self:NextThink(CurTime())

	return true
end

if CLIENT then
	local color = Color(255, 191, 0)

	function ENT:Draw()
		self:DrawModel()

		render.DrawWireframeBox(self:GetPos(), self:GetAngles(), self.Mins, self.Maxs, color, true)
	end
end
```

**Comment by robotboy655** [comment]
You cannot have physics simulation clientside on a shared entity. That just not going to work, and its not logical. Ideally you'd call `self:GetPhysicsObject():MakeShadow()` clientside for such cases. I have improved the sinking issue a bit for the code you provided, but it will never work perfectly unless you call the aforementioned function, which will disable gravity and stuff.

I don't know how the other issues come into play here, there were no serverside changes at all in regards to this. Rubbing a cinderblock prop around the entity does not show any inconsistencies with the serverside collisions and the visual representation your entity renders.

**Comment by TankNut** [comment]
I've done a bit more testing and the sinking issue can be avoided by just not calling PhysWake on the client at all. The other two issues still occur in some form though, the collision issue specifically seems to only apply to players?

I've attached a video showing both issues.

https://github.com/Facepunch/garrysmod-issues/assets/1381265/f7af7703-40f3-4696-91d2-28bbcf1ff769

**Comment by TankNut** [comment]
Side note, seems that forcing `self:SetSolid(SOLID_VPHYSICS)` after initializing physics fixes the issues
