### ISSUE TITLE
Steam auth ticket has been canceled crashes. 

### ISSUE THREAD

**Issue by sam6321** [Facepunch/garrysmod-issues#590]
I've been getting these crashes a lot recently, either randomly during a game or when attempting to connect to a server. 
I'll load in perfectly fine before simply crashing to the desktop, no dump files are written either. Other clients on the servers I attempt to join tell me that my disconnect message is 

Player *Sam left the game (Client left game (Steam auth ticket has been canceled))

Sometimes I'll be able to get into a server for a few seconds before the game closes, other times it'll close immediately on loading in.
I should also note, there's no "hl2.exe has stopped working" error message, the program literally just closes straight to my desktop (in the same way it would if I used the "quit" command in console) 

I did a bit of googling and found that there are other people reporting this issue for other source games, however I only appear to have it with Garry's Mod.
Any help would be appreciated.

**Comment by Donkie** [comment]
This keeps happening on my servers, where all clients get disconnected at the same time with the reason: "Steam auth ticket has been canceled".

People are able to rejoin just fine afterwards.

If there's any way to debug this I'll gladly help.

**Comment by Donkie** [comment]
Could we have some light shed on this? What is it that's happening? I'm having roughly 2000 players a week getting disconnected and progress lost because of this issue.

**Comment by chelog** [comment]
It happened for me sometimes before current update (22.02.2016). Now it's a constant thing. Game is ALWAYS crashing. I can't play anymore. My friend and some more people (see screen below) started experiencing this after latest update.

[SCREENSHOT](http://i.imgur.com/6BQCCCs.png)

**Comment by Donkie** [comment]
Could add that my servers are hosted on Linux Ubuntu

**Comment by chelog** [comment]
Same as @Donkie

**Comment by willox** [comment]
I believe I've found the cause. There'll be a fix out by tonight.

**Comment by Donkie** [comment]
:heart:

**Comment by robotboy655** [comment]
The fix is for Linux crashing, not for the ```Steam auth ticket has been canceled``` crashes in general.

The message ```Steam auth ticket has been canceled``` is just a weird reaction to the client crashing, the actual crash reason could be anything. If you know of any way to reproduce these crash(es), please do report.

**Comment by kkl1974** [comment]
I am getting this as well, removed steam + GMod completely, still getting it
