### ISSUE TITLE
Players in the same team can shove each other.

### ISSUE THREAD

**Issue by oninoni** [Facepunch/garrysmod-issues#5900]
### Details
When 2 players are in the same team, they can shove each other around.
This does not happen, when they are in different teams.
There is no control over this functionality that i can find.

It is especially bad, if one of the players has no collision enabled (For example when in an administration mode)
It would be great to be able to disable this shoving of teammates.
Right now it is just a bit inconsistent.

### Steps to reproduce
It is fairly easy to reproduce, however the effect is a bit hard to see sometimes.
Easiest is to set one player's collision group to "COLLISION_GROUP_DEBRIS" and then noclip into a second player that is in the same team.
In Sandbox, all players are in the same team by default.

**Comment by robotboy655** [comment]
This should control what you are talking about as far as I can tell.

https://wiki.facepunch.com/gmod/Player:SetAvoidPlayers

**Comment by robotboy655** [comment]
There's also this:
https://wiki.facepunch.com/gmod/Player:SetNoCollideWithTeammates

**Comment by oninoni** [comment]
Yes you are right.

It is still weird that https://wiki.facepunch.com/gmod/Player:SetAvoidPlayers only applies to people in the same team?

Thank you
