### ISSUE TITLE
'Keep Corpses' fails to keep corpses

### ISSUE THREAD

**Issue by LeodisHodis** [Facepunch/garrysmod-issues#5904]
Following a recent update, NPC corpses have started to disappear a few minutes after they die, despite Keep Corpses being enabled in the menu. Also, the Keep Corpses setting itself is often disabled when a map is first started, even if it was enabled in a previous session. The issue doesn't look to be related to any addon, and is present on both the base and x86-64 branches.

(Here's the game version, btw)
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:26:45 Jun  6 2024 (9341) (4000)
GMod version 2024.06.14, branch: x86-64, multicore: 1
Windows 64bit

**Comment by robotboy655** [comment]
To be clear, just to make sure, I have tried waiting 15 minutes on a map with dead NPCs with keep corpses, and predictably they did not disappear.
