### ISSUE TITLE
NPCs break when going through a trigger_changelevel.

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#5906]
When custom maps are made with trigger_changelevel with the intent to make the player go to the next map, NPCs AI will shut down when the player loads into the map. If the player loads into the map directly, the NPCs work just fine.

For some reason, this issue isn't present in officially supported games such as the Half-Life series. So it is entirely possible the problem is on my end. If it is then please tell me how to solve it. I was using the x86-64 - Chromium +64-bit binaries branch when I discovered this. The glitch is also present in the dev branch.

Steps to reproduce:
1. Create two maps with trigger_changelevel, info_landmark, trigger_transition, and various NPCs of your choice.
2. Run the two maps and observe how NPCs work fine when loading in one of the maps directly but will become inactive when going to the next map via trigger_changelevel

Video provided:
https://youtu.be/3T-EDmoDlI8

**Comment by TheBillinator3000** [comment]
[test maps.zip](https://github.com/user-attachments/files/15874115/test.maps.zip)

Here you go.

**Comment by TheBillinator3000** [comment]
If you need it, here are the test maps with Half-Life 2 NPCs only.

[test maps with hl2 npcs only.zip](https://github.com/user-attachments/files/15879034/test.maps.with.hl2.npcs.only.zip)

I even removed the npc_furniture to make it more serious.

**Comment by robotboy655** [comment]
This happens because your map does not have nodes at all  (No .ain file for the map changelevel-ing to), specifically when loading a game during changelevel. Without nodes the AI is forcibly disabled in this scenario.

You will get this error when this happens:
```
***
ERROR: Loaded save game with no node graph. Load map and build node graph first!
***
```

**Comment by TheBillinator3000** [comment]
Thank you.

**Comment by TheBillinator3000** [comment]
Tested it and it's working so far. Thank you so much!
