### ISSUE TITLE
Weird default cubemap behaviour

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-issues#5909]
### Details
Default HDR cubemaps glow with the force of a thousand suns.
![20240617160437_1](https://github.com/Facepunch/garrysmod-issues/assets/64710817/f3e4f69c-759f-4b2d-bc22-1305f1fec342)
![20240617155654_1](https://github.com/Facepunch/garrysmod-issues/assets/64710817/d6aba230-57d2-4820-a089-405fbb55fa72)

### Steps to reproduce
Branch doesn't seem to matter, happens on both the base, and x86/x64 branch.
I'm using a GTX 1060, with an AMD cpu, just in case this is somehow a hardware issue.

1. Enable HDR, with mat_specular 1
2. Load into a map with the issue.
This map works well https://steamcommunity.com/sharedfiles/filedetails/?id=1324502544
3. See the issue everywhere.

**Comment by robotboy655** [comment]
This is only a problem on maps renamed after compilation, but I have replaced the default cubemap texture with the placeholder one that VBSP generates on map compile by default, which is just pitch black.
