### ISSUE TITLE
Crash after using game.CleanUpMap and going to a specific location in a map

### ISSUE THREAD

**Issue by Lazyneer** [Facepunch/garrysmod-issues#5910]
### Details
The game crashes after game.CleanUpMap has been used and then going to a specific location in the map. The map hasn't changed and it wasn't a problem before. I don't know when it became a problem.
The two locations that cause the crash both have a func_tracktrain, but other maps with that entity don't crash.

The map it crashes on: [ow_citadel.zip](https://github.com/user-attachments/files/15892966/ow_citadel.zip)
Crash dump: [hl2_240321_crash_2024_6_18T21_12_51C0.zip](https://github.com/user-attachments/files/15892965/hl2_240321_crash_2024_6_18T21_12_51C0.zip)

### Steps to reproduce
- Load the map ow_citadel
- lua_run game.CleanUpMap()
- sv_cheats 1
- setpos 943 1976 -1971

**Comment by robotboy655** [comment]
Your map has env_soundscape_proxy parented to an entity. It is being deleted on map cleanup. I will see if I can make soundscape entities automatically unparent from everything.

**Comment by robotboy655** [comment]
The crash is fixed on `x86-64` beta, I will let you deal with the permanent removal of the soundscape entity on map cleanup.
