### ISSUE TITLE
The game wont let you change gamemode on x86-x64 version

### ISSUE THREAD

**Issue by dizaXD** [Facepunch/garrysmod-issues#5912]
If i load up a map in sandbox and then quit to mainmenu then switch gamemode to other  and load the map again its gonna be sandbox gamemode again.This happens not only to me but also to other people.I have 0 addons, I reinstalled the game, verified the game files and did a factory reset of gmod and it still happens. ONLY ON x86 VERSION OF THE GAME. Its starts happening after 2024.06.18    x86 update

**Comment by robotboy655** [comment]
Will be fixed when it next updates, thanks for the report.
