### ISSUE TITLE
Crash after removing (active?) env_soundscape entity

### ISSUE THREAD

**Issue by Def-Try** [Facepunch/garrysmod-issues#5913]
### Details
A crash is caused by removing (active?) env_soundscape entity.
Using main branch with latest version
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:00:21 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: unknown, multicore: 0
Windows 32bit
```
https://github.com/Facepunch/garrysmod-issues/assets/71168720/617f3ab5-642c-4635-b45d-1f4b61b86089
https://github.com/Facepunch/garrysmod-issues/assets/71168720/295c9397-b770-45c1-9a1a-c5397cb2734d

### Steps to reproduce
1. `lua_run PrintTable(ents.FindInCone(Entity(1):EyePos(), Entity(1):GetAimVector(), 1000, math.cos(math.rad(30))))`
2. Find any env_soundscape entity
3. If there isn't, go to another location and try again from step 1.
4. Try to remove it, e.g. for Entity[8][env_soundscape] run `lua_run Entity(8):Remove()`

**Comment by robotboy655** [comment]
I just fixed a bug with deleting soundscapes on `x86-64`, please try it and see if the issue is fixed there.

**Comment by Def-Try** [comment]
Doesn't crash on `x86-64`, so yeah the issue is fixed
