### ISSUE TITLE
Un-Reported change to player death? Cannot replicate old behaviour.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5914]
When not giving the player a ragdoll to view from, The player would still have their position and camera attached to the Origin of their player entity. (Which would still fly out in the direction they are moving before hitting the ground. Movement keys still moved the player awkwardly.)

I can no longer replicate this effect (Which is something I actually WANT)

I've tried everything so far and all I seem to do is float mid-air, constantly gaining downwards velocity with the inability to replicate this old effect.

I cannot find any changes in any commits anywhere that notify this was changed, nor how to revert it manually.

**Comment by homonovus** [comment]
https://commits.facepunch.com/469230
the change is listed here in a commit from January

**Comment by MagentaIris** [comment]
> What do you want this bug for?

Because it let me replicate how DOOM (1993) did the players death, by simply sticking with the player entity then sliding their view down to the ground.

I cannot replicate this anymore due to these changes, Would be nice if you just simply set the players movetype to NONE on death instead of changed the movetype itself.

Unless you have another form of replicating this without me having to do make my own system (Which it looks like i'm going to have to, for the 1,000th time now)

> https://commits.facepunch.com/469230 the change is listed here in a commit from January

It was this far back? No wonder I couldn't find it damn.

**Comment by MagentaIris** [comment]
I'm going to assume that support for this is not going to be created, nor is planned to be able to be achieved again?

**Comment by robotboy655** [comment]
How exactly were you doing it in your case? Forcing player input in a move hook? Or simply applying velocity? if the former, I am not interesting in doing any additional changes for this. If the latter, I can look into it more.

**Comment by MagentaIris** [comment]
> How exactly were you doing it in your case? Forcing player input in a move hook? Or simply applying velocity? if the former, I am not interesting in doing any additional changes for this. If the latter, I can look into it more.

Neither...?

All i was doing was not creating a player ragdoll when the player died. I then just let the movetype do its job until the player hits the ground, Then i do some custom camera stuff on the Z Vector to sink them to the ground.

That was literally all I did.

Simply just adding ply:UseOldDeathBehaviour(true) would work fine. That's what i'm asking for, or for the changes to move types being reverted, since they don't honestly do anything anyway apart from _MAYBE_ stopping the player entity from leaving a visleaf or an area portal section.

**Comment by BREEDNKMs** [comment]
it can also be considered; moving player object also emits ai sounds (footstep sounds that only npcs can react) in my tests and some even face or move to player object position, not just about triggers.

**Comment by MagentaIris** [comment]
> it can also be considered; moving player object also emits ai sounds (footstep sounds that only npcs can react) in my tests and some even face or move to player object position, not just about triggers.

That's funny, But again. This could have been fixed by simply setting the players move type to NONE after they die instead of messing with the move types we currently have.

Also if the player died mid-air with the new movement changes, their Z Velocity climbs slowly to -999-etc.etc.

**Comment by robotboy655** [comment]
It should be fixed for your use case on `x86-64` when it next update, please confirm.

**Comment by MagentaIris** [comment]
My apologies for my late reply.

It does indeed work as intended for the use case I have.

However I can see the players movement jittering due to prediction errors, I'm fairly certain this never used to happen.

```
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3099 pred 3098) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3100 pred 3099) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3101 pred 3100) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3102 pred 3101) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3103 pred 3102) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3104 pred 3103) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3105 pred 3104) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3106 pred 3105) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3107 pred 3106) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3108 pred 3107) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3109 pred 3108) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3110 pred 3109) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3111 pred 3110) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3112 pred 3111) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3113 pred 3112) diff(-1)
001 C_BasePlayer::m_nNextThinkTick - int differs (net 3114 pred 3113) diff(-1)
```

**Comment by robotboy655** [comment]
It did, it is documented here: https://github.com/Facepunch/garrysmod-issues/issues/3826

**Comment by MagentaIris** [comment]
> It did, it is documented here: #3826

Shit, I swear it didn't feel like it.

Ah well, Atleast it's actually WORKING now so thankies.
