### ISSUE TITLE
file.AsyncRead called in ShutDown hook causes errors after changelevel

### ISSUE THREAD

**Issue by plally** [Facepunch/garrysmod-issues#5916]
### Details
using file.AsyncRead in a ShutDown hook causes errors and crashes after the server has changed level

specifically `[ERROR] attempt to call a nil value` and other calls to non function values.

### Steps to reproduce
- Run this code
```lua
hook.Add("ShutDown", "test", function()
    file.AsyncRead("data.txt", "DATA", function(a)
        print(a)
    end)
end)
```
- Run changelevel

**Comment by robotboy655** [comment]
Fixed.
