### ISSUE TITLE
texture fullbright issue

### ISSUE THREAD

**Issue by ZvZPvz** [Facepunch/garrysmod-issues#5919]
version:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:41:45 Jun 17 2024 (9354) (4000)
GMod version 2024.06.21, branch: x86-64, multicore: 1
Windows 64bit

### Details

This texture is fullbright in the game ,
No matter what branch it is

but the vtf&vmt file is not broken.
They work fine in other source1 games(like hl2 or portal2)

### Steps to reproduce

1.Create a VTF texture file with default flag
![-470e32b2604b6987.png](https://github.com/Facepunch/garrysmod-issues/assets/130430455/808bda2b-088c-4ab5-bb9b-97c1206aebf4)
2.Create a VMT file WITHOUT "$selfillum 1" keyvalue
![-26823341fd905116.png](https://github.com/Facepunch/garrysmod-issues/assets/130430455/fc6632d2-240a-4139-bae1-0921221aab77)
3.The texture is fullbright in game
    ![-b87725fdc29bb4a.png](https://github.com/Facepunch/garrysmod-issues/assets/130430455/02c79d88-72be-40c0-8d0d-b4e32167deca)

**Comment by robotboy655** [comment]
This is not a place to get modding help. Please use the official Discord server (https://discord.gg/gmod)

**Comment by robotboy655** [comment]
To be clear, gm_construct uses a material with `WorldVertexTransition` shader for its grass/sand and it is functioning there correctly, so it has to be an issue on your end. Check if the material exists in some addon, etc, etc.

**Comment by skybox-vmt** [comment]
hey I made this issue .My friend helped report it 。anyway This is definitely not a problem with texture files！ @robotboy655  look！it work fine 
! in other source game! [Uploading 6CC0983BC5B6A90870450115F40722A6.png…]()
Why did it go wrong in the gmod？

**Comment by robotboy655** [comment]
You didn't upload your picture, and as I said in my previous message, the same setup works correctly on the base Garry's Mod map - gm_construct.

Since you also did not provide any files to test with, there's physically nothing I can do to help you.
