### ISSUE TITLE
CUtlRBTree overflow

### ISSUE THREAD

**Issue by NovaDiablox** [Facepunch/garrysmod-issues#5920]
Exe version 2023.06.28 (garrysmod)
Exe build: 19:00:21 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: unknown, multicore: 0
Windows 32bit

### Details
Spawning bunch of turrets may crash the game if they shoot a single NPC.
No addons.
Probably same issue as https://github.com/Facepunch/garrysmod-issues/issues/4452 but without any addons.
Dump File: https://drive.google.com/file/d/1AvoRSufbkO93KeCGI1tHes_BdRZsOZr_/view?usp=sharing

### Steps to reproduce

1. Cap your FPS to 150.
2. Spawn bunch of ceiling turrets (like 60 of them).
3. Spawn a citizen or an enemy NPC.
4. As turrets activate and shoot the NPC the game crashes.

**Comment by robotboy655** [comment]
It's a completely unrelated issue to the one mentioned. Yours has to do with NPC memory, not fonts.

Unfortunately I am unable to reproduce the issue by spawning even 170 of those turrets and getting them to shoot a citizen or 10, or myself.

**Comment by robotboy655** [comment]
Nevermind, I had to increase the turret count to above 255, that did it. 

I will fix the crash.
