### ISSUE TITLE
util.DecalMaterial crashes/doesn't return the correct value for some materials

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#5921]
### Details
The problems with `util.DecalMaterial` vary depending on the environment. For all scenarios, you must add a decal using `game.AddDecal` with a material that is mounted but not included with the game (from an addon or something).

### Steps to reproduce
1. Put the following material at `materials/spray/spraypaint_decal1.vmt`:
```
"LightmappedGeneric"
{
    "$basetexture" "spray/dot"
    "$translucent" "1"
    "$decal" "1"
    "$decalscale" "0.375"
    "$color2" "[1 0 0]"
}
```
3. Start a singleplayer game or join a server you control
4. `lua_run game.AddDecal("DecalTest", "spray/spraypaint_decal1")`
5. `lua_run print(util.DecalMaterial("DecalTest"))`

### Results
- On Windows Client (no beta): Crash
- On Windows Client (x86-64/dev): Returns `decals/concrete/shot1_subrect` instead of the expected `spray/spraypaint_decal1`
- On Linux Server (x86-64): Crash

**Note:** It doesn't seem to matter if `materials/spray/dot.vtf` exists or not, the result is the same, but [it's here anyway](https://winteris.moe/share/2024-06-26_21-51-11.vtf) if you want it

**Comment by robotboy655** [comment]
Will be fixed.
