### ISSUE TITLE
Hammer - Mismatching Model Version

### ISSUE THREAD

**Issue by Freezgam03** [Facepunch/garrysmod-issues#5923]
### Details

CSGO, INFRA and Portal 2 models are throwing the "model X has mismatching model version (49, expected 48! Expect problems.", which doesn't result in anything strange with said models in-game, but it does increase compile time depending on how many you have on the map. 

Compared to Slammin Compilers, this warning doesn't exist and the models are fine on the actual map. So i'd be nice if the warning could just be removed all together. 

### Steps to reproduce

1. Get a CSGO, INFRA or Portal 2 model and place it into your models folder according to the correct model path
2. Compile a map with the model on it with Garry's Mod compilers

**Comment by robotboy655** [comment]
I have moved it to `-verbose`.

**Comment by Freezgam03** [comment]
> I have moved it to `-verbose`.


I have just tried it out with the most up-to-date vbsp.exe, and it's still there. If I try to use -verbose the message there, which is how it should be. But if you remove the -verbose command, it's still there.

**Comment by robotboy655** [comment]
You are probably not running the latest version.

**Comment by Freezgam03** [comment]
I switched branches, deleted the vbsp.exe multiple times and revalidated to make sure I got the most up-to-date version, but the message still appears in the compiling process.

**Comment by robotboy655** [comment]
You must be talking about a different warning then, or are using `vbsp.exe` not from GMod, or not from the update. I have looked at the code and found out that the warning is disabled even with -verbose due to a prior bug in `vbsp.exe`. I will fix this.

Check the date your `vbsp.exe` was built on:
![image](https://github.com/user-attachments/assets/dcc1c51f-282a-4ca1-9d2e-9322bb07af58)

It should say "July 2024" on NONE or PRERELEASE betas.

**Comment by Freezgam03** [comment]
I see, the problem was me switching back from the prelease/NONE branch back to 64bit as I figured by the commits posted on the discord, that it was also on the 64bit compilers. Reason being is that Hammer++ only works with 64bit, but it seems like the 64bit compilers are not updated and are from "Sep 23 2024". While from the other branches are on the date that you marked.

Is it on purpose that you haven't pushed it to 64bit and only have it on NONE/PRELEASE?

**Comment by robotboy655** [comment]
Can you please attach the **entire** output log you are getting where the issue is present?

**Comment by robotboy655** [comment]
I have just tested `x86-64` beta and its default compile tools, it definitely works correctly there.
