### ISSUE TITLE
Activated point_viewcontrol gives invincibility to the player

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5926]
So basically, if you activate a point_viewcontrol - you get invincibility. However if you kill yourself via commands and respawn when the point_viewcontrol is still active - you can get killed by anything again, so in a scenario where you die via commands and the camera is still tracking you, when you activate the point_viewcontrol again - you will once again become invincible.
Obviously if you deactivate the point_viewcontrol - you take damage as usual.
I played in a P2P server with a bot, only the activator gains the invincibility and not everyone on the server.

[pointviewcontrol.zip](https://github.com/user-attachments/files/16090644/pointviewcontrol.zip)
^ Map for ease of review.
On your left is a green button that activates the point_viewcontrol and the red one deactivates.
Loads of turrets will try to gun you down in front of you and the red brush behind you deals 99999 damage.

Now I know that fixing this is tricky as it _may_ break HL2 cutscenes by making the player vulnerable, but those cutscenes are all far from combat so the player should be fine? But then again some custom maps could be relying on the invincibility.
So perhaps the best way to tackle this is to preserve the original function and let the player be invincible, so add a flag or a property that says "Player Is Invincible", which is checked / set to "Yes" by default.

Other branches behave the same.
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:00:21 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: unknown, multicore: 0
Windows 32bit

**Comment by robotboy655** [comment]
I have made it give invincibility only when "Freeze player" spawnflag is enabled, as judging from internal comments, it was meant for this case, where player would be unable to reload autosave (or respawn in GMod) if they die while input is disabled.
