### ISSUE TITLE
util.BlastDamageInfo with invalid AmmoType can cause crash on certain npcs

### ISSUE THREAD

**Issue by Bonyoze** [Facepunch/garrysmod-issues#5930]
### Details

Running util.BlastDamageInfo on certain npcs can cause both singleplayer and dedicated servers to crash completely. This occurs when setting the AmmoType to 0 or anything above 37, Valid ammo ids are 1-37, and anything negative seems to works fine. The damage also has to be greater than 0.

If the damage has AmmoType 0, but the blast is positioned far enough away from the npc it doesn't crash the game. Even with a large radius and still causing damage, it won't crash. Only if the position of the blast is right on top or in a certain vicinity of the entity.

I've only tested npc_monk and npc_vortigaunt, which both lead to a crash.

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:41:45 Jun 17 2024 (9354) (4000)
GMod version 2024.07.05, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce
1. Join a singleplayer or dedicated server
2. Spawn npc_monk
3. Run the following code:
```lua
local dmg = DamageInfo()
dmg:SetAmmoType(0)
dmg:SetDamage(1)
util.BlastDamageInfo(dmg, ents.FindByClass("npc_monk")[1]:GetPos(), 100)
```
```
lua_run local dmg = DamageInfo() dmg:SetAmmoType(0) dmg:SetDamage(1) util.BlastDamageInfo(dmg, ents.FindByClass("npc_monk")[1]:GetPos(), 100)
```

**Comment by robotboy655** [comment]
Thanks. Will be fixed.
