### ISSUE TITLE
Think hook of the tool `X` gets run one last time after deploy of tool `Y`

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#5931]
### Please try running a different branch and verifying your game file integrity before reporting an issue.
Verification completed successfully ( all branches below ) and tested for every beta with and without addons:
  * None: Present
  * prerelease: Present
  * dev: Present
  * x64: Present

### Details
The `TOOL:Think()` routine is called one last time for tool `X` after user switches from tool `X` to tool `Y`. 
The current game version running is:
```
] version
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:41:45 Jun 17 2024 (9354) (4000)
GMod version 2024.07.05, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
1. Install the [`MASTER`](https://github.com/dvdvideo1234/TrackAssemblyTool/tree/master) version of the TA tool
2. Start Gmod and load random map ( I used flatgrass. Any branch/map will do )
3. Pick up the TA tool. The ghost gets drawn. Normal behavior here.
4. Press `1` to select the crowbar. The ghost is removed via `RemoveEntityDelay` and gone after the given time. All OK here too
5. Pick up any other random tool. The TA ghosting is re-triggered for one frame and the ghost is drawn

Details about the issue and the current workaround can be found here:
https://github.com/dvdvideo1234/TrackAssemblyTool/issues/58
```[tasklist]
### Tasks
- [ ] https://github.com/dvdvideo1234/TrackAssemblyTool/issues/58
- [ ] https://github.com/wiremod/advduplicator/issues/91
```

**Comment by Grocel** [comment]
This also causes this issue:
https://github.com/wiremod/advduplicator/issues/91

**Comment by robotboy655** [comment]
Core issue aside, your issue could be solved with 3 lines of code, by properly implementing base TOOL hooks:
```
function TOOL:ReleaseGhostEntity()
    asmlib.ClearGhosts()
end
```

**Comment by dvdvideo1234** [comment]
Sorry.. Clicked the close by mistake
