### ISSUE TITLE
`CThreadPool::SuspendExecution` is very slow (Linux DS 32x)

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5932]
### Details
On Linux DS, `CThreadPool::SuspendExecution` is slowed down, by a CWorkerThread not responding which slows it down by ~110ms.
If `developer` is set to `2` (or higher), you can see that a Thread is failing to respond:
```txt
Adding Filesystem Addon 'addons/test01'
Thread failed to respond, probably exited
Thread failed to respond, probably exited
Adding Filesystem Addon 'addons/test02'
Thread failed to respond, probably exited
Thread failed to respond, probably exited
```

With a added debug print:
```txt
Thread failed to respond, probably exited
--- CWorkerThread::WaitForReply ---
Result: -2 (WTCR_TIMEOUT)
Took: 109ms
Thread Name: IOJob0
-----------------------------------
```

### Steps to reproduce
1. Start a Linux DS Server
2. Have any amount of Legacy addons
3. See how slow the Legacy Addons get mounted.

**Comment by brandonsturgeon** [comment]
This causes my immense grief. My startup time is insanely high because I separate my code out into many separate addons.

It would be a huge improvement for my server and its players if this were fixed on main branch 🙌

**Comment by robotboy655** [comment]
Got a temporary solution for you: `-noasync` should disable those threads.

**Comment by phoen1xf** [comment]
> Got a temporary solution for you: `-noasync` should disable those threads.

https://github.com/RaphaelIT7/gmod-holylib/blob/main/source/modules/threadpoolfix.cpp#L27
this workaround seems fine, but the real fix would be finding the thread that causes the hang
