### ISSUE TITLE
Voice extremely low, works well all other places than gmod

### ISSUE THREAD

**Issue by omicca** [Facepunch/garrysmod-issues#5942]
Details
I'm running x64 version. My microphone works well in all other places (Including the Steam settings), but in Garry's Mod I have to almost scream for my microphone to pick-up anything. I have everything set to max and have boost on as well.

I have no way to reproduce it and there's no errors being displayed in console related to sound/voice.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
