### ISSUE TITLE
trigger_weapon_strip crashes the game when a prop enters its volume

### ISSUE THREAD

**Issue by FyREFREE** [Facepunch/garrysmod-issues#5944]
When a prop enters a trigger_weapon_strip trigger, the game crashes. This happens in singleplayer and p2p servers. This also includes player and npc ragdolls.

I'm on the 2024.07.19 x86-64 branch.

How to reproduce:
1. Enter a map with a trigger_weapon_strip
2. have a prop enter the trigger
3. *crash*

**Comment by robotboy655** [comment]
Can you please link a map that this issue happens on?

**Comment by FyREFREE** [comment]
I don't know of any maps on the workshop or in HL2 with the trigger. Only on maps that I have made and not uploaded, sorry. If it helps, I can record and link a video of me recreating the bug.

**Comment by robotboy655** [comment]
Should be fixed in the next update.

**Comment by FyREFREE** [comment]
Hell yeah
