### ISSUE TITLE
RemoveAllDecals does nothing on players if called on server

### ISSUE THREAD

**Issue by danx91** [Facepunch/garrysmod-issues#5946]
### Details
Calling `Entity:RemoveAllDecals()` has no effect on players if it's called by the server (calling that on other entities works fine).
Tested both on x64 branch and default branch. Tested with `-noworkshop` and `-noaddons` flags as well. Tested on sandbox and other gamemodes.

### Steps to reproduce
1. Go to a bot
2. Shoot the bot
3. Run `lua_run Entity(2):RemoveAllDecals()` - nothing happens (`Entity(2)` was the bot in my case)
4. Run `lua_run_cl Entity(2):RemoveAllDecals()` - decals disappear (only locally ofc)

**Comment by robotboy655** [comment]
Fixed on `dev` beta.
