### ISSUE TITLE
uhh i need help garry

### ISSUE THREAD

**Issue by Abby250** [Facepunch/garrysmod-issues#5948]
hey uhh garry ive been seeing this black gman with white eyes it wont stop watching us and i tried to kill it but it wouldnt die i have a instant kill gun that even kills a boss with 99999999 health but when i went near it it just randomly dissapears we cant figure out what it is but i have a screenshot of proof just letting you know, maybe you could fix it
![gman (1)](https://github.com/user-attachments/assets/13dd2012-7a89-4372-82dd-38400d88567d)

**Comment by Abby250** [comment]
comment here if anyone also has seen it

**Comment by Abby250** [comment]
it has not been completed

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

**Comment by garryspins** [comment]
ive been seeing this too!!!!!! no way i thought i was hallucinating!!!!!!!!!!!!!!!!!!!!!!!!
