### ISSUE TITLE
require() on Windows 11 ARM systems

### ISSUE THREAD

**Issue by TastyFrenchBun** [Facepunch/garrysmod-issues#5949]
### Details

OS: Windows 11 ARM (24H2 Build 26100.1)
`version` command output:
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:05:22 Jul 22 2024 (9379) (4000)
GMod version 2024.07.26, branch: x86-64, multicore: 1
Windows 64bit
```

The require() command can't find the same .dll that worked perfectly on the x64 system
It says: `Couldn't load module library! (The specified module could not be found.)` even though it's in folder
The game itself runs perfectly

### Steps to reproduce

1. Throw https://github.com/Metastruct/luadev/tree/master/lua/bin in /garrysmod/lua/bin
2. Try to require() it in-game

If you want to test something on ARM system and you don't have it, contact me, maybe I can be of help

**Comment by robotboy655** [comment]
ARM systems are not supported. The game requires x86-64 processor architecture.

**Comment by TastyFrenchBun** [comment]
Is there really nothing I can do to make require() work again? The game is emulated and runs perfectly, it's weird that only that part is broken :/

**Comment by TastyFrenchBun** [comment]
@robotboy655 Is there really nothing I can do to make require() work again? The game is emulated and runs perfectly, it's weird that only that part is broken :/

**Comment by PolEpie** [comment]
Please consider at least looking into the issue ? Or let us load via winarm64.dll idk ? Everything working perfectly at side of it and you can just use that to verify if we use arm

https://github.com/dotnet/runtime/pull/68583/commits/ecc55fe82e43daaafac20ce0b63a55c32eb4f68f
