### ISSUE TITLE
Floating point imprecision of mass in studiomdl

### ISSUE THREAD

**Issue by nnk000** [Facepunch/garrysmod-issues#5953]
### Details
models with certain values have not equal to integer mass values even if QC file have them correct

### Steps to reproduce
compile any model with mass 360, for example

![image](https://github.com/user-attachments/assets/d55529ac-c955-474f-8145-a5b13a6b9bf7)
![image](https://github.com/user-attachments/assets/92d1b448-eadb-4285-b58e-30a834c020cf)

literally unplayable rubat pls fix

**Comment by robotboy655** [comment]
Literally irrelevant, not going to "fix".
