### ISSUE TITLE
Base Derived gamemode throw "AddCSLuaFile: Couldn't find 'weapons/gmod_tool/shared.lua'" Lua Error

### ISSUE THREAD

**Issue by SpaxscE** [Facepunch/garrysmod-issues#5955]
Im on x86-64, but im sure this happens on all branches. 

I am creating a base gamemode following this guide: https://wiki.facepunch.com/gmod/Gamemode_Creation#:~:text=To%20create%20a%20new%20gamemode,named%20whatever%20your%20folder%20is.

But as soon ANY addon with a tool in "lua\weapons\gmod_tool\stools" is present it throw a lua error: 
![image](https://github.com/user-attachments/assets/cb6e57e3-4dc2-4eba-a032-75f463b0a4fb)

How to reproduce? Put this in addons and select test gamemode:
[put_in_addons.zip](https://github.com/user-attachments/files/16440462/put_in_addons.zip)

**Comment by robotboy655** [comment]
You have addons that add Sandbox tools, which creates the folder `lua/weapons/gmod_tool/`, which makes the game think there's a weapon that needs loading, but the files are not there, hence the error.
