### ISSUE TITLE
PlayerDroppedWeapon does not behave as expected.

### ISSUE THREAD

**Issue by NathanX-S** [Facepunch/garrysmod-issues#5956]
### Details
StripWeapons, StripWeapon, etc. do not trigger the PlayerDroppedWeapon hook as of 2024.07.30

### Steps to reproduce

`hook.Add("PlayerDroppedWeapon", "WeaponRemoved", function( owner, wep )
print(owner,wep)
end)
`
And then use ply:StripWeapons().

**Comment by robotboy655** [comment]
Did they ever? Stripping weapons deleted them, it doesn't drop them.

**Comment by NathanX-S** [comment]
> Did they ever? Stripping weapons deletes them, it doesn't drop them.

> Also called when a weapon is removed from a player via [Player:StripWeapon](https://wiki.facepunch.com/gmod/Player:StripWeapon).

Quoted from wiki documentation. Otherwise, there's no hook for when a weapon is 'generally' removed from a player.

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/f3177004-759b-4ed7-bbf3-02e2c937623e)

That still appears to work? There were no changes to the hook. The wiki info is still correct.

**Comment by robotboy655** [comment]
Yes. `StripWeapon` calls drop weapon internally, but `StripWeapons` doesn't. It was always this way, there's no regression.

**Comment by NathanX-S** [comment]
Is it possible to add a hook or something in that case, or add the behavior to StripWeapons? I'd prefer not to override the meta table if I can avoid it.

**Comment by robotboy655** [comment]
Made `StripWeapons` drop the weapons before they are removed.
