### ISSUE TITLE
Ep2 Car cluster props have no texture

### ISSUE THREAD

**Issue by VCSoldier** [Facepunch/garrysmod-issues#5957]
### Details
for some unknown reason, the car cluster props from ep2 (used during the part where your trying to sneak past the trio of pulse cannons shooting at zombies while the jalopy gets fixed) do not have any textures, and looking at them in the submaterial tool shows the texture as "__error"

![image](https://github.com/user-attachments/assets/1b17d5be-19d4-409e-9f5b-c00f97823fc5)

### Steps to reproduce
1. Spawn models/props_vehicles/car001b_cluster01-04
2. View Texture using submaterial tool (addon) or a lua script that grabs the texture

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/12935780-47da-4fda-bd63-8cfa3b54c2dd)

You must have Episode 1 and 2 mounted, Episode 2 uses some textures from episode 1, which maybe the issue you are having.

**Comment by VCSoldier** [comment]
Episode 1 doesnt have a prop_vehicles material or model folder, it cannot be that as the cause, ive checked myself, and if it did, it wouldnt cause the textures to not load properly, it would simply replace the texture the ep2 prop uses with the ep1/hl2 variant

**Comment by robotboy655** [comment]
Ah I see, they are just models included in Episode 2, but do not have any textures. As I have shown above, there are no missing textures on the Episode 2 map. These models are **not** used anywhere in Episode 2.

They have missing materials even in Episode  2 itself. (`prop_dynamic_create  props_vehicles/car001b_cluster04.mdl`)
![image](https://github.com/user-attachments/assets/2f62e2a9-4c40-413e-9af3-61e418a6e607)
