### ISSUE TITLE
Missing convar mat_reduceparticles during vbsp compile step

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5961]
`ConVarRef mat_reduceparticles doesn't point to an existing ConVar` always appears when vbsp runs 
![image](https://github.com/user-attachments/assets/7b2bc942-3c6d-4383-b688-23150d8c0fa4)

Can be replicated by just running vbsp with any vmf.

**Comment by robotboy655** [comment]
Fixed on `dev` beta.
