### ISSUE TITLE
Performance regression in gm_fork and gm_boreas

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/garrysmod-issues#5962]
My maps gm_fork and gm_boreas are suddenly performing far worse than they should. I don't know how long this has been going on as I'm no longer playing GMod or updating these maps, but comments from players suggest that the issue was introduced in the July 2024 update. The Chromium/x64 branch appears to be the only one that's not affected (both in 32-bit and 64-bit mode).

### Details
`+showbudget` indicates that significantly more time is spent under `Unaccounted` and `ComputeTranslucentRenderLeaf`, particularly in gm_fork:
gm_fork (main branch) | gm_fork (Chromium/x64 branch)
--- | ---
![fork_main](https://github.com/user-attachments/assets/61bf7e44-bb86-4553-84c8-9450cf775546) | ![fork_x64](https://github.com/user-attachments/assets/715b349e-caf1-490c-925a-7c1c28773d29)

gm_boreas (main branch) | gm_boreas (Chromium/x64 branch)
--- | ---
![boreas_main](https://github.com/user-attachments/assets/1bced295-6c2c-415a-8526-03370952d279) | ![boreas_x64](https://github.com/user-attachments/assets/168a5e9c-a4f2-4642-8984-2a12657e46f3)

I'm unable to pinpoint anything specific in the maps that's causing the issue. The performance impact simply grows as more things are being rendered. Disabling `r_drawentities` 'fixes' the issue but obviously isn't a real solution. I've tried a couple of other rendering commands as well (including `r_drawstaticprops`, `r_drawtranslucentrenderables` and `r_novis`) but those didn't seem to make a difference.

It's worth noting that both maps rely heavily on [func_viscluster](https://developer.valvesoftware.com/wiki/Func_viscluster) entities to reduce compile times. In gm_boreas they're used mostly as intended, but gm_fork has enormous func_visclusters that cover the entire playable area (one for everything above water level and one for everything below). The latter definitely isn't ideal, but this has never been a big issue before as the map relies mainly on LODs and fade distances for visibility optimization.

### Steps to reproduce
Using a fresh GMod installation with no other addons enabled:
1. Subscribe to [gm_fork](https://steamcommunity.com/sharedfiles/filedetails/?id=326332456) or [gm_boreas](https://steamcommunity.com/sharedfiles/filedetails/?id=1572373847) and play either map in singleplayer sandbox mode
2. Open the console and enter this command: `sv_cheats 1; noclip; setpos 0 0 15000; setang 89 0 0; +showbudget`
3. Close the console and unpause the game

If it matters, my specs are as follows:
**CPU:** Ryzen 7 7800X3D
**GPU:** GeForce RTX 4080
**Memory:** 32 GB DDR5-6000
**OS:** Windows 11 Home 23H2

**Comment by robotboy655** [comment]
Thanks for the report, will be fixed. Really strange that it doesn't happen on `x86-64` though.
