### ISSUE TITLE
Point Sample flag in .vtf breaks mip maps

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5963]
### Details
Setting the Point Sample flag in a texture makes it ignore mip maps. However, setting mat_filtertextures 0 in game somehow fixes them while retaining the look. Couldn't it be an easy fix considering how it already works with a console command?

mat_filtertextures 1 and Point Sample
![image](https://github.com/user-attachments/assets/15a37672-19db-405f-b203-36bbe1e414db)
mat_filtertextures 0 and Point Sample
![image](https://github.com/user-attachments/assets/62029f58-8831-458e-9058-a09e062591a9)

**Comment by robotboy655** [comment]
Alright, I have made TEXTUREFLAGS_NOMIP be functional when TEXTUREFLAGS_POINTSAMPLE is set, so you can toggle this behavior. Let's see if this breaks anything.
