### ISSUE TITLE
Unable to connect to one specific server.

### ISSUE THREAD

**Issue by Zyliath95** [Facepunch/garrysmod-issues#5966]
.I play on a Warhammer40-esque Gmod server, where I was able to log in without trouble.

After the update, however, every single time I attempt connection, I get stuck hanging at the Lua Started! step for several minutes, after which I get the Disconnect: [player] timed out. message.

I don't think it can be actually reproduced, sadly. What I do is the following:

Open GMOD;
Click on Multiplayer;
Click on Favorites (as I do have it as favorites);
Connect, load everything the server requires, and play.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
