### ISSUE TITLE
Invalid Sprite Name for env_spritetrail crashes the game

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5969]
The correct format for a valid Sprite Name is always `texture.vmt` ( or `texture.spr` ). If typed incorrectly, the game will crash upon map load.
[env_spritetrail.zip](https://github.com/user-attachments/files/16511033/env_spritetrail.zip)
^ Map for ease of review + crash log.

I tested all of this on env_sprite as well but that entity works completely fine.
_( Side note: Unlike env_sprite, env_spritetrail doesnt have `Browse` button, which makes it a bit frustrating to work with. )_

Consistent on other branches.
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:28:13 Jul 24 2024 (9391) (4000)
GMod version 2024.08.02, branch: unknown, multicore: 0
Windows 32bit

**Comment by robotboy655** [comment]
Thanks, will be fixed!
