### ISSUE TITLE
IMaterial:SetVector4D Only allows integer values

### ISSUE THREAD

**Issue by meetric1** [Facepunch/garrysmod-issues#5971]
### Details
IMaterial:SetVector4D Appears to round the input, meaning that dynamically setting certain flags on a material, such as $color2, are impossible

### Steps to reproduce
1. Create a blank material, heres mine:
```
UnlitGeneric {
    $color2 "[1 1 1 1]"
    $basetexture "lights/white"
}
```

2. Apply it onto a prop (I just did `lua_run Entity(1):GetEyeTrace().Entity:SetMaterial("mymaterial")`)
3. Try and set your material to a dim color (I did `lua_run_cl Material("mymaterial"):SetVector4D("$color2", 0.5, 0, 0, 1)`)
4. The material will be black, despite setting the color to (in my case) red 

### Extra Notes: 
`IMaterial:SetVector` does work in this case, but doesn't support the alpha component
`IMaterial:SetString` does not work in any form
This was tested on the x64-86 branch, though results are likely identical on other branches

**Comment by robotboy655** [comment]
Will be fixed.
