### ISSUE TITLE
debugoverlay fails to render anything despite `developer 1` or `developer 2`

### ISSUE THREAD

**Issue by yogwoggf** [Facepunch/garrysmod-issues#5972]
### Details

**Affected branches:** `x86-64`, `dev`, none.

**Test code:** `lua_run_cl debugoverlay.Box(Vector(), Vector(-32, -32, -32), Vector(32, 32, 32), 10, Color(255, 0, 0, 255))`
**Expected behavior:** A red box to appear for ten seconds at the origin of the currently loaded map (for me, this is gm_construct)
**Actual behavior:** Nothing. No output messages or red boxes at the origin of the map.

**File integrity:** ✅ 
**Build ID:** 15265359

**`version` output for my usual setup:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:05:22 Jul 22 2024 (9379) (4000)
GMod version 2024.08.05, branch: x86-64, multicore: 1
Windows 64bit
```

Also worth nothing I reproduced this issue with a friend using the same setup. I did not exhaustively test all functions within `debugoverlay` but other common functions like `Sphere` or `Cross` also do not function properly anymore.

### Steps to reproduce

1. Load `gm_construct` on any of the affected branches
2. Ensure `developer` is at 1 or higher
3. Ensure `sv_allowcslua` is at 1
4. Ensure `sv_cheats` is at 1 (not mandatory)
5. Type these following commands into console.
6. `noclip`
7. `setpos 0 0 0` _requires sv_cheats 1_
8. `lua_run_cl debugoverlay.Box(Vector(), Vector(-32, -32, -32), Vector(32, 32, 32), 10, Color(255, 0, 0, 255))`
9. After running each game, observe for a red box at the origin of the map (directly below where you're standing)

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/655f4b92-c68b-4450-b9d5-35886bb4e17a)

There's some code that prevents debugoverlay from being added if the game is paused, i.e. when console is open in singleplayer.

**Comment by yogwoggf** [comment]
Makes sense. Should probably put that on the wiki.
