### ISSUE TITLE
NPC-Related Crash (CalcAbsolutePosition - RelinkBeam)

### ISSUE THREAD

**Issue by robotik517** [Facepunch/garrysmod-issues#5973]
Hi, im maintaining a public server, and I began to notice frequent crashes.
Main suspect is a sniper and his beam-relinking to something out of range
Sniper deleted for the time being, i continue to monitor this issue

### Details
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:30:28 Jul 24 2024 (9391) (4000)
GMod version 2024.08.09, branch: unknown
Linux 32bit Dedicated Server

Debug and condebug are "on" and here are the results as well as additional server configuration:
https://drive.google.com/drive/folders/1Fi75RxH6oOiCZntEZJi_340TZ0keSviv?usp=sharing

All of the crashes are ending like this:
 ./srcds_run: line 360:  4648 Segmentation fault      $HL_CMD

### Steps to reproduce
No idea, for now i found no certain way to reproduce, crashes once a day
I hope that these logs will help to determine the cause of the crash

**Comment by elixirelix** [comment]
Hi !

I have the same issue in my public server !

My server has the same problem. It crashes without giving more information, and in an irregular way. I send a link to a crash log file, maybe it will help you.

https://drive.google.com/file/d/1sZPd6ovxQ1P6Yk2xQkxSp1sW4wzdolEy/view?usp=sharing

**Comment by robotboy655** [comment]
I think I understand what is happening, I have applied fixes for the HL2 sniper on the `dev` beta.

@elixirelix Your issue appears to be entirely unrelated, judging from the log file you posted.
