### ISSUE TITLE
GMod doesn't load addons/workshop items when launched via `+map` command line

### ISSUE THREAD

**Issue by TetraTheta** [Facepunch/garrysmod-issues#5974]
### Details
```plaintext
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:05:22 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
1. Subscribe Workshop items like [Dark UI Spawnmenu](https://steamcommunity.com/sharedfiles/filedetails/?id=888392108) for better visibility.  
   If the workshop item is not loaded, your spawnmenu will be 'white', instead of 'dark'.
2. Create simple map via Hammer Editor. Or you can get any map that runs on GMod and put it into `GarrysMod/garrysmod/maps`.
   1. If you create a new map via Hammer Editor, compile the map first.
3. Navigate to `GarrysMod` directory.
4. Open Shell (Command Prompt) and run `hl2.exe +map <map name>`.
5. GMod is opened with the map. But your addons/workshop items are not loaded, as if you didn't subscribed it.
6. Run `restart` on Console.
7. Now you have your subscribed workshop items or addons.

If I understand the [Command Line Parameters](https://wiki.facepunch.com/gmod/Command_Line_Parameters) correctly, those subscribed workshop items or addons should be disabled only if you launch GMod with `-noaddons` or `-noworkshop`.

If this behavior is intended, then the phenomenon that subscribed workshop items or addons are loaded after `restart` would be the bug. But I really want to load map with the addons and the workshop items I've subscribed, so please don't tell me that this is intended behavior...

### Things I've tested

Branch doesn't matter. I tested with the 'x86-64' beta branch and the 'main' branch (default branch).

Executing binary also doesn't matter. I tried `GarrysMod/hl2.exe` and `GarrysMod/bin/gmod.exe`, `GarrysMod/bin/win64/gmod.exe` with `+map <map name>` parameter. None of them loaded addons/workshop items.

**Comment by TetraTheta** [comment]
If then, will there be any way to make GMod to load `.gma` file _anyway_ when its launch?  
I depend on multiple addons that utilize Lua, so it would be nice to load them via `.cfg` file like `mount.cfg`.

I thought that if GMod needs to wait Steam for fetching subscribed workshop addons, using local addon will bypass such check, and they will be loaded even when launched via `hl2.exe +map gm_construct`.  
But local addons are not properly loaded neither. I think this implies GMod still checks details of addon even if it is local addon file.

In this case, I don't think there is a way to make GMod to 'load addons under XXX path anyway' with launch options.

Other way that I can think of is, modifying `gameinfo.txt` to load VPK files under `custom/` directory, and repack addon files to VPK, instead of GMA. This may make repacked addons to be loaded with `garrysmod_xxx.vpk` and `fallback_xxx.vpk`.  
Of course, I'm not sure if this would work or not.

**Comment by robotboy655** [comment]
It seems locally installed `.gma` files are mounted after all subscriptions were fetched, I will change this so they mount before that instead on `dev` beta, and we shall see if that causes any problems.

Alternatively maybe there perhaps can be a loading screen step to wait for subscriptions to mount before continuing.

**Comment by TetraTheta** [comment]
> It seems locally installed `.gma` files are mounted after all subscriptions were fetched
> Alternatively maybe there perhaps can be a loading screen step to wait for subscriptions to mount before continuing.

I'm not sure if this information helps, but launching GMod with `+map` option is a little bit different in `x86-64` branch. I'm sure this would be same for all branches, though.

### Normal Launch
This is when launching GMod via Steam or Shortcut link without `+map` option.

1. Blue-backgrounded Facepunch Logo (Always Fullscreen)  
   I'm not sure if this is intended behavior or not, but even though GMod is set to Windowed Mode, this screen is always Fullscreen.
2. GMod Main Menu
3. Click 'Start New Game' and select a map, and click 'Start Game'
4. Dark-themed map loading screen  
   * 'Starting local game server...'
   * 'Loading world...'
   * ...
   
   This is always dark-themed even though it is day time. I personally like current behavior because light-theme burns my eye.
5. Map loaded

### Launch with Options
This is when launching GMod with `+map` option.

1. Blue-backgrounded Facepunch Logo (Always Fullscreen)  
   I'm not sure if this is intended behavior or not, but even though GMod is set to Windowed Mode, this screen is always Fullscreen.
2. Frozen GMod Main Menu  
   I see Frozen 'Fetching Subscriptions...' too.
3. ~~Click 'Start New Game' and select a map, and click 'Start Game'~~  
   This is skipped because we launch GMod with `+map`
4. ~~Dark-themed map loading screen~~  
   I don't see this screen even though I think it should appear.
5. Map loaded  
   Addon files are not properly loaded.

**Comment by TetraTheta** [comment]
It seems latest `dev` branch doesn't load local addon files at all. In normal launch, I don't see maps that are included in local GMA files under `addons/test`. Also GMod doesn't load addon files at `addons/private` too.

I'll go back to `x86-64` branch for now.

**Comment by robotboy655** [comment]
Sorry for the delayed response, I have looked into your report, and there was an unintentional sideeffect where float .gma files would not load from addons/ folder because the addons/ folder was mounted after workshop content. I have fixed this on `dev` beta now.
