### ISSUE TITLE
if point_spotlight is killed the beam will teleport at the center of the map

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-issues#5975]
### Steps to reproduce
1. kill any point_spotlight (perhaps only parented ones? not sure if it's all in general)
2. the beam should teleport in the center of the map

i am not sure if this is a known issue and if it's possible to fix

**Comment by Battlefieldkille** [comment]
Can confirm, but im not sure if its fixable.
[pointspotlight.zip](https://github.com/user-attachments/files/16626418/pointspotlight.zip)
^ Map for ease of review.
Left button will kill the point_spotlight that doesnt have a parent. - Looks fine.
Right button will kill the point_spotlight that is parented to a func_rotating. - The beam is teleported to the map's origin.

**Comment by robotboy655** [comment]
Killing `point_spotlight` will now correctly remove the entities it creates.
