### ISSUE TITLE
FireBullets Spread is visually incorrect in singleplayer

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#5979]
The Spread parameter for FireBullets accepts a vector, however there is a bug in singleplayer where it visually ignores all but the first value. In fact, it looks like it has its own value hardcoded (?)

If you set something like Vector(.2, 0, 0) for the bullet spread in multiplayer, the result is correct:
![изображение](https://github.com/user-attachments/assets/c47630c2-3c61-4fb8-bfd8-7d170f2c2ee7)

But in singleplayer it looks like this:
![изображение](https://github.com/user-attachments/assets/20d33e36-66c5-4bd5-9bb3-463467a8835e)
If you try to damage something, you'll see that the damage isn't applying, so the spread is just visual
![изображение](https://github.com/user-attachments/assets/0d460364-7405-4f33-a8fb-199e5b60ba8f)

Still, the spread for NPCs is always correct even in singleplayer
![изображение](https://github.com/user-attachments/assets/dd7ae8d5-ffde-4203-adcd-2f8cbf5a3baf)

**Comment by robotboy655** [comment]
Will be fixed in the next update.
