### ISSUE TITLE
Version/branch info card redirects to deprecated repository

### ISSUE THREAD

**Issue by grande1900** [Facepunch/garrysmod-issues#5980]
![image](https://github.com/user-attachments/assets/ba1e3f2e-be2b-44d8-8d39-63eba07b1922)
The version and branch information card in the top right corner of the menu currently directs to https://commits.facepunch.com/r/Garrys%20Mod whenever you click it; which, as far as I know, has been deprecated since August 2022. This should be updated to the new repository of https://commits.facepunch.com/r/garrysmod.main.

**Comment by robotboy655** [comment]
Will be fixed.
