### ISSUE TITLE
Garrys Mod wont start due to Direct X error

### ISSUE THREAD

**Issue by RavenTheWolfr** [Facepunch/garrysmod-issues#5986]
On attempted launch after Multiple reinstalls. The Game fails to launch and a error that says your system appears to be missing D3DX9_40.dll which is part of DirectX 9.0c run time necessary to run the game. Do you wish to open the support website to help with is problem. Press Yes to open the support website describing how to update your direct x runtime. Press no to try to continue loading Garry's mod. Press cancels to Exit Garry's mod.  Garry's mod is latest version as it does not require an update. 

### Steps to reproduce

1.To reproduce the problem don't say yes to the to install and don't allow steam client service. In my case I forgot the admin password my dad stupidly put on my gaming laptop even though I'm an adult that is 19 years old.
2.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
