### ISSUE TITLE
GM:PlayerAuthed Bug

### ISSUE THREAD

**Issue by Srlion** [Facepunch/garrysmod-issues#5988]
### Details

Calling `Player:IsFullyAuthenticated()` returns false in `GM:PlayerAuthed` when `Player:UniqueID()` is called before this hook is called

### Steps to reproduce

1.
```lua
hook.Add("PlayerInitialSpawn", "aaaaaa", function(ply)
    print("PlayerInitialSpawn", ply:UniqueID())
end)

-- just so you notice it in console easier
hook.Add("NetworkIDValidated", "NetworkIDValidatedTest", function( name, steamID )
    print( "NetworkIDValidated", name, steamID )
end)

hook.Add("PlayerAuthed", "aaaaaaaa", function(ply)
    print("PlayerAuthed", ply:IsFullyAuthenticated())
    debug.Trace()
end)
```

2. Keep rejoining till steam delays the authentication and you will be able to replicate it.

How does `PlayerAuthed` get called? I'm thinking of just switching to `NetworkIDValidated`

**Comment by Srlion** [comment]
I figured a faster way to replicate it, is by joining the server when it's still starting, this makes NetworkIDValidated get called 10 seconds after you spawn in.

**Comment by robotboy655** [comment]
Not a bug, the hook is poorly named/incorrectly documented.

Its called when the player gets their UniqueID, not when authenticated by Steam. For the latter, you have `NetworkIDValidated`.

I have updated the wiki page for it.
