### ISSUE TITLE
ent_fire !player sethudvisility also hides Subtitles.

### ISSUE THREAD

**Issue by IBRS-4Ever** [Facepunch/garrysmod-issues#5990]
### Details
Especially on map ep2_outland_02, where Vortigrunt healing Alyx, the HUD will be hide during the cutscene, but it also hides subtitles.
![20240831181237_1](https://github.com/user-attachments/assets/2980033c-c1d4-4e11-8ef7-05737952727f)
![20240831181334_1](https://github.com/user-attachments/assets/92649b2c-3752-4491-ab53-0294fbe9c747)

**Comment by robotboy655** [comment]
Will be fixed.
