### ISSUE TITLE
TraceHull ignores HitBoxes

### ISSUE THREAD

**Issue by robotik517** [Facepunch/garrysmod-issues#5997]
Working on a ballistics, investigating a hit unreg on NPCs
So, TraceLine is checking against hitboxes, TraceHull does not(with identical setup)
Switch ai_disabled on-off-on for hitboxes to update(a must in VJBased - NPC)

### Details
Video
https://drive.google.com/file/d/1X2qf4l9nRRkWFdmUeVZn0MeO91WExfcQ/view?usp=sharing

### Steps to reproduce
Run code, spawn a big NPC, so its hitboxes are outside of its hull
[sv_debug.txt](https://github.com/user-attachments/files/16914090/sv_debug.txt)

**Comment by Goldermor** [comment]
It is just what TraceHull does, it does not detect hitboxes. And if you're having trouble detecting hitboxes outside of NPC's collision bounds with any other traces, we have [this](https://wiki.facepunch.com/gmod/Entity:SetSurroundingBounds).

**Comment by robotik517** [comment]
It is not intended, or if it is - this feature should have been documented, it is very obscure

**Comment by garryspins** [comment]
The wiki is public to make edits for!

**Comment by robotik517** [comment]
I think it is an error

**Comment by robotboy655** [comment]
It is not an error, hitbox tracing is not implemented for hull traces. I will update the wiki to reflect this info.

https://github.com/nillerusr/source-engine/blob/29985681a18508e78dc79ad863952f830be237b6/engine/enginetrace.cpp#L473
