### ISSUE TITLE
The taskbar icon vanishes when you enter a game.

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-issues#600]
![2013-11-30_10-06-53](https://f.cloud.github.com/assets/847422/1648560/554b2cd4-59a7-11e3-80ea-983e998355c9.gif)
This happens consistently:
1. Open up GMod with the launch options `-windowed -novid -noborder` 
2. Start a new game (any type - for this I used singleplayer)
3. Click out
4. Click back in

**Comment by robotboy655** [comment]
Is this still a thing?

**Comment by Lexicality** [comment]
I don't _think_ so?
