### ISSUE TITLE
Changelevel & his trigger will freeze the loading on very populated/big maps

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-issues#6002]
Now, i know this is probably NOT PLANNED but i was wondering what could this cause the game to freeze entirely, usually i have a workaround for this situations (which is straightup replacing the changelevel trigger with map load lua stuff), but what's the reason for the game to hang up entirely? like failing to transition entities, too many entities? and if it's possible to fix??

using report_entities, the entities number doesn't seem that much? it's around 3000...
usually this type of behavior can be spotted easily if cleaning up the map, also this is related to changelevel entirely
sometimes in the next map, some entities will be straight up removed/missing, until the map has reloaded from 0??

### Details
This was tested in the standard version of the game, the map itself it's still a WIP in fixing, since it's just a copy n' paste of 2 in 1, with slight changes, and retargeting of names to avoid conflict
If you transition to the "Broken" map, the changelevel will be fine, however, if you changelevel FROM the "Broken" map, your game will hang up on the loading

### Steps to reproduce
EPISODE 2 MAP
THE MAP AFFECTED IS gmhl2e2_outland_03
use `changelevel` inside the map mentioned above, same thing happends when touching `trigger_changelevel`'s
Had to upload on MEGA, file too big
https://mega.nz/file/xfQRnSqT#NFVX2-YNPzjhXUJZ6efePZnFUn_LkScIH8eCkVUikn4

**Comment by ALIEN31ITA** [comment]
Sorry if it's just a straight rip from 2 map files, i wasn't sure if i could replicate it by creating 2 simple empty maps with a lot of entities in it and changelevels

**Comment by robotboy655** [comment]
The transition was hitting the internal 3MB limit for the savegame, so when it was trying to load the invalid broken save game, it was hitting an infinite loop, or a near-inifnite loop. 

I will bump the max filesize to 16MB for save files.

**Comment by ALIEN31ITA** [comment]
> The transition was hitting the internal 3MB limit for the savegame, so when it was trying to load the invalid broken save game, it was hitting an infinite loop, or a near-inifnite loop.
> 
> I will bump the max filesize to 16MB for save files.

Just for curiosity, how much was trying to save? and also is it possible to disable this system somehow?
if it's the autosave entities i can just remove them, but if it's something else i don't know...

**Comment by robotboy655** [comment]
You cannot disable this, without making a save there can be no smooth transitions from one level to another. (Smooth transitions meaning the player position is saved and moved properly as if there was no map change, as well as any props in the transition trigger being saved and moved to the new map)
