### ISSUE TITLE
Orthographic RenderView has incorrect PVS origin

### ISSUE THREAD

**Issue by meetric1** [Facepunch/garrysmod-issues#6003]
### Details
When using render.RenderView, map faces are culled when they shouldn't be. It appears like the visleaf is set to 0,0,0, or something like that. 
![image](https://github.com/user-attachments/assets/a3ca542c-1b84-4495-9b0a-9943bc75a38d)
![image](https://github.com/user-attachments/assets/0f8cfd18-02f7-484c-a62f-625bb684c22f)

### Steps to reproduce
Run this script in any map and look at faces facing away from the origin.
On gm_flatgrass this is extremely prevalent since the origin is so far up.

```
hook.Add("HUDPaint", "", function()
    render.RenderView({
        x = ScrW() - 512,
        w = 512,
        h = 512,
        aspect = 1,
        drawviewmodel = false,
        znear = 1,
        zfar = 2^16,
        ortho = {
            left = -500,
            right = 500,
            top = -500,
            bottom = 500
        }
    })
end)
```

### Extra Notes
- Tested on x64-86 branch
- Specifying an `origin` in the render.RenderView table doesn't fix anything

**Comment by robotboy655** [comment]
Potentially related:
https://github.com/Facepunch/garrysmod-issues/issues/5363
https://github.com/Facepunch/garrysmod-issues/issues/5085

Please specify which beta of the game you are running.

**Comment by meetric1** [comment]
Tested on 64 bit.

**Comment by meetric1** [comment]
Closing because of duplicate
