### ISSUE TITLE
`sv_showlagcompensation` apparently crashes Linux DS

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#6008]
### Details
If you enable it on a Linux DS it apparently crashes in `CLagCompensationManager::BacktrackEntity`

```txt
                 mov     eax, ds:debugoverlay
                 mov     eax, [eax] <------- Crash -------
                 mov     esi, [eax+4]
                 mov     eax, ds:dword_15FD63C
                 call    _ZNK6ConVar8GetFloatEv_isra_10 ; ConVar::GetFloat(void) [clone]
```

`debug.log`:
[linux_debug.log](https://github.com/user-attachments/files/17090634/linux_debug.log)
(Tested it on the dev branch only)

### Steps to reproduce
1. Enable it `sv_showlagcompensation 1`
2. Shoot the world
3. Watch as it crashes

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta when it next updates.

**Comment by RaphaelIT7** [comment]
I'll try it as soon as it's deployed

**Comment by RaphaelIT7** [comment]
Seems to be fixed
