### ISSUE TITLE
CurTime() can be inaccurate in the clientside Move hooks

### ISSUE THREAD

**Issue by Bonyoze** [Facepunch/garrysmod-issues#6009]
### Details
`CurTime()` will seemingly reset back to 0 at the first calls of clientside `SetupMove`, `Move` and `FinishMove` then jump back to its correct value at some point.

### Steps to reproduce
Tested on a local dedicated server with the code loaded from `lua/autorun`.
```lua
if SERVER then return end

print("Initial CurTime: ", CurTime())

local i = 0
hook.Add("SetupMove", "", function()
	print("SetupMove CurTime: ", CurTime())
	i = i + 1
	if i == 100 then
		hook.Remove("SetupMove", "")
	end
end)
```

Initial CurTime will be correct. First calls in SetupMove will be incorrect then suddenly correct:

![image](https://github.com/user-attachments/assets/0ff31e55-6d63-4055-8089-9af4162ff446)

**Comment by robotboy655** [comment]
Related or duplicate: https://github.com/Facepunch/garrysmod-issues/issues/3026

**Comment by robotboy655** [comment]
This is just prediction system rolling back the timer. If you want to get the "real" value, you use the aptly named https://wiki.facepunch.com/gmod/Global.UnPredictedCurTime
