### ISSUE TITLE
Player:UniqueID()="" when called inside of GM:OnEntityCreated on the SERVER

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#6012]
### Details

if you call Player:UniqueID() on the serverside in the tick their entity is created, you will get an empty string

Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:22:33 Sep 23 2024 (9452) (4000)
GMod version 2024.09.25, branch: x86-64, multicore: 1
Linux 64bit

### Steps to reproduce
1. make a shared autorun file with the following code:
```lua
hook.Add("OnEntityCreated","UniqueID",function(ent)
    if ent:IsPlayer()then
        local ID=ent:UniqueID()
        if ID==""then
            ErrorNoHaltWithStack("ent:UniqueID()=\"\"")
        end
    end
end)
```
2. start a single player game,
3. you will see that you get an error serverside

**Comment by robotboy655** [comment]
Should be fixed on `dev`.
