### ISSUE TITLE
Point_devshot_camera doesnt work because of missing command (devshots_screenshot).

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-issues#6016]
### Details

The command "-makedevshots" doesn`t work because the command "devshots_screenshot" does not exist

![Image](https://github.com/user-attachments/assets/a3cfd9e2-6d99-4b20-a6dc-a121d523d80c)

### Steps to reproduce

1. Load a map with the entity point_devshot_camera with a command like this "+map name_of_the_map -makedevshots"
2.See the error in the console

**Comment by robotboy655** [comment]
Made it use `screenshot` command instead.
