### ISSUE TITLE
gui.AddCaption() does not support non-English Characters (Tested Chinese and Russian)

### ISSUE THREAD

**Issue by IBRS-4Ever** [Facepunch/garrysmod-issues#6017]
### Details

![Image](https://github.com/user-attachments/assets/37ea6a32-afe4-48ae-a517-00763d6ea19e)

### Steps to reproduce

1. concommand.Add("subtitles_test", function()
       gui.AddCaption( "This is English, 这是中文。 Это русский.", 5)
end)
2. subtitles_test
3. Only English characters are displayed correctly.

**Comment by robotboy655** [comment]
Will be fixed.
