### ISSUE TITLE
[Linux DS 64] VProf doesn't work.

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#6019]
### Details
On 64x Linux DS, vprof doesn't seem to work.  
As far as I found out, it is caused by `CVProfile::InTargetThread` failing.  
It fails because it compares `CVProfile::m_TargetThreadId`(an `unsigned int`) against `ThreadGetCurrentId`(an `ThreadId_t` / `uint64`) which then fails to compare.  
`CVProfile::m_TargetThreadId` should probably be changed to `ThreadId_t` / an uint64 to match `ThreadGetCurrentId`.  

An example to easily see the Issue I mean:
```cpp
#include <cstdio>
#include <pthread.h>

int main()
{
    unsigned m_TargetThreadId = pthread_self(); // Basicly what vprof does
    unsigned long int pthread_Id = pthread_self(); // You can see the type difference
    printf("%u %lu %s!\n", m_TargetThreadId, pthread_Id, m_TargetThreadId == pthread_Id ? "true" : "false");
    return 0;
}
```

### Steps to reproduce

1. Run `vprof_on`
2. Run `vprof_generate_report`
3. See the empty report

> NOTE: This could maybe be linked to https://github.com/Facepunch/garrysmod-issues/issues/5981

**Comment by RaphaelIT7** [comment]
![Image](https://github.com/user-attachments/assets/81ca3ba0-74f2-4621-980d-f0da28d4b854)

**Comment by robotboy655** [comment]
That's kinda weird that it doesn't work because of that, both are 64bit ints on 64bit builds, unless its signed/unsigned mismatch?

Either way, the proposed changes appear to have fixed the issue.

**Comment by RaphaelIT7** [comment]
> That's kinda weird that it doesn't work because of that, both are 64bit ints on 64bit builds, unless its signed/unsigned mismatch?

If I remember correctly, on Windows the compiler would make it a 64bit int, but on Linux it became a 32bit int instead, which was why it broke.
