### ISSUE TITLE
can't send http requests to localhost

### ISSUE THREAD

**Issue by github0oa** [Facepunch/garrysmod-issues#6021]
example

```lua
HTTP({
    url = "http://localhost",
    method = "GET",
    failed = function(err)
        print(err)
    end,
    success = function(code,body)
        print(body)
    end
})
```

output err `Operation was aborted by an application callback`

the request is processed in the browser and everything is fine.
my server doesn't even see that the request was accepted. (nodejs http server)

I dont know why.

try creating a simple http server on nodejs and see if requests come in

```js
let http = require("http")

http.createServer((req,res) => {
    console.log("input!")
}).listen(80)
```

I ran garry's mod x86-64 chronium with this parameter. (on window 10 in game, is not dedicated server)
![Image](https://github.com/user-attachments/assets/cc3dd394-fc6f-478a-929a-39396f9bc5f2)

**Comment by robotboy655** [comment]
This is not a bug.
