### ISSUE TITLE
Instant CTD upon level transition [x86-64]

### ISSUE THREAD

**Issue by evilpigeonlol** [Facepunch/garrysmod-issues#6022]
### Details
As soon as the loading screen opens, even before any info is seen on the window on the bottom right, the game crashes. This does not happen with loading a level with the menu. (i.e the "map" console command)

https://mega.nz/file/vcVkSTpB#w9IZLjk9OkqbeZGOf5rYvLo1iW9tRor7cs32VqgEtkU

### Steps to reproduce

1. Load any campaign map that has a level transition such as c1a0
2. Go to and trigger any level transition, the game will instantly CTD

This has been tested using -noaddons and -noworkshop

**Comment by robotboy655** [comment]
Will be fixed soon.
