### ISSUE TITLE
[MAT/UI] Missing shader on UI elements on numerous HUDS (Dev Branch)

### ISSUE THREAD

**Issue by DopeyPepsee** [Facepunch/garrysmod-issues#6027]
Hello! Just noticed today, on the Dev branch that a handful of UI elements from both some of my HUDs and a night vision mod have changed, I'll post some screenshots below. I know this probably won't be that descriptive of a bug report so I'll try my best.

For the HUD for instance, it seems they have the missing shader wireframe texture for both the light meter background and the weapon select here.
![Image](https://github.com/user-attachments/assets/d802e69b-52da-4125-8fe4-fbb2ea2fb1b5)

I am not sure what causes this, it seems to only affect certain HUDs/mods, I'll link what I noticed was affected for sure from the most recent commit that changed vguimatsurface.dll

- For the HUD add-on, all HUD elements are .PNG's.
- For the goggles add-on they use Post Processing and Color correction/color modulation.

I will also post some comparison images for before and after if that helps narrow down the cause.
![Image](https://github.com/user-attachments/assets/947787a5-6147-4fc2-a5e8-8e7d5dd76af5)
![Image](https://github.com/user-attachments/assets/8bd9e27a-31a4-4848-979b-5f76b9f9eef4)

Here are the links to the mods used:

- https://steamcommunity.com/sharedfiles/filedetails/?id=2907238445
- https://steamcommunity.com/sharedfiles/filedetails/?id=1819260044

Have a good one! And thank you for your time.

**Comment by robotboy655** [comment]
Thanks for the report and for using the `dev` beta, the issue should be resolved soon.
