### ISSUE TITLE
The problem with the in-game keyvalue physgun_interactions

### ISSUE THREAD

**Issue by oda-di** [Facepunch/garrysmod-issues#6029]
Problem with 
Physgun interaction “impale”
The props_junk\harpoon002a.mdl object contains a physgun interaction called “impale”. It doesn't work properly.
In the qc. file harpoon002a.mdl is this:

```
physgun_interactions
{
“preferred_carryangles” ”0 0 0 0 0”
“onfirstimpact” ”impale”
“onlaunch” ”spin_none”
“damage” ”none”
}
```

This says that this prop can't do damage, but it will do an “impale” on the first impact. That said, the Source code says that an NPC that was killed with a prop containing “impale” will have the BecomeRagdoll function called. Therefore, the game considers that the NPC was not “killed by the player”, but “removed from the world”. Therefore, it is not possible to catch the death of an NPC through the script if it was killed by a prop containing “implale”. You can also check that when killing an NPC with harpoon002a.mdl, no notification will appear in killfeed that the NPC was killed. 

https://github.com/user-attachments/assets/3ac2f4bf-67eb-426a-a003-2db95b744d4a

**Comment by robotboy655** [comment]
Will be fixed.
