### ISSUE TITLE
[Linux DS 64] file.AsyncRead isn't Async

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#6031]
### Details
On Linux 64x file.AsyncRead doesn't seem to be Async.

My guess is that the filesystem's threadpool isn't started properly / same issue as https://github.com/Facepunch/garrysmod-issues/issues/5310 but I didn't verify this yet.
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/filesystem/filesystem_async.cpp#L639

### Steps to reproduce

1. Start a Linux DS Server
2. Run `lua_run local a=SysTime() for k=1, 50 do file.AsyncRead("steamclient.so", "BASE_PATH", function() end) end print(SysTime()-a)`
3. Watch it freeze the main thread

**Comment by RaphaelIT7** [comment]
Just verified it and it really seems like `bEnableOnLinuxDedicatedServer` is missing for the threadpool.

**Comment by robotboy655** [comment]
I have applied the proposed fix to the `x86-64` beta.

**Comment by RaphaelIT7** [comment]
Just tested it and it seems like it's still an active issue

**Comment by robotboy655** [comment]
I think I used the wrong define for it, please test again.

**Comment by RaphaelIT7** [comment]
tested it again and it works
