### ISSUE TITLE
"nav_update_blocked" concommand blocks all NavAreas

### ISSUE THREAD

**Issue by Necrossin** [Facepunch/garrysmod-issues#6032]
### Details
Running a "nav_update_blocked" console command ends up in blocking every single NavArea on the map (instead of ones that are being blocked by breakable walls etc).
Happens on default/x64 and pre-release branch (as of 16.10.2024).

### Steps to reproduce
1. Load any map with navmesh (singleplayer/multiplayer, any gamemode)
2. Enable cheats, run "nav_edit 1"
3. Run  "nav_update_blocked" and watch the whole navmesh go blue

![Image](https://github.com/user-attachments/assets/487ce295-9df3-4dbb-96c7-4a55a2a17ed5)

**Comment by Necrossin** [comment]
On a side note: this may or may not be related to NavAreas no longer triggering their internal UpdateBlocked function.

**Comment by robotboy655** [comment]
Fixed.
