### ISSUE TITLE
Poison Zombie animations not working/freaking out.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#6035]
This never used to happen before, which is why I'm bringing it up here since it seems to be an **issue caused by an update**.

Inside of Temporal Assassin the Poison Zombies and Hive Zombies (Who all use the same .ani file) no longer animate correctly.

They slide around at a 90 degree offset and their legs sometimes go a little crazy, I'll be able to grab a video later today.

1: Get TA (https://steamcommunity.com/sharedfiles/filedetails/?id=3258426988)
2: Goto GM_Flatgrass or something.
3: Enable TA_Dev_DeveloperMode 1
4: Hold F1 and spawn a poison zombie.
5: Wacky Woohoo Pizza Man Slide.

**Comment by MagentaIris** [comment]
Weird, I don't think I remember seeing it happen in the later parts of August.

Hopefully this issue gets resolved soon then.

**Comment by robotboy655** [comment]
Ok. so from what I can understand, this is an issue on your end.

The poison zombie model was updated in the base game, including its `.ani` file, so it has episodic animations. You are using custom models  but include the original `.ani` file for some reason (from your `models/zombie/poiani.mdl`). You should not be doing this. You should either ship your own `.ani` file for each model (You do ship `poiani.ani`, but you are not including it?), or if you wish to include the animations from the base game model, you should simply `$includemodel` the original model.

`.ani` files appear to be relying on the associated model file to load in correctly. This is how all other HL2 models handle including animations from separate models, they `$includemodel` the associated `.mdl` files.

**Comment by MagentaIris** [comment]
> Ok. so from what I can understand, this is an issue on your end.
> 
> The poison zombie model was updated in the base game, including its `.ani` file, so it has episodic animations. (Many more models are also updated, list of which you can find in the changelog on wiki) You are using custom models but include the original `.ani` file for some reason (from your `models/zombie/poiani.mdl`). You should not be doing this. You should either ship your own `.ani` file for each model (You do ship `poiani.ani`, but you are not including it?), or if you wish to include the animations from the base game model, you should simply `$includemodel` the original model.
> 
> `.ani` files appear to be relying on the associated model file to load in correctly. This is how all other HL2 models handle including animations from separate models, they `$includemodel` the associated `.mdl` files.

Including the original model caused tons of other issues.

But whatever, I'll figure it out i guess.
