### ISSUE TITLE
CNewParticleEffect:AddControlPoint() always errors if not given attachment, takes attachment string instead of num

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-issues#6037]
Two minor issues with  CNewParticleEffect:AddControlPoint(), confirmed on both the main branch and the dev branch:

First, while the function has multiple PATTACH_ modes to choose from, only two of which use an attachment ID, the function will _always_ print an error in the console if you don't give it a valid attachment, even if it won't use it. This doesn't stop the function from working, but it clutters up the console, especially if you're making a lot of effects. You can get around this by supplying it with a valid attachment anyway (even though it won't be used), but it's impossible to avoid the error on a model with no attachments.

```
//Try to attach cpoint 0 to the attachment of one ent, and cpoint 1 to the origin of another ent
PrecacheParticleSystem("medicgun_beam_blue")
local p = CreateParticleSystem(ents.FindByClass("prop_physics")[1], "medicgun_beam_blue", PATTACH_POINT_FOLLOW, 1)
p:AddControlPoint(1, ents.FindByClass("npc_citizen")[1], PATTACH_ABSORIGIN_FOLLOW)
```
Result: Works as intended, but prints `Model '(null)' doesn't have attachment '' to attach particle system 'medicgun_beam_blue' to.` in console.
![Image](https://github.com/user-attachments/assets/fed0f3dd-2638-4b74-9a8d-4cfdba180dac)

Second, if you _do_ want to use an attachment, the function takes an attachment name string, not an ID number like every other CNewParticleEffect function, or as described in the wiki. (https://wiki.facepunch.com/gmod/CNewParticleEffect:AddControlPoint) I don't know if this is unintended behavior, or if the wiki is just wrong, but I'm reporting it anyway to be thorough. If you give it an ID number instead, it won't work and will also print the same error.

```
//Try to attach cpoint 0 to the attachment of one ent, and cpoint 1 to the attachment of another ent
local p = CreateParticleSystem(ents.FindByClass("prop_physics")[1], "medicgun_beam_blue", PATTACH_POINT_FOLLOW, 1)
p:AddControlPoint(1, ents.FindByClass("npc_citizen")[1], PATTACH_POINT_FOLLOW, 3)
```
Result: Doesn't work, still attaches to origin like the first picture, and prints `Model '(null)' doesn't have attachment '3' to attach particle system 'medicgun_beam_blue' to.` in console.

With a string instead:
```
//Try it again, but use a string instead of an id number for the second one
local p = CreateParticleSystem(ents.FindByClass("prop_physics")[1], "medicgun_beam_blue", PATTACH_POINT_FOLLOW, 1)
p:AddControlPoint(1, ents.FindByClass("npc_citizen")[1], PATTACH_POINT_FOLLOW, "chest")
```
Result: Works as intended, doesn't print anything in console.
![Image](https://github.com/user-attachments/assets/fbcd2687-7f68-4bec-873a-b2a1e184ddaf)

**Comment by robotboy655** [comment]
Fixed the first issue, and documented the argument correctly on wiki.
