### ISSUE TITLE
smoke_volime / AMBIENT_GENERIC

### ISSUE THREAD

**Issue by Mayorov0001** [Facepunch/garrysmod-issues#6044]
Greetings Rubat.

Relatively recently I created an o describing a problem with smoke_volume. This problem was fixed today - however, the exact same problem persists with ambient_generic.

Is there any possibility to fix this in a similar way?

---> https://github.com/Facepunch/garrysmod-issues/issues/5987

I sincerely apologise for opening a new appeal. 
My bad. I should have just opened the old one.

I apologise again.

**Comment by robotboy655** [comment]
Use soundscapes to play static/ambient sounds on your map, not a billion ambient_generic entities which would all be playing at the same time.

https://developer.valvesoftware.com/wiki/Soundscape
