### ISSUE TITLE
DataTable_ParseClientsFromBuffer Error. From Demos

### ISSUE THREAD

**Issue by DanielRabbit** [Facepunch/garrysmod-issues#6045]
### Details
<!-- When attempting to start a demo gives the error DataTable_ParseClientsFromBuffer
<!-- Branch is chromium updated to the latest version.

<!--N/A

### Steps to reproduce
<!-- Acquire a demo of yours. 
     - Put it in your demo file
     - Start the demo
     - Error: DataTable_ParseClientsFromBuffer
<!-- N/A

1.
2.

**Comment by DanielRabbit** [comment]
When opening a demo will make you receive the error DataTable_ParseClientsFromBuffer

**Comment by robotboy655** [comment]
Old demos are incompatible with newer versions of the game, I think due to networking changes. This is unfortunately a necessary evil with how the engine is.

I'd rather improve the game for everyone else then to keep old demos working, which is a very, very niche feature by itself.
