### ISSUE TITLE
Looping sound generated through sound.Generate can not be stop

### ISSUE THREAD

**Issue by Zanik231** [Facepunch/garrysmod-issues#6049]
**Details**
Tested on all branches. 2024.10.29
Tested on singleplayer.
Sound does not stop when using any of the gmod api's sound stop functions.
To stop sound you must enter stopsound in console.
**Steps to reproduce**
Input in console:
-- Init
sv_allowcslua 1
lua_run_cl frequency = 2000 
lua_run_cl samplerate = 44100
lua_run_cl function data( t )    return math.sin( t * math.pi * 2 / samplerate * frequency )end
lua_run_cl sound.Generate( "testgen", samplerate, 2, data, 0 )
-- First attempt
lua_run_cl a = Entity(1):StartLoopingSound("testgen")
lua_run_cl Entity(1):StopLoopingSound(a)
-- Second attempt
lua_run_cl a = CreateSound(Entity(1), "testgen")
lua_run_cl a:Play()
lua_run_cl a:Stop()
-- Third attempt
lua_run_cl a = Entity(1):EmitSound("testgen")
lua_run_cl Entity(1):StopSound("testgen")
In all attempts, the sound does not stop.

**Comment by robotboy655** [comment]
Fixed not being able to StopSound generated sounds, all 3 cases.
