### ISSUE TITLE
Weapon owner is `NULL Entity` in `SWEP:OnRemove` when weapon is removed by `Player:KillSilent()` since October 2024 update

### ISSUE THREAD

**Issue by luca1197** [Facepunch/garrysmod-issues#6051]
### Details
When a player is killed using `Player:KillSilent()`, the weapon owner retrieved in `SWEP:OnRemove` using `self:GetOwner()` is invalid / `NULL Entity` serverside. Clientside, it seems to work fine (the valid owner is returned).

This is the case since the October 2024 update. In the previous version, the valid owner of the weapon was returned.

I tested it on a game client (current main branch, current 64bit branch) and a fresh dedicated server (current main branch, current dev branch, pre October 2024 update main branch [Manifest [6646759056875658017](https://steamdb.info/depot/4022/history/?changeid=M:6646759056875658017)]).

Since it isn't uncommon to do something with the weapon owner when the weapon is removed, it'd be great if this could be addressed. (and maybe pushed to main and published before the next regular update :)) )

### Steps to reproduce
1. Call and store / output the result of `self:GetOwner()` in `SWEP:OnRemove`
2. `NULL Entity` is returned serverside, the valid owner is returned clientside

```lua
function SWEP:OnRemove()

    print("Self: ", self)

    local owner = self:GetOwner()

    print("Owner:", owner, IsValid(owner), self.Owner, IsValid(self.Owner))

    if IsValid(owner) then
        print("Alive:", owner:Alive())
    end

end
```
```lua
--- October 2024 update
Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 00:49:59 Oct 29 2024 (9488) (4000)
GMod version 2024.10.29, branch: unknown
Windows 32bit Dedicated Server

--- KillSilent (Owner is NULL Entity ❌)
] lua_run player.GetAll()[1]:KillSilent()
[SERVER] Self:     Weapon [76][testaddon_weapon]
[SERVER] Owner:    [NULL Entity]    false    [NULL Entity]    false

[CLIENT] Self:     Weapon [76][testaddon_weapon]
[CLIENT] Owner:    Player [1][Luca]    true    Player [1][Luca]    true
[CLIENT] Alive:    true

--- Kill (Works fine ✅)
] lua_run player.GetAll()[1]:Kill()
[SERVER] Self:     Weapon [76][testaddon_weapon]
[SERVER] Owner:    Player [1][Luca]    true    Player [1][Luca]    true
[SERVER] Alive:    false

[CLIENT] Self:     Weapon [76][testaddon_weapon]
[CLIENT] Owner:    Player [1][Luca]    true    Player [1][Luca]    true
[CLIENT] Alive:    true
```
```lua
-- Pre October 2024 update (Manifest 6646759056875658017)
-- (No client output since I can't join the server due to the version difference, shouldn't really matter though)
Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 17:28:13 Jul 24 2024 (9391) (4000)
GMod version 2024.10.29, branch: unknown
Windows 32bit Dedicated Server

--- KillSilent (Works fine ✅)
] lua_run player.GetAll()[1]:KillSilent()
[SERVER] Self:   Weapon [141][testaddon_weapon]
[SERVER] Owner:  Player [1][Bot01]       true    Player [1][Bot01]       true
[SERVER] Alive:  false

--- Kill (Works fine ✅)
] lua_run player.GetAll()[1]:Kill()
[SERVER] Self:   Weapon [135][testaddon_weapon]
[SERVER] Owner:  Player [1][Bot01]       true    Player [1][Bot01]       true
[SERVER] Alive:  false
```

**Comment by robotboy655** [comment]
This is a result of changes from https://github.com/Facepunch/garrysmod-issues/issues/5956

Since the weapon is dropped before it is removed, the owner is reset.

I have made it so that only the Lua binding (`Player:StripWeapons`) has the changed behavior. (Which is now consistent with `Player:StripWeapon`) This also fixes "spawning weapon in solid" warnings when dying outside of the map.
