### ISSUE TITLE
GM:PlayerAuthed - Called twice if UniqueID called before the normal call of PlayerAuthed after October Update

### ISSUE THREAD

**Issue by wgaylord** [Facepunch/garrysmod-issues#6053]
### Details
If  Player:UniqueID()  https://wiki.facepunch.com/gmod/Player:UniqueID is called before PlayerAuthed is normally called, the PlayerAuthed hook gets called once while UniqueID runs then once again when it would have normally been called.  

 If this is intended behavior, a note about this possibly breaking change and that it can happen should be made somewhere. 

This was found because on a server with Pointshop2 install (which uses LibK) the PlayerAuthed hook was getting called twice within 0.01 seconds of each other causing lag on player joins after the October Update.  It was tracked down to some code that called UniqueID during the OnEntityCreated hook. 

Also to be fully clear, if UniqueID is not called PlayerAuthed is called only once. If UniqueID is called before the PlayerAuthed hook is called the hook ends up called once during UniqueID's call and once as it would normally. 

### Steps to reproduce
This code reproduces the issue.
```
if SERVER then
	hook.Add("OnEntityCreated", "OnEntityCreated_Test", function(ply)
		if ply:IsValid() and ply:IsPlayer() then
			ply:UniqueID()
		end
	end)
	hook.Add("PlayerAuthed", "PlayerAuthed_Test", function(ply,steamid,uniqueid)
		MsgN("Player "..ply:Nick().." "..steamid.." "..uniqueid.." "..CurTime())
	end)
end

```

**Comment by robotboy655** [comment]
Will be fixed.
