### ISSUE TITLE
env_player_surface_trigger I/O problems

### ISSUE THREAD

**Issue by LambdaHidden** [Facepunch/garrysmod-issues#6056]
### Details
The entity doesn't detect when players leave the ground and go airborne. There's a comment in the entity's source code that says that's intentional, to stop bunny hoppers from avoiding the trigger, but there may be situations in which it is preferrable to detect this change. Since the entity doesn't have any spawnflags, one could be added for enabling this function.

Also, when a player triggers the entity, the `!activator` is the `env_player_surface_trigger`, not the player who did it. Changing this would make the entity more useful.

**Comment by robotboy655** [comment]
Added the spawnflag to trigger outputs on leaving the ground.

The activator thing is done on purpose for `sv_alternateticks`. The output is actually delayed, so there's simply no player object to reference for the output's activator.

I have added a second spawnflag to have the activator be the player, but this does change the way the outputs are fired (no longer delayed), so it may cause unexpected issues.
