### ISSUE TITLE
`GM:ClientSignOnStateChanged` is called for HLTV Clients.

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#6057]
### Details
So, `GM:ClientSignOnStateChanged` is also called for HLTV Clients since the engine calls `CBaseClient::SetSignOnState` in which it makes the call to the serverGameDLL.
The solution: the `CHLTVClient` should override that function with an empty implementation of it so that it won't make the call to the serverGameDLL.
Or you simply check if it's a HLTV client and then return.

### Steps to reproduce
1. Run `tv_enable 1`
2. Load a map
3. Run this: `lua_run hook.Add("ClientSignOnStateChanged","", print)`
4. Join the SourceTV Server.

**Comment by robotboy655** [comment]
Fixed.
