### ISSUE TITLE
DrawOverlay doesn't run on CLIENT

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-issues#6065]
DrawOverlay hook doesn't seems to be called in DEV branch, meanwhile on MAIN it does well

### Details
There's no mention or anyway to intercept how is the incompatibility possible between branches neither addons
But this breaks draganddrop, making you drag an invisible panel

### Steps to reproduce
Run this:
lua_run_cl hook.Add("DrawOverlay", "TEST", function() print(CurTime()) end)

1. On Main, it will print curtime as usual
2. On DEV, it won't print anything

On a extra note, this seems to be called for menu state for the pause menu as well, possible relation?

**Comment by robotboy655** [comment]
Fixed.
