### ISSUE TITLE
Tools Gizmo Red/Green are incorrectly angled.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#6068]
The gizmo inside of "-tools" mode is the incorrect angle.

For some reason, Red is where Green should be, and Green is where Red should be.

How to floof:
Open them tools.
Goto a particle effect.
Notice that the First Value in Position Within Sphere Random's velocity in local is for some reason going along the Green, instead of the Red.

![Image](https://github.com/user-attachments/assets/5fce7b32-1b9b-41bb-b362-8e32cf05c3a1)

**Comment by robotboy655** [comment]
![Image](https://github.com/user-attachments/assets/74c9fd6a-d040-4ebc-a1b0-7c9c6083df17)

I think it works correctly.

[Image](https://github.com/user-attachments/assets/a4dbe60d-b15b-4068-a5df-544150b05d01)

**Comment by MagentaIris** [comment]
That's funny, Because here's my shit.

![Image](https://github.com/user-attachments/assets/134cceb4-89f9-4ca4-ac92-9bee3dd80a69)

First number is flying it out of the green, The gizmo is angled wrong.

Here's my launch exe _`GarrysMod\bin\gmod.exe -windowed -noborder -nojoy -nosteamcontroller -nohltv -tools -noworkshop`_

**Comment by MagentaIris** [comment]
Just incase a picture isn't enough.

https://github.com/user-attachments/assets/23191271-be2d-4bca-8929-2a4728cc9b67

**Comment by MagentaIris** [comment]
As an EXTRA Note, Yes. This happens on BRAND NEW pcf's as well.

![Image](https://github.com/user-attachments/assets/dba87cad-d4ed-4a43-a79e-8d8e85f8bf17)

**Comment by robotboy655** [comment]
That would appear to be consistent with at least L4D2's particle editor, but I will make it set the first control point on panel creation, just for you.

**Comment by MagentaIris** [comment]
> That would appear to be consistent with at least L4D2's particle editor, but I will make it set the first control point on panel creation, just for you.

So it's due to the recent tools change, Fun stuff.

Main reason i'm marking this down as a problem is because some people might open tools mode not knowing this, So they will start to create particles using the incorrect velocity intigers and values.

**Comment by robotboy655** [comment]
> So it's due to the recent tools change, Fun stuff.

I do not know how you got to that conclusion, but it is not.

**Comment by MagentaIris** [comment]
> > So it's due to the recent tools change, Fun stuff.
> 
> I do not know how you got to that conclusion, but it is not.

No I mean, when tools was moved to the newer editor. This never used to happen with the older version (The version without previews)
