### ISSUE TITLE
Entity:GetVelocity always returns Vector(0,0,0) clientside on the latest x86-64 build

### ISSUE THREAD

**Issue by StyledStrike** [Facepunch/garrysmod-issues#6069]
After Garry's Mod updated just now, I noticed that `Entity:GetVelocity` is returning a 0 vector on the _CLIENT_ for props/scripted entities, even though it was working a couple of hours ago. 

![Image](https://github.com/user-attachments/assets/03eb8058-8f65-4190-a1d7-97ce8d0c2f01)
_That button was falling when I took this screenshot, see the code below for details._

### Details

To make sure it wasn't just an addon messing with it, before running the following test code, I made sure to:

- Have the `x86-64 - Chromium + 64 bit binaries` beta selected on Steam
- Use `-noworkshop` as a launch parameter
- Completely empty my `garrysmod/addons` folder, on the only exception being the code below

### Steps to reproduce

1. Create a lua file at: `GarrysMod\garrysmod\addons\velocity_test\lua\autorun\velocity_test.lua`
2. Copy and paste the following code to that file:

```lua
-- All this does is, let the client ask the server to
-- spawn a button prop when the local player fully loads,
-- then send that entity back to the client.
-- The client then just prints the prop's velocity every tick.

if SERVER then
    util.AddNetworkString( "velocity_test_setup" )
    util.AddNetworkString( "velocity_test_prop" )

    net.Receive( "velocity_test_setup", function( _, ply )
        local prop = ents.Create( "prop_physics" )
        prop:SetModel( "models/dav0r/buttons/button.mdl" )
        prop:SetPos( ply:GetPos() + Vector( 0, 0, 50 ) )
        prop:Spawn()

        net.Start( "velocity_test_prop" )
        net.WriteUInt( prop:EntIndex(), 32 )
        net.Send( ply )
    end )
end

if CLIENT then
    hook.Add( "InitPostEntity", "VelocityTest.Init", function()
        net.Start( "velocity_test_setup" )
        net.SendToServer()
    end )

    local propId

    net.Receive( "velocity_test_prop", function()
        propId = net.ReadUInt( 32 )
    end )

    hook.Add( "Think", "VelocityTest", function()
        if not propId then return end

        local prop = Entity( propId )

        if IsValid( prop ) then
            print( prop:GetVelocity() )
        end
    end )
end
```

3. Launch the game, start a new single player or local server game.
4. Type `developer 1` to make easier to watch whats being printed
5. Grab the button that should've spawned right above you, move it around or let it fall

That same code, when running on the "default" branch works as expected:

![Image](https://github.com/user-attachments/assets/6840202f-3b14-4d7d-9293-4cfea1131635)

### Version screenshot

![Image](https://github.com/user-attachments/assets/760748a8-3694-4534-a1b8-d7cc5ac481c0)

**Comment by robotboy655** [comment]
Thanks, will be fixed.
