### ISSUE TITLE
Newer engine PCF files don't have latest features + Screen particles crashes the game

### ISSUE THREAD

**Issue by siobhan-saoirse** [Facepunch/garrysmod-issues#6071]
### Details
Particles from the Left 4 Dead engine branch and newer may crash the game when used. I've tested it with -tools mode and looked at the boomer_fx.pcf file from Left 4 Dead 2. When i scrolled down to see the vomit particles, my game crashed. 

### Steps to reproduce

1. Enable -tools mode
2. Open the extracted boomer_fx.pcf file
3. Scroll down until you see vomit particles
4. A crash will occur when you reach further down the vomit particles.

**Comment by siobhan-saoirse** [comment]
I did not receive a dump file when this crash occurred.

**Comment by robotboy655** [comment]
Will be fixed.

**Comment by siobhan-saoirse** [comment]
K.
