### ISSUE TITLE
Harmless Rollermine is not harmless

### ISSUE THREAD

**Issue by Dobbi124** [Facepunch/garrysmod-issues#6072]
### Details
 The Harmless Rollermine will still do 5-10 prop damage when hitting into you 95% of the time.

### Branch
 x86-64 - Chromium + 64-bit binaries

### Steps to reproduce
Step 1: Spawn in Harmless Rollermine
Step 2: Let it travel and ram into you.

![Image](https://github.com/user-attachments/assets/9eaa942c-04aa-4732-9829-86405efaf8ff)

**Comment by robotboy655** [comment]
Whatever, it just needed a name that is not "friendly" because it is still considered an enemy.

**Comment by robotboy655** [comment]
To be clear, this is just the NPC from HL2 campaign, the Dog section.
