### ISSUE TITLE
Loading screen is dark in November

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-issues#6077]
### Details
The loading screen enables dark mode between 15th November and 5th December. This happens on any branch.

### Steps to reproduce

1. Start a singleplayer game between 15th November and 5th December.
2. See that the loading screen is dark.

### How to fix
This is happening because `isHalloween` is checking for `today.getMonth() == 10` which is November in Javascript as it is zero-indexed. I assume it's aiming for October.

Some solutions could be:
- Change it to month 9 (October in javascript). 
- Just remove the halloween check and use the system theme.
- Add a setting to Gmod itself which defaults to system theme (auto) but allows manually selecting either light or dark. This could then be used by the loading screen and potentially exposed to servers to customise their vgui or html panels.

**Comment by robotboy655** [comment]
Damn.
