### ISSUE TITLE
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "particle_name"!

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#6081]
When you use a particle with missing materials it seems to spam this error
`C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "particle_name"!`
However the error doesn't say *which* material is missing so it's annoyingly hard to easily fix

Having the material path in there would be great, the `IMaterial` seems to be already in there so it should be a simple fix.
![Image](https://github.com/user-attachments/assets/8bffafa5-9d29-42bf-92c2-30e07931a11f)

**Comment by robotboy655** [comment]
Done.
