### ISSUE TITLE
Grenade weapon only emits a throwing sound while crouched

### ISSUE THREAD

**Issue by KiwifruitDev** [Facepunch/garrysmod-issues#6083]
### Details

When throwing a grenade while standing, there is an error reported to the console:
```
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
```
However, throwing it while crouching will instead cause a sound to be played, `)weapons\slam\throw.wav`.

Tested in single-player with the Sandbox gamemode.

Version:
```
] version
Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 19:26:44 Nov 13 2024 (9488) (4000)
GMod version 2024.11.14, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce

1. Obtain at least 2 Frag Grenades
2. Equip and throw a grenade without crouching
3. Observe the error in console
4. Hold crouch and throw a second grenade
5. A sound was played

### Media
https://github.com/user-attachments/assets/62cbb3b2-a645-4438-9ee9-0bdb39d53761

**Comment by robotboy655** [comment]
This is intentional and is consistent with Half-Life 2, besides the console warning of course, which will be fixed.
