### ISSUE TITLE
Main branch reports itself as "prerelease" since the October 2024 update

### ISSUE THREAD

**Issue by thecraftianman** [Facepunch/garrysmod-issues#6085]
### Details

Pretty much just what the title says. I figure that this just slipped into the update by accident.

### Steps to reproduce

1. `lua_run print(BRANCH)` on main branch/"none" beta

**Comment by thecraftianman** [comment]
That's true, but previously main branch just called itself "main" and prerelease was "prerelease", whereas now both of them just report themselves as "prerelease" in-game. It's not really a big deal at all, but I assumed this change might've been accidental.

**Comment by robotboy655** [comment]
Ah I see, according to the wiki it used to say `unknown` for NONE beta, but it says `prerelease` now, even on the client. That is not intentional, I will fix that.

For dedicated servers it will still say `prerelease` on no beta, because again, there are no `main` builds.
