### ISSUE TITLE
Flashlight (env_projectedtexture) makes the map "background" white.

### ISSUE THREAD

**Issue by dmitykorolev2009** [Facepunch/garrysmod-issues#6086]
## Details

When env_projectedtexure is enabled, the background of the map becomes white.

This doesn't cause much of a problem during normal play, however it does interfere with planar reflections (such as func_reflective_glass with LightmappedReflective) working.

### A:
1. Turn on the flashlight or any env_projectedtexture.
2. Move outside the bounds of the map (using noclip).
3. The background of the map turns white.
### B:
1. Place any func_reflective_glass with refractions on the map.
2. Turn on the flashlight or any env_projectedtexture.
3. See the white background in reflections.

### Picture with screenshots for comparison:
![Image](https://github.com/user-attachments/assets/0bcaa9b3-ec2f-486c-9010-3278762fca53)

## Version
Exe version 2024.10.29 (garrysmod)
Exe build: 00:49:59 Oct 29 2024 (9488) (4000)
GMod version 2024.10.29, branch: unknown, multicore: 0
Windows 32bit

Bug also appears in the x86-64 branch.

mat_dxlevel 95
Maximum graphics settings.

My GPU: AMD RX470
GPU driver version: Adrenalin Edition 24.9.1 (Latest)

**Comment by robotboy655** [comment]
Do you have a map link that can exhibit the issue with the reflections like in your second picture?

**Comment by dmitykorolev2009** [comment]
As I said earlier, this bug can be reproduced on any map, so I made a simple map to show it.
![Image](https://github.com/user-attachments/assets/57aa6a38-72d3-4c5d-b052-030d446fd01d)
![Image](https://github.com/user-attachments/assets/87012a6d-5ff5-4a56-8c3b-c74ac05fa949)

[https://github.com/dmitykorolev2009/reftest-map/blob/5e0996127c14134a0631c74864fa674c90b3600c/reftest.bsp](url)

**Comment by robotboy655** [comment]
Changed it to be black when the flashlight is on. We shall see if this causes any side effects.

To be fair, your mirror thing is definitely too close to the map edge, which is likely why this issue happens. You can actually see outside of the map if you look at the reflection at a certain angle.
