### ISSUE TITLE
Player hands parenting issues involving fully clientside viewmodels in singleplayer

### ISSUE THREAD

**Issue by littlebabyman** [Facepunch/garrysmod-issues#6090]
### Details

Using either x86-64 or dev beta branch, a number of weapons utilizing player hands and clientside viewmodel implementations (prominently Customizable Weaponry 2.0, allowing the usage of player hands) cause hands to vanish upon switching to other weapons using the predicted viewmodel entity.

### Steps to reproduce

1. Install [[CW 2.0] Sharksenal](https://steamcommunity.com/sharedfiles/filedetails/?id=3334029450) with its requirements.
2. Equip one of the weapons in-game and switch from it to any engine weapon. Many scripted weapons using engine predicted viewmodels are affected aswell.

**Comment by robotboy655** [comment]
Related PR: https://github.com/Facepunch/garrysmod/pull/2143

**Comment by Ha2ard01** [comment]
> Related PR: [Facepunch/garrysmod#2143](https://github.com/Facepunch/garrysmod/pull/2143) 相关 PR： [Facepunch/garrysmod#2143](https://github.com/Facepunch/garrysmod/pull/2143)

This fix still doesn't solve viewmodel problem...

**Comment by robotboy655** [comment]
Will be fixed later today.
