### ISSUE TITLE
Crash on hitting the entity limit, might be fixable.

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#6091]
Currently when you hit the entity limit `Sys_Error` gets called causing a crash. I think console will get spammed with `Warning: free edicts below threshold` `g_Log.Printf( "Warning: free edicts below threshold. %i free edict%s remaining.\n", nEdictsRemaining, nEdictsRemaining == 1 ? "" : "s" );` before it crashes.
![Image](https://github.com/user-attachments/assets/19c7e8c0-a002-4a17-b898-e4c6a226f50e)

However seemingly in the code above, the function is able to return `NULL` to prevent anything from happening, it might be possible to instead return `NULL` when the edict limit is hit, this still wont be great but it wouldn't cause a direct server crash.
![Image](https://github.com/user-attachments/assets/0db65fc2-95fc-442d-80ad-1a09f224655a)

For anyone reading this that had a crash due to this, the convar `sv_lowedict_action` can be used to "catch" them sorta early.
![Image](https://github.com/user-attachments/assets/0b672d98-7116-4728-affc-b6a4b5d0d0fc)

**Comment by robotboy655** [comment]
The game already has safeguards against hitting the hard limit and causing a crash, you will not be able to reach it with for example spawning props in Sandbox.

**Comment by wrefgtzweve** [comment]
I managed to get this crash with ~60 players regularly playing on sandbox, is there that much harm to not hard crash and just return NULL here?

**Comment by wrefgtzweve** [comment]
![Image](https://github.com/user-attachments/assets/e2b3c9c2-045e-4fc6-b307-26ab4a365d74)
I spammed
`bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;bot;`
a few times on a 128 slot server

crashed

**Comment by robotboy655** [comment]
Huh? You'd reach the max player count way before hitting any edict count, unless you are spamming that while already at edict count?

**Comment by wrefgtzweve** [comment]
Seems erroring in the player death hook specifically triggered it in that case. `lua_run hook.Add("PlayerDeath", "test", function() error() end)`

**Comment by robotboy655** [comment]
Ok that was a lot less mysterious, but I have adjusted the safeguards to also check for allocated edicts with a smaller buffer.
