### ISSUE TITLE
Super Charged Gravity Gun cannot pick up prop/ragdoll with "flesh" surface property.

### ISSUE THREAD

**Issue by IBRS-4Ever** [Facepunch/garrysmod-issues#6097]
### Details

The Super Charged Gravity Gun can't pick up prop/ragdoll with "flesh" surface property (Secondary Attack), but can punt "fleshy" prop/ragdoll (Primary Attack), the only way to pick up a "fleshy" ragdoll is to kill a NPC with Secondary Attack, and once you drop it, you cannot pick it up again.

### Steps to reproduce

1.Load a map
2.Enable Super Charged Gravity Gun
3.Spawn a NPC (Combine Soldier, Zombie etc)
4.Kill it with Super Charged Gravity Gun
5.Try to pick up the ragdoll

**Comment by robotboy655** [comment]
Will be fixed.
