### ISSUE TITLE
Faceposing is buggy with ragdolls using the Facial Action Control System 

### ISSUE THREAD

**Issue by LurkyLurker** [Facepunch/garrysmod-issues#61]
Been having this problem for some time now. Any and all ragdolls using the Half-Life 2 Facial Action Control System have improper and buggy eyelid flexes when using the face poser tool on them.

To demonstrate, here's the stock HL2 group01/male_04 citizen. Default face.
![hl2citizen_default](https://f.cloud.github.com/assets/4642528/625387/91fd3dae-cf9e-11e2-9686-501a83bfcb05.jpg)

Same model. Selected with the faceposer tool with no changes. Notice the subtle eyelid droop.
![hl2citizen_toolengaged](https://f.cloud.github.com/assets/4642528/625391/9a08dddc-cf9e-11e2-8a5d-f2227b3d8c37.jpg)

Same model. With "blink" flex raised to full. Notice how the eyelids have raised instead of lowered.
![hl2citizen_blinkinvert](https://f.cloud.github.com/assets/4642528/625395/a2ab2e2c-cf9e-11e2-9b87-45977747b1fd.jpg)

Same model. With "blink" flex inverted via console commands. The eyelids have lowered, but refuse to close.
![hl2citizen_blinknoclose](https://f.cloud.github.com/assets/4642528/625397/af023d1e-cf9e-11e2-894a-91f59a1487ab.jpg)

This issue usually only affects eyelid flexes, but I've seen bugs with other ragdolls faceposing (L4D bill's chin raiser, vortigaunt) that can probably be traced to this issue as well.

Models that use flexes that are not based on the FACS do not have this problem. 

Using Windows 7, 64-bit. If that's any help.

**Comment by drSo** [comment]
This bug still persists.
Also what @DeadMansChest said is still an issue.

**Comment by robotboy655** [comment]
Eye flexes are fixed in the next update.
