### ISSUE TITLE
`engine.CloseServer()` does not work until `GM:InitPostEntity()` is called.

### ISSUE THREAD

**Issue by xCynDev** [Facepunch/garrysmod-issues#6102]
### Details

Title. `engine.CloseServer()` will silently fail if you call it before `GM:InitPostEntity()` is called. It would be useful to have it work before that, for cases where we do not want to wait or continue processing until `InitPostEntity`.

If anything, perhaps add a new argument to the function, like `force` which would immediately kill the server. 

### Steps to reproduce

1. Try to run `engine.CloseServer()` in an addon's init script, with `-allowquit` in the server's commandline.
2. It won't work.
3. Run it in a `GM:InitPostEntity` hook, and it will.

**Comment by robotboy655** [comment]
Why do you need to shutdown a server before it even started is my question.

**Comment by xCynDev** [comment]
If I deem the server is in an invalid state for whatever reason, I'd like to shut it down in code.

**Comment by robotboy655** [comment]
Will be fixed.
