### ISSUE TITLE
Broken force impulse on clientside player ragdolls

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#6103]
### Details
Player corpses always have their impulses applied to the center of ragdoll rather than the area they were shot in.
Comparison between players and NPCs:

https://github.com/user-attachments/assets/59b4a04b-145b-468f-af52-43f54f38c252

https://github.com/user-attachments/assets/3d28246f-6357-4b6c-a051-3fa3e30c7543

### Steps to reproduce
Create a bot in multiplayer and shoot it in any body part

**Comment by robotboy655** [comment]
Will be fixed.
