### ISSUE TITLE
DAdjustableModelPanel sensitivity goes crazy with esc menu open

### ISSUE THREAD

**Issue by blobles-dev** [Facepunch/garrysmod-issues#6106]
### Details
As the title suggests, DAdjustableModelPanel behave very weird with the ESC menu open. Not only is the sensitivity increased a huge amount, but without even moving the mouse the model will flicker around

### Steps to reproduce

```
concommand.Add("modelpaneltest", function()
    local frame = vgui.Create("DFrame")
    frame:SetSize(400, 600)
    frame:Center()
    frame:SetTitle("DAdjustableModelPanel Test")
    frame:MakePopup()

    local modelPanel = vgui.Create("DAdjustableModelPanel", frame)
    modelPanel:Dock(FILL)
    modelPanel:SetModel("models/player/charple.mdl")
end)
```

1. Run above code on the client and run the modelpaneltest concommand
2. Adjust the model as usual
3. Open the escape menu
4. Adjust the model & obersve

## System
**Client:**
Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 00:49:59 Oct 29 2024 (9488) (4000)
GMod version 2024.10.29, branch: unknown, multicore: 0
Windows 32bit

**Dedicated server (if that even matters):**
Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 00:49:59 Oct 29 2024 (9488) (4000)
GMod version 2024.10.29, branch: unknown
Windows 32bit Dedicated Server

![Example](https://media.discordapp.net/attachments/567617926991970306/1315431382138490911/hl2_WdggoZAFuu.gif?ex=67576271&is=675610f1&hm=e3a71b58193bb8447a6fd04c9ca99732e5a347a296f5bc60503640ae573a05cb&=&width=883&height=662)

**Comment by blobles-dev** [comment]
This appears to be due to SetCursorPos being blocked when the main menu is open

https://commits.facepunch.com/501884 - Block gui/input.SetCursorPos while main menu is open

Likely also will effect other VGUI elements which use SetCursorPos internally

**Comment by robotboy655** [comment]
Made it do nothing instead of spazzing out when main menu is open.
