### ISSUE TITLE
Removing func_tank that is in use by an NPC crashes the game

### ISSUE THREAD

**Issue by SageJFox** [Facepunch/garrysmod-issues#6108]
### Details
Tested on latest public release of the 64-bit beta branch.

As the title says, if a func_tank is removed while an NPC is currently firing it, the game crashes. Both single and multiplayer.

### Steps to reproduce
An easy way to see it is to load up d3_c17_06a from Half-Life 2 in singleplayer.
1. Head through the map (noclipping is fine, the map is a straight shot from spawn to the barricades) until you can see the civil protection officers behind the barricades (if you get too close to them a trigger will fire that makes them unman the guns).
2. Wait for them to man the turrets and start shooting at you.
3. enter `ent_fire turret_1 kill` into console while the turret to your left is firing (the right one is turret_2). The game will crash immediately upon unpausing.

Note that if you enter `ent_fire turret_1 forcenpcoff` beforehand, the crash does not occur. Also note that the func_tanks are parented to the gun models, so `ent_fire turret_1_model kill` also produces the crash.

**Comment by robotboy655** [comment]
Should be fixed on `dev` today.
