### ISSUE TITLE
Missing gmod.exe on recent x86-x64 change

### ISSUE THREAD

**Issue by KiwontaTv** [Facepunch/garrysmod-issues#6109]
### Details

When trying to run the game on dev/x64 build, it says the gmod.exe is missing. This is due to some mistake that was done to rename the hl2.exe to gmod.exe.

### Steps to reproduce

1. Be on x86-x64
2. Run the game

[Preview](https://print-screen.dev/content/610adfee9058e/steamwebhelper_hQGDQKN8AY.png)

**Comment by robotboy655** [comment]
Fixed.
