### ISSUE TITLE
Hammer still looking for hl2.exe

### ISSUE THREAD

**Issue by Pinsplash** [Facepunch/garrysmod-issues#6110]
Apparently in today's update you changed the game's exe name to gmod.exe, but did not mirror this in GameConfig.txt. When you compile a map, it still looks for hl2.exe.

**Comment by robotboy655** [comment]
My bad. You will need to delete your `GameConfig.txt` to regenerate it to use `gmod.exe`, or simply change the path in the Hammer options menu.

It should be fixed on `dev` when that updates in a few minutes, I will push the fix for the other versions of the game a bit later.
