### ISSUE TITLE
NPC Zombie Torso no head animation

### ISSUE THREAD

**Issue by Hauwler** [Facepunch/garrysmod-issues#6111]
### Details
When i spawn in the Zombie Torso NPC, he moves and his headcrab clips through the head because the head isnt moving at all, it doesnt move with the body.(i disabled headcrab bodygroup and saw it)

i have TF2,all HLs (1,2, all DMs and Lost Coast),all L4Ds (L4D1,L4D2),DoD source,all cs (CSS,CSGO) and all Portal games (P1,P2) mounted
0 mods

Protocol version 24
Exe version 2024.10.29 (garrysmod)
Exe build: 18:32:12 Nov 29 2024 (9519) (4000)
GMod version 2024.12.09, branch: x86-64, multicore: 1
Windows 64bit

### Steps to reproduce

1.spawn in Zombie Torso NPC 
2.look at it and watch the head clip
3.disable headcrab bodygroup to confirm

**Comment by robotboy655** [comment]
This is the case in all Half-Life 2 games, even post anniversary update.
