### ISSUE TITLE
Calling Panel:GetChildren() on CHudChat (or any chat panels) returns an empty table

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-issues#6133]
### Details

like the title mentions, i can't seem to access any chat panel children even though Panel:ChildCount() shows there are some
i tested on both none and x86-64 branches, and i've used both Panel:GetChild(idx) and Panel:GetChildren()
my use case for getting the chat child panels is for modifying some elements in chat

### Steps to reproduce

Sample code:
```
timer.Create("test", 1, 0, function()
	if not vgui.GetHoveredPanel() then return end
	print("hovered panel:", vgui.GetHoveredPanel(), "childcount:", vgui.GetHoveredPanel():ChildCount(), "first child:", vgui.GetHoveredPanel():GetChild(0), "getchildren table len:", table.Count(vgui.GetHoveredPanel():GetChildren()))
end)
```

Result when hovering over the chat's gray top bar (line 1), over the hud (line 2), and over a part of chat which also has unretrievable children (line 3)
```
hovered panel:	Panel: [name:HudChat][class:CHudChat][20,312,600,437]	childcount:	5	first child:	nil	getchildren table len:	0
hovered panel:	Panel: [name:GModBase][class:CGModBase][0,0,1600,900]	childcount:	29	first child:	Panel: [name:ControlPanel][class:Panel][0,0,16,16]	getchildren table len:	28
hovered panel:	Panel: [name:ChatInputLine][class:Panel][18,409,562,16]	childcount:	2	first child:	nil	getchildren table len:	0
```

**Comment by robotboy655** [comment]
You cannot access engine panels (non Lua created) via Lua.  This is not a bug, its intentional.

**Comment by Andrew-Eathan** [comment]
but why? it used to work, and now that it's not possible anymore it affects a legitimate use case i had for accessing them, i can't figure out any reason why it should be restricted now

**Comment by robotboy655** [comment]
It was changed due to security issues it enabled in the past. It will not be changed back. I understand that it limits some things.
