### ISSUE TITLE
"FactoryReset-GMod.bat" doesn't work

### ISSUE THREAD

**Issue by CharlesKTo** [Facepunch/garrysmod-issues#6136]
### Details

File "FactoryReset-GMod.bat" doesn't work. It closes after open. I tried to open it with cmd and it showed this: "Game binary doesn't exist. Are you executing this script from the wrong directory?". I think it's because of this:

```
::We don't want people running this in the wrong place
IF NOT EXIST ".\hl2.exe" (
	ECHO Game binary doesn't exist. Are you executing this script from the wrong directory?
	EXIT /B 1
)
``` 
I think the reason for the error is that .bat file is trying to find "hl2.exe" in the "GarrysMod" folder, but it can't because it was renamed to "gmod.exe" in one of the game updates.

### Steps to reproduce

1. Open "GarrysMod" folder
2. Open "FactoryReset-GMod.bat"

**Comment by robotboy655** [comment]
It's already fixed in the betas for the next update.
