### ISSUE TITLE
DLabel/DButton SetTextInset Inconsistent between main and x86-64

### ISSUE THREAD

**Issue by Srlion** [Facepunch/garrysmod-issues#6137]
### Steps to reproduce

```lua
dframe = vgui.Create("DFrame")
dframe:SetSize(100, 200)
dframe:Center()
dframe:MakePopup()

local button = vgui.Create("DButton", dframe)
button:SetText("Im testing")
button:SetTextInset(15, 0)
button:SizeToContentsX()
button:Center()
```
main
![Image](https://github.com/user-attachments/assets/e26351da-c07d-4c90-86d5-ba6d972c6376)

x86-64

![Image](https://github.com/user-attachments/assets/e724dd6b-903c-4ff5-bb96-970fe5761467)

**Comment by robotboy655** [comment]
The changes on `x86-64` are not live on main yet. You can see the current difference here:

https://wiki.facepunch.com/gmod/Update_Preview_Changelog

Specifically:
> Improved X-axis text inset handling with center alignment (for DButton when an icon is use)

**Comment by Srlion** [comment]
> The changes on `x86-64` are not live on main yet. You can see the current difference here:
> 
> https://wiki.facepunch.com/gmod/Update_Preview_Changelog
> 
> Specifically:
> 
> > Improved X-axis text inset handling with center alignment (for DButton when an icon is use)

But that change affects DButtons that don't use an icon and also DLabels, that changes the behavior completly :/

**Comment by Srlion** [comment]
Hold up, I don't use an icon and manually using `SetTextInset` [This change here](https://github.com/Facepunch/garrysmod/blob/5b5fa7dcd58270c53b0c9a9f4d4a447fdd52c424/garrysmod/lua/vgui/dbutton.lua#L121) shouldn't affect the code I provided? I don't even use DButton, I have a custom version built on top of `Label` and got that issue.

**Comment by robotboy655** [comment]
What is the "issue" exactly? That the text inset is working correctly? I don't understand.

**Comment by Srlion** [comment]
The text inset works but it's not centered like the main branch, you can clearly see a difference there, I'm not sure what is happening. I will test on dev branch though.

**Comment by Srlion** [comment]
dev branch has the same issue, reverting your commit in dbutton does nothing, there is a change in `SetTextInset`, I don't mind it but at least what is the change that happened so I can fix it in my addons before dev is released?

**Comment by Srlion** [comment]
Yeah I assumed that after playing with it that it wasn't working, thank you for the explanation. If possible to add it in changes so people can know about it.

**Comment by robotboy655** [comment]
It is already in the change log linked above.

**Comment by Srlion** [comment]
Oops, I got confused as it doesn't say that it fixes it and there is a commit for DButton that plays with TextInset lol
