### ISSUE TITLE
Server crashes increase exponentially on auto-refresh with more than 1 player in the server with 1 vehicle spawned.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#636]
As the title states; I've experienced server crashes when editing lights of a vehicle. This isn't the ONLY time it crashes.

This is a file which is loaded by the client so it should have no effect on the crash. This happens on ANY file I edit; but primarily on lighting as I update those most often. Even with a light editing tool that I wrote, I still paste the entire contents in, save, then do the next vehicle. With hundreds of vehicles, you get the idea.

It does not only happen with more than 1 player. The lighting files were given as an example, it can happen with any other file I load too.

Here are the scenarios:

1 player, myself, modifying files on auto-refresh. 99.9% stable, seldom crashes with 1 vehicle spawned; it does happen.

1 player, myself, modifying files on auto-refresh. 100% stable with 0 vehicles in the server.

more than 1 player, myself and a friend or more. UNKNOWN% stable with 1 vehicle spawned. Crashes FREQUENTLY when auto-refreshing. It crashes almost 100% of the time with auto-refresh.

More than 1 player, more than 1 vehicle, same thing. It can be 1 vehicle, or many vehicles. The issue appears to be with autorefreshing with vehicles spawned. I made a "fix" by despawning ALL vehicles OnReloaded; and that resolved the issue and made the server 100% stable when autorefreshing with more than 1 player and more than 1 vehicle.

This is an issue, and should be fixed because it can happen when I'm alone, SELDEM, or when it's live. The point of auto-refresh is to be able to modify the game-mode as a development environment tool which is FANTASTIC and I'm trying to pitch Garry's Mod to high-schools across the nation as a learning aid for more sales because of it. But, if the servers keep crashing because a prop_vehicle_jeep is spawned with more than 1 player, it defeats the ability to auto-refresh on a production server to add new features or fix bugs.

I use a recursive, dynamic, game-mode load system. Here's the load order:
https://dl.dropboxusercontent.com/u/26074909/tutoring/file_structure/File_Load_Order.txt

Here are the realms files:
https://dl.dropboxusercontent.com/u/26074909/tutoring/file_structure/Client_Files.txt
https://dl.dropboxusercontent.com/u/26074909/tutoring/file_structure/Shared_Files.txt
https://dl.dropboxusercontent.com/u/26074909/tutoring/file_structure/Server_Files.txt

And the latest crash which just happened:
https://dl.dropboxusercontent.com/u/26074909/debugging/garrysmod/crashes/vehicle_in_server_auto_refresh_crashes/srcds_20131214_191509_1_PureClass.mdmp

Another crash -- This crashed on changelevel after the server was up for 3 days, or from auto-refresh with vehicle in the server:
https://dl.dropboxusercontent.com/u/26074909/debugging/garrysmod/crashes/vehicle_in_server_auto_refresh_crashes/srcds_2000247_crash_2013_12_9T21_39_51C0.mdmp

**Comment by NathanX-S** [comment]
@robotboy655

**Comment by robotboy655** [comment]
Give dumps/ways to reproduce, the ones from 2013 are unusable.

**Comment by robotboy655** [comment]
Closing as stale.
