### ISSUE TITLE
PlayerButtonDown / PlayerButtonUp do not properly detect all buttons depending on when you push them; calls release when key not released!

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#645]
PRESS	57	FORWARD
PRESS	29	BACK
PRESS	14	RIGHT
PRESS	11	LEFT

57 is CONSOLE

I've pasted the key next. In the following output, I am going to HOLD the forward key, then press other keys from WASD.

PRESS	57
Holding!	
RELEASE	57

Notice no others were detecting. Holding is simply logging the time when a key was pressed, starting a .5 second timer to see if they have yet to release the button based on my times.

Now, I will hold D/Right and press the other keys from WASD in that order.
PRESS	14	
Holding!	
PRESS	33	???
RELEASE	14	Even though it is still held
Holding!	
PRESS	14	Even though it is still held
RELEASE	33	???
Holding!	
PRESS	29	???
RELEASE	14	Even though it is still held
Holding!	
PRESS	14	Even though it is still held
RELEASE	29	???
RELEASE	14	Now it is proper

So, even though a key is held; some buttons will detect and others will not. It will "release" the first key that was pressed.

```lua
hook.Add( "PlayerButtonDown", "BindsManager:KeyPress", function ( ply, _button ) 
	print( "PRESS", _button )
end );

hook.Add( "PlayerButtonUp", "BindsManager:KeyRelease", function ( ply, _button ) 
	print( "RELEASE", _button )
end );
```

**Comment by willox** [comment]
I suppose this is fixed too.
