### ISSUE TITLE
Workshop does not download on server-startup collections linked to main collection

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#646]
I linked a collection to my server collection in hopes that I could clean up the downloads. It linked fine, however it will not download claiming bad headers. 

I have yet to test this on the client-side if it downloads; but this defeats the purpose of linking collections. I don't know if this i can be fixed on Garry's Side, if not, I'd like to ask that Garry bring this up with Valve.

**Comment by TheClonker** [comment]
Problem still persists, any update on this ?

**Comment by robotboy655** [comment]
It will come with ISteamUGC.

**Comment by robotboy655** [comment]
Currently we are waiting for Valve to fix ISteamUGC for "old style" workshop items.

**Comment by TheClonker** [comment]
Ok thank you for the Info!

**Comment by robotboy655** [comment]
Sound be solved on Dev branch.

**Comment by TheClonker** [comment]
Works as intended, thank you very much :)

**Comment by mbaehr2909** [comment]
This problem still seems to persist. 
I have three Collections (one "Server", where the Collections "Weapons" and "Maps" are linked). The Server does not Download the Collections.

It gives me the following error:
Assigned anonymous gameserver Steam ID [A-1:1774444551(9164)].
Done!
Extracting...
Mounting Addon 'Wodanheim T Items' (1139909751)
Downloading...
VAC secure mode is activated.
Done!
Extracting...
Mounting Addon '' (1150181180)
Downloading...
Not loading addon 'addons/ds_1139908417.gma' - addon header invalid
Couldn't mount addon [Wodanheim Maps][addons/ds_1139908417.gma]
Removing bad addon addons/ds_1139908417.gma
Not loading addon 'addons/ds_1139909751.gma' - addon header invalid
Couldn't mount addon [Wodanheim T Items][addons/ds_1139909751.gma]
Removing bad addon addons/ds_1139909751.gma

**Comment by robotboy655** [comment]
Your server is extremely out of date
