### ISSUE TITLE
Garry is a cunt toward the Linux community

### ISSUE THREAD

**Issue by lookatmema** [Facepunch/garrysmod-issues#65]
As the title says, Garry Newman ( garry :D ) is a cunt. I've been able to reproduce this many times in the past 4 years. [Here's some proof when reproducing this bug](https://twitter.com/garrynewman/status/343128562745892865)

Possible workarounds:
1. Separate garrynewman from society
2. Stop insulting the world's best software(and by relation, its community)
3. Don't feed the troll.

**Comment by yureegasven** [comment]
Just want to say I play it on GNU/Linux but I'm probably not counted in the stats because I bought this game long before it was available on GNU/Linux. I believe most are in the same boat.
