### ISSUE TITLE
[Linux] Missing bin/filesystem_steam.so

### ISSUE THREAD

**Issue by 94k** [Facepunch/garrysmod-issues#650]
Starting Garry's Mod in linux alway fails with the message

"AppFramework : Unable to load module /absolute/path/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod/bin/filesystem_steam.so!"

I tried reinstalling, checking the files, changing to the beta and back (both, Garry's Mod and Steam), even starting the game in windowed mode (I had a problem with source games and my tiling WM a couple of months back) but nothing works. Checking the files reveals that the file in question is in fact missing. Here's some console output:

```
[0|irvin|%|~] cd Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod 
[0|irvin|%|~/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod] ./hl2.sh 
AppFramework : Unable to load module /absolute/path/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod/bin/filesystem_steam.so!
[0|1|irvin|%|~/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod] cd bin
[0|irvin|%|~/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod/bin] ls
Awesomium            datacache.so            filters                libcef.so                 libudev.so.0       shaderapiempty.so      vidcfg.bin
Awesomium.framework  dedicated.so            GameUI.so              libffmpegsumo.so          libvstdlib.so      soundemittersystem.so  video_services.so
awesomium_process    dxsupport.cfg           gmod_audio.so          libprofiler.so.0          materialsystem.so  stdshader_dx9.so       video_webm.so
base.fgd             dxsupport.csv           halflife2.fgd          libSDL2-2.0.so.0          replay.so          steam_appid.txt        vphysics.so
basehaptics.txt      dxsupport_episodic.cfg  inputsystem.so         libsteam_api.so           scenefilecache.so  studiorender.so        vtex_dll.so
bsppack.so           dxsupport_sp.cfg        launcher.so            libtcmalloc_minimal.so.4  sdk.fgd            vaudio_speex.so
chromehtml.so        engine.so               libawesomium-1-7.so.0  libtier0.so               ServerBrowser.so   vgui2.so
CmdSeq.wc            filesystem_stdio.so     libbass.so             libtogl.so                shaderapidx9.so    vguimatsurface.so
[0|irvin|%|~/Datadump/Games/SteamLibrary/SteamApps/common/GarrysMod/bin] 
```

Usually I simply softlink libraries to solve those issues (temporarly) but there's no file with a similar name. Note that I tried different parameters after hl2.sh but none worked for me so far.

I'm using Archlinux 64bit with the newest steam package from multilib.

Edit:

The game "No More Room in Hell" comes up with the same issue; I'm still lost.

**Comment by pirenaico** [comment]
Same here, running on Linux Mind Debian Edition 64. If i execute GMOD on Steam i see the blue loading screen for five seconds and it shuts down.
On console, running hl2_linux only tells me
AppFramework : Unable to load module /home/carlos/.steam/steam/steamapps/common/GarrysMod/bin/filesystem_stdio.so!
Here is my bin folder
Awesomium		gmad_linux		  materialsystem.so
Awesomium.framework	gmod_audio.so		  replay.so
awesomium_process	gmpublish_linux		  scenefilecache.so
base.fgd		halflife2.fgd		  sdk.fgd
basehaptics.txt		inputsystem.so		  ServerBrowser.so
bsppack.so		launcher.so		  shaderapidx9.so
chromehtml.so		libawesomium-1-7.so.0	  shaderapiempty.so
CmdSeq.wc		libawesomium-1-7.so.2	  soundemittersystem.so
datacache.so		libbass.so		  stdshader_dx9.so
dedicated.so		libcef.so		  steam_appid.txt
dxsupport.cfg		libffmpegsumo.so	  studiorender.so
dxsupport.csv		libprofiler.so.0	  vaudio_speex.so
dxsupport_episodic.cfg	libSDL2-2.0.so.0	  vgui2.so
dxsupport_sp.cfg	libsteam_api.so		  vguimatsurface.so
engine.so		libtcmalloc_minimal.so.4  vidcfg.bin
filesystem_stdio.so	libtier0.so		  video_services.so
filters			libtogl.so		  video_webm.so
GameUI.so		libudev.so.0		  vphysics.so
garrysmod.fgd		libvstdlib.so		  vtex_dll.so


and running hl2.sh
hl2.sh: 9: cd: can't cd to hl2.sh
hl2.sh: 13: [: Linux: unexpected operator
hl2.sh: 16: [: Linux: unexpected operator
hl2.sh: 22: [: Linux: unexpected operator
hl2.sh: 24: [: Linux: unexpected operator
hl2.sh: 49: [: unexpected operator
hl2.sh: 49: [: unexpected operator
hl2.sh: 64: hl2.sh: /: Permission denied
I have an almost complete Valve games collection and all of them run without any problems.

**Comment by trinitronx** [comment]
This bug also seems related: ValveSoftware/Source-1-Games#1685

I am seeing this problem on a 64bit Linux system with steam library installed to a large XFS RAID array.  The bug report details match my use case, but the weird thing is that `filesystem_steam.so` does not exist in any of my old Source engine game directories.  Just like in this bug report...

Does the engine expect to create this file on launch somehow?  I can't imagine that it's dynamically compiling this library `.so` file... maybe extracting it?  It does seem more likely to be a packaging issue at the moment, and it's apparently affecting many original Source engine games.

**Comment by robotboy655** [comment]
The game no longer tries to load `filesystem_steam`, ever.
