### ISSUE TITLE
Searching Servers on linux, Cannot delete text

### ISSUE THREAD

**Issue by DiJuMx** [Facepunch/garrysmod-issues#700]
When searching for servers, backspace, arrow keys, and delete do not work. I.e. it is only possible to add characters to the search box, not remove them.

Also, if you go back to the gamemode list (from the server list), after inputting a search term, returning to the server list does not clear the search box.

**Comment by MinIsMin** [comment]
Can confirm on Ubuntu 16.04, also happens on the "server password" textbox.
You can't remove characters, but no character is added.

**Comment by MinIsMin** [comment]
Still happening on Ubuntu 18.04, Gmod Prerelease.
Also, when selecting text it gets hidden.

![bug](https://user-images.githubusercontent.com/18466226/40481421-f7ed9d7a-5f40-11e8-96bd-e7884542c494.gif)

On the **chromium** branch it works fine!

**Comment by rbreslow** [comment]
See: https://github.com/Facepunch/garrysmod-issues/issues/176#issuecomment-528925807. 

Looks like these issues could be consolidated.
