### ISSUE TITLE
Closing pack file with -1 open files! crash when loading maps from content folder

### ISSUE THREAD

**Issue by JetBoom** [Facepunch/garrysmod-issues#717]
If you have a map inside your gamemode content/maps folder, the game will crash if you attempt to load it twice in a row with the engine error in the title.

If you switch to a different map first then the crash has a low chance of happening, but still happens randomly on map changes.

Does not go away if you have the map in both content/maps and garrysmod/maps.
DOES go away if you ONLY have it in garrysmod/maps.

**Comment by willox** [comment]
I believe that the 2nd February 2016 Hotfix solved this issue. (The change involved all pack files).

```
FIX
Game no longer crashes when attempting to mount a VPK archive twice
```
