### ISSUE TITLE
engine.GetGames() broken on servers

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#74]
Regardless of what is mounted, CS:S and TF2 are always shown as mounted while every other game is always shown as not mounted. Note that HL2 does show as mounted (but it always should anyway since it's included in GMod) and that this does not affect the actual mounting of games (eg. mounting Episode 2 works perfectly but engine.GetGames() and IsMounted shows it as unmounted -- even if I use the SteamPipe beta).

AFAIK, from what I've heard, this only affects servers but I've not tested the client myself.

**Comment by Kefta** [comment]
Why not check the mount.cfg? They use standardised names for the key (cstrike, tf2, ep2)

**Comment by robotboy655** [comment]
So you are thinking set everything to false on srcds and check mount.cfg and ignore cfg/mountdepots.txt?

**Comment by Kefta** [comment]
I didn't even know mountdepots worked/was used on srcds.

**Comment by robotboy655** [comment]
So, mountdepots.txt is now auto generated and can be edited, but also keys in mount.cfg will automatically be marked as mounted. So this mount.cfg:
```
"mountcfg"
{
	"cstrike"	"C:\steamcmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike"
}
```

Will make ```IsMounted( "cstrike" )``` return true, etc. This will not work with custom keys, so replacing that with "fapoijapwo" will not make IsMounted() return true for it.

**Comment by Kefta** [comment]
So are the allowed keys hardcoded or do they use the folder name?

**Comment by robotboy655** [comment]
They use the folder name from the list of mountable games. Basically whatever you use in IsMounted normally.
