### ISSUE TITLE
Half Life 2: Episode 1 & 2 - Unknown scripted sequences

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#793]
Throughout the levels, they fail to play scripted scenes on garry's mod.

Take ep1_citadel_00 as an example for episode 1- https://www.youtube.com/watch?v=xwRyNBewGM8

These errors appear in the console (most are spammed so I've taken some lines)
alyx_01: unknown scripted sequence "intro_vort_rescue_preI"
vort_summon&0568: unknown scripted sequence "vortloop"
vort_summon&0570: unknown scripted sequence "vort_chantloop"
alt_vort_summon&0733: unknown scripted sequence "vort_defense_cycle"
alyx: unknown scripted sequence "E1_Dogintro"
blackout: unknown scripted sequence "e1_dogintro"
blackout: unknown scripted sequence "e1_dogintro_postidle"
Dog: unknown scripted sequence "E1_DogIntro"
blackout: unknown scripted sequence "e1_dogintro_postidle"

Take ep2_outland_01 as an example for episode 2 - https://www.youtube.com/watch?v=LoiI5TKzmIQ

These errors appear in the console
alyx: unknown scripted sequence "alyx_gravgun_pickup"
alyx: unknown scripted sequence "alyx_gravgun_pickup_post"
alyx: unknown scripted sequence "alyx_gravgun_use"
alyx: unknown scripted sequence "alyx_gravgun_use_post"

**Comment by kem008** [comment]
When it will be released?

**Comment by Kefta** [comment]
I can do this tomorrow

**Comment by Kefta** [comment]
*as long as the bone structure between all three models is the same. Are there any other models that need to be combined?

**Comment by kem008** [comment]
Dog maybe but need to go through whole Half Life 2 story in gmod ot check them

**Comment by robotboy655** [comment]
Any model that exists in at last two of the three half life 2 games need merging.

**Comment by Kefta** [comment]
I'll just do Kleiner, Eli, Alyx, and Dog for now. Wasn't there a problem with the advisor, too?

**Comment by robotboy655** [comment]
Yeah, in EP2 there was. I am pretty sure Barney in HL2:EP1 is also affected.

**Comment by kem008** [comment]
Advisor mdl cant find in HL2:EP2 ep2_outland_07

**Comment by kem008** [comment]
in EP2 when alyx appears to help us :D
In ep2_outland_01
When Alyx starts his amazing pick up gravitygun Script :D :D
Someone is started to recreate this it can be found in Workshop 
https://steamcommunity.com/sharedfiles/filedetails/?id=129361322

**Comment by Kefta** [comment]
This is fixed with @willox 's new mounting order. I did manage to finally get the models to have all animations (after doing a lot of hack work to make similarly-named sequences), however, I guess it's not really needed anymore.

**Comment by kem008** [comment]
Oh so the new mounting system added again and you wont remove it? :dancer:

**Comment by robotboy655** [comment]
There's no such thing as "new mounting system". What was changed is in what order the content is mounted. ( To reflect the changes made to newer Source engine games ).

No, the thing that fixes this bug is not in the game yet, it was taken out due to some instability, but it will most likely return soon enough.

**Comment by kem008** [comment]
Ye I read about the cache problem.
I hope it will come back because it was awesome too see the animations are working. :-)

**Comment by spoopyghostramses** [comment]
Was this ever resolved? Where do I find @willox 's new mounting order?

Apologies for being a noob, just trying to find the solution for the animations.

**Comment by robotboy655** [comment]
It was temporarily disabled as it introduced new, bigger problems.

**Comment by spoopyghostramses** [comment]
Ah well I'll keep my eye out for when this fixes, thanks for the quick response!

**Comment by DjReplica** [comment]
Bump

Hope I can play episode 1 in gmod as i'm supposed to :D

**Comment by kem008** [comment]
Good job??? what are you talking about??? I get crash in ep2_outland_11a for no reason something says about line 11. But only on Linux. I dont know how you can play easily in episode 2. Maximum singleplayer.

**Comment by EgrOnWire** [comment]
@robotboy655 "one year later and you want the ~~jooj~~working episodic even more than the first time"

**Comment by besenyei** [comment]
Could $includemodel also solve this?

**Comment by robotboy655** [comment]
No.

**Comment by robotboy655** [comment]
Fixed for Alyx and many other models, progress can be seen here: https://github.com/Facepunch/garrysmod-issues/issues/5945
