### ISSUE TITLE
Crazy physics Crash Server

### ISSUE THREAD

**Issue by ForeverButthurt** [Facepunch/garrysmod-issues#803]
Example:
Crazy physics on [151][prop_physics] [Ang:-1.#IND00,1.#QNAN0,180.000000] [Pos:-1.#IND00,-1.#IND00,1.#QNAN0] - removing
player/leet.mdl (2) at -1.$ -1.$ -1.$ in contact with player/leet.mdl (2) at 64.7 38.5 47.9, crash. dist = -1, minq = 99999999999999998000000000000000000000000000000000 00000000000000000000000000000000000000000000000000 0.000000
L 12/21/2013 - 20:47:01: Engine error: player/leet.mdl (2) at -1.$ -1.$ -1.$ in contact with player/leet.mdl (2) at 64.7 38.5 47.9, crash. dist = -1, minq = 99999999999999998000000000000000000000000000000000 00000000000000000000000000000000000000000000000000 0.000000

http://facepunch.com/showthread.php?t=1334822
http://facepunch.com/showthread.php?t=1336779
http://facepunch.com/showthread.php?t=1291717
https://facepunch.com/showthread.php?t=1282764

it happens for a long time and it's not cool

**Comment by TheKigen** [comment]
Hi,

I have found that crazy physics is directly related to COLLISION_GROUP_DEBRIS_TRIGGER.  Which TTT sets the ragdoll to.  Sometimes physics can be imparted that are normally impossible for an entity but become possible when its collision group is set to COLLISION_GROUP_DEBRIS_TRIGGER.  I figured this out while working on the ZS gamemode to get a rid of inefficient hooks.  During this process a bug cropped up in which a single prop could get infinite velocity after being held by a player (normally through spamming the USE key).  This prop would start bouncing around as if it was light as a feather and as soon as it touches another prop it "infects" the prop in comes into contact with.
