### ISSUE TITLE
Certain .vtf files over 10MB 'cannot be unserialized'

### ISSUE THREAD

**Issue by rumoredlegends** [Facepunch/garrysmod-issues#85]
I've noticed that several .vtf textures that are over 10MB do not load properly and encounter the console message: "Error unserializing VTF file... is the file empty?", this seems to be similar to the bug in SFM where it cannot handle most VTFs over 10mb mentioned in this thread: https://facepunch.com/showthread.php?t=1275917

**Comment by mcNuggets1** [comment]
Does this still happen?

**Comment by robotboy655** [comment]
Post the files in question otherwise there's nothing to be done.

**Comment by LillyWho** [comment]
Old issue, but this still seems to happen. I've a VTF that happens to be 60MB and it won't load.
https://drive.google.com/file/d/1kMwcfpeeNi-Jy2OAkelTSMqFzaFhS7wY/view?usp=sharing

**Comment by thegrb93** [comment]
That's insane. Compress your texture

**Comment by LillyWho** [comment]
@thegrb93 Oh. That worked. And the texture is now 16MB so it's definitely not a 10MB file size limit.

**Comment by Kefta** [comment]
Should be reopened

**Comment by robotboy655** [comment]
Yeah it's an issue with the mipmaps, the engine thinks it has them while the texture doesn't, and the engine tries to read the nonexistent data and fails.

**Comment by robotboy655** [comment]
Should be fixed.
