### ISSUE TITLE
Error when loading maps. Total freakout.

### ISSUE THREAD

**Issue by mattycfp** [Facepunch/garrysmod-issues#863]
Hai.

Matt here, and I have a problem with the startup of a map on Garry's Mod. Apparently, recently my game had been crashing on map load. I found my crash log, and here is the last stuff in my "console" before crash:

694(312.712335):  TEST [maps/gm_sarlacc_b1.png][maps/gm_freespace_13.bsp]
693(312.712327):  TEST [maps/gm_revmoon2.png][maps/gm_freespace_13.bsp]
692(312.712319):  TEST [maps/gm_rail_xm_b2.png][maps/gm_freespace_13.bsp]
691(312.712311):  TEST [maps/gm_ragdoll_slaughter_4.png][maps/gm_freespace_13.bsp]
690(312.712303):  TEST [maps/gm_pripyat_fix.bsp][maps/gm_freespace_13.bsp]
689(312.712294):  TEST [maps/gm_parasite.png][maps/gm_freespace_13.bsp]
688(312.712286):  TEST [maps/gm_overwatch_v1_proc.bsp][maps/gm_freespace_13.bsp]
687(312.712278):  TEST [maps/gm_mountain_v1.png][maps/gm_freespace_13.bsp]
686(312.712270):  TEST [maps/gm_mountain_defense_v1_2.png][maps/gm_freespace_13.bsp]
685(312.712261):  TEST [maps/gm_mountain_defence_v1_1.png][maps/gm_freespace_13.bsp]
684(312.712253):  TEST [maps/gm_mountain_defence_hl2_v1_1.png][maps/gm_freespace_13.bsp]
683(312.712244):  TEST [maps/gm_mobenix_v3_final.png][maps/gm_freespace_13.bsp]
682(312.712236):  TEST [maps/gm_mobenix_v3_final.bsp][maps/gm_freespace_13.bsp]
681(312.712227):  TEST [maps/gm_middle_of_nowhere_night.png][maps/gm_freespa{garbled garbled garbled garbled garbled garbled garbled garbled garbled garbled garbled garbled, and so forth.)

So, I have a lot of maps. It's probably a problem. Problem.

Anyway, so as you can see, it crashes in the middle of it, quite literally. But, the list somehow progresses about 6 maps every time I start a new map after crash. It's weird. It's trying, but not hard enough.

Any solutions would be greatly appreciated.

Thanks, and best regards,
-Matt

**Comment by mcd1992** [comment]
Right click on gmod and goto properties. Then click the 'Local Files' tab and click ' Browse Local Files...' 

In this folder you should see some other folders: bin/ garrysmod/ platform/ sourceengine/. You can delete everything in here even the files. But if you have anything you want to keep a copy of you'll need to rename the garrysmod/ folder to something else.

Now go back to the 'Browse Local Files' tab and click 'Delete Local Content'. Now re-install gmod.
