### ISSUE TITLE
Awesomium Framework is not rendering alternative Alpha

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#865]
Awesomium Framework is not rendering alpha which is not 255 or 0 , it turn it to 255.

Example here : https://github.com/ExtReMLapin/GryMod/blob/master/lua/grymod/client/cl_Scaleform_GFx.lua

Try to run the function : ZoomScaleform()

The gradiant is not working, it turn it to apha 255 insead of 254...253...252...

**Comment by ExtReMLapin** [comment]
I give up

**Comment by thegrb93** [comment]
Almost everything tagged awesomium will be closed anyway once the new branch is completed
