### ISSUE TITLE
Crash when loading maps from gamemode/content folder

### ISSUE THREAD

**Issue by JetBoom** [Facepunch/garrysmod-issues#868]
Pretty simple. Put your map in your content folder of the gamemode. Load the map. Then changelevel to the same map. Game will crash with a message "Closing pack file with -1 open files"

This may also need to have the map in your garrysmod/maps folder at the same time. Seems to be different for each map but this is a guaranteed way to do it.

**Comment by robotboy655** [comment]
#717
