### ISSUE TITLE
Can't Select Anything Other Than Single Player Without Response Shutting Down

### ISSUE THREAD

**Issue by justanediblefriend** [Facepunch/garrysmod-issues#876]
If I try to start a server and I select "2 Players" or "4 Players" or ANYTHING other than Single Player, I can't click anything anymore. Everything seems to still be going. The background is still zooming in, so the game is still working, aside from its inability to accept input.

I'm on Ubuntu 12.04 Precise, Cinnamon 2.0.14. I'm not in a Beta of Garry's Mod, just ordinary 14.01.22. The only gamemode I've tested this effect on is Sandbox. My OpenGL version is 4.3.12682. I can join multiplayer games, I simply can't create one from the menu.

Also, my keyboard doesn't do anything either, it's worth mentioning. Unless I ALT+TAB or ALT+F4 or or any other hotkey related to my computer as opposed to the game, an instance of the latter being the tilda key.

**Comment by Pernath** [comment]
For the people who are still interested in a temporary solution to the multiplayer freeze in GMod. 
Scroll down in **control.NewGame.js** code file (usually located in **/home/user/.steam/steam/steamapps/common/GarrysMod/garrysmod/html/js/menu/**) near the line 130 (something), inside the curly braces of *$scope.StartGame = function() { ... }*  and replace the second parameter of the RunConsoleCommand( ) function call: 
*lua.Run( 'RunConsoleCommand( "maxplayers", "'+yourVariable+'" )' )*, where yourVariable holds the number of players. It would look something like this **var yourVariable = 4;**, or any other integer (positive) number you might need for your server. Remember to place the variable line inside the curly braces of the main function I mentioned and, of course, not after the edited line. Finally repeat the change inside this function call inside the main function: *setTimeout( function() { ... }, 200 );*, where you will find the same line to edit as before with your preferences. Save the changes, and restart GMod. By the time you start a SinglePlayer game it should now allow 3 more players if you chose number four as the value of your variable in the JavaScript file. No need to use the boxes that freezes the game.
Hope it works for you, it did for me.
