### ISSUE TITLE
Fonts are not working on the Workshop

### ISSUE THREAD

**Issue by ExtReMLapin** [Facepunch/garrysmod-issues#883]
We can upload fonts but they're broke when they're downloaded

Example here : http://steamcommunity.com/sharedfiles/filedetails/?id=209535414

**Comment by fruitwasp** [comment]
Bump?

```
Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/resource/fonts/libelsuit.ttf'
```

Both the server and client run on Windows.

**Comment by jackson-c** [comment]
Fixed?

**Comment by Kefta** [comment]
Font mounting is still pretty wonky, overall
