### ISSUE TITLE
In some hooks like OnEntityCreated and EntityRemoved the error "Player is NULL(!?)" when using the entity even if it's valid

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-issues#885]
I don't think this hook should be called with useless invalid entities anyway. The check should be done in the engine IMO.

**Comment by robotboy655** [comment]
This is probably fixed with changes to how entity tables work as well as changes to OnEntityCreated and EntityRemoved. If you can make it happen still, do tell preferably with steps to reproduce.
