### ISSUE TITLE
Half-Life 2 Episode 1: Antlion holes cannot be sealed

### ISSUE THREAD

**Issue by BoXiousNet** [Facepunch/garrysmod-issues#907]
On the level ep1_c17_00a
The player is presented by 3 antlion holes which they must seal by knocking the vehicles onto them.

The issue is, somehow the cars are slowly pushed out of the way by an unseen force, thus the antlions continue to spawn.

**Comment by robotboy655** [comment]
You can fix this by entering hl2_episodic 1 into your console.
