### ISSUE TITLE
Add callback to steamworks.RequestPlayerInfo()

### ISSUE THREAD

**Issue by Chessnut** [Facepunch/garrysmod-issues#924]
The second argument should be a callback when the information has been requested.

**Comment by DevulTj** [comment]
Can anything happen regarding this? It would be great to have a callback as right now using a timer is quite unreliable.

**Comment by robotboy655** [comment]
This function in the Steam API (ISteamFriends->RequestUserInformation) doesn't appear to even have a callback, so this is impossible to do at the moment.

**Comment by robotboy655** [comment]
No I am wrong, it's just not documented in the header files

**Comment by DevulTj** [comment]
Much appreciated on the addition! :)
