### ISSUE TITLE
PhysObj:IsPenetrating() Buggy?

### ISSUE THREAD

**Issue by 8BallBomBom** [Facepunch/garrysmod-issues#927]
I have been trying to make a device which ghosts props when their collision models are penetrated by other props, the issue i'm having is the penetration function doesn't seem to always update.

For example, if i have a row of props which have been ghosted and then grab the physicsobject with the physgun drop hook and check if props are still penetrating then it will sometimes return true even if i have moved the props out of each other.

I can provide a video and code if you need to know what i mean.

**Comment by Kefta** [comment]
You could wake the physics object every tick. Definitely not ideal but probably the best solution you're going to get as sleeping is handled in vphysics.
