### ISSUE TITLE
SoundDuration does not return the actual sound's duration

### ISSUE THREAD

**Issue by Dispenserim** [Facepunch/garrysmod-issues#936]
Regardless of sound format.

Most of the time it returns a value that you need to multiply by 4.5 in order to get it's approximate duration, sometimes it returns 60 and very rarely returns 0.

**Comment by hanm13** [comment]
It does give the right value in the client side but not in the server side.

**Comment by Kefta** [comment]
This may be on Linux, works on Windows locally

**Comment by OhDaeto** [comment]
[6adf529c-604f-4c0d-a5563490-cb727dd4.txt](https://github.com/Facepunch/garrysmod-issues/files/3802033/6adf529c-604f-4c0d-a5563490-cb727dd4.txt)

Can my log file be related to this error?

![Снимок экрана от 2019-11-03 22-53-04](https://user-images.githubusercontent.com/14937307/68091109-b827bf80-fe8c-11e9-9e15-93df6a9fb701.png)

**Comment by robotboy655** [comment]
If you are talking about a crash on the x64-86 branch, it would be a separate issue unrelated to this.

**Comment by yobson1** [comment]
https://github.com/yobson1/glua-soundduration
Made this to replace the included function, right now only supports MP3s and isn't extensively tested so it might not work on every MP3 file out there, but anyone can feel free to give it a try if they need it.

**Comment by robotboy655** [comment]
It should be fixed for the most part for .wav and .mp3 files on both srcds and client, and on linux and windows.
