### ISSUE TITLE
ViewPunch is not predicted

### ISSUE THREAD

**Issue by Dispenserim** [Facepunch/garrysmod-issues#938]
It seems that the value to punch the screen with is networked in multiplayer? From what I understand it's that way to make nospread hacks and shit harder to make, but in reality any good hack can walk around that.

As the ping rises, the view punch gets uglier and quite frankly, I think that this is completely unnecessary.
Adding prediction for ViewPunch would fix the issue.

**Comment by robotboy655** [comment]
#2887
