### ISSUE TITLE
Serverside mounting broken after 14.04.03

### ISSUE THREAD

**Issue by leiftiger** [Facepunch/garrysmod-issues#952]
(This issue is also prevalent in the hotfix 14.04.04)

It would appear as if serverside mounting no longer functions properly as it did before this update, certain animation files from EP1/EP2 are not mounted for e.g. combines and citizens. All audio files from EP1/EP2 also appear to be missing with the exception of a few sounds.

Workshop addons overriding HL2 models also do not appear to behave as they did before the update, they no longer have load priority over the HL2 models for example.

**Comment by kem008** [comment]
I think in Dedicated server mounting is still a big problem like npc_barney animation and npc_kleiner and others terrible.
