### ISSUE TITLE
Console Bug

### ISSUE THREAD

**Issue by Lundinator27** [Facepunch/garrysmod-issues#955]
Every time I press console my game crashs

**Comment by BroIamBro** [comment]
When I open console, my gmod crashes, this only happens in Multiplayer

PLZ HELP ME !!!

**Comment by uRandomAlex** [comment]
how have you f_ckin unassigned someone without "contributor" access????????????????????

**Comment by Bo98** [comment]
GitHub bug on older issues which Kilburn was assigned. When someone interacts with an issue (i.e. edit or comment), it seems to unassign Kilburn.

#69
#697
#1158
#1827

**Comment by Bo98** [comment]
Try comment on #938 or something.
