### ISSUE TITLE
Mounting/unmounting anything while ingame severely corrupts all mounted content until restart

### ISSUE THREAD

**Issue by andrewmh2013** [Facepunch/garrysmod-issues#96]
1) Load a map.
2) While ingame, change which games are mounted by checking/unchecking boxes.
3) Load a new map.

GMod will now be moderately to severely corrupted depending on which games you left mounted. I've detailed the results because I have seen individual reports of these various issues, and they all seem to have the same root cause.

CS:GO / Portal 2:
-The screen will be blocked by a missing motion blur texture.
-Sprites on the gravity gun will appear completely wrong.
![motion blur](https://f.cloud.github.com/assets/4635283/634172/7bfd8b6e-d212-11e2-8137-4f995b78a810.jpg)
![grav2](https://f.cloud.github.com/assets/4635283/634227/45682ed6-d214-11e2-95a5-71f98529f1fd.jpg)

Counter-Strike: Source:
-Playermodels revert to very low resolution and have bizarre specular masks
-Weapon models revert to very low resolution and lose their bone data to attach to players' hands

![spotty textures](https://f.cloud.github.com/assets/4635283/634220/ee1d0c8c-d213-11e2-9c42-3556bf85f775.jpg)
![crotch1](https://f.cloud.github.com/assets/4635283/634225/31d428b6-d214-11e2-99b5-4143867bc58d.jpg)

Day of Defeat: Source:
-Playermodel, world weapon, and viewmodel arm textures will revert to very low resolution.
-Viewmodel weapon textures have wrong specular mask
![dod m1903](https://f.cloud.github.com/assets/4635283/634189/f158e746-d212-11e2-96a9-1d885037606f.jpg)

CSS and CS:GO both mounted:
-CS:GO sounds appear to always override CSS sounds
-Any model that has a matching filename in both CSS and CS:GO will load but will appear invisible, with a console error about an incorrect checksum. This affects most viewmodels and worldmodels from each game.

```
MDLCache: weapons\v_rif_m4a1.mdl needs to be recompiled
Error Index File for 'weapons\v_rif_m4a1.mdl' checksum -210423205 should be -1995542441
MDLCache: weapons\w_rif_m4a1.mdl needs to be recompiled
Error Index File for 'weapons\w_rif_m4a1.mdl' checksum -1606317444 should be 722401713
```

The issues all persist even when loading another map. The only workaround is to return to the main menu and reconfigure which games are mounted, which resets most of the issues but appears to disrupt the mounting order (CS:GO soundscripts still override CSS ones for instance). Restarting the game resets all the errors.

**Comment by Availer2121** [comment]
> I'm the guy who made the "Low Quality Texture Bug" issue robotboy referenced- I moved my garrysmod folder from common to /steamapps/[username] and ran it from there, seems to have fixed the problem. Only the HL2 and TF2 content is currently mounted, though.

I might be a little late but I am having the same problem that you had and cant fix it
