### ISSUE TITLE
"_restart" is now a blocked command

### ISSUE THREAD

**Issue by leiftiger** [Facepunch/garrysmod-issues#963]
The console command "_restart" used to restart the game (e.g. to restart dedicated servers) is for some reason newly blocked in this new update when using game.ConsoleCommand:

``` lua
game.ConsoleCommand("_restart\n")...
         -- Output: game.ConsoleCommand blocked! (_restart)
```

Are we expected to use another method of closing a dedicated server from the Lua state? If so, please mention it.

**Comment by UAVXP** [comment]
Just crash the server with Lua shit, that's what developers are talking about
