### ISSUE TITLE
FOV changes in vehicle - messes up zoom_sensitivity_ratio 

### ISSUE THREAD

**Issue by Amplar** [Facepunch/garrysmod-issues#967]
Regardless of what fov_desired is set to, fov in vehicles is locked at 90 by r_jeepfov (only changed by sv_cheats 1)

If you set zoom_sensitivity_ratio to anything below 1, when you get into a seat it will lower your mouse sensitivity as if you were in suit zoom. 

This doesn't allow players to make use of suit zoom's mouse sensitivity adjustment while in a vehicle/seat.

 FOV should stay constant and modified by fov_desired, regardless of being in vehicle or not.

**Comment by robotboy655** [comment]
Defaulted r_jeepFOV to 0 (uses player's desired FOV), to match other vehicles.
Fixed jeepFOV not updating properly when re-entering the vehicle
Fixed FOV desync between server/client for jeeps

**Comment by Amplar** [comment]
holy crap, I totally forgot about this. A workaround was making sure you get into a seat with a phsygun and not a swep, it would fix this. For eons i've had a script that lowers mouse sensitivity when using suitzoom.
nice work!
