### ISSUE TITLE
pcall can't catch errors caused inside RunString or RunStringEx

### ISSUE THREAD

**Issue by Divran** [Facepunch/garrysmod-issues#979]
We were using custom error messages to halt the execution of some Lua code that was `RunString`'d. These error messages were never meant to be true errors. They were just there to halt execution.
However, it suddenly stopped working.
I narrowed down the problem to the fact that any errors in a `RunString` can't be caught by `pcall`. The errors completely bypass `pcall` and the stack traces are printed directly to the console. `pcall` even returns true, as if the code executed without a problem.

I solved it by using `CompileString` instead, but I thought I should still report the issue.

See https://github.com/wiremod/wire/issues/456

Here's how to reproduce it:
`lua_run print(pcall(RunString,"error('hi')"))`

Results:
```
> print(pcall(RunString,"error('hi')"))...

[ERROR] RunString:1: hi
  1. error - [C]:-1
   2. unknown - RunString:1
    3. unknown - [C]:-1
     4. pcall - [C]:-1
      5. unknown - lua_run:1

true
```

The same problem also occurs for "real" errors, such as runtime errors or compile errors. Examples:
`lua_run print(pcall(RunString,"if (true then"))`
```
> print(pcall(RunString,"if (true then"))...

[ERROR] RunString:1: ')' expected near 'then'
  1. unknown - RunString:0

true
```
`lua_run print(pcall(RunString,"a = a+b"))`
```
> print(pcall(RunString,"a = a+b"))...

[ERROR] RunString:1: attempt to perform arithmetic on global 'a' (a nil value)
  1. unknown - RunString:1
   2. unknown - [C]:-1
    3. pcall - [C]:-1
     4. unknown - lua_run:1

true
```

**Comment by willox** [comment]
https://wiki.garrysmod.com/page/Global/RunString

**Comment by Divran** [comment]
don't know if that handle error parameter existed back when I reported this
issue, but yeah this can definitely be closed now.
