### ISSUE TITLE
Drawing a textured rect to a rendertarget fails

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#992]
I'm trying to first draw to a rendertarget, and then draw the contents of that rendertarget to another rendertarget (https://gist.github.com/10576674), but just trying to draw a simple texture to a rendertarget fails as well.

**Comment by xaviergmail** [comment]
In case anyone else stumbles upon this from the googles after trying to draw a texture that has some non-255 alpha pixels, generate your RT using this:
` GetRenderTargetEx("RT_NAME",  RT_WIDTH, RT_HEIGHT, RT_SIZE_OFFSCREEN, MATERIAL_RT_DEPTH_NONE, 0, 0, IMAGE_FORMAT_RGBA8888)`
